### ISSUE TITLE
Can't install twisted behind corporate proxy (without internet)

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10028]
|[<img alt="Gilwyad's avatar" src="https://avatars.githubusercontent.com/u/1919041?s=50" width="50" height="50">](https://github.com/Gilwyad)| @Gilwyad reported|
|-|-|
|Trac ID|trac#10028|
|Type|defect|
|Created|2020-10-20 13:12:16Z|

I am trying to install twisted (something that depends on twisted 20.3.0) on a machine which has no internet access, using internal Pypi mirror repository. The issue is that during installation of twisted, it manually tries to connect to pypi.org to download its dependencies, instead of relying on pip that I already set up to use the internal mirror.

The problem is that it spawns a new pip instance to fetch the dependencies, so if I try to install as:

pip3 install --index-url https://corporate-pypi-mirror/simple --extra-index-url https://$corporate-pypi-mirror/simple -r Twisted

then the spawned pip will not use these parameters! Same if I pre-download the packages for later installation somehow, then:

pip3 install --no-index --find-links dist/dependencies Twisted

instead of using the files in the directory, the spawned pip tries to connect to pypi.org!

```
Collecting twisted[tls]>=18.7

  Downloading https://corporate-pypi-mirror/packages/packages/4a/b4/4973c7ccb5be2ec0abc779b7d5f9d5f24b17b0349e23240cfc9dc3bd83cc/Twisted-20.3.0.tar.bz2 (3.1 MB)

    ERROR: Command errored out with exit status 1:

     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-download-xn53es71/twisted/setup.py'"'"'; __file__='"'"'/tmp/pip-download-xn53es71/twisted/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-rpd_hit4

         cwd: /tmp/pip-download-xn53es71/twisted/

    Complete output (37 lines):

    WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe8fd43c8b0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/incremental/

    WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe8fd43c7f0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/incremental/

    WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe8fd43c910>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/incremental/

    WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe8fd43c3a0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/incremental/

    WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe8fd429f40>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/incremental/

    ERROR: Could not find a version that satisfies the requirement incremental>=16.10.1 (from versions: none)

    ERROR: No matching distribution found for incremental>=16.10.1

    Traceback (most recent call last):

      File "/usr/local/lib/python3.8/site-packages/setuptools/installer.py", line 126, in fetch_build_egg

        subprocess.check_call(cmd)

      File "/usr/local/lib/python3.8/subprocess.py", line 364, in check_call

        raise CalledProcessError(retcode, cmd)

    subprocess.CalledProcessError: Command '['/usr/local/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpc6yueevz', '--quiet', 'incremental>=16.10.1']' returned non-zero exit status 1.

    

    The above exception was the direct cause of the following exception:

    

    Traceback (most recent call last):

      File "<string>", line 1, in <module>

      File "/tmp/pip-download-xn53es71/twisted/setup.py", line 20, in <module>

        setuptools.setup(**_setup["getSetupArgs"]())

      File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 152, in setup

        _install_setup_requires(attrs)

      File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires

        dist.fetch_build_eggs(dist.setup_requires)

      File "/usr/local/lib/python3.8/site-packages/setuptools/dist.py", line 673, in fetch_build_eggs

        resolved_dists = pkg_resources.working_set.resolve(

      File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 764, in resolve

        dist = best[req.key] = env.best_match(

      File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1049, in best_match

        return self.obtain(req, installer)

      File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1061, in obtain

        return installer(requirement)

      File "/usr/local/lib/python3.8/site-packages/setuptools/dist.py", line 732, in fetch_build_egg

        return fetch_build_egg(self, req)

      File "/usr/local/lib/python3.8/site-packages/setuptools/installer.py", line 128, in fetch_build_egg

        raise DistutilsError(str(e)) from e

    distutils.errors.DistutilsError: Command '['/usr/local/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpc6yueevz', '--quiet', 'incremental>=16.10.1']' returned non-zero exit status 1.

    ----------------------------------------

ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

<details><summary>Searchable metadata</summary>

```
trac-id__10028 10028
type__defect defect
reporter__Gilwyad Gilwyad
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__duplicate duplicate
component__core core
keywords__install_installation_internet install installation internet
time__1603199536108561 1603199536108561
changetime__1603248092609106 1603248092609106
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="altendky's avatar" src="https://avatars.githubusercontent.com/u/543719?s=50" width="50" height="50">](https://github.com/altendky)<a name="note_1"></a>|@altendky commented|
|-|-|

I didn't see anything about us calling pip in a quick search I just did.  I did notice there was a new version of pip released last Saturday.  v20.2.4.  Any chance of a connection there?  Does the same happen with twisted v20.3.0rc1 or v19.10.0.  Is this a system pip or in an env?  What os?  Just to help get to the bottom of this, is there any evidence that twisted is in fact launching pip?

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_2"></a>|@twm set status to `closed`|
|-|-|

This is caused by Twisted's `setup_requires` dependency on Incremental. A `setup_requires` dependency causes setuptools (not Pip, which is why it's disregarding your index) to easy_install the package if it's not available.

You can work around this adding a [distutils config file](https://docs.python.org/3.8/install/index.html#distutils-configuration-files) that directs easy_install to use your proxy. Something like this in `~/.pydistutils.cfg`:

```
[easy_install]
index_url = https://corporate-pypi-mirror/simple/
```

There's work ongoing to make the main Twisted distribution a pure-Python wheel in the next release. This will solve this problem in the common case because wheels don't have `setup_requires` dependencies. The final resolution for the source distribution is [[#9457](https://github.com/twisted/twisted/issues/9457)](https://github.com/twisted/twisted/issues/9457).

I'm going to close this as a duplicate of #9457.
