### ISSUE TITLE
Fix narrativedocs dependencies

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10064]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)| @adiroiban reported|
|-|-|
|Trac ID|trac#10064|
|Type|defect|
|Created|2020-12-07 14:49:20Z|

Have tox env working again for the docs

`tox -e narrativedocs`

fails with

```

 ERROR: Exception:
Traceback (most recent call last):
  File "/home/runner/work/twisted/twisted/.tox/narrativedocs/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 224, in _main
    status = self.run(options, args)
  File "/home/runner/work/twisted/twisted/.tox/narrativedocs/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "/home/runner/work/twisted/twisted/.tox/narrativedocs/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 320, in run
    requirement_set = resolver.resolve(
  File "/home/runner/work/twisted/twisted/.tox/narrativedocs/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 121, in resolve
    self._result = resolver.resolve(
  File "/home/runner/work/twisted/twisted/.tox/narrativedocs/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 445, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/runner/work/twisted/twisted/.tox/narrativedocs/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 344, in resolve
    success = self._backtrack()
  File "/home/runner/work/twisted/twisted/.tox/narrativedocs/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 287, in _backtrack
    criterion = self.state.criteria[name].excluded_of([candidate])
AttributeError: 'NoneType' object has no attribute 'excluded_of'


ERROR:   narrativedocs: InvocationError for command /home/runner/work/twisted/twisted/.tox/narrativedocs/bin/python -m pip install --exists-action w '/home/runner/work/twisted/twisted/.tox/.tmp/package/1/Twisted-20.3.0.dev0-py3-none-any.whl[dev]' (exited with code 2)
}}

see https://github.com/twisted/twisted/pull/1491/checks?check_run_id=1511293197#step:6:93```{

 ERROR: Exception:
Traceback (most recent call last):
  File "/home/runner/work/twisted/twisted/.tox/narrativedocs/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 224, in _main
    status = self.run(options, args)
  File "/home/runner/work/twisted/twisted/.tox/narrativedocs/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "/home/runner/work/twisted/twisted/.tox/narrativedocs/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 320, in run
    requirement_set = resolver.resolve(
  File "/home/runner/work/twisted/twisted/.tox/narrativedocs/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 121, in resolve
    self._result = resolver.resolve(
  File "/home/runner/work/twisted/twisted/.tox/narrativedocs/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 445, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/runner/work/twisted/twisted/.tox/narrativedocs/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 344, in resolve
    success = self._backtrack()
  File "/home/runner/work/twisted/twisted/.tox/narrativedocs/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 287, in _backtrack
    criterion = self.state.criteria[name].excluded_of([candidate])
AttributeError: 'NoneType' object has no attribute 'excluded_of'


ERROR:   narrativedocs: InvocationError for command /home/runner/work/twisted/twisted/.tox/narrativedocs/bin/python -m pip install --exists-action w '/home/runner/work/twisted/twisted/.tox/.tmp/package/1/Twisted-20.3.0.dev0-py3-none-any.whl[dev]' (exited with code 2)
}}

see https://github.com/twisted/twisted/pull/1491/checks?check_run_id=1511293197#step:6:933

<details><summary>Searchable metadata</summary>

```
trac-id__10064 10064
type__defect defect
reporter__adiroiban adiroiban
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__review review
time__1607352560632549 1607352560632549
changetime__1607530195176839 1607530195176839
version__None None
owner__Adi_Roiban__adiroiban_____ Adi Roiban <adiroiban@...>

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_1"></a>|@adiroiban commented|
|-|-|

This might be just a cache issue... I am investigating

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_2"></a>|@adiroiban commented|
|-|-|

PR at https://github.com/twisted/twisted/pull/1492

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_3"></a>|@adiroiban commented|
|-|-|

Another PR with fewer changes 
https://github.com/twisted/twisted/pull/1495

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_4"></a>|@adiroiban set owner to @adiroiban<br>@adiroiban set status to `closed`|
|-|-|

In changeset 4391e9423dc10fadb58e1a5d0736f26d0b5676c9
```
#!CommitTicketReference repository="" revision="4391e9423dc10fadb58e1a5d0736f26d0b5676c9"
Merge pull request #1495 from twisted/10064-docs-build-fix-quick

Author: adiroiban
Reviewer: mthuurne 
Fixes: ticket:10064

Fix docs build and relase tests after latest pip 20.3.1 and pin pydoctor to 20.7.0 for now.
```
