### ISSUE TITLE
Twisted trunk breaks tests in buildbot's regression suite

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10069]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)| @rodrigc reported|
|-|-|
|Trac ID|trac#10069|
|Type|release blocker: regression|
|Created|2020-12-27 20:00:36Z|

While working with Pierre Tardy to test Twisted trunk against
buildbot's test suite, we found that Twisted trunk broke
some tests in buildbot's test suite:

https://github.com/buildbot/buildbot/pull/5591

This must be fixed before a new Twisted release is pushed out.

```
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/buildbot/buildbot-job/build/sandbox/lib/python3.8/site-packages/twisted/internet/defer.py", line 1445, in _inlineCallbacks
    result = current_context.run(g.send, result)
  File "/buildbot/buildbot-job/build/master/buildbot/test/unit/scripts/test_start.py", line 117, in test_start_timeout_number_string
    res = yield self.runStart(start_timeout='10')
  File "/buildbot/buildbot-job/build/master/buildbot/test/unit/scripts/test_start.py", line 87, in runStart
    return getProcessOutputAndValue(sys.executable, args=args, env=env)
  File "/buildbot/buildbot-job/build/sandbox/lib/python3.8/site-packages/twisted/internet/utils.py", line 174, in getProcessOutputAndValue
    return _callProtocolWithDeferred(
  File "/buildbot/buildbot-job/build/sandbox/lib/python3.8/site-packages/twisted/internet/utils.py", line 28, in _callProtocolWithDeferred
    reactor.spawnProcess(p, executable, (executable,) + tuple(args), env, path)
  File "/buildbot/buildbot-job/build/sandbox/lib/python3.8/site-packages/twisted/internet/posixbase.py", line 386, in spawnProcess
    args, env = self._checkProcessArgs(args, env)
  File "/buildbot/buildbot-job/build/sandbox/lib/python3.8/site-packages/twisted/internet/base.py", line 1088, in _checkProcessArgs
    _arg = argChecker(arg)
  File "/buildbot/buildbot-job/build/sandbox/lib/python3.8/site-packages/twisted/internet/base.py", line 1074, in argChecker
    arg = arg.encode(defaultEncoding)
builtins.TypeError: encode() argument 'encoding' must be str, not None
buildbot.test.unit.scripts.test_start.TestStart.test_start_timeout_number_string
-------------------------------------------------------------------------------
```

<details><summary>Searchable metadata</summary>

```
trac-id__10069 10069
type__release_blocker__regression release blocker: regression
reporter__rodrigc rodrigc
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__None None
time__1609099236801177 1609099236801177
changetime__1612945895380367 1612945895380367
version__None None
owner__rodrigc rodrigc

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_1"></a>|@adiroiban set status to `closed`|
|-|-|

Duplicate of [#10070](https://github.com/twisted/twisted/issues/10070)  ... as that ticket has more information.

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)|@rodrigc set status to `reopened`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)|@rodrigc set owner to @rodrigc<br>@rodrigc set status to `new`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_4"></a>|@rodrigc commented|
|-|-|

https://github.com/twisted/twisted/pull/1502

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)|@twm set owner to @twm<br>@twm set status to `assigned`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_6"></a>|@twm commented|
|-|-|

Sorry, I forgot to remove the review keyword after reviewing earlier this week.

https://github.com/twisted/twisted/pull/1502#pullrequestreview-561556663
https://github.com/twisted/twisted/pull/1502#issuecomment-755139267

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_7"></a>|@twm set owner to @rodrigc<br>@twm set status to `new`|
|-|-|

Sorry, I missed reassigning this.

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_8"></a>|@adiroiban commented|
|-|-|

Since this is a release blocker.

One option is to revert the change in which this regression was introduces (I think [#9858](https://github.com/twisted/twisted/issues/9858) https://github.com/twisted/twisted/pull/1502)

This will un-block the release.

A fix could be merge later at any time.

As a general rule, if a fix for a release blocker can't be done in a reasonable timeframe (1 month), it should be reverted and do the release.


Cheers

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_9"></a>|@rodrigc commented|
|-|-|

I want to merge https://github.com/twisted/twisted/pull/1502
and do the release, since that has been tested against Buildbot's regression test framework.

I cannot merge this because I need review approval from someone with write permission to the Twisted GitHub repository to approve the review.

I am in the process of incorporating feedback from Tom Most, in order to modify PR 1502 so that he can approve it.

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_11"></a>|@twm commented|
|-|-|

Approved: https://github.com/twisted/twisted/pull/1502#pullrequestreview-587318856

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_12"></a>|@rodrigc set status to `closed`|
|-|-|

In changeset 7cf6c8bc320ac5fd96b4784f6feb932ea819856d
```
#!CommitTicketReference repository="" revision="7cf6c8bc320ac5fd96b4784f6feb932ea819856d"
Merge pull request #1502 from twisted/10069-rodrigc-encoding

Author: rodrigc
Reviewer: twm
Fixes: ticket:10069

Fix defaultEncoding in base.py, uncovered by Buildbot regression tests
```
