### ISSUE TITLE
Twisted trunk breaks tests in buildbot's regression suite

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10070]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)| @rodrigc reported|
|-|-|
|Trac ID|trac#10070|
|Type|release blocker: regression|
|Created|2020-12-27 20:00:41Z|
|Branch|https://github.com/twisted/twisted/tree/defaultencoding-10070|

While working with Pierre Tardy to test Twisted trunk against
buildbot's test suite, we found that Twisted trunk broke
some tests in buildbot's test suite:

https://github.com/buildbot/buildbot/pull/5591

This should be fixed before a new Twisted release is pushed out.

```
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/buildbot/buildbot-job/build/sandbox/lib/python3.8/site-packages/twisted/internet/defer.py", line 1445, in _inlineCallbacks
    result = current_context.run(g.send, result)
  File "/buildbot/buildbot-job/build/master/buildbot/test/unit/scripts/test_start.py", line 117, in test_start_timeout_number_string
    res = yield self.runStart(start_timeout='10')
  File "/buildbot/buildbot-job/build/master/buildbot/test/unit/scripts/test_start.py", line 87, in runStart
    return getProcessOutputAndValue(sys.executable, args=args, env=env)
  File "/buildbot/buildbot-job/build/sandbox/lib/python3.8/site-packages/twisted/internet/utils.py", line 174, in getProcessOutputAndValue
    return _callProtocolWithDeferred(
  File "/buildbot/buildbot-job/build/sandbox/lib/python3.8/site-packages/twisted/internet/utils.py", line 28, in _callProtocolWithDeferred
    reactor.spawnProcess(p, executable, (executable,) + tuple(args), env, path)
  File "/buildbot/buildbot-job/build/sandbox/lib/python3.8/site-packages/twisted/internet/posixbase.py", line 386, in spawnProcess
    args, env = self._checkProcessArgs(args, env)
  File "/buildbot/buildbot-job/build/sandbox/lib/python3.8/site-packages/twisted/internet/base.py", line 1088, in _checkProcessArgs
    _arg = argChecker(arg)
  File "/buildbot/buildbot-job/build/sandbox/lib/python3.8/site-packages/twisted/internet/base.py", line 1074, in argChecker
    arg = arg.encode(defaultEncoding)
builtins.TypeError: encode() argument 'encoding' must be str, not None
buildbot.test.unit.scripts.test_start.TestStart.test_start_timeout_number_string
-------------------------------------------------------------------------------
```

<details><summary>Searchable metadata</summary>

```
trac-id__10070 10070
type__release_blocker__regression release blocker: regression
reporter__rodrigc rodrigc
priority__normal normal
milestone__None None
branch__defaultencoding_10070 defaultencoding-10070
branch_author__ 
status__closed closed
resolution__duplicate duplicate
component__core core
keywords__None None
time__1609099241131996 1609099241131996
changetime__1609696798473345 1609696798473345
version__None None
owner__twm twm

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_2"></a>|@twm commented|
|-|-|

Appears to come from here: https://github.com/twisted/twisted/blob/c8064075a207af1fc9ce19d8f885a986bc5ab00c/src/twisted/internet/base.py#L1055-L1074

It looks like `defaultEncoding` used to default to `sys.getfilesystemencoding()`: https://github.com/twisted/twisted/commit/85069b5ccdc92745809a8287ab24d6127c1a75da

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_3"></a>|@twm commented|
|-|-|

I'm toying with https://github.com/twisted/twisted/pull/1499 but not sure it will work out.

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)|@twm set owner to @twm<br>@twm set status to `assigned`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_5"></a>|@twm commented|
|-|-|

PR: https://github.com/twisted/twisted/pull/1499

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_6"></a>|@rodrigc set status to `closed`|
|-|-|

I'm working on a fix under ticket:10069 .  This has to be done carefully not to break the different versions of Python on Mac and Windows.  I have several VM's to test this
