### ISSUE TITLE
'NoneType' object has no attribute 'encode' in requestReceived() when multipart body doesn't include content-disposition

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10084]
|[<img alt="vtapia's avatar" src="https://avatars.githubusercontent.com/u/5339299?s=50" width="50" height="50">](https://github.com/vtapia)| @vtapia reported|
|-|-|
|Trac ID|trac#10084|
|Type|defect|
|Created|2021-02-08 14:45:29Z|

Before commit https://github.com/python/cpython/commit/cc3fa204d357be5fafc10eb8c2a80fe0bca998f1 cgi.parse_multipart ignored parts without "content-disposition" but after 3.7+, to make it consistent with FieldStorage, the return of the function can contain keys set to Nonetype, which fail to encode.

For instance, with a Body like this:
```
--8825899812428059282  

--8825899812428059282--
```

And headers:

```
Content-Type': 'multipart/form-data; boundary="8825899812428059282"
```

cgiArgs is set to `{None: ['']}` and this error shows up:

```
2021-02-08T14:52:16+0100 [_GenericHTTPChannelProtocol,16,127.0.0.1] Unhandled Error
        Traceback (most recent call last):
          File "/usr/lib/python3/dist-packages/twisted/python/log.py", line 103, in callWithLogger
            return callWithContext({"system": lp}, func, *args, **kw)
          File "/usr/lib/python3/dist-packages/twisted/python/log.py", line 86, in callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext
            return func(*args,**kw)
        --- <exception caught here> ---
          File "/usr/lib/python3/dist-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
            why = selectable.doRead()
          File "/usr/lib/python3/dist-packages/twisted/internet/tcp.py", line 243, in doRead
            return self._dataReceived(data)
          File "/usr/lib/python3/dist-packages/twisted/internet/tcp.py", line 249, in _dataReceived
            rval = self.protocol.dataReceived(data)
          File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 2952, in dataReceived
            return self._channel.dataReceived(data)
          File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 2245, in dataReceived
            return basic.LineReceiver.dataReceived(self, data)
          File "/usr/lib/python3/dist-packages/twisted/protocols/basic.py", line 579, in dataReceived
            why = self.rawDataReceived(data)
          File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 2252, in rawDataReceived
            self._transferDecoder.dataReceived(data)
          File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 1699, in dataReceived
            finishCallback(data[contentLength:])
          File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 2115, in _finishRequestBody
            self.allContentReceived()
          File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 2224, in allContentReceived
            req.requestReceived(command, path, version)
          File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 898, in requestReceived
            self.args.update({
          File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 899, in <dictcomp>
            x.encode('iso-8859-1'): \
        builtins.AttributeError: 'NoneType' object has no attribute 'encode'

```

<details><summary>Searchable metadata</summary>

```
trac-id__10084 10084
type__defect defect
reporter__vtapia vtapia
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__web web
keywords__None None
time__1612795529355519 1612795529355519
changetime__1613271831724196 1613271831724196
version__None None
owner__Tom_Most__twm_____ Tom Most <twm@...>

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="vtapia's avatar" src="https://avatars.githubusercontent.com/u/5339299?s=50" width="50" height="50">](https://github.com/vtapia)<a name="note_2"></a>|@vtapia commented|
|-|-|

https://github.com/twisted/twisted/pull/1512

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)|@twm set owner to @twm<br>@twm set status to `assigned`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_4"></a>|@twm removed owner<br>@twm set status to `new`|
|-|-|

Approved: https://github.com/twisted/twisted/pull/1512 Thank you!

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_5"></a>|@twm set owner to @twm<br>@twm set status to `closed`|
|-|-|

In changeset bf02deda3117e82ed844f56b989e692a84daca95
```
#!CommitTicketReference repository="" revision="bf02deda3117e82ed844f56b989e692a84daca95"
Merge pull request #1512 from vtapia/10084-vtapia-fix-nonetype-encode

Author: vtapia
Reviewer: twm
Fixes: ticket:10084

Fix NoneType encode error when multipart body part does not include headers

Before commit ​python/cpython@cc3fa20 in cpython, cgi.parse_multipart ignored parts without a name defined in "content-disposition" (or parts without headers for that matter) but after 3.7+, to make it consistent with FieldStorage, the return of the function can now contain NoneType keys, which fail to encode.
```
