### ISSUE TITLE
Bump python_requires to 3.5.3 for typing.Type

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10098]
|[<img alt="graingert's avatar" src="https://avatars.githubusercontent.com/u/413772?s=50" width="50" height="50">](https://github.com/graingert)| @graingert reported|
|-|-|
|Trac ID|trac#10098|
|Type|enhancement|
|Created|2021-02-25 21:53:41Z|

fixed in python 3.5.3 https://github.com/python/typing/pull/267

```
(env3)rav at faith:~$ python3
Python 3.5.2 (default, Oct  7 2020, 17:19:02)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
 >>> from twisted.python import log
Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
   File 
"/home/synapse/env3/lib/python3.5/site-packages/twisted/python/log.py", 
line 20, in <module>
     from twisted.python import reflect
   File 
"/home/synapse/env3/lib/python3.5/site-packages/twisted/python/reflect.py", 
line 377, in <module>
     def _safeFormat(formatter: Union[types.FunctionType, Type[str]], o: 
object) -> str:
   File "/usr/lib/python3.5/typing.py", line 552, in __getitem__
     dict(self.__dict__), parameters, _root=True)
   File "/usr/lib/python3.5/typing.py", line 512, in __new__
     for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
   File "/usr/lib/python3.5/typing.py", line 512, in <genexpr>
     for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
   File "/usr/lib/python3.5/typing.py", line 1077, in __subclasscheck__
     if super().__subclasscheck__(cls):
   File "/usr/lib/python3.5/abc.py", line 225, in __subclasscheck__
     for scls in cls.__subclasses__():
TypeError: descriptor '__subclasses__' of 'type' object needs an argument

```

https://github.com/twisted/twisted/pull/1524

<details><summary>Searchable metadata</summary>

```
trac-id__10098 10098
type__enhancement enhancement
reporter__graingert graingert
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__review review
time__1614290021714800 1614290021714800
changetime__1614536347034081 1614536347034081
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="graingert's avatar" src="https://avatars.githubusercontent.com/u/413772?s=50" width="50" height="50">](https://github.com/graingert)<a name="note_1"></a>|@graingert commented|
|-|-|

https://github.com/twisted/twisted/pull/1524

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_2"></a>|@rodrigc set status to `closed`|
|-|-|

This has been merged
