### ISSUE TITLE
TypeError: SelectorEventLoop required, instead got: <uvloop.Loop running=False closed=False debug=False>

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10106]
|[<img alt="tonal's avatar" src="https://avatars.githubusercontent.com/u/316216?s=50" width="50" height="50">](https://github.com/tonal)| @tonal reported|
|-|-|
|Trac ID|trac#10106|
|Type|defect|
|Created|2021-03-01 04:26:06Z|

Twisted versionn 21.02
uvloop version 0.15.2

Traceback:
```
Traceback (most recent call last):
  File "/home/user/projects/test/venv/lib/python3.9/site-packages/scrapy/utils/reactor.py", line 66, in install_reactor
    asyncioreactor.install(eventloop=event_loop)
  File "/home/user/projects/test/venv/lib/python3.9/site-packages/twisted/internet/asyncioreactor.py", line 307, in install
    reactor = AsyncioSelectorReactor(eventloop)
  File "/home/user/projects/test/venv/lib/python3.9/site-packages/twisted/internet/asyncioreactor.py", line 60, in __init__
    raise TypeError(
TypeError: SelectorEventLoop required, instead got: <uvloop.Loop running=False closed=False debug=False>
```

Python 3.8
Os: Ubuntu 20.04 with all upgrades

<details><summary>Searchable metadata</summary>

```
trac-id__10106 10106
type__defect defect
reporter__tonal tonal
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__regression_review regression review
time__1614572766304584 1614572766304584
changetime__1622316521526448 1622316521526448
version__None None
owner__Wim_Lewis__wiml_____ Wim Lewis <wiml@...>

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="tonal's avatar" src="https://avatars.githubusercontent.com/u/316216?s=50" width="50" height="50">](https://github.com/tonal)<a name="note_1"></a>|@tonal commented|
|-|-|

See also: [https://github.com/scrapy/scrapy/issues/5017#issuecomment-787935098 Scrapy issues [#5017](https://github.com/twisted/twisted/issues/5017) comment 787935098]

**Comment by twisted-trac** [comment]
|[<img alt="kwist-sgr's avatar" src="https://avatars.githubusercontent.com/u/4199178?s=50" width="50" height="50">](https://github.com/kwist-sgr)<a name="note_2"></a>|@kwist-sgr commented|
|-|-|

See also: [ticket:10039 asyncioreactor interop with uvloop?]

**Comment by twisted-trac** [comment]
|[<img alt="wiml's avatar" src="https://avatars.githubusercontent.com/u/156891?s=50" width="50" height="50">](https://github.com/wiml)<a name="note_3"></a>|@wiml commented|
|-|-|

This is presumably fallout from ticket:9766 in which ```asyncioreactor``` broke on Windows.

Probably Twisted shouldn't be making a inheritance-based test, but should (imho) test for the existence of ```add_reader()``` etc., or conformance to a protocol, or if that doesn't work the test could be changed to reject ```ProactorEventLoop``` instead of only accepting ```SelectorEventLoop```.

To be honest I'm not sure if it's important to have that type assertion in ```AsyncioSelectorReactor.__init__()``` anywway.

**Comment by twisted-trac** [comment]
|[<img alt="AndreyMZ's avatar" src="https://avatars.githubusercontent.com/u/9609370?s=50" width="50" height="50">](https://github.com/AndreyMZ)<a name="note_4"></a>|@AndreyMZ commented|
|-|-|

PR for review: https://github.com/twisted/twisted/pull/1601

**Comment by twisted-trac** [comment]
|[<img alt="wiml's avatar" src="https://avatars.githubusercontent.com/u/156891?s=50" width="50" height="50">](https://github.com/wiml)<a name="note_5"></a>|@wiml set owner to @wiml<br>@wiml set status to `closed`|
|-|-|

In changeset fd036b78650c97bddc7201cff741b82259cd84d5
```
#!CommitTicketReference repository="" revision="fd036b78650c97bddc7201cff741b82259cd84d5"
Merge pull request #1601 from AndreyMZ/10106-andreymz-fix-typeerror-uvloop

Author: AndreyMZ
Reviewer: wiml
Fixes: ticket:10106

Fix exception "TypeError: SelectorEventLoop required, instead got: <uvloop.Loop ...>"
```
