### ISSUE TITLE
update tests for incremental >= 21.3.0

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10112]
|[<img alt="graingert's avatar" src="https://avatars.githubusercontent.com/u/413772?s=50" width="50" height="50">](https://github.com/graingert)| @graingert reported|
|-|-|
|Trac ID|trac#10112|
|Type|release blocker: regression|
|Created|2021-03-02 11:45:01Z|

all CI builds are failing due to:

```
2021-03-02T11:16:34.7538932Z ===============================================================================
2021-03-02T11:16:34.7539250Z [FAIL]
2021-03-02T11:16:34.7539602Z Traceback (most recent call last):
2021-03-02T11:16:34.7541123Z   File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.8/site-packages/twisted/python/test/test_versions.py", line 161, in test_baseWithPrerelease
2021-03-02T11:16:34.7542376Z     self.assertEqual(Version("foo", 1, 0, 0, prerelease=8).base(), "1.0.0rc8")
2021-03-02T11:16:34.7543622Z   File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.8/site-packages/twisted/trial/_synctest.py", line 424, in assertEqual
2021-03-02T11:16:34.7544633Z     super().assertEqual(first, second, msg)
2021-03-02T11:16:34.7545313Z   File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/unittest/case.py", line 912, in assertEqual
2021-03-02T11:16:34.7545932Z     assertion_func(first, second, msg=msg)
2021-03-02T11:16:34.7546668Z   File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/unittest/case.py", line 1292, in assertMultiLineEqual
2021-03-02T11:16:34.7547441Z     self.fail(self._formatMessage(msg, standardMsg))
2021-03-02T11:16:34.7548381Z twisted.trial.unittest.FailTest: '1.0.0.rc8' != '1.0.0rc8'
2021-03-02T11:16:34.7549029Z - 1.0.0.rc8
2021-03-02T11:16:34.7549381Z ?      -
2021-03-02T11:16:34.7549646Z + 1.0.0rc8
2021-03-02T11:16:34.7549831Z 
2021-03-02T11:16:34.7549989Z 
2021-03-02T11:16:34.7550660Z twisted.python.test.test_versions.VersionsTests.test_baseWithPrerelease
2021-03-02T11:16:34.7551531Z ===============================================================================
2021-03-02T11:16:34.7551835Z [FAIL]
2021-03-02T11:16:34.7552167Z Traceback (most recent call last):
2021-03-02T11:16:34.7553553Z   File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.8/site-packages/twisted/python/test/test_versions.py", line 146, in test_getVersionStringWithPrerelease
2021-03-02T11:16:34.7554605Z     self.assertEqual(
2021-03-02T11:16:34.7555870Z   File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.8/site-packages/twisted/trial/_synctest.py", line 424, in assertEqual
2021-03-02T11:16:34.7556766Z     super().assertEqual(first, second, msg)
2021-03-02T11:16:34.7557633Z   File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/unittest/case.py", line 912, in assertEqual
2021-03-02T11:16:34.7558596Z     assertion_func(first, second, msg=msg)
2021-03-02T11:16:34.7559537Z   File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/unittest/case.py", line 1292, in assertMultiLineEqual
2021-03-02T11:16:34.7560331Z     self.fail(self._formatMessage(msg, standardMsg))
2021-03-02T11:16:34.7561452Z twisted.trial.unittest.FailTest: 'whatever 8.0.0.rc1' != 'whatever 8.0.0rc1'
2021-03-02T11:16:34.7562425Z - whatever 8.0.0.rc1
2021-03-02T11:16:34.7562989Z ?               -
2021-03-02T11:16:34.7563472Z + whatever 8.0.0rc1
2021-03-02T11:16:34.7563680Z 
2021-03-02T11:16:34.7563860Z 
2021-03-02T11:16:34.7564701Z twisted.python.test.test_versions.VersionsTests.test_getVersionStringWithPrerelease
2021-03-02T11:16:34.7565901Z ===============================================================================
2021-03-02T11:16:34.7566215Z [FAIL]
2021-03-02T11:16:34.7566553Z Traceback (most recent call last):
2021-03-02T11:16:34.7567812Z   File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.8/site-packages/twisted/python/test/test_versions.py", line 128, in test_strWithPrerelease
2021-03-02T11:16:34.7569056Z     self.assertEqual(
2021-03-02T11:16:34.7570138Z   File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.8/site-packages/twisted/trial/_synctest.py", line 424, in assertEqual
2021-03-02T11:16:34.7571011Z     super().assertEqual(first, second, msg)
2021-03-02T11:16:34.7572036Z   File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/unittest/case.py", line 912, in assertEqual
2021-03-02T11:16:34.7572690Z     assertion_func(first, second, msg=msg)
2021-03-02T11:16:34.7573450Z   File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/unittest/case.py", line 1292, in assertMultiLineEqual
2021-03-02T11:16:34.7574225Z     self.fail(self._formatMessage(msg, standardMsg))
2021-03-02T11:16:34.7575273Z twisted.trial.unittest.FailTest: '[dummy, version 1.0.0.rc1]' != '[dummy, version 1.0.0rc1]'
2021-03-02T11:16:34.7576253Z - [dummy, version 1.0.0.rc1]
2021-03-02T11:16:34.7576856Z ?                      -
2021-03-02T11:16:34.7577164Z + [dummy, version 1.0.0rc1]
2021-03-02T11:16:34.7577396Z 
2021-03-02T11:16:34.7577573Z 
2021-03-02T11:16:34.7578257Z twisted.python.test.test_versions.VersionsTests.test_strWithPrerelease
2021-03-02T11:16:34.7579258Z -------------------------------------------------------------------------------
```

<details><summary>Searchable metadata</summary>

```
trac-id__10112 10112
type__release_blocker__regression release blocker: regression
reporter__graingert graingert
priority__highest highest
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__review review
time__1614685501192006 1614685501192006
changetime__1614686615342602 1614686615342602
version__None None
owner__graingert graingert

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="graingert's avatar" src="https://avatars.githubusercontent.com/u/413772?s=50" width="50" height="50">](https://github.com/graingert)|@graingert set owner to @graingert<br>@graingert set status to `assigned`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="graingert's avatar" src="https://avatars.githubusercontent.com/u/413772?s=50" width="50" height="50">](https://github.com/graingert)<a name="note_3"></a>|@graingert commented|
|-|-|

https://github.com/twisted/twisted/pull/1536

**Comment by twisted-trac** [comment]
|<img alt="tagrain's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_4"></a>|tagrain set status to `closed`|
|-|-|

In changeset e9cb6258e01031fb6cc836d15ca2f7f00852fdd2
```
#!CommitTicketReference repository="" revision="e9cb6258e01031fb6cc836d15ca2f7f00852fdd2"
Merge pull request #1536 from graingert/upgrade-incremental

Fixes: ticket:10112
```
