### ISSUE TITLE
Conch: Regression: using dropbear as a client no longer works in Twisted 21.2.0

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10138]
|[<img alt="nielsavonds's avatar" src="https://avatars.githubusercontent.com/u/1017293?s=50" width="50" height="50">](https://github.com/nielsavonds)| @nielsavonds reported|
|-|-|
|Trac ID|trac#10138|
|Type|defect|
|Created|2021-03-18 12:56:09Z|

When connecting to a Twisted SSH server using dropbear, an Exception is thrown in the server.

Here is the stacktrace:

```
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/twisted/python/log.py", line 101, in callWithLogger
return callWithContext({"system": lp}, func, *args, **kw)
File "/usr/local/lib/python3.8/site-packages/twisted/python/log.py", line 85, in callWithContext
return context.call({ILogContext: newCtx}, func, *args, **kw)
File "/usr/local/lib/python3.8/site-packages/twisted/python/context.py", line 118, in callWithContext
return self.currentContext().callWithContext(ctx, func, *args, **kw)
File "/usr/local/lib/python3.8/site-packages/twisted/python/context.py", line 83, in callWithContext
return func(*args, **kw)
--- <exception caught here> ---
File "/usr/local/lib/python3.8/site-packages/twisted/internet/posixbase.py", line 687, in _doReadOrWrite
why = selectable.doRead()
File "/usr/local/lib/python3.8/site-packages/twisted/internet/tcp.py", line 246, in doRead
return self._dataReceived(data)
File "/usr/local/lib/python3.8/site-packages/twisted/internet/tcp.py", line 251, in _dataReceived
rval = self.protocol.dataReceived(data)
File "/usr/local/lib/python3.8/site-packages/twisted/conch/ssh/transport.py", line 721, in dataReceived
self.dispatchMessage(messageNum, packet[1:])
File "/usr/local/lib/python3.8/site-packages/twisted/conch/ssh/transport.py", line 738, in dispatchMessage
f(payload)
File "/usr/local/lib/python3.8/site-packages/twisted/conch/ssh/transport.py", line 1372, in ssh_KEXINIT
or keyAlgs[0] != self.supportedPublicKeys[0]
builtins.TypeError: 'dict_keys' object is not subscriptable
```

The root cause is that the supportedPublicKeys field contains a dict_keys object instead of the expected list.

<details><summary>Searchable metadata</summary>

```
trac-id__10138 10138
type__defect defect
reporter__nielsavonds nielsavonds
priority__normal normal
milestone__None None
branch__None None
branch_author__ 
status__new new
resolution__None None
component__conch conch
keywords__None None
time__1616072169796510 1616072169796510
changetime__1646514015375960 1646514015375960
version__None None
owner__nielsavonds nielsavonds

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="nielsavonds's avatar" src="https://avatars.githubusercontent.com/u/1017293?s=50" width="50" height="50">](https://github.com/nielsavonds)<a name="note_1"></a>|@nielsavonds commented|
|-|-|

Pull request: https://github.com/twisted/twisted/pull/1553

**Comment by twisted-trac** [comment]
|[<img alt="wiml's avatar" src="https://avatars.githubusercontent.com/u/156891?s=50" width="50" height="50">](https://github.com/wiml)<a name="note_2"></a>|@wiml commented|
|-|-|

Since you're using Dropbear, do you have any insight on Trac bugs [#9464](https://github.com/twisted/twisted/issues/9464) and [[#9670](https://github.com/twisted/twisted/issues/9670) ? We don't have a reproducible case for either one of those, and we could probably fix them if we did.

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_3"></a>|@adiroiban commented|
|-|-|

I think that the defect is observed only on python3.

This is not only a regression in 21.2.0 but also in 20.3.0 if you use it with Python3.

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_4"></a>|@twm set owner to @nielsavonds|
|-|-|

The patch has conflicts and needs tests, so marking this reviewed to sync up Trac and PR status https://github.com/twisted/twisted/pull/1553#pullrequestreview-901008903 Thanks!
