### ISSUE TITLE
Fix PYPY coverage run

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10171]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)| @adiroiban reported|
|-|-|
|Trac ID|trac#10171|
|Type|defect|
|Created|2021-04-06 10:12:55Z|

Most probably there is a race condition with sqlite and pypy, as used by coverage run.

https://github.com/twisted/twisted/pull/1577/checks?check_run_id=2274177993#step:9:751

See coverage issue https://github.com/nedbat/coveragepy/issues/1010
PyPY issue - https://foss.heptapod.net/pypy/pypy/-/issues/3351

Output looks like this

```
PASSED (skips=35, successes=373)
Traceback (most recent call last):
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/site-packages/coverage/cmdline.py", line 746, in do_run
    runner.run()
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/site-packages/coverage/execfile.py", line 247, in run
    exec(code, main_mod.__dict__)
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/site-packages/twisted/trial/__main__.py", line 8, in <module>
    sys.exit(load_entry_point("Twisted", "console_scripts", "trial")())
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/site-packages/twisted/scripts/trial.py", line 662, in run
    sys.exit(not test_result.wasSuccessful())
SystemExit: False

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/bin/coverage", line 8, in <module>
    sys.exit(main())
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/site-packages/coverage/cmdline.py", line 871, in main
    status = CoverageScript().command_line(argv)
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/site-packages/coverage/cmdline.py", line 588, in command_line
    return self.do_run(options, args)
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/site-packages/coverage/cmdline.py", line 753, in do_run
    self.coverage.save()
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/site-packages/coverage/control.py", line 659, in save
    data = self.get_data()
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/site-packages/coverage/control.py", line 727, in get_data
    if self._collector and self._collector.flush_data():
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/site-packages/coverage/collector.py", line 440, in flush_data
    self.covdata.add_arcs(self.mapped_file_dict(self.data))
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/site-packages/coverage/sqldata.py", line 481, in add_arcs
    data,
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/site-packages/coverage/sqldata.py", line 1106, in executemany
    return self.con.executemany(sql, data)
  File "/opt/hostedtoolcache/PyPy/3.7.9/x64/lib_pypy/_sqlite3.py", line 424, in executemany
    return cur.executemany(*args)
  File "/opt/hostedtoolcache/PyPy/3.7.9/x64/lib_pypy/_sqlite3.py", line 821, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/hostedtoolcache/PyPy/3.7.9/x64/lib_pypy/_sqlite3.py", line 986, in executemany
    return self.__execute(True, sql, many_params)
  File "/opt/hostedtoolcache/PyPy/3.7.9/x64/lib_pypy/_sqlite3.py", line 937, in __execute
    self.__statement._set_params(params)
  File "/opt/hostedtoolcache/PyPy/3.7.9/x64/lib_pypy/_sqlite3.py", line 1228, in _set_params
    "probably unsupported type." % i)
_sqlite3.InterfaceError: Error binding parameter 0 - probably unsupported type.
ERROR: InvocationError for command /home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/bin/coverage run -p --rcfile=/home/runner/work/twisted/twisted/.coveragerc -m twisted.trial --temp-directory=/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/tmp/_trial_temp --reactor=default --reporter=verbose -j 4 twisted.test.test_compat twisted.test.test_defer twisted.internet.test.test_socket twisted.trial.test.test_tests (exited with code 1)
```

<details><summary>Searchable metadata</summary>

```
trac-id__10171 10171
type__defect defect
reporter__adiroiban adiroiban
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__None None
time__1617703975713468 1617703975713468
changetime__1626934762598969 1626934762598969
version__None None
owner__Adi_Roiban__adiroiban_____ Adi Roiban <adiroiban@...>

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_1"></a>|@adiroiban commented|
|-|-|

PR at https://github.com/twisted/twisted/pull/1581

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_3"></a>|@adiroiban set owner to @adiroiban<br>@adiroiban set status to `closed`|
|-|-|

In changeset 8e2344832c11f57c8647ccfd36e3a1c762505892
```
#!CommitTicketReference repository="" revision="8e2344832c11f57c8647ccfd36e3a1c762505892"
Merge pull request #1581 from twisted/10171-pypy-coverage-run

Merge pull request #123 from twisted/4356-branch-name-with-trac-id

Author: adiroiban
Reviewer: altendky 
Fixes: ticket:10171

Fix coverage run on PYPY due to SQLite error by using an unreleased python coverage version.
```

**Comment by twisted-trac** [comment]
|[<img alt="graingert's avatar" src="https://avatars.githubusercontent.com/u/413772?s=50" width="50" height="50">](https://github.com/graingert)|@graingert set status to `reopened`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_5"></a>|@glyph set status to `closed`|
|-|-|

The PR here seems to be merged.
