### ISSUE TITLE
Fix cancellation of deferred flattening

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10186]
|[<img alt="mthuurne's avatar" src="https://avatars.githubusercontent.com/u/246676?s=50" width="50" height="50">](https://github.com/mthuurne)| @mthuurne reported|
|-|-|
|Trac ID|trac#10186|
|Type|defect|
|Created|2021-04-27 19:49:04Z|

There is a problem in the way `twisted.web._flatten._fork()` handles cancellation:

```
>>> from twisted.internet.defer import Deferred
>>> from twisted.web._flatten import _fork
>>> _fork(Deferred()).cancel()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mth/src/twisted/src/twisted/internet/defer.py", line 728, in cancel
    canceller(self)
TypeError: cancel() takes 1 positional argument but 2 were given
```

This problem was introduced in [#10125](https://github.com/twisted/twisted/issues/10125).

<details><summary>Searchable metadata</summary>

```
trac-id__10186 10186
type__defect defect
reporter__mthuurne mthuurne
priority__high high
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__web web
keywords__None None
time__1619552944397473 1619552944397473
changetime__1619694190799029 1619694190799029
version__None None
owner__mthuurne mthuurne

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="mthuurne's avatar" src="https://avatars.githubusercontent.com/u/246676?s=50" width="50" height="50">](https://github.com/mthuurne)<a name="note_1"></a>|@mthuurne commented|
|-|-|

Ready for review: https://github.com/twisted/twisted/pull/1590

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_2"></a>|@glyph set owner to @glyph|
|-|-|

Approved.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_3"></a>|@glyph set status to `closed`|
|-|-|

In changeset 3c868ac11786eef7ea269caa3056f00854128957
```
#!CommitTicketReference repository="" revision="3c868ac11786eef7ea269caa3056f00854128957"
Merge pull request #1590 from twisted/10186-fix-flatten-cancel

Author: mthuurne
Reviewer: glyph
Fixes: ticket:10186

Fix cancellation of deferred flattening.
Add a test case to demonstrate the bug.
```

**Comment by twisted-trac** [comment]
|[<img alt="mthuurne's avatar" src="https://avatars.githubusercontent.com/u/246676?s=50" width="50" height="50">](https://github.com/mthuurne)<a name="note_4"></a>|@mthuurne set status to `reopened`|
|-|-|

Sadly, the PR was incorrect and the test wasn't thorough enough to spot that.

**Comment by twisted-trac** [comment]
|[<img alt="mthuurne's avatar" src="https://avatars.githubusercontent.com/u/246676?s=50" width="50" height="50">](https://github.com/mthuurne)<a name="note_5"></a>|@mthuurne commented|
|-|-|

New PR: https://github.com/twisted/twisted/pull/1593

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_6"></a>|@glyph set owner to @mthuurne<br>@glyph set status to `new`|
|-|-|

Re-reviewed.

**Comment by twisted-trac** [comment]
|[<img alt="mthuurne's avatar" src="https://avatars.githubusercontent.com/u/246676?s=50" width="50" height="50">](https://github.com/mthuurne)<a name="note_7"></a>|@mthuurne set status to `closed`|
|-|-|

In changeset 63649469c1fe46d8a713e8034239ac3cc0498ea7
```
#!CommitTicketReference repository="" revision="63649469c1fe46d8a713e8034239ac3cc0498ea7"
Merge pull request #1593 from twisted/10186-fix-flatten-cancel

10186: Re-fix cancellation of deferred flattening

Author: mthuurne
Reviewer: glyph
Fixes: ticket:10186

Properly fix the cancellation of deferred flattening and improve the test case.
```
