### ISSUE TITLE
21.2.0: module 'subunit.iso8601' has no attribute 'Utc'

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10196]
|<img alt="kloczek's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| kloczek reported|
|-|-|
|Trac ID|trac#10196|
|Type|enhancement|
|Created|2021-05-14 20:29:36Z|

subunit 1.4.0
In many modules where twisted is used is emmited errorlike below:

```
$ python3 -c "import twisted.trial.unittest"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/twisted/trial/unittest.py", line 20, in <module>
    from twisted.trial._asyncrunner import TestSuite, TestDecorator, decorate
  File "/usr/lib/python3.8/site-packages/twisted/trial/_asyncrunner.py", line 15, in <module>
    from twisted.trial import itrial, reporter
  File "/usr/lib/python3.8/site-packages/twisted/trial/reporter.py", line 29, in <module>
    from subunit import TestProtocolClient
  File "/usr/lib/python3.8/site-packages/subunit/__init__.py", line 142, in <module>
    from subunit.v2 import ByteStreamToStreamResult, StreamResultToBytes
  File "/usr/lib/python3.8/site-packages/subunit/v2.py", line 52, in <module>
    EPOCH = datetime.datetime.utcfromtimestamp(0).replace(tzinfo=iso8601.Utc())
AttributeError: module 'subunit.iso8601' has no attribute 'Utc'

```

BTW do you have any plans to make new twisted odiule release?

<details><summary>Searchable metadata</summary>

```
trac-id__10196 10196
type__enhancement enhancement
reporter__kloczek kloczek
priority__high high
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__duplicate duplicate
component__core core
keywords__None None
time__1621024176923862 1621024176923862
changetime__1621194333791576 1621194333791576
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_1"></a>|@twm set status to `closed`|
|-|-|

Looks like this got double-submitted: closing as a dupe of [#10195](https://github.com/twisted/twisted/issues/10195).
