### ISSUE TITLE
MaildirMessage cannot work with a file in text mode nor in binary mode

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10244]
|[<img alt="vmario's avatar" src="https://avatars.githubusercontent.com/u/62034?s=50" width="50" height="50">](https://github.com/vmario)| @vmario reported|
|-|-|
|Trac ID|trac#10244|
|Type|defect|
|Created|2021-07-30 10:16:47Z|

I've tried to use `MaildirMessage` object (Twisted v21.7.0) with file opened in text mode but I've got this:

```
2021-07-30T12:05:59+0200 [ESMTP (TLSMemoryBIOProtocol),0,10.127.1.50] Unhandled Error
        Traceback (most recent call last):
          File "/home/user/.local/lib/python3.8/site-packages/twisted/protocols/policies.py", line 109, in dataReceived
            self.wrappedProtocol.dataReceived(data)
          File "/home/user/.local/lib/python3.8/site-packages/twisted/protocols/basic.py", line 439, in dataReceived
            self.lineReceived(line)
          File "/home/user/.local/lib/python3.8/site-packages/twisted/mail/smtp.py", line 501, in lineReceived
            return getattr(self, "state_" + self.mode)(line)
          File "/home/user/.local/lib/python3.8/site-packages/twisted/mail/smtp.py", line 515, in state_COMMAND
            method(b"")
        --- <exception caught here> ---
          File "/home/user/.local/lib/python3.8/site-packages/twisted/mail/smtp.py", line 690, in do_DATA
            msg.lineReceived(rcvdhdr)
          File "/home/user/.local/lib/python3.8/site-packages/twisted/mail/maildir.py", line 143, in lineReceived
            mail.FileMessage.lineReceived(self, line)
          File "/home/user/.local/lib/python3.8/site-packages/twisted/mail/mail.py", line 434, in lineReceived
            self.fp.write(line + b"\n")
        builtins.TypeError: write() argument must be str, not bytes
```

This is clear because you cannot write bytes to the text file. Unfortunately with file in binary mode I've got this:

```
2021-07-30T12:03:10+0200 [ESMTP (TLSMemoryBIOProtocol),0,10.127.1.50] Unhandled Error
        Traceback (most recent call last):
          File "/home/user/.local/lib/python3.8/site-packages/twisted/protocols/policies.py", line 109, in dataReceived
            self.wrappedProtocol.dataReceived(data)
          File "/home/user/.local/lib/python3.8/site-packages/twisted/protocols/basic.py", line 439, in dataReceived
            self.lineReceived(line)
          File "/home/user/.local/lib/python3.8/site-packages/twisted/mail/smtp.py", line 501, in lineReceived
            return getattr(self, "state_" + self.mode)(line)
          File "/home/user/.local/lib/python3.8/site-packages/twisted/mail/smtp.py", line 515, in state_COMMAND
            method(b"")
        --- <exception caught here> ---
          File "/home/user/.local/lib/python3.8/site-packages/twisted/mail/smtp.py", line 687, in do_DATA
            msg = msgFunc()
          File "/home/user/Kodowanie/Git/RKPProxy/smtp/client.py", line 80, in <lambda>
            return lambda: LocalMessageFactory(user, self.usersDirPath).message()
          File "/home/user/Kodowanie/Git/RKPProxy/smtp/client.py", line 217, in message
            return maildir.MaildirMessage(
          File "/home/user/.local/lib/python3.8/site-packages/twisted/mail/maildir.py", line 132, in __init__
            fp.write(header)
        builtins.TypeError: a bytes-like object is required, not 'str'
```

`MaildirMessage` writes header to the file but this header is string not bytes.

<details><summary>Searchable metadata</summary>

```
trac-id__10244 10244
type__defect defect
reporter__vmario vmario
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__mail mail
keywords__None None
time__1627640207974143 1627640207974143
changetime__1656140124886537 1656140124886537
version__None None
owner__vmario vmario

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="vmario's avatar" src="https://avatars.githubusercontent.com/u/62034?s=50" width="50" height="50">](https://github.com/vmario)<a name="note_1"></a>|@vmario commented|
|-|-|

https://github.com/twisted/twisted/pull/1650

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_2"></a>|@twm set owner to @vmario|
|-|-|

Sorry for the wait! Reviewed: https://github.com/twisted/twisted/pull/1650#pullrequestreview-1019273810 I requested some minor style changes. Please feel free to ping me for re-review (@twm on GitHub).
