### ISSUE TITLE
IRC protocol not connecting in Python 3.9

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10259]
|[<img alt="darnti's avatar" src="https://avatars.githubusercontent.com/u/55652848?s=50" width="50" height="50">](https://github.com/darnti)| @darnti reported|
|-|-|
|Trac ID|trac#10259|
|Type|defect|
|Created|2021-09-06 14:41:10Z|

The following code:

```
from twisted.internet import reactor, protocol, defer
from twisted.words.protocols import irc

class Bot(irc.IRCClient):
    def _get_nickname(self):
        return self.factory.nickname
    def _get_username(self):
        return self.factory.username
    def _get_realname(self):
        return self.factory.realname
    def _get_versionname(self):
        return self.factory.versionName

    nickname = property(_get_nickname)
    username = property(_get_username)
    realname = property(_get_realname)
    versionName = property(_get_versionname)


    def signedOn(self):
        print("Signed on as %s." % self.nickname)
        print("Logged in.")
        print("Joining channels...")
        reactor.callLater(2, self.join, self.factory.channel)


class BotFactory(protocol.ClientFactory):
    global bot_nickname, bot_channel, server_ipaddress

    protocol = Bot

    def __init__(self, channel, nickname='EnterNickHere'):
        self.channel = "#bot-test"
        self.nickname = "EnterNickHere"
        self.realname = 'Bot Nick'
        self.username = 'botnick'
        self.versionName = "Twisted IRC"
        
if __name__ == "__main__":

    reactor.connectTCP("server address here", 6667, BotFactory("#bot-test"))

reactor.run()
```

Produces the following error:

```
Unhandled Error
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\twisted\internet\tcp.py", line 252, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "C:\Python39\lib\site-packages\twisted\words\protocols\irc.py", line 2616, in dataReceived
    basic.LineReceiver.dataReceived(self, data)
  File "C:\Python39\lib\site-packages\twisted\protocols\basic.py", line 548, in dataReceived
    why = self.lineReceived(line)
  File "C:\Python39\lib\site-packages\twisted\words\protocols\irc.py", line 2628, in lineReceived
    self.handleCommand(command, prefix, params)
--- <exception caught here> ---
  File "C:\Python39\lib\site-packages\twisted\words\protocols\irc.py", line 2680, in handleCommand
    method(prefix, params)
  File "C:\Python39\lib\site-packages\twisted\words\protocols\irc.py", line 1958, in irc_RPL_WELCOME
    self.nickname = self._attemptedNick
builtins.AttributeError: can't set attribute
```

Note that this code works with the lastest twisted release for Python 2.7.

Attachments:

* [bot-connect.py](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/cc9/cc93c5fa1a9fc50db2dbf79e745a85c46b79d57a/09f2c5b9f90be7debc50ab939c89c6a6604bc9f8.py) (1343 bytes) - added by darnti on 2021-09-06 14:42:20Z - 

<details><summary>Searchable metadata</summary>

```
trac-id__10259 10259
type__defect defect
reporter__darnti darnti
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__invalid invalid
component__words words
keywords__None None
time__1630939270157286 1630939270157286
changetime__1631487079516595 1631487079516595
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_1"></a>|@twm set status to `closed`|
|-|-|

It looks like you're defining a read-only property here:

```
    nickname = property(_get_nickname)
```

The exception indicates that the superclass is using an attribute of the same name.

I'd guess, but haven't checked, that this worked in Python 2.7 because `IRCClient` was an old-style class and descriptors like `property` were weird. It won't work as written in Python 3. If you run the Python 2.7 version with the `TWISTED_NEWSTYLE=1` environment variable set, which forces all Twisted classes to be new-style, I expect you'll get the same result.

Since this is a Python 3 porting issue in user code rather than a bug in Twisted itself I'm closing it as "invalid". You'll have to make some changes for it to run under current versions of Python. Feel free to reach out on the mailing list for porting advice, and thanks for using Twisted!
