### ISSUE TITLE
Confusing combined traceback when exception thrown after inlineCallbacks generator returns

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10260]
|[<img alt="taliastocks's avatar" src="https://avatars.githubusercontent.com/u/928827?s=50" width="50" height="50">](https://github.com/taliastocks)| @taliastocks reported|
|-|-|
|Trac ID|trac#10260|
|Type|enhancement|
|Created|2021-09-14 18:26:41Z|

In the current release, if an inlineCallback generator returns to a deferred callback that throws an exception, the traceback is confusing, e.g.:

```
Traceback (most recent call last):
  File "/mnt/mesos/sandbox/.pex/install/Twisted-20.3.0-cp37-cp37m-manylinux1_x86_64.whl.1128a7e2b98487eb88697f10720d146583a69992/Twisted-20.3.0-cp37-cp37m-manylinux1_x86_64.whl/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: Response(code=200, message=b'OK')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/mesos/sandbox/__main__-D229445.750890.pex/infra_compute/proxy/proxy.py", line 291, in _proxy_request
    simplified_response = yield self.proxy.process_request(simplified_request)
... # the real traceback we care about
```

This happens because the `status.deferred.callback()` is called from within the `StopIteration` exception handler. Python assumes that the `StopIteration` is the real exception we care about because that exception was being handled while the second exception was thrown. However, we don't care about the `StopIteration` exception, as it is only used to transmit a return value from the `inlineCallback` generator.

This can be avoided by first exiting the exception handler, then calling `status.deferred.callback()`. Python will no longer incorrectly tack on the `StopIteration` traceback on the top if there is an exception in the callback.

<details><summary>Searchable metadata</summary>

```
trac-id__10260 10260
type__enhancement enhancement
reporter__taliastocks taliastocks
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__None None
time__1631644001617490 1631644001617490
changetime__1656137306906475 1656137306906475
version__None None
owner__None None
cc__taliastocks
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="taliastocks's avatar" src="https://avatars.githubusercontent.com/u/928827?s=50" width="50" height="50">](https://github.com/taliastocks)<a name="note_1"></a>|@taliastocks commented|
|-|-|

Fixed in https://github.com/twisted/twisted/pull/1662

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_2"></a>|@twm set status to `closed`|
|-|-|

Merged here: https://github.com/twisted/twisted/commit/ee0728c339091b316dc23f57a642e142c1690a93

Big thanks to Talia for the patch and Adi for review!
