### ISSUE TITLE
PyPy3.9 fails twisted.trial._dist.test.test_workertrial tests: twisted.trial.unittest.FailTest: 'rb' is not 'rb'

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10302]
|[<img alt="mgorny's avatar" src="https://avatars.githubusercontent.com/u/110765?s=50" width="50" height="50">](https://github.com/mgorny)| @mgorny reported|
|-|-|
|Trac ID|trac#10302|
|Type|defect|
|Created|2022-02-01 23:20:57Z|

4 twisted.trial._dist.test.test_workertrial tests fail because of issues resembling the following:

```
===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/home/mgorny/twisted/.venv/lib/pypy3.9/site-packages/twisted/trial/_dist/test/test_workertrial.py", line 126, in test_readInterrupted
    main(self.fdopen)
  File "/home/mgorny/twisted/.venv/lib/pypy3.9/site-packages/twisted/trial/_dist/workertrial.py", line 75, in main
    protocolIn = _fdopen(_WORKER_AMP_STDIN, "rb")
  File "/home/mgorny/twisted/.venv/lib/pypy3.9/site-packages/twisted/trial/_dist/test/test_workertrial.py", line 72, in fdopen
    self.assertIdentical("rb", mode)
  File "/home/mgorny/twisted/.venv/lib/pypy3.9/site-packages/twisted/trial/_synctest.py", line 439, in assertIs
    raise self.failureException(msg or f"{first!r} is not {second!r}")
twisted.trial.unittest.FailTest: 'rb' is not 'rb'

twisted.trial._dist.test.test_workertrial.MainTests.test_readInterrupted
-------------------------------------------------------------------------------
```

The cause seems to be that .assertIdentical() is used to perform the test rather than .assertEqual().  It seems that comparing two strings for equality happens to work on CPython (though it causes a SyntaxWarning) but does not on PyPy.

<details><summary>Searchable metadata</summary>

```
trac-id__10302 10302
type__defect defect
reporter__mgorny mgorny
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__trial trial
keywords__None None
time__1643757657468265 1643757657468265
changetime__1644040913732691 1644040913732691
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="mgorny's avatar" src="https://avatars.githubusercontent.com/u/110765?s=50" width="50" height="50">](https://github.com/mgorny)<a name="note_2"></a>|@mgorny commented|
|-|-|

https://github.com/twisted/twisted/pull/1691

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_3"></a>|@twm set status to `closed`|
|-|-|

Thank you for the patch! Merged in https://github.com/twisted/twisted/commit/b9777eb0214b6506e30234910311d549e337d5d2
