### ISSUE TITLE
DomishExpatStreamTests.test_namespaceWithWhitespace fails with expat >= 2.4.5

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10318]
|[<img alt="yan12125's avatar" src="https://avatars.githubusercontent.com/u/1937689?s=50" width="50" height="50">](https://github.com/yan12125)| @yan12125 reported|
|-|-|
|Trac ID|trac#10318|
|Type|defect|
|Created|2022-03-19 12:04:25Z|

```#!bash
twisted.words.test.test_domish
  DomishExpatStreamTests
    test_namespaceWithWhitespace ...                                    [ERROR]

===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/home/yen/tmp/twisted/src/twisted/words/test/test_domish.py", line 317, in test_namespaceWithWhitespace
    self.stream.parse(xml)
  File "/home/yen/tmp/twisted/src/twisted/words/xish/domish.py", line 802, in parse
    raise ParserError(str(e))
twisted.words.xish.domish.ParserError: syntax error: line 1, column 0

twisted.words.test.test_domish.DomishExpatStreamTests.test_namespaceWithWhitespace
-------------------------------------------------------------------------------
Ran 1 tests in 0.072s

FAILED (errors=1)
```

When the system library expat is 2.4.5 or newer, this test failed as expat "protects against insertion of namesep characters into namespace URIs" (https://github.com/libexpat/libexpat/pull/561) since that version.

Maybe skip that test for new expat?

I found this issue on Arch Linux, while I believe this can be reproduced on other systems with new enough expat.

<details><summary>Searchable metadata</summary>

```
trac-id__10318 10318
type__defect defect
reporter__yan12125 yan12125
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__None None
time__1647691465089850 1647691465089850
changetime__1649730753549748 1649730753549748
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

An xmlns of " bar baz " seems like it is illegal.  libexpat docs say that it does not validate URIs but applications should be prepared for it to do so in the future.  Maybe they have started to take some steps towards this validation (just speculating).

I wonder why it is important for domish to be able to parse such xmlns uris.

If it is not important, deleting this test entirely seems sensible.  If it is important, skipping it is probably not a useful fix.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_2"></a>|@exarkun commented|
|-|-|

(reading the expat commits, it looks like this is to address a security concern, not part of any general push to do xmlns uri validation, fwiw)

**Comment by twisted-trac** [comment]
|[<img alt="yan12125's avatar" src="https://avatars.githubusercontent.com/u/1937689?s=50" width="50" height="50">](https://github.com/yan12125)<a name="note_3"></a>|@yan12125 commented|
|-|-|

> I wonder why it is important for domish to be able to parse such xmlns uris.

Because they exist in the wild? The test in question is added for [#4503](https://github.com/twisted/twisted/issues/4503), where an NS URI contains a space.

> it looks like this is to address a security concern

Yeah, for security reasons (which I don't quite understand, to be honest), expat now rejects NS URIs containing the namespace separator character, which is specified as a space in twisted: https://github.com/twisted/twisted/blob/f28b36d02f678f4146047777f24548553425702b/src/twisted/words/xish/domish.py#L787.

From the document of expat (https://libexpat.github.io/doc/api/latest/), maybe twisted should change the separator to '\xFF'.

> If it is not important, deleting this test entirely seems sensible. If it is important, skipping it is probably not a useful fix.

The test is no longer relevant if the namespace separator is changed, but maybe still good to keep to make sure twisted can handle such unusual NS URIs.

**Comment by twisted-trac** [comment]
|[<img alt="yan12125's avatar" src="https://avatars.githubusercontent.com/u/1937689?s=50" width="50" height="50">](https://github.com/yan12125)<a name="note_4"></a>|@yan12125 commented|
|-|-|

> maybe twisted should change the separator to '\xFF'.

Just tried it and this seems impossible with pure Python. Python treats "\xff" as a unicode character and passes the corresponding UTF-8 sequence \xc3\xbf to pyexpat.

Not sure if it's a good idea to break backward compatibility, call URIs with spaces as invalid and remove the test.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_5"></a>|@glyph commented|
|-|-|

This is also possible if you just upgrade to python.org's build of 3.10.4 on macOS; I upgraded and now this test is failing for me.

> Not sure if it's a good idea to break backward compatibility, call URIs with spaces as invalid and remove the test.

I agree. Let's just kill the test, since I am not sure what code in Twisted this was even testing; we don't seem to have any configuration which specifically handles spaces here, no logic in the system under test.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_6"></a>|@glyph commented|
|-|-|

In review over at https://github.com/twisted/twisted/pull/1709

**Comment by twisted-trac** [comment]
|[<img alt="yan12125's avatar" src="https://avatars.githubusercontent.com/u/1937689?s=50" width="50" height="50">](https://github.com/yan12125)<a name="note_7"></a>|@yan12125 set status to `closed`|
|-|-|

Closing as the linked PR is merged. Thanks for the fix!
