### ISSUE TITLE
a couple twisted.trial.test.test_loader tests fail

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10319]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#10319|
|Type|enhancement|
|Created|2022-03-25 19:02:34Z|

```
[exarkun@magnon:~]$ python -V
Python 3.8.9

[exarkun@magnon:~]$ python -m venv ~/VirtualEnvs/trial-test-failure

[exarkun@magnon:~]$ . ~/VirtualEnvs/trial-test-failure/bin/activate
-bash: hash: hashing disabled
-bash: hash: hashing disabled
(trial-test-failure) 
[exarkun@magnon:~]$ pip install -e ~/Work/python/twisted/[test]
Obtaining file:///home/exarkun/Work/python/twisted
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting incremental>=21.3.0
  Using cached incremental-21.3.0-py2.py3-none-any.whl (15 kB)
Collecting typing-extensions>=3.6.5
  Using cached typing_extensions-4.1.1-py3-none-any.whl (26 kB)
Collecting attrs>=19.2.0
  Using cached attrs-21.4.0-py2.py3-none-any.whl (60 kB)
Collecting constantly>=15.1
  Using cached constantly-15.1.0-py2.py3-none-any.whl (7.9 kB)
Collecting Automat>=0.8.0
  Using cached Automat-20.2.0-py2.py3-none-any.whl (31 kB)
Collecting zope.interface>=4.4.2
  Using cached zope.interface-5.4.0-cp38-cp38-manylinux2010_x86_64.whl (259 kB)
Collecting hyperlink>=17.1.1
  Using cached hyperlink-21.0.0-py2.py3-none-any.whl (74 kB)
Collecting PyHamcrest>=1.9.0; extra == "test"
  Using cached PyHamcrest-2.0.3-py3-none-any.whl (51 kB)
Collecting cython-test-exception-raiser<2,>=1.0.2; extra == "test"
  Using cached cython_test_exception_raiser-1.0.2-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (48 kB)
Requirement already satisfied: six in /nix/store/14sil57w425v7ncx8jk9rwb1zz7ix204-python3.8-six-1.15.0/lib/python3.8/site-packages (from Automat>=0.8.0->Twisted==22.2.0.post0) (1.15.0)
Requirement already satisfied: setuptools in /nix/store/ad2jqwgpsh8wjrjcqqy5ql36swk5g54r-python3.8-setuptools-54.2.0/lib/python3.8/site-packages (from zope.interface>=4.4.2->Twisted==22.2.0.post0) (54.2.0.post0)
Collecting idna>=2.5
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Installing collected packages: incremental, typing-extensions, attrs, constantly, Automat, zope.interface, idna, hyperlink, PyHamcrest, cython-test-exception-raiser, Twisted
  Running setup.py develop for Twisted
Successfully installed Automat-20.2.0 PyHamcrest-2.0.3 Twisted attrs-21.4.0 constantly-15.1.0 cython-test-exception-raiser-1.0.2 hyperlink-21.0.0 idna-3.3 incremental-21.3.0 typing-extensions-4.1.1 zope.interface-5.4.0
WARNING: You are using pip version 20.2.3; however, version 22.0.4 is available.
You should consider upgrading via the '/home/exarkun/VirtualEnvs/trial-test-failure/bin/python -m pip install --upgrade pip' command.
(trial-test-failure) 
[exarkun@magnon:~]$ pip freeze | grep -i twisted
-e git+git@github.com:twisted/twisted@f28b36d02f678f4146047777f24548553425702b#egg=Twisted
(trial-test-failure) 
[exarkun@magnon:~]$ trial twisted.trial.test.test_loader.FileTests.test_moduleNotInPath twisted.trial.test.test_loader.FileTests.test_packageNotInPath
twisted.trial.test.test_loader
  FileTests
    test_moduleNotInPath ...                                             [FAIL]
    test_packageNotInPath ...                                            [FAIL]

===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/home/exarkun/Work/python/twisted/src/twisted/trial/test/test_loader.py", line 111, in test_moduleNotInPath
    self.assertEqual(sample1.__spec__, sample2.__spec__)
  File "/home/exarkun/Work/python/twisted/src/twisted/trial/_synctest.py", line 422, in assertEqual
    super().assertEqual(first, second, msg)
  File "/nix/store/66fbv9mmx1j4hrn9y06kcp73c3yb196r-python3-3.8.9/lib/python3.8/unittest/case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/nix/store/66fbv9mmx1j4hrn9y06kcp73c3yb196r-python3-3.8.9/lib/python3.8/unittest/case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
twisted.trial.unittest.FailTest: Modul[104 chars]cf9726fa60>, origin='/home/exarkun/_trial_temp[100 chars].py') != Modul[104 chars]cf972994c0>, origin='twisted.trial.test.test_l[74 chars].py')

twisted.trial.test.test_loader.FileTests.test_moduleNotInPath
===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/home/exarkun/Work/python/twisted/src/twisted/trial/test/test_loader.py", line 138, in test_packageNotInPath
    self.assertEqual(package1.__spec__, goodpackage.__spec__)
  File "/home/exarkun/Work/python/twisted/src/twisted/trial/_synctest.py", line 422, in assertEqual
    super().assertEqual(first, second, msg)
  File "/nix/store/66fbv9mmx1j4hrn9y06kcp73c3yb196r-python3-3.8.9/lib/python3.8/unittest/case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/nix/store/66fbv9mmx1j4hrn9y06kcp73c3yb196r-python3-3.8.9/lib/python3.8/unittest/case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
twisted.trial.unittest.FailTest: Modul[94 chars]97299850>, origin='/home/exarkun/_trial_temp/t[243 chars]ge']) != Modul[94 chars]97299b20>, origin='twisted.trial.test.test_loa[191 chars]ge'])

twisted.trial.test.test_loader.FileTests.test_packageNotInPath
-------------------------------------------------------------------------------
Ran 2 tests in 0.048s

FAILED (failures=2)
(trial-test-failure) 
```

<details><summary>Searchable metadata</summary>

```
trac-id__10319 10319
type__enhancement enhancement
reporter__exarkun exarkun
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__trial trial
keywords__None None
time__1648234954369677 1648234954369677
changetime__1652307626070186 1652307626070186
version__None None
owner__exarkun exarkun

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

The test failure seems to be caused by the `origin` of two `ModuleSpec` values being different.  The difference is that one is absolute and one is relative to the current working directory.

The absolute version comes from `runner.filenameToModule`.  The relative version comes from `import`.

According to `d0c7e19948026a0f7f6849170cce0da76202aa99`, `importlib.util.spec_from_file_location` is supposed to return a spec with an absolute path on Python >= 3.10.0 and this change was also backported to Python 3.8.10 (and some version of Python 3.9) but then reverted in Python 3.8.11 because it caused failures in some project.

The observed behavior is on Python 3.8.9 - but maybe this just means it is failing because of the original, incompatible Python 3.8.x behavior instead of because the new behavior added in 3.8.10 was reverted (ie, maybe Python 3.8.10 is the odd ball here and all other Python 3.8.xs are broken wrt this test).

I wonder what versions of Python 3.8 are being used on CI.  It seems like there must at least be 3.8.11 otherwise I don't know how the regression from the revert in CPython would have been noticed.  But then I don't know what difference there is between 3.8.9 and 3.8.11 that leads to different behavior in my environment vs on CI.

I'm tempted to just make trial abspath everything in sys.path and not screw with this any more.  Or weaken the assertion so that the relative path is allowed as long as it is close enough to the absolute path (equals the absolute path after abspath(), maybe?).

But I haven't really kept up with how Python's import/module system has been changing so I dunno if this is a useful direction or not.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_2"></a>|@exarkun commented|
|-|-|

https://github.com/twisted/twisted/pull/1732

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_3"></a>|@glyph set owner to @exarkun|
|-|-|

It would be good to fix the one coverage gap but otherwise looks good

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_4"></a>|@exarkun set status to `closed`|
|-|-|

Merged in https://github.com/twisted/twisted/commit/d0a8ca7f28f296feefd0695acadf8dd729acfd65
