### ISSUE TITLE
twisted.python.failure._Code is incompatible with Python 3.11

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10336]
|[<img alt="cjwatson's avatar" src="https://avatars.githubusercontent.com/u/2429141?s=50" width="50" height="50">](https://github.com/cjwatson)| @cjwatson reported|
|-|-|
|Trac ID|trac#10336|
|Type|defect|
|Created|2022-04-23 21:13:13Z|

Twisted's tests fail on Python 3.11 with a number of test failures along the lines of the following:

```
[ERROR]
Traceback (most recent call last):
  File "/home/cjwatson/src/python/twisted/twisted/.tox/py311-alldeps-nocov/lib/python3.11/site-packages/twisted/test/test_failure.py", line 724, in test_singleFrame
    traceback.extract_tb(tb), [_tb("filename.py", 123, "method", None)]
  File "/home/cjwatson/src/python/pyenv/versions/3.11.0a7/lib/python3.11/traceback.py", line 74, in extract_tb
    return StackSummary._extract_from_extended_frame_gen(
  File "/home/cjwatson/src/python/pyenv/versions/3.11.0a7/lib/python3.11/traceback.py", line 416, in _extract_from_extended_frame_gen
    for f, (lineno, end_lineno, colno, end_colno) in frame_gen:
  File "/home/cjwatson/src/python/pyenv/versions/3.11.0a7/lib/python3.11/traceback.py", line 353, in _walk_tb_with_full_positions
    positions = _get_code_position(tb.tb_frame.f_code, tb.tb_lasti)
  File "/home/cjwatson/src/python/pyenv/versions/3.11.0a7/lib/python3.11/traceback.py", line 366, in _get_code_position
    positions_gen = code.co_positions()
builtins.AttributeError: '_Code' object has no attribute 'co_positions'

twisted.test.test_failure.FormattableTracebackTests.test_singleFrame
```

(This also causes testtools's test suite to fail on Python 3.11, which is how I noticed this.)

<details><summary>Searchable metadata</summary>

```
trac-id__10336 10336
type__defect defect
reporter__cjwatson cjwatson
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__None None
time__1650748393630217 1650748393630217
changetime__1655066945572129 1655066945572129
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="cjwatson's avatar" src="https://avatars.githubusercontent.com/u/2429141?s=50" width="50" height="50">](https://github.com/cjwatson)<a name="note_1"></a>|@cjwatson commented|
|-|-|

https://github.com/twisted/twisted/pull/1723

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_2"></a>|@twm set status to `closed`|
|-|-|

This was merged a while ago: https://github.com/twisted/twisted/commit/87e494bb6e57f28f145b109c5cf5cdb325645d13
