### ISSUE TITLE
pubkey auth failing on conch with twisted 22.4.0

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10335]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)| @glyph reported|
|-|-|
|Trac ID|trac#10335|
|Type|defect|
|Created|2022-04-22 22:50:00Z|

```
#!py
2022-04-22T22:44:17+0000 [twisted.conch.ssh.userauth.SSHUserAuthServer#critical] Error checking auth for user b'user'
	Traceback (most recent call last):
	  File "/code/env/lib/pypy3.8/site-packages/twisted/internet/defer.py", line 190, in maybeDeferred
	    result = f(*args, **kwargs)
	  File "/code/env/lib/pypy3.8/site-packages/twisted/conch/checkers.py", line 486, in requestAvatarId
	    d.addCallback(self._checkKey, credentials)
	  File "/code/env/lib/pypy3.8/site-packages/twisted/internet/defer.py", line 497, in addCallback
	    return self.addCallbacks(callback, callbackArgs=args, callbackKeywords=kwargs)
	  File "/code/env/lib/pypy3.8/site-packages/twisted/internet/defer.py", line 477, in addCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/code/env/lib/pypy3.8/site-packages/twisted/internet/defer.py", line 858, in _runCallbacks
	    current.result, *args, **kwargs
	  File "/code/env/lib/pypy3.8/site-packages/twisted/conch/ssh/userauth.py", line 208, in _ebMaybeBadAuth
	    reason.trap(error.NotEnoughAuthentication)
	  File "/code/env/lib/pypy3.8/site-packages/twisted/python/failure.py", line 476, in trap
	    self.raiseException()
	  File "/code/env/lib/pypy3.8/site-packages/twisted/python/failure.py", line 500, in raiseException
	    raise self.value.with_traceback(self.tb)
	  File "/code/env/lib/pypy3.8/site-packages/twisted/internet/defer.py", line 858, in _runCallbacks
	    current.result, *args, **kwargs
	  File "/code/env/lib/pypy3.8/site-packages/twisted/conch/checkers.py", line 531, in _checkKey
	    key == pubKey for key in self._keydb.getAuthorizedKeys(credentials.username)
	  File "/code/env/lib/pypy3.8/site-packages/twisted/conch/checkers.py", line 452, in getAuthorizedKeys
	    passwd = self._userdb.getpwnam(username)
	builtins.TypeError: expected str, got bytes object
```

This from a server which is functionally running `twist conch --data=/secrets/ssh --auth=sshkey`.

<details><summary>Searchable metadata</summary>

```
trac-id__10335 10335
type__defect defect
reporter__glyph glyph
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__duplicate duplicate
component__conch conch
keywords__None None
time__1650667800984322 1650667800984322
changetime__1650756139635990 1650756139635990
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_2"></a>|@glyph commented|
|-|-|

Looks like conch's tests have not been running in CI for a while.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_3"></a>|@glyph commented|
|-|-|

Preliminary PR to fix this is here: https://github.com/twisted/twisted/pull/1722

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_4"></a>|@glyph set status to `closed`|
|-|-|

Looks like this was already filed as ticket:10286. I'll have to reconcile the two branches here.

**Comment by glyph** [comment]
Hmm. Looks like we didn't translate `ticket:` links in the migration. Is it #10286 ?

**Comment by adiroiban** [comment]
The Trac `ticket:1234` was not converted to GitHub `#1234`

The mapping from Trac IDs to GitHub IDs for tickets can be found here https://github.com/twisted/twisted.github.io/blob/main/assets/js/redirect_trac_tickets.js

10286 has the same ID in Trac and in GitHub

**Comment by twm** [comment]
Per https://github.com/twisted/twisted/issues/10286#issuecomment-1231216969 I am reopening this and removing the duplicate tag.

**Comment by twm** [comment]
Er, wait, this is a different traceback from what @glyph posted in https://github.com/twisted/twisted/issues/10286#issuecomment-1229896032. This looks like a legit duplicate.
