### ISSUE TITLE
`trial -jN ...` reports a traceback when interrupted with Ctrl+C

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10340]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#10340|
|Type|enhancement|
|Created|2022-05-03 14:19:54Z|

From 
https://github.com/twisted/twisted/pull/1726#pullrequestreview-959084307

hitting Ctrl+C while disttrial is running:

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/adi/chevah/twisted/src/twisted/trial/__main__.py", line 9, in <module>
    sys.exit(load_entry_point("Twisted", "console_scripts", "trial")())
  File "/home/adi/chevah/twisted/src/twisted/scripts/trial.py", line 652, in run
    test_result = trialRunner.runUntilFailure(suite)
  File "/home/adi/chevah/twisted/src/twisted/trial/_dist/disttrial.py", line 454, in runUntilFailure
    return self.run(suite, untilFailure=True)
  File "/home/adi/chevah/twisted/src/twisted/trial/_dist/disttrial.py", line 436, in run
    if isinstance(result, Failure):
UnboundLocalError: local variable 'result' referenced before assignment
```

It would be nice to exit cleanly with a partial result, instead.

<details><summary>Searchable metadata</summary>

```
trac-id__10340 10340
type__enhancement enhancement
reporter__exarkun exarkun
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__trial trial
keywords__None None
time__1651587594761030 1651587594761030
changetime__1651587594761030 1651587594761030
version__None None
owner__None None

```
</details>

**Comment by adiroiban** [comment]
Just copying  the comment from https://github.com/twisted/twisted/pull/11897#pullrequestreview-1542200194

I have no idea what is going on there... I just did a quick debugging and throw that sleep in the mix and it looks like there is a race condition at the middle

------------

So... #11707 is fixed.

Not sure about #10340 ... there is still a traceback obfuscating the real traceback

I agree that this PR can be merged as it is.

Maybe also rename the title of the PR to

`#11707 Fix trial -j / ctrl-c interaction with bwreporter`


If I apply this diff (which is not a fix)... somethings the final tracebacks go away

So maybe #10340 should be kept open


```diff
diff --git a/src/twisted/trial/_dist/worker.py b/src/twisted/trial/_dist/worker.py
index 04c39fc855..7dd0823566 100644
--- a/src/twisted/trial/_dist/worker.py
+++ b/src/twisted/trial/_dist/worker.py
@@ -330,7 +330,10 @@ class LocalWorkerTransport:
         """
         Forward data to transport.
         """
-        self._transport.writeToChild(_WORKER_AMP_STDIN, data)
+        try:
+            self._transport.writeToChild(_WORKER_AMP_STDIN, data)
+        except KeyError:
+            pass
 
     def writeSequence(self, sequence):
         """
@@ -392,6 +395,7 @@ class LocalWorker(ProcessProtocol):
         """
         Cause the worker process to exit.
         """
+        import time; time.sleep(0.5)
         if self.transport is None:
             raise NotRunning()
```

**Comment by glyph** [comment]
It's not entirely clear to me that we could avoid reporting a traceback entirely when interrupting a suite run with Control-C; we are in some sense *asking* for things to please fail so as to wrap up prematurely. However, it does seem like there's a pile of irrelevant / internal tracebacks which could be more effectively suppressed here by having a cleaner shutdown.

**Comment by adiroiban** [comment]
True. One traceback is expected, just like we have if you don't use distrial .

Just for reference,

Output without distrial

```
$ trial twisted.conch.test.test_transport

MORE LOGS

 ClientSSHTransportDHGroupExchangeSHA1Tests
    test_KEXINIT_groupexchange ...                                         [OK]
    test_KEX_DH_GEX_GROUP ...                                              [OK]
    test_KEX_DH_GEX_REPLY ... ^C                                          [ERROR]

===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/home/adi/chevah/twisted/src/twisted/conch/test/test_transport.py", line 2191, in setUp
    self.privObj = keys.Key.fromString(keydata.privateRSA_openssh)
  File "/home/adi/chevah/twisted/src/twisted/conch/ssh/keys.py", line 218, in fromString
    return method(data, passphrase)
  File "/home/adi/chevah/twisted/src/twisted/conch/ssh/keys.py", line 546, in _fromString_PRIVATE_OPENSSH
    return cls._fromPrivateOpenSSH_PEM(data, passphrase)
  File "/home/adi/chevah/twisted/src/twisted/conch/ssh/keys.py", line 508, in _fromPrivateOpenSSH_PEM
    key = load_pem_private_key(data, passphrase, default_backend())
  File "/home/adi/chevah/twisted/venv/lib/python3.10/site-packages/cryptography/hazmat/primitives/serialization/base.py", line 24, in load_pem_private_key
    return ossl.load_pem_private_key(
  File "/home/adi/chevah/twisted/venv/lib/python3.10/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 957, in load_pem_private_key
    return self._load_key(
  File "/home/adi/chevah/twisted/venv/lib/python3.10/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1165, in _load_key
    return self._evp_pkey_to_private_key(
  File "/home/adi/chevah/twisted/venv/lib/python3.10/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 665, in _evp_pkey_to_private_key
    return _RSAPrivateKey(
  File "/home/adi/chevah/twisted/venv/lib/python3.10/site-packages/cryptography/hazmat/backends/openssl/rsa.py", line 381, in __init__
    res = backend._lib.RSA_check_key(rsa_cdata)
builtins.KeyboardInterrupt: 

twisted.conch.test.test_transport.ClientSSHTransportDHGroupExchangeSHA1Tests.test_KEX_DH_GEX_REPLY
-------------------------------------------------------------------------------
Ran 60 tests in 0.548s

FAILED (errors=1, successes=59)
```


if I do distrial, I can see an extra CancelledError ...and all the remaining tests are somehow still processed

```
$ trial -j1 twisted.conch.test.test_transport

MORE LOGS

   test_getHost ...                                                       [OK]
    test_getPeer ...                                                       [OK]
^C  ClientSSHTransportDHGroupExchangeSHA1Tests
    test_KEXINIT_groupexchange ...                                      [ERROR]
    test_KEX_DH_GEX_GROUP ...     test_KEX_DH_GEX_REPLY ...     test_disconnectGEX_REPLYBadSignature ...     test_disconnectIfCantMatchCipher ...     test_disconnectIfCantMatchCompression ...     test_disconnectIfCantMatchKex ...     test_disconnectIfCantMatchKeyAlg ...     test_disconnectIfCantMatchMAC ...     test_disconnectKEX_ECDH_REPLYBadSignature ...     test_getHost ...     test_getPeer ...   ClientSSHTransportDHGroupExchangeSHA256Tests
    test_KEXINIT_groupexchange ...     test_KEX_DH_GEX_GROUP ...     test_KEX_DH_GEX_REPLY ...     test_disconnectGEX_REPLYBadSignature ...     test_disconnectIfCantMatchCipher ...     test_disconnectIfCantMatchCompression ...     test_disconnectIfCantMatchKex ...     test_disconnectIfCantMatchKeyAlg ...     test_disconnectIfCantMatchMAC ...     test_disconnectKEX_ECDH_REPLYBadSignature ...     test_getHost ...     test_getPeer ...   ClientSSHTransportECDHTests
    test_KEXDH_REPLY ...     test_KEXINIT ...     test_disconnectIfCantMatchCipher ...     test_disconnectIfCantMatchCompression ...     test_disconnectIfCantMatchKex ...     test_disconnectIfCantMatchKeyAlg ...     test_disconnectIfCantMatchMAC ...     test_disconnectKEXDH_REPLYBadSignature ...     test_getHost ...     test_getPeer ...   ClientSSHTransportTests
    test_KEXDH_REPLY ...     test_KEXINITExtensionNegotiation ...     test_KEXINITMultipleAlgorithms ...     test_KEXINIT_badKexAlg ...     test_KEXINIT_group14 ...     test_NEWKEYS ...                                                    [ERROR]
    test_SERVICE_ACCEPT ...     test_disconnectIfCantMatchCipher ...     test_disconnectIfCantMatchCompression ...     test_disconnectIfCantMatchKex ...     test_disconnectIfCantMatchKeyAlg ...     test_disconnectIfCantMatchMAC ...     test_disconnectKEXDH_REPLYBadSignature ...     test_disconnectKEX_ECDH_REPLYBadSignature ...     test_disconnectNEWKEYSData ...     test_disconnectSERVICE_ACCEPT ...     test_getHost ...     test_getPeer ...     test_keySetup ...     test_noPayloadSERVICE_ACCEPT ...     test_notImplementedClientMethods ...     test_requestService ...   GetMACTests
    test_hmacmd5 ...     test_hmacsha1 ...     test_hmacsha2256 ...     test_hmacsha2384 ...     test_hmacsha2512 ...     test_none ...   SSHCiphersTests
    test_getCipher ...     test_init ...     test_makeMAC ...     test_setKeysCiphers ...     test_setKeysMACs ...   ServerSSHTransportCurve25519SHA256Tests
    test_KEX_ECDH_INIT ...     test_disconnectIfCantMatchCipher ...     test_disconnectIfCantMatchCompression ...     test_disconnectIfCantMatchKex ...     test_disconnectIfCantMatchKeyAlg ...     test_disconnectIfCantMatchMAC ...     test_getHost ...     test_getPeer ...   ServerSSHTransportDHGroupExchangeSHA1Tests
    test_KEX_DH_GEX_INIT_after_REQUEST ...     test_KEX_DH_GEX_INIT_after_REQUEST_OLD ...     test_KEX_DH_GEX_INIT_after_REQUEST_rsa_sha2_512 ...     test_KEX_DH_GEX_REQUEST ...     test_KEX_DH_GEX_REQUEST_OLD ...     test_KEX_DH_GEX_REQUEST_OLD_badKexAlg ...     test_disconnectIfCantMatchCipher ...     test_disconnectIfCantMatchCompression ...     test_disconnectIfCantMatchKex ...     test_disconnectIfCantMatchKeyAlg ...     test_disconnectIfCantMatchMAC ...     test_getHost ...     test_getPeer ...   ServerSSHTransportDHGroupExchangeSHA256Tests
    test_KEX_DH_GEX_INIT_after_REQUEST ...     test_KEX_DH_GEX_INIT_after_REQUEST_OLD ...     test_KEX_DH_GEX_INIT_after_REQUEST_rsa_sha2_512 ...     test_KEX_DH_GEX_REQUEST ...     test_KEX_DH_GEX_REQUEST_OLD ...     test_KEX_DH_GEX_REQUEST_OLD_badKexAlg ...     test_disconnectIfCantMatchCipher ...     test_disconnectIfCantMatchCompression ...     test_disconnectIfCantMatchKex ...     test_disconnectIfCantMatchKeyAlg ...     test_disconnectIfCantMatchMAC ...     test_getHost ...     test_getPeer ...   ServerSSHTransportECDHTests
    test_KEX_ECDH_INIT ...     test_disconnectIfCantMatchCipher ...     test_disconnectIfCantMatchCompression ...     test_disconnectIfCantMatchKex ...     test_disconnectIfCantMatchKeyAlg ...     test_disconnectIfCantMatchMAC ...     test_getHost ...     test_getPeer ...   ServerSSHTransportTests
    test_ECDH_keySetup ...     test_KEXDH_INIT_GROUP14 ...     test_KEXDH_INIT_GROUP14_rsa_sha2_256 ...     test_KEXDH_INIT_GROUP14_rsa_sha2_512 ...     test_KEXINITExtensionNegotiation ...     test_KEXINITMultipleAlgorithms ...     test_NEWKEYS ...     test_SERVICE_REQUEST ...     test__getHostKeys ...     test_checkBad_KEX_ECDH_INIT_CurveName ...     test_checkBad_KEX_INIT_CurveName ...     test_disconnectIfCantMatchCipher ...     test_disconnectIfCantMatchCompression ...     test_disconnectIfCantMatchKex ...     test_disconnectIfCantMatchKeyAlg ...     test_disconnectIfCantMatchMAC ...     test_disconnectNEWKEYSData ...     test_disconnectSERVICE_REQUESTBadService ...     test_getHost ...     test_getPeer ...     test_ignoreGuessPacketKex ...     test_ignoreGuessPacketKey ...     test_keySetup ...     test_keySetupWithExtInfo ...   TransportLoopbackTests
    test_ciphers ...     test_compressions ...     test_keyexchanges ...     test_macs ... 
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/home/adi/chevah/twisted/src/twisted/trial/_dist/disttrial.py", line 370, in task
    await worker.run(case, result)
  File "/home/adi/chevah/twisted/src/twisted/trial/_dist/worker.py", line 300, in run
    return await self.callRemote(workercommands.Run, testCase=testCaseId)  # type: ignore[no-any-return]
twisted.internet.defer.CancelledError: 

twisted.conch.test.test_transport.ClientSSHTransportDHGroupExchangeSHA1Tests.test_KEXINIT_groupexchange
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/home/adi/chevah/twisted/src/twisted/conch/test/test_transport.py", line 2191, in setUp
    self.privObj = keys.Key.fromString(keydata.privateRSA_openssh)
  File "/home/adi/chevah/twisted/src/twisted/conch/ssh/keys.py", line 218, in fromString
    return method(data, passphrase)
  File "/home/adi/chevah/twisted/src/twisted/conch/ssh/keys.py", line 546, in _fromString_PRIVATE_OPENSSH
    return cls._fromPrivateOpenSSH_PEM(data, passphrase)
  File "/home/adi/chevah/twisted/src/twisted/conch/ssh/keys.py", line 508, in _fromPrivateOpenSSH_PEM
    key = load_pem_private_key(data, passphrase, default_backend())
  File "/home/adi/chevah/twisted/venv/lib/python3.10/site-packages/cryptography/hazmat/primitives/serialization/base.py", line 24, in load_pem_private_key
    return ossl.load_pem_private_key(
  File "/home/adi/chevah/twisted/venv/lib/python3.10/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 957, in load_pem_private_key
    return self._load_key(
  File "/home/adi/chevah/twisted/venv/lib/python3.10/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1165, in _load_key
    return self._evp_pkey_to_private_key(
  File "/home/adi/chevah/twisted/venv/lib/python3.10/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 665, in _evp_pkey_to_private_key
    return _RSAPrivateKey(
  File "/home/adi/chevah/twisted/venv/lib/python3.10/site-packages/cryptography/hazmat/backends/openssl/rsa.py", line 381, in __init__
    res = backend._lib.RSA_check_key(rsa_cdata)
builtins.KeyboardInterrupt: 

twisted.conch.test.test_transport.ClientSSHTransportTests.test_NEWKEYS
-------------------------------------------------------------------------------
Ran 194 tests in 0.669s

FAILED (errors=2, successes=57)
```


and sometimes I also get errors like

```
  File "/home/adi/chevah/twisted/src/twisted/trial/_dist/worker.py", line 333, in write
    return self._transport.writeToChild(_WORKER_AMP_STDIN, data)
  File "/home/adi/chevah/twisted/src/twisted/internet/process.py", line 1002, in writeToChild
    self.pipes[childFD].write(data)
builtins.KeyError: 3
```

**Comment by exarkun** [comment]
> True. One traceback is expected, just like we have if you don't use distrial .

I don't think this is necessarily correct.  If you don't use disttrial, trial is running one piece of user code at a time.  If you interrupt it, you are informed that one piece of user code was interrupted.  If you do use disttrial, trial is running N pieces of user code at a time.  I don't see why it should still tell you about _one_ of those being interrupted and not the rest.

I agree that the giant wall of `KeyboardInterrupt` tracebacks isn't the _ideal_ way to report this but I don't think there is a good solution that reports _one_ of these and not the rest.

**Comment by glyph** [comment]
> I agree that the giant wall of `KeyboardInterrupt` tracebacks isn't the _ideal_ way to report this but I don't think there is a good solution that reports _one_ of these and not the rest.

Yes, I think the `KeyboardInterrupt` exceptions are unavoidable. However, `KeyError` in `writeToChild` is a bug in the process pool and should be fixed.

**Comment by exarkun** [comment]
> True. One traceback is expected, just like we have if you don't use distrial .

I don't think this is necessarily correct.  If you don't use disttrial, trial is running one piece of user code at a time.  If you interrupt it, you are informed that one piece of user code was interrupted.  If you do use disttrial, trial is running N pieces of user code at a time.  I don't see why it should still tell you about _one_ of those being interrupted and not the rest.

I agree that the giant wall of `KeyboardInterrupt` tracebacks isn't the _ideal_ way to report this but I don't think there is a good solution that reports _one_ of these and not the rest.
