### ISSUE TITLE
Ctrl-c being capture in select reactor and program unable to exit

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10341]
|<img alt="dmcleod84's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| dmcleod84 reported|
|-|-|
|Trac ID|trac#10341|
|Type|defect|
|Created|2022-05-04 02:48:20Z|

Hello, 

When ending a python program implementing twisted framework it seems twisted's select reactor is capturing the Keyboard interrupt and not allowing the program to exit?

Output of the captured keyboard event below:

```
2022-05-04 11:58:09+1000 [-] Unhandled Error
        Traceback (most recent call last):
          File "C:\Repo\products\GPCLightVehicle\CentralServer\bin\rover_interface.py", line 85, in <module>
            app.start() # Blocking until interrupt
          File "C:\Users\Daniel\AppData\Local\Programs\Python\Python310\lib\site-packages\Manabotix\base_client.py", line 111, in start
            reactor.run()
          File "C:\Users\Daniel\AppData\Local\Programs\Python\Python310\lib\site-packages\twisted\internet\base.py", line 1315, in run
            self.mainLoop()
        --- <exception caught here> ---
          File "C:\Users\Daniel\AppData\Local\Programs\Python\Python310\lib\site-packages\twisted\internet\base.py", line 1328, in mainLoop
            reactorBaseSelf.doIteration(t)
          File "C:\Users\Daniel\AppData\Local\Programs\Python\Python310\lib\site-packages\twisted\internet\selectreactor.py", line 100, in doSelect
            r, w, ignored = _select(self._reads, self._writes, [], timeout)
          File "C:\Users\Daniel\AppData\Local\Programs\Python\Python310\lib\site-packages\twisted\internet\selectreactor.py", line 38, in win32select
            r, w, e = select.select(r, w, w, timeout)
          File "cypari\signals.pyx", line 230, in cypari._pari.python_check_interrupt

          File "cypari\signals.pyx", line 94, in cypari._pari.sig_raise_exception

        builtins.KeyboardInterrupt:
```

Version details:

    Python 3.10.1
    Twisted 22.4.0

Appreciate any insight that could be provided as to what is going on here. 

Please let me know if there is any further information required to assist progressing this. Cheers.

<details><summary>Searchable metadata</summary>

```
trac-id__10341 10341
type__defect defect
reporter__dmcleod84 dmcleod84
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__wontfix wontfix
component__core core
keywords__KeyboardInterrupt KeyboardInterrupt
time__1651632500693860 1651632500693860
changetime__1651694969396632 1651694969396632
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun set status to `closed`|
|-|-|

Yes.  The reactor does not allow arbitrary exceptions to cause it to shut down.  Instead, it must be stopped using `reactor.stop()` or, on some platforms, by delivering SIGINT, SIGBREAK, or SIGTERM.  This is by design.

For help implementing a certain behavior in your application, I suggest you reach out to the mailing list or the IRC channel.

**Comment by twisted-trac** [comment]
|<img alt="dmcleod84's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_2"></a>|dmcleod84 commented|
|-|-|

Replying to [Jean-Paul Calderone](#note_1):
> Yes.  The reactor does not allow arbitrary exceptions to cause it to shut down.  Instead, it must be stopped using `reactor.stop()` or, on some platforms, by delivering SIGINT, SIGBREAK, or SIGTERM.  This is by design.
> 
> For help implementing a certain behavior in your application, I suggest you reach out to the mailing list or the IRC channel.

Hi Jean-Paul

Thanks for the prompt response, I'm not sure I have made my issue clear. Will try again.

Our application already has a reactor.stop() implementation, however on a ctrl-c event we are unable to capture/detect the event as the exception is being caught by select.reactor and ignored and the program keeps running. This means we are unable to terminate the program with a keyboard command.

If we are unable to detect the ctrl-c as it is being caught and ignored by Twisted how can we run reactor.stop()?

For reference, this used to work as we expected, a KeyboardInterrupt exception would be raised on ctrl-c and we could then run reactor.stop(), however a few month ago we observed the above exception being caught in select.reactor and then program keeps running. Quite frustrating as we cannot end the program with a keyboard command, have to close the terminal. Not really useful for development.

Any feedback on this would be greatly appreciated, thank you.
