### ISSUE TITLE
cftp crashes with an unhandled exception

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10351]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#10351|
|Type|defect|
|Created|2022-06-17 16:31:31Z|

```
Unhandled Error
Traceback (most recent call last):
  File "/home/exarkun/Work/python/twisted/src/twisted/python/log.py", line 96, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/exarkun/Work/python/twisted/src/twisted/python/log.py", line 80, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/exarkun/Work/python/twisted/src/twisted/python/context.py", line 117, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/exarkun/Work/python/twisted/src/twisted/python/context.py", line 82, in callWithContext
    return func(*args, **kw)
--- <exception caught here> ---
  File "/home/exarkun/Work/python/twisted/src/twisted/internet/posixbase.py", line 683, in _doReadOrWrite
    why = selectable.doRead()
  File "/home/exarkun/Work/python/twisted/src/twisted/internet/tcp.py", line 248, in doRead
    return self._dataReceived(data)
  File "/home/exarkun/Work/python/twisted/src/twisted/internet/tcp.py", line 253, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/home/exarkun/Work/python/twisted/src/twisted/conch/ssh/transport.py", line 764, in dataReceived
    self.dispatchMessage(messageNum, packet[1:])
  File "/home/exarkun/Work/python/twisted/src/twisted/conch/ssh/transport.py", line 790, in dispatchMessage
    self.service.packetReceived(messageNum, payload)
  File "/home/exarkun/Work/python/twisted/src/twisted/conch/ssh/service.py", line 50, in packetReceived
    return f(packet)
  File "/home/exarkun/Work/python/twisted/src/twisted/conch/ssh/connection.py", line 292, in ssh_CHANNEL_EXTENDED_DATA
    channel.extReceived(typeCode, data)
  File "/home/exarkun/Work/python/twisted/src/twisted/conch/scripts/cftp.py", line 926, in extReceived
    sys.stderr.write(data)
builtins.TypeError: write() argument must be str, not bytes
```

<details><summary>Searchable metadata</summary>

```
trac-id__10351 10351
type__defect defect
reporter__exarkun exarkun
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__conch conch
keywords__None None
time__1655483491905501 1655483491905501
changetime__1656211970721871 1656211970721871
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

https://github.com/twisted/twisted/pull/1738

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_2"></a>|@twm commented|
|-|-|

Removing from the review queue as the PR was approved by moshez here: https://github.com/twisted/twisted/pull/1738#pullrequestreview-1011595047
