### ISSUE TITLE
IOCP reactor lags behind in API changes

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10386]
|<img alt="justinj's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| justinj reported|
|-|-|
|Trac ID|trac#594|
|Type|defect|
|Created|2004-04-10 01:46:44Z|

<details><summary>Searchable metadata</summary>

```
trac-id__594 594
type__defect defect
reporter__justinj justinj
priority__high high
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__ 
keywords__ 
time__1081561604000000 1081561604000000
changetime__1084616598000000 1084616598000000
version__ 
owner__ 
cc__justinj cc__PenguinOfDoom
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="justinj's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|justinj commented|
|-|-|

```
#!html
<pre>
I have some code that works with the win32eventreactor, but I get the following
errors when I switch to IOCP.  Per radix, iocp lags behind in API changes.

C:\svn\RatControl\nevow\rend.py:41: DeprecationWarning: renderer.Renderer has be
en deprecated. Use rend.Page instead.
  NotFound = FourOhFour(), ()
2004/04/09 14:37 Central Daylight Time [-] Log opened.
2004/04/09 14:37 Central Daylight Time [-] twistd 1.2.1alpha2 (C:\Python23\pytho
n.exe 2.3.3) starting up
2004/04/09 14:37 Central Daylight Time [-] reactor class: &lt;class 'twisted.intern
et.iocpreactor.proactor.Proactor'>
2004/04/09 14:37 Central Daylight Time [-] nevow.appserver.NevowSite starting on
 8888
2004/04/09 14:37 Central Daylight Time [-] Starting factory &lt;nevow.appserver.Nev
owSite instance at 0x009E94B8>
2004/04/09 14:37 Central Daylight Time [-] Traceback (most recent call last):
          File "C:\Python23\lib\site-packages\twisted\protocols\http.py", line 5
57, in requestReceived
            self.process()
          File "C:\svn\RatControl\nevow\appserver.py", line 130, in process
            return self.site.getResourceFor(
          File "C:\svn\RatControl\nevow\appserver.py", line 277, in getResourceF
or
            return self.resourceAtPathOfRequest(request)
          File "C:\svn\RatControl\nevow\appserver.py", line 290, in resourceAtPa
thOfRequest
            return defer.maybeDeferred(res.locateChild, request, path).addCallba
ck(
        --- &lt;exception caught here> ---
          File "C:\Python23\lib\site-packages\twisted\internet\defer.py", line 1
29, in maybeDeferred
            result = f(*args, **kw)
          File "C:\svn\RatControl\nevow\guard.py", line 188, in locateChild
            prepath = request.prePathURL()
          File "C:\Python23\lib\site-packages\twisted\web\server.py", line 350,
in prePathURL
            port = self.getHost().port
        exceptions.AttributeError: 'int' object has no attribute 'port'

2004/04/09 14:37 Central Daylight Time [-] html is not a string:  None
2004/04/09 14:37 Central Daylight Time [-] 0 - - [09/Apr/2004:19:37:31 +0000] "G
ET / HTTP/1.1" 500 5768 "-" "Mozilla/5.0 (Windows; U; Windows NT 5.0; en-US; rv:
1.6) Gecko/20040206 Firefox/0.8"
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="PenguinOfDoom's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|PenguinOfDoom commented|
|-|-|

```
#!html
<pre>
Having roundup multiple accounts sucks.
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="PenguinOfDoom's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|PenguinOfDoom commented|
|-|-|

```
#!html
<pre>
Fixed in SVN. I think.
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
