### ISSUE TITLE
adbapi prints backtrace

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10473]
|<img alt="orbitz's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| orbitz reported|
|-|-|
|Trac ID|trac#631|
|Type|defect|
|Created|2004-06-04 02:23:20Z|

<details><summary>Searchable metadata</summary>

```
trac-id__631 631
type__defect defect
reporter__orbitz orbitz
priority__high high
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__ 
keywords__ 
time__1086315800000000 1086315800000000
changetime__1086486970000000 1086486970000000
version__ 
owner__davep davep
cc__davep cc__orbitz
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="orbitz's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|orbitz commented|
|-|-|

```
#!html
<pre>
If runQuery raises an exception, the backtrace is printed regardless of if there
is an errback or not.

I think it's in _runQuery or _runOperation.
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="jdavisp3's avatar" src="https://avatars.githubusercontent.com/u/43582?s=50" width="50" height="50">](https://github.com/jdavisp3)|@jdavisp3 commented|
|-|-|

```
#!html
<pre>
Could you expand on this a bit? I'm not sure exactly what you mean.
Do you have some code that exposes the bug?
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="orbitz's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|orbitz commented|
|-|-|

```
#!html
<pre>
If I do a runQuery that causes an exception to be raised, then even if I have an
errback, the exception backtrace is given.
I'm under the impression I shouldn't get the backtrace.

dbpool = adbapi.ConnectionPool(...)

def printQuery(res):
  print 'Success'

def printErr(fail):
  fail.trap(Exception)
  print 'In error'
  print fail

dbpool.runQuery("""select""").addCallback(printQuery).addErrback(printErr)

I get:
Traceback (most recent call last):
  File "/usr/local/Twisted-1.2.0/twisted/python/threadpool.py", line 157, in
_worker
    context.call(ctx, function, *args, **kwargs)
  File "/usr/local/Twisted-1.2.0/twisted/python/context.py", line 53, in
callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/Twisted-1.2.0/twisted/python/context.py", line 32, in
callWithContext
    return func(*args,**kw)
  File "/usr/local/Twisted-1.2.0/twisted/internet/threads.py", line 37, in
_putResultInDeferred
    result = f(*args, **kwargs)
--- &lt;exception caught here> ---
  File "/usr/local/Twisted-1.2.0/twisted/enterprise/adbapi.py", line 247, in
_runQuery
    apply(curs.execute, args, kw)
  File "/usr/local/lib/python2.3/site-packages/MySQLdb/cursors.py", line 95, in
execute
    return self._execute(query, args)
  File "/usr/local/lib/python2.3/site-packages/MySQLdb/cursors.py", line 114, in
_execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.3/site-packages/MySQLdb/connections.py", line 33,
in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL
syntax.  Check the manual that corresponds to your MySQL server version for the
right syntax to use near '' at line 1")
In error
[Failure instance: Traceback: _mysql_exceptions.ProgrammingError, (1064, "You
have an error in your SQL syntax.  Check the manual that corresponds to your
MySQL server version for the right syntax to use near '' at line 1")
/usr/local/Twisted-1.2.0/twisted/internet/threads.py:37:_putResultInDeferred
/usr/local/Twisted-1.2.0/twisted/enterprise/adbapi.py:247:_runQuery
/usr/local/lib/python2.3/site-packages/MySQLdb/cursors.py:95:execute
/usr/local/lib/python2.3/site-packages/MySQLdb/cursors.py:114:_execute
/usr/local/lib/python2.3/site-packages/MySQLdb/connections.py:33:defaulterrorha
ndler
]
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="jdavisp3's avatar" src="https://avatars.githubusercontent.com/u/43582?s=50" width="50" height="50">](https://github.com/jdavisp3)|@jdavisp3 commented|
|-|-|

```
#!html
<pre>
Ah, right. Sorry, a little slow today :)

All sql exceptions are logged with the twisted
logging system before being re-raised. When you
are running from the command line, the log just
writes to standard out. You can redirect the log
or turn it off, I believe, see 'twisted.python.log'.

We write these exceptions to the logs to aid in
debugging your sql.
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="orbitz's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|orbitz commented|
|-|-|

```
#!html
<pre>
Ok, I was told it probably shouldn't be there still, but looks like it is. Cheers.
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="jdavisp3's avatar" src="https://avatars.githubusercontent.com/u/43582?s=50" width="50" height="50">](https://github.com/jdavisp3)|@jdavisp3 commented|
|-|-|

```
#!html
<pre>
Hm, ok. Well, I can take it out this weekend, then.
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="orbitz's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|orbitz commented|
|-|-|

```
#!html
<pre>
Just as long as it can be turned of I guess leaving it there is fine. personally
i'd prefer off by default, on with option.  But i don't maintain it:)
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="jdavisp3's avatar" src="https://avatars.githubusercontent.com/u/43582?s=50" width="50" height="50">](https://github.com/jdavisp3)|@jdavisp3 commented|
|-|-|

```
#!html
<pre>
Ah, what if I used the noisy parameter to turn it off?
Would that work for you? Turning off noisy means you
wouldn't see connect/disconnect messages either.
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="jdavisp3's avatar" src="https://avatars.githubusercontent.com/u/43582?s=50" width="50" height="50">](https://github.com/jdavisp3)|@jdavisp3 commented|
|-|-|

```
#!html
<pre>
This is now in svn.
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="jdavisp3's avatar" src="https://avatars.githubusercontent.com/u/43582?s=50" width="50" height="50">](https://github.com/jdavisp3)|@jdavisp3 commented|
|-|-|

```
#!html
<pre>
After talking with itamar, I'm just going to remove the logging calls.
</pre>
```
