### ISSUE TITLE
Incorrect traceback from trial

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10488]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#769|
|Type|defect|
|Created|2004-10-30 02:08:59Z|

<details><summary>Searchable metadata</summary>

```
trac-id__769 769
type__defect defect
reporter__exarkun exarkun
priority__high high
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__trial trial
keywords__ 
time__1099102139000000 1099102139000000
changetime__1132812848000000 1132812848000000
version__ 
owner__ 
cc__radix cc__exarkun cc__spiv cc__jml
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun commented|
|-|-|

```
#!html
<pre>
exarkun@boson:~$ PYTHONPATH=~/projects/python/Twisted/trunk/ trial -v test_foo
  test_foo
    Foo
      testFoo ...                                                       [ERROR]

===============================================================================
[ERROR]: testFoo (test_foo.Foo)


  File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py",
line 717, in run
    util._wait(r, self.timeout)
  File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/util.py", line
209, in _wait
    r.raiseException()
  File "/home/exarkun/projects/python/Twisted/trunk/twisted/python/failure.py",
line 246, in raiseException
    raise self.value.__class__, self.value, self.tb
exceptions.ZeroDivisionError: integer division or modulo by zero


-------------------------------------------------------------------------------
Ran 1 tests in 0.032s

FAILED (errors=1)
exarkun@boson:~$ cat test_foo.py
from twisted.internet import defer
from twisted.trial import unittest

class Foo(unittest.TestCase):
    def testFoo(self):
        self.assertEquals("foo", "foo")
        return defer.fail(Exception("foo")
            ).addErrback(self._ebFoo
            ).addErrback(self._ebBar
            )
    
    def _ebFoo(self, result):
        result.trap(Exception)
        1/0

    def _ebBar(self, result):
        result.trap(StopIteration)
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="slyphon's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|slyphon commented|
|-|-|

```
#!html
<pre>
this seems to be more of an issue with the way deferreds work, there is no way
that trial would be able to get the nested exception, no?

all this is doing is waiting for a deferred to return and if the result is a
failure it calls failure.raiseException

this would require a change to Deferred to hold all the failures that happened
along the way in a list
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="slyphon's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|slyphon commented|
|-|-|

```
#!html
<pre>
i'm downgrading this to a bug as it's really an issue with deferreds
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun commented|
|-|-|

```
#!html
<pre>
This has nothing to do with multiple failures.  Even if only one failures
occurs, the traceback is incorrect.
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="spiv's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|spiv commented|
|-|-|

```
#!html
<pre>
Output as of r12311:

andrew@trogdor ~/code/Twisted $ PYTHONPATH=. trial -v test_foo
  test_foo
    Foo
      testFoo ...                                                       [ERROR]

===============================================================================
[ERROR]: testFoo (test_foo.Foo)


  File "/home/andrew/code/Twisted/twisted/trial/runner.py", line 743, in run
    util._wait(r, self.timeout)
  File "/home/andrew/code/Twisted/twisted/trial/util.py", line 235, in _wait
    raise r.value.__class__, r.getTraceback()
exceptions.ZeroDivisionError: Traceback (most recent call last):
  File "/home/andrew/code/Twisted/twisted/trial/runner.py", line 741, in run
    r = self.original(tci)
  File "/home/andrew/code/Twisted/test_foo.py", line 7, in testFoo
    return defer.fail(Exception("foo")
  File "/home/andrew/code/Twisted/twisted/internet/defer.py", line 211, in
addErrback
    errbackKeywords=kw)
  File "/home/andrew/code/Twisted/twisted/internet/defer.py", line 193, in
addCallbacks
    self._runCallbacks()
--- &lt;exception caught here> ---
  File "/home/andrew/code/Twisted/twisted/internet/defer.py", line 326, in
_runCallbacks
    self.result = callback(self.result, *args, **kw)
  File "/home/andrew/code/Twisted/test_foo.py", line 14, in _ebFoo
    1/0
exceptions.ZeroDivisionError: integer division or modulo by zero



-------------------------------------------------------------------------------
Ran 1 tests in 0.139s

FAILED (errors=1)


This looks satisfactory to me... is this now resolved?
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="slyphon's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|slyphon commented|
|-|-|

```
#!html
<pre>
no, the problem comes when an exception class doesn't have a default
constructor, as the line 

    raise r.value.__class__, r.getTraceback()

will raise a TypeError
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="spiv's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|spiv commented|
|-|-|

```
#!html
<pre>
Ok, r12311 got reverted due to unforeseen issues.

Here's my proposal:

  - for deferreds returned from test methods (as in this issue), trial should 
    add an errback to capture it, and report it by using failure.printTraceback
    (rather than the troublesome failure.raiseException).

That alone solves the problem as stated here.  Judging from IRC conversations
there's a wider problem, which is dealing with errors in deferreds used with
wait, but I think they can be handled similarly:

  - for deferreds used with twisted.trial.util.wait, wait should add an errback 
    to capture failure, and raise a TrialWaitError exception that wraps the 
    failure.
  - if TrialWaitError is raised from a test method, trial should report the 
    wrapped failure, as above.
  - a new convenience method could be added, assertWaitRaises(error, deferred), 
    with similar meaning to assertRaises.

This would allow writing e.g.:

   wait(maybeDeferred(lambda: 1/0))

and:

   self.assertWaitRaises(ZeroDivisionError, maybeDeferred(lambda: 1/0))

Critiques?
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun commented|
|-|-|

```
#!html
<pre>
I'm not sure what the status of twisted.trial.util.LoggedErrors is, but as a
strike against it, tests which fail with it cannot take advantage of the new
.todo behavior - the attribute would have to be set to to (LoggedErrors, "entire
traceback"), which is bad enough by itself, but "entire traceback" cannot even
be computed statically, since it contains paths which will vary from system to
system.

I don't know why LoggedErrors exists, but I think it was an attempt to resolve
this issue, so I'm adding this comment here.  If you think it belongs on a
separate ticket, please create one.
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="spiv's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|spiv commented|
|-|-|

```
#!html
<pre>
LoggedErrors seems to predate this issue being raised.  I'll raise a new issue
for msg2807.
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="slyphon's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|slyphon commented|
|-|-|

```
#!html
<pre>
sigh, well, i believe that my latest commit solves this issue, but yes, the
LoggedErrors doesn't work with .todo because .raiseException is broken

then again, you can always .todo LoggedErrors

this is a hairy issue, and a frustrating one because someone should have
deprecated .raiseException a long time ago...and I wouldn't have designed around
its correct behavior :(

exarkun, I hereby bounce this issue over to you. if you would be so kind as to
test, as you are the one who opened this bug, and then close this issue.
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="slyphon's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|slyphon commented|
|-|-|

```
#!html
<pre>
ahem, the first sentence of msg 2819 should have read

"...the Logged errors exist and don't work with .todo, because I'd designed the
whole mess around .raiseException not being broken"
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun commented|
|-|-|

```
#!html
<pre>
re 2819,

No, you cannot .todo LoggedErrors, for the reason I mentioned in 2807.
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="radix's avatar" src="https://avatars.githubusercontent.com/u/227068?s=50" width="50" height="50">](https://github.com/radix)|@radix commented|
|-|-|

```
#!html
<pre>
I don't understand this issue. Should I assume "done-cbb" means "does need any
more work before 2.0"? If so, it should probably be moved to "bug" status.
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)|@jml commented|
|-|-|

```
#!html
<pre>
I also don't understand this issue.  I can see the observed behaviour, and how
to reproduce, but I'm not certain what the expected behaviour is. 

Current test_foo output:
Running 1 tests.
  trial-tb
    Foo
      testFoo ...                                                       [ERROR]

===============================================================================
[ERROR]: trial-tb.Foo.testFoo

  File "/Users/jml/projects/Twisted/twisted/internet/defer.py", line 307, in
_runCallbacks
    self.result = callback(self.result, *args, **kw)
  File "/Users/jml/projects/Scratch/trial-tb.py", line 14, in _ebFoo
    1/0
exceptions.ZeroDivisionError: integer division or modulo by zero
-------------------------------------------------------------------------------
Ran 1 tests in 0.141s

FAILED (errors=1)

...
Is this incorrect?  If so, what should it look like? (and why).

Is there anything in this discussion that will help this bug get fixed?

spiv, can you please link to the LoggedErrors issue that you filed?
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)|@jml commented|
|-|-|

```
#!html
<pre>
Current behaviour is fine, and it appears that it can't be better -- marking as
resolved.
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
