### ISSUE TITLE
Something broke twisted.web or twisted.internet.tcp in the latests commits

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10486]
|<img alt="dialtone's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| dialtone reported|
|-|-|
|Trac ID|trac#767|
|Type|enhancement|
|Created|2004-10-29 21:23:18Z|

<details><summary>Searchable metadata</summary>

```
trac-id__767 767
type__enhancement enhancement
reporter__dialtone dialtone
priority__lowest lowest
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__ 
keywords__ 
time__1099084998000000 1099084998000000
changetime__1099363482000000 1099363482000000
version__ 
owner__ 
cc__itamarst cc__jknight cc__dialtone
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="dialtone's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|dialtone commented|
|-|-|

```
#!html
<pre>
Here is an almost full error log of this exception.

2004/10/29 17:18 CEST [-] 127.0.0.1 - - [29/Oct/2004:15:18:20 +0000] "GET /
HTTP/1.0" 200 4649 "-" "ApacheBench/2.0.41-dev"
2004/10/29 17:18 CEST [-] 127.0.0.1 - - [29/Oct/2004:15:18:20 +0000] "GET /
HTTP/1.0" 200 4649 "-" "ApacheBench/2.0.41-dev"
2004/10/29 17:18 CEST [-] 127.0.0.1 - - [29/Oct/2004:15:18:20 +0000] "GET /
HTTP/1.0" 200 4649 "-" "ApacheBench/2.0.41-dev"
2004/10/29 17:18 CEST [-] 127.0.0.1 - - [29/Oct/2004:15:18:20 +0000] "GET /
HTTP/1.0" 200 4649 "-" "ApacheBench/2.0.41-dev"
2004/10/29 17:18 CEST [HTTPChannel,46,127.0.0.1] Traceback (most recent call last):
          File "/usr/projects/Twisted/twisted/python/log.py", line 54, in
callWithLogger
            return callWithContext({"system": lp}, func, *args, **kw)
          File "/usr/projects/Twisted/twisted/python/log.py", line 41, in
callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File "/usr/projects/Twisted/twisted/python/context.py", line 52, in
callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/usr/projects/Twisted/twisted/python/context.py", line 31, in
callWithContext
            return func(*args,**kw)
        --- &lt;exception caught here> ---
          File "/usr/projects/Twisted/twisted/internet/default.py", line 527, in
_doReadOrWrite
            why = getattr(selectable, method)()
          File "/usr/projects/Twisted/twisted/internet/abstract.py", line 106,
in doWrite
            l = self.writeSomeData(self.dataBuffer)
          File "/usr/projects/Twisted/twisted/internet/tcp.py", line 272, in
writeSomeData
            return self.socket.send(buffer(data, 0, self.SEND_LIMIT))
        exceptions.AttributeError: Server instance has no attribute 'socket'

2004/10/29 17:18 CEST [HTTPChannel,46,127.0.0.1] Traceback (most recent call last):
          File "/usr/projects/Twisted/twisted/application/app.py", line 100, in
runReactorWithLogging
            reactor.run()
          File "/usr/projects/Twisted/twisted/internet/default.py", line 112, in run
            self.mainLoop()
          File "/usr/projects/Twisted/twisted/internet/default.py", line 123, in
mainLoop
            self.doIteration(t)
          File "/usr/projects/Twisted/twisted/internet/default.py", line 521, in
doSelect
            _logrun(selectable, _drdw, selectable, method, dict)
        --- &lt;exception caught here> ---
          File "/usr/projects/Twisted/twisted/python/log.py", line 54, in
callWithLogger
            return callWithContext({"system": lp}, func, *args, **kw)
          File "/usr/projects/Twisted/twisted/python/log.py", line 41, in
callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File "/usr/projects/Twisted/twisted/python/context.py", line 52, in
callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/usr/projects/Twisted/twisted/python/context.py", line 31, in
callWithContext
            return func(*args,**kw)
          File "/usr/projects/Twisted/twisted/internet/default.py", line 537, in
_doReadOrWrite
            self._disconnectSelectable(selectable, why, method=="doRead")
          File "/usr/projects/Twisted/twisted/internet/default.py", line 150, in
_disconnectSelectable
            selectable.connectionLost(failure.Failure(why))
          File "/usr/projects/Twisted/twisted/internet/tcp.py", line 320, in
connectionLost
            self._closeSocket()
          File "/usr/projects/Twisted/twisted/internet/tcp.py", line 289, in
_closeSocket
            self.socket.shutdown(2)
        exceptions.AttributeError: Server instance has no attribute 'socket'

2004/10/29 17:18 CEST [HTTPChannel,45,127.0.0.1] Traceback (most recent call last):
          File "/usr/projects/Twisted/twisted/python/log.py", line 54, in
callWithLogger
            return callWithContext({"system": lp}, func, *args, **kw)
          File "/usr/projects/Twisted/twisted/python/log.py", line 41, in
callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File "/usr/projects/Twisted/twisted/python/context.py", line 52, in
callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/usr/projects/Twisted/twisted/python/context.py", line 31, in
callWithContext
            return func(*args,**kw)
        --- &lt;exception caught here> ---
          File "/usr/projects/Twisted/twisted/internet/default.py", line 527, in
_doReadOrWrite
            why = getattr(selectable, method)()
          File "/usr/projects/Twisted/twisted/internet/abstract.py", line 106,
in doWrite
            l = self.writeSomeData(self.dataBuffer)
          File "/usr/projects/Twisted/twisted/internet/tcp.py", line 272, in
writeSomeData
            return self.socket.send(buffer(data, 0, self.SEND_LIMIT))
        exceptions.AttributeError: Server instance has no attribute 'socket'

2004/10/29 17:18 CEST [HTTPChannel,45,127.0.0.1] Traceback (most recent call last):
          File "/usr/projects/Twisted/twisted/application/app.py", line 100, in
runReactorWithLogging
            reactor.run()
          File "/usr/projects/Twisted/twisted/internet/default.py", line 112, in run
            self.mainLoop()
          File "/usr/projects/Twisted/twisted/internet/default.py", line 123, in
mainLoop
            self.doIteration(t)
          File "/usr/projects/Twisted/twisted/internet/default.py", line 521, in
doSelect
            _logrun(selectable, _drdw, selectable, method, dict)
        --- &lt;exception caught here> ---
          File "/usr/projects/Twisted/twisted/python/log.py", line 54, in
callWithLogger
            return callWithContext({"system": lp}, func, *args, **kw)
          File "/usr/projects/Twisted/twisted/python/log.py", line 41, in
callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File "/usr/projects/Twisted/twisted/python/context.py", line 52, in
callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/usr/projects/Twisted/twisted/python/context.py", line 31, in
callWithContext
            return func(*args,**kw)
          File "/usr/projects/Twisted/twisted/internet/default.py", line 537, in
_doReadOrWrite
            self._disconnectSelectable(selectable, why, method=="doRead")
          File "/usr/projects/Twisted/twisted/internet/default.py", line 150, in
_disconnectSelectable
            selectable.connectionLost(failure.Failure(why))
          File "/usr/projects/Twisted/twisted/internet/tcp.py", line 320, in
connectionLost
            self._closeSocket()
          File "/usr/projects/Twisted/twisted/internet/tcp.py", line 289, in
_closeSocket
            self.socket.shutdown(2)
        exceptions.AttributeError: Server instance has no attribute 'socket'
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="jyknight's avatar" src="https://avatars.githubusercontent.com/u/873903?s=50" width="50" height="50">](https://github.com/jyknight)|@jyknight commented|
|-|-|

```
#!html
<pre>
tcp.readConnectionLost calls self.connectionLost(reason), if the protocol can't handle 
readConnectionLost. However, the writer has not been removed at that point, because connectionLost 
doesn't removeWriter -- whatever calls connectionLost generally does that.

Likely solution: abstract.connectionLost should self.removeWriter/removeReader after everything it 
does now.
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)|@itamarst commented|
|-|-|

```
#!html
<pre>
Fixed, it seems.
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
