### ISSUE TITLE
Lame ass error reporting formatting from trial

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10507]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#779|
|Type|defect|
|Created|2004-11-07 09:24:13Z|

Attachments:

* [trial.txt](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/635/63573d008f93d619a8743d27c55d58dcaab1c28d/37c388d26c369b2908bf3e70d7169ecc7215e792.txt) (1315 bytes) - added by exarkun on 2004-11-07 09:24:13Z - 

<details><summary>Searchable metadata</summary>

```
trac-id__779 779
type__defect defect
reporter__exarkun exarkun
priority__high high
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__trial trial
keywords__ 
time__1099819453000000 1099819453000000
changetime__1100972838000000 1100972838000000
version__ 
owner__ 
cc__exarkun cc__slyphon
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun commented|
|-|-|

```
#!html
<pre>
This seen at the end of a trial running, handily obscuring the fact that there
was an import error.
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="slyphon's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|slyphon commented|
|-|-|

```
#!html
<pre>
fixed in r12409
----------------

slyphon@willie-the-pimp:~ttt % cat foo.py
from twisted.trial import unittest
import supercalifragilisticexpialidocious


class Test(unittest.TestCase):
    pass


slyphon@willie-the-pimp:~ttt % trial -v foo.py
Traceback (most recent call last):
  File "/home/slyphon/Projects/Twisted/trunk/twisted/scripts/trial.py", line
697, in run
    config.parseOptions()
  File "/home/slyphon/Projects/Twisted/trunk/twisted/python/usage.py", line 193,
in parseOptions
    self.parseArgs(*args)
  File "/home/slyphon/Projects/Twisted/trunk/twisted/scripts/trial.py", line
423, in parseArgs
    self._handleFile(arg)
  File "/home/slyphon/Projects/Twisted/trunk/twisted/scripts/trial.py", line
283, in _handleFile
    self._tryNamedAny(mname)
--- &lt;exception caught here> ---
  File "/home/slyphon/Projects/Twisted/trunk/twisted/scripts/trial.py", line
358, in _tryNamedAny
    n = reflect.namedAny(arg)
  File "/home/slyphon/Projects/Twisted/trunk/twisted/python/reflect.py", line
370, in namedAny
    topLevelPackage = __import__(trialname)
  File "/home/slyphon/Projects/Twisted/trunk/twisted/trial/foo.py", line 2, in ?
    import supercalifragilisticexpialidocious
exceptions.ImportError: No module named supercalifragilisticexpialidocious

===============================================================================
IMPORT ERROR:

Could not import twisted.trial.foo: 
  File "/home/slyphon/Projects/Twisted/trunk/twisted/scripts/trial.py", line
358, in _tryNamedAny
    n = reflect.namedAny(arg)
  File "/home/slyphon/Projects/Twisted/trunk/twisted/python/reflect.py", line
370, in namedAny
    topLevelPackage = __import__(trialname)
  File "/home/slyphon/Projects/Twisted/trunk/twisted/trial/foo.py", line 2, in ?
    import supercalifragilisticexpialidocious
exceptions.ImportError: No module named supercalifragilisticexpialidocious

-------------------------------------------------------------------------------
Ran 0 tests in 0.000s

PASSED
slyphon@willie-the-pimp:~ttt %
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="radix's avatar" src="https://avatars.githubusercontent.com/u/227068?s=50" width="50" height="50">](https://github.com/radix)|@radix commented|
|-|-|

```
#!html
<pre>
I have verified that this is resolved; Nunatak's buildbot goes red on import
errors now.
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
