### ISSUE TITLE
twisted.enterprise.util.quote doesn't quotes unicode strings

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10501]
|<img alt="akhavr's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| akhavr reported|
|-|-|
|Trac ID|trac#675|
|Type|defect|
|Created|2004-08-14 19:20:58Z|

<details><summary>Searchable metadata</summary>

```
trac-id__675 675
type__defect defect
reporter__akhavr akhavr
priority__high high
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__ 
keywords__core core
time__1092511258000000 1092511258000000
changetime__1097923639000000 1097923639000000
version__ 
owner__davep davep
cc__davep cc__itamarst cc__akhavr
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="akhavr's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|akhavr commented|
|-|-|

```
#!html
<pre>
from twisted.enterprise.util import quote
print quote(u'xyz','char')
# "'xyz'"
print quote(u'','char')
# Traceback (most recent call last):
#   File "&lt;stdin>", line 1, in ?
#   File "/usr/lib/python2.3/site-packages/twisted/enterprise/util.py", line 90,
in quote
#     value = str(value)
# UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3:
ordinal not in range(128)
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="puzzlement's avatar" src="https://avatars.githubusercontent.com/u/94942?s=50" width="50" height="50">](https://github.com/puzzlement)|@puzzlement commented|
|-|-|

```
#!html
<pre>
Assigning to davep, although the authorship of the quote function is mainly
itamar's, so he can be nosy
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="jdavisp3's avatar" src="https://avatars.githubusercontent.com/u/43582?s=50" width="50" height="50">](https://github.com/jdavisp3)|@jdavisp3 commented|
|-|-|

```
#!html
<pre>
I can't duplicate this on Python2.3.4. What version of python
are you using? I do notice one potential problem -- Unicode
strings will be converted to ascii strings. I presume we should
leave Unicode strings as Unicode since many databases support
them?
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="jdavisp3's avatar" src="https://avatars.githubusercontent.com/u/43582?s=50" width="50" height="50">](https://github.com/jdavisp3)|@jdavisp3 commented|
|-|-|

```
#!html
<pre>
I think you may be the victim of this bug, which I quote
from the 2.3.4 NEWS file:

Bug #924361: Properly support normalization of empty unicode strings.



http://www.python.org/2.3.4/NEWS.html
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="jdavisp3's avatar" src="https://avatars.githubusercontent.com/u/43582?s=50" width="50" height="50">](https://github.com/jdavisp3)|@jdavisp3 commented|
|-|-|

```
#!html
<pre>
Quote now leaves unicode strings as unicode, so this
should be fixed for you.
</pre>
```
