### ISSUE TITLE
"mktap -t source" broken

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10517]
|[<img alt="teratorn's avatar" src="https://avatars.githubusercontent.com/u/154069?s=50" width="50" height="50">](https://github.com/teratorn)| @teratorn reported|
|-|-|
|Trac ID|trac#797|
|Type|defect|
|Created|2004-11-28 07:20:50Z|

<details><summary>Searchable metadata</summary>

```
trac-id__797 797
type__defect defect
reporter__teratorn teratorn
priority__high high
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__ 
keywords__core core
time__1101626450000000 1101626450000000
changetime__1101632438000000 1101632438000000
version__ 
owner__ 
cc__glyph cc__radix cc__exarkun cc__teratorn
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="teratorn's avatar" src="https://avatars.githubusercontent.com/u/154069?s=50" width="50" height="50">](https://github.com/teratorn)|@teratorn commented|
|-|-|

```
#!html
<pre>
It fails with any type of tap, not just web. radix, glyph, I put you on nosy 
because svn log says you have had the most to do with this code.

Elm ~ % mktap -t source web
/home/torn/code/pypath/twisted/web/twcgi.py:16: DeprecationWarning: twisted.
protocols.http is DEPRECATED. See http://twistedmatrix.com/projects/web.
  from twisted.protocols import http
/home/torn/code/pypath/twisted/web/woven/interfaces.py:60: 
ComponentsDeprecationWarning: Please don't use __adapt__ on Interface subclasses
  class IView(components.Interface):
/home/torn/code/pypath/twisted/web/woven/interfaces.py:135: 
ComponentsDeprecationWarning: Please don't use __adapt__ on Interface subclasses
  class IController(components.Interface):
Traceback (most recent call last):
  File "/usr/bin/mktap", line 30, in ?
    run()
  File "/home/torn/code/pypath/twisted/scripts/mktap.py", line 151, in run
    options['type'], options['encrypted'],
  File "/home/torn/code/pypath/twisted/scripts/mktap.py", line 61, in 
addToApplication
    sob.IPersistable(a).save(filename=append, passphrase=passphrase)
  File "/home/torn/code/pypath/twisted/persisted/sob.py", line 125, in save
    self._saveTemp(filename, passphrase, dumpFunc)
  File "/home/torn/code/pypath/twisted/persisted/sob.py", line 93, in _saveTemp
    dumpFunc(self.original, f)
  File "/home/torn/code/pypath/twisted/persisted/aot.py", line 441, in 
jellyToSource
    aot = jellyToAOT(obj)
  File "/home/torn/code/pypath/twisted/persisted/aot.py", line 432, in 
jellyToAOT
    return AOTJellier().jelly(obj)
  File "/home/torn/code/pypath/twisted/persisted/aot.py", line 548, in jelly
    ao = self.jellyToAO(obj)
  File "/home/torn/code/pypath/twisted/persisted/aot.py", line 529, in jellyToAO
    state = self.jellyToAO(obj.__getstate__())
  File "/home/torn/code/pypath/twisted/persisted/aot.py", line 524, in jellyToAO
    d[self.jellyToAO(k)] = self.jellyToAO(v)
  File "/home/torn/code/pypath/twisted/persisted/aot.py", line 524, in jellyToAO
    d[self.jellyToAO(k)] = self.jellyToAO(v)
  File "/home/torn/code/pypath/twisted/persisted/aot.py", line 529, in jellyToAO
    state = self.jellyToAO(obj.__getstate__())
  File "/home/torn/code/pypath/twisted/persisted/aot.py", line 524, in jellyToAO
    d[self.jellyToAO(k)] = self.jellyToAO(v)
  File "/home/torn/code/pypath/twisted/persisted/aot.py", line 516, in jellyToAO
    retval.setObj(map(self.jellyToAO, obj)) #hah!
  File "/home/torn/code/pypath/twisted/persisted/aot.py", line 529, in jellyToAO
    state = self.jellyToAO(obj.__getstate__())
  File "/home/torn/code/pypath/twisted/persisted/aot.py", line 524, in jellyToAO
    d[self.jellyToAO(k)] = self.jellyToAO(v)
  File "/home/torn/code/pypath/twisted/persisted/aot.py", line 516, in jellyToAO
    retval.setObj(map(self.jellyToAO, obj)) #hah!
  File "/home/torn/code/pypath/twisted/persisted/aot.py", line 529, in jellyToAO
    state = self.jellyToAO(obj.__getstate__())
  File "/home/torn/code/pypath/twisted/persisted/aot.py", line 524, in jellyToAO
    d[self.jellyToAO(k)] = self.jellyToAO(v)
  File "/home/torn/code/pypath/twisted/persisted/aot.py", line 519, in jellyToAO
    retval.setObj(tuple(map(self.jellyToAO, obj)))
  File "/home/torn/code/pypath/twisted/persisted/aot.py", line 529, in jellyToAO
    state = self.jellyToAO(obj.__getstate__())
  File "/home/torn/code/pypath/twisted/persisted/aot.py", line 524, in jellyToAO
    d[self.jellyToAO(k)] = self.jellyToAO(v)
  File "/home/torn/code/pypath/twisted/persisted/aot.py", line 541, in jellyToAO
    raise "Unsupported type: %s" % objType.__name__
Unsupported type: bool
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="teratorn's avatar" src="https://avatars.githubusercontent.com/u/154069?s=50" width="50" height="50">](https://github.com/teratorn)|@teratorn commented|
|-|-|

```
#!html
<pre>
Jp fixed it. thanks.
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
