### ISSUE TITLE
Undesirable ValueError exception masking by namedAny()

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10527]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#808|
|Type|defect|
|Created|2004-12-06 01:13:48Z|

Attachments:

* [trialfix.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/38a/38afd2ec2f9db9276c61839b6a900df67a7c9544/f643304dcfa845f2281d13cd07336b01e7aebdca.patch) (931 bytes) - added by glyph on 2004-12-13 05:26:03Z - 

<details><summary>Searchable metadata</summary>

```
trac-id__808 808
type__defect defect
reporter__exarkun exarkun
priority__high high
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__ 
time__1102295628000000 1102295628000000
changetime__1109511071000000 1109511071000000
version__ 
owner__ 
cc__glyph cc__exarkun cc__itamarst
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun commented|
|-|-|

```
#!html
<pre>
I noticed this when getting annoying output from trial.

If a test module is specified by filename, and the module raises a ValueError on
import, trial reports things like this:

exarkun@boson:~$ trial -v test_foo.py
Traceback (most recent call last):
  File "/usr/bin/trial", line 35, in ?
    run()
  File "twisted/scripts/trial.py", line 669, in run
    config.parseOptions()
  File "twisted/python/usage.py", line 193, in parseOptions
    self.parseArgs(*args)
  File "twisted/scripts/trial.py", line 425, in parseArgs
    self._handleFile(arg)
  File "manhole/twisted/scripts/trial.py", line 292, in _handleFile
    exec sourcestring in m.__dict__
  File "&lt;string>", line 1, in ?
ValueError: Some difficulty.

Ugly, but informative.

If the test module is specified by fully qualified python name, however, things
come out a bit differently:

Traceback (most recent call last):
  File "/usr/bin/trial", line 35, in ?
    run()
  File "twisted/scripts/trial.py", line 669, in run
    config.parseOptions()
  File "twisted/python/usage.py", line 193, in parseOptions
    self.parseArgs(*args)
  File "twisted/scripts/trial.py", line 410, in parseArgs
    raise IOError(errno.ENOENT, os.strerror(errno.ENOENT), arg)
IOError: [Errno 2] No such file or directory: 'test_foo'

Ideally, the same error should be reported in both cases.  I'm not sure how
namedAny() can be made to notice the difference between ValueErrors.  String
comparison would probably work, but is obviously not a wonderful solution.
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)|@glyph commented|
|-|-|

```
#!html
<pre>
Well, string comparison is the only solution that I could see that would work. 
I have attached a patch.  If you think that this solution is better than the
problem it's solving, please feel free to commit it.
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun commented|
|-|-|

```
#!html
<pre>
There are worse things in trial.  Committed at r13030 along with some new
namedAny unit tests for error behavior).
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
