### ISSUE TITLE
sshsimpleserver raises AttributeError (no attribute 'closed')

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10548]
|<img alt="spiv's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| spiv reported|
|-|-|
|Trac ID|trac#842|
|Type|defect|
|Created|2004-12-29 11:39:48Z|

<details><summary>Searchable metadata</summary>

```
trac-id__842 842
type__defect defect
reporter__spiv spiv
priority__high high
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__conch conch
keywords__documentation documentation
time__1104320388000000 1104320388000000
changetime__1104408054000000 1104408054000000
version__ 
owner__ 
cc__spiv cc__z3p
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="spiv's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|spiv commented|
|-|-|

```
#!html
<pre>
When closing a client's connection to the sshsimpleserver example (or stopping
the example with a client connection open), I get the following traceback:

Traceback (most recent call last):
          File "/home/andrew/code/Twisted/twisted/python/context.py", line 31,
in callWithContext
            return func(*args,**kw)
          File "/home/andrew/code/Twisted/twisted/conch/ssh/service.py", line
42, in packetReceived
            f(packet)
          File "/home/andrew/code/Twisted/twisted/conch/ssh/connection.py", line
169, in ssh_CHANNEL_CLOSE
            self.channelClosed(channel)
          File "/home/andrew/code/Twisted/twisted/conch/ssh/connection.py", line
420, in channelClosed
            log.callWithLogger(channel, channel.closed)
        --- &lt;exception caught here> ---
          File "/home/andrew/code/Twisted/twisted/python/log.py", line 54, in
callWithLogger
            return callWithContext({"system": lp}, func, *args, **kw)
          File "/home/andrew/code/Twisted/twisted/python/log.py", line 41, in
callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File "/home/andrew/code/Twisted/twisted/python/context.py", line 52,
in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/home/andrew/code/Twisted/twisted/python/context.py", line 31,
in callWithContext
            return func(*args,**kw)
          File "/home/andrew/code/Twisted/twisted/conch/ssh/session.py", line
122, in closed
            self.session.closed()
        exceptions.AttributeError: ExampleSession instance has no attribute 'closed'
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="spiv's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|spiv commented|
|-|-|

```
#!html
<pre>
At a glance, this seems to be because ExampleSession doesn't implement the full
ISession API?
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="z3p's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|z3p commented|
|-|-|

```
#!html
<pre>
Fixed in r12811.
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
