### ISSUE TITLE
twistd --version failed on windows? I'm using 1.3.0

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10577]
|<img alt="maoy's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| maoy reported|
|-|-|
|Trac ID|trac#742|
|Type|defect|
|Created|2004-10-08 00:43:22Z|

<details><summary>Searchable metadata</summary>

```
trac-id__742 742
type__defect defect
reporter__maoy maoy
priority__high high
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__ 
keywords__ 
time__1097196202000000 1097196202000000
changetime__1101611743000000 1101611743000000
version__ 
owner__ 
cc__maoy
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="maoy's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|maoy commented|
|-|-|

```
#!html
<pre>
D:\>twistd --version
Traceback (most recent call last):
  File "C:\Python23\scripts\twistd.py", line 36, in ?
    run()
  File "C:\Python23\lib\site-packages\twisted\scripts\twistw.py", line 61, in ru
n
    app.run(runApp, ServerOptions)
  File "C:\Python23\lib\site-packages\twisted\application\app.py", line 200, in
run
    config.parseOptions()
  File "C:\Python23\lib\site-packages\twisted\application\app.py", line 194, in
parseOptions
    usage.Options.parseOptions(self, options or sys.argv[1:] or ["--help"])
  File "C:\Python23\lib\site-packages\twisted\python\usage.py", line 187, in par
seOptions
    self.__dispatch[optMangled](optMangled, arg)
  File "C:\Python23\lib\site-packages\twisted\python\usage.py", line 347, in &lt;la
mbda>
    fn = lambda name, value=None, m=method: m()
  File "C:\Python23\lib\site-packages\twisted\scripts\twistw.py", line 29, in op
t_version
    print 'twistw (the Twisted Windows runner) %s' % copyright.version
AttributeError: _Printer instance has no attribute 'version'

D:\>
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="teratorn's avatar" src="https://avatars.githubusercontent.com/u/154069?s=50" width="50" height="50">](https://github.com/teratorn)|@teratorn commented|
|-|-|

```
#!html
<pre>
Pavel Pergamenshchik fixed this in svn.
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
