### ISSUE TITLE
twisted.python.rebuild fails if python 2.4's decimal module is imported

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10622]
|<img alt="marienz's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| marienz reported|
|-|-|
|Trac ID|trac#921|
|Type|defect|
|Created|2005-03-15 02:55:11Z|

<details><summary>Searchable metadata</summary>

```
trac-id__921 921
type__defect defect
reporter__marienz marienz
priority__high high
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__ 
keywords__ 
time__1110855311000000 1110855311000000
changetime__1112363461000000 1112363461000000
version__ 
owner__ 
cc__jknight cc__hypatia cc__marienz
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="marienz's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|marienz commented|
|-|-|

```
#!html
<pre>
>>> import decimal
>>> hash(decimal.NaN)

raises decimal.InvalidOperation. This seems to be causing rebuild to fail:

>>> import decimal
>>> from twisted.python.rebuild import rebuild
>>> import twisted
>>> rebuild(twisted)
Traceback (most recent call last):
  File "&lt;stdin>", line 1, in ?
  File "/usr/lib/python2.4/site-packages/twisted/python/rebuild.py", line 239,
in rebuild
    hash(v)
  File "/usr/lib/python2.4/decimal.py", line 720, in __hash__
    i = int(self)
  File "/usr/lib/python2.4/decimal.py", line 1410, in __int__
    return context._raise_error(InvalidContext)
  File "/usr/lib/python2.4/decimal.py", line 2215, in _raise_error
    raise error, explanation
decimal.InvalidOperation
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="jyknight's avatar" src="https://avatars.githubusercontent.com/u/873903?s=50" width="50" height="50">](https://github.com/jyknight)|@jyknight commented|
|-|-|

```
#!html
<pre>
Please report to Python bugtracker, this looks like a bug in the decimal 
module, not in twisted.
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="puzzlement's avatar" src="https://avatars.githubusercontent.com/u/94942?s=50" width="50" height="50">](https://github.com/puzzlement)|@puzzlement commented|
|-|-|

```
#!html
<pre>
Closing bug, please re-open if later evidence reveals that this is a Twisted bug
rather than a Python bug.
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
