### ISSUE TITLE
AttributeError: 'WSGIHandler' object has no attribute 'stopProducing'

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10663]
|<img alt="srichter's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| srichter reported|
|-|-|
|Trac ID|trac#987|
|Type|defect|
|Created|2005-04-17 17:45:42Z|

<details><summary>Searchable metadata</summary>

```
trac-id__987 987
type__defect defect
reporter__srichter srichter
priority__high high
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__ 
keywords__ 
time__1113759942000000 1113759942000000
changetime__1113867014000000 1113867014000000
version__ 
owner__ 
cc__jknight cc__srichter
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="srichter's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|srichter commented|
|-|-|

```
#!html
<pre>
Another traceback from Zope 3. Note that this one might be due to an unhandled 
exception on Zope's side, but I think it is still something that should be 
fixed here: 
   
Traceback (most recent call last):    
Failure: twisted.internet.error.ConnectionLost: Connection to the other side    
was lost in a non-clean fashion.    
Traceback (most recent call last):    
  File "/opt/zope/Zope3/Zope3-Twisted/src/zope/app/server/main.py", line 75,    
in main    
    reactor.run()    
  File "/opt/zope/Zope3/Zope3-Twisted/src/twisted/internet/posixbase.py", line    
205, in run    
    self.mainLoop()    
  File "/opt/zope/Zope3/Zope3-Twisted/src/twisted/internet/posixbase.py", line    
216, in mainLoop    
    self.doIteration(t)    
  File "/opt/zope/Zope3/Zope3-Twisted/src/twisted/internet/selectreactor.py",    
line 133, in doSelect    
    _logrun(selectable, _drdw, selectable, method, dict)    
--- &lt;exception caught here> ---    
  File "/opt/zope/Zope3/Zope3-Twisted/src/twisted/python/log.py", line 56, in    
callWithLogger    
    return callWithContext({"system": lp}, func, *args, **kw)    
  File "/opt/zope/Zope3/Zope3-Twisted/src/twisted/python/log.py", line 41, in    
callWithContext    
    return context.call({ILogContext: newCtx}, func, *args, **kw)    
  File "/opt/zope/Zope3/Zope3-Twisted/src/twisted/python/context.py", line 52,    
in callWithContext    
    return self.currentContext().callWithContext(ctx, func, *args, **kw)    
  File "/opt/zope/Zope3/Zope3-Twisted/src/twisted/python/context.py", line 31,    
in callWithContext    
    return func(*args,**kw)    
  File "/opt/zope/Zope3/Zope3-Twisted/src/twisted/internet/selectreactor.py",    
line 149, in _doReadOrWrite    
    self._disconnectSelectable(selectable, why, method=="doRead")    
  File "/opt/zope/Zope3/Zope3-Twisted/src/twisted/internet/posixbase.py", line    
240, in _disconnectSelectable    
    selectable.connectionLost(f)    
  File "/opt/zope/Zope3/Zope3-Twisted/src/twisted/internet/tcp.py", line 396,    
in connectionLost    
    abstract.FileDescriptor.connectionLost(self, reason)    
  File "/opt/zope/Zope3/Zope3-Twisted/src/twisted/internet/abstract.py", line    
67, in connectionLost    
    self.producer.stopProducing()    
  File "/opt/zope/Zope3/Zope3-Twisted/src/twisted/web2/stream.py", line 774,    
in stopProducing    
    self.stream.close()    
  File "/opt/zope/Zope3/Zope3-Twisted/src/twisted/web2/stream.py", line 643,    
in close    
    self.producer.stopProducing()    
exceptions.AttributeError: 'WSGIHandler' object has no attribute    
'stopProducing'
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="jyknight's avatar" src="https://avatars.githubusercontent.com/u/873903?s=50" width="50" height="50">](https://github.com/jyknight)|@jyknight commented|
|-|-|

```
#!html
<pre>
Resolved by r13590 and r13605.
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
