### ISSUE TITLE
AttributeError: HTTPChannelRequest instance has no attribute 'transport'

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10662]
|<img alt="srichter's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| srichter reported|
|-|-|
|Trac ID|trac#985|
|Type|defect|
|Created|2005-04-17 17:39:09Z|

<details><summary>Searchable metadata</summary>

```
trac-id__985 985
type__defect defect
reporter__srichter srichter
priority__high high
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__web web
keywords__ 
time__1113759549000000 1113759549000000
changetime__1113866877000000 1113866877000000
version__ 
owner__ 
cc__jknight cc__srichter
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="srichter's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|srichter commented|
|-|-|

```
#!html
<pre>
This is an exception I get. 
 
Unhandled error in Deferred: 
Traceback (most recent call last): 
  File "/opt/zope/Zope3/Zope3-Twisted/src/twisted/internet/base.py", line 509, 
in runUntilCurrent 
    f(*a, **kw) 
  File "/opt/zope/Zope3/Zope3-Twisted/src/twisted/web2/stream.py", line 679, 
in finish 
    deferred.callback(None) 
  File "/opt/zope/Zope3/Zope3-Twisted/src/twisted/internet/defer.py", line 
254, in callback 
    self._startRunCallbacks(result) 
  File "/opt/zope/Zope3/Zope3-Twisted/src/twisted/internet/defer.py", line 
315, in _startRunCallbacks 
    self._runCallbacks() 
--- &lt;exception caught here> --- 
  File "/opt/zope/Zope3/Zope3-Twisted/src/twisted/internet/defer.py", line 
328, in _runCallbacks 
    self.result = callback(self.result, *args, **kw) 
  File "/opt/zope/Zope3/Zope3-Twisted/src/twisted/web2/stream.py", line 745, 
in _doWrite 
    self.consumer.unregisterProducer() 
  File "/opt/zope/Zope3/Zope3-Twisted/src/twisted/web2/http.py", line 818, in 
unregisterProducer 
    self.transport.unregisterProducer() 
exceptions.AttributeError: HTTPChannelRequest instance has no attribute 
'transport'
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="jyknight's avatar" src="https://avatars.githubusercontent.com/u/873903?s=50" width="50" height="50">](https://github.com/jyknight)|@jyknight commented|
|-|-|

```
#!html
<pre>
Hm, it looks like connection closing down is misbehaving in some 
circumstance. I'll add some tests for aborting in various ways, but it 
might help if you knew exactly when this (and the others) were raised.
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="srichter's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|srichter commented|
|-|-|

```
#!html
<pre>
I cannot really tell you more, because I am just dealing with the WSGI  
interface you provide to me. You have to be a little bit more specific on what  
you want me to do. Of course, I could get the integration code committed to 
our repository and you could check it out.
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="jyknight's avatar" src="https://avatars.githubusercontent.com/u/873903?s=50" width="50" height="50">](https://github.com/jyknight)|@jyknight commented|
|-|-|

```
#!html
<pre>
Reportedly resolved by r13604.
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
