### ISSUE TITLE
win32 build instructions incorrect

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10681]
|<img alt="justinj's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| justinj reported|
|-|-|
|Trac ID|trac#1017|
|Type|defect|
|Created|2005-05-05 21:34:28Z|

Attachments:

* [aap1.log](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/4dd/4dd260501dec55caaf354185b0aa99c8e05c045a/832e79c3a3679a645f8356fd76dd5b8ad8bd1598.log) (167348 bytes) - added by justinj on 2005-05-05 22:47:14Z - 
* [aapwin_patch.txt](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/4dd/4dd260501dec55caaf354185b0aa99c8e05c045a/26be106b1de122963dc91443db018bfe78f0e707.txt) (1018 bytes) - added by justinj on 2005-05-17 00:29:58Z - 

<details><summary>Searchable metadata</summary>

```
trac-id__1017 1017
type__defect defect
reporter__justinj justinj
priority__high high
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__ 
keywords__ 
time__1115328868000000 1115328868000000
changetime__1117321714000000 1117321714000000
version__ 
owner__ 
cc__moonfallen cc__justinj
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="justinj's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|justinj commented|
|-|-|

```
#!html
<pre>
This may not all be Twisted's fault, but I wanted to document the problems in 
one place and hopefully resolve them.

I followed all of the instructions in win32\README.win32 in the OFFICIAL 
section.  Everything installed successfully, so I proceeded to run the aap 
command.

C:\Twisted>aap -f win32/build.aap
python: can't open file 'C:\WINNT\C:\Program': [Errno 22] Invalid argument

From this I noticed that C:\winnt\aap.bat is incorrect.  It has C:\Program 
Files\aap\Exec\aap.bat hardcoded in it, with %AAPDIR% tacked on front, which 
doesn't make any sense.  The aap.bat in C:\Program Files\aap\Exec looked 
correct though, but required that you run it from that directory.  So I deleted 
c:\winnt\aap.bat and modified my path to include C:\Program Files\aap\Exec.  
Then I tried again and got the following error.

C:\Twisted>aap -f win32/build.aap
File not found - '*.c'
Aap: Error in recipe "c:/twisted/main.aap" line 80: :attr command requires a 
file argument
Aap: More info in the logfile: C:\Twisted\win32\AAPDIR\log

The output from the log file is as follows.

extra:	Reading recipe "build.aap"
extra:	Finished reading recipe "build.aap"
depend:	Adding default dependency for "clean"
depend:	Adding default dependency for "cleanmore"
depend:	Building the "all" target
depend:	1 - updating target "all"
depend:	2 - Using dependency "all : ../main.aap"
depend:	3 - updating target "..\main.aap"
depend:	4 - Using dependency "../main.aap : main.aap"
depend:	5 - updating target "main.aap"
depend:	5 - Target has no build commands and exists: "main.aap"
depend:	3 - Target "..\main.aap" is up-to-date
depend:	1 - Updating "all" from "..\main.aap": virtual target
extra:	Executing recipe "../main.aap"
changedir:	Entering directory `C:\Twisted'
extra:	Reading recipe "C:\Program Files\aap\Exec\default.aap"
log:	Checking for MingW
log:	No mingw compiler found
extra:	Finished reading recipe "C:\Program Files\aap\Exec\default.aap"
extra:	Reading recipe "main.aap"
error:	Error in recipe "c:/twisted/main.aap" line 80: :attr command requires a 
file argument

I installed mingw via cygwin and as a standalone install and am not sure why 
the build script can't find it.  Then I thought maybe I was supposed to be 
running the aap command from within a cygwin shell, but got the following error.

$ aap -f win32/build.aap
bash: aap: command not found

So I tried using a full path.

$ "/cygdrive/c/program files/aap/exec/aap.bat" -f win32/build.aap
Aap: c:\MinGW\bin\mingw32-gcc.EXE --version
Aap: c:\MinGW\bin\mingw32-gcc.EXE --version
Aap: Error in recipe "c:/twisted/main.aap" line 6: ImportError: No module named 
winreg

Aap: More info in the logfile: c:\Twisted\win32\AAPDIR\log

Which of course makes sense, since I didn't install the required modules into 
cygwin's Python.  Should I be building from cygwin, or from a DOS prompt?

I uninstalled the standalone mingw so it is now only installed as a part of 
cygwin.  Then I modified my path at a DOS prompt to include c:\cygwin\bin and 
tried again.

C:\Twisted>set PATH=%PATH%;C:\cygwin\bin
C:\Twisted>aap -f win32/build.aap
Aap: C:\cygwin\bin\gcc.EXE --version
Aap: C:\cygwin\bin\gcc.EXE --version
File not found - '*.c'
Aap: Error in recipe "c:/twisted/main.aap" lin
e 80: :attr command requires a file argument
Aap: More info in the logfile: C:\Twisted\win32\AAPDIR\log

The contents of the log file...

extra:	Reading recipe "build.aap"
extra:	Finished reading recipe "build.aap"
depend:	Adding default dependency for "clean"
depend:	Adding default dependency for "cleanmore"
depend:	Building the "all" target
depend:	1 - updating target "all"
depend:	2 - Using dependency "all : ../main.aap"
depend:	3 - updating target "..\main.aap"
depend:	4 - Using dependency "../main.aap : main.aap"
depend:	5 - updating target "main.aap"
depend:	5 - Target has no build commands and exists: "main.aap"
depend:	3 - Target "..\main.aap" is up-to-date
depend:	1 - Updating "all" from "..\main.aap": virtual target
extra:	Executing recipe "../main.aap"
changedir:	Entering directory `C:\Twisted'
extra:	Reading recipe "C:\Program Files\aap\Exec\default.aap"
log:	Checking for MingW
log:	Guessing MingW prefix as ''
system:	C:\cygwin\bin\gcc.EXE --version
log:	C:\cygwin\bin\gcc.EXE doesn't look like MingW compiler
log:	version line: gcc (GCC) 3.3.3 (cygwin special)
extra:	Finished reading recipe "C:\Program Files\aap\Exec\default.aap"
extra:	Reading recipe "main.aap"
error:	Error in recipe "c:/twisted/main.aap" line 80: :attr command requires a 
file argument

I'd like to figure out all of the issues and then hopefully clean up this 
process.  It is too complicated at the moment, and incorrect unless I'm missing 
something obvious.
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="justinj's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|justinj commented|
|-|-|

```
#!html
<pre>
Tried reinstalling mingw standalone and it liked that compiler, but failed 
again because one of the .aap files relies on the find command from cygwin.  
Tried changing path to include c:\mingw\bin and c:\cygwin\bin at the beginning 
of the path, so we get cygwin's find before the default windows find.  Then I 
got the following error, which ocurred because the scripts chose my python23 
installation instead of python24.  Only python24 is in the path.

C:\Twisted>aap -f win32/build.aap
Aap: c:\mingw\bin\mingw32-gcc.EXE --version
Aap: c:\mingw\bin\mingw32-gcc.EXE --version
Aap: C:\Python23\python.exe setup.py all -q build --compiler=mingw32 install --r
oot=win32dist
Traceback (most recent call last):
  File "twisted/topfiles/setup.py", line 20, in ?
    from twisted import copyright
  File ".\twisted\__init__.py", line 21, in ?
    raise ImportError, "you need zope.interface installed (http://zope.org/Produ
cts/ZopeInterface/)"
ImportError: you need zope.interface installed (http://zope.org/Products/ZopeInt
erface/)
Error: Subprocess exited with result 1 for project core
Aap: Error in recipe "c:/twisted/main.aap" line 96: Shell command returned 1
Aap: More info in the logfile: C:\Twisted\win32\AAPDIR\log
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="justinj's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|justinj commented|
|-|-|

```
#!html
<pre>
After uninstalling Python2.3 it can't find Python at all.

C:\Twisted>aap -f win32/build.aap
Aap: c:\mingw\bin\mingw32-gcc.EXE --version
Aap: c:\mingw\bin\mingw32-gcc.EXE --version
Aap: C:\pythonxx\python.exe setup.py all -q build --compiler=mingw32 install --r
oot=win32dist
The system cannot find the path specified.
Aap: Error in recipe "c:/twisted/main.aap" line 96: Shell command returned 1
Aap: More info in the logfile: C:\Twisted\win32\AAPDIR\log
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="justinj's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|justinj commented|
|-|-|

```
#!html
<pre>
Attached aap1.log, which contains the contents of win32\AAPDIR\log after 
running 'aap -f win32/build.aap' from a DOS prompt with cygwin and mingw 
installed and at the front of PATH, and with only Python2.4 installed.
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="moonfallen's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|moonfallen commented|
|-|-|

```
#!html
<pre>
OK, so we identified 3 points of un-clarity:

1. You must have the right Python interpreters installed.  Do not install
Cygwin's python package.
2. After installing aap, you need to add it to PATH, and run "aap.bat" (not "aap").
3. You must run the build command from a Cygwin shell prompt.

These will be fixed in the README.
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="justinj's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|justinj commented|
|-|-|

```
#!html
<pre>
Another problem I found is that the .profile in my home directory from a 
previous install of cygwin had path info hardcoded in it.  That is why I 
couldn't get it to recognize python2.4, apparently.

So as it stands, I have cygwin installed without python, aap is in my path, and 
can be invoked as aap.bat, mingw standalone install is installed and in my path 
(since the aap scripts were puking about the cygwin version) and I'm still 
getting the following error.

$ aap.bat -f win32/build.aap
Aap: c:\mingw\bin\mingw32-gcc.EXE --version
Aap: c:\mingw\bin\mingw32-gcc.EXE --version
Aap: C:\pythonxx\python.exe setup.py all -q build --compiler=mingw32 install --r
oot=win32dist
The system cannot find the path specified.
Aap: Error in recipe "c:/twisted/main.aap" line 96: Shell command returned 1
Aap: More info in the logfile: c:\Twisted\win32\AAPDIR\log

The log file is similar to the one attached (aap1.log).  I also tried removing 
mingw from my path so it would be entirely cygwin, but got similar results.  So 
I still can't get this built.
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="moonfallen's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|moonfallen commented|
|-|-|

```
#!html
<pre>
This problem has nothing to do with mingw, the file it can't find is
C:\pythonxx\python.exe.  You only get that if there's a problem with your
registry, i.e. your pythons can't be found there.

I don't know what would cause that, but un-installing all Pythons and reinstalling
Python2.4 from the native msi installer sounds like a good start.

I'm resolving this as "cbb" with r13719.
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="justinj's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|justinj commented|
|-|-|

```
#!html
<pre>
Uninstalling and reinstalling didn't resolve it.  However, if I modify 
build.aap to remove Python2.3 from the list of Python versions to try, it works 
successfully.  Have you ever tried this script without Python2.3 installed?  If 
that is the problem, and it appears to be from my end, then the docs should be 
updated to indicate that you must have both Python2.3 and Python2.4 installed 
in order for it to work.  Otherwise the script should be smart enough to only 
build for the version installed.
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="justinj's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|justinj commented|
|-|-|

```
#!html
<pre>
Now I get a new problem.  Have you had problems like the one below if Inno 
Setup 4 is installed to a directory with spaces (like the default directory)?

$ aap.bat -f win32/build.aap
Aap: C:\cygwin\bin\gcc.EXE --version
Aap: C:\cygwin\bin\gcc.EXE --version
Aap: C:\Python24\\python.exe setup.py all -q build --compiler=mingw32 install --
root=win32dist
conftest.c:1:21: rpc/rpc.h: No such file or directory
Checking if C extensions can be compiled, don't be alarmed if a few compile erro
rs are printed.

Aap: "C:\Program Files\Inno Setup 4\ISCC.exe" py2.4-nodocs.iss
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
Aap: Error in recipe "c:/twisted/main.aap" line 110: Shell command returned 1
Aap: More info in the logfile: c:\Twisted\win32\AAPDIR\log
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="justinj's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|justinj commented|
|-|-|

```
#!html
<pre>
It looks like the ISCC problem is because aapwin.py hardcodes Inno Setup 4 in 
it.  I have Inno Setup 5 installed.  The readme says version 4.0.8 or above is 
required, which includes 5.  The instructions should be updated or aapwin.py 
should be updated to work with later versions of Inno Setup.
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="justinj's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|justinj commented|
|-|-|

```
#!html
<pre>
I am restating all the problems I've found, since they aren't all listed clearly
below.

1) aapwin.py has a requirement of Inno Setup 4 hardcoded into it.  The attached
patch changes this so it looks through a list of support versions (currently 4
and 5) until it finds one installed.

2) After I installed aap I had to first remove C:\winnt\aap.bat because its
contents were messed up, and then modify my path to include c:\Program
Files\aap\Exec.  Also had to remove .profile from my home directory (placed
their by cygwin) so cygwin would pick up the right path.

3) The file must be run as aap.bat and not just aap.

4) Both Python 2.3 and Python 2.4 must be installed or the script will die.

5) Cygwin Python cannot be installed.

6) ZopeInteface-3.0.1.tgz must be downloaded and sitting in the root directory
before building.
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="moonfallen's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|moonfallen commented|
|-|-|

```
#!html
<pre>
Fixed #1 - r13848.  Will be fixing most if not all of the others on my way to
2.0.1 release.
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="moonfallen's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|moonfallen commented|
|-|-|

```
#!html
<pre>
Added a Troubleshooting section and more detail to the requirements.  Also added
maintainer-notes.txt.

r13856
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
