### ISSUE TITLE
extra reference needed to show main window when using qtreactor

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10697]
|<img alt="insanekane's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| insanekane reported|
|-|-|
|Trac ID|trac#1041|
|Type|defect|
|Created|2005-05-17 02:57:23Z|

Attachments:

* [another_test.py](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/8a8/8a8ec485492bb9442e4988518bbf5b62ed8501a1/85e8d45e1f55efc1a63cd137df7a0167e9150331.py) (747 bytes) - added by insanekane on 2005-05-17 02:57:23Z - 

<details><summary>Searchable metadata</summary>

```
trac-id__1041 1041
type__defect defect
reporter__insanekane insanekane
priority__low low
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__ 
component__core core
keywords__ 
time__1116298643000000 1116298643000000
changetime__1326973096000000 1326973096000000
version__ 
owner__ 
cc__exarkun cc__itamarst cc__insanekane cc__thijs
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="insanekane's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|insanekane commented|
|-|-|

```
#!html
<pre>
calling qApp.setMainWidget(mW) should be sufficient. I am not entirely sure 
that this is a twisted problem, but qApp.setMainWidget was sufficient when the 
app was not using twisted.
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_2"></a>|@thijstriemstra commented|
|-|-|

Why does this have a high priority? Is it still relevant?

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_3"></a>|@exarkun commented|
|-|-|

I guess it's a bug in qtreactor.  It probably isn't really high priority.  It might be nice if it got fixed someday perhaps.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_5"></a>|@thijstriemstra commented|
|-|-|

See [#3977](https://github.com/twisted/twisted/issues/3977) for qtreactor re-integration, with 12.0 trunk this demo prints:

```
Traceback (most recent call last):
  File "another_test.py", line 20, in <module>
    from twisted.internet import qtreactor
  File "/home/thijs/workspaces/opensource/twisted-trunk/twisted/internet/qtreactor.py", line 12, in <module>
    raise ImportError(errorMessage)
ImportError: qtreactor is no longer a part of Twisted due to licensing issues. Please see http://twistedmatrix.com/trac/wiki/QTReactor for details.
```
