### ISSUE TITLE
internet.py: self._port.stopListening() should check that self._port exists

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10716]
|<img alt="loic's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| loic reported|
|-|-|
|Trac ID|trac#1088|
|Type|defect|
|Created|2005-06-20 13:35:28Z|

<details><summary>Searchable metadata</summary>

```
trac-id__1088 1088
type__defect defect
reporter__loic loic
priority__high high
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__ 
keywords__ 
time__1119274528000000 1119274528000000
changetime__1120118208000000 1120118208000000
version__ 
owner__ 
cc__exarkun cc__loic
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="loic's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|loic commented|
|-|-|

```
#!html
<pre>
From the comment in the file, this seems to be a well known issue.
However, when searching the bug database for entries with a title containing
"_port", many results are returned, most of which do not contain the _port
string. I figured it would be best to have a duplicate rather than no entry at all.

I have triggered this by running a server, launching hundreds of connections and
killing the server before they were all properly established. I used twisted-1.3
but the code in twisted-2.0 is not modified in that respect therefore my guess
is that it would also happen with twisted-2.0.

Here is the stack trace:

Unhandled error in Deferred:
Traceback (most recent call last):
  File "/usr/lib/python2.3/site-packages/twisted/internet/base.py", line 423, in
runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/usr/lib/python2.3/site-packages/twisted/internet/base.py", line 257, in
stop
    self.fireSystemEvent("shutdown")
  File "/usr/lib/python2.3/site-packages/twisted/internet/base.py", line 307, in
fireSystemEvent
    d = callable(*args, **kw)
  File "/usr/lib/python2.3/site-packages/twisted/application/service.py", line
218, in stopService
    l.append(defer.maybeDeferred(service.stopService))
--- &lt;exception caught here> ---
  File "/usr/lib/python2.3/site-packages/twisted/internet/defer.py", line 129,
in maybeDeferred
    result = f(*args, **kw)
  File "/usr/lib/python2.3/site-packages/twisted/application/internet.py", line
68, in stopService
    d = self._port.stopListening()
exceptions.AttributeError: TCPServer instance has no attribute '_port'
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun commented|
|-|-|

```
#!html
<pre>
Resolved by r14058
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
