### ISSUE TITLE
tcp port __repr__ fix

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10814]
|<img alt="bruce's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| bruce reported|
|-|-|
|Trac ID|trac#1060|
|Type|defect|
|Created|2005-05-28 06:33:11Z|

<details><summary>Searchable metadata</summary>

```
trac-id__1060 1060
type__defect defect
reporter__bruce bruce
priority__high high
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__ 
keywords__ 
time__1117261991000000 1117261991000000
changetime__1117509032000000 1117509032000000
version__ 
owner__ 
cc__exarkun cc__bruce
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="bruce's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|bruce commented|
|-|-|

```
#!html
<pre>
When I'm bad and don't clean everything up at shutdown nicely, I sometimes get this:

2005/05/26 09:13 MDT [-] WARNING: serializing ephemeral
&lt;twisted.spread.pb.RemoteReference instance at 0x2a99144e60>
2005/05/26 09:13 MDT [-] Traceback (most recent call last):
      File "/home/bruce/nobackup/t/Twisted/twisted/internet/defer.py", line 254,
in callback
        self._startRunCallbacks(result)
      File "/home/bruce/nobackup/t/Twisted/twisted/internet/defer.py", line 317,
in _startRunCallbacks
        self._runCallbacks()
      File "/home/bruce/nobackup/t/Twisted/twisted/internet/defer.py", line 330,
in _runCallbacks
        self.result = callback(self.result, *args, **kw)
      File "/home/bruce/nobackup/t/Twisted/twisted/internet/base.py", line 383,
in _cbContinueSystemEvent
        self._continueSystemEvent(eventType)
    --- &lt;exception caught here> ---
      File "/home/bruce/nobackup/t/Twisted/twisted/internet/base.py", line 391,
in _continueSystemEvent
        callable(*args, **kw)
      File "/home/bruce/nobackup/t/Twisted/twisted/persisted/sob.py", line 125,
in save
        self._saveTemp(filename, passphrase, dumpFunc)
      File "/home/bruce/nobackup/t/Twisted/twisted/persisted/sob.py", line 93,
in _saveTemp
        dumpFunc(self.original, f)
      File "/home/bruce/nobackup/t/Twisted/twisted/persisted/sob.py", line 109,
in dumpFunc
        pickle.dump(obj, file, 1)
      File "/home/bruce/nobackup/t/Twisted/twisted/persisted/styles.py", line
129, in __getstate__
        log.msg( " referred to by %s" % (r,))
      File "/home/bruce/nobackup/t/Twisted/twisted/internet/tcp.py", line 687,
in __repr__
        return "&lt;%s of %s on %s>" % (self.__class__, self.factory.__class__,
      File "/home/bruce/nobackup/t/Twisted/twisted/internet/tcp.py", line 811,
in getHost
        return address.IPv4Address('TCP', *(self.socket.getsockname() + ('INET',)))
    exceptions.AttributeError: Port instance has no attribute 'socket'

which can be readily fixed by:

Index: twisted/internet/tcp.py
===================================================================
--- twisted/internet/tcp.py     (revision 13543)
+++ twisted/internet/tcp.py     (working copy)
@@ -684,8 +684,13 @@
         self.interface = interface

     def __repr__(self):
-        return "&lt;%s of %s on %s>" % (self.__class__, self.factory.__class__,
-                                     self.getHost().port)
+        if hasattr(self, 'socket'):
+            return "&lt;%s of %s on %s>" % (self.__class__, self.factory.__class__,
+                                         self.getHost().port)
+        else:
+            return "&lt;%s of %s on unconnected %s>" % (self.__class__,
+ self.factory.__class__,
+                                                     self.port)

     def createInternetSocket(self):
         s = base.BasePort.createInternetSocket(self)
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun commented|
|-|-|

```
#!html
<pre>
Resolved by r13871
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
