### ISSUE TITLE
twistd.pid vs. chdir

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10840]
|<img alt="bruce's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| bruce reported|
|-|-|
|Trac ID|trac#1065|
|Type|enhancement|
|Created|2005-05-28 07:34:56Z|

<details><summary>Searchable metadata</summary>

```
trac-id__1065 1065
type__enhancement enhancement
reporter__bruce bruce
priority__low low
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__ 
keywords__ 
time__1117265696000000 1117265696000000
changetime__1117526719000000 1117526719000000
version__ 
owner__ 
cc__exarkun cc__bruce
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="bruce's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|bruce commented|
|-|-|

```
#!html
<pre>
If you're running twistd and you do a chdir() while the app is running, then
twistd fails to delete twistd.pid at exit.

This results in this sort of traceback:

2005/05/27 15:49 MDT [-] Failed to unlink PID file:
2005/05/27 15:49 MDT [-] Traceback (most recent call last):
      File "/usr/local/bin/twistd", line 32, in ?
        run()
      File "/home/bruce/nobackup/t/Twisted/twisted/scripts/twistd.py", line 195,
in run
        app.run(runApp, ServerOptions)
      File "/home/bruce/nobackup/t/Twisted/twisted/application/app.py", line
271, in run
        runApp(config)
      File "/home/bruce/nobackup/t/Twisted/twisted/scripts/twistd.py", line 188,
in runApp
        removePID(config['pidfile'])
    --- &lt;exception caught here> ---
      File "/home/bruce/nobackup/t/Twisted/twisted/scripts/twistd.py", line 81,
in removePID
        os.unlink(pidfile)
    exceptions.OSError: [Errno 2] No such file or directory: 'twistd.pid'
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun commented|
|-|-|

```
#!html
<pre>
Resolved by r13878
</pre>
```
