### ISSUE TITLE
UnboundLocalError in twisted.words.tap

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10869]
|<img alt="mike's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| mike reported|
|-|-|
|Trac ID|trac#1283|
|Type|defect|
|Created|2005-10-24 22:25:48Z|

<details><summary>Searchable metadata</summary>

```
trac-id__1283 1283
type__defect defect
reporter__mike mike
priority__high high
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__words words
keywords__backport backport
time__1130192748000000 1130192748000000
changetime__1130329714000000 1130329714000000
version__ 
owner__ 
cc__exarkun cc__mike
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="mike's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|mike commented|
|-|-|

```
#!html
<pre>
--passwd option is broken --   
   
> mktap words --passwd=/etc/passwd   
 Traceback (most recent call last):  
  File "/usr/local/bin/mktap", line 19, in ?  
    run()  
  File "/usr/local/lib/python2.4/site-packages/twisted/scripts/mktap.py", line  
203, in run  
    ser = makeService(plg, options.subCommand, options.subOptions)  
  File "/usr/local/lib/python2.4/site-packages/twisted/scripts/mktap.py", line  
87, in makeService  
    ser = mod.makeService(options)  
  File "/usr/local/lib/python2.4/site-packages/twisted/words/tap.py", line 50,  
in makeService  
    checkers = [checkers.FilePasswordDB(config['passwd'], cache=True)]  
UnboundLocalError: local variable 'checkers' referenced before assignment  
  
Possible fix:  
  
*** tap.py.orig Mon Oct 24 12:24:25 2005 
--- tap.py      Mon Oct 24 12:16:22 2005 
*************** 
*** 13,19 **** 
  from twisted import plugin 
   
  from twisted.words import iwords, service 
! from twisted.cred import checkers, portal 
   
  class Options(usage.Options): 
      optParameters = [ 
--- 13,19 ---- 
  from twisted import plugin 
   
  from twisted.words import iwords, service 
! from twisted.cred import checkers as checkers_module, portal 
   
  class Options(usage.Options): 
      optParameters = [ 
*************** 
*** 47,53 **** 
   
  def makeService(config): 
      if config['passwd']: 
!         checkers = [checkers.FilePasswordDB(config['passwd'], cache=True)] 
      elif config['checkers']: 
          checkers = config['checkers'] 
      else: 
--- 47,53 ---- 
   
  def makeService(config): 
      if config['passwd']: 
!         checkers = [checkers_module.FilePasswordDB(config['passwd'], 
cache=True)] 
      elif config['checkers']: 
          checkers = config['checkers'] 
      else:
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun commented|
|-|-|

```
#!html
<pre>
Resolved by r14919, thanks
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
