### ISSUE TITLE
socket.error: (53, 'Software caused connection abort')

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10865]
|[<img alt="ghazel's avatar" src="https://avatars.githubusercontent.com/u/31402?s=50" width="50" height="50">](https://github.com/ghazel)| @ghazel reported|
|-|-|
|Trac ID|trac#1274|
|Type|defect|
|Created|2005-10-13 10:09:57Z|

<details><summary>Searchable metadata</summary>

```
trac-id__1274 1274
type__defect defect
reporter__ghazel ghazel
priority__high high
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__invalid invalid
component__conch conch
keywords__ 
time__1129198197000000 1129198197000000
changetime__1132137936000000 1132137936000000
version__ 
owner__ 
cc__teratorn cc__ghazel cc__zectbumo
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="ghazel's avatar" src="https://avatars.githubusercontent.com/u/31402?s=50" width="50" height="50">](https://github.com/ghazel)|@ghazel commented|
|-|-|

```
#!html
<pre>
This traceback happens every so often on FreeBSD (5.4-STABLE), using twisted 
2.1.0

Traceback (most recent call last):
--- &lt;exception caught here> ---
 File "/usr/local/lib/python2.4/site-packages/twisted/internet/tcp.py", line 
760, in doRead

 File "/usr/local/lib/python2.4/site-packages/twisted/internet/tcp.py", line 
753, in doRead

 File "/usr/local/lib/python2.4/socket.py", line 169, in accept
   sock, addr = self._sock.accept()
socket.error: (53, 'Software caused connection abort')
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="zectbumo's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|zectbumo commented|
|-|-|

```
#!html
<pre>
Same here running amd64 FreeBSD 5.4-stable twisted 2.0.1

5.4-STABLE FreeBSD 5.4-STABLE #0: Fri Sep  9 14:02:41 PDT 2005 amd64

Twisted installed packages:
py24-twistedCore-2.0.1
py24-twistedNames-0.1.0_1
py24-twistedWeb-0.5.0_1

Traceback (most recent call last):
          File "/usr/local/lib/python2.4/site-packages/twisted/python/log.py",
line 41, in callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File
"/usr/local/lib/python2.4/site-packages/twisted/python/context.py", line 52, in
callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File
"/usr/local/lib/python2.4/site-packages/twisted/python/context.py", line 31, in
callWithContext
            return func(*args,**kw)
          File
"/usr/local/lib/python2.4/site-packages/twisted/internet/selectreactor.py", line
139, in _doReadOrWrite
            why = getattr(selectable, method)()
        --- &lt;exception caught here> ---
          File "/usr/local/lib/python2.4/site-packages/twisted/internet/tcp.py",
line 734, in doRead
            skt, addr = self.socket.accept()
          File "/usr/local/lib/python2.4/socket.py", line 169, in accept
            sock, addr = self._sock.accept()
        socket.error: (53, 'Software caused connection abort')
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="teratorn's avatar" src="https://avatars.githubusercontent.com/u/154069?s=50" width="50" height="50">](https://github.com/teratorn)|@teratorn commented|
|-|-|

```
#!html
<pre>
misc info...
According to sys/sys/errno.h on a FreeBSD 4.11-RELEASE box:

#define ECONNABORTED    53   /* Software caused connection abort */

According to the accept(2) man page:
[ECONNABORTED]     A connection arrived, but it was closed while waiting
                   on the listen queue.
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="teratorn's avatar" src="https://avatars.githubusercontent.com/u/154069?s=50" width="50" height="50">](https://github.com/teratorn)|@teratorn commented|
|-|-|

```
#!html
<pre>
Please provide more specific information regarding the circumstances under which 
these errors occur. Also, if at all possible, please provide code samples that 
reproduce the issue.
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="ghazel's avatar" src="https://avatars.githubusercontent.com/u/31402?s=50" width="50" height="50">](https://github.com/ghazel)|@ghazel commented|
|-|-|

```
#!html
<pre>
There probably is no specific code that will reproduce the problem, unless you 
can manage to write something which will reliably close a connection while it's 
waiting in the listen queue - but that's just a guess.
I don't have any more specific information about how to reproduce it, because 
it seems to happen occasionally no matter what I do.
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="teratorn's avatar" src="https://avatars.githubusercontent.com/u/154069?s=50" width="50" height="50">](https://github.com/teratorn)|@teratorn commented|
|-|-|

```
#!html
<pre>
Well, if the remote end is closing the connection before Twisted has the chance 
to accept() it, then it's not really a bug, per se.

There doesn't seem to be any reliable way to catch this error as the error code, 
in this case 53, doesn't seem to be standard. E.g on Linux:

include/asm-alpha/errno.h:#define ECONNABORTED 53 /* Software caused connection 
abort */
include/asm-generic/errno.h:#define ECONNABORTED 103 /* Software caused 
connection abort */
include/asm-mips/errno.h:#define ECONNABORTED 130 /* Software caused connection 
abort */

What do you think?
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="ghazel's avatar" src="https://avatars.githubusercontent.com/u/31402?s=50" width="50" height="50">](https://github.com/ghazel)|@ghazel commented|
|-|-|

```
#!html
<pre>
what's wrong with: 
    from errno import ECONNABORTED
then:
elif e.args[0] == ECONNABORTED:
?
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="teratorn's avatar" src="https://avatars.githubusercontent.com/u/154069?s=50" width="50" height="50">](https://github.com/teratorn)|@teratorn commented|
|-|-|

```
#!html
<pre>
OK, apart from discussing how to detect this condition, what are you expecting 
Twisted to do with it? Is this actually a problem in your app, or just log spam?

As far as detecting the condition, yeah, the errno module...
ECONNABORTED is defined on Windows, but I wouldn't bet my life that it is 
actually used or that it means the exact same thing. (Can anyone provide insight 
here?)
Otherwise, another question I have is how to detect this condition under all 
reactors? Maybe this isn't a problem, or maybe it is - I haven't looked in to 
it.
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="ghazel's avatar" src="https://avatars.githubusercontent.com/u/31402?s=50" width="50" height="50">](https://github.com/ghazel)|@ghazel commented|
|-|-|

```
#!html
<pre>
Sorry, I misunderstood the question. This is just log spam - I can't imagine 
why I would need to know about an incoming connection that was never made.

Yes, on windows it is the same thing, except you can get it from "Any function 
that takes a socket as an input parameter".
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="teratorn's avatar" src="https://avatars.githubusercontent.com/u/154069?s=50" width="50" height="50">](https://github.com/teratorn)|@teratorn commented|
|-|-|

```
#!html
<pre>
I think we should continue to yell about aborted connections, by default - it's 
an unusual condition that may indicate an error in the application under 
development, or the 3rd party client that Twisted is talking to, as it were. It 
could also indicate a network reliability issue.

I suggest you ignore these errors in your application. Unfortunately, if you are 
running under twistd, there isn't any good way to modify the default log 
observer yet. Otherwise, you can use the twisted.python.log API to have a look 
at the Failures before logging them.

If you would prefer that twisted caught these errors, as well as they can be 
caught, and emitted a warning, or just plain ignored them, (instead of just 
allowing the traceback) then please write a summary email (with plenty of 
detail) to the mailing list, and we'll see what people think.
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
