### ISSUE TITLE
twisted.web2 problems on Windows.

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10863]
|<img alt="mkerrin's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| mkerrin reported|
|-|-|
|Trac ID|trac#1270|
|Type|defect|
|Created|2005-10-10 22:09:38Z|

<details><summary>Searchable metadata</summary>

```
trac-id__1270 1270
type__defect defect
reporter__mkerrin mkerrin
priority__highest highest
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__web web
keywords__win32 win32
time__1128982178000000 1128982178000000
changetime__1138400398000000 1138400398000000
version__ 
owner__ 
cc__moonfallen cc__jknight cc__dreid cc__mkerrin cc__moof
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="mkerrin's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|mkerrin commented|
|-|-|

```
#!html
<pre>
I am getting reports of Zope3 failing tests on Windows with the following
traceback, because the fcntl module doesn't exist on Windows.

 Traceback (most recent call last):
      File "C:\Code\Zope3\src\zope\testing\doctest.py", line 1256, in __run
        compileflags, 1) in test.globs
      File "&lt;doctest log.txt[14]>", line 1, in ?
        from twisted.web2 import http, http_headers, iweb, channel
      File "C:\Code\Zope3\src\twisted\web2\channel\__init__.py", line 7, in ?
        from twisted.web2.channel.cgi import startCGI
      File "C:\Code\Zope3\src\twisted\web2\channel\cgi.py", line 9, in ?
        from twisted.internet import process, error, interfaces, fdesc
      File "C:\Code\Zope3\src\twisted\internet\process.py", line 34, in ?
        import abstract, fdesc, error
      File "C:\Code\Zope3\src\twisted\internet\fdesc.py", line 15, in ?
        import fcntl
    ImportError: No module named fcntl

This would also say to me that our HTTP server will not start on Windows.
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="moof's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|moof commented|
|-|-|

```
#!html
<pre>
fcntl is not available in windows, except possibly under cygwin.

http://www.python.org/doc/current/lib/module-fcntl.html quite clearly states
it's Unix-only.

There's a bunch of OS-independent locking mechanisms in the python cookbook, of
greater or lesser utility, and pywin32 and ctypes also give access to windows'
own locking abilities (or lack of).
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="jyknight's avatar" src="https://avatars.githubusercontent.com/u/873903?s=50" width="50" height="50">](https://github.com/jyknight)|@jyknight commented|
|-|-|

```
#!html
<pre>
Fixed. web2 tets appear to be passing on win32 buildbot now.
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="moonfallen's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|moonfallen commented|
|-|-|

```
#!html
<pre>
Re-opening.  web2.channel.cgi still imports t.i.stdio, which still eventually
imports fcntl, which still doesn't exist on windows.  The buildbot is red at the
moment, and some of the tests are passing, but I didn't see any that failed
because of this import.

This suggests that a proper test doesn't exist yet.  There is no way this code
will work on Windows as-is.
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="moonfallen's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|moonfallen commented|
|-|-|

```
#!html
<pre>
Confirmed.. no test actually imports twisted.web2.channel.cgi.

If we want a failing test for this bug, this is it:

"import twisted.web2.channel.cgi"
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="jyknight's avatar" src="https://avatars.githubusercontent.com/u/873903?s=50" width="50" height="50">](https://github.com/jyknight)|@jyknight commented|
|-|-|

```
#!html
<pre>
Said import is only inside the startCGI function (which is only called if you 
ask to start up web2 _as a cgi_). This function is, as you note, currently not 
tested, and support for running as a CGI cannot possibly work under windows due 
to the lack of stdio protocol support in twisted.

However, this bug was about the entirety of web2 breaking because of a load-time 
dependance upon fcntl. That was fixed, thus this bug was and is resolved. If 
you'd like you can submit an issue about the lack of tests for running as a CGI, 
but that's not this bug. => Re-Resolved.

Furthermore, unlike the comment below states, importing the module on windows 
does succeed. You just cannot call startCGI.
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="moonfallen's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|moonfallen commented|
|-|-|

```
#!html
<pre>
Sorry, you're right of course about the plain import.

The reason I came to this bug is that the one and only demo for web2 calls
startCGI, which makes it seem as if web2 is completely broken to someone who
hasn't used web2 before (e.g. me).  I'll open another bug.
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
