### ISSUE TITLE
trial won't run nevow's unit tests

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10864]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)| @glyph reported|
|-|-|
|Trac ID|trac#1271|
|Type|defect|
|Created|2005-10-11 00:39:59Z|

<details><summary>Searchable metadata</summary>

```
trac-id__1271 1271
type__defect defect
reporter__glyph glyph
priority__highest highest
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__backport backport
time__1128991199000000 1128991199000000
changetime__1129020236000000 1129020236000000
version__ 
owner__ 
cc__glyph cc__radix cc__exarkun cc__jml cc__jknight
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)|@glyph commented|
|-|-|

```
#!html
<pre>
This is manifested because trial does not work around a known bug in zope.interface.

glyph@legion:~/Scratch/Test% trial nevow

/home/glyph/Projects/Nevow/trunk/formless/annotate.py:768:
twisted.python.components.ComponentsDeprecationWarning: Don't get attributes (in
this case, 'getComponent') off Interface, use .queryDescriptionFor() etc. instead

/home/glyph/Projects/Twisted/trunk/twisted/python/components.py:338:
twisted.python.components.ComponentsDeprecationWarning: Don't get attributes (in
this case, '__conform__') off Interface, use .queryDescriptionFor() etc. instead
Traceback (most recent call last):
  File "/home/glyph/Projects/Twisted/trunk/bin/trial", line 24, in ?
    run()
  File "/home/glyph/Projects/Twisted/trunk/twisted/scripts/trial.py", line 526,
in run
    suite = reallyRun(config)
  File "/home/glyph/Projects/Twisted/trunk/twisted/scripts/trial.py", line 496,
in reallyRun
    suite = _getSuite(config, reporter)
  File "/home/glyph/Projects/Twisted/trunk/twisted/scripts/trial.py", line 383,
in _getSuite
    suite.addTest(loader.loadByName(test, recurse))
  File "/home/glyph/Projects/Twisted/trunk/twisted/trial/runner.py", line 479,
in loadByName
    return self.loadAnything(thing, recurse)
  File "/home/glyph/Projects/Twisted/trunk/twisted/trial/runner.py", line 435,
in loadAnything
    return self.loadPackage(thing, recurse)
  File "/home/glyph/Projects/Twisted/trunk/twisted/trial/runner.py", line 392,
in loadPackage
    return self.loadPackageRecursive(package)
  File "/home/glyph/Projects/Twisted/trunk/twisted/trial/runner.py", line 417,
in loadPackageRecursive
    os.path.walk(packageDir, self._packageRecurse, suite)
  File "/usr/lib/python2.4/posixpath.py", line 298, in walk
    walk(name, func, arg)
  File "/usr/lib/python2.4/posixpath.py", line 290, in walk
    func(arg, top, names)
  File "/home/glyph/Projects/Twisted/trunk/twisted/trial/runner.py", line 412,
in _packageRecurse
    suite.addTest(self.loadModule(module))
  File "/home/glyph/Projects/Twisted/trunk/twisted/trial/runner.py", line 353,
in loadModule
    for testClass in self._findTestClasses(module):
  File "/home/glyph/Projects/Twisted/trunk/twisted/trial/runner.py", line 324,
in _findTestClasses
    if ITestCase.implementedBy(val):
  File "/usr/lib/python2.4/site-packages/zope/interface/declarations.py", line
356, in implementedByFallback
    spec.__name__ = (getattr(cls, '__module__', '?') or '?') + \
AttributeError: 'Tag' object has no attribute '__name__'
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)|@glyph commented|
|-|-|

```
#!html
<pre>
Resolved as of 14807.  This has to make it into a release soon, though.
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)|@jml commented|
|-|-|

```
#!html
<pre>
Thanks glyph.  It'd be a great help if I could get a url for the bug in Zope
Interface.


PS. the plan is to change the test to issubclass(test, pyunit.TestCase)
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)|@jml commented|
|-|-|

```
#!html
<pre>
OK. I've searched the Zope bug tracker and there's no mention of this.  I tried
creating a minimal example so I *could* file it, but I can't reproduce this error.  

(Also, I couldn't reproduce this after removing the 'except AttributeError'
clause and running trial on Nevow's subversion tests)

The line referred to in the stack trace has a different number in my
zope.interfaces.  Perhaps we are using different versions?
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)|@glyph commented|
|-|-|

```
#!html
<pre>
Minimal example of ZI bug:

glyph@legion:~% python
Python 2.4.2 (#2, Sep 30 2005, 21:19:01)
[GCC 4.0.2 20050808 (prerelease) (Ubuntu 4.0.1-4ubuntu8)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from zope.interface import Interface
>>> class J(Interface):
...  ''
...
>>> class K(object):
...  def __call__(self):
...   return self
...
>>> J.implementedBy(K())
Traceback (most recent call last):
  File "&lt;stdin>", line 1, in ?
  File "/usr/lib/python2.4/site-packages/zope/interface/declarations.py", line
356, in implementedByFallback
    spec.__name__ = (getattr(cls, '__module__', '?') or '?') + \
AttributeError: 'K' object has no attribute '__name__'
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)|@jml commented|
|-|-|

```
#!html
<pre>
I've posted this to the Zope bug tracker:
http://www.zope.org/Collectors/Zope3-dev/470
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
