### ISSUE TITLE
trial --until-failure is broken

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10860]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#1263|
|Type|defect|
|Created|2005-10-09 10:39:25Z|

<details><summary>Searchable metadata</summary>

```
trac-id__1263 1263
type__defect defect
reporter__exarkun exarkun
priority__high high
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__ 
time__1128854365000000 1128854365000000
changetime__1132131835000000 1132131835000000
version__ 
owner__ 
cc__exarkun cc__jml
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun commented|
|-|-|

```
#!html
<pre>
exarkun@boson:~/Scratch/Test$ trial --until-failure xyz
Test Pass 1
Running 0 tests.

===============================================================================
IMPORT ERROR:

Could not import xyz: 
  File "/home/exarkun/Projects/Twisted/trunk/twisted/trial/runner.py", line 474,
in loadByName
    thing = self.findByName(name)
  File "/home/exarkun/Projects/Twisted/trunk/twisted/trial/runner.py", line 346,
in findByName
    return reflect.namedAny(name)
  File "/home/exarkun/Projects/Twisted/trunk/twisted/python/reflect.py", line
361, in namedAny
    topLevelPackage = __import__(trialname)
exceptions.ValueError: Empty module name

-------------------------------------------------------------------------------
Ran 0 tests in 0.000s

PASSED
Traceback (most recent call last):
  File "/home/exarkun/Projects/Twisted/trunk/bin/trial", line 24, in ?
    run()
  File "/home/exarkun/Projects/Twisted/trunk/twisted/scripts/trial.py", line
525, in run
    suite = reallyRun(config)
  File "/home/exarkun/Projects/Twisted/trunk/twisted/scripts/trial.py", line
506, in reallyRun
    call_until_failure(root.run, suite)
  File "/home/exarkun/Projects/Twisted/trunk/twisted/scripts/trial.py", line
461, in call_until_failure
    while suite.reporter.wasSuccessful():
AttributeError: 'NoneType' object has no attribute 'reporter'
exarkun@boson:~/Scratch/Test$ 


exarkun@boson:~/Scratch/Test$ trial --until-failure
twisted.names.test.test_dns.Encoding.testNULL
Test Pass 1
Running 1 tests.
    Encoding
      testNULL ...                                                         [OK]

-------------------------------------------------------------------------------
Ran 1 tests in 0.030s

PASSED (successes=1)
Traceback (most recent call last):
  File "/home/exarkun/Projects/Twisted/trunk/bin/trial", line 24, in ?
    run()
  File "/home/exarkun/Projects/Twisted/trunk/twisted/scripts/trial.py", line
525, in run
    suite = reallyRun(config)
  File "/home/exarkun/Projects/Twisted/trunk/twisted/scripts/trial.py", line
506, in reallyRun
    call_until_failure(root.run, suite)
  File "/home/exarkun/Projects/Twisted/trunk/twisted/scripts/trial.py", line
461, in call_until_failure
    while suite.reporter.wasSuccessful():
AttributeError: 'NoneType' object has no attribute 'reporter'
exarkun@boson:~/Scratch/Test$
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun commented|
|-|-|

```
#!html
<pre>
That other behavior fixed.  Now just this bad behavior:

exarkun@boson:~$ trial -u
Test Pass 1
Running 0 tests. 

-------------------------------------------------------------------------------
Ran 0 tests in 0.000s

PASSED
Test Pass 2
Running 0 tests.

-------------------------------------------------------------------------------
Ran 0 tests in 0.000s

PASSED
Test Pass 3
Running 0 tests.

-------------------------------------------------------------------------------
Ran 0 tests in 0.000s

PASSED
Test Pass 4
Running 0 tests.

-------------------------------------------------------------------------------
Ran 0 tests in 0.000s

PASSED
Test Pass 5
Running 0 tests.

-------------------------------------------------------------------------------
Ran 0 tests in 0.000s

PASSED
Test Pass 6
.
.
.
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun commented|
|-|-|

```
#!html
<pre>
Another problem is that skips accumulate between runs, and get re-reported after
each run.  That is, if you run 3 tests with -u, and one of them is set to skip,
it will be reported as skipped once after the first run, twice after the second
run, three times after the third run, etc.

Also, test case class names are not included in output for any run but the first.
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun commented|
|-|-|

```
#!html
<pre>
This is a regression, which is why it was classified as urgent.
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)|@jml commented|
|-|-|

```
#!html
<pre>
I believe the sole remaining problem, noted in msg4678, is not a regression.
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun commented|
|-|-|

```
#!html
<pre>
Woops sorry, I thought this ticket included this bug, too:

exarkun@boson:~$ cat test_zam.py
from twisted.trial import unittest

class X(unittest.TestCase):
  def testX(self):
    pass
  testX.todo = "yep"
exarkun@boson:~$ trial -u test_zam.py
Test Pass 1
Running 1 tests.
  test_zam
    X
      testX ...                                                    [SUCCESS!?!]

===============================================================================
[SUCCESS!?!]: test_zam.X.testX

Reason: 'yep'
-------------------------------------------------------------------------------
Ran 1 tests in 0.088s

PASSED (unexpectedSuccesses=1)
Test Pass 2
Running 1 tests.
  test_zam
    X
      testX ...                                                    [SUCCESS!?!]

===============================================================================
[SUCCESS!?!]: test_zam.X.testX

Reason: 'yep'
===============================================================================
[SUCCESS!?!]: test_zam.X.testX

Reason: 'yep'
-------------------------------------------------------------------------------
Ran 2 tests in 0.049s
.
.
.

Each run includes its own results as well as the cumulative results of all
previous runs.
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)|@jml commented|
|-|-|

```
#!html
<pre>
Yeah it did.  But that's fixed, as far as I can tell.  ... ummm... r15134.
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun commented|
|-|-|

```
#!html
<pre>
Cool.
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)|@jml commented|
|-|-|

```
#!html
<pre>
Resolved in r15140
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
