### ISSUE TITLE
trial doesn't run test suite all the way on win32eventreactor

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10894]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#1306|
|Type|defect|
|Created|2005-11-02 10:40:11Z|

<details><summary>Searchable metadata</summary>

```
trac-id__1306 1306
type__defect defect
reporter__exarkun exarkun
priority__highest highest
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__tests tests
time__1130928011000000 1130928011000000
changetime__1131991259000000 1131991259000000
version__ 
owner__ 
cc__exarkun cc__spiv cc__jml
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun commented|
|-|-|

```
#!html
<pre>
All the recent runs end something like:

-------------------------------------------------------------------------------
Ran 1358 tests in 122.313s

FAILED (skips=158, expectedFailures=14, failures=5, errors=13, successes=1167)
Exception in thread win32er.Process.doReadErr pid=1216:
Traceback (most recent call last):
  File "c:\python24\lib\threading.py", line 442, in __bootstrap
    self.run()
  File "c:\python24\lib\threading.py", line 422, in run
    self.__target(*self.__args, **self.__kwargs)
  File
"c:\buildslave\w32\W32-full2.2\Twisted\twisted\internet\win32eventreactor.py",
line 419, in doReadErr
    buffer, bytesToRead, result = win32pipe.PeekNamedPipe(self.hStderrR, 1)
AttributeError: 'Process' object has no attribute 'hStderrR'

Exception in thread win32er.Process.doReadOut pid=896:
Traceback (most recent call last):
  File "c:\python24\lib\threading.py", line 442, in __bootstrap
    self.run()
  File "c:\python24\lib\threading.py", line 422, in run
    self.__target(*self.__args, **self.__kwargs)
  File
"c:\buildslave\w32\W32-full2.2\Twisted\twisted\internet\win32eventreactor.py",
line 400, in doReadOut
    buffer, bytesToRead, result = win32pipe.PeekNamedPipe(self.hStdoutR, 1)
AttributeError: 'Process' object has no attribute 'hStdoutR'

Traceback (most recent call last):
  File "c:\buildslave\w32\W32-full2.2\Twisted\./bin/trial", line 24, in ?
    run()
  File "c:\buildslave\w32\W32-full2.2\Twisted\twisted\scripts\trial.py", line
449, in run
    test_result = reallyRun(config)
  File "c:\buildslave\w32\W32-full2.2\Twisted\twisted\scripts\trial.py", line
437, in reallyRun
    return call_with(do_a_run)
  File "c:\buildslave\w32\W32-full2.2\Twisted\twisted\scripts\trial.py", line
433, in &lt;lambda>
    call_with = lambda func, *args, **kwargs: func(*args, **kwargs)
  File "c:\buildslave\w32\W32-full2.2\Twisted\twisted\scripts\trial.py", line
429, in do_a_run
    return my_runner.run(suite)
  File "c:\buildslave\w32\W32-full2.2\Twisted\twisted\trial\runner.py", line
544, in run
    suite.run(result)
  File "c:\buildslave\w32\W32-full2.2\Twisted\twisted\trial\runner.py", line
175, in run
    TestSuite.run(self, result)
  File "c:\buildslave\w32\W32-full2.2\Twisted\twisted\trial\runner.py", line
119, in run
    test(result)
  File "c:\buildslave\w32\W32-full2.2\Twisted\twisted\trial\runner.py", line
111, in __call__
    return self.run(result)
  File "c:\buildslave\w32\W32-full2.2\Twisted\twisted\trial\runner.py", line
119, in run
    test(result)
  File "c:\buildslave\w32\W32-full2.2\Twisted\twisted\trial\runner.py", line
111, in __call__
    return self.run(result)
  File "c:\buildslave\w32\W32-full2.2\Twisted\twisted\trial\runner.py", line
119, in run
    test(result)
  File "c:\buildslave\w32\W32-full2.2\Twisted\twisted\trial\runner.py", line
190, in __call__
    return self.run(reporter)
  File "c:\buildslave\w32\W32-full2.2\Twisted\twisted\trial\runner.py", line
197, in run
    self._suite.run(reporter)
  File "c:\buildslave\w32\W32-full2.2\Twisted\twisted\trial\runner.py", line
119, in run
    test(result)
  File "c:\buildslave\w32\W32-full2.2\Twisted\twisted\trial\runner.py", line
190, in __call__
    return self.run(reporter)
  File "c:\buildslave\w32\W32-full2.2\Twisted\twisted\trial\runner.py", line
197, in run
    self._suite.run(reporter)
  File "c:\buildslave\w32\W32-full2.2\Twisted\twisted\trial\runner.py", line
271, in run
    testMethod.run(reporter)
  File "c:\buildslave\w32\W32-full2.2\Twisted\twisted\trial\unittest.py", line
127, in run
    janitor.postMethodCleanup()
  File "c:\buildslave\w32\W32-full2.2\Twisted\twisted\trial\util.py", line 138,
in postMethodCleanup
    return self._dispatch('logErrCheck', 'cleanPending')
  File "c:\buildslave\w32\W32-full2.2\Twisted\twisted\trial\util.py", line 150,
in _dispatch
    getattr(self, "do_%s" % attr)()
  File "c:\buildslave\w32\W32-full2.2\Twisted\twisted\trial\util.py", line 175,
in do_cleanPending
    reactor.iterate(0)
  File "c:\buildslave\w32\W32-full2.2\Twisted\twisted\internet\base.py", line
368, in iterate
    self.doIteration(delay)
  File
"c:\buildslave\w32\W32-full2.2\Twisted\twisted\internet\win32eventreactor.py",
line 158, in doWaitForMultipleEvents
    val = MsgWaitForMultipleObjects(handles, 0, timeout, QS_ALLINPUT | QS_ALLEVENTS)
pywintypes.error: (87, 'MsgWaitForMultipleObjects', 'The parameter is incorrect.')
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="spiv's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|spiv commented|
|-|-|

```
#!html
<pre>
This appears to be partly due to the same problem that affected the iocp
reactor: reactor.iterate(0) raising an exception and thus breaking trial's cleanup.

Trial probably needs to handle this better, given that it's happened more than
once.  The win32reactor should probably also not raise this exception -- perhaps
that should be a seperate bug report, though.
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)|@jml commented|
|-|-|

```
#!html
<pre>
This appears to be resolved with the merge of trial-umw-death
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
