### ISSUE TITLE
[PATCH] Traceback running a test with broken setUp method

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10930]
|<img alt="headly's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| headly reported|
|-|-|
|Trac ID|trac#1359|
|Type|defect|
|Created|2005-12-12 04:54:07Z|

Attachments:

* [reporter.diff](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/ccc/cccfd063b99f899232d571d89d3f832308c0d0bc/6e10ee3ed4342cc6d283c1e79ee16b52bad45142.diff) (534 bytes) - added by headly on 2005-12-12 04:54:06Z - 

<details><summary>Searchable metadata</summary>

```
trac-id__1359 1359
type__defect defect
reporter__headly headly
priority__high high
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__trial trial
keywords__ 
time__1134363247000000 1134363247000000
changetime__1135080525000000 1135080525000000
version__ 
owner__ 
cc__headly cc__jml
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="headly's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|headly commented|
|-|-|

```
#!html
<pre>
I get the following error when running a test script that has a broken setUp
method. Attached is a patch to fix it.

$ trial test
Running 91 tests.
  equalog.test.test_accounting
  equalog.test.test_catalog
    Catalog
  setUpClass                                                       ['ERROR']

-------------------------------------------------------------------------------
Ran 0 tests in 0.013s

PASSED
Traceback (most recent call last):
  File "/usr/bin/trial", line 24, in ?
    run()
  File "/home/ed/projects/Twisted/twisted/scripts/trial.py", line 461, in run
    test_result = reallyRun(config)
  File "/home/ed/projects/Twisted/twisted/scripts/trial.py", line 448, in reallyRun
    return call_with(do_a_run)
  File "/home/ed/projects/Twisted/twisted/scripts/trial.py", line 444, in &lt;lambda>
    call_with = lambda func, *args, **kwargs: func(*args, **kwargs)
  File "/home/ed/projects/Twisted/twisted/scripts/trial.py", line 440, in do_a_run
    return my_runner.run(suite)
  File "/home/ed/projects/Twisted/twisted/trial/runner.py", line 552, in run
    suite.run(result)
  File "/home/ed/projects/Twisted/twisted/trial/runner.py", line 175, in run
    TestSuite.run(self, result)
  File "/home/ed/projects/Twisted/twisted/trial/runner.py", line 119, in run
    test(result)
  File "/home/ed/projects/Twisted/twisted/trial/runner.py", line 111, in __call__
    return self.run(result)
  File "/home/ed/projects/Twisted/twisted/trial/runner.py", line 119, in run
    test(result)
  File "/home/ed/projects/Twisted/twisted/trial/runner.py", line 111, in __call__
    return self.run(result)
  File "/home/ed/projects/Twisted/twisted/trial/runner.py", line 119, in run
    test(result)
  File "/home/ed/projects/Twisted/twisted/trial/runner.py", line 190, in __call__
    return self.run(reporter)
  File "/home/ed/projects/Twisted/twisted/trial/runner.py", line 197, in run
    self._suite.run(reporter)
  File "/home/ed/projects/Twisted/twisted/trial/runner.py", line 119, in run
    test(result)
  File "/home/ed/projects/Twisted/twisted/trial/runner.py", line 190, in __call__
    return self.run(reporter)
  File "/home/ed/projects/Twisted/twisted/trial/runner.py", line 197, in run
    self._suite.run(reporter)
  File "/home/ed/projects/Twisted/twisted/trial/runner.py", line 291, in run
    util.wait(d, timeout=None)
  File "/home/ed/projects/Twisted/twisted/trial/util.py", line 340, in wait
    r.raiseException()
  File "/home/ed/projects/Twisted/twisted/python/failure.py", line 247, in
raiseException
    raise self.type, self.value, self.tb
NameError: global name 'methNameWarnMsg' is not defined
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)|@jml commented|
|-|-|

```
#!html
<pre>
Thanks headly.

I'm going to hold off on applying the patch until I write up a test case.
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)|@jml commented|
|-|-|

```
#!html
<pre>
Fixed in r15353.  Thanks.

Didn't end up writing a test -- too hard.
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
