### ISSUE TITLE
ExpatError on xmlrpc client connection close

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10985]
|<img alt="kkinder's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| kkinder reported|
|-|-|
|Trac ID|trac#1412|
|Type|defect|
|Created|2006-01-11 06:21:08Z|

<details><summary>Searchable metadata</summary>

```
trac-id__1412 1412
type__defect defect
reporter__kkinder kkinder
priority__high high
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__duplicate duplicate
component__web web
keywords__ 
time__1136960468000000 1136960468000000
changetime__1212786430000000 1212786430000000
version__ 
owner__ 
cc__jknight cc__kkinder
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="kkinder's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|kkinder commented|
|-|-|

```
#!html
<pre>
Upon using the twisted.web.xmlrpc.Proxy class, if you have an active HTTP
session that is closed mid-stream, you get this exception:

Traceback (most recent call last):
  File "test.py", line 20, in ?
    reactor.run()
  File "/usr/lib/python2.4/site-packages/twisted/internet/posixbase.py", line
206, in run
    self.mainLoop()
  File "/usr/lib/python2.4/site-packages/twisted/internet/posixbase.py", line
217, in mainLoop
    self.doIteration(t)
  File "/usr/lib/python2.4/site-packages/twisted/internet/selectreactor.py",
line 133, in doSelect
    _logrun(selectable, _drdw, selectable, method, dict)
--- &lt;exception caught here> ---
  File "/usr/lib/python2.4/site-packages/twisted/python/log.py", line 58, in
callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/lib/python2.4/site-packages/twisted/python/log.py", line 43, in
callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/lib/python2.4/site-packages/twisted/python/context.py", line 59, in
callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.4/site-packages/twisted/python/context.py", line 37, in
callWithContext
    return func(*args,**kw)
  File "/usr/lib/python2.4/site-packages/twisted/internet/selectreactor.py",
line 149, in _doReadOrWrite
    self._disconnectSelectable(selectable, why, method=="doRead")
  File "/usr/lib/python2.4/site-packages/twisted/internet/posixbase.py", line
238, in _disconnectSelectable
    selectable.readConnectionLost(f)
  File "/usr/lib/python2.4/site-packages/twisted/internet/tcp.py", line 390, in
readConnectionLost
    self.connectionLost(reason)
  File "/usr/lib/python2.4/site-packages/twisted/internet/tcp.py", line 555, in
connectionLost
    Connection.connectionLost(self, reason)
  File "/usr/lib/python2.4/site-packages/twisted/internet/tcp.py", line 401, in
connectionLost
    protocol.connectionLost(reason)
  File "/usr/lib/python2.4/site-packages/twisted/web/http.py", line 351, in
connectionLost
    self.handleResponseEnd()
  File "/usr/lib/python2.4/site-packages/twisted/web/http.py", line 357, in
handleResponseEnd
    self.handleResponse(b)
  File "/usr/lib/python2.4/site-packages/twisted/web/xmlrpc.py", line 259, in
handleResponse
    self.factory.parseResponse(contents)
  File "/usr/lib/python2.4/site-packages/twisted/web/xmlrpc.py", line 284, in
parseResponse
    response = xmlrpclib.loads(contents)
  File "/usr/lib/python2.4/xmlrpclib.py", line 1080, in loads
    p.close()
  File "/usr/lib/python2.4/xmlrpclib.py", line 530, in close
    self._parser.Parse("", 1) # end of data
xml.parsers.expat.ExpatError: no element found: line 1, column 0

Ostensibly, this is because Twisted decides to parse the returned value even
though the connection was closed. Then, it fails to catch this exception in the
Query class.
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_2"></a>|@exarkun set status to `closed`|
|-|-|

This is basically a duplicate of [#10587](https://github.com/twisted/twisted/issues/10587), although [#10568](https://github.com/twisted/twisted/issues/10568) is a bit related as well.  Both are resolved now.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
