### ISSUE TITLE
[PATCH] iocp's doIteration doesn't handle errors thrown from selectables

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10984]
|<img alt="spiv's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| spiv reported|
|-|-|
|Trac ID|trac#1294|
|Type|defect|
|Created|2005-10-29 09:43:35Z|

Attachments:

* [iocp_callWithLogger.diff](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/607/6077ad2b372d5a152de8191d73e3e4480c620035/bb251ab7eda8d188ee67f7dd94584fe90b8365ad.diff) (1967 bytes) - added by spiv on 2005-10-29 09:44:10Z - 

<details><summary>Searchable metadata</summary>

```
trac-id__1294 1294
type__defect defect
reporter__spiv spiv
priority__high high
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__win32 win32
time__1130579015000000 1130579015000000
changetime__1130884486000000 1130884486000000
version__ 
owner__justinj justinj
cc__spiv cc__jml cc__justinj
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="spiv's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|spiv commented|
|-|-|

```
#!html
<pre>
iocp's doIteration currently lets exceptions from random code it invokes bubble
up to the caller of doIteration.  This is currently causing the iocp buildslave
to abort 1/5th of the way through the test suite with the following traceback:

Traceback (most recent call last):
  File "c:\buildslave\w32\W32-full2.2\Twisted\./bin/trial", line 24, in ?
    run()
  File "c:\buildslave\w32\W32-full2.2\Twisted\twisted\scripts\trial.py", line
451, in run
    test_result = reallyRun(config)
  File "c:\buildslave\w32\W32-full2.2\Twisted\twisted\scripts\trial.py", line
439, in reallyRun
    return call_with(do_a_run)
  File "c:\buildslave\w32\W32-full2.2\Twisted\twisted\scripts\trial.py", line
435, in &lt;lambda>
    call_with = lambda func, *args, **kwargs: func(*args, **kwargs)
  File "c:\buildslave\w32\W32-full2.2\Twisted\twisted\scripts\trial.py", line
431, in do_a_run
    return my_runner.run(suite)
  File "c:\buildslave\w32\W32-full2.2\Twisted\twisted\trial\runner.py", line
449, in run
    suite.run(result)
  File "c:\buildslave\w32\W32-full2.2\Twisted\twisted\trial\runner.py", line
175, in run
    TestSuite.run(self, result)
  File "c:\buildslave\w32\W32-full2.2\Twisted\twisted\trial\runner.py", line
119, in run
    test(result)
  File "c:\buildslave\w32\W32-full2.2\Twisted\twisted\trial\runner.py", line
111, in __call__
    return self.run(result)
  File "c:\buildslave\w32\W32-full2.2\Twisted\twisted\trial\runner.py", line
119, in run
    test(result)
  File "c:\buildslave\w32\W32-full2.2\Twisted\twisted\trial\runner.py", line
111, in __call__
    return self.run(result)
  File "c:\buildslave\w32\W32-full2.2\Twisted\twisted\trial\runner.py", line
119, in run
    test(result)
  File "c:\buildslave\w32\W32-full2.2\Twisted\twisted\trial\runner.py", line
190, in __call__
    return self.run(reporter)
  File "c:\buildslave\w32\W32-full2.2\Twisted\twisted\trial\runner.py", line
197, in run
    self._suite.run(reporter)
  File "c:\buildslave\w32\W32-full2.2\Twisted\twisted\trial\runner.py", line
119, in run
    test(result)
  File "c:\buildslave\w32\W32-full2.2\Twisted\twisted\trial\runner.py", line
190, in __call__
    return self.run(reporter)
  File "c:\buildslave\w32\W32-full2.2\Twisted\twisted\trial\runner.py", line
197, in run
    self._suite.run(reporter)
  File "c:\buildslave\w32\W32-full2.2\Twisted\twisted\trial\runner.py", line
119, in run
    test(result)
  File "c:\buildslave\w32\W32-full2.2\Twisted\twisted\trial\unittest.py", line
61, in __call__
    return self.run(*args, **kwargs)
  File "c:\buildslave\w32\W32-full2.2\Twisted\twisted\trial\unittest.py", line
112, in run
    util._Janitor().postMethodCleanup()
  File "c:\buildslave\w32\W32-full2.2\Twisted\twisted\trial\util.py", line 143,
in postMethodCleanup
    return self._dispatch('logErrCheck', 'cleanPending')
  File "c:\buildslave\w32\W32-full2.2\Twisted\twisted\trial\util.py", line 155,
in _dispatch
    getattr(self, "do_%s" % attr)()
  File "c:\buildslave\w32\W32-full2.2\Twisted\twisted\trial\util.py", line 180,
in do_cleanPending
    reactor.iterate(0)
  File "c:\buildslave\w32\W32-full2.2\Twisted\twisted\internet\base.py", line
368, in iterate
    self.doIteration(delay)
  File
"c:\buildslave\w32\W32-full2.2\Twisted\twisted\internet\iocpreactor\ops.py",
line 36, in ovDone
    self.transport.readDone(bytes)
  File
"c:\buildslave\w32\W32-full2.2\Twisted\twisted\internet\iocpreactor\util.py",
line 17, in helpful
    return getattr(self, "handle_%s_%s" % (self.state, name))(*a, **kw)
  File
"c:\buildslave\w32\W32-full2.2\Twisted\twisted\internet\iocpreactor\abstract.py",
line 157, in handle_connected_readDone
    self.protocol.dataReceived(self.readbuf[:bytes])
  File "c:\buildslave\w32\W32-full2.2\Twisted\twisted\protocols\basic.py", line
149, in dataReceived
    self.lineReceived(line)
  File "c:\buildslave\w32\W32-full2.2\Twisted\twisted\mail\pop3.py", line 163,
in lineReceived
    self.resetTimeout()
  File "c:\buildslave\w32\W32-full2.2\Twisted\twisted\protocols\policies.py",
line 512, in resetTimeout
    self.__timeoutCall.reset(self.timeOut)
  File "c:\buildslave\w32\W32-full2.2\Twisted\twisted\internet\base.py", line
97, in reset
    raise error.AlreadyCancelled
twisted.internet.error.AlreadyCancelled: Tried to cancel an already-cancelled event.

(see http://twistedmatrix.com/buildbot/win32/builds/839/iocp/0)

The attached, untested, patch attempts to make it call the callback using
t.p.log.callWithLogger, same as the selectreactor does.

Someone with win32 should test this works :)

Hopefully this will make the iocp slave work better.
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="justinj's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|justinj commented|
|-|-|

```
#!html
<pre>
Resolved in 14989.
</pre>
```
