### ISSUE TITLE
win32eventreactor goes crazy at 64 connections

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10981]
|[<img alt="ghazel's avatar" src="https://avatars.githubusercontent.com/u/31402?s=50" width="50" height="50">](https://github.com/ghazel)| @ghazel reported|
|-|-|
|Trac ID|trac#1260|
|Type|defect|
|Created|2005-10-09 07:01:58Z|

Attachments:

* [enumevents.diff](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/98f/98f59d0c790f1ae9d5c7f8f7b9f189f093d69c55/88a8aa9a46dec7607c689d2ef92e3f600448b534.diff) (6187 bytes) - added by ghazel on 2007-05-11 00:58:59Z - WSAWaitForMultipleEvents, WSAEnumNetworkEvents example
* [enumevents.2.diff](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/98f/98f59d0c790f1ae9d5c7f8f7b9f189f093d69c55/27e193cd8eec3dd3d3e711f6e9a51a2d0c1eca23.diff) (6215 bytes) - added by ghazel on 2007-05-11 01:31:31Z - WSAWaitForMultipleEvents, WFMO example

<details><summary>Searchable metadata</summary>

```
trac-id__1260 1260
type__defect defect
reporter__ghazel ghazel
priority__high high
milestone__ 
branch__ 
branch_author__ 
status__reopened reopened
resolution__ 
component__core core
keywords__ 
time__1128841318000000 1128841318000000
changetime__1207876412000000 1207876412000000
version__ 
owner__justinj justinj
cc__justinj cc__ghazel cc__itamar cc__glyph cc__Trent.Nelson
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="ghazel's avatar" src="https://avatars.githubusercontent.com/u/31402?s=50" width="50" height="50">](https://github.com/ghazel)|@ghazel commented|
|-|-|

```
#!html
<pre>
Run any win32eventreactor and make over 64 connections, you get this traceback 
repeatedly, until you kill the process.

Traceback (most recent call last):
  ...
   reactor.run()
  File "C:\Python24\Lib\site-packages\twisted\internet\posixbase.py", line 199, 
in run
    self.mainLoop()
--- &lt;exception caught here> ---
  File "C:\Python24\Lib\site-packages\twisted\internet\posixbase.py", line 210, 
in mainLoop
    self.doIteration(t)
  File "C:\Python24\Lib\site-packages\twisted\internet\win32eventreactor.py", 
line 157, in doWaitForMultipleEvents
    val = MsgWaitForMultipleObjects(handles, 0, timeout, QS_ALLINPUT | 
QS_ALLEVENTS)
pywintypes.error: (87, 'MsgWaitForMultipleObjects', 'The parameter is 
incorrect.')
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="justinj's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|justinj commented|
|-|-|

```
#!html
<pre>
This is a known issue and is due to a Windows limitation on 
MsgWaitForMultipleObjects.  See http://msdn.microsoft.com/library/default.asp?
url=/library/en-us/dllproc/base/msgwaitformultipleobjects.asp for more 
information.

There are potential ways to clean up the win32eventreactor (documented at URL 
above), but it seems that the direction with Twisted is to make iocpreactor 
more stable and full featured and use it instead.  The iocpreactor doesn't 
suffer from the same limitations, but it also doesn't have all of the 
functionality that win32eventreactor has at the moment.  I have a patch 
(#1008) that I will (hopefully soon) be applying to add spawnProcess 
support, but there are other things missing as well.
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="ghazel's avatar" src="https://avatars.githubusercontent.com/u/31402?s=50" width="50" height="50">](https://github.com/ghazel)<a name="note_3"></a>|@ghazel set status to `reopened`|
|-|-|

Here's an example of a fairly reasonable way to handle >64 sockets in a win32 reactor without threads or IOCP. This passes unit tests as well as win32eventreactor used to.

Any interest in polishing this up for inclusion?
