### ISSUE TITLE
trial's minimal reporter is broken

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10991]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)| @itamarst reported|
|-|-|
|Trac ID|trac#1426|
|Type|defect|
|Created|2006-01-18 23:27:16Z|

<details><summary>Searchable metadata</summary>

```
trac-id__1426 1426
type__defect defect
reporter__itamarst itamarst
priority__highest highest
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__trial trial
keywords__ 
time__1137626836000000 1137626836000000
changetime__1138691544000000 1138691544000000
version__ 
owner__ 
cc__itamarst cc__jml
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)|@itamarst commented|
|-|-|

```
#!html
<pre>
Running these tests with regular reporter succeeds. These are pyunit tests.

$ trial --reporter summary swipy.test
Running 24 tests.
-------------------------------------------------------------------------------
Ran 24 tests in 0.096s

Traceback (most recent call last):
  File "/usr/bin/trial", line 24, in ?
    run()
  File "/home/itamarst/devel/python/Twisted/twisted/scripts/trial.py", line 364,
in run
    test_result = trialRunner.run(suite)
  File "/home/itamarst/devel/python/Twisted/twisted/trial/runner.py", line 473,
in run
    result.printSummary()
  File "/home/itamarst/devel/python/Twisted/twisted/trial/reporter.py", line
232, in printSummary
    t = (self._somethingStopped(), numTests, numTests,
AttributeError: 'MinimalReporter' object has no attribute 'couldNotImport'
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)|@itamarst commented|
|-|-|

```
#!html
<pre>
BTW, being able to run pyunit tests with trial is really useful. Good work!
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)|@jml commented|
|-|-|

```
#!html
<pre>
You can also run Trial unit tests with pyunit :)

looking at this one now
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)|@jml commented|
|-|-|

```
#!html
<pre>
Resolved in r15790
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
