### ISSUE TITLE
trial TestImportErrors tests fail on Windows due to in use files

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#11019]
|<img alt="justinj's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| justinj reported|
|-|-|
|Trac ID|trac#1317|
|Type|defect|
|Created|2005-11-08 01:59:36Z|

<details><summary>Searchable metadata</summary>

```
trac-id__1317 1317
type__defect defect
reporter__justinj justinj
priority__high high
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__trial trial
keywords__ 
time__1131415176000000 1131415176000000
changetime__1132186394000000 1132186394000000
version__ 
owner__justinj justinj
cc__jml cc__justinj
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="justinj's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|justinj commented|
|-|-|

```
#!html
<pre>
On Windows you can't remove files when they are in use by a process.  These 
errors occur for both iocp (code I'm working on) and win32 (code already 
committed).

C:\src\Twisted-1008>trial -r iocp 
twisted.trial.test.test_output.TestImportErrors
Using twisted.internet.iocpreactor reactor
Running 14 tests.
  TestImportErrors
    test_badimport ...                                                     ←
[32;
1m[OK]←[0m
    test_badmodule ... could not remove path, caught OSError [Errno 13]: 
Permission denied
could not rename path, caught OSError [Errno 13]: Permission denied
                                                 ←[31;1m[ERROR]←[0m
    test_badpackage ... could not remove path, caught OSError [Errno 13]: 
Permission denied
could not rename path, caught OSError [Errno 13]: Permission denied
                                                ←[31;1m[ERROR]←[0m
    test_dosFile ... could not remove path, caught OSError [Errno 13]: 
Permission denied
could not rename path, caught OSError [Errno 13]: Permission denied
                                                   ←[31;1m[ERROR]←[0m
    test_filename ... could not remove path, caught OSError [Errno 13]: 
Permission denied
could not rename path, caught OSError [Errno 13]: Permission denied
                                                  ←[31;1m[ERROR]←[0m
    test_moduleInBadpackage ... could not remove path, caught OSError [Errno 
13]: Permission denied
could not rename path, caught OSError [Errno 13]: Permission denied
                                        ←[31;1m[ERROR]←[0m
    test_nonRecurseImportErrors ... could not remove path, caught OSError 
[Errno 13]: Permission denied
could not rename path, caught OSError [Errno 13]: Permission denied
                                    ←[31;1m[ERROR]←[0m
    test_nonexistentModule ... could not remove path, caught OSError [Errno 
13]: Permission denied
could not rename path, caught OSError [Errno 13]: Permission denied
                                         ←[31;1m[ERROR]←[0m
    test_nonexistentPackage ... could not remove path, caught OSError [Errno 
13]: Permission denied
could not rename path, caught OSError [Errno 13]: Permission denied
                                        ←[31;1m[ERROR]←[0m
    test_nonexistentPackageWithModule ... could not remove path, caught 
OSError [Errno 13]: Permission denied
could not rename path, caught OSError [Errno 13]: Permission denied
                              ←[31;1m[ERROR]←[0m
    test_recurseImport ... could not remove path, caught OSError [Errno 13]: 
Permission denied
could not rename path, caught OSError [Errno 13]: Permission denied
                                             ←[31;1m[ERROR]←[0m
    test_recurseImportErrors ... could not remove path, caught OSError [Errno 
13]: Permission denied
could not rename path, caught OSError [Errno 13]: Permission denied
                                       ←[31;1m[ERROR]←[0m
    test_regularRun ... could not remove path, caught OSError [Errno 13]: 
Permission denied
could not rename path, caught OSError [Errno 13]: Permission denied
                                                ←[31;1m[ERROR]←[0m
    test_trialRun ... could not remove path, caught OSError [Errno 13]: 
Permission denied
could not rename path, caught OSError [Errno 13]: Permission denied
                                                  ←[31;1m[ERROR]←[0m

===============================================================================
[ERROR]: twisted.trial.test.test_output.TestImportErrors.test_badmodule

  File "C:\src\Twisted-1008\twisted\internet\defer.py", line 107, in 
maybeDeferred
    result = f(*args, **kw)
  File "C:\src\Twisted-1008\twisted\trial\test\test_output.py", line 118, in 
test_badmodule
    d = self.runTrial('package.test_bad_module')
  File "C:\src\Twisted-1008\twisted\trial\test\test_output.py", line 59, in 
runTrial
    return self._runTrial(*args)
  File "C:\src\Twisted-1008\twisted\trial\test\test_output.py", line 45, in 
_runTrial
    config.parseOptions(args)
  File "C:\src\Twisted-1008\twisted\python\usage.py", line 197, in parseOptions
    self.postOptions()
  File "C:\src\Twisted-1008\twisted\scripts\trial.py", line 295, in postOptions
    _setUpTestdir()
  File "C:\src\Twisted-1008\twisted\scripts\trial.py", line 367, in 
_setUpTestdir
    os.path.abspath("_trial_temp_old%s"
exceptions.OSError: [Errno 13] Permission denied
===============================================================================

... lots of similar output here ...

Ran 14 tests in 4.297s

FAILED (errors=13, successes=1)
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="justinj's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|justinj commented|
|-|-|

```
#!html
<pre>
Manually (after a pdb.set_trace) removing the correct observer from 
log.theLogPublisher.observers freed up _trial_temp\_trial_temp\test.log so it 
could be removed.  So apparently some of the code that normally runs at 
shutdown or something for trial which closes the logs, etc, doesn't get run 
when trial is run from within test_output.
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="justinj's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|justinj commented|
|-|-|

```
#!html
<pre>
The following test fails for the same reason.

[FAIL]: twisted.trial.test.test_script.TestModuleTest.test_actuallyRuns

  File "c:\buildslave\w32\W32-full2.2\Twisted\twisted\internet\defer.py", line 
307, in _runCallbacks
    self.result = callback(self.result, *args, **kw)
  File "c:\buildslave\w32\W32-full2.2
\Twisted\twisted\trial\test\test_script.py", line 70, in &lt;lambda>
    d.addCallback(lambda x : self.assertSubstring(
  File "c:\buildslave\w32\W32-full2.2\Twisted\twisted\trial\unittest.py", line 
401, in failUnlessSubstring
    raise self.failureException(msg or "%r not found in %r"
twisted.trial.unittest.FailTest: 'twisted.trial.test.test_test_visitor' not 
found in 'could not remove path, caught OSError [Errno 13]: Permission 
denied\r\ncould not rename path, caught OSError [Errno 13]: Permission 
denied\r\nTraceback (most recent call last):\r\n  File "&lt;string>", line 1, in ?
\r\n  File "c:\\buildslave\\w32\\W32-full2.2
\\Twisted\\twisted\\scripts\\trial.py", line 445, in run\r\n    
config.parseOptions()\r\n  File "c:\\buildslave\\w32\\W32-full2.2
\\Twisted\\twisted\\python\\usage.py", line 197, in parseOptions\r\n    
self.postOptions()\r\n  File "c:\\buildslave\\w32\\W32-full2.2
\\Twisted\\twisted\\scripts\\trial.py", line 295, in postOptions\r\n    
_setUpTestdir()\r\n  File "c:\\buildslave\\w32\\W32-full2.2
\\Twisted\\twisted\\scripts\\trial.py", line 367, in _setUpTestdir\r\n    
os.path.abspath("_trial_temp_old%s"\r\nOSError: [Errno 13] Permission 
denied\r\n'
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)|@jml commented|
|-|-|

```
#!html
<pre>
I've cleaned up these tests.  If this fixes your errors, please mark this issue
as 'resolved'.  Thanks!
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="justinj's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|justinj commented|
|-|-|

```
#!html
<pre>
Resolved.  Thanks!
</pre>
```
