### ISSUE TITLE
trial ImportErrors in loadReporters when subpackages not installed

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#11023]
|[<img alt="keturn's avatar" src="https://avatars.githubusercontent.com/u/83819?s=50" width="50" height="50">](https://github.com/keturn)| @keturn reported|
|-|-|
|Trac ID|trac#1336|
|Type|defect|
|Created|2005-11-22 01:59:21Z|

<details><summary>Searchable metadata</summary>

```
trac-id__1336 1336
type__defect defect
reporter__acapnotic acapnotic
priority__high high
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__ 
time__1132624761000000 1132624761000000
changetime__1213560445000000 1213560445000000
version__ 
owner__acapnotic acapnotic
cc__exarkun cc__spiv cc__acapnotic cc__itamarst cc__jml
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="keturn's avatar" src="https://avatars.githubusercontent.com/u/83819?s=50" width="50" height="50">](https://github.com/keturn)|@keturn commented|
|-|-|

```
#!html
<pre>
Traceback (most recent call last):
  File "/home/kevint/lib/python/twisted/scripts/trial.py", line 520, in run
    config = Options()
  File "/home/kevint/lib/python/twisted/scripts/trial.py", line 133, in __init__
    self._loadReporters()
  File "/home/kevint/lib/python/twisted/scripts/trial.py", line 138, in
_loadReporters
    for p in plugin.getPlugins(itrial.IReporter):
  File "/home/kevint/lib/python/twisted/plugin.py", line 210, in getPlugins
    allDropins = getCache(package)
--- &lt;exception caught here> ---
  File "/home/kevint/lib/python/twisted/plugin.py", line 166, in getCache
    provider = namedAny(module.__name__ + '.' + moduleName)
  File "/home/kevint/lib/python/twisted/python/reflect.py", line 361, in namedAny
    topLevelPackage = __import__(trialname)
  File "/usr/lib/python2.4/site-packages/twisted/plugins/twisted_words.py", line
12, in ?
    from twisted.words import botbot
exceptions.ImportError: No module named words
Traceback (most recent call last):
  File "/home/kevint/lib/python/twisted/scripts/trial.py", line 520, in run
    config = Options()
  File "/home/kevint/lib/python/twisted/scripts/trial.py", line 133, in __init__
    self._loadReporters()
  File "/home/kevint/lib/python/twisted/scripts/trial.py", line 138, in
_loadReporters
    for p in plugin.getPlugins(itrial.IReporter):
  File "/home/kevint/lib/python/twisted/plugin.py", line 210, in getPlugins
    allDropins = getCache(package)
--- &lt;exception caught here> ---
  File "/home/kevint/lib/python/twisted/plugin.py", line 166, in getCache
    provider = namedAny(module.__name__ + '.' + moduleName)
  File "/home/kevint/lib/python/twisted/python/reflect.py", line 361, in namedAny
    topLevelPackage = __import__(trialname)
  File "/usr/lib/python2.4/site-packages/twisted/plugins/twisted_lore.py", line
5, in ?
    from twisted.lore.scripts.lore import IProcessor
exceptions.ImportError: No module named lore.scripts.lore
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun commented|
|-|-|

```
#!html
<pre>
Notice half the paths are from /home/kevint/lib/python/ and the other half are
from /usr/lib/python2.4/site-packages/.  The plugin system traverses sys.path to
discover plugins: if a twisted package is present at two locations in sys.path,
plugins will be found from each.  If the twisted package present in the first
location in sys.path is missing modules expected by the twisted package present
in the second location in sys.path, import errors will follow.
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun commented|
|-|-|

```
#!html
<pre>
I think this can be closed?  It seems to have been a deployment configuration
problem.
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="keturn's avatar" src="https://avatars.githubusercontent.com/u/83819?s=50" width="50" height="50">](https://github.com/keturn)|@keturn commented|
|-|-|

```
#!html
<pre>
The deployment was "setup.py install --home $HOME".  There was probably
system-wide Debian twisted install as well.  That should not be a problematic
deployment.
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_5"></a>|@exarkun set status to `closed`|
|-|-|

This was due to [#2339](https://github.com/twisted/twisted/issues/2339), which is now fixed.
