### ISSUE TITLE
doStart missing, reactor.listenTCP.  debian unstable twisted,

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#11035]
|<img alt="illume's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| illume reported|
|-|-|
|Trac ID|trac#1496|
|Type|defect|
|Created|2006-02-21 04:54:08Z|

<details><summary>Searchable metadata</summary>

```
trac-id__1496 1496
type__defect defect
reporter__illume illume
priority__high high
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__invalid invalid
component__web2 web2
keywords__ 
time__1140497648000000 1140497648000000
changetime__1140754364000000 1140754364000000
version__ 
owner__ 
cc__jknight cc__illume
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="illume's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|illume commented|
|-|-|

```
#!html
<pre>
Traceback (most recent call last):
  File "serve_all_pp.py", line 67, in ?
    reactor.listenTCP(config.http_port, site)
  File "/usr/lib/python2.4/site-packages/twisted/internet/posixbase.py", line
368, in listenTCP
    p.startListening()
  File "/usr/lib/python2.4/site-packages/twisted/internet/tcp.py", line 722, in
startListening
    self.factory.doStart()
AttributeError: Site instance has no attribute 'doStart'
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="illume's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|illume commented|
|-|-|

```
#!html
<pre>
Site was a twisted.web2.server.Site instance.

I used the factory in this line:
reactor.listenTCP(config.http_port, http.HTTPFactory(site))

Instead of this line that used to work with an older version of twisted:
reactor.listenTCP(config.http_port, site)
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="jyknight's avatar" src="https://avatars.githubusercontent.com/u/873903?s=50" width="50" height="50">](https://github.com/jyknight)|@jyknight commented|
|-|-|

```
#!html
<pre>
Yes, that's how it works.

Closing issue as rejected.
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="illume's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|illume commented|
|-|-|

```
#!html
<pre>
Hello,

I just checked out the latest svn twisted... and now
twisted.web2.http.HTTPFactory doesn't exist.  

What to do now?
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="jyknight's avatar" src="https://avatars.githubusercontent.com/u/873903?s=50" width="50" height="50">](https://github.com/jyknight)|@jyknight commented|
|-|-|

```
#!html
<pre>
You read the docs and examples in doc/web2/examples/. Also please use the mailing 
list for questions rather than the bug tracker.

I'll give you a hint cause I'm nice, though: it moved to 
twisted.web2.channel.HTTPFactory.
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
