### ISSUE TITLE
iocpreactor (udp) socket.error: (10049, "Can't assign requested address")

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#11047]
|[<img alt="ghazel's avatar" src="https://avatars.githubusercontent.com/u/31402?s=50" width="50" height="50">](https://github.com/ghazel)| @ghazel reported|
|-|-|
|Trac ID|trac#1369|
|Type|defect|
|Created|2005-12-20 06:14:17Z|

<details><summary>Searchable metadata</summary>

```
trac-id__1369 1369
type__defect defect
reporter__ghazel ghazel
priority__high high
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__invalid invalid
component__core core
keywords__ 
time__1135059257000000 1135059257000000
changetime__1205874825000000 1205874825000000
version__ 
owner__ 
cc__justinj cc__ghazel
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="ghazel's avatar" src="https://avatars.githubusercontent.com/u/31402?s=50" width="50" height="50">](https://github.com/ghazel)|@ghazel commented|
|-|-|

```
#!html
<pre>
Not sure what causes this, maybe the requested address should be printed with 
the exception?

Traceback (most recent call last):
  File "twisted\internet\defer.pyc", line 307, in _runCallbacks
    
  File "twisted\internet\iocpreactor\udp.pyc", line 209, in _joinAddr1
    
  File "twisted\internet\defer.pyc", line 191, in addCallback
    
  File "twisted\internet\defer.pyc", line 182, in addCallbacks
    
--- &lt;exception caught here> ---
  File "twisted\internet\defer.pyc", line 307, in _runCallbacks
    
  File "twisted\internet\iocpreactor\udp.pyc", line 218, in _joinAddr2
    
  File "&lt;string>", line 1, in setsockopt
    
socket.error: (10049, "Can't assign requested address")
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="justinj's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|justinj removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|<img alt="PenguinOfDoom's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|PenguinOfDoom set status to `closed`|
|-|-|

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
