### ISSUE TITLE
twisted.words oscardemo throws traceback

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#11069]
|<img alt="yacc's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| yacc reported|
|-|-|
|Trac ID|trac#1529|
|Type|defect|
|Created|2006-03-02 08:04:43Z|

When running the oscardemo.py from the current svn (r16115), I'm getting the following traceback:

Username: yaccHome
Password:
{'name': 'yaccHome', 'caps': [], 'warning': 0, 'onSince': 1141285824L, 'icqIPaddy': '85.124.84.82', 'flags': ['trial', 'aim'], 'sessionLength': 1L}
([<twisted.words.protocols.oscar.SSIGroup instance at 0xb7696f0c>, <twisted.words.protocols.oscar.SSIGroup instance at 0xb7696f4c>, <twisted.words.protocols.oscar.SSIGroup instance at 0xb7696f6c>, <twisted.words.protocols.oscar.SSIGroup instance at 0xb7696f8c>], [], [], None, None, 1141285604L, 12)
<OSCARUser yacc143, flags ['trial', 'aim'], online for 216 minutes, caps ['chat', 'icon', ('unknown', '\tF\x13#L\x7f\x11\xd1\x82"DEST\x00\x00')]>
Unhandled error in Deferred:
Traceback (most recent call last):
  File "/usr/lib/python2.4/site-packages/twisted/words/protocols/oscar.py", line 284, in dataReceived
    state=func(flap)
  File "/usr/lib/python2.4/site-packages/twisted/words/protocols/oscar.py", line 359, in oscar_Data
    d.callback(snac)
  File "/usr/lib/python2.4/site-packages/twisted/internet/defer.py", line 229, in callback
    self._startRunCallbacks(result)
  File "/usr/lib/python2.4/site-packages/twisted/internet/defer.py", line 294, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/usr/lib/python2.4/site-packages/twisted/internet/defer.py", line 307, in _runCallbacks
    self.result = callback(self.result, *args, **kw)
  File "/usr/lib/python2.4/site-packages/twisted/words/protocols/oscar.py", line 861, in _cbConnectService
    d.arm()
exceptions.AttributeError: Deferred instance has no attribute 'arm'

<details><summary>Searchable metadata</summary>

```
trac-id__1529 1529
type__defect defect
reporter__yacc yacc
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__words words
keywords__traceback_defered_arm traceback defered.arm
time__1141286683000000 1141286683000000
changetime__1141286961000000 1141286961000000
version__ 
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|<img alt="yacc's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|yacc set status to `closed`|
|-|-|

oops, mixed different Twisted revisions via PYTHONPATH.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
