### ISSUE TITLE
QtReactor Problems with Modal Dialogs

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#11070]
|<img alt="mustafa's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| mustafa reported|
|-|-|
|Trac ID|trac#1531|
|Type|defect|
|Created|2006-03-02 16:39:28Z|

I am using a pb client and a pb server. My client uses the twisted's qtreactor. Since twisted 2.0, modal dialogs cause _"connection lost"_ and I couldn't overcome this problem for months. I tested this behaviour in twisted 1.3, 2.0, 2.1 and finally 2.2.

When I use **twisted 1.3, no problem occurs**, the other versions**(2.0, 2.1, 2.2)** all cause the same error.

```
Traceback (most recent call last):
 File "/usr/lib/python2.4/site-packages/twisted/internet/defer.py", line 294, in _startRunCallbacks
   self._runCallbacks()
 File "/usr/lib/python2.4/site-packages/twisted/internet/defer.py", line 307, in _runCallbacks
   self.result = callback(self.result, *args, **kw)
 File "qttestclient.py", line 39, in success
   return self.openModalDialog(None)
 File "qttestclient.py", line 56, in openModalDialog
   return dialog.exec_loop()
--- <exception caught here> ---
 File "/usr/lib/python2.4/site-packages/twisted/internet/qtreactor.py", line 60, in read
   why = w.doRead()
 File "/usr/lib/python2.4/site-packages/twisted/internet/tcp.py", line 349, in doRead
   return self.protocol.dataReceived(data)
 File "/usr/lib/python2.4/site-packages/twisted/spread/banana.py", line 173, in dataReceived
   gotItem(self.incomingVocabulary[num])
 File "/usr/lib/python2.4/site-packages/twisted/spread/banana.py", line 114, in gotItem
   self.callExpressionReceived(item)
 File "/usr/lib/python2.4/site-packages/twisted/spread/banana.py", line 81, in callExpressionReceived
   self.expressionReceived(obj)
 File "/usr/lib/python2.4/site-packages/twisted/spread/pb.py", line 567, in expressionReceived
   raise ProtocolError("Non-list expression received.")
twisted.spread.pb.ProtocolError: Non-list expression received.
error received: [Failure instance: Traceback (failure with no frames): twisted.spread.pb.PBConnectionLost: [Failure instance: Traceback (failure with no frames): twisted.spread.pb.ProtocolError: Non-list expression received.
]
]
Lost: Non-list expression received.
```

Attachments:

* [qttestclient.py](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/a7d/a7d3048f93d82e2e3dd337ea701ef07704939a3b/642e699ff84ec1c6ebc861ceb381a7685521ce6f.py) (1897 bytes) - added by mustafa on 2006-03-02 16:40:18Z - 
* [testserver.py](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/a7d/a7d3048f93d82e2e3dd337ea701ef07704939a3b/cecb0481021dca2649768126aaec4843dd2fb65b.py) (1034 bytes) - added by mustafa on 2006-03-02 16:40:50Z - 

<details><summary>Searchable metadata</summary>

```
trac-id__1531 1531
type__defect defect
reporter__mustafa mustafa
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__wontfix wontfix
component__core core
keywords__qtreactor_modal_dialog qtreactor modal dialog
time__1141317568000000 1141317568000000
changetime__1169008617000000 1169008617000000
version__ 
owner__ 
cc__warner cc__mustafa
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun commented|
|-|-|

This is basically due to the fact that using Qt's modal dialogs in this manner requires support for a re-entrant mainloop.  Twisted doesn't support this, though it may have accidentally worked in the past.

I've heard rumors that there is another way to drive modal dialogs in Qt, one that doesn't involve an explicit call to exec_loop()?  I don't really use Qt though so I don't know much more than this.

**Comment by twisted-trac** [comment]
|[<img alt="warner's avatar" src="https://avatars.githubusercontent.com/u/27146?s=50" width="50" height="50">](https://github.com/warner)<a name="note_2"></a>|@warner set owner to @glyph|
|-|-|

I do not have any experience with Qt either.

This isn't a PB-specific problem.. any socket-using code will suffer from this.

Do we have a Qt expert in the house?

**Comment by twisted-trac** [comment]
|[<img alt="warner's avatar" src="https://avatars.githubusercontent.com/u/27146?s=50" width="50" height="50">](https://github.com/warner)<a name="note_3"></a>|@warner set owner to @warner|
|-|-|

gah, I didn't tell trac to change the owner.. sorry glyph.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_4"></a>|@exarkun set status to `closed`|
|-|-|

No, no Qt developers around.  Qt reactor is also no longer even part of the main Twisted distribution.  _And_ using modal dialogs in this way was never supported anyhow.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
