### ISSUE TITLE
Calling reactor.stop() in shutdown function causes hard-to-understand error message

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#11080]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)| @itamarst reported|
|-|-|
|Trac ID|trac#1485|
|Type|defect|
|Created|2006-02-14 03:46:08Z|

<details><summary>Searchable metadata</summary>

```
trac-id__1485 1485
type__defect defect
reporter__itamarst itamarst
priority__high high
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__ 
time__1139888768000000 1139888768000000
changetime__1221617529000000 1221617529000000
version__ 
owner__ 
cc__itamarst cc__thijs
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)|@itamarst commented|
|-|-|

```
#!html
<pre>
Specifically, if the shutdown function returns a Deferred, and some later code
calls reactor.stop(). Ideally it should say something like "don't do that."
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_2"></a>|@therve commented|
|-|-|

I think that is more or less solved. See the following script:

```
from twisted.internet import reactor

if __name__ == "__main__":
    reactor.addSystemEventTrigger('after', 'shutdown', reactor.stop)
    reactor.callLater(0.5, reactor.stop)
    reactor.run()
```

which produces the following output:

```
Traceback (most recent call last):
  File "/home/th/twisted_dev/twisted/trunk/twisted/internet/base.py", line 376, in fireEvent
    DeferredList(beforeResults).addCallback(self._continueFiring)
  File "/home/th/twisted_dev/twisted/trunk/twisted/internet/defer.py", line 191, in addCallback
    callbackKeywords=kw)
  File "/home/th/twisted_dev/twisted/trunk/twisted/internet/defer.py", line 182, in addCallbacks
    self._runCallbacks()
  File "/home/th/twisted_dev/twisted/trunk/twisted/internet/defer.py", line 317, in _runCallbacks
    self.result = callback(self.result, *args, **kw)
--- <exception caught here> ---
  File "/home/th/twisted_dev/twisted/trunk/twisted/internet/base.py", line 389, in _continueFiring
    callable(*args, **kwargs)
  File "/home/th/twisted_dev/twisted/trunk/twisted/internet/base.py", line 480, in stop
    raise RuntimeError, "can't stop reactor that isn't running"
exceptions.RuntimeError: can't stop reactor that isn't running
```


At least, the error is more clear.

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_3"></a>|@thijstriemstra set status to `closed`|
|-|-|

And nowadays it looks like:

```
Traceback (most recent call last):
  File "/twisted/internet/base.py", line 374, in fireEvent
    DeferredList(beforeResults).addCallback(self._continueFiring)
  File "/twisted/internet/defer.py", line 195, in addCallback
    callbackKeywords=kw)
  File "/twisted/internet/defer.py", line 186, in addCallbacks
    self._runCallbacks()
  File "/twisted/internet/defer.py", line 328, in _runCallbacks
    self.result = callback(self.result, *args, **kw)
--- <exception caught here> ---
  File "/twisted/internet/base.py", line 387, in _continueFiring
    callable(*args, **kwargs)
  File "/twisted/internet/base.py", line 527, in stop
    "Can't stop reactor that isn't running.")
twisted.internet.error.ReactorNotRunning: Can't stop reactor that isn't running.
```

Closing this ticket because it doesn't describe the text of the error message, making it impossible to verify if it was fixed or not. Reopen with a more detailed description if necessary.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
