### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'connectionLost'

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#11081]
|<img alt="miro's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| miro reported|
|-|-|
|Trac ID|trac#1486|
|Type|defect|
|Created|2006-02-14 09:47:28Z|

Attachments:

* [sshserver.py](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/896/89606b3e6179739f7ed413b20dd9583b33fa9e75/4df6097851b6d1cace1502314e5eeb97e1c19eee.py) (5072 bytes) - added by miro on 2006-02-14 09:47:27Z - 

<details><summary>Searchable metadata</summary>

```
trac-id__1486 1486
type__defect defect
reporter__miro miro
priority__highest highest
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__conch conch
keywords__ 
time__1139910448000000 1139910448000000
changetime__1151017317000000 1151017317000000
version__ 
owner__ 
cc__exarkun cc__miro cc__itamarst cc__therve
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="miro's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|miro commented|
|-|-|

```
#!html
<pre>
sshserver.py from "Twisted Network Programming Essentials"
throws AttributeError when run on Fedora Core 4
after invoking terminal.looseConnection()
witin a class that extends recvline.HistoricRecvLine.

Same code runs fine on windows (W2K).

Environment on both systems:
Python 2.4.1 with latest Twisted (2.2) and Conch (0.6.0).

sshserver source attached, see trace below.

Miro

[miro@t42 ch10]$ python sshserver.py
Traceback (most recent call last):
  File "/usr/lib/python2.4/site-packages/twisted/python/context.py", line 59, in
callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.4/site-packages/twisted/python/context.py", line 37, in
callWithContext
    return func(*args,**kw)
  File "/usr/lib/python2.4/site-packages/twisted/conch/ssh/service.py", line 42,
in packetReceived
    f(packet)
  File "/usr/lib/python2.4/site-packages/twisted/conch/ssh/connection.py", line
139, in ssh_CHANNEL_DATA
    log.callWithLogger(channel, channel.dataReceived, data)
--- &lt;exception caught here> ---
  File "/usr/lib/python2.4/site-packages/twisted/python/log.py", line 58, in
callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/lib/python2.4/site-packages/twisted/python/log.py", line 43, in
callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/lib/python2.4/site-packages/twisted/python/context.py", line 59, in
callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.4/site-packages/twisted/python/context.py", line 37, in
callWithContext
    return func(*args,**kw)
  File "/usr/lib/python2.4/site-packages/twisted/conch/ssh/session.py", line
107, in dataReceived
    self.client.transport.write(data)
  File "/usr/lib/python2.4/site-packages/twisted/conch/ssh/session.py", line
154, in write
    self.proto.dataReceived(data)
  File "/usr/lib/python2.4/site-packages/twisted/conch/insults/insults.py", line
390, in dataReceived
    self.terminalProtocol.keystrokeReceived(ch, None)
  File "/usr/lib/python2.4/site-packages/twisted/conch/recvline.py", line 191,
in keystrokeReceived
    m()
  File "/usr/lib/python2.4/site-packages/twisted/conch/recvline.py", line 320,
in handle_RETURN
    return RecvLine.handle_RETURN(self)
  File "/usr/lib/python2.4/site-packages/twisted/conch/recvline.py", line 249,
in handle_RETURN
    self.lineReceived(line)
  File "sshserver.py", line 43, in lineReceived
    if not quitting: self.showPrompt()
  File "sshserver.py", line 21, in showPrompt
    self.terminal.write("$ ")
  File "/usr/lib/python2.4/site-packages/twisted/conch/insults/insults.py", line
687, in write
    self.transport.write(lines[0])
  File "/usr/lib/python2.4/site-packages/twisted/conch/ssh/session.py", line
203, in write
    self.session.write(data)
  File "/usr/lib/python2.4/site-packages/twisted/conch/ssh/channel.py", line
163, in write
    self.loseConnection() # try again
  File "/usr/lib/python2.4/site-packages/twisted/conch/ssh/session.py", line
129, in loseConnection
    self.client.transport.loseConnection()
  File "/usr/lib/python2.4/site-packages/twisted/conch/ssh/session.py", line
160, in loseConnection
    self.proto.connectionLost(protocol.connectionDone)
  File "/usr/lib/python2.4/site-packages/twisted/conch/insults/insults.py", line
706, in connectionLost
    self.terminalProtocol.connectionLost(reason)
exceptions.AttributeError: 'NoneType' object has no attribute 'connectionLost'
Traceback (most recent call last):
  File "/usr/lib/python2.4/site-packages/twisted/python/context.py", line 59, in
callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.4/site-packages/twisted/python/context.py", line 37, in
callWithContext
    return func(*args,**kw)
  File "/usr/lib/python2.4/site-packages/twisted/conch/ssh/service.py", line 42,
in packetReceived
    f(packet)
  File "/usr/lib/python2.4/site-packages/twisted/conch/ssh/connection.py", line
166, in ssh_CHANNEL_CLOSE
    log.callWithLogger(channel, channel.closeReceived)
--- &lt;exception caught here> ---
  File "/usr/lib/python2.4/site-packages/twisted/python/log.py", line 58, in
callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/lib/python2.4/site-packages/twisted/python/log.py", line 43, in
callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/lib/python2.4/site-packages/twisted/python/context.py", line 59, in
callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.4/site-packages/twisted/python/context.py", line 37, in
callWithContext
    return func(*args,**kw)
  File "/usr/lib/python2.4/site-packages/twisted/conch/ssh/channel.py", line
129, in closeReceived
    self.loseConnection()
  File "/usr/lib/python2.4/site-packages/twisted/conch/ssh/session.py", line
129, in loseConnection
    self.client.transport.loseConnection()
  File "/usr/lib/python2.4/site-packages/twisted/conch/ssh/session.py", line
160, in loseConnection
    self.proto.connectionLost(protocol.connectionDone)
  File "/usr/lib/python2.4/site-packages/twisted/conch/insults/insults.py", line
706, in connectionLost
    self.terminalProtocol.connectionLost(reason)
exceptions.AttributeError: 'NoneType' object has no attribute 'connectionLost'
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun commented|
|-|-|

Which real-world event precipitates this traceback?  The user typing "quit"?  I haven't managed to reproduce this so far.  I'll see if I can find a FC4 box to test it on.

**Comment by twisted-trac** [comment]
|<img alt="miro's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|miro commented|
|-|-|

Correct. You should be able to reproduce it by typing "quit" on FC4. I suspect
the behavior should be the same on other similar Linux flavors.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun removed owner|
|-|-|

I still can't reproduce this.  I'm going to need some help to deal with this issue.

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)|@therve commented|
|-|-|

I can't reproduce it either (Ubuntu Dapper and Debian Etch).

By looking at the traceback, I don't see how can this still happen: it was fixed in [13542]. It should have been resolved.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun set status to `closed`|
|-|-|

Cool.  Miro sent me an email saying he also couldn't reproduce it on a more recent system or with a more recent Twisted.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
