### ISSUE TITLE
selectreactor 'winsock error'

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#11207]
|[<img alt="ghazel's avatar" src="https://avatars.githubusercontent.com/u/31402?s=50" width="50" height="50">](https://github.com/ghazel)| @ghazel reported|
|-|-|
|Trac ID|trac#1725|
|Type|defect|
|Created|2006-05-18 20:10:13Z|

Win98

 Traceback (most recent call last):
   ...
   File "twisted\internet\reactor.pyc", line 12, in ?
   File "twisted\internet\selectreactor.pyc", line 231, in install
   File "twisted\internet\posixbase.pyc", line 156, in __init__
   File "twisted\internet\base.pyc", line 268, in __init__
   File "twisted\internet\base.pyc", line 568, in _initThreads
   File "twisted\internet\posixbase.pyc", line 253, in installWaker
   File "twisted\internet\posixbase.pyc", line 69, in __init__
   File "socket.pyc", line 156, in __init__
 socket.error: (10106, 'winsock error')

<details><summary>Searchable metadata</summary>

```
trac-id__1725 1725
type__defect defect
reporter__ghazel ghazel
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__wontfix wontfix
component__core core
keywords__ 
time__1147983013000000 1147983013000000
changetime__1148692489000000 1148692489000000
version__ 
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)|@glyph set status to `closed`|
|-|-|

Win98 is not a supported platform, sorry.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
