### ISSUE TITLE
conch script does not work on Windows

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#11211]
|<img alt="synapsis's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| synapsis reported|
|-|-|
|Trac ID|trac#1679|
|Type|defect|
|Created|2006-04-29 16:22:25Z|

The conch (and cftp) script does not work on Windows.
There is a specific reason for this? Or simply it can be done?

Attachments:

* [conch.py](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/64e/64e89c002d47826fd7e23d43e239e4ee0d583896/5f61b4d05b3e94af880bbdef70a3aab159f8197a.py) (24921 bytes) - added by synapsis on 2006-09-24 20:54:23Z - 

<details><summary>Searchable metadata</summary>

```
trac-id__1679 1679
type__defect defect
reporter__synapsis synapsis
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__duplicate duplicate
component__conch conch
keywords__ 
time__1146327745000000 1146327745000000
changetime__1160498723000000 1160498723000000
version__ 
owner__synapsis synapsis
cc__synapsis
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)<a name="note_1"></a>|@jml set owner to synapsis|
|-|-|

Hi synapsis, 

Is this the same as [#7421](https://github.com/twisted/twisted/issues/7421)?  If not, can you please explain exactly how the conch and cftp scripts misbehave on Windows?  

Thanks,
jml

**Comment by twisted-trac** [comment]
|<img alt="synapsis's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_3"></a>|synapsis commented|
|-|-|

Replying to [jml](#note_1):
> Hi synapsis, 
> 
> Is this the same as [#7421](https://github.com/twisted/twisted/issues/7421)?  

It seems so.
However I got this traceback:

Traceback (most recent call last):
  File "C:\Python2.4\Scripts\conch.py", line 20, in ?
    from twisted.conch.scripts.conch import run
  File "C:\Python2.4\lib\site-packages\twisted\conch\scripts\conch.py", line 18,
 in ?
    import os, sys, getpass, struct, tty, fcntl, base64, signal, stat, errno
  File "C:\Python2.4\lib\tty.py", line 5, in ?
    from termios import *
ImportError: No module named termios

The same error with cftp.

> If not, can you please explain exactly how the conch and cftp scripts misbehave on Windows?  
> 

The problem is the same.
I think Conch needs some layer of abstraction over the terminal.

I have tried to remove all POSIX specific stuff from twisted.conch.scripts.conch, but now I obtain:

F:\home\manlio\Documenti\Projects\local\languages\Python\Test\twisted>conch --no
tty --noshell python.it
Traceback (most recent call last):
  File "F:\home\manlio\Documenti\Projects\local\languages\Python\Test\twisted\co
nch.py", line 530, in ?
    run()
  File "F:\home\manlio\Documenti\Projects\local\languages\Python\Test\twisted\co
nch.py", line 121, in run
    doConnect()
  File "F:\home\manlio\Documenti\Projects\local\languages\Python\Test\twisted\co
nch.py", line 176, in doConnect
    connect.connect(host, port, options, vhk, uao).addErrback(_ebExit)
  File "C:\Python2.4\lib\site-packages\twisted\conch\client\connect.py", line 13
, in connect
    userAuthObject)
  File "C:\Python2.4\lib\site-packages\twisted\conch\client\connect.py", line 20
, in _ebConnect
    d = f(host, port, options, vhk, uao)
  File "C:\Python2.4\lib\site-packages\twisted\conch\client\unix.py", line 395,
in connect
    reactor.connectUNIX(filename, factory, timeout=2, checkPID=1)
  File "C:\Python2.4\lib\site-packages\twisted\internet\posixbase.py", line 341,
 in connectUNIX
    assert unixEnabled, "UNIX support is not present"
AssertionError: UNIX support is not present


I have hacked the source, inserting pieces of code from tkconch and I manage to obtain a working conch; it connects to a remote server, display its output but unfortunately I can't write anything (source code attached).

> Thanks,
> jml


Thanks to you
Manlio Perillo

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_4"></a>|@exarkun set status to `closed`|
|-|-|

Seems like a duplicate of [#7421](https://github.com/twisted/twisted/issues/7421) to me.

synapsis, please attach your changes as a unified diff to [#7421](https://github.com/twisted/twisted/issues/7421) if you think there's something useful there.

**Comment by twisted-trac** [comment]
|<img alt="synapsis's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_5"></a>|synapsis commented|
|-|-|

Replying to [exarkun](#note_4):
> Seems like a duplicate of [#7421](https://github.com/twisted/twisted/issues/7421) to me.
> 
> synapsis, please attach your changes as a unified diff to [#7421](https://github.com/twisted/twisted/issues/7421) if you think there's something useful there.

Ok.
I will write a patch (or a specialized version for Windows) once the work on console support for Windows ([#2157](https://github.com/twisted/twisted/issues/2157)) is done.
