### ISSUE TITLE
Failure.__getstate__() does not clean self.value()

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#11215]
|<img alt="moof's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| moof reported|
|-|-|
|Trac ID|trac#1738|
|Type|defect|
|Created|2006-05-22 13:06:35Z|

I have the following error:

```
>>> import socket
>>> e = Exception(socket.socket().makefile())
>>> from twisted.python.failure import Failure
>>> f = Failure(e)
>>> from twisted.spread import jelly
>>> jelly.jelly(f)
Traceback (most recent call last):
  File "<input>", line 1, in ?
  File "C:\Documents and Settings\Moof\My Documents\Partner\Kukaburra\Software adicional\Twisted\twisted\spread\jelly.py", line 879, in jelly
    return _Jellier(taster, persistentStore, invoker).jelly(object)
  File "C:\Documents and Settings\Moof\My Documents\Partner\Kukaburra\Software adicional\Twisted\twisted\spread\jelly.py", line 483, in jelly
    sxp.append(self.jelly(state))
  File "C:\Documents and Settings\Moof\My Documents\Partner\Kukaburra\Software adicional\Twisted\twisted\spread\jelly.py", line 468, in jelly
    sxp.append([self.jelly(key), self.jelly(val)])
  File "C:\Documents and Settings\Moof\My Documents\Partner\Kukaburra\Software adicional\Twisted\twisted\spread\jelly.py", line 483, in jelly
    sxp.append(self.jelly(state))
  File "C:\Documents and Settings\Moof\My Documents\Partner\Kukaburra\Software adicional\Twisted\twisted\spread\jelly.py", line 468, in jelly
    sxp.append([self.jelly(key), self.jelly(val)])
  File "C:\Documents and Settings\Moof\My Documents\Partner\Kukaburra\Software adicional\Twisted\twisted\spread\jelly.py", line 464, in jelly
    sxp.append(self.jelly(item))
  File "C:\Documents and Settings\Moof\My Documents\Partner\Kukaburra\Software adicional\Twisted\twisted\spread\jelly.py", line 489, in jelly
    raise NotImplementedError("Don't know the type: %s" % objType)
NotImplementedError: Don't know the type: <class 'socket._fileobject'>
```

Possible solutions:

 * _Naive:_ in ```Failure.__getstate__```, replace ```state.value``` with ```safe_repr(state.value)```
 * _Equally Naive:_ replace ```state.value``` with ```safe_str(state.value)```
 * _Slightly saner:_ Only do the above if it's a type of object that jelly can't process (ie. has no obvious ```__getstate__``` and ```__setstate__```, or is builtin)
 * _Possibly even saner:_ have a ```.safeCleanFailure()``` which does the above
 * _More thought required:_ Maybe this is a Jelly problem, or something that needs noting in docs and that the protocol implementor needs to be aware of

Is ```.value``` used as an object after being jellied somewhere? or is ```safe_repr``` or ```safe_str``` the way to go?

Right now, my error serialisation code is doing the Naive implementation if jelly raises an exception, and seems to be working for my uses.

Attachments:

* [test_failure.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/754/75499e2e72acfa9011fef6ea0a0994c19707ee4f/59a7dbbc008889b47b76c6c1a02e07e6f2d12b5a.patch) (923 bytes) - added by moof on 2006-05-22 13:07:43Z - Patch for test_failure.py with the error in question

<details><summary>Searchable metadata</summary>

```
trac-id__1738 1738
type__defect defect
reporter__moof moof
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__ 
time__1148303195000000 1148303195000000
changetime__1215968114000000 1215968114000000
version__ 
owner__ 
cc__spiv cc__thijs
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="spiv's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|spiv set owner to @warner|
|-|-|

You typoed "2006" in your patch ;)

Ideally, an exception value of tuples, lists, strings and numbers wouldn't need to be collapsed to a single repr, and changing the behaviour of how Exception([1,2]) is serialised is likely to be a backwards-compatibility problem.

But clearly arbitrary objects are unacceptable.  Some thought is required... assigning to warner for his opinion.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun commented|
|-|-|

I don't think this is actually a PB issue.  Failure.cleanFailure() isn't for PB.  It's for eliminating local reference cycles to prevent uncollectable garbage leaks.

It seems like it should just repr() or str() the value and not worry about doing anything else.

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_3"></a>|@thijstriemstra commented|
|-|-|

I can't reproduce your error with r24264:

```
Python 2.5.2 Stackless 3.1b3 060516 (python-2.52:61022, Feb 27 2008, 16:52:03) 
[GCC 4.0.1 (Apple Computer, Inc. build 5341)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> e = Exception(socket.socket().makefile())
>>> from twisted.python.failure import Failure
>>> f = Failure(e)
>>> from twisted.spread import jelly
>>> jelly.jelly(f)
['twisted.python.failure.Failure', ['dictionary', ['count', 1], ['parents', ['list', 'exceptions.BaseException', '__builtin__.object', 'exceptions.Exception']], ['frames', ['list']], ['type', ['class', 'exceptions.Exception']], ['tb', ['None']], ['stack', ['list']], ['value', ['exceptions.Exception', ['dictionary']]], ['pickled', 1]]]
>>> 
```

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_4"></a>|@therve set status to `closed`|
|-|-|

Looks good. Please reopen if the problem is not solved.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
