### ISSUE TITLE
PyLucene doesn't close write indexes properly

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#11219]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#1711|
|Type|defect|
|Created|2006-05-11 14:03:11Z|

This causes a lock to remain in the system which prevents the index from being opened by subsequent runs with this traceback:

```
2006/05/11 04:13 EDT [-] Traceback (most recent call last):
          File "/home/divmod/Projects/Divmod/trunk/Axiom/axiom/batch.py", line 1037, in step
            itemHasMore = item.store.transact(item.step, style=self.style, skip=self.suspended)
          File "/home/divmod/Projects/Divmod/trunk/Axiom/axiom/store.py", line 964, in transact  
            result = f(*a, **k)
          File "/home/divmod/Projects/Divmod/trunk/Axiom/axiom/batch.py", line 254, in step
            if listener.step():
          File "/home/divmod/Projects/Divmod/trunk/Axiom/axiom/batch.py", line 220, in step
            self._doOneWork(workUnit, _ForwardProcessingFailure)
        --- <exception caught here> ---
          File "/home/divmod/Projects/Divmod/trunk/Axiom/axiom/batch.py", line 194, in _doOneWork
            self.listener.processItem(workUnit)
          File "/home/divmod/Projects/Divmod/trunk/Mantissa/xmantissa/fulltext.py", line 88, in processItem
            self._index = self.openWriteIndex()
          File "/home/divmod/Projects/Divmod/trunk/Mantissa/xmantissa/fulltext.py", line 349, in openWriteIndex
            PyLucene.IndexWriter(fsdir, analyzer, create),
          File "/usr/lib/python2.4/site-packages/PyLucene.py", line 2261, in __init__
            newobj = _PyLucene.new_IndexWriter(*args)
        PyLucene.JavaError: java.io.IOException: Lock obtain timed out: Lock@/tmp/lucene-b5448e9f96c58cc68d1130b92e20136c-write.lock
```

This also slows down message delivery by several orders of magnitudes.  I'm not sure what right API is to clean these up or prevent them from being created in the first place.

<details><summary>Searchable metadata</summary>

```
trac-id__1711 1711
type__defect defect
reporter__exarkun exarkun
priority__high high
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__invalid invalid
component__core core
keywords__ 
time__1147356191000000 1147356191000000
changetime__1147356227000000 1147356227000000
version__ 
owner__amir amir

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun set status to `closed`|
|-|-|
