### ISSUE TITLE
xmlrpc.QueryFactory failed to catch some exceptions

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#11268]
|<img alt="maoy's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| maoy reported|
|-|-|
|Trac ID|trac#914|
|Type|defect|
|Created|2005-03-09 11:14:53Z|

<details><summary>Searchable metadata</summary>

```
trac-id__914 914
type__defect defect
reporter__maoy maoy
priority__high high
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__duplicate duplicate
component__web web
keywords__ 
time__1110366893000000 1110366893000000
changetime__1212781689000000 1212781689000000
version__ 
owner__ 
cc__exarkun cc__itamarst cc__maoy cc__oubiwann
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="maoy's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|maoy commented|
|-|-|

```
#!html
<pre>
[QueryProtocol,client] Traceback (most recent call last):
      File "/usr/lib/python2.3/site-packages/twisted/python/log.py", line 65, in
callWithLogger
        callWithContext({"system": lp}, func, *args, **kw)
      File "/usr/lib/python2.3/site-packages/twisted/python/log.py", line 52, in
callWithContext
        return context.call({ILogContext: newCtx}, func, *args, **kw)
      File "/usr/lib/python2.3/site-packages/twisted/python/context.py", line
43, in callWithContext
        return func(*args,**kw)
      File "/usr/lib/python2.3/site-packages/twisted/internet/default.py", line
535, in _doReadOrWrite
        why = getattr(selectable, method)()
    --- &lt;exception caught here> ---
      File "/usr/lib/python2.3/site-packages/twisted/internet/tcp.py", line 98,
in doRead
        return Connection.doRead(self)
      File "/usr/lib/python2.3/site-packages/twisted/internet/tcp.py", line 239,
in doRead
        data = self.socket.recv(self.bufferSize)
    SSL.SysCallError: (104, 'Connection reset by peer')

2005/03/08 23:27 EST [QueryProtocol,client] Traceback (most recent call last):
      File "/usr/lib/python2.3/site-packages/twisted/application/app.py", line
90, in runReactorWithLogging
        reactor.run()
      File "/usr/lib/python2.3/site-packages/twisted/internet/default.py", line
126, in run
        self.mainLoop()
      File "/usr/lib/python2.3/site-packages/twisted/internet/default.py", line
137, in mainLoop
        self.doIteration(t)
      File "/usr/lib/python2.3/site-packages/twisted/internet/default.py", line
526, in doSelect
        _logrun(selectable, _drdw, selectable, method, dict)
    --- &lt;exception caught here> ---
      File "/usr/lib/python2.3/site-packages/twisted/python/log.py", line 65, in
callWithLogger
        callWithContext({"system": lp}, func, *args, **kw)
      File "/usr/lib/python2.3/site-packages/twisted/python/log.py", line 52, in
callWithContext
        return context.call({ILogContext: newCtx}, func, *args, **kw)
      File "/usr/lib/python2.3/site-packages/twisted/python/context.py", line
43, in callWithContext
        return func(*args,**kw)
      File "/usr/lib/python2.3/site-packages/twisted/internet/default.py", line
549, in _doReadOrWrite
        selectable.connectionLost(f)
      File "/usr/lib/python2.3/site-packages/twisted/internet/tcp.py", line 454,
in connectionLost
        Connection.connectionLost(self, reason)
      File "/usr/lib/python2.3/site-packages/twisted/internet/tcp.py", line 294,
in connectionLost
        protocol.connectionLost(reason)
      File "/usr/lib/python2.3/site-packages/twisted/protocols/http.py", line
361, in connectionLost
        self.handleResponseEnd()
      File "/usr/lib/python2.3/site-packages/twisted/protocols/http.py", line
367, in handleResponseEnd
        self.handleResponse(b)
      File "/usr/lib/python2.3/site-packages/twisted/web/xmlrpc.py", line 271,
in handleResponse
        self.factory.parseResponse(contents)
      File "/usr/lib/python2.3/site-packages/twisted/web/xmlrpc.py", line 296,
in parseResponse
        response = xmlrpclib.loads(contents)
      File "/usr/lib/python2.3/xmlrpclib.py", line 1013, in loads
        p.close()
      File "/usr/lib/python2.3/xmlrpclib.py", line 531, in close
        self._parser.Parse("", 1) # end of data
    xml.parsers.expat.ExpatError: no element found: line 1, column 0
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="maoy's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|maoy commented|
|-|-|

```
#!html
<pre>
The direct consequence of this bug is that errback of Proxy.callRemote() doesn't
catch all the exceptions.
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)<a name="note_5"></a>|@itamarst set owner to @oubiwann|
|-|-|

Also need to verify whether web2 has same bug.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_6"></a>|@exarkun set status to `closed`|
|-|-|

This is a duplicate of [#10568](https://github.com/twisted/twisted/issues/10568)

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
