### ISSUE TITLE
posixbase win32 waker problem

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#11289]
|<img alt="antony's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| antony reported|
|-|-|
|Trac ID|trac#1344|
|Type|defect|
|Created|2005-11-30 23:24:31Z|

Attachments:

* [eagain.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/bf1/bf106f603f5a1ca065cb9438fb4eae247d89aef3/acee52111c34c9460740c5d8a871a2193d0af404.patch) (1132 bytes) - added by exarkun on 2006-01-08 02:49:38Z - 

<details><summary>Searchable metadata</summary>

```
trac-id__1344 1344
type__defect defect
reporter__antony antony
priority__high high
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__ 
time__1133393071000000 1133393071000000
changetime__1137993432000000 1137993432000000
version__ 
owner__ 
cc__exarkun cc__itamarst cc__etrepum cc__antony
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="antony's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|antony commented|
|-|-|

```
#!html
<pre>
Using threadedselectreactor on win32, sometimes I get this error:
  Traceback (most recent call last):
    File "C:\Python23\Lib\site-packages\wx-2.6-msw-unicode\wx\_core.py", line
7493, in MainLoop
      wx.PyApp.MainLoop(self)
    File "C:\Python23\Lib\site-packages\wx-2.6-msw-unicode\wx\_core.py", line
6926, in MainLoop
      return _core_.PyApp_MainLoop(*args, **kwargs)
    File "C:\Python23\Lib\site-packages\wx-2.6-msw-unicode\wx\_core.py", line
13266, in &lt;lambda>
      lambda event: event.callable(*event.args, **event.kw) )
    File
"C:\Python23\Lib\site-packages\twisted\internet\threadedselectreactor.py", line
241, in _interleave
      self.runUntilCurrent()
  --- &lt;exception caught here> ---
    File "C:\Python23\Lib\site-packages\twisted\internet\base.py", line 541, in
runUntilCurrent
      call.func(*call.args, **call.kw)
    File "C:\Python23\Lib\site-packages\twisted\internet\task.py", line 91, in
__call__
      self._reschedule()
    File "C:\Python23\Lib\site-packages\twisted\internet\task.py", line 108, in
_reschedule
      self.call = reactor.callLater(delay, self)
    File
"C:\Python23\Lib\site-packages\twisted\internet\threadedselectreactor.py", line
116, in callLater
      self.wakeUp()
    File
"C:\Python23\Lib\site-packages\twisted\internet\threadedselectreactor.py", line
112, in wakeUp
      self.waker.wakeUp()
    File "C:\Python23\Lib\site-packages\twisted\internet\posixbase.py", line 85,
in wakeUp
      self.w.send('x')
  socket.error: (10055, 'No buffer space available')
  
  This doesn't seem to be a threadedselectreactor problem, but rather a  problem
that stems from it's use with arbitrary event loops. I suspect  that it happens
when the main thread doesn't respond for some time. I  think that the best way
to deal with it is simply to ignore this error  (in wakeUp), because if the
buffer is full, then the main thread  already knows (or about to find out) that
it needs to wake up, although  maybe the user should be somehow notified that
there is a problem (log  message?).
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="antony's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|antony commented|
|-|-|

```
#!html
<pre>
I recently encountered this condition again, this time without
threadedselectreactor. It seems that it happens when there is not enough memory
available for WINSOCK.DLL (at least according to this:
http://lists.distributed.net/pipermail/rc5/2001-April/034552.html).

I propose solving this by changing posixbase._Win32Waker so that the client
socket is non-blocking. This way, when the socket's buffer is full, wakeUp will
not send anything and will not complain, which is okay because the reactor is
going to wake up anyway.
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun commented|
|-|-|

```
#!html
<pre>
Untested patch attached.

A unit test for this behavior should be written before any fix is applied.
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="antony's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|antony commented|
|-|-|

```
#!html
<pre>
But the error is ENOBUFS, not EAGAIN... no?
Why not make the socket non-blocking?
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun commented|
|-|-|

```
#!html
<pre>
2nd version catches ENOBUFS.

I did it this way because it was less typing.  Does using a non-blocking socket
change anything except the errno of the exception raised?
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="antony's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|antony commented|
|-|-|

```
#!html
<pre>
To my understanding, a non-blocking socket would not raise an exception at all,
it would simply return the number of bytes written, which is 0 when writing
failed. This yields minimum typing, as it only requires changing
client.setblocking(1) to client.setblocking(0).

I don't know for sure if this will prevent the problem, because I don't know how
to recreate it, but I'm guessing that any reason for failing to write other than
the socket having closed should simply return 0 and not raise anything. This
also means that it may be a problem writing a unit test. I suppose what needs to
be done is to make WINSOCK.DLL run out of memory, perhaps by opening many
different sockets and writing stuff into them.
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun commented|
|-|-|

```
#!html
<pre>
In the normal case, it will raise WSAEWOULDBLOCK, not return 0.  I don't know
about the ENOBUFS case.
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun commented|
|-|-|

```
#!html
<pre>
This is probably resolved now.  The socket is now non-blocking, and
WSAEWOULDBLOCK from .send() is handled now.  I don't now if WSAENOBUFS is still
possible from the .send().  I hope not.  If it /is/ still possible, I do not
know how to determine whether there are already bytes queued for delivery, in
which case it is okay to ignore the error, or if the send queue is empty and it
is not okay to ignore the error.

Either way, I am resolving /this/ issue until someone can provide more specific
information, or at least demonstrate the problem is still present.
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
