### ISSUE TITLE
Possible bug in cgi

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#11301]
|[<img alt="oubiwann's avatar" src="https://avatars.githubusercontent.com/u/894251?s=50" width="50" height="50">](https://github.com/oubiwann)| @oubiwann reported|
|-|-|
|Trac ID|trac#560|
|Type|defect|
|Created|2004-03-23 03:36:31Z|

<details><summary>Searchable metadata</summary>

```
trac-id__560 560
type__defect defect
reporter__oubiwann oubiwann
priority__high high
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__ 
keywords__ 
time__1080012991000000 1080012991000000
changetime__1080021347000000 1080021347000000
version__ 
owner__ 
cc__itamarst cc__oubiwann
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="oubiwann's avatar" src="https://avatars.githubusercontent.com/u/894251?s=50" width="50" height="50">](https://github.com/oubiwann)|@oubiwann commented|
|-|-|

```
#!html
<pre>
We created a test server based on the documentation on the web:

from twisted.internet import reactor
from twisted.web import static, server, twcgi

docroot = "/Users/oubiwann/scripts/python/zope_twisted"
cgibin = docroot + '/cgibin'
root = static.File(docroot)
root.putChild("cgi-bin", twcgi.CGIDirectory(cgibin))
reactor.listenTCP(6969, server.Site(root))
reactor.run()

And then ran apachebench against it with the following command:

ab -n 100 -c 10 http://localhost:6969/cgi-bin/test.py

test.py is just a loop of printed text.

Here are the exceptions that were spit out:

Traceback (most recent call last):
  File "test_cgi_server.py", line 9, in ?
    reactor.run()
  File "/usr/local/lib/python2.3/site-packages/twisted/internet/default.py",
line 125, in run
    self.mainLoop()
  File "/usr/local/lib/python2.3/site-packages/twisted/internet/default.py",
line 136, in mainLoop
    self.doIteration(t)
  File "/usr/local/lib/python2.3/site-packages/twisted/internet/default.py",
line 523, in doSelect
    _logrun(selectable, _drdw, selectable, method, dict)
--- &lt;exception caught here> ---
  File "/usr/local/lib/python2.3/site-packages/twisted/python/log.py", line 65,
in callWithLogger
    callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/local/lib/python2.3/site-packages/twisted/python/log.py", line 52,
in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/local/lib/python2.3/site-packages/twisted/python/context.py", line
32, in callWithContext
    return func(*args,**kw)
  File "/usr/local/lib/python2.3/site-packages/twisted/internet/default.py",
line 546, in _doReadOrWrite
    selectable.connectionLost(f)
  File "/usr/local/lib/python2.3/site-packages/twisted/internet/tcp.py", line
282, in connectionLost
    abstract.FileDescriptor.connectionLost(self, reason)
  File "/usr/local/lib/python2.3/site-packages/twisted/internet/abstract.py",
line 72, in connectionLost
    self.producer.stopProducing()
  File "/usr/local/lib/python2.3/site-packages/twisted/web/twcgi.py", line 186,
in stopProducing
    self.transport.stopProducing()
exceptions.AttributeError: Process instance has no attribute 'stopProducing'

This repeats a total of nine times.
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="oubiwann's avatar" src="https://avatars.githubusercontent.com/u/894251?s=50" width="50" height="50">](https://github.com/oubiwann)|@oubiwann commented|
|-|-|

```
#!html
<pre>
I failed to mention that I am running twisted 1.20 on Mac OS X:

uname -a
Darwin mdcitx01.local 7.3.0 Darwin Kernel Version 7.3.0: Fri Mar  5 14:22:55 PST
2004; root:xnu/xnu-517.3.15.obj~4/RELEASE_PPC  Power Macintosh powerpc

python -V
Python 2.3.3

python -c "from twisted.copyright import *;print longversion"
Twisted 1.2.0
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)|@itamarst commented|
|-|-|

```
#!html
<pre>
Should be fixed in svn r10344.
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
