### ISSUE TITLE
ProducerConsumerProxy won't transfer data: "Writing fresh data to consumer before my buffer is empty!"

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#11345]
|[<img alt="ghazel's avatar" src="https://avatars.githubusercontent.com/u/31402?s=50" width="50" height="50">](https://github.com/ghazel)| @ghazel reported|
|-|-|
|Trac ID|trac#1461|
|Type|defect|
|Created|2006-02-01 05:45:20Z|

Attachments:

* [shaper.py](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/8b4/8b4078f9f76081a0c3ce5db983aa4f340ecd7531/ddfc262d140814aa4ef69079d0472481309e5e00.py) (1694 bytes) - added by ghazel on 2006-02-01 05:45:14Z - 

<details><summary>Searchable metadata</summary>

```
trac-id__1461 1461
type__defect defect
reporter__ghazel ghazel
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__ 
component__core core
keywords__ 
time__1138772720000000 1138772720000000
changetime__1210343015000000 1210343015000000
version__ 
owner__ 
cc__ghazel
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="ghazel's avatar" src="https://avatars.githubusercontent.com/u/31402?s=50" width="50" height="50">](https://github.com/ghazel)|@ghazel commented|
|-|-|

```
#!html
<pre>
I tried to test out htb using the shaper.py example in SVN. I changed it a 
little bit to just spew data (see shaper.py, attached), and after trying to use 
wget to download from it locally, I quickly get this:

IPv4Address.__getitem__ is deprecated.  Use attributes instead.
  return transport.getPeer()[1]
Traceback (most recent call last):
  File "shaper.py", line 16, in ?
    import shaper
  File "shaper.py", line 58, in ?
    reactor.run()
  File "C:\Python24\lib\site-packages\twisted\internet\posixbase.py", line 206, 
in run
    self.mainLoop()
  File "C:\Python24\lib\site-packages\twisted\internet\posixbase.py", line 214, 
in mainLoop
    self.runUntilCurrent()
--- &lt;exception caught here> ---
  File "C:\Python24\lib\site-packages\twisted\internet\base.py", line 541, in 
runUntilCurrent
    call.func(*call.args, **call.kw)
  File "shaper.py", line 44, in spewing
    self.transport.write(data)
  File "C:\Python24\lib\site-packages\twisted\protocols\pcp.py", line 166, in 
write
    assert not self._buffer, (
exceptions.AssertionError: Writing fresh data to consumer before my buffer is 
empty!
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_2"></a>|@therve set owner to @therve|
|-|-|

It seems to work fine for me, maybe a windows problem. I'll see what I can do.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
