### ISSUE TITLE
Pb unicode errors get an UnicodeEncodeError crash

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#11341]
|<img alt="rodrigob's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| rodrigob reported|
|-|-|
|Trac ID|trac#456|
|Type|enhancement|
|Created|2003-12-31 10:32:34Z|

<details><summary>Searchable metadata</summary>

```
trac-id__456 456
type__enhancement enhancement
reporter__rodrigob rodrigob
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__ 
component__pb pb
keywords__ 
time__1072866754000000 1072866754000000
changetime__1268666667000000 1268666667000000
version__ 
owner__ 
cc__glyph cc__itamarst cc__warner cc__rodrigob
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="rodrigob's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|rodrigob commented|
|-|-|

```
#!html
<pre>
If an error get an Unicode message, the error will generate a crash in Pb.

This situation is common if the programmer create a debug text based on some data.

This problem is that "str(self.value) # Exception instance" require and
encoding, and the default encoding can fail.

This situation is weird because Pb is supposed to be capable of managing unicode
strings transparently.

Glyph has detected that there is a related python bug
"unicode(Exception(u"\u1234"))" raise the same error. (someone has to post it to
the python comunity)

Traceback (most recent call last):
  File "/usr/local/lib/python2.3/site-packages/twisted/internet/default.py",
line 507, in doSelect
    _logrun(selectable, _drdw, selectable, method, dict)
  File "/usr/local/lib/python2.3/site-packages/twisted/python/log.py", line 65,
in callWithLogger
    callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/local/lib/python2.3/site-packages/twisted/python/log.py", line 52,
in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/local/lib/python2.3/site-packages/twisted/python/context.py", line
32, in callWithContext
    return func(*args,**kw)
--- &lt;exception caught here> ---
  File "/usr/local/lib/python2.3/site-packages/twisted/internet/default.py",
line 516, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "/usr/local/lib/python2.3/site-packages/twisted/internet/tcp.py", line
250, in doRead
    return self.protocol.dataReceived(data)
  File "/usr/local/lib/python2.3/site-packages/twisted/spread/banana.py", line
320, in dataReceived
    processed = cBanana.dataReceived(self.state, buffer,
self.callExpressionReceived)
  File "/usr/local/lib/python2.3/site-packages/twisted/spread/banana.py", line
93, in callExpressionReceived
    self.expressionReceived(obj)
  File "/usr/local/lib/python2.3/site-packages/twisted/spread/pb.py", line 568,
in expressionReceived
    method(*sexp[1:])
  File "/usr/local/lib/python2.3/site-packages/twisted/spread/pb.py", line 879,
in proto_message
    self._recvMessage(self.localObjectForID, requestID, objectID, message,
answerRequired, netArgs, netKw)
  File "/usr/local/lib/python2.3/site-packages/twisted/spread/pb.py", line 901,
in _recvMessage
    self._sendError(f, requestID)
  File "/usr/local/lib/python2.3/site-packages/twisted/spread/pb.py", line 949,
in _sendError
    self.sendCall("error", requestID, self.serialize(fail))
  File "/usr/local/lib/python2.3/site-packages/twisted/spread/pb.py", line 816,
in serialize
    return jelly(object, self.security, None, self)
  File "/usr/local/lib/python2.3/site-packages/twisted/spread/jelly.py", line
845, in jelly
    return _Jellier(taster, persistentStore, invoker).jelly(object)
  File "/usr/local/lib/python2.3/site-packages/twisted/spread/jelly.py", line
407, in jelly
    return obj.jellyFor(self)
  File "/usr/local/lib/python2.3/site-packages/twisted/spread/flavors.py", line
310, in jellyFor
    state = self.getStateToCopyFor(p)
  File "/usr/local/lib/python2.3/site-packages/twisted/spread/flavors.py", line
278, in getStateToCopyFor
    return self.getStateToCopy()
  File "/usr/local/lib/python2.3/site-packages/twisted/spread/pb.py", line 469,
in getStateToCopy
    state['value'] = str(self.value) # Exception instance
exceptions.UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in
position 60: ordinal not in range(128)
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)|@itamarst commented|
|-|-|

```
#!html
<pre>
Two issues here:

1. Exceptions need some way to be sent over the wire. Currently they are
converted to strings, i.e. __str__ is called. Default __str__ can't handle
unicode strings that aren't encodable in current encoding. I suggest
pre-encoding it, e.g. Exception(u"\u1234".encode("utf-8")). Basically, for
standard exceptions there is no way this can (or will) work.

2. Do we want to allow passing more info in exception instances? I think we do,
in which case doing str() on it is rather limiting. I suggest checking if it's
Copyable, and if so sending as is, otherwise converting to string. In current
PB, your Exception class would also inherit from Copyable. 

This needs to be specified in the protocol. Warner?
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="warner's avatar" src="https://avatars.githubusercontent.com/u/27146?s=50" width="50" height="50">](https://github.com/warner)<a name="note_3"></a>|@warner commented|
|-|-|

Ah, this is complex.

Issue [#11338](https://github.com/twisted/twisted/issues/11338): When PB serializes an exception (i.e. str(self.value)), we can catch the UnicodeEncodeError and replace the value with a note that explains what happened. Not helpful but better than crashing.

Issue #2: yeah, that might improve matters. I've been pondering this w.r.t. newpb.

The goal of serializing the exception is to provide an appropriate amount of information to the caller. The calling code might want to look at the exception type and base a decision upon that (which means we have to find a way to safely serialize the type, and unserialize it, which is hard given that we generally refuse to serialize arbitrary instances or classes). For heavily customized exception classes, the calling code might want to examine attributes which have added more information to the object (but subclassing Copyable provides a good way to explicitly indicate how these should be serialized) (but we need a mapping on the deserializing end). The developer on the calling side might want to look at the stack trace (from the callee side) to figure out what they're doing wrong, but the develope on the callee side might not want to expose their code. Likewise a developer might want to look at an even more detailed stack trace, one with local variables, but that's even less likely to be something the callee side is willing to publish.

I'm inclined to say that there's only one CopiedFailure class (which is what the caller gets back from the callee), but that it is populated from a serialized form that's under control of the callee-side Failure object, and there should be a way to have that Failure (or the Exception that it wraps) serialize itself however it likes.

Given that the original problem was just about unicode, I'm going to defer the second issue (and put it on the TODO list for newpb), and let this bug focus on the UnicodeEncodeError. As Itamar pointed out, there's no way for pb to do anything useful with an exception that contains un-encodable strings, so the best we can do is let someone know that there *is* a problem. I'll create a branch to add the catch-and-summarize code I described above. Does that seem like it would be worth the effort?

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_4"></a>|@exarkun commented|
|-|-|

This may be a possibility as well:

```
Index: /home/exarkun/Projects/Twisted/trunk/twisted/spread/pb.py
===================================================================
--- /home/exarkun/Projects/Twisted/trunk/twisted/spread/pb.py   (revision 28736)
+++ /home/exarkun/Projects/Twisted/trunk/twisted/spread/pb.py   (working copy)
@@ -404,7 +404,7 @@
         if isinstance(self.value, failure.Failure):
             state['value'] = failure2Copyable(self.value, self.unsafeTracebacks)
         else:
-            state['value'] = str(self.value) # Exception instance
+            state['value'] = unicode(self.value) # Exception instance
         if isinstance(self.type, str):
             state['type'] = self.type
         else:
```

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
