### ISSUE TITLE
cftp.py fails to transfer files

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#11354]
|<img alt="jaze's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| jaze reported|
|-|-|
|Trac ID|trac#1589|
|Type|defect|
|Created|2006-03-17 20:35:39Z|

```
Unhandled error in Deferred:
Traceback (most recent call last):
  File "/usr/lib/python2.4/site-packages/twisted/internet/defer.py", line 292, i                                                                                                    n unpause
    self._runCallbacks()
  File "/usr/lib/python2.4/site-packages/twisted/internet/defer.py", line 328, i                                                                                                    n _runCallbacks
    self.result = callback(self.result, *args, **kw)
  File "/usr/lib/python2.4/site-packages/twisted/internet/defer.py", line 296, i                                                                                                    n _continue
    self.unpause()
  File "/usr/lib/python2.4/site-packages/twisted/internet/defer.py", line 292, i                                                                                                    n unpause
    self._runCallbacks()
--- <exception caught here> ---
  File "/usr/lib/python2.4/site-packages/twisted/internet/defer.py", line 328, i                                                                                                    n _runCallbacks
    self.result = callback(self.result, *args, **kw)
  File "/usr/lib/python2.4/site-packages/twisted/internet/defer.py", line 296, i                                                                                                    n _continue
    self.unpause()
  File "/usr/lib/python2.4/site-packages/twisted/internet/defer.py", line 292, i                                                                                                    n unpause
    self._runCallbacks()
  File "/usr/lib/python2.4/site-packages/twisted/internet/defer.py", line 345, i                                                                                                    n _runCallbacks
    self.result.cleanFailure()
  File "/usr/lib/python2.4/site-packages/twisted/python/failure.py", line 297, i                                                                                                    n cleanFailure
    self.__dict__ = self.__getstate__()
  File "/usr/lib/python2.4/site-packages/twisted/python/failure.py", line 283, i                                                                                                    n __getstate__
    c['stack'] = [
  File "/usr/lib/python2.4/site-packages/twisted/python/reflect.py", line 448, i                                                                                                    n safe_repr
    failure.Failure().printTraceback(file=io)
  File "/usr/lib/python2.4/site-packages/twisted/python/failure.py", line 171, i                                                                                                    n __init__
    stack.insert(0, [
  File "/usr/lib/python2.4/site-packages/twisted/internet/base.py", line 331, in                                                                                                     sigInt
    log.msg("Received SIGINT, shutting down.")
  File "<twisted.python.hook (macro)>", line 8, in msg

  File "/usr/lib/python2.4/site-packages/twisted/python/threadable.py", line 182                                                                                                    , in _synchPre
    self._threadable_lock.acquire()
exceptions.RuntimeError: maximum recursion depth exceeded
```

<details><summary>Searchable metadata</summary>

```
trac-id__1589 1589
type__defect defect
reporter__jaze jaze
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__conch conch
keywords__ 
time__1142627739000000 1142627739000000
changetime__1293054945000000 1293054945000000
version__2_0 2.0
owner__jaze jaze
cc__spiv cc__exarkun
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_2"></a>|@exarkun set owner to jaze|
|-|-|

jaze, can you explain how or when this happens?  Best would be if you could provide a minimal self-contained example which produces the behavior or a unit test which does so.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_3"></a>|@exarkun set status to `closed`|
|-|-|

[#3927](https://github.com/twisted/twisted/issues/3927) was a duplicate of this.

Also, with [#4593](https://github.com/twisted/twisted/issues/4593) resolved, this should be fixed.
