### ISSUE TITLE
twisted.web.distrib uses deprecated pb classes

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#11381]
|[<img alt="puzzlement's avatar" src="https://avatars.githubusercontent.com/u/94942?s=50" width="50" height="50">](https://github.com/puzzlement)| @puzzlement reported|
|-|-|
|Trac ID|trac#543|
|Type|defect|
|Created|2004-03-06 07:10:23Z|

<details><summary>Searchable metadata</summary>

```
trac-id__543 543
type__defect defect
reporter__hypatia hypatia
priority__high high
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__web web
keywords__ 
time__1078557023000000 1078557023000000
changetime__1113385030000000 1113385030000000
version__ 
owner__ 
cc__warner cc__hypatia
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="puzzlement's avatar" src="https://avatars.githubusercontent.com/u/94942?s=50" width="50" height="50">](https://github.com/puzzlement)|@puzzlement commented|
|-|-|

```
#!html
<pre>
twisted.web.distrib appears to use at least some deprecated PB classes.

Example:

$ python doc/examples/silly-web.py
[ visit http://localhost:19988/ ]
twisted/web/distrib.py:169: DeprecationWarning: This is deprecated. Use
PBClientFactory.
  pb.getObjectAt(self.host, self.port, 10).addCallbacks(self.connected,
self.notConnected)
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)|@glyph commented|
|-|-|

```
#!html
<pre>
This has gotten even better.
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)|@glyph commented|
|-|-|

```
#!html
<pre>
It needs to be updated to more recent pb, saaay, post newpb.  However, the demonstrating case has 
gotten even better.

New example:

glyph@parchment:~/Projects/Twisted/doc/examples% python silly-web.py
/Users/glyph/Projects/Twisted/twisted/web/distrib.py:176: DeprecationWarning: This is deprecated. 
Use PBClientFactory.
  pb.getObjectAt(self.host, self.port, 10).addCallbacks(self.connected, self.notConnected)
/Users/glyph/Projects/Twisted/twisted/web/server.py:122: DeprecationWarning: 
IPv4Address.__getitem__ is deprecated.  Use attributes instead.
  x['host'] = tuple(x['host'])
/Users/glyph/Projects/Twisted/twisted/web/server.py:123: DeprecationWarning: 
IPv4Address.__getitem__ is deprecated.  Use attributes instead.
  x['client'] = tuple(x['client'])
Peer will receive following PB traceback:
Traceback (most recent call last):
  File "/Users/glyph/Projects/Twisted/twisted/spread/banana.py", line 126, in gotItem
    self.callExpressionReceived(item)
  File "/Users/glyph/Projects/Twisted/twisted/spread/banana.py", line 93, in callExpressionReceived
    self.expressionReceived(obj)
  File "/Users/glyph/Projects/Twisted/twisted/spread/pb.py", line 568, in expressionReceived
    method(*sexp[1:])
  File "/Users/glyph/Projects/Twisted/twisted/spread/pb.py", line 879, in proto_message
    self._recvMessage(self.localObjectForID, requestID, objectID, message, answerRequired, netArgs, 
netKw)
--- &lt;exception caught here> ---
  File "/Users/glyph/Projects/Twisted/twisted/spread/pb.py", line 893, in _recvMessage
    netResult = object.remoteMessageReceived(self, message, netArgs, netKw)
  File "/Users/glyph/Projects/Twisted/twisted/spread/flavors.py", line 124, in remoteMessageReceived
    state = method(*args, **kw)
  File "/Users/glyph/Projects/Twisted/twisted/web/distrib.py", line 200, in remote_request
    res = self.site.getResourceFor(request)
  File "/Users/glyph/Projects/Twisted/twisted/web/server.py", line 517, in getResourceFor
    return resource.getChildForRequest(self.resource, request)
  File "/Users/glyph/Projects/Twisted/twisted/web/resource.py", line 62, in getChildForRequest
    resource = resource.getChildWithDefault(pathElement, request)
  File "/Users/glyph/Projects/Twisted/twisted/web/resource.py", line 162, in getChildWithDefault
    return self.getChild(path, request)
  File "/Users/glyph/Projects/Twisted/twisted/web/static.py", line 268, in getChild
    self.restat()
  File "/Users/glyph/Projects/Twisted/twisted/python/filepath.py", line 144, in restat
    self.statinfo = stat(self.path)
exceptions.OSError: [Errno 2] No such file or directory: '/Users/glyph/Projects/Twisted/doc/examples/
static'
Peer will receive following PB traceback:
Traceback (most recent call last):
  File "/Users/glyph/Projects/Twisted/twisted/spread/banana.py", line 126, in gotItem
    self.callExpressionReceived(item)
  File "/Users/glyph/Projects/Twisted/twisted/spread/banana.py", line 93, in callExpressionReceived
    self.expressionReceived(obj)
  File "/Users/glyph/Projects/Twisted/twisted/spread/pb.py", line 568, in expressionReceived
    method(*sexp[1:])
  File "/Users/glyph/Projects/Twisted/twisted/spread/pb.py", line 879, in proto_message
    self._recvMessage(self.localObjectForID, requestID, objectID, message, answerRequired, netArgs, 
netKw)
--- &lt;exception caught here> ---
  File "/Users/glyph/Projects/Twisted/twisted/spread/pb.py", line 893, in _recvMessage
    netResult = object.remoteMessageReceived(self, message, netArgs, netKw)
  File "/Users/glyph/Projects/Twisted/twisted/spread/flavors.py", line 124, in remoteMessageReceived
    state = method(*args, **kw)
  File "/Users/glyph/Projects/Twisted/twisted/web/distrib.py", line 200, in remote_request
    res = self.site.getResourceFor(request)
  File "/Users/glyph/Projects/Twisted/twisted/web/server.py", line 517, in getResourceFor
    return resource.getChildForRequest(self.resource, request)
  File "/Users/glyph/Projects/Twisted/twisted/web/resource.py", line 62, in getChildForRequest
    resource = resource.getChildWithDefault(pathElement, request)
  File "/Users/glyph/Projects/Twisted/twisted/web/resource.py", line 162, in getChildWithDefault
    return self.getChild(path, request)
  File "/Users/glyph/Projects/Twisted/twisted/web/static.py", line 268, in getChild
    self.restat()
  File "/Users/glyph/Projects/Twisted/twisted/python/filepath.py", line 144, in restat
    self.statinfo = stat(self.path)
exceptions.OSError: [Errno 2] No such file or directory: '/Users/glyph/Projects/Twisted/doc/examples/
static'
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="warner's avatar" src="https://avatars.githubusercontent.com/u/27146?s=50" width="50" height="50">](https://github.com/warner)|@warner commented|
|-|-|

```
#!html
<pre>
shouldn't we update it to modern oldpb first? I'd like to cause as little
collateral damage with newpb as possible :)
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="warner's avatar" src="https://avatars.githubusercontent.com/u/27146?s=50" width="50" height="50">](https://github.com/warner)|@warner commented|
|-|-|

```
#!html
<pre>
I've just added a test case which at least provokes the deprecation message.
If no one complains, I'll see about updating distrib to use (oldpb)
PBClientFactory . When newpb is available, it should be little effort to move it
from (oldpb) PBClientFactory to (newpb) PBClientFactory.
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="warner's avatar" src="https://avatars.githubusercontent.com/u/27146?s=50" width="50" height="50">](https://github.com/warner)|@warner commented|
|-|-|

```
#!html
<pre>
finally fixed this. The wire format of web.distrib addresses remains unchanged:
('INET', host, portnum) for TCP, ('UNIX', pathname) for unix-domain sockets.
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
