### ISSUE TITLE
Switch to epydoc 2.0 for API docs

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#11472]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)| @itamarst reported|
|-|-|
|Trac ID|trac#119|
|Type|enhancement|
|Created|2003-07-24 06:37:02Z|

<details><summary>Searchable metadata</summary>

```
trac-id__119 119
type__enhancement enhancement
reporter__itamarst itamarst
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__ 
keywords__ 
time__1059028622000000 1059028622000000
changetime__1060654287000000 1060654287000000
version__ 
owner__ 
cc__moonfallen cc__radix cc__spiv cc__warner
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="spiv's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|spiv commented|
|-|-|

```
#!html
<pre>
I tested epydoc CVS from a few weeks ago, and admin/epyrun
seemed to work just fine with it, so hopefully this will
just be a simple matter of installing the new version...

What might be really nice is if this version is fast enough,
adding an API-doc building buildslave, both so that we can
point bleeding-edge users at current docs for CVS, and also
so that people can see markup warnings from epydoc.

</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="radix's avatar" src="https://avatars.githubusercontent.com/u/227068?s=50" width="50" height="50">](https://github.com/radix)|@radix commented|
|-|-|

```
#!html
<pre>
MoonFallen just tried running epyrun with epydoc 2.0, but it
failed when it started writing the files, because of the
"TwistedHTMLFormatter" hack. It tried calling _write with a
different signature than what's defined in epyrun. 

spiv, can you update the hack with the new API (you wrote
that code, IIRC?)? just send a patch to the tracker here so
I can test with it and if it's good i'll switch to epydoc 2.0.

</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="moonfallen's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|moonfallen commented|
|-|-|

```
#!html
<pre>
I might as well add the full traceback here:

$ python admin/epyrun
... lots and lots and lots of output ...
Writing HTML docs (2852 files) to 'html'.
  [  0%] .Traceback (most recent call last):
  File "admin/epyrun", line 151, in ?
    cli()
  File "C:\python22\Lib\site-packages\epydoc\cli.py", line
93, in cli
    if options['action'] == 'html': _html(docmap, options)
  File "C:\python22\Lib\site-packages\epydoc\cli.py", line
571, in _html
    try: html_doc.write(options['target'], progress.report)
  File "C:\python22\Lib\site-packages\epydoc\html.py", line
469, in write
    progress_callback, uid.is_public(), uid, doc)
TypeError: _write() takes exactly 3 arguments (8 given)

</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="moonfallen's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|moonfallen commented|
|-|-|

```
#!html
<pre>
OK, I tried PDF output, and I got the following.  Don't know
if this is because needed hacks are missing, or because
epydoc has problems with our stuff unrelated to hacks:

$ python admin/epyrun --pdf
... lots and lots etc. ...
Writing LaTeX docs (485 files) to 'pdf'.
  [  0%]
........................................................Traceback
(most
 recent call last):
  File "admin/epyrun", line 151, in ?
    cli()
  File "C:\python22\Lib\site-packages\epydoc\cli.py", line
98, in cli
    elif options['action'] == 'pdf': _latex(docmap, options,
'pdf')
  File "C:\python22\Lib\site-packages\epydoc\cli.py", line
508, in _latex
    latex_doc.write(options['target'], progress.report)
  File "C:\python22\Lib\site-packages\epydoc\latex.py", line
219, in write
    open(filename, 'w').write(self._module_to_latex(uid))
  File "C:\python22\Lib\site-packages\epydoc\latex.py", line
383, in _module_to_
latex
    str += self._class_to_latex(cls.target())
  File "C:\python22\Lib\site-packages\epydoc\latex.py", line
390, in _class_to_l
atex
    doc = self._docmap[uid]
  File "C:\python22\Lib\site-packages\epydoc\objdoc.py",
line 2932, in __getitem
__
    return self.data[key]
KeyError: twisted.enterprise.adbapi.Transaction

</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="spiv's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|spiv commented|
|-|-|

```
#!html
<pre>
radix -- I've checked in an updated admin/epyrun.  It looks
good to me, so if you agree, we can close this issue.

</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="moonfallen's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|moonfallen commented|
|-|-|

```
#!html
<pre>
Yay, epydoc 2.0 works and win32 builds work with epydoc 2.0!

Thanks, spiv.

</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="warner's avatar" src="https://avatars.githubusercontent.com/u/27146?s=50" width="50" height="50">](https://github.com/warner)|@warner commented|
|-|-|

```
#!html
<pre>
I ran some tests.. epyrun currently takes 13 minutes and
130MB of core on my laptop, so I'd rather not put it into a
buildbot pass until it slims down a bit.

What does epydoc do that requires holding the entire
codebase in RAM before it writes anything out?

</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="spiv's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|spiv commented|
|-|-|

```
#!html
<pre>
warner: epydoc holds everything in RAM for cross-linking
purposes, so that it hyperlinks everything it can.  Besides,
it's not the code that takes up all the RAM -- try this:
    find twisted/ -type f | grep .py$ | grep -v \
    "test/process" | sed -e "s/.py$//" | sed -e "s#/#\.#g" \
    | awk "{ printf \"print '%s'\ntry: import %s\nexcept:
pass\n\" , \$1 , \$1 }" > uberimport.py

Then run "import uberimport" at the interpreter.  The RAM
usage only hits 21MB for me.  So the bulk of the memory is
being used by epydoc internals (such as the UID class).

I intend to do some memory profiling at some point to see if
I can slim it down.  Hopefully reducing memory use will
speed it up a bit more, too...

</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="radix's avatar" src="https://avatars.githubusercontent.com/u/227068?s=50" width="50" height="50">](https://github.com/radix)|@radix commented|
|-|-|

```
#!html
<pre>
I generated 1.0.7alpha4's documentation with epydoc2, and
noticed that the size of the documentation has grown a LOT.

% ls -sh TwistedDocs-1.0.7alpha4.tar.bz2 \
  old/TwistedDocs-1.0.7alpha3.tar.bz2
5.8M TwistedDocs-1.0.7alpha4.tar.bz2  
4.4M old/TwistedDocs-1.0.7alpha3.tar.bz2

Man, epydoc is full of frustration. I'll look into it....

</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="radix's avatar" src="https://avatars.githubusercontent.com/u/227068?s=50" width="50" height="50">](https://github.com/radix)|@radix commented|
|-|-|

```
#!html
<pre>
i'm setting this to "done-could be better"

</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="radix's avatar" src="https://avatars.githubusercontent.com/u/227068?s=50" width="50" height="50">](https://github.com/radix)|@radix commented|
|-|-|

```
#!html
<pre>
Ok! All fixed up. No more non-Twisted documentation is
generated, and I got rid of "private" while I was at it.

</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
