### ISSUE TITLE
Support XHTML entities in XMLString

### ISSUE THREAD

**Issue by tristanlatr** [twisted/twisted#11581]
From https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1005338

Need to check if that's still happening with latest version of pydoctor.

**Comment by tristanlatr** [comment]
The bug is probably still active, but here's the workaround: https://salsa.debian.org/agx/git-buildpackage/-/commit/40b96935c1ac0727fa670636f86e36d8c2d76c74

**Comment by tristanlatr** [comment]
@tijuca it would be good that this kind of bugs get reported in this tracker too. I see that you guys just worked around the issue, but having a proper fix is the right thing to do. So hopefully I've clicked around in the debian tracker...

**Comment by tristanlatr** [comment]
For a bit of history of this bug:

This issue happens since we've migrated epydoc to use docutils. 
Because we're now (since twisted/pydoctor#386) using docutils HTML translator combined with `html2stan()` (that uses Twisted `XMLString` to parse HTML). The issue is present from [pydoctor 21.12.1](https://github.com/twisted/pydoctor#id16) to the latest versions. The issue wasn't present before because we used to convert directly from epydoc to HTML, without docutils.

This is not a easy issue to fix... Ideally, we should not rely in `html2stan()` at all and we shoud have our own translator that output stan tag directly. But that's a lot of work, at least, a lot fo code. Alternatively, we could simply replace all problematic caracters in docstrings before parsing them, but that sounds hacky. 

This was likely an issue with `restructuredtext` markup before version 21.12.1, but simply not detected because less people were using `restructuredtext` markup.

**Comment by tijuca** [comment]
Thanks for picking up the issue from the Debian BTS!
The maintainer if the package `git-buildpackage` and I talked about upstreaming the issue after find out the real root for the issue just yesterday. But as I've really no knowledge about how pydoctor is working internally (and it's difficult to debug what's happen under the hood) I did not have an inspiration about what to write into a bug report. And after Guido did realize what's probably broken since the latest upload of a newer pydocter version into the Debian archive we wanted to create a small example to visualize the problem, but you were simply faster in creating this issue here. Thanks again for looking into it.

And yes, the change in `git-buildpackage` it's just a work around to get this package usable.

**Comment by tristanlatr** [comment]
Maybe this issue should be handled at the Twisted level, here: https://github.com/twisted/twisted/blob/f28b36d02f678f4146047777f24548553425702b/src/twisted/web/_template_util.py#L387

By adding the a correct [`resolveEntity`](https://docs.python.org/3/library/xml.sax.handler.html#xml.sax.handler.EntityResolver) method to the `_ToStan` class. Right now there is no `resolveEntity()` method defined at all. 

What do you think @adiroiban ?

(Here's the trace):

```python
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/twisted/web/_flatten.py", line 321, in _flattenTree
    element = next(stack[-1])
  File "/usr/lib/python3/dist-packages/twisted/web/_flatten.py", line 237, in _flattenElement
    result = renderMethod(request, rootClone)
  File "/usr/lib/python3/dist-packages/pydoctor/templatewriter/pages/functionchild.py", line 73, in functionBody
    return self.docgetter.get(self.ob)
  File "/usr/lib/python3/dist-packages/pydoctor/templatewriter/pages/__init__.py", line 71, in get
    return epydoc2stan.format_docstring(ob)
  File "/usr/lib/python3/dist-packages/pydoctor/epydoc2stan.py", line 744, in format_docstring
    fh.handle(Field.from_epydoc(field, source))
  File "/usr/lib/python3/dist-packages/pydoctor/epydoc2stan.py", line 600, in handle
    m(field)
  File "/usr/lib/python3/dist-packages/pydoctor/epydoc2stan.py", line 529, in handle_type
    self.types[name] = field.format()
  File "/usr/lib/python3/dist-packages/pydoctor/epydoc2stan.py", line 353, in format
    return self.body.to_stan(_EpydocLinker(self.source))
  File "/usr/lib/python3/dist-packages/pydoctor/epydoc/markup/__init__.py", line 134, in to_stan
    self._stan = Tag('', children=node2stan.node2stan(self.to_node(), docstring_linker).children)
  File "/usr/lib/python3/dist-packages/pydoctor/node2stan.py", line 42, in node2stan
    return html2stan(''.join(html))
  File "/usr/lib/python3/dist-packages/pydoctor/stanutils.py", line 30, in html2stan
    stan = XMLString(b'<div>%s</div>' % html).load()[0]
  File "/usr/lib/python3/dist-packages/twisted/web/template.py", line 402, in __init__
    self._loadedTemplate = _flatsaxParse(NativeStringIO(s))
  File "/usr/lib/python3/dist-packages/twisted/web/template.py", line 356, in _flatsaxParse
    parser.parse(fl)
  File "/usr/lib/python3.9/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python3.9/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/usr/lib/python3.9/xml/sax/expatreader.py", line 221, in feed
    self._err_handler.fatalError(exc)
  File "/usr/lib/python3.9/xml/sax/handler.py", line 38, in fatalError
    raise exception
xml.sax._exceptions.SAXParseException: <unknown>:1:46: undefined entity
```

**Comment by adiroiban** [comment]
Thanks for the analysis. 
yes. It looks like  this is an issue with Twisted.

**Comment by tristanlatr** [comment]
@adiroiban, can you create an issue in the Twisted trac to fix this ?

Thanks a lot,

**Comment by adiroiban** [comment]
sorry. I have very busy these days and I will not have time for this.

All my free time is dedicated to migrate twisted/twisted Trac tickets to GitHub Issues

**Comment by tristanlatr** [comment]
@adiroiban can this issue be transferred to twisted repo ?

**Comment by twm** [comment]
I see pydoctor is using docutils' [html4css1](https://docutils.sourceforge.io/docs/user/html.html#html4css1), which outputs XHTML. So the ask here is to support XHTML entities in `XMLString`?

**Comment by tristanlatr** [comment]
Yes, I believe this is core of the issue. Thanks for clarifying.
