### ISSUE TITLE
`trial -j` silently hangs if a logfile with a directory separator in its name is passed

### ISSUE THREAD

**Issue by glyph** [twisted/twisted#11580]
Make a test file like this:

```python3
from twisted.trial.unittest import TestCase

class NothingTest(TestCase):
    def test_nothing(self) -> None:
        "Do nothing."
```

Then,

```
$ mkdir hello
$ trial -j 1 -l hello/test.log ./test_nothing.py
Running 1 tests.
^CTraceback (most recent call last):
  File "/Users/glyph/.virtualenvs/Twisted/bin/trial", line 33, in <module>
    sys.exit(load_entry_point('Twisted', 'console_scripts', 'trial')())
  File "/Users/glyph/Projects/Twisted/src/twisted/scripts/trial.py", line 654, in run
    test_result = trialRunner.run(suite)
  File "/Users/glyph/Projects/Twisted/src/twisted/trial/_dist/disttrial.py", line 453, in run
    result.raiseException()
  File "/Users/glyph/Projects/Twisted/src/twisted/python/failure.py", line 503, in raiseException
    raise self.value.with_traceback(self.tb)
twisted.python.filepath.InsecurePath: 'hello/test.log' contains one or more directory separators
Unhandled error in Deferred:

Traceback (most recent call last):
  File "/Users/glyph/Projects/Twisted/src/twisted/scripts/trial.py", line 654, in run
    test_result = trialRunner.run(suite)
  File "/Users/glyph/Projects/Twisted/src/twisted/trial/_dist/disttrial.py", line 449, in run
    d.addBoth(lambda ignored: self._reactor.stop())
  File "/Users/glyph/Projects/Twisted/src/twisted/internet/defer.py", line 572, in addBoth
    return self.addCallbacks(
  File "/Users/glyph/Projects/Twisted/src/twisted/internet/defer.py", line 511, in addCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/Users/glyph/Projects/Twisted/src/twisted/internet/defer.py", line 891, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "/Users/glyph/Projects/Twisted/src/twisted/trial/_dist/disttrial.py", line 449, in <lambda>
    d.addBoth(lambda ignored: self._reactor.stop())
  File "/Users/glyph/Projects/Twisted/src/twisted/internet/base.py", line 708, in stop
    raise error.ReactorNotRunning("Can't stop reactor that isn't running.")
twisted.internet.error.ReactorNotRunning: Can't stop reactor that isn't running.
$ 
```

You'll see the `^C` there, because `trial` just hangs forever.

**Comment by exarkun** [comment]
Presumably the preferred behavior would be to use the log file specified, interpreting the directory separator as a directory separator?

**Comment by exarkun** [comment]
Annoyingly, the current behavior is to interpret relative paths given to `--logfile` as relative to the trial temporary working directory instead of relative to the original process working directory.  I guess that's not really related to this, except I hate to codify it with a unit test. :/
