### ISSUE TITLE
yahoo.com mx record can't be resolved

### ISSUE THREAD

**Issue by gallmed** [twisted/twisted#11619]
A simple snippet taken for the examples.

Relevant part : 
```
relaymanager.MXCalculator().getMX("yahoo.com").addCallback(cbMX) 
```

Full code:
```
from twisted.application import service

application = service.Application("SMTP Client Tutorial")

from twisted.application import internet
from twisted.internet import defer, protocol, reactor
from twisted.mail import relaymanager, smtp


class SMTPTutorialClient(smtp.ESMTPClient):
    mailFrom = "tutorial_sender@example.com"
    mailTo = "tutorial_recipient@example.net"
    mailData = """\
Date: Fri, 6 Feb 2004 10:14:39 -0800
From: Tutorial Guy <tutorial_sender@example.com>
To: Tutorial Gal <tutorial_recipient@example.net>
Subject: Tutorate!
Hello, how are you, goodbye.
"""

    def getMailFrom(self):
        result = self.mailFrom
        self.mailFrom = None
        return result

    def getMailTo(self):
        return [self.mailTo]

    def getMailData(self):
        return "abce" #StringIO.StringIO(self.mailData)

    def sentMail(self, code, resp, numOk, addresses, log):
        print("Sent", numOk, "messages")

        from twisted.internet import reactor

        reactor.stop()


class SMTPClientFactory(protocol.ClientFactory):
    protocol = SMTPTutorialClient

    def buildProtocol(self, addr):
        return self.protocol(secret=None, identity="example.com")


def getMailExchange(host):
    def cbMX(mxRecord):
        return str(mxRecord.name)

    return relaymanager.MXCalculator().getMX(host).addCallback(cbMX)


def cbMailExchange(exchange):
    smtpClientFactory = SMTPClientFactory()
    print(exchange)
    smtpClientService = internet.TCPClient(exchange, 25, smtpClientFactory)
    smtpClientService.setServiceParent(application)


getMailExchange("yahoo.com").addCallback(cbMailExchange)

reactor.run()
```

The error :
```
apps-mail-relayer-1  | Unhandled error in Deferred:
apps-mail-relayer-1  |
apps-mail-relayer-1  | Traceback (most recent call last):
apps-mail-relayer-1  |   File "/usr/local/lib/python3.9/site-packages/twisted/internet/udp.py", line 254, in doRead
apps-mail-relayer-1  |     self.protocol.datagramReceived(data, addr)
apps-mail-relayer-1  |   File "/usr/local/lib/python3.9/site-packages/twisted/names/dns.py", line 3235, in datagramReceived
apps-mail-relayer-1  |     d.callback(m)
apps-mail-relayer-1  |   File "/usr/local/lib/python3.9/site-packages/twisted/internet/defer.py", line 661, in callback
apps-mail-relayer-1  |     self._startRunCallbacks(result)
apps-mail-relayer-1  |   File "/usr/local/lib/python3.9/site-packages/twisted/internet/defer.py", line 763, in _startRunCallbacks
apps-mail-relayer-1  |     self._runCallbacks()
apps-mail-relayer-1  | --- <exception caught here> ---
apps-mail-relayer-1  |   File "/usr/local/lib/python3.9/site-packages/twisted/internet/defer.py", line 857, in _runCallbacks
apps-mail-relayer-1  |     current.result = callback(  # type: ignore[misc]
apps-mail-relayer-1  |   File "/usr/local/lib/python3.9/site-packages/twisted/mail/relaymanager.py", line 1116, in _ebMX
apps-mail-relayer-1  |     failure.trap(error.DNSNameError)
apps-mail-relayer-1  |   File "/usr/local/lib/python3.9/site-packages/twisted/python/failure.py", line 476, in trap
apps-mail-relayer-1  |     self.raiseException()
apps-mail-relayer-1  |   File "/usr/local/lib/python3.9/site-packages/twisted/python/failure.py", line 500, in raiseException
apps-mail-relayer-1  |     raise self.value.with_traceback(self.tb)
apps-mail-relayer-1  |   File "/usr/local/lib/python3.9/site-packages/twisted/internet/defer.py", line 857, in _runCallbacks
apps-mail-relayer-1  |     current.result = callback(  # type: ignore[misc]
apps-mail-relayer-1  |   File "/usr/local/lib/python3.9/site-packages/twisted/mail/relaymanager.py", line 1073, in _cbMX
apps-mail-relayer-1  |     exchanges.sort()
apps-mail-relayer-1  | builtins.TypeError: '<' not supported between instances of 'Record_MX' and 'Record_MX'
apps-mail-relayer-1  |
```

gmail.com and some other domains works fine.

**Comment by exarkun** [comment]
It looks like the DNS part of this is fine but then `twisted.mail.relaymanager.MXCalculator` can't handle more than one MX record on Python 3.  On Python 2 `Record_MX` was probably ordered (I bet based on preference).

`Record_MX` (and other records) use `FancyEqMixin` and `FancyStrMixin` which should definitely be thrown away and replaced with `attrs.
