### ISSUE TITLE
Unnecessary coercion to nativeString in t.conch.unix

### ISSUE THREAD

**Issue by twm** [twisted/twisted#11627]
https://github.com/twisted/twisted/blob/26c3c04e55d0b25532709e1e1dc5d1433dde80f3/src/twisted/conch/unix.py#L373

**Comment by twm** [comment]
This is incorrect, I was thinking of `FilePath`. `os.path.join()` doesn't allow mixing:

```pyi
>>> from os.path import join
>>> join(b'foo', u'bar')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.10/genericpath.py", line 155, in _check_arg_types
    raise TypeError("Can't mix strings and bytes in path components") from None
TypeError: Can't mix strings and bytes in path components
```
