### ISSUE TITLE
strings and bytes are mixed in mail/smtp.py when using emailserver.tac

### ISSUE THREAD

**Issue by greyltc** [twisted/twisted#11634]
I was reading [the docs here](https://docs.twisted.org/en/latest/mail/examples/index.html#smtp-servers) and was encouraged to try out the "toy email server," https://raw.githubusercontent.com/twisted/twisted/trunk/docs/mail/examples/emailserver.tac

I ran it under Arch Linux and when I tried to use it with [this example](https://docs.python.org/3/library/email.examples.html#email-examples) to try to send an email, it crashed like this:
```
$ twistd -ny emailserver.tac
:0: UserWarning: You do not have a working installation of the service_identity module: 'No module named 'service_identity''.  Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module, Twisted can perform only rudimentary TLS client hostname verification.  Many valid certificate/hostname mappings may be rejected.
2022-09-04T23:01:21+0200 [-] Loading emailserver.tac...
2022-09-04T23:01:22+0200 [-] Loaded.
2022-09-04T23:01:22+0200 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 22.1.0 (/usr/bin/python 3.10.6) starting up.
2022-09-04T23:01:22+0200 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.epollreactor.EPollReactor.
2022-09-04T23:01:22+0200 [-] ConsoleSMTPFactory starting on 2500
2022-09-04T23:01:22+0200 [builtins.ConsoleSMTPFactory#info] Starting factory <ConsoleSMTPFactory object at 0x7fd169abde40>
2022-09-04T23:01:30+0200 [ESMTP,0,127.0.0.1] Unhandled Error
        Traceback (most recent call last):
          File "/usr/lib/python3.10/site-packages/twisted/python/log.py", line 96, in callWithLogger
            return callWithContext({"system": lp}, func, *args, **kw)
          File "/usr/lib/python3.10/site-packages/twisted/python/log.py", line 80, in callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File "/usr/lib/python3.10/site-packages/twisted/python/context.py", line 117, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/usr/lib/python3.10/site-packages/twisted/python/context.py", line 82, in callWithContext
            return func(*args, **kw)
        --- <exception caught here> ---
          File "/usr/lib/python3.10/site-packages/twisted/internet/posixbase.py", line 683, in _doReadOrWrite
            why = selectable.doRead()
          File "/usr/lib/python3.10/site-packages/twisted/internet/tcp.py", line 248, in doRead
            return self._dataReceived(data)
          File "/usr/lib/python3.10/site-packages/twisted/internet/tcp.py", line 253, in _dataReceived
            rval = self.protocol.dataReceived(data)
          File "/usr/lib/python3.10/site-packages/twisted/protocols/basic.py", line 440, in dataReceived
            self.lineReceived(line)
          File "/usr/lib/python3.10/site-packages/twisted/mail/smtp.py", line 489, in lineReceived
            return getattr(self, "state_" + self.mode)(line)
          File "/usr/lib/python3.10/site-packages/twisted/mail/smtp.py", line 501, in state_COMMAND
            method(parts[1])
          File "/usr/lib/python3.10/site-packages/twisted/mail/smtp.py", line 1677, in do_EHLO
            + self.listExtensions()
          File "/usr/lib/python3.10/site-packages/twisted/mail/smtp.py", line 1655, in listExtensions
            r.append(c + b" " + b" ".join(v))
        builtins.TypeError: sequence item 0: expected a bytes-like object, str found

^C2022-09-04T23:01:35+0200 [-] Received SIGINT, shutting down.
2022-09-04T23:01:35+0200 [-] (TCP Port 2500 Closed)
2022-09-04T23:01:35+0200 [builtins.ConsoleSMTPFactory#info] Stopping factory <ConsoleSMTPFactory object at 0x7fd169abde40>
2022-09-04T23:01:35+0200 [-] Main loop terminated.
2022-09-04T23:01:35+0200 [twisted.scripts._twistd_unix.UnixAppLogger#info] Server Shut Down.
```

**Comment by 4censord** [comment]
Heya, i just ran into this again:

```
2026-02-03T16:28:06+0100 [ESMTP,0,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	 File "/home/user/.local/share/virtualenvs/project-O0NyrjdQ/lib/python3.14/site-packages/twisted/internet/posixbase.py", line 491, in _doReadOrWrite
	   why = selectable.doRead()
	 File "/home/user/.local/share/virtualenvs/project-O0NyrjdQ/lib/python3.14/site-packages/twisted/internet/tcp.py", line 250, in doRead
	   return self._dataReceived(data)
	 File "/home/user/.local/share/virtualenvs/project-O0NyrjdQ/lib/python3.14/site-packages/twisted/internet/tcp.py", line 255, in _dataReceived
	   rval = self.protocol.dataReceived(data)
	 File "/home/user/.local/share/virtualenvs/project-O0NyrjdQ/lib/python3.14/site-packages/twisted/protocols/basic.py", line 440, in dataReceived
	   self.lineReceived(line)
	 File "/home/user/.local/share/virtualenvs/project-O0NyrjdQ/lib/python3.14/site-packages/twisted/mail/smtp.py", line 489, in lineReceived
	   return getattr(self, "state_" + self.mode)(line)
	 File "/home/user/.local/share/virtualenvs/project-O0NyrjdQ/lib/python3.14/site-packages/twisted/mail/smtp.py", line 736, in dataLineReceived
	   [m.eomReceived() for m in self.__messages], consumeErrors=True
	 File "twisted-emailexmaple.tac", line 44, in eomReceived
	   print("\n".join(self.lines))
	builtins.TypeError: sequence item 1: expected str instance, bytes found
	
```

this is `twisted 25.5.0`, with `python 3.14`, installed in a venv on archlinux.


The error only happens if i send it any email via a client like thunderbird though, sending manually using e.g. telnet works fine.

**Comment by adiroiban** [comment]
Thanks for the report.

It looks like the issue is with your `twisted-emailexmaple.tac` 

I guess that the line should be `print(b"\n".join(self.lines))`
