### ISSUE TITLE
AttributeError: module 'twisted' has no attribute '__version__'

### ISSUE THREAD

**Issue by atptour2017** [twisted/twisted#11651]
**Describe the incorrect behavior you saw**
Build twisted lib by cross compile, it was failed.
`AttributeError: twisted has no attribute __version__`

**Describe how to cause this behavior**
Edit setup.py firstly to add cross compile configuration:
`os.environ["CC"] ="aarch64-linux-gnu-gcc"`
Then run:
`python setup.py build`

What did you do to get it to happen?
Does it happen every time you follow these steps, sometimes, or only one time?
Every time

If you have a traceback, please paste it here; otherwise, delete this.
```
(py38) [root@localhost twisted]# python setup.py build
Traceback (most recent call last):
  File "/home/anaconda/envs/py38/lib/python3.8/site-packages/setuptools/config/expand.py", line 81, in __getattr__
    return next(
  File "/home/anaconda/envs/py38/lib/python3.8/site-packages/setuptools/config/expand.py", line 82, in <genexpr>
    ast.literal_eval(value)
  File "/home/anaconda/envs/py38/lib/python3.8/ast.py", line 99, in literal_eval
    return _convert(node_or_string)
  File "/home/anaconda/envs/py38/lib/python3.8/ast.py", line 98, in _convert
    return _convert_signed_num(node)
  File "/home/anaconda/envs/py38/lib/python3.8/ast.py", line 75, in _convert_signed_num
    return _convert_num(node)
  File "/home/anaconda/envs/py38/lib/python3.8/ast.py", line 66, in _convert_num
    _raise_malformed_node(node)
  File "/home/anaconda/envs/py38/lib/python3.8/ast.py", line 63, in _raise_malformed_node
    raise ValueError(f'malformed node or string: {node!r}')
ValueError: malformed node or string: <_ast.Call object at 0x7f4065184f40>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/anaconda/envs/py38/lib/python3.8/site-packages/setuptools/config/expand.py", line 191, in read_attr
    return getattr(StaticModule(module_name, spec), attr_name)
  File "/home/anaconda/envs/py38/lib/python3.8/site-packages/setuptools/config/expand.py", line 87, in __getattr__
    raise AttributeError(f"{self.name} has no attribute {attr}") from e
AttributeError: twisted has no attribute __version__

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 21, in <module>
    setuptools.setup(
  File "/home/anaconda/envs/py38/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/anaconda/envs/py38/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 159, in setup
    dist.parse_config_files()
  File "/home/anaconda/envs/py38/lib/python3.8/site-packages/setuptools/dist.py", line 864, in parse_config_files
    setupcfg.parse_configuration(
  File "/home/anaconda/envs/py38/lib/python3.8/site-packages/setuptools/config/setupcfg.py", line 174, in parse_configuration
    meta.parse()
  File "/home/anaconda/envs/py38/lib/python3.8/site-packages/setuptools/config/setupcfg.py", line 496, in parse
    section_parser_method(section_options)
  File "/home/anaconda/envs/py38/lib/python3.8/site-packages/setuptools/config/setupcfg.py", line 470, in parse_section
    self[name] = value
  File "/home/anaconda/envs/py38/lib/python3.8/site-packages/setuptools/config/setupcfg.py", line 278, in __setitem__
    value = parser(value)
  File "/home/anaconda/envs/py38/lib/python3.8/site-packages/setuptools/config/setupcfg.py", line 602, in _parse_version
    return expand.version(self._parse_attr(value, self.package_dir, self.root_dir))
  File "/home/anaconda/envs/py38/lib/python3.8/site-packages/setuptools/config/setupcfg.py", line 412, in _parse_attr
    return expand.read_attr(attr_desc, package_dir, root_dir)
  File "/home/anaconda/envs/py38/lib/python3.8/site-packages/setuptools/config/expand.py", line 195, in read_attr
    return getattr(module, attr_name)
AttributeError: module 'twisted' has no attribute '__version__'
```

Preferable a [Short, Self Contained, Correct (Compilable), Example](http://www.sscce.org/) on a branch or on [a gist](https://gist.github.com).

Automated tests that are demonstrating the failure would be awesome.

**Describe the correct behavior you'd like to see**
A clear and concise description of what you expected to happen, or what you believe should be happening instead.
Build successfully.

**Testing environment**
 - Operating System and Version; paste the output of these commands:
   - on Linux, `uname -a ; cat /etc/lsb-release`
   - on Windows, `systeminfo | Findstr /i "OS"`
   - on macOS, `sw_vers`
 - Twisted version [e.g. 22.2.0]
   - please paste the output of `twist --version` and `pip --freeze`
 - Reactor [e.g. select, iocp]
Linux localhost.localdomain 3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
CentOS Linux release 7.7.1908 (Core)
Twisted version is the master I git clone from github on Sep 9, 2022.
I found in: src/twisted/_version.py:10:__version__ = Version("Twisted", 22, 8, 0, post=0)

**Additional context**
None.

**Comment by exarkun** [comment]
Twisted is a pure-Python library so there's no need to cross-compile it.  You can use any of the release packages on any architecture.  If you need to build your own package, you can do so with `pip install build; python -m build .` in the Twisted source directory.

Feel free to comment further if I've misunderstood and we can re-open.
