### ISSUE TITLE
My websocket is crashing because of unhandled errors in twisted

### ISSUE THREAD

**Issue by pavinash7** [twisted/twisted#11663]
Please check the stacktrace/backtrace below:

Unhandled Error                                                                                                                                                                                         0
Traceback (most recent call last):
  File "/home/avinash/trading-ubuntu22/lib/python3.10/site-packages/twisted/python/log.py", line 96, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/avinash/trading-ubuntu22/lib/python3.10/site-packages/twisted/python/log.py", line 80, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/avinash/trading-ubuntu22/lib/python3.10/site-packages/twisted/python/context.py", line 117, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/avinash/trading-ubuntu22/lib/python3.10/site-packages/twisted/python/context.py", line 82, in callWithContext
    return func(*args, **kw)
--- <exception caught here> ---
  File "/home/avinash/trading-ubuntu22/lib/python3.10/site-packages/twisted/internet/posixbase.py", line 683, in _doReadOrWrite
    why = selectable.doRead()
  File "/home/avinash/trading-ubuntu22/lib/python3.10/site-packages/twisted/internet/tcp.py", line 248, in doRead
    return self._dataReceived(data)
  File "/home/avinash/trading-ubuntu22/lib/python3.10/site-packages/twisted/internet/tcp.py", line 253, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/home/avinash/trading-ubuntu22/lib/python3.10/site-packages/twisted/protocols/tls.py", line 330, in dataReceived
    self._flushReceiveBIO()
  File "/home/avinash/trading-ubuntu22/lib/python3.10/site-packages/twisted/protocols/tls.py", line 301, in _flushReceiveBIO
    self._flushSendBIO()
  File "/home/avinash/trading-ubuntu22/lib/python3.10/site-packages/twisted/protocols/tls.py", line 254, in _flushSendBIO
    bytes = self._tlsConnection.bio_read(2 ** 15)
  File "/home/avinash/trading-ubuntu22/lib/python3.10/site-packages/OpenSSL/SSL.py", line 1945, in bio_read
    self._handle_bio_errors(self._from_ssl, result)
  File "/home/avinash/trading-ubuntu22/lib/python3.10/site-packages/OpenSSL/SSL.py", line 1920, in _handle_bio_errors
    raise ValueError("unknown bio failure")
builtins.ValueError: unknown bio failure

Connection error: 1006 - connection was closed uncleanly (SSL error: unexpected eof while reading (in ))                                                                                            
2022-09-14 02:42:02.937972Connection error: 1006 - connection was closed uncleanly (SSL error: unexpected eof while reading (in ))
Connection closed: 1006 - connection was closed uncleanly (SSL error: unexpected eof while reading (in ))                                                                                            
2022-09-14 02:42:02.938049Connection closed: 1006 - connection was closed uncleanly (SSL error: unexpected eof while reading (in ))

Unhandled Error                                                                                                                                                                                         
Traceback (most recent call last):
  File "/home/avinash/trading-ubuntu22/lib/python3.10/site-packages/twisted/python/log.py", line 96, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/avinash/trading-ubuntu22/lib/python3.10/site-packages/twisted/python/log.py", line 80, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/avinash/trading-ubuntu22/lib/python3.10/site-packages/twisted/python/context.py", line 117, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/avinash/trading-ubuntu22/lib/python3.10/site-packages/twisted/python/context.py", line 82, in callWithContext
    return func(*args, **kw)
--- <exception caught here> ---
  File "/home/avinash/trading-ubuntu22/lib/python3.10/site-packages/twisted/internet/posixbase.py", line 683, in _doReadOrWrite
    why = selectable.doRead()
  File "/home/avinash/trading-ubuntu22/lib/python3.10/site-packages/twisted/internet/tcp.py", line 248, in doRead
    return self._dataReceived(data)
  File "/home/avinash/trading-ubuntu22/lib/python3.10/site-packages/twisted/internet/tcp.py", line 253, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/home/avinash/trading-ubuntu22/lib/python3.10/site-packages/twisted/protocols/tls.py", line 330, in dataReceived
    self._flushReceiveBIO()
  File "/home/avinash/trading-ubuntu22/lib/python3.10/site-packages/twisted/protocols/tls.py", line 301, in _flushReceiveBIO
    self._flushSendBIO()
  File "/home/avinash/trading-ubuntu22/lib/python3.10/site-packages/twisted/protocols/tls.py", line 254, in _flushSendBIO
    bytes = self._tlsConnection.bio_read(2 ** 15)
  File "/home/avinash/trading-ubuntu22/lib/python3.10/site-packages/OpenSSL/SSL.py", line 1945, in bio_read
    self._handle_bio_errors(self._from_ssl, result)
  File "/home/avinash/trading-ubuntu22/lib/python3.10/site-packages/OpenSSL/SSL.py", line 1923, in _handle_bio_errors
    _raise_current_error()
  File "/home/avinash/trading-ubuntu22/lib/python3.10/site-packages/OpenSSL/_util.py", line 55, in exception_from_error_queue                                                                       
    raise exception_type(errors)
OpenSSL.SSL.Error: []                                                                                                                                                                                

Connection error: 1006 - connection was closed uncleanly (SSL error: unexpected eof while reading (in ))                                                                                            
2022-09-14 02:49:42.981655Connection error: 1006 - connection was closed uncleanly (SSL error: unexpected eof while reading (in ))
Connection closed: 1006 - connection was closed uncleanly (SSL error: unexpected eof while reading (in ))                                                                                            
2022-09-14 02:49:42.981719Connection closed: 1006 - connection was closed uncleanly (SSL error: unexpected eof while reading (in ))

**Comment by exarkun** [comment]
Hello,

There's not enough information here to know whether this is a bug in Twisted itself or not, nor what that bug might be if so.  This kind of issue is better pursued in one of the other discussion forums - the IRC channel (also accessible via, eg [Gitter](https://gitter.im/twisted/twisted)), [the mailing list](https://docs.twisted.org/en/latest/community.html#mail-lists), or a site like [https://stackoverflow.com/](https://stackoverflow.com/).
