### ISSUE TITLE
`UnboundLocalError` exception when exiting `trial -j` via an interrupt (i.e. ctrl-C)

### ISSUE THREAD

**Issue by glyph** [twisted/twisted#11707]
running `trial --reporter=bwverbose -j 10 twisted.internet.test` for unrelated reasons:

`trial --reporter=bwverbose -j 10 twisted.internet.test`

```
^CTraceback (most recent call last):
  File "/Users/glyph/.virtualenvs/Twisted/bin/trial", line 8, in <module>
    sys.exit(run())
  File "/Users/glyph/Projects/Twisted/src/twisted/scripts/trial.py", line 647, in run
    testResult = trialRunner.run(suite)
  File "/Users/glyph/Projects/Twisted/src/twisted/trial/_dist/disttrial.py", line 473, in run
    return self._run(test, untilFailure=False)
  File "/Users/glyph/Projects/Twisted/src/twisted/trial/_dist/disttrial.py", line 455, in _run
    if isinstance(result, Failure):
UnboundLocalError: local variable 'result' referenced before assignment
```

**Comment by glyph** [comment]
The hang that provokes this seems to only occur with the `bwverbose` reporter, oddly. The default reporter runs to completion on this suite.

**Comment by exarkun** [comment]
Sounds related to https://github.com/twisted/twisted/issues/10340 but no mention of `bwverbose` there.

**Comment by glyph** [comment]
On Python 3.11, we get a different exception type, so recording this here in case anyone is searching for it:
```
^CTraceback (most recent call last):                                                                                                                                              
  File "<frozen runpy>", line 198, in _run_module_as_main                                                                                                                         
  File "<frozen runpy>", line 88, in _run_code                                                                                                                                    
  File "/Users/glyph/Projects/Twisted/.tox/alldeps-macos-nocov/lib/python3.11/site-packages/twisted/trial/__main__.py", line 9, in <module>                                       
    sys.exit(run())                                                                                                                                                               
             ^^^^^                                                                                                                                                                
  File "/Users/glyph/Projects/Twisted/.tox/alldeps-macos-nocov/lib/python3.11/site-packages/twisted/scripts/trial.py", line 647, in run                                           
    testResult = trialRunner.run(suite)                                                                                                                                           
                 ^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                           
  File "/Users/glyph/Projects/Twisted/.tox/alldeps-macos-nocov/lib/python3.11/site-packages/twisted/trial/_dist/disttrial.py", line 473, in run                                   
    return self._run(test, untilFailure=False)                                                                                                                                    
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                    
  File "/Users/glyph/Projects/Twisted/.tox/alldeps-macos-nocov/lib/python3.11/site-packages/twisted/trial/_dist/disttrial.py", line 455, in _run                                  
    if isinstance(result, Failure):                                                                                                                                               
                  ^^^^^^                                                                                                                                                          
UnboundLocalError: cannot access local variable 'result' where it is not associated with a value                                                                                  
```
