### ISSUE TITLE
test flake: twisted.internet.test.test_unix.UNIXPortTestsBuilder_SelectReactorTests.test_closePeerOnEMFILE

### ISSUE THREAD

**Issue by glyph** [twisted/twisted#11704]
```
twisted.internet.test.test_unix.UNIXPortTestsBuilder_SelectReactorTests.test_closePeerOnEMFILE ... Traceback (most recent call last):
  File "/Users/glyph/Projects/Twisted/src/twisted/internet/test/test_tcp.py", line 1412, in test_closePeerOnEMFILE
    assertPeerClosedOnEMFILE(
  File "/Users/glyph/Projects/Twisted/src/twisted/internet/test/test_tcp.py", line 1269, in assertPeerClosedOnEMFILE
    testCase.assertNoResult(clientFactory.failDeferred)
  File "/Users/glyph/Projects/Twisted/src/twisted/trial/_synctest.py", line 827, in assertNoResult
    self.fail(
twisted.trial.unittest.FailTest: No result expected on <Deferred at 0x115fbdb70 current result: None>, found None instead
[FAILURE]Traceback (most recent call last):
  File "/Users/glyph/Projects/Twisted/src/twisted/trial/_synctest.py", line 1443, in _runCleanups
    f(*args, **kwargs)
  File "/Users/glyph/Projects/Twisted/src/twisted/internet/test/reactormixins.py", line 242, in unbuildReactor
    reader.connectionLost(None)
  File "/Users/glyph/Projects/Twisted/src/twisted/internet/posixbase.py", line 197, in connectionLost
    os.close(fd)
builtins.TypeError: 'NoneType' object cannot be interpreted as an integer
[ERROR]
twisted.internet.test.test_unix.UNIXPortTestsBuilder_SelectReactorTests.test_connectionLostLogMsg ... Traceback (most recent call last):
  File "/Users/glyph/Projects/Twisted/src/twisted/trial/_synctest.py", line 1443, in _runCleanups
    f(*args, **kwargs)
  File "/Users/glyph/Projects/Twisted/src/twisted/internet/test/reactormixins.py", line 242, in unbuildReactor
    reader.connectionLost(None)
  File "/Users/glyph/Projects/Twisted/src/twisted/internet/posixbase.py", line 197, in connectionLost
    os.close(fd)
builtins.TypeError: 'NoneType' object cannot be interpreted as an integer
[ERROR][OK]
```

**Testing environment**
 - Operating System and Version; paste the output of these commands:
   - on Linux, `uname -a ; cat /etc/lsb-release`
   - on Windows, `systeminfo | Findstr /i "OS"`
   - on macOS, `sw_vers`

```
ProductName:	macOS
ProductVersion:	12.6
BuildVersion:	21G115
```

 - Twisted version [e.g. 22.2.0]
   - please paste the output of `twist --version` and `pip --freeze`
 - Reactor [e.g. select, iocp]

```
22.8.0.post0
alabaster==0.7.12
appdirs==1.4.4
appnope==0.1.3
astor==0.8.1
astroid==2.12.10
asttokens==2.0.8
attrs==22.1.0
Automat==20.2.0
Babel==2.10.3
backcall==0.2.0
bcrypt==4.0.0
blessed==1.19.1
bpython==0.23
CacheControl==0.12.11
certifi==2022.9.24
cffi==1.15.1
charset-normalizer==2.1.1
click==8.1.3
click-default-group==1.2.2
ConfigArgParse==1.5.3
constantly==15.1.0
coverage==6.5.0
cryptography==38.0.1
curtsies==0.4.0
cwcwidth==0.1.7
cython-test-exception-raiser==1.0.2
debugpy==1.6.3
decorator==5.1.1
dill==0.3.5.1
docutils==0.17.1
entrypoints==0.4
epc==0.0.5
exceptiongroup==1.0.0rc9
executing==1.1.0
flake8==5.0.4
greenlet==1.1.3
h2==4.1.0
hpack==4.0.0
hyperframe==6.0.1
hyperlink==21.0.0
hypothesis==6.56.0
idna==3.4
imagesize==1.4.1
importmagic==0.1.7
incremental @ https://github.com/twisted/incremental/archive/refs/heads/trunk.tar.gz
ipykernel==6.16.0
ipython==8.5.0
isort==5.10.1
jedi==0.18.1
Jinja2==3.1.2
jupyter-core==4.11.1
jupyter_client==7.3.5
lazy-object-proxy==1.7.1
lockfile==0.12.2
lunr==0.6.2
MarkupSafe==2.1.1
matplotlib-inline==0.1.6
mccabe==0.7.0
msgpack==1.0.4
mypy==0.930
mypy-extensions==0.4.3
mypy-zope==0.3.4
nest-asyncio==1.5.6
packaging==21.3
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
platformdirs==2.5.2
priority==1.3.0
prompt-toolkit==3.0.31
psutil==5.9.2
ptyprocess==0.7.0
pudb==2022.1.2
pure-eval==0.2.2
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycairo==1.21.0
pycodestyle==2.9.1
pycparser==2.21
pydoctor==22.9.1
pyflakes==2.5.0
Pygments==2.13.0
PyGObject==3.42.2
PyHamcrest==2.0.4
pylint==2.15.3
PyNaCl==1.5.0
pyobjc-core==8.5.1
pyobjc-framework-CFNetwork==8.5.1
pyobjc-framework-Cocoa==8.5.1
pyOpenSSL==22.1.0
pyparsing==3.0.9
pyserial==3.5
python-dateutil==2.8.2
pytz==2022.4
pyxdg==0.28
pyzmq==24.0.1
readthedocs-sphinx-ext==2.1.9
requests==2.28.1
service-identity==21.1.0
sexpdata==0.0.3
six==1.16.0
snowballstemmer==2.2.0
sortedcontainers==2.4.0
Sphinx==5.2.3
sphinx-rtd-theme==1.0.0
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
stack-data==0.5.1
toml==0.10.2
tomli==2.0.1
tomlkit==0.11.5
tornado==6.2
towncrier==22.8.0
traitlets==5.4.0
-e git+ssh://git@github.com/twisted/twisted@c5b30bdcfbed20f849dfcdbd49a33a8628892604#egg=Twisted
twistedchecker==0.7.4
types-cryptography==3.3.23
types-pyOpenSSL==22.1.0.0
types-setuptools==65.4.0.0
typing_extensions==4.3.0
urllib3==1.26.12
urwid==2.1.2
urwid-readline==0.13
wcwidth==0.2.5
wrapt==1.14.1
zope.event==4.5.0
zope.interface==5.4.0
zope.schema==6.2.1
```

**Comment by glyph** [comment]
c5b30bdcfbed20f849dfcdbd49a33a8628892604

**Comment by glyph** [comment]
Command line:

```
['/Users/glyph/.virtualenvs/Twisted/bin/trial', '--force-gc', '--reporter=bwverbose', '--rterrors', '--temp-directory', '/Users/glyph/Scratch/Test/_trial_obb_temp', '--testmodule', '/Users/glyph/Projects/Twisted/src/twisted/internet/_glibbase.py']
```
