### ISSUE TITLE
Sometimes cfreactor fails twisted.internet.test.test_fdset.ReactorFDSetTestsBuilder_CFReactorTests.test_addReader with 120 second TimeoutError

### ISSUE THREAD

**Issue by exarkun** [twisted/twisted#11771]
```
===============================================================================
Error: 
Traceback (most recent call last):
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.11/site-packages/twisted/internet/test/test_fdset.py", line 91, in test_addReader
    self.runReactor(reactor)
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.11/site-packages/twisted/internet/test/reactormixins.py", line 337, in runReactor
    raise TestTimeoutError(f"reactor still running after {timeout} seconds")
twisted.internet.test.reactormixins.TestTimeoutError: reactor still running after 120.0 seconds

twisted.internet.test.test_fdset.ReactorFDSetTestsBuilder_CFReactorTests.test_addReader
===============================================================================
Error: 
Traceback (most recent call last):
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.11/site-packages/twisted/internet/base.py", line 1049, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.11/site-packages/twisted/internet/test/reactormixins.py", line 332, in stop
    reactor.stop()
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.11/site-packages/twisted/internet/cfreactor.py", line 538, in stop
    PosixReactorBase.stop(self)
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.11/site-packages/twisted/internet/base.py", line 757, in stop
    raise error.ReactorNotRunning("Can't stop reactor that isn't running.")
twisted.internet.error.ReactorNotRunning: Can't stop reactor that isn't running.

twisted.internet.test.test_fdset.ReactorFDSetTestsBuilder_CFReactorTests.test_addReader
-------------------------------------------------------------------------------
```

**Comment by exarkun** [comment]
Also twisted.internet.test.test_tcp.AbortConnectionTests_CFReactorTests.test_fullWriteBufferAfterByteExchange

**Comment by glyph** [comment]
I believe #12029 is a duplicate of this?

**Comment by glyph** [comment]
Sometimes it's `twisted.internet.test.test_process.ProcessTestsBuilder_CFReactorTests.test_pauseAndResumeProducing` too. Not sure if this is the same bug.

```
===============================================================================
Error: 
Traceback (most recent call last):
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.8/site-packages/twisted/internet/test/test_process.py", line 888, in test_pauseAndResumeProducing
    self.runReactor(reactor)
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.8/site-packages/twisted/internet/test/reactormixins.py", line 351, in runReactor
    raise TestTimeoutError(f"reactor still running after {timeout} seconds")
twisted.internet.test.reactormixins.TestTimeoutError: reactor still running after 120.0 seconds

twisted.internet.test.test_process.ProcessTestsBuilder_CFReactorTests.test_pauseAndResumeProducing
===============================================================================
Error: 
Traceback (most recent call last):
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.8/site-packages/twisted/internet/base.py", line 1090, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.8/site-packages/twisted/internet/test/reactormixins.py", line 346, in stop
    reactor.stop()
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.8/site-packages/twisted/internet/cfreactor.py", line 536, in stop
    PosixReactorBase.stop(self)
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.8/site-packages/twisted/internet/base.py", line 794, in stop
    raise error.ReactorNotRunning("Can't stop reactor that isn't running.")
twisted.internet.error.ReactorNotRunning: Can't stop reactor that isn't running.

twisted.internet.test.test_process.ProcessTestsBuilder_CFReactorTests.test_pauseAndResumeProducing
-------------------------------------------------------------------------------
Ran 10791 tests in 176.943s
```

https://github.com/twisted/twisted/actions/runs/7521167302/job/20471684152?pr=12083
