### ISSUE TITLE
Trial incompatibility with pip 23.1 when setup.py-based package is installed in editable mode

### ISSUE THREAD

**Issue by p12tic** [twisted/twisted#11840]
**Describe the incorrect behavior you saw**
trial is completely broken under certain conditions with recently released pip 23.1

**Describe how to cause this behavior**

I don't yet have a proper small reproducer for this issue, but I wanted to bring this up for attention because the error message is extremely confusing and will cause lots of wasted time for anyone that's affected by the bug.

The bug is this: under certain conditions trial test discovery is completely broken and it's impossible to run any tests. The following error is produced:

```
[ERROR]
Traceback (most recent call last):
  File ".../venv/.../site-packages/twisted/trial/runner.py", line 711, in loadByName
    return self.suiteFactory([self.findByName(name, recurse=recurse)])
  File ".../venv/.../site-packages/twisted/trial/runner.py", line 517, in findByName
    return self.loadAnything(
  File ".../venv/.../site-packages/twisted/trial/runner.py", line 673, in loadAnything
    return self.loadPackage(obj, recurse=recurse)
  File ".../venv/.../site-packages/twisted/trial/runner.py", line 604, in loadPackage
    pkgobj = modules.getModule(package.__name__)
  File ".../venv/.../site-packages/twisted/python/modules.py", line 781, in getModule
    return theSystemPath[moduleName]
  File ".../venv/.../site-packages/twisted/python/modules.py", line 704, in __getitem__
    self._smartPath(self._findEntryPathString(moduleObject)), self
  File ".../venv/.../site-packages/twisted/python/modules.py", line 645, in _findEntryPathString
    warnings.warn(
builtins.UserWarning: path/to/my/myproject (for module myproject.test) not in path importer cache (PEP 302 violation - check your local configuration).
```

The conditions which I've found are the following:
 - a `venv`-based virtualenv is created (i.e. `python3 -m venv path`, not `virtualenv path`)
 - recently released pip 23.1 is used within the venv
 - the tested package uses legacy setup.py-based installation
 - the tested package is installed in editable mode
 - `wheel` package is not present in the venv

Under these conditions `venv` will use `pyproject.toml` as an intermediate step for installation. This results in a different set of entries in `sys.path_importer_cache`, which breaks `trial` auto discovery. Simple `pyproject.toml`-based project produces the same change in `sys.path_importer_cache`, so it could be that `trial` is broken with any `pyproject.toml`-based project.

A relevant discussion in pip bug tracker: https://github.com/pypa/pip/issues/11964.
 

**Describe the correct behavior you'd like to see**
`trial` should run tests.

**Workaround**
Install `wheel` package into the virtualenv.

**Testing environment**

OS: Linux, debian bookworm

Twisted: 22.10.0

```
$ pip freeze
alembic==1.10.3
attrs==23.1.0
autobahn==23.1.2
Automat==22.10.0
-e git+https://github.com/buildbot/buildbot.git@20fea31a1daf173c3e530ce2b7568f3a43908df4#egg=buildbot&subdirectory=master
cffi==1.15.1
constantly==15.1.0
cryptography==40.0.2
greenlet==2.0.2
hyperlink==21.0.0
idna==3.4
incremental==22.10.0
Jinja2==3.1.2
Mako==1.2.4
MarkupSafe==2.1.2
mock==5.0.1
msgpack==1.0.5
pycparser==2.21
PyJWT==2.6.0
python-dateutil==2.8.2
PyYAML==6.0
six==1.16.0
SQLAlchemy==1.4.47
Twisted==22.10.0
txaio==23.1.1
typing_extensions==4.5.0
zope.interface==6.0
```

**Comment by adiroiban** [comment]
Thanks for the report. From the traceback, I can see that this is an issue with [twisted.python.modules.getModule](https://docs.twisted.org/en/stable/api/twisted.python.modules.html#getModule)

For reference, the code raising this issue is here 

https://github.com/twisted/twisted/blob/525da4a0becad1e814c74f12c365f15fe9cd10de/src/twisted/python/modules.py#L620:L653

**Comment by p12tic** [comment]
@adiroiban Yes, I already debugged that. The problem is essentially that this comment:

```
 if package 'foo' is on sys.path at /a/b/foo, package 'foo's
__file__ will be /a/b/foo/__init__.py, and we are looking for
/a/b here, the path-entry; so go up two steps.
```

Is no longer true with pyproject.toml based packages: /a/b/foo will be in the package cache, but not /a/b

**Comment by p12tic** [comment]
I will prepare a proper reproduction project a bit later. For any initial investigation the reproduction project linked to https://github.com/pypa/pip/issues/11964 (instructions on how to run it is in the bug page) is an easy way to see the difference of sys.path_importer_cache contents.

**Comment by tdesveaux** [comment]
I believe I setup a small reproduction case for this here: https://github.com/tdesveaux/buildbot-repro/commit/9db0a5151baa5aee58f8e8c38b532fb96a3f7b0d

A fairly obvious change made by setuptools editable installation looks to be the .pth generated.
Where before, it would only add the abspath to the module, it now generate some code that patches `sys.[path,path_hooks,meta_path]`.

**Comment by glyph** [comment]
1. It looks like this is a bug introduced in setuptools, and should be reported upstream; this warning exists for a reason
2. it's a warning, not an error; you are only getting this as an exception because you've specified something like `-Werror` to Python; you may just want to add a warnings filter to suppress this warning if you don't care about it.

**Comment by tdesveaux** [comment]
> 1. It looks like this is a bug introduced in setuptools, and should be reported upstream; this warning exists for a reason

Granted, I'm not familiar with PEP302, my knowledge about this is from reading the PEP and docs so I might be wrong.

But, this doesn't match what I get from the docs.

[`sys.path_importer_cache`](https://docs.python.org/3/library/sys.html#sys.path_importer_cache) is a cache for `sys.path_hooks`.


Forgot to link it in my last comment, but here are the difference between `.pth` for the legacy editable mode and the 'new' one generated by setuptools https://github.com/tdesveaux/buildbot-repro/commit/0270aa24ed5f83e24f92f3f0a71b7f999d9eabf5.

Since there is no namespaces in this case, only [this `sys.meta_path`](https://github.com/tdesveaux/buildbot-repro/blob/0270aa24ed5f83e24f92f3f0a71b7f999d9eabf5/pths/new/__editable___twisted_trial_editable_0_0_1_finder.py#L76) is active.
So the new method hooks itself in `sys.meta_path`.

> PEP 302
>  In this PEP’s implementation, it’s a list of importer objects that is traversed before sys.path. This list is yet another new object in the sys module: sys.meta_path.

This result it the import of the editable module do not go through `sys.path` lookup. Resulting in no `sys.path_hooks` lookup either.
In this context, the entry not being part of `sys.path_importer_cache` seems a valid case.

As said, I'm not knowledgeable enough on this to be sure.
If you still think the issue is on the setuptools side, I don't mind bringing up there.
If so, could you provide a bit more context around why this warning is there so I can properly report the issue?


> 2. it's a warning, not an error; you are only getting this as an exception because you've specified something like -Werror to Python; you may just want to add a warnings filter to suppress this warning if you don't care about it.

For sure, that would work. Just wanted to make sure it was a false positive or a real issue.

**Comment by glyph** [comment]
> Granted, I'm not familiar with PEP302, my knowledge about this is from reading the PEP and docs so I might be wrong.

Fair enough; this warning was written after extensive review of PEP 302 at the time, but I do need to refresh my memory on how all this is supposed to work and whether any ensuing jurisprudence about the spec has altered the relevant parts of my understanding.

**Comment by glyph** [comment]
> For sure, that would work. Just wanted to make sure it was a false positive or a real issue.

At the very least we *do* have some work to do on the Twisted side, which is to reflect on the actionability and the instructions for this warning. "Check your local configuration" is perhaps the apotheosis of horrible error messages: what "configuration"? how do I check it? Is there a "remote" configuration I don't need to check? Why would I bother checking it, if the import is going to work either way?

If the PEP 302 violation is meaningful and might result in incorrect or undesirable behavior, we should explicitly spell out what the relevant behavior _is_ so that a user seeing this warning can meaningfully decide whether to silence it or fix… whatever is causing it.
