### ISSUE TITLE
protocols/ident has bytes/str confusion on python 3

### ISSUE THREAD

**Issue by wilhelmy** [twisted/twisted#11868]
**Describe the incorrect behavior you saw**

ident.py is missing encode("utf-8") and decode("utf-8") in certain places. This causes uncaught exceptions.

**Describe how to cause this behavior**

Run the freshly ported python3-qwebirc I use for IRCnet. (Commits in question: [#1](https://github.com/qwebirc/qwebirc/commit/45f1282003014f2539a1a2bd085d77f6d3640843) [#2](https://github.com/qwebirc/qwebirc/commit/16e05385b5775112ecb8c47f015be40d24979a6c))
This code worked on Python 2.7 but doesn't anymore. The traceback in question:
```
2023-05-28T22:24:25+0200 [IdentProtocol,12,94.125.182.253] Unhandled Error
        Traceback (most recent call last):
          File "/usr/lib/python3/dist-packages/twisted/python/log.py", line 103, in callWithLogger
            return callWithContext({"system": lp}, func, *args, **kw)
          File "/usr/lib/python3/dist-packages/twisted/python/log.py", line 86, in callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext
            return func(*args,**kw)
        --- <exception caught here> ---
          File "/usr/lib/python3/dist-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
            why = selectable.doRead()
          File "/usr/lib/python3/dist-packages/twisted/internet/tcp.py", line 243, in doRead
            return self._dataReceived(data)
          File "/usr/lib/python3/dist-packages/twisted/internet/tcp.py", line 249, in _dataReceived
            rval = self.protocol.dataReceived(data)
          File "/usr/lib/python3/dist-packages/twisted/protocols/basic.py", line 454, in dataReceived
            self.lineReceived(line)
          File "/usr/lib/python3/dist-packages/twisted/protocols/ident.py", line 73, in lineReceived
            parts = line.split(',')
        builtins.TypeError: a bytes-like object is required, not 'str'

```
and
```        


2023-05-29T01:00:02+0200 [IdentProtocol,0,94.125.182.253] Unhandled Error
        Traceback (most recent call last):
          File "/usr/lib/python3/dist-packages/twisted/protocols/ident.py", line 83, in lineReceived
            self.validQuery(portOnServer, portOnClient)
          File "/usr/lib/python3/dist-packages/twisted/protocols/ident.py", line 102, in validQuery
            defer.maybeDeferred(self.lookup, serverAddr, clientAddr
          File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 321, in addCallback
            return self.addCallbacks(callback, callbackArgs=args,
          File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 311, in addCallbacks
            self._runCallbacks()
        --- <exception caught here> ---
          File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 654, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "/usr/lib/python3/dist-packages/twisted/protocols/ident.py", line 110, in _cbLookup
            self.sendLine('%d, %d : USERID : %s : %s' % (sport, cport, sysName, userId))
          File "/usr/lib/python3/dist-packages/twisted/protocols/basic.py", line 476, in sendLine
            return self.transport.writeSequence((line, self.delimiter))
          File "/usr/lib/python3/dist-packages/twisted/internet/_newtls.py", line 204, in writeSequence
            FileDescriptor.writeSequence(self, iovec)
          File "/usr/lib/python3/dist-packages/twisted/internet/abstract.py", line 377, in writeSequence
            raise TypeError("Data must not be unicode")
        builtins.TypeError: Data must not be unicode
```
 
Adding `.encode("utf-8")` and `.decode("utf-8")` to twisted in the right places fixes the problem.

**Describe the correct behavior you'd like to see**
A clear and concise description of what you expected to happen, or what you believe should be happening instead.

**Testing environment**
`Linux webchat.ircnet.net 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux`
```
root@webchat:~# cat /etc/lsb*
cat: '/etc/lsb*': No such file or directory
```
 - Twisted version
```
root@webchat:~# twist3 --version
20.3.0
```
pip isn't used, this is from the debian repos.
 - Reactor
seems to be epoll

**Additional context**

This patch works for me, but doesn't apply directly on trunk

```
--- ident.py.orig	2019-12-18 04:08:42.000000000 +0100
+++ ident.py	2023-05-29 01:25:14.985550125 +0200
@@ -70,7 +70,7 @@
     """
 
     def lineReceived(self, line):
-        parts = line.split(',')
+        parts = line.decode('us-ascii').split(',')
         if len(parts) != 2:
             self.invalidQuery()
         else:
@@ -107,15 +107,15 @@
 
     def _cbLookup(self, result, sport, cport):
         (sysName, userId) = result
-        self.sendLine('%d, %d : USERID : %s : %s' % (sport, cport, sysName, userId))
+        self.sendLine(('%d, %d : USERID : %s : %s' % (sport, cport, sysName, userId)).encode('utf-8'))
 
 
     def _ebLookup(self, failure, sport, cport):
         if failure.check(IdentError):
-            self.sendLine('%d, %d : ERROR : %s' % (sport, cport, failure.value))
+            self.sendLine(('%d, %d : ERROR : %s' % (sport, cport, failure.value)).encode('utf-8'))
         else:
             log.err(failure)
-            self.sendLine('%d, %d : ERROR : %s' % (sport, cport, IdentError(failure.value)))
+            self.sendLine(('%d, %d : ERROR : %s' % (sport, cport, IdentError(failure.value))).encode('utf-8'))
 
 
     def lookup(self, serverAddress, clientAddress):
@@ -180,6 +180,7 @@
 
 
     def parseLine(self, line):
+        # unsure if decode() is required here as well
         parts = line.strip().split()
         localAddr, localPort = self.unpackAddress(parts[1])
         remoteAddr, remotePort = self.unpackAddress(parts[2])
@@ -213,7 +214,7 @@
         if len(self.queries) > 1:
             return self.queries[-1][0]
 
-        self.sendLine('%d, %d' % (portOnServer, portOnClient))
+        self.sendLine(('%d, %d' % (portOnServer, portOnClient)).encode('utf-8'))
         return self.queries[-1][0]
 
 
@@ -224,7 +225,7 @@
             d, _, _ = self.queries.pop(0)
             self.parseResponse(d, line)
             if self.queries:
-                self.sendLine('%d, %d' % (self.queries[0][1], self.queries[0][2]))
+                self.sendLine(('%d, %d' % (self.queries[0][1], self.queries[0][2])).encode('utf-8')
 
 
     def connectionLost(self, reason):
@@ -234,7 +235,7 @@
 
 
     def parseResponse(self, deferred, line):
-        parts = line.split(':', 2)
+        parts = line.decode("us-ascii").split(':', 2)
         if len(parts) != 3:
             deferred.errback(IdentError(line))
         else:

```

**Comment by adiroiban** [comment]
Many thanks, Moritz for the report and the patch.

I am not familiar with the ident protocol.

If `ident` is a 100% text only protocol, I think that all decoding should be done in "lineReceived" an all encoding should be done in `sendLine` 

And if `ident` is not harcdoded to `ascii` then use the `self.encoding` argument.

If you are interested into getting this merged, please send a PR and I can help with the review.

To ensure the quality of the code, we need at least one person sending a patch and at least one other person reviewing changes.

Thanks again

**Comment by wilhelmy** [comment]
Hi Adi, and thanks for the quick response.

ident is a very simple line-based protocol. By the looks of it the default is US-ASCII but it's possible to [specify a different character set](https://www.rfc-editor.org/rfc/rfc1413#section-5). 

That's a good point about `lineReceived`, however `sendLine` isn't defined in ident.py.
Does setting `self.encoding` change the type of values passed to these functions, or how is it handled?

Best regards,
Moritz

**Comment by adiroiban** [comment]
I see `class IdentServer(basic.LineOnlyReceiver):` ... this means that IdentServer should not send anything back.

But sendLine is defined here 
https://github.com/twisted/twisted/blob/34b161e66bc7c9f9efbb95e82c770a863933e498/src/twisted/protocols/basic.py#L453-L460

I guess that sendLines need to be reimplemented inside ident to do encoding

and parse USERID input to extract and update the encoding.

Cheers

**Comment by wilhelmy** [comment]
As I understand the docs, LineOnlyReceiver doesn't mean "doesn't send anything back" but "only supports line mode, not raw mode" https://docs.twistedmatrix.com/en/stable/api/twisted.protocols.basic.LineOnlyReceiver.html

Thanks for all the pointers, I'll see what I can do.

**Comment by adiroiban** [comment]
True. One option is to create a new `TextOnlyReceiver` that will work with str/Unicode instead of bytes, and will have a method to allow setting/switching the current encoding.
The encoding can be 'utf-8', as this should be 'ascii' backward compatbile. 

We can have this fixed just inside Ident, but I think there might be many other protocols that would benefit from this change.

Regards
