### ISSUE TITLE
Scrapy 在23.8版本的twisted下无法通过scrap crawl启动

### ISSUE THREAD

**Issue by Song-Silence** [twisted/twisted#11933]
Platform：MacOS 14.0 Beta版(23A5328b)
twisted：23.8
scrapy：2.10
python：3.11.5

通过scrapy crawl 启动spider项目出现以下错误：
2023-08-29 17:45:40 [scrapy.core.engine] INFO: Spider opened
2023-08-29 17:45:40 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2023-08-29 17:45:40 [legu] INFO: Spider opened: legu
2023-08-29 17:45:40 [legu] INFO: Spider opened: legu
2023-08-29 17:45:40 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
Traceback (most recent call last):
  File "/opt/homebrew/bin/scrapy", line 8, in <module>
    sys.exit(execute())
             ^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/scrapy/cmdline.py", line 161, in execute
    _run_print_help(parser, _run_command, cmd, args, opts)
  File "/opt/homebrew/lib/python3.11/site-packages/scrapy/cmdline.py", line 114, in _run_print_help
    func(*a, **kw)
  File "/opt/homebrew/lib/python3.11/site-packages/scrapy/cmdline.py", line 169, in _run_command
    cmd.run(args, opts)
  File "/opt/homebrew/lib/python3.11/site-packages/scrapy/commands/crawl.py", line 30, in run
    self.crawler_process.start()
  File "/opt/homebrew/lib/python3.11/site-packages/scrapy/crawler.py", line 390, in start
    install_shutdown_handlers(self._signal_shutdown)
  File "/opt/homebrew/lib/python3.11/site-packages/scrapy/utils/ossignal.py", line 19, in install_shutdown_handlers
    reactor._handleSignals()
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AsyncioSelectorReactor' object has no attribute '_handleSignals'

**Comment by Song-Silence** [comment]
我退回到twisted 22.10版本后解决了这个问题，可能是新版本更新了reactor的相关内容？

**Comment by Song-Silence** [comment]
我退回到twisted 22.10版本后解决了这个问题，可能是新版本更新了reactor的相关内容？

**Comment by adiroiban** [comment]
Thanks for the report.
Can you please provide the steps required to reproduce this issue?

It looks like the error is generated in `scrapy/utils/ossignal.py` and it looks like `scrapy` is calling some Twisted private methods.

was this issue raised with the scrappy project?

I am closing this for now, as it looks like a `scrapy` issue, but we can re-open it at any time.

Regards

**Comment by glyph** [comment]
Translating @Song-Silence's comment for readers' convenience:

> I solved this problem after returning to twisted version 22.10, maybe the new version updated the relevant content of reactor?

So it does seem likely this is an issue on our end that may bear investigating. Do we have a contact point at Scrapy project who might be interested?

**Comment by glyph** [comment]
> So it does seem likely this is an issue on our end

Oops, nope, it's a scrapy issue, I missed the fact that `scrapy.utils.ossignal` is calling into quite explicitly private reactor APIs (`._handleSignals`).

**Comment by glyph** [comment]
Here's the scrapy issue in question, already filed: https://github.com/scrapy/scrapy/issues/6024
