### ISSUE TITLE
Flaky twisted.internet.test.test_fdset.ReactorFDSetTestsBuilder_CFReactorTests

### ISSUE THREAD

**Issue by adiroiban** [twisted/twisted#12029]
I saw the `twisted.internet.test.test_fdset.ReactorFDSetTestsBuilder_CFReactorTests` tests failing on GitHub Action multiple times 

It's not a single test.

See if we can fix it or just disable the test on CI.

![image](https://github.com/twisted/twisted/assets/204609/3742b774-3b6f-43b4-a1a6-ba3ebd36f26a)

```
Error: 
Traceback (most recent call last):
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.8/site-packages/twisted/internet/test/test_fdset.py", line 133, in test_addWriter
    self.runReactor(reactor)
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.8/site-packages/twisted/internet/test/reactormixins.py", line 351, in runReactor
    raise TestTimeoutError(f"reactor still running after {timeout} seconds")
twisted.internet.test.reactormixins.TestTimeoutError: reactor still running after 120.0 seconds

twisted.internet.test.test_fdset.ReactorFDSetTestsBuilder_CFReactorTests.test_addWriter
===============================================================================
Error: 
Traceback (most recent call last):
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.8/site-packages/twisted/internet/base.py", line 1090, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.8/site-packages/twisted/internet/test/reactormixins.py", line 346, in stop
    reactor.stop()
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.8/site-packages/twisted/internet/cfreactor.py", line 536, in stop
    PosixReactorBase.stop(self)
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.8/site-packages/twisted/internet/base.py", line 794, in stop
    raise error.ReactorNotRunning("Can't stop reactor that isn't running.")
twisted.internet.error.ReactorNotRunning: Can't stop reactor that isn't running.

twisted.internet.test.test_fdset.ReactorFDSetTestsBuilder_CFReactorTests.test_addWriter
```

**Comment by adiroiban** [comment]
I gave it a try on my M1 macmini, but it looks like this test is harder to reproduce.

I tried to reproduce it but I ended up with a different error

```
% trial -u twisted.internet.test.test_fdset.ReactorFDSetTestsBuilder_CFReactorTests
or just
% trial -u twisted.internet.test.test_fdset.ReactorFDSetTestsBuilder_CFReactorTests.test_addWriter
or like our CI
% coverage run -m twisted.trial -u twisted.internet.test.test_fdset.ReactorFDSetTestsBuilder_CFReactorTests
``` 

after many test runs it fails with a different errro

```
===============================================================================
[SKIPPED]
'CFReactor' cannot detect lost file descriptors

twisted.internet.test.test_fdset.ReactorFDSetTestsBuilder_CFReactorTests.test_lostFileDescriptor
===============================================================================
[SKIPPED]
CFReactor uses APIs which manipulate global state, so it's not safe to run its own reactor-builder tests under itself

twisted.internet.test.test_fdset.ReactorFDSetTestsBuilder_CFReactorTests.test_removeAll
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/Users/chevah/adi/twisted/venv/lib/python3.9/site-packages/twisted/internet/test/test_fdset.py", line 357, in test_connectionLostOnShutdown
    client, server = self._connectedPair()
  File "/Users/chevah/adi/twisted/venv/lib/python3.9/site-packages/twisted/internet/test/test_fdset.py", line 60, in _connectedPair
    client, server = socketpair()
  File "/Users/chevah/adi/twisted/venv/lib/python3.9/site-packages/twisted/internet/test/test_fdset.py", line 35, in socketpair
    client.connect(("127.0.0.1", serverSocket.getsockname()[1]))
builtins.OSError: [Errno 49] Can't assign requested address

twisted.internet.test.test_fdset.ReactorFDSetTestsBuilder_CFReactorTests.test_connectionLostOnShutdown
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/Users/chevah/adi/twisted/venv/lib/python3.9/site-packages/twisted/internet/test/test_fdset.py", line 163, in test_getReaders
    self._getFDTest("Reader")
  File "/Users/chevah/adi/twisted/venv/lib/python3.9/site-packages/twisted/internet/test/test_fdset.py", line 145, in _getFDTest
    client, server = self._connectedPair()
  File "/Users/chevah/adi/twisted/venv/lib/python3.9/site-packages/twisted/internet/test/test_fdset.py", line 60, in _connectedPair
    client, server = socketpair()
  File "/Users/chevah/adi/twisted/venv/lib/python3.9/site-packages/twisted/internet/test/test_fdset.py", line 35, in socketpair
    client.connect(("127.0.0.1", serverSocket.getsockname()[1]))
builtins.OSError: [Errno 49] Can't assign requested address

twisted.internet.test.test_fdset.ReactorFDSetTestsBuilder_CFReactorTests.test_getReaders
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/Users/chevah/adi/twisted/venv/lib/python3.9/site-packages/twisted/internet/test/test_fdset.py", line 193, in test_getWriters
    self._getFDTest("Writer")
  File "/Users/chevah/adi/twisted/venv/lib/python3.9/site-packages/twisted/internet/test/test_fdset.py", line 145, in _getFDTest
    client, server = self._connectedPair()
  File "/Users/chevah/adi/twisted/venv/lib/python3.9/site-packages/twisted/internet/test/test_fdset.py", line 60, in _connectedPair
    client, server = socketpair()
  File "/Users/chevah/adi/twisted/venv/lib/python3.9/site-packages/twisted/internet/test/test_fdset.py", line 35, in socketpair
    client.connect(("127.0.0.1", serverSocket.getsockname()[1]))
builtins.OSError: [Errno 49] Can't assign requested address

twisted.internet.test.test_fdset.ReactorFDSetTestsBuilder_CFReactorTests.test_getWriters
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/Users/chevah/adi/twisted/venv/lib/python3.9/site-packages/twisted/internet/test/test_fdset.py", line 242, in test_negativeOneFileDescriptor
    client, server = self._connectedPair()
  File "/Users/chevah/adi/twisted/venv/lib/python3.9/site-packages/twisted/internet/test/test_fdset.py", line 60, in _connectedPair
    client, server = socketpair()
  File "/Users/chevah/adi/twisted/venv/lib/python3.9/site-packages/twisted/internet/test/test_fdset.py", line 35, in socketpair
    client.connect(("127.0.0.1", serverSocket.getsockname()[1]))
builtins.OSError: [Errno 49] Can't assign requested address

twisted.internet.test.test_fdset.ReactorFDSetTestsBuilder_CFReactorTests.test_negativeOneFileDescriptor
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/Users/chevah/adi/twisted/venv/lib/python3.9/site-packages/twisted/internet/test/test_fdset.py", line 100, in test_removeReader
    reactor, fd, server = self._simpleSetup()
  File "/Users/chevah/adi/twisted/venv/lib/python3.9/site-packages/twisted/internet/test/test_fdset.py", line 68, in _simpleSetup
    client, server = self._connectedPair()
  File "/Users/chevah/adi/twisted/venv/lib/python3.9/site-packages/twisted/internet/test/test_fdset.py", line 60, in _connectedPair
    client, server = socketpair()
  File "/Users/chevah/adi/twisted/venv/lib/python3.9/site-packages/twisted/internet/test/test_fdset.py", line 35, in socketpair
    client.connect(("127.0.0.1", serverSocket.getsockname()[1]))
builtins.OSError: [Errno 49] Can't assign requested address

twisted.internet.test.test_fdset.ReactorFDSetTestsBuilder_CFReactorTests.test_removeReader
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/Users/chevah/adi/twisted/venv/lib/python3.9/site-packages/twisted/internet/test/test_fdset.py", line 171, in test_removeWriter
    reactor, fd, server = self._simpleSetup()
  File "/Users/chevah/adi/twisted/venv/lib/python3.9/site-packages/twisted/internet/test/test_fdset.py", line 68, in _simpleSetup
    client, server = self._connectedPair()
  File "/Users/chevah/adi/twisted/venv/lib/python3.9/site-packages/twisted/internet/test/test_fdset.py", line 60, in _connectedPair
    client, server = socketpair()
  File "/Users/chevah/adi/twisted/venv/lib/python3.9/site-packages/twisted/internet/test/test_fdset.py", line 35, in socketpair
    client.connect(("127.0.0.1", serverSocket.getsockname()[1]))
builtins.OSError: [Errno 49] Can't assign requested address

twisted.internet.test.test_fdset.ReactorFDSetTestsBuilder_CFReactorTests.test_removeWriter
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/Users/chevah/adi/twisted/venv/lib/python3.9/site-packages/twisted/internet/test/test_fdset.py", line 230, in test_removedFromReactor
    descriptor = RemovingDescriptor(reactor)
  File "/Users/chevah/adi/twisted/venv/lib/python3.9/site-packages/twisted/internet/test/test_fdset.py", line 390, in __init__
    self.read, self.write = socketpair()
  File "/Users/chevah/adi/twisted/venv/lib/python3.9/site-packages/twisted/internet/test/test_fdset.py", line 35, in socketpair
    client.connect(("127.0.0.1", serverSocket.getsockname()[1]))
builtins.OSError: [Errno 49] Can't assign requested address

twisted.internet.test.test_fdset.ReactorFDSetTestsBuilder_CFReactorTests.test_removedFromReactor
-------------------------------------------------------------------------------
Ran 11 tests in 0.011s

FAILED (skips=2, errors=7, successes=2)
```

**Comment by glyph** [comment]
What run are you getting to? I get to around 8500, which is getting into the scale of test where you might run out of actual system TCP resources for a few seconds.  Which is borne out by the fact that if I immediately run the tests again, they fail immediately.  So this failure is just a feature of the BSD TCP stack, not really a bug in Twisted or the tests.

**Comment by glyph** [comment]
```
Test Pass 8452
twisted.internet.test.test_fdset
  ReactorFDSetTestsBuilder_CFReactorTests
    test_addWriter ...                                                  [ERROR]

===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/Users/glyph/Projects/Twisted/src/twisted/internet/test/test_fdset.py", line 124, in test_addWriter
    reactor, fd, server = self._simpleSetup()
  File "/Users/glyph/Projects/Twisted/src/twisted/internet/test/test_fdset.py", line 68, in _simpleSetup
    client, server = self._connectedPair()
  File "/Users/glyph/Projects/Twisted/src/twisted/internet/test/test_fdset.py", line 60, in _connectedPair
    client, server = socketpair()
  File "/Users/glyph/Projects/Twisted/src/twisted/internet/test/test_fdset.py", line 35, in socketpair
    client.connect(("127.0.0.1", serverSocket.getsockname()[1]))
builtins.OSError: [Errno 49] Can't assign requested address

twisted.internet.test.test_fdset.ReactorFDSetTestsBuilder_CFReactorTests.test_addWriter
-------------------------------------------------------------------------------
Ran 1 tests in 0.001s

FAILED (errors=1)
 ↪ Tue Oct 31 00:01:53 PDT 2023 (★ trial -u twisted.internet.test.test_fdset.ReactorFDSetTestsBuilder_CFReactorTests.test_addWriter) (20 seconds elapsed)                     
glyph@arabella:~/Projects/Twisted  🏰 Twisted  🔀 trunk  🐚 🔑   🛑 1  🐳 🫛  🖥️  ✅  ⮐
  ★ trial -u twisted.internet.test.test_fdset.ReactorFDSetTestsBuilder_CFReactorTests.test_addWriter
 ↩ Tue Oct 31 00:01:54 PDT 2023
Test Pass 1
twisted.internet.test.test_fdset
  ReactorFDSetTestsBuilder_CFReactorTests
    test_addWriter ...                                                  [ERROR]

===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/Users/glyph/Projects/Twisted/src/twisted/internet/test/test_fdset.py", line 124, in test_addWriter
    reactor, fd, server = self._simpleSetup()
  File "/Users/glyph/Projects/Twisted/src/twisted/internet/test/test_fdset.py", line 68, in _simpleSetup
    client, server = self._connectedPair()
  File "/Users/glyph/Projects/Twisted/src/twisted/internet/test/test_fdset.py", line 60, in _connectedPair
    client, server = socketpair()
  File "/Users/glyph/Projects/Twisted/src/twisted/internet/test/test_fdset.py", line 35, in socketpair
    client.connect(("127.0.0.1", serverSocket.getsockname()[1]))
builtins.OSError: [Errno 49] Can't assign requested address

twisted.internet.test.test_fdset.ReactorFDSetTestsBuilder_CFReactorTests.test_addWriter
-------------------------------------------------------------------------------
Ran 1 tests in 0.002s

FAILED (errors=1)
 ↪ Tue Oct 31 00:01:55 PDT 2023 (★ trial -u twisted.internet.test.test_fdset.ReactorFDSetTestsBuilder_CFReactorTests.test_addWriter) (1 seconds elapsed)                      
glyph@arabella:~/Projects/Twisted  🏰 Twisted  🔀 trunk  🐚 🔑   🛑 1  🐳 🫛  🖥️  ✅  ⮐
  ★ trial -u twisted.internet.test.test_fdset.ReactorFDSetTestsBuilder_CFReactorTests.test_addWriter
 ↩ Tue Oct 31 00:01:56 PDT 2023
Test Pass 1
twisted.internet.test.test_fdset
  ReactorFDSetTestsBuilder_CFReactorTests
    test_addWriter ...                                                  [ERROR]

===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/Users/glyph/Projects/Twisted/src/twisted/internet/test/test_fdset.py", line 124, in test_addWriter
    reactor, fd, server = self._simpleSetup()
  File "/Users/glyph/Projects/Twisted/src/twisted/internet/test/test_fdset.py", line 68, in _simpleSetup
    client, server = self._connectedPair()
  File "/Users/glyph/Projects/Twisted/src/twisted/internet/test/test_fdset.py", line 60, in _connectedPair
    client, server = socketpair()
  File "/Users/glyph/Projects/Twisted/src/twisted/internet/test/test_fdset.py", line 35, in socketpair
    client.connect(("127.0.0.1", serverSocket.getsockname()[1]))
builtins.OSError: [Errno 49] Can't assign requested address

twisted.internet.test.test_fdset.ReactorFDSetTestsBuilder_CFReactorTests.test_addWriter
-------------------------------------------------------------------------------
Ran 1 tests in 0.002s

FAILED (errors=1)
 ↪ Tue Oct 31 00:01:56 PDT 2023 (★ trial -u twisted.internet.test.test_fdset.ReactorFDSetTestsBuilder_CFReactorTests.test_addWriter)                                          
glyph@arabella:~/Projects/Twisted  🏰 Twisted  🔀 trunk  🐚 🔑   🛑 1  🐳 🫛  🖥️  ✅  ⮐
  ★ 
```

**Comment by glyph** [comment]
Note that the first thing in the output there is `Test Pass 8452`, but the next one fails *immediately* at `Test Pass 1`.  Wait 240 seconds for MSLx2 to elapse, the system's TCP resources are restored, and you can get a similar number of passes again.

**Comment by adiroiban** [comment]
I get the same TCP stack error.

The problem is that I was not albe to reproduce the "original" error

**Comment by adiroiban** [comment]
I just added a simple  sleep to one of those tests to let macOS free up the sockets ... in the hope that the test run can trigger the same error that is observed on GitHub Actions

not luck

I think is best to  just skip the test for now, and re-enable it one someone has more time for Twisted on macos with cfreactor.

**Comment by adiroiban** [comment]
With the sleep in place, to prevent the TCP socket error, I ended up with another error on macos... but this time for the `select` reactor

```
[FAIL]
Traceback (most recent call last):
  File "/Users/chevah/adi/twisted/venv/lib/python3.9/site-packages/twisted/internet/test/test_fdset.py", line 266, in test_negativeOneFileDescriptor
    self.assertEqual(descriptor._received, b"x")
  File "/Users/chevah/adi/twisted/venv/lib/python3.9/site-packages/twisted/trial/_synctest.py", line 444, in assertEqual
    super().assertEqual(first, second, msg)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 831, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 824, in _baseAssertEqual
    raise self.failureException(msg)
twisted.trial.unittest.FailTest: b'' != b'x'

twisted.internet.test.test_fdset.ReactorFDSetTestsBuilder_SelectReactorTests.test_negativeOneFileDescriptor
```

**Comment by adiroiban** [comment]
There is also this test failing with a similar error 

```
Traceback (most recent call last):
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.8/site-packages/twisted/internet/test/test_core.py", line 117, in test_signalHandlersInstalledDuringStartup
    self.runReactor(reactor)
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.8/site-packages/twisted/internet/test/reactormixins.py", line 351, in runReactor
    raise TestTimeoutError(f"reactor still running after {timeout} seconds")
twisted.internet.test.reactormixins.TestTimeoutError: reactor still running after 120.0 seconds

twisted.internet.test.test_core.SystemEventTestsBuilder_CFReactorTests.test_signalHandlersInstalledDuringStartup
```

**Comment by adiroiban** [comment]
Not sure what we can do with #12029 ... 

They can be annoying for doing auto-merge

maybe just skip the test as part of the main test suite, and re-run the test in a separate job that will automatically retry twice on errors.

---------

I think that once a test fails, just retrying the test in the same run will not work, as the tests is failing due to a side effect

**Comment by adiroiban** [comment]
This is duplicate of #11711

Thanks Glyph
