### ISSUE TITLE
Fix inlineCallbacks tests on Python 3.13

### ISSUE THREAD

**Issue by adiroiban** [twisted/twisted#12061]
Failing tests

```
[FAIL]
Traceback (most recent call last):
  File "/home/adi/chevah/twisted/src/twisted/internet/test/test_inlinecb.py", line 192, in test_forwardLotsOfTracebacks
    self.assertIn("in erroring", tb)
  File "/home/adi/chevah/twisted/src/twisted/trial/_synctest.py", line 509, in assertIn
    raise self.failureException(msg or f"{containee!r} not in {container!r}")
twisted.trial.unittest.FailTest: 'in erroring' not in 'Traceback (most recent call last):\n  File "/home/adi/chevah/twisted/src/twisted/python/util.py", line 958, in runWithWarningsSuppressed\n    return f(*args, **kwargs)\n  File "/home/adi/chevah/twisted/src/twisted/internet/test/test_inlinecb.py", line 189, in test_forwardLotsOfTracebacks\n    d = calling()\n  File "/home/adi/chevah/twisted/src/twisted/internet/defer.py", line 2256, in unwindGenerator\n    return _cancellableInlineCallbacks(gen)\n  File "/home/adi/chevah/twisted/src/twisted/internet/defer.py", line 2168, in _cancellableInlineCallbacks\n    _inlineCallbacks(None, gen, status, _copy_context())\n--- <exception caught here> ---\n  File "/home/adi/chevah/twisted/src/twisted/internet/defer.py", line 1996, in _inlineCallbacks\n    result = context.run(\n  File "/home/adi/chevah/twisted/src/twisted/python/failure.py", line 519, in throwExceptionIntoGenerator\n    return g.throw(self.type, self.value, self.tb)\n  File "/home/adi/chevah/twisted/src/twisted/internet/test/test_inlinecb.py", line 187, in calling\n    yield calling2()\nbuiltins.Exception: Error Marker\n'

twisted.internet.test.test_inlinecb.ForwardTraceBackTests.test_forwardLotsOfTracebacks
===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/home/adi/chevah/twisted/src/twisted/internet/test/test_inlinecb.py", line 149, in test_forwardTracebacks
    self.assertIn("in erroring", tb)
  File "/home/adi/chevah/twisted/src/twisted/trial/_synctest.py", line 509, in assertIn
    raise self.failureException(msg or f"{containee!r} not in {container!r}")
twisted.trial.unittest.FailTest: 'in erroring' not in 'Traceback (most recent call last):\n  File "/home/adi/chevah/twisted/src/twisted/python/util.py", line 958, in runWithWarningsSuppressed\n    return f(*args, **kwargs)\n  File "/home/adi/chevah/twisted/src/twisted/internet/test/test_inlinecb.py", line 146, in test_forwardTracebacks\n    d = calling()\n  File "/home/adi/chevah/twisted/src/twisted/internet/defer.py", line 2256, in unwindGenerator\n    return _cancellableInlineCallbacks(gen)\n  File "/home/adi/chevah/twisted/src/twisted/internet/defer.py", line 2168, in _cancellableInlineCallbacks\n    _inlineCallbacks(None, gen, status, _copy_context())\n--- <exception caught here> ---\n  File "/home/adi/chevah/twisted/src/twisted/internet/defer.py", line 1996, in _inlineCallbacks\n    result = context.run(\n  File "/home/adi/chevah/twisted/src/twisted/python/failure.py", line 519, in throwExceptionIntoGenerator\n    return g.throw(self.type, self.value, self.tb)\n  File "/home/adi/chevah/twisted/src/twisted/internet/test/test_inlinecb.py", line 144, in calling\n    yield erroring()\nbuiltins.Exception: Error Marker\n'

twisted.internet.test.test_inlinecb.ForwardTraceBackTests.test_forwardTracebacks
```

My traceback on Python 3.11

```
'Traceback (most recent call last):
  File "/home/adi/chevah/twisted/src/twisted/internet/defer.py", line 2000, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "/home/adi/chevah/twisted/src/twisted/internet/test/test_inlinecb.py", line 144, in calling
    yield erroring()
  File "/home/adi/chevah/twisted/src/twisted/internet/defer.py", line 2256, in unwindGenerator
    return _cancellableInlineCallbacks(gen)
  File "/home/adi/chevah/twisted/src/twisted/internet/defer.py", line 2168, in _cancellableInlineCallbacks
    _inlineCallbacks(None, gen, status, _copy_context())
--- <exception caught here> ---
  File "/home/adi/chevah/twisted/src/twisted/internet/test/test_inlinecb.py", line 144, in calling
    yield erroring()
  File "/home/adi/chevah/twisted/src/twisted/internet/defer.py", line 2000, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "/home/adi/chevah/twisted/src/twisted/internet/test/test_inlinecb.py", line 140, in erroring
    raise Exception("Error Marker")
builtins.Exception: Error Marker
'
```

My traceback on Python 3.13

```
'Traceback (most recent call last):
  File "/home/adi/chevah/twisted/src/twisted/python/util.py", line 958, in runWithWarningsSuppressed
    return f(*args, **kwargs)
  File "/home/adi/chevah/twisted/src/twisted/internet/test/test_inlinecb.py", line 146, in test_forwardTracebacks
    d = calling()
  File "/home/adi/chevah/twisted/src/twisted/internet/defer.py", line 2256, in unwindGenerator
    return _cancellableInlineCallbacks(gen)
  File "/home/adi/chevah/twisted/src/twisted/internet/defer.py", line 2168, in _cancellableInlineCallbacks
    _inlineCallbacks(None, gen, status, _copy_context())
--- <exception caught here> ---
  File "/home/adi/chevah/twisted/src/twisted/internet/defer.py", line 1996, in _inlineCallbacks
    result = context.run(
  File "/home/adi/chevah/twisted/src/twisted/python/failure.py", line 519, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/adi/chevah/twisted/src/twisted/internet/test/test_inlinecb.py", line 144, in calling
    yield erroring()
builtins.Exception: Error Marker
'
```

**Comment by itamarst** [comment]
I believe the issue is that the way bytecode is generated for yields in 3.13 is different, so this should be fixable by changes to `failure.py` rather than the tests. I have an empirically derived fix, it's not clear if it matches all possible situations though... would need to dig through CPython source code maybe.

**Comment by glaubitz** [comment]
Could someone point me to the actual commit that fixes this test failure? I need to backport the fix for this failure since a new upstream version has not been released yet and even after looking at the changes for a longer time, I'm not sure what part of #12292 fixes this test failure.

Thanks!

**Comment by adiroiban** [comment]
I don't think there is a single commit.

I think that once Twisted is supported on Python 3.13 we should do a release.
No need for backport.

I think that we are quite close to 3.13 support https://github.com/twisted/twisted/issues/11750

...and it needed, we can also do a release with support just for Linux + macOS

**Comment by itamarst** [comment]
In the short term, you can install Twisted from git (a specific commit, even, if you want reproducibility) with standard pip install and equivalent tools: https://adamj.eu/tech/2019/03/11/pip-install-from-a-git-repository/

**Comment by glaubitz** [comment]
> In the short term, you can install Twisted from git (a specific commit, even, if you want reproducibility) with standard pip install and equivalent tools: https://adamj.eu/tech/2019/03/11/pip-install-from-a-git-repository/

Thanks, but I'm working on a distribution package to fix compatibility with Python 3.13 in openSUSE, so I have to rely on releases.

**Comment by adiroiban** [comment]
@glaubitz  is the code from `trunk` working for you?

To help with various Linux releases, I guess that we can do a new release, even if not yet compatible with Windows (we are just waiting for pywin32)

**Comment by glaubitz** [comment]
> @glaubitz is the code from `trunk` working for you?

Unfortunately not, there are still failures:

```
twisted.web.test.test_tap.ServiceTests.test_HTTPSFailureOnMissingSSL
===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/twisted/conch/test/test_manhole.py", line 237, in finished
    self._assertBuffer(
  File "/usr/lib/python3.13/site-packages/twisted/conch/test/test_recvline.py", line 476, in _assertBuffer
    self.assertEqual(receivedLines, expectedLines)
  File "/usr/lib/python3.13/site-packages/twisted/trial/_synctest.py", line 444, in assertEqual
    super().assertEqual(first, second, msg)
  File "/usr/lib64/python3.13/unittest/case.py", line 907, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib64/python3.13/unittest/case.py", line 1113, in assertListEqual
    self.assertSequenceEqual(list1, list2, msg, seq_type=list)
  File "/usr/lib64/python3.13/unittest/case.py", line 1095, in assertSequenceEqual
    self.fail(msg)
twisted.trial.unittest.FailTest: Lists differ: [b">>[32 chars]", b'Exception: foo bar baz', b'>>> done', b''[91 chars] b''] != [b">>[32 chars]", b'Traceback (most recent call last):', b'  [164 chars] b'']

First differing element 1:
b'Exception: foo bar baz'
b'Traceback (most recent call last):'

  [b">>> raise Exception('foo bar baz')",
+  b'Traceback (most recent call last):',
+  b'  File "<console>", line 1, in <module>',
   b'Exception: foo bar baz',
   b'>>> done',
   b'',
   b'',
   b'',
   b'',
   b'',
   b'',
   b'',
   b'',
   b'',
   b'',
   b'',
   b'',
   b'',
   b'',
   b'',
   b'',
   b'',
-  b'',
-  b'',
   b'']

twisted.conch.test.test_manhole.ManholeLoopbackSSHTests.test_Exception
twisted.conch.test.test_manhole.ManholeLoopbackSSHTests.test_ExceptionWithCustomExcepthook
twisted.conch.test.test_manhole.ManholeLoopbackStdioTests.test_Exception
twisted.conch.test.test_manhole.ManholeLoopbackStdioTests.test_ExceptionWithCustomExcepthook
twisted.conch.test.test_manhole.ManholeLoopbackTelnetTests.test_Exception
twisted.conch.test.test_manhole.ManholeLoopbackTelnetTests.test_ExceptionWithCustomExcepthook
===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/twisted/internet/test/test_inlinecb.py", line 1213, in test_forwardLotsOfTracebacks
    self.assertIn("in erroring", tb)
  File "/usr/lib/python3.13/site-packages/twisted/trial/_synctest.py", line 509, in assertIn
    raise self.failureException(msg or f"{containee!r} not in {container!r}")
twisted.trial.unittest.FailTest: 'in erroring' not in 'Traceback (most recent call last):\n  File "/usr/lib/python3.13/site-packages/twisted/python/util.py", line 955, in runWithWarningsSuppressed\n    return f(*args, **kwargs)\n  File "/usr/lib/python3.13/site-packages/twisted/internet/test/test_inlinecb.py", line 1210, in test_forwardLotsOfTracebacks\n    d = calling()\n  File "/usr/lib/python3.13/site-packages/twisted/internet/defer.py", line 2287, in unwindGenerator\n    return _cancellableInlineCallbacks(gen)\n  File "/usr/lib/python3.13/site-packages/twisted/internet/defer.py", line 2197, in _cancellableInlineCallbacks\n    _inlineCallbacks(None, gen, status, _copy_context())\n--- <exception caught here> ---\n  File "/usr/lib/python3.13/site-packages/twisted/internet/defer.py", line 2010, in _inlineCallbacks\n    result = context.run(\n  File "/usr/lib/python3.13/site-packages/twisted/python/failure.py", line 549, in throwExceptionIntoGenerator\n    return g.throw(self.value.with_traceback(self.tb))\n  File "/usr/lib/python3.13/site-packages/twisted/internet/test/test_inlinecb.py", line 1208, in calling\n    yield calling2()\nbuiltins.Exception: Error Marker\n'

twisted.internet.test.test_inlinecb.ForwardTraceBackTests.test_forwardLotsOfTracebacks
===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/twisted/internet/test/test_inlinecb.py", line 1248, in test_forwardLotsOfTracebacksCoro
    self.assertIn("in erroring", tb)
  File "/usr/lib/python3.13/site-packages/twisted/trial/_synctest.py", line 509, in assertIn
    raise self.failureException(msg or f"{containee!r} not in {container!r}")
twisted.trial.unittest.FailTest: 'in erroring' not in 'Traceback (most recent call last):\n  File "/usr/lib/python3.13/site-packages/twisted/python/util.py", line 955, in runWithWarningsSuppressed\n    return f(*args, **kwargs)\n  File "/usr/lib/python3.13/site-packages/twisted/internet/test/test_inlinecb.py", line 1245, in test_forwardLotsOfTracebacksCoro\n    d = calling()\n  File "/usr/lib/python3.13/site-packages/twisted/internet/defer.py", line 2287, in unwindGenerator\n    return _cancellableInlineCallbacks(gen)\n  File "/usr/lib/python3.13/site-packages/twisted/internet/defer.py", line 2197, in _cancellableInlineCallbacks\n    _inlineCallbacks(None, gen, status, _copy_context())\n--- <exception caught here> ---\n  File "/usr/lib/python3.13/site-packages/twisted/internet/defer.py", line 2010, in _inlineCallbacks\n    result = context.run(\n  File "/usr/lib/python3.13/site-packages/twisted/python/failure.py", line 549, in throwExceptionIntoGenerator\n    return g.throw(self.value.with_traceback(self.tb))\n  File "/usr/lib/python3.13/site-packages/twisted/internet/test/test_inlinecb.py", line 1243, in calling\n    yield calling2()\nbuiltins.Exception: Error Marker\n'

twisted.internet.test.test_inlinecb.ForwardTraceBackTests.test_forwardLotsOfTracebacksCoro
===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/twisted/internet/test/test_inlinecb.py", line 1145, in test_forwardTracebacks
    self.assertIn("in erroring", tb)
  File "/usr/lib/python3.13/site-packages/twisted/trial/_synctest.py", line 509, in assertIn
    raise self.failureException(msg or f"{containee!r} not in {container!r}")
twisted.trial.unittest.FailTest: 'in erroring' not in 'Traceback (most recent call last):\n  File "/usr/lib/python3.13/site-packages/twisted/python/util.py", line 955, in runWithWarningsSuppressed\n    return f(*args, **kwargs)\n  File "/usr/lib/python3.13/site-packages/twisted/internet/test/test_inlinecb.py", line 1142, in test_forwardTracebacks\n    d = calling()\n  File "/usr/lib/python3.13/site-packages/twisted/internet/defer.py", line 2287, in unwindGenerator\n    return _cancellableInlineCallbacks(gen)\n  File "/usr/lib/python3.13/site-packages/twisted/internet/defer.py", line 2197, in _cancellableInlineCallbacks\n    _inlineCallbacks(None, gen, status, _copy_context())\n--- <exception caught here> ---\n  File "/usr/lib/python3.13/site-packages/twisted/internet/defer.py", line 2010, in _inlineCallbacks\n    result = context.run(\n  File "/usr/lib/python3.13/site-packages/twisted/python/failure.py", line 549, in throwExceptionIntoGenerator\n    return g.throw(self.value.with_traceback(self.tb))\n  File "/usr/lib/python3.13/site-packages/twisted/internet/test/test_inlinecb.py", line 1140, in calling\n    yield erroring()\nbuiltins.Exception: Error Marker\n'

twisted.internet.test.test_inlinecb.ForwardTraceBackTests.test_forwardTracebacks
===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/twisted/test/test_failure.py", line 1027, in test_findFailureInGenerator
    self.assertEqual(foundFailures, [f])
  File "/usr/lib/python3.13/site-packages/twisted/trial/_synctest.py", line 444, in assertEqual
    super().assertEqual(first, second, msg)
  File "/usr/lib64/python3.13/unittest/case.py", line 907, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib64/python3.13/unittest/case.py", line 1113, in assertListEqual
    self.assertSequenceEqual(list1, list2, msg, seq_type=list)
  File "/usr/lib64/python3.13/unittest/case.py", line 1095, in assertSequenceEqual
    self.fail(msg)
twisted.trial.unittest.FailTest: Lists differ: [None] != [<twisted.python.failure.Failure builtins.ZeroDivisionError: division by zero>]

First differing element 0:
None
<twisted.python.failure.Failure builtins.ZeroDivisionError: division by zero>

- [None]
+ [<twisted.python.failure.Failure builtins.ZeroDivisionError: division by zero>]

twisted.test.test_failure.ExtendedGeneratorTests.test_findFailureInGenerator
-------------------------------------------------------------------------------
Ran 11474 tests in 226.201s

FAILED (skips=774, failures=10, successes=10690)
Exception ignored in: <function gc_cumulative_time.<locals>.gc_callback at 0x7fa6b276a840>
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/hypothesis/internal/conjecture/junkdrawer.py", line 441, in gc_callback
TypeError: 'NoneType' object is not callable
Exception ignored in: <function gc_cumulative_time.<locals>.gc_callback at 0x7fa6b276a840>
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/hypothesis/internal/conjecture/junkdrawer.py", line 441, in gc_callback
TypeError: 'NoneType' object is not callable
```

**Comment by adiroiban** [comment]
@glaubitz Which version of Python do you use ?

Can you please create a new report ?

I can then link it to  https://github.com/twisted/twisted/issues/11750

----------

From what I can tell, at a high level project management, Twisted on Linux works ok with 3.13

We have the test runs OK for Ubuntu, using `Python 3.13.0-rc.2`

https://github.com/twisted/twisted/actions/runs/10926733537/job/30331300450#step:10:2521


I can see the tests pass

```
  ForwardTraceBackTests
    test_forwardLotsOfTracebacks ...                                       [OK]
    test_forwardLotsOfTracebacksCoro ...                                   [OK]
    test_forwardTracebacks ...                                             [OK]
    test_forwardTracebacksCoro ...                                         [OK]
    test_reraiseTracebacksFromDeferred ...                                 [OK]
```

I think is better to have a new GitHub issue and discuss the errors observed with your build.

Thanks

**Comment by itamarst** [comment]
I see no tests failures locally with Python 3.13.0rc2 running tests on `trunk`.

**Comment by glaubitz** [comment]
> @glaubitz Which version of Python do you use ?

I tested with:

```
abuild@suse-laptop:~> python3.13
Python 3.13.0rc2 (main, Sep 07 2024, 16:06:06) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

> From what I can tell, at a high level project management, Twisted on Linux works ok with 3.13
> 
> We have the test runs OK for Ubuntu, using `Python 3.13.0-rc.2`
> 
> https://github.com/twisted/twisted/actions/runs/10926733537/job/30331300450#step:10:2521
> 
> I can see the tests pass
> 
> ```
>   ForwardTraceBackTests
>     test_forwardLotsOfTracebacks ...                                       [OK]
>     test_forwardLotsOfTracebacksCoro ...                                   [OK]
>     test_forwardTracebacks ...                                             [OK]
>     test_forwardTracebacksCoro ...                                         [OK]
>     test_reraiseTracebacksFromDeferred ...                                 [OK]
> ```

Well, it might also just me being unable to run the tests properly. Maybe I'm missing an important dependency.

I think that releasing a new upstream version wouldn't hurt as other distributions like Debian and Fedora want to prepare the switch to Python 3.13 as well.
