### ISSUE TITLE
`twisted.internet.test.test_tcp.AbortConnectionTests_*Tests.test_fullWriteBuffer` test timeout on macOS

### ISSUE THREAD

**Issue by glyph** [twisted/twisted#12151]
while debugging https://github.com/twisted/twisted/pull/12150 I saw this error locally:

```
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/Users/glyph/Projects/Twisted/.tox/py312-alldeps-withcov-macos/lib/python3.12/site-packages/twisted/internet/test/test_tcp.py", line 2867, in test_fullWriteBuffer
    self.runAbortTest(StreamingProducerClient, NoReadServer)
  File "/Users/glyph/Projects/Twisted/.tox/py312-alldeps-withcov-macos/lib/python3.12/site-packages/twisted/internet/test/test_tcp.py", line 2763, in runAbortTest
    reactor = runProtocolsWithReactor(self, server, client, self.endpoints)
  File "/Users/glyph/Projects/Twisted/.tox/py312-alldeps-withcov-macos/lib/python3.12/site-packages/twisted/internet/test/connectionmixins.py", line 177, in runProtocolsWithReactor
    reactorBuilder.runReactor(reactor)
  File "/Users/glyph/Projects/Twisted/.tox/py312-alldeps-withcov-macos/lib/python3.12/site-packages/twisted/internet/test/reactormixins.py", line 356, in runReactor
    raise TestTimeoutError(f"reactor still running after {timeout} seconds")
twisted.internet.test.reactormixins.TestTimeoutError: reactor still running after 120.0 seconds

twisted.internet.test.test_tcp.AbortConnectionTests_AsyncioSelectorReactorTests.test_fullWriteBuffer
-------------------------------------------------------------------------------
Ran 10823 tests in 138.537s

FAILED (skips=584, errors=1, successes=10238)
ERROR: InvocationError for command /Users/glyph/Projects/Twisted/.tox/py312-alldeps-withcov-macos/bin/coverage run -p --rcfile=/Users/glyph/Projects/Twisted/.coveragerc -m twisted.trial --temp-directory=/Users/glyph/Projects/Twisted/.tox/py312-alldeps-withcov-macos/tmp/_trial_temp --reporter=verbose -j8 twisted (exited with code 1)
```

which suggests that maybe CFReactor isn't the only flaky test in there…

**Comment by adiroiban** [comment]
I am trying to reproduce it.


I am using something like this on Ubuntu... 

```
$ trial -u -j 8 twisted.internet.test.test_tcp
```

It failed with

```
twisted.internet.test.test_tcp.TCPTransportTestsBuilder_GIReactorTests.test_writeSequenceWithUnicodeRaisesException
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/home/adi/chevah/twisted/src/twisted/internet/posixbase.py", line 487, in _doReadOrWrite
    why = selectable.doWrite()
  File "/home/adi/chevah/twisted/src/twisted/internet/tcp.py", line 617, in doConnect
    self._connectDone()
  File "/home/adi/chevah/twisted/src/twisted/internet/tcp.py", line 630, in _connectDone
    self.protocol = self.connector.buildProtocol(self.getPeer())
  File "/home/adi/chevah/twisted/src/twisted/internet/base.py", line 1291, in buildProtocol
    return self.factory.buildProtocol(addr)
  File "/home/adi/chevah/twisted/src/twisted/internet/protocol.py", line 131, in buildProtocol
    assert self.protocol is not None
builtins.AssertionError: 

twisted.internet.test.test_tcp.TCP4ClientTestsBuilder_EPollReactorTests.test_clientConnectionFailedStopsReactor
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/home/adi/chevah/twisted/src/twisted/internet/asyncioreactor.py", line 138, in _readOrWrite
    why = method()
  File "/home/adi/chevah/twisted/src/twisted/internet/tcp.py", line 617, in doConnect
    self._connectDone()
  File "/home/adi/chevah/twisted/src/twisted/internet/tcp.py", line 630, in _connectDone
    self.protocol = self.connector.buildProtocol(self.getPeer())
  File "/home/adi/chevah/twisted/src/twisted/internet/base.py", line 1291, in buildProtocol
    return self.factory.buildProtocol(addr)
  File "/home/adi/chevah/twisted/src/twisted/internet/protocol.py", line 131, in buildProtocol
    assert self.protocol is not None
builtins.AssertionError: 

twisted.internet.test.test_tcp.TCP4ClientTestsBuilder_AsyncioSelectorReactorTests.test_clientConnectionFailedStopsReactor
-------------------------------------------------------------------------------
Ran 473 tests in 0.410s

FAILED (skips=87, errors=2, successes=384)
```


If I don't run in parallel... it  doesn't look like it's failing.

**Comment by adiroiban** [comment]
Another failure anter running in a loop for about 1 minute

```
[ERROR]
Traceback (most recent call last):
  File "/home/adi/chevah/twisted/src/twisted/internet/selectreactor.py", line 148, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "/home/adi/chevah/twisted/src/twisted/internet/tcp.py", line 617, in doConnect
    self._connectDone()
  File "/home/adi/chevah/twisted/src/twisted/internet/tcp.py", line 630, in _connectDone
    self.protocol = self.connector.buildProtocol(self.getPeer())
  File "/home/adi/chevah/twisted/src/twisted/internet/base.py", line 1291, in buildProtocol
    return self.factory.buildProtocol(addr)
  File "/home/adi/chevah/twisted/src/twisted/internet/protocol.py", line 131, in buildProtocol
    assert self.protocol is not None
builtins.AssertionError: 

twisted.internet.test.test_tcp.TCP6ClientTestsBuilder_SelectReactorTests.test_clientConnectionFailedStopsReactor
-------------------------------------------------------------------------------
Ran 473 tests in 0.810s

FAILED (skips=87, errors=1, successes=385)
```

**Comment by glyph** [comment]
The issue here has to do with vagaries regarding the maximum outbound buffer size.  It writes one big outgoing chunk, then assumes that this chunk is big enough to flood its own buffer.  IF the OS were to actually consume that data somehow, and just put it into a big buffer, hanging is what we would logically see.

**Comment by glyph** [comment]
I can actually get a failure relatively quickly with just `trial -u twisted.internet.test.test_tcp.AbortConnectionTests_AsyncioSelectorReactorTests.test_fullWriteBuffer`; it craps out a bit over 500 iterations for me.

**Comment by adiroiban** [comment]
> trial -u twisted.internet.test.test_tcp.AbortConnectionTests_AsyncioSelectorReactorTests.test_fullWriteBuffer

On Ubuntu Desktop 23.10 (default kernel setup) I am not able to get that test to fail.
It was running for more than 30.000 iteration, without a failure

**Comment by adiroiban** [comment]
After the merge of https://github.com/twisted/twisted/pull/12160 i still get an error.... but it might be due to OS limitations

```
$ netstat -tan | grep TIME_WAIT | wc -l
21214
```

```
[ERROR]
Traceback (most recent call last):
  File "/home/adi/chevah/twisted/src/twisted/internet/asyncioreactor.py", line 138, in _readOrWrite
    why = method()
  File "/home/adi/chevah/twisted/src/twisted/internet/tcp.py", line 617, in doConnect
    self._connectDone()
  File "/home/adi/chevah/twisted/src/twisted/internet/tcp.py", line 630, in _connectDone
    self.protocol = self.connector.buildProtocol(self.getPeer())
  File "/home/adi/chevah/twisted/src/twisted/internet/base.py", line 1291, in buildProtocol
    return self.factory.buildProtocol(addr)
  File "/home/adi/chevah/twisted/src/twisted/internet/protocol.py", line 131, in buildProtocol
    assert self.protocol is not None
builtins.AssertionError: 

twisted.internet.test.test_tcp.TCP4ClientTestsBuilder_AsyncioSelectorReactorTests.test_clientConnectionFailedStopsReactor
-------------------------------------------------------------------------------
Ran 473 tests in 0.419s

FAILED (skips=87, errors=1, successes=385)
```

Sometimes the error is something like this ...no sure if it's related

```

[FAIL]
Traceback (most recent call last):
  File "/home/adi/chevah/twisted/src/twisted/internet/test/test_tcp.py", line 684, in test_addresses
    self.fail(clientFactory.failReason.getTraceback())
twisted.trial.unittest.FailTest: Traceback (most recent call last):
Failure: twisted.internet.error.ConnectBindError: Couldn't bind: 98: Address already in use.


twisted.internet.test.test_tcp.TCP4ClientTestsBuilder_AsyncioSelectorReactorTests.test_addresses
-------------------------------------------------------------------------------
Ran 473 tests in 0.381s
```

**Comment by glyph** [comment]
> twisted.internet.test.test_tcp.TCP4ClientTestsBuilder_AsyncioSelectorReactorTests.test_addresses

I am pretty sure this one is an OS limitation.

**Comment by glyph** [comment]
> twisted.internet.test.test_tcp.TCP4ClientTestsBuilder_AsyncioSelectorReactorTests.test_clientConnectionFailedStopsReactor

I suspect this one is yet another, different test flake :)

**Comment by glyph** [comment]
> It was running for more than 30.000 iteration, without a failure

I have instrumented it and I can get it to fail locally, reliably, in the same way: the server connection doesn't get notified of its connection dropping.

… 

And, oh, of course, this is a predictable failure mode, because the server does `stopReading` and never starts again, which means that various reactors will not be *able* to detect that it has lost its connection. I am surprised this doesn't happen more often.

**Comment by glyph** [comment]
This might just be a bug in asyncio.

There are definitely some potential race conditions in the Twisted code here too, but when I fixed them and instrumented `doRead` and looked at when it was being called, I can see that when a second call to `recv` would provoke `EWOULDBLOCK`, asyncio's main loop does not wake up again to notify that the socket is disconnected; despite the fact that the socket reader is still registered as a reader with the asyncio loop, the loop stays asleep.

**Comment by glyph** [comment]
Scratch that, not asyncio, I can reproduce it on the select reactor.

**Comment by glyph** [comment]
It happens much more frequently if I lose focus on the terminal window where the test is running which makes me wonder if the OS is implicated too

**Comment by glyph** [comment]
I think I'm going to stop debugging this for a while because this looks like a kernel bug where select (and kqueue, and CFRunLoop, and select and friends) will notify that a socket whose peer has closed has some work to do, recv() will give errno 35, and if you busy-loop polling the file descriptor, it will start giving errno 54 as expected after 5 seconds or so, but if you just select() on it it will not start appearing as readable at that transition.  Building a test case to illustrate that the sockets layer is broken in this way would be an annoying amount of work, because we'd really want an absolutely minimal test case that doesn't involve any Twisted code, just sockets.

**Comment by glyph** [comment]
sigh. another one https://github.com/twisted/twisted/actions/runs/13447543175/job/37576016373?pr=12432

**Comment by glyph** [comment]
And another one https://github.com/twisted/twisted/actions/runs/13554251314/job/37885040034?pr=12422

**Comment by glyph** [comment]
```
Error: 
Traceback (most recent call last):
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.13/site-packages/twisted/internet/test/test_tcp.py", line 2867, in test_fullWriteBuffer
    self.runAbortTest(StreamingProducerClient, NoReadServer)
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.13/site-packages/twisted/internet/test/test_tcp.py", line 2763, in runAbortTest
    reactor = runProtocolsWithReactor(self, server, client, self.endpoints)
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.13/site-packages/twisted/internet/test/connectionmixins.py", line 177, in runProtocolsWithReactor
    reactorBuilder.runReactor(reactor)
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.13/site-packages/twisted/internet/test/reactormixins.py", line 352, in runReactor
    raise TestTimeoutError(f"reactor still running after {timeout} seconds")
twisted.internet.test.reactormixins.TestTimeoutError: reactor still running after 120.0 seconds

twisted.internet.test.test_tcp.AbortConnectionTests_CFReactorTests.test_fullWriteBuffer
-------------------------------------------------------------------------------
Ran 11150 tests in 161.694s

FAILED (skips=647, errors=1, successes=10502)
ERROR: InvocationError for command /Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/bin/coverage run -p --rcfile=/Users/runner/work/twisted/twisted/.coveragerc -m twisted.trial --temp-directory=/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/tmp/_trial_temp --reporter=verbose -j 4 twisted (exited with code 1)
```

seems to be happening more regularly on python 3.13/macOS 14 ?

**Comment by glyph** [comment]
and again: https://github.com/twisted/twisted/actions/runs/13666667550/job/38209240261?pr=12433

**Comment by glyph** [comment]
```

Traceback (most recent call last):
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.13/site-packages/twisted/internet/test/test_tcp.py", line 2867, in test_fullWriteBuffer
    self.runAbortTest(StreamingProducerClient, NoReadServer)
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.13/site-packages/twisted/internet/test/test_tcp.py", line 2763, in runAbortTest
    reactor = runProtocolsWithReactor(self, server, client, self.endpoints)
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.13/site-packages/twisted/internet/test/connectionmixins.py", line 177, in runProtocolsWithReactor
    reactorBuilder.runReactor(reactor)
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.13/site-packages/twisted/internet/test/reactormixins.py", line 352, in runReactor
    raise TestTimeoutError(f"reactor still running after {timeout} seconds")
twisted.internet.test.reactormixins.TestTimeoutError: reactor still running after 120.0 seconds

twisted.internet.test.test_tcp.AbortConnectionTests_AsyncioSelectorReactorTests.test_fullWriteBuffer
-------------------------------------------------------------------------------
Ran 11150 tests in 161.016s
```

**Comment by glyph** [comment]
still happening https://github.com/twisted/twisted/actions/runs/20143803227/job/57818517982

```
Error: 
Traceback (most recent call last):
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.10/site-packages/twisted/internet/test/test_tcp.py", line 2930, in test_fullWriteBufferAfterByteExchange
    return self.runAbortTest(StreamingProducerClientLater, EventualNoReadServer)
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.10/site-packages/twisted/internet/test/test_tcp.py", line 2816, in runAbortTest
    reactor = runProtocolsWithReactor(self, server, client, self.endpoints)
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.10/site-packages/twisted/internet/test/connectionmixins.py", line 177, in runProtocolsWithReactor
    reactorBuilder.runReactor(reactor)
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.10/site-packages/twisted/internet/test/reactormixins.py", line 352, in runReactor
    raise TestTimeoutError(f"reactor still running after {timeout} seconds")
twisted.internet.test.reactormixins.TestTimeoutError: reactor still running after 120.0 seconds

twisted.internet.test.test_tcp.AbortConnectionTests_AsyncioSelectorReactorTests.test_fullWriteBufferAfterByteExchange
```

**Comment by glyph** [comment]
another one https://github.com/twisted/twisted/actions/runs/22838269432/job/66238961146?pr=12577

**Comment by glyph** [comment]
```
Error: 
Traceback (most recent call last):
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.10/site-packages/twisted/internet/test/test_tcp.py", line 2930, in test_fullWriteBufferAfterByteExchange
    return self.runAbortTest(StreamingProducerClientLater, EventualNoReadServer)
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.10/site-packages/twisted/internet/test/test_tcp.py", line 2816, in runAbortTest
    reactor = runProtocolsWithReactor(self, server, client, self.endpoints)
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.10/site-packages/twisted/internet/test/connectionmixins.py", line 177, in runProtocolsWithReactor
    reactorBuilder.runReactor(reactor)
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.10/site-packages/twisted/internet/test/reactormixins.py", line 352, in runReactor
    raise TestTimeoutError(f"reactor still running after {timeout} seconds")
twisted.internet.test.reactormixins.TestTimeoutError: reactor still running after 120.0 seconds

twisted.internet.test.test_tcp.AbortConnectionTests_AsyncioSelectorReactorTests.test_fullWriteBufferAfterByteExchange
-------------------------------------------------------------------------------
Ran 11191 tests in 195.748s

FAILED (skips=620, errors=1, successes=10570)
```

increasingly this is the *only* failing test on these flaky runs, so it may be worth just fully deleting it at this point

**Comment by glyph** [comment]
```
Traceback (most recent call last):
  File "/Users/runner/work/twisted/twisted/.tox/nodeps-withcov-posix/lib/python3.14/site-packages/twisted/internet/test/test_tcp.py", line 2920, in test_fullWriteBuffer
    self.runAbortTest(StreamingProducerClient, NoReadServer)
  File "/Users/runner/work/twisted/twisted/.tox/nodeps-withcov-posix/lib/python3.14/site-packages/twisted/internet/test/test_tcp.py", line 2816, in runAbortTest
    reactor = runProtocolsWithReactor(self, server, client, self.endpoints)
  File "/Users/runner/work/twisted/twisted/.tox/nodeps-withcov-posix/lib/python3.14/site-packages/twisted/internet/test/connectionmixins.py", line 177, in runProtocolsWithReactor
    reactorBuilder.runReactor(reactor)
  File "/Users/runner/work/twisted/twisted/.tox/nodeps-withcov-posix/lib/python3.14/site-packages/twisted/internet/test/reactormixins.py", line 352, in runReactor
    raise TestTimeoutError(f"reactor still running after {timeout} seconds")
twisted.internet.test.reactormixins.TestTimeoutError: reactor still running after 120.0 seconds

twisted.internet.test.test_tcp.AbortConnectionTests_SelectReactorTests.test_fullWriteBuffer
-------------------------------------------------------------------------------
Ran 9926 tests in 125.049s

FAILED (skips=1466, errors=1, successes=8459)
```
https://github.com/twisted/twisted/actions/runs/23629648080/job/68826046085?pr=12599

**Comment by adiroiban** [comment]
@glyph 

Do you think that this patch might help ?

I tried to read the code and I have no idea why `self.otherProtocol` is None... I can't find the place where it is set to none

My guess is that this fails, and then `ConnectableProtocol.connectionLost(self, reason)` is no longer call and then the reactor keeps waiting for the connection to be close and this is why we get a timeout.

I can try to apply this patch as a drive-by and see if this still fails.

-------



```diff
diff --git a/src/twisted/internet/test/test_tcp.py b/src/twisted/internet/test/test_tcp.py
index dd3d8b5ee5..d540b7d0bc 100644
--- a/src/twisted/internet/test/test_tcp.py
+++ b/src/twisted/internet/test/test_tcp.py
@@ -2821,7 +2821,8 @@ class StreamingProducerClient(ConnectableProtocol):
 
     def connectionLost(self, reason):
         # Tell server to start reading again so it knows to go away:
-        self.otherProtocol.transport.startReading()
+        if self.otherProtocol:
+            self.otherProtocol.transport.startReading()
```

I see that nixos is skipping this tests

**Comment by glyph** [comment]
> Do you think that this patch might help ?
> 
> I tried to read the code and I have no idea why `self.otherProtocol` is None... I can't find the place where it is set to none
> 
> My guess is that this fails, and then `ConnectableProtocol.connectionLost(self, reason)` is no longer call and then the reactor keeps waiting for the connection to be close and this is why we get a timeout.
> 
> I can try to apply this patch as a drive-by and see if this still fails.

My guess is that it's `self.otherProtocol.transport` that is `None` sometimes, which can happen *before* it's connected. Exactly when and how is still a mystery to me. But `otherProtocol` is just… never set to `None`, not as a default, not as a possible result of a `del`, nowhere.
