### ISSUE TITLE
Instantiating multiprocessing.SimpleQueue() from an imported package fails unless SimpleQueue() is instantiated inside Twisted application first

### ISSUE THREAD

**Issue by michelcrypt4d4mus** [twisted/twisted#12178]
## **Describe the incorrect behavior you saw**
[See discussion](https://github.com/Jorricks/macos-notifications/issues/23). Ran into a weird situation where I was importing a package `macos_notifications`. That package in turn instantiates a `multiprocessing.SimpleQueue` object - or at least it tries to. Just the simple instantiation call fails with a `bad value(s) in fds_to_keep` error...

...unless, I discovered, I instantiate a `SimpleQueue` object inside my Twisted application somewhere, anywhere. Then there's no error and things more or less work fine albeit with warnings about uncollected resources when the Twisted server exits:

```
resource_tracker: There appear to be 2 leaked semaphore objects to clean up at shutdown
```

## **Describe how to cause this behavior**
[See exact steps below](https://github.com/twisted/twisted/issues/12178#issuecomment-2119338599)

Inside of a `twisted.application` (specifically [opencanary](https://github.com/thinkst/opencanary)) running some twisted servers (both `internet.TCPServer` and `internet.UDPServer`, roughly 10 at the same time) do:
```python
    from mac_notifications import client

    client.create_notification(
        title="Meeting starts now!",
        subtitle="Team Standup",
        action_button_str="Join zoom meeting",
        action_callback=partial(join_zoom_meeting, conf_number=zoom_conf_number)
    )
```

I would presume the same error might arise from other packages that choose to instantiate a `SimpleQueue()` but `macos_notifications` is the only one I tested.

## Stack trace

```
2024-05-19T15:34:59-0400 [opencanary.modules.ssh.HoneyPotSSHFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/Users/uzor/workspace/opencanary/env/lib/python3.12/site-packages/twisted/python/log.py", line 80, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/Users/uzor/workspace/opencanary/env/lib/python3.12/site-packages/twisted/python/context.py", line 117, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/Users/uzor/workspace/opencanary/env/lib/python3.12/site-packages/twisted/python/context.py", line 82, in callWithContext
	    return func(*args, **kw)
	  File "/Users/uzor/workspace/opencanary/env/lib/python3.12/site-packages/twisted/internet/selectreactor.py", line 148, in _doReadOrWrite
	    why = getattr(selectable, method)()
	--- <exception caught here> ---
	  File "/Users/uzor/workspace/opencanary/env/lib/python3.12/site-packages/twisted/internet/tcp.py", line 1410, in doRead
	    protocol.makeConnection(transport)
	  File "/Users/uzor/workspace/opencanary/env/lib/python3.12/site-packages/twisted/internet/protocol.py", line 509, in makeConnection
	    self.connectionMade()
	  File "/Users/uzor/workspace/opencanary/env/lib/python3.12/site-packages/opencanary/modules/ssh.py", line 156, in connectionMade
	    log(logdata, transport=self.transport, logtype=logtype)
	  File "/Users/uzor/workspace/opencanary/env/lib/python3.12/site-packages/opencanary/modules/__init__.py", line 100, in log
	    client.create_notification(**notification_kwargs)
	  File "/Users/uzor/workspace/opencanary/env/lib/python3.12/site-packages/mac_notifications/client.py", line 66, in create_notification
	    return get_notification_manager().create_notification(notification_config)
	  File "/Users/uzor/workspace/opencanary/env/lib/python3.12/site-packages/mac_notifications/client.py", line 21, in get_notification_manager
	    return NotificationManager()
	  File "/Users/uzor/workspace/opencanary/env/lib/python3.12/site-packages/mac_notifications/singleton.py", line 17, in __call__
	    instance = super().__call__(*args, **kwargs)
	  File "/Users/uzor/workspace/opencanary/env/lib/python3.12/site-packages/mac_notifications/manager.py", line 51, in __init__
	    self._callback_queue: SimpleQueue = SimpleQueue()
	  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/context.py", line 113, in SimpleQueue
	    return SimpleQueue(ctx=self.get_context())
	  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/queues.py", line 363, in __init__
	    self._rlock = ctx.Lock()
	  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/context.py", line 68, in Lock
	    return Lock(ctx=self.get_context())
	  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/synchronize.py", line 169, in __init__
	    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
	  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/synchronize.py", line 80, in __init__
	    register(self._semlock.name, "semaphore")
	  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/resource_tracker.py", line 174, in register
	    self._send('REGISTER', name, rtype)
	  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/resource_tracker.py", line 182, in _send
	    self.ensure_running()
	  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/resource_tracker.py", line 148, in ensure_running
	    pid = util.spawnv_passfds(exe, args, fds_to_pass)
	  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/util.py", line 456, in spawnv_passfds
	    return _posixsubprocess.fork_exec(
	builtins.ValueError: bad value(s) in fds_to_keep
```

## **Describe the correct behavior you'd like to see**
I shouldn't need to instantiate `SimpleQueue()` to get `SimpleQueue()` to work in packages used by my twisted app.

## **Testing environment**
 - Operating System and Version; paste the output of these commands:
```
ProductName:		macOS
ProductVersion:		13.6.4
BuildVersion:		22G513
```
 - Twisted version: 24.3.0

`pip freeze`:
```
attrs==23.2.0
Automat==22.10.0
bcrypt==3.1.7
certifi==2024.2.2
cffi==1.16.0
charset-normalizer==3.3.2
constantly==23.10.4
cryptography==38.0.1
hpfeeds==3.0.0
hyperlink==21.0.0
idna==3.7
incremental==22.10.0
Jinja2==3.0.1
macos-notifications==0.2.0
markdown-it-py==3.0.0
MarkupSafe==2.1.5
mdurl==0.1.2
ntlmlib==0.72
ordereddict==1.1
passlib==1.7.1
pyasn1==0.4.5
pyasn1-modules==0.2.5
pycparser==2.22
Pygments==2.18.0
pyobjc-core==10.2
pyobjc-framework-Cocoa==10.2
pyOpenSSL==22.1.0
requests==2.31.0
rich==13.7.1
service-identity==21.1.0
setuptools==68.0.0
simplejson==3.19.2
six==1.16.0
Twisted==24.3.0
typing_extensions==4.11.0
urllib3==2.0.7
zope.interface==6.4
```
 - Reactor [e.g. select, iocp]

**Additional context**

**Comment by adiroiban** [comment]
Thanks for the report.

I don't see how this is related to twisted.

I don't see any twisted code in the traceback.

From what I can see, this is about [mac-notifications](https://github.com/Jorricks/macos-notifications/blob/main/pyproject.toml) and that project don't use Twisted.

Can you please share an [self-contained](http://www.sscce.org/) example that replicate this error

--------

Note that if you are using threads in your Twisted code, those thread should be handled only via [Twisted helper API](https://docs.twisted.org/en/stable/core/howto/threading.html). You should not mix Twited code and threading code without using the Twisted helping API. 

-------

I am closing this.
If you think this is a bug with twisted please add a complete example that can be used to reproduce this bug and then we can look into this,

Without being able to reproduce this error, it is very hard to fix this.

If you have a fix for this, please submit a pull request and I we can reopen this ticket.

Regards

**Comment by michelcrypt4d4mus** [comment]
As I said in the bug report all I did was call `macos_notifications` from [`opencanary`](https://github.com/thinkst/opencanary). OpenCanary is a twisted application; [here's the `.tac` file](https://github.com/thinkst/opencanary/blob/master/bin/opencanary.tac). the bug arises in instantiation just a few lines in when `SimpleQueue()` constructor is called. i don't have more of the stack trace at hand right now.

> _Note that if you are using threads in your Twisted code, those thread should be handled only via [Twisted helper API](https://docs.twisted.org/en/stable/core/howto/threading.html). You should not mix Twited code and threading code without using the Twisted helping API._

thanks, i suspect it is related to this, but the code never gets to the thread instantiation. it dies on literally [the first line of `__init__()` in one of the startup classes](https://github.com/Jorricks/macos-notifications/blob/main/src/mac_notifications/manager.py#L51).

**Comment by glyph** [comment]
I think there might be more to discuss here.

The fact that this is related to `fds_to_keep` suggests that Twisted is manipulating some global file descriptor state that it is fighting with Multiprocessing over, and we may have some work to do there.

I am not reopening right away because this *really* needs a clear reproducer to be actionable enough to be more than a vague "uhhh, maybe, global state, *handwave handwave* processes, file descriptors" magnet for anxiety or FUD :).

But if someone can do that so we can figure out what, if anything, we are having issues with, that would be great.

**Comment by michelcrypt4d4mus** [comment]
i think i can create a reproducible example relatively easily; i will try to do so.

**Comment by michelcrypt4d4mus** [comment]
> _The fact that this is related to fds_to_keep suggests that Twisted is manipulating some global file descriptor state that it is fighting with Multiprocessing over, and we may have some work to do there._

and fwiw that was my general impression as well.

**Comment by michelcrypt4d4mus** [comment]
ps i did find a [very old issue](https://github.com/twisted/klein/issues/288) over in the `klein` repo where someone seemed to have run into something similar - they were trying to use a package that did its own multiprocessing with a twistd server and getting `fds_to_keep` issues.

**Comment by michelcrypt4d4mus** [comment]
Easily reproducible on macOS:

1. Checkout my branch of `opencanary`: https://github.com/michelcrypt4d4mus/opencanary/tree/twistd_fds_to_keep_reproduce
2. run `build_scripts/build_opencanary.sh`
3. activate virtual env
4. run `twistd -noy bin/opencanary.tac`
5. `ssh localhost` from another window

**Comment by michelcrypt4d4mus** [comment]
Here's the full stack trace:
```
2024-05-19T15:34:59-0400 [opencanary.modules.ssh.HoneyPotSSHFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/Users/stardestroyer/workspace/opencanary/env/lib/python3.12/site-packages/twisted/python/log.py", line 80, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/Users/stardestroyer/workspace/opencanary/env/lib/python3.12/site-packages/twisted/python/context.py", line 117, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/Users/stardestroyer/workspace/opencanary/env/lib/python3.12/site-packages/twisted/python/context.py", line 82, in callWithContext
	    return func(*args, **kw)
	  File "/Users/stardestroyer/workspace/opencanary/env/lib/python3.12/site-packages/twisted/internet/selectreactor.py", line 148, in _doReadOrWrite
	    why = getattr(selectable, method)()
	--- <exception caught here> ---
	  File "/Users/stardestroyer/workspace/opencanary/env/lib/python3.12/site-packages/twisted/internet/tcp.py", line 1410, in doRead
	    protocol.makeConnection(transport)
	  File "/Users/stardestroyer/workspace/opencanary/env/lib/python3.12/site-packages/twisted/internet/protocol.py", line 509, in makeConnection
	    self.connectionMade()
	  File "/Users/stardestroyer/workspace/opencanary/env/lib/python3.12/site-packages/opencanary/modules/ssh.py", line 156, in connectionMade
	    log(logdata, transport=self.transport, logtype=logtype)
	  File "/Users/stardestroyer/workspace/opencanary/env/lib/python3.12/site-packages/opencanary/modules/__init__.py", line 100, in log
	    client.create_notification(**notification_kwargs)
	  File "/Users/stardestroyer/workspace/opencanary/env/lib/python3.12/site-packages/mac_notifications/client.py", line 66, in create_notification
	    return get_notification_manager().create_notification(notification_config)
	  File "/Users/stardestroyer/workspace/opencanary/env/lib/python3.12/site-packages/mac_notifications/client.py", line 21, in get_notification_manager
	    return NotificationManager()
	  File "/Users/stardestroyer/workspace/opencanary/env/lib/python3.12/site-packages/mac_notifications/singleton.py", line 17, in __call__
	    instance = super().__call__(*args, **kwargs)
	  File "/Users/stardestroyer/workspace/opencanary/env/lib/python3.12/site-packages/mac_notifications/manager.py", line 51, in __init__
	    self._callback_queue: SimpleQueue = SimpleQueue()
	  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/context.py", line 113, in SimpleQueue
	    return SimpleQueue(ctx=self.get_context())
	  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/queues.py", line 363, in __init__
	    self._rlock = ctx.Lock()
	  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/context.py", line 68, in Lock
	    return Lock(ctx=self.get_context())
	  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/synchronize.py", line 169, in __init__
	    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
	  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/synchronize.py", line 80, in __init__
	    register(self._semlock.name, "semaphore")
	  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/resource_tracker.py", line 174, in register
	    self._send('REGISTER', name, rtype)
	  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/resource_tracker.py", line 182, in _send
	    self.ensure_running()
	  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/resource_tracker.py", line 148, in ensure_running
	    pid = util.spawnv_passfds(exe, args, fds_to_pass)
	  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/util.py", line 456, in spawnv_passfds
	    return _posixsubprocess.fork_exec(
	builtins.ValueError: bad value(s) in fds_to_keep
```

**Comment by michelcrypt4d4mus** [comment]
I updated the issue description with the full stack trace instead of just the fragment i had put initially.

**Comment by adiroiban** [comment]
I am reopening this.

I don't have a macOS VM at hand to try to reproduce this... but I guess that there is enought information here to reproduce it.

It would be awesome to have this error reproduced via GitHub Actions

**Comment by galynazholtkevych** [comment]
This can be easily reproduced trying to spawn mutliprocessing Process with forkserver and Queue / Pipe. Snippet:

`
```
ctx = multiprocessing.get_context('forkserver')
r_queue = ctx.Queue()   <----- fails here

process = ctx.Process(target=_process_worker, args=(payload, r_queue))

process.start()
```


Going with ctx.Pipe it fails the same way at the `ctx.Process(....).start()`
`
Related traceback: 

`multiprocessing/context:104,multiprocessing/queues:44,multiprocessing/context:68,multiprocessing/synchronize:166,multiprocessing/synchronize:82,multiprocessing/resource_tracker:166,multiprocessing/resource_tracker:174,multiprocessing/resource_tracker:139,multiprocessing/util:460,multiprocessing/util:454 (ValueError)`

the thing that mutliptocessing with forkserver spawning a process get file descriptor from stderr:

`fds_to_pass.append(sys.stderr.fileno())`   ->
Twisted fileno returns -1 .

Then executing forkexec with invalid fds brings this trace. 

Reference: https://docs.python.org/3.14/library/multiprocessing.html#contexts-and-start-methods

 I fixed it internally raising io.UnsupportedOperation in fileno method instead of returning -1 bad file descriptor, but I am not sure this is a valid fix.

**Comment by galynazholtkevych** [comment]
@glyph is there enough information to reproduce? 
Also, I can make a pr a bit later, if you agree with the direction of the fix

**Comment by adiroiban** [comment]
I think that the main question here is why  `sys.stderr.fileno()` returns `-1`

with that, we should have a better idea of how to fix this issue.

In terms of Short, Self Contained, Correct (Compilable), Example to reproduce this error I was thinking to get something as simple as

create a file in `lib/python3.NN/site-packages/test_module.py`

```python
import multiprocessing
test_queue = multiprocessing.SimpleQueue()
ctx = multiprocessing.get_context('forkserver')
test_queue = ctx.Queue()
```

then in current working directory create `test.tac`

```python
import sys
from twisted.application import service
from test_module import test_queue
application = service.Application("Simple Example")
print(sys.stderr.fileno())
```

run it with `twistd -noy test.tac`

thanks

**Comment by glyph** [comment]
> I think that the main question here is why `sys.stderr.fileno()` returns `-1`

Yeah. When I try this example, I get `2` as one would expect. Something is calling `sys.stderr.close()` somewhere.  And I do mean they're calling it on that literal Python object, since if FD 2 got closed out from underneath it, it would still *have* a `.fileno()` result, until some method got called on it, which might make it realize that it's broken.

**Comment by galynazholtkevych** [comment]
@adiroiban  here is the reproduction steps. I guess, this maybe because of UnixApplicationRunner , that uses UnixAppLogger (child of AppLogger) 
Environment : Ubuntu 22 with python3.10 ( but it is reproduced for me on python3.13 on Debian Trixie as well). 

NOTE: Important reproduction detail  is that multiprocessing context should be 'forkserver' or 'spawn'.

My test_twisted.tac: 


```python
import sys
import multiprocessing
from twisted.application import service, app

from twisted.scripts._twistd_unix import UnixApplicationRunner, ServerOptions
from twisted.internet import reactor

def trigger():
  print(f"sys.stderr = {sys.stderr}")
  print(f"sys.stderr.fileno() = {sys.stderr.fileno()}")

  ctx = multiprocessing.get_context('forkserver')
  queue = ctx.SimpleQueue()
  reactor.stop()


reactor.callWhenRunning(trigger)

opts = ServerOptions()
opts.parseOptions(["--nodaemon", "web"])

apprunner = UnixApplicationRunner(opts)
apprunner.run()



``` 

Tracelog

```shell
twistd3  -ny test_twisted.tac
2026-07-08T11:06:20+0000 [-] Loading test_twisted.tac...
2026-07-08T11:06:20+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 25.5.0 (/usr/bin/python3 3.10.12) starting up.
2026-07-08T11:06:20+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.epollreactor.EPollReactor.
2026-07-08T11:06:20+0000 [-] Site starting on 8080
2026-07-08T11:06:20+0000 [twisted.web.server.Site#info] Starting factory <twisted.web.server.Site object at 0x7fcbfa4c6e00>
2026-07-08T11:06:20+0000 [stdout#info] sys.stderr = <twisted.logger._io.LoggingFile object at 0x7fcbfa4c7220>
2026-07-08T11:06:20+0000 [stdout#info] sys.stderr.fileno() = -1
2026-07-08T11:06:20+0000 [twisted.internet.base#critical] While calling system event trigger handler
	Traceback (most recent call last):
	  File "/usr/local/openvpn_as/lib/python/twisted/internet/base.py", line 518, in _continueFiring
	    callable(*args, **kwargs)
	  File "test_twisted.tac", line 13, in trigger
	    queue = ctx.SimpleQueue()
	  File "/usr/lib/python3.10/multiprocessing/context.py", line 113, in SimpleQueue
	    return SimpleQueue(ctx=self.get_context())
	  File "/usr/lib/python3.10/multiprocessing/queues.py", line 341, in __init__
	    self._rlock = ctx.Lock()
	  File "/usr/lib/python3.10/multiprocessing/context.py", line 68, in Lock
	    return Lock(ctx=self.get_context())
	  File "/usr/lib/python3.10/multiprocessing/synchronize.py", line 162, in __init__
	    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
	  File "/usr/lib/python3.10/multiprocessing/synchronize.py", line 80, in __init__
	    register(self._semlock.name, "semaphore")
	  File "/usr/lib/python3.10/multiprocessing/resource_tracker.py", line 156, in register
	    self._send('REGISTER', name, rtype)
	  File "/usr/lib/python3.10/multiprocessing/resource_tracker.py", line 163, in _send
	    self.ensure_running()
	  File "/usr/lib/python3.10/multiprocessing/resource_tracker.py", line 130, in ensure_running
	    pid = util.spawnv_passfds(exe, args, fds_to_pass)
	  File "/usr/lib/python3.10/multiprocessing/util.py", line 458, in spawnv_passfds
	    raise e
	  File "/usr/lib/python3.10/multiprocessing/util.py", line 453, in spawnv_passfds
	    return _posixsubprocess.fork_exec(
	builtins.ValueError: bad value(s) in fds_to_keep

```

**Comment by adiroiban** [comment]
Awesome work @galynazholtkevych 

I was able to reproduce this on Ubuntu 26.04 with Python 3.13

I can see that `sys.stderr` is now `twisted.logger._io.LoggingFile`  and LoggingFile implementation is

```python
    def fileno(self) -> int:
        """
        Returns an invalid file descriptor, since this is not backed by an FD.

        @return: C{-1}
        """
        return -1
```



this is of great help

**Comment by adiroiban** [comment]
in `multiprocessing/resource_tracker.py` I see this code

```python
    def _launch(self):
        fds_to_pass = []
        try:
            fds_to_pass.append(sys.stderr.fileno())
        except Exception:
            pass
        r, w = os.pipe()
```


so I guess that raising an exception is good enough.

Regarding the raised exception. [The documentation asks for OSError](https://docs.python.org/3/library/io.html#io.IOBase.fileno)

> **fileno()**
> Return the underlying file descriptor (an integer) of the stream if it exists. An [OSError](https://docs.python.org/3/library/exceptions.html#OSError) is raised if the IO object does not use a file descriptor.

--------

I guess that this should be considered a bug in `twisted.logger._io.LoggingFile.fileno()` and instead of returning -1 we should raise an OS error

**Comment by adiroiban** [comment]
It looks like this is a duplicate of #9638 . I am working to fix it

**Comment by adiroiban** [comment]
A pr with a fix for this is ready for review https://github.com/twisted/twisted/pull/12720
