### ISSUE TITLE
Several tests involving ipv6 in twisted.internet.test.test_tcp time out on Windows with no further information

### ISSUE THREAD

**Issue by machallboyd** [twisted/twisted#12206]
**Describe the incorrect behavior you saw**

In my Windows environment, several tests in the test suite involving ipv6 time out or produce cryptic errors.

**Describe how to cause this behavior**

I've been trying to get a clean test run on a fresh development environment, and am reporting issues along the way.

Invoked  `trial --rterrors twisted.internet.test.test_tcp` in a virtual environment that had been set up with `pip install -e '.[all_non_platform,windows_platform]'`

Some tracebacks: 
```
  TCP6ClientTestsBuilder_IOCPReactorTests
    test_addresses ... Traceback (most recent call last):
  File "C:\Users\macha\PycharmProjects\twisted\src\twisted\internet\test\test_tcp.py", line 684, in test_addresses
    self.fail(clientFactory.failReason.getTraceback())
twisted.trial.unittest.FailTest: Traceback (most recent call last):
Failure: twisted.internet.error.ConnectError: An error occurred while connecting: 121: ENOLINK.

[FAIL]
```
```
    test_serverAddressTCP6 ... Traceback (most recent call last):
  File "C:\Users\macha\PycharmProjects\twisted\src\twisted\internet\test\test_tcp.py", line 2288, in test_serverAddressTCP6
    return self._testServerAddress(
  File "C:\Users\macha\PycharmProjects\twisted\src\twisted\internet\test\test_tcp.py", line 2271, in _testServerAddress
    self.runReactor(reactor)
  File "C:\Users\macha\PycharmProjects\twisted\src\twisted\internet\test\reactormixins.py", line 351, in runReactor
    raise TestTimeoutError(f"reactor still running after {timeout} seconds")
twisted.internet.test.reactormixins.TestTimeoutError: reactor still running after 120.0 seconds
```
```
 test_serverGetHostOnIPv6ScopeID ... Traceback (most recent call last):
  File "C:\Users\macha\PycharmProjects\twisted\src\twisted\internet\test\test_tcp.py", line 1718, in test_serverGetHostOnIPv6ScopeID
    hostAddress = self._serverGetConnectionAddressTest(client, interface, "getHost")
  File "C:\Users\macha\PycharmProjects\twisted\src\twisted\internet\test\test_tcp.py", line 1678, in _serverGetConnectionAddressTest
    self.runReactor(reactor)
  File "C:\Users\macha\PycharmProjects\twisted\src\twisted\internet\test\reactormixins.py", line 351, in runReactor
    raise TestTimeoutError(f"reactor still running after {timeout} seconds")
twisted.internet.test.reactormixins.TestTimeoutError: reactor still running after 120.0 seconds
[ERROR]
```

In running through the latter traceback, @glyph noted:

> serverGetPeerOnIPv6ScopeID is specifically testing that it can listen on a link-local scope, then connect *back* to that address with the relevant scope ID specified, and Windows is, possibly understandably, saying "no, if you want to talk to localhost, you have to use an interface that allows that". It might even be routing traffic out to your actual network interface and then your switch has some opinions. (A "scope ID" if you haven't done much IPv6 junk is an identifier of a specific physical network.)
> 
> So this test is "wrong", and your network's setup is totally valid; it's just assuming that an fe80:: (i.e.: link-local-only) network exists, and that you have an address on it, and that it routes traffic. But "wrong" in quotes because there's no way to test the API surface that *uses* scope IDs actually works on a real-life operating system without making that sort of assumption
> 
> Still worth writing up a bug though, because it should not be timing out; it should be able to at least tell you what's going on

**Describe the correct behavior you'd like to see**
It would be helpful to have the test messages point to a way forward to configure a setup to run them successfully, rather than timing out.

**Testing environment**
 - Operating System and Version; 

```
> systeminfo | Findstr /i "OS"
Host Name:                 DESKTOP-2C3AUEJ
OS Name:                   Microsoft Windows 11 Home
OS Version:                10.0.22631 N/A Build 22631
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              American Megatrends International, LLC. F37, 12/26/2022
```

 - Twisted version 
  24.3.0.post0
  
  > pip freeze
alabaster==0.7.16
appdirs==1.4.4
astor==0.8.1
astroid==3.2.2
attrs==23.2.0
Automat==22.10.0
Babel==2.15.0
bcrypt==4.1.3
CacheControl==0.14.0
certifi==2024.6.2
cffi==1.16.0
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
ConfigArgParse==1.7
constantly==23.10.4
coverage==6.6.0b1
cryptography==42.0.8
cython-test-exception-raiser==1.0.2
dill==0.3.8
docutils==0.18.1
filelock==3.14.0
h2==4.1.0
hpack==4.0.0
hyperframe==6.0.1
hyperlink==21.0.0
hypothesis==6.103.1
idna==3.7
imagesize==1.4.1
incremental==22.10.0
iso8601==2.1.0
isort==5.13.2
Jinja2==3.1.4
lunr==0.6.2
MarkupSafe==2.1.5
mccabe==0.7.0
msgpack==1.0.8
packaging==24.0
platformdirs==4.2.2
priority==1.3.0
pyasn1==0.6.0
pyasn1_modules==0.4.0
pycparser==2.22
pydoctor==23.9.1
pyflakes==2.5.0
Pygments==2.18.0
PyHamcrest==2.1.0
pylint==3.2.3
pyOpenSSL==24.1.0
pyserial==3.5
python-subunit==1.4.4
pywin32==306
requests==2.32.3
service-identity==24.1.0
six==1.16.0
snowballstemmer==2.2.0
sortedcontainers==2.4.0
Sphinx==6.2.1
sphinx-rtd-theme==1.3.0
sphinxcontrib-applehelp==1.0.8
sphinxcontrib-devhelp==1.0.6
sphinxcontrib-htmlhelp==2.0.5
sphinxcontrib-jquery==4.1
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.7
sphinxcontrib-serializinghtml==1.1.10
testtools==2.7.1
toml==0.10.2
tomlkit==0.12.5
towncrier==23.11.0
-e git+https://github.com/machallboyd/twisted.git@41db66cf45a6fdcceaa0e6f2485d6ad6263b1ffb#egg=Twisted
twisted-iocpsupport==1.0.4
twistedchecker==0.7.4
typing_extensions==4.12.2
urllib3==1.26.18
zope.interface==6.4.post2

  
 - Reactor [e.g. select, iocp]

**Additional context**

Running `win32GetLinkLocalIPv6Addresses()` as `python -c 'from twisted.internet.test._win32ifaces import win32GetLinkLocalIPv6Addresses as A; print(A())'` produced:

`['fe80::d8ff:5060:f230:9168%6', 'fe80::ab19:a2ee:74f2:fb93%11', 'fe80::f1da:909e:d775:9be7%26']`

glyph noted that on windows the "single VMP physical interface" is an "extremely tightly-controlled virtualized" thing rather than actual switch gear, and would be much more sensitive to config issues than MacOS or Linux which seem to hand out scope IDs for everything.

**Comment by glyph** [comment]
> ... MacOS or Linux which seem to hand out scope IDs for everything

Specifically, the link-local address discovery mechanism that we use seems to give back addresses with embedded scope IDs already on `lo0` on those platforms.

On Windows, we don't get back an `lo0` address at all.  In fact the tools seem quite reluctant to show them to us.

After some digging, I found `netsh interface ipv6 show addresses level=verbose` which gave me this tidbit:

```
Address ::1 Parameters
---------------------------------------------------------
Interface Luid     : Loopback Pseudo-Interface 1
Scope Id           : 0.0
Valid Lifetime     : infinite
Preferred Lifetime : infinite
DAD State          : Preferred
Address Type       : Other
Skip as Source     : false

Address fe80::e65f:9fbd:d3aa:8c15%9 Parameters
---------------------------------------------------------
Interface Luid     : Bluetooth Network Connection
Scope Id           : 0.9
Valid Lifetime     : infinite
Preferred Lifetime : infinite
DAD State          : Deprecated
Address Type       : Other
Skip as Source     : false
```

Note that `fe80:...:8c15` embeds a scope ID of 9, and the tool outputs `Scope Id` of `0.9`; whereas `Loopback Pseudo-Interface 1` doesn't embed a scope ID at all, but *does* say `Scope Id` is `0.0`.  So, on a lark, I tried:

```
PS C:\Users\glyph> ping '::1'

Pinging ::1 with 32 bytes of data:
Reply from ::1: time<1ms
Reply from ::1: time<1ms
Reply from ::1: time<1ms
Reply from ::1: time=1ms

Ping statistics for ::1:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 1ms, Average = 0ms
PS C:\Users\glyph> ping '::1%1'

Pinging ::1%1 with 32 bytes of data:
PING: transmit failed. General failure.
PING: transmit failed. General failure.
PING: transmit failed. General failure.
PING: transmit failed. General failure.

Ping statistics for ::1%1:
    Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),
PS C:\Users\glyph> ping '::1%0'

Pinging ::1 with 32 bytes of data:
Reply from ::1: time<1ms
Reply from ::1: time<1ms
Reply from ::1: time<1ms
Reply from ::1: time<1ms

Ping statistics for ::1:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms
PS C:\Users\glyph>
```

So it looks like maybe `::1%0` is something we could hard-code on Windows? Just guessing here, but the docs for this are … not clear.

@machallboyd if you apply this patch does this test pass, or at least fail without timing out?

```
1 file changed, 1 insertion(+), 1 deletion(-)
src/twisted/internet/test/_win32ifaces.py | 2 +-

modified   src/twisted/internet/test/_win32ifaces.py
@@ -120,7 +120,7 @@ def win32GetLinkLocalIPv6Addresses():
     addressStringBufLength = 1024
     addressStringBuf = create_unicode_buffer(addressStringBufLength)
 
-    retList = []
+    retList = ["::1%0"]
     for i in range(addrList[0].iAddressCount):
         retBytes.value = addressStringBufLength
         address = addrList[0].Address[i]

```

**Comment by machallboyd** [comment]
Looks like `test_serverGetHostOnIPv6ScopeID` in particular does pass with this change, though I'm getting a few other failures elsewhere.

```
    test_serverAddressTCP6 ... Traceback (most recent call last):
  File "C:\Users\macha\PycharmProjects\twisted\src\twisted\internet\test\test_tcp.py", line 2253, in connected
    self.assertEqual(
  File "C:\Users\macha\PycharmProjects\twisted\src\twisted\trial\_synctest.py", line 444, in assertEqual
    super().assertEqual(first, second, msg)
  File "C:\Users\macha\AppData\Local\Programs\Python\Python311\Lib\unittest\case.py", line 873, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\macha\AppData\Local\Programs\Python\Python311\Lib\unittest\case.py", line 1253, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
twisted.trial.unittest.FailTest: 'AccumulatingProtocol,0,::1%0' != 'AccumulatingProtocol,0,::1'
- AccumulatingProtocol,0,::1%0
?                           --
+ AccumulatingProtocol,0,::1

[ERROR]
```

```
twisted.internet.test.test_tcp.TCPPortTestsBuilder_Win32ReactorTests.test_portGetHostOnIPv6ScopeID
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "C:\Users\macha\PycharmProjects\twisted\src\twisted\internet\test\test_tcp.py", line 2253, in connected
    self.assertEqual(
  File "C:\Users\macha\PycharmProjects\twisted\src\twisted\trial\_synctest.py", line 444, in assertEqual
    super().assertEqual(first, second, msg)
  File "C:\Users\macha\AppData\Local\Programs\Python\Python311\Lib\unittest\case.py", line 873, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\macha\AppData\Local\Programs\Python\Python311\Lib\unittest\case.py", line 1253, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
twisted.trial.unittest.FailTest: 'AccumulatingProtocol,63702,::1%0' != 'AccumulatingProtocol,63702,::1'
- AccumulatingProtocol,63702,::1%0
?                               --
+ AccumulatingProtocol,63702,::1
```

**Comment by adiroiban** [comment]
Thanks for trying this. I guess we also need to update the expectations in the tests.

I am looking into the CI part, to see why we don't see this test on our GitHub Action runners

Here is the result on Windows 

https://github.com/twisted/twisted/actions/runs/9426962968/job/25970518379#step:10:3085

also added a screenshot as the logs expire after 3 months


![image](https://github.com/twisted/twisted/assets/204609/b04d4884-bf4a-4f14-9c52-cc856b492559)

**Comment by glyph** [comment]
> Looks like `test_serverGetHostOnIPv6ScopeID` in particular does pass with this change, though I'm getting a few other failures elsewhere.

Both of the failures being shown here are that we listen with a scope ID, but then when incoming connections come in, Windows does not report them as having a scope ID. Which is… fine, and correct, since nothing says the platform needs to report optional scope IDs back to you. But obviously the strings don't match, and that's annoying.

I think we need to fix this in phases:

1. make a PR to get new developers un-stuck by adding a `.skip` condition that checks an environment variable named something something super obnoxious like `TWISTED_TESTS_VALIDATED_WINDOWS_IPV6_SCOPED_LINK`, then skips any tests that fail in your environment if it is not set.
2. file a new issue to write some code to remove this env var, either by programmatically validating the windows IPv6 stack and proceeding if it passes (i.e. enumerating the link and checking its routability by doing a raw listen/connect), or by rewriting some of this code to work by explicitly using `lo0%0`, ideally finding some kind of MSDN citation for it
