### ISSUE TITLE
[trial] builtins.RuntimeError: no running event loop with --reactor=asyncio

### ISSUE THREAD

**Issue by brennoflavio** [twisted/twisted#12265]
When mixing coroutines and deferreds in Twitsed trial, it fails with event loop not running. For example for the following file:

tests/trial/test_async_reactor.py
```
from twisted.trial.unittest import TestCase
from twisted.internet.defer import Deferred, inlineCallbacks
import asyncio

async def example(t: int):
    await asyncio.sleep(t)
    return t

class AsyncTestCase(TestCase):
    @inlineCallbacks
    def test_async(self):
        result = yield Deferred.fromCoroutine(example(1))
        self.assertTrue(result, 1)
```

And run
`trial --reactor=asyncio tests/trial/test_async_reactor.py`

You'll get an error like:
```
[ERROR]
Traceback (most recent call last):
  File "/home/brenno/github/crawler/tests/trial/test_async_reactor.py", line 12, in test_async
    result = yield Deferred.fromCoroutine(example(1))
  File "/home/brenno/.cache/pypoetry/virtualenvs/crawler-BWSR_5X1-py3.11/lib/python3.11/site-packages/twisted/internet/defer.py", line 2003, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "/home/brenno/github/crawler/tests/trial/test_async_reactor.py", line 6, in example
    await asyncio.sleep(t)
  File "/home/brenno/.pyenv/versions/3.11.8/lib/python3.11/asyncio/tasks.py", line 643, in sleep
    loop = events.get_running_loop()
builtins.RuntimeError: no running event loop

tests.trial.test_async_reactor.AsyncTestCase.test_async
```

This is just for trial, in actual application everything is fine.

**Comment by adiroiban** [comment]
Thanks for the report.

I am reproducing this error even with the epoll or select reactor

```python
    @inlineCallbacks
    def test_async(self):
        from twisted.internet import reactor
        print(reactor)
        result = yield Deferred.fromCoroutine(example(1))
        self.assertTrue(result, 1)
```


```
$ trial --reactor=select src/twisted/test/test_async_reactor.py

$ trial src/twisted/test/test_async_reactor.py
twisted.test.test_async_reactor
  AsyncTestCase
    test_async ... <twisted.internet.epollreactor.EPollReactor object at 0x7811684650d0>
                                                     [ERROR]

===============================================================================
[ERROR]
Traceback (most recent call last):
  File "src/twisted/test/test_async_reactor.py", line 14, in test_async
    result = yield Deferred.fromCoroutine(example(1))
  File "/home/adi/chevah/twisted/venv-3.12/lib/python3.12/site-packages/twisted/internet/defer.py", line 1999, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "src/twisted/test/test_async_reactor.py", line 6, in example
    await asyncio.sleep(t)
  File "/usr/lib/python3.12/asyncio/tasks.py", line 659, in sleep
    loop = events.get_running_loop()
builtins.RuntimeError: no running event loop

twisted.test.test_async_reactor.AsyncTestCase.test_async
-------------------------------------------------------------------------------
Ran 1 tests in 0.010s
```

**Comment by adiroiban** [comment]
I guess the issue here is that `trial` itself starts will not start the async loop

I am not sure that using non-twisted event loops is supported by `trial`.

this breakpoint is never reached.

```diff
diff --git a/src/twisted/internet/asyncioreactor.py b/src/twisted/internet/asyncioreactor.py
index cd1cf65f05..6d1fc885d2 100644
--- a/src/twisted/internet/asyncioreactor.py
+++ b/src/twisted/internet/asyncioreactor.py
@@ -249,6 +249,7 @@ class AsyncioSelectorReactor(PosixReactorBase):
         self._asyncioEventloop.run_forever()
 
     def run(self, installSignalHandlers=True):
+        import pdb; import sys; sys.stdout = sys.__stdout__; pdb.set_trace()
         self.startRunning(installSignalHandlers=installSignalHandlers)
         self._asyncioEventloop.run_forever()
         if self._justStopped:
```

**Comment by brennoflavio** [comment]
After exploring how Scrapy converts coroutines to Deferreds inside `scrapy.utils.defer.deferred_from_coro` I managed to get this example working by using fromFuture:

```python
from twisted.trial.unittest import TestCase
from twisted.internet.defer import Deferred, inlineCallbacks
import asyncio

async def example(t: int):
    await asyncio.sleep(t)
    return t

class AsyncTestCase(TestCase):
    @inlineCallbacks
    def test_async(self):
        loop = asyncio.get_event_loop()
        result = yield Deferred.fromFuture(asyncio.ensure_future(example(1), loop=loop))
        self.assertTrue(result, 1)
```

I also noticed that the `react` function has the same problem:

```python
from twisted.internet import asyncioreactor

asyncioreactor.install()

from twisted.internet.task import react
from twisted.internet.defer import Deferred, inlineCallbacks
import asyncio

async def example(t: int):
    await asyncio.sleep(t)
    return t

@inlineCallbacks
def main(reactor):
    yield Deferred.fromCoroutine(example(1))

react(main)
```

This code does not work with the same error than before. You need to wrap the coroutine into a future for it to properly work as I did with the first example

**Comment by congzhangzh** [comment]
Ref: https://docs.scrapy.org/en/2.11/topics/asyncio.html#install-asyncio
