### ISSUE TITLE
Methods in IMAP4Server class throws exception when copy fails or there is no mailbox

### ISSUE THREAD

**Issue by dooblaic** [twisted/twisted#12262]
**Describe the incorrect behavior you saw**

The sendNegativeResponse method requires all parameters to be in byte[] instead of string. It'll thow an exception like this:
```
     File ".venv/lib/python3.12/site-packages/twisted/mail/imap4.py", line 1101, in _respond
            self.sendLine(b" ".join((tag, state, message)))
        builtins.TypeError: sequence item 2: expected a bytes-like object, str found
```
This happens because of following code in `__cbCopied` method:
```
        if failures:
            self.sendNegativeResponse(tag, "[ALERT] Some messages were not copied")
        else:
            self.sendPositiveResponse(tag, b"COPY completed")
```
There are similar issue in few other places - mostly for uncommon error case. Found those with our internal unit testing.

**Describe how to cause this behavior**

What did you do to get it to happen?
Does it happen every time you follow these steps, sometimes, or only one time?

If copy of a message fails (for example INBOX to Trash) the exception is thown instead of returning a failure response.

```
        Traceback (most recent call last):
          File "/home/ubuntu/domail/.venv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1078, in _runCallbacks
            current.result = callback(  # type: ignore[misc]
          File "/home/ubuntu/domail/.venv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1561, in _cbDeferred
            self.callback(cast(_DeferredListResultListT[Any], self.resultList))
          File "/home/ubuntu/domail/.venv/lib/python3.12/site-packages/twisted/internet/defer.py", line 877, in callback
            self._startRunCallbacks(result)
          File "/home/ubuntu/domail/.venv/lib/python3.12/site-packages/twisted/internet/defer.py", line 984, in _startRunCallbacks
            self._runCallbacks()
        --- <exception caught here> ---
          File "/home/ubuntu/domail/.venv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1078, in _runCallbacks
            current.result = callback(  # type: ignore[misc]
          File "/home/ubuntu/domail/.venv/lib/python3.12/site-packages/twisted/mail/imap4.py", line 2373, in __cbCopied
            self.sendNegativeResponse(tag, "[ALERT] Some messages were not copied")
          File "/home/ubuntu/domail/.venv/lib/python3.12/site-packages/twisted/mail/imap4.py", line 1077, in sendNegativeResponse
            self._respond(b"NO", tag, message)
          File "/home/ubuntu/domail/.venv/lib/python3.12/site-packages/twisted/mail/imap4.py", line 1101, in _respond
            self.sendLine(b" ".join((tag, state, message)))
        builtins.TypeError: sequence item 2: expected a bytes-like object, str found
```

Preferable a [Short, Self Contained, Correct (Compilable), Example](http://www.sscce.org/) on a branch or on [a gist](https://gist.github.com).

Automated tests that are demonstrating the failure would be awesome.
We just need to convert the error strings to bytes in a few places. If this bug report is accepted we can fix an issue, create automated tests and submit a pull request.

**Describe the correct behavior you'd like to see**
The error response should be sent to client - instead an exception is being thrown from code.

**Testing environment**
 - Operating System and Version; paste the output of these commands:
      Linux ip-172-31-25-14 6.8.0-1010-aws #10-Ubuntu SMP Thu Jun 13 17:36:15 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
      DISTRIB_ID=Ubuntu
      DISTRIB_RELEASE=24.04
      DISTRIB_CODENAME=noble
      DISTRIB_DESCRIPTION="Ubuntu 24.04 LTS"

 - Twisted version: 24.3.0 (I see code in latest in github too)

**Comment by adiroiban** [comment]
Thanks for the report.
As far as I know, there is no active maintainer for the IMAP code in Twisted.

If you have time, please consider sending a PR with a fix

I would be happy to review and merge.

Thanks again
