### ISSUE TITLE
rpc example doesn't work anymore

### ISSUE THREAD

**Issue by siht** [twisted/twisted#12321]
**when i run example of rcp it thorws exception No module named 'email.policy'**
I installed the new version of twisted and examples that already works about rpc doesnt work anymore throwing an exception in server when i called an rpc method with client

**Describe how to cause this behavior**

I downgrade the twisted version to 23.10.0 and examples works again, in the new version doesn't work.

```
Traceback (most recent call last):
    File "/.../site-packages/twisted/python/log.py", line 96, in callWithLogger

    File "/.../site-packages/twisted/python/log.py", line 80, in callWithContext

    File "/.../site-packages/twisted/python/context.py", line 117, in callWithContext

    File "/.../site-packages/twisted/python/context.py", line 82, in callWithContext

  --- <exception caught here> ---
    File "/.../site-packages/twisted/internet/posixbase.py", line 481, in _doReadOrWrite

    File "/.../site-packages/twisted/internet/tcp.py", line 250, in doRead

    File "/.../site-packages/twisted/internet/tcp.py", line 255, in _dataReceived

    File "/.../site-packages/twisted/web/http.py", line 3267, in dataReceived

    File "/.../site-packages/twisted/web/http.py", line 2362, in dataReceived

    File "/.../site-packages/twisted/protocols/basic.py", line 555, in dataReceived

    File "/.../site-packages/twisted/web/http.py", line 2584, in rawDataReceived

    File "/.../site-packages/twisted/web/http.py", line 1866, in dataReceived

    File "/.../site-packages/twisted/web/http.py", line 2432, in _finishRequestBody

    File "/.../site-packages/twisted/web/http.py", line 2545, in allContentReceived

    File "/.../site-packages/twisted/web/http.py", line 1095, in requestReceived

    File "/.../site-packages/twisted/web/http.py", line 295, in _parseContentType

    File "/.../email/message.py", line 981, in __init__

  builtins.ModuleNotFoundError: No module named 'email.policy'

2024-09-22T16:47:50-0600 [_GenericHTTPChannelProtocol,1,127.0.0.1] Unhandled Error
  Traceback (most recent call last):
    File "/.../site-packages/twisted/python/log.py", line 96, in callWithLogger

    File "/.../site-packages/twisted/python/log.py", line 80, in callWithContext

    File "/.../site-packages/twisted/python/context.py", line 117, in callWithContext

    File "/.../site-packages/twisted/python/context.py", line 82, in callWithContext

  --- <exception caught here> ---
    File "/.../site-packages/twisted/internet/posixbase.py", line 481, in _doReadOrWrite

    File "/.../site-packages/twisted/internet/tcp.py", line 250, in doRead

    File "/.../site-packages/twisted/internet/tcp.py", line 255, in _dataReceived

    File "/.../site-packages/twisted/web/http.py", line 3267, in dataReceived

    File "/.../site-packages/twisted/web/http.py", line 2362, in dataReceived

    File "/.../site-packages/twisted/protocols/basic.py", line 555, in dataReceived

    File "/.../site-packages/twisted/web/http.py", line 2584, in rawDataReceived

    File "/.../site-packages/twisted/web/http.py", line 1866, in dataReceived

    File "/.../site-packages/twisted/web/http.py", line 2432, in _finishRequestBody

    File "/.../site-packages/twisted/web/http.py", line 2545, in allContentReceived

    File "/.../site-packages/twisted/web/http.py", line 1095, in requestReceived

    File "/.../site-packages/twisted/web/http.py", line 295, in _parseContentType

    File "/.../email/message.py", line 981, in __init__

  builtins.ModuleNotFoundError: No module named 'email.policy'
```

[https://gist.github.com](https://gist.github.com/siht/45b9d0fa931c4b48a8dab15e2cb534c6).

before the new version its returns a value when i called

**Testing environment**
- `
Linux WSNMXLP083 5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.5 LTS"
`
 - Twisted version 24.7.0
  - `asgiref==3.8.1
asttokens==2.4.1
attrs==24.2.0
Automat==24.8.1
cffi==1.17.0
constantly==23.10.4
cryptography==43.0.1
decorator==5.1.1
Django==5.1.1
executing==2.1.0
h2==4.1.0
hpack==4.0.0
hyperframe==6.0.1
hyperlink==21.0.0
idna==3.8
incremental==24.7.2
ipdb==0.13.13
ipython==8.27.0
jedi==0.19.1
MarkupSafe==2.1.5
matplotlib-inline==0.1.7
parso==0.8.4
pexpect==4.9.0
priority==1.3.0
prompt_toolkit==3.0.47
ptyprocess==0.7.0
pure_eval==0.2.3
pyasn1==0.6.0
pyasn1_modules==0.4.0
pycparser==2.22
Pygments==2.18.0
pyOpenSSL==24.2.1
service-identity==24.1.0
setuptools==72.1.0
six==1.16.0
sqlparse==0.5.1
stack-data==0.6.3
traitlets==5.14.3
Twisted==24.7.0
typing_extensions==4.12.2
wcwidth==0.2.13
Werkzeug==3.0.4
wheel==0.43.0
zope.interface==7.0.3`
 - Reactor default

**Comment by gudnimg** [comment]
Have you checked if `/.../email/policy.py` is actually installed on your system? Likely located in `/usr/lib/python3.12/email/policy.py` or similar path. I don’t see how this is a bug in Twisted as the problem is specific to Python’s standard library. 🤔

**Comment by siht** [comment]
i review as you writes and you're right. There is something rare in how i installed all.
there's no bug.
thank you

**Comment by adiroiban** [comment]
Thanks @gudnimg for looking into this and thanks @siht  for the followup. 
I will close this for now, as "not a bug"

**Comment by cjwatson** [comment]
This seems like you're trying to use Python 2 (probably by mistake).  Ubuntu 22.04 was the last Ubuntu LTS release to include Python 2; for compatibility reasons it was `/usr/bin/python`, so if you just used `python` without thinking about it then you'd get Python 2.  Current versions of Twisted only work with Python 3, so use `python3` instead.

**Comment by siht** [comment]
@cjwatson i think its a path issue with miniconda when i run as admin, but if i run as a non privileged user it runs perfect. Thank you
