### ISSUE TITLE
TLS client endpoint parser mishandles bindAddress 

### ISSUE THREAD

**Issue by warner** [twisted/twisted#12325]
**Describe the incorrect behavior you saw**

Creating a TLS client endpoint from a string, and including a `bindAddress=ADDR` value (e.g. `tls:github.com:443:bindAddress=1.2.3.4` will cause a crash during connection.

The `twisted.internet.endpoints._parseClientTLS` function passes the `ADDR` into the `HostnameEndpoint()` constructor as a *string*, whereas the function is expecting a tuple of `(ADDR, PORT)`. This doesn't trigger an error during Endpoint construction, however actually trying to connect with the endpoint (`ep.connect(factory)`) gets an error as it attempts to dereference the first element of the tuple and examine it as a hostname.

The following test program ought to connect to Github's TLS endpoint and say hello (note that `bindAddress=`, without a hostname, is a legitimate way to bind to the "ANY" interface, and avoids the need to e.g. call `ifconfig` to figure out a suitable host for binding first.. `bindAddress=0.0.0.0` should work the same way).

```python
from twisted.internet import endpoints, task, protocol, defer

class P(protocol.Protocol):
    def connectionMade(self):
        print("connectionMade")
        self.transport.write(b"GET / HTTP/1.0\n\n")
        self.transport.loseConnection()
    def connectionLost(self, reason):
        self.factory.d.callback("done")
    def dataReceived(self, data):
        print("dataReceived", data)

@defer.inlineCallbacks
def go(reactor):
    #ep = endpoints.clientFromString(reactor, 'tcp:github.com:443:bindAddress=')
    #print(ep._bindAddress)
    ep = endpoints.clientFromString(reactor, 'tls:github.com:443:bindAddress=')
    #print(ep._wrappedEndpoint._bindAddress)
    client_f = protocol.Factory.forProtocol(P)
    client_f.d = defer.Deferred()
    c = yield ep.connect(client_f)
    yield client_f.d
task.react(go)
```

yields the following error:

```
% python3 t.py
main function encountered error
Traceback (most recent call last):
  File "/Users/warner/stuff/python/twisted/src/twisted/internet/defer.py", line 2013, in _inlineCallbacks
    result = context.run(
  File "/Users/warner/stuff/python/twisted/src/twisted/python/failure.py", line 467, in throwExceptionIntoGenerator
    return g.throw(self.value.with_traceback(self.tb))
  File "/Users/warner/stuff/python/twisted/t.py", line 21, in go
    c = yield ep.connect(client_f)
  File "/Users/warner/stuff/python/twisted/src/twisted/internet/endpoints.py", line 600, in connect
    self._reactor.connectTCP(
  File "/Users/warner/stuff/python/twisted/src/twisted/internet/posixbase.py", line 368, in connectTCP
    c.connect()
  File "/Users/warner/stuff/python/twisted/src/twisted/internet/base.py", line 1266, in connect
    self.transport: Optional[Client] = self._makeTransport()
  File "/Users/warner/stuff/python/twisted/src/twisted/internet/tcp.py", line 1529, in _makeTransport
    return Client(self.host, self.port, self.bindAddress, self, self.reactor)
  File "/Users/warner/stuff/python/twisted/src/twisted/internet/tcp.py", line 730, in __init__
    if abstract.isIPv6Address(bindAddress[0]):
builtins.IndexError: string index out of range
```

The `bindAddress[0]` is attempting to extract the host portion of the `(host, port)` tuple, but in this case `bindAddress` is an empty string, so `bindAddress[0]` is an attempt to extract its zeroth character, which fails with IndexError.

If we change the program to use `bindAddress=0.0.0.0`, we get:

```
  File "/Users/warner/stuff/python/twisted/src/twisted/internet/tcp.py", line 1529, in _makeTransport
    return Client(self.host, self.port, self.bindAddress, self, self.reactor)
  File "/Users/warner/stuff/python/twisted/src/twisted/internet/tcp.py", line 734, in __init__
    skt.bind(bindinfo)
builtins.TypeError: bind(): AF_INET address must be tuple, not str
```

because `bindinfo` is a copy of `bindAddress`, and `socket.bind()` expects a tuple.

Changing the program to use the `tcp:` endpoint instead of the `tls:` one yields success:

```
% python3 t.py
connectionMade
```

The problem lies in `_parseClientTLS`. The `bindAddress` is extracted as a string:

https://github.com/twisted/twisted/blob/05cc97afa3c9c00386e5cd0c50e0807e9ef963d4/src/twisted/internet/endpoints.py#L2287-L2291

but then passed into `HostnameEndpoint()` as is:

https://github.com/twisted/twisted/blob/05cc97afa3c9c00386e5cd0c50e0807e9ef963d4/src/twisted/internet/endpoints.py#L2300-L2302

whereas for e.g. `_parseClientTCP`, it converts the string into a `(string, 0)` tuple:

https://github.com/twisted/twisted/blob/05cc97afa3c9c00386e5cd0c50e0807e9ef963d4/src/twisted/internet/endpoints.py#L1880

It looks like the types are not consistent:
* `_parseClientTLS` passes a string `bindAddress` into `HostnameEndpoint`
* [`HostnameEndpoint` is documented](https://github.com/twisted/twisted/blob/05cc97afa3c9c00386e5cd0c50e0807e9ef963d4/src/twisted/internet/endpoints.py#L811-L813) to take a bytestring as `bindAddress`, and after DNS resolution, passes it unmodified into [`TCP6ClientEndpoint`](https://github.com/twisted/twisted/blob/05cc97afa3c9c00386e5cd0c50e0807e9ef963d4/src/twisted/internet/endpoints.py#L975-L980) or [`TCP4ClientEndpoint`](https://github.com/twisted/twisted/blob/05cc97afa3c9c00386e5cd0c50e0807e9ef963d4/src/twisted/internet/endpoints.py#L982-L988)
* [`TCP4ClientEndpoint` is documented](https://github.com/twisted/twisted/blob/05cc97afa3c9c00386e5cd0c50e0807e9ef963d4/src/twisted/internet/endpoints.py#L584-L586) to take `bindAddress` as a *tuple*, as is TCP6ClientEndpoint

I think stronger typechecking might have caught the inconsistency.

`test_endpoints.py` is meant to test this code. However it asserts that the parsed `hostnameEndpoint._bindAddress` is a string, when it should be asserting a tuple.

https://github.com/twisted/twisted/blob/05cc97afa3c9c00386e5cd0c50e0807e9ef963d4/src/twisted/internet/test/test_endpoints.py#L4199

I couldn't find a test that uses `endpointFromtString("tls:...:bindAddress=ADDR")` and then actually tries an `ep.connect()` on it, possibly because generating a suitable TLS server cert is too much of a hassle, and also because it's not obvious that you can use `bindAddress=` or `bindAddress=0.0.0.0` to avoid also needing to probe for a safe address to bind to. The `test_tls` case uses `endpoint.connect()`, but I think with mocked out values which means it doesn't make it all the way to `_BaseTCPClient` and the call to `skt.bind()`, where the error would arise.

My recommended fix is:
* add an `assert(isinstance(bindaddress, (tuple, type(None))))` to _BaseTCPClient.__init__`, `TCP4ClientEndpoint`, and `TCP6ClientEndpoint`
* change the specification of `HostnameEndpoint` to expect a `tuple` for the `bindAddress`
* change `_parseClientTLS()` to call `HostnameEndpoint()` with `(bindAddress, 0)` instead of `bindAddress`
* update test_endpoints.py to check tuple-ness of parsed bindAddress

I'd really like to incorporate a proper `ep.connect()` test, but I didn't see an obvious way to do so.. maybe someone more familiar with the code can come up with a good approach.

I'll attach a PR with the fix and an update to the unit tests.

**Testing environment**

MacOS and Linux. Twisted 24.7.0 and current trunk. Default reactor.

**Comment by warner** [comment]
Oops, that PR broke a lot of tests. Clearly there's more code depending upon `bindAddress` than I realized. Here's what I learned:


## Investigation

Comprehensive enumeration of interfaces/implementations handling of `bindAddress` in current trunk:

`endpoints.py`:

* `clientFromString`: docstring says bindAddress field should be IPv4 address string, and that ports are not supported, passes strings to `_parseClientTCP` and `_parseClientSSL`
* `_parseClientTCP`: docstring says "Valid keyword arguments to this function are all IReactorTCP.connectTCP arguments". Code converts any `bindAddress=` into a tuple of (bindAddress, 0)
* `_parseClientTLS`: docstring says bindAddress is bytes-or-unicode, code requires the same, passes to HostnameEndpoint
* `HostnameEndpoint`: docstring says `bindAddress` is bytes, passes to `TCP{4,6}ClientEndpoint`
* `TCP4ClientEndpoint`: `bindAddress` docstring says tuple-or-None, passes to reactor.connectTCP
* `TCP6ClientEndpoint`: passes to reactor.connectTCP
* `SSL4ClientEndpoint`: docstring says tuple-or-None, passes to reactor.connectSSL
* tests: MemoryReactor tests generally expect bindAddress to be a tuple-or-None
  * `SSLClientStringTests.test_ssl` asserts that `clientFromString("ssl:.."` produces `SSL4ClientEndpoint` with a tuple
  * but `WrapClientTLSParserTests.test_hostnameEndpointConstruction` asserts that `clientFromString("tls:.."` produces an endpoint which wraps a HostnameEndpoint whose `.bindAddress` is a nativeString

other `twisted.internet.*`:

* `IReactorTCP`: the `connectTCP()` types and docstring say `bindAddress` is a tuple or None
* `ClientCreator.connectTCP`: forwards to `reactor.connectTCP`
* `_BaseTCPClient.__init__`: needs `bindAddress` to be a tuple of (addr, port) or None
* `tcp.Connector`: _makeTransport forwards to `Client`, subclass of `_BaseTCPClient`
* `PosixReactorBase.connectTCP`: forwards to `tcp.Connector`
* `IOCPReactor.connectTCP`: forwards to `tcp.Connector`
* `MemoryReactor` (used for tests): records `bindAddress` in self.tcpClients unmodified

`twisted.web`:

* `client.Agent`: docstring says bindAddress is bytes or None, passes to `_StandardEndpointFactory`
* `client._StandardEndpointFactory`: class docstring says `self._bindAddress` is passed to `HostnameEndpoint`, `__init__` docstring says bindAddress is bytes or None. `.endpointForURI()` implementation passes `self._bindAddress` to HostnameEndpoint
* tests use `MemoryReactor` and inspect `self.reactor.tcpClients` to make assertions about arguments
* tests that use `bindAddress` are looking for a string, not a tuple

`twisted.conch`: MemoryReactor tests retrieve `bindAddress` but do not inspect it

I don't see any other calls to HostnameEndpoint in the tree that can provide `bindAddress` (conch/ssh/forwarding.py uses one but doesn't let you control that argument).

## Conclusions

So I think `connectTCP` is pretty clearly defined to expect a tuple-or-None. And MemoryReactor just records the arguments passed into `connectTCP`, which means tests that use MemoryReactor should expect `tcpClients` to contain tuples.

Endpoints need to accept a tuple so you can control the port as well as the address. Endpoint *descriptors* (the strings passed to `clientFromString`) don't have the syntax to accepts ports. So the dividing line between "bindAddress is a string" and "bindAddress is a tuple" should be in `clientFromString`.

I think that means `HostnameEndpoint` really wants to accept a tuple-or-None. But `HostnameEndpoint` is a super-public interface, and it would probably break user code to reject bytes.

twisted.web says it expects bytes-or-None and passes it to HostnameEndpoint. I'm on the fence as to whether it would useful to accept tuples as well: the target IP+port of an HTTP connection is pretty static, so if you bind the local port, you probably can't make more than one HTTP request without causing trouble (the kind that TIME_WAIT is meant to protect you from). So if we leave `client.Agent` alone, we need to change the `twisted.web` tests that look for `bindAddress` via `MemoryReactor` to expect to see tuples.

So, to be consistent, I think that results in the following changes:

* `HostnameEndpoint`: change to accept tuple-or-bytes-or-None, convert to tuple during `__init__`
* `_parseClientTLS`: change to wrap strings in tuples
* `twisted.web.test`: change to expect `self.reactor.tcpClients` to hold tuples, not strings


That's expanding one public API (`HostnameEndpoint()`), and changing its internals to record a different type (`HostnameEndpoint._bindAddress` holds tuple-or-None instead of bytes-or-None).

Also, now that I think about it, I'm not confident about the bytes-vs-str in these interfaces.. the docstrings mostly talk about `bytes`, but `WrapClientTLSParserTests.test_hostnameEndpointConstruction` does:

```python
    self.assertEqual(hostnameEndpoint._bindAddress, nativeString("127.0.0.1"))
```

which looks like it's expecting `hostnameEndpoint._bindAddress` to be a `str`, not `bytes`. That's the internal format, though, so it doesn't need to correspond to the API definition. This test would change to expect a tuple, but I don't know whether I should retain the `nativeString()` wrapper or not (we're py3-only these days, right?)
