### ISSUE TITLE
builtins.OSError when using HTTP server over unix sockets since Twisted 24.10.0

### ISSUE THREAD

**Issue by p12tic** [twisted/twisted#12365]
Since 24.10.0 it is not possible to use HTTP server over `unix:` protocol. 

This bug has been initially reported in https://github.com/buildbot/buildbot/issues/8207.

Relevant log:
```
2024-11-12 05:54:43+0000 [buildbot.www.service.BuildbotSite] Unhandled Error
        Traceback (most recent call last):
          File "/home/buildbot/venv/lib64/python3.13/site-packages/twisted/internet/tcp.py", line 1423, in doRead
            protocol.makeConnection(transport)
          File "/home/buildbot/venv/lib64/python3.13/site-packages/twisted/internet/protocol.py", line 509, in makeConnection
            self.connectionMade()
          File "/home/buildbot/venv/lib64/python3.13/site-packages/twisted/web/http.py", line 2336, in connectionMade
            self.transport.setTcpNoDelay(True)
          File "/home/buildbot/venv/lib64/python3.13/site-packages/twisted/internet/tcp.py", line 340, in setTcpNoDelay
            self.socket.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, enabled)
        builtins.OSError: [Errno 95] Operation not supported
```

Relevant Twisted configuration:
```
    port='unix:/run/buildbot/buildbot-loop-master.sock:mode=660',
```

Most likely https://github.com/twisted/twisted/pull/12312 is the cause of the regression because it introduces `setTcpNoDelay` to HTTP client. Unfortunately `setTcpNoDelay` is available on all stream sockets, which includes unix domain sockets. Setting TCP NODELAY option on them fails with error.

**Comment by adiroiban** [comment]
Many thanks for the report.

SO... we have the [ITCPTransport](https://docs.twisted.org/en/latest/api/twisted.internet.interfaces.ITCPTransport.html) interface that defined the setTcpNoDelay


We have [IUNIXTransport](https://docs.twisted.org/en/latest/api/twisted.internet.interfaces.IUNIXTransport.html) which is the interface for our Unix socket transport

I guess that in the HTTP code we need to call `self.transport.setTcpNoDelay(True)` only if the transport implements the `ITCPTransport` interface
