### ISSUE TITLE
reactor.listenTCP invalid argument

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#1744]
|[<img alt="ghazel's avatar" src="https://avatars.githubusercontent.com/u/31402?s=50" width="50" height="50">](https://github.com/ghazel)| @ghazel reported|
|-|-|
|Trac ID|trac#1744|
|Type|defect|
|Created|2006-05-24 06:46:56Z|

Windows XP

```
Traceback (most recent call last):
  ...
  File "twisted\internet\iocpreactor\proactor.pyo", line 68, in listenTCP
  File "twisted\internet\iocpreactor\util.pyo", line 17, in helpful
  File "twisted\internet\iocpreactor\server.pyo", line 64, in handle_disconnected_startListening
  File "<string>", line 1, in listen
error: (10022, 'Invalid argument')
```

the arguments were probably:
```
reactor.listenTCP(1029, factory, interface='')
```

<details><summary>Searchable metadata</summary>

```
trac-id__1744 1744
type__defect defect
reporter__ghazel ghazel
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__worksforme worksforme
component__core core
keywords__ 
time__1148453216000000 1148453216000000
changetime__1329685090000000 1329685090000000
version__ 
owner__ghazel ghazel
cc__thijs
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="ghazel's avatar" src="https://avatars.githubusercontent.com/u/31402?s=50" width="50" height="50">](https://github.com/ghazel)|@ghazel commented|
|-|-|

I saw this happen again with a totally different port: 10026 (that's the port number, not the error number).

**Comment by twisted-trac** [comment]
|[<img alt="ghazel's avatar" src="https://avatars.githubusercontent.com/u/31402?s=50" width="50" height="50">](https://github.com/ghazel)|@ghazel commented|
|-|-|

Here's selectreactor doing the same thing (same box exhibits error regardless of which reactor I use):

```
Traceback (most recent call last):
  ...
  File "twisted\internet\reactor.pyo", line 12, in ?
  File "twisted\internet\selectreactor.pyo", line 231, in install
  File "twisted\internet\posixbase.pyo", line 168, in __init__
  File "twisted\internet\base.pyo", line 268, in __init__
  File "twisted\internet\base.pyo", line 575, in _initThreads
  File "twisted\internet\posixbase.pyo", line 265, in installWaker
  File "twisted\internet\posixbase.pyo", line 77, in __init__
  File "<string>", line 1, in listen
socket.error: (10022, 'Invalid argument')
```

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)|@glyph set owner to @ghazel|
|-|-|

This doesn't happen for me, obviously.  I suspect it's a deliberate misconfiguration on the box in question.  For example, does it have any "firewall" software active?

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_4"></a>|@thijstriemstra commented|
|-|-|

With no responses to the previous comment in the last 3 years this can probably be closed i'd say.

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_5"></a>|@thijstriemstra set status to `closed`|
|-|-|

Replying to [thijs](#note_4):
> With no responses to the previous comment in the last 3 years this can probably be closed i'd say.

2 years later im closing this as worksforme.
