### ISSUE TITLE
iocpreactor 'Connector' object has no attribute 'sub'

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#1762]
|[<img alt="ghazel's avatar" src="https://avatars.githubusercontent.com/u/31402?s=50" width="50" height="50">](https://github.com/ghazel)| @ghazel reported|
|-|-|
|Trac ID|trac#1762|
|Type|defect|
|Created|2006-05-30 07:50:37Z|

```
Traceback (most recent call last):
  ...
  File "C:\Python24\lib\site-packages\twisted\internet\iocpreactor\proactor.py",
 line 34, in run
    self.mainLoop()
  File "C:\Python24\lib\site-packages\twisted\internet\iocpreactor\proactor.py",
 line 42, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "C:\Python24\lib\site-packages\twisted\internet\base.py", line 562, in ru
nUntilCurrent
    call.func(*call.args, **call.kw)
  File "C:\Python24\Lib\hotshot\__init__.py", line 76, in runcall
    return self._prof.runcall(func, args, kw)
  File "C:\Python24\lib\site-packages\twisted\internet\iocpreactor\client.py", l
ine 140, in connectionFailed
    if self.sub.socket:
exceptions.AttributeError: 'Connector' object has no attribute 'sub'
```

<details><summary>Searchable metadata</summary>

```
trac-id__1762 1762
type__defect defect
reporter__ghazel ghazel
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__invalid invalid
component__core core
keywords__ 
time__1148975437000000 1148975437000000
changetime__1148976315000000 1148976315000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="ghazel's avatar" src="https://avatars.githubusercontent.com/u/31402?s=50" width="50" height="50">](https://github.com/ghazel)|@ghazel commented|
|-|-|

I built a mechanism to capture the stack when .sub was first deleted, then print it before the exception occurs.
```
    reactor.run()
  File "C:\Python24\lib\site-packages\twisted\internet\iocpreactor\proactor.py",
 line 34, in run
    self.mainLoop()
  File "C:\Python24\lib\site-packages\twisted\internet\iocpreactor\proactor.py",
 line 45, in mainLoop
    self.doIteration(t)
  File "C:\Python24\lib\site-packages\twisted\python\log.py", line 53, in callWi
thLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "C:\Python24\lib\site-packages\twisted\python\log.py", line 38, in callWi
thContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "C:\Python24\lib\site-packages\twisted\python\context.py", line 59, in ca
llWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "C:\Python24\lib\site-packages\twisted\python\context.py", line 37, in ca
llWithContext
    return func(*args,**kw)
  File "C:\Python24\lib\site-packages\twisted\internet\iocpreactor\ops.py", line
 134, in ovDone
    self.transport.connectDone()
  File "C:\Python24\lib\site-packages\twisted\internet\iocpreactor\client.py", l
ine 66, in connectDone
    self.sf.connectionSuccess()
  File "C:\Python24\lib\site-packages\twisted\internet\iocpreactor\client.py", l
ine 168, in connectionSuccess
    self.stack = traceback.format_stack()
```

**Comment by twisted-trac** [comment]
|[<img alt="ghazel's avatar" src="https://avatars.githubusercontent.com/u/31402?s=50" width="50" height="50">](https://github.com/ghazel)|@ghazel set status to `closed`|
|-|-|

Looks like this was caused by my profiler wrapping callLater and not returning a value.

client.py:153
if self.timeoutID:

in cancelTimeout was causing the timeout to not be cancelled, and no error message to be thrown.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
