### ISSUE TITLE
Remove TestCase._wait from Trial

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#1781]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)| @jml reported|
|-|-|
|Trac ID|trac#1781|
|Type|enhancement|
|Created|2006-06-03 01:25:11Z|

Trial starts and stops the reactor. This is not good.  It should just set up a bunch of deferreds and run the reactor once, stopping only when complete.

<details><summary>Searchable metadata</summary>

```
trac-id__1781 1781
type__enhancement enhancement
reporter__jml jml
priority__high high
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__wontfix wontfix
component__trial trial
keywords__ 
time__1149297911000000 1149297911000000
changetime__1195061421000000 1195061421000000
version__None None
owner__ 
cc__spiv cc__exarkun
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)|@jml set status to `assigned`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)|@jml commented|
|-|-|

So, here's where I'm at
 1. This branch can't be merged til [#1883](https://github.com/twisted/twisted/issues/1883) gets merged.
 1. Everything is being run inside _exactly one_ _wait call
 1. A whole stack of Trial's tests need to be changed so we aren't re-entering the reactor

Once 3 gets done, I'll ditch wait and run everything inside a reactor.run / reactor.stop pair.

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)|@jml commented|
|-|-|

2 and 3 are done.

I've changed my mind about 1.


spiv, I'd appreciate it if you could cast your eye over the branch ([branches/deferred-1781-2)](branches/deferred-1781-2))

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)|@jml commented|
|-|-|

Running on full-2.4-debian64 gave the following errors:

```
===============================================================================
[ERROR]: twisted.mail.test.test_pop3.AnotherPOP3TestCase.testAuthListing

Traceback (most recent call last):
  File "/home/buildslave/slaves/twisted/full2.4-debian64/Twisted/twisted/internet/base.py", line 532, in runUntilCurrent
    f(*a, **kw)
  File "/home/buildslave/slaves/twisted/full2.4-debian64/Twisted/twisted/internet/process.py", line 44, in reapAllProcesses
    process.reapProcess()
  File "/home/buildslave/slaves/twisted/full2.4-debian64/Twisted/twisted/internet/process.py", line 556, in reapProcess
    log.msg('Failed to reap %d:' % self.pid)
exceptions.TypeError: int argument required
===============================================================================
[ERROR]: twisted.test.test_internet.SystemEventTestCase.testTriggerSystemEvent1

Traceback (most recent call last):
  File "/home/buildslave/slaves/twisted/full2.4-debian64/Twisted/twisted/internet/base.py", line 532, in runUntilCurrent
    f(*a, **kw)
  File "/home/buildslave/slaves/twisted/full2.4-debian64/Twisted/twisted/internet/process.py", line 44, in reapAllProcesses
    process.reapProcess()
  File "/home/buildslave/slaves/twisted/full2.4-debian64/Twisted/twisted/internet/process.py", line 556, in reapProcess
    log.msg('Failed to reap %d:' % self.pid)
exceptions.TypeError: int argument required
-------------------------------------------------------------------------------
```

I assume this has to do with the changed clean up code.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun commented|
|-|-|

I'd like to understand those tracebacks before this branch is merged.  Fixing them in the obvious way may well just be papering over a real bug, either existing or introduced in this branch.

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)|@jml commented|
|-|-|

Likewise.  Although, I don't even know what the obvious way of fixing them is :)

They are race conditions, it seems.

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)|@jml commented|
|-|-|

OK. More info.

```
2006/07/16 22:46 EST [-] --> twisted.mail.test.test_mail.ProcessAliasTestCase.testAliasResolution <--
2006/07/16 22:46 EST [-] Process constructed: echo, ['echo'], {}, None
2006/07/16 22:46 EST [-] Process constructed: echo, ['echo'], {}, None
2006/07/16 22:46 EST [-] --> twisted.mail.test.test_mail.ProcessAliasTestCase.testCyclicAlias <--
2006/07/16 22:46 EST [-] Process constructed: echo, ['echo'], {}, None
2006/07/16 22:46 EST [-] --> twisted.mail.test.test_mail.ProcessAliasTestCase.testProcessAlias <--
2006/07/16 22:46 EST [-] Process constructed: /Users/jml/Projects/Twisted/branches/deferred-1781-2/twisted/mail/test/process.alias.sh, ['/Users/jml/Projects/Twisted/branches/deferred-1781-2/twisted/mail/test/process.alias.sh'], {}, None
2006/07/16 22:46 EST [-] /Users/jml/Projects/Twisted/branches/deferred-1781-2/twisted/mail/alias.py:214: exceptions.DeprecationWarning: Deferred.setTimeout is deprecated.  Look for timeout support specific to the API you are using instead.
2006/07/16 22:46 EST [-] --> twisted.mail.test.test_mail.RelayTestCase.testExists <--
2006/07/16 22:46 EST [-] --> twisted.mail.test.test_mail.RelayerTestCase.testMailData <--
2006/07/16 22:46 EST [-] --> twisted.mail.test.test_mail.RelayerTestCase.testMailFrom <--
2006/07/16 22:46 EST [-] --> twisted.mail.test.test_mail.RelayerTestCase.testMailTo <--
2006/07/16 22:46 EST [-] --> twisted.mail.test.test_mail.ServiceDomainTestCase.testReceivedHeader <--
2006/07/16 22:46 EST [-] --> twisted.mail.test.test_mail.ServiceDomainTestCase.testValidateFrom <--
2006/07/16 22:46 EST [-] --> twisted.mail.test.test_mail.ServiceDomainTestCase.testValidateTo <--
2006/07/16 22:46 EST [-] --> twisted.mail.test.test_mail.ServiceDomainTestCase.testValidateToBadDomain <--
2006/07/16 22:46 EST [-] --> twisted.mail.test.test_mail.ServiceDomainTestCase.testValidateToBadUsername <--
2006/07/16 22:46 EST [-] --> twisted.mail.test.test_mail.VirtualPOP3TestCase.testAuthenticateAPOP <--
2006/07/16 22:46 EST [-] --> twisted.mail.test.test_mail.VirtualPOP3TestCase.testAuthenticateBadPasswordPASS <--
2006/07/16 22:46 EST [-] --> twisted.mail.test.test_mail.VirtualPOP3TestCase.testAuthenticateBadUserPASS <--
2006/07/16 22:46 EST [-] --> twisted.mail.test.test_mail.VirtualPOP3TestCase.testAuthenticateIncorrectResponseAPOP <--
2006/07/16 22:46 EST [-] --> twisted.mail.test.test_mail.VirtualPOP3TestCase.testAuthenticateIncorrectUserAPOP <--
2006/07/16 22:46 EST [-] --> twisted.mail.test.test_mail.VirtualPOP3TestCase.testAuthenticatePASS <--
2006/07/16 22:46 EST [-] --> twisted.mail.test.test_pop3.AnotherPOP3TestCase.testAuthListing <--
2006/07/16 22:46 EST [-] New connection from loopback
2006/07/16 22:46 EST [-] Failed to reap None (None):
2006/07/16 22:46 EST [-] Unhandled Error
	Traceback (most recent call last):
	  File "/Users/jml/projects/Twisted/trunk/twisted/protocols/loopback.py", line 85, in loopback
	    reactor.iterate(0.01) # this is to clear any deferreds
	  File "/Users/jml/Projects/Twisted/branches/deferred-1781-2/twisted/internet/base.py", line 381, in iterate
	    self.runUntilCurrent()
	  File "/Users/jml/Projects/Twisted/branches/deferred-1781-2/twisted/internet/base.py", line 532, in runUntilCurrent
	    f(*a, **kw)
	  File "/Users/jml/Projects/Twisted/branches/deferred-1781-2/twisted/internet/process.py", line 44, in reapAllProcesses
	    process.reapProcess()
	--- <exception caught here> ---
	  File "/Users/jml/Projects/Twisted/branches/deferred-1781-2/twisted/internet/process.py", line 558, in reapProcess
	    pid, status = os.waitpid(self.pid, os.WNOHANG)
	exceptions.TypeError: an integer is required
```

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)|@jml commented|
|-|-|

So, it looks like `ProcessAliasTestCase` doesn't clean up its processes.  Then, `testAuthListing` uses loopback, which runs `reactor.iterate`, which triggers a reapProcess call.

How do I proceed from here?

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)|@jml commented|
|-|-|


 1. Fix `loopback` to not call `reactor.iterate`. This would mean making it return a `Deferred`, which would mean changing a 'lot' of tests.
 1. Insert an arbitrary `d = defer.Deferred(); reactor.callLater(0, d.callback, None); return d` into `TestCase._cbCleanup`.
 1. Do something to correctly clean up whatever processes are misbehaving.

I reckon 1.

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)<a name="note_12"></a>|@jml commented|
|-|-|

OK, touching this bug after a long break.

[#1936](https://github.com/twisted/twisted/issues/1936) added a new `loopbackAsync` and deprecated the old, blocking loopback. It meant changing a lot of tests.

There are still a lot of unclean tests that become failing tests when I drop the iterate() calls in cleanup. I propose implementing something similar to what foom suggests in [#1883](https://github.com/twisted/twisted/issues/1883) and giving a warning for unclean tests.

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)<a name="note_13"></a>|@jml commented|
|-|-|

We want this in Twisted 2.7

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)<a name="note_15"></a>|@jml set status to `closed`|
|-|-|

It would be really, really good if all of the tests could be run in one never-restarted reactor. It would also be really, really good if Trial provided a way to run a suite of tests in one reactor.

However:
 * This is not the best way to remove the _wait ugliness from Trial
 * The current branch is way too big and conflicty.

I have filed [#2900](https://github.com/twisted/twisted/issues/2900), which supersedes this ticket.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
