### ISSUE TITLE
setup.py bdist_rpm fails on FC5 for x86_64

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#1811]
|<img alt="troy@...'s avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| troy@... reported|
|-|-|
|Trac ID|trac#1811|
|Type|defect|
|Created|2006-06-10 15:25:13Z|

```
[troy@minas-tirith twisted-src-svn]$ ./setup.py bdist_rpm
running bdist_rpm
writing 'build/bdist.linux-x86_64/rpm/SPECS/Twisted.spec'
running sdist
warning: sdist: manifest template 'MANIFEST.in' does not exist (using default file list)
Traceback (most recent call last):
  File "twisted/topfiles/setup.py", line 107, in ?
    dist.setup(**setup_args)
  File "./twisted/python/dist.py", line 74, in setup
    return core.setup(**kw)
  File "/usr/lib64/python2.4/distutils/core.py", line 149, in setup
    dist.run_commands()
  File "/usr/lib64/python2.4/distutils/dist.py", line 946, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.4/distutils/dist.py", line 966, in run_command
    cmd_obj.run()
  File "/usr/lib64/python2.4/distutils/command/bdist_rpm.py", line 305, in run
    self.run_command('sdist')
  File "/usr/lib64/python2.4/distutils/cmd.py", line 333, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.4/distutils/dist.py", line 966, in run_command
    cmd_obj.run()
  File "/usr/lib64/python2.4/distutils/command/sdist.py", line 143, in run
    self.get_file_list()
  File "/usr/lib64/python2.4/distutils/command/sdist.py", line 240, in get_file_list
    self.add_defaults()
  File "/usr/lib64/python2.4/distutils/command/sdist.py", line 301, in add_defaults
    self.filelist.extend(build_ext.get_source_files())
  File "/usr/lib64/python2.4/distutils/command/build_ext.py", line 371, in get_source_files
    self.check_extensions_list(self.extensions)
  File "/usr/lib64/python2.4/distutils/command/build_ext.py", line 304, in check_extensions_list
    (ext_name, build_info) = ext
TypeError: unpack non-sequence
Error: Subprocess exited with result 1 for project core
```

<details><summary>Searchable metadata</summary>

```
trac-id__1811 1811
type__defect defect
reporter__troy____ troy@...
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__duplicate duplicate
component__core core
keywords__ 
time__1149953113000000 1149953113000000
changetime__1149981233000000 1149981233000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)|@glyph set status to `closed`|
|-|-|

Duplicate of [#7099](https://github.com/twisted/twisted/issues/7099)

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
