### ISSUE TITLE
web2.dav COPY and MOVE methods fail if root directory of DAV resource is unwritable

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#1825]
|<img alt="troy@...'s avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| troy@... reported|
|-|-|
|Trac ID|trac#1825|
|Type|defect|
|Created|2006-06-15 18:25:42Z|

I've found that if the root directory of a DAV resource is not writable by the userid of the DAV service, attempts to invoke the COPY and MOVE methods will fail, even if the source and destination are both writable by that userid.

For instance, say I own a directory /local/davtest containing a zero-length file called foo.  If I as a non-root user run a DAV service exporting /local/davtest on port 8901, I can connect to it with "cadaver http://localhost:8901/" and copy or move foo to bar.  However, if I instead have the DAV service export / (not writable by me) and connect to it with "cadaver http://localhost:8901/local/davtest/", copy and move operations on that exact same file will fail, sending the client an internal server error and printing the following stack trace:

Following running "copy foo bar" in "cadaver http://localhost:8901/local/davtest/":
```
2006/06/15 13:52 EDT [HTTPChannel,1,127.0.0.1] COPY /local/davtest/foo HTTP/1.1
2006/06/15 13:52 EDT [HTTPChannel,1,127.0.0.1] Exception rendering:
2006/06/15 13:52 EDT [HTTPChannel,1,127.0.0.1] Unhandled Error
        Traceback (most recent call last):
          File "/local/twisted-svn/lib/python2.3/site-packages/twisted/web2/resource.py", line 85, in renderHTTP
            return method(request)
          File "/local/twisted-svn/lib/python2.3/site-packages/twisted/web2/dav/method/copymove.py", line 56, in http_COPY
            return prepareForCopy(self, request).addCallback(do)
          File "/local/twisted-svn/lib/python2.3/site-packages/twisted/web2/dav/method/copymove.py", line 105, in prepareForCopy
            d = request.locateResource(destination_uri)
          File "/local/twisted-svn/lib/python2.3/site-packages/twisted/web2/server.py", line 417, in locateResource
            return defer.maybeDeferred(self._getChild, None, self.site.resource, segments, updatepaths=False)
        --- <exception caught here> ---
          File "/local/twisted-svn/lib/python2.3/site-packages/twisted/internet/defer.py", line 107, in maybeDeferred
            result = f(*args, **kw)
          File "/local/twisted-svn/lib/python2.3/site-packages/twisted/web2/server.py", line 298, in _getChild
            return self._handleSegment(result, res, path, updatepaths)
          File "/local/twisted-svn/lib/python2.3/site-packages/twisted/web2/server.py", line 342, in _handleSegment
            child = self._getChild(None, newres, newpath)
          File "/local/twisted-svn/lib/python2.3/site-packages/twisted/web2/server.py", line 298, in _getChild
            return self._handleSegment(result, res, path, updatepaths)
          File "/local/twisted-svn/lib/python2.3/site-packages/twisted/web2/server.py", line 340, in _handleSegment
            self.prepath.append(self.postpath.pop(0))
        exceptions.IndexError: pop from empty list

```
(The move operation generates a similar traceback.)

Obviously this is only a consideration for situations where the DAV server exports a directory hierarchy whose root is nonwritable to its userid, but as I mentioned in ticket [#1807](https://github.com/twisted/twisted/issues/1807), some of the things we're trying to do with DAV require exactly that.  Since the directory containing the leaf resource in question *is* writable by the DAV server, it seems to me that this ought to either work or fail more gracefully than an "internal server error".

I'll attach an example DAV service implementation and, if desired, logs and full output for both cases.

Attachments:

* [DAVservice.py](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/74c/74c8aab11c14f69a22bcbe2f4bfb0d4d4577459d/a19ef42bb28c34abccd1afd9bc3126379e787f7d.py) (1528 bytes) - added by troy@... on 2006-06-15 18:26:35Z - DAV service example

<details><summary>Searchable metadata</summary>

```
trac-id__1825 1825
type__defect defect
reporter__troy____ troy@...
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__web2_dav web2.dav
keywords__dav dav
time__1150395942000000 1150395942000000
changetime__1158093679000000 1158093679000000
version__None None
owner__ 
cc__wsanchez
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="dreid's avatar" src="https://avatars.githubusercontent.com/u/48695?s=50" width="50" height="50">](https://github.com/dreid)|@dreid set owner to @wsanchez|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="dreid's avatar" src="https://avatars.githubusercontent.com/u/48695?s=50" width="50" height="50">](https://github.com/dreid)|@dreid commented|
|-|-|

Thanks for the report troy, I think this bug was actually fixed yesterday in a branch which should be ready for review sometime today or tomorrow.  You might try applying this changeset:17222 and seeing if it fixes the problem.

**Comment by twisted-trac** [comment]
|<img alt="troy@...'s avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|troy@... commented|
|-|-|

changeset:17222 fixes the problem I describe.  Thanks!

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)|@wsanchez set status to `assigned`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)<a name="note_7"></a>|@wsanchez set status to `closed`|
|-|-|

This has been merged to trunk.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
