### ISSUE TITLE
DAV server using web2.dav fails several properties tests in Litmus 0.10.5

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#1828]
|<img alt="troy@...'s avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| troy@... reported|
|-|-|
|Trac ID|trac#1828|
|Type|defect|
|Created|2006-06-16 21:31:47Z|

When running Litmus 0.10.5 against a authenticated DAV server implemented using web2.dav (with the patches in [#1807](https://github.com/twisted/twisted/issues/1807), [#1825](https://github.com/twisted/twisted/issues/1825), and [#1827](https://github.com/twisted/twisted/issues/1827)), three of the properties tests fail and several more are skipped:

```
...basic and copymove tests all succeed...
-> running `props':
 0. init.................. pass
 1. begin................. pass
...
 6. propset............... FAIL (PROPPATCH on `/local/davtest/litmus/prop': 500
Internal Server Error)
 7. propget............... SKIPPED
...
 9. propmove.............. SKIPPED
10. propget............... SKIPPED
11. propdeletes........... SKIPPED
12. propget............... SKIPPED
13. propreplace........... SKIPPED
14. propget............... SKIPPED
15. propnullns............ SKIPPED
16. propget............... SKIPPED
17. prophighunicode....... SKIPPED
18. propget............... SKIPPED
19. propvalnspace......... SKIPPED
...
22. propmanyns............ FAIL (PROPPATCH on `/local/davtest/litmus/prop': 500
Internal Server Error)
23. propget............... FAIL (No value given for property {kappa}somename)
...
-> 12 tests were skipped.
<- summary for `props': of 14 tests run: 11 passed, 3 failed. 78.6%
...
```

The first of these produces the following message in the logs:
```
2006/06/16 16:51 EDT [HTTPChannel,5,192.148.249.102] PROPFIND /local/davtest/litmus/ HTTP/1.1
2006/06/16 16:51 EDT [-] 'Bad XML:\n<foo>'
2006/06/16 16:51 EDT [-] 'Error while handling PROPFIND body: [Failure instance: Traceback: exceptions.ValueError: <unknown>:1:5: no element found\n/local/twisted-svn/lib/python2.3/site-packages/twisted/web2/stream.py:407:_read\n/local/twisted-svn/lib/python2.3/site-packages/twisted/web2/stream.py:418:_gotData\n/local/twisted-svn/lib/python2.3/site-packages/twisted/internet/defer.py:229:callback\n/local/twisted-svn/lib/python2.3/site-packages/twisted/internet/defer.py:294:_startRunCallbacks\n--- <exception caught here> ---\n/local/twisted-svn/lib/python2.3/site-packages/twisted/internet/defer.py:307:_runCallbacks\n/local/twisted-svn/lib/python2.3/site-packages/twisted/web2/dav/util.py:65:gotAllData\n/local/twisted-svn/lib/python2.3/site-packages/twisted/web2/dav/util.py:75:parse\n/local/twisted-svn/lib/python2.3/site-packages/twisted/web2/dav/element/parser.py:187:parse\n]'
```

The latter two produce tracebacks on the server side which end with:
```
2006/06/16 16:51 EDT [-] Exception rendering:
2006/06/16 16:51 EDT [-] Unhandled Error
        Traceback (most recent call last):
...
          File "/local/twisted-svn/lib/python2.3/site-packages/twisted/web2/dav/method/proppatch.py", line 102, in do
            action(property, request)
          File "/local/twisted-svn/lib/python2.3/site-packages/twisted/web2/dav/resource.py", line 186, in writeProperty
            self.deadProperties().set(property)
          File "/local/twisted-svn/lib/python2.3/site-packages/twisted/web2/dav/noneprops.py", line 49, in set
            raise HTTPError(responsecode.NOT_FOUND, StatusResponse("Permission denied for setting property: %s" % (property,)))
        exceptions.TypeError: __init__() takes at least 3 arguments (2 given)
```

It looks like some of the exception handling in web2/dav/element/parser.py and web2/dav/noneprops.py may not be initializing themselves properly in all cases.

DAV server code, logs, and full Litmus output attached.

Attachments:

* [litmus.out](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/f9d/f9db519c97dc5f0cdf3a6ee0d574c9cd36fb1c61/28379911f7d7b03050f4fbe7e81a45adc2349ec6.out) (2902 bytes) - added by troy@... on 2006-06-16 21:32:21Z - Litmus 0.10.5 output
* [litmus-test-DAVservice.log](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/f9d/f9db519c97dc5f0cdf3a6ee0d574c9cd36fb1c61/08afaf16dc953b4f7528f66089023b4830b03dca.log) (42314 bytes) - added by troy@... on 2006-06-16 21:33:05Z - server log from litmus run

<details><summary>Searchable metadata</summary>

```
trac-id__1828 1828
type__defect defect
reporter__troy____ troy@...
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__wontfix wontfix
component__web2_dav web2.dav
keywords__dav dav
time__1150493507000000 1150493507000000
changetime__1260484399000000 1260484399000000
version__None None
owner__ 
cc__wsanchez cc__thijs
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="troy@...'s avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|troy@... commented|
|-|-|

The DAV server program I used is attached to [#1827](https://github.com/twisted/twisted/issues/1827).

**Comment by twisted-trac** [comment]
|<img alt="troy@...'s avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|troy@... commented|
|-|-|

In today's SVN head (r17407), the same prop tests fail as when I first reported this, but with HTTP code 403 ("Forbidden") rather than 500.  Furthermore, the tracebacks that occurred previously do not happen.  I suspect that xattr is not supported very well on the ancient FC3 distro I have to work with on the host running the DAV server, so there's a very good probability that this problem is fixed.

**Comment by twisted-trac** [comment]
|<img alt="troy@...'s avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|troy@... commented|
|-|-|

I have tried on both an FC3 system and an FC5 system, both with attr and python-xattr installed, and I still get "permission denied" on any PROPPATCH tests in litmus.  I can however set xattrs on file manually using attr and python-xattr.  I have noticed that an xattr set with the attr command (eg. "attr -s comment -V "This is a comment" /tmp/foo") will be named "user.comment" from the PoV of python-xattr; could that be part of the problem?

**Comment by twisted-trac** [comment]
|[<img alt="jyknight's avatar" src="https://avatars.githubusercontent.com/u/873903?s=50" width="50" height="50">](https://github.com/jyknight)|@jyknight commented|
|-|-|

I think python-xattr is the wrong xattr module. There's two.

Web2 currently requires: http://undefined.org/python/#xattr but patches to support the other would be accepted.

**Comment by twisted-trac** [comment]
|<img alt="rfmohr@...'s avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_5"></a>|rfmohr@... commented|
|-|-|

I believe the root cause has to do with the deadPropertyXattrPrefix variable in the xattrPropertyStore class (in the twisted.web2.dav.xattrprops module).  When I mount an ext3 filesystem with the user_xattr option, I can set properties, but they must all be prefixed with "user.".  I have found that adding the following lines to my dav server program seems to solve the problem:
```
from twisted.web2.dav.xattrprops import xattrPropertyStore
xattrPropertyStore.deadPropertyXattrPrefix = "user."
```
The default value of "WebDAV:" won't work.  Ideally, there should be some sort of internal mechanism to check the platform and set this prefix appropriately.  Is there any reason why it needs to be a class variable?  Would it work to make it an instance variable and then have the constructor determine the proper value automatically?

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)|@wsanchez set status to `assigned`|
|-|-|

**Comment by twisted-trac** [comment]
|<img alt="vincentk's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_8"></a>|vincentk commented|
|-|-|

Replying to [rfmohr@...](#note_5):
> I believe the root cause has to do with the deadPropertyXattrPrefix variable in the xattrPropertyStore class (in the twisted.web2.dav.xattrprops module).  




I believe this issue with xattrs on linux has now been fixed. See: http://twistedmatrix.com/trac/ticket/2081 
and
http://lists.macosforge.org/pipermail/calendarserver-dev/2006-September/000011.html

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_10"></a>|@thijstriemstra commented|
|-|-|

web2.dav doesn't exist anymore, and web2 is deprecated, so can this ticket be closed?

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)<a name="note_11"></a>|@wsanchez set status to `closed`|
|-|-|

okies

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
