### ISSUE TITLE
Trac spews a RuntimeError when creating a New Ticket under some conditions.

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#1834]
|[<img alt="bitglue's avatar" src="https://avatars.githubusercontent.com/u/1232472?s=50" width="50" height="50">](https://github.com/bitglue)| @bitglue reported|
|-|-|
|Trac ID|trac#1834|
|Type|defect|
|Created|2006-06-19 17:40:25Z|

1. go to http://twistedmatrix.com/trac/newticket

2. In the field at the top of that form labeled "Your email or username:", enter your email.

3. Submit the ticket

4. get something like this:

```
Traceback (most recent call last):
  File "/home/trac/Projects/trac/trunk/trac/web/main.py", line 283, in dispatch_request
    dispatcher.dispatch(req)
  File "/home/trac/Projects/trac/trunk/trac/web/main.py", line 170, in dispatch
    resp = chosen_handler.process_request(req)
  File "/home/trac/Projects/trac/trunk/trac/ticket/web_ui.py", line 83, in process_request
    self._do_create(req, db)
  File "/home/trac/Projects/trac/trunk/trac/ticket/web_ui.py", line 138, in _do_create
    ticket.insert(db=db)
  File "/home/trac/Projects/trac/trunk/trac/ticket/model.py", line 196, in insert
    tktObs.ticket_added(self)
  File "/home/trac/projects/trac/plugins/TICKET_EMAILER_MAN-ONE-py2.4.egg/ticket_emailer/ticket_emailer.py", line 128, in ticket_added
  File "/home/trac/projects/trac/plugins/TICKET_EMAILER_MAN-ONE-py2.4.egg/ticket_emailer/ticket_emailer.py", line 95, in ticketAddedMessage
  File "/home/trac/projects/trac/plugins/TICKET_EMAILER_MAN-ONE-py2.4.egg/ticket_emailer/ticket_emailer.py", line 86, in baseMessage
  File "/home/trac/projects/trac/plugins/TICKET_EMAILER_MAN-ONE-py2.4.egg/ticket_emailer/ticket_emailer.py", line 53, in ticketVars
RuntimeError: Visit the 'User Configuration' page and enter an email address before you create a ticket.
```

<details><summary>Searchable metadata</summary>

```
trac-id__1834 1834
type__defect defect
reporter__indigo indigo
priority__low low
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__website website
keywords__ 
time__1150738825000000 1150738825000000
changetime__1267287782000000 1267287782000000
version__None None
owner__tekNico tekNico
cc__tekNico cc__thijs
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="teknico's avatar" src="https://avatars.githubusercontent.com/u/172521?s=50" width="50" height="50">](https://github.com/teknico)|@teknico set status to `assigned`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun commented|
|-|-|

The source for TICKET_EMAILER_MAN is here:

http://divmod.org/trac/browser/sandbox/exarkun/ticket-emailer

We can relocate it or figure something else out if you want to make some changes.

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_3"></a>|@thijstriemstra commented|
|-|-|

How should this be fixed? http://divmod.org/trac/changeset/11238/sandbox/exarkun/ticket-emailer/ticket_emailer/ticket_emailer.py introduced the change, but other bugfixes have been added since then, not sure if it's still an issue.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_4"></a>|@exarkun set status to `closed`|
|-|-|

No longer an issue for quite some time.
