### ISSUE TITLE
DAV MKCOL method with body causes uncaught exception

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#1838]
|<img alt="troy@...'s avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| troy@... reported|
|-|-|
|Trac ID|trac#1838|
|Type|defect|
|Created|2006-06-21 17:43:46Z|

Litmus 0.10.5 has found another bug that seems to have crept into web2.dav during the recent spate of DAV patches:

Client side messages:
```
-> running `basic':
 0. init.................. pass
 1. begin................. pass
 2. options............... WARNING: server does not claim Class 2 compliance
    ...................... pass (with 1 warning)
...
13. mkcol_with_body....... FAIL (MKCOL with weird body must fail with 415 (RFC2518:8.3.1))
14. finish................ pass
<- summary for `basic': of 15 tests run: 14 passed, 1 failed. 93.3%
-> 1 warning was issued.
```

Traceback on server side:
```
2006/06/21 13:31 EDT [HTTPChannel,1,192.148.249.102] MKCOL /local/davtest/litmus/mkcolbody HTTP/1.1
2006/06/21 13:31 EDT [HTTPChannel,1,192.148.249.102] Exception rendering:
2006/06/21 13:31 EDT [HTTPChannel,1,192.148.249.102] Unhandled Error
        Traceback (most recent call last):
          File "/local/twisted-svn/lib/python2.3/site-packages/twisted/internet/defer.py", line 261, in errback
            self._startRunCallbacks(fail)
          File "/local/twisted-svn/lib/python2.3/site-packages/twisted/internet/defer.py", line 304, in _startRunCallbacks
            self._runCallbacks()
          File "/local/twisted-svn/lib/python2.3/site-packages/twisted/internet/defer.py", line 317, in _runCallbacks
            self.result = callback(self.result, *args, **kw)
          File "/local/twisted-svn/lib/python2.3/site-packages/twisted/internet/defer.py", line 647, in gotResult
            _deferGenerator(g, deferred)
        --- <exception caught here> ---
          File "/local/twisted-svn/lib/python2.3/site-packages/twisted/internet/defer.py", line 623, in _deferGenerator
            result = g.next()
          File "/local/twisted-svn/lib/python2.3/site-packages/twisted/web2/dav/method/mkcol.py", line 82, in http_MKCOL
            log.err("Error while handling MKCOL body: %s" % (f,))
        exceptions.NameError: global name 'f' is not defined
```

<details><summary>Searchable metadata</summary>

```
trac-id__1838 1838
type__defect defect
reporter__troy____ troy@...
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__web2_dav web2.dav
keywords__None None
time__1150911826000000 1150911826000000
changetime__1474197555542286 1474197555542286
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|<img alt="troy@...'s avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|troy@... commented|
|-|-|

BTW, the DAV server used here is the same one used in [#1827](https://github.com/twisted/twisted/issues/1827) and [#1828](https://github.com/twisted/twisted/issues/1828), using the head from svn twisted/trunk.

**Comment by twisted-trac** [comment]
|<img alt="troy@...'s avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|troy@... commented|
|-|-|

This appears to be fixed as of r17407 or so.

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)|@wsanchez set status to `assigned`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)<a name="note_5"></a>|@wsanchez commented|
|-|-|

OK, I'm adding a test for this.  The traceback above appears to have been fixed earlier...  And a 415 is resulting from a MKCOL with a goofy body, so that looks good.

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)<a name="note_6"></a>|@wsanchez commented|
|-|-|

Test added to branch dav-mkcol-with-body-1838

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)|@wsanchez set owner to @dreid<br>@wsanchez set status to `new`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="dreid's avatar" src="https://avatars.githubusercontent.com/u/48695?s=50" width="50" height="50">](https://github.com/dreid)<a name="note_9"></a>|@dreid set owner to @wsanchez|
|-|-|

What exactly is the failure condition here?  Is it that the MKCOL request actually has a body? Or just that it has an invalid body?  If the latter where is the test that includes the valid body?

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)<a name="note_10"></a>|@wsanchez set owner to @dreid|
|-|-|

Any body at all is invalid in our implementation.

It's possible to add support for an XML body that does some additional logic, but we do not support any such requests, hence the lack for a test for them.

**Comment by twisted-trac** [comment]
|[<img alt="dreid's avatar" src="https://avatars.githubusercontent.com/u/48695?s=50" width="50" height="50">](https://github.com/dreid)<a name="note_11"></a>|@dreid set owner to @wsanchez|
|-|-|

Ok, the testname and the body content made it seem like there were valid bodies (in our implementation.) If this is not the case then perhaps the test should be renamed to more clearly indicate what it's actually testing.  

Otherwise it looks fine.

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)<a name="note_12"></a>|@wsanchez set status to `closed`|
|-|-|

(In [18110]) Add a test for requests with an invalid (that would be any) request body.
Reviewed by dreid
Fixes [#1838](https://github.com/twisted/twisted/issues/1838)

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_14"></a>|@hawkowl commented|
|-|-|

[mass edit] Removing review from closed tickets.
