### ISSUE TITLE
Svn  python 2.4  Suse 9, 64 bit

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#1851]
|<img alt="scmikes's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| scmikes reported|
|-|-|
|Trac ID|trac#1851|
|Type|enhancement|
|Created|2006-06-23 18:18:18Z|

Here is the Python 2.4 version of ticket [#1848](https://github.com/twisted/twisted/issues/1848)

Suse 9 ,  64 bit
Python 2.4

Twisted SVN co  version #

Ran 895 tests in 179.913s

FAILED (skips=53, expectedFailures=4, failures=7, errors=17, successes=820)
$

Attachments:

* [trial_python2.4.out](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/f48/f4807e7bc0ab85a61203b6e384806efeb08177af/948125ae1931ab99376a40b19a672325a61acf37.out) (104714 bytes) - added by scmikes on 2006-06-23 18:18:38Z - 
* [trial_python2.4.2.out](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/f48/f4807e7bc0ab85a61203b6e384806efeb08177af/ba28f2b9e0c9553d1f92d95fcab1c82cb60c2939.out) (104714 bytes) - added by scmikes on 2006-06-23 18:19:00Z - 
* [test.log](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/f48/f4807e7bc0ab85a61203b6e384806efeb08177af/324a41b34d2dfa32c804ef7b2ac23fc24200c596.log) (288284 bytes) - added by scmikes on 2006-06-23 18:22:13Z - 

<details><summary>Searchable metadata</summary>

```
trac-id__1851 1851
type__enhancement enhancement
reporter__scmikes scmikes
priority__normal normal
milestone__Core_2_5 Core-2.5
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__suse9_64bit_twisted_trial_test_run_results suse9 64bit twisted trial test run results
time__1151086698000000 1151086698000000
changetime__1155871143000000 1155871143000000
version__None None
owner__scmikes scmikes
cc__scmikes cc__exarkun
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun set owner to scmikes|
|-|-|

Are you sure this is Python 2.4?

Note the following:

```
pythonexarkun@kunai:~$ python
Python 2.4.3 (#2, Apr 27 2006, 14:43:58)
[GCC 4.0.3 (Ubuntu 4.0.3-1ubuntu5)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from twisted.python import failure
>>> try:
...     1/0
... except:
...     failure.Failure().printTraceback()
...
Traceback (most recent call last):
--- <exception caught here> ---
  File "<stdin>", line 2, in ?

exceptions.ZeroDivisionError: integer division or modulo by zero
>>>
```

```
Python 2.5a2 (trunk:46477, May 27 2006, 12:22:09)
[GCC 4.0.3 (Ubuntu 4.0.3-1ubuntu5)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from twisted.python import failure
>>> try:
...     1/0
... except:
...     failure.Failure().printTraceback()
... 
Traceback (most recent call last):
--- <exception caught here> ---
  File "<stdin>", line 2, in <module>
    
<type 'exceptions.ZeroDivisionError'>: integer division or modulo by zero
>>> 
```

The log attached looks more like a Python 2.5 log.

**Comment by twisted-trac** [comment]
|<img alt="scmikes's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|scmikes set status to `assigned`|
|-|-|

Let me build pycrypto on Monday (machine is being updated this weekend).

And I will rerun.

**Comment by twisted-trac** [comment]
|<img alt="scmikes's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_3"></a>|scmikes set status to `closed`|
|-|-|

created suse buildbot
