### ISSUE TITLE
twisted.web.monitor traceback, AttributeError: class IChangeNotified has no attribute '__class__'

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#1878]
|<img alt="misc@...'s avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| misc@... reported|
|-|-|
|Trac ID|trac#1878|
|Type|defect|
|Created|2006-06-29 19:02:02Z|

```
~ $ python /usr/share/doc/python-twisted-web-0.6.0/examples/webmon.py http://sisay.ephaone.org/~misc/tmp/tmp.rss
Traceback (most recent call last):
  File "/usr/share/doc/python-twisted-web-0.6.0/examples/webmon.py", line 6, in ?
    from twisted.web import monitor
  File "/usr/lib64/python2.4/site-packages/twisted/web/monitor.py", line 14, in ?
    class BaseChangeNotified:
  File "/usr/lib64/python2.4/site-packages/zope/interface/advice.py", line 132, in advise
    return callback(newClass)
  File "/usr/lib64/python2.4/site-packages/zope/interface/declarations.py", line 550, in _implements_advice
    classImplements(cls, *interfaces)
  File "/usr/lib64/python2.4/site-packages/zope/interface/declarations.py", line 527, in classImplements
    spec.declared += tuple(_normalizeargs(interfaces))
  File "/usr/lib64/python2.4/site-packages/zope/interface/declarations.py", line 1345, in _normalizeargs
    _normalizeargs(v, output)
  File "/usr/lib64/python2.4/site-packages/zope/interface/declarations.py", line 1340, in _normalizeargs
    cls = sequence.__class__
AttributeError: class IChangeNotified has no attribute '__class__'
```

It seems IChangeNotified need to inherit from components.Interface, i will attach a patch.

Attachments:

* [twisted.monitor.fix1878.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/f38/f3881e12b389bb007064da68e4203a2f4507fcfb/d68b14f6704b9a6801f052acbf9e580eac52fe52.patch) (393 bytes) - added by misc@... on 2006-06-29 19:03:04Z - patch that fix the issue
* [monitor-1878.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/f38/f3881e12b389bb007064da68e4203a2f4507fcfb/7f02d08c5330253545cc8116d3e994f7747b8b8a.patch) (489 bytes) - added by collab on 2008-07-01 02:44:57Z - Patch against r24190

<details><summary>Searchable metadata</summary>

```
trac-id__1878 1878
type__defect defect
reporter__misc____ misc@...
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__wontfix wontfix
component__web web
keywords__ 
time__1151607722000000 1151607722000000
changetime__1227136226000000 1227136226000000
version__None None
owner__ 
cc__thijs cc__exarkun
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun commented|
|-|-|

Actually this code looks stupid and has no tests.  I think it should be deleted.

**Comment by twisted-trac** [comment]
|[<img alt="jyknight's avatar" src="https://avatars.githubusercontent.com/u/873903?s=50" width="50" height="50">](https://github.com/jyknight)|@jyknight commented|
|-|-|

From what I can see, it has two examples but no documentation or tests at all:
./doc/web/examples/tkwebmon.py
./doc/web/examples/webmon.py

I'm not really sure why that's pat of twisted.web at all, either. And it looks like it's probably been broken since August 2004 without anybody noticing so I think deleting it is probably not such a bad plan.

**Comment by twisted-trac** [comment]
|<img alt="collab's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_3"></a>|collab commented|
|-|-|

Replying to [exarkun](#note_1):
> Actually this code looks stupid and has no tests.  I think it should be deleted.

As long as the monitor module is still distributed in Twisted releases it would be probably not hurt to fix these imports, especially when there's 2 examples using it and it's a really simple fix. I attached an updated [[monitor-1878.patch](None/monitor-1878.patch) patch].

**Comment by twisted-trac** [comment]
|<img alt="collab's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_4"></a>|collab removed owner|
|-|-|

Putting this patch up for review.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_5"></a>|@exarkun commented|
|-|-|

Hmm.  I should have deleted it two years ago. :)

Any interest in writing tests for this code, collab?  I could see how it might be useful, but it needs docs and tests.   Also, I think the interface is probably adding minimal value here.  Deleting it and adding docstrings to `BaseChangeNotified` and its methods would simplify it and make it possible to use.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun set owner to collab|
|-|-|

**Comment by twisted-trac** [comment]
|<img alt="collab's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_7"></a>|collab set status to `assigned`|
|-|-|

Replying to [exarkun](#note_5):
> Deleting it and adding docstrings to `BaseChangeNotified` and its methods would simplify it and make it possible to use.
I could give that a try..

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)|@thijstriemstra set owner to @thijstriemstra<br>@thijstriemstra set status to `new`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_9"></a>|@exarkun commented|
|-|-|

I deleted this module in the [#2763](https://github.com/twisted/twisted/issues/2763) branch.  Assuming that change is accepted, when that branch is merged, this ticket will be resolved.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_10"></a>|@exarkun set status to `closed`|
|-|-|

I merged that branch and it deleted twisted.web.monitor, so yea, nothing to fix here anymore.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
