### ISSUE TITLE
web2 installation failure on win32

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#1898]
|[<img alt="ghazel's avatar" src="https://avatars.githubusercontent.com/u/31402?s=50" width="50" height="50">](https://github.com/ghazel)| @ghazel reported|
|-|-|
|Trac ID|trac#1898|
|Type|defect|
|Created|2006-07-05 01:25:38Z|

```
C:\Documents and Settings\user\Desktop\TwistedWeb2-0.1>python setup.py install
Traceback (most recent call last):
  File "setup.py", line 23, in ?
    long_description="Twisted Web2 is a web server.",
  File "c:\python24\lib\site-packages\twisted\python\dist.py", line 41, in setup

    kw['version'] = getVersion(projname)
  File "c:\python24\lib\site-packages\twisted\python\dist.py", line 92, in getVe
rsion
    execfile(vfile, ns)
IOError: [Errno 2] No such file or directory: 'twisted\\web2\\_version.py'
```

<details><summary>Searchable metadata</summary>

```
trac-id__1898 1898
type__defect defect
reporter__ghazel ghazel
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__invalid invalid
component__web2 web2
keywords__ 
time__1152062738000000 1152062738000000
changetime__1153008905000000 1153008905000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="jyknight's avatar" src="https://avatars.githubusercontent.com/u/873903?s=50" width="50" height="50">](https://github.com/jyknight)|@jyknight set status to `closed`|
|-|-|

Twisted 2.4 broke compatibility with older versions of subprojects. I believe web2 0.2 will work. Did you find 0.1 linked from somewhere? It looks like the website is properly linking to 0.2.

**Comment by twisted-trac** [comment]
|[<img alt="ghazel's avatar" src="https://avatars.githubusercontent.com/u/31402?s=50" width="50" height="50">](https://github.com/ghazel)|@ghazel commented|
|-|-|

http://twistedmatrix.com/projects/web2/ very clearly mentions and links to 0.1.0 only

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
