### ISSUE TITLE
twisted.web2.dav fails on copies & directory renaming

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#1913]
|<img alt="krp's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| krp reported|
|-|-|
|Trac ID|trac#1913|
|Type|defect|
|Created|2006-07-11 16:13:14Z|

I generated a simple tap application by using "mktap web2 --dav files". I'm using twistedWeb2 version 0.2.

In files/ i have 2 directories. Inside them some files. I'm accessing it with cadaver.

When trying to copy a file from one of these directories to another, here's what i get.

2006/07/11 18:07 CEST [HTTPChannel,5,127.0.0.1] Traceback (most recent call last):
          File "/usr/local/lib/python2.4/site-packages/twisted/web2/resource.py", line 85, in renderHTTP
            return method(request)
          File "/usr/local/lib/python2.4/site-packages/twisted/web2/dav/method/copymove.py", line 56, in http_COPY
            return prepareForCopy(self, request).addCallback(do)
          File "/usr/local/lib/python2.4/site-packages/twisted/web2/dav/method/copymove.py", line 105, in prepareForCopy
            d = request.locateResource(destination_uri)
          File "/usr/local/lib/python2.4/site-packages/twisted/web2/server.py", line 417, in locateResource
            return defer.maybeDeferred(self._getChild, None, self.site.resource, segments, updatepaths=False)
        --- <exception caught here> ---
          File "/usr/local/lib/python2.4/site-packages/twisted/internet/defer.py", line 107, in maybeDeferred
            result = f(*args, **kw)
          File "/usr/local/lib/python2.4/site-packages/twisted/web2/server.py", line 298, in _getChild
            return self._handleSegment(result, res, path, updatepaths)
          File "/usr/local/lib/python2.4/site-packages/twisted/web2/server.py", line 342, in _handleSegment
            child = self._getChild(None, newres, newpath)
          File "/usr/local/lib/python2.4/site-packages/twisted/web2/server.py", line 298, in _getChild
            return self._handleSegment(result, res, path, updatepaths)
          File "/usr/local/lib/python2.4/site-packages/twisted/web2/server.py", line 340, in _handleSegment
            self.prepath.append(self.postpath.pop(0))
        exceptions.IndexError: pop from empty list

<details><summary>Searchable metadata</summary>

```
trac-id__1913 1913
type__defect defect
reporter__krp krp
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__dav dav
time__1152634394000000 1152634394000000
changetime__1152635300000000 1152635300000000
version__None None
owner__ 
cc__wsanchez
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)|@wsanchez set status to `closed`|
|-|-|

Problem is already fixed on trunk.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
