### ISSUE TITLE
pydoctor tries to parse a dotfile

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#1998]
|[<img alt="dreid's avatar" src="https://avatars.githubusercontent.com/u/48695?s=50" width="50" height="50">](https://github.com/dreid)| @dreid reported|
|-|-|
|Trac ID|trac#1998|
|Type|enhancement|
|Created|2006-08-14 22:13:09Z|

Traceback (most recent call last):
  File "/private/Network/Servers/harris/Volumes/veedu/dreid/projects/CalendarServer/pydoctor/build/scripts-2.4/pydoctor", line 5, in ?
    main(sys.argv[1:])
  File "/private/Network/Servers/harris/Volumes/veedu/dreid/projects/CalendarServer/pydoctor/build/lib/pydoctor/driver.py", line 227, in main
    f()
  File "/private/Network/Servers/harris/Volumes/veedu/dreid/projects/CalendarServer/pydoctor/build/lib/pydoctor/astbuilder.py", line 316, in findImportStars
    ast = transformer.parseFile(mod.filepath)
  File "/Library/Frameworks/Python.framework/Versions/2.4//lib/python2.4/compiler/transformer.py", line 41, in parseFile
    f = open(path, "U")
IOError: [Errno 2] No such file or directory: '../twistedcaldav/.#ical.py'

I can't think of a case where I would want it to parse a dotfile, but even if I did it shouldn't fail horribly if that file is a dangling symlink.

<details><summary>Searchable metadata</summary>

```
trac-id__1998 1998
type__enhancement enhancement
reporter__dreid dreid
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__pydoctor pydoctor
keywords__ 
time__1155593589000000 1155593589000000
changetime__1155629695000000 1155629695000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="mwhudson's avatar" src="https://avatars.githubusercontent.com/u/672022?s=50" width="50" height="50">](https://github.com/mwhudson)<a name="note_1"></a>|@mwhudson set status to `closed`|
|-|-|

I wonder how I have managed to avoid that so far.  I must save my files super religiously or something.

Fixed in pydoctor revision 31310.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
