### ISSUE TITLE
trial can misreport leftover DelayedCalls

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#2006]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#2006|
|Type|defect|
|Created|2006-08-19 14:15:27Z|

On a recent run of the full test suite, this output was observed:

```
twisted.mail.test.test_imap.AuthenticatorTestCase.testFailedCramMD5 ... 
/tmp/Twisted/twisted/trial/reporter.py:201: twisted.trial.reporter.BrokenTestCaseWarning: REACTOR UNCLEAN! traceback(s) follow: 
Traceback (most recent call last):
  File "/tmp/Twisted/twisted/trial/unittest.py", line 447, in _cleanUp
    util._Janitor().postCaseCleanup()
  File "/tmp/Twisted/twisted/trial/util.py", line 64, in postCaseCleanup
    return self._dispatch('logErrCheck', 'cleanPending')
  File "/tmp/Twisted/twisted/trial/util.py", line 72, in _dispatch
    getattr(self, "do_%s" % attr)()
  File "/tmp/Twisted/twisted/trial/util.py", line 99, in do_cleanPending
    raise PendingTimedCallsError(s)
twisted.trial.util.PendingTimedCallsError: pendingTimedCalls still pending (consider setting twisted.internet.base.DelayedCall.debug = True): <DelayedCall 1100221964 [-0.000146865844727s] called=0 cancelled=0 _SimpleCallQueue.turn()>
```

However, _SimpleCallQueue is a twisted.pb feature which twisted.mail does not use.

<details><summary>Searchable metadata</summary>

```
trac-id__2006 2006
type__defect defect
reporter__exarkun exarkun
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__ 
component__trial trial
keywords__ 
time__1155996927000000 1155996927000000
changetime__1170555046000000 1170555046000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="ralphm's avatar" src="https://avatars.githubusercontent.com/u/116741?s=50" width="50" height="50">](https://github.com/ralphm)<a name="note_1"></a>|@ralphm set status to `closed`|
|-|-|

(In [17910]) Make iq tracker clean up after disconnect or firing the associated deferred.

Author: ralphm
Reviewer: exarkun
Fixes [#2006](https://github.com/twisted/twisted/issues/2006)

**Comment by twisted-trac** [comment]
|[<img alt="ralphm's avatar" src="https://avatars.githubusercontent.com/u/116741?s=50" width="50" height="50">](https://github.com/ralphm)<a name="note_2"></a>|@ralphm set status to `reopened`|
|-|-|

Oops, wrong issue mentioned.

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)<a name="note_3"></a>|@jml commented|
|-|-|

Thanks.

I wonder if we'll ever be rid of these.

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)|@jml set status to `new`|
|-|-|

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
