### ISSUE TITLE
zipstream.py (unzipIter) cannot unzip files created by distutils.archive_utils

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#2010]
|<img alt="jacobg23's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| jacobg23 reported|
|-|-|
|Trac ID|trac#2010|
|Type|defect|
|Created|2006-08-21 16:29:48Z|
|Branch|https://github.com/twisted/twisted/tree/unzip-folders-2010|

Using twisted 2.4.0 on Windows Server 2003, I tried zipstream.unzip() on a simple .zip file whose contents looked like:

```

M Filemode      Length  Date         Time      File
- ----------  --------  -----------  --------  --------
  -rw-rw-rw-        53  20-Aug-2006  13:18:42  foob
  -rw-rw-rw-        58  20-Aug-2006  13:18:56  a/b
- ----------  --------  -----------  --------  --------
                   111                         2 files

```

and ended up getting the following error:

```
>>> unzip('c:\\users\\jacob\\Workspace\\trunk\\Developer\\Jacob\\Artemis\\test1.zip', directory=normcase('c:/temp/jacob-out'), overwrite=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in ?
  File "c:\Python24\lib\site-packages\twisted\python\zipstream.py", line 138, in unzip
    for i in unzipIter(filename, directory, overwrite):
  File "c:\Python24\lib\site-packages\twisted\python\zipstream.py", line 166, in unzipIter
    outfile=file(f, 'wb')
IOError: [Errno 13] Permission denied: 'c:\\temp\\jacob-out\\a/b'
```

AFAIK, the problem is that in unzipIter, it does this:

```
            ...
            fdir=os.path.split(f)[0]
            if not os.path.exists(fdir):
                os.makedirs(f)
```

instead of:

```
{{{
            fdir=os.path.split(f)[0]
            if not os.path.exists(fdir):
                os.makedirs(fdir)
```

That seems to fix the problem.  But I'm not familiar with the code, and I also couldn't repro this problem on the Mac, which makes me suspicious I'm wrong.

Attachments:

* [foo.diff](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/e22/e22cd461c068aea5dff1c3462214880d76b3e39c/0ad4260dc64d73e657581a09e54228a4aea64fca.diff) (430 bytes) - added by jacobg23 on 2006-08-29 18:41:38Z - fix

<details><summary>Searchable metadata</summary>

```
trac-id__2010 2010
type__defect defect
reporter__jacobg23 jacobg23
priority__high high
milestone__ 
branch__branches_unzip_folders_2010 branches/unzip-folders-2010
branch_author__tenth tenth
status__closed closed
resolution__wontfix wontfix
component__core core
keywords__ 
time__1156177788000000 1156177788000000
changetime__1235343216000000 1235343216000000
version__None None
owner__jacobg23 jacobg23

```
</details>

**Comment by twisted-trac** [comment]
|<img alt="jacobg23's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_1"></a>|jacobg23 commented|
|-|-|

BTW, I think I figured out why nobody else has run into this before.  Most ZIP utilites (e.g., Info-ZIP) actually contain directory entries explicitly, e.g., the file listing might look like this:

```
mydir/
mydir/foo.bar
mydir/gnorf
mydir2/
mydir2/a.txt
```

However, I used Python's distuils.archive_util.make_zipfile() in order to crate the zip file, which does NOT include the directories in the zipfile it creates:

```
mydir/foo.bar
mydir/gnorf
mydir2/a.txt
```

The attached diff should fix the problem in zipstream -- it looks like the code intended to handle this, but there's a typo preventing it from actually working.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_3"></a>|@glyph commented|
|-|-|

There need to be tests for this.  Also, that patch was created in kind of a weird way, the filename is wrong.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)|@glyph set owner to jacobg23|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="tenth10th's avatar" src="https://avatars.githubusercontent.com/u/854235?s=50" width="50" height="50">](https://github.com/tenth10th)<a name="note_5"></a>|@tenth10th commented|
|-|-|

(In [26270]) Branching to 'unzip-folders-2010'

**Comment by twisted-trac** [comment]
|[<img alt="tenth10th's avatar" src="https://avatars.githubusercontent.com/u/854235?s=50" width="50" height="50">](https://github.com/tenth10th)<a name="note_6"></a>|@tenth10th set status to `closed`|
|-|-|

Fixed the "unzipIter" version, but not "unzipIterChunky". However, after some discussion, it sounds like this code should just be deprecated.
