### ISSUE TITLE
twisted.python.reflect.namedAny depends on undocumented import implementation details

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#2037]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#2037|
|Type|defect|
|Created|2006-08-30 03:41:59Z|

In attempting to detect ImportErrors which result from exceptions rather than missing modules, namedAny relies on the fact that CPython's import only uses a single frame for its import logic.  If this changes, or if an alternate runtime (for example, PyPy) is used, ImportErrors which stem from the lookup of a module which really does not exist will be re-raised incorrectly.

For example:
```
Traceback (most recent call last):
  File "runtrial.py", line 4, in <module>
    run()
  File "/Users/stephen/pypy-packages/twisted/scripts/trial.py", line 339, in run
    config = Options()
  File "/Users/stephen/pypy-packages/twisted/scripts/trial.py", line 129, in __init__
    self._loadReporters()
  File "/Users/stephen/pypy-packages/twisted/scripts/trial.py", line 138, in _loadReporters
    for p in plugin.getPlugins(itrial.IReporter):
--- <exception caught here> ---
  File "/Users/stephen/pypy-packages/twisted/plugin.py", line 219, in getPlugins
    adapted = interface(plugin, None)
  File "zope/interface/interface.py", line 679, in __call__
    adapter = conform(self)
  File "/Users/stephen/pypy-packages/twisted/plugin.py", line 77, in __conform__
    return self.load()
  File "/Users/stephen/pypy-packages/twisted/plugin.py", line 72, in load
    return namedAny(self.dropin.moduleName + '.' + self.name)
  File "/Users/stephen/src/Twisted/trunk/twisted/python/reflect.py", line 352, in namedAny
    topLevelPackage = __import__(trialname)
  File "/Users/stephen/src/pypy-fresh/pypy/lib/imp.py", line 208, in __lockedimport__
    return _original_import_hook(modulename, globals, locals, fromlist)
exceptions.ImportError: No module named twisted.plugins.twisted_trial.BlackAndWhite
```

<details><summary>Searchable metadata</summary>

```
trac-id__2037 2037
type__defect defect
reporter__exarkun exarkun
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__duplicate duplicate
component__core core
keywords__ 
time__1156909319000000 1156909319000000
changetime__1169008829000000 1169008829000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="jyknight's avatar" src="https://avatars.githubusercontent.com/u/873903?s=50" width="50" height="50">](https://github.com/jyknight)<a name="note_1"></a>|@jyknight commented|
|-|-|

Suggested fix? Look at the actual error message in the exception?

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_2"></a>|@exarkun commented|
|-|-|

I don't have a better idea yet.  Looking at the message is pretty icky, though :(

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_3"></a>|@exarkun set status to `closed`|
|-|-|

I suppose this is a duplicate of [#11357](https://github.com/twisted/twisted/issues/11357).

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
