### ISSUE TITLE
t.c.t.test_manhole.ManholeLoopbackStdio.testControlBackslash fails intermittently

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#2123]
|[<img alt="dreid's avatar" src="https://avatars.githubusercontent.com/u/48695?s=50" width="50" height="50">](https://github.com/dreid)| @dreid reported|
|-|-|
|Trac ID|trac#2123|
|Type|defect|
|Created|2006-09-23 15:38:12Z|

I should say this "passes intermittently" because it seems to fail most of the time on my powerbook.

```
===============================================================================
[FAIL]: twisted.conch.test.test_manhole.ManholeLoopbackStdio.testControlBackslash

Traceback (most recent call last):
  File "/Users/dreid/projects/Twisted/trunk/twisted/conch/test/test_manhole.py", line 179, in gotClearedLine
    self._assertBuffer(
  File "/Users/dreid/projects/Twisted/trunk/twisted/conch/test/test_recvline.py", line 380, in _assertBuffer
    str(receivedLines[max(0, i-1):i+1]) +
twisted.trial.unittest.FailTest: ['>>> cancelled line'] != ['']
-------------------------------------------------------------------------------
```

<details><summary>Searchable metadata</summary>

```
trac-id__2123 2123
type__defect defect
reporter__dreid dreid
priority__highest highest
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__conch conch
keywords__None None
time__1159025892000000 1159025892000000
changetime__1474197555542286 1474197555542286
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="dreid's avatar" src="https://avatars.githubusercontent.com/u/48695?s=50" width="50" height="50">](https://github.com/dreid)<a name="note_2"></a>|@dreid commented|
|-|-|

I've only observed this on OS X.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_3"></a>|@exarkun commented|
|-|-|

This seems to it less likely for the race to go the wrong way:

```
Index: twisted/conch/stdio.py
===================================================================
--- twisted/conch/stdio.py      (revision 18289)
+++ twisted/conch/stdio.py      (working copy)
@@ -52,8 +52,7 @@
             self.proto = None
 
 class ConsoleManhole(ColoredManhole):
-    def handle_QUIT(self):
-        ColoredManhole.handle_QUIT(self)
+    def connectionLost(self, reason):
         reactor.stop()
 
 def runWithProtocol(klass):
```

Apparently it is not a complete fix, though.  Don't really understand why yet.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_4"></a>|@exarkun removed owner|
|-|-|

See [#2371](https://github.com/twisted/twisted/issues/2371).  The above is not a complete fix because OS X randomly drops bytes on the floor unless one does extra things to trick it into delivering them.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_5"></a>|@exarkun commented|
|-|-|

This isn't really up for review right now.  I need to fix a couple things in the branch.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_6"></a>|@exarkun commented|
|-|-|

Okay, now this should be fixed in ctrl+backslash-2371+2123-3

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_7"></a>|@therve commented|
|-|-|

FYI, it's ctrl+backslash-2371+2123-4.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_8"></a>|@exarkun set status to `closed`|
|-|-|

(In [19640]) Merge ctrl+backslash-2371+2123-5

Author: exarkun
Reviewer: jknight, radix, therve
Fixes [[[#2371](https://github.com/twisted/twisted/issues/2371)](https://github.com/twisted/twisted/issues/2371)](https://github.com/twisted/twisted/issues/2371), [[#2123](https://github.com/twisted/twisted/issues/2123)](https://github.com/twisted/twisted/issues/2123), [[#2378](https://github.com/twisted/twisted/issues/2378)](https://github.com/twisted/twisted/issues/2378)

Remove the long-since obsolete test helper SignalMixin, which set up
and tore down special signal handling state.  For some time, trial has
taken care of this detail. (#2378)

Change the process file descriptor "connection lost" code to reverse
the setNonBlocking operation done during initialization, leaving the
file descriptor in the blocking state (what it probably was before it
was given to the process code).  This works around a bug with PTYs on
OS X where the last write made to a non-blocking PTY might be lost if
the process exits before the data is read from the other end of the
PTY.  This also corrects a (perhaps unreasonable) assumption that
blocking writes may be made to stdout after twisted.internet.stdio
has been used.  (#2371)

Change ConsoleManhole so that it waits for connectionLost notification
before stopping the reactor.  This avoids the possibility that the
reactor will stop before its transport has had all of its output
flushed.  Combined with the fix for #2371, this fixes #2123.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_10"></a>|@hawkowl commented|
|-|-|

[mass edit] Removing review from closed tickets.
