### ISSUE TITLE
trial's IReporter interface is missing some attributes

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#2164]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#2164|
|Type|defect|
|Created|2006-10-10 13:46:17Z|
|Branch|https://github.com/twisted/twisted/tree/ireporter-2164-6|

It doesn't define:

  * module
  * klass
  * longOpt
  * description

As these seem to be solely for the benefit of command line interaction, they probably don't belong on the IReporter interface directly.  Rather, trial should load a plugin of a different type and use it to create the actual IReporter.

<details><summary>Searchable metadata</summary>

```
trac-id__2164 2164
type__defect defect
reporter__exarkun exarkun
priority__normal normal
milestone__ 
branch__branches_ireporter_2164_6 branches/ireporter-2164-6
branch_author__exarkun__jml exarkun, jml
status__new new
resolution__None None
component__trial trial
keywords__ 
time__1160487977000000 1160487977000000
changetime__1287501681000000 1287501681000000
version__None None
owner__ 
cc__exarkun cc__jml
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

Also undocumented is that the reporter will be instantiated with 3 arguments to !__init!__.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_2"></a>|@exarkun commented|
|-|-|

Also undocumented, the separator and testsRun attributes and the printErrors, write, writeln, wasSuccessful, and printSummary methods.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_3"></a>|@exarkun commented|
|-|-|

Also addFailure

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_4"></a>|@exarkun commented|
|-|-|

Also addError

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_5"></a>|@exarkun commented|
|-|-|

Also, startSuite and endSuite are defined on the interface but they never seem to be called, except by the dry run visitor.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_6"></a>|@exarkun commented|
|-|-|

addError seems to be used inconsistently, too, but it's hard to tell.  Does it take a Failure instance or a three-tuple of exception information?

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)<a name="note_7"></a>|@jml commented|
|-|-|

Yes

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)<a name="note_8"></a>|@jml set owner to @jerub|
|-|-|

Ready for review

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)<a name="note_9"></a>|@jml commented|
|-|-|

... in ireporter-2164

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)<a name="note_10"></a>|@jml commented|
|-|-|

Really, actually ready.

**Comment by twisted-trac** [comment]
|[<img alt="jerub's avatar" src="https://avatars.githubusercontent.com/u/315461?s=50" width="50" height="50">](https://github.com/jerub)<a name="note_11"></a>|@jerub set owner to @jml|
|-|-|

Excellent. A few places that could use slightly better docstrings.

TrialRunner.__init__() has no docstring. Please add one. TrialRunner.run() doesn't define the types of the objects passed or returned. They are a TestCase monkeytype and IReporter I think?

test_tests doesn't have docstrings on the test_* methods, and you've done changes there. I'm not really too worried about these, but if you feel like it, add docstrings here too.

Please also file a bug about the --tbformat option. Some of the documentation says, 'plain', 'emacs' and 'cgitb'. Other bits of documentation say, 'default', 'brief' or 'verbose'. All 6 options work. I mention this here because you change a string to mention the latter instead of the former.

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)<a name="note_12"></a>|@jml commented|
|-|-|

All done. I've fixed the tbformat stuff in the branch.

btw, when doing reviews, it is _really_ helpful to specify exactly which tests you mean. Remember the author isn't looking at the diff, and by the time you do the review, they may not remember which tests they changed in that module.

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)|@jml removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)|@jml set owner to @exarkun|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_15"></a>|@exarkun set owner to @jml|
|-|-|

I guess it would be good to mark itrial's API as unstable in this branch as well.

It is not conventional for plugin interfaces to inherit from IPlugin.  I suppose this works, but it is probably not what people will expect when writing IReporterPlugin interface.  The interface also seems slightly sub-optimal for a few reasons:

  * Separating setOptions from makeReporter forces the implementation to be stateful and introduces the potential for errors where the methods are called out of order or where one is not called at all.  I can't think of a reason that makeReporter shouldn't just take the arguments itself.
  * Using Python keyword arguments restricts the possible keys to valid Python identifiers.  This rules out options with dashes in them, which are quite common on the command line.
  * Using a dictionary destroys ordering information, which may not be very important, but also makes it slightly unclear what this actually represents.  The docstring also doesn't make it clear.  At a guess, without looking at the implementation, I'd say that trial somehow accepts any possible command line argument now, parses the entire command line in the standard way with Options, and then passes a dictionary of the result in.  Looking at the implementation though, I see this is incorrect.

Some other issues, of varying severity:
  * Why do addError and addFailure take two different types?  If trial is passing in different things, it should probably stop doing that.  If someone else is passing in different things, could trial wrap the IResult and force things to be consistent?
  * IResult has an XXX comment which talks about printErrors and printSummary, but those methods are on a separate interface now.
  * twisted/trial/reporter.py has a wildcard import
  * Neither twisted.trial.reporter.Reporter nor twisted.trial.reporter.TrialReporterPlugin has a docstring
  * changes to twisted/plugins/twisted_trial.py introduce inconsistent import styles - the reporter module is both imported and imported from.
  * twisted/scripts/trial.py's opt_help_reporter doesn't put a newline after reporters without a description; this seems likely to cause confusion.
  * Renaming IReporter to IResult breaks any existing plugins (eg, merit. ;).  I think there should be some level of backwards compatibility here.
  * twisted.trial.test.test_tests.FixtureMetaTest.test_testBrokenTearDownClass fails for me when the branch is merged to trunk

I see lots of good changes in this branch too:
  * Less code in twisted_trial.py
  * IReporter/IResult simplified by the removal of extraneous attributes and methods, and separated from the nastiness of IResultPrinter (which hopefully a future branch can remove entirely).
  * Runner simplified by the removal of objects it shouldn't care about, and documentation for it added

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)<a name="note_16"></a>|@jml commented|
|-|-|

Just quickly:
 * `IResultPrinter` going away? What makes you say that?
 * `setOptions` is there so that `TrialRunner` doesn't have to know about reporter constructor arguments.
 * By my reading, `addError` and `addFailure` take the same types.
 * Got a way to support backward compat w/ `IReporter` -> `IResult` while warning `IReporter` users about the change?

Most other things sound fair.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_17"></a>|@exarkun commented|
|-|-|

  * If I make a GUI reporter, IResultPrinter is senseless.  I want to know about events, not strings.
  * In that case,
```python
            if p.name == name:
                p.setOptions(tbformat=self['tbformat'],
                             realtime=self['rterrors'])
                return p.makeReporter
```
may trivially be replaced with
```python
            if p.name == name:
                return lambda: p.makeReporter(tbformat=self['tbformat'],
                                              realtime=self['rterrors'])
```
  * Sorry, I was unclear.  addError and addFailure take the same types as each other.  But, they both take either a Failure or a three-tuple: that's the part I was complaining about.
  * I expect something is possible wrt IReporter->IResult compatibility.  If you assign this back to me at some point I'll try to make a concrete suggestion.

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)<a name="note_18"></a>|@jml set owner to @exarkun|
|-|-|

Filed [#2411](https://github.com/twisted/twisted/issues/2411) re `addError` and `addFailure`

Ready for re-review.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_19"></a>|@exarkun set owner to @jml|
|-|-|

In the docstring for twisted.trial.test.test_tests.TestCleanup.test_leftoverSockets/test_leftoverPendingCalls, is it still appropriate to call the things being tested for "cleanup errors"?

In twisted.trial.test.test_runner.TestRunner.setUp, the nested function getPlugins used to assert something about iface, but no longer does.  Is this an intentional change?  Is this functionality tested elsewhere now?

These are pretty minor issues, clearly.  I think the only major outstanding issue is the question of IReporter/IResult.  Here's my suggestion for compatibility:  put IReporter back, just as it was; continue to load IReporter plugins; issue a deprecation either for each one found, or for each class which implements it (harder, since it's just a module attribute, I think foom can suggest an implementation technique for this).  Since, if I am not missing anything, IReporter is basically just an aggregation of IResult and IResultPrinter, except with some things missing (which were missing before), it should be usable in each role.  Register an adapter from IReporter to IResultPrinter that returns the same object, and the rest of the code may just work.  Of course, since the interface was underspecified before, this is still somewhat sketchy, but I think this branch mostly removes method calls onto this object, so I think this will actually allow existing code to continue to work.

I know it won't be fun, but the backwards compatibility layer should also have some minimal test coverage as well.

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)|@jml set status to `assigned`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)<a name="note_21"></a>|@jml commented|
|-|-|

 * Fixed the docstrings in test_tests
 * That assert wasn't testing functionality. It's testing that the usage object passes the right parameters to the `getPlugins` function. We don't want to be testing that directly, as we only really care that the call to `getPlugins` returns the right things. The details of its parameters shouldn't be tested.
 * Working on restoring IReporter and deprecating it properly.

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)<a name="note_22"></a>|@jml set owner to @exarkun<br>@jml set status to `new`|
|-|-|

Ready for review in ireporter-2164

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_23"></a>|@exarkun set owner to @jml|
|-|-|

Some pyflakes suggestions:

```
twisted/scripts/trial.py:11: 'reflect' imported but unused
twisted/scripts/trial.py:14: 'reporter' imported but unused
twisted/plugins/twisted_trial.py:2: 'implements' imported but unused
twisted/trial/test/test_output.py:4: 'sys' imported but unused
twisted/trial/test/test_tests.py:3: 'log' imported but unused
twisted/trial/test/test_reporter.py:8: 'suppressWarnings' imported but unused
twisted/trial/test/test_reporter.py:10: 'util' imported but unused
twisted/trial/test/test_reporter.py:68: redefinition of unused 'failure' from line 9
twisted/trial/test/test_reporter.py:78: redefinition of unused 'failure' from line 9
twisted/trial/test/test_runner.py:17: 'twisted_trial' imported but unused
twisted/trial/runner.py:675: 'readline' imported but unused
twisted/trial/reporter.py:15: 'warnings' imported but unused
twisted/trial/reporter.py:17: 'log' imported but unused
```

test_deferred.TestTimeout.test_callbackReturnsNonCallingDeferred has a change the motivation for which is not immediately obvious and has no docstring (and it is the kind of test that really deserves a docstring a lot).

test_reporter.TestReporterPlugin.test_settings doesn't make any assertions about stream.  Seems like it should.

Also in test_runner, TestRunner.test_runner_can_get_reporter isn't named with the right convention and is missing a docstring and has changes.  The local "my_runner" is also misnamed.

test_scripts is missing a copyright statement and a module docstring.  also please adjust the docstrings in that module which are like this:

```
"""foo"""
```

to be like this:

```
"""
foo
"""
```

in test_tests, why do TestCleanup.test_leftoverSockets and TestCleanup.test_leftoverPendingCalls create their suites differently?

also in test_tests, the first two test methods on FixtureTest assert something about the type of error which occurred, but the last two don't.  Shouldn't they all check the exception type?

in test_utils, the use of the word "raise" with respect to warnings is a bit confusing (warnings actually /are/ ```raise```d when the module is configured specially, eg with "python -Werror").  "emit" or "issue" or "log" would be better.

Several trial tests fail:

```
===============================================================================
[ERROR]: twisted.trial.test.test_runner.TestMalformedMethod.test_decorated

Traceback (most recent call last):
  File "/home/exarkun/Projects/Twisted/trunk/twisted/trial/test/test_runner.py", line 502, in test_decorated
    self._test('test_spam')
  File "/home/exarkun/Projects/Twisted/trunk/twisted/trial/test/test_runner.py", line 479, in _test
    trialRunner = runner.TrialRunner(reporter.Reporter, stream=stream)
exceptions.TypeError: __init__() got an unexpected keyword argument 'stream'
===============================================================================
[ERROR]: twisted.trial.test.test_runner.TestMalformedMethod.test_extraArg

Traceback (most recent call last):
  File "/home/exarkun/Projects/Twisted/trunk/twisted/trial/test/test_runner.py", line 490, in test_extraArg
    self._test('test_foo')
  File "/home/exarkun/Projects/Twisted/trunk/twisted/trial/test/test_runner.py", line 479, in _test
    trialRunner = runner.TrialRunner(reporter.Reporter, stream=stream)
exceptions.TypeError: __init__() got an unexpected keyword argument 'stream'
===============================================================================
[ERROR]: twisted.trial.test.test_runner.TestMalformedMethod.test_noArg

Traceback (most recent call last):
  File "/home/exarkun/Projects/Twisted/trunk/twisted/trial/test/test_runner.py", line 496, in test_noArg
    self._test('test_bar')
  File "/home/exarkun/Projects/Twisted/trunk/twisted/trial/test/test_runner.py", line 479, in _test
    trialRunner = runner.TrialRunner(reporter.Reporter, stream=stream)
exceptions.TypeError: __init__() got an unexpected keyword argument 'stream'
-------------------------------------------------------------------------------
```

There's also a trivial conflict with trunk, so it'd be good to merge the branch forward.

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)<a name="note_24"></a>|@jml commented|
|-|-|

All changes applied. 

re "why do they create their suites differently?". The short answer is historical reasons.

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)|@jml set owner to @exarkun|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_26"></a>|@exarkun set owner to @jml|
|-|-|

still conflicts with trunk

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)<a name="note_27"></a>|@jml commented|
|-|-|

You are so wrong. So terribly wrong.

It doesn't _still_ conflict with trunk. This is a whole new set of conflicts from another branch I  landed.

Twisted prevails.

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)<a name="note_28"></a>|@jml set owner to @exarkun|
|-|-|

Ready for review in ireporter-2164-3

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_29"></a>|@exarkun set owner to @jml|
|-|-|

 * twisted/trial/itrial.py
   * docstring belongs below copyright statement
   * no test-case-name (should be twisted.trial.test)
   * maintainer is more commonly put in the module docstring
 * twisted/plugins/twisted_trial.py
   * missing test-case-name/copyright
   * missing module docstring
 * twisted/scripts/trial.py
   * no test coverage for _zshReporterAction
   * no test coverage for opt_help_reporters
   * no test coverage for opt_tbformat
 * twisted/trial/reporter.py
   * no test coverage for the code suite guarded by ```if options is None``` in ```TrialReporterPlugin.makeReporter```
 * twisted/trial/runner.py
   * I prefer not to change code to satisfy buggy utilities: I don't think you need to add the no-op ```readline``` statement to ```_getDebugger```.  A comment explaining to a human that the readline module is imported only for its side-effects would be a nice improvement, though.

The branch also has various failures across all buildslaves.

The parameter list for ```IReporterPlugin.makeReporter``` still seems suboptimal.  A blob of values makes for poor documentability and tends towards incoherence.  Plus, reporters still can't accept any options not presented by trial itself on the command line.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_30"></a>|@glyph commented|
|-|-|

In case anybody is looking into fixing this, the error I get when I run the tests is:
```
[ERROR]: twisted.mail.test.test_imap.Timeout.testLongFetchDoesntTimeout

Traceback (most recent call last):
  File "/home/glyph/Projects/Twisted/trunk/twisted/trial/unittest.py", line 702, in _cleanUp
    util._Janitor().postCaseCleanup()
  File "/home/glyph/Projects/Twisted/trunk/twisted/trial/util.py", line 64, in postCaseCleanup
    return self._dispatch('cleanPending')
  File "/home/glyph/Projects/Twisted/trunk/twisted/trial/util.py", line 72, in _dispatch
    getattr(self, "do_%s" % attr)()
  File "/home/glyph/Projects/Twisted/trunk/twisted/internet/utils.py", line 164, in warningSuppressingWrapper
    return runWithWarningsSuppressed(suppressedWarnings, f, *a, **kw)
  File "/home/glyph/Projects/Twisted/trunk/twisted/internet/utils.py", line 144, in runWithWarningsSuppressed
    result = f(*a, **kw)
  File "/home/glyph/Projects/Twisted/trunk/twisted/trial/util.py", line 91, in do_cleanPending
    raise PendingTimedCallsError(s)
twisted.trial.util.PendingTimedCallsError: pendingTimedCalls still pending (consider setting twisted.internet.base.DelayedCall.debug = True): <DelayedCall 268990732 [1799.99956107s] called=0 cancelled=0 SimpleServer.__timedOut()>
```

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_31"></a>|@glyph commented|
|-|-|

OK, so upon further investigation, the issue is reentrancy.  I don't understand how this works in trunk, and I can't understand why the branch broke it, but the gist of the broken behavior is this:

  * some timed call invokes ```__cbFetch```
  * ```__cbFetch``` calls ```sendPositiveResponse```
    * that invokes ```transport.write```
      * which invokes loopback's ```_LoopbackQueue.put```
        * which continues the asynchronous loop
          * which calls ```connectionLost``` on everybody
            * which cancels the timeout
    * then all of those pop back up the stack, and suddenly we're re-instating the callback inside ```__cbFetch```.  the timeout cancellation in ```connectionLost``` has already been invoked, but it gets re-set.  voila, the reactor is dirty.

The real bug here is that ```_loopbackAsync``` isn't, and its queue put can't do anything to be correct except to pop the stack with a ```callLater```.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_32"></a>|@exarkun commented|
|-|-|

Thanks for looking into that.  Another point worth noting is that the PendingTimeCallsError _is_ present in trunk; however, it does not cause the suite to fail.  I think the change the branch made was to convert this from a "cleanup error" to an actual error (if this is the case, I don't understand how, and clearly this wasn't the purpose of the branch).

There is also a less subtle failure due to the fact that trial now imports gtkreactor, which is not always possible.

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)<a name="note_34"></a>|@jml commented|
|-|-|

(In [21946]) Branching to 'ireporter-2164-5'

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)<a name="note_35"></a>|@jml commented|
|-|-|

Next step is for me to review the diff, review the ticket, produce a summary of both and then figure out what to do with this code.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_37"></a>|@exarkun commented|
|-|-|

(In [25433]) Branching to 'ireporter-2164-6'

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_38"></a>|@exarkun set owner to @exarkun|
|-|-|

Merged forward to resolve a lot of new conflicts with trunk.  I notice there's some code which is redundant, given additions to trunk since this was started, so I'm going to try to get rid of that stuff.  Then if I can I'll try to make some comments about the state of the code.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_39"></a>|@exarkun commented|
|-|-|

A note of some functional issues the branch has, just so they're not forgotten:

  1. twisted.trial.test.test_script messes up stdout in the branch but not in trunk
  1. warnings aren't properly captured by a number of the tests for trial's warning interactions, so warnings which are expected to be generated during tests go to stdout
  1. legitimate warnings emitted more than once during the course of a single test method are written to stdout more than once; in trunk (and the intent is that) they are written only once.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
