### ISSUE TITLE
twisted.names.client.getHostByName and friends insufficently documented.

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#2181]
|[<img alt="jerub's avatar" src="https://avatars.githubusercontent.com/u/315461?s=50" width="50" height="50">](https://github.com/jerub)| @jerub reported|
|-|-|
|Trac ID|trac#2181|
|Type|defect|
|Created|2006-10-19 23:05:05Z|

twisted.names.client.getHostByName seems to be the correct way to look up a DNS name asynchronously. getHostByName, lookupAddress, lookupNameservers, etc (22 names) are not mentioned in the module docstring, and is inserted into the namespace using this line of code:
```
for method in common.typeToMethod.values():
    globals()[method] = _makeLookup(method)
del method

getHostByName = _makeLookup('getHostByName')
```

I suggest that the module docstring should refer to every method that will be inserted into the namespace explicitly, in such a way that it appears in the API reference.

<details><summary>Searchable metadata</summary>

```
trac-id__2181 2181
type__defect defect
reporter__jerub jerub
priority__highest highest
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__names names
keywords__ 
time__1161299105000000 1161299105000000
changetime__1167401592000000 1167401592000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="jerub's avatar" src="https://avatars.githubusercontent.com/u/315461?s=50" width="50" height="50">](https://github.com/jerub)<a name="note_1"></a>|@jerub set owner to @jerub<br>@jerub set status to `assigned`|
|-|-|

This example is also broken: http://twistedmatrix.com/projects/names/documentation/examples/gethostbyname.py

**Comment by twisted-trac** [comment]
|[<img alt="jerub's avatar" src="https://avatars.githubusercontent.com/u/315461?s=50" width="50" height="50">](https://github.com/jerub)<a name="note_2"></a>|@jerub commented|
|-|-|

Available for review in document-getHostByName-2181

I have explicitly defined every single one of these methods. It took me a long time. I then used pydoctor to see how wonderful this looks in the api docs, and I was pleased.

The examples are also repaired to work with current twisted.client.names.

**Comment by twisted-trac** [comment]
|[<img alt="jerub's avatar" src="https://avatars.githubusercontent.com/u/315461?s=50" width="50" height="50">](https://github.com/jerub)|@jerub removed owner<br>@jerub set status to `new`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)<a name="note_4"></a>|@jml set owner to @jerub|
|-|-|

 * Docstring for `createResolver` says `@param servers` for all its parameters.
 * Watch for 80 cols in that docstring
 * Docstring for `getHostByName` says `@type effort` for all its parameters.
 * `./doc/names/examples/gethostbyname.py google.com` fails with:
```
Traceback (most recent call last):
  File "./doc/names/examples/gethostbyname.py", line 15, in ?
    d = client.getHostByName(sys.argv[1])
IndexError: list index out of range
(jml@graywand ~/Code/Twisted/trunk) ./doc/names/examples/gethostbyname.py google.com
Traceback (most recent call last):
  File "./doc/names/examples/gethostbyname.py", line 15, in ?
    d = client.getHostByName(sys.argv[1])
  File "/Users/jml/Code/Twisted/trunk/twisted/names/client.py", line 488, in getHostByName
    return getResolver().getHostByName(name, timeout, effort)
  File "/Users/jml/Code/Twisted/trunk/twisted/names/client.py", line 464, in getResolver
    theResolver = _createResolver()
NameError: global name '_createResolver' is not defined
```
 * Docstrings for test methods in `test_client`
 * The motivation for this change is not clear to me:
```
-    def __getstate__(self):
+    def _getstate__(self):
```

**Comment by twisted-trac** [comment]
|[<img alt="jerub's avatar" src="https://avatars.githubusercontent.com/u/315461?s=50" width="50" height="50">](https://github.com/jerub)<a name="note_5"></a>|@jerub set owner to @jml|
|-|-|

Okay, all those should be addressed now.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_6"></a>|@exarkun set owner to @jerub|
|-|-|

The timeout parameter to all of the lookup function is documented incorrectly.

I think using createResolver() is preferred to any other means of finding an object to call lookup methods on.  I'd like to see this reflected in the documentation somehow.  At least, the lookup methods on ResolverBase should have as much information as the free functions in the client module.

**Comment by twisted-trac** [comment]
|[<img alt="jerub's avatar" src="https://avatars.githubusercontent.com/u/315461?s=50" width="50" height="50">](https://github.com/jerub)<a name="note_7"></a>|@jerub set owner to @jml|
|-|-|

Okay, timeout docstring updated to be better, ResolverBase now has all the same docstrings.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_8"></a>|@exarkun commented|
|-|-|

Erm the timeout parameter is still documented incorrectly.  It isn't an int, it's a sequence of ints.

Also I would recommend using @see rather than including copies of all the docstrings in two places.

**Comment by twisted-trac** [comment]
|[<img alt="jerub's avatar" src="https://avatars.githubusercontent.com/u/315461?s=50" width="50" height="50">](https://github.com/jerub)<a name="note_9"></a>|@jerub commented|
|-|-|

[#2336](https://github.com/twisted/twisted/issues/2336) has been created because of the issue of the timeouts. It seems sometimes a sequence of ints is expected, sometimes an int. I think that's out of scope for this ticket, so I've just documented everything to take a sequence of ints.

I've done the @see thing.

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)<a name="note_10"></a>|@jml set owner to @jerub|
|-|-|

Where did test_client go? Otherwise, looks good.

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)<a name="note_11"></a>|@jml commented|
|-|-|

Found it. Incorrect docstring fixed. Please merge.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_12"></a>|@exarkun set status to `closed`|
|-|-|

Resolved by r19144

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
