### ISSUE TITLE
Documentation codelistings need updating and tests

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#2205]
|[<img alt="jerub's avatar" src="https://avatars.githubusercontent.com/u/315461?s=50" width="50" height="50">](https://github.com/jerub)| @jerub reported|
|-|-|
|Trac ID|trac#2205|
|Type|enhancement|
|Created|2006-10-31 23:20:49Z|
|Branch|https://github.com/twisted/twisted/tree/simple-app-2205-2|

The code used in .tac files is too complicated. I'd like to be able to create an application object with a minimum of verbage.

What we have:
```python
application = Application('myapp', uid=1, gid=1)
serviceCollection = IServiceCollection(application)
service1.setServiceParent(serviceCollection)
service2.setServiceParent(serviceCollection)
``` 

What I'd like
```python
application = Application('myapp', uid=1, gid=1, servies=[service1, service2])
```

The tutorials and documentation would have to be updated to include this new form, and probably to continue to acknowledge how to do both ways.

<details><summary>Searchable metadata</summary>

```
trac-id__2205 2205
type__enhancement enhancement
reporter__jerub jerub
priority__normal normal
milestone__ 
branch__branches_simple_app_2205_2 branches/simple-app-2205-2
branch_author__thijs__jerub thijs, jerub
status__new new
resolution__None None
component__core core
keywords__documentation__finger__doctests documentation, finger, doctests
time__1162336849000000 1162336849000000
changetime__1295966841000000 1295966841000000
version__None None
owner__ 
cc__thijs cc__exarkun cc__kehander1 cc__binjured
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_1"></a>|@glyph commented|
|-|-|

You asked for my feedback, and my feedback is that I think this is a good idea (although definitely high enough priority for me to work on it...)

I think that this might apply to other ```twisted.application``` stuff as well, not just ```Application```.  Personally, I can never remember how to create a service without going and reading the code, and that's a very bad sign for other folks...

**Comment by twisted-trac** [comment]
|[<img alt="jerub's avatar" src="https://avatars.githubusercontent.com/u/315461?s=50" width="50" height="50">](https://github.com/jerub)<a name="note_2"></a>|@jerub set status to `assigned`|
|-|-|

Branch is simple-app-2205. Tests and code have been updated, children=[] is the kwarg as per a suggestion on irc.

Still need to update the docs.

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_4"></a>|@thijstriemstra set owner to @thijstriemstra<br>@thijstriemstra set status to `new`|
|-|-|

I can go through those docs.

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_5"></a>|@thijstriemstra removed owner|
|-|-|

Perhaps someone can review jerub's branch as well, putting it up for review.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_6"></a>|@exarkun set owner to @thijstriemstra|
|-|-|

This conflicts horribly with trunk.  The conflicts need to be resolved and the branch merged forward.

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_7"></a>|@thijstriemstra commented|
|-|-|

(In [25314]) Branching to 'simple-app-2205-2'

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_8"></a>|@thijstriemstra removed owner|
|-|-|

Replying to [exarkun](#note_6):
> This conflicts horribly with trunk.  The conflicts need to be resolved and the branch merged forward.

Done, see r25315

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_9"></a>|@thijstriemstra commented|
|-|-|

Forgot to add the tests, included in r25319

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_10"></a>|@therve set owner to @thijstriemstra|
|-|-|

Most of the tests are failing with this error:

```
[ERROR]: twisted.test.test_fingertutorial.Finger21TestCase.testFingerFactory

Traceback (most recent call last):
  File "/home/therve/projects/Twisted/trunk/twisted/test/test_fingertutorial.py", line 264, in setUp
    super(Finger19TestCase, self).setUp()
  File "/home/therve/projects/Twisted/trunk/twisted/test/test_fingertutorial.py", line 36, in setUp
    self.finger = __import__(self.module)
exceptions.ImportError: No module named finger21
-------------------------------------------------------------------------------
Ran 68 tests in 0.496s

FAILED (errors=47, successes=21)
```

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_11"></a>|@thijstriemstra commented|
|-|-|

kehander1 has been working on splitting up the finger example into libraries and the tests here should be made up to date for that.

**Comment by twisted-trac** [comment]
|<img alt="binjured's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_12"></a>|binjured commented|
|-|-|

kehander1 has _stopped_ working on that (as far as I can tell) which takes this ticket to limbo with it. There seem to be a number of circular dependencies for the Finger tutorial to make any progress towards "maybe less awful".

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
