### ISSUE TITLE
t.p.usage documents multicharacter shortcuts for subcommands but does not support them.

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#2231]
|[<img alt="dreid's avatar" src="https://avatars.githubusercontent.com/u/48695?s=50" width="50" height="50">](https://github.com/dreid)| @dreid reported|
|-|-|
|Trac ID|trac#2231|
|Type|defect|
|Created|2006-11-14 19:38:01Z|

From http://twistedmatrix.com/documents/current/api/twisted.python.usage.Options.html:

''subCommands is a list of 4-tuples of (command name, command shortcut, parser class, documentation). If the first non-option argument found is one of the given command names, an instance of the given parser class is instantiated and given the remainder of the arguments to parse and self.opts[command] is set to the command name. For example:

| subCommands = [ | ['inquisition', 'inquest', InquisitionOptions, 'Perform an inquisition'], | ['holyquest', 'quest', HolyQuestOptions, 'Embark upon a holy quest'] | ]''

However actually using a multicharacter command shortcut causes a typeerror to be raised when issuing --help.

```
dreid:~> python projects/bs.py --help
Traceback (most recent call last):
  File "projects/bs.py", line 12, in ?
    Options().parseOptions()
  File "/private/Network/Servers/harris/Volumes/veedu/dreid/projects/Twisted/trunk/twisted/python/usage.py", line 177, in parseOptions
    self.__dispatch[optMangled](optMangled, arg)
  File "/private/Network/Servers/harris/Volumes/veedu/dreid/projects/Twisted/trunk/twisted/python/usage.py", line 337, in <lambda>
    fn = lambda name, value=None, m=method: m()
  File "/private/Network/Servers/harris/Volumes/veedu/dreid/projects/Twisted/trunk/twisted/python/usage.py", line 141, in opt_help
    print self.__str__()
  File "/private/Network/Servers/harris/Volumes/veedu/dreid/projects/Twisted/trunk/twisted/python/usage.py", line 373, in __str__
    return self.getSynopsis() + '\n' + self.getUsage(width=None)
  File "/private/Network/Servers/harris/Volumes/veedu/dreid/projects/Twisted/trunk/twisted/python/usage.py", line 415, in getUsage
    chunks = docMakeChunks(cmdDicts, width)
  File "/private/Network/Servers/harris/Volumes/veedu/dreid/projects/Twisted/trunk/twisted/python/usage.py", line 517, in docMakeChunks
    short = "-%c" % (opt['short'],)
TypeError: %c requires int or char
zsh: exit 1     python projects/bs.py --help
```

Attachments:

* [bs.py](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/07c/07cef16b46a72f33f6a597a473845b1e89e0278e/932928e50a853c3ff73d9035bc309cf57d020c13.py) (229 bytes) - added by dreid on 2006-11-14 19:38:58Z - bad subcommands example

<details><summary>Searchable metadata</summary>

```
trac-id__2231 2231
type__defect defect
reporter__dreid dreid
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__duplicate duplicate
component__core core
keywords__ 
time__1163533081000000 1163533081000000
changetime__1163533235000000 1163533235000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="dreid's avatar" src="https://avatars.githubusercontent.com/u/48695?s=50" width="50" height="50">](https://github.com/dreid)|@dreid set status to `closed`|
|-|-|

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
