### ISSUE TITLE
Trial hangs if callLater is replaced

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#2249]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)| @jml reported|
|-|-|
|Trac ID|trac#2249|
|Type|defect|
|Created|2006-11-30 00:51:24Z|

```python
from twisted.internet import reactor
from twisted.internet.task import Clock
 
from twisted.trial.unittest import TestCase
 
class X(TestCase):
    def setUp(self):
        reactor.callLater = Clock().callLater
 
 
    def test_foo(self):
        pass
```

```
exarkun@charm:~$ trial foo.py
Running 1 tests.
foo
  X
    test_foo ...                                                           [OK]
^CTraceback (most recent call last):
  File "/home/exarkun/Projects/Twisted/trunk/bin/trial", line 24, in ?
    run()
  File "/home/exarkun/Projects/Twisted/trunk/twisted/scripts/trial.py", line 341, in run
    test_result = trialRunner.run(suite)
  File "/home/exarkun/Projects/Twisted/trunk/twisted/trial/runner.py", line 786, in run
    suite.run(result)
  File "/home/exarkun/Projects/Twisted/trunk/twisted/trial/runner.py", line 281, in run
    self._bail()
  File "/home/exarkun/Projects/Twisted/trunk/twisted/trial/runner.py", line 275, in _bail
    unittest.TestCase('mktemp')._wait(d)
  File "/home/exarkun/Projects/Twisted/trunk/twisted/trial/unittest.py", line 891, in _wait
    if results or self._timedOut: #defined in run() and _run()
AttributeError: 'TestCase' object has no attribute '_timedOut'
exarkun@charm:~$
```

<details><summary>Searchable metadata</summary>

```
trac-id__2249 2249
type__defect defect
reporter__jml jml
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__trial trial
keywords__ 
time__1164847884000000 1164847884000000
changetime__1255797056000000 1255797056000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|<img alt="kelly's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_1"></a>|kelly commented|
|-|-|


Possibly fixed by r20909.  At least the behaviour exists at r20908 but not at r20909.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
