### ISSUE TITLE
twisted.conch.insults.insults.ITerminalTransport.setScrollRegion missing

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#2358]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#2358|
|Type|defect|
|Created|2007-01-06 05:30:32Z|
|Branch|https://github.com/twisted/twisted/tree/terminal-transport-2358|

The implementation provides it but the interface doesn't talk about it.  Ditto for resetScrollRegion.

The implementation looks inconsistent though, it passes through the 1-based indexing instead of providing 0-based indexing like other methods do.

<details><summary>Searchable metadata</summary>

```
trac-id__2358 2358
type__defect defect
reporter__exarkun exarkun
priority__normal normal
milestone__ 
branch__branches_terminal_transport_2358 branches/terminal-transport-2358
branch_author__jkakar jkakar
status__new new
resolution__None None
component__conch conch
keywords__insults insults
time__1168061432000000 1168061432000000
changetime__1285946983000000 1285946983000000
version__None None
owner__jkakar jkakar

```
</details>

**Comment by twisted-trac** [comment]
|<img alt="jkakar's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|jkakar set owner to jkakar|
|-|-|

**Comment by twisted-trac** [comment]
|<img alt="jkakar's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_2"></a>|jkakar commented|
|-|-|

(In [28780]) Branching to 'terminal-transport-2358'

**Comment by twisted-trac** [comment]
|<img alt="jkakar's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_3"></a>|jkakar commented|
|-|-|

The ticket description mentions problems with the implementation of
the {set,reset}ScrollRegion methods not providing 0-based indexing.
I can fix this, but what about backwards compatibility?  Is this
just a bug that needs to be addressed, despite the fact that
existing code depending on the 1-based indexing will break?

No tests broke when I changed the indexing which was surprising.  I
do seem to have two errors both in my branch (with or without the
change) and in trunk, with 'trial twisted.conch.test':

===============================================================================
[ERROR]: twisted.conch.test.test_cftp.TestOurServerSftpClient.test_extendedAttributes

Traceback (most recent call last):
  File "/home/jkakar/src/projects/twisted/trunk/twisted/internet/selectreactor.py", line 146, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "/home/jkakar/src/projects/twisted/trunk/twisted/internet/tcp.py", line 460, in doRead
    return self.protocol.dataReceived(data)
  File "/home/jkakar/src/projects/twisted/trunk/twisted/conch/ssh/transport.py", line 313, in dataReceived
    self.dispatchMessage(messageNum, packet[1:])
  File "/home/jkakar/src/projects/twisted/trunk/twisted/conch/ssh/transport.py", line 328, in dispatchMessage
    f(payload)
  File "/home/jkakar/src/projects/twisted/trunk/twisted/conch/ssh/transport.py", line 421, in ssh_DISCONNECT
    self.receiveError(reasonCode, description)
  File "/home/jkakar/src/projects/twisted/trunk/twisted/conch/test/test_ssh.py", line 330, in receiveError
    (self, reasonCode, desc))
  File "/home/jkakar/src/projects/twisted/trunk/twisted/trial/unittest.py", line 1575, in _
    return getattr(_inst, name)(*args, **kwargs)
twisted.trial.unittest.FailTest: got disconnect for <twisted.conch.test.test_ssh.ConchTestServer instance at 0xaa3a82c>: reason 11, desc: disconnected by user
===============================================================================
[ERROR]: twisted.conch.test.test_conch.OpenSSHClientTestCase.test_exec

Traceback (most recent call last):
  File "/home/jkakar/src/projects/twisted/trunk/twisted/internet/selectreactor.py", line 146, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "/home/jkakar/src/projects/twisted/trunk/twisted/internet/tcp.py", line 460, in doRead
    return self.protocol.dataReceived(data)
  File "/home/jkakar/src/projects/twisted/trunk/twisted/conch/ssh/transport.py", line 313, in dataReceived
    self.dispatchMessage(messageNum, packet[1:])
  File "/home/jkakar/src/projects/twisted/trunk/twisted/conch/ssh/transport.py", line 328, in dispatchMessage
    f(payload)
  File "/home/jkakar/src/projects/twisted/trunk/twisted/conch/ssh/transport.py", line 421, in ssh_DISCONNECT
    self.receiveError(reasonCode, description)
  File "/home/jkakar/src/projects/twisted/trunk/twisted/conch/test/test_ssh.py", line 330, in receiveError
    (self, reasonCode, desc))
  File "/home/jkakar/src/projects/twisted/trunk/twisted/trial/unittest.py", line 1575, in _
    return getattr(_inst, name)(*args, **kwargs)
twisted.trial.unittest.FailTest: got disconnect for <twisted.conch.test.test_ssh.ConchTestServer instance at 0xa9bddcc>: reason 11, desc: disconnected by user
-------------------------------------------------------------------------------

I don't have any skips in the test output, so I assume I have all
the right dependencies in place.  I'm running the tests with Python
2.6.5 on Ubuntu (lucid).

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_4"></a>|@exarkun commented|
|-|-|

One approach would be to add new methods with 0-based indexing, add them to the interface, and eventually deprecate the old ones.
