### ISSUE TITLE
twisted.test.test_failure.FailureTestCase.testBrokenStr breaks trial in debug mode

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#2367]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#2367|
|Type|defect|
|Created|2007-01-07 17:37:16Z|
|Branch|https://github.com/twisted/twisted/tree/fix-broken-str-2376|

```
exarkun@kunai:/tmp$ trial -b twisted.test.test_failure
Running 9 tests.
> /home/exarkun/Projects/Twisted/trunk/twisted/trial/runner.py(284)run()
-> try:
(Pdb) c
twisted.test.test_failure
  FailureTestCase
    testBrokenStr ... Traceback (most recent call last):
  File "/home/exarkun/Projects/Twisted/trunk/bin/trial", line 24, in ?
    run()
  File "/home/exarkun/Projects/Twisted/trunk/twisted/scripts/trial.py", line 345, in run
    test_result = trialRunner.run(suite)
  File "/home/exarkun/Projects/Twisted/trunk/twisted/trial/runner.py", line 787, in run
    debugger.runcall(suite.run, result)
  File "/usr/lib/python2.4/bdb.py", line 404, in runcall
    res = func(*args, **kwds)
  File "/home/exarkun/Projects/Twisted/trunk/twisted/trial/runner.py", line 285, in run
    TestSuite.run(self, result)
  File "/home/exarkun/Projects/Twisted/trunk/twisted/trial/runner.py", line 149, in run
    test(result)
  File "/home/exarkun/Projects/Twisted/trunk/twisted/trial/runner.py", line 138, in __call__
    return self.run(result)
  File "/home/exarkun/Projects/Twisted/trunk/twisted/trial/runner.py", line 176, in run
    super(LoggedSuite, self).run(result)
  File "/home/exarkun/Projects/Twisted/trunk/twisted/trial/runner.py", line 149, in run
    test(result)
  File "/home/exarkun/Projects/Twisted/trunk/twisted/trial/runner.py", line 138, in __call__
    return self.run(result)
  File "/home/exarkun/Projects/Twisted/trunk/twisted/trial/runner.py", line 149, in run
    test(result)
  File "/home/exarkun/Projects/Twisted/trunk/twisted/trial/runner.py", line 138, in __call__
    return self.run(result)
  File "/home/exarkun/Projects/Twisted/trunk/twisted/trial/runner.py", line 149, in run
    test(result)
  File "/home/exarkun/Projects/Twisted/trunk/twisted/trial/runner.py", line 138, in __call__
    return self.run(result)
  File "/home/exarkun/Projects/Twisted/trunk/twisted/trial/runner.py", line 149, in run
    test(result)
  File "/home/exarkun/Projects/Twisted/trunk/twisted/trial/unittest.py", line 537, in __call__
    return self.run(*args, **kwargs)
  File "/home/exarkun/Projects/Twisted/trunk/twisted/trial/unittest.py", line 761, in run
    d = self.deferSetUp(None, result)
  File "/home/exarkun/Projects/Twisted/trunk/twisted/trial/unittest.py", line 566, in deferSetUp
    errbackArgs=(result,))
  File "/home/exarkun/Projects/Twisted/trunk/twisted/internet/defer.py", line 182, in addCallbacks
    self._runCallbacks()
  File "/home/exarkun/Projects/Twisted/trunk/twisted/internet/defer.py", line 331, in _runCallbacks
    self.result = failure.Failure()
  File "/home/exarkun/Projects/Twisted/trunk/twisted/python/failure.py", line 382, in _debuginit
    print "Jumping into debugger for post-mortem of exception '%s':" % exc[1]
  File "/home/exarkun/Projects/Twisted/trunk/twisted/test/test_failure.py", line 23, in __str__
    raise self
twisted.test.test_failure.BrokenStrexarkun@kunai:/tmp$ 
```

<details><summary>Searchable metadata</summary>

```
trac-id__2367 2367
type__defect defect
reporter__exarkun exarkun
priority__high high
milestone__ 
branch__branches_fix_broken_str_2376 branches/fix-broken-str-2376
branch_author__ 
status__closed closed
resolution__fixed fixed
component__trial trial
keywords__ 
time__1168191436000000 1168191436000000
changetime__1266942066000000 1266942066000000
version__None None
owner__fijal fijal
cc__jesstess
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="fijal's avatar" src="https://avatars.githubusercontent.com/u/85944?s=50" width="50" height="50">](https://github.com/fijal)|@fijal removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="jesstess's avatar" src="https://avatars.githubusercontent.com/u/188336?s=50" width="50" height="50">](https://github.com/jesstess)|@jesstess set owner to @jesstess|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="jesstess's avatar" src="https://avatars.githubusercontent.com/u/188336?s=50" width="50" height="50">](https://github.com/jesstess)<a name="note_4"></a>|@jesstess set owner to @fijal|
|-|-|

Thanks for the branch, fijal. A few comments:

 * ```twisted/python/failure.py``` needs a copyright bump
 * needs a NEWS file
 * even though ```_debuginit``` is private, there's a lot going on and it'd benefit from a docstring.

Relatedly, it looks like ```twisted.test.test_failure.FailureTestCase.testConstructionFails``` fails in debug mode with ```exceptions.ValueError: A valid traceback must be passed if no exception is being handled```, which possibly needs its own ticket.

**Comment by twisted-trac** [comment]
|[<img alt="fijal's avatar" src="https://avatars.githubusercontent.com/u/85944?s=50" width="50" height="50">](https://github.com/fijal)<a name="note_5"></a>|@fijal set status to `closed`|
|-|-|

Closing this, created 4302
