### ISSUE TITLE
twisted.python.versions is broken with svn 1.4

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#2369]
|<img alt="psino's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| psino reported|
|-|-|
|Trac ID|trac#2369|
|Type|defect|
|Created|2007-01-07 20:37:47Z|

Since the format of .svn/entries changed, it cant determine the svn-version number anymore. Making a patch for this should be pretty trivial (if you want me to post a patch for this, just say so ;) ).

Considering it pretty severe (at least for me), as if the project root ever is imported (where version is usually imported) results in a traceback, and a failed import.

Traceback:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in ?
  File "projectname/__init__.py", line 5, in ?
    version = str(version)
  File "/home/psino/Twisted/trunk/twisted/python/versions.py", line 63, in __str__
    return '[%s, version %d.%d.%d%s]' % (
  File "/home/psino/Twisted/trunk/twisted/python/versions.py", line 98, in _formatSVNVersion
    ver = self._getSVNVersion()
  File "/home/psino/Twisted/trunk/twisted/python/versions.py", line 90, in _getSVNVersion
    doc = parse(file(ent)).documentElement
  File "/usr/lib/python2.4/site-packages/_xmlplus/dom/minidom.py", line 1915, in parse
    return expatbuilder.parse(file)
  File "/usr/lib/python2.4/site-packages/_xmlplus/dom/expatbuilder.py", line 930, in parse
    result = builder.parseFile(file)
  File "/usr/lib/python2.4/site-packages/_xmlplus/dom/expatbuilder.py", line 207, in parseFile
    parser.Parse(buffer, 0)
xml.parsers.expat.ExpatError: syntax error: line 1, column 0
```

<details><summary>Searchable metadata</summary>

```
trac-id__2369 2369
type__defect defect
reporter__psino psino
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__duplicate duplicate
component__core core
keywords__ 
time__1168202267000000 1168202267000000
changetime__1168203019000000 1168203019000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="ralphm's avatar" src="https://avatars.githubusercontent.com/u/116741?s=50" width="50" height="50">](https://github.com/ralphm)<a name="note_1"></a>|@ralphm set status to `closed`|
|-|-|

Identical duplicate of [#2368](https://github.com/twisted/twisted/issues/2368), that was a dupe itself.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
