### ISSUE TITLE
RuntimeError: Visit the 'User Configuration' page and enter an email address before you create a ticket.

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#2390]
|<img alt="seletz's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| seletz reported|
|-|-|
|Trac ID|trac#2390|
|Type|enhancement|
|Created|2007-01-11 15:01:35Z|

#### NOTE

The user configuration page allows to enter an email, but tere's no submit button.
Doh.

#### How to Reproduce
While doing a POST operation on `/newticket`, Trac issued an internal error.
{'action': u'create',
 'attachment': u'on',
 'cc': u'',
 'component': u'core',
 'description': u"The module twisted.runner.procmon isn't importable on windows because it imports\r\ntwisted.internet.process directly. twisted.internet.process is not used further,\r\njust an exception class is used from it, which isn't even defined there.\r\n\r\nA simple patch to make the twisted.runner.procmon importable is attached.",
 'keywords': u'',
 'milestone': u'',
 'owner': u'',
 'priority': u'normal',
 'status': u'new',
 'summary': u'twisted.runner.procmon not even importable on windows',
 'type': u'defect'}
#### System Information
| **Python** | 
|------------|-`2.4.3 (#2, Oct  6 2006, 07:52:30) `
`[GCC 4.0.3 (Ubuntu 4.0.3-1ubuntu5)]`
 ||
| **Subversion** | 
|----------------|-`1.4.2` ||
| **SQLite** | 
|------------|-`3.2.8` ||
| **pysqlite** | 
|--------------|-`2.0.5` ||
#### Python Traceback
```
Traceback (most recent call last):
  File "/home/trac/.local/lib/python2.4/site-packages/trac/web/main.py", line 377, in dispatch_request
    dispatcher.dispatch(req)
  File "/home/trac/.local/lib/python2.4/site-packages/trac/web/main.py", line 237, in dispatch
    resp = chosen_handler.process_request(req)
  File "/home/trac/.local/lib/python2.4/site-packages/trac/ticket/web_ui.py", line 105, in process_request
    self._do_create(req, db)
  File "/home/trac/.local/lib/python2.4/site-packages/trac/ticket/web_ui.py", line 165, in _do_create
    ticket.insert(db=db)
  File "/home/trac/.local/lib/python2.4/site-packages/trac/ticket/model.py", line 185, in insert
    listener.ticket_created(self)
  File "build/bdist.linux-i686/egg/ticket_emailer/ticket_emailer.py", line 174, in ticket_created
  File "build/bdist.linux-i686/egg/ticket_emailer/ticket_emailer.py", line 96, in ticketAddedMessage
  File "build/bdist.linux-i686/egg/ticket_emailer/ticket_emailer.py", line 87, in baseMessage
  File "build/bdist.linux-i686/egg/ticket_emailer/ticket_emailer.py", line 53, in ticketVars
RuntimeError: Visit the 'User Configuration' page and enter an email address before you create a ticket.
```
    

<details><summary>Searchable metadata</summary>

```
trac-id__2390 2390
type__enhancement enhancement
reporter__seletz seletz
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__ 
time__1168527695000000 1168527695000000
changetime__1168723683000000 1168723683000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun set status to `closed`|
|-|-|

See [#11097](https://github.com/twisted/twisted/issues/11097)

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
