### ISSUE TITLE
missing attribute causing a traceback when running trial

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#2397]
|<img alt="jacques's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| jacques reported|
|-|-|
|Trac ID|trac#2397|
|Type|defect|
|Created|2007-01-13 17:34:09Z|

trial nevow.test
Traceback (most recent call last):
  File "/usr/local/lib/python2.5/site-packages/twisted/python/usage.py", line 199, in parseOptions
    self.postOptions()
  File "/usr/local/lib/python2.5/site-packages/twisted/scripts/trial.py", line 279, in postOptions
    self['reporter'] = self._loadReporterByName(self['reporter'])
  File "/usr/local/lib/python2.5/site-packages/twisted/scripts/trial.py", line 265, in _loadReporterByName
    for p in plugin.getPlugins(itrial.IReporter):
  File "/usr/local/lib/python2.5/site-packages/twisted/plugin.py", line 227, in getPlugins
    allDropins = getCache(package)
--- <exception caught here> ---
  File "/usr/local/lib/python2.5/site-packages/twisted/plugin.py", line 178, in getCache
    provider = namedAny(module.__name__ + '.' + moduleName)
  File "/usr/local/lib/python2.5/site-packages/twisted/python/reflect.py", line 357, in namedAny
    topLevelPackage = __import__(trialname)
  File "/usr/local/lib/python2.5/site-packages/twisted/plugins/twisted_web2.py", line 7, in <module>
    from twisted.web2.iweb import IResource
  File "/usr/local/lib/python2.5/site-packages/twisted/web2/iweb.py", line 58, in <module>
    class IOldNevowResource(components.Interface):
exceptions.AttributeError: 'module' object has no attribute 'Interface'

<details><summary>Searchable metadata</summary>

```
trac-id__2397 2397
type__defect defect
reporter__jacques jacques
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__duplicate duplicate
component__trial trial
keywords__ 
time__1168709649000000 1168709649000000
changetime__1168712229000000 1168712229000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun set status to `closed`|
|-|-|

Duplicate of [#2398](https://github.com/twisted/twisted/issues/2398)

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
