### ISSUE TITLE
ImportError on Nevow in pydoctor

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#2423]
|<img alt="peterbe's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| peterbe reported|
|-|-|
|Trac ID|trac#2423|
|Type|defect|
|Created|2007-01-25 16:11:32Z|

I took the latest pydoctor (python 2.4.4) and Nevow from SVN and tried to run it but ran into this error:

```
$ pydoctor --add-package=/home/peterbe/Mest --project-name="Mest" --make-html
adding directory /home/peterbe/Mest
analyseImports
38 / 38 modules parsed 
extractDocstrings
37 / 38 modules parsed 153 warnings 
finalStateComputations
Traceback (most recent call last):
  File "/usr/bin/pydoctor", line 5, in ?
    sys.exit(main(sys.argv[1:]))
  File "/usr/lib/python2.4/site-packages/pydoctor/driver.py", line 312, in main
    from pydoctor import nevowhtml
  File "/usr/lib/python2.4/site-packages/pydoctor/nevowhtml/__init__.py", line 3, in ?
    from nevow import loaders, tags, page, flat, inevow
ImportError: cannot import name page

```

<details><summary>Searchable metadata</summary>

```
trac-id__2423 2423
type__defect defect
reporter__peterbe peterbe
priority__high high
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__wontfix wontfix
component__pydoctor pydoctor
keywords__ 
time__1169741492000000 1169741492000000
changetime__1169800638000000 1169800638000000
version__None None
owner__ 
cc__exarkun
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

nevow.page exists in nevow trunk@HEAD:

  http://divmod.org/trac/browser/trunk/Nevow/nevow/page.py

Perhaps an installation of an older version of Nevow is being used, rather than the svn checkout you got?

**Comment by twisted-trac** [comment]
|[<img alt="mwhudson's avatar" src="https://avatars.githubusercontent.com/u/672022?s=50" width="50" height="50">](https://github.com/mwhudson)<a name="note_2"></a>|@mwhudson set status to `closed`|
|-|-|

Or, Nevow from SVN when? :-)

Definitely sounds like you're installation is messed up.  That said, maybe I could remove the dependence on page.py, or just plain include my own version of it or something -- this is coming up increasingly frequently.

Closing, nevertheless.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
