### ISSUE TITLE
TestCase.setUpClass and TestCase.flushLoggedErrors conflict

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#2428]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#2428|
|Type|defect|
|Created|2007-01-30 23:25:38Z|

Demonstration:

```
from twisted.trial.unittest import TestCase

class XTests(TestCase):
    def setUpClass(self):
        pass

    def test_x(self):
        self.flushLoggedErrors()


    def test_y(self):
        self.flushLoggedErrors()
```

Results in this output:

```
Running 2 tests.
test_foo
  XTests
    test_x ...                                                          [ERROR]
    test_y ...                                                             [OK]

===============================================================================
[ERROR]: test_foo.XTests.test_x

Traceback (most recent call last):
  File "/home/exarkun/test_foo.py", line 9, in test_x
    self.flushLoggedErrors()
  File "/home/exarkun/Projects/Twisted/branches/ctrl+\\\\-2371+2123-2/twisted/trial/unittest.py", line 717, in flushLoggedErrors
    return self._observer.flushErrors(*errorTypes)
exceptions.AttributeError: 'XTests' object has no attribute '_observer'
-------------------------------------------------------------------------------
Ran 2 tests in 0.010s
```

<details><summary>Searchable metadata</summary>

```
trac-id__2428 2428
type__defect defect
reporter__exarkun exarkun
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__wontfix wontfix
component__trial trial
keywords__ 
time__1170199538000000 1170199538000000
changetime__1275662518000000 1275662518000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

This is probably related to [#1870](https://github.com/twisted/twisted/issues/1870)

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_2"></a>|@exarkun set status to `closed`|
|-|-|

We've dropped support for `setUpClass`.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
