### ISSUE TITLE
trial dumps on frame error

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#2445]
|<img alt="gardnerpomper's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| gardnerpomper reported|
|-|-|
|Trac ID|trac#2445|
|Type|defect|
|Created|2007-02-08 17:59:44Z|

I run the attached code and I get this stack dump:

```
===============================================================================
[ERROR]: sip_test.sipTest.testRegister

Traceback (most recent call last):
  File "/usr/bin/trial", line 24, in ?
    run()
  File "/usr/lib/python2.3/site-packages/twisted/scripts/trial.py", line 345, in run
    test_result = trialRunner.run(suite)
  File "/usr/lib/python2.3/site-packages/twisted/trial/runner.py", line 798, in run
    result.printErrors()
  File "/usr/lib/python2.3/site-packages/twisted/trial/reporter.py", line 297, in printErrors
    self._formatFailureTraceback)
  File "/usr/lib/python2.3/site-packages/twisted/trial/reporter.py", line 275, in _printResults
    self.write(formatter(*(content[1:])))
  File "/usr/lib/python2.3/site-packages/twisted/trial/reporter.py", line 265, in _formatFailureTraceback
    fail.frames, frames = self._trimFrames(fail.frames), fail.frames
  File "/usr/lib/python2.3/site-packages/twisted/trial/reporter.py", line 255, in _trimFrames
    last = newFrames[-1]
IndexError: list index out of range
```

Attachments:

* [sip_test.py](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/211/21188f1974ee9a6a79de64dee0fc849629de3181/716c35911fe537a8f290801c35a6fd7cf1be1d0e.py) (1770 bytes) - added by gardnerpomper on 2007-02-08 18:00:18Z - very very simple sip unit test

<details><summary>Searchable metadata</summary>

```
trac-id__2445 2445
type__defect defect
reporter__gardnerpomper gardnerpomper
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__duplicate duplicate
component__trial trial
keywords__ 
time__1170957584000000 1170957584000000
changetime__1170957895000000 1170957895000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_2"></a>|@exarkun set status to `closed`|
|-|-|

Looks like a duplicate of [#1901](https://github.com/twisted/twisted/issues/1901) - testRegister in the attachment isn't defined to take ```self```.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
