### ISSUE TITLE
Assertion error on invalid epydoc @type syntax

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#2455]
|<img alt="jdahlin's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| jdahlin reported|
|-|-|
|Trac ID|trac#2455|
|Type|defect|
|Created|2007-02-16 20:18:59Z|

I used trunk of twisted (19650), nevow (11609), pydoctor (39044) and I ran it on stoqlib (svn://svn.async.com.br/stoqlib/trunk) and got the following assertion:

```
$ /mondo/local/pydoctor/bin/pydoctor --add-package=stoqlib --project-name="Stoqlib" --make-html
adding directory stoqlib
analyseImports
183 / 183 modules parsed
extractDocstrings
183 / 183 modules parsed 4 warnings
finalStateComputations
writing html to apidocs using pydoctor.nevowhtml.writer.NevowWriter
starting ModuleIndexPage ... took 0.225080966949 s
starting ClassIndexPage ... took 0.743959188461 s
starting IndexPage ... took 0.0153460502625 s
starting NameIndexPage ... took 1.33525395393 s
starting UndocumentedSummaryPage ... took 0.44473195076 s
written 20 / 673 pages XXX unknown field <Field 'keyword' 'obj_field'>
XXX unknown field <Field 'keyword' 'adapted'>
written 23 / 673 pages XXX unknown field <Field 'dialog' None>
XXX unknown field <Field 'parent' None>
XXX unknown field <Field 'args' None>
XXX unknown field <Field 'kwargs' None>
written 342 / 673 pages XXX unknown field <Field 'header' None>
Traceback (most recent call last):
  File "/mondo/local/pydoctor/bin/pydoctor", line 5, in ?
    sys.exit(main(sys.argv[1:]))
  File "/mondo/local/pydoctor/lib/python2.4/site-packages/pydoctor/driver.py", line 332, in main
    writer.writeIndividualFiles(subjects, options.htmlfunctionpages)
  File "/mondo/local/pydoctor/lib/python2.4/site-packages/pydoctor/nevowhtml/writer.py", line 33, in writeIndividualFiles
    self.writeDocsFor(ob, functionpages=functionpages)
  File "/mondo/local/pydoctor/lib/python2.4/site-packages/pydoctor/nevowhtml/writer.py", line 55, in writeDocsFor
    self.writeDocsFor(o, functionpages)
  File "/mondo/local/pydoctor/lib/python2.4/site-packages/pydoctor/nevowhtml/writer.py", line 55, in writeDocsFor
    self.writeDocsFor(o, functionpages)
  File "/mondo/local/pydoctor/lib/python2.4/site-packages/pydoctor/nevowhtml/writer.py", line 55, in writeDocsFor
    self.writeDocsFor(o, functionpages)
  File "/mondo/local/pydoctor/lib/python2.4/site-packages/pydoctor/nevowhtml/writer.py", line 55, in writeDocsFor
    self.writeDocsFor(o, functionpages)
  File "/mondo/local/pydoctor/lib/python2.4/site-packages/pydoctor/nevowhtml/writer.py", line 52, in writeDocsFor
    self.writeDocsForOne(ob, f)
  File "/mondo/local/pydoctor/lib/python2.4/site-packages/pydoctor/nevowhtml/writer.py", line 77, in writeDocsForOne
    fobj.write(flat.flatten(page))
  File "/mondo/local/pydoctor/lib/python2.4/site-packages/nevow/flat/ten.py", line 128, in flatten
    list(iterflatten(stan, ctx, result.append))
  File "/mondo/local/pydoctor/lib/python2.4/site-packages/nevow/flat/ten.py", line 79, in iterflatten
    rest = [ iter([partialflatten(ctx, stan)]) ]
  File "/mondo/local/pydoctor/lib/python2.4/site-packages/nevow/flat/ten.py", line 61, in partialflatten
    return flattener(obj, context)
  File "/mondo/local/pydoctor/lib/python2.4/site-packages/nevow/flat/flatstan.py", line 253, in RendererSerializer
    return FunctionSerializer(original.rend, context, nocontext)
  File "/mondo/local/pydoctor/lib/python2.4/site-packages/nevow/flat/flatstan.py", line 234, in FunctionSerializer
    result = original(context, data)
  File "/mondo/local/pydoctor/lib/python2.4/site-packages/pydoctor/nevowhtml/pages.py", line 270, in rend
    childlist=self.childlist(tag.onePattern('childlist')),
  File "/mondo/local/pydoctor/lib/python2.4/site-packages/pydoctor/nevowhtml/pages.py", line 235, in childlist
    functionBody=self.functionBody(data))]
  File "/mondo/local/pydoctor/lib/python2.4/site-packages/pydoctor/nevowhtml/pages.py", line 242, in functionBody
    return epydoc2stan.doc2html(data)
  File "/mondo/local/pydoctor/lib/python2.4/site-packages/pydoctor/epydoc2stan.py", line 351, in doc2html
    fh.handle(Field(field, obj))
  File "/mondo/local/pydoctor/lib/python2.4/site-packages/pydoctor/epydoc2stan.py", line 241, in handle
    m(field)
  File "/mondo/local/pydoctor/lib/python2.4/site-packages/pydoctor/epydoc2stan.py", line 187, in handle_type
    self.add_type_info(self.parameter_descs, field)
  File "/mondo/local/pydoctor/lib/python2.4/site-packages/pydoctor/epydoc2stan.py", line 165, in add_type_info
    assert desc_list[-1].type is None
AssertionError
```

Commenting out the offending line makes it work and I have not been able to reproduce even if I add back the assertion strangely enough.
Do I need to clean any state on disk?

<details><summary>Searchable metadata</summary>

```
trac-id__2455 2455
type__defect defect
reporter__jdahlin jdahlin
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__pydoctor pydoctor
keywords__ 
time__1171657139000000 1171657139000000
changetime__1172277287000000 1172277287000000
version__None None
owner__mwh mwh

```
</details>

**Comment by twisted-trac** [comment]
|<img alt="jdahlin's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_2"></a>|jdahlin commented|
|-|-|

Minimal testcase;

```
def error():
    """@type: a
    @type: b"""
```

Yes, invalid syntax but a nicer error should probably be displayed

**Comment by twisted-trac** [comment]
|[<img alt="mwhudson's avatar" src="https://avatars.githubusercontent.com/u/672022?s=50" width="50" height="50">](https://github.com/mwhudson)<a name="note_3"></a>|@mwhudson set status to `closed`|
|-|-|

I fixed this on the plane to PyCon, I think (rev 39349).
