### ISSUE TITLE
missing 'plugins' directory breaks trial

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#2507]
|<img alt="mlum@...'s avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| mlum@... reported|
|-|-|
|Trac ID|trac#2507|
|Type|defect|
|Created|2007-03-06 17:35:27Z|

I'm running 'trial buildbot' buildbot within the buildbot source.  Running 'trial' is breaking in the following:

```
Traceback (most recent call last):
  File "/usr/local/bin/trial", line 24, in <module>
    run()
  File "/usr/local/lib/python2.5/site-packages/twisted/scripts/trial.py", line 341, in run
    suite = _getSuite(config)
  File "/usr/local/lib/python2.5/site-packages/twisted/scripts/trial.py", line 301, in _getSuite
    return loader.loadByNames(config['tests'], recurse)
  File "/usr/local/lib/python2.5/site-packages/twisted/trial/runner.py", line 635, in loadByNames
    for thing in sets.Set(things)]
  File "/usr/local/lib/python2.5/site-packages/twisted/trial/runner.py", line 592, in loadAnything
    return self.loadPackage(thing, recurse)
  File "/usr/local/lib/python2.5/site-packages/twisted/trial/runner.py", line 543, in loadPackage
    pkgobj = modules.getModule(package.__name__)
  File "/usr/local/lib/python2.5/site-packages/twisted/python/modules.py", line 762, in getModule
    return theSystemPath[moduleName]
  File "/usr/local/lib/python2.5/site-packages/twisted/python/modules.py", line 698, in __getitem__
    self._findEntryPathString(moduleObject)),
  File "/usr/local/lib/python2.5/site-packages/twisted/python/modules.py", line 651, in _findEntryPathString
    rval, modobj, pformat(self.importerCache))
AssertionError: '' for <module '__init__' from 'buildbot/__init__.pyc'> not in import cache {'/usr/local/bin': None,
 '/usr/local/bin/twisted/plugins': <imp.NullImporter object at 0x2aaaaab18100>,
```

<details><summary>Searchable metadata</summary>

```
trac-id__2507 2507
type__defect defect
reporter__mlum____ mlum@...
priority__high high
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__worksforme worksforme
component__trial trial
keywords__ 
time__1173202527000000 1173202527000000
changetime__1319820646000000 1319820646000000
version__None None
owner__mlum____ mlum@...
cc__glyph cc__jesstess
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

Reformatting description

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)<a name="note_2"></a>|@jml set owner to @jml|
|-|-|

Best to treat it as a trial bug at first.

mlum, which version of buildbot were you using?

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_3"></a>|@glyph commented|
|-|-|

It's really a bug in t.p.m, so I'm very interested as well.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_4"></a>|@exarkun commented|
|-|-|

This may be related to [#2005](https://github.com/twisted/twisted/issues/2005).

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_5"></a>|@exarkun commented|
|-|-|

Probably [#2489](https://github.com/twisted/twisted/issues/2489) too.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="jesstess's avatar" src="https://avatars.githubusercontent.com/u/188336?s=50" width="50" height="50">](https://github.com/jesstess)<a name="note_7"></a>|@jesstess set owner to mlum@...|
|-|-|

The buildbot tests from the latest release run without issue with Twisted 11.0. Can someone speak up if this issue still exists for them?

**Comment by twisted-trac** [comment]
|[<img alt="jesstess's avatar" src="https://avatars.githubusercontent.com/u/188336?s=50" width="50" height="50">](https://github.com/jesstess)<a name="note_8"></a>|@jesstess set status to `closed`|
|-|-|

 I'm going to go ahead and close this since we can't reproduce on the latest version of Twisted, but mlum if you find that this is still an issue please don't hesitate to re-open the ticket.
