### ISSUE TITLE
TypeError: <lambda>() got multiple values for keyword argument 'asc'

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#2508]
|<img alt="tsal's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| tsal reported|
|-|-|
|Trac ID|trac#2508|
|Type|defect|
|Created|2007-03-06 18:16:06Z|

#### Notes
  
I was attempting to sort tickets by ticket number to get the most recent tickets (I'm interested in seeing if I can help), but Trac did not grok this.  I did this by clicking on the "ticket" header on the table.

#### How to Reproduce
While doing a GET operation on `/report/1`, Trac issued an internal error.
#### System Information
| **Python** | 
|------------|-`2.4.3 (#2, Oct  6 2006, 07:52:30) `
`[GCC 4.0.3 (Ubuntu 4.0.3-1ubuntu5)]`
 ||
| **Subversion** | 
|----------------|-`1.4.2` ||
| **SQLite** | 
|------------|-`3.2.8` ||
| **pysqlite** | 
|--------------|-`2.0.5` ||
#### Python Traceback
```
Traceback (most recent call last):
  File "/home/trac/.local/lib/python2.4/site-packages/trac/web/main.py", line 377, in dispatch_request
    dispatcher.dispatch(req)
  File "/home/trac/.local/lib/python2.4/site-packages/trac/web/main.py", line 248, in dispatch
    content_type)
  File "/home/trac/.local/lib/python2.4/site-packages/trac/web/chrome.py", line 475, in render_template
    return stream.render(method, doctype=doctype)
  File "/home/trac/Projects/genshi/trunk/genshi/core.py", line 146, in render
    output = u''.join(list(generator))
  File "/home/trac/Projects/genshi/trunk/genshi/output.py", line 200, in __call__
    for kind, data, pos in stream:
  File "/home/trac/Projects/genshi/trunk/genshi/output.py", line 486, in __call__
    for kind, data, pos in chain(stream, [(None, None, None)]):
  File "/home/trac/Projects/genshi/trunk/genshi/output.py", line 436, in __call__
    for kind, data, pos in stream:
  File "/home/trac/Projects/genshi/trunk/genshi/core.py", line 207, in _ensure
    for event in stream:
  File "/home/trac/Projects/genshi/trunk/genshi/core.py", line 207, in _ensure
    for event in stream:
  File "/home/trac/.local/lib/python2.4/site-packages/trac/web/chrome.py", line 478, in _strip_accesskeys
    for kind, data, pos in stream:
  File "/home/trac/Projects/genshi/trunk/genshi/filters.py", line 313, in __call__
    for kind, data, pos in stream:
  File "/home/trac/Projects/genshi/trunk/genshi/template.py", line 1145, in _match
    content = list(content)
  File "/home/trac/Projects/genshi/trunk/genshi/filters.py", line 331, in __call__
    for event in template.generate(ctxt):
  File "/home/trac/Projects/genshi/trunk/genshi/filters.py", line 313, in __call__
    for kind, data, pos in stream:
  File "/home/trac/Projects/genshi/trunk/genshi/template.py", line 1120, in _match
    for event in stream:
  File "/home/trac/Projects/genshi/trunk/genshi/template.py", line 920, in _eval
    ctxt):
  File "/home/trac/Projects/genshi/trunk/genshi/template.py", line 930, in _eval
    result = data.evaluate(ctxt)
  File "/home/trac/Projects/genshi/trunk/genshi/eval.py", line 101, in evaluate
    {'data': data})
  File "/home/trac/.local/share/trac/templates/report_view.html", line 39, in <Expression u"href.report(report.id, sort=header.col, asc=not header.asc and "1" or "0", **report.args)">
    <a py:strip="not sorting_enabled"
TypeError: <lambda>() got multiple values for keyword argument 'asc'
```
  

<details><summary>Searchable metadata</summary>

```
trac-id__2508 2508
type__defect defect
reporter__tsal tsal
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__wontfix wontfix
component__release_management release management
keywords__trac trac
time__1173204966000000 1173204966000000
changetime__1173205226000000 1173205226000000
version__None None
owner__ 
cc__tsal@... cc__exarkun
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun set status to `closed`|
|-|-|

Thanks, and sorry for this problem.  This is a trac bug, though.  I don't think we're going to do anything about it.  If you want, it may make sense to file a ticket a <http://trac.edgewall.org/> for this issue.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_2"></a>|@exarkun commented|
|-|-|

Oh, and to respond to the motivation which discovered this bug, you should be able to construct a custom query (use the "Custom Query" link on the reports page) to look at the tickets you want to in the order you want to.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
