### ISSUE TITLE
AttributeError when generating docs with pydoctor

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#2511]
|<img alt="kumar303's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| kumar303 reported|
|-|-|
|Trac ID|trac#2511|
|Type|defect|
|Created|2007-03-08 04:43:17Z|

I'm not really sure what's going on at a glance, but I ran into this while trying to generate docs for my module "fixture."  Here is a way to reproduce it with pydoctor, revision 40054, nevow revision 11752 :

```
$ svn checkout --revision=126 http://fixture.googlecode.com/svn/trunk/ fixture
$ cd fixture
$ mkdir build
$ pydoctor --html-output=build/apidocs --project-name=fixture --project-url=http://code.google.com/p/fixture/ --make-html --add-package=fixture --verbose
```

When I up the verbose flags it drops off just after "starting ClassIndexPage".  Is this is a Nevow issue?  I can't tell for sure.  If so, can you tell me a stable nevow revision that you know of?  thx, Kumar

```
Traceback (most recent call last):
  File "/Users/kumar/py/bin/pydoctor", line 5, in ?
    sys.exit(main(sys.argv[1:]))
  File "/Library/Frameworks/Python.framework/Versions/2.4/lib/python2.4/site-packages/pydoctor/driver.py", line 330, in main
    writer.writeModuleIndex(system)
  File "/Library/Frameworks/Python.framework/Versions/2.4/lib/python2.4/site-packages/pydoctor/nevowhtml/writer.py", line 44, in writeModuleIndex
    f.write(flat.flatten(page))
  File "/Library/Frameworks/Python.framework/Versions/2.4/lib/python2.4/site-packages/nevow/flat/ten.py", line 128, in flatten
    list(iterflatten(stan, ctx, result.append))
  File "/Library/Frameworks/Python.framework/Versions/2.4/lib/python2.4/site-packages/nevow/flat/ten.py", line 83, in iterflatten
    for item in gen:
  File "/Library/Frameworks/Python.framework/Versions/2.4/lib/python2.4/site-packages/nevow/flat/flatstan.py", line 103, in TagSerializer
    yield serialize(toBeRenderedBy, context)
  File "/Library/Frameworks/Python.framework/Versions/2.4/lib/python2.4/site-packages/nevow/flat/ten.py", line 70, in serialize
    return partialflatten(context, obj)
  File "/Library/Frameworks/Python.framework/Versions/2.4/lib/python2.4/site-packages/nevow/flat/ten.py", line 61, in partialflatten
    return flattener(obj, context)
  File "/Library/Frameworks/Python.framework/Versions/2.4/lib/python2.4/site-packages/nevow/flat/flatstan.py", line 262, in DirectiveSerializer
    return serialize(renderer, context)
  File "/Library/Frameworks/Python.framework/Versions/2.4/lib/python2.4/site-packages/nevow/flat/ten.py", line 70, in serialize
    return partialflatten(context, obj)
  File "/Library/Frameworks/Python.framework/Versions/2.4/lib/python2.4/site-packages/nevow/flat/ten.py", line 61, in partialflatten
    return flattener(obj, context)
  File "/Library/Frameworks/Python.framework/Versions/2.4/lib/python2.4/site-packages/nevow/flat/flatstan.py", line 232, in FunctionSerializer
    result = original(renderer, context, data)
  File "/Library/Frameworks/Python.framework/Versions/2.4/lib/python2.4/site-packages/nevow/page.py", line 81, in <lambda>
    return lambda self, ctx, data: renderMethod(IRequest(ctx), ctx.tag)
  File "/Library/Frameworks/Python.framework/Versions/2.4/lib/python2.4/site-packages/pydoctor/nevowhtml/summary.py", line 80, in stuff
    for b, o in findRootClasses(self.system):
  File "/Library/Frameworks/Python.framework/Versions/2.4/lib/python2.4/site-packages/pydoctor/nevowhtml/summary.py", line 46, in findRootClasses
    roots.setdefault(n, []).append(cls)
AttributeError: 'Class' object has no attribute 'append'
```

<details><summary>Searchable metadata</summary>

```
trac-id__2511 2511
type__defect defect
reporter__kumar303 kumar303
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__pydoctor pydoctor
keywords__ 
time__1173328997000000 1173328997000000
changetime__1173357702000000 1173357702000000
version__None None
owner__ 
cc__kumar303 cc__mwh
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="mwhudson's avatar" src="https://avatars.githubusercontent.com/u/672022?s=50" width="50" height="50">](https://github.com/mwhudson)<a name="note_2"></a>|@mwhudson set status to `assigned`|
|-|-|

Um, no, this looks like my fault.

Will dig in a bit.

**Comment by twisted-trac** [comment]
|[<img alt="mwhudson's avatar" src="https://avatars.githubusercontent.com/u/672022?s=50" width="50" height="50">](https://github.com/mwhudson)<a name="note_3"></a>|@mwhudson set status to `closed`|
|-|-|

Fixed in pydoctor revision 40061.  Please open another ticket if you find more problems.

That's some confusing code you've got there!

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
