### ISSUE TITLE
Infinite recursion in udp write() function

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#2513]
|<img alt="p1mrx's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| p1mrx reported|
|-|-|
|Trac ID|trac#2513|
|Type|defect|
|Created|2007-03-09 00:56:50Z|

I received this traceback from a user of my program.  It looks like, in certain cases, twisted can go into an infinite recursive loop inside the UDP write() function.  Maybe it should just fail after a certain number of retries?

```
Traceback (most recent call last):
 File "dtella.py", line 446, in <module>
 File "dtella.py", line 419, in run
 File "twisted\internet\posixbase.pyo", line 220, in run
 File "twisted\internet\posixbase.pyo", line 228, in mainLoop
--- <exception caught here> ---
 File "twisted\internet\base.pyo", line 561, in runUntilCurrent
 File "dtella_core.pyo", line 3294, in cb
 File "dtella_core.pyo", line 258, in sendPacket
 File "twisted\internet\udp.pyo", line 160, in write
 File "twisted\internet\udp.pyo", line 160, in write
 File "twisted\internet\udp.pyo", line 160, in write
 File "twisted\internet\udp.pyo", line 160, in write
 File "twisted\internet\udp.pyo", line 160, in write
 File "twisted\internet\udp.pyo", line 160, in write

(a couple thousand times)

 File "twisted\internet\udp.pyo", line 160, in write
 File "twisted\internet\udp.pyo", line 160, in write
exceptions.RuntimeError: maximum recursion depth exceeded
```

Attachments:

* [udp-infinite-eintr.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/628/6286b52ae81a4481bb77caf4d35139764e32d0c8/fff7884e1d2f9378f02bd696af9df87fa99f54f4.patch) (1625 bytes) - added by p1mrx on 2007-09-09 23:24:21Z - Proposed patch

<details><summary>Searchable metadata</summary>

```
trac-id__2513 2513
type__defect defect
reporter__p1mrx p1mrx
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__ 
time__1173401810000000 1173401810000000
changetime__1319836320000000 1319836320000000
version__None None
owner__p1mrx p1mrx
cc__therve cc__jesstess
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="kbrooks's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_1"></a>|kbrooks set owner to kbrooks<br>kbrooks set status to `assigned`|
|-|-|

confirmed in trunk

**Comment by twisted-trac** [comment]
|<img alt="kbrooks's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_2"></a>|kbrooks set owner to @glyph<br>kbrooks set status to `new`|
|-|-|

oops, i did not mean to change the owner

**Comment by twisted-trac** [comment]
|[<img alt="jyknight's avatar" src="https://avatars.githubusercontent.com/u/873903?s=50" width="50" height="50">](https://github.com/jyknight)<a name="note_3"></a>|@jyknight commented|
|-|-|

"confirmed in trunk" -- confirmed how? What causes this?

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_4"></a>|@glyph set owner to p1mrx|
|-|-|

Patch has no tests.  I don't quite understand what's causing this either.  Please add some and expound.

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_6"></a>|@therve commented|
|-|-|

We should first thank you for the report :). As glyph spotted earlier, this has few chances to be in if there is no test, and absolutely no chance if we don't understand what's happening.

First, it seems it happens only under win32? Do you have some details on your application? Does it happen in a particular situation (closing the app,..).? Every feedback will be welcome.

**Comment by twisted-trac** [comment]
|<img alt="p1mrx's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_7"></a>|p1mrx commented|
|-|-|

This was an intermittent failure that a few people sent me tracebacks for.  Most people are running it on Windows, but I can't be certain that this was a Windows-only bug.  It did occur on more than one computer though.  That's all I know about it.

My program now just catches RuntimeErrors when doing a UDP write, and treats it like packet loss.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_8"></a>|@exarkun commented|
|-|-|

Milestones are used for something different.

**Comment by twisted-trac** [comment]
|[<img alt="jesstess's avatar" src="https://avatars.githubusercontent.com/u/188336?s=50" width="50" height="50">](https://github.com/jesstess)<a name="note_9"></a>|@jesstess commented|
|-|-|

p1mrx, thanks again for the initial bug report. Do you know if this an issue that still exists under Twisted 11.0? If we can get a reproducer we'd like to investigate it, but if we can't get some more concrete details it may be time to close the ticket.

**Comment by twisted-trac** [comment]
|<img alt="p1mrx's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_10"></a>|p1mrx commented|
|-|-|

Sorry, I don't have any information beyond what I've provided.  Dtella still contains the "except RuntimeError" hack, but I don't know if it's still required, and it wouldn't be in the users' interest to remove it.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_11"></a>|@glyph commented|
|-|-|

Replying to [p1mrx](#note_10):
> Sorry, I don't have any information beyond what I've provided.  Dtella still contains the "except RuntimeError" hack, but I don't know if it's still required, and it wouldn't be in the users' interest to remove it.

Can you try removing that `except:` just on a test system?  I realize that Dtella doesn't stand to benefit much from doing this, but it would really be helpful to Twisted if you could let us know whether we still need to fix this issue, especially since we don't have a simple case that reproduces it.

**Comment by twisted-trac** [comment]
|<img alt="p1mrx's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_12"></a>|p1mrx commented|
|-|-|

I can't just reproduce the error at will; the traceback was sent to me by a random user, and I have no idea what conditions triggered it.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_13"></a>|@glyph commented|
|-|-|

Replying to [p1mrx](#note_12):
> I can't just reproduce the error at will; the traceback was sent to me by a random user, and I have no idea what conditions triggered it.

My hypothesis would be "firewall" software like AVG which randomly changes the behavior of sockets (c.f. [#3831](https://github.com/twisted/twisted/issues/3831)).  Although not necessarily AVG itself, in this case.

I'm sorry we haven't up with a better solution for you yet, but I really appreciate your extreme responsiveness to all the feedback on the ticket.  Thank you.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_14"></a>|@glyph commented|
|-|-|

Whether or not it is easy to produce repeated`EINTR`s from a UDP `socket.send`, the fact remains that this has the _potential_ for infinite recursion since the socket implementation is totally within its rights to raise that errno at any time if it feels like it.  Maybe another process is anxiously trying to kill it; maybe some syscall interception library is messing with it.  It doesn't matter, we should handle it better, and the tests for this case are going to use a synthetic socket anyway; producing it from the real implementation is not realistic.

I think a 'pass' might be a more legitimate implementation for this case anyway.  Then we'd be dropping a packet knowingly without telling application code, which means that this is also potentially related to [#2790](https://github.com/twisted/twisted/issues/2790).  (Perhaps somebody could just re-write `udp.Port.write` completely, with tests, because the current behavior is accidental and gross and obviously wrong in several cases.)
