### ISSUE TITLE
strange connect timeouts

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#2554]
|<img alt="gudron's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| gudron reported|
|-|-|
|Trac ID|trac#2554|
|Type|task|
|Created|2007-04-05 13:24:20Z|

hello!

currently i'm developing a little web crawler for our school and doing it in twisted.

i use standart t.w.c getPage in about 300 concurent workers.
all works pretty fine, but sometimes i got many error.TimeoutError timeout ( done by base.BaseConnector)

but using curl, wget, fetch etc i can connect( and download) these hosts successfully.
therefore i need to use connector.connect() many times in clientConnectionFailed ( my subclass of HTTPClientFactory)
i tried to find where this problem occurs but can't.

could anyone tells me why i have too much connect timeout errors( but i can connect and fetch from these hosts via curl, wget,....). is it a bug or i make mistakes somewhere?

thank you!

<details><summary>Searchable metadata</summary>

```
trac-id__2554 2554
type__task task
reporter__gudron gudron
priority__high high
milestone__Web_0_7 Web-0.7
branch__ 
branch_author__ 
status__closed closed
resolution__invalid invalid
component__web web
keywords__timeouterror_clientfactory_getpage timeouterror,clientfactory,getpage
time__1175779460000000 1175779460000000
changetime__1180091512000000 1180091512000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="pitrou's avatar" src="https://avatars.githubusercontent.com/u/1721820?s=50" width="50" height="50">](https://github.com/pitrou)<a name="note_1"></a>|@pitrou commented|
|-|-|

Perhaps you are doing too many connections at once?
If those 300 connections bang on the same server, it wouldn't be a surprise that some of them are refused, ignored, or queued for a long time. If this is indeed the case, please note that the server administrators won't be very happy with you either.

First try lowering the connection number to e.g. 10 or 20 and see if the problem still occurs.

**Comment by twisted-trac** [comment]
|<img alt="gudron's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_2"></a>|gudron commented|
|-|-|

yep. if i lower connections to 50-60 the problem dissapears.
but i use shuffled queue of urls. also i tried to used reconnectingHTTPfactory(which have exponential reconnections if failed) it solved my problem, but these fails still exists.

**Comment by twisted-trac** [comment]
|[<img alt="pitrou's avatar" src="https://avatars.githubusercontent.com/u/1721820?s=50" width="50" height="50">](https://github.com/pitrou)<a name="note_3"></a>|@pitrou commented|
|-|-|

Replying to [gudron](#note_2):
> yep. if i lower connections to 50-60 the problem dissapears.

So there's your fix ;)

> but these fails still exists

But it's very likely that they are simply caused by the server not answering. In that case it's not a bug in Twisted, but in your code making too many connections at once. If you have doubts about it, please do a Wireshark capture and see whether the server answers all requests or not.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_4"></a>|@exarkun set status to `closed`|
|-|-|

This is indeed an application bug.

You can try raising the timeouts instead of lowering the concurrency, but ultimately you will need to have error handling code for the timeout case, if you want your application to be robust.

**Comment by twisted-trac** [comment]
|<img alt="gudron's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_5"></a>|gudron set status to `reopened`|
|-|-|

i'm not sure this is app bug.

i got connection timeout error from different servers, max conn to 1 server isn't big.

i use conn timeout equeal to 60 secs - i think this is more, than enought


i wrote same program in perl( forks,curl) - it uses more memory, but don't raise so much conn timeouts.


yes, i have error handling code. it based on documented twisted err handling codes( connector.connect() or using reconnecting http client factory).


maybe problem occurs, because using only 1 local IP address( i use more web-programs on this server, doing same)?

thnx, sorry 4 my english.

PS i tried to do post here in russian ( coz my english is ugly) and got UnicodeEncodeError: 'ascii' codec can't encode characters in position 177-179: ordinal not in range(128)

#### How to Reproduce
While doing a POST operation on `/ticket/2554`, Trac issued an internal error.
{'action': u'leave',
 'cc': u'',
 'cnum': u'5',
 'comment': u"please use russian-english translator, but i'll try to do it self( my english is very bad, sorry)\r\n\r\nrus ver:\r\n\r\n\u043d\u0435\u0442, \u044d\u0442\u043e \u043d\u0435 \u043e\u0448\u0438\u0431\u043a\u0430 \u043f\u0440\u0438\u043b\u043e\u0436\u0435\u043d\u0438\u044f.\r\n\u044f \u043f\u043e\u043b\u0443\u0447\u0430\u044e connect timeout \u0441\u043e\u0432\u0435\u0440\u0448\u0435\u043d\u043d\u043e \u0441 \u0440\u0430\u0437\u043d\u044b\u0445 \u0441\u0435\u0440\u0432\u0435\u0440\u043e\u0432, \u043f\u0440\u0438 \u044d\u0442\u043e\u043c \u043a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043e\u0431\u0440\u0430\u0449\u0435\u043d\u0438\u0439 \u043a \u043e\u043f\u0440\u0435\u0434\u0435\u043b\u0435\u043d\u043d\u043e\u043c\u0443 \u0441\u0435\u0440\u0432\u0435\u0440\u0443 \u0432 \u0434\u0430\u043d\u043d\u044b\u0439 \u043c\u043e\u043c\u0435\u043d\u0442 \u0432\u0440\u0435\u043c\u0435\u043d\u0438 \u043d\u0435\u0432\u0435\u043b\u0438\u043a\u043e.\r\n\u0442\u0430\u0439\u043c\u0430\u0443\u0442 \u043d\u0430 \u0441\u043e\u0435\u0434\u0438\u043d\u0435\u043d\u0438\u0435 \u0432 \u043c\u043e\u0435\u043c \u043f\u0440\u0438\u043b\u043e\u0436\u0435\u043d\u0438\u0438 \u0441\u0435\u0439\u0447\u0430\u0441 \u0440\u0430\u0432\u0435\u043d 60 \u0441\u0435\u043a\u0443\u043d\u0434\u0430\u043c - \u044d\u0442\u043e \u0431\u043e\u043b\u0435\u0435, \u0447\u0435\u043c \u0434\u043e\u0441\u0442\u0430\u0442\u043e\u0447\u043d\u043e.\r\n\u043d\u0430\u043f\u0438\u0441\u0430\u043d\u043d\u0430\u044f \u043d\u0430 perl \u0442\u0430 \u0436\u0435 \u043f\u0440\u043e\u0433\u0440\u0430\u043c\u043c\u0430 (forks, curl) \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u0443\u0435\u0442 \u0431\u043e\u043b\u044c\u0448\u0435 \u043f\u0430\u043c\u044f\u0442\u0438, \u043d\u043e \u043e\u0448\u0438\u0431\u043a\u0438 connection timeout \u043f\u0440\u0430\u043a\u0442\u0438\u0447\u0435\u0441\u043a\u0438 \u043e\u0442\u0441\u0443\u0442\u0441\u0442\u0432\u0443\u044e\u0442.\r\n\r\n\u0434\u0430 \u0443 \u043c\u0435\u043d\u044f \u0435\u0441\u0442\u044c \u043e\u0431\u0440\u0430\u0442\u0447\u0438\u043a \u043e\u0448\u0438\u0431\u043e\u043a. \u0432 \u0434\u0430\u043d\u043d\u043e\u043c \u0441\u043b\u0443\u0447\u0430\u0435 \u044f \u043f\u0440\u043e\u0431\u043e\u0432\u0430\u043b \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c connector.connect() \u0438, \u043a\u043e\u0433\u0434\u0430 \u044d\u0442\u043e \u043d\u0435 \u043f\u043e\u043c\u043e\u0433\u043b\u043e, reconnecting Factory - \u044d\u0442\u043e \u043d\u0435 \u043f\u043e\u043c\u043e\u0433\u043b\u043e,\u043a \u0441\u043e\u0436\u0430\u043b\u0435\u043d\u0438\u044e, \u0442\u043e\u0436\u0435.\r\n\r\n\u043c\u043e\u0436\u0435\u0442 \u0431\u044b\u0442\u044c \u043f\u0440\u043e\u0431\u043b\u0435\u043c\u0430 \u0438\u0437-\u0437\u0430 \u0442\u043e\u0433\u043e, \u0447\u0442\u043e \u044f \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u0443\u044e 1 \u043b\u043e\u043a\u0430\u043b\u044c\u043d\u044b\u0439 IP \u0430\u0434\u0440\u0435\u0441 \u0434\u043b\u044f \u0432\u0441\u0435\u0445 \u0441\u043e\u0435\u0434\u0438\u043d\u0435\u043d\u0438\u0439 ( \u043d\u0430 \u0441\u0435\u0440\u0432\u0435\u0440\u0435 \u043f\u043e\u043c\u0438\u043c\u043e \u044d\u0442\u043e\u0439 \u043f\u0440\u043e\u0433\u0440\u0430\u043c\u044b \u0440\u0430\u0431\u043e\u0442\u0430\u0435\u0442 \u0435\u0449\u0435 \u043c\u043d\u043e\u0433\u043e \u0434\u0440\u0443\u0433\u0438\u0445 \u0435\u0439 \u043f\u043e\u0434\u043e\u0431\u043d\u044b\u0445)?\r\n\r\neng ver:\r\n\r\n\r\ni'm not sure this is app bug.\r\n\r\ni got connection timeout error from different servers, max conn to 1 server isn't big.\r\n\r\ni use conn timeout equeal to 60 secs - i think this is more, than enought\r\n\r\n\r\ni wrote same program in perl( forks,curl) - it uses more memory, but don't raise so much conn timeouts.\r\n\r\n\r\nyes, i have error handling code. it based on documented twisted err handling codes( connector.connect() or using reconnecting http client factory).\r\n\r\n\r\nmaybe problem occurs, because using only 1 local IP address( i use more web-programs on this server, doing same)?\r\n\r\nthnx, sorry 4 my english.\r\n",
 'component': u'web',
 'id': u'2554',
 'keywords': u'timeouterror,clientfactory,getpage',
 'milestone': u'Web-0.7',
 'priority': u'high',
 'replyto': u'',
 'summary': u'strange connect timeouts',
 'ts': u'2007-04-08 03:49:11+00:00',
 'type': u'task'}
#### System Information
| **Python** | 
|------------|-`2.4.3 (#2, Oct  6 2006, 07:52:30) `
`[GCC 4.0.3 (Ubuntu 4.0.3-1ubuntu5)]`
 ||
| **Subversion** | 
|----------------|-`1.4.2` ||
| **SQLite** | 
|------------|-`3.2.8` ||
| **pysqlite** | 
|--------------|-`2.0.5` ||
#### Python Traceback
```
Traceback (most recent call last):
  File "/home/trac/.local/lib/python2.4/site-packages/trac/web/main.py", line 377, in dispatch_request
    dispatcher.dispatch(req)
  File "/home/trac/.local/lib/python2.4/site-packages/trac/web/main.py", line 237, in dispatch
    resp = chosen_handler.process_request(req)
  File "/home/trac/.local/lib/python2.4/site-packages/trac/ticket/web_ui.py", line 256, in process_request
    self._do_save(req, db, ticket)
  File "/home/trac/.local/lib/python2.4/site-packages/trac/ticket/web_ui.py", line 530, in _do_save
    cnum=internal_cnum)
  File "/home/trac/.local/lib/python2.4/site-packages/trac/ticket/model.py", line 268, in save_changes
    listener.ticket_changed(self, comment, author, old_values)
  File "build/bdist.linux-i686/egg/ticket_emailer/ticket_emailer.py", line 193, in ticket_changed
  File "build/bdist.linux-i686/egg/ticket_emailer/ticket_emailer.py", line 79, in flattenMessage
  File "/usr/lib/python2.4/email/Generator.py", line 82, in flatten
    self._write(msg)
  File "/usr/lib/python2.4/email/Generator.py", line 113, in _write
    self._dispatch(msg)
  File "/usr/lib/python2.4/email/Generator.py", line 139, in _dispatch
    meth(msg)
  File "/usr/lib/python2.4/email/Generator.py", line 182, in _handle_text
    self._fp.write(payload)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 177-179: ordinal not in range(128)
```

**Comment by twisted-trac** [comment]
|[<img alt="pitrou's avatar" src="https://avatars.githubusercontent.com/u/1721820?s=50" width="50" height="50">](https://github.com/pitrou)<a name="note_6"></a>|@pitrou commented|
|-|-|

Hi again,

Replying to [gudron](#note_5):
> i got connection timeout error from different servers, max conn to 1 server isn't big.

But the bottleneck could be anywhere: on your network connection, on your personal NAT/firewall, on a router somewhere along the path, etc. Since you are making so many connections at once, perhaps a security mechanism somewhere thinks you are an attacker and decides to drop those connections. You don't know what can happen.

I'm not saying it can't be a Twisted bug. Just that you'd have to eliminate the uncertainties related to network characteristics and present a reasonable way to reproduce the behaviour (one where you make sure that you don't depend on the behaviour of an uncontrolled external entity).

> i wrote same program in perl( forks,curl) - it uses more memory, but don't raise so much conn timeouts.

A Twisted program trying 300 connections at once will _really_ try them at once (or nearly). A program forking each connection to a separate process will issue those connections more slowly so, yes, you will get less timeouts because you are being more graceful to the network.

> PS i tried to do post here in russian ( coz my english is ugly)

Well, it's better to post in English even if your English is imperfect. It's likely that few people understand Russian here (or French or any other language for that matter ;-)).

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_7"></a>|@therve set status to `closed`|
|-|-|

Please provide a reproductible example to show the problem. Until then, we still consider that the problem comes from your code.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
