### ISSUE TITLE
.py/.pyc mismatch causes internal trial error

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#2561]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#2561|
|Type|defect|
|Created|2007-04-10 13:36:11Z|

```
exarkun@charm:~$ mkdir trial_test
exarkun@charm:~$ cd trial_test/
exarkun@charm:~/trial_test$ touch test_foo.py
exarkun@charm:~/trial_test$ trial test_foo.py
Running 0 tests.

-------------------------------------------------------------------------------
Ran 0 tests in 0.014s

PASSED
exarkun@charm:~/trial_test$ mkdir foo
exarkun@charm:~/trial_test$ mv test_foo.py foo/
exarkun@charm:~/trial_test$ trial foo/test_foo.py
Running 0 tests.
                                                       [ERROR]

===============================================================================
[ERROR]: foo/test_foo.py

Traceback (most recent call last):
  File "/home/exarkun/Projects/Twisted/trunk/twisted/trial/runner.py", line 631, in loadByNames
    things.append(self.findByName(name))
  File "/home/exarkun/Projects/Twisted/trunk/twisted/trial/runner.py", line 450, in findByName
    return filenameToModule(name)
  File "/home/exarkun/Projects/Twisted/trunk/twisted/trial/runner.py", line 78, in filenameToModule
    if os.path.isfile(fn) and not same(fn, retFile):
  File "/usr/lib/python2.4/posixpath.py", line 219, in samefile
    s2 = os.stat(f2)
exceptions.OSError: [Errno 2] No such file or directory: '/home/exarkun/trial_test/test_foo.py'
-------------------------------------------------------------------------------
Ran 0 tests in 0.001s

FAILED (errors=1)
exarkun@charm:~/trial_test$                                                                                                               
```

<details><summary>Searchable metadata</summary>

```
trac-id__2561 2561
type__defect defect
reporter__exarkun exarkun
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__trial trial
keywords__ 
time__1176212171000000 1176212171000000
changetime__1176282752000000 1176282752000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_1"></a>|@therve commented|
|-|-|

That's because foo/ directory is not a package. I don't know if it should be a problem or not, though.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
