### ISSUE TITLE
Race condition with connector.stopConnecting

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#2579]
|<img alt="arkanes's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| arkanes reported|
|-|-|
|Trac ID|trac#2579|
|Type|defect|
|Created|2007-04-18 16:28:23Z|

When you call stopConnecting on a Connector, any DNS lookup in progress is not cancelled, because there is not API for doing so. This leads to a race condition which can cause a dirty reactor error in trial, because the DNS timeout delayed call hangs around.

Compounding this problem, when trial detects the dirty reactor it cancels the DelayedCall, which will result in an error in an unrelated test sometime later, when the DNS cleanup is called and attempts to cancel the timeout call again.

Example of trials dirty reactor error below.

```
c:\Python25\lib\site-packages\twisted\trial\reporter.py:219: twisted.trial.repor
ter.BrokenTestCaseWarning: REACTOR UNCLEAN! traceback(s) follow:
Traceback (most recent call last):
  File "c:\Python25\lib\site-packages\twisted\trial\unittest.py", line 635, in _
cleanUp
    util._Janitor().postCaseCleanup()
  File "c:\Python25\lib\site-packages\twisted\trial\util.py", line 64, in postCa
seCleanup
    return self._dispatch('cleanPending')
  File "c:\Python25\lib\site-packages\twisted\trial\util.py", line 72, in _dispa
tch
    getattr(self, "do_%s" % attr)()
  File "c:\Python25\lib\site-packages\twisted\internet\utils.py", line 164, in w
arningSuppressingWrapper
    return runWithWarningsSuppressed(suppressedWarnings, f, *a, **kw)
  File "c:\Python25\lib\site-packages\twisted\internet\utils.py", line 144, in r
unWithWarningsSuppressed
    result = f(*a, **kw)
  File "c:\Python25\lib\site-packages\twisted\trial\util.py", line 91, in do_cle
anPending
    raise PendingTimedCallsError(s)
twisted.trial.util.PendingTimedCallsError: pendingTimedCalls still pending (cons
ider setting twisted.internet.base.DelayedCall.debug = True): <DelayedCall 17632
112 [60.0s] called=0 cancelled=0 ThreadedResolver._cleanup('localhost', <Deferre
d at 0x10d0df0>)>

```

<details><summary>Searchable metadata</summary>

```
trac-id__2579 2579
type__defect defect
reporter__arkanes arkanes
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__ 
time__1176913703000000 1176913703000000
changetime__1176913703000000 1176913703000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
