### ISSUE TITLE
Possible intermittent failure in twisted.test.test_modules

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#2584]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)| @jml reported|
|-|-|
|Trac ID|trac#2584|
|Type|defect|
|Created|2007-04-20 08:57:24Z|

While running the full test suite under Python 2.5, I got this error message:

```
[ERROR]: twisted.test.test_modules.BasicTests.test_loadPackagesAndModules
 
Traceback (most recent call last):
  File "/home/jml/Code/Twisted/trunk/twisted/test/test_modules.py", line 138, in test_loadPackagesAndModules
    self.findByIteration(n).load(),
  File "/home/jml/Code/Twisted/trunk/twisted/test/test_modules.py", line 31, in findByIteration
    for modinfo in where.walkModules(importPackages=importPackages):
  File "/home/jml/Code/Twisted/trunk/twisted/python/modules.py", line 729, in walkModules
    for module in package.walkModules(importPackages=False):
  File "/home/jml/Code/Twisted/trunk/twisted/python/modules.py", line 174, in walkModules
    for module in package.walkModules(importPackages=importPackages):
  File "/home/jml/Code/Twisted/trunk/twisted/python/modules.py", line 174, in walkModules
    for module in package.walkModules(importPackages=importPackages):
  File "/home/jml/Code/Twisted/trunk/twisted/python/modules.py", line 173, in walkModules
    for package in self.iterModules():
  File "/home/jml/Code/Twisted/trunk/twisted/python/modules.py", line 125, in iterModules
    for placeToLook in self._packagePaths():
  File "/home/jml/Code/Twisted/trunk/twisted/python/modules.py", line 418, in _packagePaths
    for fn in self.load().__path__:
exceptions.AttributeError: 'module' object has no attribute '__path__'
```

Running 'trial twisted.test.test_module' worked just fine.

<details><summary>Searchable metadata</summary>

```
trac-id__2584 2584
type__defect defect
reporter__jml jml
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__worksforme worksforme
component__core core
keywords__ 
time__1177059444000000 1177059444000000
changetime__1221176872000000 1221176872000000
version__None None
owner__ 
cc__exarkun
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

This doesn't fail for me.  I suspect it's dependent on the environment somehow.  Could you supply some more detail?

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_3"></a>|@exarkun commented|
|-|-|

Ping?  Perhaps instrument the code to print out which module it is that does not have `__path__`.

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)<a name="note_4"></a>|@jml set status to `closed`|
|-|-|

2000+ runs later, I can't reproduce this.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
