### ISSUE TITLE
trac: TypeError: <lambda>() got multiple values for keyword argument 'asc'

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#2597]
|<img alt="slamb's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| slamb reported|
|-|-|
|Trac ID|trac#2597|
|Type|defect|
|Created|2007-04-23 17:36:30Z|

#### How to Reproduce
Go to http://twistedmatrix.com/trac/report/13

Click on the "Modified" header to sort by date. You'll end up at a URL like http://twistedmatrix.com/trac/report/13?asc=1&sort=modified&USER=slamb, which will show this error. (and has a nice thing that autofills most of the bug report.)

#### System Information
| **Python** | 
|------------|-`2.4.3 (#2, Oct  6 2006, 07:52:30) `
`[GCC 4.0.3 (Ubuntu 4.0.3-1ubuntu5)]`
 ||
| **Subversion** | 
|----------------|-`1.4.2` ||
| **SQLite** | 
|------------|-`3.2.8` ||
| **pysqlite** | 
|--------------|-`2.0.5` ||
#### Python Traceback
```
Traceback (most recent call last):
  File "/home/trac/.local/lib/python2.4/site-packages/trac/web/main.py", line 377, in dispatch_request
    dispatcher.dispatch(req)
  File "/home/trac/.local/lib/python2.4/site-packages/trac/web/main.py", line 248, in dispatch
    content_type)
  File "/home/trac/.local/lib/python2.4/site-packages/trac/web/chrome.py", line 475, in render_template
    return stream.render(method, doctype=doctype)
  File "/home/trac/Projects/genshi/trunk/genshi/core.py", line 146, in render
    output = u''.join(list(generator))
  File "/home/trac/Projects/genshi/trunk/genshi/output.py", line 200, in __call__
    for kind, data, pos in stream:
  File "/home/trac/Projects/genshi/trunk/genshi/output.py", line 486, in __call__
    for kind, data, pos in chain(stream, [(None, None, None)]):
  File "/home/trac/Projects/genshi/trunk/genshi/output.py", line 436, in __call__
    for kind, data, pos in stream:
  File "/home/trac/Projects/genshi/trunk/genshi/core.py", line 207, in _ensure
    for event in stream:
  File "/home/trac/Projects/genshi/trunk/genshi/core.py", line 207, in _ensure
    for event in stream:
  File "/home/trac/.local/lib/python2.4/site-packages/trac/web/chrome.py", line 478, in _strip_accesskeys
    for kind, data, pos in stream:
  File "/home/trac/Projects/genshi/trunk/genshi/filters.py", line 313, in __call__
    for kind, data, pos in stream:
  File "/home/trac/Projects/genshi/trunk/genshi/template.py", line 1145, in _match
    content = list(content)
  File "/home/trac/Projects/genshi/trunk/genshi/filters.py", line 331, in __call__
    for event in template.generate(ctxt):
  File "/home/trac/Projects/genshi/trunk/genshi/filters.py", line 313, in __call__
    for kind, data, pos in stream:
  File "/home/trac/Projects/genshi/trunk/genshi/template.py", line 1120, in _match
    for event in stream:
  File "/home/trac/Projects/genshi/trunk/genshi/template.py", line 920, in _eval
    ctxt):
  File "/home/trac/Projects/genshi/trunk/genshi/template.py", line 930, in _eval
    result = data.evaluate(ctxt)
  File "/home/trac/Projects/genshi/trunk/genshi/eval.py", line 101, in evaluate
    {'data': data})
  File "/home/trac/.local/share/trac/templates/report_view.html", line 39, in <Expression u"href.report(report.id, sort=header.col, asc=not header.asc and "1" or "0", **report.args)">
    <a py:strip="not sorting_enabled"
TypeError: <lambda>() got multiple values for keyword argument 'asc'
```
    

<details><summary>Searchable metadata</summary>

```
trac-id__2597 2597
type__defect defect
reporter__slamb slamb
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__wontfix wontfix
component__website website
keywords__ 
time__1177349790000000 1177349790000000
changetime__1177358596000000 1177358596000000
version__None None
owner__oubiwann oubiwann

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun set status to `closed`|
|-|-|

This is a trac defect.  Please see http://trac.edgewall.com/

**Comment by twisted-trac** [comment]
|<img alt="slamb's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_2"></a>|slamb commented|
|-|-|

It is indeed a trac defect. The trac bug reporting screen suggested reporting it to the local site administrator (and automatically started the ticket to do so). I don't know the trac version to report upstream.
