### ISSUE TITLE
trial runner does not recognize class based decorators

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#2645]
|<img alt="synapsis's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| synapsis reported|
|-|-|
|Trac ID|trac#2645|
|Type|defect|
|Created|2007-05-14 20:46:15Z|
|Branch|https://github.com/twisted/twisted/tree/class-based-decorators-2645|

I'm using Twisted 2.4 with Python 2.4.4 on Debian Etch.

If I decorate a test case with a class based decorator, trial does not recognize it.

I have attached the test script.

Here is the problem:

```
#!sh
$trial trial_decorator.TestCase.test_Answer
Traceback (most recent call last):
  File "/usr/local/bin/trial", line 24, in ?
    run()
  File "/usr/lib/python2.4/site-packages/twisted/scripts/trial.py", line 373, in run
    suite = _getSuite(config)
  File "/usr/lib/python2.4/site-packages/twisted/scripts/trial.py", line 332, in _getSuite
    suite.addTest(loader.loadByName(test, recurse))
  File "/usr/lib/python2.4/site-packages/twisted/trial/runner.py", line 346, in loadByName
    return self.loadAnything(thing, recurse)
  File "/usr/lib/python2.4/site-packages/twisted/trial/runner.py", line 339, in loadAnything
    raise TypeError("No loader for %r. Unrecognized type" % (thing,))
TypeError: No loader for <trial_decorator.logger object at 0xb77933cc>. Unrecognized type
```

Attachments:

* [trial_decorator.py](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/3e2/3e2feb47655ed2eb9623395ebfa3b54bdc7d2b7d/1e856bc47b2679a69b00b1c3f814a2ec9365fc3c.py) (701 bytes) - added by synapsis on 2007-05-14 20:46:43Z - 
* [trial_decorator.2.py](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/3e2/3e2feb47655ed2eb9623395ebfa3b54bdc7d2b7d/6e26db80a747db2c49c37e920db05970f4a4ea07.py) (1194 bytes) - added by synapsis on 2007-05-14 21:57:07Z - correct implementation of the decorator
* [AddMethodNamesToDictTests.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/3e2/3e2feb47655ed2eb9623395ebfa3b54bdc7d2b7d/8a9a80dc59a5740b1d0082baa0b5c9110ae70aee.patch) (5013 bytes) - added by kelly on 2009-10-17 23:57:14Z - tests for twisted.python.reflect.addMethodNamesToDict
* [TestMethodDescriptors.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/3e2/3e2feb47655ed2eb9623395ebfa3b54bdc7d2b7d/fd72643bbbb65bd748a2b96c0051943e91a19c82.patch) (1531 bytes) - added by kelly on 2009-10-17 23:57:52Z - changes twisted.python.reflect.addMethodNamesToDict to look for methods using getattr
* [max-test-discovery.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/3e2/3e2feb47655ed2eb9623395ebfa3b54bdc7d2b7d/9707f7690b0f19d53e3eb38066f497a9000e4e38.patch) (3058 bytes) - added by kelly on 2009-10-17 23:58:36Z - test method objects are no longer required to have an im_class property
* [review-1.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/3e2/3e2feb47655ed2eb9623395ebfa3b54bdc7d2b7d/d6f75a6b02a267c1af9d5c891b302802f088d957.patch) (19489 bytes) - added by kelly on 2009-10-23 21:20:43Z - Fixes outstanding review issues (I hope)

<details><summary>Searchable metadata</summary>

```
trac-id__2645 2645
type__defect defect
reporter__synapsis synapsis
priority__normal normal
milestone__ 
branch__branches_class_based_decorators_2645 branches/class-based-decorators-2645
branch_author__jml jml
status__new new
resolution__None None
component__trial trial
keywords__ 
time__1179175575000000 1179175575000000
changetime__1258225932000000 1258225932000000
version__None None
owner__kelly kelly
cc__synapsis cc__exarkun
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_3"></a>|@exarkun commented|
|-|-|

This doesn't work with Python, either.  Methods can only be implemented with functions, not arbitrary callable objects.

However, current Twisted trunk@HEAD skips the test entirely.  Instead, it should try to call the method, fail with a TypeError (not the one in the description above, but one resulting from not calling the function with enough arguments), and report this error in the usual way.

If you want logger to actually be a usable decorator, you should give it a ```__get__``` method which binds it to the instance with an ```instancemethod```.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_4"></a>|@exarkun commented|
|-|-|

Err, first I said you can only implement methods with functions, then I explained that you can use descriptors to implement methods.  The first of these two statements is, clearly, incorrect.  Please disregard it. :)

**Comment by twisted-trac** [comment]
|[<img alt="jyknight's avatar" src="https://avatars.githubusercontent.com/u/873903?s=50" width="50" height="50">](https://github.com/jyknight)<a name="note_5"></a>|@jyknight commented|
|-|-|

In particular, you need to add:
```
    def __get__(self, obj, objtype=None):
        return types.MethodType(self, obj, objtype)
```
to your class definition.

(but trial still won't work with it).

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_6"></a>|@exarkun commented|
|-|-|

Oh hey, I see there are different behaviors based on different trial command-lines too.  So maybe there are two separate issues here.

**Comment by twisted-trac** [comment]
|<img alt="synapsis's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_7"></a>|synapsis commented|
|-|-|

Replying to [exarkun](#note_3):
> This doesn't work with Python, either.  Methods can only be implemented with functions, not arbitrary callable objects.
>
> However, current Twisted trunk@HEAD skips the test entirely.  Instead, it should try to call the method, fail with a TypeError (not the one in the description above, but one resulting from not calling the function with enough arguments), and report this error in the usual way.
>
> If you want logger to actually be a usable decorator, you should give it a ```__get__``` method which binds it to the instance with an ```instancemethod```.


Yes, you are right, sorry.

I just forgot to add it, however the problem is the same.

I have updated the attached test script.

**Comment by twisted-trac** [comment]
|<img alt="kelly's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_8"></a>|kelly commented|
|-|-|

Part of the cause for this lies in `twisted.python.reflect.addMethodNamesToDict`.  It iterates through the class `__dict__` looking for things that are `FunctionType`.  In the example the `__dict__` entry for `test_Answer` is a `logger`.

First patch adds tests for `twisted.python.reflect.addMethodNamesToDict` to demonstrate the problem.

Second patch changes `twisted.python.reflect.addMethodNamesToDict` to look for methods using `getattr` (to trigger descriptor `__get__`).

At this point descriptors which return `MethodType` objects from `__get__` work.

Third patch modifies `twisted.trial.unittest.TestCase.__init__` so that test method objects are no longer required to have an im_class property.  This fixes the original problem.

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)<a name="note_10"></a>|@jml commented|
|-|-|

(In [27383]) Branching to 'class-based-decorators-2645'

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)<a name="note_11"></a>|@jml set owner to kelly|
|-|-|

Hi Kelly,

Thanks for contributing this patch. I have a couple of questions about it that I'd like resolved before it lands. I've only had a shallow look, so please bear with me if I ask something stupid.

I notice that your initial patch is supposed to reproduce the problem. However, when I apply the patch, I don't see any test that actually fails. How is it reproducing the problem?

Thank you so much for adding tests, btw. It makes it a lot easier to get the patch landed. I have to say that I don't understand the motivation for a lot of these tests. Could you please add docstrings to each that explain the behaviour that each of them is checking? e.g.

```python
    def test_no_prefix_methods(self):
        """
        When there are no methods that match the given prefix, nothing is added 
        to the dict.
        """
```

A bit redundant for that method perhaps, but very useful for things like `test_all`.

Similarly, each of the example classes that you add should have docstrings explaining how they are actually used and why they are needed.

Comments should in general be sentences, e.g.

```python
# Not a method.
```

rather than 

```python
# not a method
```

Although, better still would be a comment explaining why you've got something that's not a method. Most of the people reading this will be able to infer that 42 isn't actually a method. ;) Similar reasoning applies to "create a bunch of methods various ways".

It would also be worthwhile having an explanatory comment before the two `for` blocks that generate tests. They are reasonably arcane, so it would be good to explain what they are actually testing and why we're generating tests this way rather than writing them the old-fashioned way.

Using `hasattr(method, '__call__')` seems a bit dodgy to me. Why not use `callable`?

In twisted/trial/util.py, `DUMMY` should be named `_DUMMY`, since it's not intended for export.

Also in twisted/trial/util.py, could you please update the docstring of `getPythonContainers` to document the new parameter? While you're there, I'd appreciate it if you could also put the docstring into the correct format.

There are a few places where the branch doesn't comply with the [coding standard](http://twistedmatrix.com/trac/browser/trunk/doc/core/development/policy/coding-standard.xhtml?format=raw). In particular, we deviate from standard Python practice in that there must be two blank lines between methods and three blank lines between top-level blocks. You don't have to address all of these issues yourself; I can do some cleanup before landing. However, if you're planning on submitting patches in the future, it'd be good to get familiar with the coding standard, since it also 

I'm also a little nervous as to how the change to `unittest.py` will affect old-style classes. Using `type(self)` seems wrong for them, since it will always return `<type 'instance'>`.

I'd really appreciate it if you could add a test that would fail without the change you made to `unittest.py`.

Phew. I hope that's not too much. Sorry for taking so long to get back to you.

And thanks again!

jml

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)<a name="note_12"></a>|@jml commented|
|-|-|

therve says use `getattr(f, '__call__', None) is not None` rather than `hasattr(f, '__call__')` or `callable`.

**Comment by twisted-trac** [comment]
|<img alt="kelly's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_13"></a>|kelly commented|
|-|-|

Replying to [jml](#note_11):

> I notice that your initial patch is supposed to reproduce the problem. However, when I apply the patch, I don't see any test that actually fails. How is it reproducing the problem?

Oops. Sorry, that patch doesn't really demonstrate the problem so much as the current behaviour.  Essentially it asserts that the types of test methods that work, work and the types that don't work, don't work.  The idea was that these tests could be added regardless of whether the later patches were deemed appropriate.  It seemed logical at the time, less so now.

> It would also be worthwhile having an explanatory comment before the two `for` blocks that generate tests. They are reasonably arcane, so it would be good to explain what they are actually testing and why we're generating tests this way rather than writing them the old-fashioned way.

I've since found a better way to create those tests which should be considerably less arcane.

> Using `hasattr(method, '__call__')` seems a bit dodgy to me. Why not use `callable`?

callable is removed in 3.0 I figured it would be good to be forward compatible.

> I'm also a little nervous as to how the change to `unittest.py` will affect old-style classes. Using `type(self)` seems wrong for them, since it will always return `<type 'instance'>`.

Using `self.__class__` should fix that.  I believe it does the same thing for both new and old classes.

>I'd really appreciate it if you could add a test that would fail without the change you made to unittest.py. 

> Phew. I hope that's not too much. Sorry for taking so long to get back to you.

Thanks for the feedback.  I'll resubmit the patch once I've fixed everything.  Should it still be against trunk or against the branch?  And should I break the tests out into a separate patch again?

**Comment by twisted-trac** [comment]
|<img alt="kelly's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_14"></a>|kelly commented|
|-|-|

Replying to [jml](#note_12):
> therve says use `getattr(f, '__call__', None) is not None` rather than `hasattr(f, '__call__')` or `callable`.

Seems a bit circuitous, what's the reason behind that?

**Comment by twisted-trac** [comment]
|<img alt="kelly's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_15"></a>|kelly commented|
|-|-|

Replying to [jml](#note_11):

> I'm also a little nervous as to how the change to `unittest.py` will affect old-style classes. Using `type(self)` seems wrong for them, since it will always return `<type 'instance'>`.

Added some tests under `twisted.trial.test.test_tests.TestInit`. 

`test_absent_im_class` fails spectacularly before the patch.  

I also added `test_parents_oldstyle` with the intention of demonstrating the negative effect using type(self) would've had, at which point I noticed that t.t.unittest.TestCase has been a new style class since r12088.

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)|@jml set owner to @jml|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_18"></a>|@exarkun commented|
|-|-|

(In [27458]) Apply review-1.patch

refs [#2645](https://github.com/twisted/twisted/issues/2645)

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_19"></a>|@exarkun set owner to kelly|
|-|-|

  1. Some coding standard issues:
    1. The patch adds some trailing whitespace in a few places.  You can fix this in emacs with `M-x whitespace-cleanup`.  And you can customize `show-trailing-whitespace` to `t` to make it obvious when this is necessary.
    1. Test methods should be named like `test_fooBar`.  This is a consequence of two things:
      1. `_` is used in Twisted to separate a prefix from a dynamically discovered suffix.
      1. Functions and methods are named with camelCase.
    1. `assertEquals` is preferred over `assertEqual`
    1. Operators should have whitespace around them, eg `1 + 1` rather than `1+1`.  Also `foo: bar` rather than `foo:bar`.
  1. In `twisted/trial/test/test_tests.py`
    1. The ''Test that'' prefix in the `test_absent_im_class` docstring is redundant.
    1. The `test_shared` docstring is missing a word or two, I think.
  1. In `twisted/test/test_reflect.py`
    1. In the comment explaining `prefix_method_descriptor_method`, it's probably worth mentioning how it differs from `prefix_def_method` as well (ie, that looking it up in the `__dict__` directory results in an object of a different type)
    1. The docstring for `test_base_match_one` says _ancestor_ where I think it means _descendant_.
    1. Overall, reading this code, it's hard to stop thinking about how bad a function `addMethodNamesToDict` is.  I think it may be worth leaving it unmodified, opening a ticket for its deprecation, and adding the necessary logic to make trial happy to a new function which doesn't have all the weird `baseClass` behavior that `addMethodNamesToDict` has.  `prefixedMethodNames` is really the API most people want, anyway.
  1. `twisted/trial/util.py`
    1. The `getPythonContainers` change could probably use a direct unit test (`twisted/trial/test/test_util.py` seems like the place for such things)

Thanks!
