### ISSUE TITLE
twisted.internet.abstract.isIPAddress rejects valid IPv4 strings

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#2654]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#2654|
|Type|defect|
|Created|2007-05-16 15:04:23Z|

```127.1``` is an allowed spelling of ```127.0.0.1```.  ```isIPAddress``` returns ```False``` for this input, though.

<details><summary>Searchable metadata</summary>

```
trac-id__2654 2654
type__defect defect
reporter__exarkun exarkun
priority__highest highest
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__wontfix wontfix
component__core core
keywords__ 
time__1179327863000000 1179327863000000
changetime__1180883308000000 1180883308000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)|@glyph set owner to @exarkun|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_2"></a>|@exarkun removed owner|
|-|-|

Done in isipaddress-2654

Numerous other common IPv4 conventions are still unsupported, but if someone wants those, they can add them later.

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_3"></a>|@therve set owner to @exarkun|
|-|-|

Looks good. Please update the copyright of abstract.py, and merge.

For the record, it seems that socket.inet_aton might do the job here. I don't know about the platform support though.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_4"></a>|@exarkun commented|
|-|-|

Yep, inet_aton would work too, on all platforms I think, but I'm not ready to allow ```reactor.connectTCP('0x7f.0x00.0.01', ...)``` or to write tests to make sure it works. :)

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_5"></a>|@exarkun set status to `closed`|
|-|-|

(In [20345]) Merge isipaddress-2654

Author: exarkun
Reviewer: therve
Fixes [#2654](https://github.com/twisted/twisted/issues/2654)

Change twisted.internet.abstract.isIPAddress to accept dotted decimal
strings of four or fewer parts if they are otherwise valid.

**Comment by twisted-trac** [comment]
|[<img alt="jyknight's avatar" src="https://avatars.githubusercontent.com/u/873903?s=50" width="50" height="50">](https://github.com/jyknight)<a name="note_6"></a>|@jyknight set status to `reopened`|
|-|-|

What was the impetus for changing this? This is now incorrect for OSX, as 127.1 is actually *not* an IP address for OSX.

```
Python 2.3.5 (#1, Aug 19 2006, 21:31:42) 
[GCC 4.0.1 (Apple Computer, Inc. build 5363)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> s=socket.socket()
>>> s.connect(('127.1', 22))
Traceback (most recent call last):
  File "<stdin>", line 1, in ?
  File "<string>", line 1, in connect
socket.gaierror: (7, 'No address associated with nodename')
```


Not only that, but it actually sent out a DNS query for the A record for "127.1".

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_7"></a>|@exarkun commented|
|-|-|

Meh, I hate OS X.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_8"></a>|@exarkun commented|
|-|-|

Reverted at r20349.

Why doesn't this work on OS X?  inet_aton seems to behave properly there.  Is this a Python bug or a platform bug?

The impetus for the change is that '127.1' is a widely-accepted spelling for '127.0.0.1', and I wanted it to work with Twisted.

**Comment by twisted-trac** [comment]
|[<img alt="jyknight's avatar" src="https://avatars.githubusercontent.com/u/873903?s=50" width="50" height="50">](https://github.com/jyknight)<a name="note_9"></a>|@jyknight commented|
|-|-|

It's a "platform bug". But I'd hardly call the 127.1 spelling widely-accepted. "It works sometimes" would be more accurate. E.g. host/nslookup, even on linux, doesn't accept it. I'm sure there's many more similar examples of places it is not accepted.

I suspect apple probably considers it a feature that it's not accepted, since its only use is making confusing URLs for phishing.

PS: doesn't work on winxp either.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_10"></a>|@exarkun commented|
|-|-|

But inet_aton _does_ accept it on OS X.  This is why I wonder if it's actually Python's fault this isn't working.  inet_pton does _not_ accept it on Linux; I wonder if connect doesn't work with it on OS X because Python uses inet_pton on OS X.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_11"></a>|@exarkun commented|
|-|-|

Okay, I finally bothered to dig all the way through sock_connect to the getaddrinfo call in setipaddr.  I see that it's the difference in getaddrinfo on Linux and OS X that causes the difference in behavior.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_12"></a>|@exarkun set status to `closed`|
|-|-|

This is a pretty big mess.  Short of implementing an IPv4 address parser and changing isIPAddress to canonicalizeIPv4Address there's probably no reasonable change to make.  Don't really feel like doing that.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
