### ISSUE TITLE
ssh execCommand: closing the connection throws an error

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#2754]
|<img alt="smurfixx's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| smurfixx reported|
|-|-|
|Trac ID|trac#2754|
|Type|defect|
|Created|2007-07-27 10:00:37Z|

My code basically does this:

```
    def execCommand(self, protocol, cmd):
        d = parse_and_run(cmd, out=protocol)
        d.addErrback(lambda _: _.printTraceback(file=protocol))
        d.addBoth(lambda _: protocol.loseConnection())
```

However, I get this error:

```
[...]
  File "modules/ssh.py", line 57, in shut
    protocol.loseConnection()
  File "/usr/lib/python2.5/site-packages/twisted/conch/ssh/session.py", line 194, in connectionLost
    self.session.loseConnection()
  File "/usr/lib/python2.5/site-packages/twisted/conch/ssh/session.py", line 131, in loseConnection
    self.client.transport.loseConnection()
exceptions.AttributeError: 'NoneType' object has no attribute 'loseConnection'

```

Looking at the code, twisted/conch/ssh/session.py (line 130) tests only self.client for None, but not self.client.transport. Adding that test fixes the problem AFAICS.

(Seen on version 2.5.0-0ubuntu3)

Attachments:

* [registerAdapter-2754.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/ea5/ea5fc66a5b8923430d5c3db90ce238ebd95d4058/0af77e11644f9e9f824c62c4f899a53c327e4c89.patch) (1126 bytes) - added by jkk on 2008-04-06 10:48:54Z - 
* [test_ssh-2754.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/ea5/ea5fc66a5b8923430d5c3db90ce238ebd95d4058/f3bc1ef70aa899d94173f21c8e1627905feec203.patch) (5548 bytes) - added by jkk on 2008-06-01 15:17:36Z - Please note that this patch is for ssh-connection-lost-3007 branch
* [conch-server-close.py](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/ea5/ea5fc66a5b8923430d5c3db90ce238ebd95d4058/1b9d31ffeba0d69ee1117fb913552017964d14fa.py) (958 bytes) - added by wulczer on 2013-06-19 09:56:43Z - minimal example to demonstrate the error
* [conch-server-close.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/ea5/ea5fc66a5b8923430d5c3db90ce238ebd95d4058/25b7495a55c4c96967a2a8a26e056712ec78fc5b.patch) (1426 bytes) - added by wulczer on 2013-06-19 09:57:04Z - patch to fix the issue

<details><summary>Searchable metadata</summary>

```
trac-id__2754 2754
type__defect defect
reporter__smurfixx smurfixx
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__conch conch
keywords__ 
time__1185530437000000 1185530437000000
changetime__1371635762000000 1371635762000000
version__None None
owner__ 
cc__jakamkon@... cc__s0undt3ch
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

[#3155](https://github.com/twisted/twisted/issues/3155) was a duplicate of this.

**Comment by twisted-trac** [comment]
|<img alt="jkk's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_2"></a>|jkk commented|
|-|-|

I've just discovered that patch that fix [#3007](https://github.com/twisted/twisted/issues/3007) also fix this problem.

**Comment by twisted-trac** [comment]
|<img alt="jkk's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_3"></a>|jkk commented|
|-|-|

First patch allows registryAdapter to use unregister feature of AdapterRegistry.register.For example: in case of test_ssh, it allows tests to use different server session adapters for a different tests (included test_ssh patch is example of it).It's possible to use components.ALLOW_DUPLICATES=1 instead (without any code changes), but then globalRegistry would grow bigger on every adapter change.

Second patch is based on test_ssh patch from [[#3007](https://github.com/twisted/twisted/issues/3007)](https://github.com/twisted/twisted/issues/3007).I'm not sure if it's good idea or not while it hasn't been yet reviewed, but I wanted to show a specific problem I'm having.Catching an AttributeError in ConchSessionTest_loseConnection.execCommand simply doesn't work and I'm not quite sure why.I reckon it's because of #3007 bug behaviour.Please review and say what you think.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_4"></a>|@exarkun set owner to jkk|
|-|-|

I don't think we want to make that `registerAdapter` change.  The tests can make two different `ConchUser` subclasses and register a different adapter for each one.

Thanks for the patch, sorry it took so long to get reviewed.

**Comment by twisted-trac** [comment]
|<img alt="jkk's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_5"></a>|jkk set status to `assigned`|
|-|-|

Please review a new version of the patch.

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)|@therve set owner to @therve<br>@therve set status to `new`|
|-|-|

**Comment by twisted-trac** [comment]
|<img alt="s0undt3ch's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_8"></a>|s0undt3ch commented|
|-|-|

I'm having the same issues on my code.

On `openShell()` I can use:
```
transport.session.conn.transport.transport.loseConnection()
```

The connection is closed, but if the same solution is applied in `execCommand`, the problem will appear.

I saw the session's code invoking those 2 calls and it's the same, so, what changes the behaviour?

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)<a name="note_10"></a>|@jml commented|
|-|-|

"Me too". We work around this bug by subclassing `SSHSession` and hooking up our avatars to use that.

**Comment by twisted-trac** [comment]
|[<img alt="khorn's avatar" src="https://avatars.githubusercontent.com/u/815352?s=50" width="50" height="50">](https://github.com/khorn)<a name="note_11"></a>|@khorn commented|
|-|-|

this came up in IRC today, and the following link provides a possible workaround:

http://bazaar.launchpad.net/~launchpad-pqm/launchpad/devel/annotate/head%3A/lib/lp/codehosting/sshserver/session.py#L43

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_12"></a>|@exarkun commented|
|-|-|

[#4383](https://github.com/twisted/twisted/issues/4383) may be a duplicate of this.  I'm not sure.  The conversation with its creator is what khorn is referring to in the previous comment.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|<img alt="wulczer's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_14"></a>|wulczer commented|
|-|-|

I've come across the same problem and came up with a much more localised patch. It simply skips calling loseConnection() when receiving a remote close if we're already disconnecting.

Attached is the patch and a minimal code example to reproduce the problem.

Run it with `python conch-server-close.py` and it will listen on port 10022. Then try `ssh -p 10022 127.0.0.1 'CMD'`.

Output without the patch:
```
don't want to exec CMD
Unhandled Error
Traceback (most recent call last):
  File "/home/wulczer/src/twisted-trunk/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/wulczer/src/twisted-trunk/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "/home/wulczer/src/twisted-trunk/twisted/conch/ssh/service.py", line 44, in packetReceived
    return f(packet)
  File "/home/wulczer/src/twisted-trunk/twisted/conch/ssh/connection.py", line 293, in ssh_CHANNEL_CLOSE
    log.callWithLogger(channel, channel.closeReceived)
--- <exception caught here> ---
  File "/home/wulczer/src/twisted-trunk/twisted/python/log.py", line 88, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/wulczer/src/twisted-trunk/twisted/python/log.py", line 73, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/wulczer/src/twisted-trunk/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/wulczer/src/twisted-trunk/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "/home/wulczer/src/twisted-trunk/twisted/conch/ssh/channel.py", line 169, in closeReceived
    self.loseConnection()
  File "/home/wulczer/src/twisted-trunk/twisted/conch/ssh/session.py", line 133, in loseConnection
    self.client.transport.loseConnection()
exceptions.AttributeError: 'NoneType' object has no attribute 'loseConnection'
```

Output with the patch:
```
don't want to exec CMD
```
