### ISSUE TITLE
trial --spew doesn't work in Python 2.5

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#2765]
|[<img alt="radix's avatar" src="https://avatars.githubusercontent.com/u/227068?s=50" width="50" height="50">](https://github.com/radix)| @radix reported|
|-|-|
|Trac ID|trac#2765|
|Type|defect|
|Created|2007-08-01 21:05:16Z|

It starts spewing, but then it stops again before starting to run tests.

<details><summary>Searchable metadata</summary>

```
trac-id__2765 2765
type__defect defect
reporter__radix radix
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__invalid invalid
component__trial trial
keywords__ 
time__1186002316000000 1186002316000000
changetime__1363706925000000 1363706925000000
version__None None
owner__ 
cc__therve cc__ralphm cc__exarkun cc__thijs cc__jesstess
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_1"></a>|@therve commented|
|-|-|

I think I've work around the problem, can you try this:
```
Index: twisted/python/util.py
===================================================================
--- twisted/python/util.py      (revision 20908)
+++ twisted/python/util.py      (working copy)
@@ -12,6 +12,9 @@

 from UserDict import UserDict

+from twisted.python import reflect
+
+
 class InsensitiveDict:
     """Dictionary, that has case-insensitive keys.

@@ -367,7 +370,6 @@

 def spewer(frame, s, ignored):
     """A trace function for sys.settrace that prints every function or method call."""
-    from twisted.python import reflect
     if frame.f_locals.has_key('self'):
         se = frame.f_locals['self']
         if hasattr(se, '__class__'):
```

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_3"></a>|@exarkun commented|
|-|-|

fwiw, this bit of information is amusing, if not useful:

```python
exarkun@boson:~$ twistd --spew
function settrace in threading.py, line 68
Traceback (most recent call last):
  File "/home/exarkun/Projects/Twisted/trunk/twisted/python/util.py", line 366, in spewer
    from twisted.python import reflect
GeneratorExit
```

This, from modifying ```spewer``` to use ```traceback.print_exc()``` if the import raises an exception.

So this is really definitely a CPython bug.  I forget if someone reported it already.

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_4"></a>|@thijstriemstra commented|
|-|-|

Fixed in Python 2.6 perhaps?

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_5"></a>|@exarkun commented|
|-|-|

But still broken in older versions supported by Twisted.  Someone should write a test for therve's fix and then we can apply this.

**Comment by twisted-trac** [comment]
|[<img alt="jesstess's avatar" src="https://avatars.githubusercontent.com/u/188336?s=50" width="50" height="50">](https://github.com/jesstess)<a name="note_6"></a>|@jesstess commented|
|-|-|

After applying therve's change I get the following Traceback when trying to trial anything using 2.5.1. It looks like there's a circular import between reflect.py and util.py.

Traceback (most recent call last):
  File "/usr/bin/trial", line 23, in <module>
    from twisted.scripts.trial import run
  File "/Library/Python/2.5/site-packages/Twisted-8.2.0_r27275-py2.5-macosx-10.5-i386.egg/twisted/scripts/trial.py", line 9, in <module>
    from twisted.internet import defer
  File "/Library/Python/2.5/site-packages/Twisted-8.2.0_r27275-py2.5-macosx-10.5-i386.egg/twisted/internet/defer.py", line 15, in <module>
    from twisted.python import log, failure, lockfile
  File "/Library/Python/2.5/site-packages/Twisted-8.2.0_r27275-py2.5-macosx-10.5-i386.egg/twisted/python/log.py", line 19, in <module>
    from twisted.python import util, context, reflect
  File "/Library/Python/2.5/site-packages/Twisted-8.2.0_r27275-py2.5-macosx-10.5-i386.egg/twisted/python/util.py", line 15, in <module>
    from twisted.python import reflect
  File "/Library/Python/2.5/site-packages/Twisted-8.2.0_r27275-py2.5-macosx-10.5-i386.egg/twisted/python/reflect.py", line 33, in <module>
    from twisted.python.util import unsignedID

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="Julian's avatar" src="https://avatars.githubusercontent.com/u/329822?s=50" width="50" height="50">](https://github.com/Julian)<a name="note_8"></a>|@Julian set status to `closed`|
|-|-|

Support for 2.5 was dropped in 12.1, so this can go away it looks like.
