### ISSUE TITLE
create twistd plugin for vfs

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#2821]
|<img alt="cablehead's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| cablehead reported|
|-|-|
|Trac ID|trac#2821|
|Type|enhancement|
|Created|2007-09-06 19:57:06Z|
|Branch|https://github.com/twisted/twisted/tree/vfs-twistd-plugin-2821-2|

Remove the old crappy vfs examples and bring across the plugin from [branches/makeVFSAsync-1223-2](branches/makeVFSAsync-1223-2) as a replacement example.

<details><summary>Searchable metadata</summary>

```
trac-id__2821 2821
type__enhancement enhancement
reporter__cablehead cablehead
priority__highest highest
milestone__ 
branch__branches_vfs_twistd_plugin_2821_2 branches/vfs-twistd-plugin-2821-2
branch_author__ 
status__closed closed
resolution__wontfix wontfix
component__vfs vfs
keywords__ 
time__1189108626000000 1189108626000000
changetime__1300038038000000 1300038038000000
version__None None
owner__ 
cc__exarkun
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

Can you elaborate on what this plugin will do?

**Comment by twisted-trac** [comment]
|<img alt="cablehead's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_2"></a>|cablehead commented|
|-|-|

This is the plugin I'm planning to bring across:

[branches/makeVFSAsync-1223-2/twisted/vfs/plugins/twisted_vfs.py](branches/makeVFSAsync-1223-2/twisted/vfs/plugins/twisted_vfs.py)

I'm breaking makeVFSAsync-1223-2 into bits, so we can get it incrementally into trunk.

**Comment by twisted-trac** [comment]
|<img alt="cablehead's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_3"></a>|cablehead set status to `assigned`|
|-|-|

Done in branch:

 * [branches/vfs-twistd-plugin-2821](branches/vfs-twistd-plugin-2821)

**Comment by twisted-trac** [comment]
|<img alt="cablehead's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|cablehead removed owner<br>cablehead set status to `new`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="dreid's avatar" src="https://avatars.githubusercontent.com/u/48695?s=50" width="50" height="50">](https://github.com/dreid)<a name="note_5"></a>|@dreid set owner to cablehead|
|-|-|

No docstrings:
 * plugin.FileOptions
 * plugin.MemoryOptions -- the pass can be replaced by a docstring
 * plugin.Realm.__init__ doesn't have a docstring

in plugin.py

the optParameters for 'password-file' is 84 characters long.

line 114 has an extra space after the if:
```
if  options['password-file']:
```

pyflakes output
```
twisted/vfs/plugin.py:16: 'ftp' imported but unused
```

This also doesn't have any unittests.

That's all I see right now, keep up the good work.

**Comment by twisted-trac** [comment]
|<img alt="cablehead's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_6"></a>|cablehead set owner to @dreid|
|-|-|

Replying to [dreid](#note_5):
> No docstrings:
>  * plugin.FileOptions
>  * plugin.MemoryOptions -- the pass can be replaced by a docstring
>  * plugin.Realm.__init__ doesn't have a docstring
>
> in plugin.py
>
> the optParameters for 'password-file' is 84 characters long.
>
> line 114 has an extra space after the if:
> ```
> if  options['password-file']:
> ```

Docstrings added and whitespace fixed up.

> pyflakes output
> ```
> twisted/vfs/plugin.py:16: 'ftp' imported but unused
> ```

Damn the old vfs code is ugly.

twisted.vfs.adapters.ftp is imported to register the IFTPShell adapter.

> This also doesn't have any unittests.

Added some unit tests.

Thanks dried!

**Comment by twisted-trac** [comment]
|[<img alt="dreid's avatar" src="https://avatars.githubusercontent.com/u/48695?s=50" width="50" height="50">](https://github.com/dreid)<a name="note_7"></a>|@dreid set owner to cablehead|
|-|-|

===============================================================================
[FAIL]: twisted.vfs.test.test_plugin.VFSPluginBackendTest.test_none

Traceback (most recent call last):
  File "/Volumes/Users/dreid/projects/Twisted/trunk/twisted/vfs/test/test_plugin.py", line 63, in test_none
    self.assertRaises(usage.UsageError, self._makeService, ['--ftp'])
twisted.trial.unittest.FailTest: <type 'exceptions.UnboundLocalError'> raised instead of UsageError:
 Traceback (most recent call last):
  File "/Volumes/Users/dreid/projects/Twisted/trunk/twisted/trial/unittest.py", line 608, in _run
    self.getSuppress(), method)
  File "/Volumes/Users/dreid/projects/Twisted/trunk/twisted/internet/defer.py", line 107, in maybeDeferred
    result = f(*args, **kw)
  File "/Volumes/Users/dreid/projects/Twisted/trunk/twisted/internet/utils.py", line 144, in runWithWarningsSuppressed
    result = f(*a, **kw)
  File "/Volumes/Users/dreid/projects/Twisted/trunk/twisted/vfs/test/test_plugin.py", line 63, in test_none
    self.assertRaises(usage.UsageError, self._makeService, ['--ftp'])
--- <exception caught here> ---
  File "/Volumes/Users/dreid/projects/Twisted/trunk/twisted/trial/unittest.py", line 152, in failUnlessRaises
    result = f(*args, **kwargs)
  File "/Volumes/Users/dreid/projects/Twisted/trunk/twisted/vfs/test/test_plugin.py", line 25, in _makeService
    return plugin.ServiceMaker().makeService(options).services
  File "/Volumes/Users/dreid/projects/Twisted/trunk/twisted/vfs/plugin.py", line 113, in makeService
    p = portal.Portal(Realm(vfs))
exceptions.UnboundLocalError: local variable 'vfs' referenced before assignment

-------------------------------------------------------------------------------

**Comment by twisted-trac** [comment]
|<img alt="cablehead's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_8"></a>|cablehead set owner to @dreid|
|-|-|

Hey dried,

Something may have gone awry with your merge.

```
  File "/Volumes/Users/dreid/projects/Twisted/trunk/twisted/vfs/plugin.py", line 113, in makeService
    p = portal.Portal(Realm(vfs))
```

The above line is now on 121:

http://twistedmatrix.com/trac/browser/branches/vfs-twistd-plugin-2821/twisted/vfs/plugin.py#L121

cheers again,

**Comment by twisted-trac** [comment]
|[<img alt="dreid's avatar" src="https://avatars.githubusercontent.com/u/48695?s=50" width="50" height="50">](https://github.com/dreid)<a name="note_9"></a>|@dreid set owner to cablehead|
|-|-|

Ok yeah a revert and another unbranch seems to work.

trial with --coverage shows that the Realm is untested and that there is no coverage for registering the FilePasswordDB checker.

**Comment by twisted-trac** [comment]
|<img alt="andy's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_10"></a>|andy commented|
|-|-|

(In [21835]) Branching to 'vfs-twistd-plugin-2821-2'

**Comment by twisted-trac** [comment]
|<img alt="cablehead's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_11"></a>|cablehead set owner to @dreid|
|-|-|

Added tests for the Realm and for registering the FilePasswordDB checker.

Conch's test keys moved since the initial branch for this ticket, so I've merged forward and updated the conch key import for test_plugin.

New branch is: [branches/vfs-twistd-plugin-2821-2](branches/vfs-twistd-plugin-2821-2)

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun set owner to @exarkun<br>@exarkun set status to `assigned`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_13"></a>|@exarkun set owner to cablehead<br>@exarkun set status to `new`|
|-|-|

  * twisted/vfs/plugin.py
    * copyright date should be 2007
    * Module docstring could be a bit more descriptive - ie, describe what the service can actually do.
    * FileOptions docstring should be formatted so triple quotes are on their own lines
    * long description for the ```path``` optParameter might say that it is the root of the published filesystem
    * MemoryOptions docstring should be formatted so triple quotes are on their own lines
    * ''ftp-port'' and ''sftp-port'' optParameters would be better implemented using the Options coercion feature and twisted.python.usage.portCoerce.
    * Realm has no class docstring
    * requestAvatar method has no docstring
    * The ```IFTPShell``` case returns ```None``` for logout which isn't allowed
    * ServiceMaker has no class docstring
    * makeService method has no docstring
    * the ```options.subCommand == ...``` checks in makeService might be better done as methods on the subcommand object - then FileOptions and MemoryOptions can be responsible for knowing what real python objects they represent, instead of putting that logic in the service creation function, letting the service creation function just stick to creating the service.
    * The ```UsageError``` might be better raised from ```Options.postOptions```
    * makeService would also read more clearly if the sftp and ftp stuff was each implemented in a separate method
  * twisted/plugins/twisted_vfs.py
    * copyright date should be 2007
    * module docstring is missing
    * twisted/vfs/plugin.py imports a ton of stuff; twisted/plugins/twisted_vfs.py imports twisted/vfs/plugin.py, so anything which does plugin lookups in twisted will load a big part of twisted because of the vfs plugin definition.  This is partly due to some problems with the plugin system, but it can be avoided by delaying imports until makeService is actually called.
  * twisted/vfs/test/test_plugin.py
    * VFSPluginTestMixin doesn't need the tearDown method it has
    * If tearDown doesn't exist, then there's no reason to have ```self.tmpdir``` instead of just returning the temporary directory's path from ```_createTmpDir``` (less stateful stuff is good)
    * VFSPluginTestMixin isn't really a mixin, since it subclasses TestCase.  The naming convention here might be something like ```VFSPluginTestBase```.
    * If makeService is split up into multiple methods, it'll be easier to unit test various bits of the functionality. (ie, without needing to do ```services[0].args[1].portal.realm.vfs```
    * ```test_password_default``` and ```test_password_file``` should be named ```test_passwordDefault``` and ```test_passwordFile```
    * ```file``` is preferred to ```open``` and ```FilePath(path).setContent(bytes)``` is preferred to ```file(name, 'w').write(bytes)```
    * ```test_badInterface``` isn't wrong, but passing ```IUsernamePassword``` there is a little weird.

**Comment by twisted-trac** [comment]
|<img alt="andy's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_14"></a>|andy commented|
|-|-|

(In [24142]) Branching to 'vfs-twistd-plugin-2821-2'

**Comment by twisted-trac** [comment]
|<img alt="cablehead's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_15"></a>|cablehead set owner to @exarkun|
|-|-|

 * set copyright dates to 2008
 * made module vfs/plugin.py docstring a bit more descriptive
 * formatted class docstrings so that triple quotes are on their own lines
 * improve long description for the FileOptions path option
 * added doc string for Realm class
 * added doc string for requestAvatar and ServiceMaker.makeService
 * return the logout method on the IFTPShell user adaptor, if available
 * add docstring for the ServiceMaker class
 * delay imports as much as possible to improve plugin lookup performance
 * add docstrings for the twisted.plugins.twisted_vfs module
 * rename VFSPluginTestMixin to VFSPluginTestBase as that's what it is
 * just return tmpdir from _createTmpDir in vfs/test/test_plugin.py
 * rename test_password_default and test_password_file to meet standards
 * make use of FilePath for creating temporary files for testing
 * be less weird with VFSPluginRealmTest.test_badInterface
 * make use of usage.PortCoerce
 * move creating the sftp and ftp services, the vfs backend and the checker into seperate methods
 * move usage validation into Options.postOptions
 * rework tests to call the new methods on options instead of make service directly

These changes are in branch: [branches/vfs-twistd-plugin-2821-2](branches/vfs-twistd-plugin-2821-2)

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_16"></a>|@exarkun set owner to cablehead|
|-|-|

Looking pretty good.  Still a few things to take care of, Ithink:

  * twisted/plugins/twisted_vfs.py
    * copyright date needs to be updated
  * twisted/vfs/plugin.py
    * some trailing whitespace
    * instead of `--password-file`/`getChecker`, it'd probably be cool to use `twisted.cred.strcred`.  I think this should be mandatory, instead of defaulting to admin/admin
    * the sftp server only works with dsa host keys.  This is annoying, particularly since dsa keys are crummy. :)  I also can't actually manage to establish an sftp connection to the server, OpenSSH sftp client claims "no hostkey alg".
    * `ServiceMaker.makeService` appears to be untested
  * twisted/vfs/test/test_plugin.py
    * some trailing whitespace
    * `assertTrue` is preferred to `failUnless`
    * use two blank lines between methods, three between classes
    * `IBadInterface` also isn't wrong, but having it subclass `ICredentials` is weird. :P  More generally, it's rare to use a credentials interface as av avatar interface (in fact, I've never seen a real app do it).  I think `IBadInterface` should just subclass `Interface`.
    * test method docstrings should also describe the behavior they're testing, not just say what high-level feature is being tested.  Hm, when put that way, the distinction isn't really clear.  Here's an example.  Instead of ''Test requesting an unknown interface from the realm'', say ''L{Realm.requestAvatar} raises L{NotImplementedError} when passed an avatar interface which isn't supported.''

I'd also suggest making `twisted/vfs/plugin.py` private.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_18"></a>|@exarkun set status to `closed`|
|-|-|

VFS has been removed ([#4934](https://github.com/twisted/twisted/issues/4934))
