### ISSUE TITLE
Reactor claims not be running although reactor.run() has been called

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#2854]
|<img alt="htj's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| htj reported|
|-|-|
|Trac ID|trac#2854|
|Type|defect|
|Created|2007-10-22 13:54:03Z|

Hi

The following code fails in current twisted trunk:

```

from twisted.internet import reactor, defer

def main():
    reactor.stop()
    return

if __name__ == '__main__':
    reactor.callWhenRunning(main)
    reactor.run()
```

The output is:
```
Unhandled error in Deferred:
Traceback (most recent call last):
  File "/home/htj/pack/python/twisted/internet/base.py", line 389, in _continueFiring
    callable(*args, **kwargs)
  File "ting.py", line 8, in main
    d.addBoth(lambda _ : reactor.stop())
  File "/home/htj/pack/python/twisted/internet/defer.py", line 210, in addBoth
    callbackKeywords=kw, errbackKeywords=kw)
  File "/home/htj/pack/python/twisted/internet/defer.py", line 182, in addCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/home/htj/pack/python/twisted/internet/defer.py", line 317, in _runCallbacks
    self.result = callback(self.result, *args, **kw)
  File "ting.py", line 4, in main
    reactor.stop()
  File "/home/htj/pack/python/twisted/internet/base.py", line 480, in stop
    raise RuntimeError, "can't stop reactor that isn't running"
exceptions.RuntimeError: can't stop reactor that isn't running
```

This has worked well in previous versions if twisted. Am I doing anything wrong?
If I start doing actual IO the above structure works well.

I've tracked down the change in behaviour to be in internet/base.py from changeset 20909:
http://twistedmatrix.com/trac/changeset/20909

Although I do not really an idea of whats causing it.

I'm not quite sure how to have this as a trial test, it seems to be related to events during startup.

<details><summary>Searchable metadata</summary>

```
trac-id__2854 2854
type__defect defect
reporter__htj htj
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__ 
time__1193061243000000 1193061243000000
changetime__1231346289000000 1231346289000000
version__None None
owner__ 
cc__therve cc__exarkun
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="htj's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_1"></a>|htj commented|
|-|-|

enhancement -> defect

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_2"></a>|@exarkun commented|
|-|-|

Apparently ```running``` used to be set to ```1``` after the _before_ phase of the _startup_ event in all cases.  Now, if there are no _before_ phase triggers for the _startup_ event which return Deferreds which have not already been called back, ```running``` will not be set to ```1``` until after all _before_ phase _startup_ triggers have run.  This includes triggers added via ```callWhenRunning```.

I suppose the old behavior should be restored.  Obviously, as part of that, tests for ```running``` should be added.  Hopefully just as obviously, the exact semantics of ```running``` should probably be documented (however, I still think ```running``` is a private attribute of the reactor.  It is unfortunate that it does not have an ```_``` prefix).

This is a regression introduced by r20909.  If conflicts which would make it difficult have not yet been introduced, that revision should be reverted, fixed, re-reviewed, and re-merged.

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_4"></a>|@therve commented|
|-|-|

The great thing (or maybe not), is that it has been fixed in r21395. At least, the reported problem doesn't appear anymore.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_5"></a>|@exarkun commented|
|-|-|

Some new tests should still be added

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_7"></a>|@exarkun set status to `closed`|
|-|-|

This behavior is tested by `twisted.internet.test.test_core.SystemEventTestsBuilder.test_stopWhenAlreadyStopped`.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
