### ISSUE TITLE
twisted.test.test_pb.BrokerTestCase.test_publishable fails on windows sometimes

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#2879]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#2879|
|Type|defect|
|Created|2007-11-09 14:35:50Z|

Exciting traceback:

```
===============================================================================
[ERROR]: twisted.test.test_pb.BrokerTestCase.test_publishable

Traceback (most recent call last):
  File "c:\twistedbuildbot24\WXP32-full2.5-scmikes-select\Twisted\twisted\test\test_pb.py", line 732, in test_publishable
    pump.flush()
  File "c:\twistedbuildbot24\WXP32-full2.5-scmikes-select\Twisted\twisted\test\test_pb.py", line 71, in flush
    while self.pump():
  File "c:\twistedbuildbot24\WXP32-full2.5-scmikes-select\Twisted\twisted\test\test_pb.py", line 94, in pump
    self.client.dataReceived(byte)
  File "c:\twistedbuildbot24\WXP32-full2.5-scmikes-select\Twisted\twisted\spread\banana.py", line 218, in dataReceived
    gotItem(item)
  File "c:\twistedbuildbot24\WXP32-full2.5-scmikes-select\Twisted\twisted\spread\banana.py", line 148, in gotItem
    self.callExpressionReceived(item)
  File "c:\twistedbuildbot24\WXP32-full2.5-scmikes-select\Twisted\twisted\spread\banana.py", line 113, in callExpressionReceived
    self.expressionReceived(obj)
  File "c:\twistedbuildbot24\WXP32-full2.5-scmikes-select\Twisted\twisted\spread\pb.py", line 522, in expressionReceived
    method(*sexp[1:])
  File "c:\twistedbuildbot24\WXP32-full2.5-scmikes-select\Twisted\twisted\spread\pb.py", line 891, in proto_answer
    d.callback(self.unserialize(netResult))
  File "c:\twistedbuildbot24\WXP32-full2.5-scmikes-select\Twisted\twisted\spread\pb.py", line 783, in unserialize
    return unjelly(sexp, self.security, None, self)
  File "c:\twistedbuildbot24\WXP32-full2.5-scmikes-select\Twisted\twisted\spread\jelly.py", line 900, in unjelly
    return _Unjellier(taster, persistentLoad, invoker).unjellyFull(sexp)
  File "c:\twistedbuildbot24\WXP32-full2.5-scmikes-select\Twisted\twisted\spread\jelly.py", line 523, in unjellyFull
    o = self.unjelly(obj)
  File "c:\twistedbuildbot24\WXP32-full2.5-scmikes-select\Twisted\twisted\spread\jelly.py", line 546, in unjelly
    val = method(self, obj)
  File "c:\twistedbuildbot24\WXP32-full2.5-scmikes-select\Twisted\twisted\spread\flavors.py", line 458, in unjellyFor
    cProxy.setCopyableState(unjellier.unjelly(jellyList[2]))
  File "c:\twistedbuildbot24\WXP32-full2.5-scmikes-select\Twisted\twisted\spread\publish.py", line 86, in setCopyableState
    newself = jelly.unjelly(banana.decode(data))
  File "c:\twistedbuildbot24\WXP32-full2.5-scmikes-select\Twisted\twisted\spread\banana.py", line 353, in decode
    return l[0]
exceptions.IndexError: list index out of range
-------------------------------------------------------------------------------
```

<details><summary>Searchable metadata</summary>

```
trac-id__2879 2879
type__defect defect
reporter__exarkun exarkun
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__duplicate duplicate
component__core core
keywords__ 
time__1194618950000000 1194618950000000
changetime__1214834094000000 1214834094000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun set status to `closed`|
|-|-|

Duplicate of [#2327](https://github.com/twisted/twisted/issues/2327)

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
