### ISSUE TITLE
mime-type option for web2 causes error

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#2989]
|[<img alt="djfroofy's avatar" src="https://avatars.githubusercontent.com/u/89760?s=50" width="50" height="50">](https://github.com/djfroofy)| @djfroofy reported|
|-|-|
|Trac ID|trac#2989|
|Type|defect|
|Created|2008-01-10 21:13:58Z|

```
$  twistd web2 --path=blah/ --mimetype="jsp=text/html"
Traceback (most recent call last):
  File "/opt/pyinstances/twisted/bin/twistd", line 21, in <module>
    run()
  File "/opt/pyinstances/twisted/lib/python2.5/site-packages/twisted/scripts/twistd.py", line 27, in run
    app.run(runApp, ServerOptions)
  File "/opt/pyinstances/twisted/lib/python2.5/site-packages/twisted/application/app.py", line 425, in run
    config.parseOptions()
  File "/opt/pyinstances/twisted/lib/python2.5/site-packages/twisted/application/app.py", line 405, in parseOptions
    usage.Options.parseOptions(self, options)
  File "/opt/pyinstances/twisted/lib/python2.5/site-packages/twisted/python/usage.py", line 231, in parseOptions
    self.subOptions.parseOptions(rest)
  File "/opt/pyinstances/twisted/lib/python2.5/site-packages/twisted/python/usage.py", line 219, in parseOptions
    self._dispatch[optMangled](optMangled, arg)
  File "/opt/pyinstances/twisted/lib/python2.5/site-packages/twisted/python/usage.py", line 373, in <lambda>
    fn = lambda name, value, m=method: m(value)
  File "/opt/pyinstances/twisted/lib/python2.5/site-packages/twisted/web2/tap.py", line 137, in opt_mimetype
    self['root']._sharedContentTypes.update({ext: mimetype})
AttributeError: 'File' object has no attribute '_sharedContentTypes'
```

<details><summary>Searchable metadata</summary>

```
trac-id__2989 2989
type__defect defect
reporter__djfroofy djfroofy
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__wontfix wontfix
component__web2 web2
keywords__ 
time__1199999638000000 1199999638000000
changetime__1301189730000000 1301189730000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="dreid's avatar" src="https://avatars.githubusercontent.com/u/48695?s=50" width="50" height="50">](https://github.com/dreid)<a name="note_1"></a>|@dreid commented|
|-|-|

(In [22700]) Tap test cases, fix some bugs involving indexes default value and mimetype.

Refs [#3051](https://github.com/twisted/twisted/issues/3051), [#2989](https://github.com/twisted/twisted/issues/2989)

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_3"></a>|@exarkun set status to `closed`|
|-|-|

Since [#4821](https://github.com/twisted/twisted/issues/4821) is now resolved, there is no more `twistd web2` command line tool, so this bug is no longer in code we have.  The `--mime-type` option for `twistd web` works differently, and doesn't seem to have a similar issue, so the bug doesn't apply to Twisted Web either.
