### ISSUE TITLE
twisted.conch.ssh.keys.Key._fromString_PRIVATE_OPENSSH fails on RSA keys

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3008]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#3008|
|Type|enhancement|
|Created|2008-01-23 15:16:57Z|
|Branch|https://github.com/twisted/twisted/tree/broken-private-key-3008|

```
          File "/home/exarkun/Projects/Twisted/trunk/twisted/conch/ssh/keys.py", line 186, in _fromString_PRIVATE_OPENSSH
            n, e, d, p, q = decodedKey[1:6]
        exceptions.ValueError: need more than 1 value to unpack
```

```decodedKey``` appears to be a list of one element containing the desired values.

This is a regression from the previous release.

Attachments:

* [temp](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/2ec/2ec22303caffe3c4a2a675a85aa5bde87da43c8a/d969831eb8a99cff8c02e681f43289e5d3d69664) (1675 bytes) - added by exarkun on 2008-02-20 17:50:53Z - rsa private key

<details><summary>Searchable metadata</summary>

```
trac-id__3008 3008
type__enhancement enhancement
reporter__exarkun exarkun
priority__highest highest
milestone__twisted_8_0 twisted-8.0
branch__branches_broken_private_key_3008 branches/broken-private-key-3008
branch_author__ 
status__closed closed
resolution__fixed fixed
component__conch conch
keywords__ 
time__1201101417000000 1201101417000000
changetime__1230850780000000 1230850780000000
version__None None
owner__ 
cc__exarkun
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="z3p's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_1"></a>|z3p commented|
|-|-|

(In [22635]) Branching to 'broken-private-key-3008'

**Comment by twisted-trac** [comment]
|<img alt="z3p's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_2"></a>|z3p set status to `assigned`|
|-|-|

Where are you seeing this problem?  I'm not seeing it in the test cases, nor when I loaded my own OpenSSH private key.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_3"></a>|@exarkun commented|
|-|-|

Here's a transcript:

```
exarkun@boson:~/temp$ ssh -V
OpenSSH_4.6p1 Debian-5ubuntu0.1, OpenSSL 0.9.8e 23 Feb 2007
exarkun@boson:~/temp$ ssh-keygen -t rsa
Generating public/private rsa key pair.
Enter file in which to save the key (/home/exarkun/.ssh/id_rsa): id_rsa
Enter passphrase (empty for no passphrase):
Enter same passphrase again:
Your identification has been saved in id_rsa.
Your public key has been saved in id_rsa.pub.
The key fingerprint is:
42:a9:de:e4:c3:4c:32:4e:e8:f4:41:1c:a0:3f:9f:42 exarkun@boson
exarkun@boson:~/temp$ python
Python 2.5.1 (r251:54863, Oct  5 2007, 13:36:32)
[GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from twisted.conch.ssh.keys import Key
>>> Key.fromString(file('id_rsa').read())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/exarkun/Projects/Twisted/trunk/twisted/conch/ssh/keys.py", line 89, in fromString
    return method(data, passphrase)
  File "/home/exarkun/Projects/Twisted/trunk/twisted/conch/ssh/keys.py", line 185, in _fromString_PRIVATE_OPENSSH
    n, e, d, p, q = decodedKey[1:6]
ValueError: need more than 1 value to unpack
>>>
```

I just noticed this _doesn't_ happen with the version of ssh in Dapper, though.  It could be that this isn't a regression, but an incompatibility with the new version of OpenSSH?

**Comment by twisted-trac** [comment]
|<img alt="z3p's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_4"></a>|z3p commented|
|-|-|

I just tried that here, with the same version of OpenSSH, but didn't get the error.  Can you send me or attach that key that you generated?

**Comment by twisted-trac** [comment]
|<img alt="z3p's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_5"></a>|z3p removed owner<br>z3p set status to `new`|
|-|-|

Ready for review.

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_6"></a>|@therve set owner to z3p|
|-|-|

* pyflakes: ```twisted/conch/ssh/keys.py:24: 'log' imported but unused```
 * keydata should have a copyright notice
 * please update the copyright of the 2 other files.

It looks good, and solves the reported problem. Please merge once corrected.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_7"></a>|@glyph set status to `closed`|
|-|-|

(In [22762]) Fix parsing of OpenSSH-generated RSA keys with differing ASN.1 packing style.

Author: z3p

Reviewer: therve

Fixes [#3008](https://github.com/twisted/twisted/issues/3008)

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_8"></a>|@exarkun commented|
|-|-|

[#3448](https://github.com/twisted/twisted/issues/3448) was a duplicate of this.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
