### ISSUE TITLE
Problem installing twisted2.5.0 on Solaris 10 (x86_64) using pyhton2.5.1.... zope issue

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3043]
|<img alt="shaunos's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| shaunos reported|
|-|-|
|Trac ID|trac#3043|
|Type|defect|
|Created|2008-02-20 13:52:26Z|

Hi,

When I try to install twisted it complains that it can't find zope even though it has been installed.

Here's the output from the zope installation:
```
COPS-pubtools62% cd zope.interface-3.3.0
COPS-pubtools63% python ./setup.py install --prefix=/projects/install_dub/cops/tools/sol86
running install
running build
running build_py
running build_ext
running install_lib
running install_egg_info
Removing
/projects/install_dub/cops/tools/sol86/lib/python2.5/site-packages/zope.interface-3.3.0-py2.5.egg-info
Writing 
/projects/install_dub/cops/tools/sol86/lib/python2.5/site-packages/zope.interface-3.3.0-py2.5.egg-info
COPS-pubtools64% 
```

Next I step back a directory to install the twisted components and get the following output:
```
COPS-pubtools64% cd ..
COPS-pubtools65% python ./setup.py install --prefix=/projects/install_dub/cops/tools/sol86
Traceback (most recent call last):
  File "setup.py", line 20, in <module>
    from twisted import copyright
  File "./twisted/__init__.py", line 22, in <module>
    raise ImportError("you need zope.interface installed "
ImportError: you need zope.interface installed (http://zope.org/Products/ZopeInterface/)
Error: Subprocess exited with result 1 for project core
COPS-pubtools66%
```

Here's some other system information:
```
COPS-pubtools69% python --version
Python 2.5.1
COPS-pubtools70%
COPS-pubtools90% uname -a
SunOS itgsol10 5.10 Generic_118855-33 i86pc i386 i86pc
COPS-pubtools91%
```

Have you seen this before?

FYI, I have successfully installed (and using) Twisted 2.5.0 with Python2.5.1 on Solaris8 (sparc), `RedHatEnterprise` 3.0, AIX5.3.

Cheers,

Shaun.

<details><summary>Searchable metadata</summary>

```
trac-id__3043 3043
type__defect defect
reporter__shaunos shaunos
priority__high high
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__worksforme worksforme
component__core core
keywords__ 
time__1203515546000000 1203515546000000
changetime__1204025737000000 1204025737000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_2"></a>|@therve commented|
|-|-|

That probably means that /projects/install_dub/cops/tools/sol86/lib/python2.5/ isn't in your PYTHONPATH.

Can you try this:
```
PYTHONPATH=/projects/install_dub/cops/tools/sol86/lib/python2.5/site-packages python ./setup.py install --prefix=/projects/install_dub/cops/tools/sol86
```

FWIW, it's not really a problem related to twisted. If you can import zope.interface in python, it will work for twisted.

**Comment by twisted-trac** [comment]
|<img alt="shaunos's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_3"></a>|shaunos commented|
|-|-|

I had thought something similar too but no joy I'm afraid.....

<SNIP>
COPS-pubtools94% setenv PYTHONPATH /projects/install_dub/cops/tools/sol86/lib/python2.5/site-packages
COPS-pubtools95% python ./setup.py install --prefix=/projects/install_dub/cops/tools/sol86
Traceback (most recent call last):
  File "./setup.py", line 20, in <module>
    from twisted import copyright
  File "./twisted/__init__.py", line 22, in <module>
    raise ImportError("you need zope.interface installed "
ImportError: you need zope.interface installed (http://zope.org/Products/ZopeInterface/)
COPS-pubtools96%
</SNIP>


~Shaun.

**Comment by twisted-trac** [comment]
|<img alt="shaunos's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_4"></a>|shaunos commented|
|-|-|

Replying to [therve](#note_2):
> That probably means that /projects/install_dub/cops/tools/sol86/lib/python2.5/ isn't in your PYTHONPATH.
>
> Can you try this:
> ```
> PYTHONPATH=/projects/install_dub/cops/tools/sol86/lib/python2.5/site-packages python ./setup.py install --prefix=/projects/install_dub/cops/tools/sol86
> ```
>
> FWIW, it's not really a problem related to twisted. If you can import zope.interface in python, it will work for twisted.

I've tried setting PYTHONPATH environment variable to no avail.
I've even tried appending to sys.path in __init__.py (see below) to no avail.....

<SNIP>
# Ensure zope.interface is installed
import sys
sys.path.append("/projects/install_dub/cops/tools/sol86/lib/python2.5/site-packages")
try:
    from zope.interface import Interface
    del Interface
except ImportError:
    raise ImportError("you need zope.interface installed "
                      "(http://zope.org/Products/ZopeInterface/)")
del sys
</SNIP>

Zope appeared to get installed ok
<SNIP>
COPS-pubtools104% ls /projects/install_dub/cops/tools/sol86/lib/python2.5/site-packages/
Conch-0.8.0-py2.5.egg-info                buildbot-0.7.6-py2.5.egg-info             zope.interface-3.3.0-py2.5.egg-info
README                                    twisted/                                  zope.interface-3.3.0-py2.5.egg-info_mvd
buildbot/                                 zope/                                     zope_mvd/
COPS-pubtools105%
</SNIP>

Any ideas why the twisted core __init__.py can't import the zope stuff??

I'm relatively new to python etc so any pointers would be appreciated...

Cheers,

Shaun.

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_5"></a>|@therve commented|
|-|-|

Twisted doesn't make any thing magic. If you can import zope.interface in python, twisted will be able to import it too. As it a 64 bits system, maybe you have this problem : FrequentlyAskedQuestions#WhyamIgettingImportErrorsforTwistedsubpackagesonmy64bitinstallationofRedHatFedoraCentOS ?

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_6"></a>|@therve set status to `closed`|
|-|-|

I close this. This is not really a problem anyway, it should just find zope installed. Please reopen if you have a more specific problem.

**Comment by twisted-trac** [comment]
|<img alt="shaunos's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_7"></a>|shaunos commented|
|-|-|

Replying to [therve](#note_6):
> I close this. This is not really a problem anyway, it should just find zope installed. Please reopen if you have a more specific problem.


Hi,

I have resolved this issue. The error message is a bit misleading.
The code involved is the following:


```
try:
    from zope.interface import Interface
    del Interface
except ImportError:
    raise ImportError("you need zope.interface installed "
                      "(http://zope.org/Products/ZopeInterface/)")
del sys

```


Unfortunately the exception gets thrown if there is *any* error during the import.
In my case the actual error was that it couldn't find libgcc.so in my LD_LIBRARY_PATH.
I discovered this by trussing the command (See below for output).


```
xstat(2, "/projects/install_dub/cops/tools/sol86/qt432/lib/libgcc_s.so.1", 0x08041200) Err#2 ENOENT
xstat(2, "/projects/install_dub/cops/tools/sol86/lib/libgcc_s.so.1", 0x08041200) Err#2 ENOENT
xstat(2, "/grid/common/pkgs/forte/v11.0p2/SUNWspro/lib/libgcc_s.so.1", 0x08041200) Err#2 ENOENT
xstat(2, "/usr/lib/libgcc_s.so.1", 0x08041200)	Err#2 ENOENT
xstat(2, "/usr/openwin/lib/libgcc_s.so.1", 0x08041200) Err#2 ENOENT
xstat(2, "/lib/libgcc_s.so.1", 0x08041200)	Err#2 ENOENT
xstat(2, "/usr/lib/libgcc_s.so.1", 0x08041200)	Err#2 ENOENT
munmap(0xFECB0000, 2614)			= 0
munmap(0xFECC0000, 3452)			= 0
munmap(0xFECA0000, 4096)			= 0
munmap(0xFECD0000, 4096)			= 0
llseek(7, 0, SEEK_CUR)				= 0
close(7)					= 0
llseek(6, 0, SEEK_CUR)				= 0
close(6)					= 0
llseek(5, 0, SEEK_CUR)				= 0
close(5)					= 0
llseek(4, 0, SEEK_CUR)				= 0
close(4)					= 0
llseek(3, 0, SEEK_CUR)				= 0
close(3)					= 0
fstat64(2, 0x08046E40)				= 0
write(2, " T r a c e b a c k   ( m".., 35)	= 35
open64("./setup.py", O_RDONLY)			= 3
write(2, "     F i l e   " . / s e".., 42)	= 42
fstat64(3, 0x080462D0)				= 0
fstat64(3, 0x08046210)				= 0
ioctl(3, TCGETA, 0x080462A4)			Err#25 ENOTTY
read(3, " # ! / u s r / b i n / e".., 8192)	= 3655
write(2, "        ", 4)				= 4
write(2, " f r o m   t w i s t e d".., 30)	= 30
llseek(3, 0xFFFFFFFFFFFFF38B, SEEK_CUR)		= 466
close(3)					= 0
open64("./twisted/__init__.py", O_RDONLY)	= 3
write(2, "     F i l e   " . / t w".., 53)	= 53
fstat64(3, 0x080462D0)				= 0
fstat64(3, 0x08046210)				= 0
ioctl(3, TCGETA, 0x080462A4)			Err#25 ENOTTY
read(3, " #   - * -   t e s t - c".., 8192)	= 893
write(2, "        ", 4)				= 4
write(2, " r a i s e   I m p o r t".., 55)	= 55
llseek(3, 0xFFFFFFFFFFFFFF15, SEEK_CUR)		= 658
close(3)					= 0
write(2, " I m p o r t E r r o r", 11)		= 11
write(2, " :  ", 2)				= 2
write(2, " y o u   n e e d   z o p".., 75)	= 75
write(2, "\n", 1)				= 1
sigaction(SIGINT, 0x08047110, 0x08047160)	= 0
_exit(1)
```


Maybe you could update the error message to indicate that zope not being installed may not be the only error or can you do a more specific test?

Anyway just thought I'd post an update with my actual issue resolution.

Cheers,

Shaun.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
