### ISSUE TITLE
twisted.internet.tcp.Client.getPeer incorrectly returns hostnames

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3059]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#3059|
|Type|defect|
|Created|2008-02-28 20:53:28Z|
|Branch|https://github.com/twisted/twisted/tree/getpeer-hostname-3059-2|

If a hostname is passed to `connectTCP`, it will appear in the peer address.  The `IPv4Address` should always have the IP address instead.

The `IConnector` returned by `connectTCP` seems to have the same problem with its `getDestination` method.  This is a bit trickier, since the connector is available synchronously, whereas name resolution is asynchronous...

<details><summary>Searchable metadata</summary>

```
trac-id__3059 3059
type__defect defect
reporter__exarkun exarkun
priority__high high
milestone__ 
branch__branches_getpeer_hostname_3059_2 branches/getpeer-hostname-3059-2
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__ 
time__1204232008000000 1204232008000000
changetime__1265388142000000 1265388142000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_1"></a>|@glyph commented|
|-|-|

This highlights another deficiency in `Connector` as well; its job should be reserved for something like endpoints.

If `getDestination` is supposed to answer the question "where will this connector reconnect to" then it is fundamentally broken.  Passing a hostname to `connectTCP` and then calling `connect` on the connector ought to reconnect to the hostname, including name resolution (honoring, for example, round-robin DNS if it is configured for that host).

Perhaps we should simply remove that method, or give it a different return type if a hostname was specified?  (Returning an IPv4Address with a hostname in it is definitely wrong, no argument there.)

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_2"></a>|@exarkun commented|
|-|-|

(In [23993]) Branching to 'getpeer-hostname-3059'

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_3"></a>|@exarkun removed owner|
|-|-|

`Client.getPeer` fixed

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_4"></a>|@therve set owner to @exarkun|
|-|-|

Please merge.

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_5"></a>|@therve commented|
|-|-|

Oups, this fails under iocpreactor:
```
[FAIL]: twisted.internet.test.test_tcp.TCPClientTestsBuilder_IOCPReactor.test_addresses

Traceback (most recent call last):
  File "s:\buildbots\twisted\server-2k8-x86-py2.5-select\Twisted\twisted\internet\test\test_tcp.py", line 111, in test_addresses
    IPv4Address('TCP', '127.0.0.1', serverAddress.port))
twisted.trial.unittest.FailTest: not equal:
a = <twisted.internet.address.IPv4Address object at 0x01C7CE70>
b = <twisted.internet.address.IPv4Address object at 0x01C58270>
```

I guess this is because of useless code duplication :/

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_6"></a>|@exarkun commented|
|-|-|

(In [24055]) realAddress

refs [#3059](https://github.com/twisted/twisted/issues/3059)

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_7"></a>|@exarkun commented|
|-|-|

Duplicated the fix.  Building here - 
http://buildbot.twistedmatrix.com/builders/server-2k8-x86-py2.5-iocp/builds/83

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_8"></a>|@exarkun commented|
|-|-|

(In [24057]) Branching to 'getpeer-hostname-3059-2'

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_9"></a>|@exarkun removed owner|
|-|-|

Okay, that build failed.  More recent results - <http://buildbot.twistedmatrix.com/builders/server-2k8-x86-py2.5-iocp/builds/88>, <http://buildbot.twistedmatrix.com/builders/winxp32-py2.5-iocp/builds/117>, including a fix to correctly propagate the right reactor in tcp.py that I pulled out of the [#3218](https://github.com/twisted/twisted/issues/3218) branch.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_10"></a>|@glyph set owner to @exarkun|
|-|-|

Among other things:

```
===============================================================================
[ERROR]: twisted.test.test_unix.UnixSocketTestCase.test_pidFile

Traceback (most recent call last):
  File "/home/glyph/Projects/Twisted/trunk/twisted/internet/tcp.py", line 834, in doRead
    transport = self.transport(skt, protocol, addr, self, s, self.reactor)
exceptions.TypeError: __init__() takes exactly 6 arguments (7 given)
```

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_11"></a>|@exarkun commented|
|-|-|

(In [24089]) funny, I forgot to do this last time, too

refs [#3059](https://github.com/twisted/twisted/issues/3059)

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_12"></a>|@exarkun removed owner|
|-|-|

Most recent results - http://buildbot.twistedmatrix.com/boxes-supported?branch=/branches/getpeer-hostname-3059-2

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_13"></a>|@therve set owner to @exarkun|
|-|-|

Please merge.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_14"></a>|@exarkun set status to `closed`|
|-|-|

(In [24132]) Merge getpeer-hostname-3059-2

Author: exarkun
Reviewer: glyph, therve
Fixes: [#3059](https://github.com/twisted/twisted/issues/3059)

Fix the implementations of `getPeer` for client transports so that
if the connection was made using a hostname, the returned `IPv4Address`
still contains an IPv4 address instead of the hostname.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_15"></a>|@exarkun commented|
|-|-|

This was a duplicate of [#2738](https://github.com/twisted/twisted/issues/2738).

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
