### ISSUE TITLE
twisted.words.xish.utility.addOnetimeObserver can register a permanent xml stream observer

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3066]
|<img alt="jgill's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| jgill reported|
|-|-|
|Trac ID|trac#3066|
|Type|defect|
|Created|2008-03-04 01:03:21Z|
|Branch|https://github.com/twisted/twisted/tree/xish-nested-dispatch-3066|

twisted.words.xish.utility.addOnetimeObserver() adds an observer to an XPath event on an xml stream.  Under some situations the method will defer appending the callback to the callback queue, e.g. if is in the middle of a dispatch call.  The queued command, however, calls addObserver() rather than _addObserver(), and therefore drops the 'onetime' flag.

A simple fix might be to change the lambda call near the start of _addObserver() from

lambda:self.addObserver(event, observerfn, priority, *args, **kwargs)

to:

lambda:self._addObserver(onetime, event, observerfn, priority, *args, **kwargs)

<details><summary>Searchable metadata</summary>

```
trac-id__3066 3066
type__defect defect
reporter__jgill jgill
priority__high high
milestone__None None
branch__branches_xish_nested_dispatch_3066 branches/xish-nested-dispatch-3066
branch_author__ 
status__closed closed
resolution__fixed fixed
component__words words
keywords__ 
time__1204592601000000 1204592601000000
changetime__1211199884000000 1211199884000000
version__None None
owner__ 
cc__jgill cc__ralphm cc__therve
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="jgill's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_1"></a>|jgill set owner to @exarkun|
|-|-|

Part of words package.

**Comment by twisted-trac** [comment]
|[<img alt="ralphm's avatar" src="https://avatars.githubusercontent.com/u/116741?s=50" width="50" height="50">](https://github.com/ralphm)<a name="note_2"></a>|@ralphm set owner to @ralphm|
|-|-|

Reading that piece of code, this indeed seems to be the case. Do you have a test case that shows this behavior?

**Comment by twisted-trac** [comment]
|[<img alt="ralphm's avatar" src="https://avatars.githubusercontent.com/u/116741?s=50" width="50" height="50">](https://github.com/ralphm)<a name="note_3"></a>|@ralphm commented|
|-|-|

(In [23387]) Branching to 'xish-nested-dispatch-3066'

**Comment by twisted-trac** [comment]
|[<img alt="ralphm's avatar" src="https://avatars.githubusercontent.com/u/116741?s=50" width="50" height="50">](https://github.com/ralphm)<a name="note_4"></a>|@ralphm removed owner|
|-|-|

I made up the test case myself and fixed the one for the non-onetime observer to actually test that.

Please review.

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_5"></a>|@therve set owner to @ralphm|
|-|-|

2 tests are failing:

```
[ERROR]: twisted.words.test.test_xishutil.EventDispatcherTest.testStuff

Traceback (most recent call last):
  File "/home/therve/Projets/Twisted/trunk/twisted/words/test/test_xishutil.py", line 80, in testStuff
    self.assertEquals(cb1.object, msg)
exceptions.AttributeError: CallbackTracker instance has no attribute 'object'
===============================================================================
[ERROR]: twisted.words.test.test_xishutil.EventDispatcherTest.test_addObserverTwice

Traceback (most recent call last):
  File "/home/therve/Projets/Twisted/trunk/twisted/words/test/test_xishutil.py", line 113, in test_addObserverTwice
    self.assertEquals(cb1.object, d)
exceptions.AttributeError: CallbackTracker instance has no attribute 'object'
```

**Comment by twisted-trac** [comment]
|[<img alt="ralphm's avatar" src="https://avatars.githubusercontent.com/u/116741?s=50" width="50" height="50">](https://github.com/ralphm)<a name="note_6"></a>|@ralphm set owner to @therve|
|-|-|

:-( Sorry about that. Fixed now.

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_7"></a>|@therve set owner to @ralphm|
|-|-|

Great, please merge.

**Comment by twisted-trac** [comment]
|[<img alt="ralphm's avatar" src="https://avatars.githubusercontent.com/u/116741?s=50" width="50" height="50">](https://github.com/ralphm)<a name="note_8"></a>|@ralphm set status to `closed`|
|-|-|

(In [23418]) Fix adding one-time observers while in dispatch.

Author: jgill, ralphm
Reviewer: therve
Fixes [#3066](https://github.com/twisted/twisted/issues/3066).

**Comment by twisted-trac** [comment]
|<img alt="trac's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|trac commented|
|-|-|

Milestone Words 8.0.0 + 1 deleted

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
