### ISSUE TITLE
signal module shouldn't be imported unless it's used

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3099]
|<img alt="nriley's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| nriley reported|
|-|-|
|Trac ID|trac#3099|
|Type|defect|
|Created|2008-03-19 14:46:32Z|
|Branch|https://github.com/twisted/twisted/tree/signal-module-3099|

I'm working on getting Twisted on Jython.  Twisted already makes this conditional on `runtime.platformType == 'posix'`. Jython doesn't yet have a signal module, so this patch makes the import conditional as well.

Attachments:

* [signal.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/659/6590318a70806f5b81e1bab1d862f20e621bc1fd/d713b3ed8fc7463b7773d0083005d32fd45c8c53.patch) (872 bytes) - added by nriley on 2008-03-19 14:47:41Z - patch

<details><summary>Searchable metadata</summary>

```
trac-id__3099 3099
type__defect defect
reporter__nriley nriley
priority__normal normal
milestone__ 
branch__branches_signal_module_3099 branches/signal-module-3099
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__jython jython
time__1205937992000000 1205937992000000
changetime__1232923632000000 1232923632000000
version__None None
owner__ 
cc__thijs
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_1"></a>|@glyph commented|
|-|-|

In terms of a long-term solution, wouldn't wrapping `sun.misc.SignalHandler` for a simple 'signal' module be almost as easy?

For real inclusion, this change would need some kind of tests (or at least a Jython buildbot that we could start testing bootstrap / import issues like this on).

**Comment by twisted-trac** [comment]
|<img alt="nriley's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_2"></a>|nriley commented|
|-|-|

Replying to [glyph](#note_1):
> In terms of a long-term solution, wouldn't wrapping `sun.misc.SignalHandler` for a simple 'signal' module be almost as easy?

sun.misc.* is not portable; however we're working on wrapping "jna-posix", a library used by JRuby, to implement the bits of Python os, signal, subprocess, etc. that we don't currently.  (This is a potential SoC project for this year).

> For real inclusion, this change would need some kind of tests (or at least a Jython buildbot that we could start testing bootstrap / import issues like this on).

Uhh.  I'm moving an import from one place to another in a file where the usage is conditional anyway; I'm not sure what there is to test.

That said, we are working on getting a machine to use for Jython testing, on which we could likely host a Twisted buildbot.  We'll let you know when it's up.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_3"></a>|@glyph commented|
|-|-|

Replying to [nriley](#note_2):
> Replying to [glyph](#note_1):
> sun.misc.* is not portable; however we're working on wrapping "jna-posix", a library used by JRuby, to implement the bits of Python os, signal, subprocess, etc. that we don't currently.  (This is a potential SoC project for this year).

Given that jython could dynamically import sun.misc, it seems like a reasonable temporary workaround, but I knew it was 

> > For real inclusion, this change would need some kind of tests (or at least a Jython buildbot that we could start testing bootstrap / import issues like this on).
>
> Uhh.  I'm moving an import from one place to another in a file where the usage is conditional anyway; I'm not sure what there is to test.

Normally I'd say any change needs to have unit tests; the reason I specifically included "a buildbot" as an alternative in this case is because issues like this that completely prevent the unit tests from bootstrapping on a particular platform can obviously be counted as a failure, assuming that people know about them ;).

Without that kind of facility available to our core developers, the chances of some future change breaking this fix are very high.  (Way, way higher than you'd normally think in a library like Twisted with all these fiddly platform-specific bits - and likely to get higher now that both Jython and IronPython hackers are interested in stretching our portability to even more ridiculous heights).

> That said, we are working on getting a machine to use for Jython testing, on which we could likely host a Twisted buildbot.  We'll let you know when it's up.

This is really great news.  For best results, drop a message to the mailing list when this is available so that one of our buildbot admins finds out about it and give you the appropriate info to get it connected to our buildmaster.

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_4"></a>|@thijstriemstra set owner to @thijstriemstra<br>@thijstriemstra set status to `assigned`|
|-|-|

There's now a Jython buildbot available at http://buildbot.twistedmatrix.com/builders/ubuntu64-jython2.5-select

Unfortunately it's not doing much at the moment because it's blocked by [this](http://bugs.jython.org/issue1118) jython ticket. I'll check the patch into a branch when that issue(s) is resolved.

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_6"></a>|@thijstriemstra commented|
|-|-|

(In [24689]) Branching to 'signal-module-3099'

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_7"></a>|@thijstriemstra commented|
|-|-|

Replying to [thijs](#note_4):
> Unfortunately it's not doing much at the moment because it's blocked by [this](http://bugs.jython.org/issue1118) jython ticket. I'll check the patch into a branch when that issue(s) is resolved.

That ticket was fixed in r5290 of Jython so the buildbot is now working. I applied the patch in r24688, and adjusted setup.py in r24688, but the build [fails](http://buildbot.twistedmatrix.com/builders/ubuntu64-jython2.5-select/builds/7/steps/trial/logs/stdio):

```
Traceback (most recent call last):
  File "./bin/trial", line 23, in <module>
    from twisted.scripts.trial import run
  File "/home/buildbot/slaves/twisted-jython/jython2.5-thijs-ubuntu/Twisted/twisted/scripts/trial.py", line 9, in <module>
    from twisted.internet import defer
  File "/home/buildbot/slaves/twisted-jython/jython2.5-thijs-ubuntu/Twisted/twisted/internet/defer.py", line 17, in <module>
    from twisted.python import log, failure, lockfile
  File "/home/buildbot/slaves/twisted-jython/jython2.5-thijs-ubuntu/Twisted/twisted/python/lockfile.py", line 28, in <module>
    from win32api import OpenProcess
ImportError: No module named win32api
```

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_8"></a>|@exarkun commented|
|-|-|

There's a ton more signal imports throughout the codebase.  Maybe more than one thing should change in this branch?

On the other hand, it's pretty hard to see what effect any particular fix is having until the test suite can run.  Maybe there should be a ticket for all the fixes required to make `trial twisted` actually produce a summary?

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_9"></a>|@thijstriemstra commented|
|-|-|

Replying to [exarkun](#note_8):
>  Maybe there should be a ticket for all the fixes required to make `trial twisted` actually produce a summary?

Looks like [#3413](https://github.com/twisted/twisted/issues/3413) was opened for that.

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_10"></a>|@thijstriemstra set status to `closed`|
|-|-|

Closing this ticket now that there's [initial support](http://bugs.jython.org/issue1074) for signal in Jython. The buildslave doesn't fail anymore with the ```win32api ImportError``` we saw before.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
