### ISSUE TITLE
<span class="index" value="" /> causes runtime error

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3100]
|<img alt="jelkner's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| jelkner reported|
|-|-|
|Trac ID|trac#3100|
|Type|defect|
|Created|2008-03-19 15:48:07Z|

Creating indexing markup with an empty string for value:

<span class="index" value="" />

causes a runtime error:

```
Traceback (most recent call last):
  File "/home/jelkner/bin/obpdoc", line 21, in <module>
    run()
  File "/home/jelkner/lib/python/obpdoc/scripts/lorescript.py", line 190, in run
    result = runGivenOptions(opt)
  File "/home/jelkner/lib/python/obpdoc/scripts/lorescript.py", line 171, in runGivenOptions
    walker.generate(book, indexer, toc)
  File "/home/jelkner/lib/python/obpdoc/process.py", line 58, in generate
    self._writeIndex(book, indexer, linkrel)
  File "/home/jelkner/lib/python/obpdoc/process.py", line 65, in _writeIndex
    output = self.generator.generateIndex(book, indexer, linkrel)
  File "/home/jelkner/lib/python/obpdoc/default.py", line 45, in generateIndex
    document = indexer.toDocument()
  File "/home/jelkner/lib/python/obpdoc/indexer.py", line 212, in toDocument
    body.appendChild(self.generateIndexBody())
  File "/home/jelkner/lib/python/obpdoc/indexer.py", line 257, in generateIndexBody
    initial = key[0].upper()
IndexError: string index out of range
```

<details><summary>Searchable metadata</summary>

```
trac-id__3100 3100
type__defect defect
reporter__jelkner jelkner
priority__low low
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__wontfix wontfix
component__lore lore
keywords__EndOfLore EndOfLore
time__1205941687000000 1205941687000000
changetime__1389978518000000 1389978518000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun set owner to @khorn|
|-|-|

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="khorn's avatar" src="https://avatars.githubusercontent.com/u/815352?s=50" width="50" height="50">](https://github.com/khorn)<a name="note_4"></a>|@khorn set status to `closed`|
|-|-|

Lore is no longer being used for Twisted documentation, and is being deprecated, prior to eventual removal, per [#6907](https://github.com/twisted/twisted/issues/6907).

This issue will not be fixed.
