### ISSUE TITLE
Failure creation fails if the exception was generated from a C extension

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3132]
|<img alt="arkanes's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| arkanes reported|
|-|-|
|Trac ID|trac#3132|
|Type|release blocker: regression|
|Created|2008-03-27 20:55:32Z|
|Branch|https://github.com/twisted/twisted/tree/failure-c-extension-3132|

This may only apply to Pyrex/Cython extensions, I haven't been able to test fully.
The problem is at line 366 in failure.py, where the last frames code is inspecting looking for a yield opcode. If the previous frame was a call to a C extension, the co_code is `''`, and this generates and index error. Below is a traceback: 
```
Traceback (most recent call last):
  File "c:\Python25\lib\site-packages\twisted\python\threadpool.py", line 161, i
n _worker
    context.call(ctx, function, *args, **kwargs)
  File "C:\Python25\lib\site-packages\twisted\python\context.py", line 59, in ca
llWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "C:\Python25\lib\site-packages\twisted\python\context.py", line 37, in ca
llWithContext
    return func(*args,**kw)
  File "c:\Python25\lib\site-packages\twisted\internet\threads.py", line 26, in
_putResultInDeferred
    f = failure.Failure()
  File "C:\Python25\lib\site-packages\twisted\python\failure.py", line 168, in _
_init__
    exc_value = self._findFailure()
  File "C:\Python25\lib\site-packages\twisted\python\failure.py", line 366, in _
findFailure
    if lastFrame.f_code.co_code[lastTb.tb_lasti] != cls._yieldOpcode:
exceptions.IndexError: string index out of range
```

Attachments:

* [raiser.pyx](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/870/8700f469be02a32dd6e5ee2cd2471bb04b4d463e/ef21d4bcb3962286b5738232b7448229d2e0d5b7.pyx) (180 bytes) - added by arkanes on 2008-03-27 22:10:14Z - Pyrex extension for testing error
* [setup.py](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/870/8700f469be02a32dd6e5ee2cd2471bb04b4d463e/8e2edce0d507e1297474f25c00cae94258db38d8.py) (396 bytes) - added by arkanes on 2008-03-27 22:10:30Z - Build script for extension
* [test_failure.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/870/8700f469be02a32dd6e5ee2cd2471bb04b4d463e/59a7dbbc008889b47b76c6c1a02e07e6f2d12b5a.patch) (1101 bytes) - added by arkanes on 2008-03-27 22:10:57Z - Patch for test_failure adding a unit test for the bug
* [failure.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/870/8700f469be02a32dd6e5ee2cd2471bb04b4d463e/026688a31bf0dfebfbbe198b22f1c3866d81d69e.patch) (540 bytes) - added by arkanes on 2008-03-27 22:11:15Z - patch with proposed fix
* [raiser.c](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/870/8700f469be02a32dd6e5ee2cd2471bb04b4d463e/45cdb2e00d5c34efdadec2a07b160bb620e4d3ab.c) (14857 bytes) - added by arkanes on 2008-04-09 16:39:30Z - raiser.c
* [updated_per_review.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/870/8700f469be02a32dd6e5ee2cd2471bb04b4d463e/9c326daed38f4b27a247d476fe074639fce3e980.patch) (2424 bytes) - added by arkanes on 2008-04-09 16:39:52Z - updated patch as per review

<details><summary>Searchable metadata</summary>

```
trac-id__3132 3132
type__release_blocker__regression release blocker: regression
reporter__arkanes arkanes
priority__normal normal
milestone__ 
branch__branches_failure_c_extension_3132 branches/failure-c-extension-3132
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__None None
time__1206651332000000 1206651332000000
changetime__1474197555542286 1474197555542286
version__None None
owner__ 
cc__arkanes cc__therve
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_4"></a>|@therve commented|
|-|-|

(In [23114]) Branching to 'failure-c-extension-3132'

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_5"></a>|@therve commented|
|-|-|

(In [23115]) Check patch in.

Refs [#3132](https://github.com/twisted/twisted/issues/3132)

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)|@therve removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="radix's avatar" src="https://avatars.githubusercontent.com/u/227068?s=50" width="50" height="50">](https://github.com/radix)<a name="note_7"></a>|@radix set owner to arkanes|
|-|-|

[1] Why is it a cdef class instead of just a function?

[2] the docstring of raiser.pyx is not formatted properly. Also, it'd be nice if it referred to test_failure.

[3] I guess I would be slightly happier if you actually introspected something about the failure in the test, but then, the change isn't really about what the failure looks like, just that it doesn't blow up horribly.

[4] Please add a comment explaining why we check for an empty co_code, and why it's ok to return when it's empty (because we know that those C extensions can't yield...)

Thanks very much, arkanes, for getting this going, and thanks, therve, for organizing it into a branch. I'm reassigning this back to arkanes, but please feel free to deal with the comments if you want, therve :-) I'd like to get this merged so that I can do 8.0.2 very soon.

**Comment by twisted-trac** [comment]
|<img alt="arkanes's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_9"></a>|arkanes commented|
|-|-|

Replying to [radix](#note_8):

new patch attached, against Therves branch. I can't get an SVN checkout here (need an http-accessible repo), so I generated it manually and the patch might be a little screwey. Sorry :(.

raiser.c is attached separately so it doesn't bloat the patch up.

**Comment by twisted-trac** [comment]
|<img alt="arkanes's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|arkanes removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_13"></a>|@therve commented|
|-|-|

(In [23269]) Apply patch from tracker, with some docstrings.

Refs [#3132](https://github.com/twisted/twisted/issues/3132)

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_14"></a>|@therve commented|
|-|-|

Checked in the branch.

**Comment by twisted-trac** [comment]
|[<img alt="radix's avatar" src="https://avatars.githubusercontent.com/u/227068?s=50" width="50" height="50">](https://github.com/radix)<a name="note_15"></a>|@radix set status to `closed`|
|-|-|

(In [23279]) Merge failure-c-extension-3132

Author: arkanes
Reviewer: radix
Santa's Little Helper: therve
Fixes [#3132](https://github.com/twisted/twisted/issues/3132)

Constructing failures in contexts where Pyrex or Cython has inserted dodgy
pseudo-frames onto the stack now works. This involved a fix to the code
which detected existing failures on the exception stack to chain which was
trying to introspect those frames.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_17"></a>|@hawkowl commented|
|-|-|

[mass edit] Removing review from closed tickets.
