### ISSUE TITLE
ClientFactory.clientConnectionFailed re-entrancy problem

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3168]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#3168|
|Type|release blocker: regression|
|Created|2008-04-05 21:22:32Z|

Consider:

```python
from twisted.internet import protocol, reactor

class Stopper(protocol.ClientFactory):
    def clientConnectionFailed(self, connector, reason):
        print 'here'
        reactor.stop()


def main():
    reactor.connectTCP("localhost", 12345, Stopper())
    reactor.run()

if __name__ == '__main__':
    main()
```

With Twisted 2.5.0, this results in _here_ being printed once and the process exiting.  With Twisted 8.0.1, this is the result:

```
here
here
Traceback (most recent call last):
  File "/home/exarkun/Projects/Twisted/trunk/twisted/internet/defer.py", line 186, in addCallbacks
    self._runCallbacks()
  File "/home/exarkun/Projects/Twisted/trunk/twisted/internet/defer.py", line 328, in _runCallbacks
    self.result = callback(self.result, *args, **kw)
  File "/home/exarkun/Projects/Twisted/trunk/twisted/internet/base.py", line 387, in _continueFiring
    callable(*args, **kwargs)
  File "/home/exarkun/Projects/Twisted/trunk/twisted/internet/base.py", line 524, in disconnectAll
    failure.Failure(main.CONNECTION_LOST))
--- <exception caught here> ---
  File "/home/exarkun/Projects/Twisted/trunk/twisted/python/log.py", line 51, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/exarkun/Projects/Twisted/trunk/twisted/python/log.py", line 36, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/exarkun/Projects/Twisted/trunk/twisted/python/context.py", line 59, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/exarkun/Projects/Twisted/trunk/twisted/python/context.py", line 37, in callWithContext
    return func(*args,**kw)
  File "/home/exarkun/Projects/Twisted/trunk/twisted/internet/tcp.py", line 574, in connectionLost
    self.failIfNotConnected(error.ConnectError(string=reason))
  File "/home/exarkun/Projects/Twisted/trunk/twisted/internet/tcp.py", line 479, in failIfNotConnected
    self.connector.connectionFailed(failure.Failure(err))
  File "/home/exarkun/Projects/Twisted/trunk/twisted/internet/base.py", line 929, in connectionFailed
    self.factory.clientConnectionFailed(self, reason)
  File "foo.py", line 6, in clientConnectionFailed
    reactor.stop()
  File "/home/exarkun/Projects/Twisted/trunk/twisted/internet/base.py", line 490, in stop
    "Can't stop reactor that isn't running.")
twisted.internet.error.ReactorNotRunning: Can't stop reactor that isn't running.
```

<details><summary>Searchable metadata</summary>

```
trac-id__3168 3168
type__release_blocker__regression release blocker: regression
reporter__exarkun exarkun
priority__highest highest
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__ 
time__1207430552000000 1207430552000000
changetime__1208719868000000 1208719868000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

This seems to have roughly the same origin as [#3146](https://github.com/twisted/twisted/issues/3146)

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_2"></a>|@exarkun commented|
|-|-|

(In [23273]) Perhaps a test for [[#3168](https://github.com/twisted/twisted/issues/3168)](https://github.com/twisted/twisted/issues/3168)

refs #3168

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_3"></a>|@exarkun removed owner|
|-|-|

See [#3146](https://github.com/twisted/twisted/issues/3146).

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_4"></a>|@exarkun commented|
|-|-|

(In [23342]) Refer to another ticket

refs [#3168](https://github.com/twisted/twisted/issues/3168)
refs [#3146](https://github.com/twisted/twisted/issues/3146)
refs [#3198](https://github.com/twisted/twisted/issues/3198)

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_5"></a>|@exarkun set status to `closed`|
|-|-|

This was resolved r23345

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
