### ISSUE TITLE
twisted.words.protocols.jabber.xmlstream.streamStarted() takes 2 arguments (1 given)

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3194]
|<img alt="hanzz's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| hanzz reported|
|-|-|
|Trac ID|trac#3194|
|Type|defect|
|Created|2008-04-19 11:53:46Z|

Hi,

exactly the same traceback as in subject I get, when I try to registerAccount for Jabber. Traceback happends when registration is finished. in twisted.words.protocols.jabber.client.py; class BasicAuthenticator; function _registerResultEvent(self, iq) is xmlstream.streamStarted() called without any parametrs, which is bad and causes this traceback.

```
2008-04-19 13:25:33+0200 [-] XML: <iq from='njs.netlab.cz' id='H_2' type='result'><query xmlns='jabber:iq:register'><username>testjid88</username><password>test</password></query></iq>
2008-04-19 13:25:33+0200 [-] Unhandled Error
        Traceback (most recent call last):
          File "/usr/lib/python2.5/site-packages/Twisted-8.0.1-py2.5-linux-i686.egg/twisted/words/xish/utility.py", line 302, in dispatch
            callbacklist.callback(obj)
          File "/usr/lib/python2.5/site-packages/Twisted-8.0.1-py2.5-linux-i686.egg/twisted/words/xish/utility.py", line 101, in callback
            methodwrapper(*args, **kwargs)
          File "/usr/lib/python2.5/site-packages/Twisted-8.0.1-py2.5-linux-i686.egg/twisted/words/xish/utility.py", line 26, in __call__
            self.method(*nargs, **nkwargs)
          File "/usr/lib/python2.5/site-packages/Twisted-8.0.1-py2.5-linux-i686.egg/twisted/words/protocols/jabber/client.py", line 74, in _resultEvent
            self.callbacks.callback(iq)
        --- <exception caught here> ---
          File "/usr/lib/python2.5/site-packages/Twisted-8.0.1-py2.5-linux-i686.egg/twisted/words/xish/utility.py", line 101, in callback
            methodwrapper(*args, **kwargs)
          File "/usr/lib/python2.5/site-packages/Twisted-8.0.1-py2.5-linux-i686.egg/twisted/words/xish/utility.py", line 26, in __call__
            self.method(*nargs, **nkwargs)
          File "/usr/lib/python2.5/site-packages/Twisted-8.0.1-py2.5-linux-i686.egg/twisted/words/protocols/jabber/client.py", line 217, in _registerResultEvent
            self.streamStarted()
        exceptions.TypeError: streamStarted() takes exactly 2 arguments (1 given)

```

<details><summary>Searchable metadata</summary>

```
trac-id__3194 3194
type__defect defect
reporter__hanzz hanzz
priority__low low
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__words words
keywords__ 
time__1208606026000000 1208606026000000
changetime__1223328272000000 1223328272000000
version__None None
owner__ 
cc__hanzz cc__ralphm
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="ralphm's avatar" src="https://avatars.githubusercontent.com/u/116741?s=50" width="50" height="50">](https://github.com/ralphm)<a name="note_1"></a>|@ralphm set owner to @ralphm|
|-|-|

Apparently this has been broken for the last 9 months as a result of [20997] and there are no tests for this part of the code, yet. Also, as you might know, there has been discussion on the XMPP standards list to start deprecating inband registration.

That all said, could you attach a piece of code where you use this? I can then determine how to best fix this, if it all.

As an aside, for new tickets, could you not assign random keywords or set milestones? Thanks!

**Comment by twisted-trac** [comment]
|<img alt="franck34's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_3"></a>|franck34 commented|
|-|-|

We can see in Changeset 20997, file trunk/twisted/words/protocols/jabber/xmlstream.py, line 88, that streamStarted require rootElement

Before 20997:

def streamStarted(self)

After 20997

def streamStarted(self, rootElement)

And in trunk/twisted/words/protocols/jabber/client.py, line 216:
  # Registration succeeded -- go ahead and auth

  self.streamStarted()




Here is a test to reproduce the bug. I'm sorry, i don't know how to write test without a jabber server.

```
from twisted.words.protocols.jabber import client, jid, xmlstream
from twisted.words.xish import domish
from twisted.internet import reactor

# the jid must not be registered in the server
name =  'testtest'
server='localhost'
resource = 'Home'
password = 'mypassword'
me = '%s@%s/%s' % (name, server, resource)
registrationAlreadyDone = False

def authd(xs):
    global reactor
    print "login succesfull"
    reactor.stop()

def connected(xs):
    xs.rawDataInFn = rawDataIn
    xs.rawDataOutFn = rawDataOut

def invaliduserEvent(xmlstream):
    print 'Invalid user,trying to register!'
    global registrationAlreadyDone
    if not registrationAlreadyDone:
        registrationAlreadyDone = True 
        print 'Attempting to register...'
        global factory
        factory.authenticator.registerAccount(name, password)
    else:
        global reactor
        reactor.stop()

def authfailedEvent(xmlstream):
    global reactor
    print 'Auth failed'
    reactor.stop()

def registerfailedEvent(xmlstream):
    global reactor
    print 'Register failed!'
    reactor.stop()

def rawDataIn(buf):
    print "RECV: %s" % unicode(buf, 'utf-8').encode('ascii', 'replace')

def rawDataOut(buf):
    print "SEND: %s" % unicode(buf, 'utf-8').encode('ascii', 'replace')

myJid = jid.JID(me)
secret = password
factory = client.basicClientFactory(myJid,secret)

# Register authentication callbacks
factory.addBootstrap(xmlstream.STREAM_AUTHD_EVENT, authd)
factory.addBootstrap(xmlstream.STREAM_CONNECTED_EVENT, connected)
#factory.addBootstrap(client.BasicAuthenticator.INVALID_USER_EVENT,invaliduserEvent)
factory.addBootstrap(client.BasicAuthenticator.AUTH_FAILED_EVENT,invaliduserEvent)
factory.addBootstrap(client.BasicAuthenticator.REGISTER_FAILED_EVENT,registerfailedEvent)

# Go!
reactor.connectTCP(server, 5222, factory)
reactor.run()
```

My 2 cents

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
