### ISSUE TITLE
failure sometimes gets stack frames out of order

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3209]
|<img alt="arkanes's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| arkanes reported|
|-|-|
|Trac ID|trac#3209|
|Type|defect|
|Created|2008-04-25 19:29:58Z|

See the attached test case. When the rollback() method re-raises the exception, the stackframes that Failure inserts to try to give meaningful context to inlineCallbacks are inserted after, instead of before, the correct stack frame. Note in the stack trace below that self.rollback before self.process in the traceback.
```
===============================================================================
[ERROR]: testcase.TestProcessor.testProcessor

Traceback (most recent call last):
  File "C:\Python25\lib\site-packages\twisted\internet\defer.py", line 730, in
inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "C:\Python25\lib\site-packages\twisted\python\failure.py", line 330, in
hrowExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "C:\testcase.py", line 16, in process
    self.rollback()
  File "C:\testcase.py", line 14, in process
    val = yield threads.deferToThread(failingThing)
  File "C:\Python25\lib\site-packages\twisted\internet\threads.py", line 24, in
_putResultInDeferred
    result = f(*args, **kwargs)
  File "C:\testcase.py", line 8, in failingThing
    raise SpecialException("Failing thing is failing")
testcase.SpecialException: Failing thing is failing
-------------------------------------------------------------------------------
```

Attachments:

* [testcase.py](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/725/72546dfc81df135bce74c51980c2c5abe2dd1150/c6fa543491d4da1185be2699b43835c0d5ed8473.py) (616 bytes) - added by arkanes on 2008-04-25 19:30:07Z - testcase

<details><summary>Searchable metadata</summary>

```
trac-id__3209 3209
type__defect defect
reporter__arkanes arkanes
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__ 
time__1209151798000000 1209151798000000
changetime__1374681887000000 1374681887000000
version__None None
owner__ 
cc__therve
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_1"></a>|@therve commented|
|-|-|

Can you explain a little bit more what you expect? You say that self.rollback appears before self.process, but self.process is not in the traceback (self.rollback is in process?)

**Comment by twisted-trac** [comment]
|<img alt="arkanes's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_2"></a>|arkanes commented|
|-|-|

Replying to [therve](#note_1):
> Can you explain a little bit more what you expect? You say that self.rollback appears before self.process, but self.process is not in the traceback (self.rollback is in process?)

Sorry, I wasn't clear in how I described things. What I meant by "self.process" was the yield statement within it.

In the traceback, the stack as shown is:
rollback->yield statement->raise statement

But what I'd expect to see is:
yield statement->rollback->raise statement

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)|@glyph set owner to @radix|
|-|-|

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="radix's avatar" src="https://avatars.githubusercontent.com/u/227068?s=50" width="50" height="50">](https://github.com/radix)<a name="note_5"></a>|@radix commented|
|-|-|

I'm not really sure this is a bug in Twisted, as opposed to a weirdness of generator traceback formatting.

Maybe I'm wrong, though. The only magic about inlineCallbacks in failure formatting that I know of is the "_findFailure" method of Failure. If I disable its use, the traceback is formatted in exactly the same way.

I think I'm missing something. Anyone know what it is?
