### ISSUE TITLE
Intermittent failure of twisted.test.test_application.TestInternet2.test_UDP on ubuntu64-py2.5-poll

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3232]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#3232|
|Type|defect|
|Created|2008-05-12 01:17:55Z|

This test failed with the following error:

```
[ERROR]: twisted.test.test_application.TestInternet2.test_UDP

Traceback (most recent call last):
  File "/home/tarbox/projects/buildbotdir/ubuntu64-py2.5-poll/Twisted/twisted/test/test_application.py", line 386, in onStop
    t.startService()
  File "/home/tarbox/projects/buildbotdir/ubuntu64-py2.5-poll/Twisted/twisted/application/internet.py", line 91, in startService
    self._port = self._getPort()
  File "/home/tarbox/projects/buildbotdir/ubuntu64-py2.5-poll/Twisted/twisted/application/internet.py", line 116, in _getPort
    *self.args, **self.kwargs)
  File "/home/tarbox/projects/buildbotdir/ubuntu64-py2.5-poll/Twisted/twisted/internet/posixbase.py", line 249, in listenUDP
    p.startListening()
  File "/home/tarbox/projects/buildbotdir/ubuntu64-py2.5-poll/Twisted/twisted/internet/udp.py", line 83, in startListening
    self._bindSocket()
  File "/home/tarbox/projects/buildbotdir/ubuntu64-py2.5-poll/Twisted/twisted/internet/udp.py", line 91, in _bindSocket
    raise error.CannotListenError, (self.interface, self.port, le)
twisted.internet.error.CannotListenError: Couldn't listen on any:51175: (98, 'Address already in use').
```

<details><summary>Searchable metadata</summary>

```
trac-id__3232 3232
type__defect defect
reporter__exarkun exarkun
priority__low low
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__ 
time__1210555075000000 1210555075000000
changetime__1268551566000000 1268551566000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
