### ISSUE TITLE
trial raises AssertionError when running 'trial tests/*.py' and there is a __init__.py in "tests"

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3234]
|<img alt="dpn's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| dpn reported|
|-|-|
|Trac ID|trac#3234|
|Type|defect|
|Created|2008-05-13 01:22:18Z|

note: have removed full paths from traceback.

```
Traceback (most recent call last):
  File "bin/trial", line 24, in <module>
    run()
  File "twisted/scripts/trial.py", line 341, in run
    suite = _getSuite(config)
  File "twisted/scripts/trial.py", line 301, in _getSuite
    return loader.loadByNames(config['tests'], recurse)
  File "twisted/trial/runner.py", line 635, in loadByNames
    for thing in sets.Set(things)]
  File "twisted/trial/runner.py", line 592, in loadAnything
    return self.loadPackage(thing, recurse)
  File "twisted/trial/runner.py", line 543, in loadPackage
    pkgobj = modules.getModule(package.__name__)
  File "python/modules.py", line 762, in getModule
    return theSystemPath[moduleName]
  File "twisted/python/modules.py", line 701, in __getitem__
    return PythonModule(modname, mp, pe)
  File "twisted/python/modules.py", line 319, in __init__
    assert not name.endswith(".__init__")
AssertionError
```

<details><summary>Searchable metadata</summary>

```
trac-id__3234 3234
type__defect defect
reporter__dpn dpn
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__trial trial
keywords__ 
time__1210641738000000 1210641738000000
changetime__1210644504000000 1210644504000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

reformatting description

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
