### ISSUE TITLE
Trial fails to display the line where the error occured in case of SyntaxError

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3255]
|<img alt="Wolf's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| Wolf reported|
|-|-|
|Trac ID|trac#3255|
|Type|defect|
|Created|2008-05-29 20:52:42Z|
|Branch|https://github.com/twisted/twisted/tree/syntaxerror-failure-3255|

```
Running 0 tests.
                                                       [ERROR]

===============================================================================
[ERROR]: test_search.py

Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/twisted/trial/runner.py", line 631, in loadByNames
    things.append(self.findByName(name))
  File "/usr/lib/python2.5/site-packages/twisted/trial/runner.py", line 450, in findByName
    return filenameToModule(name)
  File "/usr/lib/python2.5/site-packages/twisted/trial/runner.py", line 70, in filenameToModule
    ret = reflect.namedAny(reflect.filenameToModuleName(fn))
  File "/usr/lib/python2.5/site-packages/twisted/python/reflect.py", line 357, in namedAny
    topLevelPackage = __import__(trialname)
exceptions.SyntaxError: invalid syntax (test_search.py, line 25)
-------------------------------------------------------------------------------
Ran 0 tests in 0.068s
```

Trial should display the line 25 of test_search.py (i.e. where the `SyntaxError` occured) instead of `topLevelPackage = __import__(trialname)`. This will provide some useful information about the real problem. The other function involved in the traceback could also be removed because they don't actually provide any useful information and they make the output less readable.

I tried to take a look at the code but the situation seems fairly complex down there (`trial/reporter.py`). If I can find something I could try to fix the problem and submit a patch.

Wolf

Attachments:

* [ticket3255.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/2c5/2c58a48d0d651f870cc921370b693a5f4700514a/c301e6852990fb6da65a0e1eba8b1bc23af99f48.patch) (4228 bytes) - added by Wolf on 2008-06-04 16:53:42Z - 

<details><summary>Searchable metadata</summary>

```
trac-id__3255 3255
type__defect defect
reporter__Wolf Wolf
priority__normal normal
milestone__ 
branch__branches_syntaxerror_failure_3255 branches/syntaxerror-failure-3255
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__trial_reporter_traceback_syntaxerror trial reporter traceback syntaxerror
time__1212094362000000 1212094362000000
changetime__1215089656000000 1215089656000000
version__None None
owner__Wolf Wolf
cc__therve cc__exarkun
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_1"></a>|@therve set owner to @glyph|
|-|-|

Failure should use the format_exception_only function from the traceback module. It has a special case for `SyntaxError`.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_2"></a>|@exarkun commented|
|-|-|

minor description markup fixes

**Comment by twisted-trac** [comment]
|<img alt="Wolf's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_3"></a>|Wolf removed owner|
|-|-|

I used the patch that therve gave me and I added a test to check it. It seems to work.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun set owner to @exarkun<br>@exarkun set status to `assigned`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_5"></a>|@exarkun set owner to Wolf<br>@exarkun set status to `new`|
|-|-|

In `_formatSyntaxError`, the exception handler for `msg, (filename, lineno, offset, badline) = exc` is untested.  Likewise, the `if c == '\t':` case is untested.

I'm not sure why you need the regular expression in the test.  I think you should be able to use simple string comparisons, perhaps after splitting the formatted text into lines and stripping whitespace.

Also, the test should call `getTraceback` rather than `_formatSyntaxError`.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_6"></a>|@exarkun commented|
|-|-|

(In [24227]) Branching to 'syntaxerror-failure-3255'
