### ISSUE TITLE
The XMPP example in Twisted.Words crashes if I stop it with Ctrl-C

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3270]
|<img alt="jozilla's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| jozilla reported|
|-|-|
|Trac ID|trac#3270|
|Type|defect|
|Created|2008-06-02 11:36:50Z|
|Branch|https://github.com/twisted/twisted/tree/xmpp_client.py-3270-3|

The XMPP example (xmpp_client.py) in Twisted words throws an exception when I quit it with Ctrl-C:

```
Disconnected.
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/twisted/internet/posixbase.py", line 228, in mainLoop
    self.runUntilCurrent()
  File "/usr/lib/python2.5/site-packages/twisted/internet/base.py", line 561, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/usr/lib/python2.5/site-packages/twisted/internet/base.py", line 414, in _continueSystemEvent
    callable(*args, **kw)
  File "/usr/lib/python2.5/site-packages/twisted/internet/base.py", line 375, in disconnectAll
    failure.Failure(main.CONNECTION_LOST))
--- <exception caught here> ---
  File "/usr/lib/python2.5/site-packages/twisted/python/log.py", line 48, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/lib/python2.5/site-packages/twisted/python/log.py", line 33, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/lib/python2.5/site-packages/twisted/python/context.py", line 59, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.5/site-packages/twisted/python/context.py", line 37, in callWithContext
    return func(*args,**kw)
  File "/usr/lib/python2.5/site-packages/twisted/internet/tcp.py", line 576, in connectionLost
    Connection.connectionLost(self, reason)
  File "/usr/lib/python2.5/site-packages/twisted/internet/tcp.py", line 416, in connectionLost
    protocol.connectionLost(reason)
  File "/usr/lib/python2.5/site-packages/twisted/words/xish/xmlstream.py", line 82, in connectionLost
    self.dispatch(self, STREAM_END_EVENT)
  File "/usr/lib/python2.5/site-packages/twisted/words/xish/utility.py", line 227, in dispatch
    self._eventObservers[(priority, event)].callback(object)
  File "/usr/lib/python2.5/site-packages/twisted/words/xish/utility.py", line 37, in callback
    methodwrapper(*args, **kwargs)
  File "/usr/lib/python2.5/site-packages/twisted/words/xish/utility.py", line 21, in __call__
    self.method(*nargs, **nkwargs)
  File "xmpp_client.py", line 58, in disconnected
    reactor.stop()
  File "/usr/lib/python2.5/site-packages/twisted/internet/base.py", line 342, in stop
    raise RuntimeError, "can't stop reactor that isn't running"
exceptions.RuntimeError: can't stop reactor that isn't running
```

I already posted this on the mailing list. Here is the comment by Ralph Meijer:

=================
I haven't seen that behavior before, but I can confirm this happens. I
poked around a bit with the example. It seems that the socket is closed
before its factory is shut down. It might be that the reactor shutdown
procedure has changed, so I think this behavior is the result of a bug,
either in the example or somewhere else. 
=================

<details><summary>Searchable metadata</summary>

```
trac-id__3270 3270
type__defect defect
reporter__jozilla jozilla
priority__normal normal
milestone__ 
branch__branches_xmpp_client_py_3270_3 branches/xmpp_client.py-3270-3
branch_author__ 
status__closed closed
resolution__fixed fixed
component__words words
keywords__ 
time__1212406610000000 1212406610000000
changetime__1347903457000000 1347903457000000
version__None None
owner__exarkun exarkun

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

reformatting description

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_2"></a>|@exarkun commented|
|-|-|

(In [23876]) Branching to 'xmpp_client.py-3270'

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_3"></a>|@exarkun commented|
|-|-|

I'm not going to finish this now.  radix convinced me that we should not introduce a new public API which is only capable of being used as `twisted.internet.task.react` in this branch is capable of being used.  Instead, [#11551](https://github.com/twisted/twisted/issues/11551) should do something about this use-case and the examples should be updated to use that solution.

**Comment by twisted-trac** [comment]
|[<img alt="ralphm's avatar" src="https://avatars.githubusercontent.com/u/116741?s=50" width="50" height="50">](https://github.com/ralphm)<a name="note_4"></a>|@ralphm commented|
|-|-|

exarkun: could you expand a bit on why the current behaves as it does? I don't remember seeing such exceptions when the example code was written. I assume the idiom used in the example is not correct? Also, do you have some kind of work around that could be used until what you suggest should happen on [#11551](https://github.com/twisted/twisted/issues/11551) has been completed?

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_5"></a>|@exarkun commented|
|-|-|

It calls `reactor.stop()` in its connection-lost handler.  Also, ^C calls `reactor.stop()` and disconnects everything.  It needs to keep track of whether the reactor is already in the process of shutting down or not so that it can skip the call if it is.  This is basically what I implemented in a general way in the branch.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_6"></a>|@exarkun commented|
|-|-|

And I love trac markup.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_8"></a>|@exarkun commented|
|-|-|

(In [34897]) Branching to 'xmpp_client.py-3270-2'

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_9"></a>|@exarkun commented|
|-|-|

(In [35697]) Branching to 'xmpp_client.py-3270-3'

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_10"></a>|@exarkun set owner to @glyph|
|-|-|

Years later, [#11551](https://github.com/twisted/twisted/issues/11551) is still open, so guess we'll go with this.

[Build results](http://buildbot.twistedmatrix.com/boxes-supported?branch=/branches/xmpp_client.py-3270-3)

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_11"></a>|@therve set owner to @exarkun|
|-|-|

OK, I buy that.

 * One (blocking) pyflakes: `doc/words/examples/xmpp_client.py:23: undefined name 'client_jid'`

 * It most likely deserves some documentation. Please open a bug if you're not tackling it there.

Thanks, please merge!

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_12"></a>|@exarkun commented|
|-|-|

(In [35702]) Slightly improve the react docstring

refs [#3270](https://github.com/twisted/twisted/issues/3270)

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_13"></a>|@exarkun set status to `closed`|
|-|-|

(In [35703]) Merge xmpp_client.py-3270-2

Author: exarkun
Reviewer: therve
Fixes: [#3270](https://github.com/twisted/twisted/issues/3270)

Add `twisted.internet.task.react`, a helper for running and stopping the reactor.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_14"></a>|@glyph commented|
|-|-|

Would it be nice to also have a decorator-syntax version of this?

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_15"></a>|@exarkun commented|
|-|-|

I don't know, would it?  I feel like no.  The decorator form (I am guessing, since "decorator-syntax version" is a long way away from a complete specification - if I guessed wrong it's your fault :) would take a perfectly reasonable Deferred-returning function and make it so you can _only_ call it once, and only if the reactor is not running yet.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_16"></a>|@glyph commented|
|-|-|

Replying to [exarkun](#note_15):
> I don't know, would it?  I feel like no.  The decorator form (I am guessing, since "decorator-syntax version" is a long way away from a complete specification - if I guessed wrong it's your fault :) would take a perfectly reasonable Deferred-returning function and make it so you can _only_ call it once, and only if the reactor is not running yet.

Yeah, that would be the naive implementation.  I did implement this once: [amphacks.util.mainpoint](http://bazaar.launchpad.net/~glyph/+junk/amphacks/view/head:/python/amphacks/util.py#L30).  It checks the function's `__module__` and only runs it if it's in `__main__`, in that implementation.
