### ISSUE TITLE
twisted.conch.test.test_manhole.ManholeLoopbackStdio.testException has oververbose checks

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3309]
|[<img alt="fijal's avatar" src="https://avatars.githubusercontent.com/u/85944?s=50" width="50" height="50">](https://github.com/fijal)| @fijal reported|
|-|-|
|Trac ID|trac#3309|
|Type|defect|
|Created|2008-06-25 04:40:12Z|
|Branch|https://github.com/twisted/twisted/tree/over-verbose-manhole-tests-3309|

it fails on top of pypy with more or less:

twisted.trial.unittest.FailTest: ['Traceback (most recent call last):', '  File "<console>", line 1, in <interactive>'] != ['Traceback (most recent call last):', '  File "<console>", line 1, in entry_point']
not equal:
a = '  File "<console>", line 1, in <interactive>'
b = '  File "<console>", line 1, in entry_point'

should be changed to
assert a.startswith('File ...') or something like that.

<details><summary>Searchable metadata</summary>

```
trac-id__3309 3309
type__defect defect
reporter__fijal fijal
priority__low low
milestone__ 
branch__branches_over_verbose_manhole_tests_3309 branches/over-verbose-manhole-tests-3309
branch_author__fijal__jkakar fijal, jkakar
status__closed closed
resolution__invalid invalid
component__conch conch
keywords__ 
time__1214368812000000 1214368812000000
changetime__1269810541000000 1269810541000000
version__None None
owner__jkakar jkakar

```
</details>

**Comment by twisted-trac** [comment]
|<img alt="jkakar's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_1"></a>|jkakar commented|
|-|-|

(In [28778]) Branching to 'over-verbose-manhole-tests-3309'

**Comment by twisted-trac** [comment]
|<img alt="jkakar's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|jkakar set owner to jkakar|
|-|-|

**Comment by twisted-trac** [comment]
|<img alt="jkakar's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|jkakar removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_4"></a>|@exarkun set owner to jkakar|
|-|-|

Hi jkakar, thanks for investigating this.

So as it turns out, this test passes on PyPy these days.  You can check that kind of thing on our buildbot (since I assume you don't have PyPy installed, although there are actually binaries packaged up for the 1.2 release).  eg, follow one of the build links from <http://buildbot.twistedmatrix.com/builders/ubuntu32-pypy>.  I think that's a good thing, because _entry_point_ was just sort of a nonsense thing exposing an implementation detail of the PyPy repl.

Unless another interpreter comes along that can't present a CPython-compatible line in its traceback formatting code, I think it's probably worth leaving this code as-is.

So, close as invalid?  Or wontfix (who knows what the difference between the two is).

**Comment by twisted-trac** [comment]
|<img alt="jkakar's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_5"></a>|jkakar set status to `closed`|
|-|-|

exarkun: Woot, the changes I made to the test were pretty ugly
anyway.
