### ISSUE TITLE
Basically MySQL connection issues...

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3334]
|<img alt="epctechno's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| epctechno reported|
|-|-|
|Trac ID|trac#3334|
|Type|defect|
|Created|2008-07-06 06:59:29Z|

Here is my Traceback of many thousands, which MySQL hasn't really gone away at all, but seems to be some sort of bug of some sort... I'm new here so let me know if this is correct to post this here:

2008-07-05 23:46:49-0700 [-] Unhandled error in Deferred:
2008-07-05 23:46:49-0700 [-] Unhandled Error
        Traceback (most recent call last):
          File "/usr/local/lib/python2.5/site-packages/twisted/internet/defer.py", line 269, in errback
            self._startRunCallbacks(fail)
          File "/usr/local/lib/python2.5/site-packages/twisted/internet/defer.py", line 312, in _startRunCallbacks
            self._runCallbacks()
          File "/usr/local/lib/python2.5/site-packages/twisted/internet/defer.py", line 328, in _runCallbacks
            self.result = callback(self.result, *args, **kw)
          File "/usr/local/lib/python2.5/site-packages/twisted/internet/defer.py", line 757, in gotResult
            _inlineCallbacks(r, g, deferred)
        --- <exception caught here> ---
          File "/usr/local/lib/python2.5/site-packages/twisted/internet/defer.py", line 735, in _inlineCallbacks
            result = result.throwExceptionIntoGenerator(g)
          File "/usr/local/lib/python2.5/site-packages/twisted/python/failure.py", line 331, in throwExceptionIntoGenerator
            return g.throw(self.type, self.value, self.tb)
          File "/usr/local/lib/python2.5/site-packages/twisted/plugins/proxychecker.py", line 222, in saveInfo
            (self.proxy_type, proxy))
          File "/usr/local/lib/python2.5/site-packages/twisted/internet/threads.py", line 24, in _putResultInDeferred
            result = f(*args, **kwargs)
          File "/usr/local/lib/python2.5/site-packages/twisted/enterprise/adbapi.py", line 380, in _runInteraction
            conn.rollback()
          File "/usr/local/lib/python2.5/site-packages/twisted/enterprise/adbapi.py", line 47, in rollback
            self._connection.rollback()
        _mysql_exceptions.OperationalError: (2006, 'MySQL server has gone away')

<details><summary>Searchable metadata</summary>

```
trac-id__3334 3334
type__defect defect
reporter__epctechno epctechno
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__invalid invalid
component__core core
keywords__ 
time__1215327569000000 1215327569000000
changetime__1215435439000000 1215435439000000
version__None None
owner__ 
cc__exarkun
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun set status to `closed`|
|-|-|

MySQL has a connection lifetime timeout.  It will close connections after a while, and this is how that case is reported.  You may want to change your MySQL configuration to raise the timeout, or change your code to handle this exception, or both.

You should be able to find more information about this problem in the twisted-python mailing list archives.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
