### ISSUE TITLE
twisted.trial.test.test_reporter.FormatFailures.test_formatDefault fails if there is a "foo/bar.py" in the working directory

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3336]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#3336|
|Type|defect|
|Created|2008-07-07 21:34:54Z|

It takes source lines from that file, apparently, perhaps due to the relative path names in test data.

Also, I doubt it's actually ideal to include a blank line if the source can't be found.  Omitting the line entirely seems like superior behavior.

Reproduce by running following (from trunk):

```
mkdir foo
cp setup.py foo/bar.py
bin/trial twisted.trial.test.test_reporter.FormatFailures.test_formatDefault
```

Output:
```
twisted.trial.test.test_reporter
  FormatFailures
    test_formatDefault ...                                               [FAIL]

===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/home/thijs/workspace/Twisted/trunk/twisted/trial/test/test_reporter.py", line 298, in test_formatDefault
    'RuntimeError: foo'], tb.splitlines())
  File "/home/thijs/workspace/Twisted/trunk/twisted/trial/test/test_reporter.py", line 64, in stringComparison
    % (line_number, exp.pattern, out))
twisted.trial.unittest.FailTest: Line 2: '^\\s*$' did not match string '    def do_something(item, d):'

twisted.trial.test.test_reporter.FormatFailures.test_formatDefault
-------------------------------------------------------------------------------
Ran 1 tests in 0.005s

FAILED (failures=1)
```

<details><summary>Searchable metadata</summary>

```
trac-id__3336 3336
type__defect defect
reporter__exarkun exarkun
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__trial trial
keywords__ 
time__1215466494000000 1215466494000000
changetime__1308765209000000 1308765209000000
version__None None
owner__ 
cc__thijs
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
