### ISSUE TITLE
manhole exception: AttributeError: 'module' object has no attribute '__getattr__'

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3337]
|<img alt="doko's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| doko reported|
|-|-|
|Trac ID|trac#3337|
|Type|defect|
|Created|2008-07-08 12:32:46Z|

seen with 8.1.0 and python2.5:

```
$ cd /home/packages/twisted/
doko@salsa:/home/packages/twisted$ schroot -p -c sid32
I: [sid32 chroot] Running shell: '/bin/bash'
(sid32)doko@salsa:/home/packages/twisted$ manhole
Traceback (most recent call last):
  File "/usr/bin/manhole", line 21, in <module>
    manhole.run()
  File "/usr/lib/python2.5/site-packages/twisted/scripts/manhole.py", line 102, in run
    run(config)
  File "/usr/lib/python2.5/site-packages/twisted/scripts/manhole.py", line 154, in run_gtk2
    w = gtk2manhole.ManholeWindow()
  File "/usr/lib/python2.5/site-packages/twisted/manhole/ui/gtk2manhole.py", line 46, in __init__
    self.input = ConsoleInput(self._input)
  File "/usr/lib/python2.5/site-packages/twisted/manhole/ui/gtk2manhole.py", line 218, in __init__
    self.rkeymap[getattr(gtk.keysyms, name)] = name
AttributeError: 'module' object has no attribute '__getattr__'
```

<details><summary>Searchable metadata</summary>

```
trac-id__3337 3337
type__defect defect
reporter__doko doko
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__duplicate duplicate
component__core core
keywords__ 
time__1215520366000000 1215520366000000
changetime__1215520756000000 1215520756000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_1"></a>|@therve set status to `closed`|
|-|-|

This is a duplicate of [#2464](https://github.com/twisted/twisted/issues/2464).

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
