### ISSUE TITLE
twisted does not install on 64bit Windows Vista

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3352]
|<img alt="Chepra's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| Chepra reported|
|-|-|
|Trac ID|trac#3352|
|Type|defect|
|Created|2008-07-13 13:09:29Z|

Hello!

As said to me I should fill a bug here.

I have vista 64bit and python installed via the 64bit installer from python.org.
The Twisted installer did not worked and said that pyton cant be found.

Therefore I downloaded the source and tried to python setup.py install, which give me this error:

```
running build_ext
Traceback (most recent call last):
  File "setup.py", line 94, in <module>
    main(sys.argv[1:])
  File "setup.py", line 89, in main
    setup(**setup_args)
  File ".\twisted\python\dist.py", line 47, in setup
    return core.setup(**get_setup_args(**kw))
  File "D:\opt\python\lib\distutils\core.py", line 151, in setup
    dist.run_commands()
  File "D:\opt\python\lib\distutils\dist.py", line 974, in run_commands
    self.run_command(cmd)
  File "D:\opt\python\lib\distutils\dist.py", line 994, in run_command
    cmd_obj.run()
  File "D:\opt\python\lib\distutils\command\install.py", line 506, in run
    self.run_command('build')
  File "D:\opt\python\lib\distutils\cmd.py", line 333, in run_command
    self.distribution.run_command(command)
  File "D:\opt\python\lib\distutils\dist.py", line 994, in run_command
    cmd_obj.run()
  File "D:\opt\python\lib\distutils\command\build.py", line 112, in run
    self.run_command(cmd_name)
  File "D:\opt\python\lib\distutils\cmd.py", line 333, in run_command
    self.distribution.run_command(command)
  File "D:\opt\python\lib\distutils\dist.py", line 994, in run_command
    cmd_obj.run()
  File "D:\opt\python\lib\distutils\command\build_ext.py", line 290, in run
    self.build_extensions()
  File ".\twisted\python\dist.py", line 327, in build_extensions
    self.prepare_extensions()
  File ".\twisted\python\dist.py", line 318, in prepare_extensions
    if x.condition(self)]
  File "twisted\runner\topfiles\setup.py", line 11, in <lambda>
    condition=lambda builder: builder._check_header("rpc/rpc.h")),
  File ".\twisted\python\dist.py", line 360, in _check_header
    return self._compile_helper("#include <%s>\n" % header_name)
  File ".\twisted\python\dist.py", line 346, in _compile_helper
    self.compiler.compile(["conftest.c"], output_dir='')
  File "D:\opt\python\lib\distutils\msvccompiler.py", line 354, in compile
    if not self.initialized: self.initialize()
  File "D:\opt\python\lib\distutils\msvccompiler.py", line 264, in initialize
    self.__paths = self.get_msvc_paths("path")
  File "D:\opt\python\lib\distutils\msvccompiler.py", line 616, in get_msvc_paths
    % (self.__root, self.__version))
AttributeError: MSVCCompiler instance has no attribute '_MSVCCompiler__root'
```

<details><summary>Searchable metadata</summary>

```
trac-id__3352 3352
type__defect defect
reporter__Chepra Chepra
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__ 
component__core core
keywords__ 
time__1215954569000000 1215954569000000
changetime__1268548400000000 1268548400000000
version__None None
owner__ 
cc__thijs
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_1"></a>|@glyph commented|
|-|-|

Updating the summary to be clearer.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_2"></a>|@glyph commented|
|-|-|

Does the computer that you tried this on have Visual Studio installed?

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_3"></a>|@exarkun commented|
|-|-|

What version of Python?

**Comment by twisted-trac** [comment]
|<img alt="zectbumo's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_4"></a>|zectbumo commented|
|-|-|

I have the same problem as Chepra.
I'm on 64bit Vista.
I have VS.NET2003, VS2005, VS2008 installed.
I have 64bit Python 2.5

**Comment by twisted-trac** [comment]
|<img alt="zectbumo's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_6"></a>|zectbumo commented|
|-|-|

I tried 64 bit Python 2.6 and Twisted was able to build fine.  It seems to only be a problem when using 64 bit Python 2.5.

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_7"></a>|@therve set status to `closed`|
|-|-|

It looks like a problem with distutils, not twisted. Please open a ticket in python tracker (if it works with 2.6, it may already be solved).

**Comment by twisted-trac** [comment]
|<img alt="tehnicaorg's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_8"></a>|tehnicaorg set status to `reopened`|
|-|-|

I'll reopen this bug because it still doesn't install 'properly' on an Windows 64 machine. (I've tried it on Windows 7, 64 bit).

I have a 64 bit version Python. On 64 bit version of Windows there is a registry redirection for 32 bit programs. http://msdn.microsoft.com/en-us/library/aa384232(VS.85).aspx

Because the twisted installer is 32 bit it will really search in this keys:
  * HKLM\Software\**Wow6432Node**\Python\PythonCore\2.6\InstallPath
  * HKCU\Software\Python\PythonCore\2.6\InstallPath

although it wanted HKLM\Software\Python\PythonCore\2.6\InstallPath. See (1).


As you can see if I had installed python just for myself (in HKCU instead of HKLM) it would probably work.

I've created the key HKLM\Software\Wow6432Node\Python\PythonCore\2.6\InstallPath, with default value c:\python26 and twisted installed ok.

I've used the following installer: Twisted 9.0.0 for Python 2.6. 

Python: Python 2.6.4 (r264:75708, Oct 26 2009, 07:36:50) [MSC v.1500 64 bit (AMD64)] on win32. 




(1) http://support.microsoft.com/kb/896459 

"Note Developers can use the RegQueryReflectionKey function to determine the reflection state for a particular key and use the RegDisableReflectionKey function and the RegEnableReflectionKey function to programmatically disable and enable registry reflection for a particular key."

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)|@glyph set owner to PenguinOfDoom<br>@glyph set status to `new`|
|-|-|

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
