### ISSUE TITLE
Intermittent failures in twisted.conch.test.test_conch.OpenSSHClientTestCase.test_remoteToLocalForwarding errors

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3403]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#3403|
|Type|defect|
|Created|2008-09-01 12:25:37Z|

On Fedora 64bit, epoll reactor:

```
===============================================================================
[ERROR]: twisted.conch.test.test_conch.OpenSSHClientTestCase.test_remoteToLocalForwarding

Traceback (most recent call last):
Failure: twisted.internet.defer.TimeoutError: <twisted.conch.test.test_conch.OpenSSHClientTestCase testMethod=test_remoteToLocalForwarding> (test_remoteToLocalForwarding) still running at 120.0 secs
===============================================================================
[ERROR]: twisted.conch.test.test_conch.OpenSSHClientTestCase.test_remoteToLocalForwarding

Traceback (most recent call last):
  File "/home/buildbot/twisted/slave.trunk/fedora64-py2.4-reactors/Twisted/twisted/conch/test/test_ssh.py", line 56, in global_tcpip_forward
    interface = host)
  File "/home/buildbot/twisted/slave.trunk/fedora64-py2.4-reactors/Twisted/twisted/internet/posixbase.py", line 328, in listenTCP
    p.startListening()
  File "/home/buildbot/twisted/slave.trunk/fedora64-py2.4-reactors/Twisted/twisted/internet/tcp.py", line 858, in startListening
    raise CannotListenError, (self.interface, self.port, le)
twisted.internet.error.CannotListenError: Couldn't listen on localhost:55702: (98, 'Address already in use').
===============================================================================
[ERROR]: twisted.conch.test.test_conch.OpenSSHClientTestCase.test_remoteToLocalForwarding

Traceback (most recent call last):
  File "/home/buildbot/twisted/slave.trunk/fedora64-py2.4-reactors/Twisted/twisted/python/log.py", line 51, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/buildbot/twisted/slave.trunk/fedora64-py2.4-reactors/Twisted/twisted/python/log.py", line 36, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/buildbot/twisted/slave.trunk/fedora64-py2.4-reactors/Twisted/twisted/python/context.py", line 59, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/buildbot/twisted/slave.trunk/fedora64-py2.4-reactors/Twisted/twisted/python/context.py", line 37, in callWithContext
    return func(*args,**kw)
  File "/home/buildbot/twisted/slave.trunk/fedora64-py2.4-reactors/Twisted/twisted/conch/ssh/service.py", line 44, in packetReceived
    return f(packet)
  File "/home/buildbot/twisted/slave.trunk/fedora64-py2.4-reactors/Twisted/twisted/conch/ssh/connection.py", line 73, in ssh_GLOBAL_REQUEST
    ret = self.gotGlobalRequest(requestType, rest)
  File "/home/buildbot/twisted/slave.trunk/fedora64-py2.4-reactors/Twisted/twisted/conch/ssh/connection.py", line 558, in gotGlobalRequest
    return self.transport.avatar.gotGlobalRequest(requestType, data)
  File "/home/buildbot/twisted/slave.trunk/fedora64-py2.4-reactors/Twisted/twisted/conch/avatar.py", line 37, in gotGlobalRequest
    return f(data)
  File "/home/buildbot/twisted/slave.trunk/fedora64-py2.4-reactors/Twisted/twisted/conch/test/test_ssh.py", line 59, in global_tcpip_forward
    unittest.fail("something went wrong with remote->local forwarding")
  File "/home/buildbot/twisted/slave.trunk/fedora64-py2.4-reactors/Twisted/twisted/trial/unittest.py", line 1509, in _
    return getattr(_inst, name)(*args, **kwargs)
twisted.trial.unittest.FailTest: something went wrong with remote->local forwarding
-------------------------------------------------------------------------------
```

<details><summary>Searchable metadata</summary>

```
trac-id__3403 3403
type__defect defect
reporter__exarkun exarkun
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__conch conch
keywords__ 
time__1220271937000000 1220271937000000
changetime__1221164670000000 1221164670000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

I managed to reproduce this after 43 minutes of running the test (12960 iterations with --until-failure).  With that long between reproductions this is going to be a difficult one.

Besides that, the failure doesn't really make any sense.  The test very clearly closes the socket bound to the address which later cannot be bound to.  Superficially, the code is right and the test shouldn't fail.

This may be related to [#3232](https://github.com/twisted/twisted/issues/3232) which also binds a port, closes the socket, then fails to bind a new socket to it.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
