### ISSUE TITLE
Windows spawnProcess raises exception when process ends

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3517]
|<img alt="rlotun's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| rlotun reported|
|-|-|
|Trac ID|trac#3517|
|Type|defect|
|Created|2008-10-31 11:40:10Z|

I get the following traceback on Windows XP running that latest stable release of twisted 8.1.0. It seems there is a problem with `self.proc.processEnded(exitCode)` in `_dumbwin32proc.py` - in previous versions the call used to be something like `self.proc.protocol.processEnded`, but I'm not sure if the type of `self.proc` has been changed.

```
Traceback (most recent call last):
  File "C:\Python25\lib\threading.py", line 488, in __bootstrap_inner
    self.run()
  File "C:\socialistics\trunk\peer\net\app.py", line 103, in run
    reactor.run(installSignalHandlers=0)
  File "C:\Python25\lib\site-packages\twisted\internet\base.py", line 1048, in run
    self.mainLoop()
  File "C:\Python25\lib\site-packages\twisted\internet\base.py", line 1057, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "C:\Python25\lib\site-packages\twisted\internet\base.py", line 705, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "C:\Python25\lib\site-packages\twisted\internet\_pollingfile.py", line 72, in _pollEvent
    workUnits += resource.checkWork()
  File "C:\Python25\lib\site-packages\twisted\internet\_dumbwin32proc.py", line 51, in checkWork
    self.proc.processEnded(exitCode)
exceptions.AttributeError: Process instance has no attribute 'processEnded'
```

<details><summary>Searchable metadata</summary>

```
trac-id__3517 3517
type__defect defect
reporter__rlotun rlotun
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__invalid invalid
component__core core
keywords__ 
time__1225453210000000 1225453210000000
changetime__1225460929000000 1225460929000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|<img alt="rlotun's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_1"></a>|rlotun commented|
|-|-|

Well, actually `self.proc` seems to be a `_dumbin32proc.Process`, so I suppose the call should instead be `self.proc.proto.processEndend(exitCode)`??

**Comment by twisted-trac** [comment]
|<img alt="rlotun's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_2"></a>|rlotun commented|
|-|-|

I've actually just confirmed that the exception goes away if I change the line to `self.proc.protocol.processEnded(exitCode)`

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_3"></a>|@exarkun commented|
|-|-|

Can you explain how to reproduce this?

**Comment by twisted-trac** [comment]
|<img alt="rlotun's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_4"></a>|rlotun set status to `closed`|
|-|-|

Sorry, I'm going to close this ticket as invalid. This was something incorrect that I was doing. You're probably not interested in the full story so here's the abridged one: in my code base I had to spawn a windows process with a specific flag to `CreateProcess` - but since I couldn't do this through `spawnProcess` I had to unfortunately copy out the `Process` class from `_dumbwin32proc` and modify the `CreateProcess` call. However, that happened incorrectly - my fault.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_5"></a>|@exarkun commented|
|-|-|

Thanks for the follow-up!

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
