### ISSUE TITLE
Reactor run, stop, run, stop never returns

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3518]
|<img alt="dns's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| dns reported|
|-|-|
|Trac ID|trac#3518|
|Type|defect|
|Created|2008-10-31 15:22:01Z|

Windows XP SP3, Twisted 8.1.0, Python 2.4.4.  First time submitting a ticket, so apologies if I'm doing this wrong.  I looked through currently active tickets, but wasn't able to find a ticket for this problem.

My actual code is more complex, but I run into exactly the same problem when running the following code from the interactive interpreter:

```
from twisted.internet import reactor
reactor.callLater(5, reactor.stop)
<twisted.internet.base.DelayedCall instance at 0x00AA7850>
reactor.run()
reactor.callLater(5, reactor.stop)
<twisted.internet.base.DelayedCall instance at 0x011D4828>
reactor.run()
```

The second reactor.run() never terminates.  If I hit CTRL-C, I get this:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in ?

  File "C:\Python24\lib\site-packages\twisted\internet\base.py", line 1048, in run
    self.mainLoop()
  File "C:\Python24\lib\site-packages\twisted\internet\base.py", line 1057, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "C:\Python24\lib\site-packages\twisted\internet\base.py", line 677, in runUntilCurrent
    f(*a, **kw)
  File "C:\Python24\lib\site-packages\twisted\internet\base.py", line 494, in stop
    raise error.ReactorNotRunning(
twisted.internet.error.ReactorNotRunning: Can't stop reactor that isn't running.
```

This exception is repeated for each time I press CTRL-C, but the reactor still never terminates.  What I'm doing seems perfectly legitimate; is there something I'm missing?

<details><summary>Searchable metadata</summary>

```
trac-id__3518 3518
type__defect defect
reporter__dns dns
priority__high high
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__invalid invalid
component__core core
keywords__ 
time__1225466521000000 1225466521000000
changetime__1225468760000000 1225468760000000
version__None None
owner__ 
cc__exarkun
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun set status to `closed`|
|-|-|

The reactor is not restartable, so it's expected that this doesn't work.  There's no fundamental reason the reactor can't be restartable, someone just needs to do the work to make it so.  Feel free to open a ticket and attach a patch for that if you're interested in doing the work (most likely, at least a few tickets will be required, as there are many different reactors and they will each have slightly different requirements in order to be restartable - feel free to just start with one, though).  If you have any questions about how to go about this, feel free to ask them on the mailing list or the IRC channel.

**Comment by twisted-trac** [comment]
|<img alt="dns's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_2"></a>|dns set status to `reopened`|
|-|-|

Hmm I don't have time to do this.  But as a follow-up, if this is expected behavior, it seems like there should be some indication of that.  As it works now, the reactor happily runs a second time, and the problem happens (silently) only when reactor.stop is called.

If restarting isn't allowed, I'd expect the second call to reactor.run to raise some sort of 'I'm afraid I can't do that' exception.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_3"></a>|@exarkun set status to `closed`|
|-|-|

Sure.  There's a ticket for that - [#2066](https://github.com/twisted/twisted/issues/2066).

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
