### ISSUE TITLE
Improve SIP URI parsing/formatting

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3582]
|[<img alt="washort's avatar" src="https://avatars.githubusercontent.com/u/947487?s=50" width="50" height="50">](https://github.com/washort)| @washort reported|
|-|-|
|Trac ID|trac#3582|
|Type|enhancement|
|Created|2008-12-16 19:04:10Z|
|Branch|https://github.com/twisted/twisted/tree/sip-uri-3582-2|

Among other things, the current address and URI parsing code handles escaping incorrectly.

Attachments:

* [twisted3582.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/70c/70c10e8f744e83bdf3da720244ce8d0a8490fc45/1aaff2ddea3f6488df2ddd7c58f0ed8be9daa0dd.patch) (74120 bytes) - added by necaris on 2012-03-14 00:24:14Z - Updated patch against trunk with several fixes
* [3582.bugfix](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/70c/70c10e8f744e83bdf3da720244ce8d0a8490fc45/4c2a1713a81d90118d1e83ac483a986ad651d9c9.bugfix) (82 bytes) - added by necaris on 2012-03-14 07:02:48Z - 
* [twisted3582_against_branch.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/70c/70c10e8f744e83bdf3da720244ce8d0a8490fc45/ec43468524544ef734211e31ab6ca35a891886a4.patch) (1010 bytes) - added by necaris on 2012-03-14 18:51:28Z - Patch against the branch correcting issues raised

<details><summary>Searchable metadata</summary>

```
trac-id__3582 3582
type__enhancement enhancement
reporter__washort washort
priority__highest highest
milestone__ 
branch__branches_sip_uri_3582_2 branches/sip-uri-3582-2
branch_author__washort__acapnotic washort, acapnotic
status__assigned assigned
resolution__ 
component__core core
keywords__ 
time__1229454250000000 1229454250000000
changetime__1331902001000000 1331902001000000
version__None None
owner__necaris necaris

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="washort's avatar" src="https://avatars.githubusercontent.com/u/947487?s=50" width="50" height="50">](https://github.com/washort)<a name="note_1"></a>|@washort commented|
|-|-|

(In [25684]) Branching to 'sip-uri-3582'

**Comment by twisted-trac** [comment]
|[<img alt="washort's avatar" src="https://avatars.githubusercontent.com/u/947487?s=50" width="50" height="50">](https://github.com/washort)|@washort set owner to @washort|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="washort's avatar" src="https://avatars.githubusercontent.com/u/947487?s=50" width="50" height="50">](https://github.com/washort)|@washort removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_4"></a>|@therve set owner to dash|
|-|-|

Here we go!

 * There are some conflicts with trunk
 * In `headerCapitalize`, the lower() call is not tested
 * Why is the `dashCapitalize` deprecation commented?
 * Can you add a blank lines between fields documentation, and indent the subsequent lines? Like this for example:
```
    @ivar host: A hostname or IP address.
    @type host: C{str}

    @ivar username: The identifier of a particular resource at the host being
        addressed.
    @type username: C{str}, or None.
```
 * the removal of tag in URL is a backward incompatible change.
 * `URI.__ne__` is not tested.
 * `URI.__hash__` has few test coverage, and I suspect is a bit wrong. Objects that are equals must have the same hash, but the current implementation is missing several attributes.
 * the first lower() call in `parseURL` is not tested.
 * 
```
+        return "", parseURL(address, host=host, port=port), params
```
I suspect it should be `u""`.
   * 
```
+    return name.decode('utf8','replace'), url, params
```
 The usage of replace is not tested. Please add a space after the comma, too.

Thanks!

**Comment by twisted-trac** [comment]
|<img alt="necaris's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_5"></a>|necaris removed owner|
|-|-|

Patch attached against trunk, addressing issues raised in the last review:
  * Merge conflicts fixed against trunk
  * `headerCapitalize` now has a test case
  * `dashCapitalize` is deprecated again
  * fields documentation has been reformatted
  * `tag` in `URI` remains out, but it's been confirmed that `tag` is actually an attribute of the surrounding header and not of the URI itself, so shouldn't have been there originally
  * `URI.__eq__` (and by extension `URI.__ne__`, which calls `not self.__eq__()`) have more tests
  * `URI.__hash__` has better tests and a corrected implementation that passes them
  * `parseURL` has a test case for how it treats capitalization
  * `parseURL` also now returns a Unicode string
  * `parseURL` has a test case for its use of string.decode('utf8', 'replace')

There are also some formatting / coding style updates, and the tests have been moved from `twisted/test/test_sip.py` to `twisted/protocol/test/test_sip.py`

**Comment by twisted-trac** [comment]
|[<img alt="keturn's avatar" src="https://avatars.githubusercontent.com/u/83819?s=50" width="50" height="50">](https://github.com/keturn)<a name="note_6"></a>|@keturn commented|
|-|-|

(In [33795]) Branching to 'sip-uri-3582-2'

**Comment by twisted-trac** [comment]
|[<img alt="keturn's avatar" src="https://avatars.githubusercontent.com/u/83819?s=50" width="50" height="50">](https://github.com/keturn)|@keturn set owner to @keturn<br>@keturn set status to `assigned`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="keturn's avatar" src="https://avatars.githubusercontent.com/u/83819?s=50" width="50" height="50">](https://github.com/keturn)<a name="note_8"></a>|@keturn commented|
|-|-|

I appreciate your attention to detail on the tests here.  I believe you've addressed all the previous reviewer's comments, and I have nothing to add.  It's always great to get old patches out of limbo, thanks for bringing some new energy to this!

+1, will merge.

**Comment by twisted-trac** [comment]
|[<img alt="keturn's avatar" src="https://avatars.githubusercontent.com/u/83819?s=50" width="50" height="50">](https://github.com/keturn)<a name="note_9"></a>|@keturn set status to `closed`|
|-|-|

(In [33801]) Merge sip-uri-3582-2: Better escaping and equality comparisons for SIP URLs.URLs.

Authors: washort, necaris
Reviewers: acapnotic, therve
Fixes: [#3582](https://github.com/twisted/twisted/issues/3582)

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_10"></a>|@thijstriemstra commented|
|-|-|

A new deprecation was introduced by this ticket, but it's version nr is incorrect;

```
@deprecated(Version("Twisted", 8, 2, 0)) 
```

There's also not a test for this deprecation.

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_11"></a>|@thijstriemstra commented|
|-|-|

The test case name is also incorrect. I'll open a new ticket for these issues instead of reverting this..

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_12"></a>|@exarkun set status to `reopened`|
|-|-|

(In [33815]) Revert r33801 - test suite regression

Reopens: [#3582](https://github.com/twisted/twisted/issues/3582)

The `twisted.protocols.sip` module docstring has formatting errors.

Also a test fails, at least on Python 2.5:

```
[FAIL]
Traceback (most recent call last):
  File "/var/lib/buildbot/bot-glyph-3/hardy32-python2.5-select/Twisted/twisted/protocols/test/test_sip.py", line 584, in testParseAddress
    self.assertEqual(name, gname)
  File "/var/lib/buildbot/bot-glyph-3/hardy32-python2.5-select/Twisted/twisted/trial/unittest.py", line 270, in assertEqual
    % (msg, pformat(first), pformat(second)))
twisted.trial.unittest.FailTest: not equal:
a = u'Invalid \ufffd('
b = u'Invalid \ufffd'
```

twisted.protocols.test.test_sip.ParseTestCase.testParseAddress

**Comment by twisted-trac** [comment]
|<img alt="necaris's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_13"></a>|necaris removed owner<br>necaris set status to `new`|
|-|-|

Replying to [exarkun](#note_12):
> (In [33815]) Revert r33801 - test suite regression
> 
> Reopens: [#3582](https://github.com/twisted/twisted/issues/3582)
> 
> The `twisted.protocols.sip` module docstring has formatting errors.

Oops, sorry about that.

> 
> Also a test fails, at least on Python 2.5:
> 
> ```
> [FAIL]
> Traceback (most recent call last):
>   File "/var/lib/buildbot/bot-glyph-3/hardy32-python2.5-select/Twisted/twisted/protocols/test/test_sip.py", line 584, in testParseAddress
>     self.assertEqual(name, gname)
>   File "/var/lib/buildbot/bot-glyph-3/hardy32-python2.5-select/Twisted/twisted/trial/unittest.py", line 270, in assertEqual
>     % (msg, pformat(first), pformat(second)))
> twisted.trial.unittest.FailTest: not equal:
> a = u'Invalid \ufffd('
> b = u'Invalid \ufffd'
> ```
> 
> twisted.protocols.test.test_sip.ParseTestCase.testParseAddress
>

Argh -- I believe this is a change in Python's Unicode handling between 2.5 and 2.6 :-( I've changed the test to look at individual invalid characters rather than composing characters, which tests the relevant functionality but is less dependent on this particular behavior of Python 2.6+

I've attached a patch against the branch which addresses both these issues.

**Comment by twisted-trac** [comment]
|[<img alt="MostAwesomeDude's avatar" src="https://avatars.githubusercontent.com/u/118035?s=50" width="50" height="50">](https://github.com/MostAwesomeDude)<a name="note_14"></a>|@MostAwesomeDude commented|
|-|-|

(In [33845]) t.p.test.test_sip: Apply latest patch from [[#3582](https://github.com/twisted/twisted/issues/3582)](https://github.com/twisted/twisted/issues/3582).

Refs #3582

**Comment by twisted-trac** [comment]
|[<img alt="MostAwesomeDude's avatar" src="https://avatars.githubusercontent.com/u/118035?s=50" width="50" height="50">](https://github.com/MostAwesomeDude)<a name="note_15"></a>|@MostAwesomeDude set owner to @exarkun|
|-|-|

http://buildbot.twistedmatrix.com/boxes-supported?branch=/branches/sip-uri-3582-2 has builds for this branch.

After applying the provided patch (and committing it to the branch), I am not able to reproduce the test failure. Additionally, I think that the patch does adequately address the most recent review issues. However, I want exarkun to sign off on this, since he was the reopener, and I want to wait for the builds to finish so that we can be sure there aren't more failures.

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_16"></a>|@thijstriemstra set owner to @MostAwesomeDude|
|-|-|

 - `URI` needs an `@since: 12.1`
 - Many classes and methods still use `"""Allow looking up physical address for logical URL."""` but should use:
```
"""
Allow looking up physical address for logical URL.
""" 
```
 - `dashCapitalize` is deprecated but this doesn't have a test. It also uses the incorrect version nr (should be 12.1)
```
@deprecated(Version("Twisted", 8, 2, 0))
```

**Comment by twisted-trac** [comment]
|<img alt="necaris's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_17"></a>|necaris set owner to necaris<br>necaris set status to `assigned`|
|-|-|

I'm on it.
