### ISSUE TITLE
sqlite3 "created in different thread" - error after shutdown of reactor (using adbapi)

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3629]
|<img alt="VspRcr's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| VspRcr reported|
|-|-|
|Trac ID|trac#3629|
|Type|defect|
|Created|2009-01-22 16:30:06Z|

Error is triggered at shutdown of reactor:
Only caused, if during program execution a database connection was established.

Python version: 2.5.2.2
 
Twisted 8.2.0 (No error in 8.1.0)

Result of attached testscript after reactor shutdown.

```
QueryResult:[(u'myName', u'myId')][[BR]]
Traceback (most recent call last):
  File "C:\Python25\Lib\site-packages\twisted\internet\defer.py", line 186, in addCallbacks
    self._runCallbacks()
  File "C:\Python25\Lib\site-packages\twisted\internet\defer.py", line 328, in _runCallbacks
    self.result = callback(self.result, *args, **kw)
  File "C:\Python25\lib\site-packages\twisted\internet\base.py", line 387, in _continueFiring
    callable(*args, **kwargs)
  File "C:\Python25\lib\site-packages\twisted\enterprise\adbapi.py", line 374, in finalClose
    self._close(conn)
--- <exception caught here> ---
  File "C:\Python25\lib\site-packages\twisted\enterprise\adbapi.py", line 420, in _close
    conn.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 5972 and this is thread id 4916
```

Attachments:

* [testForBug.py](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/294/29485fc5d92edd753a746edf8c924f0b87e25346/166b53616f535ec2b159b3716c6e8b0ea81f542f.py) (406 bytes) - added by VspRcr on 2009-01-22 16:31:20Z - Testscript to trigger error
* [test.sqlite](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/294/29485fc5d92edd753a746edf8c924f0b87e25346/1ac13805cd9b5f069e51a25f70d1d88f47ea6696.sqlite) (3072 bytes) - added by VspRcr on 2009-01-22 16:31:57Z - Sample test DB

<details><summary>Searchable metadata</summary>

```
trac-id__3629 3629
type__defect defect
reporter__VspRcr VspRcr
priority__low low
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__ 
time__1232641806000000 1232641806000000
changetime__1255045833000000 1255045833000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_2"></a>|@therve set owner to @therve|
|-|-|

I've started to look at it, and the bug is present in 8.1, but the exception is swallowed.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_3"></a>|@exarkun commented|
|-|-|

The _regular-releases_ milestone is for release automation tickets.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_4"></a>|@exarkun commented|
|-|-|

Clearly _finalClose_ is using the connection objects in a thread where it may not be allowable to use them.  It should be asking each worker thread in the threadpool to close the connection which belongs to it.  It's not very clear how to do this, though.

Some ideas:

  * There could be an API for saying "run this function in this thread" on `ThreadPool`.  This could be used by `finalClose` to tell each thread to close its connection object.  I think this has a problem that it assumes the threadpool won't create and destroy threads at times other than startup and shutdown though (so you might end up with a connection for which the creating thread no longer even exists).
  * `finalClose` could put a bunch of jobs into the `ThreadPool` which find the connection for the thread they end up running in and close it.  The problem with this is that there's no guarantee that each thread will get exactly one of these jobs.  It will be hard to make sure every connection is cleaned up.
  * There could be an API for specifying a worker thread cleanup function.  This would just run whenever the threadpool is going to let a worker thread exit.  I can't think of the problem with this.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_6"></a>|@exarkun commented|
|-|-|

[#4040](https://github.com/twisted/twisted/issues/4040) was a duplicate of this.

**Comment by twisted-trac** [comment]
|[<img alt="jyknight's avatar" src="https://avatars.githubusercontent.com/u/873903?s=50" width="50" height="50">](https://github.com/jyknight)<a name="note_7"></a>|@jyknight commented|
|-|-|

Easy workaround: pass check_same_thread=False to ConnectionPool's (and thus by indirection, sqlite's) constructor.

It's actually completely safe, the module is just overprotective.

That said, the connection pool / thread pool should still be modified to do the teardown in the same thread.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
