### ISSUE TITLE
Possible error with key authentication of twisted conch

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3630]
|<img alt="sakalsiz's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| sakalsiz reported|
|-|-|
|Trac ID|trac#3630|
|Type|defect|
|Created|2009-01-23 13:02:17Z|
|Branch|https://github.com/twisted/twisted/tree/alternate-dsa-key-3630|

I have a python script that executes a python code on a remote host using SSH. It was working perfectly with Twisted 2.5. The method of returning private and public has changed in userauth.SSHUserAuthClient (Twisted 8.1).

I was using (Twisted 2.5)
------------------------------------------------
```python
def getPublicKey(self):
  return keys.getPublicKeyString(self.keyfile+'.pub')

def getPrivateKey(self):
  return defer.succeed(keys.getPrivateKeyObject(self.keyfile))
```

Now I am using (Twisted 8.1)
----------------------------------------------------
```python
def getPublicKey(self):
  return keys.Key.fromFile(self.keyfile+'.pub')

def getPrivateKey(self):
  return defer.succeed(keys.Key.fromFile(self.keyfile))
```

and it doesn't work any more. I have attached the simplified script. Here is the scenario I am using and the exception I got. Any help is greatly appreciated.

Scenario
----------------------
I am creating a DSA key using ssh-keygen (in Debian and Ubuntu) with an empty password

```
$ ssh-keygen -t dsa
```

and copy it to my localhost

```
$ ssh-copy-id -i ~/.ssh/id_dsa localhost
```

then run the attached script, which tries to execute a python script remotely using SSH and get the following error

```
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/twisted/internet/selectreactor.py", line 146, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "/usr/lib/python2.5/site-packages/twisted/internet/tcp.py", line 362, in doRead
    return self.protocol.dataReceived(data)
  File "/usr/lib/python2.5/site-packages/twisted/conch/ssh/transport.py", line 314, in dataReceived
    self.dispatchMessage(messageNum, packet[1:])
  File "/usr/lib/python2.5/site-packages/twisted/conch/ssh/transport.py", line 336, in dispatchMessage
    messageNum, payload)
--- <exception caught here> ---
  File "/usr/lib/python2.5/site-packages/twisted/python/log.py", line 51, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/lib/python2.5/site-packages/twisted/python/log.py", line 36, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/lib/python2.5/site-packages/twisted/python/context.py", line 59, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.5/site-packages/twisted/python/context.py", line 37, in callWithContext
    return func(*args,**kw)
  File "/usr/lib/python2.5/site-packages/twisted/conch/ssh/service.py", line 44, in packetReceived
    return f(packet)
  File "/usr/lib/python2.5/site-packages/twisted/conch/ssh/userauth.py", line 262, in ssh_USERAUTH_FAILURE
    if method not in self.authenticatedWith and self.tryAuth(method):
  File "/usr/lib/python2.5/site-packages/twisted/conch/ssh/userauth.py", line 234, in tryAuth
    return f()
  File "/usr/lib/python2.5/site-packages/twisted/conch/ssh/userauth.py", line 338, in auth_publickey
    keyType = getNS(publicKey)[0]
  File "/usr/lib/python2.5/site-packages/twisted/conch/ssh/common.py", line 51, in getNS
    l, = struct.unpack('!L',s[c:c+4])
exceptions.TypeError: 'Key' object is unsubscriptable
```

Attachments:

* [mysshconnection.py](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/99e/99ef7eebfcedca0e81c870e0d340e94d16cb302f/5d8c074dc9cd71278ff74af3ff2ca4e8383646e8.py) (7645 bytes) - added by sakalsiz on 2009-01-23 13:02:57Z - Sample script trying to execute a remote process using SSH

<details><summary>Searchable metadata</summary>

```
trac-id__3630 3630
type__defect defect
reporter__sakalsiz sakalsiz
priority__normal normal
milestone__Twisted_9_0 Twisted-9.0
branch__branches_alternate_dsa_key_3630 branches/alternate-dsa-key-3630
branch_author__therve therve
status__closed closed
resolution__duplicate duplicate
component__conch conch
keywords__ 
time__1232715737000000 1232715737000000
changetime__1246380988000000 1246380988000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|<img alt="z3p's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_2"></a>|z3p commented|
|-|-|

Twisted 8.1 doesn't support returning Key objects from getPublicKey.  If you want to be able to do that, you should look at the userauth-2682-6 branch (for bug [#2682](https://github.com/twisted/twisted/issues/2682)) which updates userauth.py to accept Key objects.

**Comment by twisted-trac** [comment]
|<img alt="sakalsiz's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_3"></a>|sakalsiz commented|
|-|-|

Replying to [z3p](#note_2):

Isn't there a way to make ssh connections using a key authentication with current snapshots or releases.

**Comment by twisted-trac** [comment]
|<img alt="sakalsiz's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_4"></a>|sakalsiz commented|
|-|-|

I also tried the userauth-2682-6 branch, it still doesn't work. Raises the following exception

```
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/twisted/internet/selectreactor.py", line 146, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "/usr/lib/python2.5/site-packages/twisted/internet/tcp.py", line 362, in doRead
    return self.protocol.dataReceived(data)
  File "/usr/lib/python2.5/site-packages/twisted/conch/ssh/transport.py", line 314, in dataReceived
    self.dispatchMessage(messageNum, packet[1:])
  File "/usr/lib/python2.5/site-packages/twisted/conch/ssh/transport.py", line 336, in dispatchMessage
    messageNum, payload)
--- <exception caught here> ---
  File "/usr/lib/python2.5/site-packages/twisted/python/log.py", line 51, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/lib/python2.5/site-packages/twisted/python/log.py", line 36, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/lib/python2.5/site-packages/twisted/python/context.py", line 59, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.5/site-packages/twisted/python/context.py", line 37, in callWithContext
    return func(*args,**kw)
  File "/usr/lib/python2.5/site-packages/twisted/conch/ssh/service.py", line 44, in packetReceived
    return f(packet)
  File "/usr/lib/python2.5/site-packages/twisted/conch/ssh/userauth.py", line 531, in ssh_USERAUTH_PK_OK
    return func(packet)
  File "/usr/lib/python2.5/site-packages/twisted/conch/ssh/userauth.py", line 545, in ssh_USERAUTH_PK_OK_publickey
    d  = self.signData(publicKey, b)
  File "/usr/lib/python2.5/site-packages/twisted/conch/ssh/userauth.py", line 726, in signData
    key = self.getPrivateKey()
  File "mysshconnection.py", line 142, in getPrivateKey
    return defer.succeed(keys.Key.fromFile(self.keyfile))
  File "/usr/lib/python2.5/site-packages/twisted/conch/ssh/keys.py", line 60, in fromFile
    return Class.fromString(file(filename, 'rb').read(), type, passphrase)
  File "/usr/lib/python2.5/site-packages/twisted/conch/ssh/keys.py", line 88, in fromString
    return method(data, passphrase)
  File "/usr/lib/python2.5/site-packages/twisted/conch/ssh/keys.py", line 232, in _fromString_PRIVATE_OPENSSH
    p, q, g, y, x = decodedKey[1: 6]
exceptions.ValueError: need more than 1 value to unpack
```

I changed the line at keys.py:231

```python
p, q, g, y, x = decodedKey[1: 6]
```

with the following

```python
p, q, g, y, x = decodedKey[0][1: 6]
```

then worked.

**Comment by twisted-trac** [comment]
|<img alt="z3p's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_5"></a>|z3p commented|
|-|-|

Replying to [sakalsiz](#note_3):
> Replying to [z3p](#note_2):
>
> Isn't there a way to make ssh connections using a key authentication with current snapshots or releases.

Yes; you can use the basically the same code that worked in Twisted 2.5.  To avoid the warnings, just replace the code you have with what the warning tells you to use.

**Comment by twisted-trac** [comment]
|<img alt="sakalsiz's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_6"></a>|sakalsiz commented|
|-|-|

Replying to [z3p](#note_5):
> Replying to [sakalsiz](#note_3):
> > Replying to [z3p](#note_2):
> >
> > Isn't there a way to make ssh connections using a key authentication with current snapshots or releases.
>
> Yes; you can use the basically the same code that worked in Twisted 2.5.  To avoid the warnings, just replace the code you have with what the warning tells you to use.

I already tried both, but none of them works. That's why I opened this ticket.

**Comment by twisted-trac** [comment]
|<img alt="z3p's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_7"></a>|z3p commented|
|-|-|

Replying to [sakalsiz](#note_6):
> I already tried both, but none of them works. That's why I opened this ticket.

Try:

```
def getPublicKey(self):
  return keys.Key.fromFile(self.keyfile+'.pub').blob()
def getPrivateKey(self):
  return defer.succeed(keys.Key.fromFile(self.keyfile).keyObject)
```

**Comment by twisted-trac** [comment]
|<img alt="sakalsiz's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_8"></a>|sakalsiz commented|
|-|-|

Replying to [z3p](#note_7):
> Replying to [sakalsiz](#note_6):
> > I already tried both, but none of them works. That's why I opened this ticket.
>
> Try:
>
> ```
> def getPublicKey(self):
>   return keys.Key.fromFile(self.keyfile+'.pub').blob()
> def getPrivateKey(self):
>   return defer.succeed(keys.Key.fromFile(self.keyfile).keyObject)
> ```


Still doesn't work, requires the patch above I proposed. It also gives warnings.

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_9"></a>|@therve set owner to @therve|
|-|-|

I can reproduce the problem.

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_10"></a>|@therve commented|
|-|-|

(In [27038]) Branching to 'alternate-dsa-key-3630'

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_11"></a>|@therve set status to `closed`|
|-|-|

This is a duplicate of [#3391](https://github.com/twisted/twisted/issues/3391) in the end.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
