### ISSUE TITLE
problem with kqreactor on daemonize

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3636]
|<img alt="p0is0n's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| p0is0n reported|
|-|-|
|Trac ID|trac#3636|
|Type|defect|
|Created|2009-01-30 11:12:44Z|

```
# -*- coding: utf8 -*-

import os

from twisted.internet import kqreactor

kqreactor.install()

from twisted.internet import reactor
from twisted.python import log
from twisted.scripts import _twistd_unix as twistd

log.startLogging \
(
	open('/tmp/test.log', 'w')
)

twistd.daemonize()

reactor.run()

```

after run this script CPU >= 80% and on log file

```
2009-01-30 17:00:28+0600 [-] Unexpected error in main loop.
2009-01-30 17:00:28+0600 [-] Unhandled Error
        Traceback (most recent call last):
          File "test.py", line 20, in <module>
            reactor.run()
          File "/usr/local/lib/python2.6/site-packages/Twisted-8.2.0_r26131-py2.6-freebsd-6.3-STABLE-i386.egg/twisted/internet/base.py", line 1148, in run
            self.mainLoop()
        --- <exception caught here> ---
          File "/usr/local/lib/python2.6/site-packages/Twisted-8.2.0_r26131-py2.6-freebsd-6.3-STABLE-i386.egg/twisted/internet/base.py", line 1160, in mainLoop
            self.doIteration(t)
          File "/usr/local/lib/python2.6/site-packages/Twisted-8.2.0_r26131-py2.6-freebsd-6.3-STABLE-i386.egg/twisted/internet/kqreactor.py", line 178, in doKEvent
            l = self._kq.kevent([], len(self._selectables), timeout)
        exceptions.OSError: [Errno 9] Bad file descriptor
```

if delete line "twistd.daemonize()" this error not raised

python 2.6 FreeBSD 6.3-STABLE PyKQueue-1.4 (http://ox.eicat.ca/~dgilbert/files/)

<details><summary>Searchable metadata</summary>

```
trac-id__3636 3636
type__defect defect
reporter__p0is0n p0is0n
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__invalid invalid
component__core core
keywords__ 
time__1233313964000000 1233313964000000
changetime__1233324461000000 1233324461000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="radix's avatar" src="https://avatars.githubusercontent.com/u/227068?s=50" width="50" height="50">](https://github.com/radix)<a name="note_1"></a>|@radix set status to `closed`|
|-|-|

Great. You removed an incorrect usage of a private API and your problem went away.

(Don't use private APIs)

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
