### ISSUE TITLE
Words IRC Server does not implement AWAY

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3668]
|[<img alt="tenth10th's avatar" src="https://avatars.githubusercontent.com/u/854235?s=50" width="50" height="50">](https://github.com/tenth10th)| @tenth10th reported|
|-|-|
|Trac ID|trac#3668|
|Type|enhancement|
|Created|2009-02-23 00:43:58Z|
|Branch|https://github.com/twisted/twisted/tree/irc-away-3668|

Here's the traceback you get when Pidgin attempts to log into a Words server:

```
2009-02-22 19:26:06-0500 [IRCUser,0,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/glyph/Projects/Twisted/trunk/twisted/python/context.py", line 37, in callWithContext
	    return func(*args,**kw)
	  File "/home/glyph/Projects/Twisted/trunk/twisted/internet/selectreactor.py", line 146, in _doReadOrWrite
	    why = getattr(selectable, method)()
	  File "/home/glyph/Projects/Twisted/trunk/twisted/internet/tcp.py", line 459, in doRead
	    return self.protocol.dataReceived(data)
	  File "/home/glyph/Projects/Twisted/trunk/twisted/words/protocols/irc.py", line 172, in dataReceived
	    self.handleCommand(command, prefix, params)
	--- <exception caught here> ---
	  File "/home/glyph/Projects/Twisted/trunk/twisted/words/protocols/irc.py", line 184, in handleCommand
	    self.irc_unknown(prefix, command, params)
	  File "/home/glyph/Projects/Twisted/trunk/twisted/words/protocols/irc.py", line 191, in irc_unknown
	    raise NotImplementedError(command, prefix, params)
	exceptions.NotImplementedError: ('AWAY', '', [])
```

Attachments:

* [ircAway.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/03f/03f62922b20ef510890482414ea2c0f123fed81f/6fc358a883b9b7cc4a570e328f9f6f406defda90.patch) (8747 bytes) - added by elitak on 2009-09-19 00:20:31Z - svn patch on main branch
* [ircAway-2.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/03f/03f62922b20ef510890482414ea2c0f123fed81f/5d6c301e58b8f246b71e0b3c2412297d3284c5f3.patch) (10485 bytes) - added by elitak on 2009-09-21 18:35:09Z - Here's the new patch

<details><summary>Searchable metadata</summary>

```
trac-id__3668 3668
type__enhancement enhancement
reporter__tenth tenth
priority__low low
milestone__ 
branch__branches_irc_away_3668 branches/irc-away-3668
branch_author__therve therve
status__new new
resolution__None None
component__words words
keywords__ 
time__1235349838000000 1235349838000000
changetime__1268269295000000 1268269295000000
version__None None
owner__elitak elitak
cc__jesstess
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

Fixing description markup

**Comment by twisted-trac** [comment]
|<img alt="elitak's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_2"></a>|elitak commented|
|-|-|

I've attached the implementation that I worked out, along with a unit test. Let me know if there are any problems with either.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_3"></a>|@exarkun removed owner|
|-|-|

Submitting this for review for elitak.

**Comment by twisted-trac** [comment]
|[<img alt="jesstess's avatar" src="https://avatars.githubusercontent.com/u/188336?s=50" width="50" height="50">](https://github.com/jesstess)<a name="note_4"></a>|@jesstess set owner to elitak|
|-|-|

Thanks for the patch elitak!

I have a couple of stylistic comments:

 1. There's trailing whitespace in the test_awayMessage docstring.
 1. In test_awayMessage, use a tuple around your value(s) for string formatting operations. The intention is to avoid unexpected behavior when you think you're passing in a single value, but the value is unexpectedly a tuple.
 1. class User doesn't have a docstring, and since you added the instance variable awayMessage it would be great if you could give it a docstring with markup (@ivar, @type) for each of the instance variables.
 1. getAway and setAway should have docstrings, with markup for the parameter (@param, @type) to setAway and the return value (@return, @rtype) from getAway
 1. The docstring quotes should be on lines by themselves in irc_AWAY. Also please use @param and @type instead of the word 'PARAMETERS'.
 1. The copyright date on services.py needs to be bumped to 2009.

The [Twisted Coding Standard](http://twistedmatrix.com/trac/browser/trunk/doc/core/development/policy/coding-standard.xhtml?format=raw) describes the style conventions more completely.

**Comment by twisted-trac** [comment]
|<img alt="elitak's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_5"></a>|elitak commented|
|-|-|

1. Fixed, along with a few other lines that weren't mine.
2. Fixed
3. Done
4. I removed these since the attribute really didn't need a getter nor setter. If they're needed later on they can be added by making the attribute a property.
5. Fixed. (I was copying the style of other comments)
6. Changed to 2001-2009.

Trac wasn't willing to serve me the Coding Standard page the day I submitted this, so I was unable to check for compliance and had to just mimic what was already in that file. The whole IRC service needs some cleanup, but I'll leave that for a later patch.

**Comment by twisted-trac** [comment]
|<img alt="elitak's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_6"></a>|elitak removed owner|
|-|-|

I'm sending this back in for another review? Not sure how/if I'm supposed to do this -- Here's my best guess.

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)|@therve set owner to @therve|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_8"></a>|@therve commented|
|-|-|

(In [27484]) Branching to 'irc-away-3668'

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_9"></a>|@therve set owner to @tenth10th|
|-|-|

Thanks a lot for the nice patch, and sorry for not looking at it sooner. Here are my comments:
 * you need to handle specially groups in the receive method. Some tests in test_service are failing because of that, so it should be easy to track down.
 * the `awayMessage` attribute should probably be added to the `IUser` interface.

I've committed your patch in the attached branch, please provide the changes as a diff against it. Thanks!

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_10"></a>|@exarkun commented|
|-|-|

I fixed the failing tests.  Some other thoughts:

  1. `awayMessage` could be private (rather than added to `IUser` - the current code no longer needs to access it from arbitrary `IUser` providers).  It's an implementation detail of the IRC `IUser` avatar.
  1. The code is calling `sendMessage` on an object documented as providing `IUser`.  This only works as long as only IRC is involved (and only as long as the current implementation is used).  You should only call `IUser` methods.  `IUser.mind.receive` will probably work.  However, you'll have to come up with a way to represent the message as an IRC AWAY response, rather than a normal PRIVMSG.  Perhaps by adding an extra key to the message dictionary.

**Comment by twisted-trac** [comment]
|[<img alt="tenth10th's avatar" src="https://avatars.githubusercontent.com/u/854235?s=50" width="50" height="50">](https://github.com/tenth10th)<a name="note_11"></a>|@tenth10th set owner to elitak|
|-|-|

I think this was meant to be reassigned to elitak (I have not worked on this particular branch...)
