### ISSUE TITLE
Reactor stop claims reactor not running when both a callLater and a StandardIO are active

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3680]
|<img alt="bhyde's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| bhyde reported|
|-|-|
|Trac ID|trac#3680|
|Type|defect|
|Created|2009-03-07 15:44:04Z|

```

bash-3.2$ (sleep 2; date +%s; sleep 2; date +%s ; sleep 10) | /tmp/bar.py
1236440028
1236440030
done
Traceback (most recent call last):
  File "/opt/local/lib/python2.5/site-packages/twisted/python/context.py", line 59, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/opt/local/lib/python2.5/site-packages/twisted/python/context.py", line 37, in callWithContext
    return func(*args,**kw)
  File "/opt/local/lib/python2.5/site-packages/twisted/internet/process.py", line 258, in connectionLost
    self.proc.childConnectionLost(self.name, reason)
  File "/opt/local/lib/python2.5/site-packages/twisted/internet/_posixstdio.py", line 86, in childConnectionLost
    self.connectionLost(reason)
--- <exception caught here> ---
  File "/opt/local/lib/python2.5/site-packages/twisted/internet/_posixstdio.py", line 105, in connectionLost
    protocol.connectionLost(reason)
  File "/tmp/bar.py", line 9, in connectionLost
    def connectionLost(self, why): reactor.stop()
  File "/opt/local/lib/python2.5/site-packages/twisted/internet/base.py", line 490, in stop
    "Can't stop reactor that isn't running.")
twisted.internet.error.ReactorNotRunning: Can't stop reactor that isn't running.
bash-3.2$ cat /tmp/bar.py
#!/usr/bin/env python
from twisted.internet import reactor
from twisted.protocols.basic import LineOnlyReceiver
from twisted.internet.stdio import StandardIO

class MyLineOnlyReceiver(LineOnlyReceiver):
    delimiter = '\n'
    def lineReceived(self, line): print line
    def connectionLost(self, why): reactor.stop()

if __name__ == '__main__':
    StandardIO(MyLineOnlyReceiver())
    def finish():
        print 'done'
        reactor.stop()
    reactor.callLater(10, finish)
    reactor.run() 
bash-3.2$ port info 'py25-twisted'
py25-twisted @8.0.1 (python, devel, net)

Twisted is an event-driven networking framework written in Python. Twisted supports TCP,
UDP, SSL/TLS, multicast, Unix sockets, a large number of protocols (including HTTP, NNTP,
SSH, IRC, FTP, and others), and much more.
Homepage:    http://www.twistedmatrix.com/

Library Dependencies: python25, py25-zopeinterface
Maintainers:          stechert@... akitada@...
                      openmaintainer@...
bash-3.2$ python -V
Python 2.5.4
bash-3.2$ uname -a
Darwin d72.cozy.org 9.6.0 Darwin Kernel Version 9.6.0: Mon Nov 24 17:37:00 PST 2008; root:xnu-1228.9.59~1/RELEASE_I386 i386 i386
bash-3.2$ 
```

<details><summary>Searchable metadata</summary>

```
trac-id__3680 3680
type__defect defect
reporter__bhyde bhyde
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__wontfix wontfix
component__core core
keywords__ 
time__1236440644000000 1236440644000000
changetime__1236441041000000 1236441041000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun set status to `closed`|
|-|-|

The example code calls `reactor.stop()` _twice_.  First in `finish`, then later in `MyLineOnlyReceiver.connectionLost`.  The second call to `reactor.stop()` is the one that fails, because indeed the reactor is already shutting down.

**Comment by twisted-trac** [comment]
|<img alt="bhyde's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_2"></a>|bhyde commented|
|-|-|

Sweet.  Thanks.  I'm an idiot.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
