### ISSUE TITLE
Add environment configuration support to twisted.runner.procmon

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3691]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#3691|
|Type|enhancement|
|Created|2009-03-16 20:59:02Z|
|Branch|https://github.com/twisted/twisted/tree/procmon-env-3691|

`ProcessMonitor.addProcess` allows several of the parameters for running a process to be specified: the arguments, the uid, and the gid.  It doesn't allow the environment to use to be specified, though.  `addProcess` should accept an environment dict to pass along to `reactor.spawnProcess`.

<details><summary>Searchable metadata</summary>

```
trac-id__3691 3691
type__enhancement enhancement
reporter__exarkun exarkun
priority__highest highest
milestone__ 
branch__branches_procmon_env_3691 branches/procmon-env-3691
branch_author__washort__exarkun washort, exarkun
status__closed closed
resolution__fixed fixed
component__runner runner
keywords__ 
time__1237237142000000 1237237142000000
changetime__1268081149000000 1268081149000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="washort's avatar" src="https://avatars.githubusercontent.com/u/947487?s=50" width="50" height="50">](https://github.com/washort)<a name="note_1"></a>|@washort commented|
|-|-|

(In [26403]) Branching to 'procmon-env-3691'

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_3"></a>|@exarkun set owner to @washort|
|-|-|

  1. twisted/runner/procmon.py
    1. update copyright date
    1. `addProcess` should have a docstring.
  1. twisted/runner/test/test_procmon.py
    1. two blank lines between methods
    1. `assertEquals` should be preferred in new tests over `assertEqual`

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun set owner to @exarkun<br>@exarkun set status to `assigned`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_5"></a>|@exarkun commented|
|-|-|

(In [26683]) update copyright date, add a docstring for addProcess, fix spacing and switch to `assertEquals`

refs [#3691](https://github.com/twisted/twisted/issues/3691)

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_6"></a>|@exarkun removed owner<br>@exarkun set status to `new`|
|-|-|

Addressed my own feedback; please review.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_8"></a>|@exarkun commented|
|-|-|

(In [26684]) Add a copyright statement and a package docstring for twisted/runner/test/ - fixes that one test in twisted.test which asserts that every module has a docstring

refs [#3691](https://github.com/twisted/twisted/issues/3691)

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_9"></a>|@glyph set owner to @exarkun|
|-|-|


I think this is probably good to merge.  Please fix the unused import of the "time" module in the tests.

Also, feel free to act on these observations:

  1. "processes" is nominally a public attribute, and you are changing its shape here; any other unpackers will die as a result.  Technically an incompatible change - if I thought anyone were using this code programmatically, I'd object.  Yet another example where an object with attributes would have been better :-\.
  2. I just reviewed [#3480](https://github.com/twisted/twisted/issues/3480), and it occurs to me that it's not terribly clear what `env` will do if it's passed, passed as None, etc.  It should probably say "`@see IReactorProcess.spawnProcess`".
  3. The use of `patch()` in the unit tests to replace a method on the reactor, which is an instance, has the peculiar effect of shadowing the class's implementation of the method with an instance-level bound method.  It doesn't look like this bothers anyone yet, but it hypothetically could.  It's really a bug in `twisted.python.monkey.MonkeyPatcher`, though; you _should_ be able to use `patch()` this way.  Want to file a ticket for that?

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_10"></a>|@exarkun commented|
|-|-|

(In [26706]) Remove unused import

refs [#3691](https://github.com/twisted/twisted/issues/3691)

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_11"></a>|@exarkun commented|
|-|-|

(In [26707]) Refer to the IReactorProcess docs for the env parameter

refs [#3691](https://github.com/twisted/twisted/issues/3691)

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_12"></a>|@exarkun commented|
|-|-|

  1. Fixed in r26706
  1. Fixed in r26707
  1. Filed [#3775](https://github.com/twisted/twisted/issues/3775) (which isn't quite for `patch` but I think it is also a valid way to address the issue with this code)

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_13"></a>|@exarkun commented|
|-|-|

Drat.  The test fails on Windows, of course.

```
[ERROR]: twisted.runner.test.test_procmon

Traceback (most recent call last):
  File "c:\buildbot\twisted\WXP32-full2.4-scmikes-select\Twisted\twisted\trial\runner.py", line 555, in loadPackage
    module = modinfo.load()
  File "c:\buildbot\twisted\WXP32-full2.4-scmikes-select\Twisted\twisted\python\modules.py", line 380, in load
    return self.pathEntry.pythonPath.moduleLoader(self.name)
  File "c:\buildbot\twisted\WXP32-full2.4-scmikes-select\Twisted\twisted\python\reflect.py", line 462, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "c:\buildbot\twisted\WXP32-full2.4-scmikes-select\Twisted\twisted\runner\test\test_procmon.py", line 9, in ?
    from twisted.runner.procmon import ProcessMonitor
  File "c:\buildbot\twisted\WXP32-full2.4-scmikes-select\Twisted\twisted\runner\procmon.py", line 51, in ?
    from signal import SIGTERM, SIGKILL
exceptions.ImportError: cannot import name SIGKILL
```

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_14"></a>|@exarkun removed owner|
|-|-|

Okay.  I made a few more changes to procmon.py so that the tests don't explode on Windows.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_15"></a>|@exarkun commented|
|-|-|

I just noticed that I didn't actually fix point 1 in the review.  But I labeled point 1 as fixed because there was an unnumbered point in the review which came before it.

Objects with attributes are great, but I don't think anyone is using this code either.  We should probably retain compatibility here, but it's more work for probably no payoff.  Unless someone asks for it, I don't think it's worthwhile.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_16"></a>|@exarkun commented|
|-|-|

Oh, and I also noticed [#2389](https://github.com/twisted/twisted/issues/2389), which this should resolve.  The test even runs and passes on Windows.

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_17"></a>|@therve set owner to @exarkun|
|-|-|

Fair enough, +1.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_18"></a>|@exarkun set status to `closed`|
|-|-|

(In [26722]) Merge procmon-env-3691

Author: washort, exarkun
Reviewer: glyph, therve
Fixes: [#3691](https://github.com/twisted/twisted/issues/3691)

Add an `env` parameter to `twisted.runner.procmon.ProcessMonitor`'s
`addProcess` method to allow applications to customize the environment
with which a process is run.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_19"></a>|@exarkun commented|
|-|-|

This was a duplicate of [#2314](https://github.com/twisted/twisted/issues/2314).

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
