### ISSUE TITLE
Headers no longer available in requests passed over twisted.web.distrib

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3697]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#3697|
|Type|release blocker: regression|
|Created|2009-03-22 23:05:33Z|
|Branch|https://github.com/twisted/twisted/tree/distrib-request-headers-3697|

`twisted.web.distrib` passes a `Request` object over PB to another process which handles the request and returns a response.

In 8.2, `Request` changed to include an attribute which cannot be serialized by PB (or it can be serialized, but not unserialized, perhaps).  This results in an `Unpersistable` instance on the remote end of a distrib setup (confusingly, `Unpersistable` is what PB calls a problem where something cannot be unpersisted).

The attributes which cause problem are `requestHeaders` and `responseHeaders`.  These are instances of `twisted.web.http_headers.Headers` which apparently don't interact with PB well.

Since this problem doesn't manifest as an exception during serialization or unserialization, the remote end will actually get a `Request` object and try to process it; however, this fails as soon as it tries to access any headers, since they are no longer available.

The failure on the remote end looks often like something like this:

```
2009-03-22 18:59:02-0400 [Broker,0,] <GET /builds HTTP/1.1>
2009-03-22 18:59:02-0400 [Broker,0,] Peer will receive following PB traceback:
2009-03-22 18:59:02-0400 [Broker,0,] Unhandled Error
        Traceback (most recent call last):
          File "/srv/bb-master/Projects/Twisted/trunk/twisted/spread/banana.py", line 148, in gotItem
            self.callExpressionReceived(item)
          File "/srv/bb-master/Projects/Twisted/trunk/twisted/spread/banana.py", line 113, in callExpressionReceived
            self.expressionReceived(obj)
          File "/srv/bb-master/Projects/Twisted/trunk/twisted/spread/pb.py", line 522, in expressionReceived
            method(*sexp[1:])
          File "/srv/bb-master/Projects/Twisted/trunk/twisted/spread/pb.py", line 833, in proto_message
            self._recvMessage(self.localObjectForID, requestID, objectID, message, answerRequired, netArgs, netKw)
        --- <exception caught here> ---
          File "/srv/bb-master/Projects/Twisted/trunk/twisted/spread/pb.py", line 847, in _recvMessage
            netResult = object.remoteMessageReceived(self, message, netArgs, netKw)
          File "/srv/bb-master/Projects/Twisted/trunk/twisted/spread/flavors.py", line 119, in remoteMessageReceived
            state = method(*args, **kw)
          File "/srv/bb-master/Projects/Twisted/trunk/twisted/web/distrib.py", line 201, in remote_request
            return res.render(request)
          File "/srv/bb-master/Projects/Twisted/trunk/twisted/web/static.py", line 304, in render
            return self.redirect(request)
          File "/srv/bb-master/Projects/Twisted/trunk/twisted/web/static.py", line 366, in redirect
            return redirectTo(addSlash(request), request)
          File "/srv/bb-master/Projects/Twisted/trunk/twisted/web/static.py", line 66, in addSlash
            return "http%s://%s%s/%s" % (
          File "/srv/bb-master/Projects/Twisted/trunk/twisted/web/http.py", line 674, in getHeader
            return self.received_headers.get(key.lower())
        exceptions.AttributeError: Unpersistable instance has no attribute 'get'
```

<details><summary>Searchable metadata</summary>

```
trac-id__3697 3697
type__release_blocker__regression release blocker: regression
reporter__exarkun exarkun
priority__highest highest
milestone__ 
branch__branches_distrib_request_headers_3697 branches/distrib-request-headers-3697
branch_author__exarkun exarkun
status__closed closed
resolution__fixed fixed
component__web web
keywords__ 
time__1237763133000000 1237763133000000
changetime__1368183961000000 1368183961000000
version__None None
owner__ 
cc__GaretJax
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

(In [26660]) Branching to 'distrib-request-headers-3697'

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_2"></a>|@exarkun removed owner|
|-|-|

The branch fixes `received_headers` (by fixing `requestHeaders`).  I didn't do anything with `headers` (the backwards compatibility name for `responseHeaders`), though.  Setting things in `headers` directly in a distrib resource didn't previously work - the values would be silently ignored.  You have to use `setHeader`, which wasn't broken by this change, since it bypasses the local `headers` dict entirely and just sends a message to set the header in the master process.  This is kind of dumb, but at least it's not broken.  In the future I think distrib should work differently (or be replaced by something which works differently) and doesn't have so much PB gunk mashed into it.

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_3"></a>|@therve set owner to @exarkun|
|-|-|

One pyflake:
`twisted/web/server.py:17: 'time' imported but unused`


Please merge.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_4"></a>|@exarkun commented|
|-|-|

(In [26695]) Remove unused import

refs [#3697](https://github.com/twisted/twisted/issues/3697)

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_5"></a>|@exarkun set status to `closed`|
|-|-|

(In [26700]) Merge distrib-request-headers-3697

Author: exarkun
Reviewer: therve
Fixes: [#3697](https://github.com/twisted/twisted/issues/3697)

Handle the new `Headers` instance at `twisted.web.http.Request.requestHeaders`
specially when serializing a `Request` over a PB connection (for example, when
sending it to a distrib client) so that the values survive the transmission
rather than morphing into an `Unpersistable` instance.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_6"></a>|@exarkun set status to `reopened`|
|-|-|

(In [26701]) Revert r26700 - new test fails on Python 2.3

Reopens [#3697](https://github.com/twisted/twisted/issues/3697)

On Python 2.3, dict.update does not accept a list of two-tuples, so the new test fails
when it passes such a list to dict.update:

```
[ERROR]: twisted.web.test.test_distrib.DistribTest.test_requestHeaders

Traceback (most recent call last):
  File "/srv/bb-slave/Run/slave/full2.3/Twisted/twisted/spread/pb.py", line 840, in _recvMessage
    netResult = object.remoteMessageReceived(self, message, netArgs, netKw)
  File "/srv/bb-slave/Run/slave/full2.3/Twisted/twisted/spread/flavors.py", line 114, in remoteMessageReceived
    state = method(*args, **kw)
  File "/srv/bb-slave/Run/slave/full2.3/Twisted/twisted/web/distrib.py", line 198, in remote_request
    return res.render(request)
  File "/srv/bb-slave/Run/slave/full2.3/Twisted/twisted/web/test/test_distrib.py", line 93, in render
    requestHeaders.update(
exceptions.AttributeError: keys
```

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_7"></a>|@exarkun removed owner<br>@exarkun set status to `new`|
|-|-|

Build results for the branch after a fix for the Python 2.3 issue in r26702 - http://buildbot.twistedmatrix.com/boxes-supported?branch=/branches/distrib-request-headers-3697

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_8"></a>|@glyph set owner to @exarkun|
|-|-|

The test failures indicate that `twisted.web.test.test_webclient.WebClientSSLTestCase.test_downloadTimeout` is intermittent.  Want to file a ticket for that?

As far as this goes, though, thanks for the handy link to the builds.  It looks fine to me: land it.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_9"></a>|@exarkun set status to `closed`|
|-|-|

(In [26710]) Merge distrib-request-headers-3697

Author: exarkun
Reviewer: therve, glyph
Fixes: [#3697](https://github.com/twisted/twisted/issues/3697)

Handle the new Headers instance at twisted.web.http.Request.requestHeaders
specially when serializing a Request over a PB connection (for example,
when sending it to a distrib client) so that the values survive the
transmission rather than morphing into an Unpersistable instance.  This
re-merge of the branch fixes Python 2.3 compatibility.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="GaretJax's avatar" src="https://avatars.githubusercontent.com/u/86236?s=50" width="50" height="50">](https://github.com/GaretJax)<a name="note_11"></a>|@GaretJax set status to `reopened`|
|-|-|

The description of the ticket mentions both `requestHeaders` and `responseHeaders` being problematic, but only `requestHeaders` are addressed in the branch. The same should be done for `responseHeaders`.

P.S.: Priority was "highest" on this one, I will leave it as is, but given that nobody encountered the problem in 4 years, we may want to set it to a lower value.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_12"></a>|@exarkun set status to `closed`|
|-|-|

Please file a new ticket; don't re-open old, fixed tickets.
