### ISSUE TITLE
Several trial tests fail when comparing the short description of test methods on Python trunk@HEAD

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3739]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#3739|
|Type|defect|
|Created|2009-03-31 21:10:28Z|

```
===============================================================================
[FAIL]: twisted.trial.test.test_class.AttributeSharing.test_shared

Traceback (most recent call last):
  File "/home/exarkun/Projects/Twisted/trunk/twisted/trial/test/test_class.py", line 131, in test_shared
    'test_2')
twisted.trial.unittest.FailTest: not equal:
a = 'test_2 (twisted.trial.test.test_class.ClassAttributeSharer)'
b = 'test_2'

```

```
===============================================================================
[FAIL]: twisted.trial.test.test_tests.TestSkipMethods.test_reasons

Traceback (most recent call last):
  File "/home/exarkun/Projects/Twisted/trunk/twisted/trial/test/test_tests.py", line 143, in test_reasons
    str(reason))
twisted.trial.unittest.FailTest: not equal:
a = 'skip1 (twisted.trial.test.test_tests.SkippingTests)'
b = 'skip1'

```

Attachments:

* [py27_shortDescription.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/acf/acfa9d2d3090d16c63aef6fe2b4f931511eb5bf3/2d0d03d0dd64117c27282a721705e0156a769a8b.patch) (530 bytes) - added by ivank on 2009-05-20 14:58:55Z - looked like the right place to change things, but maybe not

<details><summary>Searchable metadata</summary>

```
trac-id__3739 3739
type__defect defect
reporter__exarkun exarkun
priority__normal normal
milestone__Python_2_7 Python-2.7
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__trial trial
keywords__ 
time__1238533828000000 1238533828000000
changetime__1266281114000000 1266281114000000
version__None None
owner__ 
cc__thijs
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_1"></a>|@thijstriemstra removed owner|
|-|-|

I can only [detect](http://buildbot.twistedmatrix.com/builders/ubuntu64-py2.7-select/builds/71/steps/trial/logs/problems) that the 2nd testcase from the ticket description is still an issue on Python 2.7 alpha 3, seems the first one is fixed by either changes in Twisted, or most likely, changes in Python 2.7 since this ticket was opened. Putting the patch up for review to gather feedback on how to approach this issue.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_2"></a>|@exarkun set owner to @exarkun<br>@exarkun set status to `assigned`|
|-|-|

We deleted `test_class.py` since the ticket was filed.

As for the rest, I think python-dev is going to fix the issue.  See <http://mail.python.org/pipermail/python-dev/2010-February/097520.html>.

Assuming that goes through, we should be able to close this.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_3"></a>|@exarkun set status to `closed`|
|-|-|

http://bugs.python.org/issue7588 was fixed.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
