### ISSUE TITLE
Several trial tests fail when comparing the sorted order of tests on Python 2.7a3

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3740]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#3740|
|Type|defect|
|Created|2009-03-31 21:13:49Z|

```
===============================================================================
[FAIL]: twisted.trial.test.test_loader.LoaderTest.test_sortCases

Traceback (most recent call last):
  File "/home/exarkun/Projects/Twisted/trunk/twisted/trial/test/test_loader.py", line 167, in test_sortCases
    [test._testMethodName for test in suite._tests])
twisted.trial.unittest.FailTest: not equal:
a = ['test_b', 'test_c', 'test_a']
b = ['test_c', 'test_b', 'test_a']

===============================================================================
[FAIL]: twisted.trial.test.test_loader.ZipLoadingTest.test_sortCases

Traceback (most recent call last):
  File "/home/exarkun/Projects/Twisted/trunk/twisted/trial/test/test_loader.py", line 167, in test_sortCases
    [test._testMethodName for test in suite._tests])
twisted.trial.unittest.FailTest: not equal:
a = ['test_b', 'test_c', 'test_a']
b = ['test_c', 'test_b', 'test_a']

===============================================================================
```

<details><summary>Searchable metadata</summary>

```
trac-id__3740 3740
type__defect defect
reporter__exarkun exarkun
priority__normal normal
milestone__Python_2_7 Python-2.7
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__trial trial
keywords__ 
time__1238534029000000 1238534029000000
changetime__1275670553000000 1275670553000000
version__None None
owner__ 
cc__thijs
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_1"></a>|@thijstriemstra commented|
|-|-|

Still an [issue](http://buildbot.twistedmatrix.com/builders/ubuntu64-py2.7-select/builds/71/steps/trial/logs/problems) with the latest alpha 3 of Python 2.7.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_3"></a>|@exarkun set status to `closed`|
|-|-|

This appears to have been fixed in Python trunk.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
