### ISSUE TITLE
Issues with gtk2reactor

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3744]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)| @thijstriemstra reported|
|-|-|
|Trac ID|trac#3744|
|Type|defect|
|Created|2009-04-01 00:46:16Z|

When running the unit tests against the trunk it fails on this test:
```
[ERROR]: twisted.manhole.ui.test.test_gtk2manhole

Traceback (most recent call last):
  File "/Volumes/collab1/Sites/software/twisted/svn/Twisted/trunk/twisted/trial/runner.py", line 555, in loadPackage
    
  File "/Volumes/collab1/Sites/software/twisted/svn/Twisted/trunk/twisted/python/modules.py", line 380, in load
    
  File "/Volumes/collab1/Sites/software/twisted/svn/Twisted/trunk/twisted/python/reflect.py", line 462, in namedAny
    
  File "/Volumes/collab1/Sites/software/twisted/svn/Twisted/trunk/twisted/python/reflect.py", line 398, in _importAndCheckStack
    
  File "/Volumes/collab/Sites/software/twisted/svn/Twisted/branches/ref-split-code-3713/twisted/manhole/ui/test/test_gtk2manhole.py", line 21, in <module>
    if gtk.gtk_version[0] == 1:
exceptions.AttributeError: 'module' object has no attribute 'gtk_version'
-------------------------------------------------------------------------------
```

When starting manhole it throws this error:

```
$ manhole
Traceback (most recent call last):
  File "/Volumes/collab/Sites/software/twisted/svn/Twisted/trunk/bin/manhole", line 21, in <module>
    manhole.run()
  File "/Volumes/collab/Sites/software/twisted/svn/Twisted/trunk/twisted/scripts/manhole.py", line 102, in run
    run(config)
  File "/Volumes/collab/Sites/software/twisted/svn/Twisted/trunk/twisted/scripts/manhole.py", line 138, in run_gtk2
    gtk2reactor.install()
  File "/Volumes/collab/Sites/software/twisted/svn/Twisted/trunk/twisted/internet/gtk2reactor.py", line 279, in install
    reactor = Gtk2Reactor(useGtk)
  File "/Volumes/collab/Sites/software/twisted/svn/Twisted/trunk/twisted/internet/gtk2reactor.py", line 93, in __init__
    self.__pending = gtk.events_pending
AttributeError: 'module' object has no attribute 'events_pending'
```

Here's some info about my gtk:

```python
$ python
Python 2.5.1 (r251:54863, Jan 13 2009, 10:26:13) 
[GCC 4.0.1 (Apple Inc. build 5465)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import gtk
>>> gtk._get_available_versions()
{'2.0': '/Library/Python/2.5/site-packages/gtk-2.0'}
>>> import pygtk
>>> pygtk._get_available_versions()
{'2.0': '/Library/Python/2.5/site-packages/gtk-2.0'}
>>> import gobject
>>> print gobject.pygobject_version
(2, 16, 1)
>>> print gobject.pygtk_version
(2, 16, 1)
```

<details><summary>Searchable metadata</summary>

```
trac-id__3744 3744
type__defect defect
reporter__thijs thijs
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__worksforme worksforme
component__core core
keywords__ 
time__1238546776000000 1238546776000000
changetime__1246351485000000 1246351485000000
version__None None
owner__ 
cc__thijs
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

This is weird.  #pygtk says that `gtk.gtk_version` didn't get removed and suggests that maybe this is an OS X specific issue.  Although they didn't present any hypothesis.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_2"></a>|@glyph set owner to @thijstriemstra|
|-|-|

This obviously bears further investigation.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_3"></a>|@glyph set status to `closed`|
|-|-|

As it happens, I have an OS X / PyGTK install here, and I don't see any of these problems.  Please reopen if further investigation yields anything interesting.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
