### ISSUE TITLE
exception shown as originating from yield rather than an assert 0 when using inlineCallbacks and try/finally

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3778]
|<img alt="dickon's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| dickon reported|
|-|-|
|Trac ID|trac#3778|
|Type|defect|
|Created|2009-04-16 11:37:50Z|

Using inlineCallbacks in twisted 8.2.0 I find exceptions tracebacks are not correct if an exception is raised by a yielded deferred in the middle of a try/finally where the finally clause also uses deferreds. I'll attach a test case.

Attachments:

* [inline_callbacks_and_finally.py](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/53c/53ced1ca67fd40d906d39285fbaf97e4f2548fad/cb7fb4a2a38b7f16c77c8bad050c4fd7ba0e17bd.py) (1046 bytes) - added by dickon on 2009-04-17 10:35:19Z - second version of the test code which imports twisted.trial.unittest.TestCase instead of the Python standard library version
* [twisted-inline.py](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/53c/53ced1ca67fd40d906d39285fbaf97e4f2548fad/ea641809b0f8d2a69f2112d75dfe2a0a17c48639.py) (700 bytes) - added by meejah on 2016-06-11 18:52:33Z - different example of the failure-mode

<details><summary>Searchable metadata</summary>

```
trac-id__3778 3778
type__defect defect
reporter__dickon dickon
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__ 
time__1239881870000000 1239881870000000
changetime__1615753392691284 1615753392691284
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|<img alt="dickon's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_1"></a>|dickon commented|
|-|-|

When I run the attached code under trial, the backtraces involving the FT() functions show "yield F3()" as the location that raised ZeroDivisionError rather than the actual underlying "1/0" which I'd expect to see, and do see in the other four  cases.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)|@glyph set owner to @radix|
|-|-|

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|<img alt="meejah's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_4"></a>|meejah commented|
|-|-|

I think I've seen something similar (in 16.2.0), and it turns out this can be "fixed" by removing the `c['tb'] = None` in `__getstate__` (which gets called by `.cleanFailure`) -- as this is ultimately used by `.throwExceptionIntoGenerator`. Now, I'm not sure if that's really a fix, but .. I don't know what is.

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_5"></a>|@twm commented|
|-|-|

Here's the output of the attached scripts run with trunk:

`twisted-inline.py`:

```
STDLIB

Traceback (most recent call last):
  File "twisted-inline.py", line 17, in method
    yield something_failing()
ZeroDivisionError: division by zero

TWISTED

Traceback (most recent call last):
  File ".../dev/twisted/src/twisted/internet/defer.py", line 1656, in unwindGenerator
    return _cancellableInlineCallbacks(gen)
  File ".../dev/twisted/src/twisted/internet/defer.py", line 1571, in _cancellableInlineCallbacks
    _inlineCallbacks(None, g, status)
  File ".../dev/twisted/src/twisted/internet/defer.py", line 1445, in _inlineCallbacks
    result = current_context.run(g.send, result)
  File "twisted-inline.py", line 12, in something_failing
    yield maybeDeferred(real_bad)
--- <exception caught here> ---
  File "twisted-inline.py", line 17, in method
    yield something_failing()
  File "twisted-inline.py", line 12, in something_failing
    yield maybeDeferred(real_bad)
  File ".../dev/twisted/src/twisted/internet/defer.py", line 167, in maybeDeferred
    result = f(*args, **kw)
  File "twisted-inline.py", line 8, in real_bad
    return 1 / 0
builtins.ZeroDivisionError: division by zero
```

`inline_callbacks_and_finally.py`:

```
PYTHONPATH=. bin/trial inline_callbacks_and_finally
Unhandled error in Deferred:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    
  File ".../tmp/tx/inline_callbacks_and_finally.py", line 47, in <module>
    FT()
  File ".../dev/twisted/src/twisted/internet/defer.py", line 1656, in unwindGenerator
    return _cancellableInlineCallbacks(gen)
  File ".../dev/twisted/src/twisted/internet/defer.py", line 1571, in _cancellableInlineCallbacks
    _inlineCallbacks(None, g, status)
--- <exception caught here> ---
  File ".../dev/twisted/src/twisted/internet/defer.py", line 1445, in _inlineCallbacks
    result = current_context.run(g.send, result)
  File ".../tmp/tx/inline_callbacks_and_finally.py", line 41, in FT
    yield F3()
builtins.ZeroDivisionError: division by zero

inline_callbacks_and_finally
  InlineDefTest
    testCall ...                                                           [OK]
    testDirect ...                                                         [OK]
    testDoubleIndirect ...                                                 [OK]
    testFinallyGenerator ...                                            [ERROR]
    testIndirect ...                                                       [OK]

===============================================================================
[ERROR]
Traceback (most recent call last):
  File ".../tmp/tx/inline_callbacks_and_finally.py", line 17, in nok
    assert 'in F3' in tb, tb
builtins.AssertionError: Traceback (most recent call last):
  File ".../dev/twisted/src/twisted/internet/utils.py", line 205, in runWithWarningsSuppressed
    result = f(*a, **kw)
  File ".../tmp/tx/inline_callbacks_and_finally.py", line 13, in testFinallyGenerator
    return FT().addCallbacks(ok, nok)
  File ".../dev/twisted/src/twisted/internet/defer.py", line 1656, in unwindGenerator
    return _cancellableInlineCallbacks(gen)
  File ".../dev/twisted/src/twisted/internet/defer.py", line 1571, in _cancellableInlineCallbacks
    _inlineCallbacks(None, g, status)
--- <exception caught here> ---
  File ".../dev/twisted/src/twisted/internet/defer.py", line 1445, in _inlineCallbacks
    result = current_context.run(g.send, result)
  File ".../tmp/tx/inline_callbacks_and_finally.py", line 41, in FT
    yield F3()
builtins.ZeroDivisionError: division by zero


inline_callbacks_and_finally.InlineDefTest.testFinallyGenerator
-------------------------------------------------------------------------------
Ran 5 tests in 0.026s

FAILED (errors=1, successes=4)
```
