### ISSUE TITLE
web.client.getPage sometimes throws errors that don't get handed to to right Errback

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3792]
|<img alt="usar's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| usar reported|
|-|-|
|Trac ID|trac#3792|
|Type|defect|
|Created|2009-04-23 13:19:04Z|

Every few thousand requests, probably due to broken servers or broken responses from fine servers, I get one of the following Tracebacks printed on the terminal even though I've registered an Errback with the Deferred returned by web.client.getPage

```
--- 1st ---
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/twisted/python/log.py", line 51, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/lib/python2.5/site-packages/twisted/python/log.py", line 36, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/lib/python2.5/site-packages/twisted/python/context.py", line 59, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.5/site-packages/twisted/python/context.py", line 37, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python2.5/site-packages/twisted/internet/selectreactor.py", line 146, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "/usr/lib/python2.5/site-packages/twisted/internet/tcp.py", line 362, in doRead
    return self.protocol.dataReceived(data)
  File "/usr/lib/python2.5/site-packages/twisted/protocols/basic.py", line 231, in dataReceived
    why = self.lineReceived(line)
  File "/usr/lib/python2.5/site-packages/twisted/web/http.py", line 405, in lineReceived
    status = l[1]
exceptions.IndexError: list index out of range
--- /1st ---
```

```
--- 2nd ---
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/twisted/python/log.py", line 51, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/lib/python2.5/site-packages/twisted/python/log.py", line 36, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/lib/python2.5/site-packages/twisted/python/context.py", line 59, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.5/site-packages/twisted/python/context.py", line 37, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python2.5/site-packages/twisted/internet/selectreactor.py", line 146, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "/usr/lib/python2.5/site-packages/twisted/internet/tcp.py", line 362, in doRead
    return self.protocol.dataReceived(data)
  File "/usr/lib/python2.5/site-packages/twisted/protocols/basic.py", line 239, in dataReceived
    return self.rawDataReceived(data)
  File "/usr/lib/python2.5/site-packages/twisted/web/http.py", line 450, in rawDataReceived
    self.setLineMode(rest)
  File "/usr/lib/python2.5/site-packages/twisted/protocols/basic.py", line 254, in setLineMode
    return self.dataReceived(extra)
  File "/usr/lib/python2.5/site-packages/twisted/protocols/basic.py", line 231, in dataReceived
    why = self.lineReceived(line)
  File "/usr/lib/python2.5/site-packages/twisted/web/http.py", line 414, in lineReceived
    key, val = line.split(':', 1)
exceptions.ValueError: need more than 1 value to unpack
--- /2nd ---
```

```
--- 3rd ---
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/twisted/python/log.py", line 51, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/lib/python2.5/site-packages/twisted/python/log.py", line 36, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/lib/python2.5/site-packages/twisted/python/context.py", line 59, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.5/site-packages/twisted/python/context.py", line 37, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python2.5/site-packages/twisted/internet/selectreactor.py", line 146, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "/usr/lib/python2.5/site-packages/twisted/internet/tcp.py", line 362, in doRead
    return self.protocol.dataReceived(data)
  File "/usr/lib/python2.5/site-packages/twisted/protocols/basic.py", line 231, in dataReceived
    why = self.lineReceived(line)
  File "/usr/lib/python2.5/site-packages/twisted/web/http.py", line 421, in lineReceived
    self.handleEndHeaders()
  File "/usr/lib/python2.5/site-packages/twisted/web/client.py", line 65, in handleEndHeaders
    self.factory.gotHeaders(self.headers)
  File "/usr/lib/python2.5/site-packages/twisted/web/client.py", line 261, in gotHeaders
    k, v = cook.split('=', 1)
exceptions.ValueError: need more than 1 value to unpack
--- /3rd ---
```

The third seems to happen with HTTP Cookie headers not containing proper key=value pairs, not sure with the other ones.

I'm running twisted 8.1.0 (Debian 8.1.0-4 from squeeze) on linux-ppc with Python 2.5.4.

<details><summary>Searchable metadata</summary>

```
trac-id__3792 3792
type__defect defect
reporter__usar usar
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__web web
keywords__httpclient httpclient
time__1240492744000000 1240492744000000
changetime__1240495010000000 1240495010000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|

**Comment by twm** [comment]
Closing as `getPage` was removed in #10295.

**Comment by glyph** [comment]
Thanks for cleaning these up, tom, I cannot wait to live in a world where twisted only contains 3 or 4 HTTP clients
