### ISSUE TITLE
Can not use multiprocessing with trial on windows.

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3804]
|<img alt="ablmf's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| ablmf reported|
|-|-|
|Trac ID|trac#3804|
|Type|defect|
|Created|2009-04-28 03:17:59Z|

Try the code below:

```python
#test_call.py

import time
from multiprocessing import Process, Queue
from twisted.trial import unittest

import wx

FRAME_NUM = 4

def f(q):
    app = wx.PySimpleApp()
    frame = wx.Frame(None, wx.ID_ANY, "Hello World")
    frame.Show(True)
    q.put(frame.Handle)
    app.MainLoop()

def makeFrame():
    q = Queue()
    p = Process(target=f, args=(q,))
    p.start()
    return p, q.get()

class TestInvite(unittest.TestCase):

    def setUp(self):
        self.app = wx.PySimpleApp()
        self.frames = []
        for i in range(FRAME_NUM):
            self.frames.append(makeFrame())

    def testInvite(self):
        return

    def tearDown(self):
        self.vb.UserUnregister()

        for p, f in self.frames:
            p.terminate()
```

Error message
```
[ERROR]: test_call.py

Traceback (most recent call last):
  File "D:\Python26\Lib\site-packages\twisted\trial\runner.py", line 643, in loadByNames
    things.append(self.findByName(name))
  File "D:\Python26\Lib\site-packages\twisted\trial\runner.py", line 453, in findByName
    return reflect.namedAny(name)
  File "D:\Python26\lib\site-packages\twisted\python\reflect.py", line 463, in namedAny
    raise ObjectNotFound('%r does not name an object' % (name,))
twisted.python.reflect.ObjectNotFound: 'test_call.py' does not name an object
```

<details><summary>Searchable metadata</summary>

```
trac-id__3804 3804
type__defect defect
reporter__ablmf ablmf
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__worksforme worksforme
component__trial trial
keywords__ 
time__1240888679000000 1240888679000000
changetime__1241035295000000 1241035295000000
version__None None
owner__ablmf ablmf
cc__exarkun
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

The error message you're seeing doesn't _seem_ to be related to Windows or the use of multiprocessing.  The error message is reporting that it doesn't know how to turn "test_call.py" into a test suite - it can't find the tests you're trying to run.

What command are you running, and where is test_call.py in relation to the working directory you run it in?

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_2"></a>|@glyph set owner to ablmf|
|-|-|

This really looks like a problem with PYTHONPATH or something; please reopen if there is actually a problem with Twisted here.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)|@glyph set status to `closed`|
|-|-|
