### ISSUE TITLE
AttributeError: 'cStringIO.StringO' object has no attribute 'len'

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3808]
|<img alt="jmg's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| jmg reported|
|-|-|
|Trac ID|trac#3808|
|Type|defect|
|Created|2009-04-30 21:59:20Z|

#### How to Reproduce
While doing a POST operation on `/attachment/ticket/3807`, Trac issued an internal error.
```
{'action': u'new',
 'attachment': FieldStorage('attachment', 'http.patch', "--- http.py.orig\tThu Apr 30 14:40:13 2009\n+++ http.py\tThu Apr 30 14:40:32 2009\n@@ -794,6 +794,7 @@\n         if (not self.lastModified) or (self.lastModified < when):\n             self.lastModified = when\n \n+        when = self.lastModified\n         modified_since = self.getHeader('if-modified-since')\n         if modified_since:\n             modified_since = stringToDatetime(modified_since.split(';', 1)[0])\n"),
 'description': u'Patch fixing the problem.',
 'id': u'3807',
 'path': u'3807',
 'type': u'ticket'}
==== System Information ====
|| '''Python''' || `2.5.2 (r252:60911, Jul 31 2008, 17:28:52) `[[br]]`[GCC 4.2.3 (Ubuntu 4.2.3-2ubuntu7)]`[[br]] ||
|| '''Subversion''' || `1.4.6` ||
|| '''SQLite''' || `3.4.2` ||
|| '''pysqlite''' || `2.4.0` ||
==== Python Traceback ====
{{{
Traceback (most recent call last):
  File "/srv/trac/.local/lib/python2.5/site-packages/trac/web/main.py", line 377, in dispatch_request
    dispatcher.dispatch(req)
  File "/srv/trac/.local/lib/python2.5/site-packages/trac/web/main.py", line 237, in dispatch
    resp = chosen_handler.process_request(req)
  File "/srv/trac/.local/lib/python2.5/site-packages/trac/attachment.py", line 383, in process_request
    self._do_save(req, attachment)
  File "/srv/trac/.local/lib/python2.5/site-packages/trac/attachment.py", line 461, in _do_save
    size = upload.file.len
AttributeError: 'cStringIO.StringO' object has no attribute 'len'
```
}}}
Just attempted to include an attachment as part of a new bug.
    

<details><summary>Searchable metadata</summary>

```
trac-id__3808 3808
type__defect defect
reporter__jmg jmg
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__website website
keywords__ 
time__1241128760000000 1241128760000000
changetime__1241181796000000 1241181796000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

Fixing description markup.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun set owner to @exarkun|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_3"></a>|@exarkun set status to `closed`|
|-|-|

I believe this is fixed.  Please re-open if you encounter it again.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
