### ISSUE TITLE
AssertionError: HDF dataset not available. Check your clearsilver installation

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3825]
|<img alt="mgeisler's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| mgeisler reported|
|-|-|
|Trac ID|trac#3825|
|Type|defect|
|Created|2009-05-08 08:26:43Z|

I tried to view my account and got an error. Trac suggested that I filed this bug:

#### How to Reproduce
While doing a GET operation on `/account`, Trac issued an internal error.
#### System Information
| **Python** | 
|------------|-`2.5.2 (r252:60911, Jul 31 2008, 17:28:16) `
`[GCC 4.2.3 (Ubuntu 4.2.3-2ubuntu7)]`
 ||
| **Subversion** | 
|----------------|-`1.4.6` ||
| **SQLite** | 
|------------|-`3.4.2` ||
| **pysqlite** | 
|--------------|-`2.3.2` ||
#### Python Traceback
```
Traceback (most recent call last):
  File "/srv/trac/.local/lib/python2.5/site-packages/trac/web/main.py", line 377, in dispatch_request
    dispatcher.dispatch(req)
  File "/srv/trac/.local/lib/python2.5/site-packages/trac/web/main.py", line 244, in dispatch
    req.display(template, content_type or 'text/html')
  File "/srv/trac/.local/lib/python2.5/site-packages/trac/web/api.py", line 347, in display
    assert self.hdf, 'HDF dataset not available. Check your clearsilver installation'
AssertionError: HDF dataset not available. Check your clearsilver installation
```
    

<details><summary>Searchable metadata</summary>

```
trac-id__3825 3825
type__defect defect
reporter__mgeisler mgeisler
priority__low low
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__worksforme worksforme
component__website website
keywords__ 
time__1241771203000000 1241771203000000
changetime__1241781020000000 1241781020000000
version__None None
owner__oubiwann oubiwann

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)|@therve set owner to @oubiwann|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_2"></a>|@exarkun set status to `closed`|
|-|-|

This is because of some other debugging I'm doing.  It'll go away when I stop doing that.

There's no _will fix later_ resolution status, so I'm just going to pick another status at random.
