### ISSUE TITLE
twisted.test.test_randbytes.ConditionalSecureRandomTestCase fails on Python trunk@HEAD

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3848]
|<img alt="ivank's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| ivank reported|
|-|-|
|Trac ID|trac#3848|
|Type|defect|
|Created|2009-05-20 16:51:47Z|

Python 2.7r72791, PyCrypto 2.0.1:

```
===============================================================================
[ERROR]: twisted.test.test_randbytes.ConditionalSecureRandomTestCase.test_cryptoRandom
 
Traceback (most recent call last):
  File "/home/bear/Twisted/twisted/test/test_randbytes.py", line 107, in test_cryptoRandom
    self._check(self.factory._cryptoRandom)
  File "/home/bear/Twisted/twisted/test/test_randbytes.py", line 34, in _check
    s = source(nbytes)
  File "/home/bear/Twisted/twisted/python/randbytes.py", line 92, in _cryptoRandom
    self.randomPool = self.randpool.RandomPool()
  File "/usr/local/lib/python2.7/site-packages/Crypto/Util/randpool.py", line 86, in __init__
    self._measureTickSize()        # Estimate timer resolution
  File "/usr/local/lib/python2.7/site-packages/Crypto/Util/randpool.py", line 271, in _measureTickSize
    self.stir(h.digest())
  File "/usr/local/lib/python2.7/site-packages/Crypto/Util/randpool.py", line 158, in stir
    h = self._hash.new(self._randpool)
exceptions.TypeError: object supporting the buffer API required
===============================================================================
[ERROR]: twisted.test.test_randbytes.ConditionalSecureRandomTestCase.test_withoutOsAndFileUrandom
 
Traceback (most recent call last):
  File "/home/bear/Twisted/twisted/test/test_randbytes.py", line 131, in test_withoutOsAndFileUrandom
    self._check(self.factory.secureRandom)
  File "/home/bear/Twisted/twisted/test/test_randbytes.py", line 34, in _check
    s = source(nbytes)
  File "/home/bear/Twisted/twisted/python/randbytes.py", line 113, in secureRandom
    return getattr(self, src)(nbytes)
  File "/home/bear/Twisted/twisted/python/randbytes.py", line 92, in _cryptoRandom
    self.randomPool = self.randpool.RandomPool()
  File "/usr/local/lib/python2.7/site-packages/Crypto/Util/randpool.py", line 86, in __init__
    self._measureTickSize()        # Estimate timer resolution
  File "/usr/local/lib/python2.7/site-packages/Crypto/Util/randpool.py", line 271, in _measureTickSize
    self.stir(h.digest())
  File "/usr/local/lib/python2.7/site-packages/Crypto/Util/randpool.py", line 158, in stir
    h = self._hash.new(self._randpool)
exceptions.TypeError: object supporting the buffer API required
```

<details><summary>Searchable metadata</summary>

```
trac-id__3848 3848
type__defect defect
reporter__ivank ivank
priority__normal normal
milestone__Python_2_7 Python-2.7
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__pycrypto pycrypto
time__1242838307000000 1242838307000000
changetime__1262588763000000 1262588763000000
version__None None
owner__ivank ivank

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

Seems like a CPython bug to me.  Filed upstream, <http://bugs.python.org/issue6071>.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)|@glyph set owner to ivank|
|-|-|

**Comment by twisted-trac** [comment]
|<img alt="ivank's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_3"></a>|ivank set status to `closed`|
|-|-|

This was fixed in CPython, trunk r``77252

http://svn.python.org/view?view=rev&revision=77252

http://svn.python.org/view/python/trunk/Misc/NEWS?r1=77254&r2=77253&pathrev=77254
