### ISSUE TITLE
Intermittent test failures in twisted.test.test_process.PosixProcessTestCasePTY

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3872]
|<img alt="ivank's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| ivank reported|
|-|-|
|Trac ID|trac#3872|
|Type|defect|
|Created|2009-06-08 03:11:41Z|

After running PosixProcessTestCasePTY a few hundred times (with an script running `trial twisted.test.test_process.PosixProcessTestCasePTY`), I see this on Ubuntu 9.04 server 64 bit (with its default Python 2.6.2 install):

```
/usr/local/lib/python2.6/dist-packages/twisted/test/test_process.py:10: DeprecationWarning:
The popen2 module is deprecated.  Use the subprocess module.
  import popen2
twisted.test.test_process
  PosixProcessTestCasePTY
    testBadArgs ...                                                        [OK]
    testNormalTermination ...                                           [ERROR]
/usr/local/lib/python2.6/dist-packages/twisted/test/test_process.py:988: PotentialZombieWarning:
 spawnProcess called, but the SIGCHLD handler is not installed. This probably means you have not
 yet called reactor.run, or called reactor.run(installSignalHandler=0). You will probably never
 see this process finish, and it may become a zombie process.
    testOpeningTTY ...                                                  [ERROR]
    test_abnormalTermination ...                                           [OK]
    test_errorInProcessEnded ...                                           [OK]
    test_executionError ...                                                [OK]
    test_signalHUP ...                                                     [OK]
    test_signalINT ...                                                     [OK]
    test_signalKILL ...                                                    [OK]
    test_signalTERM ...                                                    [OK]

===============================================================================
[ERROR]: twisted.test.test_process.PosixProcessTestCasePTY.testNormalTermination

Traceback (most recent call last):
Failure: twisted.internet.defer.TimeoutError: <twisted.test.test_process.PosixProcessTestCasePTY
 testMethod=testNormalTermination> (testNormalTermination) still running at 120.0 secs
===============================================================================
[ERROR]: twisted.test.test_process.PosixProcessTestCasePTY.testOpeningTTY

Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/twisted/internet/_baseprocess.py", line 60, in maybeCallProcessEnded
    proto.processEnded(Failure(reason))
  File "/usr/local/lib/python2.6/dist-packages/twisted/test/test_process.py", line 165, in processEnded
    self.deferred.callback(None)
  File "/usr/local/lib/python2.6/dist-packages/twisted/internet/defer.py", line 241, in callback
    self._startRunCallbacks(result)
  File "/usr/local/lib/python2.6/dist-packages/twisted/internet/defer.py", line 296, in _startRunCallbacks
    raise AlreadyCalledError
twisted.internet.defer.AlreadyCalledError: 
-------------------------------------------------------------------------------
Ran 10 tests in 120.970s

FAILED (errors=2, successes=8)
```

Twisted version: trunk, svn r26968

<details><summary>Searchable metadata</summary>

```
trac-id__3872 3872
type__defect defect
reporter__ivank ivank
priority__lowest lowest
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__ 
time__1244430701000000 1244430701000000
changetime__1331751131000000 1331751131000000
version__None None
owner__ivank ivank
cc__jesstess cc__ivank
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="ivank's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_1"></a>|ivank commented|
|-|-|

I also get the exact same errors and traceback when using the libevent reactor (from launchpad).

I used this script `looper-stop` to run trial:

```
#!/bin/bash -e

# Starts a process in a while 1 loop. Stop restarting if the exit code is non-zero.

# Sample usage:
# looper-stop ls -l
# looper-stop python script.py --some-args

shift 0

while [ 1 ]; do
        echo "[`date`] starting: ${*}"
        ${*}
        echo "Process done."
        sleep 0.25
done
```

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)|@glyph set owner to ivank|
|-|-|

**Comment by twisted-trac** [comment]
|<img alt="ivank's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_3"></a>|ivank commented|
|-|-|

I cannot reproduce this with Twisted r28631, Python 2.7a3, Ubuntu 9.10 server 64 bit. Nor with the operating system's default Python 2.6.4.

I don't know if anything relevant has actually changed in any of Twisted, Python, or Ubuntu.

**Comment by twisted-trac** [comment]
|[<img alt="jesstess's avatar" src="https://avatars.githubusercontent.com/u/188336?s=50" width="50" height="50">](https://github.com/jesstess)<a name="note_4"></a>|@jesstess commented|
|-|-|

I wasn't able to reproduce this after 1000 loops through `twisted.test.test_process.PosixProcessTestCasePTY` on trunk (r33705) with:
 * Python 2.6 or 2.7 on OS X 10.6
 * Python 2.6 or 2.7 on Ubuntu 11.04.

ivank, can you still reproduce this in some environment?

**Comment by twisted-trac** [comment]
|<img alt="ivank's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_5"></a>|ivank set status to `closed`|
|-|-|

I can't reproduce this on Twisted trunk running in CentOS 6.3 or Gentoo.  This is not surprising, because `spawnProcess` was fixed to not emit `PotentialZombieWarning`.  (Could have been something else, though.)
