### ISSUE TITLE
Intermittent test failure in twisted.mail.test.test_mail.MaildirAppendStringTestCase.testAppend

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3877]
|<img alt="ivank's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| ivank reported|
|-|-|
|Trac ID|trac#3877|
|Type|defect|
|Created|2009-06-10 12:21:30Z|

After about 500 runs (new process each time, not `trial -u`), it failed:

```
===============================================================================
[FAIL]: twisted.mail.test.test_mail.MaildirAppendStringTestCase.testAppend

Traceback (most recent call last):
  File "/opt/Python-latest/lib/python2.7/site-packages/twisted/mail/test/test_mail.py", line 371, in _cbTestAppend
    self.assertEquals(len(mbox.getMessage(5).read()), 6)
twisted.trial.unittest.FailTest: not equal:
a = 3
b = 6
```

I also saw a failure with these numbers:

```
===============================================================================
[FAIL]: twisted.mail.test.test_mail.MaildirAppendStringTestCase.testAppend

Traceback (most recent call last):
  File "/opt/Python-latest/lib/python2.7/site-packages/twisted/mail/test/test_mail.py", line 371, in _cbTestAppend
    self.assertEquals(len(mbox.getMessage(5).read()), 6)
twisted.trial.unittest.FailTest: not equal:
a = 9
b = 6
```

select reactor, Twisted trunk r26989, Python 2.7r73314 on Ubuntu 9.04 server 64-bit

<details><summary>Searchable metadata</summary>

```
trac-id__3877 3877
type__defect defect
reporter__ivank ivank
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__mail mail
keywords__ 
time__1244636490000000 1244636490000000
changetime__1244636490000000 1244636490000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
