### ISSUE TITLE
don't need sibling imports

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3887]
|<img alt="benjamin's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| benjamin reported|
|-|-|
|Trac ID|trac#3887|
|Type|enhancement|
|Created|2009-06-19 17:39:10Z|

The sibling imports in twisted.python.log can go.

Attachments:

* [die_sibling_imports_DIE.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/c48/c48c68f82c9e8a3302bb2b222be0a925aebea221/678f36d973b7e3cbe1618f8e1a2bdad7d842e5c7.patch) (521 bytes) - added by benjamin on 2009-06-19 17:39:59Z - 

<details><summary>Searchable metadata</summary>

```
trac-id__3887 3887
type__enhancement enhancement
reporter__benjamin benjamin
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__invalid invalid
component__core core
keywords__ 
time__1245433150000000 1245433150000000
changetime__1245434669000000 1245434669000000
version__None None
owner__benjamin benjamin
cc__exarkun
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

That's cool (assuming it works).  I wonder _why_ you filed this ticket, though?

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_2"></a>|@exarkun set owner to benjamin|
|-|-|

Okay, unfortunately it doesn't work:

```
exarkun@charm:/tmp$ python -c 'import twisted.python.failure'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/exarkun/Projects/Twisted/trunk/twisted/python/failure.py", line 557, in <module>
    import log
  File "/home/exarkun/Projects/Twisted/trunk/twisted/python/log.py", line 633, in <module>
    from twisted.python import threadable, failure
ImportError: cannot import name failure
exarkun@charm:/tmp$ 
```

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_3"></a>|@glyph set status to `closed`|
|-|-|

Closing as invalid, since apparently we _do_ need those sibling imports.  benjamin, if you'd like to clarify what exactly you were actually trying to get done here, please feel free to explain more and reopen.
