### ISSUE TITLE
AttributeError: connector

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3889]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)| @jml reported|
|-|-|
|Trac ID|trac#3889|
|Type|defect|
|Created|2009-06-23 04:18:01Z|

Our error reporting system recently mailed us this error:

```
  AttributeError: connector

    Traceback (most recent call last):
  File "/srv/bazaar.launchpad.net/production/launchpad-rev-8112/utilities/../lib/twisted/python/log.py", line 51, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/srv/bazaar.launchpad.net/production/launchpad-rev-8112/utilities/../lib/twisted/python/log.py", line 36, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/srv/bazaar.launchpad.net/production/launchpad-rev-8112/utilities/../lib/twisted/python/context.py", line 59, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/srv/bazaar.launchpad.net/production/launchpad-rev-8112/utilities/../lib/twisted/python/context.py", line 37, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/srv/bazaar.launchpad.net/production/launchpad-rev-8112/utilities/../lib/twisted/internet/selectreactor.py", line 146, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "/srv/bazaar.launchpad.net/production/launchpad-rev-8112/utilities/../lib/twisted/internet/tcp.py", line 527, in doConnect
    self.failIfNotConnected(error.getConnectError((err, strerror(err))))
  File "/srv/bazaar.launchpad.net/production/launchpad-rev-8112/utilities/../lib/twisted/internet/tcp.py", line 484, in failIfNotConnected
    del self.connector
exceptions.AttributeError: connector
```

It doesn't look like something in our code, and a little googling found another instance of this in buildbot (I think).  Not really sure of the cause of the bug or how to reproduce it -- sorry.

<details><summary>Searchable metadata</summary>

```
trac-id__3889 3889
type__defect defect
reporter__jml jml
priority__low low
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__ 
component__core core
keywords__ 
time__1245730681000000 1245730681000000
changetime__1360627204000000 1360627204000000
version__None None
owner__itamar itamar
cc__mwh cc__thijs cc__cengizkarabacak
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_1"></a>|@therve commented|
|-|-|

What revision on Twisted are you using?

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)<a name="note_2"></a>|@jml commented|
|-|-|

Twisted SVN r23227, with some small mods.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_3"></a>|@glyph set owner to @jml|
|-|-|

Please update if you find more information.  Obviously it's tempting to blame your "small mods", but I doubt they're to the TCP connection logic.

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)<a name="note_4"></a>|@jml commented|
|-|-|

You can find the actual patches somewhere on this very trac instance. :)

Will update when I get more info.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_6"></a>|@thijstriemstra commented|
|-|-|

Close as invalid?

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_7"></a>|@exarkun set status to `closed`|
|-|-|

How about _worksforme_?  Because it does. :)  Of course, please feel free to re-open with reproduction instructions or other new information.

**Comment by twisted-trac** [comment]
|<img alt="cengizkarabacak's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_8"></a>|cengizkarabacak set status to `reopened`|
|-|-|

Hi, it is my first contribute, sorry for mistakes... 
I reproduce this error, it is console output.

2013-01-28 17:31:02,501 ERROR > FeedBackSender: Feedback Request errback [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionRefusedError'>: Connection was refused by other side: 111: Connection refused.
]
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 84, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 69, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/home/cengiz/Dropbox/workspace/myFramework/qt4reactor.py", line 84, in _read
    why = w.doRead()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 383, in doConnect
    self.failIfNotConnected(error.getConnectError((err, strerror(err))))
  File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 342, in failIfNotConnected
    del self.connector
exceptions.AttributeError: connector
^C^C^C^Z
[1]+  Stopped                 python run.py

Then this is my code snippet,

```
    def __errback(self, error):
        myLogger.error("Feedback Request errback %s" % error)
        self.__failureFunc()

    def __makeRequest(self):
        postdata = ""
        for key, value in self.__params.items():
            postdata = postdata + key + "=" + value + "&"
        postdata = urllib.quote(postdata.encode('utf-8'), safe="=&")
        myLogger.info("FeedBack Request:" + self.__url + postdata)
        d = getPage(self.__url,
                    method="POST",
                    postdata=postdata,
                    headers={'Content-Type': 'application/x-www-form-urlencoded'}
                    ).addCallback(self.__callback).addErrback(self.__errback)
```

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_9"></a>|@exarkun set status to `new`|
|-|-|

Thanks for your interest in helping get this issue resolved, cengizkarabacak.  The code snippet you added is a good start, but it's not complete - no one else can run it, so it doesn't help a _lot_ in tracking down the cause of this problem.  See http://sscce.org/ for some tips on constructing a good reproducer.  Thanks again!

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_10"></a>|@exarkun set status to `closed`|
|-|-|

Please feel free to re-open with further details.

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)<a name="note_11"></a>|@itamarst set status to `reopened`|
|-|-|

Here's one case where I believe this could happen, from reading the code:

  1. Connection fails, calling `failIfNotConnected` on the transport.
  2. In the last line of `failIfNotConnected`, the connector's `connectionFailed` method is called, which in turn calls the factory's `clientConnectionFailed` method.
  3. The factory's `clientConnectionFailed` method calls `stopConnecting` on the connector. (This is the first place we hit user code.) This results in `failIfNotConnected` being called reentrantly, eventually deleting the `connector` attribute.
  4. Finally, we return to original `failIfNotConnected` call, and run its last line... which tries to delete a no longer existent attribute.

In general, it looks like the place to look for potential causes for the issue are the factory's `clientConnectionFailed` method.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun set owner to @itamarst<br>@exarkun set status to `new`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_13"></a>|@glyph commented|
|-|-|

Replying to [itamar](#note_11):
> Here's one case where I believe this could happen, from reading the code:
> 
>   1. Connection fails, calling `failIfNotConnected` on the transport.
>   2. In the last line of `failIfNotConnected`, the connector's `connectionFailed` method is called, which in turn calls the factory's `clientConnectionFailed` method.
>   3. The factory's `clientConnectionFailed` method calls `stopConnecting` on the connector. (This is the first place we hit user code.) This results in `failIfNotConnected` being called reentrantly, eventually deleting the `connector` attribute.
>   4. Finally, we return to original `failIfNotConnected` call, and run its last line... which tries to delete a no longer existent attribute.
> 
> In general, it looks like the place to look for potential causes for the issue are the factory's `clientConnectionFailed` method.

Thanks for investigating.  Any chance you could turn this description into a unit test?  I'll happily commit to implementing the fix if someone can figure that out ;).
