### ISSUE TITLE
TypeError: <lambda>() got multiple values for keyword argument 'asc'

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3957]
|<img alt="Gerrat's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| Gerrat reported|
|-|-|
|Trac ID|trac#3957|
|Type|defect|
|Created|2009-08-06 18:13:26Z|

#### How to Reproduce
While doing a GET operation on `/report/10`, Trac issued an internal error.
#### System Information
| **Python** | 
|------------|-`2.5.2 (r252:60911, Jul 22 2009, 15:34:27) `
`[GCC 4.2.4 (Ubuntu 4.2.4-1ubuntu3)]`
 ||
| **Subversion** | 
|----------------|-`1.4.6` ||
| **SQLite** | 
|------------|-`3.4.2` ||
| **pysqlite** | 
|--------------|-`2.3.2` ||
#### Python Traceback
```
Traceback (most recent call last):
  File "/srv/trac/.local/lib/python2.5/site-packages/trac/web/main.py", line 377, in dispatch_request
    dispatcher.dispatch(req)
  File "/srv/trac/.local/lib/python2.5/site-packages/trac/web/main.py", line 248, in dispatch
    content_type)
  File "/srv/trac/.local/lib/python2.5/site-packages/trac/web/chrome.py", line 475, in render_template
    return stream.render(method, doctype=doctype)
  File "/srv/trac/.local/lib/python2.5/site-packages/genshi/core.py", line 146, in render
    output = u''.join(list(generator))
  File "/srv/trac/.local/lib/python2.5/site-packages/genshi/output.py", line 200, in __call__
    for kind, data, pos in stream:
  File "/srv/trac/.local/lib/python2.5/site-packages/genshi/output.py", line 486, in __call__
    for kind, data, pos in chain(stream, [(None, None, None)]):
  File "/srv/trac/.local/lib/python2.5/site-packages/genshi/output.py", line 436, in __call__
    for kind, data, pos in stream:
  File "/srv/trac/.local/lib/python2.5/site-packages/genshi/core.py", line 207, in _ensure
    for event in stream:
  File "/srv/trac/.local/lib/python2.5/site-packages/genshi/core.py", line 207, in _ensure
    for event in stream:
  File "/srv/trac/.local/lib/python2.5/site-packages/trac/web/chrome.py", line 478, in _strip_accesskeys
    for kind, data, pos in stream:
  File "/srv/trac/.local/lib/python2.5/site-packages/genshi/filters.py", line 313, in __call__
    for kind, data, pos in stream:
  File "/srv/trac/.local/lib/python2.5/site-packages/genshi/template.py", line 1145, in _match
    content = list(content)
  File "/srv/trac/.local/lib/python2.5/site-packages/genshi/filters.py", line 331, in __call__
    for event in template.generate(ctxt):
  File "/srv/trac/.local/lib/python2.5/site-packages/genshi/filters.py", line 313, in __call__
    for kind, data, pos in stream:
  File "/srv/trac/.local/lib/python2.5/site-packages/genshi/template.py", line 1120, in _match
    for event in stream:
  File "/srv/trac/.local/lib/python2.5/site-packages/genshi/template.py", line 920, in _eval
    ctxt):
  File "/srv/trac/.local/lib/python2.5/site-packages/genshi/template.py", line 930, in _eval
    result = data.evaluate(ctxt)
  File "/srv/trac/.local/lib/python2.5/site-packages/genshi/eval.py", line 101, in evaluate
    {'data': data})
  File "/home/trac/.local/share/trac/templates/report_view.html", line 39, in <Expression u"href.report(report.id, sort=header.col, asc=not header.asc and "1" or "0", **report.args)">
    <a py:strip="not sorting_enabled"
TypeError: <lambda>() got multiple values for keyword argument 'asc'
```
    

<details><summary>Searchable metadata</summary>

```
trac-id__3957 3957
type__defect defect
reporter__Gerrat Gerrat
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__duplicate duplicate
component__core core
keywords__ 
time__1249582406000000 1249582406000000
changetime__1249584007000000 1249584007000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun set status to `closed`|
|-|-|

Duplicate of [#2508](https://github.com/twisted/twisted/issues/2508).

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
