### ISSUE TITLE
getPage does not accept extra positional arguments

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3962]
|<img alt="truppo's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| truppo reported|
|-|-|
|Trac ID|trac#3962|
|Type|defect|
|Created|2009-08-12 08:42:00Z|

When using getPage and wanting to pass extra arguments to HTTPClientFactory, positional arguments cannot be used even though "*args" is specified in the getPage signature and the docstring suggests it would accept any extra args that HTTPClientFactory accepts.

```
Python 2.6.2 (r262:71605, Apr 14 2009, 22:40:02) [MSC v.1500 32 bit (Intel)] on
win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from twisted.web.client import getPage, HTTPClientFactory
>>> url = "http://www.foo.bar"
>>> data = {"foo":"bar"}
>>> HTTPClientFactory(url, "POST", data)
<HTTPClientFactory: http://www.foo.bar>
>>> getPage(url, None, "POST", data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\python26\lib\site-packages\twisted\web\client.py", line 473, in getPage
    *args, **kwargs).deferred
TypeError: _makeGetterFactory() got multiple values for keyword argument 'contextFactory'
>>> HTTPClientFactory(url, method="POST", postdata=data)
<HTTPClientFactory: http://www.foo.bar>
>>> getPage(url, None, method="POST", postdata=data)
<Deferred at 0x2a2fe40>
>>>
```

<details><summary>Searchable metadata</summary>

```
trac-id__3962 3962
type__defect defect
reporter__truppo truppo
priority__low low
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__web web
keywords__ 
time__1250066520000000 1250066520000000
changetime__1250066520000000 1250066520000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|

**Comment by adiroiban** [comment]
I am closing this as the getPage API was removed in #1683
