### ISSUE TITLE
t.conch.test.test_conch.OpenSSHClientTestCase cannot find ssh binary on Vista

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3966]
|<img alt="ivank's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| ivank reported|
|-|-|
|Trac ID|trac#3966|
|Type|defect|
|Created|2009-08-15 04:48:03Z|

I'm using MSYS's ssh.exe, installed to C:\msys\1.0\bin\ssh.exe. `twisted.python.procutils.which` finds one ssh.exe:

```
>>> from twisted.python.procutils import which
>>> which('ssh')
['C:\\msys\\1.0\\bin\\ssh.EXE']
```

So `OpenSSHClientTestCase` correctly thinks that the client is available (it does not skip).

```
    if not which('ssh'):
        skip = "no ssh command-line client available"
```

But when the tests actually run, they fail:

```
===============================================================================
[ERROR]: twisted.conch.test.test_conch.OpenSSHClientTestCase.test_exec

Traceback (most recent call last):
  File "C:\Python26\lib\site-packages\twisted\conch\test\test_conch.py", line 340, in test_exec
    d = self.execute('echo goodbye', ConchTestOpenSSHProcess())
  File "C:\Python26\lib\site-packages\twisted\conch\test\test_conch.py", line 405, in execute
    reactor.spawnProcess(process, "ssh", cmds)
  File "C:\Python26\lib\site-packages\twisted\internet\posixbase.py", line 234, in spawnProcess
    return Process(self, processProtocol, executable, args, env, path)
  File "C:\Python26\lib\site-packages\twisted\internet\_dumbwin32proc.py", line 203, in __init__
    raise OSError(pwte)
exceptions.OSError: (2, 'CreateProcess', 'The system cannot find the file specified.')
===============================================================================
[ERROR]: twisted.conch.test.test_conch.OpenSSHClientTestCase.test_localToRemoteForwarding

Traceback (most recent call last):
  File "C:\Python26\lib\site-packages\twisted\conch\test\test_conch.py", line 353, in test_localToRemoteForwarding
    % (localPort, self.echoPort))
  File "C:\Python26\lib\site-packages\twisted\conch\test\test_conch.py", line 405, in execute
    reactor.spawnProcess(process, "ssh", cmds)
  File "C:\Python26\lib\site-packages\twisted\internet\posixbase.py", line 234, in spawnProcess
    return Process(self, processProtocol, executable, args, env, path)
  File "C:\Python26\lib\site-packages\twisted\internet\_dumbwin32proc.py", line 203, in __init__
    raise OSError(pwte)
exceptions.OSError: (2, 'CreateProcess', 'The system cannot find the file specified.')
===============================================================================
[ERROR]: twisted.conch.test.test_conch.OpenSSHClientTestCase.test_remoteToLocalForwarding

Traceback (most recent call last):
  File "C:\Python26\lib\site-packages\twisted\conch\test\test_conch.py", line 367, in test_remoteToLocalForwarding
    % (localPort, self.echoPort))
  File "C:\Python26\lib\site-packages\twisted\conch\test\test_conch.py", line 405, in execute
    reactor.spawnProcess(process, "ssh", cmds)
  File "C:\Python26\lib\site-packages\twisted\internet\posixbase.py", line 234, in spawnProcess
    return Process(self, processProtocol, executable, args, env, path)
  File "C:\Python26\lib\site-packages\twisted\internet\_dumbwin32proc.py", line 203, in __init__
    raise OSError(pwte)
exceptions.OSError: (2, 'CreateProcess', 'The system cannot find the file specified.')
-------------------------------------------------------------------------------
Ran 7 tests in 0.082s
```

I think the solution is to `spawnProcess` with the full path of the ssh executable, instead of with "ssh".

Tested with Server 2008 SP1, Python 2.6.2 32 bit, Twisted r27226.

Attachments:

* [OpenSSHClientTestCase_spawn_full_ssh_path.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/5c3/5c36a01dac388a87eeec89d3501710fbdb012c62/cdae421c671f0a543ec23c5eb926602739f713a5.patch) (448 bytes) - added by ivank on 2009-08-15 04:51:33Z - fix

<details><summary>Searchable metadata</summary>

```
trac-id__3966 3966
type__defect defect
reporter__ivank ivank
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__conch conch
keywords__ 
time__1250311683000000 1250311683000000
changetime__1251855044000000 1251855044000000
version__None None
owner__ivank ivank

```
</details>

**Comment by twisted-trac** [comment]
|<img alt="ivank's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_1"></a>|ivank commented|
|-|-|

The attached patch makes the three tests pass on Vista and does not seem to break anything on Linux.

I don't think there's a need to warn if there's multiple "ssh"es in the PATH. It does the same thing as it did before.

**Comment by twisted-trac** [comment]
|<img alt="ivank's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_2"></a>|ivank removed owner|
|-|-|

reassign to no one

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_3"></a>|@exarkun commented|
|-|-|

Why can `which` find ssh but `spawnProcess` can't?

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_4"></a>|@glyph commented|
|-|-|

On UNIX, `spawnProcess` uses `execvpe`; the 'p' in which means 'use the `$PATH` environment variable like a shell would'.  On Windows, we use `CreateProcess`, whose rules are different.  [To quote the relevant MSDN documentation](http://msdn.microsoft.com/en-us/library/ms682425(VS.85).aspx), "lpApplicationName: (...) In the case of a partial name, the function uses the current drive and current directory to complete the specification. **The function will not use the search path.**".  We provide an `lpApplicationName`, which means that no search takes place.

I think this is pretty clearly a bug in our Windows process support, and a better way to fix these tests would be to fix the underlying issue.  I haven't investigated iocpreactor yet.

One possible way around this would be to pass `NULL`, er, I mean, `None`, for `lpApplicationName` and let Windows figure it out from `lpCommandLine`.  The page above says: "If the file name does not contain a directory path, the system searches for the executable file in the following sequence: (...)" and goes on to describe a bunch of directories which are searched, including the Windows directory and everything on `%PATH%`.  I think this change would be fairly backwards-compatible, since any incomplete path names on Windows would currently cause an error.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_5"></a>|@exarkun set owner to ivank|
|-|-|

Okay, so it sounds like we should really make that change to the Windows `IReactorProcess` implementation.
