### ISSUE TITLE
Intermittent twisted.test.test_udp.UDPTestCase.testSendPackets failure with iocpreactor/Vista

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3969]
|<img alt="ivank's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| ivank reported|
|-|-|
|Trac ID|trac#3969|
|Type|defect|
|Created|2009-08-15 12:02:37Z|

```
C:\temp>python C:\Python26\Scripts\trial.py -r iocp -e -u twisted.test.test_udp.UDPTestCase.testSendPackets
Test Pass 1
twisted.test.test_udp
  UDPTestCase
    testSendPackets ...                                                    [OK]

-------------------------------------------------------------------------------
Ran 1 tests in 0.006s

PASSED (successes=1)
Test Pass 2
twisted.test.test_udp
  UDPTestCase
    testSendPackets ...                                                    [OK]

-------------------------------------------------------------------------------
Ran 1 tests in 0.004s

PASSED (successes=1)
Test Pass 3
twisted.test.test_udp
  UDPTestCase
    testSendPackets ...                                                    [OK]

-------------------------------------------------------------------------------
Ran 1 tests in 0.006s

...successes elided...

PASSED (successes=1)
Test Pass 103
twisted.test.test_udp
  UDPTestCase
    testSendPackets ... Traceback (most recent call last):
  File "C:\Python26\lib\site-packages\twisted\test\test_udp.py", line 374, in cbSendsFinished
    ("c", clientAddr)])
twisted.trial.unittest.FailTest: not equal:
a = [('a', ('127.0.0.1', 61336)),
 ('', ('127.0.0.1', 61336)),
 ('c', ('127.0.0.1', 61336))]
b = [('a', ('127.0.0.1', 61336)),
 ('b', ('127.0.0.1', 61336)),
 ('c', ('127.0.0.1', 61336))]

[FAIL]
Traceback (most recent call last):
Failure: twisted.trial.util.DirtyReactorAggregateError: Reactor was unclean.
Selectables:
<twisted.test.test_udp.Server on 61335>
<twisted.test.test_udp.GoodClient on 61336>
[ERROR]

===============================================================================
[FAIL]: twisted.test.test_udp.UDPTestCase.testSendPackets

Traceback (most recent call last):
  File "C:\Python26\lib\site-packages\twisted\test\test_udp.py", line 374, in cbSendsFinished
    ("c", clientAddr)])
twisted.trial.unittest.FailTest: not equal:
a = [('a', ('127.0.0.1', 61336)),
 ('', ('127.0.0.1', 61336)),
 ('c', ('127.0.0.1', 61336))]
b = [('a', ('127.0.0.1', 61336)),
 ('b', ('127.0.0.1', 61336)),
 ('c', ('127.0.0.1', 61336))]

===============================================================================
[ERROR]: twisted.test.test_udp.UDPTestCase.testSendPackets

Traceback (most recent call last):
Failure: twisted.trial.util.DirtyReactorAggregateError: Reactor was unclean.
Selectables:
<twisted.test.test_udp.Server on 61335>
<twisted.test.test_udp.GoodClient on 61336>
-------------------------------------------------------------------------------
Ran 1 tests in 0.019s

FAILED (failures=1, errors=1)

```

The incorrectly-empty string might be different each time (sometimes it's not 'b')

I tested with Server 2008 SP1, Python 2.6.2 32 bit, Twisted r27226 (built with VS2008).

<details><summary>Searchable metadata</summary>

```
trac-id__3969 3969
type__defect defect
reporter__ivank ivank
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__iocp_iocpreactor iocp iocpreactor
time__1250337757000000 1250337757000000
changetime__1269112197000000 1269112197000000
version__None None
owner__ 
cc__ivank
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="ivank's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_1"></a>|ivank commented|
|-|-|

I managed to reproduce this again on:

Twisted trunk r28752

(a 32-bit) Python 2.7a3+ (trunk, Feb  7 2010, 19:32:45) [MSC v.1500 32 bit (Intel)] on win32

Server 2008 R2 (64-bit)

**Comment by twisted-trac** [comment]
|<img alt="ivank's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_2"></a>|ivank commented|
|-|-|

Here's a method that should make this quicker to reproduce:

1. Open a cmd shell

2. Paste something like
```
python C:\Python26\Scripts\trial.py -r iocp -e -u twisted.test.test_udp.UDPTestCase.testSendPackets
```

3. Hit enter, up, enter, up, enter, up, enter, a few dozen times. The keystrokes will be backlogged as it tries to keep up.

4. Move focus away from the cmd window or make another application use CPU time

**Comment by twisted-trac** [comment]
|<img alt="ivank's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_3"></a>|ivank commented|
|-|-|

Or just use `trial -u` and focus away, heh.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
