### ISSUE TITLE
trial -u intermittent error: WindowsError: [Error 145] The directory is not empty: 'C:\\temp\\_trial_temp.lock'

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3971]
|<img alt="ivank's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| ivank reported|
|-|-|
|Trac ID|trac#3971|
|Type|defect|
|Created|2009-08-15 12:56:40Z|

C:\temp>python C:\Python26\Scripts\trial.py -u -e twisted.test.test_udp.UDPTestCase.testSendPackets

```
...successes elided...
-------------------------------------------------------------------------------
Ran 1 tests in 0.004s

PASSED (successes=1)
Test Pass 262
twisted.test.test_udp
  UDPTestCase
    testSendPackets ...                                                    [OK]

-------------------------------------------------------------------------------
Ran 1 tests in 0.005s

PASSED (successes=1)
Test Pass 263
twisted.test.test_udp
  UDPTestCase
    testSendPackets ...                                                    [OK]

-------------------------------------------------------------------------------
Ran 1 tests in 0.006s

PASSED (successes=1)
Test Pass 264
twisted.test.test_udp
  UDPTestCase
    testSendPackets ...                                                    [OK]

-------------------------------------------------------------------------------
Ran 1 tests in 0.006s

PASSED (successes=1)
Test Pass 265
twisted.test.test_udp
  UDPTestCase
    testSendPackets ...                                                    [OK]
Traceback (most recent call last):
  File "C:\Python26\Scripts\trial.py", line 22, in <module>
    run()
  File "C:\Python26\lib\site-packages\twisted\scripts\trial.py", line 359, in run
    test_result = trialRunner.runUntilFailure(suite)
  File "C:\Python26\lib\site-packages\twisted\trial\runner.py", line 893, in runUntilFailure
    result = self._runWithoutDecoration(test)
  File "C:\Python26\lib\site-packages\twisted\trial\runner.py", line 862, in _runWithoutDecoration
    self._tearDownTestdir(oldDir)
  File "C:\Python26\lib\site-packages\twisted\trial\runner.py", line 770, in _tearDownTestdir
    self._testDirLock.unlock()
  File "C:\Python26\lib\site-packages\twisted\python\lockfile.py", line 188, in unlock
    rmlink(self.name)
  File "C:\Python26\lib\site-packages\twisted\python\lockfile.py", line 82, in rmlink
    os.rmdir(filename)
WindowsError: [Error 145] The directory is not empty: 'C:\\temp\\_trial_temp.lock'
```

I did not start another process at this time. This happens on its own. After trial exits due to the exception, `_trial_temp\test.log`, `_trial_temp\test.log`, and a directory `_trial_temp.lock` remain.

It might be necessary to occupy CPU time to reproduce this bug, using something like OCCT or Prime95.

I tested with Server 2008 SP1, Python 2.6.2 32 bit, Twisted r27226 (built with VS2008).

<details><summary>Searchable metadata</summary>

```
trac-id__3971 3971
type__defect defect
reporter__ivank ivank
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__trial trial
keywords__ 
time__1250341000000000 1250341000000000
changetime__1262849564000000 1262849564000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|<img alt="gerald.combs's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_1"></a>|gerald.combs commented|
|-|-|

Do you have indexing enabled for that drive or directory?

**Comment by twisted-trac** [comment]
|<img alt="ivank's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_2"></a>|ivank commented|
|-|-|

The indexing bit for that directory is probably set, but Indexing is not running. I confirmed with Control Panel/System and Maintenance/Indexing Options.

I just reproduced this bug again by running a CPU-hungry program and lowering the priority of the Python process.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
