### ISSUE TITLE
trial on Windows tries forever to acquire a stale lock

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3972]
|<img alt="ivank's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| ivank reported|
|-|-|
|Trac ID|trac#3972|
|Type|defect|
|Created|2009-08-15 13:04:33Z|

After being left with a stale `_trial_temp.lock` (probably for any reason, but I had one due to issue [#3971](https://github.com/twisted/twisted/issues/3971)), running trial again never works, no matter how many times you try.

To get the below tracebacks, I pressing Ctrl-C after "Test Pass 1" was printed on the screen.

```
C:\temp\temp67>dir
 Volume in drive C is SomeDrive
 Volume Serial Number is REMO-VED1

 Directory of C:\temp\temp67

2009-08-15  05:53    <DIR>          .
2009-08-15  05:53    <DIR>          ..
2009-08-15  05:53    <DIR>          _trial_temp
2009-08-15  05:53    <DIR>          _trial_temp.lock
               0 File(s)              0 bytes
               4 Dir(s)  18,364,100,608 bytes free

C:\temp\temp67>python C:\Python26\Scripts\trial.py -u -e twisted.test.test_udp.UDPTestCase.testSendPackets
Test Pass 1
Traceback (most recent call last):
  File "C:\Python26\Scripts\trial.py", line 22, in <module>
    run()
  File "C:\Python26\lib\site-packages\twisted\scripts\trial.py", line 359, in run
    test_result = trialRunner.runUntilFailure(suite)
  File "C:\Python26\lib\site-packages\twisted\trial\runner.py", line 891, in runUntilFailure
    result = self.run(test)
  File "C:\Python26\lib\site-packages\twisted\trial\runner.py", line 833, in run
    return self._runWithoutDecoration(test)
  File "C:\Python26\lib\site-packages\twisted\trial\runner.py", line 856, in _runWithoutDecoration
    oldDir = self._setUpTestdir()
  File "C:\Python26\lib\site-packages\twisted\trial\runner.py", line 749, in _setUpTestdir
    if self._testDirLock.lock():
  File "C:\Python26\lib\site-packages\twisted\python\lockfile.py", line 125, in lock
    symlink(str(os.getpid()), self.name)
  File "C:\Python26\lib\site-packages\twisted\python\lockfile.py", line 57, in symlink
    f = _open(newvalname,'wcb')
KeyboardInterrupt

C:\temp\temp67>python C:\Python26\Scripts\trial.py -u -e twisted.test.test_udp.UDPTestCase.testSendPackets
Test Pass 1
Traceback (most recent call last):
  File "C:\Python26\Scripts\trial.py", line 22, in <module>
    run()
  File "C:\Python26\lib\site-packages\twisted\scripts\trial.py", line 359, in run
    test_result = trialRunner.runUntilFailure(suite)
  File "C:\Python26\lib\site-packages\twisted\trial\runner.py", line 891, in runUntilFailure
    result = self.run(test)
  File "C:\Python26\lib\site-packages\twisted\trial\runner.py", line 833, in run
    return self._runWithoutDecoration(test)
  File "C:\Python26\lib\site-packages\twisted\trial\runner.py", line 856, in _runWithoutDecoration
    oldDir = self._setUpTestdir()
  File "C:\Python26\lib\site-packages\twisted\trial\runner.py", line 749, in _setUpTestdir
    if self._testDirLock.lock():
  File "C:\Python26\lib\site-packages\twisted\python\lockfile.py", line 125, in lock
    symlink(str(os.getpid()), self.name)
  File "C:\Python26\lib\site-packages\twisted\python\lockfile.py", line 62, in symlink
    rename(newlinkname, filename)
KeyboardInterrupt
```

<details><summary>Searchable metadata</summary>

```
trac-id__3972 3972
type__defect defect
reporter__ivank ivank
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__trial trial
keywords__ 
time__1250341473000000 1250341473000000
changetime__1250341473000000 1250341473000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
