### ISSUE TITLE
OperationalError: database is locked

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3979]
|<img alt="lorph's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| lorph reported|
|-|-|
|Trac ID|trac#3979|
|Type|defect|
|Created|2009-08-23 02:41:18Z|

#### How to Reproduce
While doing a GET operation on `/login`, Trac issued an internal error.
#### System Information
| **Python** | 
|------------|-`2.5.2 (r252:60911, Jul 22 2009, 15:34:27) `
`[GCC 4.2.4 (Ubuntu 4.2.4-1ubuntu3)]`
 ||
| **Subversion** | 
|----------------|-`1.4.6` ||
| **SQLite** | 
|------------|-`3.4.2` ||
| **pysqlite** | 
|--------------|-`2.3.2` ||
#### Python Traceback
```
Traceback (most recent call last):
  File "/srv/trac/.local/lib/python2.5/site-packages/trac/web/main.py", line 377, in dispatch_request
    dispatcher.dispatch(req)
  File "/srv/trac/.local/lib/python2.5/site-packages/trac/web/main.py", line 237, in dispatch
    resp = chosen_handler.process_request(req)
  File "/srv/trac/.local/lib/python2.5/site-packages/trac/web/auth.py", line 100, in process_request
    self._do_login(req)
  File "/srv/trac/.local/lib/python2.5/site-packages/trac/web/auth.py", line 136, in _do_login
    db.commit()
OperationalError: database is locked
```
    

<details><summary>Searchable metadata</summary>

```
trac-id__3979 3979
type__defect defect
reporter__lorph lorph
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__wontfix wontfix
component__core core
keywords__ 
time__1250995278000000 1250995278000000
changetime__1251036197000000 1251036197000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun set status to `closed`|
|-|-|

There's nothing we can really do about this aside from either fixing trac or switching away from trac.  Neither is likely to happen soon, I think.  However, if you'd like to help out with fixing this, please re-open this ticket and we can discuss it.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
