### ISSUE TITLE
AttributeError: 'module' object has no attribute '_RLock'

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#4002]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)| @thijstriemstra reported|
|-|-|
|Trac ID|trac#4002|
|Type|defect|
|Created|2009-09-06 03:37:13Z|

The Jython buildslave currently throws the following [error](http://buildbot.twistedmatrix.com/builders/ubuntu64-jython2.5-select/builds/251/steps/trial/logs/stdio) with Jython 2.5.1 trunk:

```python
Traceback (most recent call last):
  File "./bin/trial", line 21, in <module>
    from twisted.scripts.trial import run
  File "/home/buildbot/Buildslaves/twisted/jython2.5-thijs-ubuntu/Twisted/twisted/scripts/trial.py", line 9, in <module>
    from twisted.internet import defer
  File "/home/buildbot/Buildslaves/twisted/jython2.5-thijs-ubuntu/Twisted/twisted/internet/defer.py", line 15, in <module>
    from twisted.python import log, failure, lockfile
  File "/home/buildbot/Buildslaves/twisted/jython2.5-thijs-ubuntu/Twisted/twisted/python/log.py", line 19, in <module>
    from twisted.python import util, context, reflect
  File "/home/buildbot/Buildslaves/twisted/jython2.5-thijs-ubuntu/Twisted/twisted/python/context.py", line 22, in <module>
    from twisted.python import threadable
  File "/home/buildbot/Buildslaves/twisted/jython2.5-thijs-ubuntu/Twisted/twisted/python/threadable.py", line 117, in <module>
    init(True)
  File "/home/buildbot/Buildslaves/twisted/jython2.5-thijs-ubuntu/Twisted/twisted/python/threadable.py", line 68, in init
    class XLock(threadingmodule._RLock, object):
AttributeError: 'module' object has no attribute '_RLock'
```

<details><summary>Searchable metadata</summary>

```
trac-id__4002 4002
type__defect defect
reporter__thijs thijs
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__invalid invalid
component__core core
keywords__jython jython
time__1252208233000000 1252208233000000
changetime__1252359307000000 1252359307000000
version__None None
owner__ 
cc__pjenvey cc__thijs
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_1"></a>|@therve commented|
|-|-|

All this code exists to support non-threaded systems. I suspect some other stuff would break there, so I would remove all of that. Thoughts?

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_2"></a>|@thijstriemstra set status to `closed`|
|-|-|

Looks like it's a Jython bug: http://bugs.jython.org/issue1079

Closing as invalid.

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_3"></a>|@thijstriemstra commented|
|-|-|

And it's back to [#3718](https://github.com/twisted/twisted/issues/3718) with latest jython trunk:
http://buildbot.twistedmatrix.com/builders/ubuntu64-jython2.5-select/builds/254/steps/trial/logs/stdio

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
