### ISSUE TITLE
Threading error occurs with adbapi and SQLite

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#4040]
|<img alt="mjcaley's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| mjcaley reported|
|-|-|
|Trac ID|trac#4040|
|Type|defect|
|Created|2009-09-25 00:56:58Z|

An error occurs from sqlite3 when the reactor is stopped indicating that SQLite objects can only be used in the same thread.  Setting the check_same_thread parameter to False in the database connection does suppress this error.  Data is returned correctly until up until the reactor is stopped.

I was using revision 26354.

Output:

[(u'admin@example.net', u'localhost', u'sha256:4672db5a9ff30d9b2d5c97bb9b1d1ea4bdf1262e6a5110b7f43defc4a6ea04db', 1, 1, 0, None, None, None, u'Administrator', None, None, None, u'Example Inc.', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None), (u'aanderson@example.net', u'localhost', u'sha256:500c7694095af2f2e5b38b4d54b1b013e030c2ddb45510099d015bfcb5c35849', 1, 1, 0, u'Alice', None, u'Anderson', u'Alice Anderson', u'AA', u'CEO', u'Executive', u'Example Inc.', None, None, u'123 Here Ave.', u'Apt. 123', u'Appletown', u'A0A 0A0', u'Canada', None, None, None, None, None, None, u'(111) 111-1111', u'(222) 222-2222 x2222', None, None, None, None, None, None, None)]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/Twisted-8.2.0_r27354-py2.6-macosx-10.3-i386.egg/twisted/internet/defer.py", line 181, in addCallbacks
    self._runCallbacks()
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/Twisted-8.2.0_r27354-py2.6-macosx-10.3-i386.egg/twisted/internet/defer.py", line 323, in _runCallbacks
    self.result = callback(self.result, *args, **kw)
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/Twisted-8.2.0_r27354-py2.6-macosx-10.3-i386.egg/twisted/internet/base.py", line 410, in _continueFiring
    callable(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/Twisted-8.2.0_r27354-py2.6-macosx-10.3-i386.egg/twisted/enterprise/adbapi.py", line 374, in finalClose
    self._close(conn)
--- <exception caught here> ---
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/Twisted-8.2.0_r27354-py2.6-macosx-10.3-i386.egg/twisted/enterprise/adbapi.py", line 420, in _close
    conn.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id -1341648896 and this is thread id -1610029280

Attachments:

* [dirserv.py](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/80c/80cc3ab97a5b0977b051895f76c0ef8a13a3c40e/ce7593feea583b432963079757828fcabe5f0f9e.py) (411 bytes) - added by mjcaley on 2009-09-25 01:02:36Z - Source

<details><summary>Searchable metadata</summary>

```
trac-id__4040 4040
type__defect defect
reporter__mjcaley mjcaley
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__duplicate duplicate
component__core core
keywords__ 
time__1253840218000000 1253840218000000
changetime__1253843757000000 1253843757000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun set status to `closed`|
|-|-|

Duplicate of [#3629](https://github.com/twisted/twisted/issues/3629).

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
