### ISSUE TITLE
Replace 'callable(foo)' with 'hasattr(foo, "__call__")'

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#4065]
|<img alt="cvaliente's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| cvaliente reported|
|-|-|
|Trac ID|trac#4065|
|Type|enhancement|
|Created|2009-10-28 21:09:02Z|

This patch eliminates the `DeprecationWarning`s thrown when running the test suite with "`python2.6 -3`"

Attachments:

* [callable-not-supported.diff](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/a09/a095bdda62efcc85c40ac0da068651be98671ef8/6808639a1413fc34298ca967d41ad022a28f338f.diff) (9326 bytes) - added by cvaliente on 2009-10-30 08:37:38Z - 
* [callable-in-twisted-compat.diff](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/a09/a095bdda62efcc85c40ac0da068651be98671ef8/389962e5d4320cc3edc7628e05268583277bdad6.diff) (7444 bytes) - added by cvaliente on 2009-11-17 20:18:01Z - 

<details><summary>Searchable metadata</summary>

```
trac-id__4065 4065
type__enhancement enhancement
reporter__cvaliente cvaliente
priority__normal normal
milestone__Python_3_x Python-3.x
branch__ 
branch_author__ 
status__closed closed
resolution__invalid invalid
component__core core
keywords__ 
time__1256764142000000 1256764142000000
changetime__1291134563000000 1291134563000000
version__None None
owner__ 
cc__antoine cc__exarkun cc__thijs
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="pitrou's avatar" src="https://avatars.githubusercontent.com/u/1721820?s=50" width="50" height="50">](https://github.com/pitrou)<a name="note_2"></a>|@pitrou commented|
|-|-|

Please note there are corner cases where the two are not equivalent, but hopefully they don't really matter in the real world:

```
>>> class P(property):
...   def __get__(self, obj, cls):
...     1/0
... 
>>> class C(object):
...   __call__ = P()
... 
>>> c = C()
>>> callable(c)
True
>>> hasattr(c, "__call__")
False
>>> c.__call__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 3, in __get__
ZeroDivisionError: integer division or modulo by zero
```

The reason is that hasattr() really calls getattr() and then discards the result / catches any exception, while callable() only examines the type's structure (callable() is lower level).

**Comment by twisted-trac** [comment]
|<img alt="cvaliente's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_3"></a>|cvaliente commented|
|-|-|

Replying to [antoine](#note_2):

> The reason is that hasattr() really calls getattr() and then discards the result / catches any exception, while callable() only examines the type's structure (callable() is lower level).

I see. What about defining `callable` in `twisted.python.compat3` like this:

```
$ python3
Python 3.1.1 (r311:74480, Oct 29 2009, 08:31:28) 
[GCC 4.2.1] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> def callable(obj):
...    try:
...        return getattr(obj, "__call__", None) is not None
...    except:
...        return True
...
>>> class P(property):
...     def __get__(self, obj, cls):
...         1/0
... 
>>> class C(object):
...     __call__ = P()
... 
>>> c = C()
>>> callable(c)
True
```

**Comment by twisted-trac** [comment]
|[<img alt="pitrou's avatar" src="https://avatars.githubusercontent.com/u/1721820?s=50" width="50" height="50">](https://github.com/pitrou)<a name="note_4"></a>|@pitrou commented|
|-|-|

It's still not ideal:

```
>>> class C: pass
... 
>>> c = C()
>>> c.__call__ = lambda: print("__call__!")
>>> getattr(c, "__call__", None)
<function <lambda> at 0x7fb4e58b5b78>
>>> c()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'C' object is not callable
```

**Comment by twisted-trac** [comment]
|[<img alt="pitrou's avatar" src="https://avatars.githubusercontent.com/u/1721820?s=50" width="50" height="50">](https://github.com/pitrou)<a name="note_5"></a>|@pitrou commented|
|-|-|

Ok, so Benjamin Peterson answered me the following on IRC, about the ideal replacement:

```isinstance(x, collections.Callable), but I think hasattr(x, "__call__") is fine```

**Comment by twisted-trac** [comment]
|<img alt="cvaliente's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_6"></a>|cvaliente commented|
|-|-|

Replying to [antoine](#note_5):
> Ok, so Benjamin Peterson answered me the following on IRC, about the ideal replacement:
>
> ```isinstance(x, collections.Callable), but I think hasattr(x, "__call__") is fine```

Since that option seems to be better, shall I implement `callable()` in `twisted.python.compat3`, together with some test cases like the samples you provided here, Antoine?

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_7"></a>|@glyph commented|
|-|-|

Shouldn't this just be in twisted.python.compat?  Why a new `compat3` module?

**Comment by twisted-trac** [comment]
|<img alt="cvaliente's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_8"></a>|cvaliente commented|
|-|-|

Replying to [glyph](#note_7):
> Shouldn't this just be in twisted.python.compat?  Why a new `compat3` module?

According to the description of [#2484](https://github.com/twisted/twisted/issues/2484), compatibility code for Python 3.x should go in `twisted.python.compat3`. Does that still hold, or should I just keep it simple and do this in `twisted.python.compat`:

```
try:
    callable = callable
except NameError:
    def callable(obj):
        # ...
```

**Comment by twisted-trac** [comment]
|[<img alt="pitrou's avatar" src="https://avatars.githubusercontent.com/u/1721820?s=50" width="50" height="50">](https://github.com/pitrou)<a name="note_9"></a>|@pitrou commented|
|-|-|

Please note that, looking at the kind of purposes `callable()` is used for here, `hasattr(XXX, "__call__")` is probably good enough a replacement (and faster than the correct approach). But the final decision is not my call :-)

By the way, there's a typo in your patch in test_assertions: `"__call_"` instead of `"__call__"`.

**Comment by twisted-trac** [comment]
|<img alt="cvaliente's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_10"></a>|cvaliente commented|
|-|-|

> By the way, there's a typo in your patch in test_assertions: `"__call_"` instead of `"__call__"`.

Oops, just fixed that . Thanks, Antoine!

**Comment by twisted-trac** [comment]
|<img alt="cvaliente's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|cvaliente removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_12"></a>|@exarkun set owner to cvaliente|
|-|-|

`hasattr` is a Python mis-function:

```
   >>> class X:
   ...     def __getattr__(self, name):
   ...             1 / 0
   ... 
   >>> hasattr(X(), 'foo')
   False
   >>> getattr(X(), 'foo', None)
   Traceback (most recent call last):
     File "<stdin>", line 1, in <module>
     File "<stdin>", line 3, in __getattr__
   ZeroDivisionError: integer division or modulo by zero
   >>> 
```

I think the `twisted.python.compat` idea makes the most sense.

**Comment by twisted-trac** [comment]
|<img alt="cvaliente's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_13"></a>|cvaliente removed owner|
|-|-|

Replying to [exarkun](#note_12):
> I think the `twisted.python.compat` idea makes the most sense.

Patch [[callable-in-twisted-compat.diff]](None/callable-in-twisted-compat.diff]) implements `callable` in `twisted.python.compat`, as suggested.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_14"></a>|@exarkun commented|
|-|-|

Thanks for the updated patch cvaliente.

The terrible implementation of `callable` in this patch motivated me to complain on #python-dev.  Someone there pointed out http://bugs.python.org/issue7006 which makes it anything _but_ clear what `callable` is actually supposed to be replaced with.  I think that waiting for that issue to be resolved before changing anything in Twisted makes sense.

**Comment by twisted-trac** [comment]
|[<img alt="jyknight's avatar" src="https://avatars.githubusercontent.com/u/873903?s=50" width="50" height="50">](https://github.com/jyknight)<a name="note_15"></a>|@jyknight commented|
|-|-|

Many (most? I didn't count.) uses of callable in twisted seem to be in "assert" expressions. These seem superfluous and should probably just be removed. Even if something is callable, it might still fail to be called, and that error must be handled properly, in any case.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_16"></a>|@exarkun commented|
|-|-|

True.  Some of the places do it so that the error happens early, near the code which is bogusly passing a non-callable in, though.  I think these make it easier for people doing something dumb to recognize their mistake, maybe.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_19"></a>|@exarkun commented|
|-|-|

Additional news, http://bugs.python.org/issue7624 (`isinstance(foo, collections.Callable)` is presently broken for classic classes).

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_20"></a>|@thijstriemstra commented|
|-|-|

Replying to [exarkun](#note_19):
> Additional news, http://bugs.python.org/issue7624 (`isinstance(foo, collections.Callable)` is presently broken for classic classes).
>

Which is fixed now in Python trunk.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_21"></a>|@exarkun set status to `closed`|
|-|-|

Python 3.2 is re-introducing the `callable` builtin: http://bugs.python.org/issue10518

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
