### ISSUE TITLE
Windows 7: A non-blocking socket operation could not be completed immediately

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#4119]
|<img alt="tom's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| tom reported|
|-|-|
|Trac ID|trac#4119|
|Type|defect|
|Created|2009-11-18 21:06:28Z|

Windows 7: A non-blocking socket operation could not be completed immediately

I'm on Windows 7 64, Python 2.6.4, Twisted 8.2.0
```
from twisted.internet import reactor, protocol
class Echo(protocol.Protocol):
   def dataReceived(self, data):
      self.transport.write(data)
factory = protocol.ServerFactory()
factory.protocol = Echo
reactor.listenTCP(8000, factory)
reactor.run()
```

It crashes at once with the following message:
```
Traceback (most recent call last):
  File "C:\Users\tom\Documents\server.py", line 5, in <module>
    reactor.listenTCP(8000, Echo())
  File "C:\Program Files (x86)\Python\lib\site-packages\twisted\internet\posixbase.py", line 356, in listenTCP
    p.startListening()
  File "C:\Program Files (x86)\Python\lib\site-packages\twisted\internet\tcp.py", line 862, in startListening
    self._realPortNumber = skt.getsockname()[1]
  File "<string>", line 1, in getsockname
socket.error: [Errno 10035] A non-blocking socket operation could not be completed immediately
```

tried this patch, but nothing changes:
```
from twisted.python.util import untilConcludes
self._realPortNumber = untilConcludes(lambda: skt.getsockname()[1])
```

<details><summary>Searchable metadata</summary>

```
trac-id__4119 4119
type__defect defect
reporter__tom tom
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__windows windows
time__1258578388000000 1258578388000000
changetime__1306093396000000 1306093396000000
version__None None
owner__PenguinOfDoom PenguinOfDoom

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun set owner to PenguinOfDoom|
|-|-|

(adjusting some metadata: I doubt this is a Python 2.6-specific issue, so the Python 2.6 milestone isn't suitable; also we don't really use priorities at all, but if we did, _high_ would probably be reserved for bugs on supported platforms or regressions.)

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_2"></a>|@exarkun commented|
|-|-|

Fixing the reproduction instructions (incomplete though they may be) in the description.
