### ISSUE TITLE
trial report unittest module in tracebacks

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#4127]
|<img alt="marco.giusti@...'s avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| marco.giusti@... reported|
|-|-|
|Trac ID|trac#4127|
|Type|enhancement|
|Created|2009-11-22 17:14:05Z|

Standard python unittest hides unhelpful tracebacks using 'levels':

```
...
__unittest = 1
...

class TestResult:

    ...

    def _exc_info_to_string(self, err, test):
        """Converts a sys.exc_info()-style tuple of values into a string."""
        exctype, value, tb = err
        # Skip test runner traceback levels
        while tb and self._is_relevant_tb_level(tb):
            tb = tb.tb_next
        if exctype is test.failureException:
            # Skip assert*() traceback levels
            length = self._count_relevant_tb_levels(tb)
            return ''.join(traceback.format_exception(exctype, value, tb, length))
        return ''.join(traceback.format_exception(exctype, value, tb))

    def _is_relevant_tb_level(self, tb):
        return '__unittest' in tb.tb_frame.f_globals
...
```

implementing somewhat similar makes tracebacks more clear and easies output parsing.

here the outputs using trial and unittest:

## trial

```
test
  TestCase
    testThatFails ...                                                    [FAIL]

===============================================================================
[FAIL]: test.TestCase.testThatFails

Traceback (most recent call last):
  File "/usr/lib/python2.5/unittest.py", line 260, in run
    testMethod()
  File "/home/nohero/test.py", line 6, in testThatFails
    self.assert_(False)
exceptions.AssertionError: 
-------------------------------------------------------------------------------
Ran 1 tests in 0.057s

FAILED (failures=1)
```

## unittest
```
F
======================================================================
FAIL: testThatFails (__main__.TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 6, in testThatFails
    self.assert_(False)
AssertionError

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
```

<details><summary>Searchable metadata</summary>

```
trac-id__4127 4127
type__enhancement enhancement
reporter__marco_giusti____ marco.giusti@...
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__trial trial
keywords__ 
time__1258910045000000 1258910045000000
changetime__1366515001000000 1366515001000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="Julian's avatar" src="https://avatars.githubusercontent.com/u/329822?s=50" width="50" height="50">](https://github.com/Julian)<a name="note_3"></a>|@Julian commented|
|-|-|

There isn't a terribly reasonable way to do this until http://bugs.python.org/issue1705520 lands, but what other test runners do is the hacky thing mentioned on that ticket.
