### ISSUE TITLE
exception in exception handling of unknown ssh channel

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#4132]
|<img alt="yvesf's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| yvesf reported|
|-|-|
|Trac ID|trac#4132|
|Type|defect|
|Created|2009-11-24 14:49:51Z|

```
2009-11-21 20:42:28+0100 [SSHService ssh-connection on SSHServerTransport,1,91.XXX231] Unhandled Error
        Traceback (most recent call last):
        Failure: twisted.conch.error.ConchError: (3, 'unknown channel')
 
2009-11-21 20:42:28+0100 [SSHService ssh-connection on SSHServerTransport,1,XXX231] Unhandled Error
        Traceback (most recent call last):
          File "/usr/lib/python2.5/site-packages/twisted/internet/selectreactor.py", line 146, in _doReadOrWrite
            why = getattr(selectable, method)()
          File "/usr/lib/python2.5/site-packages/twisted/internet/tcp.py", line 362, in doRead
            return self.protocol.dataReceived(data)
          File "/usr/lib/python2.5/site-packages/twisted/conch/ssh/transport.py", line 314, in dataReceived
            self.dispatchMessage(messageNum, packet[1:])
          File "/usr/lib/python2.5/site-packages/twisted/conch/ssh/transport.py", line 336, in dispatchMessage
            messageNum, payload)
        --- <exception caught here> ---
          File "/usr/lib/python2.5/site-packages/twisted/python/log.py", line 51, in callWithLogger
            return callWithContext({"system": lp}, func, *args, **kw)
          File "/usr/lib/python2.5/site-packages/twisted/python/log.py", line 36, in callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File "/usr/lib/python2.5/site-packages/twisted/python/context.py", line 59, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/usr/lib/python2.5/site-packages/twisted/python/context.py", line 37, in callWithContext
            return func(*args,**kw)
          File "/usr/lib/python2.5/site-packages/twisted/conch/ssh/service.py", line 44, in packetReceived
            return f(packet)
          File "/usr/lib/python2.5/site-packages/twisted/conch/ssh/connection.py", line 140, in ssh_CHANNEL_OPEN
            common.NS(textualInfo) + common.NS(''))
          File "/usr/lib/python2.5/struct.py", line 63, in pack
            return o.pack(*args)
        exceptions.TypeError: unsupported operand type(s) for &: 'str' and 'long'
```
 
##################

```
#see line 134 - i am not sure, maybe thats the other way round
http://twistedmatrix.com/trac/browser/trunk/twisted/conch/ssh/connection.py#L139:
130	        except Exception, e:
131	            log.msg('channel open failed')
132	            log.err(e)
133	            if isinstance(e, error.ConchError):
134	                textualInfo, reason = e.args
135	            else:
136	                reason = OPEN_CONNECT_FAILED
137	                textualInfo = "unknown failure"
138	            self.transport.sendPacket(MSG_CHANNEL_OPEN_FAILURE,
139	                                struct.pack('>2L', senderChannel, reason) +
140	                               common.NS(textualInfo) + common.NS('')) 
```
after changing line 134 the traceback looks more friendly like this:
```
2009-11-24 15:42:28+0100 [SSHService ssh-connection on SSHServerTransport,0,127.0.0.1] got channel direct-tcpip request
2009-11-24 15:42:28+0100 [SSHService ssh-connection on SSHServerTransport,0,127.0.0.1] channel open failed
2009-11-24 15:42:28+0100 [SSHService ssh-connection on SSHServerTransport,0,127.0.0.1] Unhandled Error
        Traceback (most recent call last):
        Failure: twisted.conch.error.ConchError: (3, 'unknown channel')
```

I suggest someone who have better undestanding of twisted internals should review this change.

<details><summary>Searchable metadata</summary>

```
trac-id__4132 4132
type__defect defect
reporter__yvesf yvesf
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__conch conch
keywords__ 
time__1259074191000000 1259074191000000
changetime__1554274600567174 1554274600567174
version__None None
owner__ 
cc__exarkun
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun set owner to yvesf|
|-|-|

Can you attach instructions to reproduce this problem?

**Comment by twisted-trac** [comment]
|<img alt="yvesf's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_2"></a>|yvesf commented|
|-|-|

Run a twisted conch ssh server without support for direct-tcpip (Kippo in this case)

Then request a direct-tcpip channel via "ssh -L PORT:host:OTHER_PORT ..."
Use the requested port with something to actually request it. the server will report to log and answer that he is unable to serve direct-tcpip to your ssh-client  but fail by packing the answer.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_3"></a>|@exarkun set owner to z3p|
|-|-|

Thanks!

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="wiml's avatar" src="https://avatars.githubusercontent.com/u/156891?s=50" width="50" height="50">](https://github.com/wiml)<a name="note_5"></a>|@wiml commented|
|-|-|

I think this problem was fixed by commit 29255 (git hash ce5ca7b2f1f) which also references trac bugs [#3071](https://github.com/twisted/twisted/issues/3071) [#3657](https://github.com/twisted/twisted/issues/3657) [#4490](https://github.com/twisted/twisted/issues/4490)
