### ISSUE TITLE
twisted.trial.runner.TrialRunner._removeSafely is missing a module qualification

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#4135]
|<img alt="arkanes's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| arkanes reported|
|-|-|
|Trac ID|trac#4135|
|Type|defect|
|Created|2009-11-25 18:29:55Z|

===============================================================================
[ERROR]: twisted.trial.test.test_runner.TestUntilFailure.test_runUntilFailureDecorate

Traceback (most recent call last):
  File "C:\Twisted-9.0.0\twisted\trial\test\test_runner.py", line 556, in test_runUntilFailureDecorate
    result = self.runner.runUntilFailure(self.test)
  File "C:\Twisted-9.0.0\twisted\trial\runner.py", line 896, in runUntilFailure
    result = self._runWithoutDecoration(test)
  File "C:\Twisted-9.0.0\twisted\trial\runner.py", line 859, in _runWithoutDecoration
    oldDir = self._setUpTestdir()
  File "C:\Twisted-9.0.0\twisted\trial\runner.py", line 753, in _setUpTestdir
    self._removeSafely(testdir)
  File "C:\Twisted-9.0.0\twisted\trial\runner.py", line 728, in _removeSafely
    newPath = FilePath('_trial_temp_old%s'
exceptions.NameError: global name 'FilePath' is not defined
-------------------------------------------------------------------------------

<details><summary>Searchable metadata</summary>

```
trac-id__4135 4135
type__defect defect
reporter__arkanes arkanes
priority__normal normal
milestone__totally_automated_release_infrastructure totally automated release infrastructure
branch__ 
branch_author__ 
status__closed closed
resolution__duplicate duplicate
component__runner runner
keywords__ 
time__1259173795000000 1259173795000000
changetime__1267485899000000 1267485899000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun set status to `closed`|
|-|-|

Duplicate of [#4020](https://github.com/twisted/twisted/issues/4020)

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
