### ISSUE TITLE
sasl fails when using unicode jids

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#4161]
|<img alt="sciasbat's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| sciasbat reported|
|-|-|
|Trac ID|trac#4161|
|Type|defect|
|Created|2009-12-08 17:48:32Z|

here is a full stack trace:
```
	Traceback (most recent call last):
	  File "/home/packages/python/2.5/python2.5-2.5.2/Modules/pyexpat.c", line 656, in EndElement
	    
	  File "/usr/lib/python2.5/site-packages/twisted/words/xish/domish.py", line 780, in _onEndElement
	    self.ElementEvent(self.currElem)
	  File "/usr/lib/python2.5/site-packages/twisted/words/xish/xmlstream.py", line 106, in onElement
	    self.dispatch(element)
	  File "/usr/lib/python2.5/site-packages/twisted/words/xish/utility.py", line 316, in dispatch
	    callbacklist.callback(obj)
	--- <exception caught here> ---
	  File "/usr/lib/python2.5/site-packages/twisted/words/xish/utility.py", line 106, in callback
	    methodwrapper(*args, **kwargs)
	  File "/usr/lib/python2.5/site-packages/twisted/words/xish/utility.py", line 27, in __call__
	    self.method(*nargs, **nkwargs)
	  File "/usr/lib/python2.5/site-packages/twisted/words/protocols/jabber/sasl.py", line 193, in onChallenge
	    self.sendResponse(self.mechanism.getResponse(challenge))
	  File "/usr/lib/python2.5/site-packages/twisted/words/protocols/jabber/sasl_mechanisms.py", line 100, in getResponse
	    directives['nonce'])
	  File "/usr/lib/python2.5/site-packages/twisted/words/protocols/jabber/sasl_mechanisms.py", line 220, in _gen_response
	    return self._unparse(directives)
	  File "/usr/lib/python2.5/site-packages/twisted/words/protocols/jabber/sasl_mechanisms.py", line 168, in _unparse
	    return ','.join(directive_list)
	exceptions.UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 13: ordinal not in range(128)
```

In my working copy this fix in _unparse works:
```
  for name, value in directives.iteritems():
            if isinstance(name, unicode): name = name.encode("utf8")
            if isinstance(value, unicode): value = value.encode("utf8")
```

<details><summary>Searchable metadata</summary>

```
trac-id__4161 4161
type__defect defect
reporter__sciasbat sciasbat
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__duplicate duplicate
component__words words
keywords__sasl sasl
time__1260294512000000 1260294512000000
changetime__1260881515000000 1260881515000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

An example of how this can be reproduced would also be useful.

**Comment by twisted-trac** [comment]
|<img alt="sciasbat's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_2"></a>|sciasbat commented|
|-|-|

Replying to [exarkun](#note_1):
> An example of how this can be reproduced would also be useful.

just try logging in with something like this

```
client.XMPPClientFactory(JID(u"élite@example.org"), secret)
```

**Comment by twisted-trac** [comment]
|[<img alt="ralphm's avatar" src="https://avatars.githubusercontent.com/u/116741?s=50" width="50" height="50">](https://github.com/ralphm)|@ralphm set status to `assigned`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="ralphm's avatar" src="https://avatars.githubusercontent.com/u/116741?s=50" width="50" height="50">](https://github.com/ralphm)<a name="note_4"></a>|@ralphm commented|
|-|-|

As you can see in `_gen_response`, the username is already encoded there. The problem lies in the digest_uri, which is not encoded, causing the join to fail. I'll create a proper test for this, along with a corresponding fix.

**Comment by twisted-trac** [comment]
|[<img alt="ralphm's avatar" src="https://avatars.githubusercontent.com/u/116741?s=50" width="50" height="50">](https://github.com/ralphm)<a name="note_5"></a>|@ralphm set status to `closed`|
|-|-|

Oh, and _you_ already added a bug for this two years ago. Closing this as a duplicate of [#2756](https://github.com/twisted/twisted/issues/2756).

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
