### ISSUE TITLE
--debug-stacktraces causes test failures on Deferred's tests

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#4177]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)| @glyph reported|
|-|-|
|Trac ID|trac#4177|
|Type|enhancement|
|Created|2009-12-18 06:33:53Z|

From the output of 'trial --debug-stacktraces twisted.test.test_defer':
```
===============================================================================
[FAIL]: twisted.test.test_defer.LogTestCase.test_errorLog

Traceback (most recent call last):
  File ".../twisted/test/test_defer.py", line 679, in test_errorLog
    self._check()
  File ".../twisted/test/test_defer.py", line 667, in _check
    self.assertEquals(len(c2), 2)
twisted.trial.unittest.FailTest: not equal:
a = 3
b = 2

===============================================================================
[FAIL]: twisted.test.test_defer.LogTestCase.test_errorLogWithInnerFrameCycle

Traceback (most recent call last):
  File ".../twisted/test/test_defer.py", line 706, in test_errorLogWithInnerFrameCycle
    self._check()
  File ".../twisted/test/test_defer.py", line 667, in _check
    self.assertEquals(len(c2), 2)
twisted.trial.unittest.FailTest: not equal:
a = 3
b = 2

===============================================================================
[FAIL]: twisted.test.test_defer.LogTestCase.test_errorLogWithInnerFrameRef

Traceback (most recent call last):
  File ".../twisted/test/test_defer.py", line 692, in test_errorLogWithInnerFrameRef
    self._check()
  File ".../twisted/test/test_defer.py", line 667, in _check
    self.assertEquals(len(c2), 2)
twisted.trial.unittest.FailTest: not equal:
a = 3
b = 2

===============================================================================
[ERROR]: twisted.test.test_defer.LogTestCase.test_errorLog

Traceback (most recent call last):
  File ".../twisted/test/test_defer.py", line 677, in <lambda>
    defer.Deferred().addCallback(lambda x: 1/0).callback(1)
exceptions.ZeroDivisionError: integer division or modulo by zero
===============================================================================
[ERROR]: twisted.test.test_defer.LogTestCase.test_errorLogWithInnerFrameCycle

Traceback (most recent call last):
  File ".../twisted/test/test_defer.py", line 700, in <lambda>
    d.addCallback(lambda x, d=d: 1/0)
exceptions.ZeroDivisionError: integer division or modulo by zero
===============================================================================
[ERROR]: twisted.test.test_defer.LogTestCase.test_errorLogWithInnerFrameRef

Traceback (most recent call last):
  File ".../twisted/test/test_defer.py", line 687, in <lambda>
    d.addCallback(lambda x: 1/0)
exceptions.ZeroDivisionError: integer division or modulo by zero
-------------------------------------------------------------------------------
Ran 53 tests in 0.532s

FAILED (failures=3, errors=3, successes=50)
```

<details><summary>Searchable metadata</summary>

```
trac-id__4177 4177
type__enhancement enhancement
reporter__glyph glyph
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__ 
time__1261118033000000 1261118033000000
changetime__1261118033000000 1261118033000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
