### ISSUE TITLE
NameError: global name 'FilePath' is not defined

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#4193]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)| @thijstriemstra reported|
|-|-|
|Trac ID|trac#4193|
|Type|defect|
|Created|2009-12-28 00:38:31Z|

Was getting this error:

```python
$ python setup.py test
running test
running egg_info
writing requirements to PyAMF.egg-info/requires.txt
writing PyAMF.egg-info/PKG-INFO
writing top-level names to PyAMF.egg-info/top_level.txt
writing dependency_links to PyAMF.egg-info/dependency_links.txt
writing manifest file 'PyAMF.egg-info/SOURCES.txt'
running build_ext
copying build/lib.linux-x86_64-2.6/cpyamf/util.so -> cpyamf
copying build/lib.linux-x86_64-2.6/cpyamf/amf3.so -> cpyamf
could not remove FilePath('/home/thijs/pyamf/_trial_temp'), caught OSError [Errno 13]: Permission denied
Traceback (most recent call last):
  File "setup.py", line 186, in <module>
    "Topic :: Software Development :: Libraries :: Python Modules",
  File "/usr/local/lib/python2.6/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/local/lib/python2.6/distutils/dist.py", line 975, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python2.6/distutils/dist.py", line 995, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.6/site-packages/setuptools-0.6c11-py2.6.egg/setuptools/command/test.py", line 121, in run
  File "/usr/local/lib/python2.6/site-packages/setuptools-0.6c11-py2.6.egg/setuptools/command/test.py", line 101, in with_project_on_sys_path
  File "setup.py", line 36, in run_tests
    return self.run_twisted()
  File "setup.py", line 26, in run_twisted
    return r.run(suite())
  File "/usr/local/lib/python2.6/site-packages/Twisted-9.0.0-py2.6-linux-x86_64.egg/twisted/trial/runner.py", line 833, in run
    return self._runWithoutDecoration(test)
  File "/usr/local/lib/python2.6/site-packages/Twisted-9.0.0-py2.6-linux-x86_64.egg/twisted/trial/runner.py", line 859, in _runWithoutDecoration
    oldDir = self._setUpTestdir()
  File "/usr/local/lib/python2.6/site-packages/Twisted-9.0.0-py2.6-linux-x86_64.egg/twisted/trial/runner.py", line 753, in _setUpTestdir
    self._removeSafely(testdir)
  File "/usr/local/lib/python2.6/site-packages/Twisted-9.0.0-py2.6-linux-x86_64.egg/twisted/trial/runner.py", line 728, in _removeSafely
    newPath = FilePath('_trial_temp_old%s'
NameError: global name 'FilePath' is not defined
```

Which starts out as a permission problem, which is ok, but turns into a ```NameError```. ```FilePath``` should be ```file.FilePath``` in [twisted/trial/runner.py#L728](twisted/trial/runner.py#L728)

<details><summary>Searchable metadata</summary>

```
trac-id__4193 4193
type__defect defect
reporter__thijs thijs
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__duplicate duplicate
component__trial trial
keywords__ 
time__1261960711000000 1261960711000000
changetime__1262009486000000 1262009486000000
version__None None
owner__jml jml
cc__thijs
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun set status to `closed`|
|-|-|

Duplicate of [#4020](https://github.com/twisted/twisted/issues/4020)
