### ISSUE TITLE
twisted.protocols.sip assumes DelayedCalls are scheduled by wallclock time

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#4198]
|<img alt="ivank's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| ivank reported|
|-|-|
|Trac ID|trac#4198|
|Type|defect|
|Created|2010-01-05 02:47:24Z|

twisted/protocols/sip.py has `dc.getTime() - time.time()` in two places, which is wrong because DelayedCall``s are not guaranteed to be scheduled by `time.time()`. Perhaps it should use `twisted.python.runtime.seconds()`, or do something else entirely.

Using a monotonic clock breaks these tests (line numbers may be wrong):

```
===============================================================================
[FAIL]: twisted.test.test_sip.RegistrationTestCase.testRegister

Traceback (most recent call last):
  File "/opt/Python-latest/lib/python2.7/site-packages/twisted/test/test_sip.py", line 540, in testRegister
    int(m.headers["expires"][0]) in (3600, 3601, 3599, 3598))
twisted.trial.unittest.FailTest: None
===============================================================================
[ERROR]: twisted.test.test_sip.AuthorizationTestCase.testChallenge

Traceback (most recent call last):
  File "/opt/Python-latest/lib/python2.7/site-packages/twisted/test/test_sip.py", line 883, in testChallenge
    self.transport.written[-1],
exceptions.IndexError: list index out of range
===============================================================================
[ERROR]: twisted.test.test_sip.AuthorizationTestCase.testChallenge

Traceback (most recent call last):
  File "/opt/Python-latest/lib/python2.7/site-packages/twisted/test/test_sip.py", line 832, in _cbReg
    "bad seconds to expire: %s" % reg.secondsToExpiry)
exceptions.RuntimeError: bad seconds to expire: -1260891498
```

<details><summary>Searchable metadata</summary>

```
trac-id__4198 4198
type__defect defect
reporter__ivank ivank
priority__low low
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__ 
time__1262659644000000 1262659644000000
changetime__1275191155000000 1275191155000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_1"></a>|@glyph commented|
|-|-|

`DelayedCall` doesn't document this as an `@ivar`, but I suspect it should: it has a "`seconds`" attribute which should be used for just this purpose.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_2"></a>|@exarkun commented|
|-|-|

It might be better to go all the way to a documented attribute that provides `IReactorTime`.

**Comment by twisted-trac** [comment]
|<img alt="ivank's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_3"></a>|ivank commented|
|-|-|

[#2424](https://github.com/twisted/twisted/issues/2424) is the "monotonic clock for reactor" ticket

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
