### ISSUE TITLE
trial --temp-directory= blows up

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#4215]
|<img alt="ChrisW's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| ChrisW reported|
|-|-|
|Trac ID|trac#4215|
|Type|defect|
|Created|2010-01-13 22:16:28Z|

In an effort to stop trial dropping spoor all over my svn checkouts, I tried:

```
$ mkdir /tmp/_trial_temp
$ trial --temp-directory=/tmp/_trial_temp
Traceback (most recent call last):
  File "/usr/bin/trial", line 5, in <module>
    pkg_resources.run_script('Twisted==9.0.0', 'trial')
  File "/usr/lib/python2.5/site-packages/pkg_resources.py", line 448, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.5/site-packages/pkg_resources.py", line 1166, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib/python2.5/site-packages/Twisted-9.0.0-py2.5-linux-x86_64.egg/EGG-INFO/scripts/trial", line 22, in <module>
    run()
  File "/usr/lib/python2.5/site-packages/Twisted-9.0.0-py2.5-linux-x86_64.egg/twisted/scripts/trial.py", line 363, in run
    test_result = trialRunner.run(suite)
  File "/usr/lib/python2.5/site-packages/Twisted-9.0.0-py2.5-linux-x86_64.egg/twisted/trial/runner.py", line 833, in run
    return self._runWithoutDecoration(test)
  File "/usr/lib/python2.5/site-packages/Twisted-9.0.0-py2.5-linux-x86_64.egg/twisted/trial/runner.py", line 859, in _runWithoutDecoration
    oldDir = self._setUpTestdir()
  File "/usr/lib/python2.5/site-packages/Twisted-9.0.0-py2.5-linux-x86_64.egg/twisted/trial/runner.py", line 753, in _setUpTestdir
    self._removeSafely(testdir)
  File "/usr/lib/python2.5/site-packages/Twisted-9.0.0-py2.5-linux-x86_64.egg/twisted/trial/runner.py", line 720, in _removeSafely
    % (path,))
twisted.trial.runner._NoTrialMarker: FilePath('/tmp/_trial_temp') is not a trial temporary path, refusing to remove it
```

<details><summary>Searchable metadata</summary>

```
trac-id__4215 4215
type__defect defect
reporter__ChrisW ChrisW
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__invalid invalid
component__trial trial
keywords__ 
time__1263420988000000 1263420988000000
changetime__1273505786000000 1273505786000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

fixing description markup

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_2"></a>|@exarkun commented|
|-|-|

This doesn't happen to me if `/tmp/_trial_temp/` doesn't already exist.  However, if I first create an empty `/tmp/_trial_temp/` then it does.  Is that what you're experiencing?

**Comment by twisted-trac** [comment]
|<img alt="ChrisW's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_3"></a>|ChrisW commented|
|-|-|

Yes.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_4"></a>|@exarkun set status to `closed`|
|-|-|

I don't understand the bug, then.  This is the intended, expected behavior because you're asking trial to delete a directory which it _knows_ it did not create.  It refuses to do this, in case you've accidentally asked it to delete ~ or something.

**Comment by twisted-trac** [comment]
|<img alt="ChrisW's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_5"></a>|ChrisW commented|
|-|-|

Okay, but I got a similar error when I tried to use:

trial --temp-directory=/tmp

I also remember getting an error when I tried:

trial --temp-directory=/tmp/_trial_temp/ and /tmp/_trial_temp/ didn't exist...

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_6"></a>|@exarkun commented|
|-|-|

`/tmp` also exists already; and you hardly want trial to delete `/tmp`.

`trial --temp-directory=/tmp/_trial_temp/` works fine for me if `/tmp/_trial_temp/` doesn't exist (or if it does and it was created by a previous trial run).

**Comment by twisted-trac** [comment]
|<img alt="ChrisW's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_7"></a>|ChrisW commented|
|-|-|

Okay, I guess that must have been the one option I missed...

Nonetheless, I do wish trial put _trial_temp in $TEMPDIR by default, rather than dropped it in the current working directory where it usually upsets whatever RCS you're using.

(and while I'm piling stuff in that has nothing to do with this specific bug ;-) - it'd be great if trial would use a config file in, say, ~/.trial for options such as the above...)

**Comment by twisted-trac** [comment]
|<img alt="ChrisW's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_8"></a>|ChrisW set status to `reopened`|
|-|-|

Any reason why this was closed with the two remaining problems unaddressed?
Should I put those in new bugs?

**Comment by twisted-trac** [comment]
|<img alt="spiv's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_9"></a>|spiv set status to `closed`|
|-|-|

Which two issues?  "wish trial put _trial_temp in $TEMPDIR by default" and "great if trial would use a config file"?

As you said yourself: they have nothing to do with this specific bug.  File new bugs for them.

It is unproductive to try to manage multiple bug reports in a single report, and it is unproductive to repurpose a bug report to be about a different bug.  Doing those things creates lengthy and confusing conversations in the bug report, and also impedes actually closing bug reports as they are fixed.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
