### ISSUE TITLE
Port _c_urlarg to 3.1

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#4246]
|<img alt="loewis's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| loewis reported|
|-|-|
|Trac ID|trac#4246|
|Type|enhancement|
|Created|2010-01-30 17:47:21Z|
|Branch|https://github.com/twisted/twisted/tree/c-urlarg-4246|

This patch makes the _c_urlarg module work with both 2.x and 3.x. The patch depends on [#4244](https://github.com/twisted/twisted/issues/4244) and [#4245](https://github.com/twisted/twisted/issues/4245) being accepted.

Attachments:

* [urlarg_3k.diff](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/19a/19afca7482367f22ec3f418a04029acb1ab6b325/6248e4f60b79ae2605777d666af312ed5bb11c81.diff) (2190 bytes) - added by loewis on 2010-01-30 17:47:39Z - 
* [4246.feature](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/19a/19afca7482367f22ec3f418a04029acb1ab6b325/135676dc286ff2fd95a1761df5607153179e4160.feature) (432 bytes) - added by loewis on 2010-01-31 08:06:45Z - 

<details><summary>Searchable metadata</summary>

```
trac-id__4246 4246
type__enhancement enhancement
reporter__loewis loewis
priority__normal normal
milestone__Python_3_x Python-3.x
branch__branches_c_urlarg_4246 branches/c-urlarg-4246
branch_author__thijs thijs
status__closed closed
resolution__duplicate duplicate
component__core core
keywords__py3k py3k
time__1264873641000000 1264873641000000
changetime__1300306299000000 1300306299000000
version__None None
owner__loewis loewis
cc__spiv cc__thijs
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="spiv's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_3"></a>|spiv commented|
|-|-|

(In [28105]) Merge curlarg-drop-cstringio-4245: Drop usage of cStringIO in _c_urlarg.c

Author: loewis
Reviewer: spiv
Fixes: [#4245](https://github.com/twisted/twisted/issues/4245)
Refs: [#4246](https://github.com/twisted/twisted/issues/4246)

Drop usage of cStringIO in _c_urlarg in favour of building (and resizing) a
PyString directly.

Thanks to martin@... for the patch.

**Comment by twisted-trac** [comment]
|<img alt="loewis's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|loewis removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)|@thijstriemstra set owner to @thijstriemstra<br>@thijstriemstra set status to `assigned`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_6"></a>|@thijstriemstra commented|
|-|-|

(In [28141]) Branching to 'c-urlarg-4246'

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_7"></a>|@thijstriemstra commented|
|-|-|

(In [28143]) Apply urlarg_3k.diff by loewis, refs [#4246](https://github.com/twisted/twisted/issues/4246)

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_8"></a>|@thijstriemstra commented|
|-|-|

Build results for Python 2.6.4 on OSX 10.6 look good:

```
building 'twisted.protocols._c_urlarg' extension
creating build/temp.macosx-10.5-fat3-2.6/twisted/protocols
gcc -arch ppc -arch i386 -arch x86_64 -isysroot / -fno-strict-aliasing -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/include/python2.6 -c twisted/protocols/_c_urlarg.c -o build/temp.macosx-10.5-fat3-2.6/twisted/protocols/_c_urlarg.o
gcc -arch ppc -arch i386 -isysroot / -Wl,-syslibroot,/Developer/SDKs/MacOSX10.5.sdk -arch ppc -arch i386 -arch x86_64 -bundle -undefined dynamic_lookup build/temp.macosx-10.5-fat3-2.6/twisted/protocols/_c_urlarg.o -o build/lib.macosx-10.5-fat3-2.6/twisted/protocols/_c_urlarg.so
```

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_9"></a>|@thijstriemstra commented|
|-|-|

(In [28147]) Make print compatible with python 3.1, refs [#4246](https://github.com/twisted/twisted/issues/4246)

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_10"></a>|@thijstriemstra set owner to loewis<br>@thijstriemstra set status to `new`|
|-|-|

Building it on Python 3.1 fails with this error:

```python
$ python3.1 setup.py build
SyntaxError: invalid token (branchmgr.py, line 571)
  File "setup.py", line 87
    """
      ^
SyntaxError: invalid syntax
```

Which is fixed with r28147. It then dies with:

```python
Traceback (most recent call last):
  File "setup.py", line 97, in <module>
    main(sys.argv[1:])
  File "setup.py", line 45, in main
    from twisted import copyright
  File "./twisted/__init__.py", line 18, in <module>
    from twisted.python import compat
  File "./twisted/python/compat.py", line 143
    self._lock.release()\n""" % (f, f)
                            ^
SyntaxError: invalid syntax
```

So there's some more work to be done before this can build cleanly on Python 3.1.

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_11"></a>|@thijstriemstra commented|
|-|-|

Replying to [thijs](#note_10):
> So there's some more work to be done before this can build cleanly on Python 3.1.

Which has been done in [[#4244](https://github.com/twisted/twisted/issues/4244)](https://github.com/twisted/twisted/issues/4244), sorry I didn't notice this before. So this ticket seems to be blocked by #4244, so let's make that land first.

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_12"></a>|@thijstriemstra commented|
|-|-|

(In [28235]) Add NEWS file, refs [#4246](https://github.com/twisted/twisted/issues/4246)

**Comment by twisted-trac** [comment]
|<img alt="PenguinOfDoom's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_13"></a>|PenguinOfDoom set status to `closed`|
|-|-|

[#4162](https://github.com/twisted/twisted/issues/4162) removed _c_urlarg completely
