### ISSUE TITLE
After upgrading from 9.0.0 to 10.0.0 cannot set uid, gid

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#4351]
|<img alt="alecm3's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| alecm3 reported|
|-|-|
|Trac ID|trac#4351|
|Type|defect|
|Created|2010-03-06 01:56:22Z|

New error in 10.0.0 (same code works with 9.0.0)
```
2010-03-05 17:39:45-0800 [-] Traceback (most recent call last):
2010-03-05 17:39:45-0800 [-]   File "/usr/local/bin/twistd", line 5, in <module>
2010-03-05 17:39:45-0800 [-]     pkg_resources.run_script('Twisted==10.0.0', 'twistd')
2010-03-05 17:39:45-0800 [-]   File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 489, in run_script
2010-03-05 17:39:45-0800 [-]   File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 1207, in run_script
2010-03-05 17:39:45-0800 [-]   File "/nail/encap/python-2.6.4/lib/python2.6/site-packages/Twisted-10.0.0-py2.6-linux-x86_64.egg/EGG-INFO/scripts/twistd", line 19, in <module>
2010-03-05 17:39:45-0800 [-]     run()
2010-03-05 17:39:45-0800 [-]   File "/usr/local/encap/python-2.6.4/lib/python2.6/site-packages/Twisted-10.0.0-py2.6-linux-x86_64.egg/twisted/scripts/twistd.py", line 27, in run
2010-03-05 17:39:45-0800 [-]     app.run(runApp, ServerOptions)
2010-03-05 17:39:45-0800 [-]   File "/usr/local/encap/python-2.6.4/lib/python2.6/site-packages/Twisted-10.0.0-py2.6-linux-x86_64.egg/twisted/application/app.py", line 693, in run
2010-03-05 17:39:45-0800 [-]     runApp(config)
2010-03-05 17:39:45-0800 [-]   File "/usr/local/encap/python-2.6.4/lib/python2.6/site-packages/Twisted-10.0.0-py2.6-linux-x86_64.egg/twisted/scripts/twistd.py", line 23, in runApp
2010-03-05 17:39:45-0800 [-]     _SomeApplicationRunner(config).run()
2010-03-05 17:39:45-0800 [-]   File "/usr/local/encap/python-2.6.4/lib/python2.6/site-packages/Twisted-10.0.0-py2.6-linux-x86_64.egg/twisted/application/app.py", line 423, in run
2010-03-05 17:39:45-0800 [-]     self.postApplication()
2010-03-05 17:39:45-0800 [-]   File "/usr/local/encap/python-2.6.4/lib/python2.6/site-packages/Twisted-10.0.0-py2.6-linux-x86_64.egg/twisted/scripts/_twistd_unix.py", line 205, in postApplication
2010-03-05 17:39:45-0800 [-]     self.startApplication(self.application)
2010-03-05 17:39:45-0800 [-]   File "/usr/local/encap/python-2.6.4/lib/python2.6/site-packages/Twisted-10.0.0-py2.6-linux-x86_64.egg/twisted/scripts/_twistd_unix.py", line 316, in startApplication
2010-03-05 17:39:45-0800 [-]     self.shedPrivileges(self.config['euid'], uid, gid)
2010-03-05 17:39:45-0800 [-]   File "/usr/local/encap/python-2.6.4/lib/python2.6/site-packages/Twisted-10.0.0-py2.6-linux-x86_64.egg/twisted/scripts/_twistd_unix.py", line 287, in shedPrivileges
2010-03-05 17:39:45-0800 [-]     switchUID(uid, gid, euid)
2010-03-05 17:39:45-0800 [-]   File "/usr/local/encap/python-2.6.4/lib/python2.6/site-packages/Twisted-10.0.0-py2.6-linux-x86_64.egg/twisted/python/util.py", line 677, in switchUID
2010-03-05 17:39:45-0800 [-]     initgroups(uid, gid)
2010-03-05 17:39:45-0800 [-]   File "/usr/local/encap/python-2.6.4/lib/python2.6/site-packages/Twisted-10.0.0-py2.6-linux-x86_64.egg/twisted/python/util.py", line 636, in initgroups
2010-03-05 17:39:45-0800 [-]     return _c_initgroups(pwd.getpwuid(uid)[0], primaryGid)
2010-03-05 17:39:45-0800 [-] OSError: [Errno 1] Operation not permitted
```
OS: Ubuntu 8.04 

<details><summary>Searchable metadata</summary>

```
trac-id__4351 4351
type__defect defect
reporter__alecm3 alecm3
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__worksforme worksforme
component__core core
keywords__ 
time__1267840582000000 1267840582000000
changetime__1268551947000000 1268551947000000
version__None None
owner__alecm3 alecm3
cc__exarkun
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

Fixing description markup.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_2"></a>|@exarkun commented|
|-|-|

Can you describe your environment in more detail?  For example, what UID and GID is starting the process, what UID and GID is it trying to switch to, is there anything unusual about how users and groups are managed on your site?

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)|@glyph set owner to alecm3|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_4"></a>|@glyph commented|
|-|-|

This works on all the systems I've tried it on, but if you can report more information about where this failed, it would be really useful.  When you do, please reopen this ticket and we'll try to address it, as this would be a serious regression.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)|@glyph set status to `closed`|
|-|-|
