### ISSUE TITLE
twistd emits a spurious traceback when signalled multiple times during shutdown

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#4406]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)| @glyph reported|
|-|-|
|Trac ID|trac#4406|
|Type|enhancement|
|Created|2010-04-20 02:08:38Z|

With the following tac file: 
```
from twisted.application import service
from twisted.internet.defer import Deferred
application = service.Application('test')
class SlowStopper(service.Service):
    def stopService(self):
        service.Service.stopService(self)
        return Deferred()
slow = SlowStopper()
slow.setServiceParent(service.IServiceCollection(application))
```
I start twistd, and hit `^C` twice.

My expectation is that it should emit log messages telling me that it is in the process of shutting down.  Perhaps it would even have a countdown to a "hard" exit (I remember we used to have that feature, although I don't know if it's actually useful except in preventing [Apport](https://wiki.ubuntu.com/Apport) or [CrashReporter](http://developer.apple.com/mac/library/technotes/tn2004/tn2123.html) from getting all up in your grill.)

Instead, I see this:

```
$ twistd -noy bugsample.tac 
2010-04-19 19:01:17-0700 [-] Log opened.
2010-04-19 19:01:17-0700 [-] using set_wakeup_fd
2010-04-19 19:01:17-0700 [-] twistd 10.0.0+r28832 (/usr/bin/python 2.6.1) starting up.
2010-04-19 19:01:17-0700 [-] reactor class: twisted.internet.selectreactor.SelectReactor.
^C2010-04-19 19:01:19-0700 [-] Received SIGINT, shutting down.
^C2010-04-19 19:01:21-0700 [-] Received SIGINT, shutting down.
2010-04-19 19:01:21-0700 [-] Unhandled Error
        Traceback (most recent call last):
          File "twisted/application/app.py", line 445, in startReactor
            self.config, oldstdout, oldstderr, self.profiler, reactor)
          File "twisted/application/app.py", line 348, in runReactorWithLogging
            reactor.run()
          File "twisted/internet/base.py", line 1148, in run
            self.mainLoop()
          File "twisted/internet/base.py", line 1157, in mainLoop
            self.runUntilCurrent()
        --- <exception caught here> ---
          File "twisted/internet/base.py", line 752, in runUntilCurrent
            f(*a, **kw)
          File "twisted/internet/base.py", line 553, in stop
            "Can't stop reactor that isn't running.")
        twisted.internet.error.ReactorNotRunning: Can't stop reactor that isn't running.
```
with the traceback repeated for every additional `^C`.

<details><summary>Searchable metadata</summary>

```
trac-id__4406 4406
type__enhancement enhancement
reporter__glyph glyph
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__twistd twistd
time__1271729318000000 1271729318000000
changetime__1279127873000000 1279127873000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_2"></a>|@exarkun commented|
|-|-|

> Perhaps it would even have a countdown to a "hard" exit (I remember we used to have that feature, although I don't know if it's actually useful except in preventing Apport or  CrashReporter from getting all up in your grill.) 

The feature never existed in version control. :)  It might be nice, though.  What do Apport and CrashReport think about SIGQUIT?

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_3"></a>|@glyph commented|
|-|-|

Replying to [exarkun](#note_2):
> > Perhaps it would even have a countdown to a "hard" exit (I remember we used to have that feature, although I don't know if it's actually useful except in preventing Apport or  CrashReporter from getting all up in your grill.) 
> 
> The feature never existed in version control. :)

Wow, really?

> It might be nice, though.  What do Apport and CrashReport think about SIGQUIT?

Hmm.  I thought they didn't like it, but it appears the problem is more specific to `SIGQUIT`ing Python.  Now I wonder if this is something about my environment that's problematic, or an actual bug in Python - I had assumed that it was spurious crash-reporting behavior.  (I haven't tested with Apport recently, but I  recall it having a similar problem on Hardy.)

At any rate, let's call that a separate issue - this one should really be about fixing the tracebacks.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
