### ISSUE TITLE
Conch's test_extendedAttributes and test_exec fail on Ubuntu 10.04

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#4413]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#4413|
|Type|defect|
|Created|2010-04-27 13:58:08Z|

This can be seen on the new Ubuntu 10.04 build slave, eg http://buildbot.twistedmatrix.com/builders/ubuntu64-py2.6-select/builds/314.

```
===============================================================================
[ERROR]: twisted.conch.test.test_cftp.TestOurServerSftpClient.test_extendedAttributes

Traceback (most recent call last):
  File "/var/lib/buildbot/twisted/ubuntu64-python2.6-select/Twisted/twisted/internet/selectreactor.py", line 146, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "/var/lib/buildbot/twisted/ubuntu64-python2.6-select/Twisted/twisted/internet/tcp.py", line 460, in doRead
    return self.protocol.dataReceived(data)
  File "/var/lib/buildbot/twisted/ubuntu64-python2.6-select/Twisted/twisted/conch/ssh/transport.py", line 313, in dataReceived
    self.dispatchMessage(messageNum, packet[1:])
  File "/var/lib/buildbot/twisted/ubuntu64-python2.6-select/Twisted/twisted/conch/ssh/transport.py", line 328, in dispatchMessage
    f(payload)
  File "/var/lib/buildbot/twisted/ubuntu64-python2.6-select/Twisted/twisted/conch/ssh/transport.py", line 421, in ssh_DISCONNECT
    self.receiveError(reasonCode, description)
  File "/var/lib/buildbot/twisted/ubuntu64-python2.6-select/Twisted/twisted/conch/test/test_ssh.py", line 330, in receiveError
    (self, reasonCode, desc))
  File "/var/lib/buildbot/twisted/ubuntu64-python2.6-select/Twisted/twisted/trial/unittest.py", line 1575, in _
    return getattr(_inst, name)(*args, **kwargs)
twisted.trial.unittest.FailTest: got disconnect for <twisted.conch.test.test_ssh.ConchTestServer instance at 0x57e8908>: reason 11, desc: disconnected by user
===============================================================================
[ERROR]: twisted.conch.test.test_conch.OpenSSHClientTestCase.test_exec

Traceback (most recent call last):
  File "/var/lib/buildbot/twisted/ubuntu64-python2.6-select/Twisted/twisted/internet/selectreactor.py", line 146, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "/var/lib/buildbot/twisted/ubuntu64-python2.6-select/Twisted/twisted/internet/tcp.py", line 460, in doRead
    return self.protocol.dataReceived(data)
  File "/var/lib/buildbot/twisted/ubuntu64-python2.6-select/Twisted/twisted/conch/ssh/transport.py", line 313, in dataReceived
    self.dispatchMessage(messageNum, packet[1:])
  File "/var/lib/buildbot/twisted/ubuntu64-python2.6-select/Twisted/twisted/conch/ssh/transport.py", line 328, in dispatchMessage
    f(payload)
  File "/var/lib/buildbot/twisted/ubuntu64-python2.6-select/Twisted/twisted/conch/ssh/transport.py", line 421, in ssh_DISCONNECT
    self.receiveError(reasonCode, description)
  File "/var/lib/buildbot/twisted/ubuntu64-python2.6-select/Twisted/twisted/conch/test/test_ssh.py", line 330, in receiveError
    (self, reasonCode, desc))
  File "/var/lib/buildbot/twisted/ubuntu64-python2.6-select/Twisted/twisted/trial/unittest.py", line 1575, in _
    return getattr(_inst, name)(*args, **kwargs)
twisted.trial.unittest.FailTest: got disconnect for <twisted.conch.test.test_ssh.ConchTestServer instance at 0x5987368>: reason 11, desc: disconnected by user
-------------------------------------------------------------------------------
```

<details><summary>Searchable metadata</summary>

```
trac-id__4413 4413
type__defect defect
reporter__exarkun exarkun
priority__high high
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__duplicate duplicate
component__conch conch
keywords__tests tests
time__1272376688000000 1272376688000000
changetime__1274779828000000 1274779828000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_1"></a>|@glyph set status to `closed`|
|-|-|

[#4454](https://github.com/twisted/twisted/issues/4454) (which is now fixed) was a duplicate of this.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
