### ISSUE TITLE
twisted.words.test.test_xpath.XPathTest.test_position fails

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#4424]
|<img alt="brianjarita's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| brianjarita reported|
|-|-|
|Trac ID|trac#4424|
|Type|enhancement|
|Created|2010-05-08 00:00:58Z|

```
[TODO]: twisted.words.test.test_xpath.XPathTest.test_position

Reason: 'XPath queries with position are not working.'
Traceback (most recent call last):
  File "/var/lib/buildbot/twisted/lucid64-python2.6-select/Twisted/twisted/words/test/test_xpath.py", line 139, in test_position
    self.assertEquals(xp.matches(self.e), 1)
  File "/var/lib/buildbot/twisted/lucid64-python2.6-select/Twisted/twisted/words/xish/xpath.py", line 288, in matches
    return self.baseLocation.matches(elem)
  File "/var/lib/buildbot/twisted/lucid64-python2.6-select/Twisted/twisted/words/xish/xpath.py", line 149, in matches
    if self.childLocation.matches(c):
  File "/var/lib/buildbot/twisted/lucid64-python2.6-select/Twisted/twisted/words/xish/xpath.py", line 144, in matches
    if not self.matchesPredicates(elem):
  File "/var/lib/buildbot/twisted/lucid64-python2.6-select/Twisted/twisted/words/xish/xpath.py", line 138, in matchesPredicates
    if not p.value(elem):
  File "/var/lib/buildbot/twisted/lucid64-python2.6-select/Twisted/twisted/words/xish/xpath.py", line 29, in value
    return elem.children[self.index]
exceptions.IndexError: list index out of range
```

This has been marked as todo for a while.  Fixing it (or deciding not to fix it) would be a good idea.

<details><summary>Searchable metadata</summary>

```
trac-id__4424 4424
type__enhancement enhancement
reporter__brianjarita brianjarita
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__wontfix wontfix
component__words words
keywords__ 
time__1273276858000000 1273276858000000
changetime__1503985158245012 1503985158245012
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun set owner to @ralphm|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_2"></a>|@exarkun commented|
|-|-|

bump

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_4"></a>|@rodrigc set status to `closed`|
|-|-|

twisted.words.test.test_xpath.XPathTest.test_position was removed in [ticket:7776]
