### ISSUE TITLE
`twistd --uid N` fails

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#4442]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#4442|
|Type|release blocker: regression|
|Created|2010-05-18 20:58:57Z|

```
exarkun@boson:~$ sudo twistd -n --uid 1000 web
2010-05-18 16:57:57-0400 [-] Log opened.
2010-05-18 16:57:57-0400 [-] twistd 10.0.0 (/usr/bin/python 2.6.4) starting up.
2010-05-18 16:57:57-0400 [-] reactor class: twisted.internet.selectreactor.SelectReactor.
2010-05-18 16:57:57-0400 [-] twisted.web.server.Site starting on 8080
2010-05-18 16:57:57-0400 [-] Starting factory <twisted.web.server.Site instance at 0x9aa3a4c>
2010-05-18 16:57:57-0400 [-] Traceback (most recent call last):
2010-05-18 16:57:57-0400 [-]   File "/usr/bin/twistd", line 19, in <module>
2010-05-18 16:57:57-0400 [-]     run()
2010-05-18 16:57:57-0400 [-]   File "/usr/lib/python2.6/dist-packages/twisted/scripts/twistd.py", line 27, in run
2010-05-18 16:57:57-0400 [-]     app.run(runApp, ServerOptions)
2010-05-18 16:57:57-0400 [-]   File "/usr/lib/python2.6/dist-packages/twisted/application/app.py", line 693, in run
2010-05-18 16:57:57-0400 [-]     runApp(config)
2010-05-18 16:57:57-0400 [-]   File "/usr/lib/python2.6/dist-packages/twisted/scripts/twistd.py", line 23, in runApp
2010-05-18 16:57:57-0400 [-]     _SomeApplicationRunner(config).run()
2010-05-18 16:57:57-0400 [-]   File "/usr/lib/python2.6/dist-packages/twisted/application/app.py", line 423, in run
2010-05-18 16:57:57-0400 [-]     self.postApplication()
2010-05-18 16:57:57-0400 [-]   File "/usr/lib/python2.6/dist-packages/twisted/scripts/_twistd_unix.py", line 205, in postApplication
2010-05-18 16:57:57-0400 [-]     self.startApplication(self.application)
2010-05-18 16:57:57-0400 [-]   File "/usr/lib/python2.6/dist-packages/twisted/scripts/_twistd_unix.py", line 316, in startApplication
2010-05-18 16:57:57-0400 [-]     self.shedPrivileges(self.config['euid'], uid, gid)
2010-05-18 16:57:57-0400 [-]   File "/usr/lib/python2.6/dist-packages/twisted/scripts/_twistd_unix.py", line 287, in shedPrivileges
2010-05-18 16:57:57-0400 [-]     switchUID(uid, gid, euid)
2010-05-18 16:57:57-0400 [-]   File "/usr/lib/python2.6/dist-packages/twisted/python/util.py", line 677, in switchUID
2010-05-18 16:57:57-0400 [-]     initgroups(uid, gid)
2010-05-18 16:57:57-0400 [-]   File "/usr/lib/python2.6/dist-packages/twisted/python/util.py", line 636, in initgroups
2010-05-18 16:57:57-0400 [-]     return _c_initgroups(pwd.getpwuid(uid)[0], primaryGid)
2010-05-18 16:57:57-0400 [-] TypeError: an integer is required
exarkun@boson:~$ 
```

<details><summary>Searchable metadata</summary>

```
trac-id__4442 4442
type__release_blocker__regression release blocker: regression
reporter__exarkun exarkun
priority__normal normal
milestone__ 
branch__None None
branch_author__exarkun exarkun
status__closed closed
resolution__fixed fixed
component__core core
keywords__twistd twistd
time__1274216337000000 1274216337000000
changetime__1504984392546129 1504984392546129
version__None None
owner__hawkowl hawkowl
cc__therve cc__thijs
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

Deleting the special note; it isn't a subtly different behavior, it's a different verison of Twisted.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_2"></a>|@exarkun commented|
|-|-|

When the initgroups extension module is available, `twisted.python.util.initgroups` will sometimes pass `None` to it for the GID.  This is because all the way up the stack, the GID value is optional.  When the extension module is not available, if the GID specified is `None`, it's just ignored.

As a random guess, a better thing to do would be to use the current GID as the primary GID, if no GID is specified.  All of this code is really subtle and complicated, though, as are the underlying states being manipulated.  So don't take my word for it.

**Comment by twisted-trac** [comment]
|<img alt="smira's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_3"></a>|smira commented|
|-|-|

It looks like bug/regression in Twisted 10.0. Twisted 8.2.0 runs program just fine.

Please, compare startup messages for the same code using the same start script using Twisted 10.0.0 and 8.2.0:

```
2010-06-18 01:30:23.879 [-] twistd 10.0.0 (/usr/local/bin/python 2.6.5) starting up.
2010-06-18 01:30:23.879 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2010-06-18 01:30:23.883 [-] twisted.web.server.Site starting on 8001
2010-06-18 01:30:23.883 [-] Starting factory <twisted.web.server.Site instance at 0x1cb62128>
2010-06-18 01:30:23.885 [-] Traceback (most recent call last):
2010-06-18 01:30:23.885 [-]   File "/usr/local/bin/twistd", line 5, in <module>
2010-06-18 01:30:23.885 [-]     pkg_resources.run_script('Twisted==10.0.0', 'twistd')
2010-06-18 01:30:23.885 [-]   File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 448, in run_script
2010-06-18 01:30:23.885 [-]   File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 1166, in run_script
2010-06-18 01:30:23.885 [-]   File "/usr/local/lib/python2.6/site-packages/Twisted-10.0.0-py2.6-linux-x86_64.egg/EGG-INFO/scripts/twistd", line 19, in <module>
2010-06-18 01:30:23.885 [-]     run()
2010-06-18 01:30:23.886 [-]   File "/usr/local/lib/python2.6/site-packages/Twisted-10.0.0-py2.6-linux-x86_64.egg/twisted/scripts/twistd.py", line 27, in run
2010-06-18 01:30:23.886 [-]     app.run(runApp, ServerOptions)
2010-06-18 01:30:23.886 [-]   File "/usr/local/lib/python2.6/site-packages/Twisted-10.0.0-py2.6-linux-x86_64.egg/twisted/application/app.py", line 693, in run
2010-06-18 01:30:23.886 [-]     runApp(config)
2010-06-18 01:30:23.886 [-]   File "/usr/local/lib/python2.6/site-packages/Twisted-10.0.0-py2.6-linux-x86_64.egg/twisted/scripts/twistd.py", line 23, in runApp
2010-06-18 01:30:23.886 [-]     _SomeApplicationRunner(config).run()
2010-06-18 01:30:23.886 [-]   File "/usr/local/lib/python2.6/site-packages/Twisted-10.0.0-py2.6-linux-x86_64.egg/twisted/application/app.py", line 423, in run
2010-06-18 01:30:23.887 [-]     self.postApplication()
2010-06-18 01:30:23.887 [-]   File "/usr/local/lib/python2.6/site-packages/Twisted-10.0.0-py2.6-linux-x86_64.egg/twisted/scripts/_twistd_unix.py", line 205, in postApplication
2010-06-18 01:30:23.887 [-]     self.startApplication(self.application)
2010-06-18 01:30:23.887 [-]   File "/usr/local/lib/python2.6/site-packages/Twisted-10.0.0-py2.6-linux-x86_64.egg/twisted/scripts/_twistd_unix.py", line 316, in startApplication
2010-06-18 01:30:23.887 [-]     self.shedPrivileges(self.config['euid'], uid, gid)
2010-06-18 01:30:23.887 [-]   File "/usr/local/lib/python2.6/site-packages/Twisted-10.0.0-py2.6-linux-x86_64.egg/twisted/scripts/_twistd_unix.py", line 287, in shedPrivileges
2010-06-18 01:30:23.888 [-]     switchUID(uid, gid, euid)
2010-06-18 01:30:23.888 [-]   File "/usr/local/lib/python2.6/site-packages/Twisted-10.0.0-py2.6-linux-x86_64.egg/twisted/python/util.py", line 677, in switchUID
2010-06-18 01:30:23.888 [-]     initgroups(uid, gid)
2010-06-18 01:30:23.888 [-]   File "/usr/local/lib/python2.6/site-packages/Twisted-10.0.0-py2.6-linux-x86_64.egg/twisted/python/util.py", line 636, in initgroups
2010-06-18 01:30:23.888 [-]     return _c_initgroups(pwd.getpwuid(uid)[0], primaryGid)
2010-06-18 01:30:23.888 [-] TypeError: an integer is required
```

```
2010-06-18 01:31:23.571 [-] twistd 8.2.0 (/usr/local/bin/python 2.6.5) starting up.
2010-06-18 01:31:23.571 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2010-06-18 01:31:23.576 [-] twisted.web.server.Site starting on 8001
2010-06-18 01:31:23.576 [-] Starting factory <twisted.web.server.Site instance at 0x60aa758>
2010-06-18 01:31:23.578 [-] set uid/gid 501/None
....
```

Startup command looks like:

```
twistd -u $USER service ...
```

OS: CentOS

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_5"></a>|@exarkun commented|
|-|-|

(In [29338]) Branching to 'initgroups-default-group-4442'

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_6"></a>|@exarkun removed owner|
|-|-|

I believe this is now fixed in the branch.  I made the change I described in my comment above, using `os.getgid()` to replace `None` when this case is triggered.

The [build results](http://buildbot.twistedmatrix.com/boxes-supported?branch=/branches/initgroups-default-group-4442) are available.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_7"></a>|@exarkun commented|
|-|-|

[#4518](https://github.com/twisted/twisted/issues/4518) was a duplicate of this.

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_8"></a>|@therve set owner to @exarkun|
|-|-|

Looks ok! I have a couple of comments though.

First, there is a spurious "set uid/gid None/$N" in the logs, because we end up doing os.setgid(os.getgid()).

Also, The process gid ends up in the result of getgroups, but I don't think there is a security problem here.

Finally, maybe the only real argument, initgroups is a public method in twisted.python.util, and used to accept None as a second argument, so we should probably fix it. I _think_ the correct behavior is to pass the getpwduid().pw_gid to initgroups. It also seems to accept -1, but it's hard to tell if it makes a difference.

Thanks!

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_9"></a>|@exarkun commented|
|-|-|

I moved the non-controversial parts of this into [#4534](https://github.com/twisted/twisted/issues/4534).  That should be an easy review, and afterwards the changes in this branch can focus just on the uid/gid issues.

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)<a name="note_10"></a>|@jml commented|
|-|-|

Twisted 10.1.0 has been released. Removing this ticket from the 10.1 milestone. If you think it's severe enough to demand a follow-up release, please say so and add this ticket back to the 10.1 milestone.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_12"></a>|@exarkun commented|
|-|-|

[#4816](https://github.com/twisted/twisted/issues/4816) was a duplicate.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_15"></a>|@rodrigc commented|
|-|-|

https://github.com/twisted/twisted/pull/869

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_16"></a>|@markrwilliams commented|
|-|-|

https://github.com/twisted/twisted/pull/869#pullrequestreview-57344298

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_18"></a>|@markrwilliams commented|
|-|-|

https://github.com/twisted/twisted/pull/869#pullrequestreview-59466926

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)|@hawkowl set owner to @hawkowl|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_21"></a>|@rodrigc commented|
|-|-|

Review approved: https://github.com/twisted/twisted/pull/869#pullrequestreview-61660733

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_22"></a>|@rodrigc set status to `closed`|
|-|-|

In changeset 5408ad616bcd0dc3478c846d3dd4be27e56aedbf
```
#!CommitTicketReference repository="" revision="5408ad616bcd0dc3478c846d3dd4be27e56aedbf"
Merge pull request #869 from twisted/4442-rodrigc-initgroups

Author: rodrigc
Reviewer: markrwilliams, hawkowl
Fixes: ticket:4442

Fix "twistd -n --uid 1000 web" if no --gid flag is specified
```
