### ISSUE TITLE
test_process failures on Debian

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#4466]
|[<img alt="mithrandi's avatar" src="https://avatars.githubusercontent.com/u/856430?s=50" width="50" height="50">](https://github.com/mithrandi)| @mithrandi reported|
|-|-|
|Trac ID|trac#4466|
|Type|release blocker: regression|
|Created|2010-05-30 10:03:18Z|

I get the following failures on Debian sid (unstable) amd64:

```
===============================================================================
[FAIL]: twisted.internet.test.test_process.PTYProcessTestsBuilder_PollReactor.test_systemCallUninterruptedByChildExit

Traceback (most recent call last):
  File "/home/mithrandi/code/Twisted/trunk/twisted/internet/test/test_process.py", line 219, in test_systemCallUninterruptedByChildExit
    self.assertEqual(result, ["Foo\n"])   
twisted.trial.unittest.FailTest: not equal:
a = []
b = ['Foo\n']

===============================================================================
[FAIL]: twisted.internet.test.test_process.PTYProcessTestsBuilder_SelectReactor.test_systemCallUninterruptedByChildExit

Traceback (most recent call last):
  File "/home/mithrandi/code/Twisted/trunk/twisted/internet/test/test_process.py", line 219, in test_systemCallUninterruptedByChildExit
    self.assertEqual(result, ["Foo\n"])   
twisted.trial.unittest.FailTest: not equal:
a = []
b = ['Foo\n']

===============================================================================
[FAIL]: twisted.internet.test.test_process.ProcessTestsBuilder_PollReactor.test_systemCallUninterruptedByChildExit

Traceback (most recent call last):
  File "/home/mithrandi/code/Twisted/trunk/twisted/internet/test/test_process.py", line 219, in test_systemCallUninterruptedByChildExit
    self.assertEqual(result, ["Foo\n"])
twisted.trial.unittest.FailTest: not equal:
a = []
b = ['Foo\n']

===============================================================================
[FAIL]: twisted.internet.test.test_process.ProcessTestsBuilder_SelectReactor.test_systemCallUninterruptedByChildExit

Traceback (most recent call last):
  File "/home/mithrandi/code/Twisted/trunk/twisted/internet/test/test_process.py", line 219, in test_systemCallUninterruptedByChildExit
    self.assertEqual(result, ["Foo\n"])
twisted.trial.unittest.FailTest: not equal:
a = []
b = ['Foo\n']

===============================================================================
[ERROR]: twisted.internet.test.test_process.PTYProcessTestsBuilder_PollReactor.test_systemCallUninterruptedByChildExit

Traceback (most recent call last):
  File "/home/mithrandi/code/Twisted/trunk/twisted/internet/base.py", line 426, in _continueFiring
    callable(*args, **kwargs)
  File "/home/mithrandi/code/Twisted/trunk/twisted/internet/test/test_process.py", line 213, in f
    result.append(f2.read())
exceptions.IOError: [Errno 4] Interrupted system call
===============================================================================
[ERROR]: twisted.internet.test.test_process.PTYProcessTestsBuilder_SelectReactor.test_systemCallUninterruptedByChildExit

Traceback (most recent call last):
  File "/home/mithrandi/code/Twisted/trunk/twisted/internet/base.py", line 426, in _continueFiring
    callable(*args, **kwargs)
  File "/home/mithrandi/code/Twisted/trunk/twisted/internet/test/test_process.py", line 213, in f
    result.append(f2.read())
exceptions.IOError: [Errno 4] Interrupted system call
===============================================================================
[ERROR]: twisted.internet.test.test_process.ProcessTestsBuilder_PollReactor.test_systemCallUninterruptedByChildExit

Traceback (most recent call last):
  File "/home/mithrandi/code/Twisted/trunk/twisted/internet/base.py", line 426, in _continueFiring
    callable(*args, **kwargs)
  File "/home/mithrandi/code/Twisted/trunk/twisted/internet/test/test_process.py", line 213, in f
    result.append(f2.read())
exceptions.IOError: [Errno 4] Interrupted system call
===============================================================================
[ERROR]: twisted.internet.test.test_process.ProcessTestsBuilder_SelectReactor.test_systemCallUninterruptedByChildExit

Traceback (most recent call last):
  File "/home/mithrandi/code/Twisted/trunk/twisted/internet/base.py", line 426, in _continueFiring
    callable(*args, **kwargs)
  File "/home/mithrandi/code/Twisted/trunk/twisted/internet/test/test_process.py", line 213, in f
    result.append(f2.read())
exceptions.IOError: [Errno 4] Interrupted system call
===============================================================================
```

I have no clue what any of them mean, but I'd be happy to provide assistance in tracking down the cause; catch me on IRC as "idnar".

<details><summary>Searchable metadata</summary>

```
trac-id__4466 4466
type__release_blocker__regression release blocker: regression
reporter__mithrandi mithrandi
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__duplicate duplicate
component__core core
keywords__ 
time__1275213798000000 1275213798000000
changetime__1275259807000000 1275259807000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun set status to `closed`|
|-|-|

Duplicate of [#4331](https://github.com/twisted/twisted/issues/4331)

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
