### ISSUE TITLE
No longer possible to run test suite with python -O

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#4476]
|<img alt="ivank's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| ivank reported|
|-|-|
|Trac ID|trac#4476|
|Type|release blocker: regression|
|Created|2010-05-31 22:52:29Z|
|Branch|https://github.com/twisted/twisted/tree/let-tests-run-under-python-O-4476|

It crashes in a flaming wreck. This is due to a very recent change.

```
~/Projects/Twisted]# python -O `which trial` twisted.internet.test
```

```
[many lines elided]

    test_removeReader ...                                             [SKIPPED]
    test_removeWriter ...                                             [SKIPPED]
twisted.internet.test.test_gtkreactor
  GtkReactorDeprecation
    test_gtkReactor ...                                                    [OK]
    test_install ...                                                     [FAIL]
                                                   [ERROR]
                                                   [ERROR]
    test_portableGtkReactor ...                                         [ERROR]
                                        [ERROR]
    test_portableInstall ...                                             [FAIL]
twisted.internet.test.inlinecb_tests
  NonLocalExitTests
    test_returnValueNonLocalDeferred ...                                   [OK]
    test_returnValueNonLocalWarning ...                                    [OK]
twisted.internet.test.test_inotify
  TestINotify
    test_access ...                                                        [OK]
Traceback (most recent call last):
  File "/usr/local/bin/trial", line 21, in <module>
    run()
  File "/home/ivank/Projects/Twisted/twisted/scripts/trial.py", line 363, in run
    test_result = trialRunner.run(suite)
  File "/home/ivank/Projects/Twisted/twisted/trial/runner.py", line 835, in run
    return self._runWithoutDecoration(test)
  File "/home/ivank/Projects/Twisted/twisted/trial/runner.py", line 864, in _runWithoutDecoration
    run()
  File "/home/ivank/Projects/Twisted/twisted/trial/runner.py", line 859, in <lambda>
    run = lambda: suite.run(result)
  File "/home/ivank/Projects/Twisted/twisted/trial/runner.py", line 298, in run
    TestSuite.run(self, result)
  File "/home/ivank/Projects/Twisted/twisted/trial/unittest.py", line 1390, in run
    test(result)
  File "/home/ivank/Projects/Twisted/twisted/trial/unittest.py", line 1378, in __call__
    return self.run(result)
  File "/home/ivank/Projects/Twisted/twisted/trial/runner.py", line 174, in run
    super(LoggedSuite, self).run(result)
  File "/home/ivank/Projects/Twisted/twisted/trial/unittest.py", line 1390, in run
    test(result)
  File "/home/ivank/Projects/Twisted/twisted/trial/unittest.py", line 1378, in __call__
    return self.run(result)
  File "/home/ivank/Projects/Twisted/twisted/trial/runner.py", line 147, in run
    test(result)
  File "/home/ivank/Projects/Twisted/twisted/trial/unittest.py", line 1378, in __call__
    return self.run(result)
  File "/home/ivank/Projects/Twisted/twisted/trial/runner.py", line 147, in run
    test(result)
  File "/home/ivank/Projects/Twisted/twisted/trial/unittest.py", line 1378, in __call__
    return self.run(result)
  File "/home/ivank/Projects/Twisted/twisted/trial/runner.py", line 147, in run
    test(result)
  File "/home/ivank/Projects/Twisted/twisted/trial/unittest.py", line 1378, in __call__
    return self.run(result)
  File "/home/ivank/Projects/Twisted/twisted/trial/runner.py", line 147, in run
    test(result)
  File "/home/ivank/Projects/Twisted/twisted/trial/unittest.py", line 745, in __call__
    return self.run(*args, **kwargs)
  File "/home/ivank/Projects/Twisted/twisted/trial/unittest.py", line 1103, in run
    _collectWarnings(self._warnings.append, runThunk)
  File "/home/ivank/Projects/Twisted/twisted/trial/unittest.py", line 196, in _collectWarnings
    result = f(*args, **kwargs)
  File "/home/ivank/Projects/Twisted/twisted/trial/unittest.py", line 1095, in runThunk
    self._wait(d)
  File "/home/ivank/Projects/Twisted/twisted/trial/unittest.py", line 1246, in _wait
    reactor.run()
  File "/home/ivank/Projects/Twisted/twisted/internet/gtkreactor.py", line 205, in run
    self.simulate()
  File "/home/ivank/Projects/Twisted/twisted/internet/gtkreactor.py", line 219, in simulate
    self._simtag = gtk.timeout_add((timeout * 1010), self.simulate)
AttributeError: StubGTK instance has no attribute 'timeout_add'
```

Attachments:

* [4476-01-really-assert-reactor-already-installed.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/2bc/2bcefe2ed09fa35dc6bf22d590be971ac69647aa/f893a461c1b8185279f13abacd79afa4dcf5280d.patch) (621 bytes) - added by ivank on 2010-05-31 23:11:01Z - terrible patch that makes tests pass
* [4476-02-block-installation-of-reactor-when-pythono.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/2bc/2bcefe2ed09fa35dc6bf22d590be971ac69647aa/4c8213444d3273af245bb50ab2d3e2ebfd5e1319.patch) (3173 bytes) - added by ivank on 2010-06-03 02:57:36Z - 
* [4476-03-block-installation-of-reactor-when-pythono.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/2bc/2bcefe2ed09fa35dc6bf22d590be971ac69647aa/35753b4000f01fbe5ab8802509ca703a1937b879.patch) (3232 bytes) - added by ivank on 2010-06-03 03:05:00Z - adjust test-case-name for main.py
* [4476-04-block-installation-of-reactor-when-pythono.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/2bc/2bcefe2ed09fa35dc6bf22d590be971ac69647aa/68b11d39bc2510191c38ce6df6988a79d2009bdb.patch) (3226 bytes) - added by ivank on 2010-06-03 04:48:17Z - don't use has_key
* [4476-05-block-installation-of-reactor-when-pythono.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/2bc/2bcefe2ed09fa35dc6bf22d590be971ac69647aa/9bb62ac4a30bbe0c08ce1a2d92b5baa0a1dcdefe.patch) (3224 bytes) - added by ivank on 2010-06-03 05:16:52Z - fix vertical whitespace: 2 lines instead of 3 lines between methods

<details><summary>Searchable metadata</summary>

```
trac-id__4476 4476
type__release_blocker__regression release blocker: regression
reporter__ivank ivank
priority__normal normal
milestone__ 
branch__branches_let_tests_run_under_python_O_4476 branches/let-tests-run-under-python-O-4476
branch_author__ivank__screwtape ivank, screwtape
status__closed closed
resolution__fixed fixed
component__core core
keywords__pythono pythono
time__1275346349000000 1275346349000000
changetime__1281986159000000 1281986159000000
version__None None
owner__Screwtape Screwtape
cc__fijal cc__amaury cc__ivank
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="ivank's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_1"></a>|ivank commented|
|-|-|

Maybe the `installReactor` `assert` should be a separate bug. It seems like a very important assert that should never be stripped out.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_2"></a>|@exarkun commented|
|-|-|

Do you have any idea why behavior changes when the assert isn't there?

**Comment by twisted-trac** [comment]
|<img alt="ivank's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_3"></a>|ivank commented|
|-|-|

test_gtkreactor has tests that try to install gtkreactor, after stubbing out modules `gtk` and `pygtk`. It expects the install() to fail, because a reactor is already installed. It's really just doing it to check for a DeprecationWarning, I think. If the `assert` in twisted.internet.main is stripped out, test_gtkreactor successfully installs the stub reactor, which promptly causes `trial` to die.

**Comment by twisted-trac** [comment]
|<img alt="ivank's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_4"></a>|ivank commented|
|-|-|

The more serious problem is that `installReactor(...)` does not raise an error if a reactor is already installed (only for `python -O`):

```
# /usr/bin/python -O 
Python 2.6.5 (r265:79063, Apr 16 2010, 13:57:41) 
[GCC 4.4.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from twisted.internet import reactor
>>> from twisted.internet import epollreactor
>>> epollreactor.install()
>>> 
```

**Comment by twisted-trac** [comment]
|<img alt="ivank's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_5"></a>|ivank removed owner|
|-|-|

Please review 4476-02...patch. It solves the originally reported test_gtkreactor problem as well, because an AssertionError is raised even with python -O.

**Comment by twisted-trac** [comment]
|[<img alt="fijal's avatar" src="https://avatars.githubusercontent.com/u/85944?s=50" width="50" height="50">](https://github.com/fijal)<a name="note_6"></a>|@fijal commented|
|-|-|

has_key is deprecated, use in (or will be deprecated).

**Comment by twisted-trac** [comment]
|[<img alt="fijal's avatar" src="https://avatars.githubusercontent.com/u/85944?s=50" width="50" height="50">](https://github.com/fijal)<a name="note_7"></a>|@fijal commented|
|-|-|

Another issue - how about not subclassing AssertionError (since you have already introduced new error), but instead catch correct error in pygtk tests?

**Comment by twisted-trac** [comment]
|<img alt="ivank's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_9"></a>|ivank commented|
|-|-|

I suspect there may be code out there that catches `AssertionError`, which is why I made the error a subclass of `AssertionError`.

Specifically, some people might have code that wraps the `install()` with a `try`/`except AssertionError`.
```
>>> from twisted.internet import reactor
>>> from twisted.internet import pollreactor
>>> pollreactor.install()
```

**Comment by twisted-trac** [comment]
|<img alt="ivank's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_10"></a>|ivank commented|
|-|-|

I'm happy to change it from AssertionError if there's a good reason to. Regardless of that, should I change test_gtkreactor to check for `ReactorAlreadyInstalledError` instead of `AssertionError`?

**Comment by twisted-trac** [comment]
|<img alt="TimAllen's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|TimAllen set owner to TimAllen|
|-|-|

**Comment by twisted-trac** [comment]
|<img alt="TimAllen's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_12"></a>|TimAllen set owner to ivank|
|-|-|

Raising something besides `AssertionError` would be against the compatibility policy, I think, so I vote for what you have now.

This looks good, and should be applied, but it doesn't solve all the problems with running the test suite under "python -O". On my system (Fedora Core 6, Python 2.4):
 * `twisted.conch.test.test_telnet.TelnetTransportTestCase.testAcceptedEnableRequest`
 * `twisted.conch.test.test_telnet.TelnetTransportTestCase.testNegotiationBlocksFurtherNegotiation`
 * `twisted.test.test_dirdbm.DirDbmTestCase.test_nonStringKeys`
 * `twisted.test.test_dirdbm.ShelfTestCase.test_nonStringKeys`
 * `twisted.web2.test.test_client.TestHTTPClient.test_prematurePipelining`
 * `twisted.test.test_plugin.DeveloperSetupTests.test_freshPyReplacesStalePyc`

Some of these are because assertions are disabled (for example, `test_prematurePipelining` dies with "AssertionError not raised (<Deferred at 0xa19af8c> returned)"), while at least one is because Python writes `.pyo` files rather than `.pyc` files.

Judging from the summary, these should probably also be fixed before this bug is closed — or at least there should be new tickets filed for them.

**Comment by twisted-trac** [comment]
|<img alt="ivank's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_13"></a>|ivank commented|
|-|-|

Thanks for the review. I did not mean to imply that the test suite completely passes with `python -O` with this fix. However, with the fix, it does run all of the tests, instead of crashing with that traceback above.

I personally like the idea of having the test suite completely pass with `python -O` (and even `-OO`), but I don't want to file a bunch of tickets unless there's some agreement that it matters.

**Comment by twisted-trac** [comment]
|<img alt="ivank's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_14"></a>|ivank commented|
|-|-|

I don't have commit access to put this in a branch.

**Comment by twisted-trac** [comment]
|<img alt="screwtape's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_15"></a>|screwtape commented|
|-|-|

(In [29770]) Create branch let-tests-run-under-python-O-4476

**Comment by twisted-trac** [comment]
|<img alt="screwtape's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_16"></a>|screwtape commented|
|-|-|

(In [29771]) Apply 4476-05-block-installation-of-reactor-when-pythono.patch

refs [#4476](https://github.com/twisted/twisted/issues/4476)

**Comment by twisted-trac** [comment]
|<img alt="Screwtape's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_17"></a>|Screwtape commented|
|-|-|

So, I used exarkun's `force-builds.py` script to make the buildbots all build this branch before I merged it, but [three](http://buildbot.twistedmatrix.com/builders/winxp32-py2.5-select/builds/227) [build](http://buildbot.twistedmatrix.com/builders/winxp32-py2.6-select/builds/621) [machines](http://buildbot.twistedmatrix.com/builders/hardy32-py2.5-glib2/builds/256) failed tests. All the failed tests look unrelated to the changes in the branch, and one of them is explicitly named `RaceConditionTestCase` so they may be known-intermittent failures, but I don't feel comfortable merging this until I know more.

**Comment by twisted-trac** [comment]
|<img alt="Screwtape's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_18"></a>|Screwtape commented|
|-|-|

From IRC:
```
11:01 < exarkun> Screwtape: You can compare against trunk results
11:01 < exarkun> Two Windows builders have a known issue with testManyProcesses
11:01 < exarkun> twisted.test.test_process.ClosingPipes.test_stdout
11:01 < exarkun> is also a known issue
```

So, I guess this is safe to merge after all.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_19"></a>|@exarkun commented|
|-|-|

`ReactorAlreadyInstalledError` probably belongs in `twisted.internet.error`

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_20"></a>|@glyph commented|
|-|-|

Replying to [Screwtape](#note_17):
> So, I used exarkun's `force-builds.py` script to make the buildbots all build this branch before I merged it,

That script outputs a link when you run it; it is helpful to include in a ticket.  The convention is to simply use the words "build results" as the link text, [like so](http://twistedmatrix.com/trac/ticket/4421#comment:5).

> but [three](http://buildbot.twistedmatrix.com/builders/winxp32-py2.5-select/builds/227) [build](http://buildbot.twistedmatrix.com/builders/winxp32-py2.6-select/builds/621) [machines](http://buildbot.twistedmatrix.com/builders/hardy32-py2.5-glib2/builds/256) failed tests.

Minor nit: the usual terminology here is "three builders", not "three build machines", since many builders run on the same "machines" as other builders, be it physical or virtual.

> All the failed tests look unrelated to the changes in the branch, and one of them is explicitly named `RaceConditionTestCase` so they may be known-intermittent failures, but I don't feel comfortable merging this until I know more.

Look for previous builders which have failed, on trunk, in the same way (in revisions which haven't been reverted).  If the builders aren't too busy  These particular failures look like failures which I've seen before.

**Comment by twisted-trac** [comment]
|<img alt="Screwtape's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_21"></a>|Screwtape removed owner|
|-|-|

Replying to [exarkun](#note_19):
> `ReactorAlreadyInstalledError` probably belongs in `twisted.internet.error`

Done.

Putting this back into the review queue, just in case there's any last requests.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_22"></a>|@exarkun set owner to Screwtape|
|-|-|

Looks great now, please merge.

**Comment by twisted-trac** [comment]
|<img alt="screwtape's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_23"></a>|screwtape set status to `closed`|
|-|-|

(In [29905]) Merge let-tests-run-under-python-O-4476: installReactor() does not use assert.

Authors: ivank, screwtape
Reviewers: screwtape, exarkun
Fixes: [#4476](https://github.com/twisted/twisted/issues/4476)

twisted.internet.main.installReactor() used to "assert" that no previous
reactor was installed, but "assert" statements are compiled out when
Python runs with the "-O" parameter, which enabled Twisted's test suite
to try installing multiple reactors with no happy result.

Now installReactor() uses an ordinary "if" statement instead of
"assert", and Trial no longer crashes when running the Twisted test
suite in "python -O" mode.

**Comment by twisted-trac** [comment]
|<img alt="amaury's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_24"></a>|amaury set status to `reopened`|
|-|-|

The change [29905] looks incorrect: `ReactorAlreadyInstalledError` was added to `__all__`, but not in the correct module. I suppose that `from twisted.internet.main import *` will now fail.

**Comment by twisted-trac** [comment]
|<img alt="ivank's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_25"></a>|ivank set status to `closed`|
|-|-|

`from twisted.internet.main import *` still works (at least in Python 2.7, does it break in older versions?).  Twisted has problems in various `__all__`s, so unless there's a regression, this doesn't need to be reverted.  I filed [#4636](https://github.com/twisted/twisted/issues/4636) for the `__all__` problem.
