### ISSUE TITLE
Cannot connect listings/pb/chatclient.py to listings/pb/chatserver.py more than once

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#4488]
|<img alt="ivank's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| ivank reported|
|-|-|
|Trac ID|trac#4488|
|Type|defect|
|Created|2010-06-04 19:42:09Z|

The first time the client connects, things seem to work. The second time, the server calls `callRemote` on a `None`.

```
# python doc/core/howto/listings/pb/chatserver.py
Unhandled error in Deferred:
Traceback (most recent call last):
Failure: twisted.spread.pb.PBConnectionLost: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-clean fashion.
]
........ second client: .........
Peer will receive following PB traceback:
Traceback (most recent call last):
  File "/opt/Python-x86/lib/python2.7/site-packages/twisted/spread/banana.py", line 155, in gotItem
    self.callExpressionReceived(item)
  File "/opt/Python-x86/lib/python2.7/site-packages/twisted/spread/banana.py", line 118, in callExpressionReceived
    self.expressionReceived(obj)
  File "/opt/Python-x86/lib/python2.7/site-packages/twisted/spread/pb.py", line 513, in expressionReceived
    method(*sexp[1:])
  File "/opt/Python-x86/lib/python2.7/site-packages/twisted/spread/pb.py", line 825, in proto_message
    self._recvMessage(self.localObjectForID, requestID, objectID, message, answerRequired, netArgs, netKw)
--- <exception caught here> ---
  File "/opt/Python-x86/lib/python2.7/site-packages/twisted/spread/pb.py", line 839, in _recvMessage
    netResult = object.remoteMessageReceived(self, message, netArgs, netKw)
  File "/opt/Python-x86/lib/python2.7/site-packages/twisted/spread/flavors.py", line 213, in remoteMessageReceived
    state = apply(method, (self.perspective,)+args, kw)
  File "doc/core/howto/listings/pb/chatserver.py", line 54, in view_send
    user.send("<%s> says: %s" % (from_user.name, message))
  File "doc/core/howto/listings/pb/chatserver.py", line 41, in send
    self.remote.callRemote("print", message)
exceptions.AttributeError: 'NoneType' object has no attribute 'callRemote'
```

<details><summary>Searchable metadata</summary>

```
trac-id__4488 4488
type__defect defect
reporter__ivank ivank
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__ 
time__1275680529000000 1275680529000000
changetime__1275680529000000 1275680529000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
