### ISSUE TITLE
test_cftp fails in non-English locale

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#4588]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)| @jml reported|
|-|-|
|Trac ID|trac#4588|
|Type|defect|
|Created|2010-07-15 10:00:46Z|

On a system with, say, a French language pack installed (`sudo apt-get install language-pack-fr` on Ubuntu), run the following command:

`LANG=fr_FR.utf8 ./bin/trial --reactor=gtk2 --reporter=subunit twisted.conch.test.test_cftp`

The following tests will fail, all with roughly the same error:

```
twisted.conch.test.test_cftp.ListingTests.test_newFile
twisted.conch.test.test_cftp.ListingTests.test_newSingleDigitDayOfMonth
twisted.conch.test.test_cftp.ListingTests.test_oldFile
twisted.conch.test.test_cftp.ListingTests.test_oldSingleDigitDayOfMonth
```

Here's one of the errors:

```
======================================================================
FAIL: twisted.conch.test.test_cftp.ListingTests.test_oldSingleDigitDayOfMonth
----------------------------------------------------------------------
_StringException: Text attachment: traceback
------------
Traceback (most recent call last):
  File "/home/jml/src/Twisted/trunk/twisted/internet/defer.py", line 125, in maybeDeferred
    result = f(*args, **kw)
  File "/home/jml/src/Twisted/trunk/twisted/internet/utils.py", line 191, in runWithWarningsSuppressed
    result = f(*a, **kw)
  File "/home/jml/src/Twisted/trunk/twisted/conch/test/test_cftp.py", line 122, in test_oldSingleDigitDayOfMonth
    '!---------    0 0        0               0 May 01  1973 foo')
  File "/home/jml/src/Twisted/trunk/twisted/trial/unittest.py", line 287, in failUnlessEqual
    % (msg, pformat(first), pformat(second)))
FailTest: not equal:
a = '!---------    0 0        0               0 mai 01  1973 foo'
b = '!---------    0 0        0               0 May 01  1973 foo'

------------


----------------------------------------------------------------------
```

<details><summary>Searchable metadata</summary>

```
trac-id__4588 4588
type__defect defect
reporter__jml jml
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__worksforme worksforme
component__conch conch
keywords__locale locale
time__1279188046000000 1279188046000000
changetime__1511496952987754 1511496952987754
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_3"></a>|@rodrigc set status to `closed`|
|-|-|

Cannot reproduce the problem with Twisted 17.9.0 and Ubuntu 14.04
