### ISSUE TITLE
Crash during one too many callbacks??

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#4599]
|<img alt="kvdb's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| kvdb reported|
|-|-|
|Trac ID|trac#525|
|Type|defect|
|Created|2004-02-25 02:50:06Z|

<details><summary>Searchable metadata</summary>

```
trac-id__525 525
type__defect defect
reporter__kvdb kvdb
priority__high high
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__ 
keywords__ 
time__1077677406000000 1077677406000000
changetime__1078136890000000 1078136890000000
version__ 
owner__ 
cc__itamarst cc__kvdb
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="kvdb's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|kvdb commented|
|-|-|

```
#!html
<pre>
Using python 2.3, twisted 1.2.0rc2 (but same misbehaviour in python 2.2 with the
stable twisted)

Assigned several callbacks.
One works fine. But assigning a new callback while actually being in a called
back procedure messes things up.
Not sure this is what actually going on, but I since I saw 'not implemented' in
the traceback. I hope it's not my fault and tried filing it as a bug.
Why is this stuff so difficult?! :-(

Traceback (most recent call last):
  File "/usr/lib/python2.3/site-packages/twisted/internet/default.py", line 133,
in mainLoop
    self.runUntilCurrent()
  File "/usr/lib/python2.3/site-packages/twisted/internet/base.py", line 420, in
runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/usr/lib/python2.3/site-packages/twisted/internet/base.py", line 325, in
_continueSystemEvent
    callable(*args, **kw)
  File "/usr/lib/python2.3/site-packages/twisted/internet/base.py", line 286, in
disconnectAll
    failure.Failure(main.CONNECTION_LOST))
--- &lt;exception caught here> ---
  File "/usr/lib/python2.3/site-packages/twisted/python/log.py", line 65, in
callWithLogger
    callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/lib/python2.3/site-packages/twisted/python/log.py", line 52, in
callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/lib/python2.3/site-packages/twisted/python/context.py", line 32, in
callWithContext
    return func(*args,**kw)
  File "/usr/lib/python2.3/site-packages/twisted/internet/tcp.py", line 443, in
connectionLost
    self.connector.connectionLost(reason)
  File "/usr/lib/python2.3/site-packages/twisted/internet/base.py", line 591, in
connectionLost
    self.factory.clientConnectionLost(self, reason)
  File "/usr/lib/python2.3/site-packages/twisted/web/xmlrpc.py", line 307, in
clientConnectionLost
    self.deferred.errback(reason)
  File "/usr/lib/python2.3/site-packages/twisted/internet/defer.py", line 249,
in errback
    self._startRunCallbacks(fail)
  File "/usr/lib/python2.3/site-packages/twisted/internet/defer.py", line 274,
in _startRunCallbacks
    raise AlreadyCalledError
twisted.internet.defer.AlreadyCalledError:
Traceback (most recent call last):
  File "/usr/lib/python2.3/site-packages/twisted/internet/default.py", line 523,
in doSelect
    _logrun(selectable, _drdw, selectable, method, dict)
  File "/usr/lib/python2.3/site-packages/twisted/python/log.py", line 65, in
callWithLogger
    callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/lib/python2.3/site-packages/twisted/python/log.py", line 52, in
callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/lib/python2.3/site-packages/twisted/python/context.py", line 32, in
callWithContext
    return func(*args,**kw)
--- &lt;exception caught here> ---
  File "/usr/lib/python2.3/site-packages/twisted/internet/default.py", line 536,
in _doReadOrWrite
    elif handfn() == -1:
  File "/usr/lib/python2.3/site-packages/twisted/internet/abstract.py", line
277, in fileno
    raise NotImplementedError(reflect.qual(self.__class__)+' has no fileno method')
exceptions.NotImplementedError: twisted.internet.tcp.Client has no fileno method
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="radix's avatar" src="https://avatars.githubusercontent.com/u/227068?s=50" width="50" height="50">](https://github.com/radix)|@radix commented|
|-|-|

```
#!html
<pre>
I don't think this has anything to do with Deferreds. Itamar, can you look at
this? It's something low-level in twisted.internet :)
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)|@itamarst commented|
|-|-|

```
#!html
<pre>
Yeesh. I'd like to see the code you're discussing, please.
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun commented|
|-|-|

```
#!html
<pre>
abstract.FileDescriptor.fileno() has been changed to return -1 instead of
raising NotImplementedError
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
