### ISSUE TITLE
Change FileDescriptor.fileno to raise an exception instead of returning -1

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#4605]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#4605|
|Type|task|
|Created|2010-07-19 23:04:01Z|

Presumably `FileDescriptor.fileno` was written this way because Python sockets used to return `-1` when they were closed.  They don't anymore, though, and exceptions are a better way to signal an error anyway.

<details><summary>Searchable metadata</summary>

```
trac-id__4605 4605
type__task task
reporter__exarkun exarkun
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__ 
time__1279580641000000 1279580641000000
changetime__1279600992000000 1279600992000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_1"></a>|@glyph commented|
|-|-|

I have some vague memories of this being a performance issue, as well - raising exceptions is expensive, and I remember some early benchmarks showing connection-closing as a hotspot if you have to raise an exception in order to close a connection it's bad.  However, I _think_ that if [#4539](https://github.com/twisted/twisted/issues/4539) were fixed, it probably wouldn't matter, since really you should never be calling `fileno` on a bad file descriptor anyway.

This ticket should also have some kind of reference to [#2825](https://github.com/twisted/twisted/issues/2825), although I'm not sure what the relationship is there.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|

**Comment by adiroiban** [comment]
I tried my luck at fixing this via https://github.com/twisted/twisted/pull/12720

Commits:

* https://github.com/twisted/twisted/pull/12720/commits/ac1749926e98f90359b541ae856e9b5a319e3f73
* https://github.com/twisted/twisted/pull/12720/commits/f668782eb9f727f6b58fdba4f0fd9dd9f58eb382

It looks like some tests are failing... we might need to change the reactors to handle the exception instead of -1

```
===============================================================================
Error: 
Traceback (most recent call last):
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/internet/test/test_posixbase.py", line 313, in test_connectionFailedDoesntCallLoseConnection
    port.connectionFailed("goodbye")
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/internet/unix.py", line 639, in connectionFailed
    self.stopListening()
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/internet/udp.py", line 358, in stopListening
    self._loseConnection()
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/internet/udp.py", line 349, in _loseConnection
    self.stopReading()
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/internet/abstract.py", line 445, in stopReading
    self.reactor.removeReader(self)
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/internet/epollreactor.py", line 178, in removeReader
    self._remove(
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/internet/epollreactor.py", line 153, in _remove
    fd = xer.fileno()
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/internet/abstract.py", line 503, in fileno
    raise UnsupportedOperation("FileDescriptor.fileno not implemented.")
io.UnsupportedOperation: FileDescriptor.fileno not implemented.

twisted.internet.test.test_posixbase.ConnectedDatagramPortTests.test_connectionFailedDoesntCallLoseConnection
===============================================================================
Error: 
Traceback (most recent call last):
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/internet/test/test_posixbase.py", line 144, in test_connectionLostFailed
    return self.assertFailure(port.stopListening(), ZeroDivisionError)
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/internet/tcp.py", line 1473, in loseConnection
    self.stopReading()
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/internet/abstract.py", line 445, in stopReading
    self.reactor.removeReader(self)
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/internet/epollreactor.py", line 178, in removeReader
    self._remove(
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/internet/epollreactor.py", line 153, in _remove
    fd = xer.fileno()
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/internet/abstract.py", line 503, in fileno
    raise UnsupportedOperation("FileDescriptor.fileno not implemented.")
io.UnsupportedOperation: FileDescriptor.fileno not implemented.

twisted.internet.test.test_posixbase.TCPPortTests.test_connectionLostFailed
===============================================================================
Error: 
Traceback (most recent call last):
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/trial/_synctest.py", line 1450, in _runCleanups
    f(*args, **kwargs)
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/internet/tcp.py", line 1473, in loseConnection
    self.stopReading()
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/internet/abstract.py", line 445, in stopReading
    self.reactor.removeReader(self)
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/internet/epollreactor.py", line 178, in removeReader
    self._remove(
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/internet/epollreactor.py", line 153, in _remove
    fd = xer.fileno()
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/internet/abstract.py", line 503, in fileno
    raise UnsupportedOperation("FileDescriptor.fileno not implemented.")
io.UnsupportedOperation: FileDescriptor.fileno not implemented.

twisted.internet.test.test_tls.SSLClientTestsMixin_EPollReactorTests.test_disconnectAfterWriteAfterStartTLS
===============================================================================
Error: 
Traceback (most recent call last):
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/trial/_asynctest.py", line 221, in _deferRunCleanups
    yield self._run(
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/internet/defer.py", line 205, in maybeDeferred
    result = f(*args, **kwargs)
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/internet/utils.py", line 227, in runWithWarningsSuppressed
    raise exc_info[1].with_traceback(exc_info[2])
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/internet/utils.py", line 223, in runWithWarningsSuppressed
    result = f(*a, **kw)
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/trial/_asynctest.py", line 222, in <lambda>
    lambda: func(*args, **kwargs),
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/internet/tcp.py", line 1473, in loseConnection
    self.stopReading()
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/internet/abstract.py", line 445, in stopReading
    self.reactor.removeReader(self)
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/internet/epollreactor.py", line 178, in removeReader
    self._remove(
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/internet/epollreactor.py", line 153, in _remove
    fd = xer.fileno()
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/internet/abstract.py", line 503, in fileno
    raise UnsupportedOperation("FileDescriptor.fileno not implemented.")
io.UnsupportedOperation: FileDescriptor.fileno not implemented.

twisted.test.test_tcp.FactoryTests.test_serverStartStop
===============================================================================
Error: 
Traceback (most recent call last):
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/trial/_asynctest.py", line 202, in _deferTearDown
    await self._run(self.tearDown, "tearDown", result)
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/internet/defer.py", line 1185, in __iter__
    result.raiseException()
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/python/failure.py", line 455, in raiseException
    raise self.value.with_traceback(self.tb)
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/internet/defer.py", line 205, in maybeDeferred
    result = f(*args, **kwargs)
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/internet/tcp.py", line 1473, in loseConnection
    self.stopReading()
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/internet/abstract.py", line 445, in stopReading
    self.reactor.removeReader(self)
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/internet/epollreactor.py", line 178, in removeReader
    self._remove(
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/internet/epollreactor.py", line 153, in _remove
    fd = xer.fileno()
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/internet/abstract.py", line 503, in fileno
    raise UnsupportedOperation("FileDescriptor.fileno not implemented.")
io.UnsupportedOperation: FileDescriptor.fileno not implemented.

twisted.test.test_tcp.HalfCloseTests.testCloseWriteCloser
twisted.test.test_tcp.HalfCloseTests.testWriteCloseNotification
===============================================================================
Error: 
Traceback (most recent call last):
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/trial/_asynctest.py", line 202, in _deferTearDown
    await self._run(self.tearDown, "tearDown", result)
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/internet/defer.py", line 1185, in __iter__
    result.raiseException()
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/python/failure.py", line 455, in raiseException
    raise self.value.with_traceback(self.tb)
twisted.internet.defer.FirstError: FirstError[#0, [Failure instance: Traceback: <class 'io.UnsupportedOperation'>: FileDescriptor.fileno not implemented.
/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/internet/defer.py:205:maybeDeferred
/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/internet/tcp.py:1473:loseConnection
/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/internet/abstract.py:445:stopReading
/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/internet/epollreactor.py:178:removeReader
/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/internet/epollreactor.py:153:_remove
/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/internet/abstract.py:503:fileno
]]

twisted.test.test_tcp_internals.SelectReactorTests.test_acceptScaling
===============================================================================
Error: 
Traceback (most recent call last):
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/trial/_asynctest.py", line 202, in _deferTearDown
    await self._run(self.tearDown, "tearDown", result)
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/internet/defer.py", line 1185, in __iter__
    result.raiseException()
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/python/failure.py", line 455, in raiseException
    raise self.value.with_traceback(self.tb)
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/internet/defer.py", line 205, in maybeDeferred
    result = f(*args, **kwargs)
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/internet/utils.py", line 227, in runWithWarningsSuppressed
    raise exc_info[1].with_traceback(exc_info[2])
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/internet/utils.py", line 223, in runWithWarningsSuppressed
    result = f(*a, **kw)
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/test/test_udp.py", line 576, in tearDown
    return self.port.stopListening()
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/internet/udp.py", line 358, in stopListening
    self._loseConnection()
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/internet/udp.py", line 349, in _loseConnection
    self.stopReading()
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/internet/abstract.py", line 445, in stopReading
    self.reactor.removeReader(self)
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/internet/epollreactor.py", line 178, in removeReader
    self._remove(
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/internet/epollreactor.py", line 153, in _remove
    fd = xer.fileno()
  File "/home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/lib/python3.12/site-packages/twisted/internet/abstract.py", line 503, in fileno
    raise UnsupportedOperation("FileDescriptor.fileno not implemented.")
io.UnsupportedOperation: FileDescriptor.fileno not implemented.

twisted.test.test_udp.ReactorShutdownInteractionTests.testShutdownFromDatagramReceived
-------------------------------------------------------------------------------
Ran 11501 tests in 199.615s

FAILED (skips=492, errors=8, successes=11002)
```

**Comment by adiroiban** [comment]
I now see that the interface documents to  return  -1 on errors ... so I don't know

Maybe for Twisted we don't have to comply with stdlib interface

https://github.com/twisted/twisted/blob/cf2a7efdd9e5b5d109a705426e06e30249f97a65/src/twisted/internet/interfaces.py#L1655-L1667

**Comment by glyph** [comment]
> I now see that the interface documents to return -1 on errors ... so I don't know

> Maybe for Twisted we don't have to comply with stdlib interface

I think that we do, since we are interposing into the place where other code is interacting with us *as if* we are a stdlib object.  This documentation is (inaccurately) attempting to describe what the stdlib does, rather than laying out a new interface.  (I think that maybe the stdlib did this in, like, python 1.5.2?)

**Comment by adiroiban** [comment]
Thanks for the feedback. I will try to get the fix for the logging part merged and then I will try to work on this one
