### ISSUE TITLE
Trial produces useless warning tracebacks with -Werror

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#4606]
|[<img alt="mithrandi's avatar" src="https://avatars.githubusercontent.com/u/856430?s=50" width="50" height="50">](https://github.com/mithrandi)| @mithrandi reported|
|-|-|
|Trac ID|trac#4606|
|Type|defect|
|Created|2010-07-20 18:03:25Z|

For example:

```
mithrandi@lorien:~> python -Werror::DeprecationWarning ~/code/Twisted/trunk/bin/trial axiom
[...snip...]
[ERROR]
Traceback (most recent call last):
  File "/home/mithrandi/code/Twisted/trunk/twisted/trial/unittest.py", line 1109, in run
    warnings.warn_explicit(**w)
exceptions.DeprecationWarning: the md5 module is deprecated; use hashlib instead

axiom.test.test_axiomatic.StartTests.test_checkSystemVersion
```

<details><summary>Searchable metadata</summary>

```
trac-id__4606 4606
type__defect defect
reporter__mithrandi mithrandi
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__trial trial
keywords__ 
time__1279649005000000 1279649005000000
changetime__1446642904278775 1446642904278775
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_2"></a>|@adiroiban set status to `closed`|
|-|-|

I think that this was fixed in latest trial changes

I can run the test and I get nice reporting error.

```
$ python -Werror::DeprecationWarning ./bin/trial twisted.conch.test.test_keys

  ObjectTypeTests
    test_deprecation ...                                                   [OK]
    test_objectKey_none ...                                                [OK]
                                            [ERROR]
    test_objectType_dsa ...                                                [OK]
                                            [ERROR]
    test_objectType_rsa ...                                                [OK]
                                            [ERROR]



===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/home/adi/chevah/twisted/twisted/trial/_synctest.py", line 1030, in run
    warnings.warn_explicit(**w)
exceptions.DeprecationWarning: twisted.conch.ssh.keys.objectType was deprecated in Twisted 15.5.0

twisted.conch.test.test_keys.ObjectTypeTests.test_objectKey_none
twisted.conch.test.test_keys.ObjectTypeTests.test_objectType_dsa
twisted.conch.test.test_keys.ObjectTypeTests.test_objectType_rsa
-------------------------------------------------------------------------------
Ran 31 tests in 1.757s

FAILED (errors=3, successes=31)

```
