### ISSUE TITLE
t.i.task.deferLater() doesn't work at all

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#4637]
|<img alt="atsuoi's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| atsuoi reported|
|-|-|
|Trac ID|trac#4637|
|Type|defect|
|Created|2010-08-20 09:57:17Z|

With Twisted 10.1.0, my application raise following error on shutdown.

```
Traceback (most recent call last):
  File "c:\python26\lib\site-packages\twisted\internet\base.py", line 818, in runUntilCurrent
    self.fireSystemEvent("shutdown")
  File "c:\python26\lib\site-packages\twisted\internet\base.py", line 628, in fireSystemEvent
    event.fireEvent()
  File "c:\python26\lib\site-packages\twisted\internet\base.py", line 407, in fireEvent
    result = callable(*args, **kwargs)
  File "c:\python26\lib\site-packages\twisted\application\service.py", line 286, in stopService
    l.append(defer.maybeDeferred(service.stopService))
--- <exception caught here> ---
  File "c:\python26\lib\site-packages\twisted\internet\defer.py", line 106, in maybeDeferred
    result = f(*args, **kw)
  File "c:\python26\lib\site-packages\twisted\application\internet.py",line 100, in stopService
    d = self._port.stopListening()
  File "c:\python26\lib\site-packages\twisted\internet\tcp.py", line 966, in loseConnection
    self.reactor, 0, self.connectionLost, connDone)
  File "c:\python26\lib\site-packages\twisted\internet\task.py", line 737, in deferLater
    d = defer.Deferred(deferLaterCancel)
exceptions.TypeError: __init__() takes exactly 1 argument (2 given)
```

Calling t.i.task.deferLater() manually causes same error.

```
>>> from twisted.internet import task
>>> task.deferLater(None, None, None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\python26\lib\site-packages\twisted\internet\task.py", line 737, in deferLater
    d = defer.Deferred(deferLaterCancel)
TypeError: __init__() takes exactly 1 argument (2 given)
```

<details><summary>Searchable metadata</summary>

```
trac-id__4637 4637
type__defect defect
reporter__atsuoi atsuoi
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__invalid invalid
component__core core
keywords__ 
time__1282298237000000 1282298237000000
changetime__1282299332000000 1282299332000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_1"></a>|@therve commented|
|-|-|

Aren't you using a specific Deferred class? It definitely takes 2 arguments in 10.1.

**Comment by twisted-trac** [comment]
|<img alt="atsuoi's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_2"></a>|atsuoi commented|
|-|-|

I installed 10.1.0 with Windows Installer, but some files (including t.i.defer) were not updated from old installation. Now it works after I deleted old files and installed again.

Sorry for false alarm.

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)|@therve set status to `closed`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_4"></a>|@therve commented|
|-|-|

No problem, thanks for the update.

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_5"></a>|@therve commented|
|-|-|

There may be a problem with the installer, though.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
