### ISSUE TITLE
Convert libglade files to gtkbuilder files

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#4672]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)| @jml reported|
|-|-|
|Trac ID|trac#4672|
|Type|task|
|Created|2010-10-05 16:01:58Z|
|Branch|https://github.com/twisted/twisted/tree/glade-gtkbuilder-4672|

Gtk added support for gtkbuilder files in 2.12, deprecating the need for libglade.

We should probably bring our glade files up to date. Also see http://stackoverflow.com/questions/1412350/modifying-a-gui-started-with-glade.

```
$ find . -name '*glade'
./doc/core/examples/pbgtk2login.glade
./twisted/spread/ui/login2.glade
./twisted/words/im/instancemessenger.glade
./twisted/manhole/gladereactor.glade
./twisted/manhole/logview.glade
./twisted/manhole/inspectro.glade
./twisted/manhole/ui/gtk2manhole.glade
```

Attachments:

* [glade-gtkbuilder-4672.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/92d/92d2b60e49c89f127530350f2ba39326fd90c541/dd7509024dd0557fa285c0a2eeedb3844e245fb9.patch) (32661 bytes) - added by thijs on 2012-05-14 14:25:25Z - 

<details><summary>Searchable metadata</summary>

```
trac-id__4672 4672
type__task task
reporter__jml jml
priority__lowest lowest
milestone__ 
branch__branches_glade_gtkbuilder_4672 branches/glade-gtkbuilder-4672
branch_author__thijs thijs
status__new new
resolution__None None
component__core core
keywords__ 
time__1286294518000000 1286294518000000
changetime__1358303624000000 1358303624000000
version__None None
owner__thijs thijs
cc__thijs
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

Assigning a priority consistent with the explanation at http://www.micahcarrick.com/gtk-builder-libglade-faq.html

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_3"></a>|@thijstriemstra commented|
|-|-|

When trying to close the `doc/core/examples/pbgtk2.py` example it prints the following traceback:

```python
Traceback (most recent call last):
  File "doc/core/examples/pbgtk2.py", line 48, in on_loginDialog_response
    handlers.get(response)()
  File "doc/core/examples/pbgtk2.py", line 55, in cancelled
    self.deferredResult.errback()
  File "/home/thijs/workspaces/opensource/Twisted/trunk/twisted/internet/defer.py", line 393, in errback
    fail = failure.Failure(captureVars=self.debug)
  File "/home/thijs/workspaces/opensource/Twisted/trunk/twisted/python/failure.py", line 217, in __init__
    raise NoCurrentExceptionError()
twisted.python.failure.NoCurrentExceptionError
```

When I convert the glade file to a gtkbuilder file the traceback is the same so this means it's not related to the conversion. Not sure what goes wrong here, any pointers are appreciated. 

Attached patch adds the converted file and changes to the example. I suggest opening additional tickets for the other glade files to limit the scope of this ticket.

**Comment by twisted-trac** [comment]
|[<img alt="washort's avatar" src="https://avatars.githubusercontent.com/u/947487?s=50" width="50" height="50">](https://github.com/washort)<a name="note_5"></a>|@washort commented|
|-|-|

How is this patch related to the error you list there? Does it fix the problem?

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_6"></a>|@exarkun commented|
|-|-|

The error is an unrelated bug in the pbgtk2.py example.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_7"></a>|@exarkun set owner to @thijstriemstra|
|-|-|

Unfortunately the bulk of this patch no longer applies.  There's a big conflict in pbgtk2.py with the part of the code that actually switches to `Builder`.

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_8"></a>|@thijstriemstra commented|
|-|-|

(In [36829]) Branching to 'glade-gtkbuilder-4672'
