### ISSUE TITLE
POP3 doesn't accept empty password

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#4714]
|<img alt="jasondavies's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| jasondavies reported|
|-|-|
|Trac ID|trac#4714|
|Type|defect|
|Created|2010-10-26 08:28:25Z|

Simple patch to follow

Attachments:

* [pop3.py.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/691/691ac52d7d25e9a85833d730b2762a3d28328cef/9a1a58da292a043b0e9fbc345d49c6a0da36424e.patch) (472 bytes) - added by jasondavies on 2010-10-26 08:29:25Z - 
* [POP3_EmptyPassword-4714.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/691/691ac52d7d25e9a85833d730b2762a3d28328cef/defb21081f90e4453e0ebf9be81eb44b5e3435a3.patch) (1194 bytes) - added by argonemyth on 2012-07-03 12:12:25Z - 

<details><summary>Searchable metadata</summary>

```
trac-id__4714 4714
type__defect defect
reporter__jasondavies jasondavies
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__invalid invalid
component__mail mail
keywords__pop3 pop3
time__1288081705000000 1288081705000000
changetime__1341925077000000 1341925077000000
version__None None
owner__argonemyth argonemyth
cc__jesstess cc__argonemyth
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="mithrandi's avatar" src="https://avatars.githubusercontent.com/u/856430?s=50" width="50" height="50">](https://github.com/mithrandi)|@mithrandi removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|<img alt="jasondavies's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_2"></a>|jasondavies commented|
|-|-|

I forgot to attach the error trace:

```
2010-10-26 09:03:14+0100 [POP3Protocol,0,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/twisted/internet/tcp.py", line 463, in doRead
	    return self.protocol.dataReceived(data)
	  File "/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/twisted/protocols/basic.py", line 148, in dataReceived
	    self.lineReceived(line)
	  File "/Users/jason/src/seren/trunk/txmailserver/pop3.py", line 29, in lineReceived
	    pop3.POP3.lineReceived(self, line)
	  File "/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/twisted/mail/pop3.py", line 331, in lineReceived
	    getattr(self, 'state_' + self.state)(line)
	--- <exception caught here> ---
	  File "/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/twisted/mail/pop3.py", line 344, in state_COMMAND
	    return self.processCommand(*line.split(' '))
	  File "/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/twisted/mail/pop3.py", line 360, in processCommand
	    return f(*args)
	exceptions.TypeError: do_PASS() takes exactly 2 arguments (1 given)
	
2010-10-26 09:03:14+0100 [POP3Protocol,0,127.0.0.1] POP3 SERVER: -ERR bad protocol or server: TypeError: do_PASS() takes exactly 2 arguments (1 given)

```

**Comment by twisted-trac** [comment]
|[<img alt="jesstess's avatar" src="https://avatars.githubusercontent.com/u/188336?s=50" width="50" height="50">](https://github.com/jesstess)<a name="note_3"></a>|@jesstess set owner to jasondavies|
|-|-|

Thanks for the bug report and patch, jasondavies! Can you add a unit test for your change as part of this patch? Some documentation on Twisted's testing policy can be found [here](http://twistedmatrix.com/documents/current/core/development/policy/test-standard.html); I'm happy to help if you have any questions about writing the test.

Looking at [RFC 1939](http://www.faqs.org/rfcs/rfc1939.html) a bit, it looks like a password is a required argument to PASS (see section 7. Optional POP3 Commands):

```
PASS string

         Arguments:
             a server/mailbox-specific password (required)
...
         Possible Responses:
             +OK maildrop locked and ready
             -ERR invalid password
             -ERR unable to lock maildrop
```

suggesting that an -ERR invalid should be returned instead. Please let me know if I'm mistaken here.

**Comment by twisted-trac** [comment]
|[<img alt="argonemyth's avatar" src="https://avatars.githubusercontent.com/u/965739?s=50" width="50" height="50">](https://github.com/argonemyth)<a name="note_4"></a>|@argonemyth commented|
|-|-|

According to RFC 1939, the PASS command indeed needs a string. do_PASS() no longer throws the exception, but I added a simple check for empty password. I also modified _cbTestEmptyPASS in test_pop3.py to reflect the change in do_PASS function.

Please review patch POP3_EmptyPassword-4714.patch. Thanks!

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun set owner to @exarkun|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_6"></a>|@exarkun set owner to @argonemyth|
|-|-|

Thanks for picking this one up!  Just one comment on this one, I think:

 1. It's still illegal to send PASS before USER.  It would be better if the server kept sending "USER required before PASS", even in the empty password case.  Only if a USER command has been sent should the server check for an empty password.

Thanks again.

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_7"></a>|@therve commented|
|-|-|

AFAICT, the branch doesn't help with the bug reported, which is when the client sends "PASS\r\n", but maybe I miss something.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_8"></a>|@exarkun commented|
|-|-|

> AFAICT, the branch doesn't help with the bug reported, which is when the client sends "PASS\r\n", but maybe I miss something.

I think that's true, but I'm not sure I believe that's really a bug.  Actually, I can probably be convinced that there's no bug here at all.

As jesstess pointed out, the spec *requires* a password argument.  So "PASS\r\n" is illegal, and we can do what we want (including send back -ERR, which is what we do now.

For "PASS \r\n", we actually try to check to see if "" is a valid password for the account.  This seems like a bad password, so having the POP3 server reject its use seems fine.  On the other hand, lots of other strings are also bad passwords, and we make no attempt to handle those specially.

So, is this bug valid at all?

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_9"></a>|@exarkun set status to `closed`|
|-|-|

therve agreed with this reasoning on IRC.  This is a client bug, not a Twisted bug.  Thanks to everyone for their efforts on this.
