### ISSUE TITLE
Problem with pollreactor on FreeBSD 8.1 amd64 - doWrite called on a twisted.internet.tcp.Port

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#4759]
|<img alt="lewq's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| lewq reported|
|-|-|
|Trac ID|trac#4759|
|Type|defect|
|Created|2010-12-05 16:10:32Z|

The following exception appears after around 80,000 requests on my MySQL reverse proxy.

The only Twisted interfaces I'm using which involve file descriptors are reactor.listenTCP(3306, ...) and reactor.connectTCP.

After the exception is thrown, the reactor stops listening on port 3306. I can't see any reference to my code in the traceback, so I'm at a loss where to start looking for a fix.

It is difficult to reproduce, even running 200 simultaneous query processes won't break it reliably, but sometimes it just fails after running for a long time.

```
2010-12-04 23:31:34+0000 [AwesomeProxy.AwesomeProxyFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.6/site-packages/Twisted-10.1.0-py2.6-freebsd-8.1-RELEASE-amd64.egg/twisted/python/log.py", line 84, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/usr/local/lib/python2.6/site-packages/Twisted-10.1.0-py2.6-freebsd-8.1-RELEASE-amd64.egg/twisted/python/log.py", line 69, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/usr/local/lib/python2.6/site-packages/Twisted-10.1.0-py2.6-freebsd-8.1-RELEASE-amd64.egg/twisted/python/context.py", line 59, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/usr/local/lib/python2.6/site-packages/Twisted-10.1.0-py2.6-freebsd-8.1-RELEASE-amd64.egg/twisted/python/context.py", line 37, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.6/site-packages/Twisted-10.1.0-py2.6-freebsd-8.1-RELEASE-amd64.egg/twisted/internet/pollreactor.py", line 184, in _doReadOrWrite
	    why = selectable.doWrite()
	  File "/usr/local/lib/python2.6/site-packages/Twisted-10.1.0-py2.6-freebsd-8.1-RELEASE-amd64.egg/twisted/internet/base.py", line 1090, in doWrite
	    raise RuntimeError, "doWrite called on a %s" % reflect.qual(self.__class__)
	exceptions.RuntimeError: doWrite called on a twisted.internet.tcp.Port
```

I guess the question is, why does Twisted think a write event is happening on a listening socket?

```
    def _doReadOrWrite(self, selectable, fd, event):
        why = None
        inRead = False
        if event & POLL_DISCONNECTED and not (event & POLLIN):
            if fd in self._reads:
                why = main.CONNECTION_DONE
                inRead = True
            else:
                why = main.CONNECTION_LOST
        else:
            try:
                if event & POLLIN:
                    why = selectable.doRead()
                    inRead = True
                if not why and event & POLLOUT:
                    why = selectable.doWrite() # XXX
                    inRead = False
                if not selectable.fileno() == fd:
                    why = error.ConnectionFdescWentAway('Filedescriptor went away')
                    inRead = False
            except:
                log.deferr()
                why = sys.exc_info()[1]
        if why:
            self._disconnectSelectable(selectable, why, inRead)
```

<details><summary>Searchable metadata</summary>

```
trac-id__4759 4759
type__defect defect
reporter__lewq lewq
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__None None
time__1291565432000000 1291565432000000
changetime__1531322704430831 1531322704430831
version__None None
owner__ 
cc__gandalf013@...
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="lewq's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_1"></a>|lewq commented|
|-|-|

Having looked at this with ousado_ on IRC, here is an evilThing which triggers this same exception, and a log listener which is my current workaround (restart the daemon when it dies with this error).

Hopefully this ticket can act as a point of discussion for improvements to the pollreactor which would render my workaround obsolete in some future version ;-)

Thanks for the great work guys. I love Twisted.

```
from select import POLLOUT
import sys
from twisted.internet import reactor
from twisted.python import log
from twisted.internet import protocol
from twisted.application import service

class P(protocol.Protocol):
    pass
    
class F(protocol.ServerFactory):
    protocol = P
    
def evilThing(port):
    print "About to add writer"
    reactor.addWriter(port)
    reactor._doReadOrWrite(port,port.fileno(),POLLOUT)
    
def init():
    port = reactor.listenTCP(9882, F())
    reactor.callLater(5, evilThing, port)
    
application = service.Application("evil")

def log_catcher(d):
    if d.get('isError',False):
        if d['failure'].getErrorMessage() == 'doWrite called on a twisted.internet.tcp.Port':
            # Re-initialise
            reactor.callLater(0,init)

log.addObserver(log_catcher)
init()

```

Start with:

```
twistd -r poll -noy testcase.py
```

**Comment by twisted-trac** [comment]
|<img alt="buffer's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_2"></a>|buffer commented|
|-|-|

I have already notified about it in the Twisted mailing list and I'm reposting here 
both for convenience and because it seems related to this ticket.
 
While developing a code based on Twisted Names I'm finding myself catching 
RuntimeErrors like the one reported below. 

```
2011-01-09 10:32:13+0100 [twisted.names.dns.DNSDatagramProtocol (UDP)]
Unhandled Error Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/twisted/python/log.py", line 84, in callWithLogger 
		return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/lib64/python2.6/site-packages/twisted/python/log.py", line 69, in callWithContext 
		return context.call({ILogContext: newCtx}, func, *args,**kw) 
  File "/usr/lib64/python2.6/site-packages/twisted/python/context.py", line 59, in callWithContext 
		return self.currentContext().callWithContext(ctx, func, *args, **kw) 
  File "/usr/lib64/python2.6/site-packages/twisted/python/context.py", line 37, in callWithContext 
	return func(*args,**kw) 
  --- <exception caught here> --- 
  File "/usr/lib64/python2.6/site-packages/twisted/internet/epollreactor.py", line 220, in _doReadOrWrite 
	why = selectable.doWrite() 
  File "/usr/lib64/python2.6/site-packages/twisted/internet/base.py", line 1083, in doWrite 
	raise RuntimeError, "doWrite called on a %s" % reflect.qual(self.__class__)
  exceptions.RuntimeError: doWrite called on a twisted.internet.udp.Port
```

The code which produces this error is really complex and is part of an intelligence data 
gathering framework I'm developing for the Honeynet Project (for those interested in 
details please take a look at my technical blog http://buffer.antifork.org/blog/category/tip/ ). 

I realized that 
	* the RuntimeError is raised really rarely (I see one of such errors 
	  every 2-3 days and during this time frame millions of DNS requests
	  and replies are handled)
	* using different Twisted versions doesn't make the problem disappear
	  (the attached traceback refers to version 10.2.0) 
	* selecting a different reactor doesn't make the problem disappear

Unfortunately I have not a test code for reproducing the issue and sincerely speaking I 
really don't know how to write it because this condition is so rarely met that I'm not able 
to understand what leads to it.

I could be wrong but taking a look at twisted.internet.udp.Port I see it defines a
write method so I really do not understand the reason why the BasePort doWrite
method raises such error. 

Additional information:

  * OS: 		Gentoo Linux (kernel 2.6.34)
  * Twisted: 	10.1.0 and10.2.0
  * Reactors:    select (default) and epoll

I tried all the possible combinations of Twisted and reactors always getting the same 
error.

Moreover I make no use of startWriting/pauseProducing in my code. I'm just creating
a client.Resolver and then using its lookup methods as suggested in the documentation 
at http://twistedmatrix.com/documents/current/names/examples/

I just subclassed the client.Resolver in order to define an empty
connectionLost method this way

```
class TIPResolver(client.Resolver):
    def __init__(self):
        client.Resolver.__init__(self, resolv = '/etc/resolv.conf')

    def connectionLost(self, protocol):
        pass 

r = TIPResolver()
```

but nothing more than this.

**Comment by twisted-trac** [comment]
|<img alt="lewq's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_3"></a>|lewq commented|
|-|-|

Found another one, which is similar...

```

2011-01-21 23:12:59+0000 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.6/site-packages/Twisted-8.1.0-py2.6-freebsd-8.1-RELEASE-amd64.egg/twisted/python/log.py", line 51, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/usr/local/lib/python2.6/site-packages/Twisted-8.1.0-py2.6-freebsd-8.1-RELEASE-amd64.egg/twisted/python/log.py", line 36, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/usr/local/lib/python2.6/site-packages/Twisted-8.1.0-py2.6-freebsd-8.1-RELEASE-amd64.egg/twisted/python/context.py", line 59, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/usr/local/lib/python2.6/site-packages/Twisted-8.1.0-py2.6-freebsd-8.1-RELEASE-amd64.egg/twisted/python/context.py", line 37, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.6/site-packages/Twisted-8.1.0-py2.6-freebsd-8.1-RELEASE-amd64.egg/twisted/internet/pollreactor.py", line 189, in _doReadOrWrite
	    why = selectable.doWrite()
	exceptions.AttributeError: _UnixWaker instance has no attribute 'doWrite'

```

Any thoughts?

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_4"></a>|@exarkun commented|
|-|-|

Any chance this is reproducable?  Can you add an `assert IWriteDescriptor.providedBy(writer)` to `SelectReactor.addWriter` and see what traceback comes up?

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_5"></a>|@exarkun commented|
|-|-|

Sorry, `PollReactor.addWriter`, or whatever reactor you happen to be able to trigger this behavior with.

**Comment by twisted-trac** [comment]
|<img alt="lewq's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_6"></a>|lewq commented|
|-|-|

Hi Jean-Paul,

Not directly reproducible I'm afraid, but I'm going to be doing some serious stress-testing of the code which exhibits this bug over the coming weeks, so I'll add that assert and watch the exception log carefully.

Hopefully I'll get to meet you on Tuesday with Glyph & Itamar? I think I owe you a drink :-)

Cheers!
Luke

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|<img alt="lewq's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_8"></a>|lewq commented|
|-|-|

This looks like this on Twisted 11.0:

```
'_SIGCHLDWaker' object has no attribute 'doWrite'
```

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_9"></a>|@exarkun commented|
|-|-|

It turns out that `IWriteDescriptor.implementedBy(Port)` is `True`. :(  This is probably wrong.  Regardless, it means the suggested assertion doesn't do anything useful.  Instead, an `isinstance` check or something similar (to actually identify the bogus type, be that `Port` or `_SIGCHLDWaker` or whatever) is probably necessary for this to provide any useful debugging information.

**Comment by twisted-trac** [comment]
|<img alt="dmcleod's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_10"></a>|dmcleod commented|
|-|-|

On Jean-Paul's recommendation we implemented the assertion `assert not isinstance(writer, Port)` where `Port` is `twisted.internet.tcp.Port` in `epollReactor.addWriter` method which is the reactor being used in our application by default. We have the same results with no further information in the traceback. 

Jean-Paul, we will put together a self-contained example and send it through soon.

Cheers,
Dan

**Comment by twisted-trac** [comment]
|<img alt="jkane's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_11"></a>|jkane commented|
|-|-|

if you replace (in epollreactor.py):
```
try:
    # In Python 2.6+, select.epoll provides epoll functionality. Try to import
    # it, and fall back to Twisted's own epoll wrapper if it isn't vailable
    # for any reason.
    from select import epoll
except ImportError:
    from twisted.python import _epoll
else:
    del epoll
    import select as _epoll
```

with

```
from twisted.python import _epoll
```

the problem disappears (in twisted 12.01 on linux using epoll)

After upgrading to 15.3 (via pip):
```
2015-08-28 22:22:45,142 CRITICAL twisted      Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 602, in _doReadOrWrite
    why = selectable.doWrite()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1119, in doWrite
    "doWrite called on a %s" % reflect.qual(self.__class__))
exceptions.RuntimeError: doWrite called on a twisted.internet.tcp.Port
```

:(

**Comment by twisted-trac** [comment]
|<img alt="jkane's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_12"></a>|jkane commented|
|-|-|

Inside epollreactor doPoll() I added sanity checks to log when _poller.poll() gives us an event flagged for READ on a fd that is _not_ in self._reads (and similarly with writes).  Low and behold, gobs of hits.  Unexpected.

So I took a closer look.  It appears to me that _epoll.epoll() is emitting events that are outside of the flags that epollreactor carefully registers.  Filtering them out in doPoll seems to avoid this particular traceback but it also breaks the world.  At least in my system this appears to be the expected behavior.

So (to restate and summarize) asserting on addWriter() doesn't do anything because the Port was added by addReader().  Despite only being in _reads() and being registered with _epoll.EPOLLIN, doPoll() is getting write events which it happily passes through to _doReadOrWrite which checks the event flag, sees it as a _POLL_OUT and tries to write it.

As I see it there are two basic possibilities.  Either (a) the python 2.7 epoll is borked or (b) the way epollreactor uses it is wrong; well, three, I guess (c) the kernel could be borked.  Switching to the old twisted.python._epoll does appear to resolve the issue but it looks like it was removed in recent versions of twisted.

I am hopefull this is enough info to nudge this toward a real solution.  If there are any other diagnostics that might be helpful I'm more than happy to assist.  I guess the reasonable assumption is (b), though I don't see anything truly wrong.

I'll keep poking around, see if I can find anything else interesting.

------------------------

I found it.  It boils down to a simple multiple process issue.

I am running four instances of my application (one per core) using a toplevel python multiprocessing manager.  Each instance connects to the same set of memcache servers.  When each instance connects to memcache, it first registers for event mask 1 (read only), then later modifies it to event mask 5 (read write).

So instance 1-4 all start at about the same time.  [[#11338](https://github.com/twisted/twisted/issues/11338)1338](https://github.com/twisted/twisted/issues/11338) registers with epoll, gives a FD and read only.  #1 then modifies it to a 5.  Instance #2 pull up and registers the _same fd_ with mask 1.  At some point a process gets an event 5 notification before that processes actually added the writer to handle it.

The kernel docs are a bit vague on what happens when a second process tries to set a second epoll on a fd: "You will probably get EEXIST".  It certainly looks like the twisted._epoll implementation handles the situation better/differently than select.epoll but the fundamental problem is in my setup (isn't that always how things end up).

I hope this helps the next person that falls into the doWrite rabbit hole.  I think I can solve my problem with a judicious os.dup() to use a duplicated file descriptor, just need to find the right place to do it.

Reg. the original freebsd ticket (kqueue?); it is reasonably possible you are in the same or very similar situation.  Sorry to have hijacked your ticket to such a degree.  I hope this helps you too.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_13"></a>|@glyph commented|
|-|-|

jkane tried to update this ticket but was prevented by the spam filter.  here it is:

-----------

I found it.  It is a simple multiple processing issue.

I am running four instances of my application (one per core) using a toplevel python multiprocessing manager.  Each instance connects to the same set of memcache servers.  When each instance connects to memcache, it first registers for event mask 1 (read only), then later modifies it to event mask 5 (read write).

So instance 1-4 all start at about the same time.  [[#11338](https://github.com/twisted/twisted/issues/11338)1338](https://github.com/twisted/twisted/issues/11338) registers with epoll, gives a FD and read only.  #1 then modifies it to a 5.  Instance #2 pull up and registers the _same fd_ with mask 1.  At some point a process gets an event 5 notification before that processes actually added the writer to handle it.

The kernel docs are a bit vague on what happens when a second process tries to set a second epoll on a fd: "You will probably get EEXIST".  It certainly looks like the twisted._epoll implementation handles the situation better/differently than select.epoll but the fundamental problem is in my setup (isn't that always how things end up).

I hope this helps the next person that falls into the doWrite rabbit hole.  I think I can solve my problem with a judicious os.dup() to use a duplicated file descriptor, just need to find the right place to do it.

Reg. the original freebsd ticket (kqueue?); it is reasonably possible you are in the same or very similar situation.  Sorry to have hijacked your ticket to such a degree.  I hope this helps you too.

**Comment by twisted-trac** [comment]
|[<img alt="marosmars's avatar" src="https://avatars.githubusercontent.com/u/3070975?s=50" width="50" height="50">](https://github.com/marosmars)<a name="note_15"></a>|@marosmars commented|
|-|-|

I ran into the same problem, multiprocess setup spawning SSH/Telnet servers.
100 endpoints per process and once I tried to connect to all of them, I ended up with a few failed connections and in the log I could see the same issue.

Since this was just a test-tool I fixed it by adding a small sleep to each sub-process . When the sub-process started, it waited for a bit, not to start at the same time as some other sub-process.

This fixed the problem for me, the code is here: https://github.com/marosmars/cli-testtool

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_16"></a>|@glyph commented|
|-|-|

It's a pity this is still an issue, but it seems very hard to reproduce.  If someone who is affected by this could write up a PR, that would be _great_.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_17"></a>|@exarkun commented|
|-|-|

It sounds like the two people who encountered it most recently did so by using Twisted in a way which it is not intended to be used.

If you use the stdlib multiprocessing module to fork a process that already has its Twisted reactor instantiated, that is definitely a problem.  Reactors are not constructed to support this use.  They _could_ be, maybe (especially only *partially* - eg don't allocate anything until `run` is called).

However, it's not clear these multiprocessing-derived problems are related to the original report - note there is a reproducer that clearly does not fork anywhere.  Also, there are reports of the issue against multiple reactors, including select which should not be affected by forking (because it has no state to accidentally share).
