### ISSUE TITLE
Twisted/python/log traceback in callWithLogger when using telnet.conch.telnet (possibly due to invalid/special chars)

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#4776]
|<img alt="atanner's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| atanner reported|
|-|-|
|Trac ID|trac#4776|
|Type|defect|
|Created|2010-12-20 06:04:08Z|

I'm building a mudclient and using twisted.conch.telnet for the
connection on the mud I'm testing the connection with there are often
escape sequence / special characters. I'm hitting the following 
traceback when executing the 'who' command on the mud:
```

[  1  Triton T+4] FTraceback (most recent call last):
  File "./telnet_client.py", line 69, in <module>
    reactor.run()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/Twisted-10.2.0-py2.6-macosx-10.6-x86_64.egg/twisted/internet/base.py", line 1158, in run
    self.mainLoop()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/Twisted-10.2.0-py2.6-macosx-10.6-x86_64.egg/twisted/internet/base.py", line 1170, in mainLoop
    self.doIteration(t)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/Twisted-10.2.0-py2.6-macosx-10.6-x86_64.egg/twisted/internet/selectreactor.py", line 140, in doSelect
    _logrun(selectable, _drdw, selectable, method, dict)
--- <exception caught here> ---
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/Twisted-10.2.0-py2.6-macosx-10.6-x86_64.egg/twisted/python/log.py", line 84, in callWithLogger
    return carolo the Assassin \}Tao{/
```

I'm using latest twisted...

```
( andrew@rhombo:~/Twist/Twisted-10.2.0 7 ) twistd --version
twistd (the Twisted daemon) 10.2.0
Copyright (c) 2001-2010 Twisted Matrix Laboratories.
See LICENSE for details.
```

Here is the code I'm seeing this behavior with:

```
class TelnetSession(telnet.Telnet):
    def __init__(self):
        self.output = None

    def dataReceived(self, data):
        #stdout.write(data)
        #stdout.flush()
        if self.output:
            self.output.write(data)

class StdioProxyProtocol(TelnetSession):
    def connectionMade(self):
        inputForwarder = TelnetSession()
        inputForwarder.output = self.transport
        inputForwarder.normalizeNewlines = True
        stdioWrapper = stdio.StandardIO(inputForwarder)
        self.output = stdioWrapper

        print "Connected to server.  Press ctrl-C to close connection."

class StdioProxyFactory(ClientFactory):
    protocol = StdioProxyProtocol

    def clientConnectionLost(self, transport, reason):
        reactor.stop()

    def clientConnectionFailed(self, transport, reason):
        print reason.getErrorMessage( )
        reactor.stop()

if __name__ == '__main__':
    hostname = "<removed>"

    port = 4000

    reactor.connectTCP(hostname, port, StdioProxyFactory())
    reactor.run()
```

Attachments:

* [conch_telnet_traceback.pcap](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/a59/a593deb730b2958fd742584dcae2b6b85fa63be5/596fd6adebf330f40684e0c5c1cd3825dcb551e4.pcap) (14569 bytes) - added by atanner on 2010-12-20 06:18:05Z - PCAP of session with traceback

<details><summary>Searchable metadata</summary>

```
trac-id__4776 4776
type__defect defect
reporter__atanner atanner
priority__high high
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__invalid invalid
component__conch conch
keywords__ 
time__1292825048000000 1292825048000000
changetime__1293331105000000 1293331105000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

Fixing description markup and removing (release-automation related) milestone.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_2"></a>|@exarkun set owner to atanner|
|-|-|

Thanks for your report.  It will probably be necessary to see the byte sequence that triggers this.  Can you do a traffic capture (eg using tcpdump or wireshark) of a connection where this happens and attach it here?

**Comment by twisted-trac** [comment]
|<img alt="atanner's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_3"></a>|atanner commented|
|-|-|

Sure. I attached a PCAP. Here is the output I saw running the attached script during
this session...

[  9  Vamp   H+4] Haruon the White Lightning [Craceback (most recent call last):
  File "./telnet_client.py", line 69, in <module>
    reactor.run()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/Twisted-10.2.0-py2.6-macosx-10.6-x86_64.egg/twisted/internet/base.py", line 1158, in run
    self.mainLoop()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/Twisted-10.2.0-py2.6-macosx-10.6-x86_64.egg/twisted/internet/base.py", line 1170, in mainLoop
    self.doIteration(t)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/Twisted-10.2.0-py2.6-macosx-10.6-x86_64.egg/twisted/internet/selectreactor.py", line 140, in doSelect
    _logrun(selectable, _drdw, selectable, method, dict)
--- <exception caught here> ---
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/Twisted-10.2.0-py2.6[1;36m]
[  1  Wolf   Thi] Gwaze the Assassin [Q]
[193  Giant  R+3] Siko the Shaman -=*)Dragon(*=-
[ 17  Giant  W+4] Yendaleth  [C]
[ 31  Troll  War] Isopropyl the Barbarian [C]
[  1  Vamp   M+6] [Advisor] Rainstorm ... {Twinlobe}
[122  Human  W+2] Schrute Assistant (to the) Regional Manager 
[ 15  H-Grif Pal] Teezpoon The immaculate 
[  8  Wolf   Pal] [Advisor] Deepred the Avenger <*]AMAZON[*>[C]
[ 92  Triton T+4] Mezixtuzagg idling/questing (-DoH-)[C]
[ 93  Sprite Thi] Tutal  
[   SUPERHERO   ] *AFK* Cartman the Shaman (+)Cabal(+)
[ 30  Diva   R+3^CTraceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/Twisted-10.2.0-py2.6-macosx-10.6-x86_64.egg/twisted/python/context.py", line 59, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/Twisted-10.2.0-py2.6-macosx-10.6-x86_64.egg/twisted/python/context.py", line 37, in callWithContext
    return func(*args,**kw)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/Twisted-10.2.0-py2.6-macosx-10.6-x86_64.egg/twisted/internet/process.py", line 275, in connectionLost
    self.proc.childConnectionLost(self.name, reason)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/Twisted-10.2.0-py2.6-macosx-10.6-x86_64.egg/twisted/internet/_posixstdio.py", line 101, in childConnectionLost
    self.connectionLost(reason)
--- <exception caught here> ---
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/Twisted-10.2.0-py2.6-macosx-10.6-x86_64.egg/twisted/internet/_posixstdio.py", line 120, in connectionLost
    protocol.connectionLost(reason)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/Twisted-10.2.0-py2.6-macosx-10.6-x86_64.egg/twisted/conch/telnet.py", line 567, in connectionLost
    for state in self.options.values():
exceptions.AttributeError: TelnetSession instance has no attribute 'options'

The second traceback was from when I ctrl-c'd the hung session...

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_4"></a>|@glyph set owner to @exarkun|
|-|-|

Reassigning to exarkun to make sure he sees the reply.

**Comment by twisted-trac** [comment]
|<img alt="atanner's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_5"></a>|atanner commented|
|-|-|

If you look at the pcap you will see the server actually initiated the disconnect.
I suspect it is initiating a disconnect because the client is not receiving data quick
enough due to lack of buffering. This may not be a twisted issue (or rather, something
that should be handled in the client implementation).

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_6"></a>|@exarkun commented|
|-|-|

The pcap only spans about 3 seconds of time.  That would be an awfully short timeout for the server to implement.  Also, there are no telnet control sequences in the captured data, so nothing special is happening in the telnet implementation, the data just gets passed through to the application layer.

Are you subclassing `twisted.conch.telnet.Telnet`?  And if so, are you overriding `__init__`?  And if so, are you calling up to the base method?

**Comment by twisted-trac** [comment]
|<img alt="atanner's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_7"></a>|atanner commented|
|-|-|

I wasn't calling the twisted.conch.telnet.Telnet base method, but I just added support
for calling it and it didn't make a difference. 

FWIW the BSD telnet client that comes with OSX has the same issue, and it's incredibly easy to repro by going to this mud (aardmud.org port 4000) and typing 'who'.

Maybe the server has an unrealistic expectation of client responsiveness. I've worked
around this by using a client implementation that supports MCCP.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_8"></a>|@exarkun commented|
|-|-|

> the BSD telnet client that comes with OSX has the same issue

I wasn't able to reproduce it on OS X.  The who results are paginated, and I can view each page of results.

> didn't make a difference

So there's still a traceback logged?  Or do you only mean that the server still disconnects the client, but with no more traceback?

> Maybe the server has an unrealistic expectation of client responsiveness

Maybe, but I wonder how you got to this conclusion.  3 seconds doesn't seem like long enough for this to be a timeout issue.

**Comment by twisted-trac** [comment]
|<img alt="atanner's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_9"></a>|atanner commented|
|-|-|

Replying to [exarkun](#note_8):
> I wasn't able to reproduce it on OS X.  The who results are paginated, and I can view each page of results.
Whoops looks like by default it uses pagination. You can disable this by typing:
'pagesize 0' when logged in I believe. Which should hopefully repro the issue.

> > didn't make a difference
> So there's still a traceback logged?  Or do you only mean that the server still disconnects the client, but with no more traceback?
You are right--I am not getting a traceback, it could be because I have it calling
telnet.TelnetTransport.__init__(self) now.

> Maybe, but I wonder how you got to this conclusion.  3 seconds doesn't seem like long enough for this to be a timeout issue.
This I don't know for sure. I am making an assumption that the server is disconnecting
because of unresponsiveness. And now that I am using compression I'm not seeing the
same disconnects. 

Seems like this isn't a twisted bug. Just a combination of strict server + not calling the parent __init__?

**Comment by twisted-trac** [comment]
|[<img alt="jyknight's avatar" src="https://avatars.githubusercontent.com/u/873903?s=50" width="50" height="50">](https://github.com/jyknight)<a name="note_10"></a>|@jyknight set status to `closed`|
|-|-|

Muds will usually disconnect you if the output buffer gets too large. So, of course, if you have a single command (e.g. "who" without paging) which generates more output than that buffersize, it'll disconnect you. Clearly this mud has their max output buffer size set too small.

Anyways, not a bug in Twisted.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
