### ISSUE TITLE
Error with FilePath

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#4777]
|<img alt="lormayna's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| lormayna reported|
|-|-|
|Trac ID|trac#4777|
|Type|defect|
|Created|2010-12-20 10:30:07Z|

I found this error on Filepath module:

```
>>> fp=FilePath("/tmp/pippo.txt")
>>> fp.create()
Traceback (most recent call last):
  File "<stdin>", line 1, in ?
  File "/usr/lib/python2.4/site-packages/Twisted-10.2.0-py2.4-linux-i686.egg/twisted/python/filepath.py", line 791, in create
    fdint = os.open(self.path, _CREATE_FLAGS)
OSError: [Errno 17] File exists: '/tmp/pippo.txt'
>>> fp.open("pippo.txt")
Traceback (most recent call last):
  File "<stdin>", line 1, in ?
  File "/usr/lib/python2.4/site-packages/Twisted-10.2.0-py2.4-linux-i686.egg/twisted/python/filepath.py", line 519, in open
    return open(self.path, mode + 'b')
IOError: invalid mode: pippo.txtb
```

So what is pippo.txtb?Why b?

It seems a bug

<details><summary>Searchable metadata</summary>

```
trac-id__4777 4777
type__defect defect
reporter__lormayna lormayna
priority__normal normal
milestone__totally_automated_release_infrastructure totally automated release infrastructure
branch__ 
branch_author__ 
status__closed closed
resolution__invalid invalid
component__core core
keywords__FilepAth FilepAth
time__1292841007000000 1292841007000000
changetime__1292841483000000 1292841483000000
version__None None
owner__glyph glyph

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_2"></a>|@therve set status to `closed`|
|-|-|

open takes a mode argument (like "w" or "r"). You already pass the file name to the constructor, you don't need to pass it again.
