### ISSUE TITLE
@unittest.expectedFailure decorator breaks trial

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#4811]
|<img alt="ivank's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| ivank reported|
|-|-|
|Trac ID|trac#4811|
|Type|defect|
|Created|2011-01-18 01:47:23Z|
|Branch|https://github.com/twisted/twisted/tree/expected-failure-4811|

This works in Python's test runner, but breaks when run with trial:

```
import unittest

class TestSomething(unittest.TestCase):

    @unittest.expectedFailure
    def test_missing(self):
        self.fail("add some tests")
```

I ran into this when running https://bitbucket.org/ronaldoussoren/altgraph/src/8a7b4c1c5473/altgraph_tests/test_dot.py

The traceback from trial:

```
$ trial altgraph_tests.test_dot
altgraph_tests.test_dot
  TestDot
    test_missing ... Traceback (most recent call last):
  File "/usr/local/bin/trial", line 22, in <module>
    run()
  File "/opt/Python-x86/lib/python2.7/site-packages/twisted/scripts/trial.py", line 377, in run
    test_result = trialRunner.run(suite)
  File "/opt/Python-x86/lib/python2.7/site-packages/twisted/trial/runner.py", line 796, in run
    return self._runWithoutDecoration(test)
  File "/opt/Python-x86/lib/python2.7/site-packages/twisted/trial/runner.py", line 825, in _runWithoutDecoration
    run()
  File "/opt/Python-x86/lib/python2.7/site-packages/twisted/trial/runner.py", line 820, in <lambda>
    run = lambda: suite.run(result)
  File "/opt/Python-x86/lib/python2.7/site-packages/twisted/trial/runner.py", line 289, in run
    TestSuite.run(self, result)
  File "/opt/Python-x86/lib/python2.7/site-packages/twisted/trial/unittest.py", line 1390, in run
    test(result)
  File "/opt/Python-x86/lib/python2.7/site-packages/twisted/trial/unittest.py", line 1378, in __call__
    return self.run(result)
  File "/opt/Python-x86/lib/python2.7/site-packages/twisted/trial/runner.py", line 165, in run
    super(LoggedSuite, self).run(result)
  File "/opt/Python-x86/lib/python2.7/site-packages/twisted/trial/unittest.py", line 1390, in run
    test(result)
  File "/opt/Python-x86/lib/python2.7/site-packages/twisted/trial/unittest.py", line 1378, in __call__
    return self.run(result)
  File "/opt/Python-x86/lib/python2.7/site-packages/twisted/trial/runner.py", line 138, in run
    test(result)
  File "/opt/Python-x86/lib/python2.7/site-packages/twisted/trial/unittest.py", line 1378, in __call__
    return self.run(result)
  File "/opt/Python-x86/lib/python2.7/site-packages/twisted/trial/runner.py", line 138, in run
    test(result)
  File "/opt/Python-x86/lib/python2.7/site-packages/twisted/trial/unittest.py", line 1378, in __call__
    return self.run(result)
  File "/opt/Python-x86/lib/python2.7/site-packages/twisted/trial/runner.py", line 138, in run
    test(result)
  File "/opt/Python-x86/lib/python2.7/site-packages/twisted/trial/unittest.py", line 1413, in __call__
    return self.run(result)
  File "/opt/Python-x86/lib/python2.7/site-packages/twisted/trial/unittest.py", line 1423, in run
    reporter._AdaptedReporter(result, self.__class__))
  File "/opt/Python-x86/lib/python2.7/unittest/case.py", line 329, in run
    addExpectedFailure(self, e.exc_info)
TypeError: addExpectedFailure() takes exactly 4 arguments (3 given)
```

Attachments:

* [Defect_4811.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/99c/99cc47b994c504f0edb738d271249b1580b9be2d/673f21a05b60bc8f6603af92d2b836ac6c69d9e5.patch) (8441 bytes) - added by suyase on 2014-03-08 05:32:25Z - Patch for defect described in Ticket #4811
* [Defect_4811_2.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/99c/99cc47b994c504f0edb738d271249b1580b9be2d/d0e5987cd99793025d33ab5c050604ab8f0f24af.patch) (9658 bytes) - added by suyase on 2014-03-18 22:16:04Z - Updates tests for addExpectedFailure and addUnexpectedSuccess
* [Defect_4811_3.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/99c/99cc47b994c504f0edb738d271249b1580b9be2d/2bc4e66d45ad7642f42dd188da10fb92245bf528.patch) (9928 bytes) - added by suyase on 2014-03-19 18:40:29Z - Revision of tests regarding twisted.trial.reporter._AdaptedReporter addExpectedFailure and addUnexpectedSuccess; includes newsfile 4811.bugfix
* [Defect_4811_4.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/99c/99cc47b994c504f0edb738d271249b1580b9be2d/157a9dec3f2bf25a1db6ad19a28acef1a74b1ad2.patch) (10100 bytes) - added by suyase on 2014-03-19 18:57:01Z - Removed getattr calls in lieu of . operator

<details><summary>Searchable metadata</summary>

```
trac-id__4811 4811
type__defect defect
reporter__ivank ivank
priority__normal normal
milestone__ 
branch__branches_expected_failure_4811 branches/expected-failure-4811
branch_author__jml jml
status__closed closed
resolution__fixed fixed
component__trial trial
keywords__None None
time__1295315243000000 1295315243000000
changetime__1519054509827745 1519054509827745
version__None None
owner__jml jml
cc__Julian
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="Julian's avatar" src="https://avatars.githubusercontent.com/u/329822?s=50" width="50" height="50">](https://github.com/Julian)<a name="note_3"></a>|@Julian commented|
|-|-|

[#6345](https://github.com/twisted/twisted/issues/6345) and transitively [#4596](https://github.com/twisted/twisted/issues/4596) were closed as duplicates of this.

**Comment by twisted-trac** [comment]
|<img alt="suyase's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_4"></a>|suyase commented|
|-|-|

In unittest's case.py, when a test is run with an expected failure decorator the method to resolve the expected failure (addExpectedFailure) is accessed as an attribute of the test reporter. I do not know whether this is normal behavior, but trial only implements a version of the method requiring a fourth `todo` argument in addition to the normal three required by unittest.

Although I am not very familiar with trial, I expect that allowing case.py to run the test is normal behavior, and since modifying the caller in this case is undesirable, I think trial would need to implement a version of the addExpectedFailure method requiring three arguments as a wrapper for trial's internal method call?

Please advise, and thanks,
Andrew

**Comment by twisted-trac** [comment]
|<img alt="suyase's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_5"></a>|suyase commented|
|-|-|

This bug is also reproducible if the decorated test succeeds and causes an addUnexpectedSuccess call from case.py with two arguments (trial expects 3) because the method is accessed via getattr() from the reporter. In the scope of TestCase.run() the reporter is referenced as `result`.

**Comment by twisted-trac** [comment]
|<img alt="suyase's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_6"></a>|suyase commented|
|-|-|

This patch modifies the addExpectedFailure and addUnexpectedSuccess methods in the _AdaptedReporter wrapper by building a default unittest.Todo if one is not provided by the caller.
When these methods are called from unittest.TestCase.run() with the wrong number of arguments, a generic todo will be created, allowing trial to successfully handle @unittest.expectedFailure decorators.

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_7"></a>|@adiroiban set owner to suyase|
|-|-|

Hi and thanks for the work in this!

Looks good.

I think that epydoc text should user @type to document argument type, rather than infer it from @param description.

For the docstring, maybe we should not assert that only pyunit.TestCase will call the method without todo (maybe there are also other testing frameworks) and instead just document what happen when todo is None. We can include a note explaining that pyunit.TestCase will call it with 3 arguments.


```
When C{todo} is C{None} a generic C{unittest.Todo} is set.

L{pyunit.TestCase} calls this with only 3 arguments (without C{todo}) when  
@unittest.expectedFailure is used.
``` 


I think that a test is needed to exercise the new behavior when todo is None.

Other that this. All good.

Thanks!

**Comment by twisted-trac** [comment]
|<img alt="suyase's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_8"></a>|suyase commented|
|-|-|

I updated the tests, they should now be appropriate.
Please see patch for details.

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_9"></a>|@adiroiban commented|
|-|-|

Looks great thanks!

I can now understand the tests :)

Now... I don't know how arguments are counted... do we count self ? :)

-----

Maybe this is right and just hard to understand just from diff:

```
786	    def _getExpectedFailures(self, result):
                  inside of an unclean warnings reporter wrapper.
 
```

Is this new method used somewhere?

-----

Instead of 
```
addExpectedFailure(test=self.test, failure=AssertionError, todo=None)
addUnexpectedSuccess(test=self.test, todo=None) 
```
I was expecting the test to exercise something closer to pyunit call.
```
addExpectedFailure(test=self.test, failure=AssertionError)
addUnexpectedSuccess(test=self.test, todo) 
```

The methods are not called without todo argument, but with a todo argument which is None :)

The the docstring can be:
```
Handles failures when called without C{todo} argument. 
```

We don't need to add 'test', 'checks', 'should' in the test docstring as it should be understood that this is a test method and this is why we write test methods ie to check / tests.

Also, the method name can be left out since it can be inferred from test name.

------

Don't forget to add the newsline in the final diff.

Beside the above comments all look good and after the next diff submission I think that the patch could be merged.

Thanks!

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_10"></a>|@adiroiban commented|
|-|-|

Hm... my previous comment contains an error

I was expecting the test to exercise something closer to pyunit call.

```
addExpectedFailure(test=self.test, failure=AssertionError)
addUnexpectedSuccess(test=self.test)
```

I am not sure if pyunit is calling the method with named arguments, so maybe the test should be use

```
addExpectedFailure(self.test, AssertionError)
addUnexpectedSuccess(self.test)
```

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_12"></a>|@adiroiban commented|
|-|-|

Much better.

This pacth contains trailing spaces. http://twistedmatrix.com/documents/current/core/development/policy/coding-standard.html#auto5

For _getExpectedFailures from UncleanWarningTodoTest there are 2 empty lines between methods. You change only add one empty line. See whitespace standards.

Also, only 3 emtpy lines before UncleanWarningTodoTest

-----

Minor comments;

I saw that this is repeated in tests.
```
def test_adapt(test): return test
reporter_instance = reporter._AdaptedReporter(self.result, test_adapt)
```

First time when I read the code, I had no idea why 'test_adapt' is needed and if its definition is significant for the tests.

Maybe it can be refactored to a creation method to hide the insignificant test adapter from the casual test reader :)

```

def makeAdaptedReporter(self):
   """
   Returns an _AdaptedReporter instances.
   """
   def test_adapter(test):
       """
       A simple adapter which returns the test itself.
       """
       return test

   return reporter._AdaptedReporter(self.result, test_adapt)
```

------

Sorry for this long ping pong... I am just starting to lean the review process

All good. Thanks!

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)<a name="note_13"></a>|@jml commented|
|-|-|

(In [46472]) Branching to expected-failure-4811.

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)<a name="note_14"></a>|@jml removed owner|
|-|-|

I have taken suyase's work and built on top of it in branches/expected-failure-4811. 

This branch goes further, in that it changes the interface of `IReporter` such that `addExpectedFailure` and `addUnexpectedSuccess` now both have an _optional_ `todo` parameter.

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_15"></a>|@adiroiban set owner to @jml|
|-|-|

Many thanks for working on this.


# Required


In  twisted/trial/test/test_reporter.py _getTodos, _getUnexpectedSuccesses ... etc have changed implementations but the docstring was not changed.


# Optional


Maybe twisted/topfiles/4811.bugfix should be split in  twisted/topfiles/4811.bugfix and  twisted/topfiles/4811.feature and consider the optional parameter a feature.

Maybe the release notes should contain full python names with package and module names.

---------

In twisted/trial/_dist/workerreporter.py can you please document the new _TODO private ivar

AFAIK the coding standard ask for all new methods, including private methods, to be fully documented with epydoc.


---------

Changes looks good.

Please check my minor comments and merge.

Thanks!

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)<a name="note_16"></a>|@jml commented|
|-|-|

Thanks for the quick review!

* Updated docstrings for test helpers
* Split NEWS file into feature & bugfix
* Left the Python names as they are
* Documented private ivar in workerreporter

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)<a name="note_17"></a>|@jml set status to `closed`|
|-|-|

(In [46494]) Merge expected-failure-4811: Make trial compatible with standard expectedFailure

Author: jml, suyase
Reviewer: adiroiban
Fixes: [#4811](https://github.com/twisted/twisted/issues/4811)

Both Twisted reporters and Python standard library TestResult objects
support addExpectedFailure and addUnexpectedSuccess. However, the
interface is slightly different.

This patch updates the Twisted reporter interface so that the "todo"
object is optional, which makes addExpectedFailure and
addUnexpectedSuccess compatible with standard Python unittest.

This means that `trial` can now be used with standard Python unittests.

**Comment by twisted-trac** [comment]
|[<img alt="Julian's avatar" src="https://avatars.githubusercontent.com/u/329822?s=50" width="50" height="50">](https://github.com/Julian)<a name="note_18"></a>|@Julian set status to `reopened`|
|-|-|

I'm not sure this fully works, it still errors out for me, albeit in a different place.

Reproduction:

```
pip install -U git+https://github.com/twisted/twisted && printf 'from unittest import TestCase, expectedFailure\nclass Test(TestCase):\n    @expectedFailure\n    def test_thing(self):\n        self.fail()' >test.py && trial test.py && rm test.py
```

which fails for me with 

```
⊙  printf 'from unittest import TestCase, expectedFailure\nclass Test(TestCase):\n    @expectedFailure\n    def test_thing(self):\n        self.fail()' >test.py && trial test.py && rm test.py                                                                                                               Julian@Macnetic
test
  Test
    test_thing ...                                                       [TODO]

Traceback (most recent call last):
  File "/usr/local/bin/trial", line 22, in <module>
    run()
  File "/usr/local/lib/python2.7/site-packages/twisted/scripts/trial.py", line 616, in run
    test_result = trialRunner.run(suite)
  File "/usr/local/lib/python2.7/site-packages/twisted/trial/runner.py", line 959, in run
    return self._runWithoutDecoration(test, self._forceGarbageCollection)
  File "/usr/local/lib/python2.7/site-packages/twisted/trial/runner.py", line 1005, in _runWithoutDecoration
    result.done()
  File "/usr/local/lib/python2.7/site-packages/twisted/trial/reporter.py", line 717, in done
    self._printErrors()
  File "/usr/local/lib/python2.7/site-packages/twisted/trial/reporter.py", line 666, in _printErrors
    self._printExpectedFailure)
  File "/usr/local/lib/python2.7/site-packages/twisted/trial/reporter.py", line 638, in _printResults
    for reason, cases in self._groupResults(errors, formatter):
  File "/usr/local/lib/python2.7/site-packages/twisted/trial/reporter.py", line 624, in _groupResults
    key = formatter(*outcome)
  File "/usr/local/lib/python2.7/site-packages/twisted/trial/reporter.py", line 649, in _printExpectedFailure
    self._formatFailureTraceback(error))
  File "/usr/local/lib/python2.7/site-packages/twisted/trial/reporter.py", line 595, in _formatFailureTraceback
    fail.frames, frames = self._trimFrames(fail.frames), fail.frames
AttributeError: 'tuple' object has no attribute 'frames'
```

It would appear that the type signature in the patch asks for:

```
@type failure: A L{failure.Failure} or L{exceptions.AssertionError}
```

but it's actually an exc_info tuple.

I think test_standardLibraryCompatibilityFailure which was added passes because it doesn't have a strong enough assertion.

The TODO ends up in self._todos, but it will, as above, blow up when printed out. Haven't stared long enough to see where the integration test should go to exercise that.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_19"></a>|@exarkun set status to `closed`|
|-|-|

This change was released and the merge was not reverted.  The workflow for issues closed as fixed with a merge which are not actually fixed is to revert the merge when re-opening the issue.

At this point, too much time has passed to revert this merge.  So if the issue remains, please file a new ticket describing it.
