### ISSUE TITLE
mktap news is broken

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#4834]
|<img alt="doko's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| doko reported|
|-|-|
|Trac ID|trac#803|
|Type|defect|
|Created|2004-11-29 02:38:39Z|

<details><summary>Searchable metadata</summary>

```
trac-id__803 803
type__defect defect
reporter__doko doko
priority__high high
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__ 
keywords__core core
time__1101695919000000 1101695919000000
changetime__1101711447000000 1101711447000000
version__ 
owner__ 
cc__teratorn cc__doko
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="doko's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|doko commented|
|-|-|

```
#!html
<pre>
[forwarded from http://bugs.debian.org/278196]

the man page documents:

       apptype
              Can  be 'web', 'portforward', 'toc', 'coil', 'words', 'manhole',
              'im', 'news', 'socks', 'telnet', 'parent', 'sibling', 'ftp', and
              'mail'. Each of those support different options.

but:

$ mktap news
Traceback (most recent call last):
  File "/usr/bin/mktap", line 30, in ?
    run()
  File "/usr/lib/python2.3/site-packages/twisted/scripts/mktap.py", line 152, in run
    options.parseOptions(sys.argv[1:])
  File "/usr/lib/python2.3/site-packages/twisted/python/usage.py", line 209, in
parseOptions
    self.postOptions()
  File "/usr/lib/python2.3/site-packages/twisted/scripts/mktap.py", line 139, in
postOptions
    self.parseOptions(self.params)
  File "/usr/lib/python2.3/site-packages/twisted/python/usage.py", line 197, in
parseOptions
    self.subOptions = parser()
  File "/usr/lib/python2.3/site-packages/twisted/scripts/mktap.py", line 105, in
&lt;lambda>
    sc = [ [name, None, (lambda obj=module:obj.load().Options()),
  File "/usr/lib/python2.3/site-packages/twisted/python/plugin.py", line 61, in load
    return namedModule(self.module)
  File "/usr/lib/python2.3/site-packages/twisted/python/reflect.py", line 348,
in namedModule
    topLevel = __import__(name)
ImportError: No module named news
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="teratorn's avatar" src="https://avatars.githubusercontent.com/u/154069?s=50" width="50" height="50">](https://github.com/teratorn)|@teratorn commented|
|-|-|

```
#!html
<pre>
What twisted version is in /usr/lib/python2.3/site-packages/twisted/ ?

mktap news works for me using an SVN checkout.
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="doko's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|doko commented|
|-|-|

```
#!html
<pre>
this is version 1.3.0, as released.
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="teratorn's avatar" src="https://avatars.githubusercontent.com/u/154069?s=50" width="50" height="50">](https://github.com/teratorn)|@teratorn commented|
|-|-|

```
#!html
<pre>
appears to be fixed in SVN.
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
