### ISSUE TITLE
twisted.internet.tcp.BaseClient breaks t.i.t.Connection, by not providing an t.i.i.IHalfCloseableProtocol

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#4845]
|<img alt="lbruno's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| lbruno reported|
|-|-|
|Trac ID|trac#4845|
|Type|defect|
|Created|2011-02-02 12:50:11Z|

BaseClient calls the superclass' Connection.__init__ with a protocol = None, but Connection assumes that self.protocol is an IHalfCloseableProtocol and doesn't handle None.

I'm not sure how I'd write the code to handle this case; I'm new to twisted.

This happens when I'm using an ReconnectingClientFactory against an Asterisk Manager Interface, and I restart asterisk.

Thanks in advance!

This line sets up the error:

http://twistedmatrix.com/trac/browser/tags/releases/twisted-10.2.0/twisted/internet/tcp.py#L553

Line 500 is where it breaks:

```

2011-02-02 12:37:21+0000 [-] Log opened.
2011-02-02 12:37:21+0000 [-] twistd 10.2.0 (/var/www/calls/bin/python 2.5.2) starting up.
2011-02-02 12:37:21+0000 [-] reactor class: twisted.internet.selectreactor.SelectReactor.
2011-02-02 12:37:21+0000 [-] Starting factory <ename.ami.client.Factory instance at 0x1723200>
2011-02-02 12:37:56+0000 [MorbidPublishingClient,client] Unhandled Error
        Traceback (most recent call last):
          File "/var/www/calls/lib/python2.5/site-packages/twisted/application/app.py", line 311, in runReactorWithLogging
            reactor.run()
          File "/var/www/calls/lib/python2.5/site-packages/twisted/internet/base.py", line 1158, in run
            self.mainLoop()
          File "/var/www/calls/lib/python2.5/site-packages/twisted/internet/base.py", line 1170, in mainLoop
            self.doIteration(t)
          File "/var/www/calls/lib/python2.5/site-packages/twisted/internet/selectreactor.py", line 140, in doSelect
            _logrun(selectable, _drdw, selectable, method, dict)
        --- <exception caught here> ---
          File "/var/www/calls/lib/python2.5/site-packages/twisted/python/log.py", line 84, in callWithLogger
            return callWithContext({"system": lp}, func, *args, **kw)
          File "/var/www/calls/lib/python2.5/site-packages/twisted/python/log.py", line 69, in callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File "/var/www/calls/lib/python2.5/site-packages/twisted/python/context.py", line 59, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/var/www/calls/lib/python2.5/site-packages/twisted/python/context.py", line 37, in callWithContext
            return func(*args,**kw)
          File "/var/www/calls/lib/python2.5/site-packages/twisted/internet/selectreactor.py", line 156, in _doReadOrWrite
            self._disconnectSelectable(selectable, why, method=="doRead")
          File "/var/www/calls/lib/python2.5/site-packages/twisted/internet/posixbase.py", line 250, in _disconnectSelectable
            selectable.readConnectionLost(f)
          File "/var/www/calls/lib/python2.5/site-packages/twisted/internet/tcp.py", line 500, in readConnectionLost
            p = interfaces.IHalfCloseableProtocol(self.protocol, None)
        exceptions.TypeError: 'NoneType' object is not callable


```

<details><summary>Searchable metadata</summary>

```
trac-id__4845 4845
type__defect defect
reporter__lbruno lbruno
priority__lowest lowest
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__invalid invalid
component__core core
keywords__IHalfCloseableProtocol__BaseClient__TCPClient__Connection IHalfCloseableProtocol, BaseClient, TCPClient, Connection
time__1296651011000000 1296651011000000
changetime__1296724637000000 1296724637000000
version__None None
owner__lbruno lbruno
cc__it@...
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun set owner to lbruno|
|-|-|

From the traceback, it appears as though `interfaces.IHalfCloseableProtocol` is what's `None`, not `self.protocol`.  I don't know how this could happen, since `IHalfCloseableProtocol` is an interface that is always defined.

Would it be possible for you to put together a short, self-contained example which reproduces this problem?  Then we could investigate more easily.

**Comment by twisted-trac** [comment]
|<img alt="lbruno's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_2"></a>|lbruno set status to `closed`|
|-|-|

Yeah, an interface being None makes no sense. My earlier diagnostic was wrong, and the bug is caused by **my own code** returning None from my protocol's ``__getattr__``. Since the base class doesn't provide an __str__, I shot my own foot.

Sorry for wasting everyone's time.
