### ISSUE TITLE
Improve integration of SerialPort (via an endpoint)

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#4847]
|<img alt="brandl's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| brandl reported|
|-|-|
|Trac ID|trac#4847|
|Type|enhancement|
|Created|2011-02-04 11:14:08Z|
|Branch|https://github.com/twisted/twisted/tree/serialports-endpoint-4847-4|

There is no easy way to create a `SerialPort` instance and use it
with twistd (like e.g. `TCPServer`). It would be nice if the 
`SerialPort` could be treated in the same way, or at least 
similarly.

This can be accomplished by implementing a serial endpoint that
can be instantiated with `(server|client)FromString` (*). Use the
plugin framework and implement an appropriate string parser to
extend the existing machinery.

See also the discussion on the mailing list, starting with
http://twistedmatrix.com/pipermail/twisted-python/2011-January/023429.html

(*) I don't know if a serial port is more like a server or a client.
Maybe this depends on the application...?

Attachments:

* [serialports-endpoint-4847-4.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/b51/b5158f95432ecc33a8848231f253a20302e5a830/d43958182eac4588fcf6a7fec3e8e58fd9584048.patch) (13330 bytes) - added by mattice on 2014-05-12 04:42:37Z - patch on f2877a7

<details><summary>Searchable metadata</summary>

```
trac-id__4847 4847
type__enhancement enhancement
reporter__brandl brandl
priority__normal normal
milestone__ 
branch__branches_serialports_endpoint_4847_4 branches/serialports-endpoint-4847-4
branch_author__exarkun__ashfall__glyph exarkun, ashfall, glyph
status__new new
resolution__None None
component__core core
keywords__ 
time__1296818048000000 1296818048000000
changetime__1460531767655775 1460531767655775
version__None None
owner__ 
cc__detly cc__oberstet
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="ashfall's avatar" src="https://avatars.githubusercontent.com/u/1138873?s=50" width="50" height="50">](https://github.com/ashfall)|@ashfall set owner to @ashfall|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="ashfall's avatar" src="https://avatars.githubusercontent.com/u/1138873?s=50" width="50" height="50">](https://github.com/ashfall)<a name="note_3"></a>|@ashfall commented|
|-|-|

(In [34676]) Branching to 'serialports-endpoint-4847'

**Comment by twisted-trac** [comment]
|[<img alt="ashfall's avatar" src="https://avatars.githubusercontent.com/u/1138873?s=50" width="50" height="50">](https://github.com/ashfall)<a name="note_4"></a>|@ashfall removed owner|
|-|-|

[Build Results](http://buildbot.twistedmatrix.com/boxes-supported?branch=/branches/serialports-endpoint-4847)

A few points:

 * The imports become tricky if there isn't serial support in the system, I've used some workarounds to avoid them for now, let me know if it needs more work.

 * Also, in the build results, this error appears repeatedly:

```
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/home/buildslave/slaves/twisted/bot-idnar-debian/easy2.6debian/Twisted/install/lib/Twisted-12.1.0-py2.6-linux-x86_64.egg/twisted/internet/test/test_serialport.py", line 66, in test_connectionMadeLost
    port = DummySerialPort(SerialProtocol(), "", reactor=DoNothing())
exceptions.TypeError: __init__() takes exactly 11 non-keyword arguments (4 given)

twisted.internet.test.test_serialport.SerialPortTests.test_connectionMadeLost
-------------------------------------------------------------------------------
```

  But I'm not able to reproduce this locally. Not sure what's to be done here.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_5"></a>|@exarkun set owner to @ashfall|
|-|-|

Thanks!  Sorry about the long review delay.  I lost track of this ticket :(

When you started work on this, I said I couldn't think of any compelling reason to make the endpoint a client rather than a server.  Unfortunately, now I can.

`IStreamServerEndpoint.listen` is defined as returning a `Deferred` which fires with an `IListeningPort`.  The branch implements this method to fire the `Deferred` with a `SerialPort` instance, and `SerialPort` does not implement `IListeningPort`.  I see two options for addressing this:

  1. Create an `IListeningPort` implementation to use with serial ports.  This would probably be fairly simple, but I think it involves understanding and addressing reconnection semantics for serial ports (a somewhat convoluted topic with many platform-specific intricacies).  I suspect that eventually we _will_ want to address this, but perhaps it isn't the highest priority right now.
  2. Create an `IStreamClientEndpoint` implementation for serial ports, instead. (I recommend this one for now)

Apart from that, here are a few general review comments to consider, but which may not be directly actionable, depending on what code is left after choosing and implementing one of the above strategies:

  1. Some trailing whitespace is added and should be cleaned up
  1. Everything in test modules is already private, so you don't need to rename `StdioFactory` to `_StdioFactory`.
  1. When testing that parameters are passed properly, it's a good idea to give each of them different values.  If you pass 1 for each of timeout, xonxoff, and rtscts, then the tests can't really demonstrate that arguments are passed in the right order.  Maybe you swapped timeout and rtscts, but since they're both 1, who knows.
  1. It's probably okay to skip testing the private attributes on the endpoint.  It's sufficient to test that the actual `SerialPort` gets passed the right arguments, based on the arguments passed to `SerialPortEndpoint`.  The intermediate step of private attributes as storage for those values is an uninteresting implementation detail (you may see tests that do this, but they're either misguided or else using this testing approach because a better approach was too difficult in that particular case).
  1. Be sure to use something like `TestCase.patch` to do monkey-patching, so things get cleaned up.

Thanks again.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_6"></a>|@exarkun commented|
|-|-|

Oh, I forgot to mention - the strange exception you saw is related to the non-use of `TestCase.patch` in `test_serialPortInstanceParam`.  One you fix the latter, the former issue will disappear.

**Comment by twisted-trac** [comment]
|[<img alt="ashfall's avatar" src="https://avatars.githubusercontent.com/u/1138873?s=50" width="50" height="50">](https://github.com/ashfall)<a name="note_8"></a>|@ashfall removed owner|
|-|-|

[New build results](http://buildbot.twistedmatrix.com/boxes-supported?branch=/branches/serialports-endpoint-4847).

Replying to [exarkun](#note_5):

Thanks for the review.

>   1. Create an `IListeningPort` implementation to use with serial ports.  This would probably be fairly simple, but I think it involves understanding and addressing reconnection semantics for serial ports (a somewhat convoluted topic with many platform-specific intricacies).  I suspect that eventually we _will_ want to address this, but perhaps it isn't the highest priority right now.
Should I file a ticket for this, since it is something that needs to be done in the future?


>   3. When testing that parameters are passed properly, it's a good idea to give each of them different values.  If you pass 1 for each of timeout, xonxoff, and rtscts, then the tests can't really demonstrate that arguments are passed in the right order.  Maybe you swapped timeout and rtscts, but since they're both 1, who knows.
Sorry about that.

>   5. Be sure to use something like `TestCase.patch` to do monkey-patching, so things get cleaned up.
Done, and the exception went away. Thanks.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_9"></a>|@exarkun set owner to @ashfall|
|-|-|

> Should I file a ticket for this, since it is something that needs to be done in the future?

Sure, that'd be great.

> > When testing that parameters are passed properly, it's a good idea to give each of them different values. If you pass 1 for each of timeout, xonxoff, and rtscts, then the tests can't really demonstrate that arguments are passed in the right order. Maybe you swapped timeout and rtscts, but since they're both 1, who knows.
> Sorry about that.

No apology needed :)  However, I notice that the test in the branch still uses 0s for all three parameters?

Also, one other thing I noticed is that xonxoff and rtscts are both booleans, so we may as well use `True` and `False` instead of `1` and `0` for them.

One comment I forgot in the previous review was about the address passed to the factory's `buildProtocol`.  We should invent a new `SerialAddress` (along the lines of the other new addresses you've been adding) and use that here.

And lastly, the Deferred `connect` returns is still not firing with the right value.  It needs to fire with the protocol instance, not the `SerialPort` instance.

> > When testing that parameters are passed properly, it's a good idea to give each of them different values. If you pass 1 for each of timeout, xonxoff, and rtscts, then the tests can't really demonstrate that arguments are passed in the right order. Maybe you swapped timeout and rtscts, but since they're both 1, who knows.

I guess I didn't do a good job explaining the idea here, so let me try again.  Consider the following:

```python
class FooTests(TestCase):
    def setUp(self):
        self.foo = Foo(123)

    def test_bar(self):
        """
        Foo.bar creates a new Bar with the same parameters given to Foo's initializer.
        """
        bar = self.foo.bar()
        self.assertEqual(self.foo.x, bar.x)
```

This test is inadequate to accomplish its stated goal, because it relies on something it assumes `Foo.__init__` does, but which it never actually tests that it does.

Consider this implementation:

```python
class Bar:
    def __init__(self, x):
        self.x = x

class Foo:
    def __init__(self, x):
        self._x = 10

    def bar(self):
        return Bar(self._x)
```

This will pass the unit test, but not actually behave correctly.  While I think that your implementation of `SerialPortEndpoint` is correct (unlike the above code), the tests you have for it suffer from this problem.

To resolve this, make sure to verify `Bar.x` against the known good value.  For example:

```python
class FooTests(TestCase):
    expectedX = 123

    def setUp(self):
        self.foo = Foo(self.expectedX)

    def test_bar(self):
        """
        Foo.bar creates a new Bar with the same parameters given to Foo's initializer.
        """
        bar = self.foo.bar()
        self.assertEqual(self.expectedX, bar.x)
```

Thanks again!

**Comment by twisted-trac** [comment]
|[<img alt="ashfall's avatar" src="https://avatars.githubusercontent.com/u/1138873?s=50" width="50" height="50">](https://github.com/ashfall)<a name="note_10"></a>|@ashfall removed owner|
|-|-|

Thanks for the review.
Addressed the review comments.
[New build results](http://buildbot.twistedmatrix.com/boxes-supported?branch=/branches/serialports-endpoint-4847)

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_11"></a>|@exarkun set owner to @ashfall|
|-|-|

Thanks.

  1. Some trivial conflicts, please merge forward to resolve.
  1. in `test_rtscts`, there's a comment suggesting the default value for xonxoff is passed, which is soooort of true.  A value *is* passed, and it is the default.  But this is a bit in contradiction to a typical meaning for "the default value", which is not passing any value for the argument at all (as is done for rtscts in `test_xonxoff`.  I'd either drop the comment or drop the explicit `False` value for xonxoff.
  1. There's a missing test for the exception handling in `SerialPortEndpoint.connect`
  1. If the `serialport` module is not installed, `connect` will raise an exception instead of returning a Deferred.  Likewise if `buildProtocol` raises an exception.  These aren't common error conditions, but they should probably both result in a Deferred that fires with a failure instead of causing an exception to be raised by `connect`.  I'd be satisfied to see these addressed in a followup ticket, but you can fix them here too if you'd prefer.

**Comment by twisted-trac** [comment]
|[<img alt="ashfall's avatar" src="https://avatars.githubusercontent.com/u/1138873?s=50" width="50" height="50">](https://github.com/ashfall)<a name="note_12"></a>|@ashfall commented|
|-|-|

(In [35245]) Branching to 'serialports-endpoint-4847-2'

**Comment by twisted-trac** [comment]
|[<img alt="ashfall's avatar" src="https://avatars.githubusercontent.com/u/1138873?s=50" width="50" height="50">](https://github.com/ashfall)<a name="note_13"></a>|@ashfall removed owner|
|-|-|

Thanks for the review, changes made.  
[New build results](http://buildbot.twistedmatrix.com/boxes-supported?branch=/branches/serialports-endpoint-4847-2)

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_14"></a>|@exarkun commented|
|-|-|

(In [36523]) Branching to 'serialports-endpoint-4847-3'

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_15"></a>|@exarkun set owner to @ashfall|
|-|-|

There were some nasty conflicts caused by the Python 3 porting work.  I merged forward and resolved those for you.  Because of the Python 3 porting work, there's also some Python 3 related comments in this review.  Sorry!

  1. `implements` is now `implementer`.  You can see an example of the new spelling in `twisted/internet/address.py`.  All the uses of `implements` in Python 3-ported modules need to be replaced with `implementer`, and generally all new code should use `implementer`.  Since `twisted/internet/address.py` is a ported module, this needs to be done for `SerialAddress`.
  1. `twisted/internet/endpoints.py` is not a ported module, but the `implements` call in `SerialPortEndpoint` should probably be switched as well.
  1. There's some new helpers in trunk now, `successResultNow` and `failureResultNow`.  `failureResultNow` might be useful, for example, in `test_connectFailure`.  The current code is fine too, but the helper makes the code a bit nicer and shorter.
  1. It might be nice to have a test for the case where pyserial (or whatever that module is called) isn't installed.  In this case `connect` should return a `Deferred` that fails with an `ImportError`, I think.  Having a test that exercises this case would be nice.

Thanks!

**Comment by twisted-trac** [comment]
|[<img alt="ashfall's avatar" src="https://avatars.githubusercontent.com/u/1138873?s=50" width="50" height="50">](https://github.com/ashfall)<a name="note_16"></a>|@ashfall removed owner|
|-|-|

Replying to [exarkun](#note_15):


[Build results](http://buildbot.twistedmatrix.com/boxes-supported?branch=/branches/serialports-endpoint-4847-3)

Thanks!  
 
Made the changes.  
If there's a better way to deal with the imports in this endpoint, please do tell in the review.

**Comment by twisted-trac** [comment]
|[<img alt="tomprince's avatar" src="https://avatars.githubusercontent.com/u/283816?s=50" width="50" height="50">](https://github.com/tomprince)<a name="note_17"></a>|@tomprince set owner to @ashfall|
|-|-|

Have a look at `twisted.trial.test.test_reporter.AnsiColorizerTests` for an example if how to test the behavior of a module that may not be available.
  1. The line `endpoint._serialport = None` in `test_importError` is masking an `AttributeError` that gets raised if `connect` is called when pyserial isn't installed.
  1. It doesn't look like any of your tests require a working `twisted.internet.serialport` module, just that that module exists, so they should be able to be written so that they work even if pyserial isn't available. (i.e. creating a fake module as in `AnsiColorizerTests`)
  1. (minor) When docstrings are referring to instance attributes or arguments, they should be wrapped with `C{}`. There are a number of instances of this in the test docstrings.
  1. The class level comment about expected values isn't clear. Those values are the values passed in `setUp` when constructing the endpoint, thus what is expected in `test_serialPortInstanceParameters`. It would perhaps be clearer to just use the default arguments for all the tests except that one (and the others that test specific arguments), and move that block of definitions there.
  1. (optional) Use the new deferred helpers, to make the tests synchronous.
  1. There are some fairly straightforward merge conflicts.

Thanks again for your persistence. Please address the above and resubmit.

**Comment by twisted-trac** [comment]
|<img alt="mattice's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_19"></a>|mattice commented|
|-|-|

I've addressed 1,4 and 6 in comment 17, I think.

If someone would like to tackle the rest...

**Comment by twisted-trac** [comment]
|[<img alt="ashfall's avatar" src="https://avatars.githubusercontent.com/u/1138873?s=50" width="50" height="50">](https://github.com/ashfall)<a name="note_20"></a>|@ashfall removed owner|
|-|-|

Thanks for working on this!

For next time, please note that trac uses a space to separate keywords, not a comma. Also, when submitting for review, please un-assign (assign to the blank space at the top of the "assign to" list) so that it can be reviewed. (I made these changes for now).

Thanks again for taking interest in this, it's one of our almost-complete but still unmerged endpoint tickets, would be nice to see it merged.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_21"></a>|@glyph commented|
|-|-|

(In [43465]) Branching to serialports-endpoint-4847-4.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_22"></a>|@glyph commented|
|-|-|

We use keywords for workflow, and "endpoint" isn't a workflow state, so I'm removing it.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_23"></a>|@glyph set owner to mattice|
|-|-|

Hi mattice,

Thanks for your contribution.  Sorry for the slow pace of code reviews, we are endeavoring to speed up.

  1. [There are numerous test failures and style issues on the buildbot](https://buildbot.twistedmatrix.com/boxes-supported?branch=/branches/serialports-endpoint-4847-4).
  2. All the private attributes on `SerialPortEndpoint` seem superfluous. `test_constructorDefaultArgs` verifies them all, but to no particular effect; `test_serialPortInstanceParameters` just tests all the same stuff over again.  Also, as twistedchecker will point out, they're not documented, and they seem to be simply deferring to `SerialPort`; so why not just take `*args` and `**kw` and document it by saying that they're the same as for one of those classes?
  3. `SerialAddress` really ought to have some actual information in it.  For example, what's the name of the serial device?
  4. `test_connectFailure` seems overly broad.  You should test a more specific exception than `Exception`, since almost any kind of programming error will provoke this sort of error.
  5. `SerialPortEndpoint._serialport` needs a better explanation in its `@ivar`, and also a type.  What sort of hook is it?  How do the tests replace it?

The main issue here is the test failures and such.  Otherwise it looks like it's getting close.

**Comment by twisted-trac** [comment]
|<img alt="mattice's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_24"></a>|mattice commented|
|-|-|

I think [https://github.com/mmattice/twisted/tree/serialports-endpoint-4847-4] mostly resolves the 5 points in ticket:4847#comment:23

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_25"></a>|@exarkun commented|
|-|-|

I started to look at this but then I realized I don't know how to get code from a fork of Twisted on github into the upstream subversion repository (apart from via manual diff shoveling).

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_26"></a>|@glyph commented|
|-|-|

Replying to [exarkun](#note_25):
> I started to look at this but then I realized I don't know how to get code from a fork of Twisted on github into the upstream subversion repository (apart from via manual diff shoveling).

I moved the commits via automatic diff shoveling :).  Since I wasn't sure I'd have the time to explain how to do it, I at least recorded myself doing it so that at least someone might be able to puzzle it out.  Please bug me to explain later if it is not obvious from watching me fumble around in my terminal:

http://asciinema.org/a/14283

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_27"></a>|@glyph commented|
|-|-|

Build forced, although I don't think any of the buildbots have pyserial, unfortunately :-\.

**Comment by twisted-trac** [comment]
|<img alt="mattice's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|mattice removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="keturn's avatar" src="https://avatars.githubusercontent.com/u/83819?s=50" width="50" height="50">](https://github.com/keturn)|@keturn set owner to @keturn|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="keturn's avatar" src="https://avatars.githubusercontent.com/u/83819?s=50" width="50" height="50">](https://github.com/keturn)<a name="note_30"></a>|@keturn commented|
|-|-|

I get one test failure:

```
Traceback (most recent call last):
  File ".../twisted/twisted/internet/test/test_endpoints.py", line 2362, in test_connectFailure
    self.assertIsInstance(self.failureResultOf(d).value, SerialException)
  File ".../twisted/twisted/trial/_synctest.py", line 664, in assertIsInstance
    instance, classOrTuple, suffix))
twisted.trial.unittest.FailTest: OSError(2, 'No such file or directory') is not an instance of <class 'serial.serialutil.SerialException'>

twisted.internet.test.test_endpoints.SerialPortEndpointsTestCase.test_connectFailure
```

**Comment by twisted-trac** [comment]
|[<img alt="keturn's avatar" src="https://avatars.githubusercontent.com/u/83819?s=50" width="50" height="50">](https://github.com/keturn)<a name="note_31"></a>|@keturn commented|
|-|-|

1) Following up on the previous reviewer's comment about `SerialPortEndpoint._serialport`, it's now documented as "serialport module."

As only a *single* thing is used from that, the serialport.SerialPort class, I think it would be clearer to have a reference to just that class, rather than its module. Then the tests could use this where they currently [patch the serialport module instead](https://github.com/twisted/twisted/blob/4c253846971a561fea4159859a2fd4c83dba3afd/twisted/internet/test/test_endpoints.py#L2301).

2) SerialPortEndpoint's constructor says "@see: L{serialport.SerialPort}", and that tells us about `*args` and `**kwargs`, but I'm still not sure about deviceOrPortNumber. Is it a number or a name or a FilePath?

The generated SerialPort API docs are kind of confused due to platform-conditional stuff, but something somewhere should be referring me to the PySerial docs that actually tell me what these parameters mean. http://pyserial.sourceforge.net/pyserial_api.html

(That also means our abstraction is leaky; there's a conversation here about how far our duty to maintain this interface extends while it's a thin wrapper around an optional third-party dependency, but that's an existing property of SerialPort and in my opinion that conversation shouldn't block this ticket about the Endpoint.)

3) I'm unclear about the role of SerialAddress. It's not used to construct the SerialEndpoint. The endpoint doesn't retain a reference to it. It's created and passed to the protocolFactory.buildProtocol, but IProtocolFactory.buildProtocol isn't documented as taking an IAddress, it's documented as taking a (host, addr) tuple. Is that an incorrect specification on IProtocolFactory?

4) Does the existence of a SerialPortEndpoint mean the current SerialPort-using examples are not longer using best practices? If so, updating the current examples would be good. If not, is it time for a new example?

Overall I think this is code that does what an endpoint does, it improves significantly on API docstring coverage, and I look forward to using it.

**Comment by twisted-trac** [comment]
|[<img alt="keturn's avatar" src="https://avatars.githubusercontent.com/u/83819?s=50" width="50" height="50">](https://github.com/keturn)<a name="note_32"></a>|@keturn removed owner|
|-|-|

As for the test_endpoints.SerialPortEndpointsTestCase.test_connectFailure failure, it seems like the intent of this is to make sure the endpoint.connect() call does return a deferred in the failure case. I think the test specifies SerialException as a response to an earlier review's comment about "You should test a more specific exception than Exception," and SerialException is indeed more specific. However, IStreamClientEndpoint is documented as returning [ConnectError](http://twistedmatrix.com/documents/current/api/twisted.internet.error.ConnectError.html) on failure, so it should probably be one of those. I am not sure what Twisted best practice is on exception chaining is. twisted.internet.error.getConnectError may be appropriate here, as SerialError seems to conform to the (errno, message) argument signature that getConnectError expects.

I do think that should be "except Exception" instead of bare "except:", so as to not catch SystemExit, although a lot of the other code in endpoints seems to do this same thing.

(We also discovered this test passed for mattice and failed for me because pyserial did not maintain consistent behavior here between versions, which was marked as a [bug upstream](http://sourceforge.net/p/pyserial/bugs/156/) and will be fixed next release. On further reflection, though, I think that's beside the point, and endpoint.connect should return Twisted's ConnectError.)

**Comment by twisted-trac** [comment]
|<img alt="rnixx's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_33"></a>|rnixx commented|
|-|-|

Hi,

any news about this? Is there a chance this gets merged soon? I want to use t.a.i.ClientService with serial port, so the serial endpoint implementation would be quite useful now.
