### ISSUE TITLE
twisted.internet.process._listOpenFDs fails on FreeBSD because fdescfs isn't mounted by default

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#4881]
|<img alt="lewq's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| lewq reported|
|-|-|
|Trac ID|trac#4881|
|Type|defect|
|Created|2011-02-14 02:01:55Z|
|Branch|https://github.com/twisted/twisted/tree/fd-closer-4881|

The solution to this is to dynamically detect whether /dev/fd/* is reliable or not, by opening some files and checking.

This breaks 10.2 on FreeBSD.

Attachments:

* [patch.txt](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/a69/a69ae58c3bbe70e39be1c3a768fdbc8a99bbec6b/3f09e3af32b63927e59020b0a1e33673b70c36c8.txt) (8082 bytes) - added by lewq on 2011-02-14 19:45:51Z - This patch actually passes the regular tests as well as the new ones
* [patch.2.txt](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/a69/a69ae58c3bbe70e39be1c3a768fdbc8a99bbec6b/a6129210bf0f9107ff4e36a5eec81c191eeecc71.txt) (8903 bytes) - added by lewq on 2011-02-14 19:50:47Z - With docstrings
* [close-devnull-after-checking-patch.txt](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/a69/a69ae58c3bbe70e39be1c3a768fdbc8a99bbec6b/4a504030f5c0f6e71b83367e368a1b9ee678d142.txt) (1478 bytes) - added by lewq on 2011-03-23 16:10:32Z - Attaching a patch which forces the explicit closing of the file pointer to /dev/null in _checkDevFDSanity in case that's hanging around and polluting the list of file descriptors somehow (although it shouldn't cause three extra FDs).

<details><summary>Searchable metadata</summary>

```
trac-id__4881 4881
type__defect defect
reporter__lewq lewq
priority__normal normal
milestone__ 
branch__branches_fd_closer_4881 branches/fd-closer-4881
branch_author__lewq lewq
status__closed closed
resolution__fixed fixed
component__core core
keywords__ 
time__1297648915000000 1297648915000000
changetime__1302661913000000 1302661913000000
version__None None
owner__lewq lewq
cc__exarkun cc__jesstess cc__dustin
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="lewq's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_1"></a>|lewq commented|
|-|-|

Please review the attached patch, it passes the tests.

Still needs doc-strings on the classes and functions though.

**Comment by twisted-trac** [comment]
|<img alt="lewq's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_2"></a>|lewq commented|
|-|-|

(I.e. please sanity check my approach. If it's right, I'll tidy it up and submit it for  full review).

**Comment by twisted-trac** [comment]
|<img alt="lewq's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_3"></a>|lewq commented|
|-|-|

Please review patch.2.txt :-)

**Comment by twisted-trac** [comment]
|<img alt="lewq's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_4"></a>|lewq commented|
|-|-|

Explanation of this issue and a workaround:

Twisted 10.2 added an optimisation which assumes that ```/dev/fd/*``` contains the current process's open file descriptors. On FreeBSD this is only true if you run ```mount -t fdescfs null /dev/fd```.

If you are running Twisted 10.2 on FreeBSD you should add that to your fstab so that it survives a reboot.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_6"></a>|@exarkun commented|
|-|-|

(In [30903]) Branching to 'fd-closer-4881'

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_7"></a>|@exarkun commented|
|-|-|

(In [30904]) Apply patch.2.txt

refs [#4881](https://github.com/twisted/twisted/issues/4881)

**Comment by twisted-trac** [comment]
|[<img alt="lvh's avatar" src="https://avatars.githubusercontent.com/u/97816?s=50" width="50" height="50">](https://github.com/lvh)<a name="note_9"></a>|@lvh commented|
|-|-|

Hi! Thanks for your patch :-)

 1. Twisted coding standard: should be 3 empty lines between the functions.
 2. "Instanciate a (testable) _FDDetector which actually does the work." Instanciate -> instantiate
 3. There's already some bare excepts there that shouldn't have been, but I think your patch adds a new one. It should probably catch a specific exception. I'm thinking OSError.
 4. In `_checkDevFDSanity`, why is the opened /dev/null assigned to a name? It doesn't seem to be used.
 5. FDDetectorTest.save_resource_module also has a bare except.

Everything else looks great :) Thanks again!

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun set owner to @exarkun<br>@exarkun set status to `assigned`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_11"></a>|@exarkun commented|
|-|-|

(In [31047]) Insert some vertical whitespace

refs [#4881](https://github.com/twisted/twisted/issues/4881)

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_12"></a>|@exarkun commented|
|-|-|

(In [31048]) Insert some vertical whitespace

refs [#4881](https://github.com/twisted/twisted/issues/4881)

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_13"></a>|@exarkun commented|
|-|-|

(In [31055]) Document FDDetectorTest attributes, rename some methods to conform to convention, simplify tests with addCleanup, fix some extra indentation

refs [#4881](https://github.com/twisted/twisted/issues/4881)

**Comment by twisted-trac** [comment]
|<img alt="lewq's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_14"></a>|lewq commented|
|-|-|

# In _checkDevFDSanity, why is the opened /dev/null assigned to a name? It doesn't seem to be used. 

```
        fp = self.openfile("/dev/null", "r")
        end = self.listdir("/dev/fd")
```

If the open file were not assigned, it would have zero references and then might it get GC'd before listdir is run?

JP, your concern that _listOpenFDs doesn't actually get set is because:

```
def _setFDImplementation():
    [...]
    _listOpenFDs = detector._getImplementation()
```

... only sets _listOpenFDs in the function-local scope. The addition of the 'global' keyword at the top of the function should fix this, right? I'll test it by checking the identity of the function in a unit test.

**Comment by twisted-trac** [comment]
|<img alt="lewq's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_15"></a>|lewq commented|
|-|-|

NB: If fdescfs on FreeBSD gets (un)mounted during the running of a Twisted program, it would be nice for us to be checking os.path.ismount on /dev/fd. This is a future correctness improvement.

**Comment by twisted-trac** [comment]
|<img alt="lewq's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_16"></a>|lewq commented|
|-|-|

Passing tests, see http://buildbot.twistedmatrix.com/boxes-supported?branch=/branches/fd-closer-4881

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_17"></a>|@glyph set owner to @glyph<br>@glyph set status to `new`|
|-|-|

Reviewing.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_18"></a>|@glyph commented|
|-|-|

One thing I can see that needs some fixing is that twisted.internet.process is now imported by test_process.  The things that test_process tests are implemented by modules other than twisted.internet.process on Windows, which is why it pokes the reactor.  See this failure - http://buildbot.twistedmatrix.com/builders/winxp32-py2.5/builds/672/steps/iocp/logs/problems

```
[ERROR]
Traceback (most recent call last):
  File "C:\twistedbot\winxp32-py2.5-select\Twisted\twisted\trial\runner.py", line 575, in loadPackage
    module = modinfo.load()
  File "C:\twistedbot\winxp32-py2.5-select\Twisted\twisted\python\modules.py", line 383, in load
    return self.pathEntry.pythonPath.moduleLoader(self.name)
  File "C:\twistedbot\winxp32-py2.5-select\Twisted\twisted\python\reflect.py", line 464, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "C:\twistedbot\winxp32-py2.5-select\Twisted\twisted\python\reflect.py", line 400, in _importAndCheckStack
    return __import__(importName)
  File "C:\twistedbot\winxp32-py2.5-select\Twisted\twisted\internet\test\test_process.py", line 25, in <module>
    from twisted.internet import process
  File "C:\twistedbot\winxp32-py2.5-select\Twisted\twisted\internet\process.py", line 103, in <module>
    detectLinuxBrokenPipeBehavior()
  File "C:\twistedbot\winxp32-py2.5-select\Twisted\twisted\internet\process.py", line 93, in detectLinuxBrokenPipeBehavior
    reads, writes, exes = select.select([w], [], [], 0)
select.error: (10038, 'An operation was attempted on something that is not a socket')

twisted.internet.test.test_process
```

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_19"></a>|@glyph set owner to lewq|
|-|-|

  1. `FDDetectorTest` is missing a couple of docstrings.  `getpid`, `listdir`and `setUp`.
  2. `FakeResourceModule` is missing a docstring for `getrlimit`.
  3. Is that TODO still valid?  If it is, file a ticket and link to it.  Otherwise just delete it.
  4. `_resourceFDImplementation` should note that on OS X, we _should_ be using one of the other implementations, but if we are on some platform which returns a similar value, we should not actually try to close all those FDs.
  5. You're wrapping docstring lines a bit early in many places.  Since I know you're a vim user: Vjgqq on your docstring paragraphs to rewrap them, with the appropriate number of 'j's :).
  6. `_FDDetector._listOpenFDs` needs a docstring.
  7. Some `@ivar`s for listdir, getpid, openfile on that class would be useful as well.
  8. `FDDetector`'s docstring should be modified so it doesn't refer to "the above implementations", since the implementations are actually below, and members of the class.  Write a docstring that explains, from scratch, why we need such a thing.  It might make sense to change the name to `_OpenFDDetector`, too; I leave that to you, though.
  9. `_defFDImplementation` could use a reference of some kind; if you can find a document to link to that would be great.
  10. You need to [write a NEWS file](http://twistedmatrix.com/trac/wiki/ReviewProcess#Newsfiles).

Aside from the functional issue raised in the previous comment, this actually looks pretty good; these are mostly minor maintenance documentation issues.  I'd like to re-review just to get a second set of eyes on those test results, but that's all; we should be able to merge it quickly thereafter.

**Comment by twisted-trac** [comment]
|<img alt="lewq's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_20"></a>|lewq commented|
|-|-|

http://buildbot.twistedmatrix.com/boxes-supported?branch=/branches/fd-closer-4881 appears to be working nicely now, please review :-)

**Comment by twisted-trac** [comment]
|[<img alt="lvh's avatar" src="https://avatars.githubusercontent.com/u/97816?s=50" width="50" height="50">](https://github.com/lvh)|@lvh removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|<img alt="lewq's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_22"></a>|lewq commented|
|-|-|

I've addressed all of the issues in comment 19, by the way.

**Comment by twisted-trac** [comment]
|[<img alt="jesstess's avatar" src="https://avatars.githubusercontent.com/u/188336?s=50" width="50" height="50">](https://github.com/jesstess)<a name="note_23"></a>|@jesstess set owner to lewq|
|-|-|

Thanks for sticking with this, lewq!

+        See: http://www.freebsd.org/cgi/man.cgi?fdescfs 

Use @see.

Other than that, I agree that the builds look fine and [the FreeBSD build](http://buildbot.twistedmatrix.com/builders/freebsd-8.1-amd64/builds/118) looks better.

Please merge!

**Comment by twisted-trac** [comment]
|<img alt="lewq's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_24"></a>|lewq set status to `closed`|
|-|-|

(In [31322]) Merge fd-closer-4881: Fix spawnProcess on FreeBSD.

Author: lewq
Reviewer: exarkun, glyph, jesstess, lvh
Fixes: [#4881](https://github.com/twisted/twisted/issues/4881)

twisted.internet.process now detects the most appropriate mechanism to use for
detecting the open file descriptors on a system, getting Twisted working on
FreeBSD even when fdescfs is not mounted.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_25"></a>|@glyph commented|
|-|-|

So, I'm not reopening this, because it's [not an issue on the buildbot](http://buildbot.twistedmatrix.com/builders/osx10.6-py2.6-select/builds/1131), but at least on my local mac, I see this:

```
[ERROR]
Traceback (most recent call last):
  File "/Domicile/glyph/Downloads/Twisted-11.0.0pre1/twisted/internet/_baseprocess.py", line 60, in maybeCallProcessEnded
    proto.processEnded(Failure(reason))
  File "/Domicile/glyph/Downloads/Twisted-11.0.0pre1/twisted/internet/test/test_process.py", line 289, in processEnded
    checkOutput("".join(self.output))
  File "/Domicile/glyph/Downloads/Twisted-11.0.0pre1/twisted/internet/test/test_process.py", line 276, in checkOutput
    self.assertEquals('[0, 1, 2, 3]', output)
twisted.trial.unittest.FailTest: not equal:
a = '[0, 1, 2, 3]'
b = '[0, 1, 2, 3, 6, 7, 8]'


twisted.internet.test.test_process.PTYProcessTestsBuilder_CFReactor.test_openFileDescriptors
twisted.internet.test.test_process.PTYProcessTestsBuilder_SelectReactor.test_openFileDescriptors
twisted.internet.test.test_process.ProcessTestsBuilder_CFReactor.test_openFileDescriptors
twisted.internet.test.test_process.ProcessTestsBuilder_SelectReactor.test_openFileDescriptors
```

Any idea what that might be about?

**Comment by twisted-trac** [comment]
|<img alt="lewq's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_26"></a>|lewq commented|
|-|-|

Not sure, what's the configuration difference between buildbot and your Mac?  Is it the same version of the OS?  Can you check whether process.detector._listOpenFDs.func_name is the same on the BuildBot vs your Mac?

**Comment by twisted-trac** [comment]
|<img alt="lewq's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_27"></a>|lewq commented|
|-|-|

(After running _listOpenFDs() at least once so that it does the detection)

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_29"></a>|@exarkun commented|
|-|-|

I filed [#5008](https://github.com/twisted/twisted/issues/5008) for the remaining /dev/null issue.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_30"></a>|@exarkun commented|
|-|-|

This was sort of a duplicate of [#4747](https://github.com/twisted/twisted/issues/4747), but that ticket also talks about one more shortcoming of the unit tests.
