### ISSUE TITLE
Trial with wx reactor fails with StopIteration

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#4884]
|<img alt="psykidellic's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| psykidellic reported|
|-|-|
|Trac ID|trac#4884|
|Type|enhancement|
|Created|2011-02-14 19:18:04Z|
|Branch|https://github.com/twisted/twisted/tree/wxreactor-trial-4884|

Running the Twisted test case with:

trial --reactor wx twisted

stops at StdioClientTests:test_bang with StopIteration

Attachments:

* [trialwithex.output](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/b45/b45798042cd43f220a9eb3a45156c84288f3ef51/3d79a6df32ff62b9625c67c7604e75cbc796f936.output) (4589 bytes) - added by psykidellic on 2011-02-14 19:19:11Z - Output of trial with wx reactor

<details><summary>Searchable metadata</summary>

```
trac-id__4884 4884
type__enhancement enhancement
reporter__psykidellic psykidellic
priority__normal normal
milestone__ 
branch__branches_wxreactor_trial_4884 branches/wxreactor-trial-4884
branch_author__itamarst itamarst
status__new new
resolution__None None
component__core core
keywords__wxreactor wxreactor
time__1297711084000000 1297711084000000
changetime__1298394044000000 1298394044000000
version__None None
owner__ 
cc__psykidellic
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)<a name="note_1"></a>|@itamarst commented|
|-|-|

(In [30824]) Branching to 'wxreactor-trial-4884'

**Comment by twisted-trac** [comment]
|<img alt="psykidellic's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_2"></a>|psykidellic commented|
|-|-|

Running the test on Mac OS X 10.5 with Python 2.6 and the latest wx 2.8.11. It initial fails at:

```
    testSimpleExpression ...                                          [SKIPPED]
    testTripleQuoteLineContinuation ...                               [SKIPPED]
    test_interruptDuringContinuation ...                              [SKIPPED]
  ManholeLoopbackStdio
    testClassDefinition ...                                             [ERROR]
                                            [ERROR]
Bus error
```

I skipped the whole manhole test and now it fails at 

```
twisted.conch.test.test_recvline
  Arrows
    testBackspace ...                                                      [OK]
    testDelete ...                                                         [OK]
    testEnd ...                                                            [OK]
    testHome ...                                                           [OK]
    testHorizontalArrows ...                                               [OK]
    testInsert ...                                                         [OK]
    testNewline ...                                                        [OK]
    testPrintableCharacters ...                                            [OK]
    testTypeover ...                                                       [OK]
    testVerticalArrows ...                                                 [OK]
  HistoricRecvlineLoopbackSSH
    testDownArrow ...                                                 [SKIPPED]
    testUpArrow ...                                                   [SKIPPED]
  HistoricRecvlineLoopbackStdio
    testDownArrow ...                                                   [ERROR]
                                                  [ERROR]
Bus error
```

As suggested by exarkun I will now set up GDB and try to track it down.

**Comment by twisted-trac** [comment]
|<img alt="psykidellic's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_3"></a>|psykidellic commented|
|-|-|

Now running with GDB I see:

```
Program received signal EXC_BAD_ACCESS, Could not access memory.
Reason: KERN_PROTECTION_FAILURE at address: 0x00000000
[Switching to process 5595 thread 0x1e07]
0x022d2295 in wxCriticalSection::Enter ()
```

I have no clue about that. I will read more but would that be a bug with wx or our threaded reactor? I can then pursue the relevant library.

I dont have Linux handily available so I will try this out tomorrow from work on my Linux box too.

**Comment by twisted-trac** [comment]
|<img alt="psykidellic's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_4"></a>|psykidellic commented|
|-|-|

Doing bt:

```
#0  0x01c12295 in wxCriticalSection::Enter ()
#1  0x01c1d06b in wxEvtHandler::AddPendingEvent ()
#2  0x015ccf3e in _wrap_PostEvent (args=0x158a5828, kwargs=0x160398a0) at /BUILD/_build_/install-root/usr/local/lib/wxPython-unicode-2.8.11.0/include/wx-2.8/wx/event.h:2570
#3  0x00297d6e in PyEval_EvalFrameEx ()
#4  0x00299e9d in PyEval_EvalCodeEx ()
#5  0x00297f0c in PyEval_EvalFrameEx ()
#6  0x00299e9d in PyEval_EvalCodeEx ()
#7  0x00297f0c in PyEval_EvalFrameEx ()
#8  0x00299e9d in PyEval_EvalCodeEx ()
#9  0x00216a36 in function_call ()
#10 0x001e5315 in PyObject_Call ()
#11 0x00295aec in PyEval_EvalFrameEx ()
#12 0x00299e9d in PyEval_EvalCodeEx ()
#13 0x00216a36 in function_call ()
#14 0x001e5315 in PyObject_Call ()
#15 0x00295aec in PyEval_EvalFrameEx ()
#16 0x002986a6 in PyEval_EvalFrameEx ()
#17 0x002986a6 in PyEval_EvalFrameEx ()
#18 0x00299e9d in PyEval_EvalCodeEx ()
#19 0x00216a36 in function_call ()
#20 0x001e5315 in PyObject_Call ()
#21 0x001f78e6 in instancemethod_call ()
#22 0x001e5315 in PyObject_Call ()
#23 0x0029217e in PyEval_CallObjectWithKeywords ()
#24 0x002d39d6 in t_bootstrap ()
#25 0x910b5155 in _pthread_start ()
#26 0x910b5012 in thread_start ()
```

**Comment by twisted-trac** [comment]
|<img alt="psykidellic's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_5"></a>|psykidellic commented|
|-|-|

Running the whole test on Ubuntu 10.04, I got stuck at the end and trial never exited.

```
-------------------------------------------------------------------------------
Ran 6845 tests in 144.347s

FAILED (skips=437, expectedFailures=18, failures=1, errors=5, successes=6389)










^C



^C^C^C




^C^C^C^C
```


I had to: kill -9 the process. Any thoughts on how can I debug it?

More info on my system:

```
Python 2.6.5 (r265:79063, Apr 16 2010, 13:09:56) 
[GCC 4.4.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import wx
>>> wx.__version__
'2.8.10.1'
```
