### ISSUE TITLE
Replace uses of twisted.python.reflect.allYourBase with inspect.getmro

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#4928]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#4928|
|Type|enhancement|
|Created|2011-03-07 16:00:44Z|
|Branch|https://github.com/twisted/twisted/tree/allyourbase-4928|

These functions are not exactly the same, but the switch should be pretty easy in most cases.  `getmro` is several times faster than `allYourBase` because it knows about `__mro__`.  It also takes care of duplication in a diamond inheritance hierarchy, which at least one caller of `allYourBase` doesn't realize it cares about (`Failure` doesn't break because of the duplication, but it ends up doing extra work).

Maybe we can eventually deprecate `allYourBase` and `accumulateBases`, too.

Attachments:

* [4928-stop-using-allyourbase.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/74f/74f5c11138cdb6f32822f4120e4f4f9d027d3ebb/250172482e46269fe049ba9845b73472cabe0bfa.patch) (1708 bytes) - added by ironfroggy on 2011-03-13 02:07:43Z - Patch to remove calls to allYourBase
* [4928-stop-using-allyourbase-1.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/74f/74f5c11138cdb6f32822f4120e4f4f9d027d3ebb/5bc50ee432b0a09c0e9e024e1d70918c2989f98a.patch) (1698 bytes) - added by binjured on 2011-03-14 19:16:36Z - Proper use of getmro()

<details><summary>Searchable metadata</summary>

```
trac-id__4928 4928
type__enhancement enhancement
reporter__exarkun exarkun
priority__normal normal
milestone__ 
branch__branches_allyourbase_4928 branches/allyourbase-4928
branch_author__lvh lvh
status__closed closed
resolution__fixed fixed
component__core core
keywords__easy easy
time__1299513644000000 1299513644000000
changetime__1300206129000000 1300206129000000
version__None None
owner__lvh lvh

```
</details>

**Comment by twisted-trac** [comment]
|<img alt="ironfroggy's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_3"></a>|ironfroggy commented|
|-|-|

The only place the attached patch does not fix is in twisted.persisted, which [#3843](https://github.com/twisted/twisted/issues/3843) calls to deprecate. That is also the only usage of the extra parameter to allYourBase(). Is it required for this ticket to fix the code in a module that is being deprecated?

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_4"></a>|@exarkun commented|
|-|-|

Thanks ironfroggy!  Leaving the deprecated code alone is fine.  It's good enough that we'll eventually delete it. :)

(not a review, just answering that question)

**Comment by twisted-trac** [comment]
|[<img alt="djfroofy's avatar" src="https://avatars.githubusercontent.com/u/89760?s=50" width="50" height="50">](https://github.com/djfroofy)|@djfroofy set owner to @djfroofy<br>@djfroofy set status to `assigned`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="lvh's avatar" src="https://avatars.githubusercontent.com/u/97816?s=50" width="50" height="50">](https://github.com/lvh)|@lvh set owner to @lvh<br>@lvh set status to `new`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="lvh's avatar" src="https://avatars.githubusercontent.com/u/97816?s=50" width="50" height="50">](https://github.com/lvh)<a name="note_7"></a>|@lvh commented|
|-|-|

(In [31015]) Branching to 'allyourbase-4928'

**Comment by twisted-trac** [comment]
|[<img alt="lvh's avatar" src="https://avatars.githubusercontent.com/u/97816?s=50" width="50" height="50">](https://github.com/lvh)<a name="note_8"></a>|@lvh set status to `assigned`|
|-|-|

Patch looks good, waiting for http://buildbot.twistedmatrix.com/boxes-supported?branch=/branches/allyourbase-4928 to not blow up and then I'll merge it. Works on my box at least, and patch looks pretty benign.

Thanks for your contribution!

**Comment by twisted-trac** [comment]
|[<img alt="lvh's avatar" src="https://avatars.githubusercontent.com/u/97816?s=50" width="50" height="50">](https://github.com/lvh)<a name="note_9"></a>|@lvh set status to `closed`|
|-|-|

(In [31020]) allYourBase replaced with inspect.getmro

Author: ironfroggy
Reviewer: lvh
Fixes: [#4928](https://github.com/twisted/twisted/issues/4928)

**Comment by twisted-trac** [comment]
|[<img alt="lvh's avatar" src="https://avatars.githubusercontent.com/u/97816?s=50" width="50" height="50">](https://github.com/lvh)<a name="note_10"></a>|@lvh set status to `reopened`|
|-|-|

(In [31023]) Reverting 31020, apparently *does* fail on some buildbots.

Reopens: [#4928](https://github.com/twisted/twisted/issues/4928)

**Comment by twisted-trac** [comment]
|[<img alt="lvh's avatar" src="https://avatars.githubusercontent.com/u/97816?s=50" width="50" height="50">](https://github.com/lvh)<a name="note_11"></a>|@lvh set owner to ironfroggy<br>@lvh set status to `new`|
|-|-|

```
[ERROR]
Traceback (most recent call last):
  File "/var/lib/buildbot/bot-bigdogcloud2/lucid64-python2.6-select/Twisted/twisted/trial/test/test_reporter.py", line 1236, in test_subunitWithoutAddExpectedFailureInstalled
    self.removeMethod(reporter.TestProtocolClient, 'addExpectedFailure')
  File "/var/lib/buildbot/bot-bigdogcloud2/lucid64-python2.6-select/Twisted/twisted/trial/test/test_reporter.py", line 1222, in removeMethod
    for base in [klass] + getmro(klass):
exceptions.TypeError: can only concatenate list (not "tuple") to list
```

So getmro returns  a tuple, and you can't concat that to a list.

My suggestion:
```
for base in [klass] + list(getmro(klass)):
```

Or possibly:
```
bases = [klass]
bases.extend(getmro(klass))
for base in bases:
```

**Comment by twisted-trac** [comment]
|[<img alt="lvh's avatar" src="https://avatars.githubusercontent.com/u/97816?s=50" width="50" height="50">](https://github.com/lvh)<a name="note_12"></a>|@lvh commented|
|-|-|

Okay so scratch that, aumary told me that you should just use getmro(klass) since it already includes the class itself.

**Comment by twisted-trac** [comment]
|[<img alt="lvh's avatar" src="https://avatars.githubusercontent.com/u/97816?s=50" width="50" height="50">](https://github.com/lvh)<a name="note_13"></a>|@lvh commented|
|-|-|

There is of course the caveat that maybe there exists code that appends that output to a list (in fact that seems plausible) so perhaps it should be list(getmro(x))

**Comment by twisted-trac** [comment]
|[<img alt="lvh's avatar" src="https://avatars.githubusercontent.com/u/97816?s=50" width="50" height="50">](https://github.com/lvh)<a name="note_14"></a>|@lvh commented|
|-|-|

We figured out the intermittent failure: tests were being skipped due to dependence on Subunit which was not installed on most slaves and my own machine which is why I was convinced it wasn't broken. Fix is still identical as mentioned in last comment

**Comment by twisted-trac** [comment]
|[<img alt="lvh's avatar" src="https://avatars.githubusercontent.com/u/97816?s=50" width="50" height="50">](https://github.com/lvh)<a name="note_15"></a>|@lvh commented|
|-|-|

[#4946](https://github.com/twisted/twisted/issues/4946) is now blocking on this so it'd be cool if someone could fix it, I have some reviews to do right now so I can't do it for the moment.

**Comment by twisted-trac** [comment]
|<img alt="binjured's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_16"></a>|binjured commented|
|-|-|

Done. (see attached)

**Comment by twisted-trac** [comment]
|[<img alt="lvh's avatar" src="https://avatars.githubusercontent.com/u/97816?s=50" width="50" height="50">](https://github.com/lvh)<a name="note_17"></a>|@lvh set owner to @lvh<br>@lvh set status to `assigned`|
|-|-|

http://buildbot.twistedmatrix.com/builders/lucid64-py2.6-select/builds/667

Yaay buildbot agrees it is no longer broken. Thanks binjured!

**Comment by twisted-trac** [comment]
|[<img alt="lvh's avatar" src="https://avatars.githubusercontent.com/u/97816?s=50" width="50" height="50">](https://github.com/lvh)<a name="note_18"></a>|@lvh set status to `closed`|
|-|-|

(In [31049]) twisted.python.reflect.allYourBase replaced by inspect.getmro

Author: ironfroggy, binjured
Reviewer: lvh
Fixes: [#4928](https://github.com/twisted/twisted/issues/4928)

**Comment by twisted-trac** [comment]
|<img alt="amaury's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_19"></a>|amaury commented|
|-|-|

One more nit: in failure.py, `self.parents` now contains the initial class *twice*. For example:
```
>>> Failure(Exception()).parents
['exceptions.Exception', 'exceptions.BaseException', '__builtin__.object', 'exceptions.Exception']
```
It's not very important (`parents` is only used in a statement `if err in self.parents:`), but it's not optimal.

**Comment by twisted-trac** [comment]
|[<img alt="lvh's avatar" src="https://avatars.githubusercontent.com/u/97816?s=50" width="50" height="50">](https://github.com/lvh)<a name="note_20"></a>|@lvh commented|
|-|-|

Good call. Made [#4957](https://github.com/twisted/twisted/issues/4957).
