### ISSUE TITLE
Remove cmp usage in 'conch' and 'internet'

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#5102]
|<img alt="facundobatista's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| facundobatista reported|
|-|-|
|Trac ID|trac#5102|
|Type|enhancement|
|Created|2011-05-10 20:40:24Z|
|Branch|https://github.com/twisted/twisted/tree/cmp-conch-internet-5102|

The attached patch removes `cmp` and `__cmp__` usage from three modules:

  * twisted/conch/ssh/factory.py
  * twisted/internet/defer.py
  * twisted/internet/task.py

All the changes are tested directly or indirectly.

Attachments:

* [remove-cmp-01a.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/051/0519a3b8d19f6d01501da1960c19385b5e938f86/b9de2f04f82170628ca4c6d580afdd96cdbaa094.patch) (2187 bytes) - added by facundobatista on 2011-05-10 20:40:48Z - 
* [remove-cmp-01b.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/051/0519a3b8d19f6d01501da1960c19385b5e938f86/d1b4b5e0cfdadb3d8b7cc5fb7166d82e59e2e442.patch) (5733 bytes) - added by facundobatista on 2011-07-02 19:03:51Z - 

<details><summary>Searchable metadata</summary>

```
trac-id__5102 5102
type__enhancement enhancement
reporter__facundobatista facundobatista
priority__normal normal
milestone__Python_3_x Python-3.x
branch__branches_cmp_conch_internet_5102 branches/cmp-conch-internet-5102
branch_author__facundobatista facundobatista
status__closed closed
resolution__fixed fixed
component__core core
keywords__py3k py3k
time__1305060024000000 1305060024000000
changetime__1484651238016977 1484651238016977
version__None None
owner__facundobatista facundobatista
cc__thijs
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_2"></a>|@therve set owner to facundobatista|
|-|-|

I may be wrong, but the change in FirstError remove absolute ordering: cmp provides sort, whereas eq/ne don't.

**Comment by twisted-trac** [comment]
|<img alt="facundobatista's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_3"></a>|facundobatista set owner to @therve|
|-|-|

therve: you're right, but FirstError doesn't seem to have the semantics for ordering: there're specific tests for FirstError comparison and they check equality and not equality, not ordering (note also that there's no documentation for this, and even the docstring for __cmp__ talks about "equality").

However, I can add tests and code for this, but are we sure that this is ok?

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_5"></a>|@therve removed owner|
|-|-|

It feels that the indexes could provide ordering. Anyway, I don't know that part of the code enough to tell.

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_7"></a>|@thijstriemstra commented|
|-|-|

(In [32115]) Branching to 'cmp-conch-internet-5102'

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_8"></a>|@thijstriemstra commented|
|-|-|

(In [32116]) apply remove-cmp-01a.patch and add news files, refs [#5102](https://github.com/twisted/twisted/issues/5102)

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_9"></a>|@thijstriemstra commented|
|-|-|

At least the [buildbot](http://buildbot.twistedmatrix.com/builders/lucid64-py2.6-select/builds/1005) is happy. Can anyone respond to [comment:3] with more knowledge about that part of the code?

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_10"></a>|@glyph set owner to facundobatista|
|-|-|

Looks good, but to respond to comment 3: making changes to `FirstError`'s sort ordering _is_ a change in behavior, and therefore an incompatible change.  Ordering isn't important, but maybe somebody was relying on it.  Please add the mess of requisite methods to preserve this behavior, at least for now.  (It is OK to deprecate them.)

(For what it's worth, this strikes me as a very silly area of Python's changes; `__cmp__` was much more expressive, compact, and harder to get wrong than the mess of `__eq__` `__ne__` `__gt__` `__ge__` etc.)

**Comment by twisted-trac** [comment]
|<img alt="facundobatista's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_12"></a>|facundobatista removed owner|
|-|-|

Added code (and tests) for ```FirstError```'s ordering, see 'b' version of the patch.

**Comment by twisted-trac** [comment]
|[<img alt="cyli's avatar" src="https://avatars.githubusercontent.com/u/223200?s=50" width="50" height="50">](https://github.com/cyli)<a name="note_13"></a>|@cyli set owner to facundobatista|
|-|-|

Thanks for working on this facundobatista!

I see two problems with this patch:

  1.  There is already a `twisted.test.test_defer.py`.  The tests should probably be moved there, so all the `twisted.internet.defer` tests are in one place.

  2.   There is no test coverage for the `__lt__` and `__le__` code for cases where you are comparing against something that is not an instance of FirstError.

Regarding #2 - I was poking around on the interactive interpreter, and I noticed an inconsistency in which comparison methods are called.  This changes the behaviour and may possibly (?) be [an incompatible change](https://twistedmatrix.com/trac/wiki/CompatibilityPolicy), although I am not sure if this can be avoided.  You might want to bring this up in the IRC channel or a mailing list - it may be worth making an exception to the [CompatibilityPolicy](https://twistedmatrix.com/trac/wiki/CompatibilityPolicy).

In the old code, it looks like when you compare an instance of FirstError with a custom class, the comparison methods on the custom class are always called, rather than the `__cmp__` method on FirstError.  In the code in the patch, the compare method of the custom class is called only when testing whether the FirstError instance is greater than the custom class instance.  I'm not entirely sure why, in the old code, FirstError's `__cmp__` method doesn't seem to be called, and there may be more nuances to this than the simple example here.

With your patch:

```
>>> from twisted.internet.defer import FirstError
>>> fe = FirstError('failure', 1)
>>> class A:
...   def __cmp__(self, other):
...     raise NotImplementedError
... 
>>> a = A()
>>> fe < a
True
>>> fe <= a
True
>>> fe > a
__cmp__ for A
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 4, in __cmp__
NotImplementedError
>>> fe >= a
__cmp__ for A
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 4, in __cmp__
NotImplementedError
>>> a < fe
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 3, in __cmp__
NotImplementedError
>>> a > fe
True
```

In trunk, without your patch, I did the same imports and definitions, and the results were:

```
>>> fe < a
__cmp__ for A
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 4, in __cmp__
NotImplementedError
>>> fe <= a
__cmp__ for A
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 4, in __cmp__
NotImplementedError
>>> fe > a
__cmp__ for A
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 4, in __cmp__
NotImplementedError
>>> fe >= a
__cmp__ for A
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 4, in __cmp__
NotImplementedError
>>> a > fe
__cmp__ for A
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 4, in __cmp__
NotImplementedError
>>> a < fe
__cmp__ for A
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 4, in __cmp__
NotImplementedError
```

**Comment by twisted-trac** [comment]
|[<img alt="multani's avatar" src="https://avatars.githubusercontent.com/u/65311?s=50" width="50" height="50">](https://github.com/multani)<a name="note_14"></a>|@multani commented|
|-|-|

In r35324, itamar implemented a replacement for ```cmp()``` in Python 3 and a class decorator which provides the new comparison semantics for Python 3, using the existing ```__cmp___``` method of the class.

So, what would be the status of this ticket?

  1. ```cmp()``` in Conch can still be safely removed.
  1. tests implemented by facundobatista are still relevant, I guess, and still pass using the ```@comparable()`` class-decorator. This means the ```__cmp__()``` of ```FirstError``` can stay without the need to add all the additionnal comparison methods.
  1. the comment in 13 regarding the different behavior comparing to the "old" code is still valid though. It now never raises the ```NotImplementedError``` exception and always returns a boolean. Should the previous behavior be kept?

I can propose an updated patch which removes 1. and add the tests from 2. in the right module. Would it be sufficient?

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_15"></a>|@rodrigc set status to `closed`|
|-|-|

The code in conch has changed so this patch is no longer applicable.
In twisted.internet.defer, twisted.python.compat.cmp has been imported to solve the problem on Python 3.
