### ISSUE TITLE
twisted.protocols.tls setTcpNoDelay fails with "Invalid argument"

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#5187]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#5187|
|Type|defect|
|Created|2011-07-08 15:27:09Z|

Observed this traceback (frequently) when running CalendarServer:

```
2011-07-08 11:25:03-0400 [-] [caldav-1]  [HTTPChannel,36,127.0.0.1] Unhandled Error
2011-07-08 11:25:03-0400 [-] [caldav-1]         Traceback (most recent call last):
2011-07-08 11:25:03-0400 [-] [caldav-1]           File "/Users/exarkun/Projects/Twisted/trunk/twisted/python/log.py", line 84, in callWithLogger
2011-07-08 11:25:03-0400 [-] [caldav-1]             return callWithContext({"system": lp}, func, *args, **kw)
2011-07-08 11:25:03-0400 [-] [caldav-1]           File "/Users/exarkun/Projects/Twisted/trunk/twisted/python/log.py", line 69, in callWithContext
2011-07-08 11:25:03-0400 [-] [caldav-1]             return context.call({ILogContext: newCtx}, func, *args, **kw)
2011-07-08 11:25:03-0400 [-] [caldav-1]           File "/Users/exarkun/Projects/Twisted/trunk/twisted/python/context.py", line 118, in callWithContext
2011-07-08 11:25:03-0400 [-] [caldav-1]             return self.currentContext().callWithContext(ctx, func, *args, **kw)
2011-07-08 11:25:03-0400 [-] [caldav-1]           File "/Users/exarkun/Projects/Twisted/trunk/twisted/python/context.py", line 81, in callWithContext
2011-07-08 11:25:03-0400 [-] [caldav-1]             return func(*args,**kw)
2011-07-08 11:25:03-0400 [-] [caldav-1]         --- <exception caught here> ---
2011-07-08 11:25:03-0400 [-] [caldav-1]           File "/Users/exarkun/Projects/Twisted/trunk/twisted/internet/selectreactor.py", line 150, in _doReadOrWrite
2011-07-08 11:25:03-0400 [-] [caldav-1]             why = getattr(selectable, method)()
2011-07-08 11:25:03-0400 [-] [caldav-1]           File "/Users/exarkun/Projects/Twisted/trunk/twisted/internet/tcp.py", line 163, in doRead
2011-07-08 11:25:03-0400 [-] [caldav-1]             rval = self.protocol.dataReceived(data)
2011-07-08 11:25:03-0400 [-] [caldav-1]           File "/Users/exarkun/Projects/Twisted/trunk/twisted/protocols/tls.py", line 248, in dataReceived
2011-07-08 11:25:03-0400 [-] [caldav-1]             self._flushReceiveBIO()
2011-07-08 11:25:03-0400 [-] [caldav-1]           File "/Users/exarkun/Projects/Twisted/trunk/twisted/protocols/tls.py", line 198, in _flushReceiveBIO
2011-07-08 11:25:03-0400 [-] [caldav-1]             self._shutdownTLS()
2011-07-08 11:25:03-0400 [-] [caldav-1]           File "/Users/exarkun/Projects/Twisted/trunk/twisted/protocols/tls.py", line 259, in _shutdownTLS
2011-07-08 11:25:03-0400 [-] [caldav-1]             self.transport.setTcpNoDelay(True)
2011-07-08 11:25:03-0400 [-] [caldav-1]           File "/Users/exarkun/Projects/Twisted/trunk/twisted/internet/tcp.py", line 245, in setTcpNoDelay
2011-07-08 11:25:03-0400 [-] [caldav-1]             self.socket.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, enabled)
2011-07-08 11:25:03-0400 [-] [caldav-1]         socket.error: [Errno 22] Invalid argument
```

<details><summary>Searchable metadata</summary>

```
trac-id__5187 5187
type__defect defect
reporter__exarkun exarkun
priority__low low
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__ 
time__1310138829000000 1310138829000000
changetime__1363296785000000 1363296785000000
version__None None
owner__itamar itamar

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

(In [32274]) Revert r32257 - this leads to problems in some real SSL-using software

Reopens: [#5118](https://github.com/twisted/twisted/issues/5118)

See [#5187](https://github.com/twisted/twisted/issues/5187) and [#5188](https://github.com/twisted/twisted/issues/5188) for details about the problems introduced.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_2"></a>|@glyph set owner to @exarkun|
|-|-|

It's not really clear to me why this happens.  I haven't managed to reproduce it myself.  It might be worth checking out this behavior with a buggy revision of Twisted trunk under dtrace or something, to see what the actual syscall is that's failing.  (For example: is this because the file descriptor is -1 by this point somehow, or is it actually an EINVAL from `setsockopt` on a real socket? Why would that happen?  Is it a kernel bug?)

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)<a name="note_3"></a>|@itamarst commented|
|-|-|

While EINVAL is obviously a problem, setTcpNoDelay is no longer called by the TLS code, so this probably isn't a release blocker. I'm removing the 11.1 milestone.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_4"></a>|@exarkun set owner to @itamarst|
|-|-|

If setTcpNoDelay is no longer called by the TLS code, why is this ticket still open?
