### ISSUE TITLE
Calling setTcpNoDelay fails with AttributeError when called after connectionLost

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#5188]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#5188|
|Type|defect|
|Created|2011-07-08 15:28:26Z|

Observed (frequently) when running CalendarServer:

```
2011-07-08 11:25:03-0400 [-] [caldav-1]         Traceback (most recent call last):
2011-07-08 11:25:03-0400 [-] [caldav-1]           File "/Users/exarkun/Projects/Twisted/trunk/twisted/application/app.py", line 313, in runReactorWithLogging
2011-07-08 11:25:03-0400 [-] [caldav-1]             reactor.run()
2011-07-08 11:25:03-0400 [-] [caldav-1]           File "/Users/exarkun/Projects/Twisted/trunk/twisted/internet/base.py", line 1169, in run
2011-07-08 11:25:03-0400 [-] [caldav-1]             self.mainLoop()
2011-07-08 11:25:03-0400 [-] [caldav-1]           File "/Users/exarkun/Projects/Twisted/trunk/twisted/internet/base.py", line 1181, in mainLoop
2011-07-08 11:25:03-0400 [-] [caldav-1]             self.doIteration(t)
2011-07-08 11:25:03-0400 [-] [caldav-1]           File "/Users/exarkun/Projects/Twisted/trunk/twisted/internet/selectreactor.py", line 144, in doSelect
2011-07-08 11:25:03-0400 [-] [caldav-1]             _logrun(selectable, _drdw, selectable, method, dict)
2011-07-08 11:25:03-0400 [-] [caldav-1]         --- <exception caught here> ---
2011-07-08 11:25:03-0400 [-] [caldav-1]           File "/Users/exarkun/Projects/Twisted/trunk/twisted/python/log.py", line 84, in callWithLogger
2011-07-08 11:25:03-0400 [-] [caldav-1]             return callWithContext({"system": lp}, func, *args, **kw)
2011-07-08 11:25:03-0400 [-] [caldav-1]           File "/Users/exarkun/Projects/Twisted/trunk/twisted/python/log.py", line 69, in callWithContext
2011-07-08 11:25:03-0400 [-] [caldav-1]             return context.call({ILogContext: newCtx}, func, *args, **kw)
2011-07-08 11:25:03-0400 [-] [caldav-1]           File "/Users/exarkun/Projects/Twisted/trunk/twisted/python/context.py", line 118, in callWithContext
2011-07-08 11:25:03-0400 [-] [caldav-1]             return self.currentContext().callWithContext(ctx, func, *args, **kw)
2011-07-08 11:25:03-0400 [-] [caldav-1]           File "/Users/exarkun/Projects/Twisted/trunk/twisted/python/context.py", line 81, in callWithContext
2011-07-08 11:25:03-0400 [-] [caldav-1]             return func(*args,**kw)
2011-07-08 11:25:03-0400 [-] [caldav-1]           File "/Users/exarkun/Projects/Twisted/trunk/twisted/internet/selectreactor.py", line 155, in _doReadOrWrite
2011-07-08 11:25:03-0400 [-] [caldav-1]             self._disconnectSelectable(selectable, why, method=="doRead")
2011-07-08 11:25:03-0400 [-] [caldav-1]           File "/Users/exarkun/Projects/Twisted/trunk/twisted/internet/posixbase.py", line 263, in _disconnectSelectable
2011-07-08 11:25:03-0400 [-] [caldav-1]             selectable.connectionLost(failure.Failure(why))
2011-07-08 11:25:03-0400 [-] [caldav-1]           File "/Users/exarkun/Projects/Twisted/trunk/twisted/internet/tcp.py", line 232, in connectionLost
2011-07-08 11:25:03-0400 [-] [caldav-1]             protocol.connectionLost(reason)
2011-07-08 11:25:03-0400 [-] [caldav-1]           File "/Users/exarkun/Projects/Twisted/trunk/twisted/protocols/tls.py", line 296, in connectionLost
2011-07-08 11:25:03-0400 [-] [caldav-1]             self._flushReceiveBIO()
2011-07-08 11:25:03-0400 [-] [caldav-1]           File "/Users/exarkun/Projects/Twisted/trunk/twisted/protocols/tls.py", line 198, in _flushReceiveBIO
2011-07-08 11:25:03-0400 [-] [caldav-1]             self._shutdownTLS()
2011-07-08 11:25:03-0400 [-] [caldav-1]           File "/Users/exarkun/Projects/Twisted/trunk/twisted/protocols/tls.py", line 259, in _shutdownTLS
2011-07-08 11:25:03-0400 [-] [caldav-1]             self.transport.setTcpNoDelay(True)
2011-07-08 11:25:03-0400 [-] [caldav-1]           File "/Users/exarkun/Projects/Twisted/trunk/twisted/internet/tcp.py", line 245, in setTcpNoDelay
2011-07-08 11:25:03-0400 [-] [caldav-1]             self.socket.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, enabled)
2011-07-08 11:25:03-0400 [-] [caldav-1]         exceptions.AttributeError: 'Server' object has no attribute 'socket'
```

<details><summary>Searchable metadata</summary>

```
trac-id__5188 5188
type__defect defect
reporter__exarkun exarkun
priority__low low
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__ 
time__1310138906000000 1310138906000000
changetime__1311190003000000 1311190003000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

(In [32274]) Revert r32257 - this leads to problems in some real SSL-using software

Reopens: [#5118](https://github.com/twisted/twisted/issues/5118)

See [#5187](https://github.com/twisted/twisted/issues/5187) and [#5188](https://github.com/twisted/twisted/issues/5188) for details about the problems introduced.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_2"></a>|@glyph commented|
|-|-|

The issue where TLS tickles this bug is addressed now, but this is still a potential issue with other protocols that might call `setTcpNoDelay`.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_3"></a>|@glyph set owner to @itamarst|
|-|-|

Hey itamar, I bet you love `TCP_NODELAY`.

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)<a name="note_4"></a>|@itamarst removed owner|
|-|-|

Updated the summary, removed Twisted-11.1 milestone because I'm pretty sure this has always been an issue with TCP transports. We probably should be raising "TransportAlreadyClosed" or something instead of the AttributeError.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_5"></a>|@glyph commented|
|-|-|

Replying to [itamar](#note_4):
> Updated the summary, removed Twisted-11.1 milestone because I'm pretty sure this has always been an issue with TCP transports.

Agreed; this is no longer necessary for the SSL fixes.

> We probably should be raising "TransportAlreadyClosed" or something instead of the AttributeError.

No way.  We should be silently ignoring the call, or at the very most, issuing a warning.  Calling `loseConnection` multiple times doesn't raise an exception, and neither does calling `write` after `loseConnection`; why should a subtle tweak of transport properties on a closed transport cause an exception when these basic operations don't?

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)<a name="note_6"></a>|@itamarst commented|
|-|-|

Silently ignoring is another alternative. But --

I should also note that you'd have same issue with a bunch of other methods (basically, anything on ITCPTransport), which should also be fixed by this ticket. And some of them use getsockopt rather than setsockopt... what should they return if connection was already closed?

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_7"></a>|@glyph commented|
|-|-|

Replying to [itamar](#note_6):
> Silently ignoring is another alternative. But --
> 
> I should also note that you'd have same issue with a bunch of other methods (basically, anything on ITCPTransport), which should also be fixed by this ticket. And some of them use getsockopt rather than setsockopt... what should they return if connection was already closed?

Call it at least once during the connection's lifetime and cache the value, I guess?  Or infer a default if it's never been called?  Since, by definition, the value can't matter at that point.

The issue is that there's no way to figure out if the connection is dead already without actually being the hooked-up `IProtocol ` object.  So any library code which wants to call any of these functions would have to have a `try:`/`except:` around them.
