### ISSUE TITLE
Strange exception in twisted.names.client.Resolver

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#5224]
|<img alt="tearyfield's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| tearyfield reported|
|-|-|
|Trac ID|trac#5224|
|Type|defect|
|Created|2011-08-08 09:15:57Z|

I managed to extend twisted.names.client.Resolver, and use queryTCP to fire a request. However, a strange exception "exceptions.AttributeError: UpstreamResolver instance has no attribute 'connectionLost'" occurred whenever I destroyed the client.

I tried to add an empty function named 'connectionLost' into the Resolver, and the exception never raised again.

Here I attached the final python script file. You may delete the function 'connectionLost' and see the following traceback:

```
Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 286, in addCallbacks
    self._runCallbacks()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 542, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 426, in _continueFiring
    callable(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 615, in disconnectAll
    failure.Failure(main.CONNECTION_LOST))
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/log.py", line 84, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/log.py", line 69, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 687, in connectionLost
    Connection.connectionLost(self, reason)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 529, in connectionLost
    protocol.connectionLost(reason)
  File "/usr/local/lib/python2.7/dist-packages/twisted/names/dns.py", line 1856, in connectionLost
    self.controller.connectionLost(self)
exceptions.AttributeError: UpstreamResolver instance has no attribute 'connectionLost'
```

Attachments:

* [resolvers.py](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/68e/68ecbf29bc06f656a27369b8fc67a4396c5a9c1a/cd30f55333bbe0b173c544cbb77578ab96c7c7dc.py) (1950 bytes) - added by tearyfield on 2011-08-08 09:16:25Z - The resolver script.
* [5224.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/68e/68ecbf29bc06f656a27369b8fc67a4396c5a9c1a/f98e03d3335a20a4c710b683201526716d9f91e4.patch) (376 bytes) - added by retenodus on 2011-08-13 01:38:10Z - 
* [5224.2.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/68e/68ecbf29bc06f656a27369b8fc67a4396c5a9c1a/5d89c039a3ab2fbbafdc87a0828e9512a1930f1a.patch) (460 bytes) - added by retenodus on 2011-08-13 01:44:10Z - 

<details><summary>Searchable metadata</summary>

```
trac-id__5224 5224
type__defect defect
reporter__tearyfield tearyfield
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__duplicate duplicate
component__names names
keywords__connectionLost__AttributeError__Resolver connectionLost, AttributeError, Resolver
time__1312794957000000 1312794957000000
changetime__1344947801000000 1344947801000000
version__None None
owner__retenodus retenodus
cc__retenodus
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

Fixing description markup and removing milestone.  Release milestones are generally only for regressions.

**Comment by twisted-trac** [comment]
|<img alt="retenodus's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_2"></a>|retenodus commented|
|-|-|

I've added a connectionLost to twisted.names.client.Resolver. The problem is addressed and there's no problem with unittests.

I didn't added unittests because actually this method doesn't do anything.

**Comment by twisted-trac** [comment]
|<img alt="retenodus's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_3"></a>|retenodus commented|
|-|-|

Oops, I had forgotten the docstring.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_4"></a>|@exarkun set owner to retenodus|
|-|-|

Thanks Retendonus.  The method _does_ do something, though.  It prevents an exception from being raised in a certain case.  That's what the unit test should verify.

Also, you don't need `pass` in the body, since the docstring already gives the function its one required statement.

**Comment by twisted-trac** [comment]
|<img alt="buddyns's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_6"></a>|buddyns commented|
|-|-|

Duplicate of [#4015](https://github.com/twisted/twisted/issues/4015) ?

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_7"></a>|@exarkun set status to `closed`|
|-|-|

Yes, thanks.
