### ISSUE TITLE
twisted.web.client.HTTPClient breaks on bare LF-terminated header fields

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#5262]
|<img alt="jacky's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| jacky reported|
|-|-|
|Trac ID|trac#5262|
|Type|defect|
|Created|2011-09-19 08:01:49Z|

my english is poor,please look at following:

```
        Traceback (most recent call last):
          File "/usr/local/python2.7/lib/python2.7/site-packages/Twisted-11.0.0-py2.7-linux-x86_64.egg/twisted/python/log.py", line 84, in callWithLogger
            return callWithContext({"system": lp}, func, *args, **kw)
          File "/usr/local/python2.7/lib/python2.7/site-packages/Twisted-11.0.0-py2.7-linux-x86_64.egg/twisted/python/log.py", line 69, in callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File "/usr/local/python2.7/lib/python2.7/site-packages/Twisted-11.0.0-py2.7-linux-x86_64.egg/twisted/python/context.py", line 118, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/usr/local/python2.7/lib/python2.7/site-packages/Twisted-11.0.0-py2.7-linux-x86_64.egg/twisted/python/context.py", line 81, in callWithContext
            return func(*args,**kw)
        --- <exception caught here> ---
          File "/usr/local/python2.7/lib/python2.7/site-packages/Twisted-11.0.0-py2.7-linux-x86_64.egg/twisted/internet/selectreactor.py", line 146, in _doReadOrWrite
            why = getattr(selectable, method)()
          File "/usr/local/python2.7/lib/python2.7/site-packages/Twisted-11.0.0-py2.7-linux-x86_64.egg/twisted/internet/tcp.py", line 460, in doRead
            rval = self.protocol.dataReceived(data)
          File "/usr/local/python2.7/lib/python2.7/site-packages/Twisted-11.0.0-py2.7-linux-x86_64.egg/twisted/protocols/basic.py", line 564, in dataReceived
            why = self.lineReceived(line)
          File "/usr/local/python2.7/lib/python2.7/site-packages/Twisted-11.0.0-py2.7-linux-x86_64.egg/twisted/web/http.py", line 448, in lineReceived
            self.extractHeader(self._header)
          File "/usr/local/python2.7/lib/python2.7/site-packages/Twisted-11.0.0-py2.7-linux-x86_64.egg/twisted/web/http.py", line 409, in extractHeader
            self.length = int(val)
        exceptions.ValueError: invalid literal for int() with base 10: '831\nPragma: no-cache'
```

<details><summary>Searchable metadata</summary>

```
trac-id__5262 5262
type__defect defect
reporter__jacky jacky
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__duplicate duplicate
component__web web
keywords__ 
time__1316419309000000 1316419309000000
changetime__1316432487000000 1316432487000000
version__None None
owner__ 
cc__jknight cc__ivank
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="ivank's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_2"></a>|ivank set status to `closed`|
|-|-|

You're getting a response from a broken server that sends `\n` instead of the correct line terminator `\r\n`.  If you use the new HTTP client `twisted.web.client.Agent` [1] in a recent version of Twisted, it'll be able to handle an HTTP response that uses `n`.

[1] http://twistedmatrix.com/documents/10.1.0/web/howto/client.html#auto2

This is a duplicate of [#2842](https://github.com/twisted/twisted/issues/2842)

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_3"></a>|@exarkun commented|
|-|-|

Fixing description markup, too.
