### ISSUE TITLE
Oscar: Unable to join group chats.

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#5264]
|<img alt="SeeJayEmm's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| SeeJayEmm reported|
|-|-|
|Trac ID|trac#5264|
|Type|defect|
|Created|2011-09-20 17:11:21Z|

Approx 2 weeks ago I lost the ability to join AIM chat rooms.  It appears that the data Twisted is expecting it no longer being provided.

Outputting the contents of the moreTLVs variable results in this:
```
{10001: '\x00\x04 !aol://2719:10-4-chatofthetitans\x00\x00', 10: '\x00\x01', 13: 'us-ascii', 14: 'en', 15: ''}
```

The exception is as follows:
```
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "/home/madcow/madcow2/madcow/include/twisted/words/protocols/oscar.py", line 1005, in oscar_0D_09
    self.clientReady()
  File "/home/madcow/madcow2/madcow/include/twisted/words/protocols/oscar.py", line 991, in clientReady
    self.d.callback(self)
  File "/home/madcow/madcow2/madcow/include/twisted/internet/defer.py", line 361, in callback
    self._startRunCallbacks(result)
  File "/home/madcow/madcow2/madcow/include/twisted/internet/defer.py", line 455, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/home/madcow/madcow2/madcow/include/twisted/internet/defer.py", line 542, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/madcow/madcow2/madcow/include/twisted/words/protocols/oscar.py", line 598, in <lambda>
    addCallback(self._cbGetChatInfoForInvite, user, moreTLVs[12]))
exceptions.KeyError: 12
```

<details><summary>Searchable metadata</summary>

```
trac-id__5264 5264
type__defect defect
reporter__SeeJayEmm SeeJayEmm
priority__high high
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__wontfix wontfix
component__words words
keywords__ 
time__1316538681000000 1316538681000000
changetime__1498793375930202 1498793375930202
version__None None
owner__ 
cc__ralphm
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_2"></a>|@exarkun commented|
|-|-|

Fixing description markup

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_3"></a>|@exarkun commented|
|-|-|

http://iserverd.khstu.ru/oscar/snac_04_07_ch2.html might help anyone interested in tackling this.

**Comment by twisted-trac** [comment]
|<img alt="SeeJayEmm's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_4"></a>|SeeJayEmm commented|
|-|-|

Is there anything I can do to assist moving this bug forward? (outside of learning python, oscar, and the inner workings of twisted words?)

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_5"></a>|@rodrigc set status to `closed`|
|-|-|

oscar was removed in ticket:9024
