### ISSUE TITLE
In the core doc, do not call reactor.stop directly in processEnded

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#5272]
|<img alt="dkdog's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| dkdog reported|
|-|-|
|Trac ID|trac#5272|
|Type|defect|
|Created|2011-09-24 12:32:03Z|

I modeled the following code after the "verbose example" at

http://twistedmatrix.com/documents/current/core/howto/process.html#auto5

```
from twisted.internet import reactor, protocol

class OneRun(protocol.ProcessProtocol):
        def processEnded(self, reason):
                print "Process ended\n"
                reactor.stop()

def main():
        reactor.spawnProcess(OneRun(), executable="echo", args=["echo", "hello"], childFDs={0:0, 1:1, 2:2})
        reactor.run()

if __name__ == '__main__':
        main()
```

But it raises the exception "twisted.internet.error.ReactorNotRunning: Can't stop reactor that isn't running." inside processEnded

It would seem one should not call reactor.stop inside processEnded. Calling reactor.callLater(0, reactor.stop) is fine.

The documentation is misleading and should be fixed.

<details><summary>Searchable metadata</summary>

```
trac-id__5272 5272
type__defect defect
reporter__dkdog dkdog
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__worksforme worksforme
component__core core
keywords__ 
time__1316867523000000 1316867523000000
changetime__1317038602000000 1317038602000000
version__None None
owner__ 
cc__dkdog
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

Fixing description markup

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_2"></a>|@exarkun set status to `closed`|
|-|-|

I'm unable to reproduce the error using Twisted trunk@HEAD on Ubuntu Karmic with Python 2.6:

```

exarkun@boson:/tmp$ cat example.py 
from twisted.internet import reactor, protocol

class OneRun(protocol.ProcessProtocol):
        def processEnded(self, reason):
                print "Process ended\n"
                reactor.stop()

def main():
        reactor.spawnProcess(OneRun(), executable="echo", args=["echo", "hello"], childFDs={0:0, 1:1, 2:2})
        reactor.run()

if __name__ == '__main__':
        main()
exarkun@boson:/tmp$ python example.py 
hello
Process ended

exarkun@boson:/tmp$ 
```

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_3"></a>|@glyph commented|
|-|-|

dkdog, if this is a problem, it's not a documentation problem.  `processEnded` is a totally valid place to call `reactor.stop` and if it doesn't work we should fix it.  If you can, please provide more details about your configuration so that we can reproduce the issue.

**Comment by twisted-trac** [comment]
|<img alt="dkdog's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_4"></a>|dkdog commented|
|-|-|

Replying to [glyph](#note_3):
> dkdog, if this is a problem, it's not a documentation problem.  `processEnded` is a totally valid place to call `reactor.stop` and if it doesn't work we should fix it.  If you can, please provide more details about your configuration so that we can reproduce the issue.

I copied/pasted the code from this ticket again and ran the following:

[root@vpn1 code]# python ticket5272.py 
hello
Process ended

unexpected error in processEnded
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/process.py", line 714, in __init__
    registerReapProcessHandler(self.pid, self)
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/process.py", line 66, in registerReapProcessHandler
    process.processEnded(status)
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/_baseprocess.py", line 48, in processEnded
    self.maybeCallProcessEnded()
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/process.py", line 916, in maybeCallProcessEnded
    _BaseProcess.maybeCallProcessEnded(self)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/_baseprocess.py", line 60, in maybeCallProcessEnded
    proto.processEnded(Failure(reason))
  File "ticket5272.py", line 6, in processEnded
    reactor.stop()
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 571, in stop
    "Can't stop reactor that isn't running.")
twisted.internet.error.ReactorNotRunning: Can't stop reactor that isn't running.
[root@vpn1 code]# cat /etc/redhat-release 
CentOS release 5.4 (Final)
[root@vpn1 code]# uname -a
Linux vpn1 2.6.18-164.el5xen [#11338](https://github.com/twisted/twisted/issues/11338) SMP Thu Sep 3 04:03:03 EDT 2009 x86_64 x86_64 x86_64 GNU/Linux
[root@vpn1 code]# python -V
Python 2.7.1
[root@vpn1 code]# 


My Centos is a virtual machine. The same exception occurs under both the following virtualization environment:

1) XenServer 5.6
2) VMware Workstation 6.5.2 under Windows 7 64bit


I think my XenServer is running in that paravirtualized mode with Intel's VT-x enabled. But the VMware under windows should be using a different mode. I am a bit fuzzy on these terms but I don't think level that deep down matters here.

Huh, I just tried the same, on another 64bit virtual machine, running Centos (but) 5.5 , on Rackspace's cloud server. Also Python 2.7.1. The code is fine. So, OS/hardware stuff could change all this? I am an average programmer, so I would be avoiding calling reactor.stop for now.


--- super tangential stuff that I just wanna bring up to bounce ideas after seeing that OS/hardware seems to matter ---

Okay ... I have had experience with buildbot that dies under virtualization environment b/c time would jump around. Because Centos 5.2 kernel defaults to 1000hz for ticks. After reducing ticks to 100hz (default for other linux kernels), the same Centos 5.2 is fine. NTP sync, etc alone don't solve it unless the ticks are reduced. This is very microscopic time shifting that humans don't see.

I hope twisted reactor isn't using any kind of time based stuff here. I would assume everything is sequential ... 

Okay, I am really going very offtrack here. Don't even know if that was even related.

**Comment by twisted-trac** [comment]
|<img alt="dkdog's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_5"></a>|dkdog commented|
|-|-|

Just be aware whitelines are kinda messed up here but in the email it looks fine.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_6"></a>|@exarkun commented|
|-|-|

Please read WikiFormatting.

**Comment by twisted-trac** [comment]
|<img alt="dkdog's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_7"></a>|dkdog set status to `reopened`|
|-|-|

I just found out that reactor.spawnProcess could spawn the subprocess right away **before** reactor.run is executed.

I get the impression that most stuff don't get run until the reactor event loop is up and running with reactor.run()

In this case, who's answering all the ProcessProtocol's methods like processEnded then, without an event loop?

Could someone take a look and make a judgment call whether:

1) this is how it should be (like the programmer should carefully code and work around this, perhaps with an extra callLater wrapped around spawnProcess) (and like, reactor can also be used as a quick and dirty way to spawn subprocess, disregarding reactor as a crucial component of the twisted framework)

2) we should improve documentation?

3) or this is actually a bug?

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_8"></a>|@exarkun set status to `closed`|
|-|-|

> I just found out that reactor.spawnProcess could spawn the subprocess right away **before** reactor.run is executed.

This doesn't seem related to this ticket.

> I get the impression that most stuff don't get run until the reactor event loop is up and running with reactor.run()

That's true.  Most stuff.

> In this case, who's answering all the ProcessProtocol's methods like processEnded then, without an event loop?

The process _starting_ is different from `ProcessProtocol` methods being called.  `ProcessProtocol.processEnded` is _not_ called until the reactor is running.

Further discussion should be moved to the mailing list.  Thanks.
