### ISSUE TITLE
t.p.modules assumes modules has a __file__ attribute

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#5318]
|<img alt="nkvoll's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| nkvoll reported|
|-|-|
|Trac ID|trac#5318|
|Type|defect|
|Created|2011-10-17 22:44:05Z|
|Branch|https://github.com/twisted/twisted/tree/modules-pth-5318|

... which is an assumption that does not hold true for namespaced packages.

See the attached output which tests against zope.interface.

Of note is the "zope.interface-3.8.0-py2.6-nspkg.pth" file, which creates new.modules for the namespace packages and inserts them into sys.modules.

Attachments:

* [namespace_without_file.txt](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/a87/a8782e82e16d00d00e35482889e0b2bb38ca598c/de936ce6b0a2b86cd912a38b2c0fc39577090f55.txt) (5135 bytes) - added by nkvoll on 2011-10-17 22:44:33Z - Example

<details><summary>Searchable metadata</summary>

```
trac-id__5318 5318
type__defect defect
reporter__nkvoll nkvoll
priority__normal normal
milestone__ 
branch__branches_modules_pth_5318 branches/modules-pth-5318
branch_author__thijs thijs
status__new new
resolution__None None
component__core core
keywords__ 
time__1318891445000000 1318891445000000
changetime__1399500353000000 1399500353000000
version__None None
owner__itamar itamar
cc__thijs
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)|@thijstriemstra set owner to @thijstriemstra<br>@thijstriemstra set status to `assigned`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_2"></a>|@thijstriemstra commented|
|-|-|

Running `trial zope` with current trunk results in:

```
Traceback (most recent call last):
  File "/home/thijs/workspaces/opensource/software/twisted/svn/Twisted/trunk/bin/trial", line 18, in <module>
    run()
  File "/home/thijs/workspaces/opensource/software/twisted/svn/Twisted/trunk/twisted/scripts/trial.py", line 510, in run
    suite = _getSuite(config)
  File "/home/thijs/workspaces/opensource/software/twisted/svn/Twisted/trunk/twisted/scripts/trial.py", line 402, in _getSuite
    return loader.loadByNames(config['tests'], recurse)
  File "/home/thijs/workspaces/opensource/software/twisted/svn/Twisted/trunk/twisted/trial/runner.py", line 592, in loadByNames
    for thing in self._uniqueTests(things)]
  File "/home/thijs/workspaces/opensource/software/twisted/svn/Twisted/trunk/twisted/trial/runner.py", line 548, in loadAnything
    if isPackage(thing):
  File "/home/thijs/workspaces/opensource/software/twisted/svn/Twisted/trunk/twisted/trial/runner.py", line 46, in isPackage
    basename = os.path.splitext(os.path.basename(module.__file__))[0]
AttributeError: 'module' object has no attribute '__file__'
```

Running `trial zope.interface` results in:

```
Traceback (most recent call last):
  File "/home/thijs/workspaces/opensource/software/twisted/svn/Twisted/trunk/bin/trial", line 18, in <module>
    run()
  File "/home/thijs/workspaces/opensource/software/twisted/svn/Twisted/trunk/twisted/scripts/trial.py", line 510, in run
    suite = _getSuite(config)
  File "/home/thijs/workspaces/opensource/software/twisted/svn/Twisted/trunk/twisted/scripts/trial.py", line 402, in _getSuite
    return loader.loadByNames(config['tests'], recurse)
  File "/home/thijs/workspaces/opensource/software/twisted/svn/Twisted/trunk/twisted/trial/runner.py", line 592, in loadByNames
    for thing in self._uniqueTests(things)]
  File "/home/thijs/workspaces/opensource/software/twisted/svn/Twisted/trunk/twisted/trial/runner.py", line 549, in loadAnything
    return self.loadPackage(thing, recurse)
  File "/home/thijs/workspaces/opensource/software/twisted/svn/Twisted/trunk/twisted/trial/runner.py", line 488, in loadPackage
    pkgobj = modules.getModule(package.__name__)
  File "/home/thijs/workspaces/opensource/software/twisted/svn/Twisted/trunk/twisted/python/modules.py", line 775, in getModule
    return theSystemPath[moduleName]
  File "/home/thijs/workspaces/opensource/software/twisted/svn/Twisted/trunk/twisted/python/modules.py", line 696, in __getitem__
    self._findEntryPathString(moduleObject)),
  File "/home/thijs/workspaces/opensource/software/twisted/svn/Twisted/trunk/twisted/python/modules.py", line 621, in _findEntryPathString
    if _isPackagePath(FilePath(topPackageObj.__file__)):
AttributeError: 'module' object has no attribute '__file__'
```

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_3"></a>|@thijstriemstra commented|
|-|-|

(In [38398]) Branching to 'modules-pth-5318'

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_4"></a>|@thijstriemstra commented|
|-|-|

(In [38399]) add test that uses .pth configuration file, refs [#5318](https://github.com/twisted/twisted/issues/5318)

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_5"></a>|@thijstriemstra commented|
|-|-|

With the changes in the branch `trial zope.interface` now works as expected:

```
zope.interface.common.tests.test_idatetime
  TestDateTimeInterfaces
    test_interfaces ...                                                    [OK]
Doctest: zope.interface.common.tests
  test_import_interfaces
    test_interface_import ...                                              [OK]

[...]

    test_module_hit ...                                                    [OK]
    test_module_miss ...                                                   [OK]
    test_w_callable_non_func_method ...                                    [OK]

-------------------------------------------------------------------------------
Ran 659 tests in 0.179s
```

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_6"></a>|@thijstriemstra commented|
|-|-|

(In [38400]) teach runner.isPackage about __path__, refs [#5318](https://github.com/twisted/twisted/issues/5318)

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_7"></a>|@thijstriemstra removed owner<br>@thijstriemstra set status to `new`|
|-|-|

Running `trial zope` doesn't throw an error anymore:

```
-------------------------------------------------------------------------------

PASSED
```

So both problems seen in [[namespace_without_file.txt]](None/namespace_without_file.txt]) are gone now.

Now,

 1. is it valid to assume a module with a `__path__` attribute is a package (see change in `trial.runner.isPackage`)? Or should we recursively check if any, or the first, sub-directory contains a `__init__.py` file?
 1. There's a `UserWarning` shown now, but I'm not sure why this was added, and whether I should update the check or just get rid of it altogether?

```
/home/peter/twisted/python/modules.py:794: UserWarning: /home/peter/_trial_temp/twisted.test.test_modules/BasicTests/test_namespacedPackagesPathConfi/cpnGSL/temp/test_package (for module test) not in path importer cache (PEP 302 violation - check your local configuration).
```


Forced a [build](http://buildbot.twistedmatrix.com/boxes-supported?branch=/branches/modules-pth-5318), up for review.

**Comment by twisted-trac** [comment]
|[<img alt="radix's avatar" src="https://avatars.githubusercontent.com/u/227068?s=50" width="50" height="50">](https://github.com/radix)<a name="note_8"></a>|@radix commented|
|-|-|

twisted.python.modules makes me pretty unhappy.

On the one hand, I think this is a useful change that makes things work, so I think it should be merged.

On the other hand, I'm unhappy for a couple of reasons:

 1. We have to "guess" at a __path__ entry in these cases, choosing [0] arbitrarily.
 2. This basically means that we're abstracting over important details of the module system, when my impression of twisted.python.modules is that it doesn't try to abstract away the information of the Python module system, but rather present it all in an unambiguous and convenient way.
 3. I'm also unhappy that it's not just an implementation detail of trial, but actually a public interface.
 4. I'm also pretty unhappy about the metaprogramming going on in t.p.modules. Methods like ```__iter__``` and ```__getitem__``` don't give a good impression of what they *really* do. I would be a lot happier if PythonPath had more clearly defined, explicit method names. 

I don't expect you to do anything about these points, thijs, but I wanted to get them off of my chest :-)


OKAY, now on to the REVIEW!

 1. On line 644 of modules.py in your branch, I think something is a little wrong here.

```
 +            rval = topPackageObj.__path__[0]
```

I'm not sure what negative effect this has, but I think it causes parentPath to basically be wrong. I *think* you should be using dirname() of __path__[0]. Observe:

```
>>> import twisted, zope
>>> twisted.__path__
['/home/radix/junkyjunk/local/lib/python2.7/site-packages/twisted']
>>> zope.__path__
['/home/radix/junkyjunk/local/lib/python2.7/site-packages/zope', '/home/radix/junkyjunk/lib/python2.7/site-packages/zope']
>>> pp = PythonPath()
>>> pp['twisted'].pathEntry
PathEntry<FilePath('/home/radix/junkyjunk/local/lib/python2.7/site-packages')>
>>> pp['zope'].pathEntry
PathEntry<FilePath('/home/radix/junkyjunk/local/lib/python2.7/site-packages/zope')>
```

I don't know what actual effect this has anywhere, but it seems wrong to say that the pathEntry for zope is the "package" directory (I don't know what to call it other than that) instead of site-packages.

**Comment by twisted-trac** [comment]
|[<img alt="radix's avatar" src="https://avatars.githubusercontent.com/u/227068?s=50" width="50" height="50">](https://github.com/radix)|@radix set owner to @thijstriemstra|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_10"></a>|@thijstriemstra commented|
|-|-|

(In [38913]) address review comments, refs [#5318](https://github.com/twisted/twisted/issues/5318)

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_11"></a>|@thijstriemstra removed owner|
|-|-|

Thanks for the review radix. I changed the dirname() call on line 644 and fixed some twistedchecker warnings. Up for review again.

**Comment by twisted-trac** [comment]
|[<img alt="tomprince's avatar" src="https://avatars.githubusercontent.com/u/283816?s=50" width="50" height="50">](https://github.com/tomprince)<a name="note_12"></a>|@tomprince commented|
|-|-|

> We have to "guess" at a path entry in these cases, choosing [0] arbitrarily.

After doing some digging, it appears that this will be true on python3, but not with the style of namespace packages that setuptools creates on python3.

Setuptools drops the following bit of insanity in a '-nspkg.pth' file:
```python
import sys,new,os; p = os.path.join(sys._getframe(1).f_locals['sitedir'], *('zope',)); ie = os.path.exists(os.path.join(p,'__init__.py')); m = not ie and sys.modules.setdefault('zope',new.module('zope')); mp = (m or []) and m.__dict__.setdefault('__path__',[]); (p not in mp) and mp.append(p)
```
(reformated:) 
```python
import sys,new,os
p = os.path.join(sys._getframe(1).f_locals['sitedir'], *('zope',))
ie = os.path.exists(os.path.join(p,'__init__.py'))
m = not ie and sys.modules.setdefault('zope',new.module('zope'))
mp = (m or []) and m.__dict__.setdefault('__path__',[])
(p not in mp) and mp.append(p)
```
which, unless somebody does some munging afterwards, will only have a single `__path__` entry.

One way to not need to guess, perhaps, is to walk down the module path, looking for `__file__` and then finding the `pathEntry` from that, if the toplevel module doesn't have a `__file__`. (Maybe comparing against the toplevel `__path__`)

Another option, would be to say that if the toplevel package doesn't have a `__file__` then there *isn't* an associated path entry. I'm not sure what, if anything this would break. But it is a more accurate representation of the module system.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_13"></a>|@glyph set owner to @thijstriemstra|
|-|-|


  1. Minor nit-picks; all optional:
    1. In `_isPackagePath`'s docstring, it would be nice to separate `@type fpath` and `@rtype` with a blank line.  (In other words, do what [my epytext wrapper](https://github.com/glyph/E-Max/blob/master/epywrap.py) would do programmatically; this is an attempt to codify the style that exarkun uses.  I think somebody might have some actual-emacs bindings for that python file lying around somewhere...)
      1. Same for `isPackageDirectory`.
      2. Same for `isPackage`.
    2. Eventually we should turn `TwistedModulesMixin` into a [separable test tool](https://twistedmatrix.com/trac/wiki/Design/KeepTestToolsOutOfFixtures).  If you can think of a way to put `_cleanUpSysPath` and `replaceSiteDir` onto an external object rather than this mix-in, please do so.
    3. It seems odd to me that all the shenanigans in `_findEntryPathString` are both constructing `FilePath` objects, throwing them away, and then calling `dirname` all over the place.  I guess that's there because we're never `abspath`ing the result, and therefore preserving the relative quality of the path string?  Weird.  I guess I have no feedback here then, except to say that everything about process state like "current working directory" and filesystems is super unfortunate.  Maybe the feedback is just that the docstring, or the tests, should say something about that being an interesting property?
  2. Also nitpicks, but please do these:
    1. `_pathEntryWithNestedPackages` should have a docstring.  The giant block comment where the docstring ought to be is just silly.
    2. `entry.child(b"test.pth").setContent(b"import sys,types,os; p = os.path.join(sys._getframe(1).f_locals['sitedir']...` Nice try.  That is both longer than 79 characters and also potentially a violation of the geneva convention.  Please put that into a readable multi-line constant.  Since I suppose the single-line-ness of the text itself is important, `;.join` might be useful.
    3. `test_namespacedPackagesPathConfigFile`'s string is a sentence fragment; it just describes the subject, without a dependent clause about its behavior.  Ambiguity about desired behavior is mirrored in the `XXX` comment.  Personally, I'd say that a `.pth` config file should definitely be honored: the bottom line is that if `import foo.bar` should work, then `foo.bar` should be yielded when iterating `foo`.  This is especially true when `importPackages=True`, since the only reason I can think of _not_ to honor this contract is to avoid importing things and running arbitrary code.
  3. Regarding the confusion over `pathEntry`... there are three potentially "right" answers here:
    1. The `pathEntry` attribute of a namespace package can be the 0th entry, and we can deprecate `pathEntry` in favor of `pathEntries`, and then fully populate `pathEntries`.
    2. The `pathEntry` attribute of a namespace package can be a new provider of `IFilePath` that magically merges together a read-only view of all entries that a namespace package is present in.  This might not be all _that_ hard, because only `.children`, `.child`, and `.walk` really need to be affected.
    3. The `pathEntry` attribute of a namespace package can be a minimal, in-memory stub implementation of `IFilePath` which basically returns nothing interesting for anything.

For now, I think I prefer option 3, since it doesn't make sense to try to load resources out of a namespace package, and it would be nice to get a sensible error when trying to look for things there.  Later, option 1 might be more reasonable.

But, I leave it to the implementor to select the one they like best.

I think that this should be OK to merge, at least if you address point 2.3 in a way which you find satisfying.

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)<a name="note_14"></a>|@itamarst commented|
|-|-|

Someone on IRC just hit this bug. Can we get this merged, since it's so close?

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_15"></a>|@glyph set owner to @itamarst|
|-|-|

My review was basically passing, if you'd like to take on the role of implementor, see if you'd like to fix any of those things, and land it :).
