### ISSUE TITLE
Unable to install 11.1.0 under Ubuntu 10.04 LTS

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#5402]
|<img alt="jacek99@...'s avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| jacek99@... reported|
|-|-|
|Trac ID|trac#5402|
|Type|release blocker: regression|
|Created|2011-11-21 17:39:42Z|

Tried this with the default python2.6 (using easy_install) and python 2.7 (custom compiled, using 'python2.7 -m easy_install -U twisted')

```
sudo easy_install -U twisted
[sudo] password for jacekf: 
Searching for twisted
Reading http://pypi.python.org/simple/twisted/
Reading http://www.twistedmatrix.com
Reading http://twistedmatrix.com/products/download
Reading http://twistedmatrix.com/
Reading http://tmrc.mit.edu/mirror/twisted/Twisted/9.0/
Reading http://twistedmatrix.com/projects/core/
Reading http://tmrc.mit.edu/mirror/twisted/Twisted/8.1/
Reading http://tmrc.mit.edu/mirror/twisted/Twisted/8.2/
Reading http://tmrc.mit.edu/mirror/twisted/Twisted/10.0/
Best match: Twisted 11.1.0
Downloading http://pypi.python.org/packages/source/T/Twisted/Twisted-11.1.0.tar.bz2#md5=972f3497e6e19318c741bf2900ffe31c
Processing Twisted-11.1.0.tar.bz2
Running Twisted-11.1.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-2XCdfX/Twisted-11.1.0/egg-dist-tmp-UYON6N
Traceback (most recent call last):
  File "/usr/local/bin/easy_install", line 8, in <module>
    load_entry_point('setuptools==0.6c11', 'console_scripts', 'easy_install')()
  File "build/bdist.linux-i686/egg/setuptools/command/easy_install.py", line 1712, in main
  File "build/bdist.linux-i686/egg/setuptools/command/easy_install.py", line 1700, in with_ei_usage
  File "build/bdist.linux-i686/egg/setuptools/command/easy_install.py", line 1716, in <lambda>
  File "/usr/local/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/local/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.linux-i686/egg/setuptools/command/easy_install.py", line 211, in run
  File "build/bdist.linux-i686/egg/setuptools/command/easy_install.py", line 446, in easy_install
  File "build/bdist.linux-i686/egg/setuptools/command/easy_install.py", line 476, in install_item
  File "build/bdist.linux-i686/egg/setuptools/command/easy_install.py", line 655, in install_eggs
  File "build/bdist.linux-i686/egg/setuptools/command/easy_install.py", line 930, in build_and_install
  File "build/bdist.linux-i686/egg/setuptools/command/easy_install.py", line 919, in run_setup
  File "build/bdist.linux-i686/egg/setuptools/sandbox.py", line 62, in run_setup
  File "build/bdist.linux-i686/egg/setuptools/sandbox.py", line 105, in run
  File "build/bdist.linux-i686/egg/setuptools/sandbox.py", line 64, in <lambda>
  File "setup.py", line 103, in <module>
  File "setup.py", line 74, in main
  File "setup.py", line 31, in getExtensions
  File "twisted/topfiles/setup.py", line 21, in <module>
ImportError: cannot import name _isCPython
```

Was able to install 11.0.0 in the past on this box withut issues

<details><summary>Searchable metadata</summary>

```
trac-id__5402 5402
type__release_blocker__regression release blocker: regression
reporter__jacek99____ jacek99@...
priority__highest highest
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__worksforme worksforme
component__core core
keywords__ubuntu_install ubuntu install
time__1321897182000000 1321897182000000
changetime__1322402558000000 1322402558000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_2"></a>|@exarkun commented|
|-|-|

This seems to only be a problem with upgrading Twisted using easy_install; ie, `easy_install -U`.  I can install Twisted 11.1 using easy_install _without_ the `-U` option without difficulty on my Ubuntu 10.04 desktop.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_3"></a>|@exarkun commented|
|-|-|

I can't reproduce this using `easy_install -U` either.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_4"></a>|@exarkun set status to `closed`|
|-|-|

See [#5403](https://github.com/twisted/twisted/issues/5403).
