### ISSUE TITLE
Unable to install 11.1.0 with PyPy 1.6

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#5403]
|<img alt="jacek99@...'s avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| jacek99@... reported|
|-|-|
|Trac ID|trac#5403|
|Type|defect|
|Created|2011-11-21 17:42:26Z|

On Ubuntu 10.04 LTS. This error is unusual because it is not related to PyPy C extensions module, but the 'copyright' module

```
pypy -m easy_install twisted
Searching for twisted
Reading http://pypi.python.org/simple/twisted/
Reading http://www.twistedmatrix.com
Reading http://twistedmatrix.com/products/download
Reading http://twistedmatrix.com/
Reading http://tmrc.mit.edu/mirror/twisted/Twisted/9.0/
Reading http://twistedmatrix.com/projects/core/
Reading http://tmrc.mit.edu/mirror/twisted/Twisted/8.1/
Reading http://tmrc.mit.edu/mirror/twisted/Twisted/8.2/
Reading http://tmrc.mit.edu/mirror/twisted/Twisted/10.0/
Best match: Twisted 11.1.0
Downloading http://pypi.python.org/packages/source/T/Twisted/Twisted-11.1.0.tar.bz2#md5=972f3497e6e19318c741bf2900ffe31c
Processing Twisted-11.1.0.tar.bz2
Running Twisted-11.1.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-TSNIil/Twisted-11.1.0/egg-dist-tmp-6UUqsL
Traceback (most recent call last):
  File "app_main.py", line 53, in run_toplevel
  File "/home/jacekf/bin/pypy-1.6/lib-python/2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/jacekf/bin/pypy-1.6/lib-python/2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/jacekf/bin/pypy-1.6/site-packages/distribute-0.6.19-py2.7.egg/easy_install.py", line 5, in <module>
    main()
  File "/home/jacekf/bin/pypy-1.6/site-packages/distribute-0.6.19-py2.7.egg/setuptools/command/easy_install.py", line 1864, in main
    with_ei_usage(lambda:
  File "/home/jacekf/bin/pypy-1.6/site-packages/distribute-0.6.19-py2.7.egg/setuptools/command/easy_install.py", line 1845, in with_ei_usage
    return f()
  File "/home/jacekf/bin/pypy-1.6/site-packages/distribute-0.6.19-py2.7.egg/setuptools/command/easy_install.py", line 1868, in <lambda>
    distclass=DistributionWithoutHelpCommands, **kw
  File "/home/jacekf/bin/pypy-1.6/lib-python/modified-2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/home/jacekf/bin/pypy-1.6/lib-python/modified-2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/home/jacekf/bin/pypy-1.6/lib-python/modified-2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/jacekf/bin/pypy-1.6/site-packages/distribute-0.6.19-py2.7.egg/setuptools/command/easy_install.py", line 345, in run
    self.easy_install(spec, not self.no_deps)
  File "/home/jacekf/bin/pypy-1.6/site-packages/distribute-0.6.19-py2.7.egg/setuptools/command/easy_install.py", line 585, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/home/jacekf/bin/pypy-1.6/site-packages/distribute-0.6.19-py2.7.egg/setuptools/command/easy_install.py", line 615, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/jacekf/bin/pypy-1.6/site-packages/distribute-0.6.19-py2.7.egg/setuptools/command/easy_install.py", line 805, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/home/jacekf/bin/pypy-1.6/site-packages/distribute-0.6.19-py2.7.egg/setuptools/command/easy_install.py", line 1082, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/home/jacekf/bin/pypy-1.6/site-packages/distribute-0.6.19-py2.7.egg/setuptools/command/easy_install.py", line 1071, in run_setup
    run_setup(setup_script, args)
  File "/home/jacekf/bin/pypy-1.6/site-packages/distribute-0.6.19-py2.7.egg/setuptools/sandbox.py", line 30, in run_setup
    lambda: execfile(
  File "/home/jacekf/bin/pypy-1.6/site-packages/distribute-0.6.19-py2.7.egg/setuptools/sandbox.py", line 72, in run
    return func()
  File "/home/jacekf/bin/pypy-1.6/site-packages/distribute-0.6.19-py2.7.egg/setuptools/sandbox.py", line 32, in <lambda>
    {'__file__':setup_script, '__name__':'__main__'}
  File "setup.py", line 103, in <module>
  File "setup.py", line 45, in main
ImportError: cannot import name 'copyright'

```

<details><summary>Searchable metadata</summary>

```
trac-id__5403 5403
type__defect defect
reporter__jacek99____ jacek99@...
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__worksforme worksforme
component__core core
keywords__ 
time__1321897346000000 1321897346000000
changetime__1322402536000000 1322402536000000
version__None None
owner__jacek99____ jacek99@...

```
</details>

**Comment by twisted-trac** [comment]
|<img alt="jacek99@...'s avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_1"></a>|jacek99@... commented|
|-|-|

Pypy 1.6 was compiled on the box from scratch, if that is of any help

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_2"></a>|@exarkun set owner to jacek99@...|
|-|-|

Twisted builds and installs without issue using PyPy on my desktop.  This seems to be a problem with **pip**, or perhaps a problem with pip **on** PyPy.

Can you verify this by downloading Twisted, unpacking it, and running:

  $ pypy setup.py install

instead of using pip?

**Comment by twisted-trac** [comment]
|<img alt="jacek99@...'s avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_3"></a>|jacek99@... commented|
|-|-|

Good news, that works fine.

We should maybe update the docs somewhere to reflect the fact that pypy may have issues with easy_install and installing it manually is recommended instead

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_4"></a>|@exarkun set status to `closed`|
|-|-|

Unfortunately, people trying to install Twisted using easy_install or pip aren't likely to be reading any of our install documentation.  We could write this up to have something to refer them to when they encounter a problem and come looking for help, but I'm not sure how much more of a win that will be than saying "easy_install and pip are not supported".

On other hand, maybe they'll at least do a search first, and perhaps come up with the documentation themselves.

I added <http://twistedmatrix.com/trac/wiki/FrequentlyAskedQuestions#CanIinstallTwistedusingeasy_installorpip>, perhaps that will be sufficient to get people on the right track.

If someone wants to _add_ support to Twisted for being installed in these ways, that would be just fine (I'm just not going to volunteer to do it).
