### ISSUE TITLE
twisted.internet.test.test_tcp.AbortConnectionTestCase_EPollReactor.test_fullWriteBufferAfterByteExchange fails on Python 2.5 on 32 bit Ubuntu Hardy

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#5418]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#5418|
|Type|defect|
|Created|2011-12-03 21:22:21Z|

Seen on BuildBot:

```
[ERROR]
Traceback (most recent call last):
  File "/var/lib/buildbot/bot-glyph-3/hardy32-python2.5-select/Twisted/twisted/internet/test/test_tcp.py", line 1766, in test_fullWriteBufferAfterByteExchange
    EventualNoReadServer)
  File "/var/lib/buildbot/bot-glyph-3/hardy32-python2.5-select/Twisted/twisted/internet/test/test_tcp.py", line 1653, in runAbortTest
    self.runReactor(reactor, timeout=10)
  File "/var/lib/buildbot/bot-glyph-3/hardy32-python2.5-select/Twisted/twisted/internet/test/reactormixins.py", line 206, in runReactor
    "reactor still running after %s seconds" % (timeout,))
twisted.internet.defer.TimeoutError: reactor still running after 10 seconds

twisted.internet.test.test_tcp.AbortConnectionTestCase_EPollReactor.test_fullWriteBufferAfterByteExchange
```

It may also fail on other platforms.

<details><summary>Searchable metadata</summary>

```
trac-id__5418 5418
type__defect defect
reporter__exarkun exarkun
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__ 
time__1322947341000000 1322947341000000
changetime__1323029718000000 1323029718000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

Some minimal investigation into this suggests that the problem is just that the test cannot reliably complete within the 10 second timeout imposed on it.  Sometimes getting through the write loop takes almost the full 10 seconds, particularly when the particular slave this failure was observed on is busy with other tasks (like running other build slaves).

The loop:

```python
       self.transport.registerProducer(self, True)
        for i in range(100):
            self.transport.write("1234567890" * 32000)
```

seems excessive to me.  The code is trying to full up the socket send buffer.  30MB is more than enough to accomplish that.  For example, on Linux:

```
>>> s.getsockopt(socket.SOL_SOCKET, socket.SO_SNDBUF)
16384
```

I'm sure other platforms make different decisions about the size of the send buffer, but I doubt anyone uses anything anywhere near 30MB.

This program suggests that a limit closer to 128kB should be sufficient on Linux, or 64kB on Windows:

```python
from socket import socket
from time import sleep
p = socket()
p.bind(("", 0))
p.listen(3)
c = socket()
c.setblocking(False)
c.connect_ex(('127.0.0.1', p.getsockname()[1]))
s, _ = p.accept()
i = 0
while True:
    try:
        c.send("x")
        i += 1
    except Exception, e:
        print i, e
        break
```

I suggest adopting twice this value as the quantity of bytes to write out in this test.  This complicated by the SSL version of the tests, though, which do not trigger `pauseProducing` with this little data.  It looks like about 16MB must be written to trigger `pauseProducing` on SSL.  That strikes me as a lot.

**Comment by glyph** [comment]
Still flaky today, as `twisted.internet.test.test_tcp.AbortConnectionTests_CFReactorTests.test_fullWriteBufferAfterByteExchange` : 

https://github.com/twisted/twisted/actions/runs/9603200300/job/26485812275

```
===============================================================================
Error: 
Traceback (most recent call last):
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.12/site-packages/twisted/internet/test/test_tcp.py", line 2877, in test_fullWriteBufferAfterByteExchange
    return self.runAbortTest(StreamingProducerClientLater, EventualNoReadServer)
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.12/site-packages/twisted/internet/test/test_tcp.py", line 2763, in runAbortTest
    reactor = runProtocolsWithReactor(self, server, client, self.endpoints)
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.12/site-packages/twisted/internet/test/connectionmixins.py", line 177, in runProtocolsWithReactor
    reactorBuilder.runReactor(reactor)
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.12/site-packages/twisted/internet/test/reactormixins.py", line 351, in runReactor
    raise TestTimeoutError(f"reactor still running after {timeout} seconds")
twisted.internet.test.reactormixins.TestTimeoutError: reactor still running after 120.0 seconds

twisted.internet.test.test_tcp.AbortConnectionTests_CFReactorTests.test_fullWriteBufferAfterByteExchange
-------------------------------------------------------------------------------
Ran 10885 tests in 164.438s
```
