### ISSUE TITLE
Delayed calls in the sufficiently distant future break epoll reactor

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#5472]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#5472|
|Type|defect|
|Created|2012-02-02 16:03:10Z|

Consider:

```
from twisted.internet import epollreactor
epollreactor.install()
from twisted.internet import reactor
reactor.callLater(2 ** 32 - 1, lambda: None)
reactor.run()
```

producing these results:

```
Unhandled Error
Traceback (most recent call last):
  File "<string>", line 6, in <module>
    
  File "/home/exarkun/Projects/Twisted/trunk/twisted/internet/base.py", line 1169, in run
    self.mainLoop()
--- <exception caught here> ---
  File "/home/exarkun/Projects/Twisted/trunk/twisted/internet/base.py", line 1181, in mainLoop
    self.doIteration(t)
  File "/home/exarkun/Projects/Twisted/trunk/twisted/internet/epollreactor.py", line 182, in doPoll
    l = self._poller.wait(len(self._selectables), timeout)
^C  File "_epoll.pyx", line 127, in twisted.python._epoll.epoll.wait (twisted/python/_epoll.c:993)
    
exceptions.OverflowError: value too large to convert to int
```

(effectively) perpetually.

This appears to be a limitation particular to epoll, perhaps due to our custom Cython bindings.  The checks for delayed calls may need a review anyway, particularly in `DelayedCall.reset` and `DelayedCall.delay`.

<details><summary>Searchable metadata</summary>

```
trac-id__5472 5472
type__defect defect
reporter__exarkun exarkun
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__duplicate duplicate
component__core core
keywords__ 
time__1328198590000000 1328198590000000
changetime__1360795417000000 1360795417000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="tomprince's avatar" src="https://avatars.githubusercontent.com/u/283816?s=50" width="50" height="50">](https://github.com/tomprince)<a name="note_1"></a>|@tomprince set status to `closed`|
|-|-|

This is a duplicate of [#6259](https://github.com/twisted/twisted/issues/6259). (Closing the older ticket as the newer one has a patch)
