### ISSUE TITLE
twisted.names.cache.CacheResolver gives a negative TTL resulting in exception encoding DNS result

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#5579]
|<img alt="acidfoo's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| acidfoo reported|
|-|-|
|Trac ID|trac#5579|
|Type|defect|
|Created|2012-03-28 13:52:37Z|
|Branch|https://github.com/twisted/twisted/tree/cacheresolver-negative-ttl-5579|

If a DNS resolver is under heavy load, there is a possibility that a query is executed exactly when the entry's TTL will expire in the cache. The deletion of the entry from the cache is done by callLater and this isn't completely accurate. If there is a query exactly when this cached entry is about to expire it results in a TTL that is < 0 which causes a struct exception.

This was picked up when using a TTL of 0 (if two queries arrive fast enough it will trigger the error) - but it can theoretically affect any TTL. 

Here is the traceback that is generated:
```
2012-03-28 11:33:30+0000 [DNSDatagramProtocol (UDP)] Unhandled Error
        Traceback (most recent call last):
          File "/usr/lib/python2.7/dist-packages/twisted/names/server.py", line 192, in messageReceived
            self.handleQuery(message, proto, address)
          File "/usr/lib/python2.7/dist-packages/twisted/names/server.py", line 137, in handleQuery
            self.gotResolverResponse, protocol, message, address
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 301, in addCallback
            callbackKeywords=kw)
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 290, in addCallbacks
            self._runCallbacks()
        --- <exception caught here> ---
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 551, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "/usr/lib/python2.7/dist-packages/twisted/names/server.py", line 107, in gotResolverResponse
            self.sendReply(protocol, message, address)
          File "/usr/lib/python2.7/dist-packages/twisted/names/server.py", line 92, in sendReply
            protocol.writeMessage(message, address)
          File "/usr/lib/python2.7/dist-packages/twisted/names/dns.py", line 1804, in writeMessage
            self.transport.write(message.toStr(), address)
          File "/usr/lib/python2.7/dist-packages/twisted/names/dns.py", line 1686, in toStr
            self.encode(strio)
          File "/usr/lib/python2.7/dist-packages/twisted/names/dns.py", line 1587, in encode
            q.encode(body_tmp, compDict)
          File "/usr/lib/python2.7/dist-packages/twisted/names/dns.py", line 497, in encode
            strio.write(struct.pack(self.fmt, self.type, self.cls, self.ttl, 0))
        struct.error: integer out of range for 'I' format code
```

Attachments:

* [cache.diff](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/4b4/4b43bd91895f09dd4192f59ff43a27c98ad7a779/a02a9c435dce34244347eda75676bb61947ed0e5.diff) (2741 bytes) - added by acidfoo on 2012-03-28 13:53:06Z - 
* [cache_clock.diff](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/4b4/4b43bd91895f09dd4192f59ff43a27c98ad7a779/3cb255359a9ae511e05ee6e4392b2f3ade06b3b2.diff) (3184 bytes) - added by acidfoo on 2012-04-08 21:01:17Z - 
* [cache_clock.2.diff](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/4b4/4b43bd91895f09dd4192f59ff43a27c98ad7a779/56a4f6320d420c60503c3b6e77c81b214c59e713.diff) (3147 bytes) - added by acidfoo on 2012-04-08 21:30:14Z - 

<details><summary>Searchable metadata</summary>

```
trac-id__5579 5579
type__defect defect
reporter__acidfoo acidfoo
priority__normal normal
milestone__ 
branch__branches_cacheresolver_negative_ttl_5579 branches/cacheresolver-negative-ttl-5579
branch_author__acidfoo acidfoo
status__closed closed
resolution__fixed fixed
component__names names
keywords__ 
time__1332942757000000 1332942757000000
changetime__1334584780000000 1334584780000000
version__None None
owner__itamar itamar

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="jonathanj's avatar" src="https://avatars.githubusercontent.com/u/112166?s=50" width="50" height="50">](https://github.com/jonathanj)<a name="note_2"></a>|@jonathanj commented|
|-|-|

(In [34046]) Branching to 'cacheresolver-negative-ttl-5579'

**Comment by twisted-trac** [comment]
|[<img alt="jonathanj's avatar" src="https://avatars.githubusercontent.com/u/112166?s=50" width="50" height="50">](https://github.com/jonathanj)<a name="note_3"></a>|@jonathanj commented|
|-|-|

Buildbot results: http://buildbot.twistedmatrix.com/boxes-supported?branch=/branches/cacheresolver-negative-ttl-5579

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)<a name="note_4"></a>|@itamarst set owner to @itamarst|
|-|-|

In general, looks good.

However, the use of time.time() and "ttl >= 0" is not ideal; ideally tests would be completely deterministic. The way to do this is to:

  1. Add reactor as optional argument to CacheResolver.__init__. If no argument is given, use "twisted.internet.reactor". Store the given reactor as an attribute of the CacheResolver.
  1. Replace all calls to `time.time()` with `self._reactor.seconds()`.
  1. Replace all calls to `reactor.callLater()` with `self._reactor.callLater()`.

This would allow using a `twisted.internet.task.Clock` instance as a replacement reactor for the unit tests, thus enabling the tests to be completely deterministic. I will try to just go ahead and do this myself, if no one beats me to it.

**Comment by twisted-trac** [comment]
|<img alt="acidfoo's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_5"></a>|acidfoo removed owner|
|-|-|

Added a new patch to use task.Clock() and updated unit tests to use this. The patch is based on the branch "cacheresolver-negative-ttl-5579" so doesn't include the original changes - wasn't sure if this was the correct way to do it.

**Comment by twisted-trac** [comment]
|<img alt="acidfoo's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_6"></a>|acidfoo commented|
|-|-|

Removed a newline that was added after imports by mistake

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)<a name="note_7"></a>|@itamarst set owner to @itamarst|
|-|-|

Looks pretty good.

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)<a name="note_8"></a>|@itamarst commented|
|-|-|

I added news file, expanded tests slightly, and renamed attribute from clock to _reactor, but these were all pretty minor changes. So, running tests:

http://buildbot.twistedmatrix.com/boxes-supported?branch=/branches/cacheresolver-negative-ttl-5579

If they pass I'll merge in the morning.

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)<a name="note_9"></a>|@itamarst set status to `closed`|
|-|-|

(In [34157]) Merge cacheresolver-negative-ttl-5579: Don't get negative TTLs from DNS cache.

Author: acidfoo
Review: itamar
Fixes: [#5579](https://github.com/twisted/twisted/issues/5579)

CacheResolver now makes sure TTLs it returns are never negative.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_10"></a>|@exarkun commented|
|-|-|

I'm a bit surprised by the approach taken here.  Rather than serving expired data with a TTL of 0, why not _not_ serve expired?  It's not a major problem, I guess, since the data is only just barely expired.  It seems like not serving it would be a bit better, though.

**Comment by twisted-trac** [comment]
|<img alt="acidfoo's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_11"></a>|acidfoo commented|
|-|-|

You are probably right, I think my brain just saw struct throwing an error because of a negative number and jumped straight to making the number not negative. Practically it's not going to make much difference but logically it shouldn't serve something that is expired. It will also mean that results that originally had a TTL of 0 will not be cached at all, as opposed to now where they will be cached for a tiny amount of time. I'll rework this in the next few days when I find a bit of spare time. Would it be better to reopen this ticket or start a new one?

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)<a name="note_12"></a>|@itamarst commented|
|-|-|

Note that there's two ways you can go: actually removing stuff if it's looked up and has TTL <= 0, and then returning nothing, or just returning nothing and not modifying anything. You seem to be going down the first path, but I would suggest sticking to the second path: actively removing stuff from the cache involves race conditions with the timeout and doesn't add any value since the external behavior doesn't change.

There is a separate problem involving cache initialization, see the newly filed [#5638](https://github.com/twisted/twisted/issues/5638).

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_13"></a>|@exarkun commented|
|-|-|

> Would it be better to reopen this ticket or start a new one?

The only way tickets get re-opened is to revert the commit that closed them.  So, new ticket. :)

**Comment by twisted-trac** [comment]
|<img alt="acidfoo's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_14"></a>|acidfoo commented|
|-|-|

Alternative to not return expired results is at [#5647](https://github.com/twisted/twisted/issues/5647)
