### ISSUE TITLE
LoopingCall possible re-entrancy bug

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#5626]
|<img alt="Dev0n's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| Dev0n reported|
|-|-|
|Trac ID|trac#5626|
|Type|defect|
|Created|2012-04-09 13:52:17Z|

Getting the following traceback for the code attached. After a conversation with itamar in #twisted, he suggested it that it might be a re-entrancy bug.

The traceback:

```
2012-04-09 14:50:50+0100 [-] Unhandled Error
  Traceback (most recent call last):
    File "/usr/local/lib/python2.6/dist-packages/Twisted-12.0.0-py2.6-linux-x86_64.egg/twisted/internet/base.py", line 1178, in mainLoop
      self.runUntilCurrent()
    File "/usr/local/lib/python2.6/dist-packages/Twisted-12.0.0-py2.6-linux-x86_64.egg/twisted/internet/base.py", line 800, in runUntilCurrent
      call.func(*call.args, **call.kw)
    File "/usr/local/lib/python2.6/dist-packages/Twisted-12.0.0-py2.6-linux-x86_64.egg/twisted/internet/defer.py", line 368, in callback
      self._startRunCallbacks(result)
    File "/usr/local/lib/python2.6/dist-packages/Twisted-12.0.0-py2.6-linux-x86_64.egg/twisted/internet/defer.py", line 464, in _startRunCallbacks
      self._runCallbacks()
  --- <exception caught here> ---
    File "/usr/local/lib/python2.6/dist-packages/Twisted-12.0.0-py2.6-linux-x86_64.egg/twisted/internet/defer.py", line 551, in _runCallbacks
      current.result = callback(current.result, *args, **kw)
    File "/usr/local/lib/python2.6/dist-packages/Twisted-12.0.0-py2.6-linux-x86_64.egg/twisted/internet/task.py", line 212, in eb
      d.errback(failure)
  exceptions.AttributeError: 'NoneType' object has no attribute 'errback'
```

Attachments:

* [txLCbug.py](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/8d7/8d7b7bd14327341ba2db82399b79b05618f7b008/42d2b6f8bac4e9aff035c5e1833d0c280309d8af.py) (659 bytes) - added by Dev0n on 2012-04-09 13:52:32Z - 

<details><summary>Searchable metadata</summary>

```
trac-id__5626 5626
type__defect defect
reporter__Dev0n Dev0n
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__duplicate duplicate
component__core core
keywords__LoopingCall_re_entrancy LoopingCall re-entrancy
time__1333979537000000 1333979537000000
changetime__1334014688000000 1334014688000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun set status to `closed`|
|-|-|

Seems very much like a duplicate of [#2998](https://github.com/twisted/twisted/issues/2998).
