### ISSUE TITLE
t.p.reflect.fullyQualifiedName doesn't support method descriptors.

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#5644]
|[<img alt="dreid's avatar" src="https://avatars.githubusercontent.com/u/48695?s=50" width="50" height="50">](https://github.com/dreid)| @dreid reported|
|-|-|
|Trac ID|trac#5644|
|Type|enhancement|
|Created|2012-04-13 03:41:19Z|
|Branch|https://github.com/twisted/twisted/tree/fullyQualifiedName-methoddescriptor-5644-3|

```
>>> fullyQualifiedName(set.add)
'add'
```

when the correct FQN is ```__builtin__.set.add```

```namedAny``` already does the right thing when handed ```__builtin__.set.add```

```
>>> namedAny('__builtin__.set.add')
<method 'add' of 'set' objects>
```

<details><summary>Searchable metadata</summary>

```
trac-id__5644 5644
type__enhancement enhancement
reporter__dreid dreid
priority__normal normal
milestone__ 
branch__branches_fullyQualifiedName_methoddescriptor_5644_3 branches/fullyQualifiedName-methoddescriptor-5644-3
branch_author__dreid dreid
status__new new
resolution__None None
component__core core
keywords__ 
time__1334288479000000 1334288479000000
changetime__1372336910000000 1372336910000000
version__None None
owner__dreid dreid

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="dreid's avatar" src="https://avatars.githubusercontent.com/u/48695?s=50" width="50" height="50">](https://github.com/dreid)<a name="note_1"></a>|@dreid commented|
|-|-|

(In [34196]) Branching to 'fullyQualifiedName-methoddescriptor-5644'

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_3"></a>|@exarkun commented|
|-|-|

[Build results](http://buildbot.twistedmatrix.com/boxes-supported?branch=/branches/fullyQualifiedName-methoddescriptor-5644)

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_4"></a>|@thijstriemstra set owner to @dreid|
|-|-|

These are doc issues in t.python.deprecate not directly related to your code but simple enough to fix while we're in that module:

 * in `getDeprecationWarningString` the docstring has duplicate `@param` definitions
 * same for `@param version` in `deprecated`
 * `warnAboutFunction` documents a `function` param but this should be `offender`

Also needs a feature or bugfix news file.

**Comment by twisted-trac** [comment]
|[<img alt="dreid's avatar" src="https://avatars.githubusercontent.com/u/48695?s=50" width="50" height="50">](https://github.com/dreid)<a name="note_5"></a>|@dreid removed owner|
|-|-|

I addressed the unrelated docstring issues and added a news fragment.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_6"></a>|@exarkun set owner to @dreid|
|-|-|

Thanks.  Two points:

  1. in `warnAboutFunction`, _C{function}_ doesn't make much sense.  Just _function_, or perhaps _L{types.FunctionType}_, or maybe _no-argument callable_ would be better.
  1. `inspect.ismethoddescriptor` looks like a sort of useless predict.  The documentation says all it guarantees is the argument has `__get__` and does not have `__set__` and that some of the other `inspect.is*` functions would return False.  In particular, it says nothing at all about `__objclass__`.  Should we just check for the existence of `__objclass__`?  These kinds of objects seem pretty gross and obscure. :/

**Comment by twisted-trac** [comment]
|[<img alt="dreid's avatar" src="https://avatars.githubusercontent.com/u/48695?s=50" width="50" height="50">](https://github.com/dreid)<a name="note_7"></a>|@dreid commented|
|-|-|

(In [34761]) Branching to 'fullyQualifiedName-methoddescriptor-5644-2'

**Comment by twisted-trac** [comment]
|[<img alt="dreid's avatar" src="https://avatars.githubusercontent.com/u/48695?s=50" width="50" height="50">](https://github.com/dreid)<a name="note_8"></a>|@dreid commented|
|-|-|

(In [34762]) Merge forward. refs [#5644](https://github.com/twisted/twisted/issues/5644)

**Comment by twisted-trac** [comment]
|[<img alt="dreid's avatar" src="https://avatars.githubusercontent.com/u/48695?s=50" width="50" height="50">](https://github.com/dreid)<a name="note_9"></a>|@dreid commented|
|-|-|

(In [38662]) Branching to fullyQualifiedName-methoddescriptor-5644-3.

**Comment by twisted-trac** [comment]
|[<img alt="dreid's avatar" src="https://avatars.githubusercontent.com/u/48695?s=50" width="50" height="50">](https://github.com/dreid)<a name="note_10"></a>|@dreid commented|
|-|-|

(In [38663]) Merging forward.  Refs [#5644](https://github.com/twisted/twisted/issues/5644)

**Comment by twisted-trac** [comment]
|[<img alt="dreid's avatar" src="https://avatars.githubusercontent.com/u/48695?s=50" width="50" height="50">](https://github.com/dreid)<a name="note_11"></a>|@dreid commented|
|-|-|

(In [38664]) Parameterize expected value because int.__module__ differs between py2 and py3.  Refs [#5644](https://github.com/twisted/twisted/issues/5644)

**Comment by twisted-trac** [comment]
|[<img alt="dreid's avatar" src="https://avatars.githubusercontent.com/u/48695?s=50" width="50" height="50">](https://github.com/dreid)|@dreid removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_13"></a>|@exarkun set owner to @dreid|
|-|-|

Thanks!  I love `fullyQualifiedName` and I love fixes to its handling of dark corner cases even more.

  1. in `twisted/python/deprecate.py`
    1. Please use `getattr` instead of `hasattr` - _particularly_ when the object is arbitrary and application-supplied.
  1. There are some confusing deletions in the branch that seem... accidental?  Docstrings of getDeprecationWarningString and deprecated and test_boundMethod seem worse than they were before.

Otherwise seems good, but I'm somewhat confused by (2) so I don't want to say "fix those and merge".

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_14"></a>|@exarkun commented|
|-|-|

Oh yes, one more thing I forgot, http://buildbot.twistedmatrix.com/builders/python-3.3-tests/builds/932/steps/shell/logs/stdio has a failure:

```
======================================================================
FAIL: test_circularChainWarning (twisted.test.test_defer.DeferredTestCase)
test_circularChainWarning
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/buildbot/buildarea/python-3.3-tests/Twisted/twisted/trial/_synctest.py", line 1211, in _run
    runWithWarningsSuppressed(suppress, method)
  File "/var/lib/buildbot/buildarea/python-3.3-tests/Twisted/twisted/python/util.py", line 1065, in runWithWarningsSuppressed
    return f(*args, **kwargs)
  File "/var/lib/buildbot/buildarea/python-3.3-tests/Twisted/twisted/test/test_defer.py", line 922, in test_circularChainWarning
    "\nExpected match: %r\nGot: %r" % (pattern, warning['message']))
  File "/var/lib/buildbot/buildarea/python-3.3-tests/Twisted/twisted/trial/_synctest.py", line 308, in assertTrue
    raise self.failureException(msg)
twisted.trial.unittest.FailTest: 
Expected match: 'Callback <function circularCallback at 0x\\w+> returned the same Deferred it was attached to'
Got: 'Callback <function DeferredTestCase.test_circularChainWarning.<locals>.circularCallback at 0x7fced8c6ecb0> returned the same Deferred it was attached to; this breaks the callback chain and will raise an exception in the future.'

----------------------------------------------------------------------
```
