### ISSUE TITLE
twisted.python._epoll slightly broken when built with glibc >= 2.15

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#5663]
|<img alt="marienz's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| marienz reported|
|-|-|
|Trac ID|trac#5663|
|Type|defect|
|Created|2012-04-30 20:28:43Z|
|Branch|https://github.com/twisted/twisted/tree/unsigned-epoll-flag-5663|

When built with glibc 2.15 _epoll from twisted 12.0.0 or trunk fails like this:

```
[ERROR]
Traceback (most recent call last):
  File "/home/marienz/share/src/twisted-svn/twisted/test/test_epoll.py", line 108, in test_controlAndWait
    _epoll.ET)
  File "_epoll.pyx", line 212, in twisted.python._epoll.epoll._control (twisted/python/_epoll.c:1571)
    
exceptions.OverflowError: value too large to convert to int

twisted.test.test_epoll.EPoll.test_controlAndWait
```

What's going on here is that the definition of EPOLLET (provided by glibc in sys/epoll.h) changed from (1 << 31) to 1u << 31, which caused the value of twisted.python._epoll.ET to change from -0x80000000 to 0x80000000. As _control (and a few other methods) are defined as taking "int events" and the new value of ET does not fit in a signed int an OverflowError results.

As "events" is actually used to set the field "events" in a struct epoll_event, and the "events" field has been of type uint32_t even when EPOLLET had the (1 << 31) definition, I think EPOLLET actually should be positive and those methods should take a uint32_t. Adding a cast to uint32_t to the EPOLLET definition in the pyx makes _epoll.ET positive even when compiled with older glibc headers.

I'm attaching just the patch to _epoll.pyx, as the cython I have here is newer than the one _epoll.c was generated with, making for a rather noisy diff. I have checked this now passes tests on a system with glibc 2.15. I've also manually checked _epoll.ET is positive when compiled and run against an older glibc, and that passing the positive value to the _control method works.

This is not all that interesting for twisted trunk, where _epoll is only used on old pythons (and the combination of old python/new glibc is probably not very common). Some distributions might want a backport of this for twisted 12.0.0 though.

Attachments:

* [twisted-epoll.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/c34/c34a1d3e46947ce5b4f3239f067d52eb81c3b1f5/6e2cfe12e9d32c8335a39c413542b6f504d6a467.patch) (1285 bytes) - added by marienz on 2012-04-30 20:29:25Z - changes to _epoll.pyx to consistently use unsigned events

<details><summary>Searchable metadata</summary>

```
trac-id__5663 5663
type__defect defect
reporter__marienz marienz
priority__normal normal
milestone__ 
branch__branches_unsigned_epoll_flag_5663 branches/unsigned-epoll-flag-5663
branch_author__therve therve
status__closed closed
resolution__wontfix wontfix
component__core core
keywords__ 
time__1335817723000000 1335817723000000
changetime__1362574591000000 1362574591000000
version__None None
owner__marienz marienz
cc__Arfrever
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="marienz's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_1"></a>|marienz commented|
|-|-|

Should not need a full-blown NEWS file entry, so I think this is ready for review.

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_3"></a>|@therve commented|
|-|-|

(In [34374]) Branching to 'unsigned-epoll-flag-5663'

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_4"></a>|@therve commented|
|-|-|

So the patch was incorrect for some reasons, and was failing for builders, and failed for me even with glibc 2.15.0. I made a different change which seems to make the tests happy, but then again, we don't have build slaves which show the problem. And, trunk works fine for me with glibc 2.15. Are you sure of your diagnostic?

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_5"></a>|@therve commented|
|-|-|

See http://buildbot.twistedmatrix.com/boxes-supported?branch=/branches/unsigned-epoll-flag-5663 for the builds.

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_6"></a>|@therve set owner to marienz|
|-|-|

Putting it out of review waiting for feedback.

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)<a name="note_7"></a>|@itamarst commented|
|-|-|

Given we just dropped support for Python 2.5, and Python 2.6 includes epoll support, seems easier to just remove the _epoll.pyx code altogether.

**Comment by twisted-trac** [comment]
|<img alt="marienz's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_8"></a>|marienz commented|
|-|-|

Removing the code makes much more sense. I fixed this before I realized _epoll was no longer all that relevant (I was looking at 12.0, not trunk). If there's a reason to keep _epoll then the changes in the branch look good to me. 

I'd overlooked that cython makes EPOLLET a python int, which on a 32-bit system will not hold 1 << 31. This masks the problem with glibc 2.15 in the original code, and makes my modified code break (with either glibc 2.15 or older). The additional change in the branch causes cython to make EPOLLET a python long if it needs to be, which should make no difference on 64-bit, and if the tests are happy also on 32-bit.

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_9"></a>|@therve set status to `closed`|
|-|-|

We're remove epoll custom bindings in [#5847](https://github.com/twisted/twisted/issues/5847). Thanks for the patch!
