### ISSUE TITLE
twisted.internet.test.test_unix in Twisted 12.1.0: Multiple failures and errors

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#5701]
|<img alt="Arfrever's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| Arfrever reported|
|-|-|
|Trac ID|trac#5701|
|Type|defect|
|Created|2012-06-06 02:31:58Z|

twisted.internet.test.test_unix module has new tests in Twisted 12.1.0, which fail. All failing tests were absent in Twisted 12.0.0.

```
twisted.internet.test.test_unix
  UNIXDatagramTestsBuilder_EPollReactor
    test_listenMode ...                                                    [OK]
    test_listenOnLinuxAbstractNamespace ...                                [OK]
  UNIXDatagramTestsBuilder_GIReactor
    test_listenMode ...                                               [SKIPPED]
    test_listenOnLinuxAbstractNamespace ...                           [SKIPPED]
  UNIXDatagramTestsBuilder_Glib2Reactor
    test_listenMode ...                                                    [OK]
    test_listenOnLinuxAbstractNamespace ...                                [OK]
  UNIXDatagramTestsBuilder_Gtk2Reactor
    test_listenMode ...                                                    [OK]
    test_listenOnLinuxAbstractNamespace ...                                [OK]
  UNIXDatagramTestsBuilder_Gtk3Reactor
    test_listenMode ...                                               [SKIPPED]
    test_listenOnLinuxAbstractNamespace ...                           [SKIPPED]
  UNIXDatagramTestsBuilder_PollReactor
    test_listenMode ...                                                    [OK]
    test_listenOnLinuxAbstractNamespace ...                                [OK]
  UNIXDatagramTestsBuilder_SelectReactor
    test_listenMode ...                                                    [OK]
    test_listenOnLinuxAbstractNamespace ...                                [OK]
  UNIXPortTestsBuilder_EPollReactor
    test_allNewStyle ...                                                   [OK]
    test_connectionLostLogMsg ...                                          [OK]
    test_startedListeningLogMessage ...                                    [OK]
  UNIXPortTestsBuilder_GIReactor
    test_allNewStyle ...                                              [SKIPPED]
    test_connectionLostLogMsg ...                                     [SKIPPED]
    test_startedListeningLogMessage ...                               [SKIPPED]
  UNIXPortTestsBuilder_Glib2Reactor
    test_allNewStyle ...                                                   [OK]
    test_connectionLostLogMsg ...                                          [OK]
    test_startedListeningLogMessage ...                                    [OK]
  UNIXPortTestsBuilder_Gtk2Reactor
    test_allNewStyle ...                                                   [OK]
    test_connectionLostLogMsg ...                                          [OK]
    test_startedListeningLogMessage ...                                    [OK]
  UNIXPortTestsBuilder_Gtk3Reactor
    test_allNewStyle ...                                              [SKIPPED]
    test_connectionLostLogMsg ...                                     [SKIPPED]
    test_startedListeningLogMessage ...                               [SKIPPED]
  UNIXPortTestsBuilder_PollReactor
    test_allNewStyle ...                                                   [OK]
    test_connectionLostLogMsg ...                                          [OK]
    test_startedListeningLogMessage ...                                    [OK]
  UNIXPortTestsBuilder_SelectReactor
    test_allNewStyle ...                                                   [OK]
    test_connectionLostLogMsg ...                                          [OK]
    test_startedListeningLogMessage ...                                    [OK]
  UNIXTestsBuilder_EPollReactor
    test_addresses ...                                                     [OK]
    test_avoidLeakingFileDescriptors ...                                 [FAIL]
    test_connectToLinuxAbstractNamespace ...                               [OK]
    test_descriptorDeliveredBeforeBytes ...                              [FAIL]
    test_fileDescriptorOverrun ...                                         [OK]
    test_interface ...                                                     [OK]
    test_listenOnLinuxAbstractNamespace ...                                [OK]
    test_logPrefix ...                                                     [OK]
    test_mode ...                                                          [OK]
    test_protocolGarbageAfterLostConnection ...                            [OK]
    test_sendFileDescriptor ...                                         [ERROR]
    test_sendFileDescriptorTriggersPauseProducing ...                      [OK]
    test_writeAfterDisconnect ...                                          [OK]
  UNIXTestsBuilder_GIReactor
    test_addresses ...                                                [SKIPPED]
    test_avoidLeakingFileDescriptors ...                              [SKIPPED]
    test_connectToLinuxAbstractNamespace ...                          [SKIPPED]
    test_descriptorDeliveredBeforeBytes ...                           [SKIPPED]
    test_fileDescriptorOverrun ...                                    [SKIPPED]
    test_interface ...                                                [SKIPPED]
    test_listenOnLinuxAbstractNamespace ...                           [SKIPPED]
    test_logPrefix ...                                                [SKIPPED]
    test_mode ...                                                     [SKIPPED]
    test_protocolGarbageAfterLostConnection ...                       [SKIPPED]
    test_sendFileDescriptor ...                                       [SKIPPED]
    test_sendFileDescriptorTriggersPauseProducing ...                 [SKIPPED]
    test_writeAfterDisconnect ...                                     [SKIPPED]
  UNIXTestsBuilder_Glib2Reactor
    test_addresses ...                                                     [OK]
    test_avoidLeakingFileDescriptors ...                                 [FAIL]
    test_connectToLinuxAbstractNamespace ...                               [OK]
    test_descriptorDeliveredBeforeBytes ...                              [FAIL]
    test_fileDescriptorOverrun ...                                         [OK]
    test_interface ...                                                     [OK]
    test_listenOnLinuxAbstractNamespace ...                                [OK]
    test_logPrefix ...                                                     [OK]
    test_mode ...                                                          [OK]
    test_protocolGarbageAfterLostConnection ...                            [OK]
    test_sendFileDescriptor ...                                         [ERROR]
    test_sendFileDescriptorTriggersPauseProducing ...                      [OK]
    test_writeAfterDisconnect ...                                          [OK]
  UNIXTestsBuilder_Gtk2Reactor
    test_addresses ...                                                     [OK]
    test_avoidLeakingFileDescriptors ...                                 [FAIL]
    test_connectToLinuxAbstractNamespace ...                               [OK]
    test_descriptorDeliveredBeforeBytes ...                              [FAIL]
    test_fileDescriptorOverrun ...                                         [OK]
    test_interface ...                                                     [OK]
    test_listenOnLinuxAbstractNamespace ...                                [OK]
    test_logPrefix ...                                                     [OK]
    test_mode ...                                                          [OK]
    test_protocolGarbageAfterLostConnection ...                            [OK]
    test_sendFileDescriptor ...                                         [ERROR]
    test_sendFileDescriptorTriggersPauseProducing ...                      [OK]
    test_writeAfterDisconnect ...                                          [OK]
  UNIXTestsBuilder_Gtk3Reactor
    test_addresses ...                                                [SKIPPED]
    test_avoidLeakingFileDescriptors ...                              [SKIPPED]
    test_connectToLinuxAbstractNamespace ...                          [SKIPPED]
    test_descriptorDeliveredBeforeBytes ...                           [SKIPPED]
    test_fileDescriptorOverrun ...                                    [SKIPPED]
    test_interface ...                                                [SKIPPED]
    test_listenOnLinuxAbstractNamespace ...                           [SKIPPED]
    test_logPrefix ...                                                [SKIPPED]
    test_mode ...                                                     [SKIPPED]
    test_protocolGarbageAfterLostConnection ...                       [SKIPPED]
    test_sendFileDescriptor ...                                       [SKIPPED]
    test_sendFileDescriptorTriggersPauseProducing ...                 [SKIPPED]
    test_writeAfterDisconnect ...                                     [SKIPPED]
  UNIXTestsBuilder_PollReactor
    test_addresses ...                                                     [OK]
    test_avoidLeakingFileDescriptors ...                                 [FAIL]
    test_connectToLinuxAbstractNamespace ...                               [OK]
    test_descriptorDeliveredBeforeBytes ...                              [FAIL]
    test_fileDescriptorOverrun ...                                         [OK]
    test_interface ...                                                     [OK]
    test_listenOnLinuxAbstractNamespace ...                                [OK]
    test_logPrefix ...                                                     [OK]
    test_mode ...                                                          [OK]
    test_protocolGarbageAfterLostConnection ...                            [OK]
    test_sendFileDescriptor ...                                         [ERROR]
    test_sendFileDescriptorTriggersPauseProducing ...                      [OK]
    test_writeAfterDisconnect ...                                          [OK]
  UNIXTestsBuilder_SelectReactor
    test_addresses ...                                                     [OK]
    test_avoidLeakingFileDescriptors ...                                 [FAIL]
    test_connectToLinuxAbstractNamespace ...                               [OK]
    test_descriptorDeliveredBeforeBytes ...                              [FAIL]
    test_fileDescriptorOverrun ...                                         [OK]
    test_interface ...                                                     [OK]
    test_listenOnLinuxAbstractNamespace ...                                [OK]
    test_logPrefix ...                                                     [OK]
    test_mode ...                                                          [OK]
    test_protocolGarbageAfterLostConnection ...                            [OK]
    test_sendFileDescriptor ...                                         [ERROR]
    test_sendFileDescriptorTriggersPauseProducing ...                      [OK]
    test_writeAfterDisconnect ...                                          [OK]

===============================================================================
[SKIPPED]
No module named gi.repository

twisted.internet.test.test_unix.UNIXDatagramTestsBuilder_GIReactor.test_listenMode
twisted.internet.test.test_unix.UNIXDatagramTestsBuilder_GIReactor.test_listenOnLinuxAbstractNamespace
twisted.internet.test.test_unix.UNIXDatagramTestsBuilder_Gtk3Reactor.test_listenMode
twisted.internet.test.test_unix.UNIXDatagramTestsBuilder_Gtk3Reactor.test_listenOnLinuxAbstractNamespace
twisted.internet.test.test_unix.UNIXPortTestsBuilder_GIReactor.test_allNewStyle
twisted.internet.test.test_unix.UNIXPortTestsBuilder_GIReactor.test_connectionLostLogMsg
twisted.internet.test.test_unix.UNIXPortTestsBuilder_GIReactor.test_startedListeningLogMessage
twisted.internet.test.test_unix.UNIXPortTestsBuilder_Gtk3Reactor.test_allNewStyle
twisted.internet.test.test_unix.UNIXPortTestsBuilder_Gtk3Reactor.test_connectionLostLogMsg
twisted.internet.test.test_unix.UNIXPortTestsBuilder_Gtk3Reactor.test_startedListeningLogMessage
twisted.internet.test.test_unix.UNIXTestsBuilder_GIReactor.test_addresses
twisted.internet.test.test_unix.UNIXTestsBuilder_GIReactor.test_avoidLeakingFileDescriptors
twisted.internet.test.test_unix.UNIXTestsBuilder_GIReactor.test_connectToLinuxAbstractNamespace
twisted.internet.test.test_unix.UNIXTestsBuilder_GIReactor.test_descriptorDeliveredBeforeBytes
twisted.internet.test.test_unix.UNIXTestsBuilder_GIReactor.test_fileDescriptorOverrun
twisted.internet.test.test_unix.UNIXTestsBuilder_GIReactor.test_interface
twisted.internet.test.test_unix.UNIXTestsBuilder_GIReactor.test_listenOnLinuxAbstractNamespace
twisted.internet.test.test_unix.UNIXTestsBuilder_GIReactor.test_logPrefix
twisted.internet.test.test_unix.UNIXTestsBuilder_GIReactor.test_mode
twisted.internet.test.test_unix.UNIXTestsBuilder_GIReactor.test_protocolGarbageAfterLostConnection
twisted.internet.test.test_unix.UNIXTestsBuilder_GIReactor.test_sendFileDescriptor
twisted.internet.test.test_unix.UNIXTestsBuilder_GIReactor.test_sendFileDescriptorTriggersPauseProducing
twisted.internet.test.test_unix.UNIXTestsBuilder_GIReactor.test_writeAfterDisconnect
twisted.internet.test.test_unix.UNIXTestsBuilder_Gtk3Reactor.test_addresses
twisted.internet.test.test_unix.UNIXTestsBuilder_Gtk3Reactor.test_avoidLeakingFileDescriptors
twisted.internet.test.test_unix.UNIXTestsBuilder_Gtk3Reactor.test_connectToLinuxAbstractNamespace
twisted.internet.test.test_unix.UNIXTestsBuilder_Gtk3Reactor.test_descriptorDeliveredBeforeBytes
twisted.internet.test.test_unix.UNIXTestsBuilder_Gtk3Reactor.test_fileDescriptorOverrun
twisted.internet.test.test_unix.UNIXTestsBuilder_Gtk3Reactor.test_interface
twisted.internet.test.test_unix.UNIXTestsBuilder_Gtk3Reactor.test_listenOnLinuxAbstractNamespace
twisted.internet.test.test_unix.UNIXTestsBuilder_Gtk3Reactor.test_logPrefix
twisted.internet.test.test_unix.UNIXTestsBuilder_Gtk3Reactor.test_mode
twisted.internet.test.test_unix.UNIXTestsBuilder_Gtk3Reactor.test_protocolGarbageAfterLostConnection
twisted.internet.test.test_unix.UNIXTestsBuilder_Gtk3Reactor.test_sendFileDescriptor
twisted.internet.test.test_unix.UNIXTestsBuilder_Gtk3Reactor.test_sendFileDescriptorTriggersPauseProducing
twisted.internet.test.test_unix.UNIXTestsBuilder_Gtk3Reactor.test_writeAfterDisconnect
===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/twisted-12.1.0-r1000/temp/tests-2.7/usr/lib64/python2.7/site-packages/twisted/internet/test/test_unix.py", line 454, in test_avoidLeakingFileDescriptors
    expectedEvent, pformat(events,)))
twisted.trial.unittest.FailTest: Expected event ({'protocolName': 'ConnectableProtocol', 'format': '%(protocolName)s (on %(hostAddress)r) does not provide IFileDescriptorReceiver; closing file descriptor received (from %(peerAddress)r).', 'hostAddress': UNIXAddress(None), 'peerAddress': UNIXAddress('./tmpkMiBIA.sock')}) not found in logged events ([{'isError': 0,
  'message': ("_SingleProtocolFactory starting on './tmpkMiBIA.sock'",),
  'system': '-',
  'time': 1338949801.733531},
 {'isError': 0,
  'message': ('Starting factory <twisted.internet.test.reactormixins._SingleProtocolFactory instance at 0x329cf80>',),
  'system': '-',
  'time': 1338949801.733802},
 {'isError': 0,
  'message': ('Starting factory <twisted.internet.test.reactormixins._SingleProtocolFactory instance at 0x329c950>',),
  'system': '-',
  'time': 1338949801.734312},
 {'isError': 0,
  'message': ('Stopping factory <twisted.internet.test.reactormixins._SingleProtocolFactory instance at 0x329c950>',),
  'system': 'ConnectableProtocol,client',
  'time': 1338949801.737718},
 {'isError': 0,
  'message': ("(UNIX Port './tmpkMiBIA.sock' Closed)",),
  'system': 'twisted.internet.test.reactormixins._SingleProtocolFactory',
  'time': 1338949801.738284},
 {'isError': 0,
  'message': ('Stopping factory <twisted.internet.test.reactormixins._SingleProtocolFactory instance at 0x329cf80>',),
  'system': 'twisted.internet.test.reactormixins._SingleProtocolFactory',
  'time': 1338949801.738597},
 {'isError': 0,
  'message': ('Main loop terminated.',),
  'system': '-',
  'time': 1338949801.738852}])

twisted.internet.test.test_unix.UNIXTestsBuilder_EPollReactor.test_avoidLeakingFileDescriptors
===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/twisted-12.1.0-r1000/temp/tests-2.7/usr/lib64/python2.7/site-packages/twisted/internet/test/test_unix.py", line 484, in test_descriptorDeliveredBeforeBytes
    self.assertEqual([int, "j", "u", "n", "k"], client.events)
  File "/var/tmp/portage/dev-python/twisted-12.1.0-r1000/temp/tests-2.7/usr/lib64/python2.7/site-packages/twisted/trial/unittest.py", line 270, in assertEqual
    % (msg, pformat(first), pformat(second)))
twisted.trial.unittest.FailTest: not equal:
a = [<type 'int'>, 'j', 'u', 'n', 'k']
b = ['j', 'u', 'n', 'k']


twisted.internet.test.test_unix.UNIXTestsBuilder_EPollReactor.test_descriptorDeliveredBeforeBytes
twisted.internet.test.test_unix.UNIXTestsBuilder_Glib2Reactor.test_descriptorDeliveredBeforeBytes
twisted.internet.test.test_unix.UNIXTestsBuilder_Gtk2Reactor.test_descriptorDeliveredBeforeBytes
twisted.internet.test.test_unix.UNIXTestsBuilder_PollReactor.test_descriptorDeliveredBeforeBytes
twisted.internet.test.test_unix.UNIXTestsBuilder_SelectReactor.test_descriptorDeliveredBeforeBytes
===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/twisted-12.1.0-r1000/temp/tests-2.7/usr/lib64/python2.7/site-packages/twisted/internet/test/test_unix.py", line 454, in test_avoidLeakingFileDescriptors
    expectedEvent, pformat(events,)))
twisted.trial.unittest.FailTest: Expected event ({'protocolName': 'ConnectableProtocol', 'format': '%(protocolName)s (on %(hostAddress)r) does not provide IFileDescriptorReceiver; closing file descriptor received (from %(peerAddress)r).', 'hostAddress': UNIXAddress(None), 'peerAddress': UNIXAddress('./tmpWSZsjP.sock')}) not found in logged events ([{'isError': 0,
  'message': ("_SingleProtocolFactory starting on './tmpWSZsjP.sock'",),
  'system': '-',
  'time': 1338949801.933403},
 {'isError': 0,
  'message': ('Starting factory <twisted.internet.test.reactormixins._SingleProtocolFactory instance at 0x32a26c8>',),
  'system': '-',
  'time': 1338949801.93369},
 {'isError': 0,
  'message': ('Starting factory <twisted.internet.test.reactormixins._SingleProtocolFactory instance at 0x32a2638>',),
  'system': '-',
  'time': 1338949801.934268},
 {'isError': 0,
  'message': ('Stopping factory <twisted.internet.test.reactormixins._SingleProtocolFactory instance at 0x32a2638>',),
  'system': 'ConnectableProtocol,client',
  'time': 1338949801.937187},
 {'isError': 0,
  'message': ("(UNIX Port './tmpWSZsjP.sock' Closed)",),
  'system': 'twisted.internet.test.reactormixins._SingleProtocolFactory',
  'time': 1338949801.937846},
 {'isError': 0,
  'message': ('Stopping factory <twisted.internet.test.reactormixins._SingleProtocolFactory instance at 0x32a26c8>',),
  'system': 'twisted.internet.test.reactormixins._SingleProtocolFactory',
  'time': 1338949801.938201}])

twisted.internet.test.test_unix.UNIXTestsBuilder_Glib2Reactor.test_avoidLeakingFileDescriptors
===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/twisted-12.1.0-r1000/temp/tests-2.7/usr/lib64/python2.7/site-packages/twisted/internet/test/test_unix.py", line 454, in test_avoidLeakingFileDescriptors
    expectedEvent, pformat(events,)))
twisted.trial.unittest.FailTest: Expected event ({'protocolName': 'ConnectableProtocol', 'format': '%(protocolName)s (on %(hostAddress)r) does not provide IFileDescriptorReceiver; closing file descriptor received (from %(peerAddress)r).', 'hostAddress': UNIXAddress(None), 'peerAddress': UNIXAddress('./tmpqLUGRr.sock')}) not found in logged events ([{'isError': 0,
  'message': ("_SingleProtocolFactory starting on './tmpqLUGRr.sock'",),
  'system': '-',
  'time': 1338949802.15536},
 {'isError': 0,
  'message': ('Starting factory <twisted.internet.test.reactormixins._SingleProtocolFactory instance at 0x2e9f4d0>',),
  'system': '-',
  'time': 1338949802.155631},
 {'isError': 0,
  'message': ('Starting factory <twisted.internet.test.reactormixins._SingleProtocolFactory instance at 0x2e9f1b8>',),
  'system': '-',
  'time': 1338949802.156191},
 {'isError': 0,
  'message': ('Stopping factory <twisted.internet.test.reactormixins._SingleProtocolFactory instance at 0x2e9f1b8>',),
  'system': 'ConnectableProtocol,client',
  'time': 1338949802.159202},
 {'isError': 0,
  'message': ("(UNIX Port './tmpqLUGRr.sock' Closed)",),
  'system': 'twisted.internet.test.reactormixins._SingleProtocolFactory',
  'time': 1338949802.15987},
 {'isError': 0,
  'message': ('Stopping factory <twisted.internet.test.reactormixins._SingleProtocolFactory instance at 0x2e9f4d0>',),
  'system': 'twisted.internet.test.reactormixins._SingleProtocolFactory',
  'time': 1338949802.160242}])

twisted.internet.test.test_unix.UNIXTestsBuilder_Gtk2Reactor.test_avoidLeakingFileDescriptors
===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/twisted-12.1.0-r1000/temp/tests-2.7/usr/lib64/python2.7/site-packages/twisted/internet/test/test_unix.py", line 454, in test_avoidLeakingFileDescriptors
    expectedEvent, pformat(events,)))
twisted.trial.unittest.FailTest: Expected event ({'protocolName': 'ConnectableProtocol', 'format': '%(protocolName)s (on %(hostAddress)r) does not provide IFileDescriptorReceiver; closing file descriptor received (from %(peerAddress)r).', 'hostAddress': UNIXAddress(None), 'peerAddress': UNIXAddress('./tmp26DK6S.sock')}) not found in logged events ([{'isError': 0,
  'message': ("_SingleProtocolFactory starting on './tmp26DK6S.sock'",),
  'system': '-',
  'time': 1338949802.35783},
 {'isError': 0,
  'message': ('Starting factory <twisted.internet.test.reactormixins._SingleProtocolFactory instance at 0x32b2ea8>',),
  'system': '-',
  'time': 1338949802.358142},
 {'isError': 0,
  'message': ('Starting factory <twisted.internet.test.reactormixins._SingleProtocolFactory instance at 0x32b2f38>',),
  'system': '-',
  'time': 1338949802.358668},
 {'isError': 0,
  'message': ('Stopping factory <twisted.internet.test.reactormixins._SingleProtocolFactory instance at 0x32b2f38>',),
  'system': 'ConnectableProtocol,client',
  'time': 1338949802.361283},
 {'isError': 0,
  'message': ("(UNIX Port './tmp26DK6S.sock' Closed)",),
  'system': 'twisted.internet.test.reactormixins._SingleProtocolFactory',
  'time': 1338949802.361801},
 {'isError': 0,
  'message': ('Stopping factory <twisted.internet.test.reactormixins._SingleProtocolFactory instance at 0x32b2ea8>',),
  'system': 'twisted.internet.test.reactormixins._SingleProtocolFactory',
  'time': 1338949802.362142},
 {'isError': 0,
  'message': ('Main loop terminated.',),
  'system': '-',
  'time': 1338949802.362408}])

twisted.internet.test.test_unix.UNIXTestsBuilder_PollReactor.test_avoidLeakingFileDescriptors
===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/twisted-12.1.0-r1000/temp/tests-2.7/usr/lib64/python2.7/site-packages/twisted/internet/test/test_unix.py", line 454, in test_avoidLeakingFileDescriptors
    expectedEvent, pformat(events,)))
twisted.trial.unittest.FailTest: Expected event ({'protocolName': 'ConnectableProtocol', 'format': '%(protocolName)s (on %(hostAddress)r) does not provide IFileDescriptorReceiver; closing file descriptor received (from %(peerAddress)r).', 'hostAddress': UNIXAddress(None), 'peerAddress': UNIXAddress('./tmp1R9nZ9.sock')}) not found in logged events ([{'isError': 0,
  'message': ("_SingleProtocolFactory starting on './tmp1R9nZ9.sock'",),
  'system': '-',
  'time': 1338949802.527728},
 {'isError': 0,
  'message': ('Starting factory <twisted.internet.test.reactormixins._SingleProtocolFactory instance at 0x32b3290>',),
  'system': '-',
  'time': 1338949802.527998},
 {'isError': 0,
  'message': ('Starting factory <twisted.internet.test.reactormixins._SingleProtocolFactory instance at 0x32b67a0>',),
  'system': '-',
  'time': 1338949802.52849},
 {'isError': 0,
  'message': ('Stopping factory <twisted.internet.test.reactormixins._SingleProtocolFactory instance at 0x32b67a0>',),
  'system': 'ConnectableProtocol,client',
  'time': 1338949802.530924},
 {'isError': 0,
  'message': ("(UNIX Port './tmp1R9nZ9.sock' Closed)",),
  'system': 'twisted.internet.test.reactormixins._SingleProtocolFactory',
  'time': 1338949802.531486},
 {'isError': 0,
  'message': ('Stopping factory <twisted.internet.test.reactormixins._SingleProtocolFactory instance at 0x32b3290>',),
  'system': 'twisted.internet.test.reactormixins._SingleProtocolFactory',
  'time': 1338949802.53178},
 {'isError': 0,
  'message': ('Main loop terminated.',),
  'system': '-',
  'time': 1338949802.532066}])

twisted.internet.test.test_unix.UNIXTestsBuilder_SelectReactor.test_avoidLeakingFileDescriptors
===============================================================================
[ERROR]
Traceback (most recent call last):
Failure: exceptions.Exception: Received bytes ('junk') before descriptor.

twisted.internet.test.test_unix.UNIXTestsBuilder_EPollReactor.test_sendFileDescriptor
twisted.internet.test.test_unix.UNIXTestsBuilder_Glib2Reactor.test_sendFileDescriptor
twisted.internet.test.test_unix.UNIXTestsBuilder_Gtk2Reactor.test_sendFileDescriptor
twisted.internet.test.test_unix.UNIXTestsBuilder_PollReactor.test_sendFileDescriptor
twisted.internet.test.test_unix.UNIXTestsBuilder_SelectReactor.test_sendFileDescriptor
-------------------------------------------------------------------------------
Ran 126 tests in 1.252s

FAILED (skips=36, failures=10, errors=5, successes=75)
```

Attachments:

* [twisted.python.sendmsg_compiler_flags.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/a4e/a4ed49c7a5f7539759cba784e0102af8bc484a02/df1591982b74910dd5aa734a992e95efadbf762f.patch) (523 bytes) - added by Arfrever on 2012-06-10 19:20:37Z - Set compiler flags for twisted.python.sendmsg extension

<details><summary>Searchable metadata</summary>

```
trac-id__5701 5701
type__defect defect
reporter__Arfrever Arfrever
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__invalid invalid
component__core core
keywords__ 
time__1338949918000000 1338949918000000
changetime__1339356698000000 1339356698000000
version__None None
owner__ 
cc__Arfrever cc__marienz
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_1"></a>|@therve commented|
|-|-|

Can you describe your system? What's your compiler, kernel version, OS, etc. This is the list of systems that we support, where tests are passing: http://buildbot.twistedmatrix.com/boxes-supported

**Comment by twisted-trac** [comment]
|<img alt="Arfrever's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_2"></a>|Arfrever commented|
|-|-|

Gentoo GNU/Linux, amd64 architecture, Linux 3.0.29, GCC 4.6.3, glibc 2.15.
The same failures and errors occur with Python 2.6.8 (official release) and 2.7.3+ (snapshot of 2.7 branch from last week).

**Comment by twisted-trac** [comment]
|<img alt="marienz's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_3"></a>|marienz commented|
|-|-|

Arfrever: can you check the compiler commandline used to build sendmsg.o (or just attach a full build log)? I had the same thing happen myself on a gentoo ~amd64 system (sys-devel/gcc-4.6.3, dev-lang/python-2.7.3-r2), and the cause seems to be -fno-strict-aliasing being missing from the compiler flags. I can manually reproduce the problem by building sendmsg.so like this:

```
x86_64-pc-linux-gnu-gcc -pthread -ggdb -O2 -march=amdfam10 -pipe -fPIC -I/usr/include/python2.7 -c twisted/python/sendmsg.c -o sendmsg.o
x86_64-pc-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,--as-needed -ggdb -O2 -march=amdfam10 -pipe sendmsg.o -L/usr/lib64 -lpython2.7 -o twisted/python/sendmsg.so
```

(you'll have to adjust -march if you're not on an amd cpu), and running twisted.python.test.test_sendmsg.SendmsgTestCase.test_sendSubProcessFD will fail (I am fairly certain all those other test failures have the same root cause). Adding -fno-strict-aliasing to the compiler commandline fixes it. The problem also does not show up if I just run "setup.py build_ext -fi": it probably needs at least -O2 or so to materialize.

I believe this is a bug in gentoo's python's distutils, as it misses -fno-strict-aliasing when compiling a dummy extension using a trivial setup.py. Please close this bug report as invalid if the test failures go away when -fno-strict-aliasing is forced into your compiler flags.

**Comment by twisted-trac** [comment]
|<img alt="Arfrever's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_4"></a>|Arfrever commented|
|-|-|

twisted.python.sendmsg_compiler_flags.patch adds -fno-strict-aliasing flag for twisted.python.sendmsg extension.

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_5"></a>|@therve set status to `closed`|
|-|-|

I guess your patch confirms what marienz found out, that the problem is a bug in Gentoo. We won't apply this patch to Twisted, and I'm considering this bug invalid. Thanks.
