### ISSUE TITLE
twisted.test.test_strcred.TestSSHChecker.test_isChecker() fails with Twisted Conch not available

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#5703]
|<img alt="Arfrever's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| Arfrever reported|
|-|-|
|Trac ID|trac#5703|
|Type|defect|
|Created|2012-06-06 02:48:41Z|

twisted.test.test_strcred.TestSSHChecker.test_isChecker() has been introduced in Twisted 12.1.0 and fails.

```
twisted.test.test_strcred
  TestAnonymousChecker
    testAnonymousAccessSucceeds ...                                        [OK]
    test_isChecker ...                                                     [OK]
  TestCheckerOptions
    test_createsDictionary ...                                             [OK]
    test_createsList ...                                                   [OK]
    test_credInterfacesProvidesLists ...                                   [OK]
    test_displaysHelpCorrectly ...                                         [OK]
    test_displaysListCorrectly ...                                         [OK]
    test_invalidAuthError ...                                              [OK]
    test_listDoesNotDisplayDuplicates ...                                  [OK]
    test_unexpectedException ...                                           [OK]
  TestFileDBChecker
    test_failsWithEmptyFilename ...                                        [OK]
    test_fileCheckerFailsPassword ...                                      [OK]
    test_fileCheckerFailsUsername ...                                      [OK]
    test_fileCheckerSucceeds ...                                           [OK]
    test_isChecker ...                                                     [OK]
    test_warnWithBadFilename ...                                           [OK]
  TestLimitingInterfaces
    test_canAddSupportedChecker ...                                        [OK]
    test_failOnAddingUnsupportedChecker ...                                [OK]
    test_helpAuthLimitsOutput ...                                          [OK]
    test_helpAuthTypeLimitsOutput ...                                      [OK]
    test_supportsAllInterfaces ...                                         [OK]
    test_supportsCheckerFactory ...                                        [OK]
    test_supportsInterface ...                                             [OK]
    test_unsupportedInterfaceError ...                                     [OK]
  TestMemoryChecker
    test_badFormatArgString ...                                            [OK]
    test_isChecker ...                                                     [OK]
    test_memoryCheckerFailsPassword ...                                    [OK]
    test_memoryCheckerFailsUsername ...                                    [OK]
    test_memoryCheckerSucceeds ...                                         [OK]
  TestPublicAPI
    test_emptyDescription ...                                              [OK]
    test_invalidAuthType ...                                               [OK]
  TestSSHChecker
    test_isChecker ...                                                  [ERROR]
  TestStrcredFunctions
    test_findCheckerFactories ...                                          [OK]
    test_findCheckerFactory ...                                            [OK]
  TestUnixChecker
    test_isChecker ...                                                     [OK]
    test_unixCheckerFailsPassword ...                                      [OK]
    test_unixCheckerFailsUsername ...                                      [OK]
    test_unixCheckerSucceeds ...                                           [OK]

===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/twisted-12.1.0-r1000/temp/tests-2.7/usr/lib64/python2.7/site-packages/twisted/test/test_strcred.py", line 361, in test_isChecker
    sshChecker = strcred.makeChecker('sshkey')
  File "/var/tmp/portage/dev-python/twisted-12.1.0-r1000/temp/tests-2.7/usr/lib64/python2.7/site-packages/twisted/cred/strcred.py", line 127, in makeChecker
    return findCheckerFactory(authType).generateChecker(argstring)
  File "/var/tmp/portage/dev-python/twisted-12.1.0-r1000/temp/tests-2.7/usr/lib64/python2.7/site-packages/twisted/cred/strcred.py", line 112, in findCheckerFactory
    raise InvalidAuthType(authType)
twisted.cred.strcred.InvalidAuthType: sshkey

twisted.test.test_strcred.TestSSHChecker.test_isChecker
-------------------------------------------------------------------------------
Ran 38 tests in 0.412s

FAILED (errors=1, successes=37)
```

Attachments:

* [twisted-12.1.0-remove-tests-conch-dependency.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/542/5420dcab71e0fb6328f565ce359ed1e0e601d64b/6d52328b7a84980ce3826431be6c3f68dc995b96.patch) (459 bytes) - added by marienz on 2012-06-10 10:17:55Z - skip a test if conch is not available

<details><summary>Searchable metadata</summary>

```
trac-id__5703 5703
type__defect defect
reporter__Arfrever Arfrever
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__ 
time__1338950921000000 1338950921000000
changetime__1384261162000000 1384261162000000
version__None None
owner__ 
cc__Arfrever cc__marienz cc__hynek
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_1"></a>|@therve commented|
|-|-|

I think one issue here is that we ship cred_sshkeys with core, whereas it looks like it should be in conch. Can you paste the output of `from twisted.conch.checkers import SSHPublicKeyDatabase`? Thanks.

**Comment by twisted-trac** [comment]
|<img alt="Arfrever's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_2"></a>|Arfrever commented|
|-|-|

Gentoo GNU/Linux, amd64 architecture, Linux 3.0.29, GCC 4.6.3, glibc 2.15.
The same error occurs with Python 2.6.8 (official release) and 2.7.3+ (snapshot of 2.7 branch from last week).

```
$ python2.7
Python 2.7.3+ (2.7:50d6592791bd+, Jun  3 2012, 03:23:33) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from twisted.conch.checkers import SSHPublicKeyDatabase
>>>
```

**Comment by twisted-trac** [comment]
|<img alt="marienz's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_3"></a>|marienz commented|
|-|-|

I believe comment [#11338](https://github.com/twisted/twisted/issues/11338) is correct. I ran into the same problem and applied the attached patch to fix it (although perhaps the test should just move into conch instead?).

If you look closely at comment #0 you'll see the failing run is via Gentoo's portage package manager, which runs the tests against an install of just Twisted core into a temporary directory. Conch is not available there. Comment #2 only shows that conch is available on the system itself, but that's not what the tests run against.

**Comment by twisted-trac** [comment]
|[<img alt="hynek's avatar" src="https://avatars.githubusercontent.com/u/41240?s=50" width="50" height="50">](https://github.com/hynek)<a name="note_5"></a>|@hynek commented|
|-|-|

I stumbled over this problem too because I was running trial before with missing dependencies (pyasn1) which gave me a conch-less `dropin.cache`. Thus, after installing all the necessary dependencies this test started to fail although conch tests passed. All imports worked but the conch **plugin** was missing in my now-stale cache.

Deleting the cache made the tests pass again – maybe that’s Arfrever’s problem too?

We’d need more information how exactly this test run came to be – I don’t see any indication why conch should be missing since the core-only paths start with “TwistedCore-” so I’m positive this is a complete twisted distribution.

**Comment by twisted-trac** [comment]
|<img alt="Arfrever's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_6"></a>|Arfrever commented|
|-|-|

I agree with comment #3. Twisted-Conch was not available in test directory.
