### ISSUE TITLE
test_http fails with randomized hashes

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#5757]
|[<img alt="pitrou's avatar" src="https://avatars.githubusercontent.com/u/1721820?s=50" width="50" height="50">](https://github.com/pitrou)| @pitrou reported|
|-|-|
|Trac ID|trac#5757|
|Type|defect|
|Created|2012-07-09 18:41:26Z|

A couple of tests in twisted.web.test.test_http fail with ``python -R``:

```
[FAIL]
Traceback (most recent call last):
  File "/home/antoine/twisted/twisted/web/test/test_http.py", line 1591, in test_HTTP10
    "HTTP/1.0 200 OK\r\n"
  File "/home/antoine/twisted/twisted/trial/unittest.py", line 270, in assertEqual
    % (msg, pformat(first), pformat(second)))
twisted.trial.unittest.FailTest: not equal:
a = "HTTP/1.0 200 OK\r\nContent-Length: 13\r\nCommand: GET\r\nRequest: /\r\nVersion: HTTP/1.0\r\n\r\n'''\n3\nabc'''\n"
b = "HTTP/1.0 200 OK\r\nCommand: GET\r\nContent-Length: 13\r\nVersion: HTTP/1.0\r\nRequest: /\r\n\r\n'''\n3\nabc'''\n"


twisted.web.test.test_http.Expect100ContinueServerTests.test_HTTP10
===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/home/antoine/twisted/twisted/web/test/test_http.py", line 1622, in test_expect100ContinueHeader
    "HTTP/1.1 100 Continue\r\n\r\n"
  File "/home/antoine/twisted/twisted/trial/unittest.py", line 270, in assertEqual
    % (msg, pformat(first), pformat(second)))
twisted.trial.unittest.FailTest: not equal:
a = "HTTP/1.1 100 Continue\r\n\r\nHTTP/1.1 200 OK\r\nContent-Length: 13\r\nCommand: GET\r\nRequest: /\r\nVersion: HTTP/1.1\r\n\r\n'''\n3\nabc'''\n"
b = "HTTP/1.1 100 Continue\r\n\r\nHTTP/1.1 200 OK\r\nCommand: GET\r\nContent-Length: 13\r\nVersion: HTTP/1.1\r\nRequest: /\r\n\r\n'''\n3\nabc'''\n"


twisted.web.test.test_http.Expect100ContinueServerTests.test_expect100ContinueHeader
===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/home/antoine/twisted/twisted/web/test/test_http.py", line 1651, in test_expect100ContinueWithPipelining
    "HTTP/1.1 100 Continue\r\n\r\n"
  File "/home/antoine/twisted/twisted/trial/unittest.py", line 270, in assertEqual
    % (msg, pformat(first), pformat(second)))
twisted.trial.unittest.FailTest: not equal:
a = "HTTP/1.1 100 Continue\r\n\r\nHTTP/1.1 200 OK\r\nContent-Length: 13\r\nCommand: GET\r\nRequest: /\r\nVersion: HTTP/1.1\r\n\r\n'''\n3\nabc'''\nHTTP/1.1 200 OK\r\nContent-Length: 14\r\nCommand: POST\r\nRequest: /foo\r\nVersion: HTTP/1.1\r\n\r\n'''\n4\ndefg'''\n"
b = "HTTP/1.1 100 Continue\r\n\r\nHTTP/1.1 200 OK\r\nCommand: GET\r\nContent-Length: 13\r\nVersion: HTTP/1.1\r\nRequest: /\r\n\r\n'''\n3\nabc'''\nHTTP/1.1 200 OK\r\nCommand: POST\r\nContent-Length: 14\r\nVersion: HTTP/1.1\r\nRequest: /foo\r\n\r\n'''\n4\ndefg'''\n"


twisted.web.test.test_http.Expect100ContinueServerTests.test_expect100ContinueWithPipelining
```

<details><summary>Searchable metadata</summary>

```
trac-id__5757 5757
type__defect defect
reporter__antoine antoine
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__duplicate duplicate
component__web web
keywords__ 
time__1341859286000000 1341859286000000
changetime__1352277811000000 1352277811000000
version__None None
owner__ 
cc__jknight
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="meissenPlate's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_2"></a>|meissenPlate set status to `closed`|
|-|-|

This seems to be a duplicate of [#6113](https://github.com/twisted/twisted/issues/6113) which was fixed by changeset 36206 ([http://twistedmatrix.com/trac/changeset/36206]) and is now closed.

I can confirm that "python -R bin/trial twisted/web/test/test_http" now has all tests passing on a fresh copy of trunk.

I hope I'm doing this right. I'm gonna select "resolve as duplicate". If I messed it all up I'm sorry!

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_3"></a>|@glyph commented|
|-|-|

You did it just right. Thanks for taking the time to find a duplicate and close it!
