### ISSUE TITLE
test_xml flaky with randomized hashes

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#5758]
|[<img alt="pitrou's avatar" src="https://avatars.githubusercontent.com/u/1721820?s=50" width="50" height="50">](https://github.com/pitrou)| @pitrou reported|
|-|-|
|Trac ID|trac#5758|
|Type|defect|
|Created|2012-07-09 18:43:12Z|

A test in twisted.web.test.test_xml fails sporadically with `python -R`:

```
[FAIL]
Traceback (most recent call last):
  File "/home/antoine/twisted/twisted/web/test/test_xml.py", line 816, in test_brokenAttributeName
    self.checkParsed(input, expected)
  File "/home/antoine/twisted/twisted/web/test/test_xml.py", line 805, in checkParsed
    self.assertEqual(output.documentElement.toxml(), expected)
  File "/home/antoine/twisted/twisted/trial/unittest.py", line 270, in assertEqual
    % (msg, pformat(first), pformat(second)))
twisted.trial.unittest.FailTest: not equal:
a = '<body><h1><div al="True" ign="center">Foo</div></h1></body>'
b = '<body><h1><div ign="center" al="True">Foo</div></h1></body>'
```

<details><summary>Searchable metadata</summary>

```
trac-id__5758 5758
type__defect defect
reporter__antoine antoine
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__web web
keywords__ 
time__1341859392000000 1341859392000000
changetime__1341859392000000 1341859392000000
version__None None
owner__ 
cc__jknight
```
</details>

**Comment by glyph** [comment]
See the close explanation on #5760
