### ISSUE TITLE
test_template flaky with randomized hashes

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#5759]
|[<img alt="pitrou's avatar" src="https://avatars.githubusercontent.com/u/1721820?s=50" width="50" height="50">](https://github.com/pitrou)| @pitrou reported|
|-|-|
|Trac ID|trac#5759|
|Type|defect|
|Created|2012-07-09 18:44:26Z|

twisted.web.test.text_template fails sporadically with `python -R`:

```
[ERROR]
Traceback (most recent call last):
  File "/home/antoine/twisted/twisted/web/test/_util.py", line 42, in <lambda>
    d.addCallback(lambda s: self.assertEqual(s, target))
  File "/home/antoine/twisted/twisted/trial/unittest.py", line 270, in assertEqual
    % (msg, pformat(first), pformat(second)))
twisted.trial.unittest.FailTest: not equal:
a = '<hello:world xmlns:hello="http://made-up.example.com/ns/not-real" hello:sample="testing">This is a made-up tag.</hello:world>'
b = '<hello:world hello:sample="testing" xmlns:hello="http://made-up.example.com/ns/not-real">This is a made-up tag.</hello:world>'

twisted.web.test.test_template.FlattenIntegrationTests.test_lenientPrefixBehavior
```

<details><summary>Searchable metadata</summary>

```
trac-id__5759 5759
type__defect defect
reporter__antoine antoine
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__web web
keywords__ 
time__1341859466000000 1341859466000000
changetime__1341859467000000 1341859467000000
version__None None
owner__ 
cc__jknight
```
</details>

**Comment by glyph** [comment]
See the close explanation on #5760
