### ISSUE TITLE
test_webclient flaky with randomized hashes

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#5760]
|[<img alt="pitrou's avatar" src="https://avatars.githubusercontent.com/u/1721820?s=50" width="50" height="50">](https://github.com/pitrou)| @pitrou reported|
|-|-|
|Trac ID|trac#5760|
|Type|defect|
|Created|2012-07-09 18:46:17Z|

twisted.web.test.test_webclient fails sporadically with `python -R`:

```
[FAIL]
Traceback (most recent call last):
  File "/home/antoine/twisted/twisted/web/test/test_webclient.py", line 2585, in test_existingHeaders
    ('Accept-Encoding', ['fizz', 'decoder1,decoder2'])])
  File "/home/antoine/twisted/twisted/trial/unittest.py", line 270, in assertEqual
    % (msg, pformat(first), pformat(second)))
twisted.trial.unittest.FailTest: not equal:
a = [('Host', ['example.com']),
 ('Accept-Encoding', ['fizz', 'decoder1,decoder2']),
 ('Foo', ['bar'])]
b = [('Host', ['example.com']),
 ('Foo', ['bar']),
 ('Accept-Encoding', ['fizz', 'decoder1,decoder2'])]


twisted.web.test.test_webclient.ContentDecoderAgentTests.test_existingHeaders
===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/home/antoine/twisted/twisted/trial/unittest.py", line 270, in assertEqual
    % (msg, pformat(first), pformat(second)))
twisted.trial.unittest.FailTest: not equal:
a = "'baz=quux; foo=bar'"
b = "'foo=bar; baz=quux'"


twisted.web.test.test_webclient.CookieTestCase.testRawSomeCookies
===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/home/antoine/twisted/twisted/web/test/test_webclient.py", line 286, in test_earlyHeaders
    "GET /bar HTTP/1.0\r\n"
  File "/home/antoine/twisted/twisted/trial/unittest.py", line 270, in assertEqual
    % (msg, pformat(first), pformat(second)))
twisted.trial.unittest.FailTest: not equal:
a = 'GET /bar HTTP/1.0\r\nHost: example.net\r\nUser-Agent: foobar\r\nContent-Length: 9\r\nconnection: close\r\nUseful: value\r\nCookie: blah blah; baz=quux\r\n\r\nsome data'
b = 'GET /bar HTTP/1.0\r\nHost: example.net\r\nUser-Agent: foobar\r\nContent-Length: 9\r\nUseful: value\r\nconnection: close\r\nCookie: blah blah; baz=quux\r\n\r\nsome data'
```

<details><summary>Searchable metadata</summary>

```
trac-id__5760 5760
type__defect defect
reporter__antoine antoine
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__web web
keywords__ 
time__1341859577000000 1341859577000000
changetime__1341859578000000 1341859578000000
version__None None
owner__ 
cc__jknight
```
</details>

**Comment by glyph** [comment]
It's been 10 years and [hashes are deterministic now](https://softwaremaniacs.org/blog/2020/02/05/dicts-ordered/en/) on all the versions of Python we support, so I think this has gone fully stale.  Please reopen if I am incorrect about that.
