### ISSUE TITLE
test_gidFromGroupnameString: fails with large gid

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#5778]
|<img alt="j2a's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| j2a reported|
|-|-|
|Trac ID|trac#5778|
|Type|defect|
|Created|2012-07-14 17:57:25Z|

```
Traceback (most recent call last):
  File "/Users/yyurevich/twisted-meetup/Sprint/Twisted/twisted/python/test/test_util.py", line 115, in test_gidFromGroupnameString
    grent = grp.getgrgid(os.getgid())
exceptions.KeyError: 'getgrgid(): gid not found: 1117076509'

twisted.python.test.test_util.UtilTestCase.test_gidFromGroupnameString
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/Users/yyurevich/twisted-meetup/Sprint/Twisted/twisted/test/test_twistd.py", line 562, in test_applicationStartsWithConfiguredNameIDs
    patchUserDatabase(self.patch, user, uid, group, gid)
  File "/Users/yyurevich/twisted-meetup/Sprint/Twisted/twisted/test/test_twistd.py", line 106, in patchUserDatabase
    grent = grp.getgrgid(os.getgid())
exceptions.KeyError: 'getgrgid(): gid not found: 1117076509'

twisted.test.test_twistd.ApplicationRunnerTest.test_applicationStartsWithConfiguredNameIDs
-------------------------------------------------------------------------------
```

Actual group id is 10-digit:
```
>>> import os
>>> os.getgid()
1117076509
```

<details><summary>Searchable metadata</summary>

```
trac-id__5778 5778
type__defect defect
reporter__j2a j2a
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__ 
time__1342288645000000 1342288645000000
changetime__1342290186000000 1342290186000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|<img alt="j2a's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_1"></a>|j2a commented|
|-|-|

Tests running on Mac computer being in the ActiveDirectory domain, but does't have connection to it at that particular moment. Actual code failing is:

```
>>> import os, grp
>>> os.getgid()
1117076509
>>> grp.getgrgid(os.getgid())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'getgrgid(): gid not found: 1117076509'
```
