### ISSUE TITLE
test_old_publickey_getPrivateKey failing with Python -3 flag

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#5804]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)| @thijstriemstra reported|
|-|-|
|Trac ID|trac#5804|
|Type|defect|
|Created|2012-07-25 11:06:13Z|

As seen on the [py3k-warnings buildslave](http://buildbot.twistedmatrix.com/builders/python-3k-warnings/builds/132):

```
[FAIL]
Traceback (most recent call last):
  File "/var/lib/buildbot/buildarea/python-3k-warnings/Twisted/twisted/conch/test/test_userauth.py", line 846, in test_old_publickey_getPrivateKey
    oldAuth.signData, None, 'data')
  File "/var/lib/buildbot/buildarea/python-3k-warnings/Twisted/twisted/trial/unittest.py", line 457, in failUnlessWarns
    self.fail("Can't handle different warnings")
twisted.trial.unittest.FailTest: Can't handle different warnings

twisted.conch.test.test_userauth.SSHUserAuthClientTestCase.test_old_publickey_getPrivateKey
-------------------------------------------------------------------------------
```

produced with `python2.7 -3 ./bin/trial --reporter=bwverbose --unclean-warnings twisted`

<details><summary>Searchable metadata</summary>

```
trac-id__5804 5804
type__defect defect
reporter__thijs thijs
priority__low low
milestone__Python_3_x Python-3.x
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__conch conch
keywords__ 
time__1343214373000000 1343214373000000
changetime__1470303835537347 1470303835537347
version__None None
owner__ 
cc__thijs cc__z3p
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_2"></a>|@thijstriemstra commented|
|-|-|

Looks like it's testing deprecated functionality in `SSHUserAuthClient.getPublicKey()` (since 9.0) so getting rid of this code instead of fixing the test seems more appropriate to me.

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_3"></a>|@rodrigc set status to `closed`|
|-|-|

test_old_publickey_getPrivateKey was removed in https://github.com/twisted/twisted/commit/9570a8f4a8141592910e395d8a3b32bfd8ad463e
