### ISSUE TITLE
When inlineCallbacks is used at multiple stacks levels, tracebacks don't show these levels.

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#5854]
|<img alt="talljosh's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| talljosh reported|
|-|-|
|Trac ID|trac#5854|
|Type|enhancement|
|Created|2012-08-10 06:49:31Z|
|Branch|https://github.com/twisted/twisted/tree/inlinecallacks-traceback-info-5854-2|

Potentially similar tickets: [#3622](https://github.com/twisted/twisted/issues/3622), [#5178](https://github.com/twisted/twisted/issues/5178)

Simple example code that creates a call stack using inlineCallbacks and causes an error at the bottom level:

```
# This example creates a call stack that uses inlineCallbacks and causes an error at the bottom level.

from twisted.internet import defer, reactor

@defer.inlineCallbacks
def a():
    yield 1/0

@defer.inlineCallbacks
def b():
    yield a()

@defer.inlineCallbacks
def c():
    yield b()

def main():
    d = c()
    @d.addErrback
    def caught(x):
        x.printTraceback()
        reactor.stop()

if __name__ == '__main__':
    reactor.callWhenRunning(main)
    reactor.run()
```

The resulting traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Twisted-11.0.0-py2.7-linux-i686.egg/twisted/internet/defer.py", line 1141, in unwindGenerator
    return _inlineCallbacks(None, f(*args, **kwargs), Deferred())
  File "/usr/local/lib/python2.7/dist-packages/Twisted-11.0.0-py2.7-linux-i686.egg/twisted/internet/defer.py", line 1020, in _inlineCallbacks
    result = g.send(result)
  File "simpletwistedtest.py", line 9, in b
    yield a()
  File "/usr/local/lib/python2.7/dist-packages/Twisted-11.0.0-py2.7-linux-i686.egg/twisted/internet/defer.py", line 1141, in unwindGenerator
    return _inlineCallbacks(None, f(*args, **kwargs), Deferred())
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/Twisted-11.0.0-py2.7-linux-i686.egg/twisted/internet/defer.py", line 1020, in _inlineCallbacks
    result = g.send(result)
  File "simpletwistedtest.py", line 5, in a
    yield 1/0
exceptions.ZeroDivisionError: integer division or modulo by zero
```

I've created a patch that inserts frames into the failure object to given something more useful:
```
Traceback (most recent call last):
  File "twistedtest.py", line 171, in unwindGenerator
    return _inlineCallbacks(None, f(*args, **kwargs), defer.Deferred())
  File "twistedtest.py", line 27, in _inlineCallbacks
    result = g.send(result)
  File "twistedtest.py", line 183, in b
    yield a()
  File "twistedtest.py", line 171, in unwindGenerator
    return _inlineCallbacks(None, f(*args, **kwargs), defer.Deferred())
--- <exception caught here> ---
  File "twistedtest.py", line 187, in c
    yield b()
  File "twistedtest.py", line 183, in b
    yield a()
  File "twistedtest.py", line 27, in _inlineCallbacks
    result = g.send(result)
  File "twistedtest.py", line 179, in a
    yield 1/0
exceptions.ZeroDivisionError: integer division or modulo by zero
```

I intend to submit the patch as soon as I've got some good tests for the code.

Attachments:

* [inlineCallbacks-extra-traceback-info.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/034/034695bdec797bfd7634c487374b598a67c47a5c/d533a89ce6758e5bb78319cd071909fdf7f376a4.patch) (1516 bytes) - added by talljosh on 2012-08-10 07:03:01Z - Patch to add extra frame information to a failure when it's inlineCallbacks passes it to its caller.
* [inlineCallbacks-extra-traceback-info.2.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/034/034695bdec797bfd7634c487374b598a67c47a5c/2f37b15e10d31a270cd1c1f41ba39641d628db1c.patch) (3509 bytes) - added by talljosh on 2012-08-10 07:30:42Z - Updated patch that includes a test.
* [inlinecallbacks-traceback-info-response-to-comments.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/034/034695bdec797bfd7634c487374b598a67c47a5c/677fdeb62813e4331837b0788a63977ccfb074be.patch) (2349 bytes) - added by talljosh on 2013-03-18 06:05:08Z - Patch against inlinecallacks-traceback-info-5854 branch in response to comments
* [inlinecallbacks-traceback-info-response-to-comments.2.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/034/034695bdec797bfd7634c487374b598a67c47a5c/719843587347f01e245f012e2a5fce843fc12bb6.patch) (5270 bytes) - added by talljosh on 2013-03-20 04:15:55Z - Patch against /branches/inlinecallacks-traceback-info-5854-2 which refactors common code into a separate function in response to review by therve.
* [inlinecallbacks-traceback-info-response-to-comments.3.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/034/034695bdec797bfd7634c487374b598a67c47a5c/f669971015d023809f074d88403f32dc77f8a1d2.patch) (7934 bytes) - added by talljosh on 2013-03-20 07:04:36Z - Added more tests in response to latest review.

<details><summary>Searchable metadata</summary>

```
trac-id__5854 5854
type__enhancement enhancement
reporter__talljosh talljosh
priority__normal normal
milestone__ 
branch__branches_inlinecallacks_traceback_info_5854_2 branches/inlinecallacks-traceback-info-5854-2
branch_author__talljosh__exarkun talljosh, exarkun
status__new new
resolution__None None
component__core core
keywords__ 
time__1344581371000000 1344581371000000
changetime__1363836809000000 1363836809000000
version__None None
owner__talljosh talljosh

```
</details>

**Comment by twisted-trac** [comment]
|<img alt="talljosh's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|talljosh set owner to talljosh<br>talljosh set status to `assigned`|
|-|-|

**Comment by twisted-trac** [comment]
|<img alt="talljosh's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_2"></a>|talljosh removed owner<br>talljosh set status to `new`|
|-|-|

Be nice to me, this is my first contribution to Twisted.

**Comment by twisted-trac** [comment]
|<img alt="talljosh's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|talljosh set owner to @jerub|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="jerub's avatar" src="https://avatars.githubusercontent.com/u/315461?s=50" width="50" height="50">](https://github.com/jerub)<a name="note_4"></a>|@jerub commented|
|-|-|

(In [36211]) Branching to 'inlinecallacks-traceback-info-5854'

**Comment by twisted-trac** [comment]
|[<img alt="jerub's avatar" src="https://avatars.githubusercontent.com/u/315461?s=50" width="50" height="50">](https://github.com/jerub)<a name="note_5"></a>|@jerub commented|
|-|-|

Patch applied in r36212.

**Comment by twisted-trac** [comment]
|[<img alt="jerub's avatar" src="https://avatars.githubusercontent.com/u/315461?s=50" width="50" height="50">](https://github.com/jerub)<a name="note_6"></a>|@jerub commented|
|-|-|

(In [36213]) Add topfile explaining that nested inlineCallbacks tracebacks will now show more levels of stackframe.

Refs [#5854](https://github.com/twisted/twisted/issues/5854)

**Comment by twisted-trac** [comment]
|[<img alt="jerub's avatar" src="https://avatars.githubusercontent.com/u/315461?s=50" width="50" height="50">](https://github.com/jerub)<a name="note_7"></a>|@jerub set owner to talljosh|
|-|-|

Thanks for the patch, I've applied it to a branch and run the tests.

As you're adding a layer to the stackframe, and capturing locals and globals, it would be good if you respected the attribute of the failure object 'twisted.python.failure.Failure.captureVars'. See http://twistedmatrix.com/trac/browser/branches/inlinecallacks-traceback-info-5854/twisted/python/failure.py#L289

'r' is a bad parameter name, it's a contraction of 'result', but in this case we have a Failure object. Rename it to 'f' or something more descriptive.

I find it to be a noxious code smell that in twisted.python.failure the same 20 line section is repeated almost verbatim twice, and then that's been copied here. I deem that outside the scope of this patch due to the complexity of f.f_lineno / tb.tb_lineno and the method of iteration through the linked list.

Please either provide a new patch against trunk, or a patch against the /svn/Twisted/branches/inlinecallacks-traceback-info-5854.

**Comment by twisted-trac** [comment]
|<img alt="talljosh's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_8"></a>|talljosh set owner to @jerub|
|-|-|

I've attached a patch that should see to the issues you highlighted.

**Comment by twisted-trac** [comment]
|[<img alt="jerub's avatar" src="https://avatars.githubusercontent.com/u/315461?s=50" width="50" height="50">](https://github.com/jerub)<a name="note_9"></a>|@jerub commented|
|-|-|

(In [37574]) Apply inlinecallbacks-traceback-info-response-to-comments.patch by talljosh

Refs [#5854](https://github.com/twisted/twisted/issues/5854)

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_10"></a>|@exarkun commented|
|-|-|

(In [37575]) Branching to 'inlinecallacks-traceback-info-5854-2'

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_11"></a>|@therve commented|
|-|-|

I understand the problem, and it's really unfortunate, but the proposed fix is fairly insane. We want to reduce the default complexity, not increase it. _Maybe_ it's OK to do that if defer debugging is set?

**Comment by twisted-trac** [comment]
|<img alt="talljosh's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_12"></a>|talljosh commented|
|-|-|

Replying to [therve](#note_11):
> I understand the problem, and it's really unfortunate, but the proposed fix is fairly insane. We want to reduce the default complexity, not increase it. _Maybe_ it's OK to do that if defer debugging is set?

In this case, what do you find to be insane?

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_13"></a>|@therve commented|
|-|-|

Copying locals, globals, and inserting frames are bad things to do. It probably performs terribly, too. If you noticed, the code copied from Failure has been hidden by a self.debug flag because of a performance issue (see [#5011](https://github.com/twisted/twisted/issues/5011) and r31727).

**Comment by twisted-trac** [comment]
|<img alt="talljosh's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_14"></a>|talljosh commented|
|-|-|

After jerub's review, the proposed fix uses the same logic as Failure to determine whether to capture locals and globals - it respects the failure's captureVars attribute.

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_15"></a>|@therve set owner to talljosh|
|-|-|

OK, fair enough. Comments:
 * The test doesn't exercise the captureVars path. We need at least one more test I think.

 * Instead of copying the code from Failure, it should be refactored so that we can call a method of Failure or a function which does the same thing.

Thanks!

**Comment by twisted-trac** [comment]
|<img alt="talljosh's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_16"></a>|talljosh set owner to @therve|
|-|-|

The patch I've just uploaded refactors the code in Failure into a separate utility function used by Failure (twice) and the new code in defer.py. The captureVars path is covered by existing failure tests.

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_17"></a>|@therve set owner to talljosh|
|-|-|

So, the captureVars in failure.py is covered by tests, but it's still missing one test for the captureVars flag being passed in inlineCallbacks itself. Otherwise it looks good I think.

**Comment by twisted-trac** [comment]
|<img alt="talljosh's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_18"></a>|talljosh set owner to @therve|
|-|-|

The latest patch adds tests to check that the deferred debug flag is respected.

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_19"></a>|@therve set owner to talljosh|
|-|-|

Arg. I was about to merge this, and noticed that the new tests fail on Python3. Do you think you can have a look? It seems related to Failure behavior there, where we don't copy frames/traceback as we should.

I'm not sure it's actually doable here, maybe we should just skip the tests.

**Comment by twisted-trac** [comment]
|<img alt="talljosh's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_20"></a>|talljosh commented|
|-|-|

I might have a chance to look at this on the weekend, but probably not before.
