### ISSUE TITLE
Deprecate inet_pton, inet_ntop, and adict in twisted.python.compat

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#5895]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)| @itamarst reported|
|-|-|
|Trac ID|trac#5895|
|Type|task|
|Created|2012-08-21 12:33:38Z|
|Branch|https://github.com/twisted/twisted/tree/inet-compat-5895|

`inet_pton`, `inet_ntop`, and `adict` in `twisted.python.compat` are no longer necessary (2.6 has good implementations of first two, third is just junk). They should be deprecated.

Attachments:

* [ticket5895.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/e11/e11c55b96799681950331ead7c44fffb32924937/7fb9438ac989b0de75c673d86b33bb7e5494d17e.patch) (10273 bytes) - added by mateusbraga on 2013-04-15 03:28:14Z - Patch to solve this ticket.
* [ticket5895_2.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/e11/e11c55b96799681950331ead7c44fffb32924937/0879f155e93c8db0c646483192fb34cf234a210d.patch) (10754 bytes) - added by mateusbraga on 2013-04-16 01:45:03Z - twisted/topfiles/5895.removal added to the patch
* [ticket5895_3.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/e11/e11c55b96799681950331ead7c44fffb32924937/a074ea9a45f638a0d27bb974a5de6e177d1a0ce7.patch) (10907 bytes) - added by mateusbraga on 2013-04-27 04:23:27Z - Included some of thijs suggestions
* [ticket5895_4.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/e11/e11c55b96799681950331ead7c44fffb32924937/999353bd494e876d5ff27cd544b105fdc9f32545.patch) (11665 bytes) - added by mateusbraga on 2013-04-28 00:06:55Z - Included thijs suggestions
* [ticket5895_5.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/e11/e11c55b96799681950331ead7c44fffb32924937/2d4a162589bf5c2b29cd49e6217a087c550c2944.patch) (506 bytes) - added by mateusbraga on 2013-05-16 01:46:25Z - Patch to pass test

<details><summary>Searchable metadata</summary>

```
trac-id__5895 5895
type__task task
reporter__itamar itamar
priority__normal normal
milestone__De_Python_2ify De-Python-2ify
branch__branches_inet_compat_5895 branches/inet-compat-5895
branch_author__mateusbraga mateusbraga
status__new new
resolution__None None
component__core core
keywords__ 
time__1345552418000000 1345552418000000
changetime__1595670454676254 1595670454676254
version__None None
owner__ 
cc__thijs
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)<a name="note_1"></a>|@itamarst commented|
|-|-|

See `twisted/python/reflect.py` and `twisted/test/test_reflect.py` for an example of deprecation and testing of deprecation.

**Comment by twisted-trac** [comment]
|<img alt="mateusbraga's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_3"></a>|mateusbraga commented|
|-|-|

How can I create a patch file that contains the new twisted/topfiles/5895.removal file that I created? 

"svn diff -x -u > my-twisted-patch.patch" did not work in my case.

twisted/topfiles/5895.removal should have: 

twisted.python.compat.adict is now deprecated.
twisted.python.compat.inet_pton is now deprecated in favor of socket.inet_pton from the standard library.
twisted.python.compat.inet_ntop is now deprecated in favor of socket.inet_ntop from the standard library.

**Comment by twisted-trac** [comment]
|<img alt="dhanush's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_4"></a>|dhanush set owner to mateusbraga|
|-|-|

You need to do the following for your 5895.removal file to show up in your patch : 

1. svn add twisted/topfiles/5895.removal 

2. svn diff

Also consider going through this : [http://twistedmatrix.com/trac/wiki/TwistedDevelopment#SubmittingaPatch]

**Comment by twisted-trac** [comment]
|<img alt="mateusbraga's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|mateusbraga removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="Julian's avatar" src="https://avatars.githubusercontent.com/u/329822?s=50" width="50" height="50">](https://github.com/Julian)<a name="note_6"></a>|@Julian commented|
|-|-|

Leaving the review keyword for a more compete review, but if the socket module functions pass the unit tests we can remove the implementation entirely in favor of just using the stdlib stuff already and just leave the deprecation for accessing the names through this module.

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_7"></a>|@thijstriemstra set owner to mateusbraga|
|-|-|

Thanks for your patch.

 1. the deprecated `inet_pton` and `inet_ntop` functions don't have a docstring: it would be nice to add that explaining why they are there, what they try to accomplish (something that is already present in the stdlib nowadays?)
 1. in `twisted.test.test_compat.DeprecationTestCase`:
   1. the class docstring contains a reference to `twisted.python.compat` that should be wrapped in `L{}` and end with a period: `L{twisted.python.compat}.`
   1. you should avoid using the word `Test` in the docstring of the tests.
   1. `C{str}` should be `L{str}`
 1. I would try to rewrite the news file into a single sentence, or at least prevent multiple lines like that

**Comment by twisted-trac** [comment]
|<img alt="mateusbraga's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_8"></a>|mateusbraga removed owner|
|-|-|

I kept C{str} instead of L{str} because according to http://epydoc.sourceforge.net/epytext.html C{} is for python identifiers. (twisted/test/test_reflect.py also uses C{} instead of L{} for str)

Did I get it right?

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_9"></a>|@thijstriemstra set owner to mateusbraga|
|-|-|

Replying to [mateusbraga](#note_8):
> I kept C{str} instead of L{str} because according to http://epydoc.sourceforge.net/epytext.html C{} is for python identifiers. (twisted/test/test_reflect.py also uses C{} instead of L{} for str)

I was confused by this as well but it turns out it's an (undocumented) feature of pydoctor, which uses epytext behind the scenes but made an exception for `L{str}` and other builtins. Here's the IRC chat we had about this recently:

```
 oh, can't you reference params with L{}?
<rwall> It ends up being a link to some API documentation - either in twisted or in stdlib
<jonathanj> that's unfortunate
<rwall> So L has to refer to something imported
<thijstriemstra> ok so L{str}  is wrong as well
<jonathanj> well, no
<kenaan> jonathanj r38147 M(branches/browser-like-redirect-agent-5434/twisted/web/client.py): Fix invalid epytext. ...
<jonathanj> L{} has some special hax for builtins
<thijstriemstra> oh..
<jonathanj> (as an addition to pydoctor)
<rwall> oh ok. Yeah.
<jonathanj> which is probably why you won't find it documented anywhere :(
<jonathanj> rwall: thanks for the review, btw
<rwall> np
<exarkun> Why is L{builtin} surprising?
<exarkun> It's not like `str` is ever /not/ in scope.  Why wouldn't L{} work with it?
<jonathanj> probably because the epydoc epytext documentation doesn't mention anything about it
<jonathanj> the list of searches taken in the epytext docs don't mention stuff about lexical scope
<jonathanj> maybe this could mean that:  Next, epydoc looks for an object with the given name in the current module.
```

> 
> Did I get it right?

 1. So switch those `C{str}` to `L{str}`
 1. Open a ticket to deprecate `set` and `frozenset` in `twisted.python.compat` (they're not useful any longer) and add to keyword `easy` to that (and feel free to start working on it of course :)
 1. Thank for adding the docstrings to the deprecated methods, but you forgot to document its parameters
 1. in docstrings things like `inet_ntop()` should be wrapped in `C{}` to indicate its a code reference
 1. there need to be 3 empty lines between functions (eg. `inet_pton` and `inet_ntop` are currently separated by 1)
 1. you haven't addressed the point from the previous review about the test docstrings yet. For example 'Test deprecation of L{compat.inet_ntop}.' shouldn't include the word 'test', so instead I would write 'L{compat.inet_ntop} is deprecated.' or 'L{compat.inet_ntop} emits a C{DeprecationWarning}.'
 1. This second patch doesn't include the `.removal` file anymore?

**Comment by twisted-trac** [comment]
|<img alt="mateusbraga's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_10"></a>|mateusbraga removed owner|
|-|-|

Thank you for the patience! I think I included everything now.

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_11"></a>|@thijstriemstra commented|
|-|-|

(In [38411]) Branching to 'inet-compat-5895'

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_12"></a>|@thijstriemstra commented|
|-|-|

(In [38412]) apply ticket5895_4.patch, refs [#5895](https://github.com/twisted/twisted/issues/5895)

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_13"></a>|@thijstriemstra set owner to mateusbraga|
|-|-|

Thanks for your patch, I applied it in a branch. When running `admin/run-python3-tests` the `test_inet_ntop` test failed with Python3.3:

```
======================================================================
ERROR: test_inet_ntop (twisted.test.test_compat.DeprecationTestCase)
test_inet_ntop
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/thijs/workspaces/opensource/software/twisted/svn/Twisted/branches/inet-compat-5895/twisted/internet/defer.py", line 137, in maybeDeferred
    result = f(*args, **kw)
  File "/home/thijs/workspaces/opensource/software/twisted/svn/Twisted/branches/inet-compat-5895/twisted/internet/utils.py", line 203, in runWithWarningsSuppressed
    reraise(exc_info[1], exc_info[2])
  File "/home/thijs/workspaces/opensource/software/twisted/svn/Twisted/branches/inet-compat-5895/twisted/python/compat.py", line 186, in reraise
    raise exception.with_traceback(traceback)
  File "/home/thijs/workspaces/opensource/software/twisted/svn/Twisted/branches/inet-compat-5895/twisted/internet/utils.py", line 199, in runWithWarningsSuppressed
    result = f(*a, **kw)
  File "/home/thijs/workspaces/opensource/software/twisted/svn/Twisted/branches/inet-compat-5895/twisted/test/test_compat.py", line 641, in test_inet_ntop
    compat.inet_ntop, socket.AF_INET, "\x01\x00\x01\x00")
  File "/home/thijs/workspaces/opensource/software/twisted/svn/Twisted/branches/inet-compat-5895/twisted/trial/_synctest.py", line 1119, in callDeprecated
    result = f(*args, **kwargs)
  File "/home/thijs/workspaces/opensource/software/twisted/svn/Twisted/branches/inet-compat-5895/twisted/python/deprecate.py", line 271, in deprecatedFunction
    return function(*args, **kwargs)
  File "/home/thijs/workspaces/opensource/software/twisted/svn/Twisted/branches/inet-compat-5895/twisted/python/compat.py", line 390, in inet_ntop
    return socket.inet_ntoa(addr)
TypeError: 'str' does not support the buffer interface

----------------------------------------------------------------------
Ran 3196 tests in 7.885s

FAILED (errors=1, skipped=952)
```

Can you take a look at this and create future patches from the new branch?

**Comment by twisted-trac** [comment]
|<img alt="mateusbraga's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_14"></a>|mateusbraga removed owner|
|-|-|

I just changed so now the test works both on python3.3 and python2.7. I changed from str to bytes. I am not completely sure about how should tests work on both versions, but it is working now.

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_15"></a>|@therve commented|
|-|-|

(In [38583]) Apply patch

Refs [#5895](https://github.com/twisted/twisted/issues/5895)

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_16"></a>|@therve set owner to mateusbraga|
|-|-|

I forced a build which quickly showed that python may have inet_pton, but only on some platforms. Can we really deprecate those?

**Comment by twisted-trac** [comment]
|<img alt="mateusbraga's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_17"></a>|mateusbraga removed owner|
|-|-|

I don't know if we can really deprecate them anymore, so I will set the owner to nobody.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_18"></a>|@exarkun commented|
|-|-|

Windows has [InetPton](http://msdn.microsoft.com/en-us/library/windows/desktop/cc805844(v=vs.85).aspx) which the Python standard library doesn't seem to bother to expose.  It might be nice if our compatibility function were implemented in terms of this instead of being a sort of bad stand-alone re-implementation (probably a not very good one).

Alternatively, we should contribute an `InetPton`-based implementation to the Python standard library so this ticket will be valid later on.

I agree that it appears we cannot get rid of these functions yet.

**Comment by twisted-trac** [comment]
|[<img alt="Julian's avatar" src="https://avatars.githubusercontent.com/u/329822?s=50" width="50" height="50">](https://github.com/Julian)<a name="note_19"></a>|@Julian commented|
|-|-|

There is an open ticket for adding it to the stdlib. It's http://bugs.python.org/issue7171

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_20"></a>|@twm commented|
|-|-|

I tried creating a PR which removes the inet_pton monkey patch: https://github.com/twisted/twisted/pull/1082 It still fails on the Windows 7 Python 2.7 buildbot:

```
Traceback (most recent call last):
  File "C:\buildslave\windows7-64-py2_7\Twisted\build\py27-alldeps-nocov-windows\lib\site-packages\twisted\python\usage.py", line 411, in <lambda>
    fn = lambda name, value, m=method: m(value)
  File "C:\buildslave\windows7-64-py2_7\Twisted\build\py27-alldeps-nocov-windows\lib\site-packages\twisted\application\app.py", line 539, in opt_reactor
    installReactor(shortName)
  File "C:\buildslave\windows7-64-py2_7\Twisted\build\py27-alldeps-nocov-windows\lib\site-packages\twisted\application\reactors.py", line 80, in installReactor
    for installer in getReactorTypes():
  File "C:\buildslave\windows7-64-py2_7\Twisted\build\py27-alldeps-nocov-windows\lib\site-packages\twisted\plugin.py", line 213, in getPlugins
    allDropins = getCache(package)
--- <exception caught here> ---
  File "C:\buildslave\windows7-64-py2_7\Twisted\build\py27-alldeps-nocov-windows\lib\site-packages\twisted\plugin.py", line 171, in getCache
    provider = pluginModule.load()
  File "C:\buildslave\windows7-64-py2_7\Twisted\build\py27-alldeps-nocov-windows\lib\site-packages\twisted\python\modules.py", line 392, in load
    return self.pathEntry.pythonPath.moduleLoader(self.name)
  File "C:\buildslave\windows7-64-py2_7\Twisted\build\py27-alldeps-nocov-windows\lib\site-packages\twisted\python\reflect.py", line 308, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "C:\buildslave\windows7-64-py2_7\Twisted\build\py27-alldeps-nocov-windows\lib\site-packages\twisted\python\reflect.py", line 255, in _importAndCheckStack
    reraise(excValue, excTraceback)
  File "C:\buildslave\windows7-64-py2_7\Twisted\build\py27-alldeps-nocov-windows\lib\site-packages\twisted\plugins\twisted_core.py", line 6, in <module>
    from twisted.internet.endpoints import (
  File "C:\buildslave\windows7-64-py2_7\Twisted\build\py27-alldeps-nocov-windows\lib\site-packages\twisted\internet\endpoints.py", line 29, in <module>
    from twisted.internet.abstract import isIPv6Address, isIPAddress
  File "C:\buildslave\windows7-64-py2_7\Twisted\build\py27-alldeps-nocov-windows\lib\site-packages\twisted\internet\abstract.py", line 11, in <module>
    from socket import AF_INET, AF_INET6, inet_pton, error
exceptions.ImportError: cannot import name inet_pton
```

The stdlib change landed in Python 3.4, so we'll probably be keeping this around until we drop 2.7 support.

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_21"></a>|@twm commented|
|-|-|

Hyperlink has a ctypes-based compatibility shim: https://github.com/python-hyper/hyperlink/blob/master/src/hyperlink/_socket.py

**Comment by twisted-trac** [comment]
|[<img alt="mthuurne's avatar" src="https://avatars.githubusercontent.com/u/246676?s=50" width="50" height="50">](https://github.com/mthuurne)<a name="note_22"></a>|@mthuurne commented|
|-|-|

None of the mentioned names are in `twisted.python.compat` anymore. Can this ticket be closed?
