### ISSUE TITLE
sendmsg.c doesn't work on PyPy

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#5902]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)| @glyph reported|
|-|-|
|Trac ID|trac#5902|
|Type|defect|
|Created|2012-08-22 18:50:04Z|

As discussed here: http://raphael.uaca.com/2012/08/irc-2012-7-24/

<details><summary>Searchable metadata</summary>

```
trac-id__5902 5902
type__defect defect
reporter__glyph glyph
priority__normal normal
milestone__PyPy_support PyPy-support
branch__ 
branch_author__ 
status__closed closed
resolution__worksforme worksforme
component__core core
keywords__ 
time__1345661404000000 1345661404000000
changetime__1511495353125506 1511495353125506
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

Perhaps a link to [the failing builder](http://buildbot.twistedmatrix.com/builders/lucid32-pypy) is more pertinent?  I hate tickets that rely on external resources to make any sense, but at least this is a resource hosted by us.

Or, here, I can just paste a failing test's output:

```
[FAIL]
Traceback (most recent call last):
  File "/var/lib/buildbot/bot-glyph-1/lucid32-pypy/build/twisted/python/test/test_sendmsg.py", line 288, in test_syscallErrorWithControlMessage
    error, send1msg, fd, "hello, world", 0, [(0, 0, "0123")])
twisted.trial.unittest.FailTest: <type 'exceptions.OverflowError'> raised instead of error:
 Traceback (most recent call last):
  File "/var/lib/buildbot/bot-glyph-1/lucid32-pypy/build/twisted/trial/unittest.py", line 1143, in _run
    utils.runWithWarningsSuppressed, self._getSuppress(), method)
  File "/var/lib/buildbot/bot-glyph-1/lucid32-pypy/build/twisted/internet/defer.py", line 134, in maybeDeferred
    result = f(*args, **kw)
  File "/var/lib/buildbot/bot-glyph-1/lucid32-pypy/build/twisted/internet/utils.py", line 191, in runWithWarningsSuppressed
    result = f(*a, **kw)
  File "/var/lib/buildbot/bot-glyph-1/lucid32-pypy/build/twisted/python/test/test_sendmsg.py", line 288, in test_syscallErrorWithControlMessage
    error, send1msg, fd, "hello, world", 0, [(0, 0, "0123")])
--- <exception caught here> ---
  File "/var/lib/buildbot/bot-glyph-1/lucid32-pypy/build/twisted/trial/unittest.py", line 243, in failUnlessRaises
    result = f(*args, **kwargs)
exceptions.OverflowError: CMSG_LEN(139930034503684) > SOCKLEN_MAX


twisted.python.test.test_sendmsg.SendmsgTestCase.test_syscallErrorWithControlMessage
```

That's just one, there are several that fail that way.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_2"></a>|@glyph commented|
|-|-|

This has got to be some nuance of `PyArgs_ParseTuple` that isn't implemented by PyPy, right?  Any idea which?

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_3"></a>|@rodrigc set status to `closed`|
|-|-|

This test now works with PyPy 5.8.0: https://buildbot.twistedmatrix.com/builders/ubuntu16.04-pypy5/builds/166/steps/select/logs/stdio
