### ISSUE TITLE
Trial fails flushing reporter stream with ENOSPC on Windows

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#5921]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)| @itamarst reported|
|-|-|
|Trac ID|trac#5921|
|Type|defect|
|Created|2012-08-26 23:27:47Z|
|Branch|https://github.com/twisted/twisted/tree/ENOSPC-5921-4|

When running under a buildslave on Windows, trial is writing to stdout, attempts to flush, and sometimes gets ENOSPC:

```
...
  File "C:\Users\Build Slave\bot-glyph-6\windows7-64-py2.7-select\Twisted\twisted\trial\unittest.py", line 752, in run
    result.startTest(self)
  File "C:\Users\Build Slave\bot-glyph-6\windows7-64-py2.7-select\Twisted\twisted\trial\reporter.py", line 765, in startTest
    self._write('%s ... ', tm.id())
  File "C:\Users\Build Slave\bot-glyph-6\windows7-64-py2.7-select\Twisted\twisted\trial\reporter.py", line 436, in _write
    untilConcludes(self._stream.flush)
  File "C:\Users\Build Slave\bot-glyph-6\windows7-64-py2.7-select\Twisted\twisted\python\util.py", line 776, in untilConcludes
    return f(*a, **kw)
IOError: [Errno 28] No space left on device
```

Here's something that may be relevant:
https://lists.gnu.org/archive/html/bug-gnulib/2011-04/msg00169.html

It suggests that `untilConcludes` or maybe trial's `SafeStream` should treat ENOSPC on writes to pipes the same as EAGAIN, at first glance.

<details><summary>Searchable metadata</summary>

```
trac-id__5921 5921
type__defect defect
reporter__itamar itamar
priority__normal normal
milestone__ 
branch__branches_ENOSPC_5921_4 branches/ENOSPC-5921-4
branch_author__itamarst__itamar__exarkun__glyph itamarst, itamar, exarkun, glyph
status__new new
resolution__None None
component__core core
keywords__ 
time__1346023667000000 1346023667000000
changetime__1390870515000000 1390870515000000
version__None None
owner__itamar itamar
cc__tom.prince cc__exarkun
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)<a name="note_2"></a>|@itamarst commented|
|-|-|

(In [35395]) Branching to 'ENOSPC-5921'

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)<a name="note_3"></a>|@itamarst commented|
|-|-|

The attempted fix I checked in seemed to work (http://buildbot.twistedmatrix.com/builders/windows7-64-py2.7/builds/1636 passed with `select()` reactor). At this point it needs to be expanded to cover `write()` as well as `flush()`. And, of course, limited to Windows pipes (an infinite loop on `ENOSPC` on the filesystem isn't a good idea).

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)|@itamarst set owner to @itamarst|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)<a name="note_5"></a>|@itamarst commented|
|-|-|

Other thoughts: this may need to be fixed in stdio and process support as well. And of course we should find and read relevant MSDN docs before proceeding.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_6"></a>|@glyph commented|
|-|-|

Relevant references: [_write](http://msdn.microsoft.com/en-us/library/t3ayayh1(v=vs.71)), [_doserrno](http://msdn.microsoft.com/en-us/library/t3ayayh1(v=vs.71)), don't have anything to say about this.  ENOSPC is listed as just meaning that there's no disk space left.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_7"></a>|@glyph commented|
|-|-|

Also nothing on [_pipe](http://msdn.microsoft.com/en-us/library/edze9h7e(v=vs.71)).

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_8"></a>|@glyph commented|
|-|-|

Based on my research just now I think that this behavior may just be an undocumented bug, and it would be okay to treat the GNU mailing list message as authoritative.

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)<a name="note_9"></a>|@itamarst commented|
|-|-|

Did you manage to reproduce it in a test script? I'm planning to include one as part of the review submission.

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)<a name="note_10"></a>|@itamarst commented|
|-|-|

(In [35852]) Branching to 'ENOSPC-5921-2'

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)<a name="note_11"></a>|@itamarst commented|
|-|-|

It occurs to me that calling `untilConcludes(file.write, ...)` is a bug: `file.write` may call `os.write` multiple times, and only the last one that raised the `EINTR/EAGAIN` should be retried. This suggests that `ENOSPC` handling should be moved into `untilConcludes`, and `SafeStream` refactored to use `os.write`.

First step is getting a test to reproduce the underlying problem.

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)<a name="note_12"></a>|@itamarst commented|
|-|-|

http://buildbot.twistedmatrix.com/builders/winxp32-py2.7/builds/1466/steps/select/logs/stdio demonstrates the brokenness of current solution. The end looks like this:

```
===============================================================================
[TODO]
Reason: 'This may be impossible but it sure would be nice.'
Traceback (most recent call last):
  File "C:\buildslave\twisted\winxp32-py2.7\Twisted\twisted\test\test_modules.py", line 357, in test_underUnderPathNotAlreadyImported
    self._underUnderPathTest(False)
  File "C:\buildslave\twisted\winxp32-py2.7\Twisted\twisted\test\test_modules.py", line 341, in _underUnderPathTest
    importPackages=doImport),
  File "C:\buildslave\twisted\winxp32-py2.7\Twisted\twisted\python\test\modules_helpers.py", line 26, in findByIteration
    self.fail("Unable to find module %r through iteration." % (modname,))
twisted.trial.unittest.FailTest: Unable to find module 'pyspacetests3.foozle' through iteration.

twisted.test.test_modules.PathModificationTest.test_underUnderPathNotAlreadyImported
===============================================================================
[TODO]

twisted.test.test_modules.RebindingTest.test_underUnderPathNotAlreadyImported

[TODO]



[TODO]



[TODO]





program finished with exit code 1
elapsedTime=306.156000
```

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_13"></a>|@glyph commented|
|-|-|

(In [36863]) Branching to 'ENOSPC-5921-3'

**Comment by twisted-trac** [comment]
|[<img alt="tomprince's avatar" src="https://avatars.githubusercontent.com/u/283816?s=50" width="50" height="50">](https://github.com/tomprince)<a name="note_14"></a>|@tomprince commented|
|-|-|

[#7248](https://github.com/twisted/twisted/issues/7248) looks related which also points to http://bugs.python.org/issue11395

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_15"></a>|@exarkun commented|
|-|-|

(In [38233]) test cleanups

  - split up a test into two to exercise each case separately
  - be explicit about bytes in the SafeStream tests
  - wrap long lines
  - minor docstring improvements
  - make the error parameter to BrokenStream required for explicitness
  - factor out IOError creation to remove redundancy
  - fix some possible fd leaks

refs [#5921](https://github.com/twisted/twisted/issues/5921)

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_16"></a>|@exarkun commented|
|-|-|

(In [38241]) Branching to 'ENOSPC-5921-4'

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_17"></a>|@exarkun commented|
|-|-|

Well I thought I had some ideas, but they didn't come to anything.  Basically just churned the code a little bit.  I 'hope' the test coverage is at least a little better overall now, but I made it at least a little worse by getting rid of the ENOSPC/flush coverage because I thought that wasn't a real case (but it turns out it is a real case).

The branch basically fails the same way now as it did when I started, with the weird semi-formed summary that itamar quoted in his comment above.  I also noticed other problems with the output, such as a big grouping of empty lines seemingly randomly inserted in the middle of a list of skips.  I'm beginning to think naive retry on encountering ENOSPC is not a correct strategy (nor even the retry I implemented, where each write is attempted with fewer and fewer bytes).  It's hard to explain how the observed behavior could be happening without the underlying write discarding some of the bytes even when it claims success.

I also observed that test.log appears truncated in the buildbot build report.  It ends at `twisted.test.test_twistd.TapFileTest.test_createOrGetApplicationWithTapFile` but this is not the last test in the suite.  I noticed this after adding some debug logging to `SafeStream`.

I also noticed that ENOSPC errors seem to happen a lot after big runs of skipped tests, perhaps because these can run faster and therefore the console buffer (or whatever it is that runs out of space) has a greater chance of filling up at these times.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_18"></a>|@exarkun commented|
|-|-|

Another problem here is that the colorizers don't use `SafeStream` - they write straight to `sys.stdout`.  Whether this is part of the problem here, I don't know, but it's at least a possibility.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_19"></a>|@exarkun commented|
|-|-|

Something I don't understand is that the gnu mailing list post talks about non-blocking pipes.  Is stdout a non-blocking pipe on Windows?  Why would it be?  I don't see any code in trial that sets it non-blocking.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_20"></a>|@exarkun commented|
|-|-|

> Whether this is part of the problem here, I don't know, but it's at least a possibility.

Buildbot runs trial with --bwverbose which skips colorizers so I guess this is unrelated.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_21"></a>|@glyph commented|
|-|-|

Replying to [exarkun](#note_19):
> Something I don't understand is that the gnu mailing list post talks about non-blocking pipes.  Is stdout a non-blocking pipe on Windows?  Why would it be?  I don't see any code in trial that sets it non-blocking.

Keep in mind that Buildbot uses Twisted, and spawns processes on Windows with `spawnProcess`.  Perhaps the non-blocking-ness of a pipe is even _more_ global on Windows than on Linux, and it actually makes _both_ ends non-blocking?  Or perhaps the way we're setting up the pipe is just stupidly setting both to be non-blocking?

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_22"></a>|@exarkun commented|
|-|-|

Indeed.  I still don't quite understand why it's so hard to reproduce, though (considering I tried using actual stdout and ran the attempt using BuildBot).

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_23"></a>|@glyph commented|
|-|-|

Just to keep the tally updated, this came up again in [ticket:6751 this review].

**Comment by exarkun** [comment]
This is now regularly impacting Tahoe-LAFS test suite runs on Windows.  It's rare to have a CI run complete without at least one Windows job fail due to this.

**Comment by itamarst** [comment]
Due to changes in https://bugs.python.org/issue5319, the new symptom is exit code 120 on Windows.

**Comment by itamarst** [comment]
Other references I've found to the ENOSPC issue:

https://trac.netlabs.org/kbuild/ticket/120#comment:1 says "_write_nolock() in crt/src/write.c returns ENOSPC if no bytes were written and no error reported by windows. (line 497 in the Visual Studio v10 sources). It's really just a way of saying: The pipe buffer is full and we're in non-blocking mode, so try again."

https://lore.kernel.org/git/YvyGJiz+CFPcgpML@coredump.intra.peff.net/ (from 2022!) says "When write() to a non-blocking pipe fails because the buffer is full, POSIX says we should see EAGAIN. But our mingw_write() compat layer on
Windows actually returns ENOSPC for this case. This is probably something we want to correct, but given that we don't plan to use non-blocking descriptors in a lot of places, we can work around it by just catching ENOSPC alongside EAGAIN. If we ever do fix mingw_write(), then this patch can be reverted."
