### ISSUE TITLE
IndexError in notifyFinish

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#5957]
|<img alt="honeyman's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| honeyman reported|
|-|-|
|Trac ID|trac#5957|
|Type|defect|
|Created|2012-09-10 11:43:59Z|

We are using Python 2.7 and Twisted 12.0 in our application. Recently we've spotted a number of errors like this:

```
2012-09-10 14:37:12,116 (5746/7f2e7b7fe700) - 504a39e6:common.server - ERROR - During <function __render_in_thread at 0x3e97500>, the following error occured: list index out of range
Traceback (most recent call last):
 File "/home/sozforex/src/freebrie/trunk/common/utils.py", line 513, in wrapper
 return f(*args, **kwargs)
 File "/home/sozforex/src/freebrie/trunk/common/server.py", line 303, in __render_in_thread
 request.notifyFinish().addErrback(self._handle_connection_close)
 File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 857, in notifyFinish
 return self.notifications[-1]
IndexError: list index out of range
```

Just to recall, `notifyFinish()` is defined this way:
```
    def notifyFinish(self):
        """
        Notify when the response to this request has finished.

        @rtype: L{Deferred}

        @return: A L{Deferred} which will be triggered when the request is
            finished -- with a C{None} value if the request finishes
            successfully or with an error if the request is interrupted by an
            error (for example, the client closing the connection prematurely).
        """
        self.notifications.append(Deferred())
        return self.notifications[-1]
```

It seems obvious that the problem is caused by a race condition between the first and the second line of `notifyFinish()`: the deferred variable gets created, appended, then (in some other thread, between the first and the second line) removed, and by the
second line, is already missing.

The fix seems obvious as well:
```
--- http.py     2011-09-25 00:04:03.000000000 +0400
+++ http-new.py 2012-09-10 15:36:35.051651398 +0400
@@ -853,8 +853,9 @@
             successfully or with an error if the request is interrupted by an
             error (for example, the client closing the connection prematurely).
         """
-        self.notifications.append(Deferred())
-        return self.notifications[-1]
+        d = Deferred()
+        self.notifications.append(d)
+        return d
```

On one hand, I believe it is related to the usual claim that Twisted is not thread-safe; so the fix probably may be ignored (unless  there is a global trend of continuously improving Twisted's thread safety); on the other hand, the fix is trivial and just gets this place to work better, so I still suggest the fix to be applied.

<details><summary>Searchable metadata</summary>

```
trac-id__5957 5957
type__defect defect
reporter__honeyman honeyman
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__invalid invalid
component__web web
keywords__ 
time__1347277439000000 1347277439000000
changetime__1347277602000000 1347277602000000
version__None None
owner__ 
cc__jknight
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_2"></a>|@exarkun set status to `closed`|
|-|-|

Thanks.  It is illegal to use these APIs from any thread except the reactor.  If you are doing so, you should stop: the behavior is undefined (and so an `IndexError` is perfectly acceptable when doing so, as far as Twisted is concerned).  If you can reproduce this problem without using threads, please feel free to re-open this ticket.  Thanks again.
