### ISSUE TITLE
twisted.internet.test.test_fdset.ReactorFDSetTestsBuilder_CFReactor.test_connectionLostOnShutdown fails sometimes

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#6020]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)| @itamarst reported|
|-|-|
|Trac ID|trac#6020|
|Type|defect|
|Created|2012-09-25 12:28:01Z|

I am not sure why this wasn't caught when merged, but:

```
[ERROR]
Traceback (most recent call last):
  File "/Users/buildbot/BuildSlave/py-without-modules/Twisted/twisted/python/log.py", line 88, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/Users/buildbot/BuildSlave/py-without-modules/Twisted/twisted/python/log.py", line 73, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/Users/buildbot/BuildSlave/py-without-modules/Twisted/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/Users/buildbot/BuildSlave/py-without-modules/Twisted/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "/Users/buildbot/BuildSlave/py-without-modules/Twisted/twisted/internet/abstract.py", line 251, in doWrite
    l = self.writeSomeData(self.dataBuffer)
  File "/Users/buildbot/BuildSlave/py-without-modules/Twisted/twisted/internet/abstract.py", line 216, in writeSomeData
    reflect.qual(self.__class__))
exceptions.NotImplementedError: twisted.internet.abstract.FileDescriptor does not implement writeSomeData

twisted.internet.test.test_fdset.ReactorFDSetTestsBuilder_CFReactor.test_connectionLostOnShutdown
twisted.internet.test.test_fdset.ReactorFDSetTestsBuilder_CFReactor.test_connectionLostOnShutdown
```

<details><summary>Searchable metadata</summary>

```
trac-id__6020 6020
type__defect defect
reporter__itamar itamar
priority__normal normal
milestone__Python_3_3_Minimal Python 3.3 Minimal
branch__ 
branch_author__ 
status__closed closed
resolution__invalid invalid
component__core core
keywords__ 
time__1348576081000000 1348576081000000
changetime__1348576229000000 1348576229000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)<a name="note_1"></a>|@itamarst set status to `closed`|
|-|-|

I'll just revert the ticket that caused this.
