### ISSUE TITLE
Port twisted.web.util to Python 3

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#6178]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)| @itamarst reported|
|-|-|
|Trac ID|trac#6178|
|Type|enhancement|
|Created|2012-11-08 20:03:45Z|
|Branch|https://github.com/twisted/twisted/tree/twutil-py3-6178|

`twisted.web.util` should run on Python 3.

<details><summary>Searchable metadata</summary>

```
trac-id__6178 6178
type__enhancement enhancement
reporter__itamar itamar
priority__lowest lowest
milestone__Python_3_x Python-3.x
branch__branches_twutil_py3_6178 branches/twutil-py3-6178
branch_author__hawkowl hawkowl
status__closed closed
resolution__fixed fixed
component__web web
keywords__ 
time__1352405025000000 1352405025000000
changetime__1449189192129098 1449189192129098
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|<img alt="nott_'s avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|nott_ set owner to nott_|
|-|-|

**Comment by twisted-trac** [comment]
|<img alt="nott_'s avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|nott_ removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|<img alt="ihrachyshka's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_3"></a>|ihrachyshka commented|
|-|-|

This will probably require changing filepath.py to expose unicode strings instead of bytes. F.e. if I try to import the module in Python3.3, I get the following:

>>> import twisted.web.util
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./twisted/web/util.py", line 362, in <module>
    class FailureElement(Element):
  File "./twisted/web/util.py", line 372, in FailureElement
    loader = XMLFile(getModule(__name__).filePath.sibling("failure.xhtml"))
  File "./twisted/python/filepath.py", line 408, in sibling
    return self.parent().child(path)
  File "./twisted/python/filepath.py", line 679, in child
    if self.sep in norm:
TypeError: 'in <string>' requires string as left operand, not bytes

If I try to pass bytes string to sibling(), I get another error:


>>> import twisted.web.util
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./twisted/web/util.py", line 362, in <module>
    class FailureElement(Element):
  File "./twisted/web/util.py", line 372, in FailureElement
    loader = XMLFile(getModule(__name__).filePath.sibling(b"failure.xhtml"))
  File "./twisted/python/filepath.py", line 408, in sibling
    return self.parent().child(path)
  File "./twisted/python/filepath.py", line 681, in child
    newpath = abspath(joinpath(self.path, norm))
  File "/usr/local/Cellar/python3/3.3.2/Frameworks/Python.framework/Versions/3.3/lib/python3.3/posixpath.py", line 92, in join
    "components.") from None
TypeError: Can't mix strings and bytes in path components.

It looks like filepath object is instantiated via unicode __module__ path, while we try to use paths as if they are bytes. Looks like the ticket to handle first is: [#5203](https://github.com/twisted/twisted/issues/5203)

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_4"></a>|@hawkowl commented|
|-|-|

(In [44196]) Branching to twutil-py3-6178.

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_6"></a>|@hawkowl set status to `closed`|
|-|-|

This has all been ported now.
