### ISSUE TITLE
TimerService is not resilient to stopService before startService

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#6202]
|[<img alt="dustin's avatar" src="https://avatars.githubusercontent.com/u/28673?s=50" width="50" height="50">](https://github.com/dustin)| @dustin reported|
|-|-|
|Trac ID|trac#6202|
|Type|enhancement|
|Created|2012-12-05 04:30:54Z|

In Buildbot, if the master fails during startup (most easily caused by a missing config file!), then it calls `reactor.stop` which calls `stopService` for the entire service hierarchy.. regardless of whether `startService` had completed successfully.

This leads to
```
2012-12-04 23:22:38-0500 [-] Unhandled error in Deferred:
2012-12-04 23:22:38-0500 [-] Unhandled Error
        Traceback (most recent call last):
          File "/home/dustin/code/buildbot/t/buildbot/master/buildbot/master.py", line 213, in stopService
            yield service.MultiService.stopService(self)
          File "/home/dustin/code/buildbot/t/buildbot/sand27/lib/python2.7/site-packages/twisted/application/service.py", line 290, in stopService
            l.append(defer.maybeDeferred(service.stopService))
          File "/home/dustin/code/buildbot/t/buildbot/sand27/lib/python2.7/site-packages/twisted/internet/defer.py", line 134, in maybeDeferred
            result = f(*args, **kw)
          File "/home/dustin/code/buildbot/t/buildbot/sand27/lib/python2.7/site-packages/twisted/application/service.py", line 290, in stopService
            l.append(defer.maybeDeferred(service.stopService))
        --- <exception caught here> ---
          File "/home/dustin/code/buildbot/t/buildbot/sand27/lib/python2.7/site-packages/twisted/internet/defer.py", line 134, in maybeDeferred
            result = f(*args, **kw)
          File "/home/dustin/code/buildbot/t/buildbot/sand27/lib/python2.7/site-packages/twisted/application/internet.py", line 297, in stopService
            if self._loop.running:
        exceptions.AttributeError: TimerService instance has no attribute '_loop'
```
which seems unnecessary, and certainly will scare users.

What do you think of adding `self._loop = None` in `__init__`, and checking `if self._loop` in `stopService`?

Attachments:

* [TimerService-stopService-warning.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/ce5/ce58dcbefc127787e08442723ee8a20e75cddf84/eeebdba97164354dd20d51eb94534d9fe274e07a.patch) (3881 bytes) - added by tom.prince on 2012-12-08 07:21:19Z - Warn user about calling stopService before startService.
* [TimerService-stopService-exception.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/ce5/ce58dcbefc127787e08442723ee8a20e75cddf84/55f09a90a95f7732dee0993bd554245b2319488e.patch) (4351 bytes) - added by tom.prince on 2012-12-09 17:11:27Z - Raise an exception if stopService called before startService

<details><summary>Searchable metadata</summary>

```
trac-id__6202 6202
type__enhancement enhancement
reporter__dustin dustin
priority__lowest lowest
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__ 
component__core core
keywords__ 
time__1354681854000000 1354681854000000
changetime__1355095729000000 1355095729000000
version__None None
owner__tom_prince tom.prince
cc__dustin
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)<a name="note_1"></a>|@itamarst commented|
|-|-|

Calling `stopService` when `startService` wasn't called is a violation of the API; even if the proposed fix is a reasonable improvement, more important is figuring and preventing this out-of-order call.

However, this doesn't seem like it's Twisted's fault. `stopService` is only _registered_ to be called, let alone called, after `startService` is called - see `twisted.application.app.startApplication`. Moreover, calling `reactor.stop()` doesn't trigger `stopService`, it only happens in the next iteration. Buildbot, however, seems to be calling `stopService` itself, and doing so apparently in a less resilient way than Twisted, so I'd say that as a first priority Buildbot should be fixed.

**Comment by twisted-trac** [comment]
|[<img alt="dustin's avatar" src="https://avatars.githubusercontent.com/u/28673?s=50" width="50" height="50">](https://github.com/dustin)<a name="note_2"></a>|@dustin commented|
|-|-|

"stopService is only _registered_ to be called, let alone called, after startService is called" is false - for TimerService, at least, `stopService` is getting called when `stopService` was not.  I think what you're saying is that at that highest level of the hierarchy, `stopService` is only called after `startService` has been *called* -- even if it has not completed successfully.

Aside from monkey-patching (https://github.com/buildbot/buildbot/commit/5267dc8e03eb12f6f60f6ea1cb8232a93b72cfe4), Buildbot has no good way to handle errors that occur *during* service startup, as during that time Twisted's notion of the service hierarchy state ("started") does not match reality (some service started, some not).

The smaller bug is that TimerService does not handle this case gracefully, instead presenting a rather misleading AttributeError.  That's what I'd like to fix in this ticket.

The larger bug is that Twisted considers the whole hierarchy to be started or stopped as one, when in fact each service has a state of its own.  To solve that, each service should track its own state, and not stop a stopped service or start a started service.  If I recall correctly, that's another (and larger) bug, although I can't find it now.  I'm not saying we should solve it here.

It's worth noting that Buildbot doesn't call `stopService`:
```python
    @defer.inlineCallbacks
    def startService(self, _reactor=reactor):
#...
            try:
                1 #...
            except config.ConfigErrors, e:
#...
                _reactor.stop()
                return
```
(https://github.com/buildbot/buildbot/blob/master/master/buildbot/master.py#L176)

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)<a name="note_3"></a>|@itamarst commented|
|-|-|

Replying to [dustin](#note_2):
> "stopService is only _registered_ to be called, let alone called, after startService is called" is false - for TimerService, at least, `stopService` is getting called when `stopService` was not.  I think what you're saying is that at that highest level of the hierarchy, `stopService` is only called after `startService` has been *called* -- even if it has not completed successfully.

No. I'm saying the that is how you are supposed to use services. If you're calling `stopService` without having called `startService`, arguably your code is buggy. So the question is where this buggy code is.


> Aside from monkey-patching (https://github.com/buildbot/buildbot/commit/5267dc8e03eb12f6f60f6ea1cb8232a93b72cfe4), Buildbot has no good way to handle errors that occur *during* service startup, as during that time Twisted's notion of the service hierarchy state ("started") does not match reality (some service started, some not).

That sounds like something worth discussing on the mailing list, maybe, as a preliminary to a ticket if there isn't one already.


> The larger bug is that Twisted considers the whole hierarchy to be started or stopped as one, when in fact each service has a state of its own.  To solve that, each service should track its own state, and not stop a stopped service or start a started service.  If I recall correctly, that's another (and larger) bug, although I can't find it now.  I'm not saying we should solve it here.

The only way you can have a hierarchy of services using pure Twisted code is `MultiService`, and `MultiService` does start all or stop all. Reading its code I don't see how it could calling `stopService` on something that hasn't been started.

It looks like the problem is in your `MultiService` subclass: it delays starting services until reactor is started, but doesn't check in `stopService` whether services have actually been started. If you set `self.actuallyStarted = True` in https://github.com/buildbot/buildbot/blob/master/master/buildbot/master.py#L166, say, and then check for that in `stopService` you can ensure this problem doesn't happen.


> It's worth noting that Buildbot doesn't call `stopService`:

Sorry, I misread the traceback.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_4"></a>|@exarkun commented|
|-|-|

It would be nice to have an example of the problem that doesn't involve buildbot.

**Comment by twisted-trac** [comment]
|[<img alt="dustin's avatar" src="https://avatars.githubusercontent.com/u/28673?s=50" width="50" height="50">](https://github.com/dustin)<a name="note_5"></a>|@dustin commented|
|-|-|

```python
from twisted.application import service, internet

class MyParent(service.MultiService):

    def startService(self):
        if not False:
            print "Oh no, that sucks"
            return
        service.MultiService.startService(self)

if __name__ == "__main__":
    parent = MyParent()
    child = internet.TimerService(10, lambda : None)
    child.setServiceParent(parent)

    parent.startService()
    parent.stopService()
```

**Comment by twisted-trac** [comment]
|[<img alt="dustin's avatar" src="https://avatars.githubusercontent.com/u/28673?s=50" width="50" height="50">](https://github.com/dustin)<a name="note_6"></a>|@dustin commented|
|-|-|

Where you should read "if not False" as an error condition occurring.  In this example, the parent startup needs to precede the child startup, but this could just as well be a case where two sibling services are starting up, and one fails to start before the other has begun starting.  In trying to unwind things gracefully, `stopService` is called everywhere, and wham, this completely non-intuitive exception.

 * minimal: make this exception more intuitive
 * simple: make TimerService resilient to stop before start
 * better: track service state on a per-service basis, not globally, and don't stop things that aren't running (but as I said above, out of scope for this particular bug)

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)<a name="note_7"></a>|@itamarst commented|
|-|-|

This is a bug in `MyParent`, it really has nothing to do with Twisted. The correct way to solve it, as I explained above, is something like this:

```python
from twisted.application import service, internet
 
class MyParent(service.MultiService):

    _reallyStarted = False

    def startService(self):
        if not configOK():
            print "Oh no, that sucks"
            return
        self._reallyStarted = True
        service.MultiService.startService(self)

    def stopService(self):
        if self._reallyStarted:
            return service.MultiService.stopService(self)
```

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)<a name="note_8"></a>|@itamarst commented|
|-|-|

The other case (a problem with one service failing after one sibling has already started) may be something Twisted itself has to deal with, I'll look at `MultiService` code in the morning.

**Comment by twisted-trac** [comment]
|[<img alt="tomprince's avatar" src="https://avatars.githubusercontent.com/u/283816?s=50" width="50" height="50">](https://github.com/tomprince)<a name="note_9"></a>|@tomprince commented|
|-|-|

Here is some code that emits a warning if stopService is called without startService being called first.

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)<a name="note_10"></a>|@itamarst commented|
|-|-|

I opened [#6206](https://github.com/twisted/twisted/issues/6206) to cover the `MultiService` issue where one service fails half-way through startup. Depending on the solution it would also solve the bug in Buildbot's `MultiService` subclass bug, but better to just fix it directly.

Regardless, I personally don't think there's any point making changes to `TimerService` to work around what's in this case a bug in Buildbot, or more generally something that should be fixed in `MultiService` ([#6206](https://github.com/twisted/twisted/issues/6206)).

**Comment by twisted-trac** [comment]
|[<img alt="dustin's avatar" src="https://avatars.githubusercontent.com/u/28673?s=50" width="50" height="50">](https://github.com/dustin)<a name="note_11"></a>|@dustin set status to `closed`|
|-|-|

Fair enough.  I think that making the error more obvious than AttributeError is worth considering, but that's certainly *very* minor.

**Comment by twisted-trac** [comment]
|[<img alt="tomprince's avatar" src="https://avatars.githubusercontent.com/u/283816?s=50" width="50" height="50">](https://github.com/tomprince)<a name="note_12"></a>|@tomprince set status to `reopened`|
|-|-|

I've attached code to either issue a warning or an exception, instead of failing on implementation details.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_13"></a>|@exarkun set owner to @tomprince<br>@exarkun set status to `new`|
|-|-|

The exception raised isn't part of the interface in either case, so I don't see the benefit of this change.

**Comment by twisted-trac** [comment]
|[<img alt="dustin's avatar" src="https://avatars.githubusercontent.com/u/28673?s=50" width="50" height="50">](https://github.com/dustin)<a name="note_14"></a>|@dustin commented|
|-|-|

Either of Tom's suggestions are helpful error messages.  AttributeError suggests an error in Twisted, and only a read of the Twisted code reveals what the real cause is.  Clarity in error messages is worthwhile, IMHO.
