### ISSUE TITLE
exceptions.ValueError: need more than 0 values to unpack

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#6279]
|<img alt="p4l4cl][n's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| p4l4cl][n reported|
|-|-|
|Trac ID|trac#6279|
|Type|defect|
|Created|2013-01-24 22:16:18Z|

Hi, I am getting this error:

```
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/protocols/ftp.py", line 753, in processCommand
    return method(*params)
  File "/usr/lib/python2.7/dist-packages/twisted/protocols/ftp.py", line 1175, in ftp_SIZE
    return self.shell.stat(newsegs, ('size',)).addCallback(cbStat)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 301, in addCallback
    callbackKeywords=kw)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 290, in addCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 551, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/protocols/ftp.py", line 1172, in cbStat
    def cbStat((size,)):
exceptions.ValueError: need more than 0 values to unpack
```

and I am not sure what to do with it.. I am not even sure if error is in my code or in twisted..

Twisted is used as ftp server. Python 2.7. Do you need any additional informations?

Thanks for reaction

<details><summary>Searchable metadata</summary>

```
trac-id__6279 6279
type__defect defect
reporter__p4l4cl__n p4l4cl][n
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__invalid invalid
component__ftp ftp
keywords__ 
time__1359065778000000 1359065778000000
changetime__1359068377000000 1359068377000000
version__None None
owner__ 
cc__itamarst
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_2"></a>|@exarkun commented|
|-|-|

Fixing description markup

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_3"></a>|@exarkun set status to `closed`|
|-|-|

This seems to be a bug in the `IFTPShell` implementation you're using.  From the traceback, it's not clear which implementation that might be, or whether it is from Twisted or your own creation.

I recommend using the [mailing list, the irc channel, or stackoverflow](http://twistedmatrix.com/trac/wiki/TwistedCommunity) to solicit assistance tracking down the particular details of the problem.  Then, if it turns out to be a bug in Twisted, please feel free to re-open this ticket.
