### ISSUE TITLE
epoll error: epollreactor stop UDP protocol while selectreactor connectionRefused

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#6287]
|<img alt="huyx's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| huyx reported|
|-|-|
|Trac ID|trac#6287|
|Type|defect|
|Created|2013-01-29 18:30:29Z|
|Branch|https://github.com/twisted/twisted/tree/epoll-udp-refused-6287|

When i use epollreactor and send UDP data to server, i got error:

```
Unhandled Error
Traceback (most recent call last):
  File "echoclient_udp_epoll.py", line 35, in <module>
    main()
  File "echoclient_udp_epoll.py", line 32, in main
    reactor.run()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1173, in run
    self.mainLoop()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1182, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 805, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "echoclient_udp_epoll.py", line 23, in sendDatagram
    self.transport.write(datagram)
exceptions.AttributeError: 'NoneType' object has no attribute 'write'
```

I used the following test code:
```
#!/usr/bin/env python

# from twisted.internet import selectreactor    # ****
# selectreactor.install()                       # ****

from twisted.internet.protocol import DatagramProtocol
from twisted.internet import reactor
from itertools import cycle

class EchoClientDatagramProtocol(DatagramProtocol):
    strings = cycle([
        "Hello, world!\n",
        "What a fine day it is.\n",
        "Bye-bye!\n"
    ])

    def startProtocol(self):
        self.transport.connect('127.0.0.1', 8000)
        self.sendDatagram()

    def sendDatagram(self):
        datagram = self.strings.next()
        self.transport.write(datagram)
        reactor.callLater(1, self.sendDatagram)

    def connectionRefused(self):
        print 'connectionRefused'

    def datagramReceived(self, datagram, host):
        print 'Datagram received: ', repr(datagram)

def main():
    protocol = EchoClientDatagramProtocol()
    t = reactor.listenUDP(0, protocol)
    reactor.run()

if __name__ == '__main__':
    main()
```

But when i uncommnet the *** line, it runs as i expected, i thank it  is a bug of epoll reactor, isn't it?

Attachments:

* [fix-epoll-not-calling-connectionRefused](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/512/51203c371f8829f82c697edb29c255d57cb88be1/06ad55589747089930186ed42e91592fd6ba0e4c) (3702 bytes) - added by marto1_ on 2013-08-02 11:20:36Z - _doReadOrWrite modification was needed so that TCP preserved it's behaviour, although still looks like a hack.

<details><summary>Searchable metadata</summary>

```
trac-id__6287 6287
type__defect defect
reporter__huyx huyx
priority__normal normal
milestone__ 
branch__branches_epoll_udp_refused_6287 branches/epoll-udp-refused-6287
branch_author__marto1_ marto1_
status__new new
resolution__None None
component__core core
keywords__epoll_udp epoll udp
time__1359484229000000 1359484229000000
changetime__1380400831000000 1380400831000000
version__None None
owner__marto1_ marto1_

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

Looks like `epoll_wait` signals this case using `EPOLLERR`.  `epollreactor` handles `EPOLLERR` the same way it handles `EPOLLHUP` (so the reason the transport disappears is that the protocol's `doStop` method is called, which throws away the transport).

Perhaps a better thing for `epollreactor` to do would be to handle `EPOLLERR` like `EPOLLIN`, since "readable" is where all of the special UDP error handling logic is implemented (`Port.doRead`).  I didn't check whether this change would have any other bad side-effects though.

**Comment by twisted-trac** [comment]
|<img alt="marto1_'s avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_2"></a>|marto1_ commented|
|-|-|

If you switch

```
    _POLL_DISCONNECTED = (EPOLLHUP | EPOLLERR)
    _POLL_IN = EPOLLIN
    _POLL_OUT = EPOLLOUT
```

with

```
    _POLL_DISCONNECTED = EPOLLHUP
    _POLL_IN = (EPOLLIN | EPOLLERR)
    _POLL_OUT = EPOLLOUT
```

in EPollReactor this will cause the expected behaviour for udp(connectionRefused is called, because host is unreachable), but twisted.test.test_tcp.WriteDataTestCase.test_writeAfterShutdownWithoutReading
fails with:
```
twisted.trial.unittest.FailTest: 
Expected: (<class 'twisted.internet.error.ConnectionLost'>,)
Got:
[Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.
]
```

**Comment by twisted-trac** [comment]
|<img alt="marto1_'s avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_3"></a>|marto1_ commented|
|-|-|

The bug is fixed, I hope on all platforms, unfortunately TCP breaks and returns CONNECTION_DONE instead of CONNECTION_LOST so I had to touch posixbase. Other approach to the problem is to leave EPOLLERR in _POLL_DISCONNECTED events, but inform in some way udp.Port.doRead that this is a special case.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun set owner to @exarkun<br>@exarkun set status to `assigned`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_5"></a>|@exarkun commented|
|-|-|

(In [40128]) Branching to 'epoll-udp-refused-6287'

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_6"></a>|@exarkun commented|
|-|-|

(In [40129]) apply fix-epoll-not-calling-connectionRefused 

refs [#6287](https://github.com/twisted/twisted/issues/6287)

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_7"></a>|@exarkun set owner to marto1_<br>@exarkun set status to `new`|
|-|-|

Thanks.

The big thing I notice when looking at this change is that it doesn't seem right to skip this new test for those three reactors.  It's true that they don't currently support the behavior being tested - but that's because the implementation shares exactly the bug that the epoll reactor has.  Looking more closely, I see that all of these reactors define their "error" condition as part of the "disconnect" set.  They can all be made to work by defining it as part of the "input" set instead.  This suggests that it really might be better to teach `_PollLikeMixin` to treat the "error" condition in a special way.  It does appear the issue can be resolved without adding this special treatment so I don't think this is a requirement to land these changes, just something to consider.

So, instead of skipping all the other poll-like reactors in this new test, I suggest running it against all of them and fixing them all (the fix for all of them is roughly the same, it seems, and only 2 or 3 lines each so this isn't going to explode the size of the changeset).

Here are some other minor issues:

  1. `hasattr` is broken and should essentially never be used.  Also, `_PollLikeMixin` declares explicitly that it 'must' be mixed in to a `PosixReactorBase` subclass.  So this makes `_ContinuousPolling` the offender here.  Maybe the right thing to do is work around this mismatch in `_PollLikeMixin` but if so then the documentation needs to be updated.  In fact, I think the right thing to do _right now_ is to rename the `_ContinuousPolling._readers` attribute so that it agrees with `_PollLikeMixin`'s expectations.  And _later_ perhaps rewriting `_PollLikeMixin` to not be a mixin for `PosixReactorBase` subclasses (ie, make it a helper function that takes some more arguments or do something else with composition) probably makes sense.
  1. The test method needs a docstring
  1. `ReactorBuilder`-style tests do their own cleanup: there's no need to return `port.stopListening()` at the end of the test.
  1. Ideally there would be an assertion in the test somewhere.  I realize it's sometimes difficult to come up with one that makes sense in "does this event happen" tests but it's worth a good try.
  1. There's no guarantee port 8000 will not be accepting udp traffic on the test machine.  An unbound UDP port should be used instead.  You can find one by creating a UDP socket and asked what its port is.
  1. Why does there need to be a `reactor.callLater(0, ...)` in the test?
  1. The news fragment should talk about `twisted.internet.epollreactor` instead of _Epoll reactor_.  Whenever possible, the subject of the fragment should be a Python FQPN so it is unambiguous and easy for people to investigate further.
