### ISSUE TITLE
LookupsTestCase.test_importExceptions failing on python 3.3

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#6298]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)| @thijstriemstra reported|
|-|-|
|Trac ID|trac#6298|
|Type|defect|
|Created|2013-02-12 01:11:14Z|
|Branch|https://github.com/twisted/twisted/tree/import-checkstack-6298|

`test_importExceptions` is failing on Python 3.3 only because [a statement was modified](https://twistedmatrix.com/trac/changeset/37124#file7) to clean up Python 2.3 code which introduced an issue in `test_reflectpy3.LookupsTestCase`. This wasn't caught initially because the buildslave for python 3.3 is down (at the time of this writing).

```
======================================================================
FAIL: test_importExceptions (twisted.python.test.test_reflectpy3.LookupsTestCase)
test_importExceptions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/thijs/workspaces/opensource/software/twisted/svn/Twisted/trunk/twisted/trial/_synctest.py", line 328, in assertRaises
    result = f(*args, **kwargs)
  File "/home/thijs/workspaces/opensource/software/twisted/svn/Twisted/trunk/twisted/python/_reflectpy3.py", line 273, in namedAny
    obj = getattr(obj, n)
AttributeError: 'module' object has no attribute 'reflect_helper_IE'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thijs/workspaces/opensource/software/twisted/svn/Twisted/trunk/twisted/trial/_synctest.py", line 1185, in _run
    runWithWarningsSuppressed(suppress, method)
  File "/home/thijs/workspaces/opensource/software/twisted/svn/Twisted/trunk/twisted/python/util.py", line 1065, in runWithWarningsSuppressed
    return f(*args, **kwargs)
  File "/home/thijs/workspaces/opensource/software/twisted/svn/Twisted/trunk/twisted/python/test/test_reflectpy3.py", line 290, in test_importExceptions
    reflect.namedAny, "twisted.test.reflect_helper_IE")
  File "/home/thijs/workspaces/opensource/software/twisted/svn/Twisted/trunk/twisted/trial/_synctest.py", line 335, in assertRaises
    failure.Failure().getTraceback()))
twisted.trial.unittest.FailTest: <class 'AttributeError'> raised instead of ImportError:
 Traceback (most recent call last):
  File "/home/thijs/workspaces/opensource/software/twisted/svn/Twisted/trunk/twisted/trial/_synctest.py", line 1216, in _runFixturesAndTest
    if self._run(suppress, todo, method, result):
  File "/home/thijs/workspaces/opensource/software/twisted/svn/Twisted/trunk/twisted/trial/_synctest.py", line 1185, in _run
    runWithWarningsSuppressed(suppress, method)
  File "/home/thijs/workspaces/opensource/software/twisted/svn/Twisted/trunk/twisted/python/util.py", line 1065, in runWithWarningsSuppressed
    return f(*args, **kwargs)
  File "/home/thijs/workspaces/opensource/software/twisted/svn/Twisted/trunk/twisted/python/test/test_reflectpy3.py", line 290, in test_importExceptions
    reflect.namedAny, "twisted.test.reflect_helper_IE")
--- <exception caught here> ---
  File "/home/thijs/workspaces/opensource/software/twisted/svn/Twisted/trunk/twisted/trial/_synctest.py", line 328, in assertRaises
    result = f(*args, **kwargs)
  File "/home/thijs/workspaces/opensource/software/twisted/svn/Twisted/trunk/twisted/python/_reflectpy3.py", line 273, in namedAny
    obj = getattr(obj, n)
builtins.AttributeError: 'module' object has no attribute 'reflect_helper_IE'
```

Attachments:

* [reflect-6298.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/a9a/a9abfec1f428ad27c5e83302509541ded06e3b94/51f3a1e1eee97a4b1d699562f7a49c7dbbbabecd.patch) (1082 bytes) - added by thijs on 2013-02-12 01:12:34Z - 

<details><summary>Searchable metadata</summary>

```
trac-id__6298 6298
type__defect defect
reporter__thijs thijs
priority__normal normal
milestone__ 
branch__branches_import_checkstack_6298 branches/import-checkstack-6298
branch_author__thijs thijs
status__closed closed
resolution__duplicate duplicate
component__core core
keywords__ 
time__1360631474000000 1360631474000000
changetime__1361469415000000 1361469415000000
version__None None
owner__ 
cc__thijs
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)|@thijstriemstra set owner to @tomprince|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="tomprince's avatar" src="https://avatars.githubusercontent.com/u/283816?s=50" width="50" height="50">](https://github.com/tomprince)<a name="note_2"></a>|@tomprince removed owner|
|-|-|

This should perhaps have some sort of comment.

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_3"></a>|@thijstriemstra commented|
|-|-|

Let me put that in a branch actually so it can be tested (when the 3.3 buildslave is back up).

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_4"></a>|@thijstriemstra commented|
|-|-|

(In [37125]) Branching to 'import-checkstack-6298'

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_5"></a>|@thijstriemstra commented|
|-|-|

(In [37126]) add note about execName, add news file. refs [#6298](https://github.com/twisted/twisted/issues/6298)

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_6"></a>|@thijstriemstra commented|
|-|-|

Forced a [build](https://buildbot.twistedmatrix.com/boxes-supported?branch=/branches/import-checkstack-6298). Up for review.

**Comment by twisted-trac** [comment]
|[<img alt="tomprince's avatar" src="https://avatars.githubusercontent.com/u/283816?s=50" width="50" height="50">](https://github.com/tomprince)<a name="note_7"></a>|@tomprince commented|
|-|-|

(In [37129]) Revert r37124: LookupsTestCase.test_importExceptions failing on python 3.3

test_importExceptions is failing on Python 3.3 only because  a statement was
modified to clean up Python 2.3 code which introduced an issue in
test_reflectpy3.LookupsTestCase. This wasn't caught initially because the
buildslave for python 3.3 wass down.

======================================================================
FAIL: test_importExceptions (twisted.python.test.test_reflectpy3.LookupsTestCase)
test_importExceptions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "twisted/trial/_synctest.py", line 328, in assertRaises
    result = f(*args, **kwargs)
  File "twisted/python/_reflectpy3.py", line 273, in namedAny
    obj = getattr(obj, n)
AttributeError: 'module' object has no attribute 'reflect_helper_IE'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "twisted/trial/_synctest.py", line 1185, in _run
    runWithWarningsSuppressed(suppress, method)
  File "twisted/python/util.py", line 1065, in runWithWarningsSuppressed
    return f(*args, **kwargs)
  File "twisted/python/test/test_reflectpy3.py", line 290, in test_importExceptions
    reflect.namedAny, "twisted.test.reflect_helper_IE")
  File "software/twisted/svn/Twisted/trunk/twisted/trial/_synctest.py", line 335, in assertRaises
    failure.Failure().getTraceback()))
twisted.trial.unittest.FailTest: <class 'AttributeError'> raised instead of ImportError:
 Traceback (most recent call last):
  File "twisted/trial/_synctest.py", line 1216, in _runFixturesAndTest
    if self._run(suppress, todo, method, result):
  File "twisted/trial/_synctest.py", line 1185, in _run
    runWithWarningsSuppressed(suppress, method)
  File "twisted/python/util.py", line 1065, in runWithWarningsSuppressed
    return f(*args, **kwargs)
  File "twisted/python/test/test_reflectpy3.py", line 290, in test_importExceptions
    reflect.namedAny, "twisted.test.reflect_helper_IE")
--- <exception caught here> ---
  File "twisted/trial/_synctest.py", line 328, in assertRaises
    result = f(*args, **kwargs)
  File "twisted/python/_reflectpy3.py", line 273, in namedAny
    obj = getattr(obj, n)
builtins.AttributeError: 'module' object has no attribute 'reflect_helper_IE'

Reopens: [#5386](https://github.com/twisted/twisted/issues/5386)
Refs: [#6298](https://github.com/twisted/twisted/issues/6298)

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_8"></a>|@thijstriemstra set status to `closed`|
|-|-|

Marking this as a duplicate of [#5386](https://github.com/twisted/twisted/issues/5386) and fixing the issue there.
