### ISSUE TITLE
Python 3 support for twisted.words.protocols.irc

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#6320]
|<img alt="brownan's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| brownan reported|
|-|-|
|Trac ID|trac#6320|
|Type|enhancement|
|Created|2013-02-23 03:49:40Z|
|Branch|https://github.com/twisted/twisted/tree/6320-rodrigc-irc-py3-2|

This ticket is to track the effort on porting the irc module to Python 3.

Attachments:

* [0001-Updated-twisted.words.protocols.irc-to-Python-3.3.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/b9f/b9fb14ee4f7c72916df87d7297e285a4fcfe7f0f/6bd7b51327c86c9051bb764ea069598c858e6e95.patch) (165889 bytes) - added by brownan on 2013-03-03 15:44:43Z - 

<details><summary>Searchable metadata</summary>

```
trac-id__6320 6320
type__enhancement enhancement
reporter__brownan brownan
priority__normal normal
milestone__Python_3_x Python-3.x
branch__6320_rodrigc_irc_py3_2 6320-rodrigc-irc-py3-2
branch_author__ 
status__closed closed
resolution__wontfix wontfix
component__words words
keywords__None None
time__1361591380000000 1361591380000000
changetime__1526073612583821 1526073612583821
version__None None
owner__rodrigc rodrigc
cc__ralphm
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="brownan's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_2"></a>|brownan commented|
|-|-|

Patch added for the update to python 3.3

All tests pass on Python 3.3. All trial tests pass on Python 2.6 and
2.7.

I added string encoding/decoding to the boundries between the protocol
objects and their underlying Protocol/LineReceiver objects. Encoding defaults to
ASCII. Text strings are used everywhere else within the module.

**Comment by twisted-trac** [comment]
|<img alt="brownan's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_3"></a>|brownan commented|
|-|-|

sumbitted for review

**Comment by twisted-trac** [comment]
|<img alt="brownan's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_4"></a>|brownan commented|
|-|-|

It's been pointed out to me that it's more compatible to leave these APIs as handling byte strings instead of converting them to unicode. I'm going to go back and change all the API calls and internal strings to byte strings.

**Comment by twisted-trac** [comment]
|<img alt="brownan's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_5"></a>|brownan commented|
|-|-|

So I'm making another attempt at porting this module, starting pretty much from scratch, with the premise being all internal strings and interfaces are to remain bytestrings, as per the suggestions I received on IRC. I want to raise some issues here about the problems I'm running into and the decisions that still have to be made.

First, I strongly feel that the interface the IRC protocol objects expose should be text strings. They shourd not expose a byte interface to applications. It makes sense to do the encoding at the protocol layer. This is my opinion, and I understand if a different decision may be made for e.g. backwards compatability, but I want to point out that if the protocol APIs take only byte strings, applications will have to take that burdon, and they will have to wrap every call they make to encode outgoing strings and decode incoming strings on every method. There is no one good place to do encoding/decoding otherwise.

Second, handling text strings internally greatly simplifies the implementation, mostly due to byte strings lacking string formatting, which is used extensively througout the module.

Third, I noticed the docstrings for some of the methods specifically say they take both str and unicode strings. So if the thought was to avoid any and all API changes as well as string encoding/decoding within the protocol implementation, then there is a conflict. I, of course, vote to have the API take text (unicode) and handle the encoding in the protocol object for the above reasons.

Fourth, if the API were changed to bytes-only, applications that used the default string will now be using unicode text, forcing applications to change all their strings from ".." to b".."

I have already made a few changes to the module that fix incompatible syntax and such, and I can go ahead and submit those patches if appropriate, but I want to find a consesus on the above issues before I move forward any further so I don't end up wasting my time and effort (again).

**Comment by twisted-trac** [comment]
|<img alt="brownan's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_6"></a>|brownan commented|
|-|-|

After some more feedback on IRC, I'm withdrawing this ticket from review. It's probably a better use of mine (or someone else's) time to add unicode support to the IRCClient module and _then_ port it to python 3.

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_7"></a>|@rodrigc commented|
|-|-|

This is a completely new port of the IRC module to Python 3:

https://github.com/twisted/twisted/pull/534

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_8"></a>|@glyph set owner to @rodrigc|
|-|-|

Github review is here: https://github.com/twisted/twisted/pull/534#pullrequestreview-1096699

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)|@rodrigc removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_10"></a>|@rodrigc commented|
|-|-|

Updated patch: https://github.com/twisted/twisted/pull/534

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_11"></a>|@rodrigc commented|
|-|-|

Updated patch: https://github.com/twisted/twisted/pull/561

**Comment by twisted-trac** [comment]
|[<img alt="acabhishek942's avatar" src="https://avatars.githubusercontent.com/u/7778186?s=50" width="50" height="50">](https://github.com/acabhishek942)<a name="note_12"></a>|@acabhishek942 commented|
|-|-|

I think this patch is almost there. I have two concerns 

The helper function assertEqualBufferValue could be changed to return decoded string and then use assertEqual for comparing equality. I believe this is a better approach for understanding purposes, but better to get glyph's approach on this.

There is a second occurrence of buffer declared as string in t.words.protocols.irc which is not converted to bytes specifically this commit[https://github.com/twisted/twisted/pull/561/commits/8207abb3ce0d91e2187afd38d13042497e24decd]. I don't understand why that is not required.

**Comment by twisted-trac** [comment]
|[<img alt="acabhishek942's avatar" src="https://avatars.githubusercontent.com/u/7778186?s=50" width="50" height="50">](https://github.com/acabhishek942)|@acabhishek942 set owner to @rodrigc|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_14"></a>|@rodrigc commented|
|-|-|

The buffer inside class DccChat must be bytes, because DccChat is a basicLineReceiver:

```
class DccChat(basic.LineReceiver, styles.Ephemeral):
```

and LineReceiver deals with bytes.


The other buffer inside class IRC must be a native string, because native string is used in
hundreds of places in the IRC code.  The IRC.sendLine function encodes as bytes just before
sending data over the wire.  This strategy for working with Unicode in Python  has been termed the "unicode sandwich" by Ned Batchelder ( http://nedbatchelder.com/text/unipain/unipain.html ), where unicode is used throughout the code,
and conversion to bytes only occurs at the "boundaries" where data is sent over the wire or received from the wire.

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_15"></a>|@rodrigc set status to `closed`|
|-|-|

In changeset 48dfa7756c8bf0221658eba814f7c5ce36396310
```
#!CommitTicketReference repository="" revision="48dfa7756c8bf0221658eba814f7c5ce36396310"
Merge pull request #561 from twisted/6320-rodrigc-irc-py3-2

Author: rodrigc
Reviewer: acabhishek942
Fixes: #6320

Port twisted.words.protocols.irc to Python 3
```

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_16"></a>|@markrwilliams set status to `reopened`|
|-|-|

Words' IRC client fails internally under Python 3 ([#6320](https://github.com/twisted/twisted/issues/6320)) because it
attempts to decode all incoming data as utf-8.  While the protocol
appears to be ASCII, RFC1459 does not specify an encoding for the
contents of PRIVMSGs or channel topics.  I ran a naive a survey of the
10 most popular networks, as found here:

http://irc.netsplit.de/networks/top100.php

And found that ~10% of PRIVMSGs and channel topics were in latin 1
(according to chardet, at least).  The code for my survey is here:

https://github.com/markrwilliams/encodingcollector/

(Note that is incredibly impolite and will get you banned from most
networks.)

Here's what the problem looks like in practice.  The following script
prints all the channels on a popular Italian IRC server:

```python
from twisted.internet import defer, endpoints, task
from twisted.words.protocols import irc


class ListBot(irc.IRCClient):
    nickname = "nothing"

    def __init__(self, done):
        self._done = done

    def signedOn(self):
        self.sendLine("LIST")

    def irc_RPL_LIST(self, prefix, params):
        print(prefix, params)

    def irc_RPL_LISTEND(self, prefix, params):
        self.transport.loseConnection()
        self._done.callback(None)


@task.react
def main(reactor):
    transport = endpoints.clientFromString(reactor, 'tcp:irc.chlame.net:6667')
    end = defer.Deferred()
    start = endpoints.connectProtocol(transport, ListBot(end))
    start.addCallback(lambda _: end)
    return start
```


Under Python 2, it will print successfully and then terminate, while under
Python 3, it will encounter the following exception and hang:

```
Unhandled Error
Traceback (most recent call last):
  File "/path/to/twisted/src/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/path/to/twisted/src/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/path/to/twisted/src/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/path/to/twisted/src/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/path/to/twisted/src/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()
  File "/path/to/twisted/src/twisted/internet/tcp.py", line 208, in doRead
    return self._dataReceived(data)
  File "/path/to/twisted/src/twisted/internet/tcp.py", line 214, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/path/to/twisted/src/twisted/internet/endpoints.py", line 116, in dataReceived
    return self._wrappedProtocol.dataReceived(data)
  File "/path/to/twisted/src/twisted/words/protocols/irc.py", line 2631, in dataReceived
    basic.LineReceiver.dataReceived(self, data)
  File "/path/to/twisted/src/twisted/protocols/basic.py", line 571, in dataReceived
    why = self.lineReceived(line)
  File "/path/to/twisted/src/twisted/words/protocols/irc.py", line 2637, in lineReceived
    line = line.decode("utf-8")
builtins.UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position 51: invalid continuation byte
```

A user cannot register an errback to handle this because the exception
occurs as a result of a read event.  They also can't write code that
doesn't encounter this exception without monkeypatching Twisted.

Additionally all length checks are wrong because they operate on native
strings prior to encoding.  This method might under-calculate the length
of a line:

https://github.com/twisted/twisted/blob/trunk/src/twisted/words/protocols/irc.py#L1687-L1707

...because `u'\u2022' * 200` would appear to be only 200 characters, when
in fact it will be 600 on the wire (`len((u'\u2022' * 200).encode('utf-8'))`)

These issues prevent IRCClient from functioning under Python 3 and need
to be addressed before the port is released.

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_17"></a>|@markrwilliams set status to `closed`|
|-|-|

The change was merged without addressing the issues described.

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_18"></a>|@markrwilliams commented|
|-|-|

See [#9443](https://github.com/twisted/twisted/issues/9443) and [#9444](https://github.com/twisted/twisted/issues/9444).
