### ISSUE TITLE
trial can't run stdlib unittest test methods with expected failures

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#6345]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#6345|
|Type|defect|
|Created|2013-03-02 23:34:20Z|

From the Python stdlib unittest module documentation:

```
import unittest

class ExpectedFailureTestCase(unittest.TestCase):
    @unittest.expectedFailure
    def test_fail(self):
        self.assertEqual(1, 0, "broken")
```

trial should be able to run this, but instead it fails with an unhandled exception:

```
$ trial test_xfail.py 
test_xfail
  ExpectedFailureTestCase
    test_fail ... Traceback (most recent call last):
  File "/usr/bin/trial", line 18, in <module>
    run()
  File "/usr/lib/python2.7/dist-packages/twisted/scripts/trial.py", line 382, in run
    test_result = trialRunner.run(suite)
  File "/usr/lib/python2.7/dist-packages/twisted/trial/runner.py", line 809, in run
    return self._runWithoutDecoration(test)
  File "/usr/lib/python2.7/dist-packages/twisted/trial/runner.py", line 838, in _runWithoutDecoration
    run()
  File "/usr/lib/python2.7/dist-packages/twisted/trial/runner.py", line 833, in <lambda>
    run = lambda: suite.run(result)
  File "/usr/lib/python2.7/dist-packages/twisted/trial/runner.py", line 284, in run
    TestSuite.run(self, result)
  File "/usr/lib/python2.7/dist-packages/twisted/trial/unittest.py", line 1413, in run
    test(result)
  File "/usr/lib/python2.7/dist-packages/twisted/trial/unittest.py", line 1401, in __call__
    return self.run(result)
  File "/usr/lib/python2.7/dist-packages/twisted/trial/runner.py", line 179, in run
    super(LoggedSuite, self).run(result)
  File "/usr/lib/python2.7/dist-packages/twisted/trial/unittest.py", line 1413, in run
    test(result)
  File "/usr/lib/python2.7/dist-packages/twisted/trial/unittest.py", line 1401, in __call__
    return self.run(result)
  File "/usr/lib/python2.7/dist-packages/twisted/trial/runner.py", line 152, in run
    test(result)
  File "/usr/lib/python2.7/dist-packages/twisted/trial/unittest.py", line 1401, in __call__
    return self.run(result)
  File "/usr/lib/python2.7/dist-packages/twisted/trial/runner.py", line 152, in run
    test(result)
  File "/usr/lib/python2.7/dist-packages/twisted/trial/unittest.py", line 1401, in __call__
    return self.run(result)
  File "/usr/lib/python2.7/dist-packages/twisted/trial/runner.py", line 152, in run
    test(result)
  File "/usr/lib/python2.7/dist-packages/twisted/trial/unittest.py", line 1436, in __call__
    return self.run(result)
  File "/usr/lib/python2.7/dist-packages/twisted/trial/unittest.py", line 1446, in run
    reporter._AdaptedReporter(result, self.__class__))
  File "/usr/lib/python2.7/unittest/case.py", line 335, in run
    addExpectedFailure(self, e.exc_info)
TypeError: addExpectedFailure() takes exactly 4 arguments (3 given)
```

This is probably because trial's `addExpectedFailure` `TestResult` API is incompatible with that of the standard library.

<details><summary>Searchable metadata</summary>

```
trac-id__6345 6345
type__defect defect
reporter__exarkun exarkun
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__duplicate duplicate
component__trial trial
keywords__ 
time__1362267260000000 1362267260000000
changetime__1366515486000000 1366515486000000
version__None None
owner__ 
cc__jml
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="Julian's avatar" src="https://avatars.githubusercontent.com/u/329822?s=50" width="50" height="50">](https://github.com/Julian)<a name="note_2"></a>|@Julian commented|
|-|-|

[#4596](https://github.com/twisted/twisted/issues/4596) was closed as being similar-y to this.

**Comment by twisted-trac** [comment]
|[<img alt="Julian's avatar" src="https://avatars.githubusercontent.com/u/329822?s=50" width="50" height="50">](https://github.com/Julian)<a name="note_3"></a>|@Julian set status to `closed`|
|-|-|

Duplicate of [#4811](https://github.com/twisted/twisted/issues/4811)
