### ISSUE TITLE
new epoll error after migrating from 10.0 to 12.3 (no app code changes)

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#6346]
|<img alt="alecm3's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| alecm3 reported|
|-|-|
|Trac ID|trac#6346|
|Type|defect|
|Created|2013-03-03 17:50:44Z|

I had 60 busy tcp servers that ran on Python 2.6/Twisted 10.0 (and Twisted
9.0) for over two years with not problems. After I upgraded to Twisted
12.3/Python 2.7, I started getting the errors below (no application code
changes). It took about two days for the first error to appear on a busy
server under heavy load:

```
[twisted.internet.protocol.ServerFactory] Unhandled Error
        Traceback (most recent call last):
          File
"/usr/local/encap/Python-2.7.3/lib/python2.7/site-packages/twisted/python/lo
g.py", line 73, in callWithCon
text
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File
"/usr/local/encap/Python-2.7.3/lib/python2.7/site-packages/twisted/python/co
ntext.py", line 118, in callWi
thContext
            return self.currentContext().callWithContext(ctx, func, *args,
**kw)
          File
"/usr/local/encap/Python-2.7.3/lib/python2.7/site-packages/twisted/python/co
ntext.py", line 81, in callWit
hContext
            return func(*args,**kw)
          File
"/usr/local/encap/Python-2.7.3/lib/python2.7/site-packages/twisted/internet/
posixbase.py", line 614, in _d
oReadOrWrite
            why = selectable.doRead()
        --- <exception caught here> ---
          File
"/usr/local/encap/Python-2.7.3/lib/python2.7/site-packages/twisted/internet/
tcp.py", line 1069, in doRead
            transport = self.transport(skt, protocol, addr, self, s,
self.reactor)
          File
"/usr/local/encap/Python-2.7.3/lib/python2.7/site-packages/twisted/internet/
tcp.py", line 786, in __init__
            self.startReading()
          File
"/usr/local/encap/Python-2.7.3/lib/python2.7/site-packages/twisted/internet/
abstract.py", line 429, in sta
rtReading
            self.reactor.addReader(self)
          File
"/usr/local/encap/Python-2.7.3/lib/python2.7/site-packages/twisted/internet/
epollreactor.py", line 256, in
 addReader
            _epoll.EPOLLIN, _epoll.EPOLLOUT)
          File
"/usr/local/encap/Python-2.7.3/lib/python2.7/site-packages/twisted/internet/
epollreactor.py", line 240, in
 _add
            self._poller.modify(fd, flags)
        exceptions.IOError: [Errno 2] No such file or directory
```

After the error occurs, the server usually starts printing 100s of this errors in the log per minute, until it is restarted. On average, a busy server enters this state every 72 hours.

Apparently I am not the only one who has encountered this:
http://stackoverflow.com/questions/12600137/twisted-internet-epollreactor-py-line-238-in-add

<details><summary>Searchable metadata</summary>

```
trac-id__6346 6346
type__defect defect
reporter__alecm3 alecm3
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__ 
time__1362333044000000 1362333044000000
changetime__1365962552000000 1365962552000000
version__None None
owner__itamar itamar
cc__alecm3 cc__dynamicgl
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

Fixing description markup.  Removing from milestone as well.  Milestones indicate what Twisted version a bug must be fixed for.  Since 12.3 has been released already, this cannot possibly be fixed for that version of Twisted.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_2"></a>|@exarkun commented|
|-|-|

Unfortunately, this will be hard to fix without additional information.  It would be very helpful if you provided an example which reproduces the problem.

Additionally, it would be useful to know if it is the Python upgrade that causes the problem (and what exact versions of Python are involved - are you using an OS package, a custom build, what is the point release, etc), or if only upgrading Twisted (without upgrading Python) is enough to cause the problem.  Also, narrowing down the Twisted versions involved would help - is it 12.2 to 12.3 that causes the problem?  12.1 to 12.2?  etc

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)<a name="note_3"></a>|@itamarst commented|
|-|-|

Looking at the traceback itself, the failure is occurring with a newly accept()ed connection that is being added as a reader... and yet the epoll reactor is trying to _modify_ the settings. I.e. the file descriptor is already registered as a writer somehow as far as the reactor is concerned. However, the kernel does not agree (Python docs say "Attempting to modify a file descriptor that was never registered causes an IOError exception with errno ENOENT to be raised.")

Presumably a file descriptor N was disconnected, but never removed from epoll's writer list. Later, a new socket the same fd number N, which is when this exception occurred. So the real question is, perhaps, why the fd was not removed from the writers set.

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)<a name="note_4"></a>|@itamarst commented|
|-|-|

Replying to [itamar](#note_3):
> Presumably a file descriptor N was disconnected, but never removed from epoll's writer list.

Or rather, never removed from the _reactor's_ writer list. It was removed from the kernel.

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)<a name="note_5"></a>|@itamarst commented|
|-|-|

Hm. I misread the docs, the epoll docs don't specify ENOENT on modifying unknown fd. The behavior is the same, though, so the analysis stands:

```
>>> import select
>>> poller = select.epoll()
>>> poller.modify(1, select.EPOLLIN)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
IOError: [Errno 2] No such file or directory
```

**Comment by twisted-trac** [comment]
|<img alt="alecm3's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_6"></a>|alecm3 commented|
|-|-|

>Also, narrowing down the Twisted versions involved would help - is it 12.2 to 12.3 that causes the problem? 12.1 to 12.2? etc


```
root@serv6:~# cat /etc/issue
Ubuntu 8.04.4 LTS \n \l
```


```
root@serv6:~# python --version
Python 2.7.3
```
(Custom compiled- although I believe the person who reported it on Stackoverflow used Ubuntu's standard python)

I am happy to try earlier twisted version, but I have a limited number of attempts on a live system before I receive complaints. Can you suggest a version before 12.3, after which significant changes were made to epoll handling? 

Not sure about reproducing it with synthetic load just yet.

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)<a name="note_7"></a>|@itamarst commented|
|-|-|

At a minimum you should try 12.0; 12.1 appears to be when a number of major changes were introduced to epoll (workaround for filesystem files, support for Python's built-in epoll). If that still exhibits the problem we can try to track it down further in the past.

**Comment by twisted-trac** [comment]
|<img alt="alecm3's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_8"></a>|alecm3 commented|
|-|-|

Python 2.7.3/Twisted 10.2 has no errors, so the problem is in Twisted 10.2->12.2 upgrade, not in the Python 2.6->2.7 upgrade. I will try 12.0 next.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_9"></a>|@exarkun commented|
|-|-|

One change in 12.1 was to start using the stdlib epoll bindings instead of our own.  It would be interesting to know if 12.1 is the version where things first start to go wrong, or if disabling use of the stdlib epoll bindings makes any difference.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_10"></a>|@exarkun commented|
|-|-|

Although therve raises the point that another change made in 12.1 was to make epoll the default reactor, whereas previously it was select.  Were you using epoll before?

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)<a name="note_11"></a>|@itamarst commented|
|-|-|

More questions:

 1. What transports do you use (TCP, SSL, UDP, processes, etc.)?
 1. Client or server?
 1. What methods do you call on those transports? (write(), loseConnection(), etc.).

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_12"></a>|@exarkun commented|
|-|-|

4. Does your application close file descriptors the reactor is monitoring without using a Twisted API to do so?  (Can you completely rule out the possibility of this being done in any of the other libraries you're using?)

**Comment by twisted-trac** [comment]
|<img alt="alecm3's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_13"></a>|alecm3 commented|
|-|-|

I have some new data now:

I reverted to Python 2.7/Twisted 10.2 combination 10 days ago, and suddenly I got these errors after 10 days of stable no-error operations (the logs are flooded again):

2013-03-14 14:57:41-0700 [twisted.internet.protocol.ServerFactory] Unhandled Error
        Traceback (most recent call last):
          File "/usr/local/encap/Python-2.7.3/lib/python2.7/site-packages/Twisted-10.2.0-py2.7-linux-x86_64.egg/twisted/python/log.py", line 69, in callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File "/usr/local/encap/Python-2.7.3/lib/python2.7/site-packages/Twisted-10.2.0-py2.7-linux-x86_64.egg/twisted/python/context.py", line 59, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/usr/local/encap/Python-2.7.3/lib/python2.7/site-packages/Twisted-10.2.0-py2.7-linux-x86_64.egg/twisted/python/context.py", line 37, in callWithContext
            return func(*args,**kw)
          File "/usr/local/encap/Python-2.7.3/lib/python2.7/site-packages/Twisted-10.2.0-py2.7-linux-x86_64.egg/twisted/internet/epollreactor.py", line 217, in _doReadOrWrite
            why = selectable.doRead()
        --- <exception caught here> ---
          File "/usr/local/encap/Python-2.7.3/lib/python2.7/site-packages/Twisted-10.2.0-py2.7-linux-x86_64.egg/twisted/internet/tcp.py", line 938, in doRead
            transport = self.transport(skt, protocol, addr, self, s, self.reactor)
          File "/usr/local/encap/Python-2.7.3/lib/python2.7/site-packages/Twisted-10.2.0-py2.7-linux-x86_64.egg/twisted/internet/tcp.py", line 752, in __init__
            self.startReading()
          File "/usr/local/encap/Python-2.7.3/lib/python2.7/site-packages/Twisted-10.2.0-py2.7-linux-x86_64.egg/twisted/internet/abstract.py", line 365, in startReading
            self.reactor.addReader(self)
          File "/usr/local/encap/Python-2.7.3/lib/python2.7/site-packages/Twisted-10.2.0-py2.7-linux-x86_64.egg/twisted/internet/epollreactor.py", line 100, in addReader
            self._add(reader, self._reads, self._writes, self._selectables, _epoll.IN, _epoll.OUT)
          File "/usr/local/encap/Python-2.7.3/lib/python2.7/site-packages/Twisted-10.2.0-py2.7-linux-x86_64.egg/twisted/internet/epollreactor.py", line 88, in _add
            self._poller._control(cmd, fd, flags)
          File "_epoll.pyx", line 125, in _epoll.epoll._control

I have never seen this with Python 2.6/10.0 (never as in two years).

Answering the questions from above:
>What transports do you use (TCP, SSL, UDP, processes, etc.)?
1. Using TCP, UDP transports
>Client or server?
2. Server
>What methods do you call on those transports? (write(), loseConnection(), etc.).
3. The protocol inherits from twisted.protocols.basic.LineOnlyReceiver and twisted.protocols.policies.TimeoutMixin. I am using transport.write(), transport.loseConnection() and lineReceived(), connectionMade(), connectionLost(), timeoutConnection()
>Does your application close file descriptors the reactor is monitoring without using a Twisted API to do so? (Can you completely rule out the possibility of this being done in any of the other libraries you're using?)
4. I never close file descriptors outside of Twisted API (and I am not really using any extensions).

Are there any changes in epoll between Twisted 10.0 and 10.2? Or is this likely a change from Python 2.6 to 2.7?

**Comment by twisted-trac** [comment]
|<img alt="alecm3's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_14"></a>|alecm3 commented|
|-|-|

Sorry, the full error got cut off in the message above:


```
2013-03-14 15:19:19-0700 [twisted.internet.protocol.ServerFactory] Unhandled Error
        Traceback (most recent call last):
          File "/usr/local/encap/Python-2.7.3/lib/python2.7/site-packages/Twisted-10.2.0-py2.7-linux-x86_64.egg/twisted/python/log.py", line 69, in callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File "/usr/local/encap/Python-2.7.3/lib/python2.7/site-packages/Twisted-10.2.0-py2.7-linux-x86_64.egg/twisted/python/context.py", line 59, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/usr/local/encap/Python-2.7.3/lib/python2.7/site-packages/Twisted-10.2.0-py2.7-linux-x86_64.egg/twisted/python/context.py", line 37, in callWithContext
            return func(*args,**kw)
          File "/usr/local/encap/Python-2.7.3/lib/python2.7/site-packages/Twisted-10.2.0-py2.7-linux-x86_64.egg/twisted/internet/epollreactor.py", line 217, in _doReadOrWrite
            why = selectable.doRead()
        --- <exception caught here> ---
          File "/usr/local/encap/Python-2.7.3/lib/python2.7/site-packages/Twisted-10.2.0-py2.7-linux-x86_64.egg/twisted/internet/tcp.py", line 938, in doRead
            transport = self.transport(skt, protocol, addr, self, s, self.reactor)
          File "/usr/local/encap/Python-2.7.3/lib/python2.7/site-packages/Twisted-10.2.0-py2.7-linux-x86_64.egg/twisted/internet/tcp.py", line 752, in __init__
            self.startReading()
          File "/usr/local/encap/Python-2.7.3/lib/python2.7/site-packages/Twisted-10.2.0-py2.7-linux-x86_64.egg/twisted/internet/abstract.py", line 365, in startReading
            self.reactor.addReader(self)
          File "/usr/local/encap/Python-2.7.3/lib/python2.7/site-packages/Twisted-10.2.0-py2.7-linux-x86_64.egg/twisted/internet/epollreactor.py", line 100, in addReader
            self._add(reader, self._reads, self._writes, self._selectables, _epoll.IN, _epoll.OUT)
          File "/usr/local/encap/Python-2.7.3/lib/python2.7/site-packages/Twisted-10.2.0-py2.7-linux-x86_64.egg/twisted/internet/epollreactor.py", line 88, in _add
            self._poller._control(cmd, fd, flags)
          File "_epoll.pyx", line 125, in _epoll.epoll._control
            
        exceptions.IOError: [Errno 2] No such file or directory

2013-03-14 15:19:19-0700 [twisted.internet.protocol.ServerFactory] Unhandled Error
        Traceback (most recent call last):
          File "/usr/local/encap/Python-2.7.3/lib/python2.7/site-packages/Twisted-10.2.0-py2.7-linux-x86_64.egg/twisted/python/log.py", line 69, in callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File "/usr/local/encap/Python-2.7.3/lib/python2.7/site-packages/Twisted-10.2.0-py2.7-linux-x86_64.egg/twisted/python/context.py", line 59, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/usr/local/encap/Python-2.7.3/lib/python2.7/site-packages/Twisted-10.2.0-py2.7-linux-x86_64.egg/twisted/python/context.py", line 37, in callWithContext
            return func(*args,**kw)
          File "/usr/local/encap/Python-2.7.3/lib/python2.7/site-packages/Twisted-10.2.0-py2.7-linux-x86_64.egg/twisted/internet/epollreactor.py", line 217, in _doReadOrWrite
            why = selectable.doRead()
        --- <exception caught here> ---
          File "/usr/local/encap/Python-2.7.3/lib/python2.7/site-packages/Twisted-10.2.0-py2.7-linux-x86_64.egg/twisted/internet/tcp.py", line 938, in doRead
            transport = self.transport(skt, protocol, addr, self, s, self.reactor)
          File "/usr/local/encap/Python-2.7.3/lib/python2.7/site-packages/Twisted-10.2.0-py2.7-linux-x86_64.egg/twisted/internet/tcp.py", line 752, in __init__
            self.startReading()
          File "/usr/local/encap/Python-2.7.3/lib/python2.7/site-packages/Twisted-10.2.0-py2.7-linux-x86_64.egg/twisted/internet/abstract.py", line 365, in startReading
            self.reactor.addReader(self)
          File "/usr/local/encap/Python-2.7.3/lib/python2.7/site-packages/Twisted-10.2.0-py2.7-linux-x86_64.egg/twisted/internet/epollreactor.py", line 100, in addReader
            self._add(reader, self._reads, self._writes, self._selectables, _epoll.IN, _epoll.OUT)
          File "/usr/local/encap/Python-2.7.3/lib/python2.7/site-packages/Twisted-10.2.0-py2.7-linux-x86_64.egg/twisted/internet/epollreactor.py", line 88, in _add
            self._poller._control(cmd, fd, flags)
          File "_epoll.pyx", line 125, in _epoll.epoll._control
            
        exceptions.IOError: [Errno 2] No such file or directory
```

**Comment by twisted-trac** [comment]
|<img alt="alecm3's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_16"></a>|alecm3 commented|
|-|-|

Sorry I missed your questions since I did not know how to subscribe to the bug until now, and I have not checked the bug URL. 
>Although therve raises the point that another change made in 12.1 was to make epoll the default reactor, whereas previously it was select. Were you using epoll before?

We hhave been using epoll only in the last 3 years

```
/usr/local/bin/twistd --reactor=epoll
```

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)<a name="note_17"></a>|@itamarst set owner to @itamarst|
|-|-|

That last traceback suggests the bug has been there for a while, yes.

While I still have no idea what causes this, I have a test manually reproducing the issue. This will allow me to test workarounds, at least.

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)<a name="note_18"></a>|@itamarst commented|
|-|-|

I opened [#6373](https://github.com/twisted/twisted/issues/6373) for a workaround, this ticket will still cover fixing the original issue that necessitates the workaround.
