### ISSUE TITLE
running the tests with PyCrypto installed, but without pyasn1, results in confusing failures

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#6376]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)| @glyph reported|
|-|-|
|Trac ID|trac#6376|
|Type|defect|
|Created|2013-03-18 06:53:13Z|

`trial --without-module=pyasn1 twisted` results in this:

```
[ERROR]
Traceback (most recent call last):
  File ".../twisted/plugin.py", line 213, in getPlugins
    adapted = interface(plugin, None)
  File ".../zope/interface/interface.py", line 494, in _call_conform
    return conform(self)
  File ".../twisted/plugin.py", line 68, in __conform__
    return self.load()
  File ".../twisted/plugin.py", line 63, in load
    return namedAny(self.dropin.moduleName + '.' + self.name)
  File ".../twisted/python/_reflectpy3.py", line 279, in namedAny
    obj = getattr(obj, n)
exceptions.AttributeError: 'module' object has no attribute 'theSSHKeyCheckerFactory'

twisted.test.test_strcred.TestAnonymousChecker.testAnonymousAccessSucceeds
twisted.test.test_strcred.TestAnonymousChecker.test_isChecker
twisted.test.test_strcred.TestCheckerOptions.test_createsDictionary
twisted.test.test_strcred.TestCheckerOptions.test_credInterfacesProvidesLists
twisted.test.test_strcred.TestCheckerOptions.test_listDoesNotDisplayDuplicates
twisted.test.test_strcred.TestCheckerOptions.test_displaysListCorrectly
twisted.test.test_strcred.TestCheckerOptions.test_displaysListCorrectly
twisted.test.test_strcred.TestCheckerOptions.test_displaysListCorrectly
twisted.test.test_strcred.TestCheckerOptions.test_invalidAuthError
twisted.test.test_strcred.TestCheckerOptions.test_invalidAuthError
twisted.test.test_strcred.TestCheckerOptions.test_invalidAuthError
twisted.test.test_strcred.TestLimitingInterfaces.test_helpAuthLimitsOutput
twisted.test.test_strcred.TestLimitingInterfaces.test_helpAuthTypeLimitsOutput
twisted.test.test_strcred.TestLimitingInterfaces.test_helpAuthTypeLimitsOutput
twisted.test.test_strcred.TestLimitingInterfaces.test_unsupportedInterfaceError
twisted.test.test_strcred.TestPublicAPI.test_emptyDescription
twisted.test.test_strcred.TestPublicAPI.test_emptyDescription
twisted.test.test_strcred.TestPublicAPI.test_emptyDescription
twisted.test.test_strcred.TestPublicAPI.test_invalidAuthType
twisted.test.test_strcred.TestPublicAPI.test_invalidAuthType
twisted.test.test_strcred.TestPublicAPI.test_invalidAuthType
twisted.test.test_strcred.TestUnixChecker.test_isChecker
twisted.test.test_strcred.TestStrcredFunctions.test_findCheckerFactories
twisted.test.test_strcred.TestStrcredFunctions.test_findCheckerFactories
```

<details><summary>Searchable metadata</summary>

```
trac-id__6376 6376
type__defect defect
reporter__glyph glyph
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__duplicate duplicate
component__core core
keywords__ 
time__1363589593000000 1363589593000000
changetime__1364142193000000 1364142193000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_1"></a>|@thijstriemstra commented|
|-|-|

This looks like a duplicate of [#5805](https://github.com/twisted/twisted/issues/5805) (that has almost exactly the same failing tests).

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_2"></a>|@exarkun set status to `closed`|
|-|-|

Looks like it.  The problem  described here also only arises after dropin.cache has been written to reflect pyasn1 (or pycrypto) is available.
