### ISSUE TITLE
Py3: Data must not be unicode

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#6422]
|<img alt="Nothing4You's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| Nothing4You reported|
|-|-|
|Trac ID|trac#6422|
|Type|defect|
|Created|2013-04-10 07:00:33Z|

Hey there,

I just installed the latest version of twisted via SVN and i'm running python 3.3.1 on my system.

I just tried these examples (changed 'print "str"' to 'print("str")' for py3 compatibility) http://twistedmatrix.com/documents/current/core/examples/simpleserv.py with http://twistedmatrix.com/documents/current/core/examples/simpleclient.py and got the following error:

$ python simpleclient.py 
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python3.3/site-packages/twisted/python/log.py", line 88, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/lib/python3.3/site-packages/twisted/python/log.py", line 73, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/lib/python3.3/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python3.3/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python3.3/site-packages/twisted/internet/posixbase.py", line 619, in _doReadOrWrite
    why = selectable.doWrite()
  File "/usr/lib/python3.3/site-packages/twisted/internet/tcp.py", line 593, in doConnect
    self._connectDone()
  File "/usr/lib/python3.3/site-packages/twisted/internet/tcp.py", line 612, in _connectDone
    self.protocol.makeConnection(self)
  File "/usr/lib/python3.3/site-packages/twisted/internet/protocol.py", line 481, in makeConnection
    self.connectionMade()
  File "simpleclient.py", line 19, in connectionMade
    self.transport.write("hello, world!")
  File "/usr/lib/python3.3/site-packages/twisted/internet/_newtls.py", line 191, in write
    FileDescriptor.write(self, bytes)
  File "/usr/lib/python3.3/site-packages/twisted/internet/abstract.py", line 343, in write
    raise TypeError("Data must not be unicode")
builtins.TypeError: Data must not be unicode
connection lost
Connection lost - goodbye!

This works fine with python 2, just python3 is broken.

<details><summary>Searchable metadata</summary>

```
trac-id__6422 6422
type__defect defect
reporter__Nothing4You Nothing4You
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__invalid invalid
component__core core
keywords__python3_unicode python3 unicode
time__1365577233000000 1365577233000000
changetime__1365580962000000 1365580962000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|<img alt="Nothing4You's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_1"></a>|Nothing4You set status to `closed`|
|-|-|

Had to give 'transport.write()' a byte string, not an unicode string.
