### ISSUE TITLE
trial -j breaks if passing unicode as _why argument to log.err

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#6516]
|[<img alt="radix's avatar" src="https://avatars.githubusercontent.com/u/227068?s=50" width="50" height="50">](https://github.com/radix)| @radix reported|
|-|-|
|Trac ID|trac#6516|
|Type|defect|
|Created|2013-05-16 04:01:49Z|

The following example

```
from twisted.trial.unittest import TestCase
from twisted.python import log
class Foo(TestCase):
    def test_foo(self):
        log.err(Exception(), u"hey!")
```

will cause "trial -j" to break:

```
[ERROR]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 210, in msg
    self.observers[i](actualEventDict)
  File "/usr/lib/python2.7/dist-packages/twisted/trial/_dist/workertrial.py", line 47, in emit
    self.protocol.callRemote(managercommands.TestWrite, out=text)
  File "/usr/lib/python2.7/dist-packages/twisted/protocols/amp.py", line 823, in callRemote
    return co._doCommand(self)
  File "/usr/lib/python2.7/dist-packages/twisted/protocols/amp.py", line 1780, in _doCommand
    self.requiresAnswer)
  File "/usr/lib/python2.7/dist-packages/twisted/protocols/amp.py", line 754, in _sendBoxCommand
    box._sendTo(self.boxSender)
  File "/usr/lib/python2.7/dist-packages/twisted/protocols/amp.py", line 579, in _sendTo
    proto.sendBox(self)
  File "/usr/lib/python2.7/dist-packages/twisted/protocols/amp.py", line 2155, in sendBox
    self.transport.write(box.serialize())
  File "/usr/lib/python2.7/dist-packages/twisted/protocols/amp.py", line 553, in serialize
    "Unicode value for key %r not allowed: %r" % (k, v))
exceptions.TypeError: Unicode value for key 'out' not allowed: u'hey!\nTraceback (most recent call last):\nFailure: exceptions.Exception: \n'

test_with_error.Foo.test_foo
```

<details><summary>Searchable metadata</summary>

```
trac-id__6516 6516
type__defect defect
reporter__radix radix
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__trial trial
keywords__ 
time__1368676909000000 1368676909000000
changetime__1368707316000000 1368707316000000
version__None None
owner__ 
cc__jml
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_2"></a>|@therve commented|
|-|-|

I'm pretty sure unicode data is not supported in the second argument of log.err. Should it raise an exception when trying to do so?

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_3"></a>|@exarkun commented|
|-|-|

[#7063](https://github.com/twisted/twisted/issues/7063) is a somewhat related ticket.  The general idea here is that the logging system does not support unicode.  Sometimes unicode works by accident, but that's not Twisted's fault.

That doesn't mean unicode shouldn't be supported.  Log messages are much more text-y than bytes-y, I should think (data explicitly intended for consumption by humans?  sounds like text).

So we should probably fix this - but the question of how remains.

I think [#7063](https://github.com/twisted/twisted/issues/7063) bears completion first, since whatever is going to be made to work for `trial -j` needs to be part of the bigger Twisted logging picture.
