### ISSUE TITLE
logging noise: Unexpected exception from twisted.web.client.FileBodyProducer.stopProducing

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#6528]
|<img alt="davidsarah's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| davidsarah reported|
|-|-|
|Trac ID|trac#6528|
|Type|defect|
|Created|2013-05-28 14:14:00Z|

I'm using ```twisted.web.client.Agent``` to connect to an HTTP web service (Microsoft Azure blob storage, but I don't think that's relevant). I use ```FileBodyProducer(StringIO(body))``` to provide the request body, basically following the [tutorial here](http://twistedmatrix.com/documents/12.3.0/web/howto/client.html#auto3). Once in every few hundred or so requests, the service will drop the connection. That's fine; I get a response with an error code and can retry, but the following error also gets logged:

```
Unexpected exception from twisted.web.client.FileBodyProducer.stopProducing
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Twisted-12.3.0-py2.7-linux-x86_64.egg/twisted/internet/_endpointspy3.py", line 77, in connectionLost
    return self._wrappedProtocol.connectionLost(reason)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-12.3.0-py2.7-linux-x86_64.egg/twisted/web/_newclient.py", line 859, in dispatcher
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-12.3.0-py2.7-linux-x86_64.egg/twisted/web/_newclient.py", line 1458, in _connectionLost_TRANSMITTING
    self._currentRequest.stopWriting()
  File "/usr/local/lib/python2.7/dist-packages/Twisted-12.3.0-py2.7-linux-x86_64.egg/twisted/web/_newclient.py", line 760, in stopWriting
    _callAppFunction(self.bodyProducer.stopProducing)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/Twisted-12.3.0-py2.7-linux-x86_64.egg/twisted/web/_newclient.py", line 191, in _callAppFunction
    function()
  File "/usr/local/lib/python2.7/dist-packages/Twisted-12.3.0-py2.7-linux-x86_64.egg/twisted/web/client.py", line 776, in stopProducing
    self._task.stop()
  File "/usr/local/lib/python2.7/dist-packages/Twisted-12.3.0-py2.7-linux-x86_64.egg/twisted/internet/task.py", line 464, in stop
    self._checkFinish()
  File "/usr/local/lib/python2.7/dist-packages/Twisted-12.3.0-py2.7-linux-x86_64.egg/twisted/internet/task.py", line 474, in _checkFinish
    raise self._completionState
twisted.internet.task.TaskStopped: 
```

The problem seems to be that the ```FileBodyProducer```'s ```stopProducing``` method is called twice (by Twisted; my own code isn't calling it), which causes a ```TaskStopped``` exception to be raised from the second call. If I use a ```FileBodyProducer``` subclass that overrides ```stopProducing``` and suppresses the ```TaskStopped``` exception, like this:
```
class QuieterFileBodyProducer(FileBodyProducer):
    def stopProducing(self):
        try:
            FileBodyProducer.stopProducing(self)
        except task.TaskStopped:
            pass
```
then I no longer get the noise in the log.

It isn't clear from the documentation of ```IProducer.stopProducing``` whether it is the caller's responsibility to avoid calling it more than once, or whether calls after the first should be ignored.

[http://comments.gmane.org/gmane.comp.python.twisted/25099] may be another report of this problem.

<details><summary>Searchable metadata</summary>

```
trac-id__6528 6528
type__defect defect
reporter__davidsarah davidsarah
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__web web
keywords__logging_review logging review
time__1369750440000000 1369750440000000
changetime__1588487434277899 1588487434277899
version__None None
owner__Glyph__glyph_____ Glyph <glyph@...>
cc__jknight
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="russellhaering's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_2"></a>|russellhaering commented|
|-|-|

I'm seeing this too.

Some background:

1. I perform a lot of POSTs to Marconi's "claim messages" API (https://wiki.openstack.org/wiki/Marconi/specs/api/v1#Claim_Messages) using treq. They all come back with 204s.
2. I perform a POST to "claim messages" which comes back with a 201.
3. I get a ConnectionDone, catch it, and retry.
4. The "Unexpected exception from twisted.web.client.FileBodyProducer.stopProducing" message gets logged. Short of implementing my own BodyProducer there isn't a reasonable way to silence this.

My problem appears to be similar to this: http://twistedmatrix.com/pipermail/twisted-python/2012-December/026369.html

**Comment by twisted-trac** [comment]
|<img alt="petri's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_3"></a>|petri commented|
|-|-|

I am also seeing this, when making a treq POST request from within a loop running using a Twisted task.Cooperator():


```
Unexpected exception from twisted.web.client.FileBodyProducer.stopProducing
Traceback (most recent call last):
  File "/opt/pythonapps/site-packages/twisted/internet/endpoints.py", line 129, in connectionLost
    return self._wrappedProtocol.connectionLost(reason)
  File "/opt/pythonapps/site-packages/twisted/web/_newclient.py", line 916, in dispatcher
    return func(*args, **kwargs)
  File "/opt/pythonapps/site-packages/twisted/web/_newclient.py", line 1574, in _connectionLost_TRANSMITTING
    self._currentRequest.stopWriting()
  File "/opt/pythonapps/site-packages/twisted/web/_newclient.py", line 817, in stopWriting
    _callAppFunction(self.bodyProducer.stopProducing)
--- <exception caught here> ---
  File "/opt/pythonapps/site-packages/twisted/web/_newclient.py", line 194, in _callAppFunction
    function()
  File "/opt/pythonapps/site-packages/twisted/web/client.py", line 1019, in stopProducing
    self._task.stop()
  File "/opt/pythonapps/site-packages/twisted/internet/task.py", line 471, in stop
    self._checkFinish()
  File "/opt/pythonapps/site-packages/twisted/internet/task.py", line 481, in _checkFinish
    raise self._completionState
twisted.internet.task.TaskStopped:
```

**Comment by twisted-trac** [comment]
|<img alt="petri's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_4"></a>|petri commented|
|-|-|

For whom it may be of interest, here's more or less full example of how to register a quieter producer in Twisted (this is for treq, see end of https://github.com/twisted/treq/blob/master/treq/client.py)

```
from StringIO import StringIO
from io import BytesIO

from zope.interface import declarations
from twisted.internet import task
from twisted.web.iweb import IBodyProducer
from twisted.web.client import FileBodyProducer
from twisted.python.components import registerAdapter, getRegistry


class QuieterFileBodyProducer(FileBodyProducer):
    def stopProducing(self):
        try:
            FileBodyProducer.stopProducing(self)
        except task.TaskStopped:
            pass

def _from_bytes(orig_bytes):
    return QuieterFileBodyProducer(StringIO(orig_bytes))

def _from_file(orig_file):
    return QuieterFileBodyProducer(orig_file)

# utility to get class interfaces (declarations)
ifaces = lambda klass: declarations.implementedBy(klass)

registrations = {
   str:_from_bytes,
   file: _from_file,
   StringIO: _from_file,
   BytesIO: _from_file
}

registry = getRegistry()

# unregister noisy producers and register better ones

for klass in registrations:
   registry.register([ifaces(klass)], IBodyProducer, '', None)

for klass, adapter in registrations.items():
   registerAdapter(adapter, klass, IBodyProducer)

```

**Comment by twisted-trac** [comment]
|<img alt="petri's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_5"></a>|petri commented|
|-|-|

Is this related to [#7457](https://github.com/twisted/twisted/issues/7457) ?

**Comment by twisted-trac** [comment]
|[<img alt="jlitzingerdev's avatar" src="https://avatars.githubusercontent.com/u/1496650?s=50" width="50" height="50">](https://github.com/jlitzingerdev)<a name="note_6"></a>|@jlitzingerdev commented|
|-|-|

PR
https://github.com/twisted/twisted/pull/1204

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_7"></a>|@glyph set owner to @glyph<br>@glyph set status to `closed`|
|-|-|

In changeset 8c251edc95b48d578660343c5de072691ff75e8b
```
#!CommitTicketReference repository="" revision="8c251edc95b48d578660343c5de072691ff75e8b"
Merge pull request #1204 from jlitzingerdev/6528-double-stop

Author: 	jlitzingerdev

Reviewer: glyph

Fixes: ticket:6528

Correct implementation of FileBodyProducer.stopProducing to avoid raising `TaskStopped`.
```
