### ISSUE TITLE
Commands of twisted.mail.pop3client.POP3Client should return a cancellable Deferred

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#6588]
|<img alt="kaizhang's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| kaizhang reported|
|-|-|
|Trac ID|trac#6588|
|Type|enhancement|
|Created|2013-06-21 11:46:39Z|
|Branch|https://github.com/twisted/twisted/tree/pop3client-deferred-cancellation-6588|

Commands of `twisted.mail.pop3client.POP3Client` should return a cancellable Deferred. If a command in blocked queue is cancelled, it should be removed from the queue. If a trying command is cancelled, the connection should be disconnected without sending the "QUIT" command, so that the operation wouldn't take affect on the server side.

<details><summary>Searchable metadata</summary>

```
trac-id__6588 6588
type__enhancement enhancement
reporter__kaizhang kaizhang
priority__normal normal
milestone__ 
branch__branches_pop3client_deferred_cancellation_6588 branches/pop3client-deferred-cancellation-6588
branch_author__kaizhang kaizhang
status__new new
resolution__None None
component__mail mail
keywords__ 
time__1371815199000000 1371815199000000
changetime__1380139771000000 1380139771000000
version__None None
owner__kaizhang kaizhang
cc__ashfall
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="kaizhang's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_1"></a>|kaizhang commented|
|-|-|

(In [38879]) Branching to 'pop3client-deferred-cancellation-6588'

**Comment by twisted-trac** [comment]
|<img alt="kaizhang's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_2"></a>|kaizhang removed owner|
|-|-|

[Build Results](http://buildbot.twistedmatrix.com/boxes-supported?branch=/branches/pop3client-deferred-cancellation-6588)

The freebsd-8.2-i386 buildbot seems to be broken.

**Comment by twisted-trac** [comment]
|<img alt="kaizhang's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|kaizhang set owner to kaizhang|
|-|-|

**Comment by twisted-trac** [comment]
|<img alt="kaizhang's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_4"></a>|kaizhang removed owner|
|-|-|

[Build Results](http://buildbot.twistedmatrix.com/boxes-supported?branch=/branches/pop3client-deferred-cancellation-6588)

**Comment by twisted-trac** [comment]
|<img alt="kaizhang's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|kaizhang set owner to kaizhang|
|-|-|

**Comment by twisted-trac** [comment]
|<img alt="kaizhang's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|kaizhang set status to `assigned`|
|-|-|

**Comment by twisted-trac** [comment]
|<img alt="kaizhang's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_7"></a>|kaizhang removed owner<br>kaizhang set status to `new`|
|-|-|

I rewrote the tests in a TDD development way.

[Build Results](https://buildbot.twistedmatrix.com/boxes-supported?branch=/branches/pop3client-deferred-cancellation-6588)

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)<a name="note_8"></a>|@itamarst set owner to kaizhang|
|-|-|

Thanks for reworking the tests.

 1. If you're overriding `POP3Client` for testing purposes, you don't need super detailed docstrings. So e.g. no need to explain stuff already explained in the base protocol class. This is test code, no one will use it in real code, goal is just to make it readable enough for people looking at the tests.
 1. The docstring for `test_cancelCommandInQueueReturnedBySendShort` talks about a case which I'm pretty sure shouldn't be handled by this test (everything after "The connection is NOT disconnected."). The second half of the test seems like it's already covered by other tests later on. Same for the `sendLong` equivalent test.
 1. "When cancel a command in the blocked queue" should be "when cancelling a command in the blocked queue".
 1. Also, "blocked queue" is a bit obscure - perhaps say "When cancelling a command that hasn't yet been sent over the network". In general test descriptions should be slightly higher level if possible, so you get a sense of overall intention rather than just implementation details.
 1. Using explicit assertions is usually a good idea in tests. So instead of:
```
failure = self.failureResultOf(deferred)
failure.trap(defer.CancelledError) 
```
  I'd instead do
```
failure = self.failureResultOf(deferred)
self.assertTrue(failure.check(defer.CancelledError))
```
 1. The `dataReceived` calls in the assertions about commands using sendShort/sendLong seem unnecessary.
 1. Might want assertIdentical in those assertions (not a big deal, since Deferreds don't actually implement custom comparison, but worth paying attention to the difference.)
 1. Add `C{}` around all the command names in those tests, e.g. "The C{stat} command uses etc.".

Please address and resubmit.

**Comment by twisted-trac** [comment]
|<img alt="kaizhang's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|kaizhang set status to `assigned`|
|-|-|

**Comment by twisted-trac** [comment]
|<img alt="kaizhang's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_10"></a>|kaizhang commented|
|-|-|

I have revised my patch according to the comments.

Replying to [itamar](#note_8):
>  1. The docstring for `test_cancelCommandInQueueReturnedBySendShort` talks about a case which I'm pretty sure shouldn't be handled by this test (everything after "The connection is NOT disconnected."). The second half of the test seems like it's already covered by other tests later on. Same for the `sendLong` equivalent test.
The second half of the `test_cancelCommandInQueueReturnedBySendShort` is the case where a command being popped out from the queue and sent over the network. What the cancellation do in this case is same to the case where the command is sent directly. But these two cases are trigger by different condition. So I splitted the `test_cancelCommandInQueueReturnedBySendShort` into two tests, keep alongside with the later test. Same for the `sendLong` equivalent test.

**Comment by twisted-trac** [comment]
|<img alt="kaizhang's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_11"></a>|kaizhang removed owner<br>kaizhang set status to `new`|
|-|-|

[Build Results](https://buildbot.twistedmatrix.com/boxes-supported?branch=/branches/pop3client-deferred-cancellation-6588)

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_12"></a>|@exarkun commented|
|-|-|

> Using explicit assertions is usually a good idea in tests. So instead of:
 ```
 failure = self.failureResultOf(deferred)
 failure.trap(defer.CancelledError) 
 ```
> I'd instead do
 ```
 failure = self.failureResultOf(deferred)
 self.assertTrue(failure.check(defer.CancelledError))
 ```

This produces a slightly worse failure from the test:

```
exarkun@top:/tmp$ trial test_mode.py 
test_mode
  FailureModeTests
    test_check ...                                                       [FAIL]
    test_trap ...                                                       [ERROR]

===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/tmp/test_mode.py", line 12, in test_check
    self.assertTrue(f.check(ValueError))
twisted.trial.unittest.FailTest: None

test_mode.FailureModeTests.test_check
===============================================================================
[ERROR]
Traceback (most recent call last):
Failure: exceptions.OSError: 

test_mode.FailureModeTests.test_trap
-------------------------------------------------------------------------------
Ran 2 tests in 0.011s

FAILED (failures=1, errors=1)
```

With `Failure.check`, you get no indication of what the `Failure` _was_.  Of course, with `trap` you get no indication of _where_ the problem occurred.

Fortunately, `failureResultOf` now takes extra arguments, producing better output:

```
    def test_failureResultOf(self):
        self.failureResultOf(fail(OSError()), ValueError)
```


```
[FAIL]
Traceback (most recent call last):
  File "/tmp/test_mode.py", line 17, in test_failureResultOf
    self.failureResultOf(fail(OSError()), ValueError)
  File "/home/exarkun/Projects/Twisted/trunk/twisted/trial/_synctest.py", line 674, in failureResultOf
    result[0].getTraceback()))
twisted.trial.unittest.FailTest: Failure of type (exceptions.ValueError) expected on <Deferred at 0x249e560 current result: None>, found type <type 'exceptions.OSError'> instead: Traceback (most recent call last):
Failure: exceptions.OSError: 


test_mode.FailureModeTests.test_failureResultOf
```

**Comment by twisted-trac** [comment]
|[<img alt="tomprince's avatar" src="https://avatars.githubusercontent.com/u/283816?s=50" width="50" height="50">](https://github.com/tomprince)<a name="note_13"></a>|@tomprince set owner to kaizhang|
|-|-|

Thanks for working on this.

 1. As exarkun suggested, please use the additional argument to `failureResultOf`, rather than `.assertTrue(failure.check(...))`. (I filed [#6721](https://github.com/twisted/twisted/issues/6721) to document this).
   - Sorry for the back-and-forth on this point. What you originally had is what all the existing code using `failureResultOf` in twisted does, and it is what is currently documented in the trial howto.
 2. There are a number of places in the test docstrings where you have `The C{comething} command uses ...`. It appears that in most (all?) of the cases, you are refering to a method on `POP3Client`. You can refer to that more explicitly as `The L{POP3Client.something} method uses ...` or simply `L{POP3Client.something} uses`.
 3. "trying commnd" is awkward. "command being tried" is somewhat more comprehensible to a native speaker, but "current command" (or maybe "executing command) would be idiomatic in this case.
   - "and is trying to send the message": If the command has been poped out and the deferred is being cancelled then the command has been sent and is waiting for a response.
 3. `MemoryPOP3Client`: "memory" isn't a verb: you probably want either "that can remember the" or "that can record the" instead of "that can memory the".
 4. (minor) Perhaps "all the commands waiting in the queue" instead of "all the waiting commands in the queue". The later formulation causes me to want to ask about the non-waiting commands in the queue.
 5. The interaction between the interaction between `chainDeferred`, `cancel` and the two cancellers here is somewhat confusing. It took my some time to convince myself that calling one canceller from the other does the correct thing. And, in fact, `_cancelTryingCommand` gets called with a different deferred, dependingon whether it gets called directly, or from the other canceller.
   - I'm not sure what to suggest to make this clearer.
   - One option for addressing the last point, is to do `self.waiting.cancel()` instead of `self._cancelTryingCommand` in the `cancel` in `_blocked`, but I don't know if that is clearer.

Please resubmit for review after addressing 1-4 above.

**Comment by twisted-trac** [comment]
|<img alt="kaizhang's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|kaizhang set status to `assigned`|
|-|-|

**Comment by twisted-trac** [comment]
|<img alt="kaizhang's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_15"></a>|kaizhang removed owner<br>kaizhang set status to `new`|
|-|-|

[Build Results](https://buildbot.twistedmatrix.com/boxes-supported?branch=/branches/pop3client-deferred-cancellation-6588)

**Comment by twisted-trac** [comment]
|[<img alt="tomprince's avatar" src="https://avatars.githubusercontent.com/u/283816?s=50" width="50" height="50">](https://github.com/tomprince)<a name="note_16"></a>|@tomprince set owner to kaizhang|
|-|-|

Thanks for working on this.

One minor point: Proper names (like method names) typicaly don't have an article (i.e "the"). "L{methodname}" rather than "The L{methodname}" (see [changeset:39836/branches/pop3client-deferred-cancellation-6588 here]).

Please merge after changing that.
