### ISSUE TITLE
t.i.endpoints.ProcessEndpoint doesn't work with LineReceiver because _ProcessEndpointTransport object has no attribute disconnecting

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#6606]
|[<img alt="wallrj's avatar" src="https://avatars.githubusercontent.com/u/978965?s=50" width="50" height="50">](https://github.com/wallrj)| @wallrj reported|
|-|-|
|Trac ID|trac#6606|
|Type|defect|
|Created|2013-06-30 10:48:53Z|

I was trying to write an example for ProcessEndpoints:
 * [pingbars.py:ticket:5744](None/pingbars.py:ticket:5744)

...but got this error from LineReceiver.

```
[richard@zorin udp-port-from-fd-5574-3]$ python doc/core/howto/listings/process/pingbars.py example.com                                            
Unhandled Error
Traceback (most recent call last):
  File "/home/richard/projects/Twisted/branches/udp-port-from-fd-5574-3/twisted/python/log.py", line 88, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/richard/projects/Twisted/branches/udp-port-from-fd-5574-3/twisted/python/log.py", line 73, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/richard/projects/Twisted/branches/udp-port-from-fd-5574-3/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/richard/projects/Twisted/branches/udp-port-from-fd-5574-3/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/home/richard/projects/Twisted/branches/udp-port-from-fd-5574-3/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
  File "/home/richard/projects/Twisted/branches/udp-port-from-fd-5574-3/twisted/internet/process.py", line 257, in doRead
    return fdesc.readFromFD(self.fd, self.dataReceived)
  File "/home/richard/projects/Twisted/branches/udp-port-from-fd-5574-3/twisted/internet/fdesc.py", line 94, in readFromFD
    callback(output)
  File "/home/richard/projects/Twisted/branches/udp-port-from-fd-5574-3/twisted/internet/process.py", line 260, in dataReceived
    self.proc.childDataReceived(self.name, data)
  File "/home/richard/projects/Twisted/branches/udp-port-from-fd-5574-3/twisted/internet/process.py", line 887, in childDataReceived
    self.proto.childDataReceived(name, data)
  File "/home/richard/projects/Twisted/branches/udp-port-from-fd-5574-3/twisted/internet/endpoints.py", line 336, in childDataReceived
    return self.protocol.dataReceived(data)
  File "/home/richard/projects/Twisted/branches/udp-port-from-fd-5574-3/twisted/protocols/basic.py", line 445, in dataReceived
    if self.transport.disconnecting:
exceptions.AttributeError: '_ProcessEndpointTransport' object has no attribute 'disconnecting'
```

<details><summary>Searchable metadata</summary>

```
trac-id__6606 6606
type__defect defect
reporter__rwall rwall
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__ 
time__1372589333000000 1372589333000000
changetime__1560836636252726 1560836636252726
version__None None
owner__None None
cc__wiml
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="wallrj's avatar" src="https://avatars.githubusercontent.com/u/978965?s=50" width="50" height="50">](https://github.com/wallrj)<a name="note_1"></a>|@wallrj commented|
|-|-|

This got things working for me, but [#1933](https://github.com/twisted/twisted/issues/1933) may be the real solution.

```
=== modified file 'twisted/internet/endpoints.py'
--- twisted/internet/endpoints.py	2013-06-29 19:23:36 +0000
+++ twisted/internet/endpoints.py	2013-06-30 10:49:31 +0000
@@ -272,6 +272,7 @@
         methods on this object to write data to a child process.
     @type _process: L{interfaces.IProcessTransport} provider
     """
+    disconnecting = False
 
     def write(self, data):
         """
```

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_2"></a>|@exarkun commented|
|-|-|

Another solution would be for `LineReceiver` to stop having a hard dependency on a `disconnecting` attribute.

`getattr(transport, 'disconnecting', False)` is pretty gross, but it localizes the grossness to `LineReceiver`, which ultimately deserves to suffer for violating the transport interface.

**Comment by twisted-trac** [comment]
|[<img alt="wallrj's avatar" src="https://avatars.githubusercontent.com/u/978965?s=50" width="50" height="50">](https://github.com/wallrj)<a name="note_3"></a>|@wallrj commented|
|-|-|

Replying to [exarkun](#note_2):
> Another solution would be for `LineReceiver` to stop having a hard dependency on a `disconnecting` attribute.
> 
> `getattr(transport, 'disconnecting', False)` is pretty gross, but it localizes the grossness to `LineReceiver`, which ultimately deserves to suffer for violating the transport interface.

Thanks for the suggestion. I've mentioned it in ticket:6357#comment:17

**Comment by twisted-trac** [comment]
|[<img alt="wallrj's avatar" src="https://avatars.githubusercontent.com/u/978965?s=50" width="50" height="50">](https://github.com/wallrj)<a name="note_4"></a>|@wallrj commented|
|-|-|

Replying to [exarkun](#note_2):
> Another solution would be for `LineReceiver` to stop having a hard dependency on a `disconnecting` attribute.

The reason seems to be to prevent further calls to LineReceiver.lineReceived when transport.loseConnection has been triggered by a previous command in the same data.

See r7747.

Do we need to preserve that behaviour and if so how can it be done without checking that transport.disconnecting?

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)|@glyph set owner to @glyph|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)|@glyph removed owner|
|-|-|
