### ISSUE TITLE
AddressAlias.createMessageReceiver() returns wrong value

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#6638]
|[<img alt="staceysern's avatar" src="https://avatars.githubusercontent.com/u/3631162?s=50" width="50" height="50">](https://github.com/staceysern)| @staceysern reported|
|-|-|
|Trac ID|trac#6638|
|Type|defect|
|Created|2013-07-21 17:34:20Z|
|Branch|https://github.com/twisted/twisted/tree/createMessageReceiver-return-6638-2|

AddressAlias.createMessageReceiver() was changed under ticket [#4151](https://github.com/twisted/twisted/issues/4151) to eliminate a call to the deprecated IDomain.startMessage().  The call was replaced with a call to IDomain.exists().  However, startMessage() returned an IMessage provider.  exists() returns a no-argument callable which returns an IMessage provider.  createMessageReceiver needs to call the result of the call to exists() to get the proper result.

<details><summary>Searchable metadata</summary>

```
trac-id__6638 6638
type__defect defect
reporter__shira shira
priority__normal normal
milestone__ 
branch__branches_createMessageReceiver_return_6638_2 branches/createMessageReceiver-return-6638-2
branch_author__shira shira
status__new new
resolution__None None
component__mail mail
keywords__ 
time__1374428060000000 1374428060000000
changetime__1422531085687628 1422531085687628
version__None None
owner__shira shira

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="staceysern's avatar" src="https://avatars.githubusercontent.com/u/3631162?s=50" width="50" height="50">](https://github.com/staceysern)|@staceysern set owner to @staceysern|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="staceysern's avatar" src="https://avatars.githubusercontent.com/u/3631162?s=50" width="50" height="50">](https://github.com/staceysern)<a name="note_2"></a>|@staceysern commented|
|-|-|

(In [39396]) Branching to 'createMessageReceiver-return-6638'

**Comment by twisted-trac** [comment]
|[<img alt="staceysern's avatar" src="https://avatars.githubusercontent.com/u/3631162?s=50" width="50" height="50">](https://github.com/staceysern)<a name="note_3"></a>|@staceysern commented|
|-|-|

(In [39408]) Fixed createMessageReceiver and unit tests.

refs [#6638](https://github.com/twisted/twisted/issues/6638)

**Comment by twisted-trac** [comment]
|[<img alt="staceysern's avatar" src="https://avatars.githubusercontent.com/u/3631162?s=50" width="50" height="50">](https://github.com/staceysern)<a name="note_4"></a>|@staceysern commented|
|-|-|

Additionally, I changed the argument to exists from a string to User which it expects.

In test_mail.py, I removed DummyDomain and changed the AliasAddressTests to use TestDomain which had to be modified slightly.  I removed AddressAliasTests.test_resolve and AddressAliasTests.test_resolveWithoutAliasMap because the AliasAddress.resolve is being well tested by ProcessAliasTestCase.test_resolution.  I modified TestDomain.exists to return TestMessage, which is an IMessage provider, when the address is local instead of AddressAlias.

**Comment by twisted-trac** [comment]
|[<img alt="staceysern's avatar" src="https://avatars.githubusercontent.com/u/3631162?s=50" width="50" height="50">](https://github.com/staceysern)<a name="note_5"></a>|@staceysern commented|
|-|-|

(In [39416]) Changed string formatting.

refs [#6638](https://github.com/twisted/twisted/issues/6638)

**Comment by twisted-trac** [comment]
|[<img alt="staceysern's avatar" src="https://avatars.githubusercontent.com/u/3631162?s=50" width="50" height="50">](https://github.com/staceysern)|@staceysern removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_7"></a>|@exarkun set owner to @staceysern|
|-|-|

Thanks for your work on this shira.  Sorry about the long delay in getting this reviewed.

  1. twisted/mail/alias.py
    1. `IAlias` and `IAlias.createMessageReceiver` are badly in need of docstrings.  This seems like a pretty good branch in which to add them.
    1. 
  1. twisted/mail/test/test_mail.py
    1. `TestMessage` (and all other new code) should use the new style of declaring what interface it implements, the `zope.interface.implementer` class decorator
    1. It's not necessary to repeat the documentation for the `user` `__init__` parameter and `user` instance attribute.  Just document the `__init__` parameter.
    1. New documentation should almost always avoid talking about `str` - instead talk about `bytes` or about `unicode` (most existing Twisted APIs that talk about `str` should be talking about `bytes` now, but not all - each case needs to be considered individually).
    1. There's some trailing whitespace that should be cleaned up in `TestMessage.__str__` (but see below)
    1. And there should be two blank lines between methods in `TestMessage`
    1. `TestCase.patch` is a good replacement for what `setUp` and `tearDown` are doing with `DNSNAME`.
    1. `test_createMessageReceiver` verifies that it gets the expected object by comparing the string representations of two objects.  It would be better to compare the objects themselves.  Consider implementing equality on `TestMessage` instead of `__str__` (see `twisted.python.util.FancyEqMixin` to make that task easier)
    1. When using `%s`-style string interpolation, always interpolate a tuple.  For example, `test_str` should do `'<Address %s>' % (str(self.destination),)` or, more simply, `'<Address %s>' % (self.destination,)` (since "%s" already applies `str`).
    1. There is a commented-out line in `TestDomain` that should be deleted (all old code should be deleted, not commented out).
    1. Some test coverage for `AddressAlias.resolve` has been lost in this branch.  in trunk all lines and branches are executed, in the branch this is not the case - http://buildbot.twistedmatrix.com/builds/twisted-coverage.py/twisted-coverage.py-r39416/twisted_mail_alias.html

Thanks again.

**Comment by twisted-trac** [comment]
|[<img alt="staceysern's avatar" src="https://avatars.githubusercontent.com/u/3631162?s=50" width="50" height="50">](https://github.com/staceysern)<a name="note_8"></a>|@staceysern commented|
|-|-|

(In [39853]) Address review comments

refs [#6638](https://github.com/twisted/twisted/issues/6638)

**Comment by twisted-trac** [comment]
|[<img alt="staceysern's avatar" src="https://avatars.githubusercontent.com/u/3631162?s=50" width="50" height="50">](https://github.com/staceysern)<a name="note_9"></a>|@staceysern commented|
|-|-|

(In [39854]) Fixed twistedchecker errors

refs [#6638](https://github.com/twisted/twisted/issues/6638)

**Comment by twisted-trac** [comment]
|[<img alt="staceysern's avatar" src="https://avatars.githubusercontent.com/u/3631162?s=50" width="50" height="50">](https://github.com/staceysern)<a name="note_10"></a>|@staceysern removed owner|
|-|-|

Everything has been fixed and tests were added to cover AddressAlias.resolve. 

smtp.DNSNAME didn't need to be patched since creating addresses that have no domain with '' as the default domain achieves the same effect.

**Comment by twisted-trac** [comment]
|[<img alt="wallrj's avatar" src="https://avatars.githubusercontent.com/u/978965?s=50" width="50" height="50">](https://github.com/wallrj)|@wallrj set owner to @wallrj<br>@wallrj set status to `assigned`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="wallrj's avatar" src="https://avatars.githubusercontent.com/u/978965?s=50" width="50" height="50">](https://github.com/wallrj)<a name="note_12"></a>|@wallrj set owner to @staceysern<br>@wallrj set status to `new`|
|-|-|

Notes:
 * Merges cleanly
 * Forced a build:
   * https://buildbot.twistedmatrix.com/boxes-supported?branch=/branches/createMessageReceiver-return-6638
 * Checked that tests fail after reverting createMessageReceiver. They do.
   ```
   [FAIL]
   Traceback (most recent call last):
     File "/home/richard/projects/Twisted/branches/createMessageReceiver-return-6638/twisted/mail/test/test_mail.py", line 1819, in test_createMessageReceiver
       self.assertEqual(messageReceiver, TestMessage(str(self.user2)))
     File "/home/richard/projects/Twisted/branches/createMessageReceiver-return-6638/twisted/trial/_synctest.py", line 356, in assertEqual
       % (msg, pformat(first), pformat(second)))
   twisted.trial.unittest.FailTest: not equal:
   a = <function <lambda> at 0x2865578>
   b = <twisted.mail.test.test_mail.TestMessage instance at 0x2985f80>
   ```

Points:
 1. [branches/createMessageReceiver-return-6638/twisted/mail/test/test_mail.py](branches/createMessageReceiver-return-6638/twisted/mail/test/test_mail.py)
    1. TestMessage
       1. Maybe worth sticking a zope.interface.verify.verifyClass to ensure
          that this fake properly implements the interface. (It looks like it
          does).
       2. The `__init__` docstring says the user is supplied as bytes, but you then
          convert it using str. Maybe `bytes(smtp.Address(user))` would be more
          explicit? Not sure.
       3. `__str__` You could mixin FancyStrMixin to create this for you
          automatically in a standardised form.
       4. lineReceived: The pass statement is unnecessary, and maybe the
          docstring should say this is a noop and that the argument is
          discarded.
       5. eomReceived: The pass statement isn't needed and the @rtype is wrong.
          In this case, nothing is returned. Is that ok?
    2. AddressAliasTests.setUp
       1. I find this wrapping difficult to read. I'd rather all the arguments
          on the line below or wrapped beneath self. Not sure if it's in the
          coding standard though.
          ```
           1804         self.alias1to2 = mail.alias.AddressAlias(self.user2, domains,
           1805             user1)
          ```
       2. AddressAlias.test_createMessageReceiver
          1. Use assertEqual and exarkun keeps telling me to put the expected
             result as the first argument, which I'm getting used to now.
          2. L{createMessageReceiver} isn't a valid reference...but I guess it
             doesn't matter since pydoctor won't be rendering these docstrings.
          3. "should get" -> "results in" (see [#6301](https://github.com/twisted/twisted/issues/6301) (you probably already have))
          4. Full stop
       3. test_str
          1. "should include" -> "includes"
          2. And actually aren't we really testing the repr here. I'd have
             thought the str (if different) would be just an email address.
       4. test_resolve
          1. "should" again.
          2. I think the original docstring was better in that it explicitly
             mentions L{None}
       5. test_resolveWithAliasmap
          1. Use assertEqual or assertIdentical (since it's testing for None)
    3. ProcessAliasTestCase.test_aliasResolution
       1. We're still using string comparison here (exarkun mentioned it in
          previous review) but it always did and I guess that could be because
          MessageWrapper and FileWrapper don't support rich comparison. It would
          be nice if those objects could be compared directly though.
    4. TestDomain.exists
       1. Needs a docstring (unless this fake should actually be implementing a
          documented interface?)
       2. Also fix the whitespace before the class
 2. [branches/createMessageReceiver-return-6638/twisted/mail/alias.py](branches/createMessageReceiver-return-6638/twisted/mail/alias.py)
    1. IAlias: Add standard 3 lines above and below "class IAlias"
    2. IAlias.createMessageReceiver
       1. I'd like to see a little more description in the docstring. What is
          this message receiver and how does it relate to this AddressAlias?
       2. No need for the "pass" statement since there's a
          docstring. https://buildbot.twistedmatrix.com/builds/twisted-coverage.py/twisted-coverage.py-r39854/twisted_mail_alias.html#n104
    3. AddressAlias.createMessageReceiver
       1. Add 2 blank lines above and below


Most of this is trivial nit picking stuff. 
Exarkun seemed happy with the change
to createMessageReceiver in his previous review and it makes sense to me. 

So I
think you should go ahead and merge this after addressing or answering the numbered points
above and linking to some clean build results.

Thanks again shira.

**Comment by twisted-trac** [comment]
|[<img alt="staceysern's avatar" src="https://avatars.githubusercontent.com/u/3631162?s=50" width="50" height="50">](https://github.com/staceysern)<a name="note_13"></a>|@staceysern commented|
|-|-|

(In [43004]) Branching to 'createMessageReceiver-return-6638-2'

**Comment by twisted-trac** [comment]
|[<img alt="staceysern's avatar" src="https://avatars.githubusercontent.com/u/3631162?s=50" width="50" height="50">](https://github.com/staceysern)<a name="note_14"></a>|@staceysern set owner to @glyph|
|-|-|

I addressed issues identified in comment:12.  The changeset is http://twistedmatrix.com/trac/changeset/43027.

**Comment by twisted-trac** [comment]
|[<img alt="staceysern's avatar" src="https://avatars.githubusercontent.com/u/3631162?s=50" width="50" height="50">](https://github.com/staceysern)<a name="note_15"></a>|@staceysern commented|
|-|-|

(In [43032]) Fix Twisted checker problems

refs [#6638](https://github.com/twisted/twisted/issues/6638)

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_16"></a>|@glyph removed owner|
|-|-|

Un-assigning all review tickets assigned to me.  Unless there's a specific reason _I_ need to review something, let's leave them unassigned :-).

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_17"></a>|@glyph set owner to @staceysern|
|-|-|

Hi Shira,

I apologize, but it has been long enough now that this doesn't merge cleanly so I can't run it on the buildbot.  Can you merge forward and resolve the conflicts?

Thanks, and sorry that long review latency causes these problems; we'll try to get to it sooner next time :).

-glyph
