### ISSUE TITLE
Failure.getTraceback should support Unicode

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#6708]
|[<img alt="oberstet's avatar" src="https://avatars.githubusercontent.com/u/233340?s=50" width="50" height="50">](https://github.com/oberstet)| @oberstet reported|
|-|-|
|Trac ID|trac#6708|
|Type|defect|
|Created|2013-08-28 11:02:34Z|

The code for `Failure.getTraceback` [http://twistedmatrix.com/trac/browser/tags/releases/twisted-13.1.0/twisted/python/failure.py#L529
] uses [http://twistedmatrix.com/trac/browser/tags/releases/twisted-13.1.0/twisted/python/failure.py#L23] a native version of `StringIO`, `NativeStringIO`, which does not support unicode.

Above situation triggers an exception when the traceback includes non-ASCII Unicode strings:

     'unicode' does not have the buffer interface

As far as I can see, there are only 2 places in above file where string IO is used and those could as well use the standard `StringIO` module which does support Unicode. Hence, the fix would be a 1 liner (change the import).

Attachments:

* [unicode-tb.py](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/5c7/5c72861b4d857e5f339166acc9d9dd3d262d349a/af88a0a04032a219d0cb1f3436728e3cc1aac1ae.py) (377 bytes) - added by twm on 2013-10-21 20:36:21Z - SSCCE for bad Unicode handling

<details><summary>Searchable metadata</summary>

```
trac-id__6708 6708
type__defect defect
reporter__oberstet oberstet
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__ 
time__1377687754000000 1377687754000000
changetime__1382387721000000 1382387721000000
version__None None
owner__ 
cc__oberstet cc__twm
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_2"></a>|@exarkun commented|
|-|-|

It's not clear that switching to `StringIO.StringIO` is the correct fix for this.  That change just makes `Failure` rely on one of Python 2's implicit unicode/bytes conversion behaviors.  It is almost always wrong to rely on that.

Instead, `Failure` needs to be careful to generate unambiguous, meaningful output that can eventually be written to a file-like object (which will probably require `bytes`).

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_3"></a>|@twm commented|
|-|-|

The ```getTraceback``` methods also produce pretty nonsensical output when the exception message contains Unicode.  This script (attached):

```
import traceback
import twisted
from twisted.python import failure


try:
    raise Exception(u'\u16c3')
except Exception:
    print "Native traceback:"
    traceback.print_exc()

print

try:
    raise Exception(u'\u16c3')
except Exception:
    f = failure.Failure()

print "Twisted", twisted.__version__, "Failure traceback:"
print f.getBriefTraceback()
```

Produces this output:

```
unicode-tb.py 
Twisted 13.1.0 Failure traceback:
Traceback: <type 'exceptions.Exception'>: <Exception instance at 0x7f6c8b443200 with str error:
 Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/_reflectpy3.py", line 354, in _safeFormat
    return formatter(o)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u16c3' in position 0: ordinal not in range(128)
>
--- <exception caught here> ---
unicode-tb.py:9:<module>


Native traceback:
Traceback (most recent call last):
  File "unicode-tb.py", line 18, in <module>
    raise Exception(u'\u16c3')
Exception: \u16c3
```

The ```traceback``` module appears to use ```.encode('ascii', 'backslashreplace')``` to coerce unicode input; that seems like a good approach for tracebacks.
