### ISSUE TITLE
FreeBSD/kqueue: DirtyReactorAggregateError

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#6852]
|[<img alt="oberstet's avatar" src="https://avatars.githubusercontent.com/u/233340?s=50" width="50" height="50">](https://github.com/oberstet)| @oberstet reported|
|-|-|
|Trac ID|trac#6852|
|Type|enhancement|
|Created|2013-11-24 11:16:30Z|

I have been trying to find out more about the last 2 remaining kqueue specific trial errors on the new FreeBSD buildslave (CPy 2.7) - please see here:

http://buildbot.twistedmatrix.com/builders/freebsd-9.2-amd64-python2.7/builds/13

I can reproduce the errors when running the complete trial, but when I run only the failing test, I *cannot* reproduce. Please see the attached log.

I could need some tips/hints on where to look, what to try or such, since I have no clue whats going on. My suspicion is, that something is left-over from previous tests that make the subsequent fail. Dunno.

Attachments:

* [trial_log_6852.txt](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/0ea/0ea003444f7d5290a2b010ced3977286f584b943/5affde378e16e32e73efad7d84248a5826574352.txt) (3664 bytes) - added by oberstet on 2013-11-24 11:17:24Z - 
* [trial_log_6852.2.txt](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/0ea/0ea003444f7d5290a2b010ced3977286f584b943/a72b9b978c4bb27bed07eb8c7f4ab0557158699a.txt) (3664 bytes) - added by oberstet on 2013-11-24 11:45:44Z - 

<details><summary>Searchable metadata</summary>

```
trac-id__6852 6852
type__enhancement enhancement
reporter__oberstet oberstet
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__ 
time__1385291790000000 1385291790000000
changetime__1385293521000000 1385293521000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="oberstet's avatar" src="https://avatars.githubusercontent.com/u/233340?s=50" width="50" height="50">](https://github.com/oberstet)<a name="note_1"></a>|@oberstet commented|
|-|-|

Probably related (or not), there is a new fail on all 3 reactors

```
twisted.conch.test.test_endpoints.NewConnectionHelperTests.test_readExisting

[FAIL]
Traceback (most recent call last):
  File "/home/bbslave_twisted/work/freebsd-9.2-amd64/Twisted/twisted/conch/test/test_endpoints.py", line 1411, in test_readExisting
    self.assertTrue(loaded.hasHostKey("127.0.0.1", key))
  File "/home/bbslave_twisted/work/freebsd-9.2-amd64/Twisted/twisted/trial/_synctest.py", line 308, in assertTrue
    raise self.failureException(msg)
twisted.trial.unittest.FailTest: None

twisted.conch.test.test_endpoints.NewConnectionHelperTests.test_readExisting
===============================================================================
```


http://buildbot.twistedmatrix.com/builders/freebsd-9.2-amd64-python2.7/builds/13/steps/select/logs/stdio

which I also cannot reproduce when running trial on that failing test or on complete `twisted.conch` .. see 2nd attached file.
