### ISSUE TITLE
twisted.scripts.test.test_tap2deb.TestTap2DEB.test_basicOperation fails (on Gentoo?)

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#6920]
|<img alt="idella's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| idella reported|
|-|-|
|Trac ID|trac#6920|
|Type|defect|
|Created|2014-01-19 07:07:44Z|

```
[FAIL]
Traceback (most recent call last):
  File "/mnt/gen2/TmpDir/portage/dev-python/twisted-core-13.2.0/work/TwistedCore-13.2.0-python2_7/test/lib/twisted/scripts/test/test_tap2deb.py", line 86, in test_basicOperation
    ['build-stamp', 'debian', 'install-stamp', 'lemon.tap'])
  File "/mnt/gen2/TmpDir/portage/dev-python/twisted-core-13.2.0/work/TwistedCore-13.2.0-python2_7/test/lib/twisted/trial/_synctest.py", line 356, in assertEqual
    % (msg, pformat(first), pformat(second)))
twisted.trial.unittest.FailTest: not equal:
a = ['debian', 'lemon.tap']
b = ['build-stamp', 'debian', 'install-stamp', 'lemon.tap']


twisted.scripts.test.test_tap2deb.TestTap2DEB.test_basicOperation
===============================================================================
```

```
$  python -V
Python 2.7.6
```

<details><summary>Searchable metadata</summary>

```
trac-id__6920 6920
type__defect defect
reporter__idella idella
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__wontfix wontfix
component__core core
keywords__ 
time__1390115264000000 1390115264000000
changetime__1449215457725523 1449215457725523
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|<img alt="idella's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_1"></a>|idella commented|
|-|-|

Cancel

 For test_inspectCertificate, is this;

For Quixote resource templates, Quixote (< http://www.quixote.ca/>) is required.

pertinent, otherwise it just fails. 

wrong README

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_3"></a>|@exarkun commented|
|-|-|

`test_inspectCertificate` report split off onto [#6921](https://github.com/twisted/twisted/issues/6921).

**Comment by twisted-trac** [comment]
|<img alt="idella's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_4"></a>|idella commented|
|-|-|

 (on Gentoo?)
yes, on gentoo

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_5"></a>|@hawkowl set status to `closed`|
|-|-|

tap2deb/tap2rpm is deprecated and these tests failures can be ignored as they have no use on Gentoo.

I believe the test failure has something to do with the tests not actually checking if the needed deb tools are there, and may have been fixed since.

Closing this as wontfix.
