### ISSUE TITLE
getPage has errors parsing http response

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#6952]
|<img alt="jesusabdullah's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| jesusabdullah reported|
|-|-|
|Trac ID|trac#6952|
|Type|defect|
|Created|2014-02-09 03:03:11Z|

I have a this chunk of code in a file:

```
from twisted.internet import reactor
from twisted.web.client import getPage

testPage = 'http://api.duckduckgo.com?q=%21map+brooklyn&no_html=1&no_redirect=1&format=json'

d = getPage(testPage)

@d.addCallback
def cbResponse(res):
    print(res)

@d.addErrback
def cbErr(err):
    raise err

@d.addBoth
def cbShutdown(_):
    reactor.stop()
reactor.run()
```

but when I run it:

```
josh@koffing:~/dev/jesusabdullah/ddgbot$ twistd --version
twistd (the Twisted daemon) 13.2.0
Copyright (c) 2001-2013 Twisted Matrix Laboratories.
See LICENSE for details.
josh@koffing:~/dev/jesusabdullah/ddgbot$ python query-test.py
Unhandled Error
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/twisted/python/log.py", line 88, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/twisted/python/log.py", line 73, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/twisted/internet/selectreactor.py", line 151, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/twisted/internet/tcp.py", line 215, in doRead
    return self._dataReceived(data)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/twisted/internet/tcp.py", line 221, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/twisted/protocols/basic.py", line 571, in dataReceived
    why = self.lineReceived(line)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/twisted/web/http.py", line 441, in lineReceived
    status = l[1]
exceptions.IndexError: list index out of range
josh@koffing:~/dev/jesusabdullah/ddgbot$
```

The ddg API call is the particular url I ran into during a side project that trips this behavior. Others I've tested, such as google.com, return just fine. No idea why this *particular* url would cause getPage to barf.

<details><summary>Searchable metadata</summary>

```
trac-id__6952 6952
type__defect defect
reporter__jesusabdullah jesusabdullah
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__invalid invalid
component__core core
keywords__ 
time__1391914991000000 1391914991000000
changetime__1391963887000000 1391963887000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|<img alt="jesusabdullah's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_2"></a>|jesusabdullah commented|
|-|-|

Note, that I have every reason to believe DDG is sending valid HTTP. I would expect this error only if the response was completely skipping status codes and headers.

**Comment by twisted-trac** [comment]
|<img alt="jesusabdullah's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_3"></a>|jesusabdullah commented|
|-|-|

Also: If you put a debug statement in the LineReceiver, you'll see the first line IT receives is in fact '<html>'. Which would scream bad response if the service wasn't running behind nginx.

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_4"></a>|@therve set status to `closed`|
|-|-|

It does scream bad response. I don't know why you think nginx can't return something bad :). The bug is that you're missing a "/" after the host, it's not a valid HTTP path. If you change to
```
testPage = 'http://api.duckduckgo.com/?q=%21map+brooklyn&no_html=1&no_redirect=1&format=json'
```

It will work.

**Comment by twisted-trac** [comment]
|<img alt="jesusabdullah's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_5"></a>|jesusabdullah commented|
|-|-|

Hahaha! Yeah, my jaw was on the floor for a good 5 minutes when I figured out that nginx was fallible.

Thanks for your help!
