### ISSUE TITLE
Test suite cannot be run on Python 3.3 from installed version of Twisted

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#6955]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)| @itamarst reported|
|-|-|
|Trac ID|trac#6955|
|Type|release blocker: regression|
|Created|2014-02-09 13:52:06Z|

It looks like as code changed people haven't been adding all modules necessary to the install list, so you can run Twisted tests from checkout but not installed version. For example:

```
======================================================================
ERROR: twisted.names.test.test_client (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.3/unittest/case.py", line 384, in _executeTestPart
    function()
  File "/usr/lib/python3.3/unittest/loader.py", line 32, in testFailure
    raise exception
ImportError: Failed to import test module: twisted.names.test.test_client
Traceback (most recent call last):
  File "/usr/lib/python3.3/unittest/loader.py", line 261, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.3/unittest/loader.py", line 239, in _get_module_from_name
    __import__(name)
  File "/home/itamar/.local/lib/python3.3/site-packages/twisted/names/test/test_client.py", line 25, in <module>
    from twisted.names.test.test_rootresolve import MemoryReactor
ImportError: No module named 'twisted.names.test.test_rootresolve'
```

<details><summary>Searchable metadata</summary>

```
trac-id__6955 6955
type__release_blocker__regression release blocker: regression
reporter__itamar itamar
priority__normal normal
milestone__Python_3_x Python-3.x
branch__ 
branch_author__ 
status__closed closed
resolution__duplicate duplicate
component__core core
keywords__ 
time__1391953926000000 1391953926000000
changetime__1467855696455399 1467855696455399
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_1"></a>|@rodrigc set status to `closed`|
|-|-|

Duplicate of [ticket:8550]
