### ISSUE TITLE
twisted.python.logfile umask race condition

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#7026]
|<img alt="jacobrichard's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| jacobrichard reported|
|-|-|
|Trac ID|trac#7026|
|Type|defect|
|Created|2014-03-11 01:56:52Z|
|Branch|https://github.com/twisted/twisted/tree/logfile-umask-7026|

In twisted.python.logfile, the _openFile function, in a specific case, the function sets the umask to 0777 in order to open a file with no permissions and then add permissions to it a few lines later. 

This creates a race condition wherein if 'thread A' has set the umask to 0777, and 'thread B' reads this as the initial value of umask, and then completes after thread A, 0777 becomes the umask value for all ensuing operations in that python process. 

Attached is reproducer.py which patches LogFile and exacerbates this problem by adding a sleep value in different places to increase the chance of the bug occurring. 

In addition, attached is a patched logfile.py which uses a threading lock to ensure that only one _openFile can access and change the umask at any given time. 

Attachments:

* [logfile_7026.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/18f/18f5742860e84eb2a340a1c9fcfa1b6263eaf604/4e468f97fd8eeaa331b9ac6959f9f98e263405e5.patch) (1322 bytes) - added by jacobrichard on 2014-03-11 02:00:08Z - Patch for twisted.python.logfile 
* [reproducer.py](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/18f/18f5742860e84eb2a340a1c9fcfa1b6263eaf604/9d89242cc58468f2f19cf3167d1fb96d502a24d4.py) (2550 bytes) - added by jacobrichard on 2014-03-11 02:00:26Z - 
* [logfile-7026-v2.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/18f/18f5742860e84eb2a340a1c9fcfa1b6263eaf604/885ede6e6085e972a6ae111aa5a2f180329e671f.patch) (1398 bytes) - added by jacobrichard on 2014-03-11 16:40:38Z - Patch for Logfile Umask Race Condition (Version 2)
* [logfile-7026-v3.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/18f/18f5742860e84eb2a340a1c9fcfa1b6263eaf604/f5ed0bcbac3d788d6646daeb96323f6bd901988e.patch) (2279 bytes) - added by jacobrichard on 2014-03-18 21:01:09Z - Patch for Logfile Umask Race Condition (Version 3) 
* [logfile-7026-v4.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/18f/18f5742860e84eb2a340a1c9fcfa1b6263eaf604/9d3a9cd7d7b5519edd7619a13917bb0d0b857256.patch) (2540 bytes) - added by jacobrichard on 2014-04-03 15:13:35Z - Version 4 of Changes for Review

<details><summary>Searchable metadata</summary>

```
trac-id__7026 7026
type__defect defect
reporter__jacobrichard jacobrichard
priority__normal normal
milestone__ 
branch__branches_logfile_umask_7026 branches/logfile-umask-7026
branch_author__rwall rwall
status__new new
resolution__None None
component__core core
keywords__ 
time__1394503012000000 1394503012000000
changetime__1413970876736892 1413970876736892
version__None None
owner__jacobrichard jacobrichard
cc__jacobrichard
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="jacobrichard's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_1"></a>|jacobrichard commented|
|-|-|

To reproduce this, run reproducer.py repeatedly, after a few tries the umask at the end of execution will not match the umask at the beginning of execution.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_3"></a>|@exarkun commented|
|-|-|

Thanks for your contribution to Twisted, jacobrichard.

I think the attached patch doesn't really solve the issue.  Other code can still call umask (or create files) in a way that interacts poorly with `twisted.python.logfile`.

Another approach would be to not use `os.umask` at all.  Instead, use `os.open` and pass the mode argument.  This probably also removes the related race condition where the file is opened with one permission and then chmoded to another permission.

Also please have a look at ReviewProcess to learn about Twisted's ticket workflow.  Thanks again.

**Comment by twisted-trac** [comment]
|<img alt="jacobrichard's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_4"></a>|jacobrichard commented|
|-|-|

You're right, it does not solve the problem from external code. I'll work up a better solution, probably using os.open as suggested.

**Comment by twisted-trac** [comment]
|<img alt="jacobrichard's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_5"></a>|jacobrichard commented|
|-|-|

I have attached logfile-7026-v2.patch, this is using os.open instead of umask for permissions. I've tested it on my own, and it passes existing test_logfile unit testing.

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_7"></a>|@adiroiban set owner to jacobrichard|
|-|-|

Hi Jacob (or Richard) and thanks for the work on this.

I am doing my first reviews so please bare with me in case I add any stupid comments.
 
Writing test to check race conditions is PITA and I have no idea how to write a test for this problem... so I can not ask you to write a test for the old code and have the test fail.

I see that there is a test test_defaultPermissions which exercise the if NOT os.path.exists branch.

Maybe this is a good time to also add a test for if os.path.exist branch so that we know that os.chmod part is executed in the test suite.


--------

Instead of this:

```
if self.defaultMode is not None: 
    # Open with the defaultMode 
    self._file = os.fdopen(os.open(self.path,  
        os.O_CREAT|os.O_RDWR, self.defaultMode)) 
 else: 
    self._file = file(self.path, "w+", 1) 
```

why not use something like this... without any comments :) :

```
mode = self.defaultMode
if mode is None:
    mode = 1
  
self._file = os.open(file=self.path, flags='w+', mode=mode) 
```

----

I see that this module uses file() function. As a separate ticket (or in this ticket) maybe you could replace all file() calls to open() calls. http://docs.python.org/2/library/functions.html#file

This should help with python 3 migration.

Thanks!

**Comment by twisted-trac** [comment]
|<img alt="jacobrichard's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_8"></a>|jacobrichard commented|
|-|-|

Race conditions are definitely a really difficult thing to test for, this one took awhile to find. 

I can take a look at testing the os.path.exist logic branch -- having not written a lot of unit tests, I'll have to investigate a bit. 

As pseudo code your example is a good idea -- the code itself as provided doesn't work as os.open doesn't appear to take any kwargs. I can easily write around that though. The fact that os.open returns a file descriptor means it will still have to be wrapped in an fdopen as i understand it. Obviously the root of the problem here is that the builtin open() doesn't take a file mode as an argument at all, so the os module functions need to be leveraged. 

I can certainly change the file() calls to open() where necessary, I can do it in another ticket for tracking purposes if you prefer, or here.

**Comment by twisted-trac** [comment]
|<img alt="jacobrichard's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_9"></a>|jacobrichard commented|
|-|-|

A little misunderstanding here:
```    
self._file = file(self.path, "w+", 1)  
```

The '1' does not have to do with the file mode in this case, it has to do with buffering: [http://docs.python.org/2/library/functions.html#open]

So the code with the mode logic as shown is not really applicable, IMO. I'm certainly open to opinions.

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_10"></a>|@adiroiban commented|
|-|-|

Sorry. My bad.

There is already a test for this and that test is test_defaultPermissions. You can check it and see how such a test can be written.

You are right regarding os.open and buffering.

I don't know what can be done to improve the code,
other than remove the ` # Open with the defaultMode` as it should be understood from the above condition and use this indentation:

```
self._file = os.fdopen(os.open( 
    self.path, os.O_CREAT|os.O_RDWR, self.defaultMode), bufsize=1)
```

Maybe also use os.fdopen(os.open( for the other branch. This could avoid problems like the one above where buffering is set in different ways.

Since this ticket is for fixing race condition, I would say to convestion from file() to os.open() should be done in a separate ticket and is not your job :)

Please try to fix the code duplication for file open code and this should be good.

Thanks!

**Comment by twisted-trac** [comment]
|<img alt="jacobrichard's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_11"></a>|jacobrichard commented|
|-|-|

I have a significantly cleaned up version of the _openFile function written. It passes current unit tests with the exception of test_nonExistentDir, which had to be modified since os.open raises OSError instead of IOError. 

Once I've proven this a bit more I'll post a patchfile for it for review (probably tomorrow). Sorry to make you review this repeatedly in different forms, but the newest version only has one conditional in it, so its a big improvement if it proves out.

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_12"></a>|@adiroiban commented|
|-|-|

Don't worry. I am happy to review better code :)

Don't forget to add a news file for this branch http://twistedmatrix.com/trac/wiki/ReviewProcess#Newsfiles

THanks!

**Comment by twisted-trac** [comment]
|<img alt="jacobrichard's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_13"></a>|jacobrichard commented|
|-|-|

Here is the patchfile with the refactored _openFile method. This currently passes the existing unit tests. I tested this manually, and let it run live in a twisted app -- the behavior appears to be normal and functional (logfile rolling, correct permissions etc).

Now with newsfile goodness as well.

**Comment by twisted-trac** [comment]
|<img alt="jacobrichard's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_14"></a>|jacobrichard commented|
|-|-|

I should say, regarding the unit tests, that the suite results in FAILURE on a fresh checkout, but no more tests fail on my patched branch than a fresh checkout.

Full Unit Tests:
```
Fresh Checkout:
bin/trial twisted/
FAILED (skips=955, expectedFailures=12, failures=7, errors=4, successes=8872)

Patched Branch:
bin/trial twisted/
FAILED (skips=955, expectedFailures=12, failures=7, errors=4, successes=8856)
```

Logfile Specific Unit Tests:
```
Fresh Checkout:
bin/trial twisted/test/test_logfile.py
PASSED (successes=14)

Patched Branch:
bin/trial twisted/test/test_logfile.py
PASSED (successes=14)
```

Any idea why the disparity between successes for the full suite between the patched branch and the current svn copy?  skips, expectedFailures, failures and errors are the same, but successes differ (8856 vs 8872).

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_16"></a>|@adiroiban commented|
|-|-|

Hi,

Thanks for the code.


In my initial calls I wanted to reduce duplicate calls to os.fdopen(os.open()) so that the 
differences are contained in a variable and os.fdopen(os.open() is only called in a single place.

It does look better, but now that I review it I think that it can be distilled to this.

```
        self._file = self._file = os.fdopen(os.open(
            self.path, os.O_CREAT|os.O_RDWR), 'r+', 1)
        try:
            os.chmod(self.path, self.defaultMode)
        except OSError:
            pass
        # WHY IS THIS SEEK HERE!!
        self._file.seek(0,2)
```

Your patch contained a change in os.open() where in one branch it is called with mode=0000 and in another without mode. I don't know why this is needed.

I don't know why the seek is needed. I think that it needs a comment to explain why the seek is done.

In the original version, seek was only done for already existing files. In your latest version and my suggest seek is alwasy done. Not sure if this is ok.

We can ask another developer to give us more details about the seek.

For the newsfile, maybe have something like:

```
twisted.python.log no longer changes system umask when handling files.
```

This not only about rotate, but also about opening log files in general.

What do you think?

-------

Regarding failed errors, I think that we can discuss this over email. Please put the errors in a gist (or pastebin) so that I can see what exact errors are failing.

Thanks!

**Comment by twisted-trac** [comment]
|<img alt="jacobrichard's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_17"></a>|jacobrichard commented|
|-|-|

I apologize for the verbosity of this comment, but I think it is necessary to explain the points you have mentioned.

```
Your patch contained a change in os.open() where in one branch it is
called with mode=0000 and in another without mode. I don't know why this
is needed.
```

This is needed because the original intent with the umask, if a file was specified to be created with defaultPermissions,  the code was would open a file with no permissions and then increase them with the chmod call.    

For example if the systems umask is 0022 and you open a file with no mode given, the resulting file will have 755 permissions. Shortly after, you chmod the permissions to 0700 - there is a small gap in time where the file is readable by unintended users.

To get around this in the original code, the file is opened with no permissions, and then the permissions are elevated appropriately. I beleive this possible security issue is why the code was put together that way in the first place, although this is mostly conjecture. I simply tried to duplicate the functionality of the original code as much as possible.

```
I don't know why the seek is needed. I think that it needs a comment to
explain why the seek is done.

In the original version, seek was only done for already existing files. In
your latest version and my suggest seek is alwasy done. Not sure if this
is ok.
```

In my patch, and your example code, the mode flag is set as r+, as per fopen() this would place the stream at the beginning of the file, and then the seek moves it to the end of the file before exiting the _openFile function. This behaviour of stream placement is the same for w+ as well. 

In testing the unit tests, getting rid of the seek() and using a+ as the mode flag causes the testAppend unit test to fail with the following error.

```
[FAIL]
Traceback (most recent call last):
  File "/root/trunk_new/twisted/test/test_logfile.py", line 75, in testAppend
    self.assertEqual(log.size, 10)
  File "/root/trunk_new/twisted/trial/_synctest.py", line 356, in assertEqual
    % (msg, pformat(first), pformat(second)))
twisted.trial.unittest.FailTest: not equal:
a = 0
b = 10
```

However, he fopen() flags seem to function differently on different platforms, as this test will pass without the seek() on my Mac, but not on a linux machine. It appears that on linux, even when opening a file 'a+', the cursor is not positioned differently when reading and writing. 

On Linux:

```
a+

Open for reading and appending (writing at end  of  file).   The
file is created if it does not exist.  The initial file position
for reading is at the beginning  of  the  file,  but  output  is
always appended to the end of the file.

```

On BSD:

```
a+

Open for reading and writing.  The file is created if it does not exist.  The stream is posi-tioned positioned
tioned at the end of the file.  Subsequent writes to the file will always end up at the then
current end of file, irrespective of any intervening fseek(3) or similar.
```

Notice the difference in stream positioning for reading between the two systems. In order to assure uniformity of cursor position within all files, the seek() is needed, regardless of whether you are using r+ or a+ as your mode flag, since we want the cursor positioned at the end of the file in all cases. 

```
For the newsfile, maybe have something like: twisted.python.log no longer changes system umask when handling files.
```

Agreed, I will update the newsfile appropriately.

**Comment by twisted-trac** [comment]
|<img alt="jacobrichard's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_18"></a>|jacobrichard commented|
|-|-|

I should add that the fopen() business all has to do with the fact that the unit test for testAppend is using LogFile.size to calculate whether data is correctly appended to the file. Since this uses tell() in its underlying code for LogFile, when the cursor is positioned at the beginning of the file for reading on linux (even though writes will appear at the end of the file), when tell() is called, the resultant value is zero. 

This results in a size mismatch in testAppend, which of course fails the unit test.

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_19"></a>|@adiroiban commented|
|-|-|


Many thanks for the explanation.

-----

In this case I think that we should keep the seek call.

A comment is required to document why seek is needed. In this way, this question will not be raised again when other developer is reading the  code.

---

regarding opening files with not permission. Why not the open the file with the required permissions, from the initial call.

chmod can still be called for all files, to fix permissions for files which already exist.

Looking forward for the new patch. Thanks again!

**Comment by twisted-trac** [comment]
|<img alt="jacobrichard's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_20"></a>|jacobrichard commented|
|-|-|

I'll just post it here to avoid more patchfiles until we agree its ready. I'm assuming you are referring to the os.open in the else branch. I updated it in the code below. There will still need to be 2 branches of logic to cover whether or not defaultMode exists, since if it is passed to os.open os os.chmod as None, the function will raise an exception. 

I added the comment as requested, let me know if you have suggestions to make it more clear. I was trying to avoid being too verbose in the comment. I looked for standards in the coding guide regarding comments for twisted, but didn't come up with anything specific.

```
    def _openFile(self):
        """
        Open the log file.
        """
        self.closed = False
        if self.defaultMode is None:
            self._file = self._file = os.fdopen(os.open(
                self.path, os.O_CREAT|os.O_RDWR), 'r+', 1)
        else:
            self._file = self._file = os.fdopen(os.open(
                self.path, os.O_CREAT|os.O_RDWR, self.defaultMode), 'r+', 1)
            try:
                os.chmod(self.path, self.defaultMode)
            except OSError:
                pass
        # Seek is needed for uniformity of stream positioning
        # for read and write between Linux and BSD systems due
        # to differences in fopen() between operating systems.
        self._file.seek(0,2)
```

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_21"></a>|@adiroiban commented|
|-|-|

Looks good.

Maybe self.closed=False should be placed after the call to os.open.

Here is my update, where os.open is called from a single place, with a variable mode.

```
    def _openFile(self):
        """
        Open the log file.
        """
        openMode = self.defaultMode or 0777
        self._file = self._file = os.fdopen(os.open(
            self.path, os.O_CREAT|os.O_RDWR, openMode), 'r+', 1)
        self.closed = False
        # Try our best to update permissions for files which already exists.
        if self.defaultMode:
            try:
                os.chmod(self.path, self.defaultMode)
            except OSError:
                pass
        # Seek is needed for uniformity of stream positioning
        # for read and write between Linux and BSD systems due
        # to differences in fopen() between operating systems.
        self._file.seek(0, 2)
```

Thanks!

**Comment by twisted-trac** [comment]
|<img alt="jacobrichard's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_22"></a>|jacobrichard commented|
|-|-|

The only major difference i see here, is that when you call os.open without a mode, the resulting file mode will have ( 0777 - umask ) permissions. In your script above, if there is not a defaultMode set, files that do not exist will get 0777 permissions.

If this is acceptable, then I would say this is ready to go. I ran your version of the patch through the unit tests:

FAILED (skips=955, expectedFailures=12, failures=7, errors=11, successes=8868)

On my machine it fails the same number of tests as a fresh SVN checkout.

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_23"></a>|@adiroiban commented|
|-|-|

From what I understood to the documentation and what I experience on my computer, mode is always masked with umask... with or without default mode.

Here is my session
```
Python 2.7.3 (default, Feb 27 2014, 20:00:17) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.

>>> import os
>>> f = os.open('defa', os.O_CREAT|os.O_RDWR)
>>> f.close()
>>> f = os.open('wit_home', os.O_CREAT|os.O_RDWR, 0777)
>>> os.close(f)
>>> os.stat('defa').st_mode
33277
>>> os.stat('wit_home').st_mode
33277
>>> print oct(33277)
0100775
>>> 
```

------

Another minor comment.

Maybe instead of ```seek(0, 2)``` we should use ```seek(0, os.END)``` This should make the code easier to read.

**Comment by twisted-trac** [comment]
|<img alt="jacobrichard's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_24"></a>|jacobrichard commented|
|-|-|

You're right. For some reason I had it in my head that I had observed some other behavior when specifying the mode, but after running your example code, I see the same results for permissions

I agree, for readability, the os constant is better in the seek. Here is the latest code ive run through the unit tests

```

    def _openFile(self):
        """
        Open the log file.
        """
        openMode = self.defaultMode or 0777
        self._file = self._file = os.fdopen(os.open(
            self.path, os.O_CREAT|os.O_RDWR, openMode), 'r+', 1)
        self.closed = False
        # Try our best to update permissions for files which already exists.
        if self.defaultMode:
            try:
                os.chmod(self.path, self.defaultMode)
            except OSError:
                pass
        # Seek is needed for uniformity of stream positioning
        # for read and write between Linux and BSD systems due
        # to differences in fopen() between operating systems.
        self._file.seek(0, os.SEEK_END)

```

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_25"></a>|@adiroiban commented|
|-|-|

Please attach a path with your final changes + news file so that I commiter dev can look at the code.

Thanks!

**Comment by twisted-trac** [comment]
|<img alt="jacobrichard's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_26"></a>|jacobrichard commented|
|-|-|

Attached Version 4 of the changes for review, including the newsfile.

**Comment by twisted-trac** [comment]
|[<img alt="wallrj's avatar" src="https://avatars.githubusercontent.com/u/978965?s=50" width="50" height="50">](https://github.com/wallrj)<a name="note_27"></a>|@wallrj commented|
|-|-|

(In [43412]) Branching to logfile-umask-7026.

**Comment by twisted-trac** [comment]
|[<img alt="wallrj's avatar" src="https://avatars.githubusercontent.com/u/978965?s=50" width="50" height="50">](https://github.com/wallrj)<a name="note_28"></a>|@wallrj commented|
|-|-|

Thanks for the latest patch jacobrichard and thanks for persevering with this.

Unfortunately, the patch no-longer seems to apply cleanly.

```
(twisted)[~/.../Twisted/twisted]$ patch -p0 < ~/Downloads/logfile-7026-v4.patch
patching file twisted/test/test_logfile.py
patching file twisted/python/logfile.py
Hunk #1 FAILED at 59.
1 out of 1 hunk FAILED -- saving rejects to file twisted/python/logfile.py.rej
patching file wisted/topfiles/7026.bugfix
```

I'll see if I can resolve the conflicts.

**Comment by twisted-trac** [comment]
|<img alt="jacobrichard's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_29"></a>|jacobrichard commented|
|-|-|

The conflicts appear to apply specifically to changes from this change:

http://twistedmatrix.com/trac/changeset/42211/

As you can see, the umask mode line was changed from 0777 to 0o777, this is blowing up the patch.  I don't see any other apparent conflicts.

**Comment by twisted-trac** [comment]
|[<img alt="wallrj's avatar" src="https://avatars.githubusercontent.com/u/978965?s=50" width="50" height="50">](https://github.com/wallrj)<a name="note_30"></a>|@wallrj commented|
|-|-|

Hey jacobrichard,

Thanks for that...I've now applied your patch along with the related py3 change in 
 * log:branches/logfile-umask-7026

I've forced a build:
 * http://buildbot.twistedmatrix.com/boxes-supported?branch=/branches/logfile-umask-7026

The results should be available shortly.

Unfortunately I've run out of time and I haven't fully understood the issue or the code, but I think you ought to join #twisted-dev and have quick discussion there about how you might go about adding a regression test for this change.

I'll try and log in later and check the build results and leave some more feedback.

**Comment by twisted-trac** [comment]
|[<img alt="wallrj's avatar" src="https://avatars.githubusercontent.com/u/978965?s=50" width="50" height="50">](https://github.com/wallrj)<a name="note_31"></a>|@wallrj commented|
|-|-|

Thanks again jacobrichards,

Notes:
 * Builds all pass
 * I searched for other calls to `os.umask` and found one in `twisted.names.authority`. 
   That is probably vulnerable to the same race condition when multiple threads are in use. 
   If you agree, I'll create a ticket for that.

Points:

 1. Double assignment to self._file
    ``` 
    63	        self._file = self._file = 
    ```

 2. Missing coverage of chmod error suppression. Add a test for this. http://buildbot.twistedmatrix.com/builds/twisted-coverage.py/twisted-coverage.py-r43414/twisted_python_logfile.html#n70

 3. I think branches around `defaultMode` should explicitly test `self.defaultMode is None` since that is the default in the class initialiser:
    ```
    62	        openMode = self.defaultMode or 0o777
    ```

 4. And on that note, I can't find a test for case where openMode falls back to 0o777 ie when the supplied logfile name does not exist and a defaultMode is not supplied.

 5. newsfile should refer to `twisted.python.logfile`. `twisted.python.log` is something else.

Please address or answer the numbered points above and submit an updated patch against [branches/logfile-umask-7026](branches/logfile-umask-7026)

Please also discuss and post a short summary explaining the difficulty of writing a regression test for this change. 
Perhaps someone will come up with a solution, or at least confirm that a test is not required in this instance.

Would it be too drastic to patch `os.umask` with a fake that raises an exception if called during these tests? It seems that there's no way to even *get* the current umask in a threadsafe way, without using locks.
 * http://bugs.python.org/issue21082

-RichardW.
