### ISSUE TITLE
t.i.utils.getProcessOutputAndValue() does not seem to be handling signals properly

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#7045]
|<img alt="craghack's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| craghack reported|
|-|-|
|Trac ID|trac#7045|
|Type|defect|
|Created|2014-03-21 16:55:32Z|

Running the example code below
```
#!/usr/bin/python

import sys, os
from time import gmtime, strftime

# latest libs
sys.path.append('/home/lajos/tmp/Twisted-13.2.0')
sys.path.append('/home/lajos/tmp/zope.interface-4.1.1/src')

from twisted.internet import defer, reactor
from twisted.internet.utils import getProcessOutputAndValue

def log(what):
    print "[%s] %s" % (strftime("%Y-%m-%d %H:%M:%S", gmtime()), what)

@defer.inlineCallbacks
def execute(cmd):
    log("executing: '%s'" % cmd)
    try:
        (out, err, code) = yield getProcessOutputAndValue(cmd, env=os.environ)
    except Exception, e:
        log("error while executing: '%s'" % e)
    else:
        log("done, return code: %d" % code)

reactor.callLater(3, execute, '/home/lajos/sig.pl')
reactor.callLater(10, reactor.stop)

reactor.run()
```

... results in the following error:
```
[2014-03-21 15:53:17] executing: '/home/lajos/sig.pl'
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "/home/lajos/tmp/Twisted-13.2.0/twisted/internet/defer.py", line 423, in errback
    self._startRunCallbacks(fail)
  File "/home/lajos/tmp/Twisted-13.2.0/twisted/internet/defer.py", line 490, in _startRunCallbacks
    self._runCallbacks()
  File "/home/lajos/tmp/Twisted-13.2.0/twisted/internet/defer.py", line 577, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/lajos/tmp/Twisted-13.2.0/twisted/internet/defer.py", line 1155, in gotResult
    _inlineCallbacks(r, g, deferred)
--- <exception caught here> ---
  File "/home/lajos/tmp/Twisted-13.2.0/twisted/internet/defer.py", line 1097, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/lajos/tmp/Twisted-13.2.0/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
exceptions.TypeError: exceptions must be classes, or instances, not type
```

Content of /home/lajos/sig.pl:
```
#!/usr/bin/perl
kill 11, $$;
```

Am I doing something wrong, or is it perhaps an issue with the library?
Your support is much appreciated.

Thanks,
Lajos

<details><summary>Searchable metadata</summary>

```
trac-id__7045 7045
type__defect defect
reporter__craghack craghack
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__invalid invalid
component__core core
keywords__signal signal
time__1395420932000000 1395420932000000
changetime__1395421044000000 1395421044000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun set status to `closed`|
|-|-|

Please use the mailing list, the IRC channel, or one of the other support forums for questions like this.
