### ISSUE TITLE
REGR: "trial -R twisted" fails

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#7076]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#1175|
|Type|defect|
|Created|2005-09-18 06:29:38Z|

<details><summary>Searchable metadata</summary>

```
trac-id__1175 1175
type__defect defect
reporter__exarkun exarkun
priority__highest highest
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__ 
time__1127024978000000 1127024978000000
changetime__1127024969000000 1127024969000000
version__ 
owner__ 
cc__exarkun cc__jml
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun commented|
|-|-|

```
#!html
<pre>
exarkun@boson:~/Scratch/Test$ trial -R twisted

/usr/lib/python2.4/site-packages/zope/interface/declarations.py:353:
twisted.python.components.ComponentsDeprecationWarning: Don't get attributes (in
this case, '__provides__') off Interface, use .queryDescriptionFor() etc. instead
Traceback (most recent call last):
  File "/home/exarkun/Projects/svn/Twisted/trunk/bin/trial", line 24, in ?
    run()
  File "/home/exarkun/Projects/svn/Twisted/trunk/twisted/scripts/trial.py", line
699, in run
    suite = reallyRun(config)
  File "/home/exarkun/Projects/svn/Twisted/trunk/twisted/scripts/trial.py", line
672, in reallyRun
    suite = _getSuite(config)
  File "/home/exarkun/Projects/svn/Twisted/trunk/twisted/scripts/trial.py", line
543, in _getSuite
    suite.addPackageRecursive(package)
  File "/home/exarkun/Projects/svn/Twisted/trunk/twisted/trial/runner.py", line
151, in addPackageRecursive
    self.addTest(self.loader.loadPackageRecursive(package))
  File "/home/exarkun/Projects/svn/Twisted/trunk/twisted/trial/runner.py", line
702, in loadPackageRecursive
    os.path.walk(packageDir, self._packageRecurse, suite)
  File "/usr/lib/python2.4/posixpath.py", line 298, in walk
    walk(name, func, arg)
  File "/usr/lib/python2.4/posixpath.py", line 298, in walk
    walk(name, func, arg)
  File "/usr/lib/python2.4/posixpath.py", line 290, in walk
    func(arg, top, names)
  File "/home/exarkun/Projects/svn/Twisted/trunk/twisted/trial/runner.py", line
697, in _packageRecurse
    suite.addTest(self.loadModule(module))
  File "/home/exarkun/Projects/svn/Twisted/trunk/twisted/trial/runner.py", line
653, in loadModule
    docSuite.addTest(self.loadDoctests(doctest))
  File "/home/exarkun/Projects/svn/Twisted/trunk/twisted/trial/runner.py", line
715, in loadDoctests
    return DocTestSuite(module)
  File "/home/exarkun/Projects/svn/Twisted/trunk/twisted/trial/runner.py", line
68, in __init__
    suite = doctest.DocTestSuite(testModule)
  File "/usr/lib/python2.4/doctest.py", line 2239, in DocTestSuite
    return self._dt_test.name
AttributeError: 'module' object has no attribute 'TestSuite'
exarkun@boson:~/Scratch/Test$
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
