### ISSUE TITLE
Trial timing reporter doesn't work

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#7113]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)| @jml reported|
|-|-|
|Trac ID|trac#1538|
|Type|defect|
|Created|2006-03-04 03:52:07Z|

```
$ trial --reporter=timing twisted.trial
Running 235 tests.
twisted.trial.test.test_assertions.TestAssertionNames.test_equalSpelling ... [OK]Traceback (most recent call last):
  File "/Users/jml/projects/Twisted/branches/deprecated-trial-1509-2/bin/trial", line 24, in ?
    run()
  File "/Users/jml/projects/Twisted/trunk/twisted/scripts/trial.py", line 373, in run
    test_result = trialRunner.run(suite)
  File "/Users/jml/projects/Twisted/trunk/twisted/trial/runner.py", line 487, in run
    suite.run(result)
  File "/Users/jml/projects/Twisted/trunk/twisted/trial/runner.py", line 177, in run
    TestSuite.run(self, result)
  File "/Users/jml/projects/Twisted/trunk/twisted/trial/runner.py", line 117, in run
    test(result)
  File "/Users/jml/projects/Twisted/trunk/twisted/trial/runner.py", line 109, in __call__
    return self.run(result)
  File "/Users/jml/projects/Twisted/trunk/twisted/trial/runner.py", line 117, in run
    test(result)
  File "/Users/jml/projects/Twisted/trunk/twisted/trial/runner.py", line 109, in __call__
    return self.run(result)
  File "/Users/jml/projects/Twisted/trunk/twisted/trial/runner.py", line 117, in run
    test(result)
  File "/Users/jml/projects/Twisted/trunk/twisted/trial/runner.py", line 109, in __call__
    return self.run(result)
  File "/Users/jml/projects/Twisted/trunk/twisted/trial/runner.py", line 117, in run
    test(result)
  File "/Users/jml/projects/Twisted/trunk/twisted/trial/runner.py", line 109, in __call__
    return self.run(result)
  File "/Users/jml/projects/Twisted/trunk/twisted/trial/runner.py", line 117, in run
    test(result)
  File "/Users/jml/projects/Twisted/branches/deprecated-trial-1509-2/twisted/trial/unittest.py", line 342, in __call__
    return self.run(*args, **kwargs)
  File "/Users/jml/projects/Twisted/branches/deprecated-trial-1509-2/twisted/trial/unittest.py", line 479, in run
    result.stopTest(self)            
  File "/Users/jml/projects/Twisted/trunk/twisted/trial/reporter.py", line 297, in stopTest
    self.write("(%.03f secs)\n" % self._last_time)
AttributeError: 'TimingTextReporter' object has no attribute '_last_time'
```

<details><summary>Searchable metadata</summary>

```
trac-id__1538 1538
type__defect defect
reporter__jml jml
priority__highest highest
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__trial trial
keywords__None None
time__1141444327000000 1141444327000000
changetime__1474197555542286 1474197555542286
version__ 
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)|@jml set status to `closed`|
|-|-|

(In [16259]) Merge timing-reporter-1538. Fix [#7113](https://github.com/twisted/twisted/issues/7113)

Author: jml
Reviewer: exarkun

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun set status to `reopened`|
|-|-|

These tests are failing on Win32, presumably due to the decreased clock precision.

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)|@jml set owner to @exarkun<br>@jml set status to `new`|
|-|-|

[branches/timing-1407-2](branches/timing-1407-2) fixes this problem also

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)|@jml commented|
|-|-|

ahem [branches/timing-1470-2](branches/timing-1470-2)

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)|@jml set status to `closed`|
|-|-|

(In [16528]) Cleanup Trial's timing support and tests thereof

Author: jml Reviewer: exarkun Fixes [#11014](https://github.com/twisted/twisted/issues/11014) and [#7113](https://github.com/twisted/twisted/issues/7113)

Factor out the bits that actually check the clock, then stub those bits out in the tests. This makes the tests more reliable -- particularly on Windows.

We also remove the nested timing abstraction, because we weren't ever nesting calls to timed things.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_7"></a>|@hawkowl commented|
|-|-|

[mass edit] Removing review from closed tickets.
