### ISSUE TITLE
Remove deprecated functions from Trial

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#7129]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)| @jml reported|
|-|-|
|Trac ID|trac#1509|
|Type|task|
|Created|2006-02-27 06:21:43Z|

Trial, particularly trial.util has a swag of deprecated functions. Remove them.
This task doesn't include remove the toplevel assertions, because the conch tests are insane.

<details><summary>Searchable metadata</summary>

```
trac-id__1509 1509
type__task task
reporter__jml jml
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__trial trial
keywords__None None
time__1141021303000000 1141021303000000
changetime__1474197555542286 1474197555542286
version__ 
owner__ 
cc__exarkun cc__PenguinOfDoom
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)|@jml set status to `assigned`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)|@jml commented|
|-|-|

OK. We've removed most of the muck from util, including format_tb, extract_tb, suppressWarnings (or  whatever it was called), fireWhenDoneFunc, spinWhile and spinUntil.  We've also removed the assertions module (no one was using it).

The bulk of the diff will be from unit tests that used spinWhile and spinUntil.  Most have been fixed to use Deferred's correctly.  However, since many of the tests in test_tcp are opaque, we've applied a stop-gap solution.

test_tcp has a function called loopUntil which uses t.i.task.LoopingCall to repeatedly check a predicate. When the predicate is true, it fires a Deferred. Tests in test_tcp use this, so at least they've got the right structure.

I'm not going to remove wait in this branch, it's just too damn big.

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)|@jml commented|
|-|-|

Ready for reviewing. [branches/deprecated-trial-1509](branches/deprecated-trial-1509)

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun commented|
|-|-|

I get the following errors:

```
===============================================================================
[ERROR]: twisted.conch.test.test_conch.CmdLineClientTestCase.testExec

  File "/home/exarkun/Projects/Twisted/trunk/twisted/internet/process.py", line 551, in reapProcess
    log.msg('Failed to reap %d:' % self.pid)
exceptions.TypeError: int argument required
===============================================================================
[ERROR]: twisted.conch.test.test_conch.UnixClientTestCase.testExec

  File "/home/exarkun/Projects/Twisted/trunk/twisted/internet/process.py", line 551, in reapProcess
    log.msg('Failed to reap %d:' % self.pid)
exceptions.TypeError: int argument required
===============================================================================
[ERROR]: twisted.web2.dav.test.test_prop.PROP.test_PROPFIND

  File "/home/exarkun/Projects/Twisted/trunk/twisted/web2/dav/resource.py", line 188, in listProperties
    for qname in self.deadProperties().list():
  File "/home/exarkun/Projects/Twisted/trunk/twisted/web2/dav/static.py", line 82, in deadProperties
    self._dead_properties = DeadPropertyStore(self)
  File "/home/exarkun/Projects/Twisted/trunk/twisted/web2/dav/xattrprops.py", line 81, in __init__
    self.attrs = xattr.xattr(self.resource.fp.path)
exceptions.AttributeError: 'module' object has no attribute 'xattr'
===============================================================================
[ERROR]: twisted.test.test_adbapi.GadflyADBAPITestCase.testPool

  File "/home/exarkun/Projects/Twisted/trunk/twisted/test/test_adbapi.py", line 52, in testPool
    self.wait(self.dbpool.runOperation(simple_table_schema))
  File "/home/exarkun/Projects/Twisted/trunk/twisted/test/test_adbapi.py", line 30, in wait
    return unittest.wait(d, timeout=timeout)
exceptions.AttributeError: 'module' object has no attribute 'wait'
===============================================================================
[ERROR]: twisted.test.test_adbapi.GadflyADBAPITestCase.testPool

  File "/home/exarkun/Projects/Twisted/trunk/twisted/test/test_adbapi.py", line 38, in tearDown
    self.wait(self.dbpool.runOperation('DROP TABLE simple'))
  File "/home/exarkun/Projects/Twisted/trunk/twisted/test/test_adbapi.py", line 30, in wait
    return unittest.wait(d, timeout=timeout)
exceptions.AttributeError: 'module' object has no attribute 'wait'
===============================================================================
[ERROR]: twisted.test.test_adbapi.GadflyReconnectTestCase.testPool

  File "/home/exarkun/Projects/Twisted/trunk/twisted/test/test_adbapi.py", line 218, in setUp
    self.wait(self.dbpool.runOperation(simple_table_schema))
  File "/home/exarkun/Projects/Twisted/trunk/twisted/test/test_adbapi.py", line 209, in wait
    return unittest.wait(d, timeout=timeout)
exceptions.AttributeError: 'module' object has no attribute 'wait'
===============================================================================
[ERROR]: twisted.test.test_adbapi.SQLiteADBAPITestCase.testPool

  File "/home/exarkun/Projects/Twisted/trunk/twisted/test/test_adbapi.py", line 52, in testPool
    self.wait(self.dbpool.runOperation(simple_table_schema))
  File "/home/exarkun/Projects/Twisted/trunk/twisted/test/test_adbapi.py", line 30, in wait
    return unittest.wait(d, timeout=timeout)
exceptions.AttributeError: 'module' object has no attribute 'wait'
===============================================================================
[ERROR]: twisted.test.test_adbapi.SQLiteADBAPITestCase.testPool

  File "/home/exarkun/Projects/Twisted/trunk/twisted/test/test_adbapi.py", line 38, in tearDown
    self.wait(self.dbpool.runOperation('DROP TABLE simple'))
  File "/home/exarkun/Projects/Twisted/trunk/twisted/test/test_adbapi.py", line 30, in wait
    return unittest.wait(d, timeout=timeout)
exceptions.AttributeError: 'module' object has no attribute 'wait'
===============================================================================
[ERROR]: twisted.test.test_adbapi.SQLiteReconnectTestCase.testPool

  File "/home/exarkun/Projects/Twisted/trunk/twisted/test/test_adbapi.py", line 218, in setUp
    self.wait(self.dbpool.runOperation(simple_table_schema))
  File "/home/exarkun/Projects/Twisted/trunk/twisted/test/test_adbapi.py", line 209, in wait
    return unittest.wait(d, timeout=timeout)
exceptions.AttributeError: 'module' object has no attribute 'wait'
===============================================================================
[ERROR]: twisted.test.test_adbapi.GadflyReflectorTestCase.testReflector

  File "/home/exarkun/Projects/Twisted/trunk/twisted/test/test_reflector.py", line 110, in setUp
    self.reflector = self.createReflector()
  File "/home/exarkun/Projects/Twisted/trunk/twisted/test/test_reflector.py", line 281, in createReflector
    self.wait(self.dbpool.runOperation(main_table_schema))
  File "/home/exarkun/Projects/Twisted/trunk/twisted/test/test_reflector.py", line 104, in wait
    return unittest.wait(d, timeout=timeout)
exceptions.AttributeError: 'module' object has no attribute 'wait'
===============================================================================
[ERROR]: twisted.test.test_adbapi.PsycopgReflectorTestCase.testReflector

  File "/home/exarkun/Projects/Twisted/trunk/twisted/enterprise/adbapi.py", line 388, in _runOperation
    trans.execute(*args, **kw)
  File "/usr/lib/python2.4/site-packages/gadfly/database.py", line 366, in execute
    cs[i] = cs[i].relbind(database)
  File "/usr/lib/python2.4/site-packages/gadfly/operations.py", line 268, in relbind
    raise NameError, `self.name` + ": cannot delete, no such table/view"
exceptions.NameError: 'TESTTABLE': cannot delete, no such table/view
===============================================================================
[ERROR]: twisted.test.test_adbapi.SQLiteReflectorTestCase.testReflector

  File "/home/exarkun/Projects/Twisted/trunk/twisted/test/test_reflector.py", line 110, in setUp
    self.reflector = self.createReflector()
  File "/home/exarkun/Projects/Twisted/trunk/twisted/test/test_reflector.py", line 281, in createReflector
    self.wait(self.dbpool.runOperation(main_table_schema))
  File "/home/exarkun/Projects/Twisted/trunk/twisted/test/test_reflector.py", line 104, in wait
    return unittest.wait(d, timeout=timeout)
exceptions.AttributeError: 'module' object has no attribute 'wait'
===============================================================================
[ERROR]: twisted.test.test_release.UtilityTest.testChdir

  File "/home/exarkun/Projects/Twisted/trunk/twisted/enterprise/adbapi.py", line 388, in _runOperation
    trans.execute(*args, **kw)
  File "/usr/lib/python2.4/site-packages/sqlite/main.py", line 244, in execute
    self.rs = self.con.db.execute(SQL)
_sqlite.DatabaseError: no such table: testTable
===============================================================================
[ERROR]: twisted.trial.test.test_keyboard.TestInterruptInSetUp.test_interruptInSetUp

  File "/home/exarkun/Projects/Twisted/trunk/twisted/enterprise/adbapi.py", line 388, in _runOperation
    trans.execute(*args, **kw)
  File "/usr/lib/python2.4/site-packages/gadfly/database.py", line 366, in execute
    cs[i] = cs[i].relbind(database)
  File "/usr/lib/python2.4/site-packages/gadfly/operations.py", line 268, in relbind
    raise NameError, `self.name` + ": cannot delete, no such table/view"
exceptions.NameError: 'CHILDTABLE': cannot delete, no such table/view
-------------------------------------------------------------------------------
Ran 2548 tests in 256.667s

FAILED (skips=38, expectedFailures=16, errors=14, successes=2483)
```

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)|@jml commented|
|-|-|

It's now officially beyond me.

From http://twistedmatrix.com/buildbot/full-2.3/builds/1407

```
2006/03/07 05:56:55 EST [SSHChannel session (0) on SSHService ssh-connection on ConchTestServer,0,127.0.0.1] remote close
2006/03/07 05:56:55 EST [SSHChannel session (0) on SSHService ssh-connection on ConchTestServer,0,127.0.0.1] closed cmd "echo goodbye"
2006/03/07 05:56:55 EST [ConchTestServer,0,127.0.0.1] connection lost
2006/03/07 05:56:55 EST [-] ERR(ssh): '2006/03/07 05:56 EST [SSHClientTransport,client] connection lost
	2006/03/07 05:56 EST [SSHClientTransport,client] Stopping factory <twisted.conch.client.direct.SSHClientFactory instance at 0xb788466c>
	2006/03/07 05:56 EST [-] Main loop terminated.
	'
2006/03/07 05:56:55 EST [-] Process.reapProcess()
2006/03/07 05:56:55 EST [-] Process.reapProcess(): ending process
2006/03/07 05:56:55 EST [-] PROCESS ENDED <Process pid=27945 status=-1>: 0
2006/03/07 05:56:55 EST [-] /home/buildbot/run/buildbot/full2.3/Twisted/twisted/conch/test/test_conch.py:52: exceptions.DeprecationWarning: unittest.assertEquals is deprecated.  Instead use the 'assertEquals' method on unittest.TestCase
2006/03/07 05:56:55 EST [-] /home/buildbot/run/buildbot/full2.3/Twisted/twisted/conch/test/test_conch.py:54: exceptions.DeprecationWarning: unittest.assertEquals is deprecated.  Instead use the 'assertEquals' method on unittest.TestCase
2006/03/07 05:56:55 EST [-] reapAllProcesses()
2006/03/07 05:56:55 EST [-] Process.reapProcess()
2006/03/07 05:56:55 EST [-] Process.reapProcess(): Failed to reap None:
2006/03/07 05:56:55 EST [-] Traceback (most recent call last):
	  File "/home/buildbot/run/buildbot/full2.3/Twisted/twisted/conch/test/test_conch.py", line 252, in tearDown
	    reactor.iterate()
	  File "/home/buildbot/run/buildbot/full2.3/Twisted/twisted/internet/base.py", line 363, in iterate
	    self.runUntilCurrent()
	  File "/home/buildbot/run/buildbot/full2.3/Twisted/twisted/internet/base.py", line 514, in runUntilCurrent
	    f(*a, **kw)
	  File "/home/buildbot/run/buildbot/full2.3/Twisted/twisted/internet/process.py", line 45, in reapAllProcesses
	    process.reapProcess()
	--- <exception caught here> ---
	  File "/home/buildbot/run/buildbot/full2.3/Twisted/twisted/internet/process.py", line 552, in reapProcess
	    pid, status = os.waitpid(self.pid, os.WNOHANG)
	exceptions.TypeError: an integer is required
```

**Comment by twisted-trac** [comment]
|<img alt="PenguinOfDoom's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|PenguinOfDoom commented|
|-|-|

I fixed the test_conch failure and added a few cosmetic changes. The rest looks fine.

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)|@jml set status to `closed`|
|-|-|

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_9"></a>|@hawkowl commented|
|-|-|

[mass edit] Removing review from closed tickets.
