### ISSUE TITLE
twisted.mail.smtp.py  timeout can cause runtime error

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#7149]
|<img alt="xing's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| xing reported|
|-|-|
|Trac ID|trac#1147|
|Type|defect|
|Created|2005-08-22 00:31:51Z|

<details><summary>Searchable metadata</summary>

```
trac-id__1147 1147
type__defect defect
reporter__xing xing
priority__low low
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__worksforme worksforme
component__mail mail
keywords__ 
time__1124670711000000 1124670711000000
changetime__1342800657000000 1342800657000000
version__ 
owner__ 
cc__exarkun cc__xing cc__mishok13 cc__argonemyth
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="xing's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|xing commented|
|-|-|

```
#!html
<pre>
Under Python2.4 and latest SVN twisted checkout.

Once in a while in my smtp app I would get the following.

Traceback (most recent call last):
  File "C:\Program Files\ActiveState Komodo 3.1\dbgp\pythonlib\dbgp\client.py",
line 590, in __init__
    execfile(file, globals, locals)
  File "E:\EPRESS\mail\dns_query.py", line 451, in ?
    reactor.run()
  File "E:\Python24\lib\site-packages\twisted\internet\posixbase.py", line 206,
in run
    self.mainLoop()
  File "E:\Python24\lib\site-packages\twisted\internet\posixbase.py", line 214,
in mainLoop
    self.runUntilCurrent()
--- &lt;exception caught here> ---
  File "E:\Python24\lib\site-packages\twisted\internet\base.py", line 541, in
runUntilCurrent
    call.func(*call.args, **call.kw)
  File "E:\Python24\lib\site-packages\twisted\protocols\policies.py", line 468,
in __timedOut
    self.timeoutConnection()
  File "E:\Python24\lib\site-packages\twisted\mail\smtp.py", line 1010, in
timeoutConnection
    self.log))
  File "E:\Python24\lib\site-packages\twisted\mail\smtp.py", line 1524, in sendError
    self.factory.result.errback(exc)
exceptions.AttributeError: SMTPSenderFactory instance has no attribute 'result'
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun commented|
|-|-|

```
#!html
<pre>
How?
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="xing's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|xing commented|
|-|-|

```
#!html
<pre>
The following SendMail is adopted from the sendmail function withn smtp class.
The exception is captured in the included _ebError() at the "UNKNOWN" error
part. SMTP_TIMEOUT is set to 5 seconds.

def SendMail(self, smtphost, envid, msg):
        body = StringIO(msg.Compose(envid)) ##need to convert string into a
readable object for smtp
        #if not hasattr(body,'read'):
        #body = StringIO(str(msg))
            
        env = msg.Get_Envelope(envid)
         
        d = defer.Deferred()
        factory = smtp.SMTPSenderFactory(msg.From,[env.To],body, d, 0,
self.SMTP_TIMEOUT)
        
        (mta_ip, mta_hostname) = Mail_Core().Get_VirtualMTA()
        
        factory.domain = mta_hostname
        reactor.connectTCP(mta_ip, 25, factory, self.SMTP_TIMEOUT) 
        return d

   def _ebError(self, err, server, envid, msg):
        self.Runners -= 1
        self.ErrorCount += 1 
        
        if err.value.__class__ == smtp.SMTPDeliveryError:
            print '=== DELIVERY ERROR ==='
            print err.value.code
            print err.value.resp
            print err.value.log  
            self.MX_Group.Log_Success(server, err.value.code, err.value.resp)
            self.Queue_Defer(envid, msg.MessageID)
            reactor.callLater(self.DELIVERY_INTERVAL, self.Delivery_Looper)
        elif err.value.__class__ == smtp.SMTPTimeoutError:
            print '=== SLOW MX ==='
            print err.value.code
            print err.value.resp
            print err.value.log
            self.MX_Group.Log_Failure(server,  0 , ' server timed out')
            self.Queue_Requeue(envid, msg.MessageID)
            reactor.callLater(self.DELIVERY_INTERVAL, self.Delivery_Looper)
        #considered mx errrors..
        elif(err.value.__class__ == smtp.SMTPConnectError
            or err.value.__class__ == error.TCPTimedOutError
            or err.value.__class__ == error.TimeoutError
            or err.value.__class__ == error.ConnectionRefusedError
            or err.value.__class__ == error.ConnectionLost):
            
            print '=== None Responsive MX ==='
            self.MX_Group.Log_Failure(server, 0 , ' server timed out')
            self.Queue_Requeue(envid, msg.MessageID)
            reactor.callLater(self.DELIVERY_INTERVAL, self.Delivery_Looper)
            
        else:
            print '=== UNKNOWN ERROR:' + str(err.value.__class__) + ' ==='
            self.MX_Group.Log_Failure(server, 0 , ' unknown' +
str(err.value.__class__))
            err.printTraceback()
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="xing's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|xing commented|
|-|-|

```
#!html
<pre>
so my calling would be link..

d = self.SendMail(...)
d.addCallback(...)
d.addErrback(...)

My original pasted code has tab problems. The error is throw to my errback
capture of the result but I was expecting some time of error.XXXX error, not an
general run-time attribute error from the smtp class.
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_6"></a>|@exarkun commented|
|-|-|

No luck reproducing this so far.  In general, I don't even see how the errback you defined could be invoked with such an attribute error, since traceback indicates that the Deferred is nowhere to be found.

It looks like there might be a race between issuing RSET, resetting the timeout, and dropping the connection, but I'm not sure this is actually the case you're encountering.

If you can produce a self-contained failing example that I can run to reproduce the traceback, I may have more luck tracking down the problem.  As a start, here's a program I wrote to try to produce the problem:

```python
if __name__ == '__main__':
    import smtperror
    raise SystemExit(smtperror.main())

from sys import stdout
from StringIO import StringIO

from zope.interface import implements

from twisted.internet import reactor
from twisted.internet.defer import succeed
from twisted.python import log
from twisted.cred.portal import IRealm, Portal
from twisted.cred.checkers import AllowAnonymousAccess
from twisted.mail.smtp import IMessageDelivery, IMessage, SMTPFactory, sendmail

from twisted.internet.protocol import Factory
Factory.noisy = False

INITIAL = 0.04
DECREMENT = 0.0001
INCREMENT = 0.0001

class Message:
    implements(IMessage)

    def lineReceived(self, line):
        pass


    def eomReceived(self):
        return succeed(None)


    def connectionLost(self):
        pass



class Mailbox:
    implements(IMessageDelivery)

    def receivedHeader(self, helo, origin, recipients):
        return ''


    def validateTo(self, user):
        return Message


    def validateFrom(self, helo, origin):
        return origin



class Realm:
    implements(IRealm)

    def requestAvatar(self, avatarId, mind, *interfaces):
        return IMessageDelivery, Mailbox(), lambda: None



def runServer():
    realm = Realm()
    portal = Portal(realm, [AllowAnonymousAccess()])
    f = SMTPFactory(portal)
    reactor.listenTCP(12345, f)



def runClient(timeout):
    print 'Sending mail with timeout', timeout
    d = sendmail(
        '127.0.0.1',
        'testuser@example.com',
        ['testuser@example.org'],
        StringIO('Hello'),
        port=12345,
        timeout=timeout)

    def cbSendmail(ign):
        runClient(timeout - DECREMENT)

    def ebSendmail(err):
        log.err(err, "Sendmail failed")
        runClient(timeout + INCREMENT)

    d.addCallbacks(cbSendmail, ebSendmail)



def main():
    log.startLogging(stdout)
    runServer()
    runClient(INITIAL)
    reactor.run()
    return 0
```

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|<img alt="mishok13's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_8"></a>|mishok13 commented|
|-|-|

Any updates in successfuly reproducing this one? I couldn't reproduce this one too (using exarkun's example).
Unless original submitter provides reproducable piece of code, I'd suggest closing this one.

**Comment by twisted-trac** [comment]
|[<img alt="argonemyth's avatar" src="https://avatars.githubusercontent.com/u/965739?s=50" width="50" height="50">](https://github.com/argonemyth)<a name="note_9"></a>|@argonemyth commented|
|-|-|

Need suggestions on what to do with this ticket...should we close this one?

**Comment by twisted-trac** [comment]
|[<img alt="argonemyth's avatar" src="https://avatars.githubusercontent.com/u/965739?s=50" width="50" height="50">](https://github.com/argonemyth)<a name="note_10"></a>|@argonemyth set status to `closed`|
|-|-|

Well, still can't re-produce the 'bug' after 7 years. I did modified the exarkun's script to use the **SMTPSenderFactory**, the current version of **sendmail** function no longer has the **timeout** parameter. If you guys couldn't re-produce it back then, I don't think it will ever be re-produced again, (due to the massive changes of the source code)...I am closing this ticket for good.
