### ISSUE TITLE
twisted/trial/ uses implements

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#7164]
|<img alt="Alex's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| Alex reported|
|-|-|
|Trac ID|trac#7164|
|Type|enhancement|
|Created|2014-04-16 00:04:38Z|
|Branch|https://github.com/twisted/twisted/tree/implementsIsLame-7164|

It should use @implementer.

<details><summary>Searchable metadata</summary>

```
trac-id__7164 7164
type__enhancement enhancement
reporter__Alex Alex
priority__normal normal
milestone__Python_3_x Python-3.x
branch__branches_implementsIsLame_7164 branches/implementsIsLame-7164
branch_author__wsanchez wsanchez
status__closed closed
resolution__fixed fixed
component__core core
keywords__ 
time__1397606678000000 1397606678000000
changetime__1397611845000000 1397611845000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|<img alt="Alex's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_1"></a>|Alex commented|
|-|-|

This is resolved by https://github.com/twisted/twisted/pull/19

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)<a name="note_2"></a>|@wsanchez commented|
|-|-|

(In [42322]) Branchy branches of branching

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)<a name="note_3"></a>|@wsanchez commented|
|-|-|

reviewed pending build

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)<a name="note_4"></a>|@wsanchez commented|
|-|-|

Tests passed

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)<a name="note_5"></a>|@wsanchez set status to `closed`|
|-|-|

Post-commit didn't auto-close.  In case anyone cares, here's a traceback:

```
2014-04-15 19:27:36-0600 [-] Starting factory <twisted.spread.pb.PBClientFactory instance at 0xb75e5f4c>
2014-04-15 19:27:37-0600 [Broker,client] postCommit result Traceback (most recent call last):
2014-04-15 19:27:37-0600 [Broker,client]   File "/srv/trac/config/trac-post-commit-hook", line 290, in <module>
2014-04-15 19:27:37-0600 [Broker,client]     CommitHook()
2014-04-15 19:27:37-0600 [Broker,client]   File "/srv/trac/config/trac-post-commit-hook", line 151, in __init__
2014-04-15 19:27:37-0600 [Broker,client]     chgset = repos.get_changeset(rev)
2014-04-15 19:27:37-0600 [Broker,client]   File "/srv/trac/.local/lib/python2.7/site-packages/trac/versioncontrol/cache.py", line 61, in get_changeset
2014-04-15 19:27:37-0600 [Broker,client]     return CachedChangeset(self.repos, self.repos.normalize_rev(rev),
2014-04-15 19:27:37-0600 [Broker,client]   File "/srv/trac/.local/lib/python2.7/site-packages/trac/versioncontrol/svn_fs.py", line 388, in normalize_rev
2014-04-15 19:27:37-0600 [Broker,client]     raise NoSuchChangeset(rev)
2014-04-15 19:27:37-0600 [Broker,client] trac.versioncontrol.api.NoSuchChangeset: No changeset 42325 in the repository
2014-04-15 19:27:37-0600 [Broker,client] 
2014-04-15 19:27:37-0600 [Broker,client] Stopping factory <twisted.spread.pb.PBClientFactory instance at 0xb75e5f4c>
2014-04-15 19:27:37-0600 [-] Main loop terminated.
```
