### ISSUE TITLE
wxreactor completely broken if there are any startup triggers.

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#7190]
|[<img alt="jyknight's avatar" src="https://avatars.githubusercontent.com/u/873903?s=50" width="50" height="50">](https://github.com/jyknight)| @jyknight reported|
|-|-|
|Trac ID|trac#1574|
|Type|defect|
|Created|2006-03-15 00:14:50Z|

```

Traceback (most recent call last):
  File "test.py", line 104, in ?
    reactor.run()
  File "C:\Programs\Python24\lib\site-packages\twisted\internet\wxreactor.py", line 84, in run
    self.interleave(wxCallAfter)
  File "C:\Programs\Python24\lib\site-packages\twisted\internet\threadedselectreactor.py", line 268, in interleave
    loop.next()
  File "C:\Programs\Python24\lib\site-packages\twisted\internet\threadedselectreactor.py", line 241, in _interleave
    self.runUntilCurrent()
--- <exception caught here> ---
  File "C:\Programs\Python24\lib\site-packages\twisted\internet\base.py", line 541, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "C:\Programs\Python24\lib\site-packages\twisted\internet\base.py", line 397, in _continueSystemEvent
    for callList in sysEvtTriggers[1], sysEvtTriggers[2]:
exceptions.TypeError: unsubscriptable object
```

<foom> the problem is in wxreactor.py

<foom> it calls self.startRunning followed by self.interleave

<foom> and the second actually calls startRunning by itself

<foom> so replacing startRunning/interleave lines with just self.interleave(wxCallAfter, installSignalHandlers=installSignalHandlers) should fix it

<Micah71381> Yep, that fixed it.

<Micah71381> Thanks a lot for the help.

If it makes sense to you, please make the above change.

<details><summary>Searchable metadata</summary>

```
trac-id__1574 1574
type__defect defect
reporter__jknight jknight
priority__lowest lowest
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__None None
time__1142381690000000 1142381690000000
changetime__1474198569965514 1474198569965514
version__ 
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="radix's avatar" src="https://avatars.githubusercontent.com/u/227068?s=50" width="50" height="50">](https://github.com/radix)|@radix commented|
|-|-|

Milestone Twisted-2.3 deleted

**Comment by twisted-trac** [comment]
|[<img alt="radix's avatar" src="https://avatars.githubusercontent.com/u/227068?s=50" width="50" height="50">](https://github.com/radix)|@radix set owner to @exarkun|
|-|-|

```
===================================================================
--- twisted/internet/wxreactor.py       (revision 16887)
+++ twisted/internet/wxreactor.py       (working copy)
@@ -80,8 +80,8 @@
         if not hasattr(self, "wxapp"):
             log.msg("registerWxApp() was not called on reactor, this is probably an error.")
             self.registerWxApp(DummyApp(0))
-        self.startRunning(installSignalHandlers=installSignalHandlers)
-        self.interleave(wxCallAfter)
+        self.interleave(wxCallAfter, 
+                        installSignalHandlers=installSignalHandlers)
         self.callLater(0, self._installSignalHandlersAgain)
         self.wxapp.MainLoop()
         
```

I would write a test for this but TSR is untestable.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun removed owner|
|-|-|

Code can't change without tests.  I'm rejecting this change until someone who cares about wxreactor enough to do the necessary work does the necessary work.

This should not block any releases of Twisted.  wxreactor never worked, it will probably never work.

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)<a name="note_5"></a>|@itamarst set owner to @exarkun|
|-|-|

I have provided a manual test, though not an automated one (kill wxdemo with Alt-F4).

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_6"></a>|@exarkun set status to `closed`|
|-|-|

(In [19070]) Merge wxreactor-1235+1574+1688

Author: itamar
Reviewer: exarkun
Fixes [#7123](https://github.com/twisted/twisted/issues/7123)
Fixes [#7190](https://github.com/twisted/twisted/issues/7190)
Fixes [#7191](https://github.com/twisted/twisted/issues/7191)

This fixes numerous problems with wxreactor:

  * startup and shutdown events are now supported
  * signal handlers will not be installed if installSignalHandlers=False
    is passed to run
  * a manual acceptance test has been added so the level of workingness
    of wxreactor can be examined

This also fixes the problem where modal GUI actions (displaying menus,
modal dialogs, resizing windows, etc) would block Twisted events from
being processed.  On Linux, Windows, and OS X Twisted events will now
be serviced in these cases.

Additionally, _threadedselect no longer creates daemon threads and
the wxdemo has been simplified by the removal of code which was only
in support of acceptance testing (which is now a separate program).

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_8"></a>|@hawkowl commented|
|-|-|

[mass edit] Removing the review tag from closed tickets
