### ISSUE TITLE
domish.Element and deepcopy problem

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#7246]
|<img alt="arthur.lutz's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| arthur.lutz reported|
|-|-|
|Trac ID|trac#724|
|Type|defect|
|Created|2004-09-20 13:46:18Z|

Attachments:

* [test_domish.py.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/b19/b19dc177a07ce563e09b457f13bf5a673ddfbba1/2c7cb79ba985b8c73a92d104ae0a73fdadf0c832.patch) (1248 bytes) - added by ralphm on 2007-05-03 12:08:18Z - deepcopy test

<details><summary>Searchable metadata</summary>

```
trac-id__724 724
type__defect defect
reporter__arthur_lutz arthur.lutz
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__ 
component__words words
keywords__ 
time__1095687978000000 1095687978000000
changetime__1178276281000000 1178276281000000
version__ 
owner__ 
cc__ralphm cc__dizzyd cc__arthur.lutz
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="arthur.lutz's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|arthur.lutz commented|
|-|-|

```
#!html
<pre>
I'm having a problem with domish.Element, here it is (isolated) : 

from twisted.xish import domish
from copy import deepcopy

invitation = domish.Element(('jabber:client', 'message'))
invitation2 = deepcopy(invitation)

gives me : 

Traceback (most recent call last):
  File "modules/isolated_bug.py", line 5, in ?
    invitation2 = deepcopy(invitI'm having a problem with domish.Element, here
it is (isolated) : 

from twisted.xish import domish
from copy import deepcopy

invitation = domish.Element(('jabber:client', 'message'))
invitation2 = deepcopy(invitation)

gives me : 

Traceback (most recent call last):
  File "modules/isolated_bug.py", line 5, in ?
    invitation2 = deepcopy(invitation)
  File "/usr/lib/python2.3/copy.py", line 198, in deepcopy
    rv = reductor(2)
TypeError: 'NoneType' object is not callable


Python version : 
Python 2.3.4 (#2, Jul  5 2004, 09:15:05) 
[GCC 3.3.4 (Debian 1:3.3.4-2)] on linux2
Type "help", "copyright", "credits" or "license" for more information.


Hope this is enough for a diagnostic. ation)
  File "/usr/lib/python2.3/copy.py", line 198, in deepcopy
    rv = reductor(2)
TypeError: 'NoneType' object is not callable


Python version : 
Python 2.3.4 (#2, Jul  5 2004, 09:15:05) 
[GCC 3.3.4 (Debian 1:3.3.4-2)] on linux2
Type "help", "copyright", "credits" or "license" for more information.


Hope this is enough for a diagnostic.
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="ralphm's avatar" src="https://avatars.githubusercontent.com/u/116741?s=50" width="50" height="50">](https://github.com/ralphm)|@ralphm set owner to @ralphm<br>@ralphm set status to `assigned`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="ralphm's avatar" src="https://avatars.githubusercontent.com/u/116741?s=50" width="50" height="50">](https://github.com/ralphm)<a name="note_3"></a>|@ralphm commented|
|-|-|

I created the above test to see if this issue is still present. It seems to me `copy.deepcopy` works fine now. I'm not sure if the semantics are ok, though.

When making copies of an element that has a parent, you typically don't want to make a copy of that parent. This also poses problems when copying lists of elements (for example when copying over only children elements). I suppose a deepcopy should only copy 'downwards', but this requires `Element` to implement `__deepcopy__`.

**Comment by twisted-trac** [comment]
|[<img alt="ralphm's avatar" src="https://avatars.githubusercontent.com/u/116741?s=50" width="50" height="50">](https://github.com/ralphm)|@ralphm set status to `new`|
|-|-|

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
