### ISSUE TITLE
trial -M fails (method testing)

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#7265]
|<img alt="benedikt's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| benedikt reported|
|-|-|
|Trac ID|trac#321|
|Type|defect|
|Created|2003-10-07 21:25:41Z|

Attachments:

* [patch_twisted_trial_runner](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/5f6/5f6955d227a320c7f1f6c7da2a6d96a851a8118f/7f0251b5d61cbfd53745b16d35e99dd018af8e4b) (617 bytes) - added by benedikt on 2003-10-07 21:25:41Z - 

<details><summary>Searchable metadata</summary>

```
trac-id__321 321
type__defect defect
reporter__benedikt benedikt
priority__high high
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__ 
keywords__ 
time__1065561941000000 1065561941000000
changetime__1065562764000000 1065562764000000
version__ 
owner__ 
cc__benedikt
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="benedikt's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|benedikt commented|
|-|-|

```
#!html
<pre>
python2.3-twisted_1.0.7+1.0.8alpha3-1 on debian sid

% trial2.3 -M twisted.test.test_text.WrapTest.test_wordMatch   
Traceback (most recent call last):
  File "/usr/bin/trial2.3", line 35, in ?
    run()
  File "/usr/lib/python2.3/site-packages/twisted/scripts/trial.py", line 302, in run
    suite.run(reporter, config['random'])
  File "/usr/lib/python2.3/site-packages/twisted/trial/unittest.py", line 400,
in run
    test.runTests(output)
  File "/usr/lib/python2.3/site-packages/twisted/trial/runner.py", line 66, in
runTests
    method = getattr(testCase, self.methodName)
AttributeError: SingletonRunner instance has no attribute 'methodName'

After applying the patch:
% trial2.3 -M twisted.test.test_text.WrapTest.test_wordMatch
.
-------------------------------------------------------------------------------
Ran 1 tests in 0.136s

OK
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="moshez's avatar" src="https://avatars.githubusercontent.com/u/422703?s=50" width="50" height="50">](https://github.com/moshez)|@moshez commented|
|-|-|

```
#!html
<pre>
/cvs/Twisted/twisted/trial/runner.py,v  &lt;--  runner.py
new revision: 1.9; previous revision: 1.8

Fixed, resolving.
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
