### ISSUE TITLE
twistd dns --secondary has been completely broken since twisted 13.2.0

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#7408]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)| @glyph reported|
|-|-|
|Trac ID|trac#7408|
|Type|release blocker: regression|
|Created|2014-05-24 06:59:55Z|
|Branch|https://github.com/twisted/twisted/tree/secondary-dns-lookup-error-7408|

`twistd -n dns --secondary 66.35.39.66/twistedmatrix.com --port 53` on every version of Twisted since Twisted 13.2.0 has resulted in simply this traceback in a loop:

```
2014-05-24 06:36:05+0000 [DNSDatagramProtocol (UDP)] Unhandled Error
	Traceback (most recent call last):
	  File "/srv/names/.virtualenvs/names/site-packages/twisted/internet/defer.py", line 139, in maybeDeferred
	    result = f(*args, **kw)
	  File "/srv/names/.virtualenvs/names/site-packages/twisted/names/common.py", line 81, in lookupAddress
	    return self._lookup(name, dns.IN, dns.A, timeout)
	  File "/srv/names/.virtualenvs/names/site-packages/twisted/names/resolve.py", line 79, in _lookup
	    d = self.resolvers[0].query(q, timeout)
	  File "/srv/names/.virtualenvs/names/site-packages/twisted/names/common.py", line 73, in query
	    return defer.maybeDeferred(method, query.name.name, timeout)
	--- <exception caught here> ---
	  File "/srv/names/.virtualenvs/names/site-packages/twisted/internet/defer.py", line 139, in maybeDeferred
	    result = f(*args, **kw)
	  File "/srv/names/.virtualenvs/names/site-packages/twisted/names/common.py", line 81, in lookupAddress
	    return self._lookup(name, dns.IN, dns.A, timeout)
	  File "/srv/names/.virtualenvs/names/site-packages/twisted/names/secondary.py", line 151, in _lookup
	    return FileAuthority.__dict__['_lookup'](self, name, cls, type, timeout)
	  File "/srv/names/.virtualenvs/names/site-packages/twisted/names/authority.py", line 181, in _lookup
	    additionalInformation = self._additionalRecords(
	exceptions.AttributeError: SecondaryAuthority instance has no attribute '_additionalRecords'
```

The server runs and listens on a port but no names are resolvable.

I've rolled back Twisted's own secondary DNS to 13.1.0 so that it's functioning again, but it would be great to fix this ASAP.

<details><summary>Searchable metadata</summary>

```
trac-id__7408 7408
type__release_blocker__regression release blocker: regression
reporter__glyph glyph
priority__highest highest
milestone__None None
branch__branches_secondary_dns_lookup_error_7408 branches/secondary-dns-lookup-error-7408
branch_author__exarkun exarkun
status__closed closed
resolution__fixed fixed
component__names names
keywords__None None
time__1400914795000000 1400914795000000
changetime__1474197555542286 1474197555542286
version__None None
owner__exarkun exarkun
cc__hawkowl
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="wallrj's avatar" src="https://avatars.githubusercontent.com/u/978965?s=50" width="50" height="50">](https://github.com/wallrj)<a name="note_2"></a>|@wallrj set status to `assigned`|
|-|-|

A few notes:
 * I think this bug was introduced in r39893 which was when `SecondaryAuthority._lookup` started calling out to `FileAuthority._additionalRecords`.
 * It wasn't detected because `SecondaryAuthority` has very few tests. See [#6454](https://github.com/twisted/twisted/issues/6454).
 * The basic problem seems to be that `SecondaryAuthority` doesn't subclass `FileAuthority` as the comment says here [twisted/names/secondary.py#L151](twisted/names/secondary.py#L151)
 * ..but that's because it can't. `FileAuthority` is too tightly coupled to the loading of records from a file. We need an in-memory authority described in [#4686](https://github.com/twisted/twisted/issues/4686). Such a thing has been hacked together in [twisted/names/test/test_names.py#L28](twisted/names/test/test_names.py#L28)
 * But even then, `SecondaryAuthority` shouldn't subclass but instead should *have* a MemoryAuthority attribute and call its _lookup method. Although it would be better if we could find a way to call a public API instead.

So perhaps the proper way forward is:
 * [#4686](https://github.com/twisted/twisted/issues/4686) Implement a MemoryAuthority
 * [#6454](https://github.com/twisted/twisted/issues/6454) Add tests for the current SecondaryAuthority
 * [#7408](https://github.com/twisted/twisted/issues/7408) Finally refactor SecondaryAuthority to use MemoryAuthority.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_3"></a>|@glyph commented|
|-|-|

That seems like a reasonable plan, except won't the tests in [#6454](https://github.com/twisted/twisted/issues/6454) necessarily be failing without the fix in [#7408](https://github.com/twisted/twisted/issues/7408)?  It seems like those may need to land together.

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_4"></a>|@hawkowl commented|
|-|-|

Marking this as a 14.1 blocker, since I think it'd be nice to get a release out which didn't break Twisted's own infra :)

ref: [#7335](https://github.com/twisted/twisted/issues/7335)

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun set owner to @exarkun<br>@exarkun set status to `new`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_6"></a>|@exarkun commented|
|-|-|

(In [43044]) Branching to 'secondary-dns-lookup-error-7408'

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_7"></a>|@exarkun commented|
|-|-|

> So perhaps the proper way forward is:
> [#4686](https://github.com/twisted/twisted/issues/4686) Implement a MemoryAuthority
> [#6454](https://github.com/twisted/twisted/issues/6454) Add tests for the current SecondaryAuthority
> [#7408](https://github.com/twisted/twisted/issues/7408) Finally refactor SecondaryAuthority to use MemoryAuthority.

I agree those steps make sense.  However since the release manager marked this as a blocker for 14.1 I went ahead and implemented a more limited fix.  I made `SecondaryAuthority` just subclass `FileAuthority`.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_8"></a>|@glyph commented|
|-|-|

Replying to [exarkun](#note_7):
> > So perhaps the proper way forward is:
> > [#4686](https://github.com/twisted/twisted/issues/4686) Implement a MemoryAuthority
> > [#6454](https://github.com/twisted/twisted/issues/6454) Add tests for the current SecondaryAuthority
> > [#7408](https://github.com/twisted/twisted/issues/7408) Finally refactor SecondaryAuthority to use MemoryAuthority.
> 
> I agree those steps make sense.  However since the release manager marked this as a blocker for 14.1 I went ahead and implemented a more limited fix.  I made `SecondaryAuthority` just subclass `FileAuthority`.

Those tickets can feel free to stay open, in the meanwhile.  Thanks for tackling this.

  1. I really don't understand what twistedchecker's deal is, but it looks like [one of the "new" errors it produced](https://buildbot.twistedmatrix.com/builders/twistedchecker/builds/2207/steps/run-twistedchecker/logs/new%20twistedchecker%20errors) is actually valid; the one about blank lines.
  2. As far as I can tell, this subclassing actually _doesn't_ inadvertently expose any new public API attributes.  Great.

I guess I don't have much more to add; I manually tested and it seems to address the issue - land away!

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_9"></a>|@exarkun set status to `closed`|
|-|-|

(In [43058]) Merge secondary-dns-lookup-error-7408 

Author: exarkun (sponsored by Hybrid Logic, Ltd.)
Reviewer: glyph
Fixes: [#7408](https://github.com/twisted/twisted/issues/7408)

Fix a regression in `SecondaryAuthority` which prevented it from working in most 
basic uses.

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_10"></a>|@hawkowl commented|
|-|-|

Ticket retargeted after milestone deleted

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_11"></a>|@hawkowl commented|
|-|-|

[mass edit] Removing review from closed tickets.
