### ISSUE TITLE
DirDBM Error (copy_reg exception)

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#7411]
|[<img alt="radix's avatar" src="https://avatars.githubusercontent.com/u/227068?s=50" width="50" height="50">](https://github.com/radix)| @radix reported|
|-|-|
|Trac ID|trac#46|
|Type|defect|
|Created|2003-07-12 20:31:13Z|

<details><summary>Searchable metadata</summary>

```
trac-id__46 46
type__defect defect
reporter__radix radix
priority__high high
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__ 
keywords__ 
time__1058041873000000 1058041873000000
changetime__1058185209000000 1058185209000000
version__ 
owner__ 
cc__radix
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="radix's avatar" src="https://avatars.githubusercontent.com/u/227068?s=50" width="50" height="50">](https://github.com/radix)|@radix commented|
|-|-|

```
#!html
<pre>
Since last update of Twisted, I've got this error :

&lt;i>
Traceback (most recent call last):
File "./project_flow.py", line 97, in ?
d['project_flow'] = project_flow
File
"/home/gravis/src/python/cvs/Twisted/twisted/persisted/dirdbm.py",
line 336, in __setitem__
v = cPickle.dumps(v)
File "/usr/lib/python2.2/copy_reg.py", line 58, in
_reduce
state = base(self)
TypeError: connect() argument 1 must be string, not
Connection
&lt;/i>

I use the same code as in the howto.

(like :
d['project_flow'] = 1
project_flow +=1
d['project_flow'] = project_flow
)

</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)|@itamarst commented|
|-|-|

```
#!html
<pre>
This was moved from the old tracker, yes? I propose we close
it, it seems to be an issue pickling something, nothing to
do with dirdbm.

</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="radix's avatar" src="https://avatars.githubusercontent.com/u/227068?s=50" width="50" height="50">](https://github.com/radix)|@radix commented|
|-|-|

```
#!html
<pre>
Yes, it was moved from the old tracker.

I agree with your assessment. I'm closing. Anyone can feel
free to reopen the bug if they decide it's valid.

</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
