### ISSUE TITLE
test failures run from -14.0.0

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#7422]
|<img alt="idella's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| idella reported|
|-|-|
|Trac ID|trac#7422|
|Type|defect|
|Created|2014-05-27 07:20:15Z|

The first 5 are cured by 

sed -e 's:test_dataReceivedThrows:_&:' \
    -e 's:test_resumeProducingThrows:_&:' \
    -e 's:test_resumeProducingAbortLater:_&:' \
    -e 's:test_resumeProducingAbort:_&:' \
    -e 's:test_fullWriteBufferAfterByteExchange:_&:' \
    -i twisted/internet/test/test_tcp.py

On running, the output indicates they are failing called from test_tls.py.  They pass fine when test_tls.py is run however I presume they are run all over again called from test_tcp.py.

--------------------------------------------------

NEXT

===============================================================
 [FAIL]
Traceback (most recent call last):
  File "/mnt/gen2/TmpDir/portage/dev-python/twisted-core-14.0.0/work/TwistedCore-14.0.0/twisted/python/test/test_dist3.py", line 42, in test_exist
    "Module {0} does not exist".format(module))
  File "/mnt/gen2/TmpDir/portage/dev-python/twisted-core-14.0.0/work/TwistedCore-14.0.0/twisted/trial/_synctest.py", line 308, in assertTrue
    raise self.failureException(msg)
twisted.trial.unittest.FailTest: Module twisted.names does not exist

twisted.python.test.test_dist3.ModulesToInstallTests.test_exist

--------------------------------------------------
$ python -c "from twisted import names"
yields success, so having twisted names already installed appears to not suite this testsuite so I don't know what's going on.

--------------------------------------------------

NEXT

===============================================================
[FAIL]
Traceback (most recent call last):
  File "/mnt/gen2/TmpDir/portage/dev-python/twisted-core-14.0.0/work/TwistedCore-14.0.0/twisted/scripts/test/test_tap2deb.py", line 86, in test_basicOperation
    ['build-stamp', 'debian', 'install-stamp', 'lemon.tap'])
  File "/mnt/gen2/TmpDir/portage/dev-python/twisted-core-14.0.0/work/TwistedCore-14.0.0/twisted/trial/_synctest.py", line 356, in assertEqual
    % (msg, pformat(first), pformat(second)))
twisted.trial.unittest.FailTest: not equal:
a = ['debian', 'lemon.tap']
b = ['build-stamp', 'debian', 'install-stamp', 'lemon.tap']

--------------------------------------------------

NEXT

===================================================================
[ERROR]
Traceback (most recent call last):
  File "/mnt/gen2/TmpDir/portage/dev-python/twisted-core-14.0.0/work/TwistedCore-14.0.0/twisted/protocols/tls.py", line 554, in _write
    sent = self._tlsConnection.send(toSend)
  File "/usr/lib64/python2.7/site-packages/OpenSSL/SSL.py", line 950, in send
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib64/python2.7/site-packages/OpenSSL/SSL.py", line 871, in _raise_ssl_error
    _raise_current_error()
  File "/usr/lib64/python2.7/site-packages/OpenSSL/_util.py", line 22, in exception_from_error_queue
    raise exceptionType(errors)
OpenSSL.SSL.Error: [('rsa routines', 'RSA_sign', 'digest too big for rsa key'), ('SSL routines', 'SSL3_SEND_SERVER_KEY_EXCHANGE', 'EVP lib')]

--------------------------------------------------

NEXT

===============================================================
[ERROR]
Traceback (most recent call last):
  File "/mnt/gen2/TmpDir/portage/dev-python/twisted-core-14.0.0/work/TwistedCore-14.0.0/twisted/internet/test/connectionmixins.py", line 320, in test_logPrefix
    self.assertIn("Custom Client", client.system)
  File "/mnt/gen2/TmpDir/portage/dev-python/twisted-core-14.0.0/work/TwistedCore-14.0.0/twisted/trial/_synctest.py", line 414, in assertIn
    if containee not in container:
exceptions.TypeError: argument of type 'NoneType' is not iterable

--------------------------------------------------

NEXT

===============================================================
[ERROR]
Traceback (most recent call last):
  File "/mnt/gen2/TmpDir/portage/dev-python/twisted-core-14.0.0/work/TwistedCore-14.0.0/twisted/trial/runner.py", line 498, in loadPackage
    module = modinfo.load()
  File "/mnt/gen2/TmpDir/portage/dev-python/twisted-core-14.0.0/work/TwistedCore-14.0.0/twisted/python/modules.py", line 383, in load
    return self.pathEntry.pythonPath.moduleLoader(self.name)
  File "/mnt/gen2/TmpDir/portage/dev-python/twisted-core-14.0.0/work/TwistedCore-14.0.0/twisted/python/reflect.py", line 303, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "/mnt/gen2/TmpDir/portage/dev-python/twisted-core-14.0.0/work/TwistedCore-14.0.0/twisted/python/reflect.py", line 250, in _importAndCheckStack
    reraise(excValue, excTraceback)
  File "/mnt/gen2/TmpDir/portage/dev-python/twisted-core-14.0.0/work/TwistedCore-14.0.0/twisted/python/test/test_release.py", line 29, in <module>
    from twisted.web.microdom import parseXMLString
exceptions.ImportError: No module named web.microdom

twisted.python.test.test_release

This again relies on importing another module of the twisted fleet.

--------------------------------------------------

NEXT

===============================================================
[ERROR]
Traceback (most recent call last):
  File "/mnt/gen2/TmpDir/portage/dev-python/twisted-core-14.0.0/work/TwistedCore-14.0.0/twisted/python/test/test_shellcomp.py", line 25, in runTest
    return test_genZshFunction(self, cmdName, optionsFQPN)
  File "/mnt/gen2/TmpDir/portage/dev-python/twisted-core-14.0.0/work/TwistedCore-14.0.0/twisted/python/test/test_shellcomp.py", line 105, in test_genZshFunction
    "zsh:3"])
  File "/mnt/gen2/TmpDir/portage/dev-python/twisted-core-14.0.0/work/TwistedCore-14.0.0/twisted/application/app.py", line 604, in parseOptions
    usage.Options.parseOptions(self, options)
  File "/mnt/gen2/TmpDir/portage/dev-python/twisted-core-14.0.0/work/TwistedCore-14.0.0/twisted/python/usage.py", line 229, in parseOptions
    self._shellCompFile)
  File "/mnt/gen2/TmpDir/portage/dev-python/twisted-core-14.0.0/work/TwistedCore-14.0.0/twisted/python/_shellcomp.py", line 106, in shellComplete
    subOptions = parser()
  File "/mnt/gen2/TmpDir/portage/dev-python/twisted-core-14.0.0/work/TwistedCore-14.0.0/twisted/application/app.py", line 628, in <lambda>
    lambda plug=plug: plug.options(),
  File "/mnt/gen2/TmpDir/portage/dev-python/twisted-core-14.0.0/work/TwistedCore-14.0.0/twisted/application/service.py", line 74, in get
    return namedAny(self.module).Options
  File "/mnt/gen2/TmpDir/portage/dev-python/twisted-core-14.0.0/work/TwistedCore-14.0.0/twisted/python/reflect.py", line 314, in namedAny
    obj = getattr(obj, n)
  File "/mnt/gen2/TmpDir/portage/dev-python/twisted-core-14.0.0/work/TwistedCore-14.0.0/twisted/python/deprecate.py", line 399, in __getattribute__
    value = getattr(state._module, name)
exceptions.AttributeError: 'module' object has no attribute 'runner

twisted.scripts.test.test_scripts.ZshIntegrationTestCase.test_genZshFunction_twistd
--------------------------------------------------

NEXT

===============================================================
[ERROR]
Traceback (most recent call last):
  File "/mnt/gen2/TmpDir/portage/dev-python/twisted-core-14.0.0/work/TwistedCore-14.0.0/twisted/protocols/tls.py", line 360, in _flushReceiveBIO
    bytes = self._tlsConnection.recv(2 ** 15)
  File "/usr/lib64/python2.7/site-packages/OpenSSL/SSL.py", line 995, in recv
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib64/python2.7/site-packages/OpenSSL/SSL.py", line 871, in _raise_ssl_error
    _raise_current_error()
  File "/usr/lib64/python2.7/site-packages/OpenSSL/_util.py", line 22, in exception_from_error_queue
    raise exceptionType(errors)
OpenSSL.SSL.Error: [('SSL routines', 'SSL23_READ', 'ssl handshake failure')]

twisted.test.test_ssl.StolenTCPTestCase.test_properlyCloseFiles

--------------------------------------------------

NEXT

===============================================================

[ERROR]
Traceback (most recent call last):
  File "/mnt/gen2/TmpDir/portage/dev-python/twisted-core-14.0.0/work/TwistedCore-14.0.0/twisted/test/test_twisted.py", line 689, in test_loreDeprecation
    reflect.namedAny("twisted.lore")
  File "/mnt/gen2/TmpDir/portage/dev-python/twisted-core-14.0.0/work/TwistedCore-14.0.0/twisted/python/reflect.py", line 314, in namedAny
    obj = getattr(obj, n)
  File "/mnt/gen2/TmpDir/portage/dev-python/twisted-core-14.0.0/work/TwistedCore-14.0.0/twisted/python/deprecate.py", line 399, in __getattribute__
    value = getattr(state._module, name)
exceptions.AttributeError: 'module' object has no attribute 'lore'

twisted.test.test_twisted.LoreDeprecationTests.test_loreDeprecation
------------------------------------------------------------------
Ran 5839 tests in 73.440s

FAILED (skips=680, expectedFailures=4, failures=3, errors=19, successes=5133)

Some of these I suspect are spurious, mainly the ones that can't import twisted.web and twisted.names, looks more like setup trickery.  Why there are 6 cited as 
==========
[ERROR]

yet errors=19 I also don't know.  Just reporting them as they came.

<details><summary>Searchable metadata</summary>

```
trac-id__7422 7422
type__defect defect
reporter__idella idella
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__invalid invalid
component__core core
keywords__tests tests
time__1401175215000000 1401175215000000
changetime__1401272572000000 1401272572000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)<a name="note_1"></a>|@itamarst commented|
|-|-|

I get the impression you only installed the Core tarball? As opposed to full Twisted?

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_2"></a>|@exarkun set status to `closed`|
|-|-|

Please open separate issues for different problems.

Most of these look like issues due to how your environment is configured or how Twisted is ... installed (if it is installed, I can't really tell).

There is already an [ticket:6920 open ticket for test_basicOperation failing on Gentoo].

The TLS failures may be new.  Please open a ticket describing just those - including the versions of pyOpenSSL and OpenSSL you're using.

Thanks.

**Comment by twisted-trac** [comment]
|<img alt="idella's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_3"></a>|idella commented|
|-|-|

well no surprises here. I publicly predicted exactly this.

All beyond the TLS failures are indeed due to the clash between the required setup of the testsuite and the gentoo something-or-other. I don't see it warrants an explicit description here.
The already open ticket I know about. I made it and yes it's still open.

I have not one but two new tickets to make. One for the tls failures, one for twisted-pair.
