### ISSUE TITLE
FileBodyProducer may be stopped twice if the conn is closed remotely

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#7457]
|<img alt="immerrr's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| immerrr reported|
|-|-|
|Trac ID|trac#7457|
|Type|defect|
|Created|2014-06-02 13:16:32Z|

Here's what I see in the traceback:

```
Unexpected exception from twisted.web.client.FileBodyProducer.stopProducing
Traceback (most recent call last):
  File "/home/immerrr/.conda/envs/twisted14/lib/python2.7/site-packages/twisted/internet/endpoints.py", line 128, in connectionLost
    return self._wrappedProtocol.connectionLost(reason)
  File "/home/immerrr/.conda/envs/twisted14/lib/python2.7/site-packages/twisted/web/_newclient.py", line 911, in dispatcher
    return func(*args, **kwargs)
  File "/home/immerrr/.conda/envs/twisted14/lib/python2.7/site-packages/twisted/web/_newclient.py", line 1564, in _connectionLost_TRANSMITTING
    self._currentRequest.stopWriting()
  File "/home/immerrr/.conda/envs/twisted14/lib/python2.7/site-packages/twisted/web/_newclient.py", line 812, in stopWriting
    _callAppFunction(self.bodyProducer.stopProducing)
--- <exception caught here> ---
  File "/home/immerrr/.conda/envs/twisted14/lib/python2.7/site-packages/twisted/web/_newclient.py", line 192, in _callAppFunction
    function()
  File "/home/immerrr/.conda/envs/twisted14/lib/python2.7/site-packages/twisted/web/client.py", line 1016, in stopProducing
    self._task.stop()
  File "/home/immerrr/.conda/envs/twisted14/lib/python2.7/site-packages/twisted/internet/task.py", line 464, in stop
    self._checkFinish()
  File "/home/immerrr/.conda/envs/twisted14/lib/python2.7/site-packages/twisted/internet/task.py", line 474, in _checkFinish
    raise self._completionState
```

The sequence of actions that lead to this stacktrace are defined in `twisted.internet.tcp.Connection.connectionLost`:

```
t.i.tcp.connectionLost
|
+-> t.abstract.FileDescriptor.connectionLost(...)
|   -> FileBodyProducer.stopProducing()
|   -> t.i.task.CooperativeTask.stop()
|
`-> t.w._newclient.HTTP11ClientProtocol.connectionLost(...)
    -> t.w._newclient.makeStatefulDispatcher.dispatcher(...)
    -> t.w._newclient.HTTP11ClientProtocol._connectionLost_TRANSMITTING(...)
    -> t.w._newclient.Request.stopWriting()
    -> FileBodyProducer.stopProducing()
    -> t.i.task.CooperativeTask.stop()
    -> t.i.task._checkFinish()
    -- raise self._completionState
```

It appears that a simple guard in `FileBodyProducer.stopProducing` is enough to prevent this error.  I'm sending a minimal test case to reproduce the behaviour.

Attachments:

* [twisted_reproduce2.py](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/cc8/cc86e147d48905016757fa14151d879d6a71c556/0748210c6d8373b0c01e83b058d266b623601f6c.py) (2285 bytes) - added by immerrr on 2014-06-02 13:18:00Z - script to display the described error
* [tentative-test-for-7427-and-7457.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/cc8/cc86e147d48905016757fa14151d879d6a71c556/a982c75a37ca624bfc4719c1f68865fec745eef9.patch) (2333 bytes) - added by immerrr on 2014-07-26 14:10:45Z - add two test cases for #7427 and #7457

<details><summary>Searchable metadata</summary>

```
trac-id__7457 7457
type__defect defect
reporter__immerrr immerrr
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__web web
keywords__ 
time__1401714992000000 1401714992000000
changetime__1543500224920546 1543500224920546
version__None None
owner__ 
cc__jknight
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="richvdh's avatar" src="https://avatars.githubusercontent.com/u/1389908?s=50" width="50" height="50">](https://github.com/richvdh)<a name="note_2"></a>|@richvdh commented|
|-|-|

This seems to be a duplicate of [#6528](https://github.com/twisted/twisted/issues/6528) ?
