### ISSUE TITLE
IMAP4Client: store() completely broken

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#7480]
|<img alt="jgoerzen's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| jgoerzen reported|
|-|-|
|Trac ID|trac#174|
|Type|defect|
|Created|2003-08-06 01:19:46Z|

<details><summary>Searchable metadata</summary>

```
trac-id__174 174
type__defect defect
reporter__jgoerzen jgoerzen
priority__highest highest
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__ 
keywords__ 
time__1060132786000000 1060132786000000
changetime__1060726501000000 1060726501000000
version__ 
owner__ 
cc__exarkun cc__jgoerzen
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="jgoerzen's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|jgoerzen commented|
|-|-|

```
#!html
<pre>
When attempting to use the store() method in IMAP4Client, 
I get tracebacks: 
 
Traceback (most recent call last): 
  File "./twistedfixes/imap4.py", line 1680, in 
_defaultHandler 
    cmd.finish(rest, self._extraInfo) 
  File "./twistedfixes/imap4.py", line 354, in finish 
    self.defer.callback((send, lastLine)) 
  File 
"/usr/lib/python2.2/site-packages/twisted/internet/defer.py", 
line 218, in callback 
    self._startRunCallbacks(result) 
  File 
"/usr/lib/python2.2/site-packages/twisted/internet/defer.py", 
line 274, in _startRunCallbacks 
    self._runCallbacks() 
--- &lt;exception caught here> --- 
  File 
"/usr/lib/python2.2/site-packages/twisted/internet/defer.py", 
line 288, in _runCallbacks 
    self.result = callback(self.result, *args, **kw) 
exceptions.TypeError: __cbFetch() got an unexpected 
keyword argument 'lookFor' 
 
Sure enough, the _store() method says: 
 
        d.addCallback(self.__cbFetch, lookFor='FLAGS') 
 
but __cbFetch() is defined as: 
 
    def __cbFetch(self, results, tag, query, uid): 
 
This problem persists in both 1.0.6 and the CVS version 
and blocks a good deal of IMAP functionality.

</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="radix's avatar" src="https://avatars.githubusercontent.com/u/227068?s=50" width="50" height="50">](https://github.com/radix)|@radix commented|
|-|-|

```
#!html
<pre>
Can you please write a failing unit test that triggers this
error?

</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)|@glyph commented|
|-|-|

```
#!html
<pre>
Please fix.

</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="jgoerzen's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|jgoerzen commented|
|-|-|

```
#!html
<pre>
radix: Unfortunately, I have not yet mastered (nor even 
looked at) the Twisted way of writing unit tests, so I'm 
afraid that I will not be of much help there.  However, I 
can show you the exact call in my program that was causing 
this failure: 
 
       return imapobj.setFlags(str(uid), 
                                
imaputil.flagsmaildir2imap(flags), 
                                uid = 1) 
 
Also, I applied this diff to imap4.py as a workaround; 
however, I am unsure if this has any unintended 
consequences anywhere: 
 
--- ../Twisted/twisted/protocols/imap4.py       2003-07-25 
16:04:29.000000000 -0 
500 
+++ twistedfixes/imap4.py       2003-08-05 
15:42:49.000000000 -0500 
@@ -2858,7 +2862,7 @@ 
         store = uid and 'UID STORE' or 'STORE' 
         args = ' '.join((messages, cmd, '(%s)' % ' 
'.join(flags))) 
         d = self.sendCommand(Command(store, args, 
wantResponse=('FETCH',))) 
-        d.addCallback(self.__cbFetch, lookFor='FLAGS') 
+        d.addCallback(self.__cbFetch) 
         return d 
 
     def copy(self, messages, mailbox, uid):

</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun commented|
|-|-|

```
#!html
<pre>
Your fix is the correct one -- lookFor was a remnant of a
previous approach to this implementation.  Fixed in CVS, thanks.

</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
