### ISSUE TITLE
twisted.test.test_udp.MulticastTestCase.test_loopback failures are indicative of machine configuration.

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#7494]
|[<img alt="tomprince's avatar" src="https://avatars.githubusercontent.com/u/283816?s=50" width="50" height="50">](https://github.com/tomprince)| @tomprince reported|
|-|-|
|Trac ID|trac#7494|
|Type|enhancement|
|Created|2014-06-07 22:21:39Z|

twisted.test.test_udp.MulticastTestCase.test_loopback fails if twisted is unable to talk to itself over loopback using multicast. This is more likely to be due to local configuration than errors in the code.

There should be a way to run twisted's test suite in such a constrained environment without having this test fail.

<details><summary>Searchable metadata</summary>

```
trac-id__7494 7494
type__enhancement enhancement
reporter__tom_prince tom.prince
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__ 
time__1402179699000000 1402179699000000
changetime__1650079667099883 1650079667099883
version__None None
owner__ 
cc__yan12125
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

Why is it better to say "run the test suite and I don't care if X fails" to the test collector/runner than it is to say "run the test suite and I don't care if X fails" to the thing that is looking at the output of a test run?

Also why don't you care if X fails?  If the Fedora packages of Twisted are built without passing the multicast tests then how does anyone know if Twisted's multicast support works on Fedora?  (Notice that I am guessing here that the environment where this is failing this time is the Fedora package builders.)

**Comment by twisted-trac** [comment]
|[<img alt="tomprince's avatar" src="https://avatars.githubusercontent.com/u/283816?s=50" width="50" height="50">](https://github.com/tomprince)<a name="note_2"></a>|@tomprince commented|
|-|-|

While it would certainly be better to test all of twisted, this bug currently means that *none* of twisted is tested. I'm not sure of a good way to skip a particular test when running trial (suggestions welcome, the code is at https://pkgs.fedoraproject.org/cgit/python-twisted.git/tree/python-twisted.spec#n110)

There is a documented way to get an environment that is able to run the tests (https://twistedmatrix.com/trac/wiki/ContinuousIntegration/TestSlaveConfiguration#OSConfiguration) but that requires root to change the iptables configuration. I doubt that would be an acceptable change in fedora's buildsystem.

**Comment by twisted-trac** [comment]
|[<img alt="tomprince's avatar" src="https://avatars.githubusercontent.com/u/283816?s=50" width="50" height="50">](https://github.com/tomprince)<a name="note_3"></a>|@tomprince commented|
|-|-|

```
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/builddir/build/BUILD/Twisted-15.4.0/twisted/test/test_udp.py", line 539, in cbJoined
    self.server.transport.write(b"hello", ("225.0.0.250", addr.port))
  File "/builddir/build/BUILD/Twisted-15.4.0/twisted/internet/udp.py", line 297, in write
    return self.socket.sendto(datagram, addr)
socket.error: [Errno 1] Operation not permitted
twisted.test.test_udp.MulticastTests.test_loopback
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/builddir/build/BUILD/Twisted-15.4.0/twisted/test/test_udp.py", line 674, in serverJoined
    firstClient.transport.write(b"hello world", (theGroup, portno))
  File "/builddir/build/BUILD/Twisted-15.4.0/twisted/internet/udp.py", line 297, in write
    return self.socket.sendto(datagram, addr)
socket.error: [Errno 1] Operation not permitted
twisted.test.test_udp.MulticastTests.test_multiListen
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/builddir/build/BUILD/Twisted-15.4.0/twisted/test/test_udp.py", line 633, in cbJoined
    c.transport.write(b"hello world", ("225.0.0.250", addr.port))
  File "/builddir/build/BUILD/Twisted-15.4.0/twisted/internet/udp.py", line 297, in write
    return self.socket.sendto(datagram, addr)
socket.error: [Errno 1] Operation not permitted
twisted.test.test_udp.MulticastTests.test_multicast
===============================================================================
[ERROR]
Traceback (most recent call last):
Failure: twisted.trial.util.DirtyReactorAggregateError: Reactor was unclean.
Selectables:
<twisted.test.test_udp.Server on 37290>
twisted.test.test_udp.MulticastTests.test_multicast
-------------------------------------------------------------------------------
```

**Comment by twisted-trac** [comment]
|[<img alt="scop's avatar" src="https://avatars.githubusercontent.com/u/109152?s=50" width="50" height="50">](https://github.com/scop)<a name="note_4"></a>|@scop commented|
|-|-|

This is not limited to the Fedora build system, it fails on my local Fedora 23 box too. I suppose it's because multicast packets don't end up in the loopback interface at all. 
http://stackoverflow.com/questions/16007311/multicasting-on-loopback-device

The base routing rules are simply:

```
default         gateway         0.0.0.0         UG    600    0        0 wlp3s0
192.168.0.0     0.0.0.0         255.255.255.0   U     600    0        0 wlp3s0
```

Now, if I add this:

```
# route add -net 224.0.0.0 netmask 240.0.0.0 dev lo
```

...everything else passes, but test_loopback fails with (this is with current twisted trunk):

```
Traceback (most recent call last):
  File ".../twisted/twisted/test/test_udp.py", line 556, in cbNoPacket
    self.assertEqual(len(self.server.packets), 1)
  File ".../twisted/twisted/trial/_synctest.py", line 425, in assertEqual
    super(_Assertions, self).assertEqual(first, second, msg)
  File "/usr/lib64/python2.7/unittest/case.py", line 551, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib64/python2.7/unittest/case.py", line 544, in _baseAssertEqual
    raise self.failureException(msg)
twisted.trial.unittest.FailTest: 2 != 1
```

**Comment by twisted-trac** [comment]
|[<img alt="yan12125's avatar" src="https://avatars.githubusercontent.com/u/1937689?s=50" width="50" height="50">](https://github.com/yan12125)<a name="note_5"></a>|@yan12125 commented|
|-|-|

> There is a documented way to get an environment that is able to run the tests (https://twistedmatrix.com/trac/wiki/ContinuousIntegration/TestSlaveConfiguration#OSConfiguration) but that requires root to change the iptables configuration. I doubt that would be an acceptable change in fedora's buildsystem. 

The documented command is for iptables and does not work on systems using firewalld and nftables. Instead, I got those tests running with the following steps:

1. Create a file /etc/firewalld/services/twisted.xml

```
<?xml version="1.0" encoding="utf-8"?>
<service>
  <short>Twisted testing</short>
  <port protocol="udp" port="1-65535"/>
  <destination ipv4="225.0.0.250"/>
</service>
```

2. Reload firewalld via `sudo firewall-cmd --reload`
3. Allow multicast traffic from twisted tests via `sudo firewall-cmd --zone=public --add-service=twisted`

Nevertheless, it will be great if there is a way to skip multicast tests on restricted environments without touching firewall configurations or patching sources. Currently, multicast tests are skipped for macOS on Azure Pipelines https://github.com/twisted/twisted/blob/twisted-22.4.0/src/twisted/test/test_udp.py#L514. Extending this condition will benefit more people.

PS. I'm on Arch Linux. There is no "official" firewall solution for Arch Linux. I picked firewalld just because it's more suitable for me.

> If the Fedora packages of Twisted are built without passing the multicast tests then how does anyone know if Twisted's multicast support works on Fedora?

I'm not sure how Fedora packaging works, while my experience with Arch Linux packaging may shed some light. Here, every package build script is expected to run on different environments (package maintainers' machines, reproducible builders, machines of package maintainers on Arch-based Linux distributions, ...). I can verify twisted multicast tests work on Arch Linux with some firewall tricks, but the build script should be generic and compatible with all kinds of environments.
