### ISSUE TITLE
Bug? in OSCAR implementation

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#7522]
|<img alt="tdc's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| tdc reported|
|-|-|
|Trac ID|trac#333|
|Type|defect|
|Created|2003-10-13 03:27:06Z|

<details><summary>Searchable metadata</summary>

```
trac-id__333 333
type__defect defect
reporter__tdc tdc
priority__high high
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__ 
keywords__ 
time__1066015626000000 1066015626000000
changetime__1077230493000000 1077230493000000
version__ 
owner__ 
cc__z3p cc__tdc
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="tdc's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|tdc commented|
|-|-|

```
#!html
<pre>
When trying to run oscardemo.py, i get this error:

$ python oscardemo.py
Username: &lt;some icq #>
Password: &lt;password>
{'sessionLength': 0L, 'warning': 0, 'onSince': 1065993327L, 'name': '&lt;some icq
#>', 'icqIPaddy': '&lt;my ip addr>', 'flags': ['aim'], 'icqRandom':
'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00',
'caps': []}
Traceback (most recent call last):
  File "/usr/lib/python2.2/site-packages/twisted/internet/default.py", line 501,
in doSelect
    _logrun(selectable, _drdw, selectable, method, dict)
  File "/usr/lib/python2.2/site-packages/twisted/python/log.py", line 65, in
callWithLogger
    callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/lib/python2.2/site-packages/twisted/python/log.py", line 52, in
callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/lib/python2.2/site-packages/twisted/python/context.py", line 32, in
callWithContext
    return func(*args,**kw)
--- &lt;exception caught here> ---
  File "/usr/lib/python2.2/site-packages/twisted/internet/default.py", line 510,
in _doReadOrWrite
    why = getattr(selectable, method)()
  File "/usr/lib/python2.2/site-packages/twisted/internet/tcp.py", line 227, in
doRead
    return self.protocol.dataReceived(data)
  File "/usr/lib/python2.2/site-packages/twisted/protocols/oscar.py", line 290,
in dataReceived
    state=func(flap)
  File "/usr/lib/python2.2/site-packages/twisted/protocols/oscar.py", line 373,
in oscar_Data
    func(snac[2:])
  File "/usr/lib/python2.2/site-packages/twisted/protocols/oscar.py", line 641,
in oscar_0B_02
    self.reportingInterval = struct.unpack('!H',snac[3])[0]
struct.error: unpack str size does not match format

tested with release 1.0.7 and fresh CVS checkout (and I remember i got exactly
this even some time before)
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="z3p's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|z3p commented|
|-|-|

```
#!html
<pre>
Try oscar.py:1.19.  I committed a fix which should eliminate this problem.
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="radix's avatar" src="https://avatars.githubusercontent.com/u/227068?s=50" width="50" height="50">](https://github.com/radix)|@radix commented|
|-|-|

```
#!html
<pre>
This is the same bug as #466 (but that one has test code), closing.
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|
