### ISSUE TITLE
twisted.test.test_sslverify.SelectVerifyImplementationTests.test_dependencyMissingWarning fails on Python 3.3

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#7535]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#7535|
|Type|release blocker: regression|
|Created|2014-07-02 13:08:44Z|
|Branch|https://github.com/twisted/twisted/tree/fix-ssl-dependency-warning-7535|

Only if you have the necessary dependencies installed, otherwise it is skipped:

```
======================================================================
FAIL: test_dependencyMissingWarning (twisted.test.test_sslverify.SelectVerifyImplementationTests)
test_dependencyMissingWarning
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/buildslave/run/python-3.3-tests/Twisted/twisted/trial/_synctest.py", line 1308, in _run
    runWithWarningsSuppressed(suppress, method)
  File "/home/buildslave/run/python-3.3-tests/Twisted/twisted/python/util.py", line 1021, in runWithWarningsSuppressed
    return f(*args, **kwargs)
  File "/home/buildslave/run/python-3.3-tests/Twisted/twisted/test/test_sslverify.py", line 2434, in test_dependencyMissingWarning
    (expectedMessage, "", 0))
  File "/home/buildslave/run/python-3.3-tests/Twisted/twisted/trial/_synctest.py", line 447, in assertEqual
    % (msg, pformat(first), pformat(second)))
twisted.trial.unittest.FailTest: not equal:
a = ("You do not have a working installation of the service_identity module: 'import of 'service_identity' halted; None in sys.modules'.  Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module and a recent enough pyOpenSSL to support it, Twisted can perform only rudimentary TLS client hostname verification.  Many valid certificate/hostname mappings may be rejected.",
 '',
 0)
b = ("You do not have a working installation of the service_identity module: 'No module named service_identity'.  Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module and a recent enough pyOpenSSL to support it, Twisted can perform only rudimentary TLS client hostname verification.  Many valid certificate/hostname mappings may be rejected.",
 '',
 0)
```

<details><summary>Searchable metadata</summary>

```
trac-id__7535 7535
type__release_blocker__regression release blocker: regression
reporter__exarkun exarkun
priority__normal normal
milestone__Python_3_x Python-3.x
branch__branches_fix_ssl_dependency_warning_7535 branches/fix-ssl-dependency-warning-7535
branch_author__hawkowl hawkowl
status__closed closed
resolution__duplicate duplicate
component__core core
keywords__ 
time__1404306524971386 1404306524971386
changetime__1404733218325204 1404733218325204
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_1"></a>|@hawkowl commented|
|-|-|

(In [42839]) Branching to fix-ssl-dependency-warning-7535.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_2"></a>|@exarkun set status to `closed`|
|-|-|

Duplicate of [#7355](https://github.com/twisted/twisted/issues/7355).
