### ISSUE TITLE
add default error reporting back to new logging system ✓

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#7545]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)| @glyph reported|
|-|-|
|Trac ID|trac#7545|
|Type|release blocker: regression|
|Created|2014-07-31 22:23:32Z|
|Branch|https://github.com/twisted/twisted/tree/log-booyah-6750-5|

This program:

```python

from twisted.python import log

try:
    1/0
except:
    log.err()
```

produces a traceback on stderr on 14.0.0, but on trunk, it produces no output.  This can make debugging scripts that use Twisted really confusing.  We should put it back.

<details><summary>Searchable metadata</summary>

```
trac-id__7545 7545
type__release_blocker__regression release blocker: regression
reporter__glyph glyph
priority__high high
milestone__New_Logging_System New Logging System
branch__branches_log_booyah_6750_5 branches/log-booyah-6750-5
branch_author__wsanchez wsanchez
status__closed closed
resolution__fixed fixed
component__logger logger
keywords__ 
time__1406845412869404 1406845412869404
changetime__1481165672140580 1481165672140580
version__None None
owner__wsanchez wsanchez
cc__wsanchez
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)<a name="note_2"></a>|@wsanchez commented|
|-|-|

The missing output glyph refers to is:
```
Unhandled Error
Traceback (most recent call last):
--- <exception caught here> ---
  File "test.py", line 6, in <module>
    1/0
exceptions.ZeroDivisionError: integer division or modulo by zero
```

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)<a name="note_3"></a>|@wsanchez commented|
|-|-|

OK, we only emit to stderr right now if the log level is "critical".

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)<a name="note_4"></a>|@wsanchez commented|
|-|-|

(In [42910]) Branch for [#7545](https://github.com/twisted/twisted/issues/7545)

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)<a name="note_5"></a>|@wsanchez commented|
|-|-|

r42912 fixes Glyph's program above.

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)<a name="note_6"></a>|@wsanchez commented|
|-|-|

This program should also work:

```
from twisted.python.logger import LegacyLogger

log = LegacyLogger()

try:
    1/0
except:
    log.err()
```

r42911 fixes LegacyLogger to log at critical level.
r42920 adds the traceback behavior to LegacyLogger.

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)<a name="note_7"></a>|@wsanchez commented|
|-|-|

That leaves the new logging API.  That API current *requires* a format string, so you would write your program something like this:

```
from twisted.python.logger import Logger

log = Logger()

try:
    1/0
except:
    log.failure("Yikes!!")
```

But that outputs simply:

```
Yikes!!
```

So… perhaps we shouldn't require the format string and provide one that includes the traceback as the default?

Or do we append to the format by default?  Seems like at least we should have an easy way to tack on the traceback, even when you specify the format, so you don't have to add `\n{log_failure.getTraceback()}` to your format string, which seems clunky.  It would be easy to add a `log_traceback` event key so that could be `\n{log_traceback()}` instead… kinda better but still not as nice as having it done for you…

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)<a name="note_8"></a>|@wsanchez commented|
|-|-|

That last point is probably a new ticket.  This branch addresses the original issue plus the LegacyLogger case, so that's worth reviewing now.  Created [#7548](https://github.com/twisted/twisted/issues/7548) for tracking the new logging behavior.

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)<a name="note_9"></a>|@wsanchez commented|
|-|-|

Kicked the builders.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_10"></a>|@glyph commented|
|-|-|

Thanks for the super fast turnaround!

Looks like there's a failing test (failing on almost all builders, thank goodness).  Given that, it probably needs a re-review, but I can probably turn that one around fast too, I don't see anything objectionable in the patch.

(Although... perhaps this should be documented with an example as well, in a separate ticket?)

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)<a name="note_11"></a>|@wsanchez commented|
|-|-|

r42926 fixes the test, as unhandled errors are CRITICAL, not ERROR.

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)<a name="note_12"></a>|@wsanchez commented|
|-|-|

I added a note in [#7548](https://github.com/twisted/twisted/issues/7548) to add some info the the `logger` HOWTO about properly logging exceptions, once we figure out what we want to say about that in the new API.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_15"></a>|@glyph commented|
|-|-|

So, I apologize for the state of the Python 3 buildbot.  It's been failing for a while now, and I have known about it, and we haven't fixed it.

But this change introduces a _new_ failure, since Py3 is keeping us honest about bytes/text distinction.

1. You shouldn't bother with getting the whole py3 buildbot to go green right now, but this error:
```
ERROR: test_errorString (twisted.test.test_log.PythonLoggingObserverTestCase)
test_errorString
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/buildslave/run/python-3.3-tests/Twisted/twisted/trial/_synctest.py", line 1308, in _run
    runWithWarningsSuppressed(suppress, method)
  File "/home/buildslave/run/python-3.3-tests/Twisted/twisted/python/util.py", line 1021, in runWithWarningsSuppressed
    return f(*args, **kwargs)
  File "/home/buildslave/run/python-3.3-tests/Twisted/twisted/test/test_log.py", line 705, in test_errorString
    output.startswith(prefix),
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```
  is new and should be fixed.
2. Just a minor stylistic nit, in `legacy_err`: `messagePrefix` doesn't actually need a branch.  `if not why: why = "Unhandled Error"` would do the same job in 2 lines of code rather than 4, and I think would be a little clearer.
3. This looks like it conflicts with the implementation strategy in [#7548](https://github.com/twisted/twisted/issues/7548).  I don't like the inclusion of stuff into the format string, but I guess we can deal with that when that lands; this looks like an adequate fix for the broken behavior.

Please address the above to your satisfaction (especially the first point) and then land.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_16"></a>|@glyph commented|
|-|-|

You might also want to see my comments on [#7548](https://github.com/twisted/twisted/issues/7548) before landing.

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)<a name="note_17"></a>|@wsanchez commented|
|-|-|

OK I've landed [#7548](https://github.com/twisted/twisted/issues/7548), merging this forward to resolve conflicts.

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)<a name="note_18"></a>|@wsanchez commented|
|-|-|

(In [42939]) Merge forward.

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)<a name="note_19"></a>|@wsanchez commented|
|-|-|

After merging forward:

* new and old logging tests pass
* the program in this ticket still outputs the expected stuff
* the program in [#7548](https://github.com/twisted/twisted/issues/7548) still outputs the expected stuff

The two branches don't interact, as Glyph thought they might; I didn't expect them to.

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)<a name="note_20"></a>|@wsanchez commented|
|-|-|

On to Glyph's review above.

1. Go Python 3 for being pedantic; nice. Fixed in r42941.
2. `why` is later used in line 219, so modifying it is bad. `why` != expected output prefix.
3. As per above, they don't interact.  The legacy implementation adds this output all the time (as the old system did) and the new one only in the (new) `FileLogObserver`.

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)<a name="note_21"></a>|@wsanchez commented|
|-|-|

Py3 builder no longer complains about test_errorString.

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)<a name="note_22"></a>|@wsanchez set status to `closed`|
|-|-|

(In [42943]) Merge branches/log-err-default-7545-1: Add default error reporting back to new logging system

Author: wsanchez
Reviewer: glyph
Fixes: [#7545](https://github.com/twisted/twisted/issues/7545)

Legacy logging now adds a traceback to rendered events to match existing behavior; this was a regression since merging the new logging (as yet unreleased).
Legacy logging now emits at `LogLevel.critical` if `isError` is set (ie. capturing an unhandled exception) to match new logging.
Python stdlib logging logs at `CRITICAL` level if `isError` is set (was `ERROR`).

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_23"></a>|@hawkowl set status to `reopened`|
|-|-|

(In [43429]) Revert r42943: Revert [#6750](https://github.com/twisted/twisted/issues/6750) and related tickets

Please see http://twistedmatrix.com/pipermail/twisted-python/2014-November/028912.html for more details.

Reopens: [#7545](https://github.com/twisted/twisted/issues/7545)

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)<a name="note_25"></a>|@wsanchez commented|
|-|-|

Re-applied in r43434 on [branches/log-booyah-6750-5.](branches/log-booyah-6750-5.)

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)<a name="note_27"></a>|@wsanchez set status to `closed`|
|-|-|

Closing as fixed on the logging branch.
