### ISSUE TITLE
Twisted fails to make HTTPS requests to some hostnames

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#7552]
|<img alt="Alex's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| Alex reported|
|-|-|
|Trac ID|trac#7552|
|Type|defect|
|Created|2014-08-12 17:18:34Z|

Using the following code:

```
import sys

import treq

from twisted.internet.defer import inlineCallbacks
from twisted.internet.task import react


@inlineCallbacks
def main(reactor, url):
    yield treq.get(url, allow_redirects=True)

if __name__ == '__main__':
    react(main, sys.argv[1:])
```

If I attempt to make a request to `https://nile.ghdonline.org`, it fails with `Failure: twisted.web._newclient.ResponseNeverReceived: [<twisted.python.failure.Failure <class 'OpenSSL.SSL.Error'>>]`. Both `requests` and my browser are able to make requests to this server.

Of note: the first error you'll hit is caused by a bug in pyOpenSSL, you can apply https://github.com/pyca/pyopenssl/pull/147 to fix that, there's still a second, underlying error of unknown origin.

<details><summary>Searchable metadata</summary>

```
trac-id__7552 7552
type__defect defect
reporter__Alex Alex
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__wontfix wontfix
component__web web
keywords__ 
time__1407863914770453 1407863914770453
changetime__1424811841933152 1424811841933152
version__None None
owner__None None
cc__jknight cc__hynek cc__dpn
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_2"></a>|@glyph commented|
|-|-|

Are there other URLs that exhibit this problem?  Are you aware of whether this is an HTTP or TLS issue? This appears to be an HTTPS to HTTP redirect, which is a slightly dodgy thing to do.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_3"></a>|@glyph commented|
|-|-|

Here's the traceback I get without the pyOpenSSL patch:

```
Unhandled Error
Traceback (most recent call last):
  File ".../twisted/python/log.py", line 102, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File ".../twisted/python/log.py", line 85, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File ".../twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File ".../twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File ".../twisted/internet/selectreactor.py", line 149, in _doReadOrWrite
    why = getattr(selectable, method)()
  File ".../twisted/internet/tcp.py", line 215, in doRead
    return self._dataReceived(data)
  File ".../twisted/internet/tcp.py", line 221, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File ".../twisted/protocols/tls.py", line 415, in dataReceived
    self._write(bytes)
  File ".../twisted/protocols/tls.py", line 554, in _write
    sent = self._tlsConnection.send(toSend)
  File ".../site-packages/OpenSSL/SSL.py", line 950, in send
    self._raise_ssl_error(self._ssl, result)
  File ".../site-packages/OpenSSL/SSL.py", line 871, in _raise_ssl_error
    _raise_current_error()
  File ".../site-packages/OpenSSL/_util.py", line 20, in exception_from_error_queue
    text(lib.ERR_reason_error_string(error))))
  File ".../site-packages/OpenSSL/_util.py", line 10, in text
    return native(ffi.string(charp))
  File ".../site-packages/cffi/api.py", line 253, in string
    return self._backend.string(cdata, maxlen)
exceptions.RuntimeError: cannot use string() on <cdata 'char *' NULL>
```

**Comment by twisted-trac** [comment]
|[<img alt="hynek's avatar" src="https://avatars.githubusercontent.com/u/41240?s=50" width="50" height="50">](https://github.com/hynek)<a name="note_4"></a>|@hynek commented|
|-|-|

I’ve run some experiments:

I took http://twisted.readthedocs.org/en/latest/_downloads/check_server_certificate.py to check whether it’s HTTPS-related and it’s **not**.

It’s independent from the pyOpenSSL version and it appears to be related to the verification code because replacing `options = ssl.optionsForClientTLS(hostname=host.decode('utf-8'))` thru `options = ssl.CertificateOptions()` makes it work for me.

Looking further, it’s enough to comment out `_maybeSetHostNameIndication` in `ClientTLSOptions._identityVerifyingInfoCallback` so I guess the problem is related somehow to it.  I played a bit with pdb and the call back gets called a few times, once with `SSL_CB_HANDSHAKE_START`, then with 4097 (I think `SSL_CB_CONNECT_LOOP`) and then a few times with 4098 (should be `SSL_CB_CONNECT_EXIT`).

No calls with `SSL_CB_HANDSHAKE_DONE` whatsoever.

Hope this helps someone more intimate with the verification code to find out what’s going on.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_5"></a>|@glyph commented|
|-|-|

So, `SSL_CB_CONNECT_EXIT` is [totally undocumented](https://www.openssl.org/docs/ssl/SSL_CTX_set_info_callback.html).  But if it's called multiple times presumably it's not a good way to decide the handshake is done anyway.

Is there no callback which happens at the spot where `SSL_CB_HANDSHAKE_DONE` ought to be?  No other hints that the handshake is completed, as per the info callback?  Is this a bug in pyOpenSSL or OpenSSL itself?

Thanks for investigating, hynek.

**Comment by twisted-trac** [comment]
|<img alt="dpn's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_6"></a>|dpn commented|
|-|-|

FWIW I think I'm having this issue with  https://api.datasift.com/v1/compile as well.

hynek's tweak on check_server_certificate.py behaved the same way for me too.

I'm not familiar with much of this code in twisted, but happy to look into anything that may seem likely. Also is anyone aware of an easy-ish way to disable checking of certs in treq?

**Comment by twisted-trac** [comment]
|<img alt="dpn's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_7"></a>|dpn commented|
|-|-|

So I can't repro on my other workstation, here's versions of things that might matter.

Broken on:
Gentoo
dev-libs/openssl-1.0.1j
PyOpenSSL 0.14
treq 0.2.1


Works on:
Ubuntu 12.04
openssl 1.0.1-4ubuntu5.16
libssl1.0.0  1.0.1-4ubuntu5.17
PyOpenSSL 0.14
treq 0.2.1

I can work around basic GET requests by using requests.get in a thread, unfortunately I have a fair bit of code doing streaming with Agent where this issue is harder to work around with threads...

**Comment by twisted-trac** [comment]
|<img alt="dpn's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_9"></a>|dpn commented|
|-|-|

For some reason I can repro using a fairly vanilla implementation of an agent, this is the example which apparently disables verification (is that even true anymore with service_identity?):

```
class WebClientContextFactory(ClientContextFactory):
    def getContext(self, hostname, port):
        return ClientContextFactory.getContext(self)

def _req(url):
    contextFactory = WebClientContextFactory()
    agent = Agent(reactor, contextFactory)
    d = agent.request("GET", url)
    return d
```

**Comment by twisted-trac** [comment]
|[<img alt="hynek's avatar" src="https://avatars.githubusercontent.com/u/41240?s=50" width="50" height="50">](https://github.com/hynek)<a name="note_10"></a>|@hynek commented|
|-|-|

JFTR, `SSL_CB_CONNECT_EXIT` ist not entirely undocumented (anymore?), apparently it means `SSL_ST_CONNECT|SSL_CB_EXIT` with the former I guess is the state (“connecting”) and the later means:

    Callback has been called to indicate error exit of a handshake function. (May be soft error with retry option for non-blocking setups.)

Is there a way to know what actually happened?  I’m not really competent with OpenSSL APIs I’m afraid. :-/  Maybe it’s just incompatible with setting SNI host names or something?  This is all just from the top of my head, I completely forgot about this issue because it’s about stuff I don’t know anything about #meaCulpa

**Comment by twisted-trac** [comment]
|[<img alt="hynek's avatar" src="https://avatars.githubusercontent.com/u/41240?s=50" width="50" height="50">](https://github.com/hynek)<a name="note_11"></a>|@hynek commented|
|-|-|

Furthermore it works fine with OpenSSL 1.0.1j on OS X but not with 1.0.1f on Trusty for me.

Maybe we should have a look at the changelog?  I suspect it could be related with long handshakes at least in the one case, so far there’s no proof that the handshakes in both cases fail for the same reasons (they have a very bad TLS configuration in common though).

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_12"></a>|@glyph commented|
|-|-|

from an ubuntu 14.04 system where it doesn't work:

```
$ openssl s_client -debug -connect api.datasift.com:443
CONNECTED(00000003)
write to 0x181add0 [0x181ae50] (305 bytes => 305 (0x131))
0000 - 16 03 01 01 2c 01 00 01-28 03 03 3a dc f7 91 fe   ....,...(..:....
0010 - 36 29 c8 b9 cc a4 79 dc-d4 e7 85 f3 a4 7b df cb   6)....y......{..
0020 - cc 16 bc 73 e0 bf e5 2c-58 93 57 00 00 92 c0 30   ...s...,X.W....0
0030 - c0 2c c0 28 c0 24 c0 14-c0 0a 00 a3 00 9f 00 6b   .,.(.$.........k
0040 - 00 6a 00 39 00 38 00 88-00 87 c0 32 c0 2e c0 2a   .j.9.8.....2...*
0050 - c0 26 c0 0f c0 05 00 9d-00 3d 00 35 00 84 c0 12   .&.......=.5....
0060 - c0 08 00 16 00 13 c0 0d-c0 03 00 0a c0 2f c0 2b   ............./.+
0070 - c0 27 c0 23 c0 13 c0 09-00 a2 00 9e 00 67 00 40   .'.#.........g.@
0080 - 00 33 00 32 00 9a 00 99-00 45 00 44 c0 31 c0 2d   .3.2.....E.D.1.-
0090 - c0 29 c0 25 c0 0e c0 04-00 9c 00 3c 00 2f 00 96   .).%.......<./..
00a0 - 00 41 c0 11 c0 07 c0 0c-c0 02 00 05 00 04 00 15   .A..............
00b0 - 00 12 00 09 00 14 00 11-00 08 00 06 00 03 00 ff   ................
00c0 - 01 00 00 6d 00 0b 00 04-03 00 01 02 00 0a 00 34   ...m...........4
00d0 - 00 32 00 0e 00 0d 00 19-00 0b 00 0c 00 18 00 09   .2..............
00e0 - 00 0a 00 16 00 17 00 08-00 06 00 07 00 14 00 15   ................
00f0 - 00 04 00 05 00 12 00 13-00 01 00 02 00 03 00 0f   ................
0100 - 00 10 00 11 00 23 00 00-00 0d 00 20 00 1e 06 01   .....#..... ....
0110 - 06 02 06 03 05 01 05 02-05 03 04 01 04 02 04 03   ................
0120 - 03 01 03 02 03 03 02 01-02 02 02 03 00 0f 00 01   ................
0130 - 01                                                .
```
... then a very long pause here ...
```
read from 0x181add0 [0x18203b0] (7 bytes => -1 (0xFFFFFFFFFFFFFFFF))
write:errno=104
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 305 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
---
```

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_13"></a>|@glyph commented|
|-|-|

Just for a sanity-check:

```
$ gnutls-cli api.datasift.com -p 443
Resolving 'api.datasift.com'...
Connecting to '46.236.5.229:443'...
- Certificate type: X.509
 - Got a certificate list of 2 certificates.
 - Certificate[0] info:
  - subject `C=GB,OU=Domain Control Validated,CN=api.datasift.com', issuer `O=AlphaSSL,CN=AlphaSSL CA - G2', RSA key 2048 bits, signed using RSA-SHA1, activated `2012-06-01 09:39:24 UTC', expires `2017-06-01 09:39:24 UTC', SHA-1 fingerprint `1d009fe19c1822c35e27aad69c7107dc8686b26f'
 - Certificate[1] info:
  - subject `O=AlphaSSL,CN=AlphaSSL CA - G2', issuer `C=BE,O=GlobalSign nv-sa,OU=Root CA,CN=GlobalSign Root CA', RSA key 2048 bits, signed using RSA-SHA1, activated `2011-04-13 10:00:00 UTC', expires `2022-04-13 10:00:00 UTC', SHA-1 fingerprint `5824cf32c3cc2a47443db10a33bbe3ac8de524e1'
- The hostname in the certificate matches 'api.datasift.com'.
- Peer's certificate issuer is unknown
- Peer's certificate is NOT trusted
- Version: TLS1.0
- Key Exchange: RSA
- Cipher: ARCFOUR-128
- MAC: SHA1
- Compression: NULL
- Handshake was completed

- Simple Client Mode:

```

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_14"></a>|@glyph commented|
|-|-|

Oh, hrm. I think I may have cracked the code, and it's not a good answer :-\

Adding `-no_tls1_1` to the `s_client` command line makes it work.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_15"></a>|@glyph commented|
|-|-|

Actually, `-no_tls1_2` works as well.  The server can negotiate 1.0 or 1.1, but 1.2 makes it refuse to respond to the handshake.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_16"></a>|@glyph commented|
|-|-|

Yup, this totally fixes the test program:

```
#!diff
--- a/twisted/internet/_sslverify.py                                                                                                     
+++ b/twisted/internet/_sslverify.py                                                                                                     
@@ -1405,6 +1405,8 @@ class OpenSSLCertificateOptions(object):                                                                           
             # will be supported.                                                                                                        
             self.method = SSL.SSLv23_METHOD                                                                                             
             self._options |= SSL.OP_NO_SSLv3                                                                                            
+            OP_NO_TLSv1_2 = 0x08000000                                                                                                  
+            self._options |= OP_NO_TLSv1_2                                                                                              
         else:                                                                                                                           
             # Otherwise respect the application decision.                                                                               
             self.method = method                                                                                                        
```

Now that I know this, I wonder if there's some way to timeout and trigger a renegotiation?  Also I really wonder why hynek using `CertificateOptions` worked for him.

Has anyone figured out how to configure a server that fails like this?

(Also, for the record, I did not patch pyOpenSSL but did not see the relevant traceback from that issue on this test.)

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_17"></a>|@glyph commented|
|-|-|

Now that I've narrowed it down to protocol version:

```
$ echo | gnutls-cli --priority "NORMAL:-VERS-TLS-ALL:+VERS-TLS1.0" api.datasift.com -p 443                                               
Resolving 'api.datasift.com'...
Connecting to '46.236.5.229:443'...
- Certificate type: X.509
 - Got a certificate list of 2 certificates.
 - Certificate[0] info:
  - subject `C=GB,OU=Domain Control Validated,CN=api.datasift.com', issuer `O=AlphaSSL,CN=AlphaSSL CA - G2', RSA key 2048 bits, signed us
ing RSA-SHA1, activated `2012-06-01 09:39:24 UTC', expires `2017-06-01 09:39:24 UTC', SHA-1 fingerprint `1d009fe19c1822c35e27aad69c7107dc
8686b26f'
 - Certificate[1] info:
  - subject `O=AlphaSSL,CN=AlphaSSL CA - G2', issuer `C=BE,O=GlobalSign nv-sa,OU=Root CA,CN=GlobalSign Root CA', RSA key 2048 bits, signe
d using RSA-SHA1, activated `2011-04-13 10:00:00 UTC', expires `2022-04-13 10:00:00 UTC', SHA-1 fingerprint `5824cf32c3cc2a47443db10a33bb
e3ac8de524e1'
- The hostname in the certificate matches 'api.datasift.com'.
- Peer's certificate issuer is unknown
- Peer's certificate is NOT trusted
- Version: TLS1.0
- Key Exchange: RSA
- Cipher: ARCFOUR-128
- MAC: SHA1
- Compression: NULL
- Handshake was completed

- Simple Client Mode:

$ echo | gnutls-cli --priority "NORMAL:-VERS-TLS-ALL:+VERS-TLS1.1" api.datasift.com -p 443                                               
Resolving 'api.datasift.com'...
Connecting to '46.236.5.229:443'...
*** Fatal error: A record packet with illegal version was received.
*** Handshake has failed
GnuTLS error: A record packet with illegal version was received.
$ echo | gnutls-cli --priority "NORMAL:-VERS-TLS-ALL:+VERS-TLS1.2" api.datasift.com -p 443                                               
Resolving 'api.datasift.com'...
Connecting to '46.236.5.229:443'...
*** Fatal error: A record packet with illegal version was received.
*** Handshake has failed
GnuTLS error: A record packet with illegal version was received.
```

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_18"></a>|@glyph commented|
|-|-|

I got in touch with datasift to see if we could get more information about what their TLS terminator is doing; I'll post something if I get a response.

I also tried to trigger a renegotiation after noticing the `SSL_CB_CONNECT_EXIT`, but no luck there.

As hynek pointed out, this is not a great TLS configuration: https://www.ssllabs.com/ssltest/analyze.html?d=api.datasift.com

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_19"></a>|@glyph commented|
|-|-|

Also, I should point out that nile.ghdonline.com now works with all versions I've tested with, so they fixed their configuration, whatever the issue was.

**Comment by twisted-trac** [comment]
|<img alt="dpn's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_20"></a>|dpn commented|
|-|-|

We have a commercial DS account, so I'll raise through our support too. Nice sleuthing :)

**Comment by twisted-trac** [comment]
|[<img alt="hynek's avatar" src="https://avatars.githubusercontent.com/u/41240?s=50" width="50" height="50">](https://github.com/hynek)<a name="note_21"></a>|@hynek commented|
|-|-|

Two quick things here:

- it’s still completely possible that we have multiple problems at hand (one of them had problems with long handshakes too)
- you may remember, that Ubuntu 12.04 LTS removed TLS 1.2 from its client code because of hanging handshakes with bad servers; this might be just the problem we just ran into?

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_22"></a>|@glyph commented|
|-|-|

hynek - if you look at the ssltest results I linked above, you'll see that qualys's openssl can't connect to the server either. So I don't think it's purely TLS 1.2, but it seems like OpenSSL has a hard time talking to it, whatever it is.  All the more reason to get a better high-level TLS architecture and move away from dependency on OpenSSL.

**Comment by twisted-trac** [comment]
|[<img alt="hynek's avatar" src="https://avatars.githubusercontent.com/u/41240?s=50" width="50" height="50">](https://github.com/hynek)<a name="note_23"></a>|@hynek commented|
|-|-|

I’m totally not arguing with you, just reminding in general.

The question at hand now is what to do next?  Wait for an answer from DS?  It doesn’t seem to be a Twisted problem in any case?

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_24"></a>|@glyph commented|
|-|-|

Replying to [hynek](#note_23):
> I’m totally not arguing with you, just reminding in general.

Same here.

> The question at hand now is what to do next?  Wait for an answer from DS?  It doesn’t seem to be a Twisted problem in any case?

I could think of some shenanigans that we could possibly get up to, but ... I am pretty sure they are all formally reducible to "downgrade attack".  So maybe we _shouldn't_ fix it.

**Comment by twisted-trac** [comment]
|[<img alt="hynek's avatar" src="https://avatars.githubusercontent.com/u/41240?s=50" width="50" height="50">](https://github.com/hynek)<a name="note_25"></a>|@hynek commented|
|-|-|

Yep, everything points to manually adding downgrade attacks to the already colorful portfolio.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_26"></a>|@glyph set status to `closed`|
|-|-|

I am going to close this as "wontfix" for the Twisted project, because I don't think there is anything further for us to do.  If your SSL endpoint is so misconfigured that OpenSSL can't talk to it, there's not really much we can do about it.

That said, new information may still arrive, which may prompt us to reopen it.  So I don't want anyone to interpret this as "won't _ever_ fix".  When DS gets back to either me or dpn, we may change our minds.  Please continue updating this ticket as your receive future information and re-open if you believe there's something Twisted should do.

But for now, this failure mode is indistinguishable from a downgrade attack and should be treated as such; the connection simply should not work.

**Comment by twisted-trac** [comment]
|<img alt="dpn's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_27"></a>|dpn commented|
|-|-|

I believe DS is responding to Glyph as well, so I'll just leave this small comment from their support here to add some context:

======================================
Our ISP's load balancers screw up protocol negotiation which was what was causing problems with some of the client libs on (iirc) Macs. Unfortunately this is why we forcefully make the client libs request TLS 1.0 / SSLv3 and not negotiate downwards from TLS1.2.

However generally speaking:

* SSLv3 and TLSv1 should work.
* TLSv1.1, TLSv1.2 won't work.
* There are also some OSX specific issues due to a documented vulnerability http://support.apple.com/kb/ht4004
======================================

Hope that helps anyone who stumbles on this. I believe Glyph has resolved this ticket appropriately.

**Comment by twisted-trac** [comment]
|<img alt="dpn's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_28"></a>|dpn commented|
|-|-|

Also for anyone stumbling on this, here's how DS's own client sets up the SSL client: https://github.com/datasift/datasift-python/blob/master/datasift/twisted_ssl.py

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_29"></a>|@glyph commented|
|-|-|

Thanks, dpn. That's roughly what they said to me.

And... regarding that context factory... wow, that has... some issues. I would _strongly_ recommend against using that particular configuration.  I will get in touch with them again.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_30"></a>|@glyph commented|
|-|-|

I filed a new ticket to deal with the version-selection issue.  In a hilarious stroke of luck, it got the ticket number [#7752](https://github.com/twisted/twisted/issues/7752) :).

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_31"></a>|@glyph commented|
|-|-|

For those of you following along at home, datasift got back to me and their configuration has been fixed.  So one less server on the Internet which will be experiencing this issue :).

**Comment by twisted-trac** [comment]
|[<img alt="hynek's avatar" src="https://avatars.githubusercontent.com/u/41240?s=50" width="50" height="50">](https://github.com/hynek)<a name="note_32"></a>|@hynek commented|
|-|-|

Could this be also related to https://bugs.launchpad.net/ubuntu/+source/openssl/+bug/965371 ?

**Comment by twisted-trac** [comment]
|<img alt="dpn's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_33"></a>|dpn commented|
|-|-|

@hynek - I've been following that issue as it impacted my work directly, as it happens, my particular issues on this thread couldn't be repro'd on my ubuntu 12.04 setup...

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_34"></a>|@glyph commented|
|-|-|

Replying to [hynek](#note_32):
> Could this be also related to https://bugs.launchpad.net/ubuntu/+source/openssl/+bug/965371 ?

Superficially appears to be the same issue to me, at least.
