### ISSUE TITLE
twisted trial imports module twice, causing duplicate calls to ffi.verify

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#7556]
|<img alt="vanandel's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| vanandel reported|
|-|-|
|Trac ID|trac#7556|
|Type|defect|
|Created|2014-08-17 03:34:26Z|

I'm developing an application using Twisted and CFFI.  I'm writing unit tests using Twisted Trial.  Multiple python modules use my CFFI generated resources. I adapted a technique I found in the pyca/pynaci package to avoid multiple calls to `cffi.verify()` - see the listing I've attached to this posting.

 I've found that the twisted Trial framework imports my module twice.
The first time, it appears the Trial is trying to discover test cases.  The second time, Trial is actually running my code.
How do I use the Twisted Trial framework to test code that uses CFFI?

Since  `ffi.verify()` gets called twice, I get the warning:

```
/usr/local/anconda/lib/python2.7/site-packages/cffi/vengine_cpy.py:177: UserWarning: reimporting '_cffi__x29622308x91e43959' might overwrite older definitions
```

and the resulting error:

```
Traceback (most recent call last):
  File "/home/vanandel/code/eol_spol_misc/agent/test/SysconClientTestCase.py", line 29, in test_SET_POL_MODE
    lib.iwrf_ui_task_operations_init(to, lib.IWRF_UI_SET_POL_MODE, "test_task", "no-owner")
exceptions.TypeError: initializer for ctype 'iwrf_ui_task_operations_t *' must be a pointer to same type, not cdata 'iwrf_ui_task_operations_t *'
```

a) First backtrace, Trial is verifying that my test class is derived from pyunit.TestCase

```
  File "/usr/local/anconda/bin/trial", line 18, in <module>
    run()
  File "/usr/local/anconda/lib/python2.7/site-packages/twisted/scripts/trial.py", line 611, in run
    suite = _getSuite(config)
  File "/usr/local/anconda/lib/python2.7/site-packages/twisted/scripts/trial.py", line 499, in _getSuite
    return loader.loadByNames(config['tests'], recurse)
  File "/usr/local/anconda/lib/python2.7/site-packages/twisted/trial/runner.py", line 590, in loadByNames
    for thing in self._uniqueTests(things)]
  File "/usr/local/anconda/lib/python2.7/site-packages/twisted/trial/runner.py", line 548, in loadAnything
    return self.loadModule(thing)
  File "/usr/local/anconda/lib/python2.7/site-packages/twisted/trial/runner.py", line 420, in loadModule
    for testClass in self.findTestClasses(module):
  File "/usr/local/anconda/lib/python2.7/site-packages/twisted/trial/runner.py", line 380, in findTestClasses
    if isTestCase(val):
  File "/usr/local/anconda/lib/python2.7/site-packages/twisted/trial/runner.py", line 249, in isTestCase
    return issubclass(obj, pyunit.TestCase)
  File "/home/vanandel/code/eol_spol_misc/agent/iwrf_cffi.py", line 49, in __getattr__
```

b) Second backtrace, Trial is running my code.

```
 (top of backtrace  omitted)
    return self.run(*args, **kwds)
  File "/usr/local/anconda/lib/python2.7/site-packages/twisted/trial/runner.py", line 151, in run
    test(result)
  File "/usr/local/anconda/lib/python2.7/site-packages/twisted/trial/_asynctest.py", line 119, in __call__
    return self.run(*args, **kwargs)
  File "/usr/local/anconda/lib/python2.7/site-packages/twisted/trial/_synctest.py", line 943, in run
    _collectWarnings(self._warnings.append, self._runFixturesAndTest, result)
  File "/usr/local/anconda/lib/python2.7/site-packages/twisted/trial/_synctest.py", line 182, in _collectWarnings
    result = f(*args, **kwargs)
  File "/usr/local/anconda/lib/python2.7/site-packages/twisted/trial/_asynctest.py", line 298, in _runFixturesAndTest
    d = self.deferSetUp(None, result)
  File "/usr/local/anconda/lib/python2.7/site-packages/twisted/trial/_asynctest.py", line 123, in deferSetUp
    d = self._run('setUp', result)
  File "/usr/local/anconda/lib/python2.7/site-packages/twisted/trial/_asynctest.py", line 112, in _run
    utils.runWithWarningsSuppressed, self._getSuppress(), method)
  File "/usr/local/anconda/lib/python2.7/site-packages/twisted/internet/defer.py", line 139, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/local/anconda/lib/python2.7/site-packages/twisted/internet/utils.py", line 199, in runWithWarningsSuppressed
    result = f(*a, **kw)
  File "/home/vanandel/code/eol_spol_misc/agent/test/SysconClientTestCase.py", line 15, in setUp
    self.polControl = PolarizationControl('localhost', 9000, self.clock)
  File "/home/vanandel/code/eol_spol_misc/agent/PolarizationControl.py", line 32, in __init__
    self._name2mode = {'alternating': lib.IWRF_ALT_HV_CO_CROSS,
  File "/home/vanandel/code/eol_spol_misc/agent/iwrf_cffi.py", line 49, in __getattr__
```

Attachments:

* [iwrf_cffi.py](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/eee/eeed2727f534b11536a2ad31f921d9093cb8ec5c/49bc1ae8586aeb8654eff962bb28ec6674dffb38.py) (1897 bytes) - added by vanandel on 2014-08-17 03:35:36Z - module that invokes cffi

<details><summary>Searchable metadata</summary>

```
trac-id__7556 7556
type__defect defect
reporter__vanandel vanandel
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__invalid invalid
component__trial trial
keywords__ 
time__1408246466191927 1408246466191927
changetime__1408275058534373 1408275058534373
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_4"></a>|@exarkun set status to `closed`|
|-|-|

This doesn't appear to be the case to me.  Consider this simpler example:

```
exarkun@top:/tmp$ trial test_foo.py 
test_foo importing

-------------------------------------------------------------------------------

PASSED
exarkun@top:/tmp$ trial test_foo
test_foo importing

-------------------------------------------------------------------------------

PASSED
exarkun@top:/tmp$ cat test_foo.py 
print 'test_foo importing'
exarkun@top:/tmp$ 
```

Please feel free to re-open if you can provide reproduction instructions.
