### ISSUE TITLE
twisted.python.filepath.FilePath.walk extremely slow

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#7619]
|<img alt="kleptog's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| kleptog reported|
|-|-|
|Trac ID|trac#7619|
|Type|defect|
|Created|2014-09-01 14:24:05Z|

I'm kind of amazed this hasn't been reported before, but the `walk()` function in `twisted.python.filepath.FilePath` is really slow, primarily because of the huge number of `lstat()` calls it does.

Basically, starting `walk()` on a directory with 1693 files in various subdirectories ends up calling `lstat()`1.times, as measured by strace. It takes three seconds, while find takes 0.006 seconds.

The problem is caused by r23707.

Note how it uses `os.path.realpath()`. This function is already pretty slow, it does one `lstat()` for every component of the filename. So `os.path.realpath("/a/b/c/d/e/f")` does 6 `lstat()` calls to check for links.

Now, suppose you run `walk("/a")`. First it will recurse down the tree, this is ok. Then because it's got nested generators, it will do the following calls:

```
os.path.realpath("/a/b/c/d/e").startswith(os.path.realpath("/a/b/c/d/e/f"))   # 11 lstats()
os.path.realpath("/a/b/c/d").startswith(os.path.realpath("/a/b/c/d/e/f"))     # 10 lstats()
os.path.realpath("/a/b/c").startswith(os.path.realpath("/a/b/c/d/e/f"))       # 9 lstats()
os.path.realpath("/a/b").startswith(os.path.realpath("/a/b/c/d/e/f"))         # 8 lstats()
os.path.realpath("/a").startswith(os.path.realpath("/a/b/c/d/e/f"))           # 7 lstats()
```

For a total of 45 `lstat()` calls for one file.

Now, I notice the same commit implements a `realpath()` call but does not use it. Perhaps that was the intention? Because that `realpath()` checks if the file is a link first, which makes it much more efficient.

Similarly `os.path.realpath(self.path)` could be cached.

Try the following script on your system. On my system it takes 41 seconds, calling `lstat()` 2.6 million times. `find /usr/lib/ |wc -l` return 27133 files in 0.063 seconds.
```
from twisted.python.filepath import FilePath

for f in FilePath("/usr").walk():     
    pass
```

Python 2.7.3, Twisted 11.0, though the code hasn't changed in essence in 6 years.

<details><summary>Searchable metadata</summary>

```
trac-id__7619 7619
type__defect defect
reporter__kleptog kleptog
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__None None
time__1409581445183422 1409581445183422
changetime__1606296835065953 1606296835065953
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|<img alt="ivank's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_1"></a>|ivank commented|
|-|-|

The cycle check in `walk()` has another problem: it makes it impossible (without subclassing) to avoid walking a symlink that points to the parent directory.  A descend function that uses `islink()` doesn't work, because the recursion gets too far ahead of itself, assuming there is a cycle when it would have been stopped by future `descend` checks.

```
from twisted.python.filepath import FilePath

def descend(f):
	return not f.islink()

for f in FilePath('.').walk(descend=descend):
	print f
```

```
mkdir a; ln -s .. a/cycle; python walk.py
```

```
Traceback (most recent call last):
  File "walk.py", line 6, in <module>
    for f in FilePath('.').walk(descend=descend):
  File "/usr/lib/python2.7/dist-packages/twisted/python/filepath.py", line 398, in walk
    raise LinkError("Cycle in file graph.")
twisted.python.filepath.LinkError: Cycle in file graph.
```

There are even more problems with this little method: it calls `descend` on non-directories ([#5123](https://github.com/twisted/twisted/issues/5123)) and it fails to call `descend` on itself before iterating over children.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_3"></a>|@glyph commented|
|-|-|

(Just removing a defunct email address.)

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_4"></a>|@adiroiban commented|
|-|-|

I don't think that this is still a valid release broker. Moving it to a normal defect.
