### ISSUE TITLE
twisted.web.error.UnsupportedMethod makes the allowed methods look like they're unsupported

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#7744]
|[<img alt="Julian's avatar" src="https://avatars.githubusercontent.com/u/329822?s=50" width="50" height="50">](https://github.com/Julian)| @Julian reported|
|-|-|
|Trac ID|trac#7744|
|Type|enhancement|
|Created|2015-01-07 01:33:41Z|
|Branch|https://github.com/twisted/twisted/tree/unsupportedmethod-str-7744|

UnsupportedMethod takes as argument a list of methods that the resource *does* support, but does not implement __str__, which leads to tracebacks that look like:

```python
Traceback (most recent call last):
  File "/Users/Julian/Development/Minion/minion/tests/test_twisted.py", line 76, in test_it_properly_routes_when_mounted_on_a_subpath
    render(resource=twistedResource, request=request)
  File "/usr/local/lib/python2.7/site-packages/klein/test_resource.py", line 100, in _render
    result = resource.render(request)
  File "/usr/local/lib/python2.7/site-packages/twisted/web/resource.py", line 249, in render
    raise UnsupportedMethod(allowedMethods)
twisted.web.error.UnsupportedMethod: ['HEAD']
```

Where it's unclear that the list isn't the unsupported methods. In some cases (like the above) the immediate stack frame above has named the variable it passes in allowedMethods, which makes things slightly better, but being a bit more explicit would make the traceback easier to read.

<details><summary>Searchable metadata</summary>

```
trac-id__7744 7744
type__enhancement enhancement
reporter__Julian Julian
priority__normal normal
milestone__ 
branch__branches_unsupportedmethod_str_7744 branches/unsupportedmethod-str-7744
branch_author__ 
status__closed closed
resolution__fixed fixed
component__web web
keywords__easy easy
time__1420594421643562 1420594421643562
changetime__1483041309907047 1483041309907047
version__None None
owner__Julian Julian
cc__jknight
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="julian's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_2"></a>|julian commented|
|-|-|

(In [43657]) Branching to unsupportedmethod-str-7744.

**Comment by twisted-trac** [comment]
|[<img alt="Julian's avatar" src="https://avatars.githubusercontent.com/u/329822?s=50" width="50" height="50">](https://github.com/Julian)<a name="note_3"></a>|@Julian commented|
|-|-|

Ideally it'd be nice if UnsupportedMethod was passed the method that was unsupported as well and showed that, but that'd be an interface change and some modification to the various places that raise the exception, which is a bit more than the 5 minutes I gave this. Putting up for review as-is. Build is [forced](http://buildbot.twistedmatrix.com/boxes-supported?branch=/branches/unsupportedmethod-str-7744).

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_4"></a>|@adiroiban set owner to @Julian|
|-|-|

Is there any new code in this branch?

Please update the track ticket so that it will see the diff in trac or github, as well as results from buildbot.

Thanks!

**Comment by twisted-trac** [comment]
|[<img alt="Julian's avatar" src="https://avatars.githubusercontent.com/u/329822?s=50" width="50" height="50">](https://github.com/Julian)<a name="note_6"></a>|@Julian commented|
|-|-|

mkbranch apparently didn't update the ticket, but I did so manually. Here's [build results](http://buildbot.twistedmatrix.com/boxes-supported?branch=/branches/unsupportedmethod-str-7744).

**Comment by twisted-trac** [comment]
|[<img alt="Julian's avatar" src="https://avatars.githubusercontent.com/u/329822?s=50" width="50" height="50">](https://github.com/Julian)|@Julian removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_8"></a>|@adiroiban commented|
|-|-|

Changes looks good. I would consider it a feature as from now on I can use str(error) as port of my custom log message.

It would have been nice if the error also include the requested method but I think that this is out of the scope for this ticket.

Note that I am just a junior reviewer so will leave this in the review queue.

Thanks!

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)<a name="note_9"></a>|@wsanchez set owner to @Julian|
|-|-|

Reviewed.

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)<a name="note_10"></a>|@wsanchez commented|
|-|-|

PR: https://github.com/twisted/twisted/pull/608#issuecomment-266533842

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_11"></a>|@rodrigc set status to `closed`|
|-|-|

In changeset 9ccee5c04348c1a16a747065b60af44eb08f2e2b
```
#!CommitTicketReference repository="" revision="9ccee5c04348c1a16a747065b60af44eb08f2e2b"
Merge pull request #608 from Julian/unsupportedmethod-str-7744

Author: Julian
Reviewer: wsanchez
Fixes: ticket:7744

twisted.web.error.UnsupportedMethod makes the allowed methods look like they're unsupported
```
