### ISSUE TITLE
test_ipv6AcceptAddress spurious failure

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#7756]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)| @adiroiban reported|
|-|-|
|Trac ID|trac#7756|
|Type|defect|
|Created|2015-01-26 20:37:55Z|

Here is the buildbot with error

https://buildbot.twistedmatrix.com/builders/winxp32-py2.7/builds/4031

```

[ERROR]
Traceback (most recent call last):
  File "C:\buildslave\twisted\winxp32-py2.7\Twisted\twisted\internet\test\test_iocp.py", line 97, in test_ipv6AcceptAddress
    self._acceptAddressTest(AF_INET6, '::1')
  File "C:\buildslave\twisted\winxp32-py2.7\Twisted\twisted\internet\test\test_iocp.py", line 66, in _acceptAddressTest
    SOL_SOCKET, SO_UPDATE_ACCEPT_CONTEXT, pack('P', server.fileno()))
  File "c:\python27\lib\socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 10057] A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied

twisted.internet.test.test_iocp.SupportTests.test_ipv6AcceptAddress
```

-----

I see that it is also failing for select reactor... have no idea why.

I was not able to get iocpsupport on my WinXP VM...tried both MSI and Wheel files

------

I guess that the test is too fast and it does not wait for windows to set up the network part.

<details><summary>Searchable metadata</summary>

```
trac-id__7756 7756
type__defect defect
reporter__adiroiban adiroiban
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__duplicate duplicate
component__core core
keywords__ 
time__1422304675482956 1422304675482956
changetime__1423315087631545 1423315087631545
version__None None
owner__adiroiban adiroiban

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)|@adiroiban set owner to @adiroiban|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_2"></a>|@adiroiban set status to `closed`|
|-|-|

This is a duplicate of [#5356](https://github.com/twisted/twisted/issues/5356)

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_3"></a>|@exarkun commented|
|-|-|

Please leave links in both directions on duplicates.  Thanks.
