### ISSUE TITLE
AMP Command.responder doesn't work with already decorated methods

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#7793]
|[<img alt="wallrj's avatar" src="https://avatars.githubusercontent.com/u/978965?s=50" width="50" height="50">](https://github.com/wallrj)| @wallrj reported|
|-|-|
|Trac ID|trac#7793|
|Type|defect|
|Created|2015-02-17 12:29:01Z|
|Branch|https://github.com/twisted/twisted/tree/pre-decorated-amp-responder-7793|

If you use AMP Command.responder on an already decorated method, `locateResponder` fails to find the callable associated with that AMP Command.

Here's an example of a test failure from Flocker

```
[ERROR]
Traceback (most recent call last):
  File "/home/richard/.virtualenvs/1275/lib/python2.7/site-packages/eliot/testing.py", line 271, in wrapper
    return function(self, *args, **kwargs)
  File "/home/richard/projects/HybridLogic/flocker/flocker/control/test/test_protocol.py", line 387, in test_cluster_updated
    eliot_context=u"abc")
  File "/home/richard/projects/HybridLogic/flocker/flocker/control/test/test_protocol.py", line 61, in callRemote
    responder = self._locator.locateResponder(command.commandName)
  File "/home/richard/.virtualenvs/1275/lib/python2.7/site-packages/twisted/protocols/amp.py", line 1067, in locateResponder
    cd = self._commandDispatch
exceptions.TypeError: first argument must be callable

flocker.control.test.test_protocol.AgentClientTests.test_cluster_updated

```

And here's a comment in the code which suggests that this problem was anticipated:

https://github.com/twisted/twisted/blob/trunk/twisted/protocols/amp.py#L958-L964

```
This metaclass keeps track of all of the Command.responder-decorated
methods defined since the last CommandLocator subclass was defined. It
assumes (usually correctly, but unfortunately not necessarily so) that
those commands responders were all declared as methods of the class
being defined. Note that this list can be incorrect if users use the
Command.responder decorator outside the context of a CommandLocator
class declaration.

```

I'll try and supply a failing test.

<details><summary>Searchable metadata</summary>

```
trac-id__7793 7793
type__defect defect
reporter__rwall rwall
priority__normal normal
milestone__ 
branch__branches_pre_decorated_amp_responder_7793 branches/pre-decorated-amp-responder-7793
branch_author__rwall rwall
status__closed closed
resolution__worksforme worksforme
component__core core
keywords__ 
time__1424176141709547 1424176141709547
changetime__1424182600297226 1424182600297226
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="wallrj's avatar" src="https://avatars.githubusercontent.com/u/978965?s=50" width="50" height="50">](https://github.com/wallrj)<a name="note_2"></a>|@wallrj commented|
|-|-|

(In [43938]) Branching to pre-decorated-amp-responder-7793.

**Comment by twisted-trac** [comment]
|[<img alt="wallrj's avatar" src="https://avatars.githubusercontent.com/u/978965?s=50" width="50" height="50">](https://github.com/wallrj)<a name="note_3"></a>|@wallrj set status to `closed`|
|-|-|

My mistake. The problem was due to a bug in the decorator.
