### ISSUE TITLE
twisted.logger doesn't play nice with characteristic

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#7930]
|[<img alt="Julian's avatar" src="https://avatars.githubusercontent.com/u/329822?s=50" width="50" height="50">](https://github.com/Julian)| @Julian reported|
|-|-|
|Trac ID|trac#7930|
|Type|defect|
|Created|2015-06-08 14:22:06Z|
|Branch|https://github.com/twisted/twisted/tree/7930-namespace-oh-no|

The following code:
```python
from characteristic import Attribute, attributes
from twisted.logger import Logger
@attributes([Attribute(name="logger", default_factory=Logger)])
class Foo(object): pass

Foo()
```

produces:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<characteristic generated init d5e9be43495223e112a5f002cf9c72b940cd8e55>", line 11, in characteristic_init
  File "/usr/local/lib/python2.7/site-packages/twisted/logger/_logger.py", line 52, in __init__
    namespace = self._namespaceFromCallingContext()
  File "/usr/local/lib/python2.7/site-packages/twisted/logger/_logger.py", line 32, in _namespaceFromCallingContext
    return currentframe(2).f_globals["__name__"]
KeyError: '__name__'
```

Characteristic is being a bit hairy (for performance), but roughly what it appears to do is just exec inside a globals dict that doesn't set __name__. I'm not sure I know whether that's it's fault or not (I'll go check), but filing the issue here first.

The following short example will reproduce the same traceback:

```
from twisted.logger import Logger
exec "Logger()" in {"Logger": Logger}
```

<details><summary>Searchable metadata</summary>

```
trac-id__7930 7930
type__defect defect
reporter__Julian Julian
priority__normal normal
milestone__None None
branch__7930_namespace_oh_no 7930-namespace-oh-no
branch_author__ 
status__closed closed
resolution__fixed fixed
component__logger logger
keywords__None None
time__1433773326425053 1433773326425053
changetime__1499138850280902 1499138850280902
version__None None
owner__glyph glyph
cc__wsanchez
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)<a name="note_2"></a>|@wsanchez commented|
|-|-|

In this case, you are asking Logger to figure out its own namespace and that logic fails, so a work-around is to provide one:

```
from twisted.logger import Logger
exec "Logger(namespace='foo')" in {"Logger": Logger}
```

I think raising `KeyError` is not great behavior here, so the question is whether this should raise a more appropriate error (eg. catch `KeyError` and raise an exception with a better message like "unable to determine namespace"), or if there's a default namespace we should use in this case (eg. `u""`).  Forcing the caller to think about this has some appeal, and a default means multiple unrelated things can end up in the same namespace.

**Comment by twisted-trac** [comment]
|[<img alt="Julian's avatar" src="https://avatars.githubusercontent.com/u/329822?s=50" width="50" height="50">](https://github.com/Julian)<a name="note_3"></a>|@Julian commented|
|-|-|

Yeah -- I think at the time we probably discussed this in #twisted-dev. I mostly agree that this bug should just be "KeyError isn't a great way to signal what's up here". I'd be +0.5 on CannotDetermineNamespace or the like.

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)<a name="note_5"></a>|@wsanchez commented|
|-|-|

Closing New Logging System milestone; use logger component for ongoing tickets.

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)<a name="note_6"></a>|@wsanchez set owner to @wsanchez<br>@wsanchez set status to `assigned`|
|-|-|

PR: https://github.com/twisted/twisted/pull/792

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)|@wsanchez removed owner<br>@wsanchez set status to `new`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_8"></a>|@glyph set owner to @wsanchez|
|-|-|

Review: https://github.com/twisted/twisted/pull/792#pullrequestreview-39665285

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)|@wsanchez removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_11"></a>|@glyph set owner to @glyph|
|-|-|

Thanks!  Feedback responded to, landing.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_12"></a>|@glyph set status to `closed`|
|-|-|

In changeset cd868a99815bf9c96bed2a1a91f7cc3eef14c03b
```
#!CommitTicketReference repository="" revision="cd868a99815bf9c96bed2a1a91f7cc3eef14c03b"
Merge pull request #792 from twisted/7930-namespace-oh-no

Author: wsanchez

Reviewer: glyph

Fixes: ticket:7930

Set namespace to "<unknown> instead of raising KeyError when unable to determine namespace from calling context.
```
