### ISSUE TITLE
Immediate crash of Twisted after trying to connect to RabbitMQ (python-twisted-core-8.2.0-4.el6.x86_64)

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#7953]
|<img alt="AquaL1te's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| AquaL1te reported|
|-|-|
|Trac ID|trac#7953|
|Type|defect|
|Created|2015-06-26 10:17:34Z|

When trying to connect to RabbitMQ via Carbon (Graphite daemon written with Twisted modules) I get the following error.
/var/log/carbon/console.log:
```
26/06/2015 11:58:29 :: Starting factory <carbon.amqp_listener.AMQPReconnectingFactory instance at 0x1528cb0>
26/06/2015 11:58:29 :: Unhandled Error
Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/twisted/python/log.py", line 84, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/lib64/python2.6/site-packages/twisted/python/log.py", line 69, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/lib64/python2.6/site-packages/twisted/python/context.py", line 59, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib64/python2.6/site-packages/twisted/python/context.py", line 37, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib64/python2.6/site-packages/twisted/internet/epollreactor.py", line 231, in _doReadOrWrite
    why = selectable.doRead()
  File "/usr/lib64/python2.6/site-packages/twisted/internet/tcp.py", line 463, in doRead
    return self.protocol.dataReceived(data)
  File "/usr/lib/python2.6/site-packages/txamqp/protocol.py", line 158, in dataReceived
    frame = self._unpackFrame(packet)
  File "/usr/lib/python2.6/site-packages/txamqp/protocol.py", line 134, in _unpackFrame
    payload = Frame.DECODERS[frameType].decode(self.spec, c)
  File "/usr/lib/python2.6/site-packages/txamqp/connection.py", line 94, in decode
    args = tuple([c.decode(f.type) for f in meth.fields])
  File "/usr/lib/python2.6/site-packages/txamqp/codec.py", line 84, in decode
    return getattr(self, "decode_" + type)()
  File "/usr/lib/python2.6/site-packages/txamqp/codec.py", line 182, in decode_table
    raise ValueError(repr(type))
exceptions.ValueError: 'F'

26/06/2015 11:58:29 :: <twisted.internet.tcp.Connector instance at 0x1508cf8> will retry in 1009 seconds
26/06/2015 11:58:29 :: Stopping factory <carbon.amqp_listener.AMQPReconnectingFactory instance at 0x1528cb0>
```

In /etc/carbon/carbon.conf I have the following:
```
# Enable AMQP if you want to receve metrics using an amqp broker
ENABLE_AMQP = True

# Verbose means a line will be logged for every metric received
# useful for testing
AMQP_VERBOSE = True

AMQP_HOST = localhost
AMQP_PORT = 5672
AMQP_VHOST = /
AMQP_USER = guest
AMQP_PASSWORD = guest
AMQP_EXCHANGE = graphite
AMQP_METRIC_NAME_IN_BODY = True
```

When restarting the carbon-cache daemon I get that exception as shown at the top of this ticket.

My software:
```
[root@gtw1 nodeagent]# rpm -q python-carbon
python-carbon-0.9.12-3.el6.noarch
```
```
[root@gtw1 nodeagent]# rpm -q python-twisted-core
python-twisted-core-8.2.0-4.el6.x86_64
```
```
[root@gtw1 nodeagent]# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 6.4 (Santiago)
```

Can anyone tell me what this Twisted exception exactly means?

<details><summary>Searchable metadata</summary>

```
trac-id__7953 7953
type__defect defect
reporter__AquaL1te AquaL1te
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__wontfix wontfix
component__core core
keywords__ 
time__1435313854701864 1435313854701864
changetime__1445217216921098 1445217216921098
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_1"></a>|@hawkowl set status to `closed`|
|-|-|

Hi!

This appears to be either:

a) A bug in txamqp, or
b) txamqp being incompatible with your Python version, or
c) An incompatibility between a current version of txamqp and a version of Twisted from 2008.

Your Twisted version (8.2) is VERY old. Please try with the latest version (15.2) from PyPI. If it doesn't work with the same error, then please file a bug at https://bugs.launchpad.net/txamqp , as it appears to be an issue in txamqp.

Thanks for using Twisted, and sorry that we can't help with this particular issue.

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_2"></a>|@hawkowl commented|
|-|-|

Ticket retargeted after milestone deleted
