### ISSUE TITLE
Stop relying on SSLv23_METHOD having SSLv3 in it

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#7991]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)| @hawkowl reported|
|-|-|
|Trac ID|trac#7991|
|Type|enhancement|
|Created|2015-08-09 06:04:52Z|

```
[FAIL]
Traceback (most recent call last):
  File "/buildslave/fedora22-py2.7/Twisted/twisted/test/test_sslverify.py", line 1239, in test_SSLv23
    method=SSL.SSLv23_METHOD)))
  File "/buildslave/fedora22-py2.7/Twisted/twisted/trial/_synctest.py", line 437, in assertEqual
    super(_Assertions, self).assertEqual(first, second, msg)
  File "/usr/lib64/python2.7/unittest/case.py", line 553, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib64/python2.7/unittest/case.py", line 836, in assertSetEqual
    self.fail(self._formatMessage(msg, standardMsg))
twisted.trial.unittest.FailTest: Items in the first set but not the second:
<ProtocolVersion=SSLv3>

twisted.test.test_sslverify.ProtocolVersionTests.test_SSLv23
```

<details><summary>Searchable metadata</summary>

```
trac-id__7991 7991
type__enhancement enhancement
reporter__hawkowl hawkowl
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__duplicate duplicate
component__core core
keywords__ 
time__1439100292516768 1439100292516768
changetime__1445217443410268 1445217443410268
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_1"></a>|@hawkowl set status to `closed`|
|-|-|

Whoops clicked the button twice

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_2"></a>|@hawkowl commented|
|-|-|

Ticket retargeted after milestone deleted
