### ISSUE TITLE
twisted.internet.endpoints.serverFromString chokes on IPv6 addresses

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#8035]
|<img alt="posita's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| posita reported|
|-|-|
|Trac ID|trac#8035|
|Type|defect|
|Created|2015-09-28 19:12:04Z|

This relates to (or extends) [#5694](https://github.com/twisted/twisted/issues/5694). Consider: 

```
>>> from twisted.internet.endpoints import serverFromString
>>> serverFromString(reactor, "tcp:2606\:2800\:220\:1\:248\:1893\:25c8\:1946")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/.../twisted/internet/endpoints.py", line 1471, in serverFromString
    return _serverFromStringLegacy(reactor, description, _NO_DEFAULT)
  File "/.../twisted/internet/endpoints.py", line 1397, in _serverFromStringLegacy
    nameOrPlugin, args, kw = _parseServer(description, None, default)
  File "/.../twisted/internet/endpoints.py", line 1388, in _parseServer
    return (endpointType.upper(),) + parser(factory, *args[1:], **kw)
  File "/.../twisted/internet/endpoints.py", line 1017, in _parseTCP
    return (int(port), factory), {'interface': interface,
ValueError: invalid literal for int() with base 10: '2606:2800:220:1:248:1893:25c8:1946'
```

Standard bracket notation is unsupported:

```
>>> serverFromString(reactor, "tcp:[2606:2800:220:1:248:1893:25c8:1946]")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/.../twisted/internet/endpoints.py", line 1471, in serverFromString
    return _serverFromStringLegacy(reactor, description, _NO_DEFAULT)
  File "/.../twisted/internet/endpoints.py", line 1397, in _serverFromStringLegacy
    nameOrPlugin, args, kw = _parseServer(description, None, default)
  File "/.../twisted/internet/endpoints.py", line 1388, in _parseServer
    return (endpointType.upper(),) + parser(factory, *args[1:], **kw)
TypeError: _parseTCP() takes at most 4 arguments (9 given)
```

<details><summary>Searchable metadata</summary>

```
trac-id__8035 8035
type__defect defect
reporter__posita posita
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__endpoint_ipv6 endpoint ipv6
time__1443467524044856 1443467524044856
changetime__1445921356290916 1445921356290916
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_1"></a>|@glyph commented|
|-|-|

Bracket notation is only "standard" in URLs; endpoint descriptions don't parse according to URL rules.
