### ISSUE TITLE
twisted.logger.jsonFileLogObserver does not record tracebacks from unhandled errors in collected Deferreds

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#8086]
|[<img alt="cdunklau's avatar" src="https://avatars.githubusercontent.com/u/882547?s=50" width="50" height="50">](https://github.com/cdunklau)| @cdunklau reported|
|-|-|
|Trac ID|trac#8086|
|Type|defect|
|Created|2015-11-05 11:03:52Z|

While textFileLogObserver dumps the traceback, jsonFileLogObserver does not. The attached code demonstrates the issue.

Attachments:

* [error.py](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/35a/35ac3451e4f9f671197372a83e857dd1c9ea14f2/ef967949be9a7da0f34bb3871e75c54697acb2c5.py) (962 bytes) - added by cdunklau on 2015-11-05 11:04:22Z - 
* [errorout.txt](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/35a/35ac3451e4f9f671197372a83e857dd1c9ea14f2/44d0312bcf39ba149219868ede204019d79acceb.txt) (1747 bytes) - added by cdunklau on 2015-11-05 11:04:30Z - 
* [error_simplified.py](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/35a/35ac3451e4f9f671197372a83e857dd1c9ea14f2/09a76167a6a634f030f440d599e6f1a873949687.py) (865 bytes) - added by cdunklau on 2015-11-05 13:14:27Z - Simplified without task.react
* [log_jsonobserver.txt](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/35a/35ac3451e4f9f671197372a83e857dd1c9ea14f2/d3671aa138d7f63ee87e68413171d5c56068c27e.txt) (1498 bytes) - added by cdunklau on 2015-11-05 13:14:53Z - Demonstration of the original problem
* [log_textobserver.txt](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/35a/35ac3451e4f9f671197372a83e857dd1c9ea14f2/1774ef502739a6269a8755a495e6f0aed0f5a80d.txt) (1314 bytes) - added by cdunklau on 2015-11-05 13:15:29Z - Demonstration showing problem does not affect text observer
* [log_jsonobserver_deferred_logging.txt](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/35a/35ac3451e4f9f671197372a83e857dd1c9ea14f2/dfa8fa5848d312fcf28f34c27220ff4032a9d55c.txt) (36171 bytes) - added by cdunklau on 2015-11-05 13:17:24Z - deferred debugging causes the traceback to be dumped directly to the log or stdout/err
* [test_to_reproduce_8086.diff](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/35a/35ac3451e4f9f671197372a83e857dd1c9ea14f2/9c87896a34d56cc9c7781f0a092a696408722e53.diff) (1037 bytes) - added by cdunklau on 2015-11-05 14:28:48Z - 
* [test_to_reproduce_8086.2.diff](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/35a/35ac3451e4f9f671197372a83e857dd1c9ea14f2/b73efe93361b6e2af07eabb7645d918572c432e5.diff) (1037 bytes) - added by cdunklau on 2015-11-05 14:32:18Z - 
* [fix-8086.diff](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/35a/35ac3451e4f9f671197372a83e857dd1c9ea14f2/a76dee57513dd0e12e6ee1ce19b85e3c6a33a8ed.diff) (1180 bytes) - added by cdunklau on 2015-11-05 15:41:36Z - My proposed fix with a test

<details><summary>Searchable metadata</summary>

```
trac-id__8086 8086
type__defect defect
reporter__cdunklau cdunklau
priority__normal normal
milestone__None None
branch__ 
branch_author__cdunklau cdunklau
status__closed closed
resolution__duplicate duplicate
component__logger logger
keywords__None None
time__1446721432912201 1446721432912201
changetime__1497443749039360 1497443749039360
version__None None
owner__cdunklau cdunklau
cc__colin.dunklau@...
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="cdunklau's avatar" src="https://avatars.githubusercontent.com/u/882547?s=50" width="50" height="50">](https://github.com/cdunklau)|@cdunklau set owner to @cdunklau<br>@cdunklau set status to `assigned`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="cdunklau's avatar" src="https://avatars.githubusercontent.com/u/882547?s=50" width="50" height="50">](https://github.com/cdunklau)<a name="note_3"></a>|@cdunklau commented|
|-|-|

Okay, i'm getting somewhere. Adding an observer to get the events directly and write the repr to a file, a new event shows up:

```
{
    'log_namespace': 'twisted.logger._observer',
    'log_level': <LogLevel=critical>,
    'observer': <twisted.logger._file.FileLogObserver object at 0x7fb1fcbc6250>,
    'log_source': None,
    'log_logger': <Logger 'twisted.logger._observer'>,
    'log_time': 1446731370.387473,
    'log_format': 'Temporarily disabling observer {observer} due to exception: {log_failure}',
    'log_failure': <twisted.python.failure.Failure exceptions.AttributeError: 'NoneType' object has no attribute '_formatter_parser'>
}
```

So it appears that the observer or some code it calls is broken.

Edit: the event that appears to cause the issue: 

```
{
    'log_namespace': 'twisted.internet.defer',
    'log_level': <LogLevel=critical>,
    'debugInfo': '',
    'log_source': None,
    'log_logger': <Logger 'twisted.internet.defer'>,
    'log_time': 1446731370.38742,
    'log_format': None,
    'log_failure': <twisted.python.failure.Failure exceptions.Exception: break stuff now>
}
```

**Comment by twisted-trac** [comment]
|[<img alt="cdunklau's avatar" src="https://avatars.githubusercontent.com/u/882547?s=50" width="50" height="50">](https://github.com/cdunklau)<a name="note_4"></a>|@cdunklau commented|
|-|-|

The test in the just-attached patch (both, i'm stupid and attached it twice) reproduces the issue, resulting in the traceback:

```
Traceback (most recent call last):
  File "/home/cdunklau/Development/Twisted/twisted/logger/test/test_json.py", line 301, in test_observerDoesntFailWithWhatever
    observer(event)
  File "/home/cdunklau/Development/Twisted/twisted/logger/_file.py", line 50, in __call__
    text = self.formatEvent(event)
  File "/home/cdunklau/Development/Twisted/twisted/logger/_json.py", line 245, in <lambda>
    lambda event: u"{0}{1}\n".format(recordSeparator, eventAsJSON(event))
  File "/home/cdunklau/Development/Twisted/twisted/logger/_json.py", line 196, in eventAsJSON
    flattenEvent(event)
  File "/home/cdunklau/Development/Twisted/twisted/logger/_flatten.py", line 87, in flattenEvent
    aFormatter.parse(event["log_format"])
  File "/usr/lib/python2.7/string.py", line 615, in parse
    return format_string._formatter_parser()
exceptions.AttributeError: 'NoneType' object has no attribute '_formatter_parser'
```


So it appears that the twisted.logger._flatten assumes the event's "log_format" key will refer to a string, but somewhere in the logger lib or in t.i.defer, the event's "log_format" key refers to None.

**Comment by twisted-trac** [comment]
|[<img alt="cdunklau's avatar" src="https://avatars.githubusercontent.com/u/882547?s=50" width="50" height="50">](https://github.com/cdunklau)<a name="note_5"></a>|@cdunklau commented|
|-|-|

Since the howto doc for twisted.logger asserts that the log_format key may be None, the bug appears to indeed be in how twisted.logger._flatten.flattenEvent handles the None case, or rather that it doesn't handle it.

**Comment by twisted-trac** [comment]
|[<img alt="cdunklau's avatar" src="https://avatars.githubusercontent.com/u/882547?s=50" width="50" height="50">](https://github.com/cdunklau)<a name="note_6"></a>|@cdunklau commented|
|-|-|

This is related to [#7927](https://github.com/twisted/twisted/issues/7927) and damn SpamBayes to hell if it rejects my comment again

**Comment by twisted-trac** [comment]
|[<img alt="cdunklau's avatar" src="https://avatars.githubusercontent.com/u/882547?s=50" width="50" height="50">](https://github.com/cdunklau)<a name="note_7"></a>|@cdunklau set owner to @glyph<br>@cdunklau set status to `new`|
|-|-|

This patch at least makes the original demonstration code print a traceback without deferred debugging on while using the json observer... but I expected it to actually log the traceback as part of an entry, not just dump the traceback in the log without a JSON wrapper.

I have no idea what to do next.

Assigning to glyph because he volunteered out of embarrassment :)

**Comment by twisted-trac** [comment]
|[<img alt="cdunklau's avatar" src="https://avatars.githubusercontent.com/u/882547?s=50" width="50" height="50">](https://github.com/cdunklau)<a name="note_8"></a>|@cdunklau commented|
|-|-|

I found where it's happening. ```FileLogObserver.__call__``` just appends the traceback to the output line it got from the formatter. Shouldn't this functionality be the formatter's job, not the observer's?

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_9"></a>|@adiroiban set owner to @cdunklau|
|-|-|

Hi cdunklau 

Can you please write a unit test demonstrating the error and the expected behaviour?

The title of this ticket talks about twisted.logger.jsonFileLogObserver but in your latest patch I can only see changes/tests in flattenEvent

Can you please update the title and description of this ticket to match the attached patch?

The documentation api-docs + narrative should describe the expected behaviour.

In case it does not do it, please also update the docs to what do you think should be the "right behaviour" and the one matching the latest patch.

Thanks!

**Comment by twisted-trac** [comment]
|[<img alt="cdunklau's avatar" src="https://avatars.githubusercontent.com/u/882547?s=50" width="50" height="50">](https://github.com/cdunklau)<a name="note_12"></a>|@cdunklau commented|
|-|-|

The problem in flattenEvent is a separate issue, covered by [#8860](https://github.com/twisted/twisted/issues/8860). I need to continue investigating the original problem, that is, that unhandled deferred failures do not provoke a log entry containing the traceback.

**Comment by twisted-trac** [comment]
|[<img alt="cdunklau's avatar" src="https://avatars.githubusercontent.com/u/882547?s=50" width="50" height="50">](https://github.com/cdunklau)<a name="note_13"></a>|@cdunklau commented|
|-|-|

With the fix in my PR for [#8860](https://github.com/twisted/twisted/issues/8860), I cannot reproduce the problem with jsonFileLogObserver.

This comment of mine confused me, since I couldn't find the code anymore... [comment:8 Colin Dunklau]:
> I found where it's happening. ```FileLogObserver.__call__``` just appends the traceback to the output line it got from the formatter. Shouldn't this functionality be the formatter's job, not the observer's?

...however the mentioned code was moved out of `FileLogObserver.__call__` in the fix for [#8858](https://github.com/twisted/twisted/issues/8858)

So, once [#8860](https://github.com/twisted/twisted/issues/8860) is closed, this issue can be closed as well.

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)<a name="note_14"></a>|@wsanchez commented|
|-|-|

Closing New Logging System milestone; use logger component for ongoing tickets.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_15"></a>|@exarkun set status to `closed`|
|-|-|

Duplicate of [#7927](https://github.com/twisted/twisted/issues/7927)
