### ISSUE TITLE
setting `t.i.b.DelayedCall.debug = True` causes all tests to fail in Python 3

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#8110]
|<img alt="posita's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| posita reported|
|-|-|
|Trac ID|trac#8110|
|Type|defect|
|Created|2015-11-16 21:21:59Z|

Consider:

```python
# test_delayedcall_py3.py
from twisted.trial import unittest as t_unittest

class Py3DelayedCallTestCase(t_unittest.TestCase): pass

if __name__ == '__main__':
    import os
    from twisted.internet import base as t_base
    t_base.DelayedCall.debug = bool(os.environ.get('DELAYED_CALL_DEBUG'))
    from unittest import main
    main()
```

As expected, with or without `DelayedCall.debug` set to `True`, it runs in Python 2:

```#!sh
% python2.7 ./test_delayedcall_py3.py
.
----------------------------------------------------------------------
Ran 1 test in 0.017s

OK
% DELAYED_CALL_DEBUG=1 python2.7 ./test_delayedcall_py3.py
.
----------------------------------------------------------------------
Ran 1 test in 0.017s

OK
```

But not so with Python 3:

```#!sh
% python3.4 ./test_delayedcall_py3.py
.
----------------------------------------------------------------------
Ran 1 test in 0.017s

OK
% DELAYED_CALL_DEBUG=1 python3.4 ./test_delayedcall_py3.py
E
======================================================================
ERROR: runTest (__main__.Py3DelayedCallTestCase)
runTest
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/matt/Documents/dev/txretry/.tox/py34-twisted_trunk/lib/python3.4/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/Users/matt/Documents/dev/txretry/.tox/py34-twisted_trunk/lib/python3.4/site-packages/twisted/trial/_asynctest.py", line 114, in <lambda>
    d.addBoth(lambda x : call.active() and call.cancel() or x)
  File "/Users/matt/Documents/dev/txretry/.tox/py34-twisted_trunk/lib/python3.4/site-packages/twisted/internet/base.py", line 94, in cancel
    self._str = bytes(self)
TypeError: 'DelayedCall' object is not iterable

----------------------------------------------------------------------
Ran 1 test in 0.022s

FAILED (errors=1)
```

Attachments:

* [8110_a.diff](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/f41/f41ab0853a052e3617a8a8a921b90d30eae439bf/8a1a97f253896079cb794d940326d86bbe36e3fa.diff) (3332 bytes) - added by pawelmhm on 2016-05-03 18:03:36Z - 
* [8110.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/f41/f41ab0853a052e3617a8a8a921b90d30eae439bf/3d40625af513c4d2780a13c00a973fb4d453657f.patch) (4840 bytes) - added by pawelmhm on 2016-06-26 17:12:33Z - 

<details><summary>Searchable metadata</summary>

```
trac-id__8110 8110
type__defect defect
reporter__posita posita
priority__normal normal
milestone__Python_3_x Python-3.x
branch__None None
branch_author__ 
status__closed closed
resolution__duplicate duplicate
component__core core
keywords__py3k py3k
time__1447708919585496 1447708919585496
changetime__1497119995918392 1497119995918392
version__None None
owner__pawelmhm pawelmhm

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="pawelmhm's avatar" src="https://avatars.githubusercontent.com/u/2700942?s=50" width="50" height="50">](https://github.com/pawelmhm)<a name="note_2"></a>|@pawelmhm commented|
|-|-|

See also [#8307](https://github.com/twisted/twisted/issues/8307) and [#8306](https://github.com/twisted/twisted/issues/8306)

**Comment by twisted-trac** [comment]
|[<img alt="pawelmhm's avatar" src="https://avatars.githubusercontent.com/u/2700942?s=50" width="50" height="50">](https://github.com/pawelmhm)<a name="note_3"></a>|@pawelmhm commented|
|-|-|

Ok so here's what happened. Debug mode on DelayedCall was not tested. [#5987](https://github.com/twisted/twisted/issues/5987) replaced one call to str() to call to bytes()( see line 94 here: https://twistedmatrix.com/trac/changeset/44579/trunk/twisted/internet/base.py), but in case of DelayedCall object there was __str__ but there was no __bytes__. This only mattered in one untested case when canceling DelayedCall in debug mode. 

Aside from this debug mode is enabled at class level, but important property that matters for this mode (DelayedCall "creator" property) is only called at instance initialization. It means that users setting debug mode on instance (not on class) e.g. here [[#8307](https://github.com/twisted/twisted/issues/8307)](https://github.com/twisted/twisted/issues/8307) were getting errors because __init__ was executed with incorrect value of "debug". 

So there were 3 bugs here:

* debug mode was not tested
* there was no way to set debug mode on instance
* there was problem in debug mode on cancel()

All this is now fixed see patch attached. 

Note that this patch also fixes: #8307 and [#8306](https://github.com/twisted/twisted/issues/8306) so please close those related ticket if patch works ok.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_4"></a>|@glyph set owner to @pawelmhm|
|-|-|

pawelmhm,

Thanks for your work on this, it's great to have nice debuggability / reliability fixes like this.  I have just a little feedback:

  1. Would you mind fixing up the patch to test using the public interface, i.e. `str()`, rather than the irrelevant internal `_str` attribute?  It seems like the old, bad behavior could be provoked using the public API as well.
  2. Can you add a docstring to `setUp`?
  3. This decoding should be conditional, since `__str__` _really_ should return bytes on py2.  Perhaps you could add a `__unicode__`?

Please address these issues to your satisfaction and re-submit.

Thank you!

**Comment by twisted-trac** [comment]
|[<img alt="pawelmhm's avatar" src="https://avatars.githubusercontent.com/u/2700942?s=50" width="50" height="50">](https://github.com/pawelmhm)<a name="note_5"></a>|@pawelmhm removed owner|
|-|-|

> Would you mind fixing up the patch to test using the public interface, i.e. str(), rather than the irrelevant internal _str attribute? It seems like the old, bad behavior could be provoked using the public API as well.

done

> Can you add a docstring to setUp?

done

> This decoding should be conditional, since __str__ really should return bytes on py2. 

After thinking about this I realized bytes() were only used internally in DelayedCall and they were only used in this deprecated _str attribute. After removing _str and updating logic around it there is no longer need for bytes.

> Perhaps you could add a __unicode__?

looking into what str does I dont see any point where it can actually be useful to handle unicode. Maybe I'm missing something but all values handled by __str__ (function name, time, etc) are guaranteed to be ascii. So I wonder if we really need unicode here? Let me know when we need it.

New patch attached.

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_6"></a>|@rodrigc set owner to @pawelmhm|
|-|-|

There have been a lot of Python 3 fixes committed to trunk, so your
patch is outdated.  Also, in the past month, the Twisted project has switched
to allowing patch contributions via GitHub.

Can you follow the steps in this document, and re-submit your patch via GitHub:

https://twistedmatrix.com/trac/wiki/TwistedDevelopment#SubmittingaPatch

**Comment by twisted-trac** [comment]
|[<img alt="pawelmhm's avatar" src="https://avatars.githubusercontent.com/u/2700942?s=50" width="50" height="50">](https://github.com/pawelmhm)<a name="note_7"></a>|@pawelmhm removed owner|
|-|-|

> There have been a lot of Python 3 fixes committed to trunk, so your patch is outdated. 

which part is outdated?

> Also, in the past month, the Twisted project has switched to allowing patch contributions via GitHub.Can you follow the steps in this document, and re-submit your patch via GitHub


sure will do that

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_9"></a>|@rodrigc set owner to @pawelmhm|
|-|-|

I think your patch might be OK, but let's confirm after you submit as per: https://twistedmatrix.com/trac/wiki/TwistedDevelopment#SubmittingaPatch

and some of the automated tests run.
Please set back to review after you have done so.

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_10"></a>|@rodrigc set status to `closed`|
|-|-|

Duplicate of ticket:8995
