### ISSUE TITLE
twistd web traceback when trailing slash is missing

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#8179]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)| @thijstriemstra reported|
|-|-|
|Trac ID|trac#8179|
|Type|defect|
|Created|2016-01-18 16:06:45Z|

I have a twistd web server running with `twistd -no web --path=.` on OSX 10.11 under Python 3.4.3 using Twisted svn trunk r46618.

When visiting a path without a trailing slash, e.g. http://localhost:8080/foo, I see the following traceback in the browser:

```
2016-01-18 17:01:49+0100 [HTTPChannel,1,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/Users/thijstriemstra/projects/twisted/twisted/protocols/basic.py", line 571, in dataReceived
	    why = self.lineReceived(line)
	  File "/Users/thijstriemstra/projects/twisted/twisted/web/http.py", line 1657, in lineReceived
	    self.allContentReceived()
	  File "/Users/thijstriemstra/projects/twisted/twisted/web/http.py", line 1736, in allContentReceived
	    req.requestReceived(command, path, version)
	  File "/Users/thijstriemstra/projects/twisted/twisted/web/http.py", line 762, in requestReceived
	    self.process()
	--- <exception caught here> ---
	  File "/Users/thijstriemstra/projects/twisted/twisted/web/server.py", line 183, in process
	    self.render(resrc)
	  File "/Users/thijstriemstra/projects/twisted/twisted/web/server.py", line 234, in render
	    body = resrc.render(self)
	  File "/Users/thijstriemstra/projects/twisted/twisted/web/resource.py", line 250, in render
	    return m(request)
	  File "/Users/thijstriemstra/projects/twisted/twisted/web/static.py", line 577, in render_GET
	    return self.redirect(request)
	  File "/Users/thijstriemstra/projects/twisted/twisted/web/static.py", line 613, in redirect
	    return redirectTo(addSlash(request), request)
	  File "/Users/thijstriemstra/projects/twisted/twisted/web/static.py", line 66, in addSlash
	    qindex = request.uri.find('?')
	builtins.TypeError: 'str' does not support the buffer interface
```

<details><summary>Searchable metadata</summary>

```
trac-id__8179 8179
type__defect defect
reporter__thijs thijs
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__duplicate duplicate
component__web web
keywords__None None
time__1453133205626002 1453133205626002
changetime__1453133713590823 1453133713590823
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_1"></a>|@adiroiban set status to `closed`|
|-|-|

Looks like a duplicate of [#8169](https://github.com/twisted/twisted/issues/8169)

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_2"></a>|@thijstriemstra commented|
|-|-|

Oops, thanks!
