### ISSUE TITLE
twisted.web incompatible with AF_UNIX sockets

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#8217]
|<img alt="infosec812's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| infosec812 reported|
|-|-|
|Trac ID|trac#8217|
|Type|defect|
|Created|2016-02-24 22:01:40Z|

2016-02-24 16:15:36-0500 [HTTPChannel,0,] Unhandled Error
        Traceback (most recent call last):
          File "/Users/deven.phillips/.virtualenvs/ops-ls/lib/python2.7/site-packages/Twisted-15.5.0-py2.7-macosx-10.11-intel.egg/twisted/protocols/basic.py", line 571, in dataReceived
            why = self.lineReceived(line)
          File "/Users/deven.phillips/.virtualenvs/ops-ls/lib/python2.7/site-packages/Twisted-15.5.0-py2.7-macosx-10.11-intel.egg/twisted/web/http.py", line 1720, in lineReceived
            self.allContentReceived()
          File "/Users/deven.phillips/.virtualenvs/ops-ls/lib/python2.7/site-packages/Twisted-15.5.0-py2.7-macosx-10.11-intel.egg/twisted/web/http.py", line 1799, in allContentReceived
            req.requestReceived(command, path, version)
          File "/Users/deven.phillips/.virtualenvs/ops-ls/lib/python2.7/site-packages/Twisted-15.5.0-py2.7-macosx-10.11-intel.egg/twisted/web/http.py", line 832, in requestReceived
            self.process()
        --- <exception caught here> ---
          File "/Users/deven.phillips/.virtualenvs/ops-ls/lib/python2.7/site-packages/Twisted-15.5.0-py2.7-macosx-10.11-intel.egg/twisted/web/server.py", line 183, in process
            self.render(resrc)
          File "/Users/deven.phillips/.virtualenvs/ops-ls/lib/python2.7/site-packages/Twisted-15.5.0-py2.7-macosx-10.11-intel.egg/twisted/web/server.py", line 234, in render
            body = resrc.render(self)
          File "/Users/deven.phillips/.virtualenvs/ops-ls/lib/python2.7/site-packages/klein-15.3.1-py2.7.egg/klein/resource.py", line 149, in render
            _extractURLparts(request)
          File "/Users/deven.phillips/.virtualenvs/ops-ls/lib/python2.7/site-packages/klein-15.3.1-py2.7.egg/klein/resource.py", line 78, in _extractURLparts
            server_port = request.getHost().port
        exceptions.AttributeError: 'UNIXAddress' object has no attribute 'port'
        
2016-02-24 16:15:36-0500 [-] "-" - - [24/Feb/2016:21:15:36 +0000] "GET /v3/na/vm/4PBNODE01 HTTP/1.1" 500 4928 "-" "python-requests/2.9.1"

<details><summary>Searchable metadata</summary>

```
trac-id__8217 8217
type__defect defect
reporter__infosec812 infosec812
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__invalid invalid
component__web web
keywords__AF_UNIX__UNIXAddress__web AF_UNIX, UNIXAddress, web
time__1456351300522911 1456351300522911
changetime__1456385168892785 1456385168892785
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="mithrandi's avatar" src="https://avatars.githubusercontent.com/u/856430?s=50" width="50" height="50">](https://github.com/mithrandi)<a name="note_1"></a>|@mithrandi set status to `closed`|
|-|-|

As far as I can tell, this is a problem with `klein`, not with `twisted.web` itself. It looks like someone else already reported the bug in the klein bug tracker, so you may want to subscribe to that issue: https://github.com/twisted/klein/issues/102

**Comment by twisted-trac** [comment]
|[<img alt="mithrandi's avatar" src="https://avatars.githubusercontent.com/u/856430?s=50" width="50" height="50">](https://github.com/mithrandi)<a name="note_2"></a>|@mithrandi commented|
|-|-|

Oh, sorry, I only noticed you are the one that contributed a fix in klein after I wrote my response :)
