### ISSUE TITLE
twisted.conch._version not available for python3 builds

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#8218]
|<img alt="doko's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| doko reported|
|-|-|
|Trac ID|trac#8218|
|Type|defect|
|Created|2016-02-24 22:50:30Z|

$ python3 -c 'import twisted.conch'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/twisted/conch/__init__.py", line 9, in <module>
    from twisted.conch._version import version
ImportError: No module named 'twisted.conch._version'

Attachments:

* [py3-twisted-conch.diff](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/271/271a48ea5da859f9d7b0d3a86a9b5b09ea2eb504/ceda5368a84e5c2a56165301367c09f4cbcd534d.diff) (404 bytes) - added by doko on 2016-02-24 22:51:04Z - patch

<details><summary>Searchable metadata</summary>

```
trac-id__8218 8218
type__defect defect
reporter__doko doko
priority__normal normal
milestone__Python_3_x Python-3.x
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__conch conch
keywords__None None
time__1456354230058950 1456354230058950
changetime__1503987559607578 1503987559607578
version__None None
owner__None None
cc__z3p
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_2"></a>|@hawkowl commented|
|-|-|

Please see [#8219](https://github.com/twisted/twisted/issues/8219) -- those _versions shouldnt be there anymore.

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_3"></a>|@rodrigc commented|
|-|-|

Fixed in [ticket:8219]

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)|@rodrigc set status to `closed`|
|-|-|
