### ISSUE TITLE
Can not import  twisted.trial.reporter without first importing unittest (or some other class)

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#8267]
|<img alt="alex----'s avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| alex---- reported|
|-|-|
|Trac ID|trac#8267|
|Type|defect|
|Created|2016-04-01 18:30:03Z|

Looks like importing reporter imports unittest, which imports _asyncrunner which import reporter which is not going to be possible while trying to import reporter.

You can work around the issue by importing unittest first (which imports _asyncrunner which imports reporter.

This was not the case in earlier versions of twisted. I am seeing it in version 16.0.0 of twisted.

```
>>> from twisted.trial import reporter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/twisted/trial/reporter.py", line 29, in <module>
    from twisted.trial.unittest import makeTodo
  File "/usr/local/lib/python2.7/dist-packages/twisted/trial/unittest.py", line 16, in <module>
    from twisted.trial._asyncrunner import (
  File "/usr/local/lib/python2.7/dist-packages/twisted/trial/_asyncrunner.py", line 16, in <module>
    from twisted.trial import itrial, reporter
ImportError: cannot import name reporter
>>> from twisted.trial import unittest
>>> from twisted.trial import reporter
>>>
```

<details><summary>Searchable metadata</summary>

```
trac-id__8267 8267
type__defect defect
reporter__alex____ alex----
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__trial trial
keywords__tests tests
time__1459535403041496 1459535403041496
changetime__1563761239852394 1563761239852394
version__None None
owner__twm twm
cc__jml
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_2"></a>|@thijstriemstra commented|
|-|-|

fixing markup

**Comment by twisted-trac** [comment]
|[<img alt="Julian's avatar" src="https://avatars.githubusercontent.com/u/329822?s=50" width="50" height="50">](https://github.com/Julian)<a name="note_3"></a>|@Julian commented|
|-|-|

[#8759](https://github.com/twisted/twisted/issues/8759) was closed as a duplicate of this ticket.

**Comment by twisted-trac** [comment]
|[<img alt="cjwatson's avatar" src="https://avatars.githubusercontent.com/u/2429141?s=50" width="50" height="50">](https://github.com/cjwatson)<a name="note_4"></a>|@cjwatson commented|
|-|-|

https://github.com/twisted/twisted/pull/1148

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_5"></a>|@twm set owner to @twm|
|-|-|

Reviewed: https://github.com/twisted/twisted/pull/1148#pullrequestreview-261527868

I will wait for a few days for further feedback on #twisted-dev in case anyone objects to merging without tests. In the meantime I'll keep this assigned to me.

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_6"></a>|@twm set status to `closed`|
|-|-|

Merged in https://github.com/twisted/twisted/commit/a4c171b461533f04fa7c041746e9a708604254e5
