### ISSUE TITLE
HTTP protocol/factory changes broke Nevow test suite

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#8273]
|[<img alt="mithrandi's avatar" src="https://avatars.githubusercontent.com/u/856430?s=50" width="50" height="50">](https://github.com/mithrandi)| @mithrandi reported|
|-|-|
|Trac ID|trac#8273|
|Type|defect|
|Created|2016-04-05 16:12:02Z|

```
[ERROR]
Traceback (most recent call last):
  File "/home/travis/build/twisted/nevow/nevow/test/test_appserver.py", line 228, in test_oldStyle
    proto = self.renderResource('/foo')
  File "/home/travis/build/twisted/nevow/nevow/test/test_appserver.py", line 210, in renderResource
    '', '']))
  File "/home/travis/virtualenv/pypy-2.5.0/site-packages/twisted/web/http.py", line 2058, in dataReceived
    return self._channel.dataReceived(data)
  File "/home/travis/virtualenv/pypy-2.5.0/site-packages/twisted/protocols/basic.py", line 571, in dataReceived
    why = self.lineReceived(line)
  File "/home/travis/virtualenv/pypy-2.5.0/site-packages/twisted/web/http.py", line 1688, in lineReceived
    self.allContentReceived()
  File "/home/travis/virtualenv/pypy-2.5.0/site-packages/twisted/web/http.py", line 1767, in allContentReceived
    req.requestReceived(command, path, version)
  File "/home/travis/virtualenv/pypy-2.5.0/site-packages/twisted/web/http.py", line 736, in requestReceived
    self.client = self.channel.transport.getPeer()
exceptions.AttributeError: 'NoneType' object has no attribute 'getPeer'

nevow.test.test_appserver.Logging.test_oldStyle
```

The tests in question do a whole bunch of fiddling around with a protocol object, and I don't know what's actually breaking, so it's not clear that this should be fixed in Twisted instead of Nevow.

<details><summary>Searchable metadata</summary>

```
trac-id__8273 8273
type__defect defect
reporter__mithrandi mithrandi
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__web web
keywords__None None
time__1459872722004795 1459872722004795
changetime__1461653380723799 1461653380723799
version__None None
owner__hawkowl hawkowl

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_1"></a>|@hawkowl commented|
|-|-|

mithrandi, was this fixed?
