### ISSUE TITLE
AttributeError: 'DelayedCall' object has no attribute 'creator'

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#8306]
|<img alt="allenap's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| allenap reported|
|-|-|
|Trac ID|trac#8306|
|Type|defect|
|Created|2016-04-26 16:04:05Z|

```
Python 3.5.1+ (default, Mar 30 2016, 22:46:26) 
[GCC 5.3.1 20160330] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from twisted.internet.base import DelayedCall
>>> dc = DelayedCall(1, lambda: None, (), {}, lambda dc: None, lambda dc: None)
>>> dc.debug = True
>>> str(dc)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../twisted/internet/base.py", line 206, in __str__
    L.append("\n\ntraceback at creation: \n\n%s" % ('    '.join(self.creator)))
AttributeError: 'DelayedCall' object has no attribute 'creator'
```

```
$ tail -n1 twisted/_version.py 
version = versions.Version('twisted', 16, 1, 1)
```

<details><summary>Searchable metadata</summary>

```
trac-id__8306 8306
type__defect defect
reporter__allenap allenap
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__None None
time__1461686645106304 1461686645106304
changetime__1462290530743285 1462290530743285
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="pawelmhm's avatar" src="https://avatars.githubusercontent.com/u/2700942?s=50" width="50" height="50">](https://github.com/pawelmhm)<a name="note_1"></a>|@pawelmhm commented|
|-|-|

seems like this is caused by [#8110](https://github.com/twisted/twisted/issues/8110) - when I remove dc.debug = True line I dont get any excception
