### ISSUE TITLE
Race in t.p.lockfile.FilesystemLock

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#8440]
|<img alt="allenap's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| allenap reported|
|-|-|
|Trac ID|trac#8440|
|Type|defect|
|Created|2016-06-09 10:44:07Z|

When `Filesystem.lock()` notices a stale lock its next step is to remove the lock file. If a concurrent process is performing the same operation it may be able to remove the stale lock file and write a fresh one in the interval between when the first process detects the stale lock and when the first process removes it. The result is that both processes believe they have the lock. When unlocking, the second process will notice the discrepancy: if the first process has released the lock, it will crash with `FileNotFoundError` (or `IOError` with `errno=ENOENT` in Python 2); if the first process still holds the lock it will crash with `ValueError`.

Use the attached script `lockrace.py` to demonstrate this problem. Some example output:

```
$ python3 lockrace.py 
   1: p1 has the lock
  36: p1 has exited okay
 539: p3 has the lock
1039: p2 has the lock
1542: p3 will release the lock...
Traceback (most recent call last):
  File "lockrace.py", line 108, in <module>
    p3pid = forkfunc(p3)
  File "lockrace.py", line 30, in forkfunc
    func()
  File "lockrace.py", line 84, in p3
    lock.unlock()
  File "/usr/lib/python3/dist-packages/twisted/python/lockfile.py", line 221, in unlock
    "Lock %r not owned by this process" % (self.name,))
ValueError: Lock 'foo' not owned by this process
1573: p3 has exited NON-ZERO
2041: p2 will release the lock...
2041: p2 has released the lock
2069: p2 has exited okay
```

I'm running Twisted 16.0.0 on Ubuntu 16.04 with Python 3.5.1.

Attachments:

* [lockrace.py](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/978/9781311d2df0c033eb6741662fe20a7fc18bba46/f86a431f66dd928486edb6715c513494230957ac.py) (2776 bytes) - added by allenap on 2016-06-09 10:45:40Z - Example script demonstrating the race.

<details><summary>Searchable metadata</summary>

```
trac-id__8440 8440
type__defect defect
reporter__allenap allenap
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__None None
time__1465469047588123 1465469047588123
changetime__1465469047588123 1465469047588123
version__None None
owner__None None

```
</details>

**Comment by exarkun** [comment]
Perhaps we should deprecate FilesystemLock in favor of some better third-party library, eg https://py-filelock.readthedocs.io/en/latest/index.html

I am not aware of any way to implement what FilesystemLock tries to implement in a way that's _actually_ cross-platform.  Instead, distinctive features of each platform need to be leveraged (eg POSIX advisory locks).

**Comment by adiroiban** [comment]
Agree.

I think Twisted should focus on fixing networking issues / provide a common interface for network communication.

A cross-platform implementation for a file lock can be left to be solved by an external project.

Now, you can argue that a file lock is an inter-process communication mechanism, and twisted is all about local or remote inter-process communication.

But since the Twisted project has limited development resources, I think is best to leave this for an external project and not try to reinvent the wheel in Twisted.
