### ISSUE TITLE
Unhandled error using FileBodyProducer for an HTTPS request

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#8473]
|[<img alt="richvdh's avatar" src="https://avatars.githubusercontent.com/u/1389908?s=50" width="50" height="50">](https://github.com/richvdh)| @richvdh reported|
|-|-|
|Trac ID|trac#8473|
|Type|defect|
|Created|2016-06-14 23:03:56Z|

I am using a FileBodyProducer (wrapping a StringIO) to provide the body for an HTTP post over TLS. Occasionally I see a pair of unhandled errors as shown below.

I think that the problem is that the FileBodyProducer reads all of the input from the StringIO before the TLS transport is ready to transmit application data; `TLSMemoryBIOProtocol` tries to tell the `FileBodyProducer` to pauseProducing, but because it has already finished, this throws an error.

From my application's perspective, it is as if the request blocks forever. The deferred never completes.

```
2016-06-14 23:42:28,999 - twisted - 154 - CRITICAL - GET-1- Unhandled Error
Traceback (most recent call last):
  File "/home/rav/matrix/env/local/lib/python2.7/site-packages/twisted/python/log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/rav/matrix/env/local/lib/python2.7/site-packages/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/rav/matrix/env/local/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/rav/matrix/env/local/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/home/rav/matrix/env/local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()
  File "/home/rav/matrix/env/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 209, in doRead
    return self._dataReceived(data)
  File "/home/rav/matrix/env/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 215, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/home/rav/matrix/env/local/lib/python2.7/site-packages/twisted/protocols/tls.py", line 421, in dataReceived
    self._write(bytes)
  File "/home/rav/matrix/env/local/lib/python2.7/site-packages/twisted/protocols/tls.py", line 574, in _write
    self._producer.pauseProducing()
  File "/home/rav/matrix/env/local/lib/python2.7/site-packages/twisted/protocols/tls.py", line 189, in pauseProducing
    self._producer.pauseProducing()
  File "/home/rav/matrix/env/local/lib/python2.7/site-packages/twisted/web/client.py", line 1082, in pauseProducing
    self._task.pause()
  File "/home/rav/matrix/env/local/lib/python2.7/site-packages/twisted/internet/task.py", line 447, in pause
    self._checkFinish()
  File "/home/rav/matrix/env/local/lib/python2.7/site-packages/twisted/internet/task.py", line 507, in _checkFinish
    raise self._completionState
twisted.internet.task.TaskDone: 

2016-06-14 23:42:29,001 - twisted - 154 - CRITICAL - GET-1- Unhandled Error
Traceback (most recent call last):
  File "/home/rav/matrix/synapse/synapse/app/homeserver.py", line 430, in in_thread
    reactor.run()
  File "/home/rav/matrix/env/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/home/rav/matrix/env/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1206, in mainLoop
    self.doIteration(t)
  File "/home/rav/matrix/env/local/lib/python2.7/site-packages/twisted/internet/epollreactor.py", line 396, in doPoll
    log.callWithLogger(selectable, _drdw, selectable, fd, event)
--- <exception caught here> ---
  File "/home/rav/matrix/env/local/lib/python2.7/site-packages/twisted/python/log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/rav/matrix/env/local/lib/python2.7/site-packages/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/rav/matrix/env/local/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/rav/matrix/env/local/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "/home/rav/matrix/env/local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 610, in _doReadOrWrite
    self._disconnectSelectable(selectable, why, inRead)
  File "/home/rav/matrix/env/local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 258, in _disconnectSelectable
    selectable.connectionLost(failure.Failure(why))
  File "/home/rav/matrix/env/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 479, in connectionLost
    self._commonConnection.connectionLost(self, reason)
  File "/home/rav/matrix/env/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 287, in connectionLost
    abstract.FileDescriptor.connectionLost(self, reason)
  File "/home/rav/matrix/env/local/lib/python2.7/site-packages/twisted/internet/abstract.py", line 204, in connectionLost
    self.producer.stopProducing()
  File "/home/rav/matrix/env/local/lib/python2.7/site-packages/twisted/protocols/tls.py", line 209, in stopProducing
    self._producer.stopProducing()
  File "/home/rav/matrix/env/local/lib/python2.7/site-packages/twisted/web/client.py", line 1041, in stopProducing
    self._task.stop()
  File "/home/rav/matrix/env/local/lib/python2.7/site-packages/twisted/internet/task.py", line 497, in stop
    self._checkFinish()
  File "/home/rav/matrix/env/local/lib/python2.7/site-packages/twisted/internet/task.py", line 507, in _checkFinish
    raise self._completionState
twisted.internet.task.TaskDone: 

```

<details><summary>Searchable metadata</summary>

```
trac-id__8473 8473
type__defect defect
reporter__richvdh richvdh
priority__high high
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__web web
keywords__None None
time__1465945436844465 1465945436844465
changetime__1560836651057656 1560836651057656
version__None None
owner__None None
cc__lukasa
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_1"></a>|@glyph set owner to @Lukasa|
|-|-|

Thanks for the bug report!  `pauseProducing` should definitely be a no-op in `FileBodyProducer` at this point in the state machine.  I think Lukasa might be working on a related fix?

**Comment by twisted-trac** [comment]
|[<img alt="Lukasa's avatar" src="https://avatars.githubusercontent.com/u/1382556?s=50" width="50" height="50">](https://github.com/Lukasa)<a name="note_2"></a>|@Lukasa set owner to @glyph|
|-|-|

Somewhat related, certainly: [[#8720](https://github.com/twisted/twisted/issues/8720)](https://github.com/twisted/twisted/issues/8720). #8720 is focused on resumeProducing not throwing exceptions when the body is already consumed, but pauseProducing is fine too.

Given that, in this case, pauseProducing is being *automatically* called in response to the loss of the connection, by the abstract implementation, it seems to safe to say that pauseProducing must *always* complete cleanly. Certainly this specific error is dumb: if the task is complete, there is no need to pause it. The fix seems easy enough: pause the task but allow this error. stopProducing also probably needs the same.

I can write this fix if you want, glyph, but I probably can't get to it until monday. Reassign to me if that is ok.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_3"></a>|@glyph commented|
|-|-|

Sorry, I didn't mean to foist it off onto you; certainly not on a weekend! I just thought (part of) the fix might be a dup of what you were already working on.  If you'd like to pick it up that would be great but if not we can fix in due time.

**Comment by twisted-trac** [comment]
|[<img alt="exvito's avatar" src="https://avatars.githubusercontent.com/u/7661068?s=50" width="50" height="50">](https://github.com/exvito)<a name="note_4"></a>|@exvito commented|
|-|-|

For completeness, I'm linking a treq issue related to this: https://github.com/twisted/treq/issues/185

**Comment by twisted-trac** [comment]
|[<img alt="richvdh's avatar" src="https://avatars.githubusercontent.com/u/1389908?s=50" width="50" height="50">](https://github.com/richvdh)<a name="note_5"></a>|@richvdh commented|
|-|-|

And I'm linking another Twisted issue which may be related: [#6528](https://github.com/twisted/twisted/issues/6528)

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)|@glyph removed owner|
|-|-|
