### ISSUE TITLE
test_outputSignal() hangs on Python 3

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#8583]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)| @rodrigc reported|
|-|-|
|Trac ID|trac#8583|
|Type|defect|
|Created|2016-07-10 05:40:43Z|
|Branch|https://github.com/twisted/twisted/pull/639|

I tried to run this:

```
python3 bin/trial twisted.test.test_iutils.ProcessUtilsTests.test_outputSignal

twisted.test.test_iutils
  ProcessUtilsTests
    test_outputSignal ... 
```

and the test was hung.  If I run it under Python 2, there is no problem.

I tried debugging this, but couldn't figure it out.  It might be due to the implementation
of exceptions and Failure is very different on Python 3, and these details have not fully
been incorporated in Twisted's Python 3 port.

<details><summary>Searchable metadata</summary>

```
trac-id__8583 8583
type__defect defect
reporter__rodrigc rodrigc
priority__normal normal
milestone__Python_3_x Python-3.x
branch__https___github_com_twisted_twisted_pull_639 https://github.com/twisted/twisted/pull/639
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__None None
time__1468129243625020 1468129243625020
changetime__1482298878090908 1482298878090908
version__None None
owner__rodrigc rodrigc

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_1"></a>|@rodrigc commented|
|-|-|

In changeset da7466bc53bd6cef2c415a2ccaa86ef2c5bcf745
```
#!CommitTicketReference repository="" revision="da7466bc53bd6cef2c415a2ccaa86ef2c5bcf745"
Skip test_outputSignal() on Python 3 because it hangs

Fix for this test will be done under #8583
```

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_2"></a>|@rodrigc commented|
|-|-|

If I run this test using unittest instead of trial:

```
python -m unittest twisted.test.test_iutils.ProcessUtilsTests.test_outputSignal
```

I get this:

```
Traceback (most recent call last):
  File "/Users/crodrigues/twisted7/src/twisted/internet/process.py", line 957, in maybeCallProcessEnded
    self.reapProcess()
  File "/Users/crodrigues/twisted7/src/twisted/internet/process.py", line 335, in reapProcess
    self.processEnded(status)
  File "/Users/crodrigues/twisted7/src/twisted/internet/_baseprocess.py", line 52, in processEnded
    self.maybeCallProcessEnded()
  File "/Users/crodrigues/twisted7/src/twisted/internet/process.py", line 959, in maybeCallProcessEnded
    _BaseProcess.maybeCallProcessEnded(self)
--- <exception caught here> ---
  File "/Users/crodrigues/twisted7/src/twisted/internet/_baseprocess.py", line 64, in maybeCallProcessEnded
    proto.processEnded(Failure(reason))
  File "/Users/crodrigues/twisted7/src/twisted/internet/utils.py", line 161, in processEnded
    self.deferred.errback((out, err, e.signal))
  File "/Users/crodrigues/twisted7/src/twisted/internet/defer.py", line 432, in errback
    fail = failure.Failure(fail)
  File "/Users/crodrigues/twisted7/src/twisted/python/failure.py", line 232, in __init__
    tb = self.value.__traceback__
builtins.AttributeError: 'tuple' object has no attribute '__traceback__'
```

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_3"></a>|@rodrigc commented|
|-|-|

https://github.com/twisted/twisted/pull/514

**Comment by twisted-trac** [comment]
|[<img alt="marcogiusti's avatar" src="https://avatars.githubusercontent.com/u/154377?s=50" width="50" height="50">](https://github.com/marcogiusti)|@marcogiusti set owner to @marcogiusti<br>@marcogiusti set status to `assigned`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="marcogiusti's avatar" src="https://avatars.githubusercontent.com/u/154377?s=50" width="50" height="50">](https://github.com/marcogiusti)<a name="note_5"></a>|@marcogiusti commented|
|-|-|

Looks good to me

**Comment by twisted-trac** [comment]
|[<img alt="marcogiusti's avatar" src="https://avatars.githubusercontent.com/u/154377?s=50" width="50" height="50">](https://github.com/marcogiusti)|@marcogiusti set owner to @rodrigc<br>@marcogiusti set status to `new`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_7"></a>|@hawkowl commented|
|-|-|

This is actually the wrong solution, sorry, we discussed it on another ticket :(

errbacking a non-Exception is wrong and only works by accident in 2.7...

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_8"></a>|@hawkowl commented|
|-|-|

[#8562](https://github.com/twisted/twisted/issues/8562) is the underlying problem.

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)|@rodrigc removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_11"></a>|@hawkowl set owner to @rodrigc|
|-|-|

LGTM

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_12"></a>|@rodrigc set status to `closed`|
|-|-|

In changeset 926c8cc9fc1788543ef284911888560be1eca917
```
#!CommitTicketReference repository="" revision="926c8cc9fc1788543ef284911888560be1eca917"
Merge pull request #639 from twisted/8583-rodrigc-outputsignal-py3

Author: rodrigc
Reviewer: hawkowl
Fixes: ticket:8583

Run test_outputSignal on Python 3
```
