### ISSUE TITLE
test_cgi fails on Python 3

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#8602]
|[<img alt="acabhishek942's avatar" src="https://avatars.githubusercontent.com/u/7778186?s=50" width="50" height="50">](https://github.com/acabhishek942)| @acabhishek942 reported|
|-|-|
|Trac ID|trac#8602|
|Type|defect|
|Created|2016-07-15 04:57:30Z|

If I do this with Python 2:

```
python2 bin/trial twisted/web/test/test_cgi.py
twisted.web.test.test_cgi
  CGIDirectoryTests
    test_notFoundChild ...                                                 [OK]
    test_render ...                                                        [OK]
  CGIProcessProtocolTests
    test_prematureEndOfHeaders ...                                         [OK]
  CGIScriptTests
    test_pathInfo ...                                                      [OK]
  CGITests
    testCGI ...                                                            [OK]
    testReadAllInput ...                                                   [OK]
    testReadEmptyInput ...                                                 [OK]
    testReadInput ...                                                      [OK]
    test_duplicateHeaderCGI ...                                            [OK]
    test_malformedHeaderCGI ...                                            [OK]
    test_noDuplicateContentTypeHeaders ...                                 [OK]
    test_protectedServerAndDate ...                                        [OK]
    test_useReactorArgument ...                                            [OK]

-------------------------------------------------------------------------------
Ran 13 tests in 0.345s

PASSED (successes=13)

```

but with python 3

```
 python3 bin/trial twisted/web/test/test_cgi.py
twisted/web/test/test_cgi
  py ...                                                                [ERROR]

===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/home/ac/Twisted/twisted/trial/runner.py", line 781, in loadByName
    return self.suiteFactory([self.findByName(name, recurse=recurse)])
  File "/home/ac/Twisted/twisted/trial/runner.py", line 682, in findByName
    return self.loadFile(_name, recurse=recurse)
  File "/home/ac/Twisted/twisted/trial/runner.py", line 652, in loadFile
    module = SourceFileLoader(name, fileName).load_module()
  File "<frozen importlib._bootstrap_external>", line 385, in _check_name_wrapper
    
  File "<frozen importlib._bootstrap_external>", line 806, in load_module
    
  File "<frozen importlib._bootstrap_external>", line 665, in load_module
    
  File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
    
  File "<frozen importlib._bootstrap>", line 693, in _load
    
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
    
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
    
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
    
  File "twisted/web/test/test_cgi.py", line 14, in <module>
    from twisted.web import client, twcgi, server, resource
  File "/home/ac/Twisted/twisted/web/twcgi.py", line 17, in <module>
    from twisted.spread import pb
  File "/home/ac/Twisted/twisted/spread/pb.py", line 46, in <module>
    from twisted.spread.jelly import jelly, unjelly, globalSecurity
  File "/home/ac/Twisted/twisted/spread/jelly.py", line 70, in <module>
    from types import StringType
builtins.ImportError: cannot import name 'StringType'

twisted/web/test/test_cgi.py
-------------------------------------------------------------------------------
Ran 1 tests in 0.064s

FAILED (errors=1)

```

<details><summary>Searchable metadata</summary>

```
trac-id__8602 8602
type__defect defect
reporter__acabhishek942 acabhishek942
priority__normal normal
milestone__Python_3_x Python-3.x
branch__ 
branch_author__ 
status__closed closed
resolution__duplicate duplicate
component__core core
keywords__None None
time__1468558650492257 1468558650492257
changetime__1497119217433109 1497119217433109
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_1"></a>|@rodrigc set status to `closed`|
|-|-|

Duplicate of ticket:8009
