### ISSUE TITLE
twisted.python.win32.quoteArguments problem with Python 3 on Windows

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#8614]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)| @rodrigc reported|
|-|-|
|Trac ID|trac#8614|
|Type|enhancement|
|Created|2016-07-17 06:47:44Z|

I did the followong on Windows with Python 3.5:
`tox -e py35-tests-windows`

and came across a bunch of errors like this:

```
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "c:\projects\twisted\build\py35-tests-windows\lib\site-packages\twisted\test\test_stdio.py", line 227, in test_hostAndPeer
    self._spawnProcess(p, b'stdio_test_hostpeer')
  File "c:\projects\twisted\build\py35-tests-windows\lib\site-packages\twisted\test\test_stdio.py", line 122, in _spawnProcess
    **kw)
  File "c:\projects\twisted\build\py35-tests-windows\lib\site-packages\twisted\internet\posixbase.py", line 353, in spawnProcess
    return Process(self, processProtocol, executable, args, env, path)
  File "c:\projects\twisted\build\py35-tests-windows\lib\site-packages\twisted\internet\_dumbwin32proc.py", line 174, in __init__
    cmdline = quoteArguments(args)
  File "c:\projects\twisted\build\py35-tests-windows\lib\site-packages\twisted\python\win32.py", line 103, in quoteArguments
    return ' '.join([cmdLineQuote(a) for a in arguments])
  File "c:\projects\twisted\build\py35-tests-windows\lib\site-packages\twisted\python\win32.py", line 103, in <listcomp>
    return ' '.join([cmdLineQuote(a) for a in arguments])
  File "c:\projects\twisted\build\py35-tests-windows\lib\site-packages\twisted\python\win32.py", line 90, in cmdLineQuote
    quote = ((" " in s) or ("\t" in s) or ('"' in s) or s == '') and '"' or ''
builtins.TypeError: a bytes-like object is required, not 'str'
twisted.test.test_stdio.StandardInputOutputTests.test_hostAndPeer
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "c:\projects\twisted\build\py35-tests-windows\lib\site-packages\twisted\test\test_stdio.py", line 142, in test_loseConnection
    self._spawnProcess(p, b'stdio_test_loseconn', errorLogFile)
  File "c:\projects\twisted\build\py35-tests-windows\lib\site-packages\twisted\test\test_stdio.py", line 122, in _spawnProcess
    **kw)
  File "c:\projects\twisted\build\py35-tests-windows\lib\site-packages\twisted\internet\posixbase.py", line 353, in spawnProcess
    return Process(self, processProtocol, executable, args, env, path)
  File "c:\projects\twisted\build\py35-tests-windows\lib\site-packages\twisted\internet\_dumbwin32proc.py", line 174, in __init__
    cmdline = quoteArguments(args)
  File "c:\projects\twisted\build\py35-tests-windows\lib\site-packages\twisted\python\win32.py", line 103, in quoteArguments
    return ' '.join([cmdLineQuote(a) for a in arguments])
  File "c:\projects\twisted\build\py35-tests-windows\lib\site-packages\twisted\python\win32.py", line 103, in <listcomp>
    return ' '.join([cmdLineQuote(a) for a in arguments])
  File "c:\projects\twisted\build\py35-tests-windows\lib\site-packages\twisted\python\win32.py", line 90, in cmdLineQuote
    quote = ((" " in s) or ("\t" in s) or ('"' in s) or s == '') and '"' or ''
builtins.TypeError: a bytes-like object is required, not 'str'
twisted.test.test_stdio.StandardInputOutputTests.test_loseConnection
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "c:\projects\twisted\build\py35-tests-windows\lib\site-packages\twisted\test\test_stdio.py", line 294, in test_producer
    proc = self._spawnProcess(p, b'stdio_test_producer')
  File "c:\projects\twisted\build\py35-tests-windows\lib\site-packages\twisted\test\test_stdio.py", line 122, in _spawnProcess
    **kw)
  File "c:\projects\twisted\build\py35-tests-windows\lib\site-packages\twisted\internet\posixbase.py", line 353, in spawnProcess
    return Process(self, processProtocol, executable, args, env, path)
  File "c:\projects\twisted\build\py35-tests-windows\lib\site-packages\twisted\internet\_dumbwin32proc.py", line 174, in __init__
    cmdline = quoteArguments(args)
  File "c:\projects\twisted\build\py35-tests-windows\lib\site-packages\twisted\python\win32.py", line 103, in quoteArguments
    return ' '.join([cmdLineQuote(a) for a in arguments])
  File "c:\projects\twisted\build\py35-tests-windows\lib\site-packages\twisted\python\win32.py", line 103, in <listcomp>
    return ' '.join([cmdLineQuote(a) for a in arguments])
  File "c:\projects\twisted\build\py35-tests-windows\lib\site-packages\twisted\python\win32.py", line 90, in cmdLineQuote
    quote = ((" " in s) or ("\t" in s) or ('"' in s) or s == '') and '"' or ''
builtins.TypeError: a bytes-like object is required, not 'str'
twisted.test.test_stdio.StandardInputOutputTests.test_producer
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "c:\projects\twisted\build\py35-tests-windows\lib\site-packages\twisted\test\test_stdio.py", line 177, in test_readConnectionLost
    p, b'stdio_test_halfclose', errorLogFile)
  File "c:\projects\twisted\build\py35-tests-windows\lib\site-packages\twisted\test\test_stdio.py", line 122, in _spawnProcess
    **kw)
  File "c:\projects\twisted\build\py35-tests-windows\lib\site-packages\twisted\internet\posixbase.py", line 353, in spawnProcess
    return Process(self, processProtocol, executable, args, env, path)
  File "c:\projects\twisted\build\py35-tests-windows\lib\site-packages\twisted\internet\_dumbwin32proc.py", line 174, in __init__
    cmdline = quoteArguments(args)
  File "c:\projects\twisted\build\py35-tests-windows\lib\site-packages\twisted\python\win32.py", line 103, in quoteArguments
    return ' '.join([cmdLineQuote(a) for a in arguments])
  File "c:\projects\twisted\build\py35-tests-windows\lib\site-packages\twisted\python\win32.py", line 103, in <listcomp>
    return ' '.join([cmdLineQuote(a) for a in arguments])
  File "c:\projects\twisted\build\py35-tests-windows\lib\site-packages\twisted\python\win32.py", line 90, in cmdLineQuote
    quote = ((" " in s) or ("\t" in s) or ('"' in s) or s == '') and '"' or ''
builtins.TypeError: a bytes-like object is required, not 'str'
twisted.test.test_stdio.StandardInputOutputTests.test_readConnectionLost
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "c:\projects\twisted\build\py35-tests-windows\lib\site-packages\twisted\test\test_stdio.py", line 245, in test_write
    self._spawnProcess(p, b'stdio_test_write')
  File "c:\projects\twisted\build\py35-tests-windows\lib\site-packages\twisted\test\test_stdio.py", line 122, in _spawnProcess
    **kw)
  File "c:\projects\twisted\build\py35-tests-windows\lib\site-packages\twisted\internet\posixbase.py", line 353, in spawnProcess
    return Process(self, processProtocol, executable, args, env, path)
  File "c:\projects\twisted\build\py35-tests-windows\lib\site-packages\twisted\internet\_dumbwin32proc.py", line 174, in __init__
    cmdline = quoteArguments(args)
  File "c:\projects\twisted\build\py35-tests-windows\lib\site-packages\twisted\python\win32.py", line 103, in quoteArguments
    return ' '.join([cmdLineQuote(a) for a in arguments])
  File "c:\projects\twisted\build\py35-tests-windows\lib\site-packages\twisted\python\win32.py", line 103, in <listcomp>
    return ' '.join([cmdLineQuote(a) for a in arguments])
  File "c:\projects\twisted\build\py35-tests-windows\lib\site-packages\twisted\python\win32.py", line 90, in cmdLineQuote
    quote = ((" " in s) or ("\t" in s) or ('"' in s) or s == '') and '"' or ''
builtins.TypeError: a bytes-like object is required, not 'str'
twisted.test.test_stdio.StandardInputOutputTests.test_write
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "c:\projects\twisted\build\py35-tests-windows\lib\site-packages\twisted\test\test_stdio.py", line 261, in test_writeSequence
    self._spawnProcess(p, b'stdio_test_writeseq')
  File "c:\projects\twisted\build\py35-tests-windows\lib\site-packages\twisted\test\test_stdio.py", line 122, in _spawnProcess
    **kw)
  File "c:\projects\twisted\build\py35-tests-windows\lib\site-packages\twisted\internet\posixbase.py", line 353, in spawnProcess
    return Process(self, processProtocol, executable, args, env, path)
  File "c:\projects\twisted\build\py35-tests-windows\lib\site-packages\twisted\internet\_dumbwin32proc.py", line 174, in __init__
    cmdline = quoteArguments(args)
  File "c:\projects\twisted\build\py35-tests-windows\lib\site-packages\twisted\python\win32.py", line 103, in quoteArguments
    return ' '.join([cmdLineQuote(a) for a in arguments])
  File "c:\projects\twisted\build\py35-tests-windows\lib\site-packages\twisted\python\win32.py", line 103, in <listcomp>
    return ' '.join([cmdLineQuote(a) for a in arguments])
  File "c:\projects\twisted\build\py35-tests-windows\lib\site-packages\twisted\python\win32.py", line 90, in cmdLineQuote
    quote = ((" " in s) or ("\t" in s) or ('"' in s) or s == '') and '"' or ''
builtins.TypeError: a bytes-like object is required, not 'str'
twisted.test.test_stdio.StandardInputOutputTests.test_writeSequence
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "c:\projects\twisted\build\py35-tests-windows\lib\site-packages\twisted\test\test_threads.py", line 407, in testCallBeforeStartupUnexecuted
    reactor.spawnProcess(proto, sys.executable, ('python', progname), env)
  File "c:\projects\twisted\build\py35-tests-windows\lib\site-packages\twisted\internet\posixbase.py", line 353, in spawnProcess
    return Process(self, processProtocol, executable, args, env, path)
  File "c:\projects\twisted\build\py35-tests-windows\lib\site-packages\twisted\internet\_dumbwin32proc.py", line 174, in __init__
    cmdline = quoteArguments(args)
  File "c:\projects\twisted\build\py35-tests-windows\lib\site-packages\twisted\python\win32.py", line 103, in quoteArguments
    return ' '.join([cmdLineQuote(a) for a in arguments])
  File "c:\projects\twisted\build\py35-tests-windows\lib\site-packages\twisted\python\win32.py", line 103, in <listcomp>
    return ' '.join([cmdLineQuote(a) for a in arguments])
  File "c:\projects\twisted\build\py35-tests-windows\lib\site-packages\twisted\python\win32.py", line 90, in cmdLineQuote
    quote = ((" " in s) or ("\t" in s) or ('"' in s) or s == '') and '"' or ''
builtins.TypeError: a bytes-like object is required, not 'str'
twisted.test.test_threads.StartupBehaviorTests.testCallBeforeStartupUnexecuted
===============================================================================
[ERROR]
Traceback (most recent call last):
```

<details><summary>Searchable metadata</summary>

```
trac-id__8614 8614
type__enhancement enhancement
reporter__rodrigc rodrigc
priority__normal normal
milestone__Python_3_x Python-3.x
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__None None
time__1468738064131141 1468738064131141
changetime__1484649326552292 1484649326552292
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_1"></a>|@rodrigc set status to `closed`|
|-|-|

Twisted tests are now passing under Python 3.5 on Windows, and running on Appveyor: https://ci.appveyor.com/project/adiroiban/twisted
