### ISSUE TITLE
test_pb fails on Python3

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#8670]
|[<img alt="acabhishek942's avatar" src="https://avatars.githubusercontent.com/u/7778186?s=50" width="50" height="50">](https://github.com/acabhishek942)| @acabhishek942 reported|
|-|-|
|Trac ID|trac#8670|
|Type|enhancement|
|Created|2016-07-25 07:37:53Z|

test_pb in twisted.test fails on Python 3
```
python3 bin/trial twisted/test/test_pb.py
```

```
twisted/test/test_pb
  py ...                                                                [ERROR]

===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/home/ac/Twisted2/twisted/trial/runner.py", line 781, in loadByName
    return self.suiteFactory([self.findByName(name, recurse=recurse)])
  File "/home/ac/Twisted2/twisted/trial/runner.py", line 682, in findByName
    return self.loadFile(_name, recurse=recurse)
  File "/home/ac/Twisted2/twisted/trial/runner.py", line 652, in loadFile
    module = SourceFileLoader(name, fileName).load_module()
  File "<frozen importlib._bootstrap_external>", line 385, in _check_name_wrapper
    
  File "<frozen importlib._bootstrap_external>", line 806, in load_module
    
  File "<frozen importlib._bootstrap_external>", line 665, in load_module
    
  File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
    
  File "<frozen importlib._bootstrap>", line 693, in _load
    
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
    
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
    
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
    
  File "twisted/test/test_pb.py", line 16, in <module>
    from cStringIO import StringIO
builtins.ImportError: No module named 'cStringIO'

twisted/test/test_pb.py
-------------------------------------------------------------------------------
Ran 1 tests in 0.065s


```

<details><summary>Searchable metadata</summary>

```
trac-id__8670 8670
type__enhancement enhancement
reporter__acabhishek942 acabhishek942
priority__normal normal
milestone__Python_3_x Python-3.x
branch__ 
branch_author__ 
status__closed closed
resolution__duplicate duplicate
component__core core
keywords__None None
time__1469432273531512 1469432273531512
changetime__1477003880389594 1477003880389594
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_1"></a>|@rodrigc set status to `closed`|
|-|-|

Duplicate of [ticket:7598]
