### ISSUE TITLE
twisted.words.test.test_oscar fails on Python 3

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#8673]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)| @rodrigc reported|
|-|-|
|Trac ID|trac#8673|
|Type|enhancement|
|Created|2016-07-25 10:20:34Z|

If I do this on Python 3:

```
python bin/trial twisted.words.test.test_oscar
```

I get this:

```
twisted.words.test.test_oscar
  OscarDeprecationTests
    test_deprecated ...                                                    [OK]
  PasswordTests
    test_encryptPasswordMD5 ...                                         [ERROR]

===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/Users/crodrigues/twisted/twisted/words/test/test_oscar.py", line 23, in test_encryptPasswordMD5
    encryptPasswordMD5('foo', 'bar').encode('hex'),
  File "/Users/crodrigues/twisted/twisted/words/protocols/oscar.py", line 63, in encryptPasswordMD5
    m.update(key)
builtins.TypeError: Unicode-objects must be encoded before hashing

twisted.words.test.test_oscar.PasswordTests.test_encryptPasswordMD5
-------------------------------------------------------------------------------
Ran 2 tests in 0.003s

FAILED (errors=1, successes=1)
```

<details><summary>Searchable metadata</summary>

```
trac-id__8673 8673
type__enhancement enhancement
reporter__rodrigc rodrigc
priority__normal normal
milestone__Python_3_x Python-3.x
branch__ 
branch_author__ 
status__closed closed
resolution__wontfix wontfix
component__core core
keywords__None None
time__1469442034787454 1469442034787454
changetime__1469538260275784 1469538260275784
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="acabhishek942's avatar" src="https://avatars.githubusercontent.com/u/7778186?s=50" width="50" height="50">](https://github.com/acabhishek942)<a name="note_1"></a>|@acabhishek942 set status to `closed`|
|-|-|

this module was deprecated in [#8260](https://github.com/twisted/twisted/issues/8260).
