### ISSUE TITLE
A few conch tests are failing if not on an interactive tty

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#8715]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)| @rodrigc reported|
|-|-|
|Trac ID|trac#8715|
|Type|defect|
|Created|2016-08-02 03:40:00Z|
|Branch|https://github.com/twisted/twisted/tree/8715-rodrigc-conch-default-ttyskip|

A few of the new conch tests pass on Travis, but fail on the buildbots because they are trying
to open /dev/tty.  

For example: https://buildbot.twistedmatrix.com/builders/fedora22-py3.4/builds/1196/steps/select/logs/stdio

```
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/buildslave/fedora22-python-3.4/Twisted/build/py34-tests-posix/lib/python3.4/site-packages/twisted/conch/test/test_default.py", line 283, in test_getGenericAnswers
    (b"pass prompt", False), (b"raw_input prompt", True)])
  File "/buildslave/fedora22-python-3.4/Twisted/build/py34-tests-posix/lib/python3.4/site-packages/twisted/conch/client/default.py", line 258, in getGenericAnswers
    with self._replaceStdoutStdin():
  File "/usr/lib64/python3.4/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/buildslave/fedora22-python-3.4/Twisted/build/py34-tests-posix/lib/python3.4/site-packages/twisted/conch/client/default.py", line 294, in _replaceStdoutStdin
    sys.stdin, sys.stdout = cls._openTty()
  File "/buildslave/fedora22-python-3.4/Twisted/build/py34-tests-posix/lib/python3.4/site-packages/twisted/conch/client/default.py", line 278, in _openTty
    stdin = open("/dev/tty", "rb")
builtins.OSError: [Errno 6] No such device or address: '/dev/tty'

twisted.conch.test.test_default.SSHUserAuthClientTests.test_getGenericAnswers
===============================================================================
```

<details><summary>Searchable metadata</summary>

```
trac-id__8715 8715
type__defect defect
reporter__rodrigc rodrigc
priority__normal normal
milestone__Python_3_x Python-3.x
branch__8715_rodrigc_conch_default_ttyskip 8715-rodrigc-conch-default-ttyskip
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__None None
time__1470109200559215 1470109200559215
changetime__1470303693512806 1470303693512806
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_1"></a>|@rodrigc commented|
|-|-|

So it turns out that if I execute the test via the command-line, it works.

However, if I execute over SSH, it fails.

Here is what I did.  I created this script  test_it.sh:

```
#!/bin/sh


. ~/venv/bin/activate
cd ~/twisted11/
python -m unittest twisted.conch.test.test_default
```

Then instead of executing the script locally, I did:

```
ssh mybox "sh ./test_it.sh"
```

And I got the same failure as on the buildbot:

```
======================================================================
ERROR: test_getPasswordPrompt (twisted.conch.test.test_default.SSHUserAuthClientTests)
test_getPasswordPrompt
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/crodrigues/twisted11/twisted/internet/defer.py", line 149, in maybeDeferred
    result = f(*args, **kw)
  File "/Users/crodrigues/twisted11/twisted/internet/utils.py", line 201, in runWithWarningsSuppressed
    reraise(exc_info[1], exc_info[2])
  File "/Users/crodrigues/twisted11/twisted/python/compat.py", line 433, in reraise
    raise exception.with_traceback(traceback)
  File "/Users/crodrigues/twisted11/twisted/internet/utils.py", line 197, in runWithWarningsSuppressed
    result = f(*a, **kw)
  File "/Users/crodrigues/twisted11/twisted/conch/test/test_default.py", line 232, in test_getPasswordPrompt
    d = client.getPassword(prompt)
  File "/Users/crodrigues/twisted11/twisted/conch/client/default.py", line 182, in getPassword
    p = self._getPassword(prompt).encode(sys.getdefaultencoding())
  File "/Users/crodrigues/twisted11/twisted/conch/client/default.py", line 164, in _getPassword
    with self._replaceStdoutStdin():
  File "/usr/local/Cellar/python3/HEAD/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 82, in __enter__
    return next(self.gen)
  File "/Users/crodrigues/twisted11/twisted/conch/client/default.py", line 294, in _replaceStdoutStdin
    sys.stdin, sys.stdout = cls._openTty()
  File "/Users/crodrigues/twisted11/twisted/conch/client/default.py", line 278, in _openTty
    stdin = open("/dev/tty", "rb")
OSError: [Errno 6] Device not configured: '/dev/tty'

----------------------------------------------------------------------
```

It turns out that we should not open /dev/tty if we are not in an interactive tty.

Luckily we can check.  If

sys.stdin.isatty()  or sys.stdout.isatty() return False,
then we should skip the test.

If you type this from the command-line:

python -c "import sys; print(sys.stdout.isatty())"

You get:

True

But if you do:

ssh myhost "python -c 'import sys; print(sys.stdout.isatty())'"

you get:

False

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_3"></a>|@rodrigc set status to `closed`|
|-|-|

Fixed in https://github.com/twisted/twisted/commit/eb53e2ef803b74d66241060a7a4410c3c4dcf301
