### ISSUE TITLE
Circular dependency on twisted.trial.reporter leads to ImportError

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#8759]
|[<img alt="nessita's avatar" src="https://avatars.githubusercontent.com/u/124304?s=50" width="50" height="50">](https://github.com/nessita)| @nessita reported|
|-|-|
|Trac ID|trac#8759|
|Type|defect|
|Created|2016-08-14 20:20:04Z|

Hello,

I'm using python-twisted-core from the debian package available in Ubuntu LTS 16.04 (Xenial), version 16.0.0-1.

I get an ImportError when trying to import from twisted.trial.reporter caused by a circular import between reporter -> unittest -> _asynctestrunner -> reporter:

```
>>> from twisted.trial.reporter import TreeReporter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/twisted/trial/reporter.py", line 29, in <module>
    from twisted.trial.unittest import makeTodo
  File "/usr/lib/python2.7/dist-packages/twisted/trial/unittest.py", line 16, in <module>
    from twisted.trial._asyncrunner import (
  File "/usr/lib/python2.7/dist-packages/twisted/trial/_asyncrunner.py", line 16, in <module>
    from twisted.trial import itrial, reporter
ImportError: cannot import name reporter
```

<details><summary>Searchable metadata</summary>

```
trac-id__8759 8759
type__defect defect
reporter__nessita nessita
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__duplicate duplicate
component__core core
keywords__None None
time__1471206004644305 1471206004644305
changetime__1489534460966318 1489534460966318
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="Julian's avatar" src="https://avatars.githubusercontent.com/u/329822?s=50" width="50" height="50">](https://github.com/Julian)<a name="note_3"></a>|@Julian set status to `closed`|
|-|-|

This is a duplicate of [#8267](https://github.com/twisted/twisted/issues/8267).
