### ISSUE TITLE
Test Failure in twisted.words.test.test_domish.ElementTests.test_addContentBytes

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#8779]
|[<img alt="reaperhulk's avatar" src="https://avatars.githubusercontent.com/u/161495?s=50" width="50" height="50">](https://github.com/reaperhulk)| @reaperhulk reported|
|-|-|
|Trac ID|trac#8779|
|Type|defect|
|Created|2016-08-23 01:51:36Z|

In the current twisted trunk twisted.words.test.test_domish.ElementTests.test_addContentBytes fails when run under tox with 

```
[ERROR]
Traceback (most recent call last):
  File "/home/travis/build/pyca/pyopenssl/.tox/py27-twistedMaster/lib/python2.7/site-packages/twisted/python/test/test_setup.py", line 338, in test_find_package_modules
    result = builder.find_package_modules('twisted.test', packageDir)
  File "/home/travis/build/pyca/pyopenssl/.tox/py27-twistedMaster/lib/python2.7/site-packages/twisted/python/_setup.py", line 247, in find_package_modules
    in build_py.find_package_modules(self, package, package_dir)
  File "/opt/python/2.7.9/lib/python2.7/distutils/command/build_py.py", line 219, in find_package_modules
    self.check_package(package, package_dir)
  File "/home/travis/build/pyca/pyopenssl/.tox/py27-twistedMaster/lib/python2.7/site-packages/setuptools/command/build_py.py", line 163, in check_package
    init_py = orig.build_py.check_package(self, package, package_dir)
  File "/opt/python/2.7.9/lib/python2.7/distutils/command/build_py.py", line 192, in check_package
    "package directory '%s' does not exist" % package_dir)
distutils.errors.DistutilsFileError: package directory '../src/twisted/test' does not exist
```

This can be seen in the smoke tests that pyopenssl runs on travis (https://travis-ci.org/pyca/pyopenssl/jobs/154167412) but can also be replicated by installing twisted trunk into a virtualenv and then (from a working directory that is NOT the twisted trunk) running `trial --reporter=text twisted`

This appears to be caused by these lines https://github.com/twisted/twisted/blob/trunk/src/twisted/python/test/test_setup.py#L333-L336, which assume an uninstalled copy of twisted (e.g. a source clone where `src` would be present) is somewhere in nearby the current working directory.

<details><summary>Searchable metadata</summary>

```
trac-id__8779 8779
type__defect defect
reporter__reaperhulk reaperhulk
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__None None
time__1471917096159725 1471917096159725
changetime__1471937981739341 1471937981739341
version__None None
owner__markrwilliams markrwilliams

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_1"></a>|@markrwilliams commented|
|-|-|

https://github.com/twisted/twisted/pull/519 makes the test pass on Python 3, in any directory, and also skips the test on Python 2 (and, uh, Python 4).

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_2"></a>|@rodrigc set owner to @reaperhulk|
|-|-|

https://github.com/twisted/twisted/pull/519#issuecomment-241626221

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_3"></a>|@glyph set owner to @markrwilliams|
|-|-|

Reassigning to the actual committer :).

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_4"></a>|@markrwilliams set status to `closed`|
|-|-|

I plopped my fingers down on the keyboard all wrong and bungled the merge commit's message.  This should now closed:

https://github.com/twisted/twisted/commit/51cf22234187ff552be61a5c8a994a10b9899287
