### ISSUE TITLE
console_scripts doesn't add os.getcwd() to twistd

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#8807]
|[<img alt="sxamit's avatar" src="https://avatars.githubusercontent.com/u/12122696?s=50" width="50" height="50">](https://github.com/sxamit)| @sxamit reported|
|-|-|
|Trac ID|trac#8807|
|Type|defect|
|Created|2016-09-07 10:16:57Z|

Version 16.3.2 added os.getcwd() to sys.path: https://github.com/twisted/twisted/blob/twisted-16.3.2/bin/twistd
The new console_scripts in version 16.4.0 doesn't add it - 

```
#!div style="font-size: 80%"
Code highlighting:
  {{{#!python
  #!/usr/local/bin/python2

# -*- coding: utf-8 -*-
import re
import sys

from twisted.scripts.twistd import run

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(run())

  ```
}}}

which causes twistd to throw 'No module exception' when running - 
``` 
#!div style="font-size: 80%"
{{{#!python
twistd -n web -p 4000 --class=main.resource
```
}}}

even if running from the correct path

```
#!div style="font-size: 80%"
Code highlighting:
  {{{#!python
 Traceback (most recent call last):
  File "/usr/local/bin/twistd", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 29, in run
    app.run(runApp, ServerOptions)
  File "/usr/local/lib/python2.7/site-packages/twisted/application/app.py", line 643, in run
    config.parseOptions()
  File "/usr/local/lib/python2.7/site-packages/twisted/application/app.py", line 610, in parseOptions
    usage.Options.parseOptions(self, options)
  File "/usr/local/lib/python2.7/site-packages/twisted/python/usage.py", line 267, in parseOptions
    self.subOptions.parseOptions(rest)
  File "/usr/local/lib/python2.7/site-packages/twisted/python/usage.py", line 255, in parseOptions
    self._dispatch[optMangled](optMangled, arg)
  File "/usr/local/lib/python2.7/site-packages/twisted/python/usage.py", line 411, in <lambda>
    fn = lambda name, value, m=method: m(value)
  File "/usr/local/lib/python2.7/site-packages/twisted/web/tap.py", line 129, in opt_class
    classObj = reflect.namedClass(className)
  File "/usr/local/lib/python2.7/site-packages/twisted/python/reflect.py", line 165, in namedObject
    module = namedModule('.'.join(classSplit[:-1]))
  File "/usr/local/lib/python2.7/site-packages/twisted/python/reflect.py", line 151, in namedModule
    topLevel = __import__(name)
ImportError: No module named main
  ```
}}}

<details><summary>Searchable metadata</summary>

```
trac-id__8807 8807
type__defect defect
reporter__sxamit sxamit
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__wontfix wontfix
component__core core
keywords__None None
time__1473243417274100 1473243417274100
changetime__1473262693961425 1473262693961425
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_1"></a>|@hawkowl set status to `closed`|
|-|-|

This is expected behaviour as of 16.4.0; you should install your code before running it.

See [#8802](https://github.com/twisted/twisted/issues/8802) for how we can document this better, see http://twistedmatrix.com/pipermail/twisted-python/2016-August/030774.html as well.

**Comment by twisted-trac** [comment]
|[<img alt="sxamit's avatar" src="https://avatars.githubusercontent.com/u/12122696?s=50" width="50" height="50">](https://github.com/sxamit)<a name="note_2"></a>|@sxamit commented|
|-|-|

Are there guidelines/best practice on how to install and run my code with twistd?
