### ISSUE TITLE
trial fails to execute tests of my project

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#8810]
|[<img alt="evgeni's avatar" src="https://avatars.githubusercontent.com/u/94284?s=50" width="50" height="50">](https://github.com/evgeni)| @evgeni reported|
|-|-|
|Trac ID|trac#8810|
|Type|defect|
|Created|2016-09-10 10:48:12Z|

ohai

I am using trail to run tests for https://github.com/evgeni/bley

This worked just fine upto Twisted 16.3.2, but now broke with 16.4.0.

With the checkout of the project (either master or python3 branch), with 16.3.2 I could do either "trial test" or "trial test/test_bleyhelpers.py" to run the whole suite or just some tests.

With 16.4.0 the behaviour is "funny". When I call "trial test" (and have Twisted installed via pip into a venv) it will run the Twisted testsuite. If I rename the test folder to "tests", and run "trial tests" I get:
Traceback (most recent call last):
```
  File "/tmp/bleh/lib/python3.5/site-packages/twisted/trial/runner.py", line 781, in loadByName
    return self.suiteFactory([self.findByName(name, recurse=recurse)])
  File "/tmp/bleh/lib/python3.5/site-packages/twisted/trial/runner.py", line 710, in findByName
    obj = reflect.namedAny(name)
  File "/tmp/bleh/lib/python3.5/site-packages/twisted/python/reflect.py", line 305, in namedAny
    raise ModuleNotFound("No module named %r" % (name,))
twisted.python.reflect.ModuleNotFound: No module named 'tests'
```

And with "trial tests/test_bleyhelpers.py" I get:
```
% trial tests/test_bleyhelpers.py                                                                                                    :(
tests/test_bleyhelpers
  py ...                                                                [ERROR]

===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/tmp/bleh/lib/python3.5/site-packages/twisted/trial/runner.py", line 781, in loadByName
    return self.suiteFactory([self.findByName(name, recurse=recurse)])
  File "/tmp/bleh/lib/python3.5/site-packages/twisted/trial/runner.py", line 682, in findByName
    return self.loadFile(_name, recurse=recurse)
  File "/tmp/bleh/lib/python3.5/site-packages/twisted/trial/runner.py", line 652, in loadFile
    module = SourceFileLoader(name, fileName).load_module()
  File "<frozen importlib._bootstrap_external>", line 385, in _check_name_wrapper
    
  File "<frozen importlib._bootstrap_external>", line 806, in load_module
    
  File "<frozen importlib._bootstrap_external>", line 665, in load_module
    
  File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
    
  File "<frozen importlib._bootstrap>", line 693, in _load
    
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
    
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
    
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
    
  File "tests/test_bleyhelpers.py", line 2, in <module>
    import bleyhelpers
builtins.ImportError: No module named 'bleyhelpers'
```

(yes, running setup.py install helps in the single-file case, but I'd rather test the current checkout :))

<details><summary>Searchable metadata</summary>

```
trac-id__8810 8810
type__defect defect
reporter__evgeni evgeni
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__wontfix wontfix
component__trial trial
keywords__None None
time__1473504492485888 1473504492485888
changetime__1473521423399677 1473521423399677
version__None None
owner__None None
cc__jml
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="evgeni's avatar" src="https://avatars.githubusercontent.com/u/94284?s=50" width="50" height="50">](https://github.com/evgeni)<a name="note_2"></a>|@evgeni commented|
|-|-|

FYI, running with "python -m twisted.trial" works.

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_3"></a>|@hawkowl set status to `closed`|
|-|-|

Yes, this is expected behaviour from `trial` from 16.4 on. Please install your package before testing it, I recommend using something like tox for this.
