### ISSUE TITLE
twisted.web._auth.wrapper.UnauthorizedResource is only half ported to Python 3

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#8813]
|[<img alt="hynek's avatar" src="https://avatars.githubusercontent.com/u/41240?s=50" width="50" height="50">](https://github.com/hynek)| @hynek reported|
|-|-|
|Trac ID|trac#8813|
|Type|enhancement|
|Created|2016-09-14 11:25:49Z|

When I try to use twisted.web.guard.HTTPAuthSessionWrapper/BasicCredentialFactory on Python 3, code that perfectly work on Python 2 does this to me:

```
2016-09-14T13:18:48+0200 [_GenericHTTPChannelProtocol,0,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/Users/hynek/.virtualenvs/lookup_ws/lib/python3.5/site-packages/twisted/web/server.py", line 241, in render
	    body = resrc.render(self)
	  File "/Users/hynek/.virtualenvs/lookup_ws/lib/python3.5/site-packages/twisted/web/util.py", line 138, in render
	    self.d.addCallback(self._cbChild, request).addErrback(
	  File "/Users/hynek/.virtualenvs/lookup_ws/lib/python3.5/site-packages/twisted/internet/defer.py", line 317, in addCallback
	    callbackKeywords=kw)
	  File "/Users/hynek/.virtualenvs/lookup_ws/lib/python3.5/site-packages/twisted/internet/defer.py", line 306, in addCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/Users/hynek/.virtualenvs/lookup_ws/lib/python3.5/site-packages/twisted/internet/defer.py", line 587, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/Users/hynek/.virtualenvs/lookup_ws/lib/python3.5/site-packages/twisted/web/util.py", line 144, in _cbChild
	    request.render(resource.getChildForRequest(child, request))
	  File "/Users/hynek/.virtualenvs/lookup_ws/lib/python3.5/site-packages/twisted/web/server.py", line 241, in render
	    body = resrc.render(self)
	  File "/Users/hynek/.virtualenvs/lookup_ws/lib/python3.5/site-packages/twisted/web/_auth/wrapper.py", line 59, in render
	    generateWWWAuthenticate(fact.scheme, challenge))
	  File "/Users/hynek/.virtualenvs/lookup_ws/lib/python3.5/site-packages/twisted/web/_auth/wrapper.py", line 48, in generateWWWAuthenticate
	    l.append(networkString("%s=%s" % (k, quoteString(v))))
	  File "/Users/hynek/.virtualenvs/lookup_ws/lib/python3.5/site-packages/twisted/web/_auth/wrapper.py", line 52, in quoteString
	    return '"%s"' % (s.replace('\\', '\\\\').replace('"', '\\"'),)
	builtins.TypeError: a bytes-like object is required, not 'str'
```

render seems to be ported except for generateWWWAuthenticate and the quoteString closures (why do they have to be closures in the first place?  isn’t that wasteful since it gets generated for each rendering?) seem to miss byte string prefixes.

<details><summary>Searchable metadata</summary>

```
trac-id__8813 8813
type__enhancement enhancement
reporter__hynek hynek
priority__normal normal
milestone__Python_3_x Python-3.x
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__web web
keywords__None None
time__1473852349368824 1473852349368824
changetime__1503913262547162 1503913262547162
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_2"></a>|@rodrigc set status to `closed`|
|-|-|

Fixed in [ticket:9127]
