### ISSUE TITLE
Twisted.web deferred handling bug

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#8820]
|<img alt="slyphon's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| slyphon reported|
|-|-|
|Trac ID|trac#417|
|Type|defect|
|Created|2003-12-02 09:02:47Z|

<details><summary>Searchable metadata</summary>

```
trac-id__417 417
type__defect defect
reporter__slyphon slyphon
priority__high high
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__invalid invalid
component__web web
keywords__ 
time__1070355767000000 1070355767000000
changetime__1150076795000000 1150076795000000
version__ 
owner__slyphon slyphon
cc__glyph cc__itamarst cc__dp cc__slyphon
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="slyphon's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|slyphon commented|
|-|-|

```
#!html
<pre>
Caused this bug whilst torture-testing quotient.

to reproduce:

start a quotient server running -nof 
run /Quotient/sandbox/slyphon/SpanishInquisition/torture_userCreation.py
watch quotient's log in amazement as it spits out the following:

2003/12/01 21:50 EST [HTTPChannel,1843,127.0.0.1] Traceback (most recent call last):
          File
"/home/jonathan/Projects/Quotient/quotient/test/twisted/protocols/http.py", line
950, in lineReceived                                                           
                                                        
          File
"/home/jonathan/Projects/Quotient/quotient/test/twisted/protocols/http.py", line
991, in allContentReceived
                                                                               
                                    
          File
"/home/jonathan/Projects/Quotient/quotient/test/twisted/protocols/http.py", line
549, in requestReceived
                                                                               
                                    
          File "/home/jonathan/Projects/Quotient/quotient/web/root.py", line 51,
in process
            return server.Request.process(self)
        --- &lt;exception caught here> ---
          File "./twisted/web/server.py", line 158, in process
                                                                               
                                    
          File "/home/jonathan/Projects/Quotient/quotient/web/root.py", line 74,
in getResourceFor
            res = gener.getResourceForRequest(request)
          File "/home/jonathan/Projects/Quotient/quotient/web/root.py", line
117, in getResourceForRequest
            return res.original.store.transact(configurable.postForm, ctx,
bindingName, request.args)
        exceptions.AttributeError: DeferredResource instance has no attribute
'original'

i'm not quite sure what it means, but dp said that it was related to
twisted.web's deferred handling
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="radix's avatar" src="https://avatars.githubusercontent.com/u/227068?s=50" width="50" height="50">](https://github.com/radix)|@radix commented|
|-|-|

```
#!html
<pre>
That traceback is almost entirely Quotient code. This probably belongs on the
Divmod tracker (unless you can come up with an actual reason to think this is
Twisted Web's fault)
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)|@itamarst commented|
|-|-|

```
#!html
<pre>
IIRC, DeferredResource assumes it's a one shot - that it only gets rendered
once, and that may be the issue. It's easy to fix, though.
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="slyphon's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|slyphon commented|
|-|-|

```
#!html
<pre>
I was talking with dp about it and he said that it was 50/50 quotient/twisted.
He said he's gonna have a look at it.
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun set status to `closed`|
|-|-|

No reproducable example.  No one has looked at it for two years.  Goodbye.
