### ISSUE TITLE
PTY tests on macOS are flaky

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#8840]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)| @hawkowl reported|
|-|-|
|Trac ID|trac#8840|
|Type|defect|
|Created|2016-09-25 11:56:27Z|

```
<glyph> if you do write() then close() real fast on one end of a pty, and the other end does read(), if close() happens first, sometimes the read() gives back the empty string
```

Affected tests:

twisted.internet.test.test_process.PTYProcessTestsBuilder
twisted.test.test_process.PosixProcessPTYTests.test_executionError

<details><summary>Searchable metadata</summary>

```
trac-id__8840 8840
type__defect defect
reporter__hawkowl hawkowl
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__None None
time__1474804587955678 1474804587955678
changetime__1475218799477390 1475218799477390
version__None None
owner__None None

```
</details>

**Comment by glyph** [comment]
We've had these tests disabled in CI for a while now, but I just did `trial -u twisted.internet.test.test_process` and got up to Test Pass ~~50~~ ~~62~~ ~~154~~ ~~237~~ ~~331~~ 410 with no issues, and it's continuing to run.  I've opened a PR to re-enable these tests on macOS.

**Comment by glyph** [comment]
(I think the relevant Darwin bug was fixed many years ago at this point)

**Comment by glyph** [comment]
(At 1 hour and 585 test passes, I'm calling it, and I'm going to stop running the tests.)

**Comment by adiroiban** [comment]
Reverted in https://github.com/twisted/twisted/pull/12173

**Comment by adiroiban** [comment]
example test failure ... not adding link to the build as the build log will expire in 30 days

```
[FAIL]
Traceback (most recent call last):
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.12/site-packages/twisted/internet/test/test_process.py", line 523, in test_errorDuringExec
    self.assertIn("\N{SNOWMAN}".encode(), output.getvalue())
  File "/Users/runner/work/twisted/twisted/.tox/macos-withcov-alldeps/lib/python3.12/site-packages/twisted/trial/_synctest.py", line 509, in assertIn
    raise self.failureException(msg or f"{containee!r} not in {container!r}")
twisted.trial.unittest.FailTest: b'\xe2\x98\x83' not in b''

twisted.internet.test.test_process.PTYProcessTestsBuilder_AsyncioSelectorReactorTests.test_errorDuringExec
```
