### ISSUE TITLE
twisted.conch.insults.helper.TerminalBuffer defines __bytes__ on Python 2

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#8843]
|[<img alt="mithrandi's avatar" src="https://avatars.githubusercontent.com/u/856430?s=50" width="50" height="50">](https://github.com/mithrandi)| @mithrandi reported|
|-|-|
|Trac ID|trac#8843|
|Type|defect|
|Created|2016-09-29 08:21:38Z|

This needs to be `__str__` on Python 2, `__bytes__` is a Python 3-only thing. This breaks the Mantissa test suite: https://travis-ci.org/twisted/mantissa/jobs/163355656

<details><summary>Searchable metadata</summary>

```
trac-id__8843 8843
type__defect defect
reporter__mithrandi mithrandi
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__wontfix wontfix
component__conch conch
keywords__None None
time__1475137298171111 1475137298171111
changetime__1603975843140155 1603975843140155
version__None None
owner__None None
cc__z3p
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_3"></a>|@glyph commented|
|-|-|

It also broke the Imaginary test suite:

```
Traceback (most recent call last):
  File "/Users/glyph/Projects/Imaginary/imaginary/test/test_text.py", line 365, in testUTF8Input
    character.encode('utf-8'))
  File "/Users/glyph/.virtualenvs/Imaginary/lib/python2.7/site-packages/twisted/trial/_synctest.py", line 425, in assertEqual
    super(_Assertions, self).assertEqual(first, second, msg)
  File "/Homebrew/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Homebrew/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 506, in _baseAssertEqual
    raise self.failureException(msg)
twisted.trial.unittest.FailTest: '<imaginary.test.test_text.UTF8TerminalBuffer instance at 0x106dd3cf8>' != '\xe3\x81\x82'

imaginary.test.test_text.TextServerTestCase.testUTF8Input
```

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_4"></a>|@exarkun commented|
|-|-|

This is sad but I guess Twisted no longer supports Python 2 at all so it probably won't be fixed?

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_5"></a>|@glyph set status to `closed`|
|-|-|

If someone wanted to do a point release on our last 2.x release I wouldn't object but unless someone is really actively interested I think we've called it for 2.x bugs at this point.
