### ISSUE TITLE
flattenEvent (and thereby jsonFileLogObserver) do not handle that log_format can be None

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#8860]
|[<img alt="Julian's avatar" src="https://avatars.githubusercontent.com/u/329822?s=50" width="50" height="50">](https://github.com/Julian)| @Julian reported|
|-|-|
|Trac ID|trac#8860|
|Type|defect|
|Created|2016-10-13 17:38:46Z|

E.g.:

```
from twisted.logger import Logger, jsonFileLogObserver
import sys
Logger(observer=jsonFileLogObserver(sys.stdout)).critical()
```

yields:

```
>>> Logger(observer=jsonFileLogObserver(sys.stdout)).critical()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    Logger(observer=jsonFileLogObserver(sys.stdout)).critical()
  File "/usr/local/lib/python2.7/site-packages/twisted/logger/_logger.py", line 258, in critical
    self.emit(LogLevel.critical, format, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/twisted/logger/_logger.py", line 132, in emit
    self.observer(event)
  File "/usr/local/lib/python2.7/site-packages/twisted/logger/_file.py", line 50, in __call__
    text = self.formatEvent(event)
  File "/usr/local/lib/python2.7/site-packages/twisted/logger/_json.py", line 245, in <lambda>
    lambda event: u"{0}{1}\n".format(recordSeparator, eventAsJSON(event))
  File "/usr/local/lib/python2.7/site-packages/twisted/logger/_json.py", line 196, in eventAsJSON
    flattenEvent(event)
  File "/usr/local/lib/python2.7/site-packages/twisted/logger/_flatten.py", line 87, in flattenEvent
    aFormatter.parse(event["log_format"])
  File "/usr/local/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/string.py", line 635, in parse
    return format_string._formatter_parser()
AttributeError: 'NoneType' object has no attribute '_formatter_parser'
```

(This is being triggered in my case by some code which I assume is passing a failure or something to logger.critical and not a format, but I haven't quite tracked down in my code what's doing it.)

<details><summary>Searchable metadata</summary>

```
trac-id__8860 8860
type__defect defect
reporter__Julian Julian
priority__normal normal
milestone__New_Logging_System New Logging System
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__logger logger
keywords__None None
time__1476380326464216 1476380326464216
changetime__1498684193316035 1498684193316035
version__None None
owner__wsanchez wsanchez
cc__colin.dunklau@...
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="cdunklau's avatar" src="https://avatars.githubusercontent.com/u/882547?s=50" width="50" height="50">](https://github.com/cdunklau)<a name="note_2"></a>|@cdunklau commented|
|-|-|

This is fixed with https://github.com/twisted/twisted/pull/655

**Comment by twisted-trac** [comment]
|[<img alt="cdunklau's avatar" src="https://avatars.githubusercontent.com/u/882547?s=50" width="50" height="50">](https://github.com/cdunklau)<a name="note_3"></a>|@cdunklau commented|
|-|-|

Once this has been fixed, [#8086](https://github.com/twisted/twisted/issues/8086) can be closed as well.

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)<a name="note_4"></a>|@wsanchez commented|
|-|-|

reviewed, OK to merge.

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)|@wsanchez set owner to @wsanchez<br>@wsanchez set status to `assigned`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)<a name="note_6"></a>|@wsanchez commented|
|-|-|

merged

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)|@wsanchez set status to `closed`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_8"></a>|@exarkun commented|
|-|-|

Is this a duplicate of [#7927](https://github.com/twisted/twisted/issues/7927)?

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_9"></a>|@glyph commented|
|-|-|

Replying to [Jean-Paul Calderone](#note_8):
> Is this a duplicate of [#7927](https://github.com/twisted/twisted/issues/7927)?

No. That's a totally separate issue.

This one is about `formatEvent` not including the traceback.  That one is about `eventAsJSON` not correctly including the failure _message_.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_10"></a>|@glyph commented|
|-|-|

I think maybe I put that comment on the wrong ticket?

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_11"></a>|@glyph commented|
|-|-|

Yeah, it was supposed to be for [#9198](https://github.com/twisted/twisted/issues/9198).
