### ISSUE TITLE
trial blows up when you compare unicode

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#8864]
|[<img alt="Julian's avatar" src="https://avatars.githubusercontent.com/u/329822?s=50" width="50" height="50">](https://github.com/Julian)| @Julian reported|
|-|-|
|Trac ID|trac#8864|
|Type|defect|
|Created|2016-10-17 00:29:14Z|

Running:

```
from unittest import TestCase
class T(TestCase):
    def test_thing(self):
        self.assertEqual(u"ש", u"a")
```

yields

```
t
  T
    test_thing ...                                                       [FAIL]

===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/opt/pypy/lib-python/2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/home/julian/Desktop/t.py", line 6, in test_thing
    self.assertEqual(u"ש", u"a")
  File "/opt/pypy/lib-python/2.7/unittest/case.py", line 515, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/opt/pypy/lib-python/2.7/unittest/case.py", line 926, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/opt/pypy/lib-python/2.7/unittest/case.py", line 412, in fail
    raise self.failureException(msg)
exceptions.AssertionError: <AssertionError instance at 0x7f68b57334c0 with str error:
 Traceback (most recent call last):
  File "/home/julian/.local/lib/pypy2.7/site-packages/twisted/python/reflect.py", line 440, in safe_str
    return str(o)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 22-23: ordinal not in range(128)
>

t.T.test_thing
-------------------------------------------------------------------------------
Ran 1 tests in 0.125s
```

<details><summary>Searchable metadata</summary>

```
trac-id__8864 8864
type__defect defect
reporter__Julian Julian
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__reopened reopened
resolution__None None
component__trial trial
keywords__None None
time__1476664154540841 1476664154540841
changetime__1606242654251418 1606242654251418
version__None None
owner__markrwilliams markrwilliams
cc__jml
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_2"></a>|@markrwilliams commented|
|-|-|

`safe_str` should always return a `str` (`bytes`) on Python 2.  The solution is encode unicode strings using `ascii_replace`, the same way [the traceback module does](https://github.com/python/cpython/blob/2.7/Lib/traceback.py#L212-L222).

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_3"></a>|@markrwilliams commented|
|-|-|

https://github.com/twisted/twisted/pull/566

**Comment by twisted-trac** [comment]
|[<img alt="Julian's avatar" src="https://avatars.githubusercontent.com/u/329822?s=50" width="50" height="50">](https://github.com/Julian)<a name="note_4"></a>|@Julian set owner to @markrwilliams|
|-|-|

Left 2 optional nitpicky comments/questions but lgtm for merge with or without them.

It might be nice to have an integration test here too since there's nothing actually tying us back to trial itself? But given how annoying that might be I think you're still OK to go without that from me.

(Especially because I really appreciate you hitting this so quickly.)

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_5"></a>|@markrwilliams commented|
|-|-|

Replying to [Julian](#note_4):
> Left 2 optional nitpicky comments/questions but lgtm for merge with or without them.

Fixed one -- good call on the docstring!  I'm putting it back in review for that reason.

> It might be nice to have an integration test here too since there's nothing actually tying us back to trial itself? But given how annoying that might be I think you're still OK to go without that from me.

I did consider this but decided against it.  The actual problem lies in `safe_str` and that gets used all over the place.  If I write integration tests for trial, I should probably also write integration tests for those other callers, too.  But doing so would create a perhaps problematic dependency on `safe_str`'s behavior.  Right now, Twisted's testing hygiene is good enough that only one other test depends on `safe_str`'s implementation.  Also, closing this ticket actually fixes a latent issue with that function, which is why I didn't even mention trial in the topfile.  Maybe I should, though?


> (Especially because I really appreciate you hitting this so quickly.)

Thanks for the quick review!  I think we can get this in before hawkie cuts the next release candidate.

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_6"></a>|@markrwilliams commented|
|-|-|

The PR, as it stands, encodes the exception's message as `ascii` with `backslashreplace`, but leaves the source in each traceback frame encoded according to the [PEP 263](https://www.python.org/dev/peps/pep-0263/) directive in its originating file.

That means the test case looks like this:

```
[FAIL]
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/tmp/test_x.py", line 5, in test_thing
    self.assertEqual(u"ש", u"a")
  File "/usr/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python2.7/unittest/case.py", line 924, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib/python2.7/unittest/case.py", line 410, in fail
    raise self.failureException(msg)
exceptions.AssertionError: u'\u05e9' != u'a'
- \u05e9
+ a
```

Note that the second frame's source has the Hebrew shin, while the Assertion error has a unicode escape sequence.

This is crummy because it's inconsistent, and also because it means this patch doesn't guarantee that a Failure's traceback can be written to an arbitrary receiver.  Doing better would be a lot of work, though, because [t.p.failure.format_frame](https://github.com/twisted/twisted/blob/trunk/src/twisted/python/failure.py#L60) just calls through to linecache, which in Python 2 just stores byte strings for each line.  On top of this there's no easy way in Python 2 to parse the encoding directive for a file, so we couldn't even pull that out from linecache and use it to decode the offending line.  I might release a backport of [Python 3's tokenize.detect_encoding](https://docs.python.org/3.3/library/tokenize.html#tokenize.detect_encoding) if there's sufficient interest in this.

Given all that I'd like this to land.  Thoughts?

**Comment by twisted-trac** [comment]
|[<img alt="Julian's avatar" src="https://avatars.githubusercontent.com/u/329822?s=50" width="50" height="50">](https://github.com/Julian)<a name="note_7"></a>|@Julian commented|
|-|-|

Yeah unfortunately that sounds reasonable to me for the current layout of the world. Green light from mois.

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_8"></a>|@markrwilliams set status to `closed`|
|-|-|

In changeset aa3a7a739cf112192fde38e1dd0cf9e84cd916a6
```
#!CommitTicketReference repository="" revision="aa3a7a739cf112192fde38e1dd0cf9e84cd916a6"
Merge 8864-safe_str-unicode: safe_str encodes unicode

Author: markrwilliams
Reviewer: Julian
Fixes: #8864

twisted.python.reflect.safe_str encodes unicode as ascii with backslashreplace error handling on Python 2.
```

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_9"></a>|@markrwilliams commented|
|-|-|

Reopening -- the intent behind forcing ```safe_str``` to encode ```unicode``` objects to ASCII with ```backslashescape``` was to make a public API less likely to raise an Exception.

Unfortunately this breaks tests that assume fidelity in bytes output.  The correct solution to this ticket is to deprecate ```safe_str``` and handle this ticket's bug closer to trial

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_10"></a>|@glyph commented|
|-|-|

In changeset 8995a48b50e4dff0a5bf4d36e15ea179c2cdefbd
```
#!CommitTicketReference repository="" revision="8995a48b50e4dff0a5bf4d36e15ea179c2cdefbd"
Merge pull request #726 from twisted/revert-566-8864-safe_str-unicode

Revert "8864 safe str unicode"

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/tmp/test_x.py", line 5, in test_thing
    self.assertEqual(u"ש", u"a")
  File "/usr/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python2.7/unittest/case.py", line 924, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib/python2.7/unittest/case.py", line 410, in fail
    raise self.failureException(msg)
exceptions.AssertionError: u'\u05e9' != u'a'
- \u05e9
+ a
```

Reopens: ticket:8864
```

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_11"></a>|@glyph set status to `reopened`|
|-|-|

Hrm. "reopens" doesn't work any more.

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_12"></a>|@adiroiban commented|
|-|-|

I don't think that this is still a valid release broker. Moving it to a normal defect.
