### ISSUE TITLE
twisted-16.4.1 test unicode failures in python-2.7.12

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#8872]
|[<img alt="dol-sen's avatar" src="https://avatars.githubusercontent.com/u/950866?s=50" width="50" height="50">](https://github.com/dol-sen)| @dol-sen reported|
|-|-|
|Trac ID|trac#8872|
|Type|defect|
|Created|2016-10-24 19:43:46Z|

The following 2 tests fail for python-2.7.12, but pass for python-3.4 and python-3.5.  The error appears to be due to the wrong form of the correct data.  I have had to disable these 2 tests for the time being in order to add this release to our package tree.

system info:
``` 
brian@professor-x $ python2.7 --version
Python 2.7.12
brian@professor-x $ emerge -vp =dev-lang/python-2.7.12

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild   R    ] dev-lang/python-2.7.12:2.7::gentoo  USE="gdbm ipv6 ncurses readline sqlite ssl threads tk (wide-unicode) xml (-berkdb) -build -doc -examples -hardened -libressl -wininst" 0 KiB 
```

Failures:
```
[FAIL]
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/twisted-16.4.1/work/Twisted-16.4.1-python2_7/lib/twisted/test/test_twistd.py", line 1782, in test_unicodeError
    reported=b'1 RuntimeError: \\u2022')
  File "/var/tmp/portage/dev-python/twisted-16.4.1/work/Twisted-16.4.1-python2_7/lib/twisted/test/test_twistd.py", line 1760, in assertErrorWritten
    ('unlink', 'twistd.pid')])
  File "/var/tmp/portage/dev-python/twisted-16.4.1/work/Twisted-16.4.1-python2_7/lib/twisted/trial/_synctest.py", line 425, in assertEqual
    super(_Assertions, self).assertEqual(first, second, msg)
  File "/usr/lib64/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib64/python2.7/unittest/case.py", line 742, in assertListEqual
    self.assertSequenceEqual(list1, list2, msg, seq_type=list)
  File "/usr/lib64/python2.7/unittest/case.py", line 724, in assertSequenceEqual
    self.fail(msg)
twisted.trial.unittest.FailTest: Lists differ: [('chdir', '.'), ('umask', 63)... != [('chdir', '.'), ('umask', 63)...

First differing element 5:
('write', -2, '1 RuntimeError: \xe2\x80\xa2')
('write', -2, '1 RuntimeError: \\u2022')

  [('chdir', '.'),
   ('umask', 63),
   ('fork', True),
   'setsid',
   ('fork', True),
-  ('write', -2, '1 RuntimeError: \xe2\x80\xa2'),
?                                  ^^ --- ^^^

+  ('write', -2, '1 RuntimeError: \\u2022'),
?                                  ^^  ^

   ('unlink', 'twistd.pid')]

twisted.test.test_twistd.DaemonizeTests.test_unicodeError
===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/twisted-16.4.1/work/Twisted-16.4.1-python2_7/lib/twisted/test/test_twistd.py", line 1884, in test_unicodeErrorMessageTruncated
    reported=b'1 RuntimeError: ' + b'\\u2022' * 14,
  File "/var/tmp/portage/dev-python/twisted-16.4.1/work/Twisted-16.4.1-python2_7/lib/twisted/test/test_twistd.py", line 1760, in assertErrorWritten
    ('unlink', 'twistd.pid')])
  File "/var/tmp/portage/dev-python/twisted-16.4.1/work/Twisted-16.4.1-python2_7/lib/twisted/trial/_synctest.py", line 425, in assertEqual
    super(_Assertions, self).assertEqual(first, second, msg)
  File "/usr/lib64/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib64/python2.7/unittest/case.py", line 742, in assertListEqual
    self.assertSequenceEqual(list1, list2, msg, seq_type=list)
  File "/usr/lib64/python2.7/unittest/case.py", line 724, in assertSequenceEqual
    self.fail(msg)
twisted.trial.unittest.FailTest: Lists differ: [('chdir', '.'), ('umask', 63)... != [('chdir', '.'), ('umask', 63)...

First differing element 5:
('write', -2, '1 RuntimeError: \xe2\x80\xa2\xe2\x80\xa2\xe2\x80\xa2\xe2\x80\xa2\xe2\x80\xa2\xe2\x80\xa2\xe2\x80\xa2\xe2\x80\xa2\xe2\x80\xa2\xe2\x80\xa2\xe2\x80\xa2\xe2\x80\xa2\xe2\x80\xa2\xe2\x80\xa2\xe2\x80\xa2\xe2\x80\xa2\xe2\x80\xa2\xe2\x80\xa2\xe2\x80\xa2\xe2\x80\xa2\xe2\x80\xa2\xe2\x80\xa2\xe2\x80\xa2\xe2\x80\xa2\xe2\x80\xa2\xe2\x80\xa2\xe2\x80\xa2\xe2\x80\xa2')
('write', -2, '1 RuntimeError: \\u2022\\u2022\\u2022\\u2022\\u2022\\u2022\\u2022\\u2022\\u2022\\u2022\\u2022\\u2022\\u2022\\u2022')

  [('chdir', '.'),
   ('umask', 63),
   ('fork', True),
   'setsid',
   ('fork', True),
   ('write',
    -2,
-   '1 RuntimeError: \xe2\x80\xa2\xe2\x80\xa2\xe2\x80\xa2\xe2\x80\xa2\xe2\x80\xa2\xe2\x80\xa2\xe2\x80\xa2\xe2\x80\xa2\xe2\x80\xa2\xe2\x80\xa2\xe2\x80\xa2\xe2\x80\xa2\xe2\x80\xa2\xe2\x80\xa2\xe2\x80\xa2\xe2\x80\xa2\xe2\x80\xa2\xe2\x80\xa2\xe2\x80\xa2\xe2\x80\xa2\xe2\x80\xa2\xe2\x80\xa2\xe2\x80\xa2\xe2\x80\xa2\xe2\x80\xa2\xe2\x80\xa2\xe2\x80\xa2\xe2\x80\xa2'),
+   '1 RuntimeError: \\u2022\\u2022\\u2022\\u2022\\u2022\\u2022\\u2022\\u2022\\u2022\\u2022\\u2022\\u2022\\u2022\\u2022'),
   ('unlink', 'twistd.pid')]

twisted.test.test_twistd.DaemonizeTests.test_unicodeErrorMessageTruncated

```

<details><summary>Searchable metadata</summary>

```
trac-id__8872 8872
type__defect defect
reporter__dol_sen dol-sen
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__invalid invalid
component__core core
keywords__None None
time__1477338226638211 1477338226638211
changetime__1490887310003467 1490887310003467
version__None None
owner__markrwilliams markrwilliams
cc__jamesbroadhead@...
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_1"></a>|@markrwilliams commented|
|-|-|

Hi!  Thanks for packaging Twisted for Gentoo, and thanks for reporting this issue.

I can't reproduce this with a fresh install of Twisted 16.4.1 under the same version of Python (2.7.12) on Debian unstable.  Is it possible you have stale *.pyc files hanging around?  What was the previous version of Twisted packaged for Gentoo?

Also, can I reproduce this issue on Gentoo with the commands you provided in the description of the ticket?  If so I'll spin up a VM and investigate.

Thanks again!

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_3"></a>|@markrwilliams set status to `closed`|
|-|-|

Hi!  This ticket hasn't received any updates, so I'm going to assume it's no longer relevant and close it as invalid.

Please reopen it with answers to the questions in [#8872](https://github.com/twisted/twisted/issues/8872)#comment:1 if it is still relevant.

Thanks!
