### ISSUE TITLE
Tracebacks with Chrome priority settings using Twisted h2.

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#8874]
|[<img alt="Lukasa's avatar" src="https://avatars.githubusercontent.com/u/1382556?s=50" width="50" height="50">](https://github.com/Lukasa)| @Lukasa reported|
|-|-|
|Trac ID|trac#8874|
|Type|defect|
|Created|2016-10-26 08:28:24Z|

Spotted on the server running python-hyper.org:

```
2016-10-26T08:27:15+0000 [_GenericHTTPChannelProtocol (TLSMemoryBIOProtocol),2538,193.204.59.123] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/local/site-packages/twisted/python/log.py", line 101, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/usr/local/site-packages/twisted/python/log.py", line 84, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/usr/local/site-packages/twisted/python/context.py", line 118, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/usr/local/site-packages/twisted/python/context.py", line 81, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/usr/local/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/usr/local/site-packages/twisted/internet/tcp.py", line 208, in doRead
	    return self._dataReceived(data)
	  File "/usr/local/site-packages/twisted/internet/tcp.py", line 214, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/usr/local/site-packages/twisted/protocols/tls.py", line 430, in dataReceived
	    self._flushReceiveBIO()
	  File "/usr/local/site-packages/twisted/protocols/tls.py", line 395, in _flushReceiveBIO
	    ProtocolWrapper.dataReceived(self, bytes)
	  File "/usr/local/site-packages/twisted/protocols/policies.py", line 120, in dataReceived
	    self.wrappedProtocol.dataReceived(data)
	  File "/usr/local/site-packages/twisted/web/http.py", line 2332, in dataReceived
	    return self._channel.dataReceived(data)
	  File "/usr/local/site-packages/twisted/web/_http2.py", line 176, in dataReceived
	    self._handlePriorityUpdate(event)
	  File "/usr/local/site-packages/twisted/web/_http2.py", line 473, in _handlePriorityUpdate
	    exclusive=event.exclusive,
	  File "/usr/local/site-packages/priority/priority.py", line 337, in reprioritize
	    new_parent = self._streams[depends_on]
	exceptions.KeyError: 3

```

<details><summary>Searchable metadata</summary>

```
trac-id__8874 8874
type__defect defect
reporter__Lukasa Lukasa
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__None None
time__1477470504370965 1477470504370965
changetime__1477471448002386 1477471448002386
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="Lukasa's avatar" src="https://avatars.githubusercontent.com/u/1382556?s=50" width="50" height="50">](https://github.com/Lukasa)<a name="note_2"></a>|@Lukasa commented|
|-|-|

I think this is a bug in the priority library, which is being tracked as [Priority Issue 35](https://github.com/python-hyper/priority/issues/35). I'm going to keep this ticket open until the upstream ticket is resolved (hopefully sometime today) and a release is pushed (also hopefully sometime today).
