### ISSUE TITLE
IRCClient fails to parse non-UTF8 messages under Python 3

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#8903]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)| @markrwilliams reported|
|-|-|
|Trac ID|trac#8903|
|Type|defect|
|Created|2016-11-17 06:49:42Z|

Words' IRC client fails internally under Python 3 ([#6320](https://github.com/twisted/twisted/issues/6320)) because it
attempts to decode all incoming data as utf-8.  While the protocol
appears to be ASCII, RFC1459 does not specify an encoding for the
contents of PRIVMSGs or channel topics.  I ran a naive a survey of the
10 most popular networks, as found here:

http://irc.netsplit.de/networks/top100.php

And found that ~10% of PRIVMSGs and channel topics were in latin 1
(according to chardet, at least).  The code for my survey is here:

https://github.com/markrwilliams/encodingcollector/

(Note that is incredibly impolite and will get you banned from most
networks.)

Here's what the problem looks like in practice.  The following script
prints all the channels on a popular Italian IRC server:

```python
from twisted.internet import defer, endpoints, task
from twisted.words.protocols import irc


class ListBot(irc.IRCClient):
    nickname = "nothing"

    def __init__(self, done):
        self._done = done

    def signedOn(self):
        self.sendLine("LIST")

    def irc_RPL_LIST(self, prefix, params):
        print(prefix, params)

    def irc_RPL_LISTEND(self, prefix, params):
        self.transport.loseConnection()
        self._done.callback(None)


@task.react
def main(reactor):
    transport = endpoints.clientFromString(reactor, 'tcp:irc.chlame.net:6667')
    end = defer.Deferred()
    start = endpoints.connectProtocol(transport, ListBot(end))
    start.addCallback(lambda _: end)
    return start
```

Under Python 2, it will print successfully and then terminate, while under
Python 3, it will encounter the following exception and hang:

```
Unhandled Error
Traceback (most recent call last):
  File "/path/to/twisted/src/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/path/to/twisted/src/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/path/to/twisted/src/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/path/to/twisted/src/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/path/to/twisted/src/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()
  File "/path/to/twisted/src/twisted/internet/tcp.py", line 208, in doRead
    return self._dataReceived(data)
  File "/path/to/twisted/src/twisted/internet/tcp.py", line 214, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/path/to/twisted/src/twisted/internet/endpoints.py", line 116, in dataReceived
    return self._wrappedProtocol.dataReceived(data)
  File "/path/to/twisted/src/twisted/words/protocols/irc.py", line 2631, in dataReceived
    basic.LineReceiver.dataReceived(self, data)
  File "/path/to/twisted/src/twisted/protocols/basic.py", line 571, in dataReceived
    why = self.lineReceived(line)
  File "/path/to/twisted/src/twisted/words/protocols/irc.py", line 2637, in lineReceived
    line = line.decode("utf-8")
builtins.UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position 51: invalid continuation byte
```

A user cannot register an errback to handle this because the exception
occurs as a result of a read event.  They also can't write code that
doesn't encounter this exception without monkeypatching Twisted.

I believe this is a serious regression and the IRC port deserves more
attention.

<details><summary>Searchable metadata</summary>

```
trac-id__8903 8903
type__defect defect
reporter__markrwilliams markrwilliams
priority__normal normal
milestone__Twisted_16_6 Twisted 16.6
branch__ 
branch_author__ 
status__closed closed
resolution__duplicate duplicate
component__core core
keywords__None None
time__1479365382967923 1479365382967923
changetime__1479366567390922 1479366567390922
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_2"></a>|@markrwilliams set status to `closed`|
|-|-|

[#6320](https://github.com/twisted/twisted/issues/6320) is reopened.  Closing this.
