### ISSUE TITLE
KeyError exception in epollreactor.py

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#8907]
|[<img alt="kgkdev13's avatar" src="https://avatars.githubusercontent.com/u/23116912?s=50" width="50" height="50">](https://github.com/kgkdev13)| @kgkdev13 reported|
|-|-|
|Trac ID|trac#8907|
|Type|enhancement|
|Created|2016-11-18 06:32:52Z|

Sometimes happens KeyError and the application stops accepting new connections.

I tried to fix this in the pull request https://github.com/twisted/twisted/pull/594
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/var/srv/websocket/modules/managers/queuemanager.py", line 164, in queueProcessor
    client.dropConnection()
  File "/usr/local/lib/python2.7/dist-packages/autobahn-0.16.0-py2.7.egg/autobahn/websocket/protocol.py", line 861, in dropConnection
    self._closeConnection(abort)
  File "/usr/local/lib/python2.7/dist-packages/autobahn-0.16.0-py2.7.egg/autobahn/twisted/websocket.py", line 139, in _closeConnection
    self.transport.loseConnection()
  File "/usr/local/lib/python2.7/dist-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/internet/_newtls.py", line 217, in loseConnection
    FileDescriptor.loseConnection(self)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/internet/abstract.py", line 407, in loseConnection
    self.stopReading()
  File "/usr/local/lib/python2.7/dist-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/internet/abstract.py", line 421, in stopReading
    self.reactor.removeReader(self)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/internet/epollreactor.py", line 333, in removeReader
    EPOLLIN, EPOLLOUT)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/internet/epollreactor.py", line 319, in _remove
    del selectables[fd]
KeyError: 306
```

<details><summary>Searchable metadata</summary>

```
trac-id__8907 8907
type__enhancement enhancement
reporter__kgkdev13 kgkdev13
priority__normal normal
milestone__None None
branch__None None
branch_author__ 
status__closed closed
resolution__invalid invalid
component__core core
keywords__None None
time__1479450772015760 1479450772015760
changetime__1595120647963885 1595120647963885
version__None None
owner__kgkdev13 kgkdev13

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_1"></a>|@glyph commented|
|-|-|

The 'branch' field indicates what branch a Twisted committer has put their changes into, so it should be empty for this.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_3"></a>|@glyph commented|
|-|-|

Since this ticket already has a PR, I believe your intention was to submit it for review; I'll attach the "review" keyword (you can do this yourself in the future).

**Comment by twisted-trac** [comment]
|[<img alt="kgkdev13's avatar" src="https://avatars.githubusercontent.com/u/23116912?s=50" width="50" height="50">](https://github.com/kgkdev13)<a name="note_4"></a>|@kgkdev13 commented|
|-|-|

Thanks for your advices! I'm new to this

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun set owner to @kgkdev13|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_7"></a>|@twm set status to `closed`|
|-|-|

Closing per discussion on the PR.
