### ISSUE TITLE
Conch no longer supports OpenSSH keys with Windows line endings

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#8928]
|[<img alt="clokep's avatar" src="https://avatars.githubusercontent.com/u/517124?s=50" width="50" height="50">](https://github.com/clokep)| @clokep reported|
|-|-|
|Trac ID|trac#8928|
|Type|defect|
|Created|2016-11-30 21:57:29Z|

I have a private OpenSSH key that has Window line endings. This used to load fine using twisted.conch.ssh.keys.Key.fromString on Twisted 16.5.0 but breaks in 16.6.0 with "unknown key type RSA".

A partial stack trace is:

```
Traceback (most recent call last):
  File "/usr/local/venv/local/lib/python2.7/site-packages/twisted/conch/ssh/keys.py", line 199, in fromString
    return method(data, passphrase)
  File "/usr/local/venv/local/lib/python2.7/site-packages/twisted/conch/ssh/keys.py", line 472, in _fromString_PRIVATE_OPENSSH
    raise BadKeyError("unknown key type %s" % (kind,))
twisted.conch.ssh.keys.BadKeyError: unknown key type RSA 
```

The regression was introduced in https://github.com/twisted/twisted/commit/f585c83fd6ddca9ea2d2683ad8b644347243d2e3 / https://github.com/twisted/twisted/pull/533/

<details><summary>Searchable metadata</summary>

```
trac-id__8928 8928
type__defect defect
reporter__clokep clokep
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__conch conch
keywords__None None
time__1480543049098138 1480543049098138
changetime__1487888824459487 1487888824459487
version__None None
owner__None None
cc__z3p
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="clokep's avatar" src="https://avatars.githubusercontent.com/u/517124?s=50" width="50" height="50">](https://github.com/clokep)<a name="note_2"></a>|@clokep commented|
|-|-|

I think I see how to fix this, so I'm going to attempt to put up a pull request today or tomorrow. I wasn't fully positive what to fill out for type/priority/etc, please feel free to fix any metadata here!

**Comment by twisted-trac** [comment]
|[<img alt="clokep's avatar" src="https://avatars.githubusercontent.com/u/517124?s=50" width="50" height="50">](https://github.com/clokep)<a name="note_3"></a>|@clokep commented|
|-|-|

Please review https://github.com/twisted/twisted/pull/612

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_4"></a>|@markrwilliams commented|
|-|-|

https://github.com/twisted/twisted/pull/612#pullrequestreview-10972953

**Comment by twisted-trac** [comment]
|<img alt="Patrick Cloke's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_5"></a>|Patrick Cloke commented|
|-|-|

In changeset e6cd341ed60946ed4105e6ff6744bd43f5878939
```
#!CommitTicketReference repository="" revision="e6cd341ed60946ed4105e6ff6744bd43f5878939"
Support OpenSSH keys with Windows line endings.

This was supported in Twisted <= 16.5.0, but broke in 16.6.0.

See ticket #8928.
```

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_6"></a>|@rodrigc commented|
|-|-|

Fixed in http://twistedmatrix.com/trac/changeset/040a1581a7feb44e294ea197420eefd25554bbe7

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_7"></a>|@glyph set status to `closed`|
|-|-|

Looks like this didn't auto-close; fixing.
