### ISSUE TITLE
host key error:  Invalid EC Key Y point.

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#8931]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)| @rodrigc reported|
|-|-|
|Trac ID|trac#8931|
|Type|defect|
|Created|2016-12-02 00:58:38Z|

In my ~/.ssh/known_hosts file, I had a host key created by OpenSSH_7.2p2, LibreSSL 2.4.1, on OS X.

If I try to use conch to log into that host, I get this:

```
Traceback (most recent call last):                                                                  
  File "/Users/crodrigues/twisted8/src/twisted/conch/client/knownhosts.py", line 70, in            
_extractCommon                                                                                                      
    key = Key.fromString(a2b_base64(keyString))                                                                     
  File "/Users/crodrigues/twisted8/src/twisted/conch/ssh/keys.py", line 197, in fromString                          
    return method(data)                                                                                             
  File "/Users/crodrigues/twisted8/src/twisted/conch/ssh/keys.py", line 251, in _fromString_BLOB                    
    return cls._fromECComponents(x=x, y=y, curve=keyType)                                                           
  File "/Users/crodrigues/twisted8/src/twisted/conch/ssh/keys.py", line 725, in _fromECComponents                   
    keyObject = publicNumbers.public_key(default_backend())
  File "/Users/crodrigues/venv-3.6/lib/python3.6/site-packages/cryptography/hazmat/primitives/asymme                
tric/ec.py", line 285, in public_key                                                                                
    return backend.load_elliptic_curve_public_numbers(self)                                                         
  File "/Users/crodrigues/venv-3.6/lib/python3.6/site-packages/cryptography/hazmat/backends/multibac                
kend.py", line 273, in load_elliptic_curve_public_numbers                                                           
    return b.load_elliptic_curve_public_numbers(numbers)                                                            
  File "/Users/crodrigues/venv-3.6/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/                
backend.py", line 1384, in load_elliptic_curve_public_numbers                                                       
    ec_cdata, numbers.x, numbers.y)                                                                                 
  File "/Users/crodrigues/venv-3.6/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/                
backend.py", line 1546, in _ec_key_set_public_key_affine_coordinates                                                
    raise ValueError("Invalid EC Key Y point.")                                                                     
ValueError: Invalid EC Key Y point.      
```

and then I get a bad host key error.

This key works fine with OpenSSH.

If I delete the known_hosts file, and log in with conch, my known_hosts file gets populated with
a different key.

Attachments:

* [known_hosts_openssh_broken.txt](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/fcb/fcbe5b62ba083df3ccf2c3a127ec1ce3ef8fe635/430b714cc1ca15ac6208597b52f1c2a9bf439e4e.txt) (173 bytes) - added by rodrigc on 2016-12-02 00:59:50Z - 
* [known_hosts_openssh_broken.2.txt](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/fcb/fcbe5b62ba083df3ccf2c3a127ec1ce3ef8fe635/4fcf2241fbb8704da4ace25588fe1d31295a8f35.txt) (173 bytes) - added by rodrigc on 2016-12-02 01:00:14Z - 
* [known_hosts_conch_working.txt](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/fcb/fcbe5b62ba083df3ccf2c3a127ec1ce3ef8fe635/b86d9f1f194cf408207be99e288bc1404fd3ae1f.txt) (884 bytes) - added by rodrigc on 2016-12-02 01:00:30Z - 

<details><summary>Searchable metadata</summary>

```
trac-id__8931 8931
type__defect defect
reporter__rodrigc rodrigc
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__conch conch
keywords__None None
time__1480640318260996 1480640318260996
changetime__1481902862052313 1481902862052313
version__None None
owner__Craig_Rodrigues__rodrigc_____ Craig Rodrigues <rodrigc@...>
cc__z3p
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_2"></a>|@rodrigc commented|
|-|-|

https://github.com/twisted/twisted/pull/615

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_3"></a>|@rodrigc set owner to @rodrigc<br>@rodrigc set status to `closed`|
|-|-|

In changeset e116bbe34dc3a3855a674043bc5f30d7e6417c7f
```
#!CommitTicketReference repository="" revision="e116bbe34dc3a3855a674043bc5f30d7e6417c7f"
Merge pull request #630 from twisted/8931-rodrigc-ssh

Author: the0id , acabhishek942
Reviewer: rodrigc
Fixes: ticket:8325 , ticket:8784 , ticket:8811 ,   ticket:8894 , ticket:8931   

Add support for elliptic curve (EC) keys to conch
```
