### ISSUE TITLE
test_forwardCommand fails on Python 3

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#8944]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)| @rodrigc reported|
|-|-|
|Trac ID|trac#8944|
|Type|enhancement|
|Created|2016-12-13 03:07:17Z|

```
trial twisted.trial._dist.test.test_workertrial.MainTests.test_forwardCommand
```

```
twisted.trial._dist.test.test_workertrial
  MainTests
    test_forwardCommand ...                                              [FAIL]

===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/Users/crodrigues/twisted9/src/twisted/trial/_dist/test/test_workertrial.py", line 110, in test_forwardCommand
    "No module named 'doesntexist'", self.writeStream.getvalue())
  File "/Users/crodrigues/twisted9/src/twisted/trial/_synctest.py", line 485, in assertIn
    % (containee, container))
twisted.trial.unittest.FailTest: "No module named 'doesntexist'" not in ''

twisted.trial._dist.test.test_workertrial.MainTests.test_forwardCommand
-------------------------------------------------------------------------------
```

It looks like the text from the exception is not propagated to the stream.
This works in Python 2.

<details><summary>Searchable metadata</summary>

```
trac-id__8944 8944
type__enhancement enhancement
reporter__rodrigc rodrigc
priority__normal normal
milestone__Python_3_x Python-3.x
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__trial trial
keywords__None None
time__1481598437835803 1481598437835803
changetime__1504335947142046 1504335947142046
version__None None
owner__Craig_Rodrigues__rodrigc_____ Craig Rodrigues <rodrigc@...>
cc__jml
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_2"></a>|@rodrigc set status to `closed`|
|-|-|

Fixed as a side-effect of fixing ticket:8943

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)|@rodrigc set status to `reopened`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_4"></a>|@rodrigc commented|
|-|-|

https://github.com/twisted/twisted/pull/882

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_5"></a>|@rodrigc commented|
|-|-|

reviewed by moshez: https://github.com/twisted/twisted/pull/882#pullrequestreview-60267647

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_6"></a>|@rodrigc set owner to @rodrigc<br>@rodrigc set status to `closed`|
|-|-|

In changeset 104b6a39a8d15b0e0416a71da66cbb58fd4b0791
```
#!CommitTicketReference repository="" revision="104b6a39a8d15b0e0416a71da66cbb58fd4b0791"
Merge pull request #882 from twisted/8944-forwardcommand-py3

Author: rodrigc
Reviewer: moshez
Fixes: ticket:8944

Fix twisted.trial._dist.test.test_workertrial on Python 3
```
