### ISSUE TITLE
twisted.internet.test.test_newtls.ProducerTestsMixin tests are flaky

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#8967]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)| @hawkowl reported|
|-|-|
|Trac ID|trac#8967|
|Type|enhancement|
|Created|2016-12-24 08:17:54Z|

```

[ERROR]
Traceback (most recent call last):
  File "/buildslave/freebsd10-py2_7/Twisted/build/py27-alldeps-nocov-posix/lib/python2.7/site-packages/twisted/internet/test/test_newtls.py", line 124, in test_producerSSLFromStart
    SSLCreator())
  File "/buildslave/freebsd10-py2_7/Twisted/build/py27-alldeps-nocov-posix/lib/python2.7/site-packages/twisted/internet/test/connectionmixins.py", line 178, in runProtocolsWithReactor
    reactorBuilder.runReactor(reactor)
  File "/buildslave/freebsd10-py2_7/Twisted/build/py27-alldeps-nocov-posix/lib/python2.7/site-packages/twisted/internet/test/reactormixins.py", line 323, in runReactor
    "reactor still running after %s seconds" % (timeout,))
twisted.internet.test.reactormixins.TestTimeoutError: reactor still running after 120.0 seconds

twisted.internet.test.test_newtls.ProducerTestsMixin_SelectReactorTests.test_producerSSLFromStart
```

<details><summary>Searchable metadata</summary>

```
trac-id__8967 8967
type__enhancement enhancement
reporter__hawkowl hawkowl
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__None None
time__1482567474275401 1482567474275401
changetime__1484699132277713 1484699132277713
version__None None
owner__glyph glyph

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_1"></a>|@hawkowl commented|
|-|-|

I'm giving up on this. It seems that the client doesn't connect to the server. Things it isn't:

- A bug in ```connectionmixins```.
- ```listen``` or ```bind``` raising EAGAIN (probably).
- ```connect``` raising EAGAIN (probably).
- using ```connectionMade``` vs ```handshakeRecieved```.

????? good luck

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_2"></a>|@markrwilliams commented|
|-|-|

 Replying to [hawkowl](#note_1):
> Things it isn't:
> 
> [snip]
>
> - using ```connectionMade``` vs ```handshakeRecieved```.


I went ahead and tested this out after being aggravated by the bug and found that switching ```ProducerProtocol.connectionMade``` to ```handshakeCompleted``` _did_ fix the issue!  I did have to patch something to make that even possible:

[#8973](https://github.com/twisted/twisted/issues/8973)

I'm not ready to convert the tests to use this just yet, though.  I'm still worried there's an authentic race condition on BSDs.

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_3"></a>|@hawkowl commented|
|-|-|

I can still trigger it when I switched it to using ```handshakeCompleted```, though. It's just much less rare. (Also, the bug still exists, even if the tests stop failing :))

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_4"></a>|@markrwilliams commented|
|-|-|

Progress!  The test hangs on FreeBSD when the client aborts the connection and sends an RST before the server can accept it, causing accept(2) to fail with ```ECONNABORTED``` and thus prevent ```TLSMemoryBIOFactory``` from creating the protocol whose ```_done``` Deferred holds up the test.

See https://github.com/twisted/twisted/blob/trunk/src/twisted/internet/tcp.py#L1044-L1062

That's why this doesn't manifest with a non-TLS version of the test (e.g., replacing ```SSLCreator``` with ```TCPCreator```) and why this particular issue doesn't manifest with ```handshakeCompleted```.  [TLSMemoryBIOProtocol.loseConnection aborts the connection if the handshake isn't done.](https://github.com/twisted/twisted/blob/4ca2dbdfdb598ff8720e64132b4dd04e6f62f2e4/src/twisted/protocols/tls.py#L406-L422)

I think for **this** instance of the bug, the right thing to do is make ```ProducerProtocol``` an ```IHandshakeListener```.

More research is needed for macOS.

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_5"></a>|@markrwilliams commented|
|-|-|

The situation on macOS is weirder!

You can use the following script to send a reset to a server before it can call ```accept(2)```:

```python
import argparse
import socket
import sys
import struct


def no_time_wait(listener):
    listener.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)


def send_rst(connection):
    connection.setsockopt(socket.SOL_SOCKET, socket.SO_LINGER,
                          struct.pack("ii", 1, 0))


def server(_):
    listener = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    no_time_wait(listener)

    listener.bind(('localhost', 0))
    listener.listen(1)
    _, port = listener.getsockname()
    print("Listening on port %d."
          "  Press enter after the client has connected." % (port,))
    sys.stdin.readline()
    listener.accept()


def client(parsed):
    connection = socket.create_connection(('localhost', parsed.port))
    send_rst(connection)
    connection.close()


parser = argparse.ArgumentParser("Can accept(2) can fail with ECONNABORTED?")
subparsers = parser.add_subparsers()

server_parser = subparsers.add_parser("server")
server_parser.set_defaults(function=server)

client_parser = subparsers.add_parser("client")
client_parser.add_argument("port", type=int)
client_parser.set_defaults(function=client)

parsed = parser.parse_args()
parsed.function(parsed)
```

Run the server somewhere:
```
$ python econnaborted.py server
Listening on port NNNN.  Press enter after the client has connected.
```

Run the client somewhere else on the same machine:
```
$ python econnaborted.py client NNNN
```

Go back to the server, press enter, and see what ```accept``` did.

Here are my results:

|= Platform             =|= Result                                                          =|
|------------------------|-------------------------------------------------------------------|
| Recent Linux (4.8.0)   | ```accept(2)``` returns a connection without raising an exception ||
| FreeBSD 10.3-RELEASE   | 
|------------------------|-```accept(2)``` fails with ```ECONNABORTED```                     ||
| macOS Sierra           | 
|------------------------|-```accept(2)``` does not return (!)                               ||

The fact that macOS' ```accept(2)``` never returns explains why no log message appears.

I'm sure now that switching to ```handshakeCompleted``` will effectively eliminate this bug.
I'm not at _all_ sure why it hasn't appeared to totally eliminate it!

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_6"></a>|@markrwilliams commented|
|-|-|

Replying to [mark williams](#note_5):

> 
> You can use the following script to send a reset to a server before it can call ```accept(2)```:
> 

...except that it skips a step: it should first poll the socket for readability, **then** call ```accept(2)```.

Here's a correct version:


```python
import argparse
import select
import socket
import sys
import struct


def no_time_wait(listener):
    listener.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)


def send_rst(connection):
    connection.setsockopt(socket.SOL_SOCKET, socket.SO_LINGER,
                          struct.pack("ii", 1, 0))


def server(_):
    listener = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    no_time_wait(listener)

    listener.bind(('localhost', 0))
    listener.listen(1)
    _, port = listener.getsockname()
    print("Listening on port %d."
          "  Press enter after the client has connected." % (port,))
    sys.stdin.readline()
    readable, writable, exceptional = select.select([listener], 
                                                    [listener], 
                                                    [listener])
    print("readable: %r" % (readable,))
    print("writable: %r" % (writable,))
    print("exceptional: %r" % (writable,))
    if listener in readable:
        listener.accept()


def client(parsed):
    connection = socket.create_connection(('localhost', parsed.port))
    send_rst(connection)
    connection.close()


parser = argparse.ArgumentParser("Can accept(2) can fail with ECONNABORTED?")
subparsers = parser.add_subparsers()

server_parser = subparsers.add_parser("server")
server_parser.set_defaults(function=server)

client_parser = subparsers.add_parser("client")
client_parser.add_argument("port", type=int)
client_parser.set_defaults(function=client)

parsed = parser.parse_args()
parsed.function(parsed)
```

Run it the same way.  And here are the results:

|= Platform             =|= select             =|= accept                                          =|
|------------------------|----------------------|---------------------------------------------------|
| Recent Linux (4.8.0)   | Listener is readable | returns a connection without raising an exception |
| FreeBSD 10.3-RELEASE   | Listener is readable | fails with ```ECONNABORTED```                     ||
| macOS Sierra           | does not return (!)  | N/A                                               |
|------------------------|----------------------|---------------------------------------------------|

That ```select(2)``` under macOS doesn't see the listener as readable explains why `t.i.tcp.Port.doRead` never runs.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_7"></a>|@glyph commented|
|-|-|

What Sierra version are you testing on?  For me, I get:


```
Listening on port 64189.  Press enter after the client has connected.

readable: [<socket._socketobject object at 0x10b562130>]
writable: []
exceptional: []
```

from the server, and the client just exits immediately on the first invocation.

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_8"></a>|@markrwilliams commented|
|-|-|

Should have been El Capitan.  Time for a new table! 


|=Platform            =|= select             =|= accept                                          =|
|----------------------|----------------------|---------------------------------------------------|
| Recent Linux (4.8.0) | Listener is readable | returns a connection without raising an exception |
| FreeBSD 10.3-RELEASE | Listener is readable | fails with ECONNABORTED                           |
| OS X El Capitan      | does not return (!)  | N/A                                               |
| macOS Sierra*        | Listener is readable | returns a connection without raising an exception |


* Only sometimes?

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_9"></a>|@markrwilliams commented|
|-|-|

https://github.com/twisted/twisted/pull/665 

This should fix the FreeBSD builders at least...

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_11"></a>|@markrwilliams commented|
|-|-|

I patched two additional issues.

One was in ```twisted.internet.test.test_ssl```:  [ImmediatelyDisconnectingProtocol](https://github.com/twisted/twisted/pull/665/commits/f86445164fbf096433e7ece043c793177f718f3c) [failed on macOS](https://buildbot.twistedmatrix.com/builders/osx10.10-py2.7/builds/2362/steps/select/logs/stdio) for what seems to be the same reason for the FreeBSD failure in ```test_producerSSLFromStart```.

I also changed [CloseAfterHandshake](https://github.com/twisted/twisted/pull/665/commits/92ae42e193628b856b7a0df1dc93a04ac61a8b16) to be an ```IHandshakeListener``` even though no tests failed.  Consistency!


The PR appears to have stabilized the FreeBSD builders:

https://buildbot.twistedmatrix.com/builders/freebsd10-py2.7-coverage/builds/82

https://buildbot.twistedmatrix.com/builders/freebsd10-py3.5-coverage/builds/79

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_12"></a>|@glyph set owner to @glyph|
|-|-|

Reviewed & approved.  Since there's already clean CI, will land momentarily.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_13"></a>|@glyph set status to `closed`|
|-|-|

In changeset aeeffc7a94880f156d30526b73c89348b6948db0
```
#!CommitTicketReference repository="" revision="aeeffc7a94880f156d30526b73c89348b6948db0"
Merge pull request #665 from twisted/8967-test_newtls-avoid-econnaborted

Author: markrwilliams

Reviewer: glyph

Fixes: ticket:8967

Fix test reliability bug in twisted.internet.test.test_newtls.ProducerTestsMixin by waiting for handshake completion for completion-sensitive tests.
```
