### ISSUE TITLE
`trial ...` and `python -m twisted.trial ...` result in significantly divergent `sys.path` values

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#8972]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#8972|
|Type|defect|
|Created|2017-01-02 14:12:29Z|

```
(trialtest) exarkun@baryon:/tmp/trialthing$ trial --version
Twisted version: 16.6.0dev0
(trialtest) exarkun@baryon:/tmp/trialthing$ cat test_thing.py
import sys
import pprint

pprint.pprint(sys.path)

(trialtest) exarkun@baryon:/tmp/trialthing$ echo ${PYTHONPATH}

(trialtest) exarkun@baryon:/tmp/trialthing$ trial test_thing
test_thing ...                                                          [ERROR]

===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/home/exarkun/Projects/twisted/src/twisted/trial/runner.py", line 602, in loadByNames
    things.append(self.findByName(name))
  File "/home/exarkun/Projects/twisted/src/twisted/trial/runner.py", line 406, in findByName
    return reflect.namedAny(name)
  File "/home/exarkun/Projects/twisted/src/twisted/python/reflect.py", line 306, in namedAny
    raise ModuleNotFound("No module named %r" % (name,))
twisted.python.reflect.ModuleNotFound: No module named 'test_thing'

test_thing
-------------------------------------------------------------------------------
Ran 1 tests in 0.012s

FAILED (errors=1)
(trialtest) exarkun@baryon:/tmp/trialthing$ python -m twisted.trial test_thing
['',
 '/tmp/trialtest/lib/python2.7',
 '/tmp/trialtest/lib/python2.7/plat-x86_64-linux-gnu',
 '/tmp/trialtest/lib/python2.7/lib-tk',
 '/tmp/trialtest/lib/python2.7/lib-old',
 '/tmp/trialtest/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/tmp/trialtest/local/lib/python2.7/site-packages',
 '/home/exarkun/Projects/twisted/src',
 '/tmp/trialtest/lib/python2.7/site-packages']

-------------------------------------------------------------------------------

PASSED
(trialtest) exarkun@baryon:/tmp/trialthing$ 
```

I can't quite find an explicit statement that the change of behavior to trial to exclude "" from sys.path was intentional - but I did find http://twistedmatrix.com/pipermail/twisted-python/2016-September/030780.html which discusses the parallel change in twistd and suggests it was intentional (or at least accidental but then desired).

In this case, making `twistd -m twisted.trial ...` agree with the desired behavior seems to make more sense than allowing the two to diverge, with the new (presumably desirable) version having the old (apparently undesirable) behavior.

<details><summary>Searchable metadata</summary>

```
trac-id__8972 8972
type__defect defect
reporter__exarkun exarkun
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__wontfix wontfix
component__trial trial
keywords__None None
time__1483366349575861 1483366349575861
changetime__1486928280219644 1486928280219644
version__None None
owner__rodrigc rodrigc

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

Apparently this was discussed, perhaps on IRC, and the decision was made that not putting pwd in sys.path is the right thing to do.

It would be nice if someone involved in the discussion documented that rationale, though.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_2"></a>|@glyph commented|
|-|-|

[#8978](https://github.com/twisted/twisted/issues/8978) was a duplicate of this.

**Comment by twisted-trac** [comment]
|[<img alt="Julian's avatar" src="https://avatars.githubusercontent.com/u/329822?s=50" width="50" height="50">](https://github.com/Julian)<a name="note_3"></a>|@Julian set owner to @rodrigc|
|-|-|

https://github.com/twisted/twisted/pull/672

**Comment by twisted-trac** [comment]
|[<img alt="Julian's avatar" src="https://avatars.githubusercontent.com/u/329822?s=50" width="50" height="50">](https://github.com/Julian)<a name="note_6"></a>|@Julian set status to `closed`|
|-|-|

At least one part of the rationale is in https://twistedmatrix.com/pipermail/twisted-python/2017-February/031145.html

Closing this out given that it sounds like consensus is to leave as-is.
