### ISSUE TITLE
twisted.trial._dist.test.test_disttrial.DistTrialRunnerTests.test_runStopAfterTests failing on Windows buildbot

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#8994]
|[<img alt="Lukasa's avatar" src="https://avatars.githubusercontent.com/u/1382556?s=50" width="50" height="50">](https://github.com/Lukasa)| @Lukasa reported|
|-|-|
|Trac ID|trac#8994|
|Type|defect|
|Created|2017-01-14 09:55:17Z|

See output here: https://buildbot.twistedmatrix.com/builders/windows7-64-py2.7-coverage/builds/711/steps/default/logs/problems

Relevant traceback:

```
[FAIL]
Traceback (most recent call last):
  File "c:\buildslave\windows7-64-py2_7-coverage\twisted\build\py27-alldeps-withcov-windows\lib\site-packages\twisted\internet\task.py", line 865, in <lambda>
    d.addCallback(lambda ignored: callable(*args, **kw))
  File "c:\buildslave\windows7-64-py2_7-coverage\twisted\build\py27-alldeps-withcov-windows\lib\site-packages\twisted\trial\_dist\test\test_disttrial.py", line 323, in check
    self.assertTrue(localLock.lock())
  File "c:\buildslave\windows7-64-py2_7-coverage\twisted\build\py27-alldeps-withcov-windows\lib\site-packages\twisted\trial\_synctest.py", line 395, in assertTrue
    super(_Assertions, self).assertTrue(condition, msg)
  File "c:\python27\Lib\unittest\case.py", line 422, in assertTrue
    raise self.failureException(msg)
twisted.trial.unittest.FailTest: False is not true

twisted.trial._dist.test.test_disttrial.DistTrialRunnerTests.test_runStopAfterTests
-------------------------------------------------------------------------------
```

<details><summary>Searchable metadata</summary>

```
trac-id__8994 8994
type__defect defect
reporter__Lukasa Lukasa
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__None None
time__1484387717290172 1484387717290172
changetime__1484387717290172 1484387717290172
version__None None
owner__None None

```
</details>

**Comment by glyph** [comment]
The disttrial tests are running and passing on Windows in GHA. (This specific test does not appear to exist any more.)
