### ISSUE TITLE
twisted.python.test.test_release.APIBuilderTests spurious failures

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#8999]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)| @wsanchez reported|
|-|-|
|Trac ID|trac#8999|
|Type|enhancement|
|Created|2017-01-18 00:15:36Z|

`twisted.python.test.test_release.APIBuilderTests` is causing spurious failures:

https://buildbot.twistedmatrix.com/builders/ubuntu16.04-py2.7/builds/2208/steps/select/logs/problems

```
===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/buildslave/ubuntu16.04-py2.7/Twisted/build/py27-alldeps-nocov-posix/local/lib/python2.7/site-packages/twisted/python/test/test_release.py", line 472, in test_buildWithPolicy
    self.assertEqual(stdout.getvalue(), '')
  File "/buildslave/ubuntu16.04-py2.7/Twisted/build/py27-alldeps-nocov-posix/local/lib/python2.7/site-packages/twisted/trial/_synctest.py", line 432, in assertEqual
    super(_Assertions, self).assertEqual(first, second, msg)
  File "/usr/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python2.7/unittest/case.py", line 506, in _baseAssertEqual
    raise self.failureException(msg)
twisted.trial.unittest.FailTest: 'Failed to get object inventory from https://python-hyper.org/h2/en/stable/objects.inv\n' != ''

twisted.python.test.test_release.APIBuilderTests.test_buildWithPolicy
-------------------------------------------------------------------------------
```

<details><summary>Searchable metadata</summary>

```
trac-id__8999 8999
type__enhancement enhancement
reporter__wsanchez wsanchez
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__duplicate duplicate
component__core core
keywords__None None
time__1484698536158838 1484698536158838
changetime__1484699128008519 1484699128008519
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)<a name="note_1"></a>|@wsanchez commented|
|-|-|

If I kick the builders repeatedly, this eventually succeeds, which suggests that we are, indeed, trying to obtain a network resource from a web site as part of a test, which seems problematic.

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)<a name="note_2"></a>|@wsanchez commented|
|-|-|

[#8950](https://github.com/twisted/twisted/issues/8950)

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)<a name="note_3"></a>|@wsanchez set status to `closed`|
|-|-|

Duplicate of [#8753](https://github.com/twisted/twisted/issues/8753)
