### ISSUE TITLE
twist command line that specifies --reactor multiple times fails.

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9002]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)| @wsanchez reported|
|-|-|
|Trac ID|trac#9002|
|Type|enhancement|
|Created|2017-01-18 00:43:03Z|

If you specify the `--reactor` option more than one time, you will get an exception:

```
wsanchez$ /tmp/ve/bin/twist --reactor select --reactor kqueue web
Traceback (most recent call last):
  File "/tmp/ve/bin/twist", line 11, in <module>
    load_entry_point('Twisted', 'console_scripts', 'twist')()
  File "/Users/wsanchez/Dropbox/Developer/Twisted/twisted/src/twisted/application/twist/_twist.py", line 132, in main
    options = cls.options(argv)
  File "/Users/wsanchez/Dropbox/Developer/Twisted/twisted/src/twisted/application/twist/_twist.py", line 38, in options
    options.parseOptions(argv[1:])
  File "/Users/wsanchez/Dropbox/Developer/Twisted/twisted/src/twisted/application/twist/_options.py", line 168, in parseOptions
    Options.parseOptions(self, options=options)
  File "/Users/wsanchez/Dropbox/Developer/Twisted/twisted/src/twisted/python/usage.py", line 255, in parseOptions
    self._dispatch[optMangled](optMangled, arg)
  File "/Users/wsanchez/Dropbox/Developer/Twisted/twisted/src/twisted/python/usage.py", line 411, in <lambda>
    fn = lambda name, value, m=method: m(value)
  File "/Users/wsanchez/Dropbox/Developer/Twisted/twisted/src/twisted/application/twist/_options.py", line 67, in opt_reactor
    self["reactor"] = self.installReactor(name)
  File "/Users/wsanchez/Dropbox/Developer/Twisted/twisted/src/twisted/application/twist/_options.py", line 88, in installReactor
    return installReactor(name)
  File "/Users/wsanchez/Dropbox/Developer/Twisted/twisted/src/twisted/application/reactors.py", line 82, in installReactor
    installer.install()
  File "/Users/wsanchez/Dropbox/Developer/Twisted/twisted/src/twisted/application/reactors.py", line 60, in install
    namedAny(self.moduleName).install()
  File "/Users/wsanchez/Dropbox/Developer/Twisted/twisted/src/twisted/internet/kqreactor.py", line 317, in install
    installReactor(p)
  File "/Users/wsanchez/Dropbox/Developer/Twisted/twisted/src/twisted/internet/main.py", line 32, in installReactor
    raise error.ReactorAlreadyInstalledError("reactor already installed")
twisted.internet.error.ReactorAlreadyInstalledError: reactor already installed
```

<details><summary>Searchable metadata</summary>

```
trac-id__9002 9002
type__enhancement enhancement
reporter__wsanchez wsanchez
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__None None
time__1484700183408762 1484700183408762
changetime__1484705116816918 1484705116816918
version__None None
owner__None None
cc__wsanchez
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)<a name="note_2"></a>|@wsanchez commented|
|-|-|

This was introduced by https://github.com/twisted/twisted/pull/668/files

I has tried to avoid this problem but ended up not getting the correct reactor at all, which the above fixes, but got this bug instead.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_3"></a>|@exarkun commented|
|-|-|

What do you think the correct behavior is?  It seems like an error to me.  Perhaps we could present it to the user more nicely...

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)<a name="note_4"></a>|@wsanchez commented|
|-|-|

The correct behavior for command line options (and I base this on having worked on BSD user land, and am aware that these conventions are often ignored) is that a flag that has set a value, when applied repeatedly, should result in the last value winning.

Printing exception is certainly a bug; if we were to decide that specifying `--reactor` twice is a user error, then yes, printing an error to that effect and exiting with an `EX_USAGE` is correct.  But I don't think that's a good decision.

The reason for that convention, and why flags like `--enable-foo` should be accompanied by an opposite like `--disable-foo`, is so that you can override flags set up earlier in a shell script without having to somehow remove the previously set flags.  A simple example, where you wrap `twist` to use some default reactor you pick but then you have a use case where you want some other reactor:

```
twist () {
  "${virtualenv}/bin/twist" --log-format=json --reactor=kqueue "$@";
}

# ...

# I'm on a Mac and I'm going to use some PTYs, so kqueue maybe isn't cool
twist --reactor=select web;
```

Anyway, other options (eg. `--log-format`) do behave this way (last call to `opt_log_format` sets the winning value), so it's good to be consistent.

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)<a name="note_5"></a>|@wsanchez commented|
|-|-|

Perhaps that was verbose.  To answer exarkun's question, this:

```
twist --reactor X --reactor Y command;
```

Should run with reactor `Y`.
