### ISSUE TITLE
Exception thrown when building apidocs

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9013]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)| @rodrigc reported|
|-|-|
|Trac ID|trac#9013|
|Type|defect|
|Created|2017-01-26 10:02:27Z|
|Branch|https://github.com/twisted/twisted/tree/9013-rodrigc-apidocs|

Activestate's web pages are temporarily unavailable, causing this error during API build:

```
apidocs runtests: commands[5] | /buildslave/documentation/Twisted/bin/admin/build-apidocs /buildslave/documentation/Twisted/src/ apidocs
Traceback (most recent call last):
  File "/buildslave/documentation/Twisted/bin/admin/build-apidocs", line 20, in <module>
    BuildAPIDocsScript().main(sys.argv[1:])
  File "/buildslave/documentation/Twisted/build/apidocs/lib/python2.7/site-packages/twisted/python/_release.py", line 859, in main
    self.buildAPIDocs(FilePath(args[0]), FilePath(args[1]))
  File "/buildslave/documentation/Twisted/build/apidocs/lib/python2.7/site-packages/twisted/python/_release.py", line 844, in buildAPIDocs
    output)
  File "/buildslave/documentation/Twisted/build/apidocs/lib/python2.7/site-packages/twisted/python/_release.py", line 376, in build
    ] + intersphinxes)
  File "/buildslave/documentation/Twisted/build/apidocs/lib/python2.7/site-packages/pydoctor/driver.py", line 364, in main
    writer.writeIndividualFiles(subjects, options.htmlfunctionpages)
  File "/buildslave/documentation/Twisted/build/apidocs/lib/python2.7/site-packages/pydoctor/templatewriter/writer.py", line 45, in writeIndividualFiles
    self.writeDocsFor(ob, functionpages=functionpages)
  File "/buildslave/documentation/Twisted/build/apidocs/lib/python2.7/site-packages/pydoctor/templatewriter/writer.py", line 70, in writeDocsFor
    self.writeDocsFor(o, functionpages)
  File "/buildslave/documentation/Twisted/build/apidocs/lib/python2.7/site-packages/pydoctor/templatewriter/writer.py", line 70, in writeDocsFor
    self.writeDocsFor(o, functionpages)
  File "/buildslave/documentation/Twisted/build/apidocs/lib/python2.7/site-packages/pydoctor/templatewriter/writer.py", line 70, in writeDocsFor
    self.writeDocsFor(o, functionpages)
  File "/buildslave/documentation/Twisted/build/apidocs/lib/python2.7/site-packages/pydoctor/templatewriter/writer.py", line 67, in writeDocsFor
    self.writeDocsForOne(ob, f)
  File "/buildslave/documentation/Twisted/build/apidocs/lib/python2.7/site-packages/pydoctor/templatewriter/writer.py", line 88, in writeDocsForOne
    flattenToFile(fobj, page)
  File "/buildslave/documentation/Twisted/build/apidocs/lib/python2.7/site-packages/pydoctor/templatewriter/writer.py", line 19, in flattenToFile
    raise err[0]
twisted.web.error.FlattenerError: Exception while flattening:
  <pydoctor.templatewriter.pages.ZopeInterfaceClassPage object at 0x7f88b0f17b90>
  [Tag(u'html', children=[u'\n', u'  ', Tag(u'head', children=[u'\n', u'    ', Tag(u'title', children=[slot(u'title'), u' : API documentation']), u'\n', u'\n', u'    ', Tag(u'meta', attributes=OrderedDict([(u'content', u'text/html;charset=utf-8'), (u'http-equiv', u'Content-Type')])), u'\n', u'    ', Tag(u'link', attributes=OrderedDict([(u'href', u'bootstrap.min.css'), (u'rel', u'stylesheet'), (u'type', u'text/css')])), u'\n', u'    ', Tag(u'link', attributes=OrderedDict([(u'href', u'apidocs.css'), (u'rel', u'stylesheet'), (u'type', u'text/css')])), u'\n', u'  ']), u'\n', u'  ', Tag(u'body', children=[u'\n', u'\n', u'    ', Tag(u'nav', attributes=OrderedDict([(u'class', u'navbar navbar-default')]), children=[u'\n', u'      ', Tag(u'div', attributes=OrderedDict([(u'class', u'container')]), children=[u'\n', u'        ', Tag(u'div', attributes=OrderedDict([(u'class', u'navbar-header')]), children=[u'\n', u'          ', Tag(u'a', attributes=OrderedDict([(u'href', u'index.html'), (u'class', u'navbar-brand')]), children=[u'\n', u'            Twisted API Documentation', u'\n', u'          ']), u'\n', u'        ']), u'\n', u'      ']), u'\n', u'    ']), u'\n', u'\n', u'   ', Tag(u'div', attributes=OrderedDict([(u'style', u'display: none'), (u'id', u'current-docs-container'), (u'class', u'container')]), children=[u'\n', u'      ', Tag(u'div', attributes=OrderedDict([(u'class', u'col-sm-12')]), children=[u'\n', u'        ', Tag(u'a', attributes=OrderedDict([(u'id', u'current-docs-link')]), children=[u'\n', u'          Go to the latest version of this document.', u'\n', u'        ']), u'\n', u'      ']), u'\n', u'    ']), u'\n', u'\n', u'    ', Tag(u'div', attributes=OrderedDict([(u'id', u'showPrivate')]), children=[u'\n', u'      ', Tag(u'button', attributes=OrderedDict([(u'onclick', u'togglePrivate()'), (u'class', u'btn btn-link')]), children=[u'Toggle Private API']), u'\n', u'    ']), u'\n', u'\n', u'    ', Tag(u'div', attributes=OrderedDict([(u'class', u'container')]), children=[u'\n', u'\n', u'      ', Tag(u'div', attributes=OrderedDict([(u'class', u'page-header')]), children=[u'\n', u'        ', slot(u'heading'), u'\n', u'\n', u'        ', Tag(u'span', attributes=OrderedDict([(u'id', u'partOf')]), children=[u'\n', u'          ', slot(u'part'), u'\n', u'          ', Tag(u'a', children=[u'View Source']), u'\n', u'          ', Tag(u'a', children=[u'(View In Hierarchy)']), u'\n', u'        ']), u'\n', u'      ']), u'\n', u'\n', u'      ', Tag(u'div', attributes=OrderedDict([(u'class', u'extrasDocstring')]), children=[u'\n', u'        ', slot(u'extras'), u'\n', u'      ']), u'\n', u'\n', u'      ', Tag(''), u'\n', u'\n', u'      ', Tag(u'div', attributes=OrderedDict([(u'class', u'moduleDocstring')]), children=[u'\n', u'        ', slot(u'docstring'), u'\n', u'      ']), u'\n', u'\n', u'      ', Tag(u'div', attributes=OrderedDict([(u'id', u'splitTables')]), children=[u'\n', u'        ', slot(u'mainTable'), u'\n', u'        ', Tag('', children=[u'\n', u'          ', Tag(u'p', attributes=OrderedDict([(u'class', u'inheritedFrom')]), children=[u'\n', u'            Inherited from ', slot(u'baseName'), u':', u'\n', u'          ']), u'\n', u'          ', slot(u'baseTable'), u'\n', u'          ']), u'\n', u'\n', u'          ', slot(u'packageInitTable'), u'\n', u'      ']), u'\n', u'\n', u'      ', Tag(u'div', attributes=OrderedDict([(u'id', u'childList')]), children=[u'\n', u'\n', u'        ', slot(u'childlist'), u'\n', u'\n', u'      ']), u'\n', u'      ', Tag(u'address', children=[u'\n', u'        ', Tag(u'a', attributes=OrderedDict([(u'href', u'index.html')]), children=[u'API Documentation']), u' for ', slot(u'project'), u', generated by ', Tag(u'a', attributes=OrderedDict([(u'href', u'https://github.com/twisted/pydoctor/')]), children=[u'pydoctor']), u' at ', slot(u'buildtime'), u'.', u'\n', u'      ']), u'\n', u'\n', u'    ']), u'\n', u'\n', u'    ', Tag(u'script', attributes=OrderedDict([(u'src', u'pydoctor.js'), (u'type', u'text/javascript')])), u'\n', u'\n', u'    ', Comment(u' Google analytics, obviously. '), u'\n', u'    ', Tag(u'script', attributes=OrderedDict([(u'src', u'//www.google-analytics.com/urchin.js'), (u'type', u'text/javascript')])), u'\n', u'    ', Tag(u'script', attributes=OrderedDict([(u'type', u'text/javascript')]), children=[u'\n', u'      _uacct = "UA-99018-6";', u'\n', u'      urchinTracker();', u'\n', u'    ']), u'\n', u'\n', u'    ', Comment(u" If the documentation isn't current, insert a current link. "), u'\n', u'    ', Tag(u'script', attributes=OrderedDict([(u'type', u'text/javascript')]), children=[u'\n', u"      if (window.location.pathname.indexOf('/current/') == -1) {", u'\n', u'        ', Comment(u' Give the user a link to this page, but in the current version of the docs. '), u'\n', u"        var link = document.getElementById('current-docs-link');", u'\n', u"        link.href = window.location.pathname.replace(/\\/\\d+\\.\\d+\\.\\d+\\/api\\//, '/current/api/');", u'\n', u'        ', Comment(u' And make it visible '), u'\n', u"        var container = document.getElementById('current-docs-container');", u'\n', u'        container.style.display = "";', u'\n', u'        delete link;', u'\n', u'        delete container;', u'\n', u'      }', u'\n', u'    ']), u'\n', u'\n', u'  ']), u'\n'])]
  Tag <html>
  File "/buildslave/documentation/Twisted/build/apidocs/lib/python2.7/site-packages/twisted/web/_flatten.py", line 312, in _flattenTree
    element = next(stack[-1])
  File "/buildslave/documentation/Twisted/build/apidocs/lib/python2.7/site-packages/twisted/web/_flatten.py", line 231, in _flattenElement
    result = renderMethod(request, rootClone)
  File "/buildslave/documentation/Twisted/build/apidocs/lib/python2.7/site-packages/pydoctor/templatewriter/pages/__init__.py", line 171, in all
    docstring=self.docstring(),
  File "/buildslave/documentation/Twisted/build/apidocs/lib/python2.7/site-packages/pydoctor/templatewriter/pages/__init__.py", line 121, in docstring
    return self.docgetter.get(self.ob)
  File "/buildslave/documentation/Twisted/build/apidocs/lib/python2.7/site-packages/pydoctor/templatewriter/pages/__init__.py", line 51, in get
    return epydoc2stan.doc2stan(ob, summary=summary)[0]
  File "/buildslave/documentation/Twisted/build/apidocs/lib/python2.7/site-packages/pydoctor/epydoc2stan.py", line 569, in doc2stan
    fh.handle(Field(field, obj))
  File "/buildslave/documentation/Twisted/build/apidocs/lib/python2.7/site-packages/pydoctor/epydoc2stan.py", line 297, in __init__
    self.body = html2stan(field.body().to_html(_EpydocLinker(obj)))
  File "/buildslave/documentation/Twisted/build/apidocs/lib/python2.7/site-packages/epydoc/markup/epytext.py", line 1782, in to_html
    docindex, context, indent)
  File "/buildslave/documentation/Twisted/build/apidocs/lib/python2.7/site-packages/epydoc/markup/epytext.py", line 1820, in _to_html
    for c in tree.children]
  File "/buildslave/documentation/Twisted/build/apidocs/lib/python2.7/site-packages/epydoc/markup/epytext.py", line 1820, in _to_html
    for c in tree.children]
  File "/buildslave/documentation/Twisted/build/apidocs/lib/python2.7/site-packages/epydoc/markup/epytext.py", line 1840, in _to_html
    return linker.translate_identifier_xref(variables[1], variables[0])
  File "/buildslave/documentation/Twisted/build/apidocs/lib/python2.7/site-packages/pydoctor/epydoc2stan.py", line 177, in translate_identifier_xref
    target = self.look_for_intersphinx(fullerID)
  File "/buildslave/documentation/Twisted/build/apidocs/lib/python2.7/site-packages/pydoctor/epydoc2stan.py", line 124, in look_for_intersphinx
    return self.obj.system.intersphinx.getLink(name)
  File "/buildslave/documentation/Twisted/build/apidocs/lib/python2.7/site-packages/twisted/python/_pydoctor.py", line 97, in getLink
    response = self._getURLAsHEAD(fullURL)
  File "/buildslave/documentation/Twisted/build/apidocs/lib/python2.7/site-packages/twisted/python/_pydoctor.py", line 119, in _getURLAsHEAD
    return urllib2.urlopen(HeadRequest(url))
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found
```

<details><summary>Searchable metadata</summary>

```
trac-id__9013 9013
type__defect defect
reporter__rodrigc rodrigc
priority__normal normal
milestone__None None
branch__9013_rodrigc_apidocs 9013-rodrigc-apidocs
branch_author__ 
status__closed closed
resolution__fixed fixed
component__release_management release management
keywords__None None
time__1485424947757526 1485424947757526
changetime__1485449577247196 1485449577247196
version__None None
owner__rodrigc rodrigc

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_1"></a>|@rodrigc commented|
|-|-|

https://github.com/twisted/twisted/pull/694

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun set owner to @rodrigc|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_3"></a>|@rodrigc set status to `closed`|
|-|-|

In changeset 675459cc2fffce67f45e5a8aa3e43bd3280fb370
```
#!CommitTicketReference repository="" revision="675459cc2fffce67f45e5a8aa3e43bd3280fb370"
Merge pull request #694 from twisted/9013-rodrigc-apidocs

Author: rodrigc
Reviewer: exarkun
Fixes: ticket:9013

Catch errors from urlopen() during apidocs build
```
