### ISSUE TITLE
Linux epoll reactor fails when reconnecting

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9025]
|<img alt="BMtthws's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| BMtthws reported|
|-|-|
|Trac ID|trac#9025|
|Type|defect|
|Created|2017-02-01 17:44:18Z|

The following exception is thrown on reconnect. Server must be restarted.

```
2017-02-01 07-24-13.143 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/opt/vaisala/bin/device_host.py", line 19, in <module>
	    host_run.run()
	  File "/opt/vaisala/viewlinc/ds/device_host/host_run.py", line 90, in run
	    
	  File "/usr/lib/python2.7/site-packages/twisted/internet/base.py", line 1192, in run
	    
	  File "/usr/lib/python2.7/site-packages/twisted/internet/base.py", line 1201, in mainLoop
	    
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/site-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    
	  File "/usr/lib/python2.7/site-packages/twisted/internet/tcp.py", line 425, in resolveAddress
	    
	  File "/usr/lib/python2.7/site-packages/twisted/internet/tcp.py", line 440, in _setRealAddress
	    
	  File "/usr/lib/python2.7/site-packages/twisted/internet/tcp.py", line 579, in doConnect
	    
	  File "/usr/lib/python2.7/site-packages/twisted/internet/abstract.py", line 434, in startReading
	    
	  File "/usr/lib/python2.7/site-packages/twisted/internet/epollreactor.py", line 271, in addReader
	    
	  File "/usr/lib/python2.7/site-packages/twisted/internet/epollreactor.py", line 255, in _add
	    
	exceptions.IOError: [Errno 2] No such file or directory
```
	

<details><summary>Searchable metadata</summary>

```
trac-id__9025 9025
type__defect defect
reporter__BMtthws BMtthws
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__wontfix wontfix
component__core core
keywords__None None
time__1485971058962787 1485971058962787
changetime__1485991640543274 1485991640543274
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_2"></a>|@exarkun set status to `closed`|
|-|-|

This happens if you fork() (even indirectly, eg via the multiprocessing module).  It's a long-standing issue.  Also, 13.2 is several years out of date and does not receive maintenance anymore.  If you can reproduce on a recent version of Twisted and can supply a minimal example, this might be fixable (but if it's due to fork() then probably not).  Please re-open, if so!

Closing for now as I don't think there's anything we can do about it.

**Comment by twisted-trac** [comment]
|<img alt="BMtthws's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_3"></a>|BMtthws commented|
|-|-|

Thank you so much for your help.
