### ISSUE TITLE
twistd web -l crashes on Python 3

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9029]
|[<img alt="hynek's avatar" src="https://avatars.githubusercontent.com/u/41240?s=50" width="50" height="50">](https://github.com/hynek)| @hynek reported|
|-|-|
|Trac ID|trac#9029|
|Type|defect|
|Created|2017-02-06 15:28:49Z|

I’m trying to use Twisted as a WSGI container and wanted to get rid of the web log using `-l /dev/null`.  Sadly it gets me:

```
2017-02-06T16:25:11+0100 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/Users/hynek/.virtualenvs/cust_ws/lib/python3.5/site-packages/twisted/application/runner/_runner.py", line 53, in run
	    self.startReactor()
	  File "/Users/hynek/.virtualenvs/cust_ws/lib/python3.5/site-packages/twisted/application/runner/_runner.py", line 134, in startReactor
	    reactor.run()
	  File "/Users/hynek/.virtualenvs/cust_ws/lib/python3.5/site-packages/twisted/internet/base.py", line 1243, in run
	    self.mainLoop()
	  File "/Users/hynek/.virtualenvs/cust_ws/lib/python3.5/site-packages/twisted/internet/base.py", line 1252, in mainLoop
	    self.runUntilCurrent()
	--- <exception caught here> ---
	  File "/Users/hynek/.virtualenvs/cust_ws/lib/python3.5/site-packages/twisted/internet/base.py", line 851, in runUntilCurrent
	    f(*a, **kw)
	  File "/Users/hynek/.virtualenvs/cust_ws/lib/python3.5/site-packages/twisted/web/wsgi.py", line 520, in wsgiFinish
	    self.request.finish()
	  File "/Users/hynek/.virtualenvs/cust_ws/lib/python3.5/site-packages/twisted/web/server.py", line 231, in finish
	    return http.Request.finish(self)
	  File "/Users/hynek/.virtualenvs/cust_ws/lib/python3.5/site-packages/twisted/web/http.py", line 885, in finish
	    self.channel.factory.log(self)
	  File "/Users/hynek/.virtualenvs/cust_ws/lib/python3.5/site-packages/twisted/web/http.py", line 2625, in log
	    logFile.write(line)
	  File "/Users/hynek/.virtualenvs/cust_ws/lib/python3.5/site-packages/twisted/python/threadable.py", line 53, in sync
	    return function(self, *args, **kwargs)
	  File "/Users/hynek/.virtualenvs/cust_ws/lib/python3.5/site-packages/twisted/python/logfile.py", line 204, in write
	    BaseLogFile.write(self, data)
	  File "/Users/hynek/.virtualenvs/cust_ws/lib/python3.5/site-packages/twisted/python/logfile.py", line 115, in write
	    self._file.write(data)
	builtins.TypeError: write() argument must be str, not bytes
```

on each request.

<details><summary>Searchable metadata</summary>

```
trac-id__9029 9029
type__defect defect
reporter__hynek hynek
priority__normal normal
milestone__Python_3_x Python-3.x
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__None None
time__1486394929366402 1486394929366402
changetime__1501741157953397 1501741157953397
version__None None
owner__None None
cc__twm@...
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_2"></a>|@rodrigc set status to `closed`|
|-|-|

Fixed in  [changeset:"d8aec37b4508885c596b7d56143916c49148cb12" d8aec37] as a side-effect of fixing ticket:6938
