### ISSUE TITLE
twisted.conch.manhole sometimes exits with an unhandled TypeError

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9031]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#9031|
|Type|release blocker: regression|
|Created|2017-02-09 14:05:54Z|

Sometimes `HistoricRecvLine._deliverBuffer` calls `characterReceived` with a list instead of a length-one byte string, violating the (implicit) interface and (unsurprisingly) breaking implementations like `Manhole`.

For Manhole, this manifests as an unexpected exit with an unhandled `TypeError`, for example:

```
2017-02-09 08:47:17-0500 [-] Unhandled Error
        Traceback (most recent call last):
          File "/home/exarkun/Environments/txkube/local/lib/python2.7/site-packages/twisted/python/log.py", line 103, in callWithLogger
            return callWithContext({"system": lp}, func, *args, **kw)
          File "/home/exarkun/Environments/txkube/local/lib/python2.7/site-packages/twisted/python/log.py", line 86, in callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File "/home/exarkun/Environments/txkube/local/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/home/exarkun/Environments/txkube/local/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
            return func(*args,**kw)
        --- <exception caught here> ---
          File "/home/exarkun/Environments/txkube/local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
            why = selectable.doRead()
          File "/home/exarkun/Environments/txkube/local/lib/python2.7/site-packages/twisted/internet/process.py", line 280, in doRead
            return fdesc.readFromFD(self.fd, self.dataReceived)
          File "/home/exarkun/Environments/txkube/local/lib/python2.7/site-packages/twisted/internet/fdesc.py", line 94, in readFromFD
            callback(output)
          File "/home/exarkun/Environments/txkube/local/lib/python2.7/site-packages/twisted/internet/process.py", line 283, in dataReceived
            self.proc.childDataReceived(self.name, data)
          File "/home/exarkun/Environments/txkube/local/lib/python2.7/site-packages/twisted/internet/_posixstdio.py", line 77, in childDataReceived
            self.protocol.dataReceived(data)
          File "/home/exarkun/Environments/txkube/local/lib/python2.7/site-packages/twisted/conch/insults/insults.py", line 551, in dataReceived
            self._handleControlSequence(b''.join(self.escBuf) + ch)
          File "/home/exarkun/Environments/txkube/local/lib/python2.7/site-packages/twisted/conch/insults/insults.py", line 575, in _handleControlSequence
            f(self, self.terminalProtocol, buf[:-1])
          File "/home/exarkun/Environments/txkube/local/lib/python2.7/site-packages/twisted/conch/insults/insults.py", line 602, in B
            handler.keystrokeReceived(proto.DOWN_ARROW, None)
          File "/home/exarkun/Environments/txkube/local/lib/python2.7/site-packages/twisted/conch/recvline.py", line 220, in keystrokeReceived
            m()
          File "/home/exarkun/Environments/txkube/local/lib/python2.7/site-packages/twisted/conch/recvline.py", line 355, in handle_DOWN
            self._deliverBuffer(self.historyLines[self.historyPosition])
          File "/home/exarkun/Environments/txkube/local/lib/python2.7/site-packages/twisted/conch/recvline.py", line 331, in _deliverBuffer
            self.characterReceived(buf[-1:], False)
          File "/home/exarkun/Environments/txkube/local/lib/python2.7/site-packages/twisted/conch/manhole.py", line 335, in characterReceived
            source = self.getSource()
          File "/home/exarkun/Environments/txkube/local/lib/python2.7/site-packages/twisted/conch/manhole.py", line 315, in getSource
            ''.join(self.lineBuffer))
        exceptions.TypeError: sequence item 0: expected string, list found
```

The cause is the last line of the method:

```
    self.characterReceived(buf[-1:], False)
```

The regression was introduced by ticket:8691 / [https://github.com/twisted/twisted/pull/421 PR[#8057](https://github.com/twisted/twisted/issues/8057)] / [1aac4c14](https://github.com/twisted/twisted/commit/1aac4c147368dcb5cbd1967ccf8bca0c41a45be0) which ported some of Twisted Conch to Python 3.  It's not obvious what the motiviation for this specific part of the change was.

<details><summary>Searchable metadata</summary>

```
trac-id__9031 9031
type__release_blocker__regression release blocker: regression
reporter__exarkun exarkun
priority__normal normal
milestone__17_1_1 17.1.1
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__conch conch
keywords__None None
time__1486649154155054 1486649154155054
changetime__1487298425815287 1487298425815287
version__None None
owner__glyph glyph
cc__mithrandi@...
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

Ah, I guess the motivation was that indexing a byte string on Python 3 produces an integer whereas slicing it (even a slice of length 1) produces another byte string.  However, the indexed/sliced object here is a list and not a byte string, so the change is spurious and incorrect.

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_3"></a>|@markrwilliams commented|
|-|-|

https://github.com/twisted/twisted/pull/706

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_5"></a>|@glyph set owner to @glyph|
|-|-|

Looks good to me, good test, fixes the regression.  I will land.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_6"></a>|@glyph set status to `closed`|
|-|-|

In changeset 2c876c87497ef610d3a57c0851974b50a33a3a3f
```
#!CommitTicketReference repository="" revision="2c876c87497ef610d3a57c0851974b50a33a3a3f"
Merge pull request #706 from twisted/9031-manhole-typeerror

Author: markrwilliams

Reviewer: glyph

Fixes: ticket:9031

History-aware terminal protocols like twisted.conch.manhole.Manhole no longer raise a TypeError when a user visits a partial line they added to the command line history by pressing up arrow before return.
```
