### ISSUE TITLE
perpective broker crash when calling py3 server from py2 with kwargs

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9047]
|[<img alt="tardyp's avatar" src="https://avatars.githubusercontent.com/u/109859?s=50" width="50" height="50">](https://github.com/tardyp)| @tardyp reported|
|-|-|
|Trac ID|trac#9047|
|Type|defect|
|Created|2017-02-22 17:53:52Z|

I edited the example as follow:
```
0 % git diff
diff --git a/docs/core/examples/pbsimple.py b/docs/core/examples/pbsimple.py
index 91a47e9..64b3c0b 100644
--- a/docs/core/examples/pbsimple.py
+++ b/docs/core/examples/pbsimple.py
@@ -8,8 +8,8 @@ from twisted.spread import pb
 from twisted.internet import reactor

 class Echoer(pb.Root):
-    def remote_echo(self, st):
-        print('echoing:', st)
+    def remote_echo(self, st, kw='toto'):
+        print('echoing:', st, kw)
         return st

 if __name__ == '__main__':
diff --git a/docs/core/examples/pbsimpleclient.py b/docs/core/examples/pbsimpleclient.py
index 05cb50a..b46989b 100644
--- a/docs/core/examples/pbsimpleclient.py
+++ b/docs/core/examples/pbsimpleclient.py
@@ -10,7 +10,7 @@ from twisted.python import util
 factory = pb.PBClientFactory()
 reactor.connectTCP("localhost", 8789, factory)
 d = factory.getRootObject()
-d.addCallback(lambda object: object.callRemote("echo", "hello network"))
+d.addCallback(lambda object: object.callRemote("echo", "hello network", kw="titi"))
 d.addCallback(lambda echo: 'server echoed: '+echo)
 d.addErrback(lambda reason: 'error: '+str(reason.value))
 d.addCallback(util.println)
```

Then starting the server from py3:
```
1 % ~/dev/bb/py3/.venv/bin/python pbsimple.py
Peer will receive following PB traceback:
Unhandled Error
Traceback (most recent call last):
  File "/Users/ptardy/dev/bb/py3/.venv/lib/python3.6/site-packages/twisted/spread/banana.py", line 173, in gotItem
    self.callExpressionReceived(item)
  File "/Users/ptardy/dev/bb/py3/.venv/lib/python3.6/site-packages/twisted/spread/banana.py", line 136, in callExpressionReceived
    self.expressionReceived(obj)
  File "/Users/ptardy/dev/bb/py3/.venv/lib/python3.6/site-packages/twisted/spread/pb.py", line 621, in expressionReceived
    method(*sexp[1:])
  File "/Users/ptardy/dev/bb/py3/.venv/lib/python3.6/site-packages/twisted/spread/pb.py", line 1025, in proto_message
    self._recvMessage(self.localObjectForID, requestID, objectID, message, answerRequired, netArgs, netKw)
--- <exception caught here> ---
  File "/Users/ptardy/dev/bb/py3/.venv/lib/python3.6/site-packages/twisted/spread/pb.py", line 1054, in _recvMessage
    netResult = object.remoteMessageReceived(self, message, netArgs, netKw)
  File "/Users/ptardy/dev/bb/py3/.venv/lib/python3.6/site-packages/twisted/spread/flavors.py", line 120, in remoteMessageReceived
    state = method(*args, **kw)
builtins.TypeError: remote_echo() keywords must be strings
```
with client from py2:
```
0 % ~/dev/bb/buildbot/.venv/bin/python pbsimpleclient.py
error: remote_echo() keywords must be strings
```

<details><summary>Searchable metadata</summary>

```
trac-id__9047 9047
type__defect defect
reporter__tardyp tardyp
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__pb pb
keywords__None None
time__1487786032840473 1487786032840473
changetime__1491333430391379 1491333430391379
version__None None
owner__rodrigc rodrigc

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="tardyp's avatar" src="https://avatars.githubusercontent.com/u/109859?s=50" width="50" height="50">](https://github.com/tardyp)<a name="note_1"></a>|@tardyp commented|
|-|-|

Following patch
```
--- a/src/twisted/spread/flavors.py
+++ b/src/twisted/spread/flavors.py
@@ -113,6 +115,8 @@ class Referenceable(Serializable):
         if not isinstance(message, str):
             message = message.decode('utf8')

+        if [x for x in kw.keys() if isinstance(x, bytes)]:
+            kw = dict((k.decode('utf8'), v) for k, v in kw.items())
         method = getattr(self, "remote_%s" % message, None)
         if method is None:
             raise NoSuchMethod("No such method: remote_%s" % (message,))
```

do fix the problem, but prints
```
 echoing: b'hello network' b'titi'
```
instead of:
```
echoing: hello network titi
```
I am not sure exactely what is the correct strategy for this.

Should we convert all the bytes arguments to native strings when we are in py3?

Should we fix this rather in banana layer?

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_2"></a>|@glyph commented|
|-|-|

Thank you very much for reporting this.  It's a pretty serious bug.

Replying to [Pierre Tardy](#note_1):
> Following patch
> ```
> --- a/src/twisted/spread/flavors.py
> +++ b/src/twisted/spread/flavors.py
> @@ -113,6 +115,8 @@ class Referenceable(Serializable):
>          if not isinstance(message, str):
>              message = message.decode('utf8')
> 
> +        if [x for x in kw.keys() if isinstance(x, bytes)]:
> +            kw = dict((k.decode('utf8'), v) for k, v in kw.items())
>          method = getattr(self, "remote_%s" % message, None)
>          if method is None:
>              raise NoSuchMethod("No such method: remote_%s" % (message,))
> ```
> 
> do fix the problem, but prints
> ```
>  echoing: b'hello network' b'titi'
> ```
> instead of:
> ```
> echoing: hello network titi
> ```
> I am not sure exactely what is the correct strategy for this.

This is correct.  You sent some bytes from py2, and py3 received them as bytes.

If you want these to show up as text, you need to put a `u''` syntax in python 2, to clearly indicate that they're text.

> Should we convert all the bytes arguments to native strings when we are in py3?

No, bytes arguments should remain bytes, if you want text (str in py3, unicode in py2) use the appropriate data type.

> Should we fix this rather in banana layer?

The thing to "fix" here is the specific case of the _names_ of the kwargs, which are bytes on python 2 and text on python 3, but should be mutually intelligible; your patch as it is already does that more or less correctly.  (Although it needs a test.)

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_4"></a>|@exarkun commented|
|-|-|

Please link to the GitHub PR.

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_5"></a>|@rodrigc commented|
|-|-|

https://github.com/twisted/twisted/pull/722

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_6"></a>|@glyph set owner to @rodrigc|
|-|-|

Thanks for fixing this, Craig!  Review is on the PR.

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_7"></a>|@rodrigc set status to `closed`|
|-|-|

In changeset 8d2af2edcc8fbf71569663cc5db2d145a48228c2
```
#!CommitTicketReference repository="" revision="8d2af2edcc8fbf71569663cc5db2d145a48228c2"
Merge pull request #722 from twisted/9047-pb-py3-kwargs

Author: rodrigc, tardyp
Reviewer: glyph
Fixes: ticket:9047

Fix PB call with keyword arguments between Py2 client and Py3 server
```
