### ISSUE TITLE
Some tests fail against idna 2.3

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9062]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#9062|
|Type|defect|
|Created|2017-02-28 13:20:10Z|

```
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/buildslave/debian8-py2.7/Twisted/build/py27-tests/local/lib/python2.7/site-packages/twisted/internet/test/test_endpoints.py", line 2057, in test_deferBadEncodingToConnect
    u'\u2ff0-garbage-\u2ff0', 80
  File "/buildslave/debian8-py2.7/Twisted/build/py27-tests/local/lib/python2.7/site-packages/twisted/internet/endpoints.py", line 708, in __init__
    self._hostAsBytesAndText(host)
  File "/buildslave/debian8-py2.7/Twisted/build/py27-tests/local/lib/python2.7/site-packages/twisted/internet/endpoints.py", line 754, in _hostAsBytesAndText
    return False, _idnaBytes(host), host
  File "/buildslave/debian8-py2.7/Twisted/build/py27-tests/local/lib/python2.7/site-packages/twisted/internet/_idna.py", line 30, in _idnaBytes
    return idna.encode(text)
  File "/buildslave/debian8-py2.7/Twisted/build/py27-tests/local/lib/python2.7/site-packages/idna/core.py", line 355, in encode
    result.append(alabel(label))
  File "/buildslave/debian8-py2.7/Twisted/build/py27-tests/local/lib/python2.7/site-packages/idna/core.py", line 276, in alabel
    check_label(label)
  File "/buildslave/debian8-py2.7/Twisted/build/py27-tests/local/lib/python2.7/site-packages/idna/core.py", line 253, in check_label
    raise InvalidCodepoint('Codepoint {0} at position {1} of {2} not allowed'.format(_unot(cp_value), pos+1, repr(label)))
idna.core.InvalidCodepoint: Codepoint U+2FF0 at position 1 of u'\u2ff0-garbage-\u2ff0' not allowed

twisted.internet.test.test_endpoints.HostnameEndpointIDNATests.test_deferBadEncodingToConnect
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/buildslave/debian8-py2.7/Twisted/build/py27-tests/local/lib/python2.7/site-packages/twisted/web/test/test_agent.py", line 955, in test_unsupportedScheme
    self.agent.request(b'GET', b'mailto:alice@example.com'),
  File "/buildslave/debian8-py2.7/Twisted/build/py27-tests/local/lib/python2.7/site-packages/twisted/web/client.py", line 1625, in request
    endpoint = self._getEndpoint(parsedURI)
  File "/buildslave/debian8-py2.7/Twisted/build/py27-tests/local/lib/python2.7/site-packages/twisted/web/client.py", line 1609, in _getEndpoint
    return self._endpointFactory.endpointForURI(uri)
  File "/buildslave/debian8-py2.7/Twisted/build/py27-tests/local/lib/python2.7/site-packages/twisted/web/client.py", line 1481, in endpointForURI
    endpoint = HostnameEndpoint(self._reactor, host, uri.port, **kwargs)
  File "/buildslave/debian8-py2.7/Twisted/build/py27-tests/local/lib/python2.7/site-packages/twisted/internet/endpoints.py", line 708, in __init__
    self._hostAsBytesAndText(host)
  File "/buildslave/debian8-py2.7/Twisted/build/py27-tests/local/lib/python2.7/site-packages/twisted/internet/endpoints.py", line 744, in _hostAsBytesAndText
    return False, host, _idnaText(host)
  File "/buildslave/debian8-py2.7/Twisted/build/py27-tests/local/lib/python2.7/site-packages/twisted/internet/_idna.py", line 51, in _idnaText
    return idna.decode(octets)
  File "/buildslave/debian8-py2.7/Twisted/build/py27-tests/local/lib/python2.7/site-packages/idna/core.py", line 379, in decode
    raise IDNAError('Empty domain')
idna.core.IDNAError: Empty domain

twisted.web.test.test_agent.AgentTests.test_unsupportedScheme
-------------------------------------------------------------------------------
```

The code seemed to work against idna 2.2.  Unfortunately the requirement is merely declared as `idna >= 0.6` so the newly released idna 2.3 gets used for any new install.

<details><summary>Searchable metadata</summary>

```
trac-id__9062 9062
type__defect defect
reporter__exarkun exarkun
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__None None
time__1488288010163511 1488288010163511
changetime__1488335062420339 1488335062420339
version__None None
owner__exarkun exarkun

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

https://github.com/twisted/twisted/pull/724

**Comment by twisted-trac** [comment]
|[<img alt="Lukasa's avatar" src="https://avatars.githubusercontent.com/u/1382556?s=50" width="50" height="50">](https://github.com/Lukasa)<a name="note_2"></a>|@Lukasa set owner to @exarkun|
|-|-|

Patch looks good to me, merge when the tests go green.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_3"></a>|@exarkun set status to `closed`|
|-|-|

Fixed by https://github.com/twisted/twisted/commit/431ebcbe27398cb6570d4ff7a5a27ad081912c68

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_4"></a>|@glyph commented|
|-|-|

We should probably report this regression upstream.  The upstream bugtracker is here.  Does anyone understand this issue any better than I do? (My understanding is just "this input now fails") :)  https://github.com/kjd/idna
