### ISSUE TITLE
large quantity of mostly-useless error log events

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9099]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#9099|
|Type|defect|
|Created|2017-03-30 14:59:41Z|

Using `twist`, most of my log output ends up being duplicates of a more-or-less useless "Unhandled error in Deferred" event:

```
{"log_namespace": "twisted.internet.defer", "log_level": {"__class_uuid__": "02e59486-f24d-46ad-8224-3acdf2a5732a", "name": "critical"}, "log_logger": {"unpersistable": true}, "log_format": "Unhandled error in Deferred:", "log_time": 1490885744.731011, "log_source": null, "isError": true}
```

This frequently comes up several hundred times in a row.  This seems highly suspicious from a process which is doing very little work - eg, accepting one TCP connection and making one outgoing TCP connection every 15 seconds.  By a recent count, each such spurt of activity resulted in 283 of these log events.

Attachments:

* [errors.txt](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/929/929e178a707b35cd4c72f7921236615d60414309/be0b779e0b7cd9993dbc1388356ed232bf4abec6.txt) (81754 bytes) - added by exarkun on 2017-03-30 15:00:02Z - 

<details><summary>Searchable metadata</summary>

```
trac-id__9099 9099
type__defect defect
reporter__exarkun exarkun
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__duplicate duplicate
component__logger logger
keywords__None None
time__1490885981548776 1490885981548776
changetime__1497443641996476 1497443641996476
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

Perhaps related is this behavior, though this may also just be another bug:

```
from sys import stdout
from twisted.logger import textFileLogObserver, globalLogPublisher
from twisted.python.failure import Failure
from twisted.internet.defer import fail

def main():
    try:
        1 / 0
    except:
        f = Failure()
    d = fail(f)
    del d

if __name__ == "__main__":
    globalLogPublisher.addObserver(textFileLogObserver(stdout))
    main()
```

producing this output:

```
Unhandled error in Deferred:
2017-04-24T08:01:38-0400 [twisted.internet.defer#critical] Unhandled error in Deferred:

2017-04-24T08:01:38-0400 [twisted.internet.defer#critical] 
        Traceback (most recent call last):
          File "debugging.py", line 16, in <module>
            main()
        --- <exception caught here> ---
          File "debugging.py", line 8, in main
            1 / 0
        exceptions.ZeroDivisionError: integer division or modulo by zero
```

Notice the doubled "Unhandled error in Deferred" reporting - with one given some kind of logging prefix and the other lacking it.

If no observer is explicitly added to the global log publisher then the output changes to:

```
Unhandled error in Deferred:

```

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_2"></a>|@exarkun commented|
|-|-|

Or maybe that's not related at all.  The duplication appears to arise from the use of `globalLogPublisher.addObserver` instead of `globalLogBeginner.beginLoggingTo`.

This mistake brought to you by the backwards order of http://twistedmatrix.com/documents/current/core/howto/logger.html#the-global-log-publisher and http://twistedmatrix.com/documents/current/core/howto/logger.html#starting-the-global-log-publisher in the documentation (introducing `addObserver` first and then relying on folks to keep reading after they think they have the answer to find out that `beginLoggingTo` is actually the answer).

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_3"></a>|@exarkun set status to `closed`|
|-|-|

This seems to be a duplicate of a *two year old bug*!

[#7927](https://github.com/twisted/twisted/issues/7927)
