### ISSUE TITLE
Twisted.web.client fails on non-standard compliant domain names

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9112]
|[<img alt="pawelmhm's avatar" src="https://avatars.githubusercontent.com/u/2700942?s=50" width="50" height="50">](https://github.com/pawelmhm)| @pawelmhm reported|
|-|-|
|Trac ID|trac#9112|
|Type|defect|
|Created|2017-04-10 12:10:26Z|

I've got url with invalid domain name: `tjhughes_co_uk.secure-cdn.visualsoft.co.uk`. Domain name contains character '_' low line https://unicode-table.com/en/005F/ according to idna tables RFC 5892 this is disallowed in domain name for idna. 

https://www.iana.org/assignments/idna-tables-6.3.0/idna-tables-6.3.0.xml 

Twisted fails to make request for this url. Following code:

```python
from twisted.internet import reactor
from twisted.web.client import Agent
from twisted.web.http_headers import Headers

agent = Agent(reactor)
url = 'https://tjhughes_co_uk.secure-cdn.visualsoft.co.uk/images/4-pack-solar-path-finder-p6049-14413_image.jpg'

d = agent.request(
    'GET',
    url,
    Headers({'User-Agent': ['Twisted Web Client Example']}),
    None)

def cbResponse(ignored):
    print('Response received')

d.addCallback(cbResponse)

def cbShutdown(ignored):
    reactor.stop()

d.addBoth(cbShutdown)

reactor.run()

  ```

Fails with

```
Traceback (most recent call last):
  File "a.py", line 12, in <module>
    None)
  File "/home/pawel/prog_langs/py/dev_twisted/src/twisted/web/client.py", line 1625, in request
    endpoint = self._getEndpoint(parsedURI)
  File "/home/pawel/prog_langs/py/dev_twisted/src/twisted/web/client.py", line 1609, in _getEndpoint
    return self._endpointFactory.endpointForURI(uri)
  File "/home/pawel/prog_langs/py/dev_twisted/src/twisted/web/client.py", line 1486, in endpointForURI
    uri.port)
  File "/home/pawel/prog_langs/py/dev_twisted/src/twisted/web/client.py", line 929, in creatorForNetloc
    trustRoot=self._trustRoot)
  File "/home/pawel/prog_langs/py/dev_twisted/src/twisted/internet/_sslverify.py", line 1289, in optionsForClientTLS
    return ClientTLSOptions(hostname, certificateOptions.getContext())
  File "/home/pawel/prog_langs/py/dev_twisted/src/twisted/internet/_sslverify.py", line 1152, in __init__
    self._hostnameBytes = _idnaBytes(hostname)
  File "/home/pawel/prog_langs/py/dev_twisted/src/twisted/internet/_idna.py", line 30, in _idnaBytes
    return idna.encode(text)
  File "/home/pawel/prog_langs/py/idna/idna/core.py", line 355, in encode
    result.append(alabel(label))
  File "/home/pawel/prog_langs/py/idna/idna/core.py", line 265, in alabel
    raise IDNAError('The label {0} is not a valid A-label'.format(label))
idna.core.IDNAError: The label tjhughes_co_uk is not a valid A-label

```
Error comes from idna, which is called by:

https://github.com/twisted/twisted/blob/trunk/src/twisted/internet/_idna.py#L28 which is called from _sslverify

I noticed that website has also http version, and this is also failing but with different error, this time it fails on getHostName(). 

I think this is a bug because:

- Users may need to download invalid urls. Servers which are not standard compliant are bad, but people need to work with them.
- Other clients are not failing on this invalid domain name. I tested following clients and libraries: chrome browser, python-requests, curl, wget. They all download this image ok. 

<details><summary>Searchable metadata</summary>

```
trac-id__9112 9112
type__defect defect
reporter__pawelmhm pawelmhm
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__web web
keywords__None None
time__1491826226155902 1491826226155902
changetime__1492766264444899 1492766264444899
version__None None
owner__pawelmhm pawelmhm

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="pawelmhm's avatar" src="https://avatars.githubusercontent.com/u/2700942?s=50" width="50" height="50">](https://github.com/pawelmhm)|@pawelmhm set owner to @pawelmhm|
|-|-|
