### ISSUE TITLE
http.Request.getClientIP() fails for IPv6 clients, breaking twistd functionality

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9113]
|[<img alt="n-st's avatar" src="https://avatars.githubusercontent.com/u/2692085?s=50" width="50" height="50">](https://github.com/n-st)| @n-st reported|
|-|-|
|Trac ID|trac#9113|
|Type|defect|
|Created|2017-04-11 04:29:37Z|

`http.Request.getClientIP()` returns `None` when the client is connecting via IPv6, or the server is using IPv6-mapped IPv4 addresses.

This leads to a complete failure to perform (the HTTP client gets an error 500 and a stacktrace):
```
2017-04-11T05:57:18+0200 [_GenericHTTPChannelProtocol,0,2001:db8::206] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/local/lib/python3.4/dist-packages/twisted/protocols/basic.py", line 571, in dataReceived
	    why = self.lineReceived(line)
	  File "/usr/local/lib/python3.4/dist-packages/twisted/web/http.py", line 1811, in lineReceived
	    self.allContentReceived()
	  File "/usr/local/lib/python3.4/dist-packages/twisted/web/http.py", line 1906, in allContentReceived
	    req.requestReceived(command, path, version)
	  File "/usr/local/lib/python3.4/dist-packages/twisted/web/http.py", line 771, in requestReceived
	    self.process()
	--- <exception caught here> ---
	  File "/usr/local/lib/python3.4/dist-packages/twisted/web/server.py", line 190, in process
	    self.render(resrc)
	  File "/usr/local/lib/python3.4/dist-packages/twisted/web/server.py", line 241, in render
	    body = resrc.render(self)
	  File "/usr/local/lib/python3.4/dist-packages/twisted/web/wsgi.py", line 562, in render
	    self._reactor, self._threadpool, self._application, request)
	  File "/usr/local/lib/python3.4/dist-packages/twisted/web/wsgi.py", line 294, in __init__
	    'REMOTE_ADDR': _wsgiString(request.getClientIP()),
	  File "/usr/local/lib/python3.4/dist-packages/twisted/web/wsgi.py", line 85, in _wsgiString
	    return string.decode("iso-8859-1")
	builtins.AttributeError: 'NoneType' object has no attribute 'decode'
```

The reason is quite obvious: `twisted/web/http.py:1339` checks `isinstance(self.client, address.IPv4Address)`, so IPv6 addresses are of course rejected.

Not sure if we should check `address.IPv4Address` and `address.IPv6Address` separately, or go straight for `address._IPAddress`.

<details><summary>Searchable metadata</summary>

```
trac-id__9113 9113
type__defect defect
reporter__n_st n-st
priority__high high
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__duplicate duplicate
component__web web
keywords__ipv6 ipv6
time__1491884977885114 1491884977885114
changetime__1529901025729831 1529901025729831
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_1"></a>|@twm set status to `closed`|
|-|-|

Fixed in [#8241](https://github.com/twisted/twisted/issues/8241).
