### ISSUE TITLE
Twisted 17.1.0 tls fails on python 2.7.5 due missing OP_NO_TLSv1_1

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9121]
|[<img alt="noc0lour's avatar" src="https://avatars.githubusercontent.com/u/4438327?s=50" width="50" height="50">](https://github.com/noc0lour)| @noc0lour reported|
|-|-|
|Trac ID|trac#9121|
|Type|defect|
|Created|2017-04-25 17:36:24Z|

I'm trying to run a twisted application on a CentOS7 container with necessary deps installed.

All deps are istalled from the official CentOS7 repo
 - OpenSSL version: 1.0.1e
 - Python version: 2.7.5

If I downgrade to Twisted 16.0.0 everything works fine.

```python
[buildbot@86134cdfec09 buildbot]$ twistd -ny buildbot.tac 
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/twisted/application/app.py", line 662, in run
    runApp(config)
  File "/usr/lib64/python2.7/site-packages/twisted/scripts/twistd.py", line 25, in runApp
    _SomeApplicationRunner(config).run()
  File "/usr/lib64/python2.7/site-packages/twisted/application/app.py", line 380, in run
    self.application = self.createOrGetApplication()
  File "/usr/lib64/python2.7/site-packages/twisted/application/app.py", line 445, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/usr/lib64/python2.7/site-packages/twisted/application/app.py", line 456, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/usr/lib64/python2.7/site-packages/twisted/application/service.py", line 413, in loadApplication
    passphrase)
  File "/usr/lib64/python2.7/site-packages/twisted/persisted/sob.py", line 223, in loadValueFromFile
    eval(codeObj, d, d)
  File "buildbot.tac", line 9, in <module>
    from buildbot_worker.bot import Worker
  File "/usr/lib/python2.7/site-packages/buildbot_worker/bot.py", line 19, in <module>
    from buildbot_worker.null import LocalWorker
  File "/usr/lib/python2.7/site-packages/buildbot_worker/null.py", line 21, in <module>
    from buildbot_worker.base import WorkerBase
  File "/usr/lib/python2.7/site-packages/buildbot_worker/base.py", line 26, in <module>
    from twisted.internet import reactor
  File "/usr/lib64/python2.7/site-packages/twisted/internet/reactor.py", line 38, in <module>
    from twisted.internet import default
  File "/usr/lib64/python2.7/site-packages/twisted/internet/default.py", line 56, in <module>
    install = _getInstallFunction(platform)
  File "/usr/lib64/python2.7/site-packages/twisted/internet/default.py", line 44, in _getInstallFunction
    from twisted.internet.epollreactor import install
  File "/usr/lib64/python2.7/site-packages/twisted/internet/epollreactor.py", line 24, in <module>
    from twisted.internet import posixbase
  File "/usr/lib64/python2.7/site-packages/twisted/internet/posixbase.py", line 18, in <module>
    from twisted.internet import error, udp, tcp
  File "/usr/lib64/python2.7/site-packages/twisted/internet/tcp.py", line 28, in <module>
    from twisted.internet._newtls import (
  File "/usr/lib64/python2.7/site-packages/twisted/internet/_newtls.py", line 21, in <module>
    from twisted.protocols.tls import TLSMemoryBIOFactory, TLSMemoryBIOProtocol
  File "/usr/lib64/python2.7/site-packages/twisted/protocols/tls.py", line 63, in <module>
    from twisted.internet._sslverify import _setAcceptableProtocols
  File "/usr/lib64/python2.7/site-packages/twisted/internet/_sslverify.py", line 38, in <module>
    TLSVersion.TLSv1_1: SSL.OP_NO_TLSv1_1,
exceptions.AttributeError: 'module' object has no attribute 'OP_NO_TLSv1_1'


Failed to load application: 'module' object has no attribute 'OP_NO_TLSv1_1'

```

<details><summary>Searchable metadata</summary>

```
trac-id__9121 9121
type__defect defect
reporter__noc0lour noc0lour
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__None None
time__1493141784860374 1493141784860374
changetime__1495562062302269 1495562062302269
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

It's more likely this has to do with the version of OpenSSL or pyOpenSSL rather than the version of Python.  It's pyOpenSSL that exports this constant (from OpenSSL, via cryptography) for Twisted.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_2"></a>|@exarkun commented|
|-|-|

[#9123](https://github.com/twisted/twisted/issues/9123) was a duplicate of this.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_3"></a>|@exarkun commented|
|-|-|

See also:
  * [ticket:9115]
  * ​https://github.com/LeastAuthority/kubetop/issues/35
  * https://github.com/warner/magic-wormhole/issues/143
  * ​http://stackoverflow.com/search?q=%5Btwisted%5D+OP_NO_TLSv1_1

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_6"></a>|@glyph commented|
|-|-|

This should definitely be addressed in some way, but it doesn't rise to the level of a spot-fix regression; the error only occurs on unsupported versions of pyOpenSSL.  See discussion on [#9115](https://github.com/twisted/twisted/issues/9115) for more information.

In the meanwhile, `pip install twisted[tls]` will fix the problem for you, by telling `pip` that not only do you need Twisted installed, you need the bits of Twisted that can do TLS installed, which includes a recent-enough version of pyOpenSSL.
