### ISSUE TITLE
misuse of CertificateOptions initializer raises a ridiculous exception

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9125]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#9125|
|Type|defect|
|Created|2017-04-28 16:05:54Z|
|Branch|https://github.com/twisted/twisted/tree/9125-mutuallyExclusive-exception-text|

```
>>> from twisted import version
>>> version
Version('Twisted', 17, 1, 0, dev=0)
>>> from twisted.internet.ssl import CertificateOptions
>>> CertificateOptions(verify=True, trustRoot=object())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "twisted/src/twisted/python/deprecate.py", line 791, in wrapped
    raise TypeError("nope")
TypeError: nope
>>> 
```

This is a poor way to report conflicting arguments.

<details><summary>Searchable metadata</summary>

```
trac-id__9125 9125
type__defect defect
reporter__exarkun exarkun
priority__normal normal
milestone__None None
branch__9125_mutuallyExclusive_exception_text 9125-mutuallyExclusive-exception-text
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__None None
time__1493395554976359 1493395554976359
changetime__1542425296500378 1542425296500378
version__None None
owner__wiml wiml
cc__wiml
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="wiml's avatar" src="https://avatars.githubusercontent.com/u/156891?s=50" width="50" height="50">](https://github.com/wiml)<a name="note_1"></a>|@wiml commented|
|-|-|

A PR with a better exception message: https://github.com/twisted/twisted/pull/1087

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun set owner to @exarkun<br>@exarkun set status to `assigned`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun set owner to @wiml<br>@exarkun set status to `new`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="wiml's avatar" src="https://avatars.githubusercontent.com/u/156891?s=50" width="50" height="50">](https://github.com/wiml)<a name="note_4"></a>|@wiml set status to `closed`|
|-|-|

In changeset 98521f8771c68f04ddd9a1d3413825f7f1054e5f
```
#!CommitTicketReference repository="" revision="98521f8771c68f04ddd9a1d3413825f7f1054e5f"
Merge pull request #1087 from twisted/9125-mutuallyExclusive-exception-text

Author: wiml
Reviewer: exarkun
Fixes: ticket:9125

The @mutuallyExclusiveArguments decorator raises a more informative exception now.
```
