### ISSUE TITLE
UnauthorizedResource: broken on py3 with digest

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9127]
|[<img alt="tardyp's avatar" src="https://avatars.githubusercontent.com/u/109859?s=50" width="50" height="50">](https://github.com/tardyp)| @tardyp reported|
|-|-|
|Trac ID|trac#9127|
|Type|defect|
|Created|2017-04-30 13:37:15Z|

See buildbot bug https://github.com/buildbot/buildbot/issues/3162

reported by @aliceinwire on IRC

if auth is configured with:
```
c['www']['auth'] = util.UserPasswordAuth(usernames_passwords)
```
Got error in the logs
```
        Traceback (most recent call last):
          File "/root/buildbot/lib/python3.4/site-packages/twisted/web/_auth/wrapper.py", line 133, in render
            return self._authorizedResource(request).render(request)
          File "/root/buildbot/lib/python3.4/site-packages/twisted/web/util.py", line 138, in render
            self.d.addCallback(self._cbChild, request).addErrback(
          File "/root/buildbot/lib/python3.4/site-packages/twisted/internet/defer.py", line 321, in addCallback
            callbackKeywords=kw)
          File "/root/buildbot/lib/python3.4/site-packages/twisted/internet/defer.py", line 310, in addCallbacks
            self._runCallbacks()
        --- <exception caught here> ---
          File "/root/buildbot/lib/python3.4/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "/root/buildbot/lib/python3.4/site-packages/twisted/web/util.py", line 144, in _cbChild
            request.render(resource.getChildForRequest(child, request))
          File "/root/buildbot/lib/python3.4/site-packages/twisted/web/server.py", line 241, in render
            body = resrc.render(self)
          File "/root/buildbot/lib/python3.4/site-packages/twisted/web/_auth/wrapper.py", line 59, in render
            generateWWWAuthenticate(fact.scheme, challenge))
          File "/root/buildbot/lib/python3.4/site-packages/twisted/web/_auth/wrapper.py", line 48, in generateWWWAuthenticate
            l.append(networkString("%s=%s" % (k, quoteString(v))))
          File "/root/buildbot/lib/python3.4/site-packages/twisted/web/_auth/wrapper.py", line 52, in quoteString
            return '"%s"' % (s.replace('\\', '\\\\').replace('"', '\\"'),)
        builtins.TypeError: 'str' does not support the buffer interface
```

working on a fix..

<details><summary>Searchable metadata</summary>

```
trac-id__9127 9127
type__defect defect
reporter__tardyp tardyp
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__web web
keywords__None None
time__1493559435284141 1493559435284141
changetime__1496463965301134 1496463965301134
version__None None
owner__Craig_Rodrigues__rodrigc_____ Craig Rodrigues <rodrigc@...>

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="jsantos2's avatar" src="https://avatars.githubusercontent.com/u/28877519?s=50" width="50" height="50">](https://github.com/jsantos2)<a name="note_1"></a>|@jsantos2 commented|
|-|-|

[#8813](https://github.com/twisted/twisted/issues/8813) is encountering the same error at the same statement in web/_auth/wrapper.py, so may be a duplicate.

I'm encountering this error as well, in code that works fine in Python2.  I could fix it by brute force, but I have no idea what else in this module might be broken in Python 3.

I'm assuming if someone else is working on this, there would be some comment here (maybe?), so I'll just "+1" it for now, but if I have time and inclination to continue, I'll let you all know.

BTW, I've created tickets previously under the name "jsantos", but GitHub says that name is taken,as is jsantos1...

P.S.  After posting this comment, I noticed the "see buildbot bug" link above, where Tardyp posted a fix using "nativeString()"  Tried that and got further.  Thanks!

I'm still encountering string vs. bytes disease, but am not sure if it is in my code or Twisted yet :-(

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_2"></a>|@rodrigc set owner to @rodrigc<br>@rodrigc set status to `closed`|
|-|-|

In changeset eca6b4423fdab92583347d4a633e6866003a4220
```
#!CommitTicketReference repository="" revision="eca6b4423fdab92583347d4a633e6866003a4220"
Merge pull request #773 from tardyp/9127-tardyp-HTTPAuthSessionWrapper-py3-fix

http auth session wrapper py3 fix

Author: tardyp
Reviewers: rodrigc
Fixes: ticket:9127
```
