### ISSUE TITLE
Test failure in test_main.MainTests.test_twisted

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9133]
|[<img alt="mahmoud's avatar" src="https://avatars.githubusercontent.com/u/130193?s=50" width="50" height="50">](https://github.com/mahmoud)| @mahmoud reported|
|-|-|
|Trac ID|trac#9133|
|Type|defect|
|Created|2017-05-06 22:40:55Z|

Hi all,

On a brand new clone off of trunk (last commit id 0aef33642cbe), new virtualenv (CPython 2.7.12 on Ubuntu), with a pip install -e .[dev]. When I run "trial twisted", I see:

```
[FAIL]
Traceback (most recent call last):
  File "/home/mahmoud/projects/twisted/src/twisted/test/test_main.py", line 35, in processEnded
    self.assertEqual(output, message)
  File "/home/mahmoud/projects/twisted/src/twisted/trial/_synctest.py", line 432, in assertEqual
    super(_Assertions, self).assertEqual(first, second, msg)
  File "/usr/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python2.7/unittest/case.py", line 506, in _baseAssertEqual
    raise self.failureException(msg)
twisted.trial.unittest.FailTest: 'Usage: __main__.py [options] plugin [plugin_options]\nOptions:\n      --log-level=   Set default log level. (options: "debug", "info", "warn",\n                     "error", "critical"; default: "info")\n      --help         Display this help and exit.\n      --version      Print version and exit.\n      --log-format=  Log file format. (options: "text", "json"; default: "text"\n                     if the log file is a tty, otherwise "json")\n      --log-file=    Log to file. ("-" for stdout, "+" for stderr; default: "-")\n      --reactor=     The name of the reactor to use. (options: "cf", "win32",\n                     "gi", "kqueue", "poll", "iocp", "select", "epoll", "gtk2",\n                     "gtk3", "wx", "default", "glib2", "asyncio")\nCommands:\n    conch            A Conch SSH service.\n    dns              A domain name server.\n    ftp              An FTP server.\n    inetd            An inetd(8) replacement.\n    mail             An email service\n    manhole          An interactive remote debugger service accessible via\n                     telnet and ssh and providing syntax coloring and basic line\n                     editing functionality.\n    news             A news server.\n    portforward      A simple port-forwarder.\n    procmon          A process watchdog / supervisor\n    socks            A SOCKSv4 proxy service.\n    web              A general-purpose web server which can serve from a\n                     filesystem or application resource.\n    words            A modern words server\n    xmpp-router      An XMPP Router server\n\n' != 'Usage: trial [options] plugin [plugin_options]\nOptions:\n      --log-level=   Set default log level. (options: "debug", "info", "warn",\n                     "error", "critical"; default: "info")\n      --help         Display this help and exit.\n      --version      Print version and exit.\n      --log-format=  Log file format. (options: "text", "json"; default: "text"\n                     if the log file is a tty, otherwise "json")\n      --log-file=    Log to file. ("-" for stdout, "+" for stderr; default: "-")\n      --reactor=     The name of the reactor to use. (options: "cf", "win32",\n                     "gi", "kqueue", "poll", "iocp", "select", "epoll", "gtk2",\n                     "gtk3", "wx", "default", "glib2", "asyncio")\nCommands:\n    conch            A Conch SSH service.\n    dns              A domain name server.\n    ftp              An FTP server.\n    inetd            An inetd(8) replacement.\n    mail             An email service\n    manhole          An interactive remote debugger service accessible via\n                     telnet and ssh and providing syntax coloring and basic line\n                     editing functionality.\n    news             A news server.\n    portforward      A simple port-forwarder.\n    procmon          A process watchdog / supervisor\n    socks            A SOCKSv4 proxy service.\n    web              A general-purpose web server which can serve from a\n                     filesystem or application resource.\n    words            A modern words server\n    xmpp-router      An XMPP Router server\n\n'

twisted.test.test_main.MainTests.test_twisted
-------------------------------------------------------------------------------
Ran 11898 tests in 75.680s

FAILED (skips=3132, failures=1, successes=8765)
```

This is the only failure. Looks like a mismatch between what twisted's ```__main__.py``` outputs and what ```TwistOptions()``` generates.

<details><summary>Searchable metadata</summary>

```
trac-id__9133 9133
type__defect defect
reporter__mahmoud mahmoud
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__None None
time__1494110455813745 1494110455813745
changetime__1551119500222992 1551119500222992
version__None None
owner__Amber_Brown__hawkowl_____ Amber Brown <hawkowl@...>

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_2"></a>|@markrwilliams commented|
|-|-|

The test passes with `python -m trial`.  That's because `t.p.usage.Options.getSynposis` [depends on](https://github.com/twisted/twisted/blob/0aef33642cbe04cac558a4aaceeb2a6a03de403b/src/twisted/python/usage.py#L455) `sys.argv[0]`, and `runpy` [rewrites this](https://github.com/python/cpython/blob/3763ea865cee5bbabcce11cd577811135e0fc747/Lib/runpy.py#L190-L191) to be `somepackage/__main__.py` when you run `python -m somepackage`.

The failing test [compares the output of](https://github.com/twisted/twisted/blob/0aef33642cbe04cac558a4aaceeb2a6a03de403b/src/twisted/test/test_main.py#L26) `python -m twisted` to `str(TwistOptions())`.  It's clear that the former will _always_ start with `__main__.py`, while the latter will start with `__main__.py` only if the user's invoked `trial` with `python -m trial`.

The fix is to either exclude the first line of the options output from comparison, or to remove the dependency on `sys.argv[0]`.

**Comment by twisted-trac** [comment]
|[<img alt="svvitale's avatar" src="https://avatars.githubusercontent.com/u/137162?s=50" width="50" height="50">](https://github.com/svvitale)|@svvitale set owner to @svvitale<br>@svvitale set status to `assigned`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="svvitale's avatar" src="https://avatars.githubusercontent.com/u/137162?s=50" width="50" height="50">](https://github.com/svvitale)<a name="note_5"></a>|@svvitale commented|
|-|-|

Fixed in PR 794 https://github.com/twisted/twisted/pull/794

**Comment by twisted-trac** [comment]
|[<img alt="svvitale's avatar" src="https://avatars.githubusercontent.com/u/137162?s=50" width="50" height="50">](https://github.com/svvitale)|@svvitale set status to `closed`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="svvitale's avatar" src="https://avatars.githubusercontent.com/u/137162?s=50" width="50" height="50">](https://github.com/svvitale)|@svvitale set status to `reopened`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="svvitale's avatar" src="https://avatars.githubusercontent.com/u/137162?s=50" width="50" height="50">](https://github.com/svvitale)|@svvitale removed owner<br>@svvitale set status to `new`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_9"></a>|@hawkowl commented|
|-|-|

PR looks good to me, and glyph had a look as well.

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_10"></a>|@hawkowl set owner to @hawkowl<br>@hawkowl set status to `closed`|
|-|-|

In changeset 45c7df42b4ac15810f51f7db87799818252cae02
```
#!CommitTicketReference repository="" revision="45c7df42b4ac15810f51f7db87799818252cae02"
Merge 9133-make-usage-synopsis-consistent: Make usage synopsis accurate and consistent when running twisted or twisted.trial with `python -m`

Author: svvitale
Reviewers: hawkowl, glyph
Fixes: ticket:9133
```

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_11"></a>|@exarkun commented|
|-|-|

Tahoe carefully constructs its `subCommands` in a particular order for an improved user experience.  This change throws that careful construction in the trash and replaces it with something confusing and bad.  For what it's worth.

Probably doesn't really matter.  It's not clear anyone even noticed in the 21 months since this landed.
