### ISSUE TITLE
Wrong Set-Cookie header causes a traceback in Twisted

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9136]
|[<img alt="itshane's avatar" src="https://avatars.githubusercontent.com/u/1818322?s=50" width="50" height="50">](https://github.com/itshane)| @itshane reported|
|-|-|
|Trac ID|trac#9136|
|Type|defect|
|Created|2017-05-15 08:06:56Z|

When the Set-Cookie header comes as a list which just contains the following "HttpOnly;Secure" string, it causes a "exceptions.ValueError: need more than 1 value to unpack" traceback.

```
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()
  File "/usr/lib/python2.7/site-packages/twisted/internet/tcp.py", line 209, in doRead
    return self._dataReceived(data)
  File "/usr/lib/python2.7/site-packages/twisted/internet/tcp.py", line 215, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/usr/lib/python2.7/site-packages/twisted/protocols/tls.py", line 422, in dataReceived
    self._flushReceiveBIO()
  File "/usr/lib/python2.7/site-packages/twisted/protocols/tls.py", line 392, in _flushReceiveBIO
    ProtocolWrapper.dataReceived(self, bytes)
  File "/usr/lib/python2.7/site-packages/twisted/protocols/policies.py", line 120, in dataReceived
    self.wrappedProtocol.dataReceived(data)
  File "/usr/lib/python2.7/site-packages/twisted/protocols/basic.py", line 571, in dataReceived
    why = self.lineReceived(line)
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 459, in lineReceived
    self.handleEndHeaders()
  File "/usr/lib/python2.7/site-packages/twisted/web/client.py", line 144, in handleEndHeaders
    self.factory.gotHeaders(self.headers)
  File "/usr/lib/python2.7/site-packages/twisted/web/client.py", line 420, in gotHeaders
    k, v = cook.split(b'=', 1)
exceptions.ValueError: need more than 1 value to unpack
```

It would be better just to omit the wrong part of the header, therefore, a response can be gracefully processed.

<details><summary>Searchable metadata</summary>

```
trac-id__9136 9136
type__defect defect
reporter__itshane itshane
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__web web
keywords__None None
time__1494835616649140 1494835616649140
changetime__1502610226137736 1502610226137736
version__None None
owner__itshane itshane

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_1"></a>|@adiroiban commented|
|-|-|

The PR is at https://github.com/twisted/twisted/pull/778

**Comment by twisted-trac** [comment]
|[<img alt="Lukasa's avatar" src="https://avatars.githubusercontent.com/u/1382556?s=50" width="50" height="50">](https://github.com/Lukasa)<a name="note_3"></a>|@Lukasa set owner to @itshane|
|-|-|

Reviewed on GitHub. No major notes, one correctness-of-documentation concern.

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_4"></a>|@rodrigc set status to `closed`|
|-|-|

In changeset 1dc8a45a0ee3e65c8172999d18846867425100ce
```
#!CommitTicketReference repository="" revision="1dc8a45a0ee3e65c8172999d18846867425100ce"
Merge pull request #778 from itshane/feature/set-cookie

Author: itshane
Reviewer: Lukasa, rodrigc
Fixes: ticket:9136 

Skip parsing of cookie headers which don't have an '='
```
