### ISSUE TITLE
IPv6 tests should be skipped on systems without IPv6 support.

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9144]
|[<img alt="Lukasa's avatar" src="https://avatars.githubusercontent.com/u/1382556?s=50" width="50" height="50">](https://github.com/Lukasa)| @Lukasa reported|
|-|-|
|Trac ID|trac#9144|
|Type|defect|
|Created|2017-05-22 18:07:03Z|

When you run trial against the twisted codebase on a system without IPv6 support, all kinds of horrifying stuff happens:

```
[ERROR]
Traceback (most recent call last):
  File "/twisted/src/twisted/conch/test/test_conch.py", line 349, in setUp
    self.echoServerV6 = reactor.listenTCP(0, EchoFactory(), interface="::1")
  File "/twisted/src/twisted/internet/posixbase.py", line 478, in listenTCP
    p.startListening()
  File "/twisted/src/twisted/internet/tcp.py", line 983, in startListening
    raise CannotListenError(self.interface, self.port, le)
twisted.internet.error.CannotListenError: Couldn't listen on ::1:0: [Errno 99] Cannot assign requested address.

twisted.conch.test.test_conch.CmdLineClientTests.test_exec
twisted.conch.test.test_conch.CmdLineClientTests.test_localToRemoteForwarding
twisted.conch.test.test_conch.CmdLineClientTests.test_remoteToLocalForwarding
twisted.conch.test.test_conch.CmdLineClientTests.test_runWithLogFile
twisted.conch.test.test_conch.CmdLineClientTests.test_runWithNoHostAlgorithmsSpecified
twisted.conch.test.test_conch.OpenSSHClientForwardingTests.test_exec
twisted.conch.test.test_conch.OpenSSHClientForwardingTests.test_localToRemoteForwarding
twisted.conch.test.test_conch.OpenSSHClientForwardingTests.test_localToRemoteForwardingV6
twisted.conch.test.test_conch.OpenSSHClientForwardingTests.test_remoteToLocalForwarding
twisted.conch.test.test_conch.OpenSSHClientRekeyTests.test_clientRekey
twisted.conch.test.test_conch.OpenSSHKeyExchangeTests.test_DH_GROUP14
twisted.conch.test.test_conch.OpenSSHKeyExchangeTests.test_DH_GROUP_EXCHANGE_SHA1
twisted.conch.test.test_conch.OpenSSHKeyExchangeTests.test_DH_GROUP_EXCHANGE_SHA256
twisted.conch.test.test_conch.OpenSSHKeyExchangeTests.test_ECDHSHA256
twisted.conch.test.test_conch.OpenSSHKeyExchangeTests.test_ECDHSHA384
twisted.conch.test.test_conch.OpenSSHKeyExchangeTests.test_ECDHSHA521
twisted.conch.test.test_conch.OpenSSHKeyExchangeTests.test_unsupported_algorithm
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/twisted/src/twisted/internet/test/test_tcp.py", line 1132, in test_buildProtocolIPv6Address
    observedAddress = self._buildProtocolAddressTest(client, interface)
  File "/twisted/src/twisted/internet/test/test_tcp.py", line 1100, in _buildProtocolAddressTest
    port = self.getListeningPort(reactor, factory, 0, interface)
  File "/twisted/src/twisted/internet/test/test_tcp.py", line 988, in getListeningPort
    portSock.bind(address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 99] Cannot assign requested address

twisted.internet.test.test_tcp.TCPFDPortTestsBuilder_EPollReactorTests.test_buildProtocolIPv6Address
twisted.internet.test.test_tcp.TCPFDPortTestsBuilder_PollReactorTests.test_buildProtocolIPv6Address
twisted.internet.test.test_tcp.TCPFDPortTestsBuilder_SelectReactorTests.test_buildProtocolIPv6Address
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/twisted/src/twisted/internet/test/test_tcp.py", line 1046, in test_portGetHostOnIPv6
    family=socket.AF_INET6, interface='::1')[:2]
  File "/twisted/src/twisted/internet/test/connectionmixins.py", line 48, in findFreePort
    probe.bind(addr)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 99] Cannot assign requested address

twisted.internet.test.test_tcp.TCPFDPortTestsBuilder_EPollReactorTests.test_portGetHostOnIPv6
twisted.internet.test.test_tcp.TCPFDPortTestsBuilder_PollReactorTests.test_portGetHostOnIPv6
twisted.internet.test.test_tcp.TCPFDPortTestsBuilder_SelectReactorTests.test_portGetHostOnIPv6
twisted.internet.test.test_tcp.TCPPortTestsBuilder_EPollReactorTests.test_portGetHostOnIPv6
twisted.internet.test.test_tcp.TCPPortTestsBuilder_PollReactorTests.test_portGetHostOnIPv6
twisted.internet.test.test_tcp.TCPPortTestsBuilder_SelectReactorTests.test_portGetHostOnIPv6
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/twisted/src/twisted/internet/test/test_tcp.py", line 1215, in test_serverGetHostOnIPv6
    client, interface, 'getHost')
  File "/twisted/src/twisted/internet/test/test_tcp.py", line 1182, in _serverGetConnectionAddressTest
    port = self.getListeningPort(reactor, factory, 0, interface)
  File "/twisted/src/twisted/internet/test/test_tcp.py", line 988, in getListeningPort
    portSock.bind(address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 99] Cannot assign requested address

twisted.internet.test.test_tcp.TCPFDPortTestsBuilder_EPollReactorTests.test_serverGetHostOnIPv6
twisted.internet.test.test_tcp.TCPFDPortTestsBuilder_PollReactorTests.test_serverGetHostOnIPv6
twisted.internet.test.test_tcp.TCPFDPortTestsBuilder_SelectReactorTests.test_serverGetHostOnIPv6
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/twisted/src/twisted/internet/test/test_tcp.py", line 1262, in test_serverGetPeerOnIPv6
    client, interface, 'getPeer')
  File "/twisted/src/twisted/internet/test/test_tcp.py", line 1182, in _serverGetConnectionAddressTest
    port = self.getListeningPort(reactor, factory, 0, interface)
  File "/twisted/src/twisted/internet/test/test_tcp.py", line 988, in getListeningPort
    portSock.bind(address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 99] Cannot assign requested address

twisted.internet.test.test_tcp.TCPFDPortTestsBuilder_EPollReactorTests.test_serverGetPeerOnIPv6
twisted.internet.test.test_tcp.TCPFDPortTestsBuilder_PollReactorTests.test_serverGetPeerOnIPv6
twisted.internet.test.test_tcp.TCPFDPortTestsBuilder_SelectReactorTests.test_serverGetPeerOnIPv6
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/twisted/src/twisted/internet/test/test_tcp.py", line 1132, in test_buildProtocolIPv6Address
    observedAddress = self._buildProtocolAddressTest(client, interface)
  File "/twisted/src/twisted/internet/test/test_tcp.py", line 1100, in _buildProtocolAddressTest
    port = self.getListeningPort(reactor, factory, 0, interface)
  File "/twisted/src/twisted/internet/test/test_tcp.py", line 966, in getListeningPort
    return reactor.listenTCP(port, factory, interface=interface)
  File "/twisted/src/twisted/internet/posixbase.py", line 478, in listenTCP
    p.startListening()
  File "/twisted/src/twisted/internet/tcp.py", line 983, in startListening
    raise CannotListenError(self.interface, self.port, le)
twisted.internet.error.CannotListenError: Couldn't listen on ::1:0: [Errno 99] Cannot assign requested address.

twisted.internet.test.test_tcp.TCPPortTestsBuilder_EPollReactorTests.test_buildProtocolIPv6Address
twisted.internet.test.test_tcp.TCPPortTestsBuilder_PollReactorTests.test_buildProtocolIPv6Address
twisted.internet.test.test_tcp.TCPPortTestsBuilder_SelectReactorTests.test_buildProtocolIPv6Address
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/twisted/src/twisted/internet/test/test_tcp.py", line 1215, in test_serverGetHostOnIPv6
    client, interface, 'getHost')
  File "/twisted/src/twisted/internet/test/test_tcp.py", line 1182, in _serverGetConnectionAddressTest
    port = self.getListeningPort(reactor, factory, 0, interface)
  File "/twisted/src/twisted/internet/test/test_tcp.py", line 966, in getListeningPort
    return reactor.listenTCP(port, factory, interface=interface)
  File "/twisted/src/twisted/internet/posixbase.py", line 478, in listenTCP
    p.startListening()
  File "/twisted/src/twisted/internet/tcp.py", line 983, in startListening
    raise CannotListenError(self.interface, self.port, le)
twisted.internet.error.CannotListenError: Couldn't listen on ::1:0: [Errno 99] Cannot assign requested address.

twisted.internet.test.test_tcp.TCPPortTestsBuilder_EPollReactorTests.test_serverGetHostOnIPv6
twisted.internet.test.test_tcp.TCPPortTestsBuilder_PollReactorTests.test_serverGetHostOnIPv6
twisted.internet.test.test_tcp.TCPPortTestsBuilder_SelectReactorTests.test_serverGetHostOnIPv6
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/twisted/src/twisted/internet/test/test_tcp.py", line 1262, in test_serverGetPeerOnIPv6
    client, interface, 'getPeer')
  File "/twisted/src/twisted/internet/test/test_tcp.py", line 1182, in _serverGetConnectionAddressTest
    port = self.getListeningPort(reactor, factory, 0, interface)
  File "/twisted/src/twisted/internet/test/test_tcp.py", line 966, in getListeningPort
    return reactor.listenTCP(port, factory, interface=interface)
  File "/twisted/src/twisted/internet/posixbase.py", line 478, in listenTCP
    p.startListening()
  File "/twisted/src/twisted/internet/tcp.py", line 983, in startListening
    raise CannotListenError(self.interface, self.port, le)
twisted.internet.error.CannotListenError: Couldn't listen on ::1:0: [Errno 99] Cannot assign requested address.

twisted.internet.test.test_tcp.TCPPortTestsBuilder_EPollReactorTests.test_serverGetPeerOnIPv6
twisted.internet.test.test_tcp.TCPPortTestsBuilder_PollReactorTests.test_serverGetPeerOnIPv6
twisted.internet.test.test_tcp.TCPPortTestsBuilder_SelectReactorTests.test_serverGetPeerOnIPv6
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/twisted/src/twisted/internet/test/test_udp.py", line 303, in test_connectedWriteToIPv6Interface
    self.getListeningPort(reactor, server, interface="::1")
  File "/twisted/src/twisted/internet/test/test_udp.py", line 465, in getListeningPort
    portSock.bind(address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 99] Cannot assign requested address

twisted.internet.test.test_udp.UDPFDServerTestsBuilder_EPollReactorTests.test_connectedWriteToIPv6Interface
twisted.internet.test.test_udp.UDPFDServerTestsBuilder_PollReactorTests.test_connectedWriteToIPv6Interface
twisted.internet.test.test_udp.UDPFDServerTestsBuilder_SelectReactorTests.test_connectedWriteToIPv6Interface
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/twisted/src/twisted/internet/test/test_udp.py", line 151, in test_getHostIPv6
    reactor, DatagramProtocol(), interface='::1')
  File "/twisted/src/twisted/internet/test/test_udp.py", line 465, in getListeningPort
    portSock.bind(address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 99] Cannot assign requested address

twisted.internet.test.test_udp.UDPFDServerTestsBuilder_EPollReactorTests.test_getHostIPv6
twisted.internet.test.test_udp.UDPFDServerTestsBuilder_PollReactorTests.test_getHostIPv6
twisted.internet.test.test_udp.UDPFDServerTestsBuilder_SelectReactorTests.test_getHostIPv6
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/twisted/src/twisted/internet/test/test_udp.py", line 256, in test_writeToIPv6Interface
    self.getListeningPort(reactor, server, interface="::1")
  File "/twisted/src/twisted/internet/test/test_udp.py", line 465, in getListeningPort
    portSock.bind(address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 99] Cannot assign requested address

twisted.internet.test.test_udp.UDPFDServerTestsBuilder_EPollReactorTests.test_writeToIPv6Interface
twisted.internet.test.test_udp.UDPFDServerTestsBuilder_PollReactorTests.test_writeToIPv6Interface
twisted.internet.test.test_udp.UDPFDServerTestsBuilder_SelectReactorTests.test_writeToIPv6Interface
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/twisted/src/twisted/internet/test/test_udp.py", line 375, in test_writingToIPv4OnIPv6RaisesInvalidAddressError
    reactor, DatagramProtocol(), interface="::1")
  File "/twisted/src/twisted/internet/test/test_udp.py", line 465, in getListeningPort
    portSock.bind(address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 99] Cannot assign requested address

twisted.internet.test.test_udp.UDPFDServerTestsBuilder_EPollReactorTests.test_writingToIPv4OnIPv6RaisesInvalidAddressError
twisted.internet.test.test_udp.UDPFDServerTestsBuilder_PollReactorTests.test_writingToIPv4OnIPv6RaisesInvalidAddressError
twisted.internet.test.test_udp.UDPFDServerTestsBuilder_SelectReactorTests.test_writingToIPv4OnIPv6RaisesInvalidAddressError
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/twisted/src/twisted/internet/test/test_udp.py", line 303, in test_connectedWriteToIPv6Interface
    self.getListeningPort(reactor, server, interface="::1")
  File "/twisted/src/twisted/internet/test/test_udp.py", line 424, in getListeningPort
    maxPacketSize=maxPacketSize)
  File "/twisted/src/twisted/internet/posixbase.py", line 369, in listenUDP
    p.startListening()
  File "/twisted/src/twisted/internet/udp.py", line 178, in startListening
    self._bindSocket()
  File "/twisted/src/twisted/internet/udp.py", line 198, in _bindSocket
    raise error.CannotListenError(self.interface, self.port, le)
twisted.internet.error.CannotListenError: Couldn't listen on ::1:0: [Errno 99] Cannot assign requested address.

twisted.internet.test.test_udp.UDPServerTestsBuilder_EPollReactorTests.test_connectedWriteToIPv6Interface
twisted.internet.test.test_udp.UDPServerTestsBuilder_PollReactorTests.test_connectedWriteToIPv6Interface
twisted.internet.test.test_udp.UDPServerTestsBuilder_SelectReactorTests.test_connectedWriteToIPv6Interface
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/twisted/src/twisted/internet/test/test_udp.py", line 151, in test_getHostIPv6
    reactor, DatagramProtocol(), interface='::1')
  File "/twisted/src/twisted/internet/test/test_udp.py", line 424, in getListeningPort
    maxPacketSize=maxPacketSize)
  File "/twisted/src/twisted/internet/posixbase.py", line 369, in listenUDP
    p.startListening()
  File "/twisted/src/twisted/internet/udp.py", line 178, in startListening
    self._bindSocket()
  File "/twisted/src/twisted/internet/udp.py", line 198, in _bindSocket
    raise error.CannotListenError(self.interface, self.port, le)
twisted.internet.error.CannotListenError: Couldn't listen on ::1:0: [Errno 99] Cannot assign requested address.

twisted.internet.test.test_udp.UDPServerTestsBuilder_EPollReactorTests.test_getHostIPv6
twisted.internet.test.test_udp.UDPServerTestsBuilder_PollReactorTests.test_getHostIPv6
twisted.internet.test.test_udp.UDPServerTestsBuilder_SelectReactorTests.test_getHostIPv6
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/twisted/src/twisted/internet/test/test_udp.py", line 256, in test_writeToIPv6Interface
    self.getListeningPort(reactor, server, interface="::1")
  File "/twisted/src/twisted/internet/test/test_udp.py", line 424, in getListeningPort
    maxPacketSize=maxPacketSize)
  File "/twisted/src/twisted/internet/posixbase.py", line 369, in listenUDP
    p.startListening()
  File "/twisted/src/twisted/internet/udp.py", line 178, in startListening
    self._bindSocket()
  File "/twisted/src/twisted/internet/udp.py", line 198, in _bindSocket
    raise error.CannotListenError(self.interface, self.port, le)
twisted.internet.error.CannotListenError: Couldn't listen on ::1:0: [Errno 99] Cannot assign requested address.

twisted.internet.test.test_udp.UDPServerTestsBuilder_EPollReactorTests.test_writeToIPv6Interface
twisted.internet.test.test_udp.UDPServerTestsBuilder_PollReactorTests.test_writeToIPv6Interface
twisted.internet.test.test_udp.UDPServerTestsBuilder_SelectReactorTests.test_writeToIPv6Interface
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/twisted/src/twisted/internet/test/test_udp.py", line 375, in test_writingToIPv4OnIPv6RaisesInvalidAddressError
    reactor, DatagramProtocol(), interface="::1")
  File "/twisted/src/twisted/internet/test/test_udp.py", line 424, in getListeningPort
    maxPacketSize=maxPacketSize)
  File "/twisted/src/twisted/internet/posixbase.py", line 369, in listenUDP
    p.startListening()
  File "/twisted/src/twisted/internet/udp.py", line 178, in startListening
    self._bindSocket()
  File "/twisted/src/twisted/internet/udp.py", line 198, in _bindSocket
    raise error.CannotListenError(self.interface, self.port, le)
twisted.internet.error.CannotListenError: Couldn't listen on ::1:0: [Errno 99] Cannot assign requested address.

twisted.internet.test.test_udp.UDPServerTestsBuilder_EPollReactorTests.test_writingToIPv4OnIPv6RaisesInvalidAddressError
twisted.internet.test.test_udp.UDPServerTestsBuilder_PollReactorTests.test_writingToIPv4OnIPv6RaisesInvalidAddressError
twisted.internet.test.test_udp.UDPServerTestsBuilder_SelectReactorTests.test_writingToIPv4OnIPv6RaisesInvalidAddressError
```

All of these tests should either be forced to use the IPv4 loopback address, or skipped on systems without IPv6 support (that is, where no IPv6 loopback address is present).

<details><summary>Searchable metadata</summary>

```
trac-id__9144 9144
type__defect defect
reporter__Lukasa Lukasa
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__None None
time__1495476423010133 1495476423010133
changetime__1495497379691690 1495497379691690
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="Lukasa's avatar" src="https://avatars.githubusercontent.com/u/1382556?s=50" width="50" height="50">](https://github.com/Lukasa)<a name="note_1"></a>|@Lukasa commented|
|-|-|

Basically it turns out we don't have a builder that does not support IPv6. While this says all kinds of great things about the support of IPv6 in the world, we don't explicitly require IPv6 support to use Twisted so that's not really super-sustainable.

**Comment by twisted-trac** [comment]
|[<img alt="Lukasa's avatar" src="https://avatars.githubusercontent.com/u/1382556?s=50" width="50" height="50">](https://github.com/Lukasa)|@Lukasa set status to `closed`|
|-|-|
