### ISSUE TITLE
'NoneType' object has no attribute '_producer'

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9156]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)| @glyph reported|
|-|-|
|Trac ID|trac#9156|
|Type|defect|
|Created|2017-06-02 07:02:17Z|
|Branch|https://github.com/twisted/twisted/tree/9156-lukasa-double-unregister|

Seen with alarming regularity on the production twistedmatrix.com webserver:

```
2017-06-02 00:57:48-0600 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/srv/t-web/virtualenv/site-packages/twisted/application/app.py", line 396, in startReactor
	    self.config, oldstdout, oldstderr, self.profiler, reactor)
	  File "/srv/t-web/virtualenv/site-packages/twisted/application/app.py", line 311, in runReactorWithLogging
	    reactor.run()
	  File "/srv/t-web/virtualenv/site-packages/twisted/internet/base.py", line 1243, in run
	    self.mainLoop()
	  File "/srv/t-web/virtualenv/site-packages/twisted/internet/base.py", line 1252, in mainLoop
	    self.runUntilCurrent()
	--- <exception caught here> ---
	  File "/srv/t-web/virtualenv/site-packages/twisted/internet/base.py", line 878, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/srv/t-web/virtualenv/site-packages/twisted/protocols/policies.py", line 735, in __timedOut
	    self.timeoutConnection()
	  File "/srv/t-web/virtualenv/site-packages/twisted/web/http.py", line 2009, in timeoutConnection
	    self.loseConnection()
	  File "/srv/t-web/virtualenv/site-packages/twisted/web/http.py", line 2109, in loseConnection
	    self._networkProducer.unregisterProducer()
	  File "/srv/t-web/virtualenv/site-packages/twisted/protocols/tls.py", line 610, in unregisterProducer
	    if isinstance(self._producer._producer, _PullToPush):
	exceptions.AttributeError: 'NoneType' object has no attribute '_producer'
```

<details><summary>Searchable metadata</summary>

```
trac-id__9156 9156
type__defect defect
reporter__glyph glyph
priority__normal normal
milestone__None None
branch__9156_lukasa_double_unregister 9156-lukasa-double-unregister
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__None None
time__1496386937788435 1496386937788435
changetime__1497187360250383 1497187360250383
version__None None
owner__Lukasa Lukasa

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_1"></a>|@glyph set owner to @Lukasa|
|-|-|

Assigning to Cory because if it isn't his fault then he knows whose fault it is.

**Comment by twisted-trac** [comment]
|[<img alt="Lukasa's avatar" src="https://avatars.githubusercontent.com/u/1382556?s=50" width="50" height="50">](https://github.com/Lukasa)<a name="note_2"></a>|@Lukasa commented|
|-|-|

Looks a lot like my fault.

**Comment by twisted-trac** [comment]
|[<img alt="Lukasa's avatar" src="https://avatars.githubusercontent.com/u/1382556?s=50" width="50" height="50">](https://github.com/Lukasa)<a name="note_3"></a>|@Lukasa commented|
|-|-|

This error occurs if the producer is *already* unregistered when we call unregisterProducer. Is it supposed to be safe to call unregisterProducer twice? Probably there's no guarantee there.

**Comment by twisted-trac** [comment]
|[<img alt="Lukasa's avatar" src="https://avatars.githubusercontent.com/u/1382556?s=50" width="50" height="50">](https://github.com/Lukasa)<a name="note_4"></a>|@Lukasa commented|
|-|-|

Hrm, ok. So it seems to be the case then that if t.w.h.HTTPChannel.loseConnection is called *twice*, or if it's called before t.w.h.HTTPChannel.connectionMade, then we would hit this problem. Let me see if I can reproduce locally.

**Comment by twisted-trac** [comment]
|[<img alt="Lukasa's avatar" src="https://avatars.githubusercontent.com/u/1382556?s=50" width="50" height="50">](https://github.com/Lukasa)<a name="note_5"></a>|@Lukasa commented|
|-|-|

Hrm, ok so the most basic test (use Requests with a Session) doesn't reproduce the error. Seems to be fine. I wonder what's going on there.

**Comment by twisted-trac** [comment]
|[<img alt="Lukasa's avatar" src="https://avatars.githubusercontent.com/u/1382556?s=50" width="50" height="50">](https://github.com/Lukasa)<a name="note_6"></a>|@Lukasa commented|
|-|-|

The next most basic test (open in Chrome/Safari/Firefox) also gives us nothing. Chrome eventually times out and hits a separate traceback in aborting (I'll tackle that soon as well), Safari never times out (presumably closing the connection itself), Firefox times out but doesn't hit the follow-on problem that Chrome does.

**Comment by twisted-trac** [comment]
|[<img alt="Lukasa's avatar" src="https://avatars.githubusercontent.com/u/1382556?s=50" width="50" height="50">](https://github.com/Lukasa)<a name="note_7"></a>|@Lukasa commented|
|-|-|

Can't reproduce this by closing the tabs either. Hrm. This seems to be very, very difficult to repro with just a vanilla "serve these static files" page.

Regardless, the goal should probably be to make sure we only unregister ourselves once, so I can write a test that confirms that and then merge it.

**Comment by twisted-trac** [comment]
|[<img alt="Lukasa's avatar" src="https://avatars.githubusercontent.com/u/1382556?s=50" width="50" height="50">](https://github.com/Lukasa)<a name="note_8"></a>|@Lukasa commented|
|-|-|

Actually, no. abstract.FileDescriptor allows unregistering of producers when no producer is registered, so we should let that be our guide and just allow double-unregister.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_9"></a>|@glyph commented|
|-|-|

The server in question here does quite a bit of reverse proxying; perhaps putting that into the mix would help you reproduce in a test integration environment?

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_10"></a>|@glyph commented|
|-|-|

(Worth noting: reverse proxying -> lots and lots of registering / unregistering of producers)

**Comment by twisted-trac** [comment]
|[<img alt="Lukasa's avatar" src="https://avatars.githubusercontent.com/u/1382556?s=50" width="50" height="50">](https://github.com/Lukasa)<a name="note_11"></a>|@Lukasa removed owner|
|-|-|

Ok, here's a proposed fix: https://github.com/twisted/twisted/pull/799

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_12"></a>|@hawkowl set owner to @hawkowl|
|-|-|

Looks fine to me.

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_13"></a>|@hawkowl set owner to @Lukasa|
|-|-|

Merged trunk in, land it when they go green.

**Comment by twisted-trac** [comment]
|[<img alt="Lukasa's avatar" src="https://avatars.githubusercontent.com/u/1382556?s=50" width="50" height="50">](https://github.com/Lukasa)|@Lukasa set status to `closed`|
|-|-|
