### ISSUE TITLE
AlreadyCalled error when timing out unresponsive HTTPS client.

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9157]
|[<img alt="Lukasa's avatar" src="https://avatars.githubusercontent.com/u/1382556?s=50" width="50" height="50">](https://github.com/Lukasa)| @Lukasa reported|
|-|-|
|Trac ID|trac#9157|
|Type|enhancement|
|Created|2017-06-02 09:37:25Z|
|Branch|https://github.com/twisted/twisted/tree/9157-lukasa-already-called|

Easily triggered by running the following Python code against a Twisted HTTPS server in an interactive interpreter and then waiting 90 seconds.

```
>>> import requests
>>> s = requests.Session()
>>> s.get('http://localhost:8080/')
<Response [200]>
```

Causes this traceback:

```
2017-06-02T09:59:32+0100 [twisted.python.log#info] "127.0.0.1" - - [02/Jun/2017:08:59:32 +0000] "GET / HTTP/1.1" 200 181 "-" "python-requests/2.17.3"
2017-06-02T10:00:32+0100 [-] Timing out client: IPv4Address(TCP, '127.0.0.1', 61510)
2017-06-02T10:00:47+0100 [-] Forcibly timing out client: IPv4Address(TCP, '127.0.0.1', 61510)
2017-06-02T10:00:47+0100 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/Users/cory/Documents/Python/twisted/src/twisted/application/runner/_runner.py", line 105, in run
	    self.startReactor()
	  File "/Users/cory/Documents/Python/twisted/src/twisted/application/runner/_runner.py", line 182, in startReactor
	    reactor.run()
	  File "/Users/cory/Documents/Python/twisted/src/twisted/internet/base.py", line 1243, in run
	    self.mainLoop()
	  File "/Users/cory/Documents/Python/twisted/src/twisted/internet/base.py", line 1252, in mainLoop
	    self.runUntilCurrent()
	--- <exception caught here> ---
	  File "/Users/cory/Documents/Python/twisted/src/twisted/internet/base.py", line 878, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/Users/cory/Documents/Python/twisted/src/twisted/internet/tcp.py", line 292, in connectionLost
	    protocol.connectionLost(reason)
	  File "/Users/cory/Documents/Python/twisted/src/twisted/protocols/tls.py", line 403, in connectionLost
	    ProtocolWrapper.connectionLost(self, reason)
	  File "/Users/cory/Documents/Python/twisted/src/twisted/protocols/policies.py", line 125, in connectionLost
	    self.wrappedProtocol.connectionLost(reason)
	  File "/Users/cory/Documents/Python/twisted/src/twisted/web/http.py", line 2190, in connectionLost
	    self._abortingCall.cancel()
	  File "/Users/cory/Documents/Python/twisted/src/twisted/internet/base.py", line 99, in cancel
	    raise error.AlreadyCalled
	twisted.internet.error.AlreadyCalled: Tried to cancel an already-called event.
```

Looks like we have a problem with double-cancellation.

<details><summary>Searchable metadata</summary>

```
trac-id__9157 9157
type__enhancement enhancement
reporter__Lukasa Lukasa
priority__normal normal
milestone__None None
branch__9157_lukasa_already_called 9157-lukasa-already-called
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__None None
time__1496396245255564 1496396245255564
changetime__1497191304147195 1497191304147195
version__None None
owner__Lukasa Lukasa

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="Lukasa's avatar" src="https://avatars.githubusercontent.com/u/1382556?s=50" width="50" height="50">](https://github.com/Lukasa)<a name="note_1"></a>|@Lukasa commented|
|-|-|

Available for review at: https://github.com/twisted/twisted/pull/803

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_2"></a>|@hawkowl set owner to @Lukasa|
|-|-|

See review, one small nitpick, then land.

**Comment by twisted-trac** [comment]
|[<img alt="Lukasa's avatar" src="https://avatars.githubusercontent.com/u/1382556?s=50" width="50" height="50">](https://github.com/Lukasa)|@Lukasa set status to `closed`|
|-|-|
