### ISSUE TITLE
flattenEvent should handle a None format

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9163]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)| @wsanchez reported|
|-|-|
|Trac ID|trac#9163|
|Type|enhancement|
|Created|2017-06-06 20:05:21Z|

`flattenEvent` will raise if the `"log_format"` key in the even it is given is `None`.

`formatEvent` has code to handle a `None` format, so it's at least legal there, and raising an exception in an observer is quite problematic, so `flattenEvent` needs to not blow up.

Here's an example of this failing from exarkun:

```
2017-06-06T15:14:03-0400 [twisted.logger._observer#critical] Temporarily disabling observer <twisted.logger._file.FileLogObserver object at 0x7f8555ba0a10> due to exception: [Failure instance: Traceback: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute '_formatter_parser'
        <stdin>:2:<module>
        /home/exarkun/Environments/leastauthority.com/local/lib/python2.7/site-packages/twisted/logger/_logger.py:178:failure
        /home/exarkun/Environments/leastauthority.com/local/lib/python2.7/site-packages/twisted/logger/_logger.py:132:emit
        --- <exception caught here> ---
        /home/exarkun/Environments/leastauthority.com/local/lib/python2.7/site-packages/twisted/logger/_observer.py:131:__call__
        /home/exarkun/Environments/leastauthority.com/local/lib/python2.7/site-packages/twisted/logger/_file.py:50:__call__
        /home/exarkun/Environments/leastauthority.com/local/lib/python2.7/site-packages/twisted/logger/_json.py:248:<lambda>
        /home/exarkun/Environments/leastauthority.com/local/lib/python2.7/site-packages/twisted/logger/_json.py:199:eventAsJSON
        /home/exarkun/Environments/leastauthority.com/local/lib/python2.7/site-packages/twisted/logger/_flatten.py:87:flattenEvent
        /usr/lib/python2.7/string.py:635:parse
        ]
        Traceback (most recent call last):
          File "<stdin>", line 2, in <module>
            
          File "/home/exarkun/Environments/leastauthority.com/local/lib/python2.7/site-packages/twisted/logger/_logger.py", line 178, in failure
            self.emit(level, format, log_failure=failure, **kwargs)
          File "/home/exarkun/Environments/leastauthority.com/local/lib/python2.7/site-packages/twisted/logger/_logger.py", line 132, in emit
            self.observer(event)
        --- <exception caught here> ---
          File "/home/exarkun/Environments/leastauthority.com/local/lib/python2.7/site-packages/twisted/logger/_observer.py", line 131, in __call__
            observer(event)
          File "/home/exarkun/Environments/leastauthority.com/local/lib/python2.7/site-packages/twisted/logger/_file.py", line 50, in __call__
            text = self.formatEvent(event)
          File "/home/exarkun/Environments/leastauthority.com/local/lib/python2.7/site-packages/twisted/logger/_json.py", line 248, in <lambda>
            lambda event: u"{0}{1}\n".format(recordSeparator, eventAsJSON(event))
          File "/home/exarkun/Environments/leastauthority.com/local/lib/python2.7/site-packages/twisted/logger/_json.py", line 199, in eventAsJSON
            flattenEvent(event)
          File "/home/exarkun/Environments/leastauthority.com/local/lib/python2.7/site-packages/twisted/logger/_flatten.py", line 87, in flattenEvent
            aFormatter.parse(event["log_format"])
          File "/usr/lib/python2.7/string.py", line 635, in parse
            return format_string._formatter_parser()
        exceptions.AttributeError: 'NoneType' object has no attribute '_formatter_parser'
```

<details><summary>Searchable metadata</summary>

```
trac-id__9163 9163
type__enhancement enhancement
reporter__wsanchez wsanchez
priority__highest highest
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__duplicate duplicate
component__logger logger
keywords__None None
time__1496779521877130 1496779521877130
changetime__1496783879930602 1496783879930602
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)<a name="note_1"></a>|@wsanchez commented|
|-|-|

Hrm, actually, `test_flattenEventWithNoneFormat` tests already for and that passes…

`flattenEvent` returns right away if `if event.get("log_format", None) is None` (line 76).

So I'm confused about how in line 87, the same key in the same event is `None`.

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)<a name="note_2"></a>|@wsanchez commented|
|-|-|

Relevant code: https://github.com/twisted/twisted/blob/trunk/src/twisted/logger/_flatten.py#L76

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)<a name="note_3"></a>|@wsanchez set status to `closed`|
|-|-|

Never mind, this was a bug in 16.6.0 and has since been fixed.
