### ISSUE TITLE
Resolver.lookupZone can fail with AttributeError

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9174]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)| @markrwilliams reported|
|-|-|
|Trac ID|trac#9174|
|Type|defect|
|Created|2017-06-12 07:35:17Z|

```twisted.names.client.Resolver.lookupZone``` [creates a DNSClientFactory with an AXFRController](https://github.com/twisted/twisted/blob/trunk/src/twisted/names/client.py#L423-L424) that it then connects to some name server.

If that connection fails, then the connector will call DNSClientFactory.clientConnectionFailed, which in turn [will attempt to extract the AXFRController's pending requests.](https://github.com/twisted/twisted/blob/trunk/src/twisted/names/client.py#L539)

However, ```AXFRController``` has no ```pending``` attribute, so this causes the Deferred to fail with an attribute error.

<details><summary>Searchable metadata</summary>

```
trac-id__9174 9174
type__defect defect
reporter__markrwilliams markrwilliams
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__None None
time__1497252917955798 1497252917955798
changetime__1497590956793865 1497590956793865
version__None None
owner__glyph glyph
cc__glyph
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_1"></a>|@markrwilliams commented|
|-|-|

Traceback courtesy of Glyph:


```
2017-06-12T06:10:58+0000 [Uninitialized] Unhandled Error
	Traceback (most recent call last):
	  File "/code/env/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/code/env/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/code/env/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/code/env/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/code/env/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/code/env/site-packages/twisted/internet/tcp.py", line 551, in doConnect
	    self.failIfNotConnected(error.getConnectError((err, strerror(err))))
	  File "/code/env/site-packages/twisted/internet/tcp.py", line 453, in failIfNotConnected
	    self.connector.connectionFailed(failure.Failure(err))
	  File "/code/env/site-packages/twisted/internet/base.py", line 1128, in connectionFailed
	    self.factory.clientConnectionFailed(self, reason)
	  File "/code/env/site-packages/twisted/names/client.py", line 539, in clientConnectionFailed
	    pending = self.controller.pending[:]
	exceptions.AttributeError: AXFRController instance has no attribute 'pending'
```

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_3"></a>|@markrwilliams commented|
|-|-|

~~AXFRController should have a ```pending``` attribute to conform to the implicit controller interface.~~

On second thought, [controller](https://github.com/twisted/twisted/blob/trunk/src/twisted/names/client.py#L539) should probably be the _resolver_.

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_4"></a>|@markrwilliams commented|
|-|-|

This script reproduces the ```AttributeError```.  Replace ```127.6.5.4``` with an address that refuses incoming connections.


```python
"""
nameserver 127.6.5.4
"""
from twisted.names import client
from twisted.internet import defer, task


@task.react
@defer.inlineCallbacks
def main(reactor):
    resolver = client.createResolver(resolvconf=__file__)
    results = yield resolver.lookupZone("impossible")
    for result in results:
        print(result)
```

(I think the ```resolv.conf``` parser should be stricter.)

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_5"></a>|@markrwilliams commented|
|-|-|

https://github.com/twisted/twisted/pull/815

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_6"></a>|@glyph set owner to @glyph|
|-|-|

As I said on the ticket, looks great.  I'll land it.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_7"></a>|@glyph set status to `closed`|
|-|-|

In changeset 81aeb139e9fd27b009a7aea0667a2252692f3ccd
```
#!CommitTicketReference repository="" revision="81aeb139e9fd27b009a7aea0667a2252692f3ccd"
Merge pull request #815 from twisted/9174-axfr-connect-failure

Author: markrwilliams 

Reviewer: glyph

Fixes: ticket:9174

Failed TCP connections for AFXR queries no longer raise an AttributeError.
```
