### ISSUE TITLE
Fix some twisted.smtp errors found with Buildbot on Python 3

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9180]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)| @rodrigc reported|
|-|-|
|Trac ID|trac#9180|
|Type|release blocker: regression|
|Created|2017-06-14 05:25:32Z|

During porting of buildbot to python 3, we found a few errors
in twisted.smtp when trying to run buildbot with Twisted 17.5.0 on Python 3.

<details><summary>Searchable metadata</summary>

```
trac-id__9180 9180
type__release_blocker__regression release blocker: regression
reporter__rodrigc rodrigc
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__mail mail
keywords__None None
time__1497417932080828 1497417932080828
changetime__1502201006411086 1502201006411086
version__None None
owner__Craig_Rodrigues__rodrigc_____ Craig Rodrigues <rodrigc@...>
cc__paul.tremberth@...
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_1"></a>|@rodrigc commented|
|-|-|

Reported by s0undt3ch on Python 2:

https://github.com/buildbot/buildbot/pull/3310#issuecomment-308211902

```
2017-06-13 12:44:32-0600 [ESMTPSender,client] Unhandled Error                                                  
        Traceback (most recent call last):                                                                                 
          File "/home/buildbot/.pyenv/versions/2.7.13/envs/Buildbot/lib/python2.7/site-packages/twisted/python/log.py", line 103, in callWithLogger
            return callWithContext({"system": lp}, func, *args, **kw)                                                      
          File "/home/buildbot/.pyenv/versions/2.7.13/envs/Buildbot/lib/python2.7/site-packages/twisted/python/log.py", line 86, in callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)                                  
          File "/home/buildbot/.pyenv/versions/2.7.13/envs/Buildbot/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)                               
          File "/home/buildbot/.pyenv/versions/2.7.13/envs/Buildbot/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
            return func(*args,**kw)                                                                                 
        --- <exception caught here> ---                                                                                    
          File "/home/buildbot/.pyenv/versions/2.7.13/envs/Buildbot/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
            why = selectable.doRead()                                                                             
          File "/home/buildbot/.pyenv/versions/2.7.13/envs/Buildbot/lib/python2.7/site-packages/twisted/internet/tcp.py", line 208, in doRead
            return self._dataReceived(data)                                                                
          File "/home/buildbot/.pyenv/versions/2.7.13/envs/Buildbot/lib/python2.7/site-packages/twisted/internet/tcp.py", line 214, in _dataReceived
            rval = self.protocol.dataReceived(data)                                                          
          File "/home/buildbot/.pyenv/versions/2.7.13/envs/Buildbot/lib/python2.7/site-packages/twisted/protocols/tls.py", line 330, in dataReceived
            self._flushReceiveBIO()                                                                                 
          File "/home/buildbot/.pyenv/versions/2.7.13/envs/Buildbot/lib/python2.7/site-packages/twisted/protocols/tls.py", line 295, in _flushReceiveBIO
            ProtocolWrapper.dataReceived(self, bytes)                                                                    
          File "/home/buildbot/.pyenv/versions/2.7.13/envs/Buildbot/lib/python2.7/site-packages/twisted/protocols/policies.py", line 120, in dataReceived
            self.wrappedProtocol.dataReceived(data)                                                        
          File "/home/buildbot/.pyenv/versions/2.7.13/envs/Buildbot/lib/python2.7/site-packages/twisted/protocols/basic.py", line 571, in dataReceived
            why = self.lineReceived(line)                                                                  
          File "/home/buildbot/.pyenv/versions/2.7.13/envs/Buildbot/lib/python2.7/site-packages/twisted/mail/smtp.py", line 995, in lineReceived
            why = self._okresponse(self.code, b'\n'.join(self.resp))                                              
          File "/home/buildbot/.pyenv/versions/2.7.13/envs/Buildbot/lib/python2.7/site-packages/twisted/mail/smtp.py", line 1044, in smtpState_to
            return self.smtpState_toOrData(0, b'')
          File "/home/buildbot/.pyenv/versions/2.7.13/envs/Buildbot/lib/python2.7/site-packages/twisted/mail/smtp.py", line 1062, in smtpState_toOrData
            self.sendLine(b'RCPT TO:' + quoteaddr(self.lastAddress))
          File "/home/buildbot/.pyenv/versions/2.7.13/envs/Buildbot/lib/python2.7/site-packages/twisted/mail/smtp.py", line 179, in quoteaddr
            res = email.utils.parseaddr(addr)
          File "/home/buildbot/.pyenv/versions/2.7.13/lib/python2.7/email/utils.py", line 214, in parseaddr
            addrs = _AddressList(addr).addresslist
          File "/home/buildbot/.pyenv/versions/2.7.13/lib/python2.7/email/_parseaddr.py", line 457, in __init__
            self.addresslist = self.getaddrlist()
          File "/home/buildbot/.pyenv/versions/2.7.13/lib/python2.7/email/_parseaddr.py", line 217, in getaddrlist
            while self.pos < len(self.field):
        exceptions.TypeError: object of type 'module' has no len()
```

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_2"></a>|@rodrigc commented|
|-|-|

Here is another stacktrace on Python 3:

```
2017-06-14 05:02:14+0000 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/home/vagrant/buildbot-venv/lib64/python3.6/site-packages/twisted/internet/defer.py", line 500, in errback
	    self._startRunCallbacks(fail)
	  File "/home/vagrant/buildbot-venv/lib64/python3.6/site-packages/twisted/internet/defer.py", line 567, in _startRunCallbacks
	    self._runCallbacks()
	  File "/home/vagrant/buildbot-venv/lib64/python3.6/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/vagrant/buildbot-venv/lib64/python3.6/site-packages/twisted/internet/defer.py", line 1442, in gotResult
	    _inlineCallbacks(r, g, deferred)
	--- <exception caught here> ---
	  File "/home/vagrant/buildbot-venv/lib64/python3.6/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
	    result = result.throwExceptionIntoGenerator(g)
	  File "/home/vagrant/buildbot-venv/lib64/python3.6/site-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
	    return g.throw(self.type, self.value, self.tb)
	  File "/home/vagrant/buildbot/master/buildbot/reporters/notifier.py", line 280, in buildMessage
	    list(users), patches, logs)
	  File "/home/vagrant/buildbot-venv/lib64/python3.6/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
	    result = result.throwExceptionIntoGenerator(g)
	  File "/home/vagrant/buildbot-venv/lib64/python3.6/site-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
	    return g.throw(self.type, self.value, self.tb)
	  File "/home/vagrant/buildbot/master/buildbot/reporters/mail.py", line 270, in sendMessage
	    yield self.sendMail(m, all_recipients)
	  File "/home/vagrant/buildbot-venv/lib64/python3.6/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/vagrant/buildbot-venv/lib64/python3.6/site-packages/twisted/internet/tcp.py", line 208, in doRead
	    return self._dataReceived(data)
	  File "/home/vagrant/buildbot-venv/lib64/python3.6/site-packages/twisted/internet/tcp.py", line 214, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/vagrant/buildbot-venv/lib64/python3.6/site-packages/twisted/protocols/tls.py", line 330, in dataReceived
	    self._flushReceiveBIO()
	  File "/home/vagrant/buildbot-venv/lib64/python3.6/site-packages/twisted/protocols/tls.py", line 295, in _flushReceiveBIO
	    ProtocolWrapper.dataReceived(self, bytes)
	  File "/home/vagrant/buildbot-venv/lib64/python3.6/site-packages/twisted/protocols/policies.py", line 120, in dataReceived
	    self.wrappedProtocol.dataReceived(data)
	  File "/home/vagrant/buildbot-venv/lib64/python3.6/site-packages/twisted/protocols/basic.py", line 571, in dataReceived
	    why = self.lineReceived(line)
	  File "/home/vagrant/buildbot-venv/lib64/python3.6/site-packages/twisted/mail/smtp.py", line 995, in lineReceived
	    why = self._okresponse(self.code, b'\n'.join(self.resp))
	  File "/home/vagrant/buildbot-venv/lib64/python3.6/site-packages/twisted/mail/smtp.py", line 1556, in esmtpState_challenge
	    self._authResponse(self._authinfo, resp)
	  File "/home/vagrant/buildbot-venv/lib64/python3.6/site-packages/twisted/mail/smtp.py", line 1572, in _authResponse
	    self.sendLine(base64.b64encode(resp))
	  File "/usr/lib64/python3.6/base64.py", line 58, in b64encode
	    encoded = binascii.b2a_base64(s, newline=False)
	builtins.TypeError: a bytes-like object is required, not 'str'
```

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_3"></a>|@rodrigc set owner to @rodrigc<br>@rodrigc set status to `closed`|
|-|-|

In changeset 5ddbe39695f65e2cd485c997fe2af7afdfe4b751
```
#!CommitTicketReference repository="" revision="5ddbe39695f65e2cd485c997fe2af7afdfe4b751"
Merge pull request #816 from twisted/9180-rodrigc-smtp

Author: rodrigc
Reviewer: tardyp
Fixes: ticket:9180

Fix stacktrace in twisted.smtp on buildbot
```

**Comment by twisted-trac** [comment]
|[<img alt="redapple's avatar" src="https://avatars.githubusercontent.com/u/886296?s=50" width="50" height="50">](https://github.com/redapple)<a name="note_5"></a>|@redapple set status to `reopened`|
|-|-|

That bug triggering that 2nd stracktrace does not seem fixed.
At least in my case, with Python 3.6, I'm experiencing the same when using 

```
ESMTPSenderFactory(
        authenticationUsername, authenticationSecret,
        fromAddress, toAddress,
        message, d, heloFallback=True,
        requireAuthentication=False, \
        requireTransportSecurity=True)
```
on port 587

Same as I reported on scrapy's GitHub https://github.com/scrapy/scrapy/issues/2375#issuecomment-299226510

This is what I have locally to make sending mails work for me
```
diff --git a/src/twisted/mail/smtp.py b/src/twisted/mail/smtp.py
index 733b76c..c64df36 100644
--- a/src/twisted/mail/smtp.py
+++ b/src/twisted/mail/smtp.py
@@ -1570,7 +1570,7 @@ class ESMTPClient(SMTPClient):
             resp = auth.challengeResponse(self.secret, challenge)
             self._expected = [235, 334]
             self._okresponse = self.smtpState_maybeAuthenticated
-            self.sendLine(base64.b64encode(resp))
+            self.sendLine(base64.b64encode(networkString(resp)))

```

**Comment by twisted-trac** [comment]
|[<img alt="redapple's avatar" src="https://avatars.githubusercontent.com/u/886296?s=50" width="50" height="50">](https://github.com/redapple)<a name="note_6"></a>|@redapple commented|
|-|-|

Note: the same stracktrace was reported recently at https://github.com/scrapy/scrapy/issues/730#issuecomment-316995315

**Comment by twisted-trac** [comment]
|[<img alt="mithrandi's avatar" src="https://avatars.githubusercontent.com/u/856430?s=50" width="50" height="50">](https://github.com/mithrandi)<a name="note_7"></a>|@mithrandi commented|
|-|-|

Are you running Twisted trunk? There has not yet been a release since this fix landed, so no release version of Twisted has the fix.

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_8"></a>|@rodrigc commented|
|-|-|

Yes, he found the same problems in trunk: https://github.com/scrapy/scrapy/pull/2671#issuecomment-299227187

**Comment by twisted-trac** [comment]
|[<img alt="redapple's avatar" src="https://avatars.githubusercontent.com/u/886296?s=50" width="50" height="50">](https://github.com/redapple)<a name="note_9"></a>|@redapple commented|
|-|-|

Indeed, I was doing my tests with Twisted trunk.

**Comment by twisted-trac** [comment]
|[<img alt="redapple's avatar" src="https://avatars.githubusercontent.com/u/886296?s=50" width="50" height="50">](https://github.com/redapple)<a name="note_11"></a>|@redapple set status to `closed`|
|-|-|

So after Craig's comment in https://github.com/scrapy/scrapy/issues/730#issuecomment-320801441 , I tested again, now with credentials and message as bytes, and sending emails is working fine. Sorry for the noise.
We'll prepare for the next Twisted in Scrapy.
