### ISSUE TITLE
setup.py ignores index-url option

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9189]
|[<img alt="MaxKh's avatar" src="https://avatars.githubusercontent.com/u/4003147?s=50" width="50" height="50">](https://github.com/MaxKh)| @MaxKh reported|
|-|-|
|Trac ID|trac#9189|
|Type|defect|
|Created|2017-06-20 07:13:17Z|

Installation of Twisted using
```
pip install -r <requirements.txt> --index-url <internal_url>
```
fails if HOST has no access to https://pypi.python.org/simple/.

```
Collecting Twisted==17.5.0 (from -r /opt/cm/pip.freeze (line 26))
  Downloading https://<internal_reposiory>/Twisted-17.5.0.tar.bz2 (3.0MB)
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/incremental/: [Errno 104] Connection reset by peer -- Some packages may not be found!
    Couldn't find index page for 'incremental' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: [Errno 104] Connection reset by peer -- Some packages may not be found!
    No local packages or working download links found for incremental>=16.10.1
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-lw5w4w/Twisted/setup.py", line 21, in <module>
        setuptools.setup(**_setup["getSetupArgs"]())
      File "/usr/local/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 320, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 377, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 852, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1124, in best_match
        return self.obtain(req, installer)
      File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1136, in obtain
        return installer(requirement)
      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 445, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 667, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('incremental>=16.10.1')
```

<details><summary>Searchable metadata</summary>

```
trac-id__9189 9189
type__defect defect
reporter__MaxKh MaxKh
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__None None
time__1497942797459893 1497942797459893
changetime__1499314829772072 1499314829772072
version__None None
owner__None None
cc__twm@...
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_1"></a>|@twm commented|
|-|-|

This is an unfortunate side effect of specifying `setup_requires` in `setup.py`. You can work around it as described here: https://pip.pypa.io/en/stable/reference/pip_install/#controlling-setup-requires

I think that the long-term plan is to remove all of Twisted's C extension modules so that we can publish universal wheels.
