### ISSUE TITLE
Broken sendmail?

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9195]
|[<img alt="Tramort's avatar" src="https://avatars.githubusercontent.com/u/3002748?s=50" width="50" height="50">](https://github.com/Tramort)| @Tramort reported|
|-|-|
|Trac ID|trac#9195|
|Type|defect|
|Created|2017-06-26 11:43:27Z|

Hi
I have tried use sendmail with 17.5.0 and have problem.
Tried trunk branch - the same issue.
With twisted 17.1.0 works fine.
There are steps to reproduce:

```
:~$ virtualenv -p python2.7 sandbox
Running virtualenv with interpreter /usr/bin/python2.7
New python executable in /home/maxim/sandbox/bin/python2.7
Also creating executable in /home/maxim/sandbox/bin/python
Installing setuptools, pip, wheel...done.

:~$ source sandbox/bin/activate
(sandbox) :~$ cat freeze.txt
pyOpenSSL==17.0
service-identity==17.0
Twisted==17.5.0

(sandbox) :~$ pip install -r freeze.txt
Collecting pyOpenSSL==17.0 (from -r freeze.txt (line 1))
  Using cached pyOpenSSL-17.0.0-py2.py3-none-any.whl
Collecting service-identity==17.0 (from -r freeze.txt (line 2))
  Using cached service_identity-17.0.0-py2.py3-none-any.whl
Collecting Twisted==17.5.0 (from -r freeze.txt (line 3))
Collecting cryptography>=1.7 (from pyOpenSSL==17.0->-r freeze.txt (line 1))
Collecting six>=1.5.2 (from pyOpenSSL==17.0->-r freeze.txt (line 1))
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting pyasn1 (from service-identity==17.0->-r freeze.txt (line 2))
  Using cached pyasn1-0.2.3-py2.py3-none-any.whl
Collecting pyasn1-modules (from service-identity==17.0->-r freeze.txt (line 2))
  Using cached pyasn1_modules-0.0.9-py2.py3-none-any.whl
Collecting attrs (from service-identity==17.0->-r freeze.txt (line 2))
  Using cached attrs-17.2.0-py2.py3-none-any.whl
Collecting Automat>=0.3.0 (from Twisted==17.5.0->-r freeze.txt (line 3))
  Using cached Automat-0.6.0-py2.py3-none-any.whl
Collecting zope.interface>=3.6.0 (from Twisted==17.5.0->-r freeze.txt (line 3))
  Using cached zope.interface-4.4.2-cp27-cp27mu-manylinux1_x86_64.whl
Collecting constantly>=15.1 (from Twisted==17.5.0->-r freeze.txt (line 3))
  Using cached constantly-15.1.0-py2.py3-none-any.whl
Collecting hyperlink>=17.1.1 (from Twisted==17.5.0->-r freeze.txt (line 3))
  Using cached hyperlink-17.2.1-py2.py3-none-any.whl
Collecting incremental>=16.10.1 (from Twisted==17.5.0->-r freeze.txt (line 3))
  Using cached incremental-17.5.0-py2.py3-none-any.whl
Collecting ipaddress (from cryptography>=1.7->pyOpenSSL==17.0->-r freeze.txt (line 1))
  Using cached ipaddress-1.0.18-py2-none-any.whl
Collecting idna>=2.1 (from cryptography>=1.7->pyOpenSSL==17.0->-r freeze.txt (line 1))
  Using cached idna-2.5-py2.py3-none-any.whl
Collecting asn1crypto>=0.21.0 (from cryptography>=1.7->pyOpenSSL==17.0->-r freeze.txt (line 1))
  Using cached asn1crypto-0.22.0-py2.py3-none-any.whl
Collecting enum34 (from cryptography>=1.7->pyOpenSSL==17.0->-r freeze.txt (line 1))
  Using cached enum34-1.1.6-py2-none-any.whl
Collecting cffi>=1.7 (from cryptography>=1.7->pyOpenSSL==17.0->-r freeze.txt (line 1))
  Using cached cffi-1.10.0-cp27-cp27mu-manylinux1_x86_64.whl
Requirement already satisfied: setuptools in ./sandbox/lib/python2.7/site-packages (from zope.interface>=3.6.0->Twisted==17.5.0->-r freeze.txt (line 3))
Collecting pycparser (from cffi>=1.7->cryptography>=1.7->pyOpenSSL==17.0->-r freeze.txt (line 1))
Installing collected packages: ipaddress, six, idna, asn1crypto, enum34, pycparser, cffi, cryptography, pyOpenSSL, pyasn1, pyasn1-modules, attrs, service-identity, Automat, zope.interface, constantly, hyperlink, incremental, Twisted
Successfully installed Automat-0.6.0 Twisted-17.5.0 asn1crypto-0.22.0 attrs-17.2.0 cffi-1.10.0 constantly-15.1.0 cryptography-1.9 enum34-1.1.6 hyperlink-17.2.1 idna-2.5 incremental-17.5.0 ipaddress-1.0.18 pyOpenSSL-17.0.0 pyasn1-0.2.3 pyasn1-modules-0.0.9 pycparser-2.17 service-identity-17.0.0 six-1.10.0 zope.interface-4.4.2

(sandbox) :~$ cat sendmail.py
from __future__ import print_function

import sys
from twisted.mail.smtp import sendmail
from email.mime.text import  MIMEText

from twisted.internet.task import react
from twisted.python import log

import getpass

me = "YOUR@EMAIL"
pwd = getpass.getpass()
msg = MIMEText("TESTS")
msg['Subject'] = "TEST"
msg['From'] = me
msg['To'] = me

log.startLogging(sys.stdout)

def main(reactor):

    d = sendmail("YOUR.SMTP.SERVER",
                 from_addr=me,
                 to_addrs=[me],
                 msg=msg.as_string(), requireAuthentication=True, requireTransportSecurity=True,
                 port=587, username=me, password=pwd)

    d.addBoth(print)
    return d

react(main)

(sandbox) :~$ python sendmail.py
Password: 
2017-06-26 14:26:50+0300 [-] Log opened.
2017-06-26 14:26:50+0300 [-] Starting factory <twisted.mail.smtp.ESMTPSenderFactory instance at 0x7fb4266db680>
2017-06-26 14:26:53+0300 [ESMTPSender,client] Unhandled Error
	Traceback (most recent call last):
	  File "/home/maxim/sandbox/local/lib/python2.7/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/maxim/sandbox/local/lib/python2.7/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/maxim/sandbox/local/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/maxim/sandbox/local/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/maxim/sandbox/local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/maxim/sandbox/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 208, in doRead
	    return self._dataReceived(data)
	  File "/home/maxim/sandbox/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 214, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/maxim/sandbox/local/lib/python2.7/site-packages/twisted/protocols/tls.py", line 330, in dataReceived
	    self._flushReceiveBIO()
	  File "/home/maxim/sandbox/local/lib/python2.7/site-packages/twisted/protocols/tls.py", line 295, in _flushReceiveBIO
	    ProtocolWrapper.dataReceived(self, bytes)
	  File "/home/maxim/sandbox/local/lib/python2.7/site-packages/twisted/protocols/policies.py", line 120, in dataReceived
	    self.wrappedProtocol.dataReceived(data)
	  File "/home/maxim/sandbox/local/lib/python2.7/site-packages/twisted/protocols/basic.py", line 571, in dataReceived
	    why = self.lineReceived(line)
	  File "/home/maxim/sandbox/local/lib/python2.7/site-packages/twisted/mail/smtp.py", line 995, in lineReceived
	    why = self._okresponse(self.code, b'\n'.join(self.resp))
	  File "/home/maxim/sandbox/local/lib/python2.7/site-packages/twisted/mail/smtp.py", line 1044, in smtpState_to
	    return self.smtpState_toOrData(0, b'')
	  File "/home/maxim/sandbox/local/lib/python2.7/site-packages/twisted/mail/smtp.py", line 1062, in smtpState_toOrData
	    self.sendLine(b'RCPT TO:' + quoteaddr(self.lastAddress))
	  File "/home/maxim/sandbox/local/lib/python2.7/site-packages/twisted/mail/smtp.py", line 179, in quoteaddr
	    res = email.utils.parseaddr(addr)
	  File "/usr/lib/python2.7/email/utils.py", line 214, in parseaddr
	    addrs = _AddressList(addr).addresslist
	  File "/usr/lib/python2.7/email/_parseaddr.py", line 457, in __init__
	    self.addresslist = self.getaddrlist()
	  File "/usr/lib/python2.7/email/_parseaddr.py", line 217, in getaddrlist
	    while self.pos < len(self.field):
	exceptions.TypeError: object of type 'module' has no len()
	
2017-06-26 14:26:53+0300 [ESMTPSender,client] SMTP Client retrying server. Retry: 5
^C2017-06-26 14:26:56+0300 [-] Received SIGINT, shutting down.
2017-06-26 14:26:56+0300 [ESMTPSender,client] SMTP Client retrying server. Retry: 4
2017-06-26 14:26:56+0300 [-] Main loop terminated.
```

<details><summary>Searchable metadata</summary>

```
trac-id__9195 9195
type__defect defect
reporter__Tramort Tramort
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__mail mail
keywords__None None
time__1498477407581347 1498477407581347
changetime__1511644610847011 1511644610847011
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="redapple's avatar" src="https://avatars.githubusercontent.com/u/886296?s=50" width="50" height="50">](https://github.com/redapple)<a name="note_3"></a>|@redapple commented|
|-|-|

This looks the same as [#9180](https://github.com/twisted/twisted/issues/9180) 's first stracktrace
And it was fixed in trunk: https://github.com/twisted/twisted/pull/816
(it is yet to appear in an official release though)

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_4"></a>|@rodrigc set status to `closed`|
|-|-|

Fixed in ticket:9180
