### ISSUE TITLE
reactor.spawnProcess() fails on Windows Python 3 if passed a path which is bytes

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9200]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)| @rodrigc reported|
|-|-|
|Trac ID|trac#9200|
|Type|defect|
|Created|2017-06-30 01:55:58Z|

jacky-chuang found the following problem when trying to run buildbot on Python 3 on Windows:

https://github.com/buildbot/buildbot/issues/3375

```
2017-06-26 11:49:08+0800 [-] while polling for changes
Traceback (most recent call last):
  File "d:\jacky\buildbot_virtualenv\buildbot\lib\site-packages\twisted\internet\defer.py", line 459, in callback
    self._startRunCallbacks(result)
  File "d:\jacky\buildbot_virtualenv\buildbot\lib\site-packages\twisted\internet\defer.py", line 567, in _startRunCallbacks
    self._runCallbacks()
  File "d:\jacky\buildbot_virtualenv\buildbot\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "d:\jacky\buildbot_virtualenv\buildbot\lib\site-packages\twisted\internet\defer.py", line 1442, in gotResult
    _inlineCallbacks(r, g, deferred)
--- ---
  File "d:\jacky\buildbot_virtualenv\buildbot\lib\site-packages\twisted\internet\defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "d:\jacky\buildbot_virtualenv\buildbot\lib\site-packages\buildbot\changes\gitpoller.py", line 190, in poll
    path=self.workdir)
  File "d:\jacky\buildbot_virtualenv\buildbot\lib\site-packages\buildbot\changes\gitpoller.py", line 357, in _dovccmd
    path=encodeArg(path), env=os.environ)
  File "d:\jacky\buildbot_virtualenv\buildbot\lib\site-packages\twisted\internet\utils.py", line 174, in getProcessOutputAndValue
    reactor)
  File "d:\jacky\buildbot_virtualenv\buildbot\lib\site-packages\twisted\internet\utils.py", line 28, in _callProtocolWithDeferred
    reactor.spawnProcess(p, executable, (executable,)+tuple(args), env, path)
  File "d:\jacky\buildbot_virtualenv\buildbot\lib\site-packages\twisted\internet\posixbase.py", line 353, in spawnProcess
    return Process(self, processProtocol, executable, args, env, path)
  File "d:\jacky\buildbot_virtualenv\buildbot\lib\site-packages\twisted\internet_dumbwin32proc.py", line 217, in init
    doCreate()
  File "d:\jacky\buildbot_virtualenv\buildbot\lib\site-packages\twisted\internet_dumbwin32proc.py", line 214, in doCreate
    command, cmdline, None, None, 1, flags, env, path, StartupInfo)
builtins.TypeError: Objects of type 'bytes' can not be converted to Unicode.
```

<details><summary>Searchable metadata</summary>

```
trac-id__9200 9200
type__defect defect
reporter__rodrigc rodrigc
priority__normal normal
milestone__Python_3_x Python-3.x
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__None None
time__1498787758509902 1498787758509902
changetime__1499290210539383 1499290210539383
version__None None
owner__Craig_Rodrigues__rodrigc_____ Craig Rodrigues <rodrigc@...>

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_1"></a>|@rodrigc commented|
|-|-|

https://github.com/twisted/twisted/pull/830

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_3"></a>|@rodrigc set owner to @rodrigc<br>@rodrigc set status to `closed`|
|-|-|

In changeset 89c53f851ef4b3943c7606e348364d8735788398
```
#!CommitTicketReference repository="" revision="89c53f851ef4b3943c7606e348364d8735788398"
Merge pull request #830 from twisted/9200-rodrigc-spawnprocess-py3-2

Author: rodrigc
Reviewer: opalmer
Fixes: ticket:9200

Make sure we pass unicode, not bytes to CreateProcess()
```

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_4"></a>|@rodrigc commented|
|-|-|

https://github.com/twisted/twisted/pull/830#pullrequestreview-47532794
