### ISSUE TITLE
logged traceback when hitting ESC in browser using HTTP2

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9208]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)| @glyph reported|
|-|-|
|Trac ID|trac#9208|
|Type|defect|
|Created|2017-07-02 21:15:31Z|
|Branch|https://github.com/twisted/twisted/tree/9208-lukasa-connectionlost|

following up from [#8692](https://github.com/twisted/twisted/issues/8692):

If I try the same example with the `http2` extra installed, and an http2-capable browser (Safari or Chrome), I get this traceback:

```
2017-07-02T14:10:24-0700 [_GenericHTTPChannelProtocol (TLSMemoryBIOProtocol),7,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/Users/glyph/Projects/Twisted/src/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/Users/glyph/Projects/Twisted/src/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/Users/glyph/Projects/Twisted/src/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/Users/glyph/Projects/Twisted/src/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/Users/glyph/Projects/Twisted/src/twisted/internet/selectreactor.py", line 149, in _doReadOrWrite
	    why = getattr(selectable, method)()
	  File "/Users/glyph/Projects/Twisted/src/twisted/internet/tcp.py", line 205, in doRead
	    return self._dataReceived(data)
	  File "/Users/glyph/Projects/Twisted/src/twisted/internet/tcp.py", line 211, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/Users/glyph/Projects/Twisted/src/twisted/protocols/tls.py", line 330, in dataReceived
	    self._flushReceiveBIO()
	  File "/Users/glyph/Projects/Twisted/src/twisted/protocols/tls.py", line 295, in _flushReceiveBIO
	    ProtocolWrapper.dataReceived(self, bytes)
	  File "/Users/glyph/Projects/Twisted/src/twisted/protocols/policies.py", line 120, in dataReceived
	    self.wrappedProtocol.dataReceived(data)
	  File "/Users/glyph/Projects/Twisted/src/twisted/web/http.py", line 2796, in dataReceived
	    return self._channel.dataReceived(data)
	  File "/Users/glyph/Projects/Twisted/src/twisted/web/_http2.py", line 186, in dataReceived
	    self._requestAborted(event)
	  File "/Users/glyph/Projects/Twisted/src/twisted/web/_http2.py", line 503, in _requestAborted
	    stream.connectionLost("Stream reset")
	  File "/Users/glyph/Projects/Twisted/src/twisted/web/_http2.py", line 999, in connectionLost
	    self._request.connectionLost(reason)
	  File "/Users/glyph/Projects/Twisted/src/twisted/web/http.py", line 1466, in connectionLost
	    d.errback(reason)
	  File "/Users/glyph/Projects/Twisted/src/twisted/internet/defer.py", line 498, in errback
	    fail = failure.Failure(fail)
	  File "/Users/glyph/Projects/Twisted/src/twisted/python/failure.py", line 207, in __init__
	    raise TypeError("Strings are not supported by Failure")
	exceptions.TypeError: Strings are not supported by Failure
	
2017-07-02T14:10:24-0700 [stdout#info] Bye! [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-clean fashion: Connection lost.
```

This behavior does _not_ occur when hitting `^C` with a build of `curl` that supports http2, so I am guessing it's something unhandled in the HTTP2 protocol itself.  (To get such a build I needed to do `brew reinstall curl --with-nghttp2`.  Note also that HTTP2 is going to require a valid TLS certificate.)

I don't know if this is a separate issue or related to the same one, but I also see 

```
2017-07-02T14:11:14-0700 [-] Timing out client: IPv4Address(TCP, '127.0.0.1', 58468)
2017-07-02T14:11:29-0700 [-] Forcibly timing out client: IPv4Address(TCP, '127.0.0.1', 58468)
```

in both `curl` (no traceback) and browser (traceback) cases; I would have expected the connection (and all its attendant timeouts) to be shut down by this point; especially in the `curl` case where the process talking to the web server doesn't even exist any more.  This may deserve a separate issue.

<details><summary>Searchable metadata</summary>

```
trac-id__9208 9208
type__defect defect
reporter__glyph glyph
priority__normal normal
milestone__None None
branch__9208_lukasa_connectionlost 9208-lukasa-connectionlost
branch_author__ 
status__closed closed
resolution__fixed fixed
component__web web
keywords__None None
time__1499030131695389 1499030131695389
changetime__1499326592730137 1499326592730137
version__None None
owner__Glyph__glyph_____ Glyph <glyph@...>
cc__Lukasa cc__exarkun cc__mithrandi
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_1"></a>|@glyph commented|
|-|-|

[#8692](https://github.com/twisted/twisted/issues/8692)

**Comment by twisted-trac** [comment]
|[<img alt="mithrandi's avatar" src="https://avatars.githubusercontent.com/u/856430?s=50" width="50" height="50">](https://github.com/mithrandi)<a name="note_2"></a>|@mithrandi commented|
|-|-|

The error appears in the traceback:
```
	    stream.connectionLost("Stream reset")
```
`connectionLost` takes an exception/failure, not a string, so this code would appear to just be straight up wrong.

**Comment by twisted-trac** [comment]
|[<img alt="mithrandi's avatar" src="https://avatars.githubusercontent.com/u/856430?s=50" width="50" height="50">](https://github.com/mithrandi)<a name="note_3"></a>|@mithrandi commented|
|-|-|

Oh, and I figure the reason why you don't see this with curl is that when you `^C` curl, all of its connections get forcibly reset; whereas when you hit Esc in your browser, it just resets that single HTTP/2 stream (hitting this code path), while keeping the underlying connection open.

**Comment by twisted-trac** [comment]
|[<img alt="Lukasa's avatar" src="https://avatars.githubusercontent.com/u/1382556?s=50" width="50" height="50">](https://github.com/Lukasa)<a name="note_5"></a>|@Lukasa commented|
|-|-|

Yup, that looks wrong. It's *almost* as if I didn't really understand `Failure` when I originally wrote this code.

**Comment by twisted-trac** [comment]
|[<img alt="Lukasa's avatar" src="https://avatars.githubusercontent.com/u/1382556?s=50" width="50" height="50">](https://github.com/Lukasa)<a name="note_6"></a>|@Lukasa commented|
|-|-|

Ok, a fix is available for this: https://github.com/twisted/twisted/pull/834

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_7"></a>|@glyph commented|
|-|-|

Thanks for fixing so quickly.  This looks good to me; I'll land.  WTB a functioning code coverage service.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_8"></a>|@glyph set owner to @glyph<br>@glyph set status to `closed`|
|-|-|

In changeset a4c285f9e63af2f2ea431f056233c75a1efeb48e
```
#!CommitTicketReference repository="" revision="a4c285f9e63af2f2ea431f056233c75a1efeb48e"
Merge pull request #834 from twisted/9208-lukasa-connectionlost

Author: Lukasa

Reviewer: glyph

Fixes: ticket:9208

Fix handling of connectionLost in HTTP2 code: pass Failure objects, not strings, as required by the interface.
```
