### ISSUE TITLE
twisted.test.test_plugin.DeveloperSetupTests.test_freshPyReplacesStalePyc ERRORs and FAILs under pypy2

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9219]
|[<img alt="dansut's avatar" src="https://avatars.githubusercontent.com/u/100365?s=50" width="50" height="50">](https://github.com/dansut)| @dansut reported|
|-|-|
|Trac ID|trac#9219|
|Type|task|
|Created|2017-07-14 12:52:17Z|

Using the standard build of pypy 5.8.0 that is compatible with CPython 2.7.13 has both an ERROR and a FAIL in twisted.test.test_plugin.DeveloperSetupTests.test_freshPyReplacesStalePyc 
```
===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/home/twisted/Twisted/src/twisted/test/test_plugin.py", line 566, in test_freshPyReplacesStalePyc
    self.assertIn('one', self.getAllPlugins())
  File "/home/twisted/Twisted/src/twisted/trial/_synctest.py", line 492, in assertIn
    % (containee, container))
twisted.trial.unittest.FailTest: 'one' not in ['dev', 'app']

twisted.test.test_plugin.DeveloperSetupTests.test_freshPyReplacesStalePyc
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/home/twisted/Twisted/src/twisted/plugin.py", line 171, in getCache
    provider = pluginModule.load()
  File "/home/twisted/Twisted/src/twisted/python/modules.py", line 392, in load
    return self.pathEntry.pythonPath.moduleLoader(self.name)
  File "/home/twisted/Twisted/src/twisted/python/reflect.py", line 312, in namedAny
    obj = getattr(obj, n)
exceptions.AttributeError: 'module' object has no attribute 'stale'

twisted.test.test_plugin.DeveloperSetupTests.test_freshPyReplacesStalePyc
-------------------------------------------------------------------------------
```

Thorough investigation shows the reason for this is that this test removes the .py version of a plugin leaving only the .pyc in the plugin directory as part of its actions. In its standard build form pypy does not support importing modules that only have the compiled .pyc even though this is standard behavior for CPython.

The reasons behind this decision are based on dangers of running optimized compiled python potentially not being runnable across similar pypy builds - ie. binary compatibility can't be guaranteed. The behavior can be turned on as a pypy configure time option but the default is off - http://doc.pypy.org/en/latest/config/objspace.lonepycfiles.html

Interestingly the pypy 5.8.0 beta build that is CPython 3.5.3 compatible passes this test - potentially because in the test compileall.compile_dir() is given legacy=True for _PY3

<details><summary>Searchable metadata</summary>

```
trac-id__9219 9219
type__task task
reporter__dansut dansut
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__pypy pypy
time__1500036737145535 1500036737145535
changetime__1500151688989484 1500151688989484
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="dansut's avatar" src="https://avatars.githubusercontent.com/u/100365?s=50" width="50" height="50">](https://github.com/dansut)<a name="note_1"></a>|@dansut commented|
|-|-|

PR to disable test under Glyph's advice: https://github.com/twisted/twisted/pull/837

**Comment by twisted-trac** [comment]
|[<img alt="dansut's avatar" src="https://avatars.githubusercontent.com/u/100365?s=50" width="50" height="50">](https://github.com/dansut)<a name="note_2"></a>|@dansut commented|
|-|-|

mailing list thread https://twistedmatrix.com/pipermail/twisted-python/2017-July/031546.html

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)|@rodrigc set status to `closed`|
|-|-|
