### ISSUE TITLE
hComPort attribute error for _win32serialport

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9252]
|[<img alt="altendky's avatar" src="https://avatars.githubusercontent.com/u/543719?s=50" width="50" height="50">](https://github.com/altendky)| @altendky reported|
|-|-|
|Trac ID|trac#9252|
|Type|defect|
|Created|2017-08-14 22:18:53Z|

Rather than an exception this should work.  Of course, the one line I didn't test because it depends on real hardware is the line with the most flagrant bug.

```
Traceback (most recent call last):
  File "C:/epc/t/613/pysunspec/venv3/Scripts/sunspecasync-script.py", line 11, in <module>
    load_entry_point('pysunspec', 'console_scripts', 'sunspecasync')()
  File "C:\epc\t\613\pysunspec\venv3\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\epc\t\613\pysunspec\venv3\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\epc\t\613\pysunspec\venv3\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\epc\t\613\pysunspec\venv3\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\epc\t\613\pysunspec\venv3\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\epc\t\613\pysunspec\sunspec\scripts\async.py", line 129, in twisted_
    name=name,
  File "C:\epc\t\613\pysunspec\sunspec\core\client.py", line 1083, in __init__
    self.device = client_device(device_type, slave_id, name, pathlist, baudrate, parity, ipaddr, ipport, timeout, trace, max_count=max_count)
  File "C:\epc\t\613\pysunspec\sunspec\core\client.py", line 327, in __init__
    self.modbus_device = modbus.ModbusClientDeviceRTUTwisted(slave_id, name, baudrate, parity, timeout, self, trace, max_count=max_count)
  File "C:\epc\t\613\pysunspec\sunspec\core\modbus\client.py", line 768, in __init__
    cls=ModbusClientRTUTwisted
  File "C:\epc\t\613\pysunspec\sunspec\core\modbus\client.py", line 161, in modbus_rtu_client
    client = cls(name, baudrate, parity)
  File "C:\epc\t\613\pysunspec\sunspec\core\modbus\client.py", line 361, in __init__
    self.open()
  File "C:\epc\t\613\pysunspec\sunspec\core\modbus\client.py", line 381, in open
    rtscts=False,
  File "c:\epc\t\613\pysunspec\venv3\src\twisted\src\twisted\internet\_win32serialport.py", line 59, in __init__
    self._finishPortSetup()
  File "c:\epc\t\613\pysunspec\venv3\src\twisted\src\twisted\internet\_win32serialport.py", line 68, in _finishPortSetup
    flags, comstat = self._clearCommError()
  File "c:\epc\t\613\pysunspec\venv3\src\twisted\src\twisted\internet\_win32serialport.py", line 75, in _clearCommError
    return win32file.ClearCommError(self._serial.hComPort)
AttributeError: 'Serial' object has no attribute 'hComPort'
```

<details><summary>Searchable metadata</summary>

```
trac-id__9252 9252
type__defect defect
reporter__altendky altendky
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__None None
time__1502749133811288 1502749133811288
changetime__1502779523567140 1502779523567140
version__None None
owner__Craig_Rodrigues__rodrigc_____ Craig Rodrigues <rodrigc@...>

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="altendky's avatar" src="https://avatars.githubusercontent.com/u/543719?s=50" width="50" height="50">](https://github.com/altendky)<a name="note_1"></a>|@altendky commented|
|-|-|

Pull request: https://github.com/twisted/twisted/pull/863

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_3"></a>|@rodrigc commented|
|-|-|

https://github.com/twisted/twisted/pull/863#pullrequestreview-56268510

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_4"></a>|@rodrigc set owner to @rodrigc<br>@rodrigc set status to `closed`|
|-|-|

In changeset 55c6e9bb6c05174069d70421aec725b606cd79b1
```
#!CommitTicketReference repository="" revision="55c6e9bb6c05174069d70421aec725b606cd79b1"
Merge pull request #863 from altendky/9252-altendky-hComPort_to__port_handle

Author: altendky
Reviewer: rodrigc
Fixes: ticket:9252

Correct twisted.internet._win32serialport hComPort to _port_handle
```
