### ISSUE TITLE
trial -j doesn't work at all on python 3

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9264]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)| @glyph reported|
|-|-|
|Trac ID|trac#9264|
|Type|enhancement|
|Created|2017-08-22 00:29:01Z|

It just prints out the number of tests to be run, then exits with success.  No output.  `test.log` is empty.

<details><summary>Searchable metadata</summary>

```
trac-id__9264 9264
type__enhancement enhancement
reporter__glyph glyph
priority__normal normal
milestone__Python_3_x Python-3.x
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__trial trial
keywords__None None
time__1503361741318737 1503361741318737
changetime__1510036087262696 1510036087262696
version__None None
owner__rodrigc rodrigc

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_2"></a>|@rodrigc commented|
|-|-|

I did some debugging of trial itself, and found that on Python 3, the following error happens, but doesn't quite make it into the logs:

```
<twisted.python.failure.Failure builtins.TypeError: Unicode value for key   
b'testCase' not allowed:
'twisted.test.test_abstract.AddressTests.test_emptyString'>
```

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_4"></a>|@rodrigc commented|
|-|-|

https://github.com/twisted/twisted/pull/924

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_5"></a>|@glyph set owner to @rodrigc|
|-|-|

Thanks Craig! This looks great. Totally fixes the issue I was seeing.

We should still add a builder that actually runs the tests under `-j` because something is still broken; under both py2 and py3, the tests crash out with:

```
Unhandled Error
Traceback (most recent call last):
  File ".../twisted/protocols/amp.py", line 1043, in _commandReceived
    deferred = self.dispatchCommand(box)
  File ".../twisted/protocols/amp.py", line 1101, in dispatchCommand
    return maybeDeferred(responder, box)
  File ".../twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File ".../twisted/protocols/amp.py", line 1188, in doit
    return maybeDeferred(aCallable, **kw).addCallback(
--- <exception caught here> ---
  File ".../twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File ".../twisted/trial/_dist/worker.py", line 133, in addSkip
    self._result.addSkip(self._testCase, reason)
  File ".../twisted/trial/_dist/distreporter.py", line 59, in addSkip
    self.running[test.id()].append((self.original.addSkip,
exceptions.KeyError: 'twisted.mail.test.test_pop3client.POP3TLSTests.test_startTLS'
```

but that's not a problem for this change.

Please land at your convenience!

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_6"></a>|@rodrigc set status to `closed`|
|-|-|

In changeset b95ce2f3937c0e9a898a22aa9c96735cf3409041
```
#!CommitTicketReference repository="" revision="b95ce2f3937c0e9a898a22aa9c96735cf3409041"
Merge pull request #924 from twisted/9264-rodrigc-trial-py3

Author: rodrigc
Reviewer: glyph
Fixes: ticket:9264

Fix bytes issues on Python 3 for "trial -j"
```
