### ISSUE TITLE
SynchronousTestCase does complete test lifecycle after failure.

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9267]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)| @markrwilliams reported|
|-|-|
|Trac ID|trac#9267|
|Type|defect|
|Created|2017-08-22 21:46:34Z|

`twisted.trial.unittest.SynchronousTestCase` does not run `tearDown` or flush logged errors when a test method raises an exception:

```python
from twisted.trial import unittest
from twisted.logger import Logger
from twisted.python.failure import Failure

class UnderTest(object):
    log = Logger()

    def method(self):
        try:
            raise Exception
        except:
            self.log.failure("what", failure=Failure())


class ExampleTest(unittest.SynchronousTestCase):

    def tearDown(self):
        self.assertFalse(True, "teardown Ran")

    def test_works(self):
        pass

    def test_broken(self):
        UnderTest().method()
        raise Exception("Failure")
```

This results in the following output:

```
module
  ExampleTest
    test_broken ...                                                     [ERROR]
    test_works ...                                                       [FAIL]
                                                     [ERROR]

===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/path/to/module.py", line 18, in tearDown
    self.assertFalse(True, "teardown Ran")
  File "/home/mrw/.virtualenvs/path/to-f9530a6b996832d1/lib/python2.7/site-packages/twisted/trial/_synctest.py", line 384, in assertFalse
    super(_Assertions, self).assertFalse(condition, msg)
  File "/home/mrw/.pyenv/versions/2.7.13/lib/python2.7/unittest/case.py", line 416, in assertFalse
    raise self.failureException(msg)
twisted.trial.unittest.FailTest: teardown Ran

module.ExampleTest.test_works
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/path/to/module.py", line 25, in test_broken
    raise Exception("Failure")
exceptions.Exception: Failure

module.ExampleTest.test_broken
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/path/to/module.py", line 10, in method
    raise Exception
exceptions.Exception: 

<not in test>
-------------------------------------------------------------------------------
Ran 2 tests in 0.126s

```

`test_works` runs the `tearDown` method, resulting in the assertion failure, while `test_broken`'s lifecycle ends with the raised exception, so that `tearDown` does not run and the logged exception is collected by the runner.

The reason is that [the tear down phase of a test's lifecycle does not happen in a finally clause](https://github.com/twisted/twisted/blob/2ca7c76073e10a6694623c5e4bf934c3000786e6/src/twisted/trial/_synctest.py#L1356-L1364).  This is particularly bad with logged errors, because the observer is global mutable state.  That means errors will hang around until something flushes those errors out.

Note that this also means an exception raised in `tearDown` will prevent flush logs from appearing with their test.

The `tearDown` method should be called and logged errors flushed even when the test method raises an exception.

See https://github.com/twisted/treq/issues/205 - thanks to Allison Kaptur for reporting this!

<details><summary>Searchable metadata</summary>

```
trac-id__9267 9267
type__defect defect
reporter__markrwilliams markrwilliams
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__trial trial
keywords__None None
time__1503438394176552 1503438394176552
changetime__1503618577870785 1503618577870785
version__None None
owner__markrwilliams markrwilliams
cc__akaptur
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_1"></a>|@markrwilliams commented|
|-|-|

Note that [the documentation](http://twistedmatrix.com/documents/17.5.0/core/howto/trial.html#factoring-out-common-test-logic) says `tearDown` should be called even when a test fails:

> Note that a test class may also provide the counterpart of setUp , named tearDown , which will be called after each test (whether successful or not).

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_2"></a>|@markrwilliams commented|
|-|-|

https://github.com/twisted/twisted/pull/875

**Comment by twisted-trac** [comment]
|[<img alt="mithrandi's avatar" src="https://avatars.githubusercontent.com/u/856430?s=50" width="50" height="50">](https://github.com/mithrandi)<a name="note_4"></a>|@mithrandi set owner to @markrwilliams|
|-|-|

https://github.com/twisted/twisted/pull/875#pullrequestreview-58515059 Looks good, please merge.

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_5"></a>|@markrwilliams set status to `closed`|
|-|-|

In changeset 33db6d7b404f63cd810c96c0aab72e9baf075cde
```
#!CommitTicketReference repository="" revision="33db6d7b404f63cd810c96c0aab72e9baf075cde"
Merge pull request #875 from twisted/9267-complete-test-lifecycle

Author: markrwilliams

Reviewer: mithrandi

Fixes: ticket:9267

SynchronousTestCase and TestCase run tearDown and flush logged errors when test methods fail.
```
