### ISSUE TITLE
Don't raise AlreadyCalled in Request.getSession when the previous session has expired.

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9288]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)| @adiroiban reported|
|-|-|
|Trac ID|trac#9288|
|Type|defect|
|Created|2017-09-24 21:44:20Z|
|Branch|https://github.com/twisted/twisted/tree/9288-request-getSession-expired|

When you have a long-running request, (more than the sessionTimeout) and you want to get the session at the end of the request, you get an error like

```
[ERROR]
Traceback (most recent call last):
  File "/home/adi/chevah/twisted/src/twisted/web/test/test_web.py", line 781, in test_getSessionExpired
    newSession = request.getSession()
  File "/home/adi/chevah/twisted/src/twisted/web/server.py", line 471, in getSession
    session.touch()
  File "/home/adi/chevah/twisted/src/twisted/web/server.py", line 701, in touch
    self._expireCall.reset(self.sessionTimeout)
  File "/home/adi/chevah/twisted/src/twisted/internet/base.py", line 120, in reset
    raise error.AlreadyCalled
twisted.internet.error.AlreadyCalled: Tried to cancel an already-called event.

twisted.web.test.test_web.RequestTests.test_getSessionExpired
```

Not sure what should be the behaviour here, but I don't think that it should raise AlreadyCalled

maybe just create a new session

<details><summary>Searchable metadata</summary>

```
trac-id__9288 9288
type__defect defect
reporter__adiroiban adiroiban
priority__normal normal
milestone__None None
branch__9288_request_getSession_expired 9288-request-getSession-expired
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__None None
time__1506289460172565 1506289460172565
changetime__1531390425164047 1531390425164047
version__None None
owner__adiroiban adiroiban

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)|@adiroiban set owner to @adiroiban<br>@adiroiban set status to `assigned`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_2"></a>|@adiroiban removed owner<br>@adiroiban set status to `new`|
|-|-|

PR at https://github.com/twisted/twisted/pull/897

Thanks!

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun set owner to @adiroiban|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)|@adiroiban removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_5"></a>|@glyph set owner to @adiroiban|
|-|-|

Thanks for your maintenance effort, adi!  Looking forward to this landing.

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_6"></a>|@adiroiban set status to `closed`|
|-|-|

In changeset cd235d181d3ac42cf8faaa12f33564b973364390
```
#!CommitTicketReference repository="" revision="cd235d181d3ac42cf8faaa12f33564b973364390"
Merge pull request #897 from twisted/9288-request-getSession-expired

Author: adiroiban
Reviewer: glyph, exarkun
Fixes: ticket:9288

Create a new session when the previous session expired.
```
