### ISSUE TITLE
python3 test failure with 17.5 and 17.9, succeeds with Python2

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9294]
|[<img alt="doko42's avatar" src="https://avatars.githubusercontent.com/u/11258518?s=50" width="50" height="50">](https://github.com/doko42)| @doko42 reported|
|-|-|
|Trac ID|trac#9294|
|Type|defect|
|Created|2017-09-29 12:25:38Z|

seen with 3.6.2 and 3.6.3rc1, failing test when running the tests from the installed location:

https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-artful/artful/amd64/t/twisted/20170927_171448_6116d@/log.gz

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/twisted/conch/test/test_manhole.py", line 237, in finished
    b">>> done"])
  File "/usr/lib/python3/dist-packages/twisted/conch/test/test_recvline.py", line 464, in _assertBuffer
    b"".join(expectedLines[max(0, i-1):i+1]))
  File "/usr/lib/python3/dist-packages/twisted/trial/_synctest.py", line 432, in assertEqual
    super(_Assertions, self).assertEqual(first, second, msg)
  File "/usr/lib/python3.6/unittest/case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.6/unittest/case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
twisted.trial.unittest.FailTest: b'>>> done' != b'Traceback (most recent call last):' : b">>> raise Exception('foo bar baz')>>> done != >>> raise Exception('foo bar baz')Traceback (most recent call last):"
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/twisted/conch/test/test_manhole.py", line 237, in finished
    b">>> done"])
  File "/usr/lib/python3/dist-packages/twisted/conch/test/test_recvline.py", line 464, in _assertBuffer
    b"".join(expectedLines[max(0, i-1):i+1]))
  File "/usr/lib/python3/dist-packages/twisted/trial/_synctest.py", line 432, in assertEqual
    super(_Assertions, self).assertEqual(first, second, msg)
  File "/usr/lib/python3.6/unittest/case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.6/unittest/case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
twisted.trial.unittest.FailTest: b'>>> done' != b'Traceback (most recent call last):' : b">>> raise Exception('foo bar baz')>>> done != >>> raise Exception('foo bar baz')Traceback (most recent call last):"
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/twisted/conch/test/test_manhole.py", line 237, in finished
    b">>> done"])
  File "/usr/lib/python3/dist-packages/twisted/conch/test/test_recvline.py", line 464, in _assertBuffer
    b"".join(expectedLines[max(0, i-1):i+1]))
  File "/usr/lib/python3/dist-packages/twisted/trial/_synctest.py", line 432, in assertEqual
    super(_Assertions, self).assertEqual(first, second, msg)
  File "/usr/lib/python3.6/unittest/case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.6/unittest/case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
twisted.trial.unittest.FailTest: b'>>> done' != b'Traceback (most recent call last):' : b">>> raise Exception('foo bar baz')>>> done != >>> raise Exception('foo bar baz')Traceback (most recent call last):"
/usr/lib/python3/dist-packages/service_identity/pyopenssl.py:97: SubjectAltNameWarning: Certificate has no `subjectAltName`, falling back to check for a `commonName` for now.  This feature is being removed by major browsers and deprecated by RFC 2818.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/twisted/test/test_sslverify.py", line 3079, in test_dependencyMissingWarning
    (expectedMessage, "", 0))
  File "/usr/lib/python3/dist-packages/twisted/trial/_synctest.py", line 432, in assertEqual
    super(_Assertions, self).assertEqual(first, second, msg)
  File "/usr/lib/python3.6/unittest/case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.6/unittest/case.py", line 1038, in assertTupleEqual
    self.assertSequenceEqual(tuple1, tuple2, msg, seq_type=tuple)
  File "/usr/lib/python3.6/unittest/case.py", line 1009, in assertSequenceEqual
    self.fail(msg)
twisted.trial.unittest.FailTest: Tuples differ: ("You[74 chars]t of service_identity halted; None in sys.modu[302 chars]', 0) != ("You[74 chars]t of 'service_identity' halted; None in sys.mo[304 chars]', 0)

First differing element 0:
"You [73 chars]t of service_identity halted; None in sys.modu[294 chars]ted."
"You [73 chars]t of 'service_identity' halted; None in sys.mo[296 chars]ted."

Diff is 763 characters long. Set self.maxDiff to None to see it.
-------------------------------------------------------------------------------
Ran 11622 tests in 282.321s

<details><summary>Searchable metadata</summary>

```
trac-id__9294 9294
type__defect defect
reporter__doko42 doko42
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__None None
time__1506687938944676 1506687938944676
changetime__1526613987993662 1526613987993662
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="moshez's avatar" src="https://avatars.githubusercontent.com/u/422703?s=50" width="50" height="50">](https://github.com/moshez)<a name="note_1"></a>|@moshez commented|
|-|-|

You said you can reproduce locally. I used ubuntu:18.04 in a docker container, installed python3-twisted and could not reproduce. Can you add reproduction instructions? Best of all is if they can be made to work in Docker, since I am not running ubuntu on my laptop.
