### ISSUE TITLE
LineOnlyReceiver receives str from connection when bytes is expected

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9298]
|<img alt="ElementalAlchemist's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| ElementalAlchemist reported|
|-|-|
|Trac ID|trac#9298|
|Type|defect|
|Created|2017-10-02 14:12:44Z|

In Python 3.6, when I receive data from a user, I get an error in Twisted. It appears that data from the socket is being converted from bytes to str sometime before it gets to dataReceived in the LineOnlyReceiver, at which point it breaks because it's still supposed to be bytes. This occurred in Twisted 17.9.0. I'm running this on a Linux system.

```
2017-10-02T08:27:05-0500 [IRCUser,0,::1] Unhandled Error
        Traceback (most recent call last):
          File "/home/jacob/txircd/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
            return callWithContext({"system": lp}, func, *args, **kw)
          File "/home/jacob/txircd/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File "/home/jacob/txircd/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/home/jacob/txircd/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
            return func(*args,**kw)
        --- <exception caught here> ---
          File "/home/jacob/txircd/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
            why = selectable.doRead()
          File "/home/jacob/txircd/lib/python3.6/site-packages/twisted/internet/tcp.py", line 205, in doRead
            return self._dataReceived(data)
          File "/home/jacob/txircd/lib/python3.6/site-packages/twisted/internet/tcp.py", line 211, in _dataReceived
            rval = self.protocol.dataReceived(data)
          File "/home/jacob/txircd/lib/python3.6/site-packages/twisted/protocols/basic.py", line 442, in dataReceived
            lines  = (self._buffer+data).split(self.delimiter)
        builtins.TypeError: a bytes-like object is required, not 'str'
```

<details><summary>Searchable metadata</summary>

```
trac-id__9298 9298
type__defect defect
reporter__ElementalAlchemist ElementalAlchemist
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__invalid invalid
component__core core
keywords__None None
time__1506953564364270 1506953564364270
changetime__1506967806115382 1506967806115382
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|<img alt="ElementalAlchemist's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_2"></a>|ElementalAlchemist set status to `closed`|
|-|-|

The problem was a different place in the line than I thought; apparently I looked into it less than needed. This is not a bug with Twisted.
