### ISSUE TITLE
test_sslverify fails with Python 3.6.3

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9302]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)| @rodrigc reported|
|-|-|
|Trac ID|trac#9302|
|Type|enhancement|
|Created|2017-10-06 09:37:16Z|

With Python 3.6.3, test_sslverify suddenly fails:

```
[FAIL]
Traceback (most recent call last):
  File "/Users/crodrigues/twisted8/src/twisted/test/test_sslverify.py", line 3079, in test_dependencyMissingWarning
    (expectedMessage, "", 0))
  File "/Users/crodrigues/twisted8/src/twisted/trial/_synctest.py", line 432, in assertEqual
    super(_Assertions, self).assertEqual(first, second, msg)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 1038, in assertTupleEqual
    self.assertSequenceEqual(tuple1, tuple2, msg, seq_type=tuple)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 1009, in assertSequenceEqual
    self.fail(msg)
twisted.trial.unittest.FailTest: Tuples differ: ("You[74 chars]t of service_identity halted; None in sys.modu[302 chars]', 0) != ("You[74 chars]t of 'service_identity' halted; None in sys.mo[304 chars]', 0)

First differing element 0:
"You [73 chars]t of service_identity halted; None in sys.modu[294 chars]ted."
"You [73 chars]t of 'service_identity' halted; None in sys.mo[296 chars]ted."

Diff is 763 characters long. Set self.maxDiff to None to see it.

twisted.test.test_sslverify.SelectVerifyImplementationTests.test_dependencyMissingWarning
-------------------------------------------------------------------------------
```

<details><summary>Searchable metadata</summary>

```
trac-id__9302 9302
type__enhancement enhancement
reporter__rodrigc rodrigc
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__None None
time__1507282636347847 1507282636347847
changetime__1507305510514557 1507305510514557
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_1"></a>|@rodrigc commented|
|-|-|

https://github.com/twisted/twisted/pull/910

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_2"></a>|@markrwilliams commented|
|-|-|

https://github.com/twisted/twisted/pull/910#pullrequestreview-67713460

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_3"></a>|@markrwilliams set status to `closed`|
|-|-|

I merged this without the right comment.  Whoops:

https://github.com/twisted/twisted/commit/d72d93f99034a39701b241c2b73530c50a765d53
