### ISSUE TITLE
Failure.trap() raises wrapped exception in Python2.7

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9307]
|[<img alt="jwaterhouse's avatar" src="https://avatars.githubusercontent.com/u/97921433?s=50" width="50" height="50">](https://github.com/jwaterhouse)| @jwaterhouse reported|
|-|-|
|Trac ID|trac#9307|
|Type|release blocker: regression|
|Created|2017-10-13 02:14:14Z|

Link to PR: ​https://github.com/twisted/twisted/pull/914

As per the docs, it should be raising itself (Failure) in Python2, and raising the wrapped exception in Python3.

With Twisted==17.9.0, I can reproduce the issue with:
```
Python 2.7.14 (default, Sep 20 2017, 01:25:59) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from twisted.python.failure import Failure
>>> f = Failure(ValueError())
>>> g = f.trap(TypeError)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jon/.virtualenvs/crossbartest/lib/python2.7/site-packages/twisted/python/failure.py", line 359, in trap
    self.raiseException()
  File "<string>", line 2, in raiseException
ValueError
```

With Twisted==16.6.0, it works as expected.
```
Python 2.7.14 (default, Sep 20 2017, 01:25:59) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from twisted.python.failure import Failure
>>> f = Failure(ValueError())
>>> g = f.trap(TypeError)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jon/.virtualenvs/crossbartest/lib/python2.7/site-packages/twisted/python/failure.py", line 344, in trap
    raise self
twisted.python.failure.Failure: [Failure instance: Traceback (failure with no frames): <type 'exceptions.ValueError'>: 
]
```

Link to relevant documentation:
http://twisted.readthedocs.io/en/latest/core/howto/python3.html#twisted-python-failure

<details><summary>Searchable metadata</summary>

```
trac-id__9307 9307
type__release_blocker__regression release blocker: regression
reporter__jwaterhouse jwaterhouse
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__Failure_trap Failure trap
time__1507860854561504 1507860854561504
changetime__1508138264796696 1508138264796696
version__None None
owner__Mark_Williams__mrw_____ Mark Williams <mrw@...>

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="jwaterhouse's avatar" src="https://avatars.githubusercontent.com/u/97921433?s=50" width="50" height="50">](https://github.com/jwaterhouse)<a name="note_1"></a>|@jwaterhouse commented|
|-|-|

Link to PR: https://github.com/twisted/twisted/pull/914

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_4"></a>|@exarkun commented|
|-|-|

This looks like it was introduced by ticket:5519.

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_6"></a>|@markrwilliams commented|
|-|-|

https://github.com/twisted/twisted/pull/914#pullrequestreview-69408098

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_7"></a>|@markrwilliams set owner to @markrwilliams<br>@markrwilliams set status to `closed`|
|-|-|

In changeset b64f480eed7a68672cf8f176d6d520c509c6097d
```
#!CommitTicketReference repository="" revision="b64f480eed7a68672cf8f176d6d520c509c6097d"
Merge pull request #914 from jwaterhouse/fix_9307_failure_trap

Fix 9307 - raise self (Failure) in python2, wrapped exception in python3

Author: jwaterhouse

Reviewer: exarkun, markrwilliams

Fixes: ticket:9307

Failure.trap() again raises itself instead of its wrapped exception in
Python 2.7.
```
