### ISSUE TITLE
twisted-17.9.0 test failures with openssh-7.6_p1

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9311]
|[<img alt="dol-sen's avatar" src="https://avatars.githubusercontent.com/u/950866?s=50" width="50" height="50">](https://github.com/dol-sen)| @dol-sen reported|
|-|-|
|Trac ID|trac#9311|
|Type|defect|
|Created|2017-10-25 21:04:54Z|

An up to date Gentoo system.  The following tests fail.  The openssl fail is common to all versions of openssh/openssl.  It appears to be a unit test error in the expected string.

All but the openssl failure were fixed with openssh-7.5_p1.

===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/twisted/conch/test/test_cftp.py", line 1485, in check
    self.assertEqual(result[2], 0)
  File "/usr/lib64/python3.6/site-packages/twisted/trial/_synctest.py", line 432, in assertEqual
    super(_Assertions, self).assertEqual(first, second, msg)
  File "/usr/lib64/python3.6/unittest/case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib64/python3.6/unittest/case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
twisted.trial.unittest.FailTest: 255 != 0

twisted.conch.test.test_cftp.OurServerSftpClientTests.test_extendedAttributes
===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/twisted/trial/_synctest.py", line 432, in assertEqual
    super(_Assertions, self).assertEqual(first, second, msg)
  File "/usr/lib64/python3.6/unittest/case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib64/python3.6/unittest/case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
twisted.trial.unittest.FailTest: None != b'test\n'

twisted.conch.test.test_conch.OpenSSHClientForwardingTests.test_localToRemoteForwarding
twisted.conch.test.test_conch.OpenSSHClientForwardingTests.test_localToRemoteForwardingV6
twisted.conch.test.test_conch.OpenSSHClientForwardingTests.test_remoteToLocalForwarding
===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/twisted/test/test_sslverify.py", line 3079, in test_dependencyMissingWarning
    (expectedMessage, "", 0))
  File "/usr/lib64/python3.6/site-packages/twisted/trial/_synctest.py", line 432, in assertEqual
    super(_Assertions, self).assertEqual(first, second, msg)
  File "/usr/lib64/python3.6/unittest/case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib64/python3.6/unittest/case.py", line 1038, in assertTupleEqual
    self.assertSequenceEqual(tuple1, tuple2, msg, seq_type=tuple)
  File "/usr/lib64/python3.6/unittest/case.py", line 1009, in assertSequenceEqual
    self.fail(msg)
twisted.trial.unittest.FailTest: Tuples differ: ("You[74 chars]t of service_identity halted; None in sys.modu[302 chars]', 0) != ("You[74 chars]t of 'service_identity' halted; None in sys.mo[304 chars]', 0)

First differing element 0:
"You [73 chars]t of service_identity halted; None in sys.modu[294 chars]ted."
"You [73 chars]t of 'service_identity' halted; None in sys.mo[296 chars]ted."

Diff is 763 characters long. Set self.maxDiff to None to see it.

twisted.test.test_sslverify.SelectVerifyImplementationTests.test_dependencyMissingWarning
===============================================================================
[ERROR]
Traceback (most recent call last):
Failure: twisted.conch.error.ConchError: ('exit code was not 0: 255', None)

twisted.conch.test.test_conch.OpenSSHClientForwardingTests.test_exec
twisted.conch.test.test_conch.OpenSSHClientRekeyTests.test_clientRekey
twisted.conch.test.test_conch.OpenSSHKeyExchangeTests.test_DH_GROUP14
twisted.conch.test.test_conch.OpenSSHKeyExchangeTests.test_DH_GROUP_EXCHANGE_SHA1
twisted.conch.test.test_conch.OpenSSHKeyExchangeTests.test_DH_GROUP_EXCHANGE_SHA256
twisted.conch.test.test_conch.OpenSSHKeyExchangeTests.test_ECDHSHA256
twisted.conch.test.test_conch.OpenSSHKeyExchangeTests.test_ECDHSHA384
twisted.conch.test.test_conch.OpenSSHKeyExchangeTests.test_ECDHSHA521
===============================================================================
[ERROR]
Traceback (most recent call last):
Failure: twisted.trial.util.DirtyReactorAggregateError: Reactor was unclean.
DelayedCalls: (set twisted.internet.base.DelayedCall.debug = True to debug)
<DelayedCall 0x7f327b300d30 [0.043089866638183594s] called=0 cancelled=0 ConchTestForwardingProcess._connect()>

twisted.conch.test.test_conch.OpenSSHClientForwardingTests.test_localToRemoteForwarding
===============================================================================
[ERROR]
Traceback (most recent call last):
Failure: twisted.trial.util.DirtyReactorAggregateError: Reactor was unclean.
DelayedCalls: (set twisted.internet.base.DelayedCall.debug = True to debug)
<DelayedCall 0x7f327bd7a470 [0.042200326919555664s] called=0 cancelled=0 ConchTestForwardingProcess._connect()>

twisted.conch.test.test_conch.OpenSSHClientForwardingTests.test_localToRemoteForwardingV6
===============================================================================
[ERROR]
Traceback (most recent call last):
Failure: twisted.trial.util.DirtyReactorAggregateError: Reactor was unclean.
DelayedCalls: (set twisted.internet.base.DelayedCall.debug = True to debug)
<DelayedCall 0x7f327b30be10 [0.04962301254272461s] called=0 cancelled=0 ConchTestForwardingProcess._connect()>

twisted.conch.test.test_conch.OpenSSHClientForwardingTests.test_remoteToLocalForwarding
-------------------------------------------------------------------------------
Ran 11622 tests in 255.755s

FAILED (skips=1417, failures=5, errors=11, successes=10192)

<details><summary>Searchable metadata</summary>

```
trac-id__9311 9311
type__defect defect
reporter__dol_sen dol-sen
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__None None
time__1508965494733802 1508965494733802
changetime__1508977752295739 1508977752295739
version__None None
owner__shylent shylent

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="dol-sen's avatar" src="https://avatars.githubusercontent.com/u/950866?s=50" width="50" height="50">](https://github.com/dol-sen)|@dol-sen set owner to shylent|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="dol-sen's avatar" src="https://avatars.githubusercontent.com/u/950866?s=50" width="50" height="50">](https://github.com/dol-sen)<a name="note_2"></a>|@dol-sen commented|
|-|-|

the openssl error in that list is fixed in git already.
https://github.com/twisted/twisted/commit/e58956fe12af7b41f6c1735ba7b14cba69e82a5e

So just the openssh errors
