### ISSUE TITLE
twisted.web.server.Request is no longer hashable

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9314]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)| @twm reported|
|-|-|
|Trac ID|trac#9314|
|Type|release blocker: regression|
|Created|2017-11-05 23:46:10Z|
|Branch|https://github.com/twisted/twisted/tree/web-request-hashable-9314|

This breaks my code, specifically this code (a simple implementation of broadcast via Server Sent Events):

```
class Spigot(object):
    log = Logger()
    heartbeatInterval = 30
 
    def __init__(self, reactor):
        self.reactor = reactor
        self.requests = {}
 
    def has_subscribers(self):
        return bool(self.requests)
 
    def register(self, request):
        """
        Subscribe a request to have the event stream written to it.
        """
        loop = task.LoopingCall(self._heartbeat, request)
        loop.clock = self.reactor
        loop.start(self.heartbeatInterval)
 
        # This is used to cleanly terminate the request when the server is
        # shutting down.
        finisher = defer.Deferred()
 
        self.requests[request] = (loop, finisher)
        request.notifyFinish().addBoth(self._cleanup, request)
 
        return finisher
 
    def _heartbeat(self, request):
        """
        Called periodically to write a keepalive to the connection.
        """
        request.write(':boop\n')
 
    def _cleanup(self, _, request):
        """
        Called when the request terminates (whether cleanly or not).  Stop the
        heartbeat loop associated with the request and remove it from the set
        of active requests.
        """
        loop, finisher = self.requests.pop(request)
        loop.stop()
 
    def emit(self, event, data):
        self.log.info("Emitting {event} {data!r} -> {count} subscribers".format(
                      event=event, data=data, count=len(self.requests)))
        message = 'event:{}\ndata:{}\n\n'.format(event, json.dumps(data))
        for request, (loop, _) in self.requests.items():
            request.write(message)
            loop.reset()
 
    def shutdown(self):
        ds = []
        for request, (loop, finisher) in self.requests.items():
            ds.append(request.notifyFinish())
            finisher.callback(None)
        return defer.gatherResults(ds)
```

When `Spigot.register(request)` is called the following traceback results:

```
 2017-11-05 15:26:39-0800 [-] Unhandled Error
        Traceback (most recent call last):
          File ".../.tox/run/local/lib/python2.7/site-packages/twisted/web/http.py", line 866, in requestReceived
            self.process()
          File ".../.tox/run/local/lib/python2.7/site-packages/twisted/web/server.py", line 195, in process
            self.render(resrc)
          File ".../.tox/run/local/lib/python2.7/site-packages/twisted/web/server.py", line 255, in render
            body = resrc.render(self)
          File ".../.tox/run/local/lib/python2.7/site-packages/klein/resource.py", line 91, in render
            **kwargs)
        --- <exception caught here> ---
          File ".../.tox/run/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
            result = f(*args, **kw)
          File ".../.tox/run/local/lib/python2.7/site-packages/klein/app.py", line 79, in execute_endpoint
            return endpoint_f(self._instance, *args, **kwargs)
          File ".../.tox/run/local/lib/python2.7/site-packages/klein/app.py", line 162, in _f
            return call(instance, f, request, *a, **kw)
          File ".../.tox/run/local/lib/python2.7/site-packages/klein/app.py", line 138, in call
            return f(instance, *args, **kwargs)
          File ".../.tox/run/local/lib/python2.7/site-packages/dashboard/__init__.py", line 238, in spigot
            return self.spigot.register(request)
          File ".../.tox/run/local/lib/python2.7/site-packages/dashboard/__init__.py", line 998, in register
            self.requests[request] = (loop, finisher)
        exceptions.TypeError: unhashable instance
```

Presumably this is because Request is now an attrs class? Full `pip freeze` from this virtualenv:

```
asn1crypto==0.23.0
attrs==17.2.0
Automat==0.6.0
certifi==2017.11.5
cffi==1.11.2
chardet==3.0.4
constantly==15.1.0
cryptography==2.1.3
dashboard==1.0.0
enum34==1.1.6
hyperlink==17.3.1
idna==2.6
incremental==17.5.0
ipaddress==1.0.18
Jinja2==2.7.1
klein==0.2.1
MarkupSafe==1.0
mock==1.0.1
Pillow==2.9.0
pyasn1==0.3.7
pyasn1-modules==0.1.5
pycparser==2.18
pyOpenSSL==17.3.0
requests==2.18.4
service-identity==17.0.0
six==1.11.0
treq==17.8.0
Twisted==17.9.0
urllib3==1.22
Werkzeug==0.12.2
zope.interface==4.4.3
```

<details><summary>Searchable metadata</summary>

```
trac-id__9314 9314
type__release_blocker__regression release blocker: regression
reporter__twm twm
priority__normal normal
milestone__None None
branch__web_request_hashable_9314 web-request-hashable-9314
branch_author__ 
status__closed closed
resolution__fixed fixed
component__web web
keywords__None None
time__1509925570244569 1509925570244569
changetime__1511427580903068 1511427580903068
version__None None
owner__twm twm

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)|@twm set owner to @twm<br>@twm set status to `assigned`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_2"></a>|@twm commented|
|-|-|

It doesn't look like attrs is involved anywhere in the Request inheritance tree. However, Request is hashable if `TWISTED_NEWSTYLE=yes` is set.

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_3"></a>|@twm commented|
|-|-|

`twisted.web.http.Request`, which `t.w.s.Request` subclasses, overrides `__eq__` and `__ne__`, which on an old-style class makes the class unhashable:

```
>>> class HashableMaybe():
...     def __eq__(self, other):
...         return NotImplemented
...     def __ne__(self, other):
...         return NotImplemented
... 
>>> hash(HashableMaybe())
Traceback (most recent call last):
  File "<console>", line 1, in <module>
TypeError: unhashable instance
>>> class HashableProbably(object):
...     def __eq__(self, other):
...         return NotImplemented
...     def __ne__(self, other):
...         return NotImplemented
... 
>>> hash(HashableProbably())
8748751673973
```

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_4"></a>|@twm commented|
|-|-|

https://github.com/twisted/twisted/pull/923

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_6"></a>|@markrwilliams commented|
|-|-|

https://github.com/twisted/twisted/pull/923#pullrequestreview-74362010

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_7"></a>|@markrwilliams set status to `closed`|
|-|-|

In changeset bb7a3e264e67342d57e7c6d4412280562700054c
```
#!CommitTicketReference repository="" revision="bb7a3e264e67342d57e7c6d4412280562700054c"
Merge pull request #923 from twisted/web-request-hashable-9314

Author: twm

Reviewer: markrwilliams

Fixes: ticket:9314

twisted.web.server.Request is hashable in Python 2 again.
```
