### ISSUE TITLE
twisted.python.monkey.MonkeyPatcher can't patch staticmethods

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9331]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)| @markrwilliams reported|
|-|-|
|Trac ID|trac#9331|
|Type|defect|
|Created|2017-11-20 23:05:32Z|

Sometimes it's convenient to attach a ```staticmethod``` to a class and then patch it out in a test, like so:

```python
from twisted.trial import unittest

def free():
    print("A free function.")

class _ClassToTest(object):
    _someMethod = staticmethod(free)
    def api(self):
        self._someMethod()


class TestClass(unittest.SynchronousTestCase):
    def test_api(self):
        def fake(self):
            print("A fake.")
        self.patch(_ClassToTest, "_someMethod", fake)
    def test_broken(self):
        _ClassToTest.api()
```

But `test_api` breaks `test_broken`:

```
broken
  TestClass
    test_api ...                                                           [OK]
    test_broken ...                                                     [ERROR]

===============================================================================
[ERROR]
Traceback (most recent call last):
  File "broken.py", line 18, in test_broken
    _ClassToTest().api()
  File "broken.py", line 9, in api
    self._someMethod()
exceptions.TypeError: free() takes no arguments (1 given)

f.TestClass.test_broken
-------------------------------------------------------------------------------
Ran 2 tests in 0.015s
```

Because `twisted.python.monkey.MonkeyPatcher.addPatch` retrieves the original object with `getattr` and `staticmethod` descriptors return their wrapped free function when accessed on a class, `patch` can't patch `staticmethod`s.

One solution would be to `MonkeyPatch`'s use of `getattr` and `setattr` with `__dict__` munging.

<details><summary>Searchable metadata</summary>

```
trac-id__9331 9331
type__defect defect
reporter__markrwilliams markrwilliams
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__trial trial
keywords__None None
time__1511219132801019 1511219132801019
changetime__1511219568721385 1511219568721385
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_1"></a>|@markrwilliams commented|
|-|-|

Note that accessing objects via `__dict__` would be an incompatible change because some tests might rely on the current behavior.
