### ISSUE TITLE
PostfixTCPMapServer raises exception handling error in python 3

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9335]
|[<img alt="albertkoch's avatar" src="https://avatars.githubusercontent.com/u/2699070?s=50" width="50" height="50">](https://github.com/albertkoch)| @albertkoch reported|
|-|-|
|Trac ID|trac#9335|
|Type|defect|
|Created|2017-11-22 21:57:31Z|

When using the PostfixTCPMapServer, the server raises an exception when handling an exception raised by its factory `get` method in python 3. The server should send a 400 code to the client. This issue was not observed in python 2.

Code example to reproduce:

```python
from twisted.protocols.postfix import PostfixTCPMapServer

# Factory that raises an error on key lookup
class TestFactory:
    def get(self, key):
        raise Exception('This is a test error')

# Transport that should receive result
class TestTransport:
    def write(self, value):
        assert(value == b'400 This is a test error\n')

# Setup Server
server = PostfixTCPMapServer()
server.factory = TestFactory()
server.transport = TestTransport()

# Run test
server.lineReceived('get example')
```

This runs fine under python 2.7, but fails under python 3.6:

```
Unhandled Error
Traceback (most recent call last):
  File "test.py", line 20, in <module>
    server.lineReceived('get example')
  File "/usr/local/lib/python3.6/site-packages/twisted/protocols/postfix.py", line 84, in lineReceived
    f(params)
  File "/usr/local/lib/python3.6/site-packages/twisted/protocols/postfix.py", line 96, in do_get
    d.addCallbacks(self._cbGot, self._cbNot)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 310, in addCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python3.6/site-packages/twisted/protocols/postfix.py", line 102, in _cbNot
    self.sendCode(400, fail.getErrorMessage())
  File "/usr/local/lib/python3.6/site-packages/twisted/protocols/postfix.py", line 67, in sendCode
    self.sendLine(intToBytes(code) + b' ' + message)
builtins.TypeError: can't concat str to bytes
```

Packages installed:

```
attrs==17.3.0
Automat==0.6.0
constantly==15.1.0
hyperlink==17.3.1
incremental==17.5.0
six==1.11.0
Twisted==17.9.0
zope.interface==4.4.3
```

<details><summary>Searchable metadata</summary>

```
trac-id__9335 9335
type__defect defect
reporter__albertkoch albertkoch
priority__normal normal
milestone__Python_3_x Python-3.x
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__None None
time__1511387851374243 1511387851374243
changetime__1511563436946969 1511563436946969
version__None None
owner__Craig_Rodrigues__rodrigc_____ Craig Rodrigues <rodrigc@...>

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_1"></a>|@rodrigc set status to `closed`|
|-|-|

Your code example is wrong.  This line:

```
# Run test
server.lineReceived('get example')
```

should be:

```

# Run test
server.lineReceived(b'get example')
```

because lineReceived must take bytes, not unicode.
Remember, by default, string literals are unicode on Python 3, but bytes on Python 2.

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)|@rodrigc set status to `reopened`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_3"></a>|@rodrigc commented|
|-|-|

While your code example is wrong, you found some legitimate errors in this code, so I'm reopening.

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_5"></a>|@rodrigc commented|
|-|-|

https://github.com/twisted/twisted/pull/930

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_6"></a>|@rodrigc commented|
|-|-|

https://github.com/twisted/twisted/pull/930#pullrequestreview-78985005

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_7"></a>|@rodrigc set owner to @rodrigc<br>@rodrigc set status to `closed`|
|-|-|

In changeset 03dcdfb5933c4f83ce6aad3f4bdf080cda65584c
```
#!CommitTicketReference repository="" revision="03dcdfb5933c4f83ce6aad3f4bdf080cda65584c"
Merge pull request #930 from twisted/9335-rodrigc-postfix-py3

Author: rodrigc
Reviewer: albertkoch
Fixes: ticket:9335

Fix postfix on Python 3
```
