### ISSUE TITLE
conch command with errors  triggers TypeError on Python 3

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9344]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)| @rodrigc reported|
|-|-|
|Trac ID|trac#9344|
|Type|defect|
|Created|2017-11-29 18:44:49Z|

If I do:

```
conch localhost 'nonexistentcommand'
```

I get:

```
Unhandled Error
               Traceback (most recent call last):
                                                   File "/Users/crodrigues/twisted6/src/twisted/python/context.py", line 122, in callWithContext
                                                                                                                                                    return self.currentContext().callWithContext(ctx, func, *args, **kw)
                                                             File "/Users/crodrigues/twisted6/src/twisted/python/context.py", line 85, in callWithContext
                                                                                                                                                             return func(*args,**kw)
                         File "/Users/crodrigues/twisted6/src/twisted/conch/ssh/service.py", line 45, in packetReceived
                                                                                                                           return f(packet)
                                                                                                                                             File "/Users/crodrigues/twisted6/src/twisted/conch/ssh/connection.py", line 273, in ssh_CHANNEL_EXTENDED_DATA
                                                                                                 log.callWithLogger(channel, channel.extReceived, typeCode, data)
    --- <exception caught here> ---
                                     File "/Users/crodrigues/twisted6/src/twisted/python/log.py", line 103, in callWithLogger
                                                                                                                                 return callWithContext({"system": lp}, func, *args, **kw)
                               File "/Users/crodrigues/twisted6/src/twisted/python/log.py", line 86, in callWithContext
                                                                                                                           return context.call({ILogContext: newCtx}, func, *args, **kw)
                             File "/Users/crodrigues/twisted6/src/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/Users/crodrigues/twisted6/src/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/Users/crodrigues/twisted6/src/twisted/conch/scripts/conch.py", line 468, in extReceived
    sys.stderr.write(data)
builtins.TypeError: write() argument must be str, not bytes
```

<details><summary>Searchable metadata</summary>

```
trac-id__9344 9344
type__defect defect
reporter__rodrigc rodrigc
priority__normal normal
milestone__Python_3_x Python-3.x
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__conch conch
keywords__None None
time__1511981089439993 1511981089439993
changetime__1521626251180238 1521626251180238
version__None None
owner__Craig_Rodrigues__rodrigc_____ Craig Rodrigues <rodrigc@...>

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_1"></a>|@rodrigc commented|
|-|-|

https://github.com/twisted/twisted/pull/937

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_2"></a>|@rodrigc commented|
|-|-|

Approved by wiml: https://github.com/twisted/twisted/pull/937#pullrequestreview-105459615

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_3"></a>|@rodrigc set owner to @rodrigc<br>@rodrigc set status to `closed`|
|-|-|

In changeset 8b3059401f362277ee9774462218daa7f1cb7bae
```
#!CommitTicketReference repository="" revision="8b3059401f362277ee9774462218daa7f1cb7bae"
Merge pull request #937 from twisted/9344-rodrigc-conch-py3

Author: rodrigc
Reviewer: wiml
Fixes: ticket:9344

Fix a few bytes/unicode issues in conch script
```
