### ISSUE TITLE
ResourceWarning from dist's LocalWorker

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9355]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)| @markrwilliams reported|
|-|-|
|Trac ID|trac#9355|
|Type|defect|
|Created|2017-12-19 21:05:39Z|

```twisted.trial._dist.LocalWorker``` doesn't close its ```testLog``` file.  The resulting ```ResourceWarning``` can cause other tests to fail:

```
[FAIL]
Traceback (most recent call last):
  File "/buildslave/debian9-py3.5/Twisted/build/py35-alldeps-nocov-posix/lib/python3.5/site-packages/twisted/trial/test/test_assertions.py", line 1287, in test_nestedDeprecation
    "Unexpected warnings: {}".format(warningsShown))
  File "/buildslave/debian9-py3.5/Twisted/build/py35-alldeps-nocov-posix/lib/python3.5/site-packages/twisted/trial/_synctest.py", line 432, in assertEqual
    super(_Assertions, self).assertEqual(first, second, msg)
  File "/usr/lib/python3.5/unittest/case.py", line 821, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.5/unittest/case.py", line 814, in _baseAssertEqual
    raise self.failureException(msg)
twisted.trial.unittest.FailTest: 3 != 1 : Unexpected warnings: [{'category': <class 'ResourceWarning'>, 'lineno': 1278, 'message': "unclosed file <_io.BufferedWriter name='/buildslave/debian9-py3.5/Twisted/_trial_temp/twisted.trial._dist.test.test_di/DistTrialRunnerTests/test_runStopAfterTests/76ydn2k5/temp/0/test.log'>", 'filename': '/buildslave/debian9-py3.5/Twisted/build/py35-alldeps-nocov-posix/lib/python3.5/site-packages/twisted/trial/test/test_assertions.py'}, {'category': <class 'ResourceWarning'>, 'lineno': 1278, 'message': "unclosed file <_io.BufferedWriter name='/buildslave/debian9-py3.5/Twisted/_trial_temp/twisted.trial._dist.test.test_di/DistTrialRunnerTests/test_runWaitForProcessesDeferred/j6khiv38/temp/0/test.log'>", 'filename': '/buildslave/debian9-py3.5/Twisted/build/py35-alldeps-nocov-posix/lib/python3.5/site-packages/twisted/trial/test/test_assertions.py'}, {'category': <class 'DeprecationWarning'>, 'lineno': 1277, 'message': 'twisted.trial.test.test_assertions.oldMethod was deprecated in Twisted 8.0.0', 'filename': '/buildslave/debian9-py3.5/Twisted/build/py35-alldeps-nocov-posix/lib/python3.5/site-packages/twisted/trial/test/test_assertions.py'}]

twisted.trial.test.test_assertions.CallDeprecatedTests.test_nestedDeprecation
```

```LocalWorker.testLog``` runs in the main ```dist``` process, so it should be closed just like ```outLog```

<details><summary>Searchable metadata</summary>

```
trac-id__9355 9355
type__defect defect
reporter__markrwilliams markrwilliams
priority__normal normal
milestone__Eliminate_ResourceWarnings Eliminate ResourceWarnings
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__trial trial
keywords__None None
time__1513717539419109 1513717539419109
changetime__1519146049351611 1519146049351611
version__None None
owner__markrwilliams markrwilliams

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_1"></a>|@markrwilliams commented|
|-|-|

https://github.com/twisted/twisted/pull/944

**Comment by twisted-trac** [comment]
|[<img alt="moshez's avatar" src="https://avatars.githubusercontent.com/u/422703?s=50" width="50" height="50">](https://github.com/moshez)|@moshez set owner to @markrwilliams|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_3"></a>|@markrwilliams set status to `closed`|
|-|-|

In changeset e2d2c06f07c1918dad0ba0bc4016d1fd1fc15b58
```
#!CommitTicketReference repository="" revision="e2d2c06f07c1918dad0ba0bc4016d1fd1fc15b58"
Merge pull request #944 from twisted/9355-close-localworker-testlog

Author: markrwilliams
    
Reviewer: moshez
    
Fixes: ticket:9355

twisted.trial._dist.LocalWorker closes its testLog file, eliminating a ResourceWarning.
```

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_4"></a>|@exarkun commented|
|-|-|

This appears to be unfixed as this test just failed on CI:

```
===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/buildslave/fedora24-python-3.5/Twisted/build/py35-alldeps-nocov-posix/lib/python3.5/site-packages/twisted/trial/test/test_assertions.py", line 1287, in test_nestedDeprecation
    "Unexpected warnings: {}".format(warningsShown))
  File "/buildslave/fedora24-python-3.5/Twisted/build/py35-alldeps-nocov-posix/lib/python3.5/site-packages/twisted/trial/_synctest.py", line 432, in assertEqual
    super(_Assertions, self).assertEqual(first, second, msg)
  File "/usr/lib64/python3.5/unittest/case.py", line 838, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib64/python3.5/unittest/case.py", line 831, in _baseAssertEqual
    raise self.failureException(msg)
twisted.trial.unittest.FailTest: 2 != 1 : Unexpected warnings: [{'category': <class 'ResourceWarning'>, 'filename': '/buildslave/fedora24-python-3.5/Twisted/build/py35-alldeps-nocov-posix/lib/python3.5/site-packages/twisted/python/deprecate.py', 'message': "unclosed file <_io.BufferedWriter name='/buildslave/fedora24-python-3.5/Twisted/_trial_temp/twisted.trial._dist.test.test_di/DistTrialRunnerTests/test_runStopAfterTests/ohj61qsx/temp/0/test.log'>", 'lineno': 288}, {'category': <class 'DeprecationWarning'>, 'filename': '/buildslave/fedora24-python-3.5/Twisted/build/py35-alldeps-nocov-posix/lib/python3.5/site-packages/twisted/trial/test/test_assertions.py', 'message': 'twisted.trial.test.test_assertions.oldMethod was deprecated in Twisted 8.0.0', 'lineno': 1277}]

twisted.trial.test.test_assertions.CallDeprecatedTests.test_nestedDeprecation
-------------------------------------------------------------------------------
```

https://buildbot.twistedmatrix.com/builders/fedora24-py3.5/builds/1194/steps/select/logs/problems

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_5"></a>|@exarkun commented|
|-|-|

And again immediately after (notice sequential build numbers): https://buildbot.twistedmatrix.com/builders/fedora24-py3.5/builds/1195/steps/poll/logs/problems

```
===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/buildslave/fedora24-python-3.5/Twisted/build/py35-alldeps-nocov-posix/lib/python3.5/site-packages/twisted/trial/test/test_assertions.py", line 1287, in test_nestedDeprecation
    "Unexpected warnings: {}".format(warningsShown))
  File "/buildslave/fedora24-python-3.5/Twisted/build/py35-alldeps-nocov-posix/lib/python3.5/site-packages/twisted/trial/_synctest.py", line 432, in assertEqual
    super(_Assertions, self).assertEqual(first, second, msg)
  File "/usr/lib64/python3.5/unittest/case.py", line 838, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib64/python3.5/unittest/case.py", line 831, in _baseAssertEqual
    raise self.failureException(msg)
twisted.trial.unittest.FailTest: 2 != 1 : Unexpected warnings: [{'lineno': 300, 'message': "unclosed file <_io.BufferedWriter name='/buildslave/fedora24-python-3.5/Twisted/_trial_temp/twisted.trial._dist.test.test_di/DistTrialRunnerTests/test_runStopAfterTests/2l24xntq/temp/0/test.log'>", 'filename': '/buildslave/fedora24-python-3.5/Twisted/build/py35-alldeps-nocov-posix/lib/python3.5/site-packages/twisted/python/deprecate.py', 'category': <class 'ResourceWarning'>}, {'lineno': 1277, 'message': 'twisted.trial.test.test_assertions.oldMethod was deprecated in Twisted 8.0.0', 'filename': '/buildslave/fedora24-python-3.5/Twisted/build/py35-alldeps-nocov-posix/lib/python3.5/site-packages/twisted/trial/test/test_assertions.py', 'category': <class 'DeprecationWarning'>}]

twisted.trial.test.test_assertions.CallDeprecatedTests.test_nestedDeprecation
-------------------------------------------------------------------------------
```

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_6"></a>|@markrwilliams commented|
|-|-|

I believe the PR for this ticket fixed the resource leak in `disttrial` itself by closing all the files opened in `LocalWorker.connectionMade` in `LocalWorker.connectionLost`.

It looks like the spurious build failures continue, however, because `disttrial`'s tests don't always call `LocalWorker.connectionLost`.  For example, `twisted.trial._dist.test.test_disttrial.DistTrialRunnerTests.test_runStopAfterTests` (mentioned in [#9355](https://github.com/twisted/twisted/issues/9355)#comment:4) uses a `FakeReactor` that calls a `LocalWorker` instance's `connectionMade` (via `makeConnection`) but never its `connectionLost`.

I think all the tests that use `FakeReactor` in `test_disttrial` leak resources in this way.  There might be other issues.  How about another ticket: [#9382](https://github.com/twisted/twisted/issues/9382)
