### ISSUE TITLE
`trial -jN ...` crashes if a test fails with a non-ASCII failure

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9378]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#9378|
|Type|release blocker: regression|
|Created|2018-02-19 15:44:26Z|

```
Unhandled Error
Traceback (most recent call last):
  File ".../site-packages/twisted/protocols/amp.py", line 1043, in _commandReceived
    deferred = self.dispatchCommand(box)
  File ".../site-packages/twisted/protocols/amp.py", line 1101, in dispatchCommand
    return maybeDeferred(responder, box)
  File ".../site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File ".../site-packages/twisted/protocols/amp.py", line 1188, in doit
    return maybeDeferred(aCallable, **kw).addCallback(
--- <exception caught here> ---
  File ".../site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File ".../site-packages/twisted/trial/_dist/worker.py", line 50, in run
    suite.run(self._result)
  File ".../site-packages/twisted/trial/runner.py", line 230, in run
    TestSuite.run(self, result)
  File ".../site-packages/twisted/trial/_asyncrunner.py", line 38, in run
    test(result)
  File "/usr/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File ".../site-packages/twisted/trial/runner.py", line 189, in run
    super(LoggedSuite, self).run(result)
  File ".../site-packages/twisted/trial/_asyncrunner.py", line 38, in run
    test(result)
  File ".../site-packages/unittest2/case.py", line 673, in __call__
    return self.run(*args, **kwds)
  File ".../site-packages/testtools/testcase.py", line 671, in run
    return run_test.run(result)
  File ".../site-packages/testtools/runtest.py", line 80, in run
    return self._run_one(actual_result)
  File ".../site-packages/testtools/runtest.py", line 94, in _run_one
    return self._run_prepared_result(ExtendedToOriginalDecorator(result))
  File ".../site-packages/testtools/runtest.py", line 115, in _run_prepared_result
    handler(self.case, self.result, e)
  File ".../site-packages/testtools/testcase.py", line 634, in _report_failure
    result.addFailure(self, details=self.getDetails())
  File ".../site-packages/testtools/testresult/real.py", line 1404, in addFailure
    return self.decorated.addFailure(test, err)
  File ".../site-packages/twisted/trial/_dist/workerreporter.py", line 100, in addFailure
    fail = failure.getErrorMessage().encode("utf-8")
exceptions.UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 52: ordinal not in range(128)
```

<details><summary>Searchable metadata</summary>

```
trac-id__9378 9378
type__release_blocker__regression release blocker: regression
reporter__exarkun exarkun
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__trial trial
keywords__None None
time__1519055066982570 1519055066982570
changetime__1560774763203003 1560774763203003
version__None None
owner__Jean_Paul_Calderone__exarkun_____ Jean-Paul Calderone <exarkun@...>

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

https://github.com/twisted/twisted/pull/959

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_2"></a>|@exarkun commented|
|-|-|

Note: This behavior is a regression introduced by [#8943](https://github.com/twisted/twisted/issues/8943) / 5b5e04a02faea2be936d9d36617d5958c7a321cb which replaced a bare `failure.getErrorMessage()` call with `failure.getErrorMessage().encode("utf-8")`.

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_4"></a>|@markrwilliams commented|
|-|-|

https://github.com/twisted/twisted/pull/959#pullrequestreview-97683478

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_5"></a>|@exarkun set owner to @exarkun<br>@exarkun set status to `closed`|
|-|-|

In changeset c16491942672d5d4d589894fc2a878eb80abed44
```
#!CommitTicketReference repository="" revision="c16491942672d5d4d589894fc2a878eb80abed44"
Merge pull request #959 from twisted/9378.disttrial-vs-non-ascii-bytes

Author: exarkun
Reviewer: adiroiban, markrwilliams
Fixes: ticket:9378

On Python 2, avoid calling `str.encode` on exception messages for disttrial failures.  This avoids implicitly decoding them as ASCII which sometimes fails.
```

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_6"></a>|@exarkun commented|
|-|-|

I wonder if this was a duplicate of [#6865](https://github.com/twisted/twisted/issues/6865)
