### ISSUE TITLE
session caching issue in request

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9385]
|<img alt="SamyCookie's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| SamyCookie reported|
|-|-|
|Trac ID|trac#9385|
|Type|defect|
|Created|2018-02-27 10:13:04Z|

Issue: obsolete session object is kept in request cache whereas that session has been expired (new session should be created).

see test case that fails: https://github.com/twisted/twisted/compare/trunk...SamyCookie:session_caching_request?expand=1

If this behaviour is not expected, I can propose a fix for that later.

<details><summary>Searchable metadata</summary>

```
trac-id__9385 9385
type__defect defect
reporter__SamyCookie SamyCookie
priority__low low
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__web web
keywords__None None
time__1519726384886212 1519726384886212
changetime__1531402541784016 1531402541784016
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|<img alt="SamyCookie's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_1"></a>|SamyCookie commented|
|-|-|

FAIL: test_sessionCaching (test_web.RequestTests)
test_sessionCaching
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/samuel/src/twisted/src/twisted/internet/defer.py", line 151, in maybeDeferred
    result = f(*args, **kw)
  File "/home/samuel/src/twisted/src/twisted/internet/utils.py", line 201, in runWithWarningsSuppressed
    reraise(exc_info[1], exc_info[2])
  File "/home/samuel/src/twisted/src/twisted/python/compat.py", line 463, in reraise
    raise exception.with_traceback(traceback)
  File "/home/samuel/src/twisted/src/twisted/internet/utils.py", line 197, in runWithWarningsSuppressed
    result = f(*a, **kw)
  File "/home/samuel/src/twisted/src/twisted/web/test/test_web.py", line 758, in test_sessionCaching
    self.assertIsNot(session1, session3)
  File "/home/samuel/src/twisted/src/twisted/trial/_synctest.py", line 462, in assertIsNot
    raise self.failureException(msg or '%r is %r' % (first, second))
twisted.trial.unittest.FailTest: <twisted.web.server.Session object at 0x7f9574b750b8> is <twisted.web.server.Session object at 0x7f9574b750b8>
