### ISSUE TITLE
twisted.test.test_threadpool.RaceConditionTests.test_singleThread is flaky on pypy

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9399]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)| @hawkowl reported|
|-|-|
|Trac ID|trac#9399|
|Type|defect|
|Created|2018-03-26 11:45:42Z|
|Branch|https://github.com/twisted/twisted/tree/9399-singlethread|

```
[FAIL]
Traceback (most recent call last):
  File "/home/hawkowl/code/twisted/src/twisted/test/test_threadpool.py", line 616, in test_singleThread
    self.assertEqual(self.threadpool.workers, 1)
  File "/home/hawkowl/code/twisted/src/twisted/trial/_synctest.py", line 432, in assertEqual
    super(_Assertions, self).assertEqual(first, second, msg)
  File "/opt/pypy/lib-python/2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/opt/pypy/lib-python/2.7/unittest/case.py", line 506, in _baseAssertEqual
    raise self.failureException(msg)
twisted.trial.unittest.FailTest: 2 != 1
```

<details><summary>Searchable metadata</summary>

```
trac-id__9399 9399
type__defect defect
reporter__hawkowl hawkowl
priority__normal normal
milestone__PyPy_support PyPy-support
branch__9399_singlethread 9399-singlethread
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__None None
time__1522064742720040 1522064742720040
changetime__1523089620614286 1523089620614286
version__None None
owner__Amber_Brown__hawkowl_____ Amber Brown <hawkowl@...>

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_2"></a>|@glyph commented|
|-|-|

I believe that the problem here is that the test is incoherent and the property it's trying to satisfy is fundamentally impossible to provide safely.  Basically it wants to say:

- by the time this callback is running, the thread will be marked as "ready to run new stuff, not running application code any more"
- and then it runs some arbitrary application code, which might block arbitrarily long

This is a bad contract and it's probably good that we're ignoring it.

The more fundamental property attempting to be verified here is that we not create workers too _fast_.  This should be addressed with a fix to [#5298](https://github.com/twisted/twisted/issues/5298) rather than attempting to make the existing test pass.

The fix currently in the branch is ingenious, but wrong because it modifies state on `self` from the wrong concurrent context.

My suggested fix for this is to simply delete the test.  This property is nonsense and if it were possible to deprecate anything concurrency-related in a meaningful way I'd say we should deprecate it.

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_3"></a>|@hawkowl commented|
|-|-|

Removed the (useless, apparently) test! R4R.

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_4"></a>|@markrwilliams commented|
|-|-|

https://github.com/twisted/twisted/pull/982#pullrequestreview-109935225

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_5"></a>|@hawkowl set owner to @hawkowl<br>@hawkowl set status to `closed`|
|-|-|

In changeset a96bac768c40c7a0ec7cc08864d6b93865ee7c42
```
#!CommitTicketReference repository="" revision="a96bac768c40c7a0ec7cc08864d6b93865ee7c42"
Merge 9399-singlethread: Remove a flaky threading test

Author: hawkowl
Reviewers: glyph, markrwilliams
Fixes: ticket:9399
```
