### ISSUE TITLE
t.i.tcp._resolveIPv6 fails on Solaris (10 and 11) as it does not work with socket.AI_NUMERICSERV

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9404]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)| @adiroiban reported|
|-|-|
|Trac ID|trac#9404|
|Type|enhancement|
|Created|2018-04-01 22:28:38Z|

In Solaris 10 and 11 when you pass `socket.AI_NUMERICSERV` flag, it fails to get the info.

```
Python 2.7.8 (default, Mar 17 2015, 11:59:21) [C] on sunos5
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> socket.getaddrinfo('::1', 1, socket.AF_UNSPEC, 0, 0, socket.AI_NUMERICHOST)
[(26, 2, 6, '', ('::1', 1, 0, 0))]
>>> socket.getaddrinfo('::1', 1, socket.AF_UNSPEC, 0, 0, socket.AI_NUMERICHOST | socket.AI_NUMERICSERV)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
socket.gaierror: [Errno 8] node name or service name not known

```

This looks like a bug in Solaris 10/11 as even if I don't pass the flags, it fails to resolve the 'http' service

```
>>> socket.getaddrinfo('localhost', 'http', 0, 0, 0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
socket.gaierror: [Errno 9] service name not available for the specified socket type
```

-----

But since for the purpose of `_resolveIPv6`  we always pass an integer (and not a service name) the `socket.AI_NUMERICSERV` should have no effect.

I guess that we can call it just like this and it should still work as expected.

```
    result = socket.getaddrinfo(
        ip,
        usedPort,
        socket.AF_UNSPEC,  # Any family.
        0,  # Any socket type.
        0,  # Any protocol.
        socket.AI_NUMERICHOST,
        )[0][4]
```

------

BTW. I have tested the code on latest releases from AIX and HPUX and it works :)

<details><summary>Searchable metadata</summary>

```
trac-id__9404 9404
type__enhancement enhancement
reporter__adiroiban adiroiban
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__None None
time__1522621718008760 1522621718008760
changetime__1522981442296833 1522981442296833
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)|@adiroiban set owner to @adiroiban<br>@adiroiban set status to `assigned`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_2"></a>|@adiroiban removed owner<br>@adiroiban set status to `new`|
|-|-|

https://github.com/twisted/twisted/pull/985

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_3"></a>|@markrwilliams commented|
|-|-|

https://github.com/twisted/twisted/pull/985#pullrequestreview-109931850
