### ISSUE TITLE
twisted.python.compat.inet_pton() monkey-patch raises the wrong exceptions

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9409]
|[<img alt="vitaly-krugl's avatar" src="https://avatars.githubusercontent.com/u/1441066?s=50" width="50" height="50">](https://github.com/vitaly-krugl)| @vitaly-krugl reported|
|-|-|
|Trac ID|trac#9409|
|Type|defect|
|Created|2018-04-03 00:53:15Z|

Twisted versin: 17.9.0
Windows python version: 2.7.14

The twisted.python.compat.inet_pton() monkey-patch raises exceptions incompatible with Python-implemented behavior and documentation (https://docs.python.org/2/library/socket.html). The following sampling of calls raise ValueError with the twisted monkey-patch. However, python documentation and builtin `socket.inet_pton()` behavior is to raise `socket.error` exceptions in all the cases.

    socket.inet_pton(socket.AF_INET6, 'localhost')
    socket.inet_pton(socket.AF_INET6, "")
    socket.inet_pton(-1, '127.0.0.1')

Here is a sampling of one of those calls on Windows python 2.7.14 with the automatic twisted monkey-patch of socket.inet_pton() using twisted-17.9.0.
```
Traceback (most recent call last):
  File "C:\projects\pika\tests\unit\base_connection_tests.py", line 41, in test_ZZZ_remove_me
    socket.inet_pton(socket.AF_INET6, 'localhost')
  File "C:\Python27\lib\site-packages\twisted\python\compat.py", line 146, in inet_pton
    raise ValueError("Syntactically invalid address")
ValueError: Syntactically invalid address
```

Since twisted is monkey-patching the socket module using the exact same function name as the library function, it's reasonable to expect it to behave according to the documentation and be compatible with the builtin library behavior, including WRT which exceptions are raised. 

Also, haven't tried, but wondering whether the twisted.python.compat.inet_ntop() monkey-patch has similar issues.

<details><summary>Searchable metadata</summary>

```
trac-id__9409 9409
type__defect defect
reporter__vitaly_krugl vitaly-krugl
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__wontfix wontfix
component__core core
keywords__Windows_inet_pton Windows,inet_pton
time__1522716795195121 1522716795195121
changetime__1585442458116593 1585442458116593
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="Julian's avatar" src="https://avatars.githubusercontent.com/u/329822?s=50" width="50" height="50">](https://github.com/Julian)<a name="note_2"></a>|@Julian commented|
|-|-|

I just ran into this too :/

[#5895](https://github.com/twisted/twisted/issues/5895) is also relevant.

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_3"></a>|@twm set status to `closed`|
|-|-|

While this appears to be a legitimate bug, I'm closing this as we plan to remove support for Python 2.7 from Twisted as announced here: https://twistedmatrix.com/pipermail/twisted-python/2020-March/065030.html This monkey-patch is not used on Python 3.
