### ISSUE TITLE
Agent.request: Support IPv6 address literals in https:// URLs

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9433]
|[<img alt="cheungnj's avatar" src="https://avatars.githubusercontent.com/u/6911370?s=50" width="50" height="50">](https://github.com/cheungnj)| @cheungnj reported|
|-|-|
|Trac ID|trac#9433|
|Type|enhancement|
|Created|2018-04-23 19:19:30Z|

Running this snippet:
```
txipv6url.py

from twisted.web.client import Agent
from twisted.internet import defer, task

@defer.inlineCallbacks
def main(reactor):
    agent = Agent(reactor)
    yield agent.request('GET', b'https://[::1]/')

task.react(main, ())
```
produces this error:
```
> python2.7 txipv6url.py 

main function encountered error
Traceback (most recent call last):
  File "/home/username/txipv6url.py", line 9, in <module>
    task.react(main, ())
  File "/home/username/dev/tx/twisted/build/py27-alldeps-nocov-posix/local/lib/python2.7/site-packages/twisted/internet/task.py", line 908, in react
    finished = main(_reactor, *argv)
  File "/home/username/dev/tx/twisted/build/py27-alldeps-nocov-posix/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1528, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/home/username/dev/tx/twisted/build/py27-alldeps-nocov-posix/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1382, in _inlineCallbacks
    result = g.send(result)
  File "/home/username/txipv6url.py", line 7, in main
    yield agent.request('GET', 'https://[::1]/')
  File "/home/username/dev/tx/twisted/build/py27-alldeps-nocov-posix/local/lib/python2.7/site-packages/twisted/web/client.py", line 1651, in request
    endpoint = self._getEndpoint(parsedURI)
  File "/home/username/dev/tx/twisted/build/py27-alldeps-nocov-posix/local/lib/python2.7/site-packages/twisted/web/client.py", line 1635, in _getEndpoint
    return self._endpointFactory.endpointForURI(uri)
  File "/home/username/dev/tx/twisted/build/py27-alldeps-nocov-posix/local/lib/python2.7/site-packages/twisted/web/client.py", line 1510, in endpointForURI
    uri.port)
  File "/home/username/dev/tx/twisted/build/py27-alldeps-nocov-posix/local/lib/python2.7/site-packages/twisted/web/client.py", line 945, in creatorForNetloc
    trustRoot=self._trustRoot)
  File "/home/username/dev/tx/twisted/build/py27-alldeps-nocov-posix/local/lib/python2.7/site-packages/twisted/internet/_sslverify.py", line 1290, in optionsForClientTLS
    return ClientTLSOptions(hostname, certificateOptions.getContext())
  File "/home/username/dev/tx/twisted/build/py27-alldeps-nocov-posix/local/lib/python2.7/site-packages/twisted/internet/_sslverify.py", line 1153, in __init__
    self._hostnameBytes = _idnaBytes(hostname)
  File "/home/username/dev/tx/twisted/build/py27-alldeps-nocov-posix/local/lib/python2.7/site-packages/twisted/internet/_idna.py", line 30, in _idnaBytes
    return idna.encode(text)
  File "/home/username/dev/tx/twisted/build/py27-alldeps-nocov-posix/local/lib/python2.7/site-packages/idna/core.py", line 355, in encode
    result.append(alabel(label))
  File "/home/username/dev/tx/twisted/build/py27-alldeps-nocov-posix/local/lib/python2.7/site-packages/idna/core.py", line 265, in alabel
    raise IDNAError('The label {0} is not a valid A-label'.format(label))
idna.core.IDNAError: The label ::1 is not a valid A-label
```

Expected behavior:

I should be able to hit the address without any errors.

<details><summary>Searchable metadata</summary>

```
trac-id__9433 9433
type__enhancement enhancement
reporter__cheungnj cheungnj
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__web web
keywords__ipv6_https ipv6 https
time__1524511170720030 1524511170720030
changetime__1533966239331193 1533966239331193
version__None None
owner__ryban ryban
cc__twm
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_4"></a>|@twm commented|
|-|-|

It should be noted that all works as expected with the URL `http://[::1]/`. The actual issue seems to be within the TLS certificate validation machinery.

**Comment by twisted-trac** [comment]
|[<img alt="ryban's avatar" src="https://avatars.githubusercontent.com/u/1617326?s=50" width="50" height="50">](https://github.com/ryban)<a name="note_5"></a>|@ryban commented|
|-|-|

I PR'd the changes. Tests are failing because we are lacking service_identity support for verifying ip addresses.

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_6"></a>|@twm set owner to @ryban|
|-|-|

Reviewed here: https://github.com/twisted/twisted/pull/1028#pullrequestreview-133462797

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_8"></a>|@twm set status to `closed`|
|-|-|

In changeset e1c380d8ce0acaadfa16b6332f463dd404a284fb
```
#!CommitTicketReference repository="" revision="e1c380d8ce0acaadfa16b6332f463dd404a284fb"
Merge pull request #1028 from ryban/9433-cheungnj-optionsForTLS

Author: ryban, cheungnj
Reviewer: twm
Fixes: ticket:9433

ClientTLSOptions will no longer raise an IDNAError when given an IPv6
address as a hostname, permitting lower levels to handle it (though they
don't yet).
```

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)|@twm set status to `reopened`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_11"></a>|@twm commented|
|-|-|

The above resolution was an artifact of an (unsuccessful) attempt to satisfy the branch protection on trunk with a minor change to the newsfile. I am going to create another PR with this change and merge it.

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_12"></a>|@twm set status to `closed`|
|-|-|

In changeset 054bf3e6433dc8f85117eb92256acc6b57ad519d
```
#!CommitTicketReference repository="" revision="054bf3e6433dc8f85117eb92256acc6b57ad519d"
Merge pull request #1047 from twisted/9433-allow-ipv6-in-https-urls-merge

Author: ryban, cheungnj
Reviewer: twm
Fixes: ticket:9433

ClientTLSOptions will no longer raise an IDNAError when given an IPv6
address as a hostname, permitting lower levels to handle it (though they
don't yet).
```
