### ISSUE TITLE
twisted.conch.ssh.keys.Key.public() busted on public keys

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9441]
|[<img alt="wiml's avatar" src="https://avatars.githubusercontent.com/u/156891?s=50" width="50" height="50">](https://github.com/wiml)| @wiml reported|
|-|-|
|Trac ID|trac#9441|
|Type|defect|
|Created|2018-05-09 23:24:50Z|

The [documentation](https://twistedmatrix.com/documents/18.4.0/api/twisted.conch.ssh.keys.Key.html#public) for the `.public()` method of `Key` implies you can safely use it on a public key (and get back either the same key, or presumably an equivalent key). However, if you try this, you get an exception thrown from the underlying `cryptography.hazmat` key.

Presumably this is fallout from the move from PyCrypto to Cryptography for the underlying key representation.

```
>>> key = base64.b64decode(b'AAAAB3NzaC1yc2EAAAADAQABAAABAQC6KQgWXkz7gV4/D1qjfSNKZhjEOWjkN6ikAG5pqChLRwFD/phaGyksQNZsG4w2GTWeue9F1/S+0ESxTnxYAFTOCXxck5SJDORVMNBepdoJrfbMllthOA1PiRIcu4aPxLDelg7oBX5b+qsKlJkMGDrnjm7yB13C7rGc42oAtihfad9PiNxwFFWIFANJRzig5sITkXojDlZETQ12ThO78jqSByo+OCzsP0icwBGeNw7OvHFaokoEhcbYkNSoRqRtKEYCDlHyG4taKhRhWErYsWaaK4EXghyBYKdNltHCbhuuSBd7ws01lqCY2465r6CD/AVmn5FSuLzFZHVcfFQYDTZl')
>>> keyobj = twisted.conch.ssh.keys.Key.fromString(key)
>>> keyobj
<RSA Public Key (2048 bits)
attr e:
	01:00:01
attr n:
	00:ba:29:08:16:5e:4c:fb:81:5e:3f:0f:5a:a3:7d:
	23:4a:66:18:c4:39:68:e4:37:a8:a4:00:6e:69:a8:
	28:4b:47:01:43:fe:98:5a:1b:29:2c:40:d6:6c:1b:
	8c:36:19:35:9e:b9:ef:45:d7:f4:be:d0:44:b1:4e:
	7c:58:00:54:ce:09:7c:5c:93:94:89:0c:e4:55:30:
	d0:5e:a5:da:09:ad:f6:cc:96:5b:61:38:0d:4f:89:
	12:1c:bb:86:8f:c4:b0:de:96:0e:e8:05:7e:5b:fa:
	ab:0a:94:99:0c:18:3a:e7:8e:6e:f2:07:5d:c2:ee:
	b1:9c:e3:6a:00:b6:28:5f:69:df:4f:88:dc:70:14:
	55:88:14:03:49:47:38:a0:e6:c2:13:91:7a:23:0e:
	56:44:4d:0d:76:4e:13:bb:f2:3a:92:07:2a:3e:38:
	2c:ec:3f:48:9c:c0:11:9e:37:0e:ce:bc:71:5a:a2:
	4a:04:85:c6:d8:90:d4:a8:46:a4:6d:28:46:02:0e:
	51:f2:1b:8b:5a:2a:14:61:58:4a:d8:b1:66:9a:2b:
	81:17:82:1c:81:60:a7:4d:96:d1:c2:6e:1b:ae:48:
	17:7b:c2:cd:35:96:a0:98:db:8e:b9:af:a0:83:fc:
	05:66:9f:91:52:b8:bc:c5:64:75:5c:7c:54:18:0d:
	36:65>
>>> keyobj.public()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Volumes/Local/OFFTW2/OmniGroup/Applications/OmniFocus/Web/InstanceManager/venv/lib/python3.6/site-packages/twisted/conch/ssh/keys.py", line 794, in public
    return Key(self._keyObject.public_key())
AttributeError: '_RSAPublicKey' object has no attribute 'public_key'
>>> keyobj._keyObject
<cryptography.hazmat.backends.openssl.rsa._RSAPublicKey object at 0x10e4edd30>

```

(ECDSA keys have the same problem as RSA.)

<details><summary>Searchable metadata</summary>

```
trac-id__9441 9441
type__defect defect
reporter__wiml wiml
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__conch conch
keywords__None None
time__1525908290300655 1525908290300655
changetime__1531057765071583 1531057765071583
version__None None
owner__markrwilliams markrwilliams

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_1"></a>|@markrwilliams commented|
|-|-|

https://github.com/twisted/twisted/pull/1010

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_2"></a>|@adiroiban set owner to @markrwilliams|
|-|-|

This is good to merge.
Only a minor comment to extend the test at https://github.com/twisted/twisted/pull/1010#pullrequestreview-119657100

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_3"></a>|@adiroiban set status to `closed`|
|-|-|

In changeset b604217b3b7240278a336a29ee5a100b86118050
```
#!CommitTicketReference repository="" revision="b604217b3b7240278a336a29ee5a100b86118050"
Merge pull request #1010 from twisted/9441-conch-public-key

Author: markrwilliams

Reviewer: adiroiban

Fixes: ticket:9441
```
