### ISSUE TITLE
lastColorizedLine() function contains wrong code causing error on non-ascii input

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9442]
|<img alt="nnseva's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| nnseva reported|
|-|-|
|Trac ID|trac#9442|
|Type|release blocker: regression|
|Created|2018-05-11 09:21:22Z|
|Branch|https://github.com/twisted/twisted/tree/9442-lastcolorized|

This problem appears while trying to make the non-ascii (utf-8 f.e.) input available for colorized manhole terminal when using python 2.x.

The following interactive example demonstrates a problem.

```
$ python
Python 2.7.14 (default, Sep 23 2017, 22:06:14) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from twisted.conch.manhole import lastColorizedLine
>>> lastColorizedLine('qqq')
'\x1b[1;33mqqq\x1b[0m'
>>> lastColorizedLine(b'привет')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/seva/django-1.10/local/lib/python2.7/site-packages/twisted/conch/manhole.py", line 335, in lastColorizedLine
    line = str(w).encode("utf-8")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)
>>> lastColorizedLine(u'привет')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/seva/django-1.10/local/lib/python2.7/site-packages/twisted/conch/manhole.py", line 335, in lastColorizedLine
    line = str(w).encode("utf-8")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)
```

The source of the issue is a wrong use of the `encode` method of the string. Really, the `encode` method converts `unicode` (wide) string to the `str` or `byte` string, as shown below:

```
>>> type(''.encode('utf-8'))
<type 'str'>
>>> type(u''.encode('utf-8'))
<type 'str'>
```

When the `encode` is called for the `str`, the `str` is implicitly converted to `unicode` first, using default (ascii) encoding. This causes the problem, when the source `str` string contains non-ascii multibyte utf-8-encoded characters.

So this code is definitely wrong:

```
line = str(w).encode("utf-8")
```

Unfortunately, this is not the only problem of the `str`-`unicode` conversion in this subsystem.

<details><summary>Searchable metadata</summary>

```
trac-id__9442 9442
type__release_blocker__regression release blocker: regression
reporter__nnseva nnseva
priority__normal normal
milestone__None None
branch__9442_lastcolorized 9442-lastcolorized
branch_author__ 
status__closed closed
resolution__fixed fixed
component__conch conch
keywords__None None
time__1526030482138678 1526030482138678
changetime__1526750741077704 1526750741077704
version__None None
owner__Mark_Williams__mrw_____ Mark Williams <mrw@...>

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

Introduced by https://github.com/twisted/twisted/commit/d2cd66cb6a6f7bda47cd0bb10a82deb66038a2e0 / https://github.com/twisted/twisted/pull/633 / [#8327](https://github.com/twisted/twisted/issues/8327)

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)|@hawkowl set owner to @hawkowl|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_3"></a>|@hawkowl removed owner|
|-|-|

PR, with added tests: https://github.com/twisted/twisted/pull/1016

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_4"></a>|@markrwilliams commented|
|-|-|

https://github.com/twisted/twisted/pull/1016#pullrequestreview-121607189

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_5"></a>|@markrwilliams set owner to @markrwilliams<br>@markrwilliams set status to `closed`|
|-|-|

In changeset 2e7b403c03e9b9b891a5eb36297e494f541d5d6a
```
#!CommitTicketReference repository="" revision="2e7b403c03e9b9b891a5eb36297e494f541d5d6a"
Merge pull request #1016 from twisted/9442-lastcolorized

Author: hawkowl

Reviewers: markrwilliams

Fixes: ticket:9442

twisted.conch.manhole.lastColorizedLine now does not throw a UnicodeDecodeError on non-ASCII input;
twisted.python.htmlizer.TokenPrinter now explicitly works on bytestrings.
```
