### ISSUE TITLE
formatEventAsClassicLogText assumes traceback bytes can be decoded as ascii on Python2

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9456]
|[<img alt="jlitzingerdev's avatar" src="https://avatars.githubusercontent.com/u/1496650?s=50" width="50" height="50">](https://github.com/jlitzingerdev)| @jlitzingerdev reported|
|-|-|
|Trac ID|trac#9456|
|Type|defect|
|Created|2018-05-20 21:19:39Z|

Example
```python
# -*- coding: utf-8 -*-
from twisted.logger import formatEventAsClassicLogText
from twisted.python import failure
f = failure.Failure(Exception('привет'))
event = {
    'log_failure': f,
    'foo': 'bar',
}


print(formatEventAsClassicLogText(event))
```

On Python2:
```
Traceback (most recent call last):
  File "logtest.py", line 12, in <module>
    print(formatEventAsClassicLogText(event))
  File "/home/jlitzing/dev/twisted/twisted-fork/src/twisted/logger/_format.py", line 197, in formatEventAsClassicLogText
    eventText = u"\n".join((eventText, traceback))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 66: ordinal not in range(128)
```
This occurs due to the fact the result of getTraceback() is bytes on Python 2 and is joined with unicode (discussed in [#9442](https://github.com/twisted/twisted/issues/9442), but due to an ascii conversion).

On Python3:
```
(twisted_p3) [jlitzing@arch-tinker ~]$ python logtest.py 
- [-#-] 
	Traceback (most recent call last):
	Failure: builtins.Exception: привет
```

<details><summary>Searchable metadata</summary>

```
trac-id__9456 9456
type__defect defect
reporter__jlitzingerdev jlitzingerdev
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__logger logger
keywords__None None
time__1526851179684821 1526851179684821
changetime__1535165914042416 1535165914042416
version__None None
owner__jlitzingerdev jlitzingerdev

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="jlitzingerdev's avatar" src="https://avatars.githubusercontent.com/u/1496650?s=50" width="50" height="50">](https://github.com/jlitzingerdev)<a name="note_2"></a>|@jlitzingerdev set owner to @jlitzingerdev|
|-|-|

Assigning this to myself as I'm hopeful the traceback formatting I have in mind for [#7927](https://github.com/twisted/twisted/issues/7927) can be reused.

**Comment by twisted-trac** [comment]
|[<img alt="jlitzingerdev's avatar" src="https://avatars.githubusercontent.com/u/1496650?s=50" width="50" height="50">](https://github.com/jlitzingerdev)<a name="note_3"></a>|@jlitzingerdev removed owner|
|-|-|

PR: https://github.com/twisted/twisted/pull/1039

Most of the discussion is in the linked PRs or in [#7927](https://github.com/twisted/twisted/issues/7927).

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_4"></a>|@glyph set owner to @jlitzingerdev|
|-|-|

Review over at https://github.com/twisted/twisted/pull/1039#pullrequestreview-137683765 .  Hopefully this is the last round! :)

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_5"></a>|@hawkowl set status to `closed`|
|-|-|

In changeset 192814655881ca1302eae70477d2d2fc0b9f2e6e
```
#!CommitTicketReference repository="" revision="192814655881ca1302eae70477d2d2fc0b9f2e6e"
Merge 7927-unhandled-error-tb-3: Make formatEvent print tracebacks.

Author: jlitzingerdev
Reviewers: hawkowl, glyph
Fixes: ticket:7927, ticket:9456
```
