### ISSUE TITLE
awaiting a deferred / using ensureDeferred loses the originating traceback's information

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9459]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)| @glyph reported|
|-|-|
|Trac ID|trac#9459|
|Type|defect|
|Created|2018-05-28 22:44:34Z|

Sample (python 3 only) program:

```python
import sys
from twisted.logger import globalLogBeginner, textFileLogObserver
globalLogBeginner.beginLoggingTo([textFileLogObserver(sys.stdout)])
from twisted.internet.defer import ensureDeferred, maybeDeferred
def bar():
    1 / 0
it = maybeDeferred(bar)
async def foo():
    return await it
ensureDeferred(foo())
```

This should show an exception originating inside `bar`, but instead, `bar` is nowhere on the stack.

This would be somewhat mitigated by using `failure.raiseException` in `Deferred.send` rather than `raise result.value`.  However, this is also related to [#9176](https://github.com/twisted/twisted/issues/9176), and a full resolution (where both `foo` and `bar` are both visible in the traceback, even if the exception is generated asynchronously) may require attaching the `Failure` object to the raised exception, even _separately_ from `__cause__` and `__traceback__`.  (Just using `result.raiseException()` produces consfusing results when _foo_ is no longer on the stack (as in the attached example), since it shows the traceback originating in `bar` and then stopping.)

<details><summary>Searchable metadata</summary>

```
trac-id__9459 9459
type__defect defect
reporter__glyph glyph
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__None None
time__1527547474095314 1527547474095314
changetime__1530303282536711 1530303282536711
version__None None
owner__glyph glyph

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_2"></a>|@glyph commented|
|-|-|

Sadly [#9176](https://github.com/twisted/twisted/issues/9176) doesn't seem to touch this at all, so it will have to be a separate fix.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_3"></a>|@glyph commented|
|-|-|

In review at https://github.com/twisted/twisted/pull/1032 .

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_4"></a>|@glyph commented|
|-|-|

Just so the reviewer can get a quick sense of what this does:

The previous release, with the example above:

```
2018-06-28T01:37:32-0700 [twisted.internet.defer#critical] Unhandled error in Deferred:
2018-06-28T01:37:32-0700 [twisted.internet.defer#critical]
	Traceback (most recent call last):
	  File "sample.py", line 10, in <module>
	    ensureDeferred(foo()) #.addErrback(lambda f: print(f.getTraceback()))
	  File "twisted/internet/defer.py", line 908, in ensureDeferred
	    return _inlineCallbacks(None, coro, Deferred())
	--- <exception caught here> ---
	  File "twisted/internet/defer.py", line 1386, in _inlineCallbacks
	    result = g.send(result)
	  File "sample.py", line 9, in foo
	    return await it
	  File "twisted/internet/defer.py", line 746, in send
	    raise result.value
	builtins.ZeroDivisionError: division by zero
```

This branch:

```
2018-06-28T01:33:05-0700 [twisted.internet.defer#critical] Unhandled error in Deferred:
2018-06-28T01:33:05-0700 [twisted.internet.defer#critical]
	Traceback (most recent call last):
	  File "sample.py", line 7, in <module>
	    it = maybeDeferred(bar)
	--- <exception caught here> ---
	  File "sample.py", line 9, in foo
	    return await it
	  File "twisted/internet/defer.py", line 151, in maybeDeferred
	    result = f(*args, **kw)
	  File "sample.py", line 6, in bar
	    1 / 0
	builtins.ZeroDivisionError: division by zero
```

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_5"></a>|@hawkowl set owner to @glyph|
|-|-|

heckin ship it (little nit on PR)

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_6"></a>|@glyph set status to `closed`|
|-|-|

In changeset 90d9cc1545bdfd44d320875d055fad749fb6356b
```
#!CommitTicketReference repository="" revision="90d9cc1545bdfd44d320875d055fad749fb6356b"
Merge pull request #1032 from twisted/9459-tracebackawait

Author: glyph

Reviewer: hawkowl

Fixes: ticket:9459

twisted.python.failure.Failure tracebacks generated by coroutines scheduled with twisted.internet.defer.ensureDeferred - i.e. any Deferred-awaiting coroutine - now contain fewer extraneous frames from the trampoline implementation, and correctly indicate the source of exceptions raised in other call stacks - i.e. the function that raised the exception.  In other words: if you 'await' a function that raises an exception, you'll be able to see where the error came from.
```
