### ISSUE TITLE
It's easy to misuse ReverseProxyRequest in a way that breaks it

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9472]
|[<img alt="dmollerm's avatar" src="https://avatars.githubusercontent.com/u/6445927?s=50" width="50" height="50">](https://github.com/dmollerm)| @dmollerm reported|
|-|-|
|Trac ID|trac#9472|
|Type|enhancement|
|Created|2018-07-01 17:09:51Z|

Setting up a simple ServerFactory with
twisted.web.proxy.ReverseProxy as protocol and hence
twisted.web.proxy.ReverseProxyRequest as request handler
will fail when pointed anywhere with the following error:

```
Unhandled Error
Traceback (most recent call last):
  File "src/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "src/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "src/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "src/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "src/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
  File "src/twisted/internet/tcp.py", line 208, in doRead
    return self._dataReceived(data)
  File "src/twisted/internet/tcp.py", line 214, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "src/twisted/web/http.py", line 2204, in dataReceived
    return basic.LineReceiver.dataReceived(self, data)
  File "src/twisted/protocols/basic.py", line 572, in dataReceived
    why = self.lineReceived(line)
  File "src/twisted/web/http.py", line 2092, in lineReceived
    self.allContentReceived()
  File "src/twisted/web/http.py", line 2183, in allContentReceived
    req.requestReceived(command, path, version)
  File "src/twisted/web/http.py", line 917, in requestReceived
    self.process()
  File "src/twisted/web/proxy.py", line 210, in process
    [self.factory.host.encode('ascii')])
builtins.AttributeError: 'ReverseProxyRequest' object has no attribute 'factory'
```

The code that caused this:

```
from twisted.internet.protocol import ServerFactory
from twisted.internet import reactor
from twisted.web import proxy


class ReverseProxyFactory(ServerFactory):
    """
    Used by ReverseProxyRequest to implement a simple transparent proxy
    """
    protocol = proxy.ReverseProxy

    def __init__(self, host, port):
        self.host = host
        self.port = port

    def log(self, *args, **kwargs):
        pass


factory = ReverseProxyFactory(b'www.twistedmatrix.com', 80)
reactor.listenTCP(8080, factory)
reactor.run()
```

<details><summary>Searchable metadata</summary>

```
trac-id__9472 9472
type__enhancement enhancement
reporter__dmollerm dmollerm
priority__normal normal
milestone__None None
branch__None None
branch_author__ 
status__new new
resolution__None None
component__web web
keywords__reverse_proxy_documentation reverse proxy documentation
time__1530464991155244 1530464991155244
changetime__1537142445715687 1537142445715687
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

This isn't the intended way to use `ReverseProxy`.  Instead, you must use it with `Site`.

See reverse-proxy.py on https://twistedmatrix.com/documents/current/web/examples/

Maybe the documentation for `twisted.web.proxy` could be improved to make this more readily apparent.

**Comment by twisted-trac** [comment]
|[<img alt="dmollerm's avatar" src="https://avatars.githubusercontent.com/u/6445927?s=50" width="50" height="50">](https://github.com/dmollerm)<a name="note_3"></a>|@dmollerm commented|
|-|-|

Hi!

Sorry I forgot about this ticket for so long, I was only paying attention to the github pull request.

I must say I strongly disagree: the whole point of the factory, protocol, transport, endpoint and all the twisted entities is to **uncouple** their usage.

If you take a look to the proposed PR, you'll see its just a matter of not relying on `Site` having a `factory` reference attached to the protocol when building it. https://github.com/twisted/twisted/pull/1035/files

I think the proposed change is fair and allows this request class to be used anywhere. I'm actually building an application atop this and it is really straight forward! (just as the contributed example)
