### ISSUE TITLE
ReverseProxyRequest will fail when building a transparent proxy

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9473]
|[<img alt="dmollerm's avatar" src="https://avatars.githubusercontent.com/u/6445927?s=50" width="50" height="50">](https://github.com/dmollerm)| @dmollerm reported|
|-|-|
|Trac ID|trac#9473|
|Type|defect|
|Created|2018-07-01 17:12:59Z|

Setting up a simple ServerFactory with
twisted.web.proxy.ReverseProxy as protocol and hence
twisted.web.proxy.ReverseProxyRequest as request handler
will fail when pointed anywhere with the following error:

```
Unhandled Error
Traceback (most recent call last):
  File "src/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "src/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "src/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "src/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "src/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
  File "src/twisted/internet/tcp.py", line 208, in doRead
    return self._dataReceived(data)
  File "src/twisted/internet/tcp.py", line 214, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "src/twisted/web/http.py", line 2204, in dataReceived
    return basic.LineReceiver.dataReceived(self, data)
  File "src/twisted/protocols/basic.py", line 572, in dataReceived
    why = self.lineReceived(line)
  File "src/twisted/web/http.py", line 2092, in lineReceived
    self.allContentReceived()
  File "src/twisted/web/http.py", line 2183, in allContentReceived
    req.requestReceived(command, path, version)
  File "src/twisted/web/http.py", line 917, in requestReceived
    self.process()
  File "src/twisted/web/proxy.py", line 210, in process
    [self.factory.host.encode('ascii')])
builtins.AttributeError: 'ReverseProxyRequest' object has no attribute 'factory'
```

The code that caused this:

```
from twisted.internet.protocol import ServerFactory
from twisted.internet import reactor
from twisted.web import proxy


class ReverseProxyFactory(ServerFactory):
    """
    Used by ReverseProxyRequest to implement a simple transparent proxy
    """
    protocol = proxy.ReverseProxy

    def __init__(self, host, port):
        self.host = host
        self.port = port

    def log(self, *args, **kwargs):
        pass


factory = ReverseProxyFactory(b'www.twistedmatrix.com', 80)
reactor.listenTCP(8080, factory)
reactor.run()
```

<details><summary>Searchable metadata</summary>

```
trac-id__9473 9473
type__defect defect
reporter__dmollerm dmollerm
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__duplicate duplicate
component__web web
keywords__proxy proxy
time__1530465179511067 1530465179511067
changetime__1530465391154062 1530465391154062
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="dmollerm's avatar" src="https://avatars.githubusercontent.com/u/6445927?s=50" width="50" height="50">](https://github.com/dmollerm)|@dmollerm set status to `closed`|
|-|-|
