### ISSUE TITLE
failure serialization round-trip via eventAsJSON / eventFromJSON loses message, renders traceback almost useless

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9483]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)| @glyph reported|
|-|-|
|Trac ID|trac#9483|
|Type|defect|
|Created|2018-07-05 06:19:44Z|

Minimal reproducer:

```
from twisted.logger import Logger, globalLogBeginner, eventAsJSON, eventFromJSON
log = Logger(namespace="test")
captureEverything = []
globalLogBeginner.beginLoggingTo([captureEverything.append], redirectStandardIO=False)
try:
    1/0
except:
    log.failure("expected")
event = captureEverything[-1]
print(event['log_failure'].getTraceback())
roundTripped = eventFromJSON(eventAsJSON(event))
print(roundTripped['log_failure'].getTraceback())
```

Expected result:

```
Traceback (most recent call last):
--- <exception caught here> ---
  File "/Users/glyph/hydration.py", line 6, in <module>
    1/0
builtins.ZeroDivisionError: division by zero

Traceback (most recent call last):
--- <exception caught here> ---
  File "/Users/glyph/hydration.py", line 6, in <module>
    1/0
builtins.ZeroDivisionError: division by zero
```

Actual result:

```
Traceback (most recent call last):
--- <exception caught here> ---
  File "/Users/glyph/hydration.py", line 6, in <module>
    1/0
builtins.ZeroDivisionError: division by zero

Traceback (most recent call last):
--- <exception caught here> ---
  File "/Users/glyph/hydration.py", line 6, in <module>
    1/0
builtins.ZeroDivisionError: {'unpersistable': True}
```

It may not be possible to fully serialize and deserialize the full exception object, but it should at least be possible to preserve the formatting of the message in the traceback.  Otherwise, structured log output is actually of lower value than unstructured output, which is sad.

<details><summary>Searchable metadata</summary>

```
trac-id__9483 9483
type__defect defect
reporter__glyph glyph
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__logger logger
keywords__None None
time__1530771584779773 1530771584779773
changetime__1554856808207342 1554856808207342
version__None None
owner__None None
cc__wsanchez
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_3"></a>|@glyph commented|
|-|-|

Part of this is [#9198](https://github.com/twisted/twisted/issues/9198) but it seems there's maybe a little more here.
