### ISSUE TITLE
twisted.names secondary doesn't refresh, tracebacks; cause unknown

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9494]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)| @glyph reported|
|-|-|
|Trac ID|trac#9494|
|Type|defect|
|Created|2018-07-19 18:23:51Z|

twistedmatrix.com's secondary got this traceback in a loop, and returned NXDOMAINs for all affected domains:

```
2018-07-18T16:21:29+0000 [-] Updating twistedmatrix.com from 66.35.39.66 f
ailed during zone transfer
2018-07-18T16:21:29+0000 [-] Unhandled Error
        Traceback (most recent call last):
          File "/code/env/site-packages/twisted/internet/base.py", line 11
46, in connectionFailed
            self.factory.clientConnectionFailed(self, reason)
          File "/code/env/site-packages/twisted/names/client.py", line 551
, in clientConnectionFailed
            d.errback(reason)
          File "/code/env/site-packages/twisted/internet/defer.py", line 5
01, in errback
            self._startRunCallbacks(fail)
          File "/code/env/site-packages/twisted/internet/defer.py", line 5
68, in _startRunCallbacks
            self._runCallbacks()
        --- <exception caught here> ---
          File "/code/env/site-packages/twisted/internet/defer.py", line 6
54, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "/code/env/site-packages/twisted/names/client.py", line 433
, in eliminateTimeout
            controller.timeoutCall.cancel()
          File "/code/env/site-packages/twisted/internet/base.py", line 99
, in cancel
            raise error.AlreadyCalled
        twisted.internet.error.AlreadyCalled: Tried to cancel an already-c
alled event.
```

the deployment of this is:

```python
from twisted.names import tap as namestap
o = namestap.Options()
o.parseOptions(
    ['--port', '53', '--cache'] +
    ['--secondary=66.35.39.66/' + x
     for x in
     [
         'twistedmatrix.com',
         'divunal.com',
         'ynchrono.us',
         'divmod.com',
         'divmod.org',
         'crookedsapling.us',
     ]
    ]
```

<details><summary>Searchable metadata</summary>

```
trac-id__9494 9494
type__defect defect
reporter__glyph glyph
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__names names
keywords__None None
time__1532024631039296 1532024631039296
changetime__1617906538819565 1617906538819565
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="mithrandi's avatar" src="https://avatars.githubusercontent.com/u/856430?s=50" width="50" height="50">](https://github.com/mithrandi)<a name="note_1"></a>|@mithrandi commented|
|-|-|

I can't seem to reproduce this.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_2"></a>|@glyph commented|
|-|-|

OK, it turns out "18.7.0" was a red herring.  I redeployed with 18.7 and the secondary is working fine.

I think that this might be an artifact of hyper.sh's networking; it is often busted for a few moments after container start-up, and sometimes an unlucky container dies.

Here's a much simpler repro:

```
$ twist dns --port 5553 --cache --secondary=127.0.0.2/twistedmatrix.com
```

After a few moments you'll get the traceback.

**Comment by twisted-trac** [comment]
|[<img alt="mithrandi's avatar" src="https://avatars.githubusercontent.com/u/856430?s=50" width="50" height="50">](https://github.com/mithrandi)<a name="note_3"></a>|@mithrandi commented|
|-|-|

```
2018-07-22T19:18:09+0200 [-] DNSServerFactory starting on 5553
2018-07-22T19:18:09+0200 [-] DNSDatagramProtocol starting on 5553
2018-07-22T19:18:09+0200 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x0000562f7a6384b8>
2018-07-22T19:18:09+0200 [twisted.application.runner._runner.Runner#info] Starting reactor...
2018-07-22T19:18:09+0200 [Uninitialized] Updating twistedmatrix.com from 127.0.0.2 failed during zone transfer
2018-07-22T19:18:09+0200 [Uninitialized] Unhandled Error
        Traceback (most recent call last):
        Failure: twisted.internet.error.ConnectionRefusedError: Connection was refused by other side: 111: Connection refused.
```

Aha, maybe I have to try Python 3?

… Nope, same error there.

**Comment by twisted-trac** [comment]
|[<img alt="mithrandi's avatar" src="https://avatars.githubusercontent.com/u/856430?s=50" width="50" height="50">](https://github.com/mithrandi)<a name="note_4"></a>|@mithrandi commented|
|-|-|

Oh, I get it; you're on macOS where 127.0.0.2 doesn't exist, whereas I'm on linux where the whole of 127.0.0.0/8 is assigned to lo by default. If I try a really nonexistent IP:

```
> twist dns --port 5553 --cache --secondary=10.1.2.3/twistedmatrix.com
2018-07-22T19:23:37+0200 [-] DNSServerFactory starting on 5553
2018-07-22T19:23:37+0200 [-] DNSDatagramProtocol starting on 5553
2018-07-22T19:23:37+0200 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x00007f3ace1c8090>
2018-07-22T19:23:37+0200 [twisted.application.runner._runner.Runner#info] Starting reactor...
2018-07-22T19:23:47+0200 [-] Updating twistedmatrix.com from 10.1.2.3 failed during zone transfer
2018-07-22T19:23:47+0200 [-] Unhandled Error
        Traceback (most recent call last):
          File "/home/mithrandi/code/Twisted/src/twisted/internet/base.py", line 1146, in connectionFailed
            self.factory.clientConnectionFailed(self, reason)
          File "/home/mithrandi/code/Twisted/src/twisted/names/client.py", line 551, in clientConnectionFailed
            d.errback(reason)
          File "/home/mithrandi/code/Twisted/src/twisted/internet/defer.py", line 501, in errback
            self._startRunCallbacks(fail)
          File "/home/mithrandi/code/Twisted/src/twisted/internet/defer.py", line 568, in _startRunCallbacks
            self._runCallbacks()
        --- <exception caught here> ---
          File "/home/mithrandi/code/Twisted/src/twisted/internet/defer.py", line 654, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "/home/mithrandi/code/Twisted/src/twisted/names/client.py", line 433, in eliminateTimeout
            controller.timeoutCall.cancel()
          File "/home/mithrandi/code/Twisted/src/twisted/internet/base.py", line 99, in cancel
            raise error.AlreadyCalled
        twisted.internet.error.AlreadyCalled: Tried to cancel an already-called event.
2018-07-22T19:23:47+0200 [-] Unhandled Error
        Traceback (most recent call last):
          File "/home/mithrandi/code/Twisted/src/twisted/application/runner/_runner.py", line 100, in run
            self.startReactor()
          File "/home/mithrandi/code/Twisted/src/twisted/application/runner/_runner.py", line 167, in startReactor
            self._reactor.run()
          File "/home/mithrandi/code/Twisted/src/twisted/internet/base.py", line 1261, in run
            self.mainLoop()
          File "/home/mithrandi/code/Twisted/src/twisted/internet/base.py", line 1270, in mainLoop
            self.runUntilCurrent()
        --- <exception caught here> ---
          File "/home/mithrandi/code/Twisted/src/twisted/internet/base.py", line 896, in runUntilCurrent
            call.func(*call.args, **call.kw)
          File "/home/mithrandi/code/Twisted/src/twisted/names/client.py", line 445, in _timeoutZone
            d.errback(error.TimeoutError("Zone lookup timed out after %d seconds" % (seconds,)))
          File "/home/mithrandi/code/Twisted/src/twisted/internet/defer.py", line 501, in errback
            self._startRunCallbacks(fail)
          File "/home/mithrandi/code/Twisted/src/twisted/internet/defer.py", line 561, in _startRunCallbacks
            raise AlreadyCalledError
        twisted.internet.defer.AlreadyCalledError:
```

**Comment by twisted-trac** [comment]
|[<img alt="wiml's avatar" src="https://avatars.githubusercontent.com/u/156891?s=50" width="50" height="50">](https://github.com/wiml)<a name="note_5"></a>|@wiml commented|
|-|-|

This looks related to ticket:10141 and ticket:3428 — my fix for the former moves the error to a different place in the code, and I think this bug might be resolved by my fix for the latter.
