### ISSUE TITLE
Tests die with "builtins.OSError: [Errno 24] Too many open files"

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9495]
|[<img alt="eli-schwartz's avatar" src="https://avatars.githubusercontent.com/u/6551424?s=50" width="50" height="50">](https://github.com/eli-schwartz)| @eli-schwartz reported|
|-|-|
|Trac ID|trac#9495|
|Type|defect|
|Created|2018-07-20 16:02:29Z|

Trying to update twisted from 18.4.0 to 18.7.0 on python 3.6, the testsuite failed with a couple of errors not present in the previous version.

The relevant logs are
```
    test_closePeerOnEMFILE ...                                          [ERROR]
```

and

```
twisted.words.test.test_domish.ElementTests.test_addContentBytesNonASCII
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/build/twisted/src/twisted-twisted-18.7.0/build/lib.linux-x86_64-3.6/twisted/internet/base.py", line 896, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/build/twisted/src/twisted-twisted-18.7.0/build/lib.linux-x86_64-3.6/twisted/internet/posixbase.py", line 298, in _handleSignals
    self._childWaker = _SIGCHLDWaker(self)
  File "/build/twisted/src/twisted-twisted-18.7.0/build/lib.linux-x86_64-3.6/twisted/internet/posixbase.py", line 200, in __init__
    _FDWaker.__init__(self, reactor)
  File "/build/twisted/src/twisted-twisted-18.7.0/build/lib.linux-x86_64-3.6/twisted/internet/posixbase.py", line 133, in __init__
    self.i, self.o = os.pipe()
builtins.OSError: [Errno 24] Too many open files
```

Attachments:

* [twisted-18.7.0-1-x86_64-check.log](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/f72/f720e90b8d647e875741b38e6a8905a382a58c37/a20afa24aeacc8f318da0905e59383b1d1bde7a3.log) (2471804 bytes) - added by eli-schwartz on 2018-07-20 16:03:32Z - Full testsuite log

<details><summary>Searchable metadata</summary>

```
trac-id__9495 9495
type__defect defect
reporter__eli_schwartz eli-schwartz
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__trial trial
keywords__tests_review tests review
time__1532102549767128 1532102549767128
changetime__1652109321156582 1652109321156582
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_1"></a>|@markrwilliams commented|
|-|-|

Looks like the ```Glib2Reactor``` doesn't work with the [[#5368](https://github.com/twisted/twisted/issues/5368) EMFILE mitigation]:

```
  TCPFDPortTestsBuilder_Glib2ReactorTests
    test_allNewStyle ...                                                   [OK]
    test_buildProtocolIPv4Address ...                                      [OK]
    test_buildProtocolIPv6Address ...                                      [OK]
    test_buildProtocolIPv6AddressScopeID ...                               [OK]
    test_closePeerOnEMFILE ...                                          [ERROR]   
    test_connectionLostLogMsg ...                                          [OK]
    test_portGetHostOnIPv4 ...                                             [OK]
    test_portGetHostOnIPv6 ...                                             [OK]
    test_portGetHostOnIPv6ScopeID ...                                      [OK]
    test_serverGetHostOnIPv4 ...                                           [OK]
    test_serverGetHostOnIPv6 ...                                           [OK]
    test_serverGetHostOnIPv6ScopeID ...                                    [OK]
    test_serverGetPeerOnIPv4 ...                                           [OK]
    test_serverGetPeerOnIPv6 ...                                           [OK]
    test_serverGetPeerOnIPv6ScopeID ...                                    [OK]
    test_startedListeningLogMessage ...                                    [OK]
```

**Comment by twisted-trac** [comment]
|[<img alt="rbalint's avatar" src="https://avatars.githubusercontent.com/u/1520835?s=50" width="50" height="50">](https://github.com/rbalint)<a name="note_2"></a>|@rbalint commented|
|-|-|

We keep hitting this in Ubuntu autopkgtests and probably this causes problems in real world deployments as well.

http://autopkgtest.ubuntu.com/packages/twisted

**Comment by twisted-trac** [comment]
|[<img alt="rbalint's avatar" src="https://avatars.githubusercontent.com/u/1520835?s=50" width="50" height="50">](https://github.com/rbalint)<a name="note_3"></a>|@rbalint commented|
|-|-|

We keep hitting the issue in Ubuntu CI: https://autopkgtest.ubuntu.com/packages/twisted
Probably it causes problems on real-world deployments as well.

**Comment by twisted-trac** [comment]
|[<img alt="yan12125's avatar" src="https://avatars.githubusercontent.com/u/1937689?s=50" width="50" height="50">](https://github.com/yan12125)<a name="note_4"></a>|@yan12125 commented|
|-|-|

Submited a PR: https://github.com/twisted/twisted/pull/1729

**Comment by twisted-trac** [comment]
|[<img alt="yan12125's avatar" src="https://avatars.githubusercontent.com/u/1937689?s=50" width="50" height="50">](https://github.com/yan12125)<a name="note_5"></a>|@yan12125 set status to `closed`|
|-|-|

Fixed with the corresponding PR merged. Thanks you all for kind reviews and helpful suggestions!

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_6"></a>|@exarkun commented|
|-|-|

Fixed in https://github.com/twisted/twisted/commit/ba4a6a5c0e9d954661fc9b4f61a4b3cd07b2516a
