### ISSUE TITLE
twisted.names traceback on python 3

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9496]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)| @glyph reported|
|-|-|
|Trac ID|trac#9496|
|Type|defect|
|Created|2018-07-22 09:22:47Z|
|Branch|https://github.com/twisted/twisted/tree/9496-names-traceback|

setup:
```
$ twist dns --port 5553 --cache --secondary=66.35.39.66/twistedmatrix.com
$ dig -p 5553 @localhost twistedmatrix.com
```

expected result: get some records, no traceback

actual result: get some records, then:

```
2018-07-22T02:20:33-0700 [DNSDatagramProtocol (UDP)] Unhandled Error
	Traceback (most recent call last):
	  File "/Users/glyph/.virtualenvs/tmp-59fae94c7e8930d/lib/python3.6/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
	    result = f(*args, **kw)
	  File "/Users/glyph/.virtualenvs/tmp-59fae94c7e8930d/lib/python3.6/site-packages/twisted/names/common.py", line 86, in lookupAddress
	    return self._lookup(name, dns.IN, dns.A, timeout)
	  File "/Users/glyph/.virtualenvs/tmp-59fae94c7e8930d/lib/python3.6/site-packages/twisted/names/resolve.py", line 79, in _lookup
	    d = self.resolvers[0].query(q, timeout)
	  File "/Users/glyph/.virtualenvs/tmp-59fae94c7e8930d/lib/python3.6/site-packages/twisted/names/common.py", line 78, in query
	    return defer.maybeDeferred(method, query.name.name, timeout)
	--- <exception caught here> ---
	  File "/Users/glyph/.virtualenvs/tmp-59fae94c7e8930d/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/Users/glyph/.virtualenvs/tmp-59fae94c7e8930d/lib/python3.6/site-packages/twisted/names/resolve.py", line 29, in __call__
	    failure.trap(dns.DomainError, defer.TimeoutError, NotImplementedError)
	  File "/Users/glyph/.virtualenvs/tmp-59fae94c7e8930d/lib/python3.6/site-packages/twisted/python/failure.py", line 439, in trap
	    self.raiseException()
	  File "/Users/glyph/.virtualenvs/tmp-59fae94c7e8930d/lib/python3.6/site-packages/twisted/python/failure.py", line 467, in raiseException
	    raise self.value.with_traceback(self.tb)
	  File "/Users/glyph/.virtualenvs/tmp-59fae94c7e8930d/lib/python3.6/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
	    result = f(*args, **kw)
	  File "/Users/glyph/.virtualenvs/tmp-59fae94c7e8930d/lib/python3.6/site-packages/twisted/names/common.py", line 86, in lookupAddress
	    return self._lookup(name, dns.IN, dns.A, timeout)
	  File "/Users/glyph/.virtualenvs/tmp-59fae94c7e8930d/lib/python3.6/site-packages/twisted/names/secondary.py", line 161, in _lookup
	    return FileAuthority._lookup(self, name, cls, type, timeout)
	  File "/Users/glyph/.virtualenvs/tmp-59fae94c7e8930d/lib/python3.6/site-packages/twisted/names/authority.py", line 205, in _lookup
	    if dns._isSubdomainOf(name, self.soa[0]):
	  File "/Users/glyph/.virtualenvs/tmp-59fae94c7e8930d/lib/python3.6/site-packages/twisted/names/dns.py", line 258, in _isSubdomainOf
	    ancestorLabels = _nameToLabels(ancestorName.lower())
	  File "/Users/glyph/.virtualenvs/tmp-59fae94c7e8930d/lib/python3.6/site-packages/twisted/names/dns.py", line 225, in _nameToLabels
	    labels = name.split(b'.')
	builtins.TypeError: must be str or None, not bytes
```

<details><summary>Searchable metadata</summary>

```
trac-id__9496 9496
type__defect defect
reporter__glyph glyph
priority__normal normal
milestone__None None
branch__9496_names_traceback 9496-names-traceback
branch_author__ 
status__closed closed
resolution__fixed fixed
component__names names
keywords__None None
time__1532251367691882 1532251367691882
changetime__1578633715267031 1578633715267031
version__None None
owner__twm twm

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_1"></a>|@glyph set owner to @mithrandi|
|-|-|

how about this one

**Comment by twisted-trac** [comment]
|[<img alt="uda's avatar" src="https://avatars.githubusercontent.com/u/199314?s=50" width="50" height="50">](https://github.com/uda)<a name="note_2"></a>|@uda commented|
|-|-|

I am testing bind compatibility, and am having same kind of issues. each time from anther line, for now the origin coming from the filename which is converted to string can't be concatenated to the names inside the zone.

There seems to be a lot of bytes and strings, and they don't always play along.

P.S. the mail module has the same issues, but the PY3 compatibility there goes deeper.

**Comment by twisted-trac** [comment]
|[<img alt="mithrandi's avatar" src="https://avatars.githubusercontent.com/u/856430?s=50" width="50" height="50">](https://github.com/mithrandi)<a name="note_3"></a>|@mithrandi removed owner|
|-|-|

(Probably won't be looking at this, so unassigning)

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)|@twm set owner to @twm<br>@twm set status to `assigned`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_5"></a>|@twm commented|
|-|-|

PR here: https://github.com/twisted/twisted/pull/1212

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_6"></a>|@glyph commented|
|-|-|

Should this be in review?

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)|@twm removed owner<br>@twm set status to `new`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_8"></a>|@glyph set owner to @twm|
|-|-|

Approved!  See github for more details.  Loved manually testing this and seeing the traceback go away :).

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_9"></a>|@twm set status to `closed`|
|-|-|

In changeset 1d68f66eeb50aed5b2a27a5649566b6f86c4d615
```
#!CommitTicketReference repository="" revision="1d68f66eeb50aed5b2a27a5649566b6f86c4d615"
Merge pull request #1212 from twisted/9496-names-traceback

Author: twm
Reviewer: glyph
Fixes: ticket:9496

Names SecondaryAuthority traceback
```
