### ISSUE TITLE
Issue with attr.ib in twisted.internet.address.UNIXAddress

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9516]
|[<img alt="vesellov's avatar" src="https://avatars.githubusercontent.com/u/5828660?s=50" width="50" height="50">](https://github.com/vesellov)| @vesellov reported|
|-|-|
|Trac ID|trac#9516|
|Type|defect|
|Created|2018-08-30 08:41:36Z|

Hello Twisted! I love that project and would like to submit a bug report I found in latest 18.7.0 release.

I think it was introduced by Amber Brown in that commit : https://github.com/twisted/twisted/commit/1cd79b6a4f564b53c9b467f3522ee6679605e12c#diff-3b02d4bcf664efc58d50c0f4ceb2c37f

I am running twisted 18.7.0 inside virtualenv with Python 2.7.14 on MacOS.

It is happening inside child process spawned from main process with `subprocess.Popen()`. Inside child process I am doing `from twisted.internet import reactor` and it is failing, however in my main process `import reactor` is working fine... 

I can imagine some environment/shell issues can be a reason for that, but to my opinion calling that during import of the module is not super good:

`name = attr.ib(converter=lambda x: _asFilesystemBytes(x) if x is not None else None)`

I have no solution for that, so reporting a bug for now.

Here is traceback:

```
Traceback (most recent call last):
  File "/Users/veselin/work/bitdust.devel/lib/net_misc.py", line 49, in <module>
    from twisted.internet import reactor
  File "/Users/veselin/.bitdust/venv/lib/python2.7/site-packages/twisted/internet/reactor.py", line 38, in <module>
    from twisted.internet import default
  File "/Users/veselin/.bitdust/venv/lib/python2.7/site-packages/twisted/internet/default.py", line 56, in <module>
    install = _getInstallFunction(platform)
  File "/Users/veselin/.bitdust/venv/lib/python2.7/site-packages/twisted/internet/default.py", line 50, in _getInstallFunction
    from twisted.internet.selectreactor import install
  File "/Users/veselin/.bitdust/venv/lib/python2.7/site-packages/twisted/internet/selectreactor.py", line 18, in <module>
    from twisted.internet import posixbase
  File "/Users/veselin/.bitdust/venv/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 18, in <module>
    from twisted.internet import error, udp, tcp
  File "/Users/veselin/.bitdust/venv/lib/python2.7/site-packages/twisted/internet/udp.py", line 53, in <module>
    from twisted.internet import base, defer, address
  File "/Users/veselin/.bitdust/venv/lib/python2.7/site-packages/twisted/internet/base.py", line 27, in <module>
    from twisted.internet._resolver import (
  File "/Users/veselin/.bitdust/venv/lib/python2.7/site-packages/twisted/internet/_resolver.py", line 25, in <module>
    from twisted.internet.address import IPv4Address, IPv6Address
  File "/Users/veselin/.bitdust/venv/lib/python2.7/site-packages/twisted/internet/address.py", line 103, in <module>
    class UNIXAddress(object):
  File "/Users/veselin/.bitdust/venv/lib/python2.7/site-packages/twisted/internet/address.py", line 111, in UNIXAddress
    name = attr.ib(converter=attr.converters.optional(_asFilesystemBytes))
TypeError: attrib() got an unexpected keyword argument 'converter'
An error has occured during the module import
```

<details><summary>Searchable metadata</summary>

```
trac-id__9516 9516
type__defect defect
reporter__vesellov vesellov
priority__normal normal
milestone__Python_3_x Python-3.x
branch__None None
branch_author__ 
status__closed closed
resolution__invalid invalid
component__core core
keywords__None None
time__1535618496614447 1535618496614447
changetime__1594454896024617 1594454896024617
version__None None
owner__vesellov vesellov
cc__Amber cc__Brown cc__wiml
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="vesellov's avatar" src="https://avatars.githubusercontent.com/u/5828660?s=50" width="50" height="50">](https://github.com/vesellov)<a name="note_1"></a>|@vesellov commented|
|-|-|

Downgraded to twisted 18.4.0 and it solves the issue....

I have attrs-18.1.0 in my virtualenv

Looks like in `attrs` they deprecated `converter` field and so solution can be two ways:

1. change code in twisted to follow attrs developers

2. limit attrs version in twisted requirements...  but it will be a temporary fix

**Comment by twisted-trac** [comment]
|[<img alt="vesellov's avatar" src="https://avatars.githubusercontent.com/u/5828660?s=50" width="50" height="50">](https://github.com/vesellov)<a name="note_2"></a>|@vesellov commented|
|-|-|

http://www.attrs.org/en/stable/changelog.html#deprecations

**Comment by twisted-trac** [comment]
|[<img alt="moshez's avatar" src="https://avatars.githubusercontent.com/u/422703?s=50" width="50" height="50">](https://github.com/moshez)<a name="note_3"></a>|@moshez commented|
|-|-|

Removed keyword review since there is no patch.

**Comment by twisted-trac** [comment]
|[<img alt="altendky's avatar" src="https://avatars.githubusercontent.com/u/543719?s=50" width="50" height="50">](https://github.com/altendky)<a name="note_4"></a>|@altendky commented|
|-|-|

Isn't the attrs link suggesting that `converter=` has been valid since at least 17.4.0?  So 18.1.0 should be fine.

https://repl.it/@altendky/SubstantialAgonizingWheel-4
```python
import attr

attr.ib(converter=None)
import twisted.internet.address
print(attr.fields(twisted.internet.address.UNIXAddress).name.converter)
print(attr.__version__)
print(twisted.__version__)
```
```
<function optional.<locals>.optional_converter at 0x7f7551b4a6a8>
17.4.0
18.9.0
```


Twisted does seem to `install_requires` `'attrs >= 17.4.0'`.

https://github.com/twisted/twisted/commit/43217d13cb458971c37761be5062a159f1ae80b0

https://github.com/twisted/twisted/blob/487dc1b4126e5b0a9712ef52123c83983100d20e/src/twisted/python/_setup.py#L237-L245

```python
requirements = [
    "zope.interface >= 4.4.2",
    "constantly >= 15.1",
    "incremental >= 16.10.1",
    "Automat >= 0.3.0",
    "hyperlink >= 17.1.1",
    "PyHamcrest >= 1.9.0",
    "attrs >= 17.4.0",
]
```

**Comment by twisted-trac** [comment]
|[<img alt="wiml's avatar" src="https://avatars.githubusercontent.com/u/156891?s=50" width="50" height="50">](https://github.com/wiml)<a name="note_5"></a>|@wiml set owner to @vesellov|
|-|-|

Looking at the `attrs` repo, the `converter` synonym showed up in the 17.4.0 release, so Twisted's requirement should be good enough: https://github.com/python-attrs/attrs/pull/315

Veselin, since you are only seeing the exception in a child process and not in the parent, is it possible that the child process is executing with a different Python path (not the one from the virtualenv) and is getting an older version of `attrs` by mistake?

Could you try printing `sys.path` and `attrs.__version__` in the child process to make sure it is using the versions it is supposed to?

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_6"></a>|@glyph set status to `closed`|
|-|-|

This appears to have been an issue in the submitter's environment, not a problem with Twisted.
