### ISSUE TITLE
KeyError running trial -j on MacOS / Python 2.7.15

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9521]
|[<img alt="teratorn's avatar" src="https://avatars.githubusercontent.com/u/154069?s=50" width="50" height="50">](https://github.com/teratorn)| @teratorn reported|
|-|-|
|Trac ID|trac#9521|
|Type|defect|
|Created|2018-09-02 15:07:50Z|

Running `venv/bin/trial -j 8 twisted` in a python 2.7.15 (homebrew) virtualenv using Twisted git trunk.

I'm getting errors like this, but it's not always the same key.. it seems to be rather ambiguous when it fails, but it's always after about 10 seconds, and it seems to be near the start of the TLSTests, but which test name will be in the key it is looking for is non-deterministic.

Running without -j works fine.

```
  SASLPLAINTests
    test_credentialsInvalidResponse ...                                    [OK]
  TLSTests
    test_loginBeforeSTARTTLS ...                                      [SKIPPED]
    test_startTLS ...                                                 [SKIPPED]
    test_startTLSWithExistingChallengers ...                          [SKIPPED]
    testAPileOfThings ...                                             [SKIPPED]
    testFailedStartTLS ...                                            [SKIPPED]
    test_doubleSTARTTLS ...                                           [SKIPPED]
    testLoginLogin ...                                                [SKIPPED]
Unhandled Error
Traceback (most recent call last):
  File "/Users/teratorn/code/twisted/src/twisted/protocols/amp.py", line 1043, in _commandReceived
    deferred = self.dispatchCommand(box)
  File "/Users/teratorn/code/twisted/src/twisted/protocols/amp.py", line 1101, in dispatchCommand
    return maybeDeferred(responder, box)
  File "/Users/teratorn/code/twisted/src/twisted/internet/defer.py", line 151, in maybeDeferred
    result = f(*args, **kw)
  File "/Users/teratorn/code/twisted/src/twisted/protocols/amp.py", line 1188, in doit
    return maybeDeferred(aCallable, **kw).addCallback(
--- <exception caught here> ---
  File "/Users/teratorn/code/twisted/src/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/Users/teratorn/code/twisted/src/twisted/protocols/amp.py", line 1171, in checkKnownErrors
    key = error.trap(*command.allErrors)
  File "/Users/teratorn/code/twisted/src/twisted/python/failure.py", line 441, in trap
    raise self
  File "/Users/teratorn/code/twisted/src/twisted/internet/defer.py", line 151, in maybeDeferred
    result = f(*args, **kw)
  File "/Users/teratorn/code/twisted/src/twisted/trial/_dist/worker.py", line 128, in addSkip
    self._result.addSkip(self._testCase, reason)
  File "/Users/teratorn/code/twisted/src/twisted/trial/_dist/distreporter.py", line 59, in addSkip
    self.running[test.id()].append((self.original.addSkip,
exceptions.KeyError: 'twisted.mail.test.test_imap.TLSTests.test_loginBeforeSTARTTLS'
```

another example:

```
  SASLPLAINTests
    test_credentialsInvalidResponse ...                                    [OK]
  TLSTests
    testAPileOfThings ...                                             [SKIPPED]
    test_startTLSWithExistingChallengers ...                          [SKIPPED]
Unhandled Error
Traceback (most recent call last):
  File "/Users/teratorn/code/twisted/src/twisted/protocols/amp.py", line 1043, in _commandReceived
    deferred = self.dispatchCommand(box)
  File "/Users/teratorn/code/twisted/src/twisted/protocols/amp.py", line 1101, in dispatchCommand
    return maybeDeferred(responder, box)
  File "/Users/teratorn/code/twisted/src/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/Users/teratorn/code/twisted/src/twisted/protocols/amp.py", line 1188, in doit
    return maybeDeferred(aCallable, **kw).addCallback(
--- <exception caught here> ---
  File "/Users/teratorn/code/twisted/src/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/Users/teratorn/code/twisted/src/twisted/trial/_dist/worker.py", line 133, in addSkip
    self._result.addSkip(self._testCase, reason)
  File "/Users/teratorn/code/twisted/src/twisted/trial/_dist/distreporter.py", line 59, in addSkip
    self.running[test.id()].append((self.original.addSkip,
exceptions.KeyError: 'twisted.mail.test.test_imap.TLSTests.testAPileOfThings'

                            [FAIL]
    testFailedStartTLS ...                                            [SKIPPED]
```

<details><summary>Searchable metadata</summary>

```
trac-id__9521 9521
type__defect defect
reporter__teratorn teratorn
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__trial trial
keywords__None None
time__1535900870818995 1535900870818995
changetime__1535900926858454 1535900926858454
version__None None
owner__None None
cc__jml
```
</details>

**Comment by adiroiban** [comment]
I think that was fixed as of the latest improvements done by @exarkun for trial.

I have enabled macOS tests on GitHub actions with -j4 and there was no error.

it looks all good on our CI with -j4 - https://github.com/twisted/twisted/pull/11665

I think this can be closed .

If this is still an issue, please re-open
