### ISSUE TITLE
trial.test.test_loader.FileTests.test_directoryNotPackage: os.fspath() needs not NoneType

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9523]
|[<img alt="altendky's avatar" src="https://avatars.githubusercontent.com/u/543719?s=50" width="50" height="50">](https://github.com/altendky)| @altendky reported|
|-|-|
|Trac ID|trac#9523|
|Type|defect|
|Created|2018-09-06 13:28:56Z|

https://travis-ci.org/twisted/twisted/jobs/425258725#L3342

https://ci.appveyor.com/project/adiroiban/twisted/build/trunk-5347/job/yuqn8cgxx794pst3#L18027

```python
[FAIL]
Traceback (most recent call last):
  File "c:\projects\twisted\build\py37-alldeps-withcov-windows\lib\site-packages\twisted\trial\test\test_loader.py", line 187, in test_directoryNotPackage
    emptyDir.path)
  File "c:\projects\twisted\build\py37-alldeps-withcov-windows\lib\site-packages\twisted\trial\_synctest.py", line 421, in assertRaises
    return context._handle(lambda: f(*args, **kwargs))
  File "c:\projects\twisted\build\py37-alldeps-withcov-windows\lib\site-packages\twisted\trial\_synctest.py", line 315, in _handle
    self._returnValue = obj()
  File "c:\projects\twisted\build\py37-alldeps-withcov-windows\lib\site-packages\twisted\trial\_synctest.py", line 353, in __exit__
    self._expectedName, reason.getTraceback()),
twisted.trial.unittest.FailTest: builtins.TypeError raised instead of ValueError:
 Traceback (most recent call last):
  File "c:\projects\twisted\build\py37-alldeps-withcov-windows\lib\site-packages\twisted\python\util.py", line 1006, in runWithWarningsSuppressed
    return f(*args, **kwargs)
  File "c:\projects\twisted\build\py37-alldeps-withcov-windows\lib\site-packages\twisted\trial\test\test_loader.py", line 187, in test_directoryNotPackage
    emptyDir.path)
  File "c:\projects\twisted\build\py37-alldeps-withcov-windows\lib\site-packages\twisted\trial\_synctest.py", line 421, in assertRaises
    return context._handle(lambda: f(*args, **kwargs))
  File "c:\projects\twisted\build\py37-alldeps-withcov-windows\lib\site-packages\twisted\trial\_synctest.py", line 315, in _handle
    self._returnValue = obj()
--- <exception caught here> ---
  File "c:\projects\twisted\build\py37-alldeps-withcov-windows\lib\site-packages\twisted\trial\_synctest.py", line 315, in _handle
    self._returnValue = obj()
  File "c:\projects\twisted\build\py37-alldeps-withcov-windows\lib\site-packages\twisted\trial\_synctest.py", line 421, in <lambda>
    return context._handle(lambda: f(*args, **kwargs))
  File "c:\projects\twisted\build\py37-alldeps-withcov-windows\lib\site-packages\twisted\trial\runner.py", line 113, in filenameToModule
    retFile = os.path.splitext(ret.__file__)[0] + '.py'
  File "c:\projects\twisted\build\py37-alldeps-withcov-windows\lib\ntpath.py", line 202, in splitext
    p = os.fspath(p)
builtins.TypeError: expected str, bytes or os.PathLike object, not NoneType
twisted.trial.test.test_loader.FileTests.test_directoryNotPackage
```

<details><summary>Searchable metadata</summary>

```
trac-id__9523 9523
type__defect defect
reporter__altendky altendky
priority__normal normal
milestone__Python_3_7_support Python 3.7 support
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__trial trial
keywords__review review
time__1536240536827043 1536240536827043
changetime__1536262832654460 1536262832654460
version__None None
owner__rodrigc rodrigc

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="altendky's avatar" src="https://avatars.githubusercontent.com/u/543719?s=50" width="50" height="50">](https://github.com/altendky)|@altendky set owner to @altendky|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="altendky's avatar" src="https://avatars.githubusercontent.com/u/543719?s=50" width="50" height="50">](https://github.com/altendky)<a name="note_2"></a>|@altendky commented|
|-|-|

In 3.7 the module object now has `__file__` as `None` rather than it simply be a missing attribute.

https://github.com/twisted/twisted/pull/1059

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_4"></a>|@rodrigc commented|
|-|-|

Approved: https://github.com/twisted/twisted/pull/1059#pullrequestreview-152963808

**Comment by twisted-trac** [comment]
|[<img alt="altendky's avatar" src="https://avatars.githubusercontent.com/u/543719?s=50" width="50" height="50">](https://github.com/altendky)<a name="note_5"></a>|@altendky set owner to @rodrigc|
|-|-|

Should I be assigning this to you?  Or nobody...

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_6"></a>|@rodrigc set status to `closed`|
|-|-|

In changeset 83be162e5c12a0d7c6eadf6012663502c669d6b0
```
#!CommitTicketReference repository="" revision="83be162e5c12a0d7c6eadf6012663502c669d6b0"
Merge pull request #1059 from altendky/9523-altendky-directory_not_package

Author: altendky
Reviewer: rodrigc
Fixes: ticket:9523

Account for change in 3.7 for __import__ and __file__ attribute
```
