### ISSUE TITLE
python.test.test_zipstream.ZipstreamTests.test_extraData: BadZipFile: Corrupt extra field

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9525]
|[<img alt="altendky's avatar" src="https://avatars.githubusercontent.com/u/543719?s=50" width="50" height="50">](https://github.com/altendky)| @altendky reported|
|-|-|
|Trac ID|trac#9525|
|Type|defect|
|Created|2018-09-06 13:31:42Z|
|Branch|https://github.com/twisted/twisted/tree/9525-altendky-skip_zipstream_extra_data_test|

https://travis-ci.org/twisted/twisted/jobs/425258725#L3403

https://ci.appveyor.com/project/adiroiban/twisted/build/trunk-5347/job/txb4qptgyiveou17#L18056

```python
[ERROR]
Traceback (most recent call last):
  File "c:\projects\twisted\build\py37-alldeps-withcov-windows\lib\site-packages\twisted\python\test\test_zipstream.py", line 253, in test_extraData
    with zipstream.ChunkingZipFile(fn) as czf, czf.readfile("0") as zfe:
  File "C:\PYTHON37-x64\Lib\zipfile.py", line 1200, in __init__
    self._RealGetContents()
  File "C:\PYTHON37-x64\Lib\zipfile.py", line 1323, in _RealGetContents
    x._decodeExtra()
  File "C:\PYTHON37-x64\Lib\zipfile.py", line 440, in _decodeExtra
    raise BadZipFile("Corrupt extra field %04x (size=%d)" % (tp, ln))
zipfile.BadZipFile: Corrupt extra field 6568 (size=27756)
twisted.python.test.test_zipstream.ZipstreamTests.test_extraData
```

<details><summary>Searchable metadata</summary>

```
trac-id__9525 9525
type__defect defect
reporter__altendky altendky
priority__normal normal
milestone__Python_3_7_support Python 3.7 support
branch__9525_altendky_skip_zipstream_extra_data_test 9525-altendky-skip_zipstream_extra_data_test
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__None None
time__1536240702773518 1536240702773518
changetime__1536450594071307 1536450594071307
version__None None
owner__hawkowl hawkowl
cc__altendky
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="altendky's avatar" src="https://avatars.githubusercontent.com/u/543719?s=50" width="50" height="50">](https://github.com/altendky)|@altendky set owner to @altendky|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="altendky's avatar" src="https://avatars.githubusercontent.com/u/543719?s=50" width="50" height="50">](https://github.com/altendky)<a name="note_2"></a>|@altendky commented|
|-|-|

Hmm, seems to be broken in Python 3.7 itself.  I'll have to dig to figure out if this is something that should work (seems like it given it does everywhere else).

Both 3.6 and 3.7 generate the same file and 3.7 is unable to read either.

```python3
altendky@lt:~/twisted$ cat ../z.py
import sys
import zipfile

print(sys.version)

fn = sys.argv[1]
print(fn)

with zipfile.ZipFile(fn, 'w') as zf:
    zi = zipfile.ZipInfo("0")
    zi.extra = b"hello, extra"
    zf.writestr(zi, b"the real data")

zipfile.ZipFile(fn)
```

```python3
altendky@lt:~/twisted$ venv36/bin/python ../z.py 36.zip
3.6.6 (default, Jul 24 2018, 16:23:12) 
[GCC 6.3.0 20170516]
36.zip
```

```python3
altendky@lt:~/twisted$ venv37/bin/python ../z.py 37.zip
3.7.0 (default, Jul  7 2018, 15:49:24) 
[GCC 6.3.0 20170516]
37.zip
Traceback (most recent call last):
  File "../z.py", line 14, in <module>
    zipfile.ZipFile(fn)
  File "/home/altendky/.pyenv/versions/3.7.0/lib/python3.7/zipfile.py", line 1200, in __init__
    self._RealGetContents()
  File "/home/altendky/.pyenv/versions/3.7.0/lib/python3.7/zipfile.py", line 1323, in _RealGetContents
    x._decodeExtra()
  File "/home/altendky/.pyenv/versions/3.7.0/lib/python3.7/zipfile.py", line 440, in _decodeExtra
    raise BadZipFile("Corrupt extra field %04x (size=%d)" % (tp, ln))
zipfile.BadZipFile: Corrupt extra field 6568 (size=27756)
```

```python3
altendky@lt:~/twisted$ cat ../z.py
import sys
import zipfile

print(sys.version)

fn = sys.argv[1]
print(fn)

#with zipfile.ZipFile(fn, 'w') as zf:
#    zi = zipfile.ZipInfo("0")
#    zi.extra = b"hello, extra"
#    zf.writestr(zi, b"the real data")

zipfile.ZipFile(fn)
```

```python3
altendky@lt:~/twisted$ venv36/bin/python ../z.py 37.zip
3.6.6 (default, Jul 24 2018, 16:23:12) 
[GCC 6.3.0 20170516]
37.zip
```

```python3
altendky@lt:~/twisted$ venv37/bin/python ../z.py 36.zip
3.7.0 (default, Jul  7 2018, 15:49:24) 
[GCC 6.3.0 20170516]
36.zip
Traceback (most recent call last):
  File "../z.py", line 14, in <module>
    zipfile.ZipFile(fn)
  File "/home/altendky/.pyenv/versions/3.7.0/lib/python3.7/zipfile.py", line 1200, in __init__
    self._RealGetContents()
  File "/home/altendky/.pyenv/versions/3.7.0/lib/python3.7/zipfile.py", line 1323, in _RealGetContents
    x._decodeExtra()
  File "/home/altendky/.pyenv/versions/3.7.0/lib/python3.7/zipfile.py", line 440, in _decodeExtra
    raise BadZipFile("Corrupt extra field %04x (size=%d)" % (tp, ln))
zipfile.BadZipFile: Corrupt extra field 6568 (size=27756)
```

```python3
altendky@lt:~/twisted$ sha256sum 36.zip
0f54bd6ab84facfeefc2c38f12c30eb84101b3be3d91f8826f6fa36e73b86cb6  36.zip
```

```python3
altendky@lt:~/twisted$ sha256sum 37.zip
0f54bd6ab84facfeefc2c38f12c30eb84101b3be3d91f8826f6fa36e73b86cb6  37.zip
```

**Comment by twisted-trac** [comment]
|[<img alt="altendky's avatar" src="https://avatars.githubusercontent.com/u/543719?s=50" width="50" height="50">](https://github.com/altendky)<a name="note_3"></a>|@altendky commented|
|-|-|

`unzip` is also able to handle the files.

```python3
altendky@lt:~/twisted$ unzip 36.zip
Archive:  36.zip
 extracting: 0                       
```

```python3
altendky@lt:~/twisted$ unzip 37.zip
Archive:  37.zip
replace 0? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
 extracting: 0                       
```

```python3
altendky@lt:~/twisted$ cat 0
the real dataaltendky@lt:~/twisted$
```

**Comment by twisted-trac** [comment]
|[<img alt="altendky's avatar" src="https://avatars.githubusercontent.com/u/543719?s=50" width="50" height="50">](https://github.com/altendky)<a name="note_4"></a>|@altendky commented|
|-|-|

https://github.com/twisted/twisted/pull/1061

**Comment by twisted-trac** [comment]
|[<img alt="altendky's avatar" src="https://avatars.githubusercontent.com/u/543719?s=50" width="50" height="50">](https://github.com/altendky)<a name="note_5"></a>|@altendky removed owner|
|-|-|

Reported upstream.

https://bugs.python.org/issue34606

**Comment by twisted-trac** [comment]
|[<img alt="altendky's avatar" src="https://avatars.githubusercontent.com/u/543719?s=50" width="50" height="50">](https://github.com/altendky)<a name="note_6"></a>|@altendky commented|
|-|-|

https://bugs.python.org/issue34606

My bad, I ought have read the docs...  They link to:

https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT

Python 3.7 works with 2-byte elements.

4.5 Extensible data fields
    --------------------------
    
       4.5.1 In order to allow different programs and different types
       of information to be stored in the 'extra' field in .ZIP
       files, the following structure MUST be used for all
       programs storing data in this field:
    
           header1+data1 + header2+data2 . . .
    
       Each header should consist of:
    
           Header ID - 2 bytes
           Data Size - 2 bytes
    
       Note: all fields stored in Intel low-byte/high-byte order.

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_9"></a>|@hawkowl set owner to @hawkowl|
|-|-|

lgtm

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_10"></a>|@hawkowl set status to `closed`|
|-|-|

In changeset 5922202d42dc074f6109feecdf5798cec8dc65e7
```
#!CommitTicketReference repository="" revision="5922202d42dc074f6109feecdf5798cec8dc65e7"
Merge 9525-altendky-skip_zipstream_extra_data_test: correct python.test.test_zipstream.ZipstreamTests.test_extraData

Author: altendky
Reviewer: hawkowl
Fixes: ticket:9525
```
