### ISSUE TITLE
test_openDirectoryIterator raised builtins.RuntimeError: generator raised StopIteration

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9527]
|[<img alt="altendky's avatar" src="https://avatars.githubusercontent.com/u/543719?s=50" width="50" height="50">](https://github.com/altendky)| @altendky reported|
|-|-|
|Trac ID|trac#9527|
|Type|defect|
|Created|2018-09-06 20:18:39Z|

Not merged yet but shows up in: [#9445](https://github.com/twisted/twisted/issues/9445) https://circleci.com/gh/twisted/twisted/1984

```python
[ERROR]
Traceback (most recent call last):
  File "/Users/distiller/repo/build/py37-alldeps-withcov-posix/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
builtins.RuntimeError: generator raised StopIteration

twisted.conch.test.test_filetransfer.OurServerOurClientTests.test_openDirectoryIterator
```

<details><summary>Searchable metadata</summary>

```
trac-id__9527 9527
type__defect defect
reporter__altendky altendky
priority__normal normal
milestone__Python_3_7_support Python 3.7 support
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__conch conch
keywords__None None
time__1536265119950676 1536265119950676
changetime__1537876307170638 1537876307170638
version__None None
owner__hawkowl hawkowl

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="altendky's avatar" src="https://avatars.githubusercontent.com/u/543719?s=50" width="50" height="50">](https://github.com/altendky)<a name="note_1"></a>|@altendky commented|
|-|-|

Maybe it isn't just OS X...

https://travis-ci.org/twisted/twisted/jobs/425924316#L3346

**Comment by twisted-trac** [comment]
|[<img alt="altendky's avatar" src="https://avatars.githubusercontent.com/u/543719?s=50" width="50" height="50">](https://github.com/altendky)<a name="note_3"></a>|@altendky commented|
|-|-|

Well, no issue when run locally from PyCharm in Linux...

```python3
Testing started at 10:55 AM ...
/home/altendky/twisted/venv27/bin/python /home/altendky/.local/share/JetBrains/Toolbox/apps/PyCharm-C/ch-1/181.4668.13/helpers/pycharm/_jb_trialtest_runner.py --target test_filetransfer.OurServerOurClientTests.test_openDirectoryIterator
Launching trial with arguments --reporter=teamcity test_filetransfer.OurServerOurClientTests.test_openDirectoryIterator in /home/altendky/twisted/src/twisted/conch/test

-------------------------------------------------------------------------------
Ran 1 tests in 0.006s

PASSED (successes=1)
Process finished with exit code 0
```

But it does fail from the CLI.

```python3
 ~/twisted   trunk  venv37/bin/trial twisted.conch.test.test_filetransfer.OurServerOurClientTests.test_openDirectoryIterator
twisted.conch.test.test_filetransfer
  OurServerOurClientTests
    test_openDirectoryIterator ...                                      [ERROR]

===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/home/altendky/twisted/src/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
builtins.RuntimeError: generator raised StopIteration

twisted.conch.test.test_filetransfer.OurServerOurClientTests.test_openDirectoryIterator
-------------------------------------------------------------------------------
Ran 1 tests in 0.006s

FAILED (errors=1)
```

**Comment by twisted-trac** [comment]
|[<img alt="altendky's avatar" src="https://avatars.githubusercontent.com/u/543719?s=50" width="50" height="50">](https://github.com/altendky)<a name="note_4"></a>|@altendky commented|
|-|-|

https://docs.python.org/3/whatsnew/3.7.html

> PEP 479 is enabled for all code in Python 3.7, meaning that StopIteration exceptions raised directly or indirectly in coroutines and generators are transformed into RuntimeError exceptions. (Contributed by Yury Selivanov in bpo-32670.)

https://www.python.org/dev/peps/pep-0479/

https://docs.python.org/3/library/exceptions.html#StopIteration

https://docs.python.org/3/library/exceptions.html#RuntimeError

https://bugs.python.org/issue32670

Consequences for existing code
https://www.python.org/dev/peps/pep-0479/#consequences-for-existing-code

**Comment by twisted-trac** [comment]
|[<img alt="altendky's avatar" src="https://avatars.githubusercontent.com/u/543719?s=50" width="50" height="50">](https://github.com/altendky)<a name="note_5"></a>|@altendky commented|
|-|-|

I think...

https://github.com/twisted/twisted/blob/f718334ba6c43992b231b6e1c7767924b8efb46a/src/twisted/conch/ssh/filetransfer.py#L945
```python
def _ebReadDir(self, reason):
    reason.trap(EOFError)
    self.filesCache = None
    return failure.Failure(StopIteration())
```

`_ebReadDir()` is 'raising' `StopIteration` via the `Failure` which gets translated along the magical `_inlineCallbacks` path into a `RuntimeError` per PEP-0479.  As such...

https://github.com/twisted/twisted/blob/f718334ba6c43992b231b6e1c7767924b8efb46a/src/twisted/internet/defer.py#L1419
```python
try:
    # Send the last result back as the result of the yield expression.
    isFailure = isinstance(result, failure.Failure)
    if isFailure:
        result = result.throwExceptionIntoGenerator(g)
    else:
        result = g.send(result)
except StopIteration as e:
    # fell off the end, or "return" statement
    status.deferred.callback(getattr(e, "value", None))
    return
```

presently misses the exception.

I'm not yet sure what a 'real fix' should look like, but I will try pushing a thing that seems to pass tests.  Just in case looking at such a thing inspires anyone else (or myself) (or it doesn't actually pass tests).

**Comment by twisted-trac** [comment]
|[<img alt="altendky's avatar" src="https://avatars.githubusercontent.com/u/543719?s=50" width="50" height="50">](https://github.com/altendky)<a name="note_6"></a>|@altendky commented|
|-|-|

https://github.com/twisted/twisted/pull/1065

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_7"></a>|@hawkowl commented|
|-|-|

See the PR. The lint failures and the windows failures are spurious.

https://github.com/twisted/twisted/pull/1066

**Comment by twisted-trac** [comment]
|[<img alt="altendky's avatar" src="https://avatars.githubusercontent.com/u/543719?s=50" width="50" height="50">](https://github.com/altendky)|@altendky set owner to @altendky|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="altendky's avatar" src="https://avatars.githubusercontent.com/u/543719?s=50" width="50" height="50">](https://github.com/altendky)<a name="note_9"></a>|@altendky set owner to @hawkowl|
|-|-|

https://github.com/twisted/twisted/pull/1066#pullrequestreview-155144288

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)|@hawkowl set status to `closed`|
|-|-|
