### ISSUE TITLE
twisted.web.client can fail with `exceptions.ValueError: list.remove(x): x not in list`

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9547]
|[<img alt="richvdh's avatar" src="https://avatars.githubusercontent.com/u/1389908?s=50" width="50" height="50">](https://github.com/richvdh)| @richvdh reported|
|-|-|
|Trac ID|trac#9547|
|Type|defect|
|Created|2018-10-09 11:56:40Z|

If an outgoing HTTP request is cancelled between the `connect` call and the request being written to the socket, then we later get an unhandled exception reported by the reactor:

```
Unhandled Error
Traceback (most recent call last):
  File "./test.py", line 59, in <module>
    reactor.run()
  File "/home/rav/work/synapse/env3/lib/python3.5/site-packages/twisted/internet/base.py", line 1261, in run
    self.mainLoop()
  File "/home/rav/work/synapse/env3/lib/python3.5/site-packages/twisted/internet/base.py", line 1270, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/home/rav/work/synapse/env3/lib/python3.5/site-packages/twisted/internet/base.py", line 896, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/home/rav/work/synapse/env3/lib/python3.5/site-packages/twisted/internet/task.py", line 671, in _tick
    taskObj._oneWorkUnit()
  File "/home/rav/work/synapse/env3/lib/python3.5/site-packages/twisted/internet/task.py", line 521, in _oneWorkUnit
    self._completeWith(TaskFailed(), Failure())
  File "/home/rav/work/synapse/env3/lib/python3.5/site-packages/twisted/internet/task.py", line 477, in _completeWith
    self._cooperator._removeTask(self)
  File "/home/rav/work/synapse/env3/lib/python3.5/site-packages/twisted/internet/task.py", line 644, in _removeTask
    self._tasks.remove(task)
builtins.ValueError: list.remove(x): x not in list
```

The error is relatively harmless, but does cause noise and confusion which distracts from other problems.

I'll attach a script which demonstrates the problem. It's slightly contrived by sticking a sleep() call in the middle, but the race condition is otherwise hard to reproduce.

It seems two attempts are being made to remove the  `FileBodyProducer`'s write loop task - once when the request is cancelled, and again when the write loop later raises an exception. 

Attachments:

* [test.py](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/94f/94fe322414f7c75cf23f427792e57379c7dbf3bd/a36e355ddb203d7d4133221f339dc406cb9f480f.py) (1592 bytes) - added by richvdh on 2018-10-09 11:57:28Z - script demonstrating the issue

<details><summary>Searchable metadata</summary>

```
trac-id__9547 9547
type__defect defect
reporter__richvdh richvdh
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__None None
time__1539086200557248 1539086200557248
changetime__1570395994582746 1570395994582746
version__None None
owner__glyph glyph

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="jchenggggg's avatar" src="https://avatars.githubusercontent.com/u/3377634?s=50" width="50" height="50">](https://github.com/jchenggggg)<a name="note_1"></a>|@jchenggggg commented|
|-|-|

Pull request: https://github.com/twisted/twisted/pull/1184

From the pull request:

`twisted.web._newclient.Request._writeToBodyProducerContentLength` returns a deferred that will be `callback`ed or `errback`ed depending on whether a Producer and Consumer pair are successful in writing the request body to the transport.  This deferred has a canceller, which calls the Producer's canceller.  However, the producer being used to reproduce the bug in 9547 (`FileBodyProducer`) has no canceller, so this just results in the cancel failure being passed to the producer's errback chain.  This errback assumes that since the producer is errbacking, it should already have stopped producing, so `stopProducing` is not called in this case.  However, the errback does stop the consumer.

This means that after the request has been cancelled, the producer will continue to produce as it is a scheduled task.  But the consumer in this case (`LengthEnforcingConsumer`) does not expect the producer to continue to write to it, and so when the producer tries to write, execution comes to a branch at `twisted/web/_newclient.py:992`, which has a comment stating that if you've reached it then you've written a bug.  In this branch, `stopProducing` is called on the producer (removing it from the task queue), and then an exception is raised (which causes the producer job to fail, and causes the task scheduler to try to remove the task from the queue again.) . This causes the exception reported in 9547.

This PR adds a canceller to `FileBodyProducer`.  The canceller calls `stopProducing`, which will prevent the producer from trying to produce after the request has already been cancelled.  As far as I can tell, `FileBodyProducer` is the only implementer of `IBodyProducer` for which it would make sense to have a canceller.  The other way to do this would have been to have `twisted.web._newclient.Request._writeToBodyProducerContentLength` call `stopProducing` directly instead of calling cancel on the producer's deferred, but to me it seems to make more sense that Producers should be the ones to know how to cancel themselves.

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_2"></a>|@twm set owner to @twm<br>@twm set status to `assigned`|
|-|-|

I'm assigning this to myself as I plan to do a review early next week. However, if anyone else gets to it sooner feel free to steal it.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)|@glyph set owner to @jchenggggg<br>@glyph set status to `new`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="jchenggggg's avatar" src="https://avatars.githubusercontent.com/u/3377634?s=50" width="50" height="50">](https://github.com/jchenggggg)<a name="note_4"></a>|@jchenggggg removed owner|
|-|-|

.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_5"></a>|@glyph set owner to @glyph|
|-|-|

Ready to merge this now, just waiting for CI to finish up.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_6"></a>|@glyph set status to `closed`|
|-|-|

In changeset e9b6f565faccd3ff7525a277719a851d43ca8c51
```
#!CommitTicketReference repository="" revision="e9b6f565faccd3ff7525a277719a851d43ca8c51"
Merge pull request #1184 from jchenggggg/9547-jchenggggg-make-filebodyproducer-cancellable

Author: jchenggggg

Reviewer: glyph

Fixes: ticket:9547

twisted.web.client.FileBodyProducer will now stop producing when the Deferred returned by FileBodyProducer.startProducing is cancelled.
```

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_7"></a>|@glyph commented|
|-|-|

Thank you for fixing this bug - your bearing with the process and driving this to completion is much appreciated!
