### ISSUE TITLE
@unittest.expectedFailure decorator breaks trial again

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9557]
|[<img alt="NotAFile's avatar" src="https://avatars.githubusercontent.com/u/5447747?s=50" width="50" height="50">](https://github.com/NotAFile)| @NotAFile reported|
|-|-|
|Trac ID|trac#9557|
|Type|defect|
|Created|2018-10-22 23:41:29Z|

Seems to be a regression on [#1837](https://github.com/twisted/twisted/issues/1837) and [#4811](https://github.com/twisted/twisted/issues/4811).

```
$ cat tests_crap.py                                                                                                                                    
import unittest
class Foo(unittest.TestCase):
    @unittest.expectedFailure
    def test_crap(self):
        1/0

$ trial tests_crap                                                                                                                                 
tests_crap
  Foo
    test_crap ...                                                        [TODO]

Traceback (most recent call last):
  File "/home/nota/prj/piqueserver/.venv/bin/trial", line 11, in <module>
    sys.exit(run())
  File "/home/nota/prj/piqueserver/.venv/lib/python3.6/site-packages/twisted/scripts/trial.py", line 621, in run
    test_result = trialRunner.run(suite)
  File "/home/nota/prj/piqueserver/.venv/lib/python3.6/site-packages/twisted/trial/runner.py", line 979, in run
    return self._runWithoutDecoration(test, self._forceGarbageCollection)
  File "/home/nota/prj/piqueserver/.venv/lib/python3.6/site-packages/twisted/trial/runner.py", line 1025, in _runWithoutDecoration
    result.done()
  File "/home/nota/prj/piqueserver/.venv/lib/python3.6/site-packages/twisted/trial/reporter.py", line 721, in done
    self._printErrors()
  File "/home/nota/prj/piqueserver/.venv/lib/python3.6/site-packages/twisted/trial/reporter.py", line 670, in _printErrors
    self._printExpectedFailure)
  File "/home/nota/prj/piqueserver/.venv/lib/python3.6/site-packages/twisted/trial/reporter.py", line 642, in _printResults
    for reason, cases in self._groupResults(errors, formatter):
  File "/home/nota/prj/piqueserver/.venv/lib/python3.6/site-packages/twisted/trial/reporter.py", line 628, in _groupResults
    key = formatter(*outcome)
  File "/home/nota/prj/piqueserver/.venv/lib/python3.6/site-packages/twisted/trial/reporter.py", line 653, in _printExpectedFailure
    self._formatFailureTraceback(error))
  File "/home/nota/prj/piqueserver/.venv/lib/python3.6/site-packages/twisted/trial/reporter.py", line 599, in _formatFailureTraceback
    fail.frames, frames = self._trimFrames(fail.frames), fail.frames
AttributeError: 'tuple' object has no attribute 'frames'
```

<details><summary>Searchable metadata</summary>

```
trac-id__9557 9557
type__defect defect
reporter__NotAFile NotAFile
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__trial trial
keywords__None None
time__1540251689705975 1540251689705975
changetime__1540294383811384 1540294383811384
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="Julian's avatar" src="https://avatars.githubusercontent.com/u/329822?s=50" width="50" height="50">](https://github.com/Julian)<a name="note_2"></a>|@Julian commented|
|-|-|

(It's not a regression, it never worked to begin with unfortunately, see [#4811](https://github.com/twisted/twisted/issues/4811)#comment:18 , but I think at the time I didn't have merge rights.)
