### ISSUE TITLE
HTTPChannel TB if bad header

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9558]
|[<img alt="barry-scott-forcepoint's avatar" src="https://avatars.githubusercontent.com/u/34742205?s=50" width="50" height="50">](https://github.com/barry-scott-forcepoint)| @barry-scott-forcepoint reported|
|-|-|
|Trac ID|trac#9558|
|Type|defect|
|Created|2018-10-23 15:08:09Z|

We see the following TB because this test is not true

basic.py:575 in LineReceiver.dataReceived()
                        why = self.lineReceived(line)
                        if (why or self.transport and
                            self.transport.disconnecting):
                            return why

lineReceived() does not return an 'why' and transport.disconnecting
is not set immediately by loseConnection call.

        Traceback (most recent call last):
          File "/usr/local/lib/python2.7/site-packages/twisted/python/log.py", line 103, in callWithLogger
            return callWithContext({"system": lp}, func, *args, **kw)
          File "/usr/local/lib/python2.7/site-packages/twisted/python/log.py", line 86, in callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File "/usr/local/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/usr/local/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
            return func(*args,**kw)
        --- <exception caught here> ---
          File "/usr/local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
            why = selectable.doRead()
          File "/usr/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 243, in doRead
            return self._dataReceived(data)
          File "/usr/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
            rval = self.protocol.dataReceived(data)
          File "/usr/local/lib/python2.7/site-packages/twisted/protocols/tls.py", line 330, in dataReceived
            self._flushReceiveBIO()
          File "/usr/local/lib/python2.7/site-packages/twisted/protocols/tls.py", line 295, in _flushReceiveBIO
            ProtocolWrapper.dataReceived(self, bytes)
          File "/usr/local/lib/python2.7/site-packages/twisted/protocols/policies.py", line 120, in dataReceived
            self.wrappedProtocol.dataReceived(data)
          File "/usr/local/lib/python2.7/site-packages/twisted/web/http.py", line 2922, in dataReceived
            return self._channel.dataReceived(data)
          File "/usr/local/lib/python2.7/site-packages/twisted/web/http.py", line 2217, in dataReceived
            return basic.LineReceiver.dataReceived(self, data)
          File "/usr/local/lib/python2.7/site-packages/twisted/protocols/basic.py", line 575, in dataReceived
            why = self.lineReceived(line)
          File "/usr/local/lib/python2.7/site-packages/twisted/web/http.py", line 2102, in lineReceived
            self.allHeadersReceived()
          File "/usr/local/lib/python2.7/site-packages/twisted/web/http.py", line 2232, in allHeadersReceived
            wd_logging.logAlways( 'HTTPChannel.allHeadersReceived() hasattr(_version) %r getattr(_version) %r', hasattr(self, '_version'), getattr(self, '_version'))
        exceptions.AttributeError: HTTPChannel instance has no attribute '_version'

Attachments:

* [twisted-http-line-receiver-disconnect.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/1c9/1c9b870c533c41f83093f4c09d293eb7f92ef3d3/8b9a2788039bc6ff46dfe23ac742c094877e1bab.patch) (1642 bytes) - added by barry-scott-forcepoint on 2018-10-23 16:08:09Z - patch

<details><summary>Searchable metadata</summary>

```
trac-id__9558 9558
type__defect defect
reporter__barry_scott_forcepoint barry-scott-forcepoint
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__None None
time__1540307289672063 1540307289672063
changetime__1554073946450617 1554073946450617
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

Thanks.  Can you please update the patch with automated unit tests demonstrating this bug and the fix?

**Comment by twisted-trac** [comment]
|[<img alt="wiml's avatar" src="https://avatars.githubusercontent.com/u/156891?s=50" width="50" height="50">](https://github.com/wiml)<a name="note_2"></a>|@wiml commented|
|-|-|

I notice that the practice of returning a truthy value from `lineReceived()` is not documented anywhere. Since it seems to be necessary in order to implement some protocols correctly (hence this bug), maybe it should be?

Or should there be a cleaner mechanism? I'm not sure exactly how I would describe the semantics of the `why = True` response.
