### ISSUE TITLE
JSON log output for WSGI exceptions does not include error message

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9574]
|[<img alt="coderanger's avatar" src="https://avatars.githubusercontent.com/u/128243?s=50" width="50" height="50">](https://github.com/coderanger)| @coderanger reported|
|-|-|
|Trac ID|trac#9574|
|Type|defect|
|Created|2019-01-16 02:45:28Z|

You can see the stack trace and (indirectly) the exception type, but the actual message is not included.

Example (formatted for readability):

```
{
    "log_failure": {
        "__class_uuid__": "e76887e2-20ed-49bf-a8f8-ba25cc586f2d",
        "captureVars": false,
        "count": 19,
        "frames": [
            [
                "run",
                "/usr/local/lib/python2.7/dist-packages/twisted/web/wsgi.py",
                505,
                [],
                []
            ]
        ],
        "parents": [
            "exceptions.TypeError",
            "exceptions.StandardError",
            "exceptions.Exception",
            "exceptions.BaseException",
            "__builtin__.object"
        ],
        "pickled": 1,
        "stack": [
            [
                "__bootstrap",
                "/usr/lib/python2.7/threading.py",
                774,
                [],
                []
            ],
            [
                "__bootstrap_inner",
                "/usr/lib/python2.7/threading.py",
                801,
                [],
                []
            ],
            [
                "run",
                "/usr/lib/python2.7/threading.py",
                754,
                [],
                []
            ],
            [
                "work",
                "/usr/local/lib/python2.7/dist-packages/twisted/_threads/_threadworker.py",
                45,
                [],
                []
            ],
            [
                "doWork",
                "/usr/local/lib/python2.7/dist-packages/twisted/_threads/_team.py",
                194,
                [],
                []
            ],
            [
                "inContext",
                "/usr/local/lib/python2.7/dist-packages/twisted/python/threadpool.py",
                261,
                [],
                []
            ],
            [
                "<lambda>",
                "/usr/local/lib/python2.7/dist-packages/twisted/python/threadpool.py",
                266,
                [],
                []
            ],
            [
                "callWithContext",
                "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py",
                122,
                [],
                []
            ],
            [
                "callWithContext",
                "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py",
                87,
                [],
                []
            ],
            [
                "run",
                "/usr/local/lib/python2.7/dist-packages/twisted/web/wsgi.py",
                533,
                [],
                []
            ]
        ],
        "tb": null,
        "type": {
            "__module__": "exceptions",
            "__name__": "TypeError"
        },
        "value": {
            "unpersistable": true
        }
    },
    "log_format": "WSGI application error",
    "log_level": {
        "__class_uuid__": "02e59486-f24d-46ad-8224-3acdf2a5732a",
        "name": "critical"
    },
    "log_logger": {
        "unpersistable": true
    },
    "log_namespace": "twisted.web.wsgi._WSGIResponse",
    "log_source": {
        "unpersistable": true
    },
    "log_time": 1547605597.19513
}
```

Compare to text format output:

```
2019-01-16T02:37:56+0000 [twisted.web.wsgi._WSGIResponse#critical] WSGI application error
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>
	    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 87, in callWithContext
	    self.contexts.pop()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/web/wsgi.py", line 533, in run
	    self.started = True
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/web/wsgi.py", line 505, in run
	    appIterator = self.application(self.environ, self.startResponse)
	exceptions.TypeError: 'module' object is not callable
```

It would be nice if the fully equivalent info was available in the JSON output, including the type, message, and code view.

<details><summary>Searchable metadata</summary>

```
trac-id__9574 9574
type__defect defect
reporter__coderanger coderanger
priority__high high
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__duplicate duplicate
component__web web
keywords__None None
time__1547606728817725 1547606728817725
changetime__1554856713348504 1554856713348504
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_1"></a>|@glyph set status to `closed`|
|-|-|

Thanks for reporting the issue.  It is indeed serious.  So serious in fact we had already filed it!

Duplicate of [#9198](https://github.com/twisted/twisted/issues/9198).
