### ISSUE TITLE
Several tests fail against cryptography 2.5

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9580]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#9580|
|Type|enhancement|
|Created|2019-01-25 01:55:09Z|

For example:

```
(twisted) exarkun@baryon:/tmp$ pip install --upgrade 'cryptography<2.5'
Collecting cryptography<2.5
  Downloading https://files.pythonhosted.org/packages/60/c7/99b33c53cf3f20a97a4c4bfd3ab66dcc93d99da0a97cc9597aa36ae6bb62/cryptography-2.4.2-cp34-abi3-manylinux1_x86_64.whl (2.1MB)
    100% |████████████████████████████████| 2.1MB 179kB/s 
Requirement already satisfied, skipping upgrade: asn1crypto>=0.21.0 in /home/exarkun/Environments/twisted/lib/python3.6/site-packages (from cryptography<2.5) (0.24.0)
Requirement already satisfied, skipping upgrade: cffi!=1.11.3,>=1.7 in /home/exarkun/Environments/twisted/lib/python3.6/site-packages (from cryptography<2.5) (1.11.5)
Requirement already satisfied, skipping upgrade: six>=1.4.1 in /home/exarkun/Environments/twisted/lib/python3.6/site-packages (from cryptography<2.5) (1.12.0)
Requirement already satisfied, skipping upgrade: idna>=2.1 in /home/exarkun/Environments/twisted/lib/python3.6/site-packages (from cryptography<2.5) (2.8)
Requirement already satisfied, skipping upgrade: pycparser in /home/exarkun/Environments/twisted/lib/python3.6/site-packages (from cffi!=1.11.3,>=1.7->cryptography<2.5) (2.19)
Installing collected packages: cryptography
  Found existing installation: cryptography 2.5
    Uninstalling cryptography-2.5:
      Successfully uninstalled cryptography-2.5
Successfully installed cryptography-2.4.2
(twisted) exarkun@baryon:/tmp$ trial twisted.test.test_sslverify.OpenSSLOptionsECDHIntegrationTests.test_ellipticCurveDiffieHellman
:0: UserWarning: You do not have a working installation of the service_identity module: 'No module named 'service_identity''.  Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module, Twisted can perform only rudimentary TLS client hostname verification.  Many valid certificate/hostname mappings may be rejected.
twisted.test.test_sslverify
  OpenSSLOptionsECDHIntegrationTests
    test_ellipticCurveDiffieHellman ...                                    [OK]

-------------------------------------------------------------------------------
Ran 1 tests in 0.103s

PASSED (successes=1)
(twisted) exarkun@baryon:/tmp$ pip install --upgrade 'cryptography==2.5'
Collecting cryptography==2.5
  Using cached https://files.pythonhosted.org/packages/98/71/e632e222f34632e0527dd41799f7847305e701f38f512d81bdf96009bca4/cryptography-2.5-cp34-abi3-manylinux1_x86_64.whl
Requirement already satisfied, skipping upgrade: asn1crypto>=0.21.0 in /home/exarkun/Environments/twisted/lib/python3.6/site-packages (from cryptography==2.5) (0.24.0)
Requirement already satisfied, skipping upgrade: cffi!=1.11.3,>=1.8 in /home/exarkun/Environments/twisted/lib/python3.6/site-packages (from cryptography==2.5) (1.11.5)
Requirement already satisfied, skipping upgrade: six>=1.4.1 in /home/exarkun/Environments/twisted/lib/python3.6/site-packages (from cryptography==2.5) (1.12.0)
Requirement already satisfied, skipping upgrade: pycparser in /home/exarkun/Environments/twisted/lib/python3.6/site-packages (from cffi!=1.11.3,>=1.8->cryptography==2.5) (2.19)
Installing collected packages: cryptography
  Found existing installation: cryptography 2.4.2
    Uninstalling cryptography-2.4.2:
      Successfully uninstalled cryptography-2.4.2
Successfully installed cryptography-2.5
(twisted) exarkun@baryon:/tmp$ trial twisted.test.test_sslverify.OpenSSLOptionsECDHIntegrationTests.test_ellipticCurveDiffieHellman
:0: UserWarning: You do not have a working installation of the service_identity module: 'No module named 'service_identity''.  Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module, Twisted can perform only rudimentary TLS client hostname verification.  Many valid certificate/hostname mappings may be rejected.
twisted.test.test_sslverify
  OpenSSLOptionsECDHIntegrationTests
    test_ellipticCurveDiffieHellman ...                                  [FAIL]

===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/home/exarkun/Work/LeastAuthority/python/twisted/src/twisted/test/test_sslverify.py", line 1678, in assertECDH
    self.assertIn(u"ECDH", cipher)
  File "/home/exarkun/Work/LeastAuthority/python/twisted/src/twisted/trial/_synctest.py", line 492, in assertIn
    % (containee, container))
twisted.trial.unittest.FailTest: 'ECDH' not in 'TLS_AES_256_GCM_SHA384'

twisted.test.test_sslverify.OpenSSLOptionsECDHIntegrationTests.test_ellipticCurveDiffieHellman
-------------------------------------------------------------------------------
Ran 1 tests in 0.096s

FAILED (failures=1)
(twisted) exarkun@baryon:/tmp$ 
```

Conveniently, complete details can be found on buildbot.

<details><summary>Searchable metadata</summary>

```
trac-id__9580 9580
type__enhancement enhancement
reporter__exarkun exarkun
priority__high high
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__None None
time__1548381309639242 1548381309639242
changetime__1550217028077935 1550217028077935
version__None None
owner__markrwilliams markrwilliams

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_2"></a>|@exarkun commented|
|-|-|

[#9582](https://github.com/twisted/twisted/issues/9582) was a duplicate of this.  It did helpfully include a complete (I believe) list of the failing tests:

```
twisted.test.test_ssl.StolenTCPTests.test_properlyCloseFiles
twisted.test.test_sslverify.OpenSSLOptionsECDHIntegrationTests.test_ellipticCurveDiffieHellman
twisted.test.test_sslverify.ExpandCipherStringTests.test_doesNotStumbleOverEmptyList
twisted.test.test_sslverify.OpenSSLOptionsTests.test_givesMeaningfulErrorMessageIfNoCipherMatches
```

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_3"></a>|@markrwilliams commented|
|-|-|

https://github.com/twisted/twisted/pull/1100

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun set owner to @markrwilliams|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_5"></a>|@glyph set status to `closed`|
|-|-|

In changeset acde101e677567028e59c476e056a4561d503656
```
#!CommitTicketReference repository="" revision="acde101e677567028e59c476e056a4561d503656"
Merge pull request #1100 from twisted/9580-cryptography-2.5-openssl-1.1.1-tls-1.3-fixes

Author: markrwilliams

Reviewer: exarkun

Fixes: ticket:9580

Address minor compatibility problems with OpenSSL 1.1.1 which were causing a few tests to fail.
```

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_6"></a>|@glyph commented|
|-|-|

This was a duplicate of [#9566](https://github.com/twisted/twisted/issues/9566), apparently.
