### ISSUE TITLE
Twisted does not have the correct minimum cryptography dependency

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9592]
|[<img alt="ryban's avatar" src="https://avatars.githubusercontent.com/u/1617326?s=50" width="50" height="50">](https://github.com/ryban)| @ryban reported|
|-|-|
|Trac ID|trac#9592|
|Type|release blocker: regression|
|Created|2019-03-02 01:38:32Z|

The fix for [#9584](https://github.com/twisted/twisted/issues/9584) depends on cryptography>=2.5 but the current dependency is >=1.5.

```
Traceback (most recent call last):
  File "env/local/lib/python2.7/site-packages/twisted/conch/ssh/transport.py", line 703, in dataReceived
    self.dispatchMessage(messageNum, packet[1:])
  File "env/local/lib/python2.7/site-packages/twisted/conch/ssh/transport.py", line 721, in dispatchMessage
    f(payload)
  File "env/local/lib/python2.7/site-packages/twisted/conch/ssh/transport.py", line 1603, in ssh_KEXINIT
    serialization.Encoding.X962,
  File "env/local/lib/python2.7/site-packages/enum/__init__.py", line 390, in __getattr__
    raise AttributeError(name)
AttributeError: X962
```

<details><summary>Searchable metadata</summary>

```
trac-id__9592 9592
type__release_blocker__regression release blocker: regression
reporter__ryban ryban
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__None None
time__1551490712145633 1551490712145633
changetime__1554626790106379 1554626790106379
version__None None
owner__hawkowl hawkowl
cc__twm
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_4"></a>|@hawkowl commented|
|-|-|

PR: https://github.com/twisted/twisted/pull/1111

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_5"></a>|@twm set owner to @hawkowl|
|-|-|

Looks good. Merge away! https://github.com/twisted/twisted/pull/1111#pullrequestreview-216434896

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_6"></a>|@hawkowl set status to `closed`|
|-|-|

In changeset 7849ccd3290d2196c0101853ecef23893a520066
```
#!CommitTicketReference repository="" revision="7849ccd3290d2196c0101853ecef23893a520066"
Merge 9592-min-cryptography-bump: Bump Cryptography dependency to 2.5

Author: hawkowl
Reviewer: twm
Fixes: ticket:9592
```

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_7"></a>|@hawkowl commented|
|-|-|

In changeset 2c739f738987546070dd8e3d3f14264603865d58
```
#!CommitTicketReference repository="" revision="2c739f738987546070dd8e3d3f14264603865d58"
Merge 9592-min-cryptography-bump: Bump Cryptography dependency to 2.5

Author: hawkowl
Reviewer: twm
Fixes: ticket:9592
```
