### ISSUE TITLE
Py3's trial can run a completely different file than one given on the command line

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9595]
|[<img alt="Julian's avatar" src="https://avatars.githubusercontent.com/u/329822?s=50" width="50" height="50">](https://github.com/Julian)| @Julian reported|
|-|-|
|Trac ID|trac#9595|
|Type|defect|
|Created|2019-03-11 11:16:54Z|

Given a file that blows up:

```
mkdir -p test && echo 'raise Exception()' >test/test_zlib.py && touch test/__init__.py
```

And a request to run it, on Py2:

```
⊙  trial test/test_zlib.py                                                                                                                                             julian@Air
test/test_zlib
  py ...                                                                [ERROR]

===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/Users/julian/.local/share/virtualenvs/dev/site-packages/twisted/trial/runner.py", line 625, in loadByNames
    things.append(self.findByName(name))
  File "/Users/julian/.local/share/virtualenvs/dev/site-packages/twisted/trial/runner.py", line 428, in findByName
    return filenameToModule(name)
  File "/Users/julian/.local/share/virtualenvs/dev/site-packages/twisted/trial/runner.py", line 119, in filenameToModule
    ret = _importFromFile(fn)
  File "/Users/julian/.local/share/virtualenvs/dev/site-packages/twisted/trial/runner.py", line 142, in _importFromFile
    module = imp.load_source(moduleName, fn, fd)
  File "test/test_zlib.py", line 1, in <module>
    raise Exception()
exceptions.Exception:

test/test_zlib.py
-------------------------------------------------------------------------------
Ran 1 tests in 0.288s

FAILED (errors=1)
```

Whereas on Py3, you'll notice trial go off and run random zlib tests:

```
⊙  trial3 test/test_zlib.py                                                                                                                                            julian@Air
test.test_zlib
  ChecksumBigBufferTestCase
    test_big_buffer ...                                               [SKIPPED]
  ChecksumTestCase
    test_adler32empty ...                                                  [OK]
    test_adler32start ...                                                  [OK]
    test_crc32_adler32_unsigned ...                                        [OK]
    test_crc32empty ...                                                    [OK]
    test_crc32start ...                                                    [OK]
    test_penguins ...                                                      [OK]
    test_same_as_binascii_crc32 ...                                        [OK]
  CompressObjectTestCase
    test_64bit_compress ...                                                [OK]
    test_badcompresscopy ...                                          [SKIPPED]
    test_baddecompresscopy ...                                        [SKIPPED]
    test_big_compress_buffer ...                                           [OK]
    test_big_decompress_buffer ...                                         [OK]
    test_clear_unconsumed_tail ...                                         [OK]
    test_compresscopy ...                                             [SKIPPED]
    test_compressincremental ...                                           [OK]
    test_compressoptions ...                                               [OK]
    test_compresspickle ...                                                [OK]
    test_decompimax ...                                                    [OK]
    test_decompinc ...                                                     [OK]
...
```

What goes wrong is the Py3-specific test loader doing this:

https://github.com/twisted/twisted/blob/c20f01967702c6941ca796cc4837791754944c1c/src/twisted/trial/runner.py#L693-L694

and trying to convert paths to modules, finding one (a different one) that is on the path, and silently deciding to run that instead once it comes time to import it.

The CAVEAT there just below seems to be talking about this exact possibility, but it's not just Twisted, and there are plenty of decent reasons to do this *if* trial is going to continue to support running from file paths (one of which you might guess from the file paths in my example).

<details><summary>Searchable metadata</summary>

```
trac-id__9595 9595
type__defect defect
reporter__Julian Julian
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__duplicate duplicate
component__trial trial
keywords__None None
time__1552303014265890 1552303014265890
changetime__1552303128432152 1552303128432152
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="Julian's avatar" src="https://avatars.githubusercontent.com/u/329822?s=50" width="50" height="50">](https://github.com/Julian)<a name="note_1"></a>|@Julian set status to `closed`|
|-|-|

Thanks trac. See [#9594](https://github.com/twisted/twisted/issues/9594).
