### ISSUE TITLE
reactor.connectTCP("", None, ...) fails with an "Unhandled error in Deferred"

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9600]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#9600|
|Type|defect|
|Created|2019-03-27 20:18:26Z|

```
exarkun@baryon:/tmp$ cat > connectTCP-None.py
from twisted.internet import reactor
from twisted.internet.protocol import ClientFactory

from twisted.python.log import startLogging
from sys import stdout
startLogging(stdout)

f = ClientFactory()                       
reactor.connectTCP("", None, f)
reactor.callLater(1, reactor.stop)
reactor.run()
print("numPorts: {}".format(f.numPorts))
exarkun@baryon:/tmp$ python connectTCP-None.py 
2019-03-27 16:17:49-0400 [-] Log opened.
2019-03-27 16:17:49-0400 [-] Starting factory <twisted.internet.protocol.ClientFactory instance at 0x7fcca57504d0>
2019-03-27 16:17:49-0400 [-] Unhandled error in Deferred:
2019-03-27 16:17:49-0400 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1252, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 878, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 413, in resolveAddress
	    d.addCallbacks(self._setRealAddress, self.failIfNotConnected)
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 310, in addCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 653, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 430, in _setRealAddress
	    self.doConnect()
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 559, in doConnect
	    connectResult = self.socket.connect_ex(self.realAddress)
	  File "/usr/lib/python2.7/socket.py", line 228, in meth
	    return getattr(self._sock,name)(*args)
	exceptions.TypeError: an integer is required
	
2019-03-27 16:17:50-0400 [-] Main loop terminated.
2019-03-27 16:17:50-0400 [-] numPorts: 1
exarkun@baryon:/tmp$ 
```

<details><summary>Searchable metadata</summary>

```
trac-id__9600 9600
type__defect defect
reporter__exarkun exarkun
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__None None
time__1553717906386774 1553717906386774
changetime__1621012095992118 1621012095992118
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_1"></a>|@adiroiban commented|
|-|-|

There is a patch for this as part of the fix for [#7798](https://github.com/twisted/twisted/issues/7798)

https://github.com/twisted/twisted/compare/trunk...ipv6-client-port-overflow-7798-2

I will see if I can revive that or send the fix only for [#9600](https://github.com/twisted/twisted/issues/9600)
