### ISSUE TITLE
test_main.MainTests usually fail on Python 3.7 on macOS

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9606]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)| @twm reported|
|-|-|
|Trac ID|trac#9606|
|Type|defect|
|Created|2019-04-01 05:06:26Z|

These two tests seem to fail more often than not on CircleCI:

```
[FAIL]
Traceback (most recent call last):
  File "/Users/distiller/repo/build/py37-alldeps-withcov-posix/lib/python3.7/site-packages/twisted/test/test_main.py", line 61, in processEnded
    self.assertEqual(output, message)
  File "/Users/distiller/repo/build/py37-alldeps-withcov-posix/lib/python3.7/site-packages/twisted/trial/_synctest.py", line 432, in assertEqual
    super(_Assertions, self).assertEqual(first, second, msg)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
twisted.trial.unittest.FailTest: b'' != b"python3.7 -m twisted.trial [options] [[f[3525 chars]\n\n"

twisted.test.test_main.MainTests.test_trial
===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/Users/distiller/repo/build/py37-alldeps-withcov-posix/lib/python3.7/site-packages/twisted/test/test_main.py", line 40, in processEnded
    self.assertEqual(output, message)
  File "/Users/distiller/repo/build/py37-alldeps-withcov-posix/lib/python3.7/site-packages/twisted/trial/_synctest.py", line 432, in assertEqual
    super(_Assertions, self).assertEqual(first, second, msg)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
twisted.trial.unittest.FailTest: b'' != b'Usage: python3.7 -m twisted [options] plu[1475 chars]\n\n'

twisted.test.test_main.MainTests.test_twisted
```

<details><summary>Searchable metadata</summary>

```
trac-id__9606 9606
type__defect defect
reporter__twm twm
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__duplicate duplicate
component__core core
keywords__None None
time__1554095186901911 1554095186901911
changetime__1554613264251927 1554613264251927
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_1"></a>|@twm commented|
|-|-|

https://circleci.com/gh/twisted/twisted/3251?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_2"></a>|@twm commented|
|-|-|

Again: https://circleci.com/gh/twisted/twisted/3251?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by twisted-trac** [comment]
|[<img alt="wiml's avatar" src="https://avatars.githubusercontent.com/u/156891?s=50" width="50" height="50">](https://github.com/wiml)<a name="note_3"></a>|@wiml commented|
|-|-|

I can reproduce this locally, though it's not obvious what's failing (tox is a little opaque to me). I added a few lines to print out more information from the failure and found that the subprocess writes this to stderr before exiting:

```
/usr/local/opt/python/bin/python3.7: Error while finding module specification for 'twisted.trial' (ModuleNotFoundError: No module named 'twisted')
```

I don't know why `sys.executable` in that process is `/usr/local/Cellar/python/3.7.3/bin/python3.7` (which is one of the many names of the systemwide py3.7 install) — shouldn't it be the path of the Python in the temporary venv that Tox creates? The system python3.7 doesn't have twisted installed.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_4"></a>|@exarkun commented|
|-|-|

Can you verify that that's the path `sys.executable` is actually set to?  Maybe a log statement in the tests would be useful.  Also, it would be useful if the tests reported stderr and the child process exit status when they fail.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_5"></a>|@exarkun commented|
|-|-|

The tests fail to propagate the process environment to the child.  I don't know if this matters but it's probably wrong.

**Comment by twisted-trac** [comment]
|[<img alt="wiml's avatar" src="https://avatars.githubusercontent.com/u/156891?s=50" width="50" height="50">](https://github.com/wiml)<a name="note_6"></a>|@wiml commented|
|-|-|

Replying to [Jean-Paul Calderone](#note_4):
> Can you verify that that's the path `sys.executable` is actually set to?  Maybe a log statement in the tests would be useful.

Yep, I added `print`s to the test methods. `sys.executable` is also logged at the start of the test run, by `dump_all_version_info.py`; in my tests the value was the same there as in the test method itself.

> Also, it would be useful if the tests reported stderr and the child process exit status when they fail.

Definitely :)

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_7"></a>|@glyph set status to `closed`|
|-|-|

I diagnosed it as a bug in tox and filed it there.

Closing this one as the dup because I made a PR before I found this one.

ticket:9615
