### ISSUE TITLE
test_trial and test_twisted from twisted.test.test_main.MainTests fail on macos_py37_default_reactor

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9608]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#9608|
|Type|release blocker: regression|
|Created|2019-04-02 01:09:41Z|

https://circleci.com/gh/twisted/twisted/3303

```
===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/Users/distiller/repo/build/py37-alldeps-withcov-posix/lib/python3.7/site-packages/twisted/test/test_main.py", line 61, in processEnded
    self.assertEqual(output, message)
  File "/Users/distiller/repo/build/py37-alldeps-withcov-posix/lib/python3.7/site-packages/twisted/trial/_synctest.py", line 432, in assertEqual
    super(_Assertions, self).assertEqual(first, second, msg)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
twisted.trial.unittest.FailTest: b'' != b"python3.7 -m twisted.trial [options] [[f[3525 chars]\n\n"

twisted.test.test_main.MainTests.test_trial
===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/Users/distiller/repo/build/py37-alldeps-withcov-posix/lib/python3.7/site-packages/twisted/test/test_main.py", line 40, in processEnded
    self.assertEqual(output, message)
  File "/Users/distiller/repo/build/py37-alldeps-withcov-posix/lib/python3.7/site-packages/twisted/trial/_synctest.py", line 432, in assertEqual
    super(_Assertions, self).assertEqual(first, second, msg)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
twisted.trial.unittest.FailTest: b'' != b'Usage: python3.7 -m twisted [options] plu[1475 chars]\n\n'

twisted.test.test_main.MainTests.test_twisted
```

<details><summary>Searchable metadata</summary>

```
trac-id__9608 9608
type__release_blocker__regression release blocker: regression
reporter__exarkun exarkun
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__duplicate duplicate
component__core core
keywords__None None
time__1554167381606460 1554167381606460
changetime__1554168747526886 1554168747526886
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_1"></a>|@hawkowl set status to `closed`|
|-|-|

Duplicate of https://tm.tl/[#9606](https://github.com/twisted/twisted/issues/9606)
