### ISSUE TITLE
Hyperlink 19.0.0 breaks Twisted test suite

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9619]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)| @twm reported|
|-|-|
|Trac ID|trac#9619|
|Type|release blocker: regression|
|Created|2019-04-09 05:33:34Z|
|Branch|https://github.com/twisted/twisted/tree/9619-test-hyperlink-less|

All the buildbots are failing like so:

```
Traceback (most recent call last):
  File "c:\buildslave\windows7-64-py2_7-coverage\twisted\build\py27-alldeps-withcov-windows\lib\site-packages\twisted\python\test\test_url.py", line 486, in test_parseEqualSignInParamValue
    self.assertEqual(u.asText(), 'http://localhost/?=x%3Dx%3Dx')
  File "c:\buildslave\windows7-64-py2_7-coverage\twisted\build\py27-alldeps-withcov-windows\lib\site-packages\twisted\trial\_synctest.py", line 432, in assertEqual
    super(_Assertions, self).assertEqual(first, second, msg)
  File "c:\python27\Lib\unittest\case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "c:\python27\Lib\unittest\case.py", line 924, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
twisted.trial.unittest.FailTest: u'http://localhost/?=x=x=x' != u'http://localhost/?=x%3Dx%3Dx'
- http://localhost/?=x=x=x
?                     ^ ^
+ http://localhost/?=x%3Dx%3Dx
?                     ^^^ ^^^
```

Hyperlink 19.0.0 was just released... it changes the handling of this specific URL:

```
$ hyper18/bin/python url.py
http://localhost?=x=x=x -> http://localhost/?=x%3Dx%3Dx
$ hyper19/bin/python url.py
http://localhost?=x=x=x -> http://localhost/?=x=x=x
$ cat url.py
from hyperlink import URL

text = u'http://localhost?=x=x=x'
print(u'{} -> {}'.format(text, URL.fromText(text).asText()))  
```

<details><summary>Searchable metadata</summary>

```
trac-id__9619 9619
type__release_blocker__regression release blocker: regression
reporter__twm twm
priority__highest highest
milestone__None None
branch__9619_test_hyperlink_less 9619-test-hyperlink-less
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__None None
time__1554788014936841 1554788014936841
changetime__1554795977276523 1554795977276523
version__None None
owner__glyph glyph

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_1"></a>|@twm commented|
|-|-|

Apparently this breakage was anticipated: https://github.com/python-hyper/hyperlink/pull/39

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_2"></a>|@twm commented|
|-|-|

PR here: https://github.com/twisted/twisted/pull/1125

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_3"></a>|@glyph set owner to @glyph|
|-|-|

Looks correct. Will merge when CI is happy.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_4"></a>|@glyph set status to `closed`|
|-|-|

In changeset 5facfd753b9d3e7a26d9a59acf43ded05084ccdc
```
#!CommitTicketReference repository="" revision="5facfd753b9d3e7a26d9a59acf43ded05084ccdc"
Merge pull request #1125 from twisted/9619-test-hyperlink-less

Author: twm

Reviewer: glyph

Fixes: ticket:9619

Make tests pass again by deleting an old twisted.python.url test; this is now hyperlink's job.
```
