### ISSUE TITLE
Unhandled error in TLS shutdown

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9629]
|[<img alt="jsantos2's avatar" src="https://avatars.githubusercontent.com/u/28877519?s=50" width="50" height="50">](https://github.com/jsantos2)| @jsantos2 reported|
|-|-|
|Trac ID|trac#9629|
|Type|defect|
|Created|2019-04-22 21:12:11Z|

My program does acts as a web server for HTTPS.  I'm seeing new errors in the process stderr log with version 19.2.0.  I think this is happening when the connection times out.  It appears my server happily continues processing, so the error is invisible to users.

This is what appears in stderr:
--------------------------------------------------
Unhandled Error
Traceback (most recent call last):
  File "/home/medusa/run/medusa_viewer.py", line 2501, in <module>
    reactor.run()
  File "/usr/Python3/lib/python3.6/site-packages/Twisted-19.2.0-py3.6-linux-x86_64.egg/twisted/internet/base.py", line 1272, in run
    self.mainLoop()
  File "/usr/Python3/lib/python3.6/site-packages/Twisted-19.2.0-py3.6-linux-x86_64.egg/twisted/internet/base.py", line 1281, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/Python3/lib/python3.6/site-packages/Twisted-19.2.0-py3.6-linux-x86_64.egg/twisted/internet/base.py", line 902, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/usr/Python3/lib/python3.6/site-packages/Twisted-19.2.0-py3.6-linux-x86_64.egg/twisted/web/http.py", line 2339, in forceAbortClient
    self.transport.abortConnection()
  File "/usr/Python3/lib/python3.6/site-packages/Twisted-19.2.0-py3.6-linux-x86_64.egg/twisted/protocols/tls.py", line 435, in abortConnection
    self._shutdownTLS()
  File "/usr/Python3/lib/python3.6/site-packages/Twisted-19.2.0-py3.6-linux-x86_64.egg/twisted/protocols/tls.py", line 338, in _shutdownTLS
    shutdownSuccess = self._tlsConnection.shutdown()
builtins.AttributeError: 'NoneType' object has no attribute 'shutdown'

------------------------------
The app sets a timeout of 110 minutes with 
   ctx.set_timeout(60*110) # 110 minutes
when it is setting up the connection.  I suspect (but haven't yet verified) that the error is occurring when the connection times out.

There doesn't appear to be a shutdown() method defined in tls.py, but there is a shutdownTLS() method so I suspect it might be a simple typo.

If the source of this problem isn't obvious (tls.py is identical to the 18.9.0 version, but I wasn't seeing this error with 18.9.0), I will attempt to make a reproducer.  (The program which exhibits this behavior is an enormous pile of spaghetti and the guy who wrote it retired last year, so it might take me a while to understand it!)  

---------------
This problem is non-urgent for us because it just results in noise in a log file, but I suppose it could be more serious for other users, if it is in fact a bug in Twisted.

<details><summary>Searchable metadata</summary>

```
trac-id__9629 9629
type__defect defect
reporter__jsantos2 jsantos2
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__tls__shutdown tls, shutdown
time__1555967531805336 1555967531805336
changetime__1556690252049643 1556690252049643
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_1"></a>|@glyph commented|
|-|-|

This was a duplicate of [#9462](https://github.com/twisted/twisted/issues/9462).
