### ISSUE TITLE
twisted-19.2.0: fails to import glib2reactor/gtk2reactor: No module named 'gobject'

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9642]
|[<img alt="eclipseo's avatar" src="https://avatars.githubusercontent.com/u/30413512?s=50" width="50" height="50">](https://github.com/eclipseo)| @eclipseo reported|
|-|-|
|Trac ID|trac#9642|
|Type|defect|
|Created|2019-05-22 16:03:46Z|

Trying to import glib2reactor in python3 fails with the following error:

> $ /usr/bin/python3 ./test.py 
> Traceback (most recent call last):
>   File "./test.py", line 3, in <module>
>     from twisted.internet import glib2reactor
>   File "/usr/lib64/python3.7/site-packages/twisted/internet/glib2reactor.py", line 19, in <module>
>     from twisted.internet import gtk2reactor
>   File "/usr/lib64/python3.7/site-packages/twisted/internet/gtk2reactor.py", line 45, in <module>
>     import gobject
> ModuleNotFoundError: No module named 'gobject'

Try with the attached test.py, which should just print on the console "Bye", instead of error. 

Downstream bug report: https://bugzilla.redhat.com/show_bug.cgi?id=1712748

Attachments:

* [test.py](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/910/910d859482f953751c8350fe5fd7e33e9ba254ac/a36e355ddb203d7d4133221f339dc406cb9f480f.py) (131 bytes) - added by eclipseo on 2019-05-22 16:04:14Z - 

<details><summary>Searchable metadata</summary>

```
trac-id__9642 9642
type__defect defect
reporter__eclipseo eclipseo
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__invalid invalid
component__core core
keywords__None None
time__1558541026535368 1558541026535368
changetime__1558548833505751 1558548833505751
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="eclipseo's avatar" src="https://avatars.githubusercontent.com/u/30413512?s=50" width="50" height="50">](https://github.com/eclipseo)<a name="note_1"></a>|@eclipseo commented|
|-|-|

https://github.com/twisted/twisted/pull/1145

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_2"></a>|@glyph set status to `closed`|
|-|-|

I think you want `gireactor`.  `gtk2reactor` is for gtk _2_, which wasn't supported by gobject introspection.

Possibly this module should be removed entirely, however! It's not clear to me any current linux distros include the relevant old pygtk modules any more.
