### ISSUE TITLE
Multi-line headers fail with a TypeError on Python 3

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9644]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)| @markrwilliams reported|
|-|-|
|Trac ID|trac#9644|
|Type|defect|
|Created|2019-05-28 02:21:20Z|
|Branch|https://github.com/twisted/twisted/tree/9644-multiline-headers|

The following program prints out the response status for a request with a multiline header (```X-multiline```) sent to a Twisted web server that prints out the headers it receives.

```python
from twisted.internet import endpoints, defer, task, protocol
from twisted.web import client, server, resource, http_headers
from twisted.web._newclient import HTTPClientParser


class HelloWeb(resource.Resource):
    isLeaf = True
    def render_GET(self, request):
        print(request.requestHeaders)
        return b"Hello, client."


HOST = b"127.0.0.1"


def printResponse(response):
    print("{} {}".format(response.code, response.phrase))


class MultilineHeader(protocol.Protocol):

    def connectionMade(self):
        self.transport.writeSequence([
            b"GET / HTTP/1.1\r\n",
            b"Host: %s\r\n" % (HOST,),
            b"X-multiline: a\r\n",
            b"    b\r\n",
            b"\r\n",
        ])
        request = client.Request(
            b"GET",
            b"http://localhost:%d/" % (self.factory.port),
            http_headers.Headers(),
            None,
        )
        self.responseParser = HTTPClientParser(request, lambda x: None)
        self.responseParser._responseDeferred.addCallback(printResponse)
        self.responseParser._responseDeferred.addBoth(
            lambda _: self.transport.loseConnection())
        self.responseParser._responseDeferred.chainDeferred(self.factory.finished)

        self.responseParser.makeConnection(self.transport)

    def dataReceived(self, data):
        self.responseParser.dataReceived(data)


@defer.inlineCallbacks
def run(reactor):
    site = server.Site(HelloWeb())
    port = yield endpoints.TCP4ServerEndpoint(
        reactor,
        port=0,
        interface=HOST,
    ).listen(site)
    localPort = port.getHost().port

    factory = protocol.Factory.forProtocol(MultilineHeader)
    factory.port = localPort
    factory.finished = defer.Deferred()
    endpoints.TCP4ClientEndpoint(
        reactor,
        host=HOST,
        port=localPort,
    ).connect(factory)

    yield factory.finished


task.react(run)
```

On Python 2, the value folding for ```X-multiline``` works:

```
(tmp-fb17e365883658c) mrw@hammal:~/.virtualenvs/tmp-fb17e365883658c$ python /tmp/example.py
Headers({'host': ['127.0.0.1'], 'x-multiline': ['a     b']})
200 OK
```

On Python 3, the server fails with a ```TypeError```

```
(tmp-5f721fb35c2361e) mrw@hammal:~/.virtualenvs/tmp-5f721fb35c2361e$ python /tmp/example.py
Unhandled Error
Traceback (most recent call last):
  File "/home/mrw/.virtualenvs/tmp-5f721fb35c2361e/lib/python3.7/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/mrw/.virtualenvs/tmp-5f721fb35c2361e/lib/python3.7/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/mrw/.virtualenvs/tmp-5f721fb35c2361e/lib/python3.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/mrw/.virtualenvs/tmp-5f721fb35c2361e/lib/python3.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/home/mrw/.virtualenvs/tmp-5f721fb35c2361e/lib/python3.7/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
  File "/home/mrw/.virtualenvs/tmp-5f721fb35c2361e/lib/python3.7/site-packages/twisted/internet/tcp.py", line 243, in doRead
    return self._dataReceived(data)
  File "/home/mrw/.virtualenvs/tmp-5f721fb35c2361e/lib/python3.7/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/home/mrw/.virtualenvs/tmp-5f721fb35c2361e/lib/python3.7/site-packages/twisted/web/http.py", line 2924, in dataReceived
    return self._channel.dataReceived(data)
  File "/home/mrw/.virtualenvs/tmp-5f721fb35c2361e/lib/python3.7/site-packages/twisted/web/http.py", line 2217, in dataReceived
    return basic.LineReceiver.dataReceived(self, data)
  File "/home/mrw/.virtualenvs/tmp-5f721fb35c2361e/lib/python3.7/site-packages/twisted/protocols/basic.py", line 572, in dataReceived
    why = self.lineReceived(line)
  File "/home/mrw/.virtualenvs/tmp-5f721fb35c2361e/lib/python3.7/site-packages/twisted/web/http.py", line 2110, in lineReceived
    self.__header = self.__header + '\n' + line
```

<details><summary>Searchable metadata</summary>

```
trac-id__9644 9644
type__defect defect
reporter__markrwilliams markrwilliams
priority__normal normal
milestone__None None
branch__9644_multiline_headers 9644-multiline-headers
branch_author__ 
status__closed closed
resolution__fixed fixed
component__web web
keywords__None None
time__1559010080215675 1559010080215675
changetime__1560399990862207 1560399990862207
version__None None
owner__twm twm

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)|@twm set owner to @twm<br>@twm set status to `assigned`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_2"></a>|@twm removed owner<br>@twm set status to `new`|
|-|-|

PR here: https://github.com/twisted/twisted/pull/1150

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_3"></a>|@glyph set owner to @twm|
|-|-|

Reviewed & approved on github.

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_4"></a>|@twm set status to `closed`|
|-|-|

In changeset fd73587f3d7c89211c8d3624f1c69c34add38024
```
#!CommitTicketReference repository="" revision="fd73587f3d7c89211c8d3624f1c69c34add38024"
Merge pull request #1150 from twisted/9644-multiline-headers

Author: twm
Reviewer: glyph
Fixes: ticket:9644

Don't TypeError on multiline headers
```
