### ISSUE TITLE
gireactor pygtkcompat hard requirement breaks twisted

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9669]
|[<img alt="cas--'s avatar" src="https://avatars.githubusercontent.com/u/606038?s=50" width="50" height="50">](https://github.com/cas--)| @cas-- reported|
|-|-|
|Trac ID|trac#9669|
|Type|defect|
|Created|2019-07-04 10:02:08Z|

I have had an OpenSuse user report they cannot start Deluge (GTK3 app) because twisted is failing with this error message:

```
Traceback (most recent call last):
File "/usr/bin/deluge-gtk", line 11, in <module>
load_entry_point('deluge==2.0.3', 'gui_scripts', 'deluge-gtk')()
File "/usr/lib/python3.6/site-packages/deluge/ui/gtk3/__init__.py", line 63, in start
Gtk().start()
File "/usr/lib/python3.6/site-packages/deluge/ui/gtk3/__init__.py", line 43, in start
from .gtkui import GtkUI
File "/usr/lib/python3.6/site-packages/deluge/ui/gtk3/gtkui.py", line 27, in <module>
from twisted.internet import defer, gtk3reactor
File "/usr/lib64/python3.6/site-packages/twisted/internet/gtk3reactor.py", line 26, in <module>
from twisted.internet import gireactor
File "/usr/lib64/python3.6/site-packages/twisted/internet/gireactor.py", line 78, in <module>
import gi.pygtkcompat
ModuleNotFoundError: No module named 'gi.pygtkcompat'
```

I traced the issue to the `python-gobject` package removing `pygtkcompat` from the package, see line 121 in this spec file:

https://build.opensuse.org/package/view_file/openSUSE:Factory/python-gobject/python-gobject.spec?expand=1

Although it is short-sighted for package maintainers to drop the module, Twisted should only optionally require `pygtkcompat` as the pygobject documentation mentions not to rely on it.

Related to [#6280](https://github.com/twisted/twisted/issues/6280)

<details><summary>Searchable metadata</summary>

```
trac-id__9669 9669
type__defect defect
reporter__cas__ cas--
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__gireactor gireactor
time__1562234528344477 1562234528344477
changetime__1562234528344477 1562234528344477
version__None None
owner__None None

```
</details>

**Comment by WhyNotHugo** [comment]
This is somewhat of a separate issue: the `pygtkcompat` module has been dropped entirely, so it is no longer available in recent versions of `py3-gobject3`.

I'm seeing this error when starting `deluge`:

```con
> deluge
Traceback (most recent call last):
  File "/usr/bin/deluge", line 8, in <module>
    sys.exit(start_ui())
             ^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/deluge/ui/ui_entry.py", line 140, in start_ui
    ui.start()
  File "/usr/lib/python3.12/site-packages/deluge/ui/gtk3/__init__.py", line 45, in start
    from .gtkui import GtkUI
  File "/usr/lib/python3.12/site-packages/deluge/ui/gtk3/gtkui.py", line 24, in <module>
    from twisted.internet import defer, gtk3reactor
  File "/usr/lib/python3.12/site-packages/twisted/internet/gtk3reactor.py", line 22, in <module>
    from twisted.internet import gireactor
  File "/usr/lib/python3.12/site-packages/twisted/internet/gireactor.py", line 37, in <module>
    gi.pygtkcompat.enable()
  File "/usr/lib/python3.12/site-packages/pygtkcompat/pygtkcompat.py", line 30, in enable
    raise RuntimeError("pygtkcompat is deprecated in 3.48 and has been removed in 3.51, see https://pygobject.gnome.org/guide/porting.html for migration instructions")
RuntimeError: pygtkcompat is deprecated in 3.48 and has been removed in 3.51, see https://pygobject.gnome.org/guide/porting.html for migration instructions
```

**Comment by WhyNotHugo** [comment]
Looks like this was fixed in 6ee11484838c18cb8ea5efd1b2c01bee5fd58ea1 anyway.

**Comment by adiroiban** [comment]
Thanks @WhyNotHugo for the followup.

The code for 6ee1148 is already present in the latest resease of Twisted.

I guess that you are using an older version of Twisted

The latest code is here


https://github.com/twisted/twisted/blob/trunk/src/twisted/internet/gireactor.py


I am closing this as already fixed by #11705 .

I am happy to reopen it if this is still an issue

**Comment by WhyNotHugo** [comment]
Upgrading to latest stable release fixes the issue on my end, thanks.

**Comment by glyph** [comment]
> Upgrading to latest stable release fixes the issue on my end, thanks.

Always the best outcome for an interaction on a bug report :). Thank you for validating this!
