### ISSUE TITLE
DNS Client getbyhostname failed for domain hosted by Cloudflare OR if Cloudflare DNS is used

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9691]
|[<img alt="aryasenna's avatar" src="https://avatars.githubusercontent.com/u/5351348?s=50" width="50" height="50">](https://github.com/aryasenna)| @aryasenna reported|
|-|-|
|Trac ID|trac#9691|
|Type|defect|
|Created|2019-08-05 08:02:22Z|

I noticed that if you try to query a domain name which DNS is hosted by cloudflare, twisted.names will throw DNSLookupError exceptions.

Let us use the default sample script found here:
https://twistedmatrix.com/documents/current/_downloads/gethostbyname.py

```
$ python3 gethostbyname.py thesfmarathon.con

main function encountered error
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/udp.py", line 249, in doRead
    self.protocol.datagramReceived(data, addr)
  File "/usr/local/lib/python3.5/dist-packages/twisted/names/dns.py", line 3056, in datagramReceived
    d.callback(m)
  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/defer.py", line 460, in callback
    self._startRunCallbacks(result)
  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "gethostbyname.py", line 53, in printError
    failure.trap(error.DNSNameError)
  File "/usr/local/lib/python3.5/dist-packages/twisted/python/failure.py", line 460, in trap
    self.raiseException()
  File "/usr/local/lib/python3.5/dist-packages/twisted/python/failure.py", line 488, in raiseException
    raise self.value.with_traceback(self.tb)
  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/twisted/names/common.py", line 189, in _cbRecords
    raise error.DNSLookupError(name)
twisted.internet.error.DNSLookupError: DNS lookup failed: thesfmarathon.com.
```

You can try some other Cloudflare DNS-hosted websites which can be found here: https://blog.cloudflare.com/the-many-sites-of-cloudflare/

Note that, the name resolution by the host system is normal:

```
$ nslookup thesfmarathon.com
Server:         8.8.8.8
Address:        8.8.8.8#53

Non-authoritative answer:
Name:   thesfmarathon.com
Address: 104.27.168.155
Name:   thesfmarathon.com
Address: 104.27.169.155
```

Additionally, if you set your host system to use Cloudflare DNS (1.1.1.1), twisted.names won't work for all domain and throws DNSNotImplemented exception.

e.g in Linux set /etc/resolv.conf

```
$ cat /etc/resolv.conf
nameserver 1.1.1.1
nameserver 1.0.0.1
nameserver 2606:4700:4700::1111
nameserver 2606:4700:4700::1001
```

then execute Twisted.names.gethostbyname

```
$ python3 gethostbyname.py google.com
main function encountered error
Traceback (most recent call last):
Failure: twisted.names.error.DNSNotImplementedError: <Message id=11027 rCode=4 maxSize=0 flags=answer,recDes,recAv queries=[Query('google.com', 255, 1)]>
```

Naturally, nslookup is working as usual:

```
$ nslookup google.com
Server:         1.1.1.1
Address:        1.1.1.1#53

Non-authoritative answer:
Name:   google.com
Address: 172.217.23.206
Name:   google.com
Address: 2a00:1450:4014:80d::200e
```

<details><summary>Searchable metadata</summary>

```
trac-id__9691 9691
type__defect defect
reporter__aryasenna aryasenna
priority__normal normal
milestone__None None
branch__None None
branch_author__ 
status__closed closed
resolution__duplicate duplicate
component__names names
keywords__None None
time__1564992142746569 1564992142746569
changetime__1611948185505734 1611948185505734
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="aryasenna's avatar" src="https://avatars.githubusercontent.com/u/5351348?s=50" width="50" height="50">](https://github.com/aryasenna)<a name="note_1"></a>|@aryasenna commented|
|-|-|

Could this be related to deprecation of answering ANY query on Cloudflare end?
https://blog.cloudflare.com/what-happened-next-the-deprecation-of-any/

**Comment by twisted-trac** [comment]
|[<img alt="evilham's avatar" src="https://avatars.githubusercontent.com/u/4446607?s=50" width="50" height="50">](https://github.com/evilham)<a name="note_3"></a>|@evilham commented|
|-|-|

Indeed getHostByName uses ANY, which in twisted is implemented in `twisted.names.common.lookupAllRecords` [1]

Which, after RFC8482 [2] is a misnomer.

From empirical observation, domains using CloudFlare's DNS have ANY queries return:
- if domain does not use DNSSEC, `HINFO	"RFC8482" ""` (4.2 in RFC8482)
- if domain uses DNSSEC, `DS + RRSIG` (4.1 in RFC8482, "subset" being: no records, just those required by DNSSEC)

Any other DNS servers can use a mix of those and 4.3 which isn't an issue.


Basically, using ANY and having getHostByName work reliably doesn't seem possible without manually trying AAAA and A records if ANY fails (I don't think we have a need to check A6 records [3]).

But that raises questions, questions that also applied to current getHostByName implementation, which always returns IPv4 addresses.

Nowadays it's not entirely obvious that a host will have a specific IP version connectivity, aka there are: dual stack hosts, legacy IPv4-only hosts and IPv6-only hosts. So, how do we decide 
which particular host is returned? Right now it looks like the priority is A6 (this is probably a bug), AAAA, A.

I'd be tempted to say: let's deprecate getHostByName and add instead getHostsByName which:

1. Starts simultaneously lookupAddress and lookupIPV6Address raising timeout if it happens
2. Joins those addresses
3. Raises DNSLookupError if the result is empty

That way, the decision as to "which address should be returned?" is left to the users and those who don't care can basically just use [0].


[1]: https://github.com/twisted/twisted/blob/db889fb993c9d6e31463cc7dda90409a2a355acb/src/twisted/names/common.py#L173
[2]: https://tools.ietf.org/html/rfc8482
[3]: https://tools.ietf.org/html/rfc6563

**Comment by twisted-trac** [comment]
|[<img alt="evilham's avatar" src="https://avatars.githubusercontent.com/u/4446607?s=50" width="50" height="50">](https://github.com/evilham)<a name="note_4"></a>|@evilham commented|
|-|-|

(hit twice '-.-)

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_5"></a>|@glyph commented|
|-|-|

Note that we already have an interface for doing the equivalent of `getaddrinfo`, https://twistedmatrix.com/documents/19.2.1/api/twisted.internet.interfaces.IHostnameResolver.html#resolveHostName which is what newer code should use when it needs a more nuanced reply.  So there's no need to introduce a `getHostsByName`.

`getHostByName` should just be reimplemented to issue a couple of parallel queries without using `ANY`, and just do `AAAA`, `A`.  We can do this compatibly, especially given that there's a relevant specification, so Gross Violation Of Specifications applies, even if the specs have moved on since it was originally implemented.

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_6"></a>|@twm commented|
|-|-|

> But that raises questions, questions that also applied to current getHostByName implementation, which always returns IPv4 addresses. 

Theoretically `getHostByName` can return IPv6 addresses. [https://twistedmatrix.com/documents/current/api/twisted.internet.interfaces.IResolverSimple.html `IResolverSimple`] discusses this:

> The callback of the Deferred that is returned will be passed a string that represents the IP address of the specified name, or the errback will be called if the lookup times out. If multiple types of address records are associated with the name, A6 records will be returned in preference to AAAA records, which will be returned in preference to A records. If there are multiple records of the type to be returned, one will be selected at random. 

And it is implemented here: https://github.com/twisted/twisted/blob/eecde4e931d77e035f2ceb8c669a563765afcc1a/src/twisted/names/common.py#L177-L226

This behavior is weird, though. Does anyone use A6 records? And why would they be preferred to AAAA?

But also, [twisted.names.hosts.Resolver](https://github.com/twisted/twisted/blob/eecde4e931d77e035f2ceb8c669a563765afcc1a/src/twisted/names/hosts.py#L146-L149) deliberately avoids returning the AAAA records that `getHostByName` can handle:

```
    # Someday this should include IPv6 addresses too, but that will cause
    # problems if users of the API (mainly via getHostByName) aren't updated to
    # know about IPv6 first.
    lookupAllRecords = lookupAddress
```

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_7"></a>|@exarkun set status to `closed`|
|-|-|

[#10062](https://github.com/twisted/twisted/issues/10062) was a duplicate of this.  There is a PR associated with that ticket already, though, so I'm closing this one as the duplicate.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_8"></a>|@glyph commented|
|-|-|

Replying to [Jean-Paul Calderone](#note_7):
> [#10062](https://github.com/twisted/twisted/issues/10062) was a duplicate of this.  There is a PR associated with that ticket already, though, so I'm closing this one as the duplicate.

❤️ thank you for the tracker gardening
