### ISSUE TITLE
Unable to import t.i.serialport after installing twisted[serial] on Windows

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9700]
|[<img alt="altendky's avatar" src="https://avatars.githubusercontent.com/u/543719?s=50" width="50" height="50">](https://github.com/altendky)| @altendky reported|
|-|-|
|Trac ID|trac#9700|
|Type|defect|
|Created|2019-08-17 02:19:07Z|
|Branch|https://github.com/altendky/twisted/tree/patch-1|

On Windows, ```twisted.internet.serialport``` imports ```win32file``` from ```pywin32``` but the ```serial``` extra doesn't depend on ```pywin32```.  The only way to get ```pywin32``` via ```twisted``` is the ```windows_platform``` extra but that brings ```all_non_platform``` with it.  The ```serial``` extra should additionally depend on ```pywin32; platform_system == "Windows"```.

PR: https://github.com/twisted/twisted/pull/1182

```
PS C:\epc> mkdir twisted_serial_pywin32


    Directory: C:\epc


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        8/16/2019   7:05 PM                twisted_serial_pywin32
```

```
PS C:\epc> cd .\twisted_serial_pywin32\
```

```
PS C:\epc\twisted_serial_pywin32> py -3.7-64 -m venv venv
```

```
PS C:\epc\twisted_serial_pywin32> venv/scripts/pip install twisted[serial]
Collecting twisted[serial]
  Using cached https://files.pythonhosted.org/packages/ee/d9/5b79fef4a7d7dc4d526151904eae5dd207f80433ae646a258b32abbe77d4/Twisted-19.7.0-cp37-cp37m-win_amd64.whl
Collecting constantly>=15.1 (from twisted[serial])
  Using cached https://files.pythonhosted.org/packages/b9/65/48c1909d0c0aeae6c10213340ce682db01b48ea900a7d9fce7a7910ff318/constantly-15.1.0-py2.py3-none-any.whl
Collecting zope.interface>=4.4.2 (from twisted[serial])
  Using cached https://files.pythonhosted.org/packages/a8/d2/e2fb1052cdf1c1d05a23c5f7a192a8dc104d5afda0539f86b9839264e1cc/zope.interface-4.6.0-cp37-cp37m-win_amd64.whl
Collecting Automat>=0.3.0 (from twisted[serial])
  Using cached https://files.pythonhosted.org/packages/a3/86/14c16bb98a5a3542ed8fed5d74fb064a902de3bdd98d6584b34553353c45/Automat-0.7.0-py2.py3-none-any.whl
Collecting incremental>=16.10.1 (from twisted[serial])
  Using cached https://files.pythonhosted.org/packages/f5/1d/c98a587dc06e107115cf4a58b49de20b19222c83d75335a192052af4c4b7/incremental-17.5.0-py2.py3-none-any.whl
Collecting PyHamcrest>=1.9.0 (from twisted[serial])
  Using cached https://files.pythonhosted.org/packages/9a/d5/d37fd731b7d0e91afcc84577edeccf4638b4f9b82f5ffe2f8b62e2ddc609/PyHamcrest-1.9.0-py2.py3-none-any.whl
Collecting hyperlink>=17.1.1 (from twisted[serial])
  Using cached https://files.pythonhosted.org/packages/7f/91/e916ca10a2de1cb7101a9b24da546fb90ee14629e23160086cf3361c4fb8/hyperlink-19.0.0-py2.py3-none-any.whl
Collecting attrs>=17.4.0 (from twisted[serial])
  Using cached https://files.pythonhosted.org/packages/23/96/d828354fa2dbdf216eaa7b7de0db692f12c234f7ef888cc14980ef40d1d2/attrs-19.1.0-py2.py3-none-any.whl
Collecting pyserial>=3.0; extra == "serial" (from twisted[serial])
  Using cached https://files.pythonhosted.org/packages/0d/e4/2a744dd9e3be04a0c0907414e2a01a7c88bb3915cbe3c8cc06e209f59c30/pyserial-3.4-py2.py3-none-any.whl
Requirement already satisfied: setuptools in c:\epc\twisted_serial_pywin32\venv\lib\site-packages (from zope.interface>=4.4.2->twisted[serial]) (40.8.0)
Collecting six (from Automat>=0.3.0->twisted[serial])
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting idna>=2.5 (from hyperlink>=17.1.1->twisted[serial])
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Installing collected packages: constantly, zope.interface, attrs, six, Automat, incremental, PyHamcrest, idna, hyperlink, pyserial, twisted
Successfully installed Automat-0.7.0 PyHamcrest-1.9.0 attrs-19.1.0 constantly-15.1.0 hyperlink-19.0.0 idna-2.8 incremental-17.5.0 pyserial-3.4 six-1.12.0 twisted-19.7.0 zope.interface-
4.6.0
You are using pip version 19.0.3, however version 19.2.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```

```
PS C:\epc\twisted_serial_pywin32> venv/scripts/python -c "import twisted.internet.serialport"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\epc\twisted_serial_pywin32\venv\lib\site-packages\twisted\internet\serialport.py", line 87, in <module>
    from twisted.internet._win32serialport import SerialPort
  File "C:\epc\twisted_serial_pywin32\venv\lib\site-packages\twisted\internet\_win32serialport.py", line 19, in <module>
    import win32file, win32event
ModuleNotFoundError: No module named 'win32file'
```

```
PS C:\epc\twisted_serial_pywin32> venv/scripts/pip install pywin32
Collecting pywin32
  Using cached https://files.pythonhosted.org/packages/a3/8a/eada1e7990202cd27e58eca2a278c344fef190759bbdc8f8f0eb6abeca9c/pywin32-224-cp37-cp37m-win_amd64.whl
Installing collected packages: pywin32
Successfully installed pywin32-224
You are using pip version 19.0.3, however version 19.2.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```

```
PS C:\epc\twisted_serial_pywin32> venv/scripts/python -c "import twisted.internet.serialport"
```

<details><summary>Searchable metadata</summary>

```
trac-id__9700 9700
type__defect defect
reporter__altendky altendky
priority__normal normal
milestone__None None
branch__altendky_patch_1 altendky:patch-1
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__None None
time__1566008347428232 1566008347428232
changetime__1567147272489082 1567147272489082
version__None None
owner__glyph glyph

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_2"></a>|@glyph commented|
|-|-|

Thanks for spotting this; looking forward to the PR.

**Comment by twisted-trac** [comment]
|[<img alt="altendky's avatar" src="https://avatars.githubusercontent.com/u/543719?s=50" width="50" height="50">](https://github.com/altendky)<a name="note_4"></a>|@altendky commented|
|-|-|

Ongoing review available in PR: https://github.com/twisted/twisted/pull/1182

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_5"></a>|@glyph set owner to @glyph|
|-|-|

review'd

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_6"></a>|@glyph set status to `closed`|
|-|-|

In changeset a2bff7d007bbeb4a448ae220d9e2e6453a40dfc8
```
#!CommitTicketReference repository="" revision="a2bff7d007bbeb4a448ae220d9e2e6453a40dfc8"
Merge pull request #1182 from altendky/patch-1

Author: altendky

Reviewer: exarkun, glyph

Fixes: ticket:9700

The serial extra now requires pywin32 on Windows enabling use of twisted.internet.serialport without specifying the windows_platform extra.
```
