### ISSUE TITLE
traceback from conch command line on writing known_hosts entries

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9702]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)| @glyph reported|
|-|-|
|Trac ID|trac#9702|
|Type|defect|
|Created|2019-08-22 06:37:09Z|

Quick repro instructions:

```
$ echo 'twistedmatrix.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAsV0VMRbGmzhqxxayLRHmvnFvtyNqgbNKV46dU1bVFB+3ytNvue4Riqv/SVkPRNwMb7eWH29SviXaBxUhYyzKkDoNUq3rTNnH1Vnif6d6X4JCrUb5d3W+DmYClyJrZ5HgD/hUpdSkTRqdbQ2TrvSAxRacj+vHHT4F4dm1bJSewm3B2D8HVOoi/CbVh3dsIiCdp8VltdZx4qYVfYe2LwVINCbAa3d3tj9ma7RVfw3OH2Mfb+toLd1N5tBQFb7oqTt2nC6I/6Bd4JwPUld+IEitw/suElq/AIJVQXXujeyiZlea90HE65U2mF1ytr17HTAIT2ySokJWyuBANGACk6iIaw==' > kh_test
$ conch --known-hosts=kh_test twistedmatrix.com
```

Expected result:

flawless connection

Actual result:

```
Unhandled Error
Traceback (most recent call last):
  File ".../site-packages/twisted/internet/defer.py", line 322, in addCallback
    callbackKeywords=kw)
  File ".../site-packages/twisted/internet/defer.py", line 311, in addCallbacks
    self._runCallbacks()
  File ".../site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File ".../site-packages/twisted/conch/client/knownhosts.py", line 476, in gotHasKey
    (key.type(), nativeString(ip)))
--- <exception caught here> ---
  File ".../site-packages/twisted/conch/client/knownhosts.py", line 628, in warn
    f.write(text)
builtins.TypeError: a bytes-like object is required, not 'str'
```

<details><summary>Searchable metadata</summary>

```
trac-id__9702 9702
type__defect defect
reporter__glyph glyph
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__conch conch
keywords__easy easy
time__1566455829548898 1566455829548898
changetime__1566455855541760 1566455855541760
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_1"></a>|@glyph commented|
|-|-|

Fixing encoding-confusion tracebacks is pretty easy, right?
