### ISSUE TITLE
require at least automat 0.8.0, since twisted.application.internet.ClientService raises an Exception on start on Python 3.8 on earlier versions of automat

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9718]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)| @hawkowl reported|
|-|-|
|Trac ID|trac#9718|
|Type|defect|
|Created|2019-10-19 19:36:29Z|

From the Synapse test suite:

```
Traceback (most recent call last):
  File "/home/hawkowl/code/synapse/tests/logging/test_terse_json.py", line 46, in test_log_output
    setup_structured_logging(
  File "/home/hawkowl/code/synapse/synapse/logging/_structured.py", line 333, in setup_structured_logging
    log_observer.start()
  File "/home/hawkowl/code/synapse/synapse/logging/_terse_json.py", line 189, in start
    self._service.startService()
  File "/home/hawkowl/code/synapse/.tox/py38/lib/python3.8/site-packages/twisted/application/internet.py", line 1138, in startService
    self._machine.start()
  File "/home/hawkowl/code/synapse/.tox/py38/lib/python3.8/site-packages/automat/_methodical.py", line 234, in __get__
    def doInput(*args, **kwargs):
  File "/home/hawkowl/code/synapse/.tox/py38/lib/python3.8/site-packages/automat/_introspection.py", line 40, in decorator
    return copyfunction(decorated,
  File "/home/hawkowl/code/synapse/.tox/py38/lib/python3.8/site-packages/automat/_introspection.py", line 32, in copyfunction
    return function(copycode(template.__code__, codechanges), *values)
  File "/home/hawkowl/code/synapse/.tox/py38/lib/python3.8/site-packages/automat/_introspection.py", line 20, in copycode
    return code(*values)
builtins.TypeError: an integer is required (got type bytes)
```

The Synapse code is here: https://github.com/matrix-org/synapse/blob/master/synapse/logging/_terse_json.py

<details><summary>Searchable metadata</summary>

```
trac-id__9718 9718
type__defect defect
reporter__hawkowl hawkowl
priority__normal normal
milestone__Python_3_8_Support Python 3.8 Support
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__None None
time__1571513789939428 1571513789939428
changetime__1589825593201483 1589825593201483
version__None None
owner__hawkowl hawkowl

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_1"></a>|@hawkowl commented|
|-|-|

I filed a bug on Automat, but I'm not sure if it's an Automat problem or a how-Twisted-uses it problem, so, I've filed bugs on both.

Automat issue: https://github.com/glyph/automat/issues/118

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_2"></a>|@hawkowl commented|
|-|-|

Upstream issue fixed in Automat.

Question is, do we want to update the Twisted dep so you can't get a misbehaving one on 3.8?

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_3"></a>|@glyph commented|
|-|-|

Replying to [hawkowl](#note_2):
> Upstream issue fixed in Automat.
> 
> Question is, do we want to update the Twisted dep so you can't get a misbehaving one on 3.8?

"yes"

Let's do that and close this issue thereby.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_5"></a>|@glyph commented|
|-|-|

In review:

https://github.com/twisted/twisted/pull/1273

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_6"></a>|@hawkowl set owner to @hawkowl|
|-|-|

lgtm

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_7"></a>|@glyph set status to `closed`|
|-|-|

In changeset e17604416eadc58e90f28806968e267a06c38909
```
#!CommitTicketReference repository="" revision="e17604416eadc58e90f28806968e267a06c38909"
Merge 9718-automat-3.8-baseline: Update automat dependency to 0.8.0 or greater

Author: glyph
Reviewer: hawkowl
Fixes: ticket:9718
```

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_8"></a>|@glyph commented|
|-|-|

🎊 thanks for the speedy review & integration hawkowl!
