### ISSUE TITLE
Twisted tests fail when using a cryptography that doesn't have NPN support

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9725]
|[<img alt="alex's avatar" src="https://avatars.githubusercontent.com/u/772?s=50" width="50" height="50">](https://github.com/alex)| @alex reported|
|-|-|
|Trac ID|trac#9725|
|Type|enhancement|
|Created|2019-11-10 17:21:25Z|

NPN has been deprecated, and is in the process of being removed, in favor of ALPN. You can see a WIP PR for this in cryptography at https://github.com/pyca/cryptography/pull/4765

However, twisted's tests fail under this PR:

```
[ERROR]
Traceback (most recent call last):
  File "/home/travis/.venv/lib/python2.7/site-packages/twisted/protocols/test/test_tls.py", line 1943, in checkNegotiatedProtocol
    self.assertEqual(client.negotiatedProtocol, b'h2')
  File "/home/travis/.venv/lib/python2.7/site-packages/twisted/trial/_synctest.py", line 434, in assertEqual
    super(_Assertions, self).assertEqual(first, second, msg)
  File "/opt/python/2.7.15/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/opt/python/2.7.15/lib/python2.7/unittest/case.py", line 506, in _baseAssertEqual
    raise self.failureException(msg)
twisted.trial.unittest.FailTest: None != 'h2'
twisted.protocols.test.test_tls.TLSMemoryBIOTests.test_disorderlyShutdown
```

One thing that is exceptionally confusing is that the test runner says `test_disorderlyShutdown` is the failing test, but the traceback points to an assertion in `test_negotiationWithProtocolOverlap`

<details><summary>Searchable metadata</summary>

```
trac-id__9725 9725
type__enhancement enhancement
reporter__alex alex
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__None None
time__1573406485455737 1573406485455737
changetime__1573406485455737 1573406485455737
version__None None
owner__None None

```
</details>

**Comment by glyph** [comment]
We correctly skip the tests now, and have for a while. (Source: most Cryptography's don't have NPN support any more, to the point where our coverage report actually fails for those lines, and yet the tests pass.)

Sorry I don't have a good citation for exactly when it got fixed.
