### ISSUE TITLE
Multipart returns 400 Bad Request on Python 3.7+

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9739]
|[<img alt="iamareebjamal's avatar" src="https://avatars.githubusercontent.com/u/3874064?s=50" width="50" height="50">](https://github.com/iamareebjamal)| @iamareebjamal reported|
|-|-|
|Trac ID|trac#9739|
|Type|defect|
|Created|2019-12-02 09:37:31Z|

Related: [#9448](https://github.com/twisted/twisted/issues/9448)
Pull Request: https://github.com/twisted/twisted/pull/1012

Downstream Issue: https://github.com/django/channels/issues/1386

Body:
```
--d66f495a-c4d1-487c-9277-9ab1a20001cc
Content-Disposition: form-data; name="content"
Content-Type: multipart/form-data; charset=utf-8

Anything
--d66f495a-c4d1-487c-9277-9ab1a20001cc--
```

Header:

```
Content-Type: multipart/form-data; boundary=d66f495a-c4d1-487c-9277-9ab1a20001cc
```

Twisted returns 400 Bad Request on Python 3.7+, works fine on Python 3.6-

In my brief debugging, Twisted tried to parse an empty line `b''` as valid boundary and throws, thus returning 400 Bad Request. That doesn't happen on Python 3.6-

This is where the exception is raised: https://github.com/twisted/twisted/blob/009b79eef42185d3c2e6a0553311c33504ddabe7/src/twisted/web/http.py#L907-L912

Hence, the problem possibly originates from this commit - https://github.com/python/cpython/commit/cc3fa204d357be5fafc10eb8c2a80fe0bca998f1

Hence, we are capped to Python 3.6 and can't move forward with upgrading to 3.7+

Any person using a library depending on twisted (like Django Channels) is impacted

<details><summary>Searchable metadata</summary>

```
trac-id__9739 9739
type__defect defect
reporter__iamareebjamal iamareebjamal
priority__high high
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__web web
keywords__multipart_python3_7_bad_request multipart,python3.7,bad request
time__1575279451587925 1575279451587925
changetime__1576958870978055 1576958870978055
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_1"></a>|@twm commented|
|-|-|

This is similar to [#9678](https://github.com/twisted/twisted/issues/9678)

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_2"></a>|@twm commented|
|-|-|

In Python 3.7 `cgi.parse_multipart()` was changed to use `FieldStorage` internally: https://github.com/python/cpython/commit/cc3fa204d357be5fafc10eb8c2a80fe0bca998f1

This is what prompted the changes in https://github.com/python/cpython/commit/cc3fa204d357be5fafc10eb8c2a80fe0bca998f1

I can reproduce this without any Twisted code:

```
Python 3.7.5 (default, Nov  7 2019, 10:50:52) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cgi
>>> 
>>> payload = """--d66f495a-c4d1-487c-9277-9ab1a20001cc
... Content-Disposition: form-data; name=\"content\"
... Content-Type: multipart/form-data; charset=utf-8
... Hello World
... --d66f495a-c4d1-487c-9277-9ab1a20001cc--"""
>>> from io import BytesIO
>>> content = BytesIO(payload.encode())
>>> pdict = {'boundary': b'd66f495a-c4d1-487c-9277-9ab1a20001cc', 'CONTENT-LENGTH': len(payload)}
>>> cgi.parse_multipart(content, pdict, encoding='utf8', errors='surrogateescape')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/cgi.py", line 222, in parse_multipart
    environ={'REQUEST_METHOD': 'POST'})
  File "/usr/lib/python3.7/cgi.py", line 489, in __init__
    self.read_multi(environ, keep_blank_values, strict_parsing)
  File "/usr/lib/python3.7/cgi.py", line 666, in read_multi
    self.encoding, self.errors, max_num_fields)
  File "/usr/lib/python3.7/cgi.py", line 489, in __init__
    self.read_multi(environ, keep_blank_values, strict_parsing)
  File "/usr/lib/python3.7/cgi.py", line 616, in read_multi
    raise ValueError('Invalid boundary in multipart form: %r' % (ib,))
ValueError: Invalid boundary in multipart form: b''
```

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_3"></a>|@twm commented|
|-|-|

This header from your example doesn't look valid to me:

```

Content-Type: multipart/form-data; charset=utf-8
```

It is missing the `boundary` parameter, [which is required](https://tools.ietf.org/html/rfc7578#section-8). This explains the `b''`. Also note that `charset` isn't defined for `multipart/form-data` (see that RFC --- charsets in form data are weird).

I'd guess that the behavioral change is due to [bpo-29979](https://bugs.python.org/issue29979). One aspect of the "consistency" it achieves is support for nested multipart, whereas the old implementation ignored the {{Content-Type}} of chunks as far as I can see.

What is generating this malformed input?

**Comment by twisted-trac** [comment]
|[<img alt="iamareebjamal's avatar" src="https://avatars.githubusercontent.com/u/3874064?s=50" width="50" height="50">](https://github.com/iamareebjamal)<a name="note_4"></a>|@iamareebjamal commented|
|-|-|

OkHTTP https://square.github.io/okhttp/

However, the request header does have a boundary, but parts in multipart don't. Not sure if it valid for parts headers to exclude boundary or not
