### ISSUE TITLE
hosts.Resolver should cope with malformed hosts lines

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9752]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)| @twm reported|
|-|-|
|Trac ID|trac#9752|
|Type|enhancement|
|Created|2019-12-31 20:48:06Z|
|Branch|https://github.com/twisted/twisted/tree/9752-malformed-hosts|

If `/etc/hosts` contains a malformed line (i.e. one that doesn't start with a valid IP address) then `twisted.names.hosts.Resolver` and `twisted.names.hosts.searchFileForAll` should ignore it, as glibc does. Such a malformed file may be accidentally generated by a human editor or misconfigured configuration management system. Right now it fails like this when AAAA records are requested:

```
Traceback (most recent call last):
  File ".../twisted/src/twisted/names/test/test_hosts.py", line 294, in test_lookupIPV6Malformed
    d = self.resolver.lookupIPV6Address(b'malformed')
  File ".../twisted/src/twisted/names/hosts.py", line 144, in lookupIPV6Address
    return self._respond(name, self._aaaaRecords(name))
  File ".../twisted/src/twisted/names/hosts.py", line 107, in _aaaaRecords
    in searchFileForAll(FilePath(self.file), name)
  File ".../twisted/src/twisted/names/hosts.py", line 108, in <listcomp>
    if not isIPAddress(addr)])
  File ".../twisted/src/twisted/names/dns.py", line 1374, in __init__
    self.address = socket.inet_pton(AF_INET6, address)
builtins.OSError: illegal IP address string passed to inet_pton
```

<details><summary>Searchable metadata</summary>

```
trac-id__9752 9752
type__enhancement enhancement
reporter__twm twm
priority__normal normal
milestone__None None
branch__9752_malformed_hosts 9752-malformed-hosts
branch_author__ 
status__closed closed
resolution__fixed fixed
component__names names
keywords__None None
time__1577825286374961 1577825286374961
changetime__1585445173970079 1585445173970079
version__None None
owner__twm twm

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)|@twm set owner to @twm<br>@twm set status to `assigned`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_3"></a>|@twm commented|
|-|-|

PR here: https://github.com/twisted/twisted/pull/1214

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_4"></a>|@rodrigc set status to `new`|
|-|-|

https://github.com/twisted/twisted/pull/1214#pullrequestreview-380821251

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_5"></a>|@twm set status to `closed`|
|-|-|

In changeset 147b31319009ef3c5d3e77cb4ed56bfc46dc61ed
```
#!CommitTicketReference repository="" revision="147b31319009ef3c5d3e77cb4ed56bfc46dc61ed"
Merge pull request #1214 from twisted/9752-malformed-hosts

Author: twm
Reviewer: rodrigc
Fixes: ticket:9752

Cope better with malformed /etc/hosts
```
