### ISSUE TITLE
Unclear type for argument to IReactorTCP.connectTCP

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9763]
|[<img alt="xdesai's avatar" src="https://avatars.githubusercontent.com/u/19935687?s=50" width="50" height="50">](https://github.com/xdesai)| @xdesai reported|
|-|-|
|Trac ID|trac#9763|
|Type|defect|
|Created|2020-02-11 15:34:15Z|

Hi All,

While converting our code base for python3 support I believe I have stumbled upon what I hope to be a simple documentation error, but felt the need to reach out for clarity.

`IReactorTCP.connectTCP` takes in an argument called `host`. According to the doc string of this function the type of `host` is to be `bytes`.
Here's the autogenerated documentation: https://twistedmatrix.com/documents/19.10.0/api/twisted.internet.interfaces.IReactorTCP.connectTCP.html

Despite this function declaring that it wants bytes for that parameter I see in several other pieces of twisted documentation that call that function with `string` as the type for `host`.
In my local testing passing in either `string` or `bytes` does seem to function correctly with the happy path. However, where we have encountered an issue is with a failed DNS resolution.

Passing in a bad hostname that doesn't resolve where the type of `host` is `string` you get a nice error like this

```
Connection failed. Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.DNSLookupError'>: DNS lookup failed: api-test.xander.
]
```

Passing in a bad hostname that doesn't resolve where the type of `host` is `bytes` we instead get this traceback.
```
Connection failed. Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.DNSLookupError'>: <DNSLookupError instance at 0x101c1a6a8 with str error:
 Traceback (most recent call last):
  File "/Users/xdesai/junk/python_weirdness/3env/lib/python3.7/site-packages/twisted/python/reflect.py", line 448, in safe_str
    return str(o)
  File "/Users/xdesai/junk/python_weirdness/3env/lib/python3.7/site-packages/twisted/internet/error.py", line 77, in __str__
    s = '%s: %s' % (s, ' '.join(self.args))
TypeError: sequence item 0: expected str instance, bytes found
>
]
```

I believe there are two simple solutions here, but I don't know which one is the right one.
1. Update the doc string for connectTCP to recommend `string` instead of `bytes`
2. Update the `__str__` method on `DNSLookupError` to handle bytes and strings

Hopefully this details the issue we are experiencing. I'm mostly trying to figure out what type we truly want to be using for the `connectTCP` call.

Please let me know if there's any more detail I can provide.

Best,
Xander

**ps**. Here is my short script to reproduce the above issue using python 3.7 and twisted 19.10.0
```
from twisted.internet import reactor
from twisted.internet.protocol import ClientFactory, Protocol

from sys import stdout

class Echo(Protocol):
    def dataReceived(self, data):
        stdout.write(data)

class EchoClientFactory(ClientFactory):
    def startedConnecting(self, connector):
        print('Started to connect.')

    def buildProtocol(self, addr):
        print('Connected.')
        return Echo()

    def clientConnectionLost(self, connector, reason):
        print('Lost connection.  Reason:', reason)

    def clientConnectionFailed(self, connector, reason):
        print('Connection failed. Reason:', reason)

def main():
    host = b'api-test.xander'
    port = 80
    reactor.connectTCP(host, port, EchoClientFactory())
    reactor.run()


if __name__ == '__main__':
    main()
```

<details><summary>Searchable metadata</summary>

```
trac-id__9763 9763
type__defect defect
reporter__xdesai xdesai
priority__normal normal
milestone__Python_3_x Python-3.x
branch__ 
branch_author__None None
status__closed closed
resolution__duplicate duplicate
component__core core
keywords__py3_python3_bytes_string_encoding_connectTCP_host_type py3 python3 bytes string encoding connectTCP host type
time__1581435255064983 1581435255064983
changetime__1581438538211050 1581438538211050
version__None None
owner__None None
cc__xdesai@...
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="Julian's avatar" src="https://avatars.githubusercontent.com/u/329822?s=50" width="50" height="50">](https://github.com/Julian)<a name="note_2"></a>|@Julian set status to `closed`|
|-|-|

Hi! Thanks.

This looks likely to be a duplicate of [#7956](https://github.com/twisted/twisted/issues/7956).

Feel free to lemme know if that's not the case, otherwise a fix would most definitely be welcome I'm sure.

**Comment by twisted-trac** [comment]
|[<img alt="xdesai's avatar" src="https://avatars.githubusercontent.com/u/19935687?s=50" width="50" height="50">](https://github.com/xdesai)<a name="note_3"></a>|@xdesai commented|
|-|-|

Ah yep it looks to be the same issue. Sorry for the duplicate. I should have searched harder.
Am I reading correctly that the ticket was opened 5 years ago. Would it help to create a pull request to change that doc string?

*Edit.
Nvm I reread your post. I'll see if I can whip up a doc string change sometime soon :)
