### ISSUE TITLE
twistd -n dns fails on Python 3

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9783]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)| @rodrigc reported|
|-|-|
|Trac ID|trac#9783|
|Type|defect|
|Created|2020-03-24 17:51:20Z|

I tried this example: https://twisted.readthedocs.io/en/twisted-18.9.0/names/howto/names.html#creating-an-authoritative-server

Using:

Twisted: 20.3.0
Python: 3.7

and it failed with:

```
Traceback (most recent call last):
  File "/Users/craigrodrigues/twisted-venv/lib/python3.7/site-packages/twisted/names/tap.py", line 95, in postOptions
    self.zones.append(authority.PySourceAuthority(f))
  File "/Users/craigrodrigues/twisted-venv/lib/python3.7/site-packages/twisted/names/authority.py", line 90, in __init__
    self.loadFile(filename)
  File "/Users/craigrodrigues/twisted-venv/lib/python3.7/site-packages/twisted/names/authority.py", line 290, in loadFile
    g, l = self.setupConfigNamespace(), {}
  File "/Users/craigrodrigues/twisted-venv/lib/python3.7/site-packages/twisted/names/authority.py", line 308, in setupConfigNamespace
    items = dns.__dict__.iterkeys()
```

<details><summary>Searchable metadata</summary>

```
trac-id__9783 9783
type__defect defect
reporter__rodrigc rodrigc
priority__normal normal
milestone__Python_3_x Python-3.x
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__names names
keywords__None None
time__1585072280055419 1585072280055419
changetime__1585165266607937 1585165266607937
version__None None
owner__rodrigc rodrigc

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_1"></a>|@rodrigc commented|
|-|-|

https://github.com/twisted/twisted/pull/1233

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_3"></a>|@rodrigc set owner to @rodrigc|
|-|-|

Approved by twm: https://github.com/twisted/twisted/pull/1233#pullrequestreview-380872910

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_4"></a>|@rodrigc set status to `closed`|
|-|-|

In changeset 1ffda84cbb7165172d53adcb687a9359ff6fdd07
```
#!CommitTicketReference repository="" revision="1ffda84cbb7165172d53adcb687a9359ff6fdd07"
Merge pull request #1233 from twisted/9783-rodrigc-names

Change iterkeys() to keys(), since iterkeys() does not exist in Python 3

Author: rodrigc
Reviewer: twm
Fixes: ticket:9783
```
