### ISSUE TITLE
_DefGen_Return and StopIteration can be set as __context__ for exceptions when using inlineCallbacks

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9792]
|[<img alt="ryban's avatar" src="https://avatars.githubusercontent.com/u/1617326?s=50" width="50" height="50">](https://github.com/ryban)| @ryban reported|
|-|-|
|Trac ID|trac#9792|
|Type|defect|
|Created|2020-04-01 20:44:27Z|

When using `inlineCallbacks`, raising an exception after defer.returnValue() or return is used in a called function will cause the `StopIteration` or `_DefGen_Return` exceptions to be the `__context__` for the actual exception. Attached script reproduces the issue.

```
Traceback (most recent call last):
  File "env/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "exc.py", line 17, in some_func
    defer.returnValue('hello')
  File "env/lib/python3.7/site-packages/twisted/internet/defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: hello

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "exc.py", line 24, in run
    raise Exception('Some actual error')
Exception: Some actual error
```

Potential solution would be to not call status.deferred.callback from with the `except` blocks. https://github.com/twisted/twisted/blob/twisted-20.3.0/src/twisted/internet/defer.py#L1461

Attachments:

* [exc.py](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/99e/99ef211e0b71e089624b136ec91e8e5b6b748878/a6ec4ce3466cd15ec7e766238233102e080e00fd.py) (914 bytes) - added by ryban on 2020-04-01 20:44:49Z - 

<details><summary>Searchable metadata</summary>

```
trac-id__9792 9792
type__defect defect
reporter__ryban ryban
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__duplicate duplicate
component__core core
keywords__None None
time__1585773867912694 1585773867912694
changetime__1656137391144817 1656137391144817
version__None None
owner__mstojcevich mstojcevich
cc__mstojcevich
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="mstojcevich's avatar" src="https://avatars.githubusercontent.com/u/871961?s=50" width="50" height="50">](https://github.com/mstojcevich)<a name="note_1"></a>|@mstojcevich commented|
|-|-|

pr https://github.com/twisted/twisted/pull/1606

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_3"></a>|@glyph set owner to @mstojcevich|
|-|-|

Thanks for your contribution.

It seems like graingert reviewed this and requested changes on github, but he forgot to update this ticket. Can you address that feedback and resubmit by re-adding the review keyword here? Thanks!

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_5"></a>|@exarkun commented|
|-|-|

It looks like there is some duplication of effort between here and [#10260](https://github.com/twisted/twisted/issues/10260)

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_6"></a>|@twm set status to `closed`|
|-|-|

Resolving as a duplicate of [#10260](https://github.com/twisted/twisted/issues/10260), which was fixed in https://github.com/twisted/twisted/commit/ee0728c339091b316dc23f57a642e142c1690a93.
