### ISSUE TITLE
Remove pycodestyle checks from twistedchecker

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9796]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)| @rodrigc reported|
|-|-|
|Trac ID|trac#9796|
|Type|defect|
|Created|2020-04-09 19:35:01Z|

In [#9389](https://github.com/twisted/twisted/issues/9389) , a plugin to pycodestyle was introduced into the tree.
This plugin is run during tox and travis checks of the code.

We need to remove pycodestyle from twistedchecker, because the plugin there is outdated and
shows a big stacktrace during CI runs like:

```
Traceback (most recent call last):

  File "/home/travis/build/twisted/twisted/build/lint/bin/twistedchecker", line 11, in <module>

    sys.exit(main())

  File "/home/travis/build/twisted/twisted/build/lint/lib/python3.5/site-packages/twistedchecker/core/runner.py", line 439, in main

    runner.run(sys.argv[1:])

  File "/home/travis/build/twisted/twisted/build/lint/lib/python3.5/site-packages/twistedchecker/core/runner.py", line 315, in run

    self.linter.check(args)

  File "/home/travis/build/twisted/twisted/build/lint/lib/python3.5/site-packages/pylint/lint.py", line 736, in check

    self._do_check(files_or_modules)

  File "/home/travis/build/twisted/twisted/build/lint/lib/python3.5/site-packages/pylint/lint.py", line 867, in _do_check

    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)

  File "/home/travis/build/twisted/twisted/build/lint/lib/python3.5/site-packages/pylint/lint.py", line 947, in check_astroid_module

    walker.walk(ast_node)

  File "/home/travis/build/twisted/twisted/build/lint/lib/python3.5/site-packages/pylint/utils.py", line 935, in walk

    cb(astroid)

  File "/home/travis/build/twisted/twisted/build/lint/lib/python3.5/site-packages/twistedchecker/checkers/pycodestyleformat.py", line 182, in visit_module

    recorder = PyCodeStyleWarningRecorder(node.file)

  File "/home/travis/build/twisted/twisted/build/lint/lib/python3.5/site-packages/twistedchecker/checkers/pycodestyleformat.py", line 50, in __init__

    self.run()

  File "/home/travis/build/twisted/twisted/build/lint/lib/python3.5/site-packages/twistedchecker/checkers/pycodestyleformat.py", line 79, in run

    pycodestyle.Checker.check_all(self)

  File "/home/travis/build/twisted/twisted/build/lint/lib/python3.5/site-packages/pycodestyle.py", line 2113, in check_all

    self.check_logical()

  File "/home/travis/build/twisted/twisted/build/lint/lib/python3.5/site-packages/pycodestyle.py", line 1998, in check_logical

    for offset, text in self.run_check(check, argument_names) or ():

  File "/home/travis/build/twisted/twisted/build/lint/lib/python3.5/site-packages/pycodestyle.py", line 1927, in run_check

    return check(*arguments)
```

This error makes it confusing for people to determine what caused their CI run to fail.

<details><summary>Searchable metadata</summary>

```
trac-id__9796 9796
type__defect defect
reporter__rodrigc rodrigc
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__None None
time__1586460901688249 1586460901688249
changetime__1586534315074493 1586534315074493
version__None None
owner__Craig_Rodrigues__rodrigc_____ Craig Rodrigues <rodrigc@...>

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_1"></a>|@rodrigc commented|
|-|-|

See:
https://github.com/twisted/twisted/pull/1248
https://github.com/twisted/twistedchecker/pull/139

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_2"></a>|@rodrigc commented|
|-|-|

Approved: https://github.com/twisted/twisted/pull/1248#pullrequestreview-391386148

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_3"></a>|@rodrigc set owner to @rodrigc<br>@rodrigc set status to `closed`|
|-|-|

In changeset 775c57f7deb536d72498296520b6ebc5ed154b14
```
#!CommitTicketReference repository="" revision="775c57f7deb536d72498296520b6ebc5ed154b14"
Merge pull request #1248 from twisted/9796-rodrigc-no-pycodestylechecker-2

Remove broken pycodestyle checker from twistedchecker

Author: rodrigc
Reviewer: adiroiban
Fixes: ticket:9796
```
