### ISSUE TITLE
Twisted HTTP2 closes connection with ConnectionLost instead of Failure

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9817]
|[<img alt="clokep's avatar" src="https://avatars.githubusercontent.com/u/517124?s=50" width="50" height="50">](https://github.com/clokep)| @clokep reported|
|-|-|
|Trac ID|trac#9817|
|Type|defect|
|Created|2020-05-08 19:08:57Z|

This was originally reported as a bug in Synapse, but it seems to be a bug in Twisted: https://github.com/matrix-org/synapse/issues/7441

The related stack trace with Twisted 20.3.0 is:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/synapse/app/_base.py", line 114, in run
    run_command()
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/base.py", line 1283, in run
    self.mainLoop()
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/base.py", line 1295, in mainLoop
    self.doIteration(t)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/pollreactor.py", line 169, in doPoll
    log.callWithLogger(selectable, _drdw, selectable, fd, event)
--- <exception caught here> ---
  File "/usr/local/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/local/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/local/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 627, in _doReadOrWrite
    self._disconnectSelectable(selectable, why, inRead)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 258, in _disconnectSelectable
    selectable.connectionLost(failure.Failure(why))
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/tcp.py", line 321, in connectionLost
    abstract.FileDescriptor.connectionLost(self, reason)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/abstract.py", line 205, in connectionLost
    self.producer.stopProducing()
  File "/usr/local/lib/python3.6/site-packages/twisted/protocols/tls.py", line 111, in stopProducing
    self._producer.stopProducing()
  File "/usr/local/lib/python3.6/site-packages/twisted/web/_http2.py", line 353, in stopProducing
    self.connectionLost(ConnectionLost("Producing stopped"))
  File "/usr/local/lib/python3.6/site-packages/twisted/web/_http2.py", line 290, in connectionLost
    stream.connectionLost(reason)
  File "/usr/local/lib/python3.6/site-packages/twisted/web/_http2.py", line 1077, in connectionLost
    self._request.connectionLost(reason)
  File "/usr/local/lib/python3.6/site-packages/synapse/http/site.py", line 204, in connectionLost
    "Error processing request %r: %s %s", self, reason.type, reason.value
builtins.AttributeError: 'ConnectionLost' object has no attribute 'type'
```

<details><summary>Searchable metadata</summary>

```
trac-id__9817 9817
type__defect defect
reporter__clokep clokep
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__web web
keywords__None None
time__1588964937435652 1588964937435652
changetime__1592345513000550 1592345513000550
version__None None
owner__clokep clokep

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="clokep's avatar" src="https://avatars.githubusercontent.com/u/517124?s=50" width="50" height="50">](https://github.com/clokep)<a name="note_2"></a>|@clokep commented|
|-|-|

https://github.com/twisted/twisted/pull/1265

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_3"></a>|@glyph set owner to @clokep|
|-|-|

Thanks!

Review over on GH https://github.com/twisted/twisted/pull/1265#pullrequestreview-410580957

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_5"></a>|@rodrigc commented|
|-|-|

https://github.com/twisted/twisted/pull/1265

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_6"></a>|@rodrigc commented|
|-|-|

Approved here: https://github.com/twisted/twisted/pull/1265#pullrequestreview-431843904

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_7"></a>|@rodrigc set status to `closed`|
|-|-|

In changeset f1636822294c9c6bddefa7d10f0765cc09f34223
```
#!CommitTicketReference repository="" revision="f1636822294c9c6bddefa7d10f0765cc09f34223"
Merge pull request #1265 from clokep/http2-failure

Wrap ConnectionLost in a Failure for HTTP/2

Author: clokep
Reviewer: rodrigc
Fixes: ticket:9817
```
