### ISSUE TITLE
imap4-utf-7 codec registration does not seem to work on py3.9

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9832]
|[<img alt="mgorny's avatar" src="https://avatars.githubusercontent.com/u/110765?s=50" width="50" height="50">](https://github.com/mgorny)| @mgorny reported|
|-|-|
|Trac ID|trac#9832|
|Type|defect|
|Created|2020-05-27 12:27:05Z|

When running tests with py3.9, a lot of them fail with an error similar to the following:

```
twisted.mail.test.test_imap.UnsolicitedResponseTests.testReadWrite
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/tmp/twisted/build/py39-alldeps-withcov/lib/python3.9/site-packages/twisted/mail/test/test_imap.py", line 59, in <lambda>
    return lambda result, f=f: f()
  File "/tmp/twisted/build/py39-alldeps-withcov/lib/python3.9/site-packages/twisted/mail/test/test_imap.py", line 7358, in select
    return self.client.select("mailbox-test")
  File "/tmp/twisted/build/py39-alldeps-withcov/lib/python3.9/site-packages/twisted/mail/imap4.py", line 3246, in select
    args = _prepareMailboxName(mailbox)
  File "/tmp/twisted/build/py39-alldeps-withcov/lib/python3.9/site-packages/twisted/mail/imap4.py", line 5003, in _prepareMailboxName
    name = name.encode('imap4-utf-7')
builtins.LookupError: unknown encoding: imap4-utf-7
```

It seems that Python 3.9 is passing `imap4_utf_7` to the lookup function.

<details><summary>Searchable metadata</summary>

```
trac-id__9832 9832
type__defect defect
reporter__mgorny mgorny
priority__normal normal
milestone__Python_3_9_Support Python 3.9 Support
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__mail mail
keywords__None None
time__1590582425172150 1590582425172150
changetime__1592669512630910 1592669512630910
version__None None
owner__Craig_Rodrigues__rodrigc_____ Craig Rodrigues <rodrigc@...>

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="mgorny's avatar" src="https://avatars.githubusercontent.com/u/110765?s=50" width="50" height="50">](https://github.com/mgorny)<a name="note_1"></a>|@mgorny commented|
|-|-|

https://github.com/twisted/twisted/pull/1276

**Comment by twisted-trac** [comment]
|[<img alt="wiml's avatar" src="https://avatars.githubusercontent.com/u/156891?s=50" width="50" height="50">](https://github.com/wiml)<a name="note_3"></a>|@wiml commented|
|-|-|

Some context, this seems to be an as-yet-undocumented breaking change in py3.9:

https://bugs.python.org/issue37751

Here's the PR to document the change: https://github.com/python/cpython/pull/17997

A bunch of other projects have also hit this. It looks like the change in this PR is likely what the Python folks expect. The behavior is described in the `encodings.normalize_encoding()` docstring.

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_4"></a>|@rodrigc commented|
|-|-|

Approved here: https://github.com/twisted/twisted/pull/1276#pullrequestreview-421595430

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_5"></a>|@rodrigc set owner to @rodrigc<br>@rodrigc set status to `closed`|
|-|-|

In changeset 8537bb8062c112746d18f85f758b60faf4f570de
```
#!CommitTicketReference repository="" revision="8537bb8062c112746d18f85f758b60faf4f570de"
Merge pull request #1276 from mgorny/9832-mgorny-imapcodec

Fix imap4-utf-7 codec lookup function for Python 3.9

Author: mgorny
Reviewer: wiml, rodrigc
Fixes: ticket:9832
```
