### ISSUE TITLE
crypt.crypt() raises OSError on invalid salt on py3.9

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9833]
|[<img alt="mgorny's avatar" src="https://avatars.githubusercontent.com/u/110765?s=50" width="50" height="50">](https://github.com/mgorny)| @mgorny reported|
|-|-|
|Trac ID|trac#9833|
|Type|defect|
|Created|2020-05-27 13:03:57Z|

The following tests fail on py3.9:

```
[ERROR]
Traceback (most recent call last):
  File "/home/mgorny/git/twisted/build/py39-alldeps-nocov/lib/python3.9/site-packages/twisted/conch/test/test_checkers.py", line 487, in test_defaultCheckers
    self.assertLoggedIn(checker.requestAvatarId(cred), b'bob')
  File "/home/mgorny/git/twisted/build/py39-alldeps-nocov/lib/python3.9/site-packages/twisted/conch/checkers.py", line 131, in requestAvatarId
    if verifyCryptedPassword(crypted, password):
  File "/home/mgorny/git/twisted/build/py39-alldeps-nocov/lib/python3.9/site-packages/twisted/conch/checkers.py", line 56, in verifyCryptedPassword
    return crypt.crypt(pw, crypted) == crypted
  File "/usr/lib/python3.9/crypt.py", line 82, in crypt
    return _crypt.crypt(word, salt)
builtins.OSError: [Errno 22] Zły argument

twisted.conch.test.test_checkers.UNIXPasswordDatabaseTests.test_defaultCheckers
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/home/mgorny/git/twisted/build/py39-alldeps-nocov/lib/python3.9/site-packages/twisted/conch/test/test_checkers.py", line 601, in test_failOnSpecial
    self.assertUnauthorizedLogin(checker.requestAvatarId(cred))
  File "/home/mgorny/git/twisted/build/py39-alldeps-nocov/lib/python3.9/site-packages/twisted/conch/checkers.py", line 131, in requestAvatarId
    if verifyCryptedPassword(crypted, password):
  File "/home/mgorny/git/twisted/build/py39-alldeps-nocov/lib/python3.9/site-packages/twisted/conch/checkers.py", line 56, in verifyCryptedPassword
    return crypt.crypt(pw, crypted) == crypted
  File "/usr/lib/python3.9/crypt.py", line 82, in crypt
    return _crypt.crypt(word, salt)
builtins.OSError: [Errno 22] Zły argument

twisted.conch.test.test_checkers.UNIXPasswordDatabaseTests.test_failOnSpecial
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/home/mgorny/git/twisted/build/py39-alldeps-nocov/lib/python3.9/site-packages/twisted/cred/test/test_strcred.py", line 323, in test_verifyCryptedPassword
    self.assertFalse(cred_unix.verifyCryptedPassword(cryptedIncorrect,
  File "/home/mgorny/git/twisted/build/py39-alldeps-nocov/lib/python3.9/site-packages/twisted/plugins/cred_unix.py", line 46, in verifyCryptedPassword
    return crypt.crypt(pw, crypted) == crypted
  File "/usr/lib/python3.9/crypt.py", line 82, in crypt
    return _crypt.crypt(word, salt)
builtins.OSError: [Errno 22] Zły argument

twisted.cred.test.test_strcred.CryptTests.test_verifyCryptedPassword

```

(sorry about the polish in logs, it says EINVAL)

FWICS this is because Python 3.9 started checking the result of `crypt()` and raising exception if it failed.

<details><summary>Searchable metadata</summary>

```
trac-id__9833 9833
type__defect defect
reporter__mgorny mgorny
priority__normal normal
milestone__Python_3_9_Support Python 3.9 Support
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__None None
time__1590584637269143 1590584637269143
changetime__1598562893372476 1598562893372476
version__None None
owner__mgorny mgorny

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="mgorny's avatar" src="https://avatars.githubusercontent.com/u/110765?s=50" width="50" height="50">](https://github.com/mgorny)<a name="note_1"></a>|@mgorny commented|
|-|-|

https://github.com/twisted/twisted/pull/1277

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_3"></a>|@glyph set owner to @mgorny|
|-|-|

Review over on github: https://github.com/twisted/twisted/pull/1277#pullrequestreview-423261572

Thanks again for your contribution; please re-submit if you can add just a tiny bit of test coverage!

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_4"></a>|@rodrigc commented|
|-|-|

Michał add the last bit of test coverage, so I think this looks OK now, and I approved it here: https://github.com/twisted/twisted/pull/1277#pullrequestreview-462162385

**Comment by twisted-trac** [comment]
|<img alt="Michał Górny's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_5"></a>|Michał Górny set status to `closed`|
|-|-|

In changeset e5b37676d17bd20d156e51299df98105de5b59f0
```
#!CommitTicketReference repository="" revision="e5b37676d17bd20d156e51299df98105de5b59f0"
Fix verifyCryptedPassword() for crypt.crypt() throwing in py3.9

In Python 3.9, the crypt.crypt() function may throw an exception
if the underlying crypt() function fails.  Update
verifyCryptedPassword() to account for that, and preserve the existing
behavior of returning False in that case.

Fixes: ticket:9833
```

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_6"></a>|@rodrigc commented|
|-|-|

In changeset aae60ddea018b05514084fba8b6f1886871df548
```
#!CommitTicketReference repository="" revision="aae60ddea018b05514084fba8b6f1886871df548"
Merge pull request #1277 from mgorny/9833-mgorny-crypt-oserror

Fix verifyCryptedPassword() for crypt.crypt() throwing in py3.9

Author: mgorny
Reviewer: rodrigc
Fixes: ticket:9833
```

**Comment by twisted-trac** [comment]
|<img alt="Michał Górny's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_7"></a>|Michał Górny commented|
|-|-|

In changeset f8bb02b7e96fae518f6f121856b0886bf654ee00
```
#!CommitTicketReference repository="" revision="f8bb02b7e96fae518f6f121856b0886bf654ee00"
Fix verifyCryptedPassword() for crypt.crypt() throwing in py3.9

In Python 3.9, the crypt.crypt() function may throw an exception
if the underlying crypt() function fails.  Update
verifyCryptedPassword() to account for that, and preserve the existing
behavior of returning False in that case.

Fixes: ticket:9833
```
