### ISSUE TITLE
xml.etree.cElementTree has been removed in Python 3.9

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9834]
|[<img alt="mgorny's avatar" src="https://avatars.githubusercontent.com/u/110765?s=50" width="50" height="50">](https://github.com/mgorny)| @mgorny reported|
|-|-|
|Trac ID|trac#9834|
|Type|defect|
|Created|2020-05-27 13:36:41Z|

```
[ERROR]
Traceback (most recent call last):
  File "/home/mgorny/git/twisted/build/py39-alldeps-nocov/lib/python3.9/site-packages/twisted/trial/runner.py", line 598, in loadPackage
    module = modinfo.load()
  File "/home/mgorny/git/twisted/build/py39-alldeps-nocov/lib/python3.9/site-packages/twisted/python/modules.py", line 391, in load
    return self.pathEntry.pythonPath.moduleLoader(self.name)
  File "/home/mgorny/git/twisted/build/py39-alldeps-nocov/lib/python3.9/site-packages/twisted/python/reflect.py", line 307, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "/home/mgorny/git/twisted/build/py39-alldeps-nocov/lib/python3.9/site-packages/twisted/python/reflect.py", line 254, in _importAndCheckStack
    reraise(excValue, excTraceback)
  File "/home/mgorny/git/twisted/build/py39-alldeps-nocov/lib/python3.9/site-packages/twisted/web/test/test_flatten.py", line 12, in <module>
    from xml.etree.cElementTree import XML
builtins.ModuleNotFoundError: No module named 'xml.etree.cElementTree'

twisted.web.test.test_flatten
```

According to [docs](https://docs.python.org/3/library/xml.etree.elementtree.html), xml.etree.ElementTree automatically uses cElementTree when available in py3.3+.

<details><summary>Searchable metadata</summary>

```
trac-id__9834 9834
type__defect defect
reporter__mgorny mgorny
priority__normal normal
milestone__Python_3_9_Support Python 3.9 Support
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__None None
time__1590586601099130 1590586601099130
changetime__1592724321317698 1592724321317698
version__None None
owner__mgorny mgorny

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="mgorny's avatar" src="https://avatars.githubusercontent.com/u/110765?s=50" width="50" height="50">](https://github.com/mgorny)<a name="note_1"></a>|@mgorny commented|
|-|-|

https://github.com/twisted/twisted/pull/1278

**Comment by twisted-trac** [comment]
|<img alt="Michał Górny's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_3"></a>|Michał Górny set owner to Michał Górny<br>Michał Górny set status to `closed`|
|-|-|

In changeset 61edfe6fb037f8bf1097bbe80d491982ea46223d
```
#!CommitTicketReference repository="" revision="61edfe6fb037f8bf1097bbe80d491982ea46223d"
Use xml.etree.ElementTree instead of deprecated cElementTree

The xml.etree.cElementTree is deprecated, and has been removed in Python
3.9.  At the same time, xml.etree.ElementTree has already been using
cElementTree implicitly since Python 3.3.  Update test_flatten to use
the latter to provide compatibility with newer Python versions.

Fixes: ticket:9834
```

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_4"></a>|@hawkowl set status to `reopened`|
|-|-|

oops this shouldn't get closed

**Comment by twisted-trac** [comment]
|[<img alt="mgorny's avatar" src="https://avatars.githubusercontent.com/u/110765?s=50" width="50" height="50">](https://github.com/mgorny)<a name="note_5"></a>|@mgorny commented|
|-|-|

Thank you for merging it.  Is there anything else I should do?

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_6"></a>|@glyph commented|
|-|-|

> Thank you for merging it. Is there anything else I should do?

It wasn't merged!  What happened here is that you discovered a bug in our commit hook :).  You used the syntax that is supposed to be reserved for merge commits in a commit on your branch ("`Fixes: ticket:...`") and thereby demonstrated that the hook fires for things that aren't on `master`.

Hopefully somebody will get around to fixing that…

**Comment by twisted-trac** [comment]
|[<img alt="mgorny's avatar" src="https://avatars.githubusercontent.com/u/110765?s=50" width="50" height="50">](https://github.com/mgorny)<a name="note_7"></a>|@mgorny commented|
|-|-|

Ah, sorry, I was looking on how to reference the ticket from the PR in `git log` and it seemed the obvious choice.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_8"></a>|@glyph commented|
|-|-|

Yeah this is totally our bad, not yours!  It makes intuitive sense to include this in the commit message you're proposing.  (Or, rather, Git & Github's, really; it would be nice to specify the message for the merge commit before the actual landing)

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)|@glyph removed owner<br>@glyph set status to `new`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)|@glyph set owner to @mgorny|
|-|-|

**Comment by twisted-trac** [comment]
|<img alt="Michał Górny's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_11"></a>|Michał Górny set status to `closed`|
|-|-|

In changeset 0fa59ffa74ba2f87d90598834d23fabb6a2f31be
```
#!CommitTicketReference repository="" revision="0fa59ffa74ba2f87d90598834d23fabb6a2f31be"
Use xml.etree.ElementTree instead of deprecated cElementTree

The xml.etree.cElementTree is deprecated, and has been removed in Python
3.9.  At the same time, xml.etree.ElementTree has already been using
cElementTree implicitly since Python 3.3.  Update test_flatten to use
the latter to provide compatibility with newer Python versions.

Fixes: ticket:9834
```

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_12"></a>|@rodrigc commented|
|-|-|

In changeset fd82b1bf048452fd1b14674490050bdbd7a84202
```
#!CommitTicketReference repository="" revision="fd82b1bf048452fd1b14674490050bdbd7a84202"
Use xml.etree.ElementTree instead of deprecated cElementTree

The xml.etree.cElementTree is deprecated, and has been removed in Python
3.9.  At the same time, xml.etree.ElementTree has already been using
cElementTree implicitly since Python 3.3.  Update test_flatten to use
the latter to provide compatibility with newer Python versions.

Submitted by: Michal Gorny <mgorny@...>
Fixes: ticket:9834
```

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_13"></a>|@rodrigc commented|
|-|-|

Approved here: https://github.com/twisted/twisted/pull/1278#pullrequestreview-434452007

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)|@rodrigc set status to `reopened`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_15"></a>|@rodrigc commented|
|-|-|

Re-submitted here: https://github.com/twisted/twisted/pull/1303
to work around issue with submitting a PR from an account with non-ASCII characters in the user id.

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_16"></a>|@rodrigc set status to `closed`|
|-|-|

In changeset 96261df69c05c0b50128d71308ff50e13dd0f010
```
#!CommitTicketReference repository="" revision="96261df69c05c0b50128d71308ff50e13dd0f010"
Merge pull request #1303 from twisted/9834-mgorny-elementtree-1

Use xml.etree.ElementTree instead of deprecated cElementTree

Author: mgorny
Reviewer: rodrigc
Fixes: ticket:9834
```

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_17"></a>|@glyph commented|
|-|-|

Thank you for tracking this down and getting it landed, Craig!  I would not have guessed the submitter's name _could_ be the problem.

And sorry for the problems, Michał.  Hopefully we can clear up this CI problem soon.
