### ISSUE TITLE
SFTPServerForUnixConchUser._absPath fails as it expects UnixConchUser.getHomeDir to return a FilePath object

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9845]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)| @adiroiban reported|
|-|-|
|Trac ID|trac#9845|
|Type|defect|
|Created|2020-06-06 08:45:00Z|

The UnixConchUser.getHomeDir returns a string and all SFTPServerForUnixConchUser operation fail.

I have attached a diff with a possible fix.

The diff also includes and update the the simple SSH server.
This can be used for manual testing.

Attachments:

* [conch-sftp-unix.diff](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/9b8/9b82ca9c4b4efc235f1a9b6c99ebbe5965543abb/36e20132e6d66663b27d1625330763c1b0887b48.diff) (2458 bytes) - added by adiroiban on 2020-06-06 08:45:18Z - 

<details><summary>Searchable metadata</summary>

```
trac-id__9845 9845
type__defect defect
reporter__adiroiban adiroiban
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__conch conch
keywords__None None
time__1591433100617764 1591433100617764
changetime__1591433168419947 1591433168419947
version__None None
owner__None None

```
</details>

**Comment by glyph** [comment]
I think I just hit this because I see this in my logs for my SFTP server: 

```
2025-07-19T21:24:23+0000 [twisted.conch.ssh.session#info] Asking for subsystem "b'sftp'"
2025-07-19T21:24:23+0000 [twisted.conch.unix.UnixConchUser#debug] Subsystem lookup: {b'sftp': <class 'twisted.conch.ssh.filetransfer.FileTransferServer'>}
2025-07-19T21:24:23+0000 [twisted.conch.ssh.filetransfer.FileTransferServer#info] dispatching: INIT requestId=3
2025-07-19T21:24:23+0000 [twisted.conch.ssh.filetransfer.FileTransferServer#info] dispatching: REALPATH requestId=1
2025-07-19T21:24:23+0000 [twisted.conch.ssh.filetransfer.FileTransferServer#critical] Request b'\x00\x00\x00\x01' failed with unknown error: b'realpath failed'
	Traceback (most recent call last):
	  File "/code/env/lib/pypy3.9/site-packages/twisted/internet/defer.py", line 216, in maybeDeferred
	    result = f(*args, **kwargs)
	  File "/code/env/lib/pypy3.9/site-packages/twisted/conch/unix.py", line 439, in realPath
	    return os.path.realpath(self._absPath(path))
	  File "/code/env/lib/pypy3.9/site-packages/twisted/conch/unix.py", line 387, in _absPath
	    return os.path.join(nativeString(home.path), nativeString(path))
	builtins.AttributeError: 'str' object has no attribute 'path'
```

But, I have been running this for years and successfully uploaded a file as recently as 7/8, when I was running 25.5.0rc1.

Not sure what has changed.

**Comment by glyph** [comment]
See also:

- #9056 
- #737 (and #720)

**Comment by glyph** [comment]
> Not sure what has changed.

Oops, nothing has changed. My other SFTP client was experiencing an unrelated bug; this has always been an issue with the command-line OpenSSH `sftp`.
