### ISSUE TITLE
ImportError: Gtk3 requires X11, and no DISPLAY environment variable is set

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9904]
|[<img alt="muelli's avatar" src="https://avatars.githubusercontent.com/u/322807?s=50" width="50" height="50">](https://github.com/muelli)| @muelli reported|
|-|-|
|Trac ID|trac#9904|
|Type|enhancement|
|Created|2020-07-14 11:56:27Z|

```
Traceback (most recent call last):
  File "/app/bin/gnome-keysign", line 10, in <module>
    sys.exit(main())
  File "/app/lib/python3.7/site-packages/keysign/__init__.py", line 22, in main
    from . import app
  File "/app/lib/python3.7/site-packages/keysign/app.py", line 31, in <module>
    from twisted.internet import gtk3reactor
  File "/app/lib/python3.7/site-packages/twisted/internet/gtk3reactor.py", line 38, in <module>
    "Gtk3 requires X11, and no DISPLAY environment variable is set")
ImportError: Gtk3 requires X11, and no DISPLAY environment variable is set
```

This seems to be hard coded
https://github.com/twisted/twisted/blob/7adb46869d9b215e2a01fe7194a715a60579ddbc/src/twisted/internet/gtk3reactor.py#L34-L37

clearly, people run wayland sessions.

https://github.com/flathub/org.gnome.Keysign/issues/14

<details><summary>Searchable metadata</summary>

```
trac-id__9904 9904
type__enhancement enhancement
reporter__muelli muelli
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__None None
time__1594727787212418 1594727787212418
changetime__1599881875740526 1599881875740526
version__None None
owner__Tom_Most__twm_____ Tom Most <twm@...>

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="muelli's avatar" src="https://avatars.githubusercontent.com/u/322807?s=50" width="50" height="50">](https://github.com/muelli)<a name="note_3"></a>|@muelli commented|
|-|-|

I have just found this bug which introduced the check:     [#6170](https://github.com/twisted/twisted/issues/6170)

**Comment by twisted-trac** [comment]
|[<img alt="muelli's avatar" src="https://avatars.githubusercontent.com/u/322807?s=50" width="50" height="50">](https://github.com/muelli)<a name="note_4"></a>|@muelli commented|
|-|-|

I have experimented a little bit.

My setup is a freshly installed Ubuntu 20.04 with a Wayland session.
xlsclients shows a few thing, namely:
ubuntu-Standard-PC-Q35-ICH9-2009  spice-vdagent
ubuntu-Standard-PC-Q35-ICH9-2009  gsd-xsettings
ubuntu-Standard-PC-Q35-ICH9-2009  ibus-x11
ubuntu-Standard-PC-Q35-ICH9-2009  gnome-shell


When starting a X11 application, e.g. xeyes, xlsclients shows:
ubuntu-Standard-PC-Q35-ICH9-2009  spice-vdagent
ubuntu-Standard-PC-Q35-ICH9-2009  gsd-xsettings
ubuntu-Standard-PC-Q35-ICH9-2009  ibus-x11
ubuntu-Standard-PC-Q35-ICH9-2009  gnome-shell
ubuntu-Standard-PC-Q35-ICH9-2009  xeyes


Now, I've run
$ env --unset DISPLAY gnome-keysign

to make sure that it doesn't use X.
Note that gnome-keysign makes use of the gtk3 reactor.
Of course, it crashes due to the test in /usr/lib/python3/dist-packages/twisted/internet/gtk3reactor.py.
But after I have simply patched the whole test out, it ran fine.

xlsclients does not show the additional app.

I conclude that the gtk3 reactor runs fine with the DISPLAY variable being set. And it runs fine on Wayland.

**Comment by twisted-trac** [comment]
|[<img alt="muelli's avatar" src="https://avatars.githubusercontent.com/u/322807?s=50" width="50" height="50">](https://github.com/muelli)<a name="note_5"></a>|@muelli commented|
|-|-|

https://github.com/twisted/twisted/pull/1379

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)|@twm set owner to @twm<br>@twm set status to `assigned`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_7"></a>|@twm removed owner<br>@twm set status to `new`|
|-|-|

Approved: https://github.com/twisted/twisted/pull/1379#pullrequestreview-487199712

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_8"></a>|@twm set owner to @twm<br>@twm set status to `closed`|
|-|-|

In changeset 6546d06769e4ca93771608fd4cbdb81d0654aa95
```
#!CommitTicketReference repository="" revision="6546d06769e4ca93771608fd4cbdb81d0654aa95"
Merge pull request #1379 from muelli/9904-muelli-wayland

Author: muelli
Reviewer: twm
Fixes: ticket:9904

gtk3: remove check for DISPLAY variable
```
