### ISSUE TITLE
python3 -bb failures

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9950]
|[<img alt="justinpryzby's avatar" src="https://avatars.githubusercontent.com/u/6146401?s=50" width="50" height="50">](https://github.com/justinpryzby)| @justinpryzby reported|
|-|-|
|Trac ID|trac#9950|
|Type|defect|
|Created|2020-09-02 20:42:36Z|

Hit this due to a unix socket which wasn't removed on shutdown.
Same isse if lockfile exists.

Should say:

```
        except socket.error as le:
            raise error.CannotListenError(None, self.port.decode(), le)
```

Details:
```
Traceback (most recent call last):
  File "/home/telsasoft/server/server/updsrv.py", line 228, in <module>
    start_server_threads(upd._socket_filename, PORT)
  File "/home/telsasoft/server/server/updsrv.py", line 221, in start_server_threads
    start_ipc_server(socket)
  File "/home/telsasoft/server/server/updsrv.py", line 205, in start_ipc_server
    raise res.result
twisted.python.failure.Failure: [Failure instance: Traceback: <class 'twisted.internet.error.CannotListenError'>: <CannotListenError instance at 0x7f2666d05588 with str error:
 Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/twisted/python/reflect.py", line 448, in safe_str
    return str(o)
  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/error.py", line 48, in __str__
    self.socketError)
BytesWarning: str() on a bytes instance
>
/home/telsasoft/server/server/updsrv.py:228:<module>
/home/telsasoft/server/server/updsrv.py:221:start_server_threads
/home/telsasoft/server/server/updsrv.py:203:start_ipc_server
/usr/local/lib64/python3.6/site-packages/twisted/internet/endpoints.py:1178:listen
--- <exception caught here> ---
/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py:122:execute
/usr/local/lib64/python3.6/site-packages/twisted/internet/posixbase.py:397:listenUNIX
/usr/local/lib64/python3.6/site-packages/twisted/internet/unix.py:398:startListening
]
Unhandled error in Deferred:

Traceback (most recent call last):
  File "/home/telsasoft/server/server/updsrv.py", line 228, in <module>
    start_server_threads(upd._socket_filename, PORT)
  File "/home/telsasoft/server/server/updsrv.py", line 221, in start_server_threads
    start_ipc_server(socket)
  File "/home/telsasoft/server/server/updsrv.py", line 203, in start_ipc_server
    res = proxy_endpoint.listen(factory)
  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/endpoints.py", line 1178, in listen
    wantPID=self._wantPID)
--- <exception caught here> ---
  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py", line 122, in execute
    result = callable(*args, **kw)
  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/posixbase.py", line 397, in listenUNIX
    p.startListening()
  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/unix.py", line 398, in startListening
    raise error.CannotListenError(None, self.port, le)
twisted.internet.error.CannotListenError: <CannotListenError instance at 0x7f2666d05588 with str error:
 Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/twisted/python/reflect.py", line 448, in safe_str
    return str(o)
  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/error.py", line 48, in __str__
    self.socketError)
BytesWarning: str() on a bytes instance
>
```

<details><summary>Searchable metadata</summary>

```
trac-id__9950 9950
type__defect defect
reporter__justinpryzby justinpryzby
priority__normal normal
milestone__Python_3_x Python-3.x
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__None None
time__1599079356117282 1599079356117282
changetime__1599154079652033 1599154079652033
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="justinpryzby's avatar" src="https://avatars.githubusercontent.com/u/6146401?s=50" width="50" height="50">](https://github.com/justinpryzby)<a name="note_2"></a>|@justinpryzby commented|
|-|-|

I should have mentioned that we're running with python -bb specifically to catch errors in our code while transitioning to py3.

And due to other, more prominent issues, we're running with:   PYTHONWARNINGS=i::BytesWarning:twisted.internet.unix

I think this is an issue more than just exception cases.  If I remove the ignore rule, then I also get:

  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/unix.py", line 300, in _inFilesystemNamespace
    return path[:1] not in (b"\0", u"\0")
builtins.BytesWarning: Comparison between bytes and string
