### ISSUE TITLE
Twisted with pypy3 on Ubuntu 20.4, SSL error: 'ee key too small'

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9985]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)| @rodrigc reported|
|-|-|
|Trac ID|trac#9985|
|Type|defect|
|Created|2020-09-30 23:57:05Z|

While trying to increase the CI on GitHub Actions, I ran the Twisted tests on Ubuntu 20.4 using this
version of using pypy3:

```
Python 3.6.9 (2ad108f17bdb, Apr 07 2020, 02:29:05
Pypy 7.3.1 with GCC 7.3.1 20180303 (Red Hat 7.3.1-5)
```

A bunch of the conch tests failed in this Ubuntu environment: https://github.com/twisted/twisted/runs/1173397508
like this:

```
===============================================================================
Error:
Traceback (most recent call last):
  File "/home/runner/work/twisted/twisted/build/alldeps-withcov-posix/site-packages/twisted/test/test_sslverify.py", line 1780, in test_ellipticCurveDiffieHellman
    onData=onData,
  File "/home/runner/work/twisted/twisted/build/alldeps-withcov-posix/site-packages/twisted/test/test_sslverify.py", line 716, in loopback
    self.serverPort = reactor.listenSSL(0, serverFactory, serverCertOpts)
  File "/home/runner/work/twisted/twisted/build/alldeps-withcov-posix/site-packages/twisted/internet/posixbase.py", line 593, in listenSSL
    tlsFactory = tls.TLSMemoryBIOFactory(contextFactory, False, factory)
  File "/home/runner/work/twisted/twisted/build/alldeps-withcov-posix/site-packages/twisted/protocols/tls.py", line 748, in __init__
    contextFactory = _ContextFactoryToConnectionFactory(contextFactory)
  File "/home/runner/work/twisted/twisted/build/alldeps-withcov-posix/site-packages/twisted/protocols/tls.py", line 629, in __init__
    oldStyleContextFactory.getContext()
  File "/home/runner/work/twisted/twisted/build/alldeps-withcov-posix/site-packages/twisted/internet/_sslverify.py", line 1636, in getContext
    self._context = self._makeContext()
  File "/home/runner/work/twisted/twisted/build/alldeps-withcov-posix/site-packages/twisted/internet/_sslverify.py", line 1645, in _makeContext
    ctx.use_certificate(self.certificate)
  File "/home/runner/work/twisted/twisted/build/alldeps-withcov-posix/site-packages/OpenSSL/SSL.py", line 960, in use_certificate
    _raise_current_error()
  File "/opt/hostedtoolcache/PyPy/3.6.9/x64/lib_pypy/_functools.py", line 80, in __call__
    return self._func(*(self._args + fargs), **fkeywords)
  File "/home/runner/work/twisted/twisted/build/alldeps-withcov-posix/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'SSL_CTX_use_certificate', 'ee key too small')]

twisted.test.test_sslverify.OpenSSLOptionsECDHIntegrationTests.test_ellipticCurveDiffieHellman
===============================================================================
```

I'm not sure what the root problem is, but my suspicion is that the SSL library in this particular Ubuntu environment
does not permit keys smaller than 2048 bits.

Adi seems to think so also: https://twistedmatrix.com/pipermail/twisted-python/2020-September/065264.html

<details><summary>Searchable metadata</summary>

```
trac-id__9985 9985
type__defect defect
reporter__rodrigc rodrigc
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__None None
time__1601510225082050 1601510225082050
changetime__1601566179862208 1601566179862208
version__None None
owner__Craig_Rodrigues__rodrigc_____ Craig Rodrigues <rodrigc@...>

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_2"></a>|@rodrigc commented|
|-|-|

https://github.com/twisted/twisted/pull/1411

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_3"></a>|@rodrigc commented|
|-|-|

Approved here: https://github.com/twisted/twisted/pull/1411#pullrequestreview-500163823

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_4"></a>|@rodrigc set owner to @rodrigc<br>@rodrigc set status to `closed`|
|-|-|

In changeset 45105d8506e95785c3226bf767e7453281cbe483
```
#!CommitTicketReference repository="" revision="45105d8506e95785c3226bf767e7453281cbe483"
Merge pull request #1411 from twisted/9985-rodrigc-ssl-keysize

Author: rodrigc
Reviewer: adiroiban
Fixes: ticket:9985

Increase keysizes used in SSL tests, to unbreak tests on Ubuntu 20.4 with Pypy3
```
