### ISSUE TITLE
Twisted SSL tests failing on pypy3 on Ubuntu 20.4

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9986]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)| @rodrigc reported|
|-|-|
|Trac ID|trac#9986|
|Type|defect|
|Created|2020-10-01 00:24:20Z|

While working on ticket:9985 , I saw additional failures in the TLS tests such as:

```
[FAIL]
Traceback (most recent call last):
  File "/home/vagrant/twisted/src/twisted/test/test_ssl.py", line 393, in check
    self.assertTrue(self.serverFactory.rawdata, "No encrypted bytes received")
  File "/home/vagrant/twisted/src/twisted/trial/_synctest.py", line 382, in assertTrue
    super(_Assertions, self).assertTrue(condition, msg)
  File "/usr/lib/pypy3/lib-python/3/unittest/case.py", line 682, in assertTrue
    raise self.failureException(msg)
twisted.trial.unittest.FailTest: b'' is not true : No encrypted bytes received

twisted.test.test_ssl.SpammyTLSTests.test_unTLS
twisted.test.test_ssl.TLSTests.test_unTLS
```

It looks like the TLS connections are not being created properly.

It looks like on this platform, certain older TLS protocols have been disabled.

<details><summary>Searchable metadata</summary>

```
trac-id__9986 9986
type__defect defect
reporter__rodrigc rodrigc
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__None None
time__1601511860403293 1601511860403293
changetime__1601752946534036 1601752946534036
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_1"></a>|@rodrigc commented|
|-|-|

https://github.com/twisted/twisted/pull/1412

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_2"></a>|@rodrigc commented|
|-|-|

Approved here: https://github.com/twisted/twisted/pull/1412#pullrequestreview-500201361

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_3"></a>|@rodrigc set status to `closed`|
|-|-|

Fixed in https://github.com/twisted/twisted/commit/092eca400445852b3391efa6d7fd2403e2c5c7c6
